(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgOAbQgGgEgEgHQgEgGAAgJQAAgJAEgHQAEgHAGgEQAHgEAHAAQAJAAAHAEQAFAEAEAHQAEAGAAAJIgBACIgBABIgmAAIgCAAIAAACQAAAEADAEQACAEADACQAEACADAAQAFAAADgCQAEgCAEgEIABgBIABAAIAHADQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgEAFgEADQgDADgFACIgLABQgHAAgHgEgAgGgSQgDACgCADQgCAEAAAFIAZAAIACgBIABgBIgCgHQgBgDgDgCQgDgDgFAAQgEAAgDADg");
	this.shape.setTransform(68.8,7.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgPAbQgHgDgDgFIAAgCIAAgBIAHgDIABgBIABABIAFAEIAEADIAHABIAHgBIAFgCQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAIgGgDIgLgDQgJgCgEgDQgDgEAAgGQAAgFADgFQACgEAGgCQAFgDAHAAQAIAAAGADQAGADADAFIAAABIAAABIgHAEIgBAAIgBgBIgGgFQgDgCgFAAQgEAAgEACQgDACAAAEIABADQACACAFABIAMADQAIACAFAEQADAFAAAFQAAAGgDAEQgDAEgGADQgGACgIAAQgIAAgHgEg");
	this.shape_1.setTransform(61.9,7.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgUAaQgFgEAAgIQAAgGADgEQAEgEAHgCQAHgDAJAAIAGgBIABAAIABgBIAAgDQAAgFgDgDQgDgCgGAAIgGABQgDACgDAEIgBABIgBAAIgJgCIgBgBIAAgCQADgGAHgDQAGgEAJAAQAJAAAFADQAFACADAEQACAEAAAGIAAAnIAAABIgBABIgKAAIgCgBIAAgCIAAgDQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAAAABIgJAFQgDACgGAAQgJAAgEgFgAAGABIgGABIgGACIgEAEQgBACAAADQAAAEADACQACACAFAAIAFgBIAEgDIADgDIACgDIAAgIQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAg");
	this.shape_2.setTransform(54.975,7.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAOAqIgBgBIgBgCIAAgmQAAgEgDgCQgCgCgEAAIgEAAIgFADIgFAEIAAAnQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgKAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAhNQAAgBABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIAMAAQAAAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAdIAAABIABAAIAHgGIAFgCIAGgBQAJAAAFAEQAFAGgBAIIAAAnQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_3.setTransform(48.4,5.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgMAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgHAHgEQAHgEAHAAQAHAAAFADQAFACADAEIAFAHQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgKACIgCgBIgDgFIgDgDIgFgBQgEAAgDACQgEADgCAFQgBAEAAAGQAAAHACAFQABAEAEADQADACAEAAQAFAAAEgCIAGgIIAAAAIABAAIAHACQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIgDAFIgFAFIgHAEQgFACgFAAQgHAAgHgEg");
	this.shape_4.setTransform(41.7313,7.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgPAeIgCAAIAAgCIAAg2QAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIALAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAGIAAABIABAAIAFgGIAFgDIAGgBQABAAABAAQABAAAAAAQABABAAAAQAAAAAAABIAAAKQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgEgBIgDAAIgFABIgEACIgCAEIgCAEIAAAhQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_5.setTransform(36.575,7.025);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgRAcQgEgCgCgEQgCgEAAgFIAAgoQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIAKAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAlQAAAEADADQACADAEAAQADAAAEgCIAGgGIAAgnQAAAAAAgBQABAAAAgBQAAAAABAAQABAAAAAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAA2QAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgLAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGIAAgBIgBAAQgGAFgEACQgEACgFAAQgFAAgEgCg");
	this.shape_6.setTransform(30.325,7.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgeAqIgBgBIgBgCIAAhNQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIAeAAQAJAAAIADQAHADAEAGQAFAFAAAIQAAAJgEAGQgEAEgHADQgHACgJAAIgQAAQgBABAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAdQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAgAgPgbIAAAXQAAAAAAABQAAAAAAAAQAAAAABAAQAAABAAAAIAOAAQAHAAAEgEQAEgDAAgHQAAgEgBgDQgCgDgEgBIgIgBIgNAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAg");
	this.shape_7.setTransform(22.975,5.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgYAlQgIgEAAgHQAAgEADgDIAIgFQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIgEgDQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgBAAgBIABgDIAEgCIAFgDIABgBIgBgBQgFgCgDgDQgCgFAAgEQAAgJAHgFQAHgGANAAQAFAAAEACQAFABACADIACAAIABgBIAEgCIAEgDIAEgBIABABIABACIAAAGIgBACIgCABIgDAAIgCAAQgBAAgBAAQAAABAAAAQgBAAAAABQAAAAABABIAAACIABAEQAAAEgDAFQgDAEgGACQgFADgIAAIgIAAIgEABQAAAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIAGABIAOAAQALACAFADQAFAFAAAHQAAAIgIAGQgHAEgOAAQgQABgIgEgAgOARIgEADQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQAAACACADQADACAEABIALABQAIAAAEgCQAEgCAAgFQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAgBAAQgCgDgFAAIgRAAIgCgBIgCABgAgLgbQgDACAAAGQAAAEADADQAEADAGAAQAFAAAEgDQADgDAAgEQAAgGgDgCQgEgEgFAAQgGAAgEAEg");
	this.shape_8.setTransform(11.325,7.95);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AANAeIgBAAIAAgCIAAglQAAgFgCgCQgDgCgEAAIgFAAIgEADIgFAEIAAAnQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgJAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAFIAAABIABAAIAGgFIAGgDIAHgBQAIAAAEAFQAFAEABAIIAAAoQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_9.setTransform(4.25,7.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgFAqIgBgBIgBgCIAAg2QAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAAAIALAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAA2IAAACIgDABgAgFgZQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgBgBIAAgLQAAgBABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIALAAQAAAAAAABQABAAAAAAQAAAAAAABQABAAAAABIAAAKQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_10.setTransform(-0.95,5.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgXAnQgBAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgHIABgBIACgBIAIAAIADgBIAEgDIACgEIgBgEIgWg0IAAgBIADgBIALAAIABAAIABACIANAkIABAAIABAAIANglIACgBIABAAIAIAAIACABIAAABIgYA7IgEAIIgFAFIgGADIgIAAg");
	this.shape_11.setTransform(-5.75,8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgGAqQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAgBIAAgtIgBgBIgJAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgHIABgCIABAAIAIAAQAAAAABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAAgIQAAgGADgEQAEgEAHgBIALAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIABAFIgBACIgBABIgHAAQAAAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgCACAAACIAAAGQAAAAABAAQAAABAAAAQAAAAAAAAQABAAAAAAIALAAIABAAIAAACIAAAHQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgLAAIgBABIAAAtQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_12.setTransform(-10.5,5.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgEAqIgCgBIgBgCIAAg2QAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAAAIALAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAA2IgBACIgBABgAgEgZQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgBgBIAAgLQAAgBABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIALAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_13.setTransform(-14.6,5.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgEAqQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhNQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIAKAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAABOIAAACIgCABg");
	this.shape_14.setTransform(-17.925,5.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgUAaQgFgEAAgIQAAgGADgEQAEgEAHgCQAHgDAJAAIAGgBIABAAIABgBIAAgDQAAgFgDgDQgDgCgGAAIgGABQgDACgDAEIgBABIgBAAIgJgCIgBgBIAAgCQADgGAHgDQAGgEAJAAQAJAAAFADQAFACADAEQACAEAAAGIAAAnIAAABIgBABIgKAAIgCgBIAAgCIAAgDQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAAAABIgJAFQgDACgGAAQgJAAgEgFgAAGABIgGABIgGACIgEAEQgBACAAADQAAAEADACQACACAFAAIAFgBIAEgDIADgDIACgDIAAgIQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAg");
	this.shape_15.setTransform(-23.425,7.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgRAcQgEgCgCgEQgCgEAAgFIAAgoQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIAKAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAlQAAAEADADQACADAEAAQADAAAEgCIAGgGIAAgnQAAAAAAgBQABAAAAgBQAAAAABAAQABAAAAAAIAKAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAA2QAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgLAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGIAAgBIgBAAQgGAFgEACQgEACgFAAQgFAAgEgCg");
	this.shape_16.setTransform(-30.075,7.125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAVAuQgGgEgFgGQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAIgEABIgEAAQgKAAgJgFQgIgFgFgKQgEgJAAgMQAAgNAEgKQAFgKAIgFQAJgFAKAAQALAAAJAFQAIAFAFAKQAEAKAAANQAAALgDAJQgEAIgHAFIAAACIACACIAEADIAGACIACAAIAAACIAAAHIgBADIgDAAQgGAAgGgDgAgOgdQgFAIAAAQQAAAPAFAHQAFAHAJAAQAKAAAFgHQAFgHAAgPQAAgQgFgIQgFgHgKgBQgJABgFAHg");
	this.shape_17.setTransform(-38.525,6.55);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AANAqIgBgBIAAgCIAAgmQAAgEgCgCQgDgCgFAAIgDAAIgFADIgFAEIAAAnQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAIgKAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAhNQABgBAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIALAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAdIAAABIABAAIAHgGIAFgCIAHgBQAIAAAFAEQAEAGABAIIAAAnQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_18.setTransform(-50.45,5.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAGAoQgHAAgEgEQgEgDAAgHIAAghQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgHAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgHQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAJAAIABgBIABgRQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAJAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAARIABABIAMAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAAAQAAAAgBABQAAAAgBAAIgMAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBAAAAABIAAAdQABAEACACQABABAEAAIAGAAIACABIAAABIAAAGQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgEAAIgFABg");
	this.shape_19.setTransform(-55.4,6.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgFAqIgBgBIgBgCIAAg2QABAAAAgBQAAAAAAAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAA2IAAACIgDABgAgFgZQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgBgBIAAgLQABgBAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIAKAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABIAAAKQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_20.setTransform(-59.55,5.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAUAqQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgPg1IgBgBIAAABIgPA1QAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBIgWhMIAAgCIACgCIALAAIACABIABABIAPA3IABABIABgBIAQg3IAAgBIACgBIAJAAIADABIAAABIAQA4IABABIABgBIAPg4IABgBIACgBIAJAAIACACIAAACIgYBMQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAg");
	this.shape_21.setTransform(-66.4,5.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgPAeIgCAAIAAgCIAAg2QAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIALAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAGIAAABIABAAIAFgGIAFgDIAGgBQABAAABAAQABAAAAAAQABABAAAAQAAAAAAABIAAAKQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgEgBIgDAAIgFABIgEACIgCAEIgCAEIAAAhQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_22.setTransform(92.125,-6.925);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgOAbQgGgEgEgHQgEgGAAgJQAAgJAEgHQAEgHAGgEQAHgEAIAAQAIAAAHAEQAFAEAEAHQAEAGAAAJIgBACIgBABIgmAAIgCAAIAAACQAAAEADAEQACAEADACQAEACADAAQAFAAADgCQAEgCAEgEIAAgBIACAAIAHADQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgEAFgEADQgDADgFACIgKABQgIAAgHgEgAgGgSQgDACgCADQgCAEAAAFIAZAAIACgBIABgBIgCgHQgBgDgDgCQgDgDgFAAQgEAAgDADg");
	this.shape_23.setTransform(85.9,-6.875);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AANAqIgBgBIAAgCIAAgmQAAgEgCgCQgDgCgEAAIgFAAIgEADIgFAEIAAAnQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAIgJAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhNQAAgBAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIALAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAdIAAABIABAAIAHgGIAFgCIAHgBQAIAAAFAEQAFAFAAAJIAAAnQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_24.setTransform(78.95,-8.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgMAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgHAHgEQAHgEAHAAQAHAAAFADQAFACADAEIAFAHQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgKACIgCgBIgDgFIgDgDIgFgBQgEAAgDACQgEADgCAFQgBAEAAAGQAAAHACAFQABAEAEADQADACAEAAQAFAAAEgCIAGgIIAAAAIABAAIAHACQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIgDAFIgFAFIgHAEQgFACgFAAQgHAAgHgEg");
	this.shape_25.setTransform(72.2813,-6.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgRAcQgEgCgCgEQgCgEAAgFIAAgoQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIAKAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAlQAAAEADADQACADAEAAQADAAAEgCIAGgGIAAgnQAAAAAAgBQABAAAAgBQAAAAABAAQABAAAAAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAA2QAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgLAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGIAAgBIgBAAQgGAFgEACQgEACgFAAQgFAAgEgCg");
	this.shape_26.setTransform(65.425,-6.825);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgOAbQgHgEgDgHQgFgHAAgJQAAgIAFgHQAEgHAGgEQAGgEAIAAQAJAAAGAEQAHAEAEAHQADAHABAIQgBAJgDAHQgEAHgHAEQgGAEgJAAQgIAAgGgEgAgHgSQgDADgCAFQgCAEABAGQgBAHACAEQACAFADACQAEADADAAQAFAAADgDQADgCACgFQACgEAAgHQAAgGgCgEQgCgFgDgDQgDgCgFAAQgDAAgEACg");
	this.shape_27.setTransform(58.5,-6.875);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgFAqQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAgBIgbhNIAAgCIABgBIANAAQABAAAAABQABAAAAAAQAAAAAAAAQABABAAAAIATA7QAAABAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBIAUg7QAAAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIALAAIABABIAAACIgbBNQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_28.setTransform(50.975,-8.05);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAOAeIgBAAIgBgCIAAglQAAgFgDgCQgCgCgFAAIgDAAIgFADIgFAEIAAAnQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgLAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAg2QAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAMAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAFIAAABIABAAIAHgFIAEgDIAHgBQAJAAAFAFQAEAEAAAIIAAAoQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_29.setTransform(39.3,-6.925);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgOAbQgHgEgDgHQgFgHAAgJQAAgIAFgHQAEgHAGgEQAHgEAHAAQAJAAAGAEQAHAEAEAHQAEAHAAAIQAAAJgEAHQgEAHgHAEQgGAEgJAAQgIAAgGgEgAgHgSQgDADgCAFQgCAEABAGQgBAHACAEQACAFADACQAEADADAAQAFAAADgDQADgCACgFQACgEAAgHQAAgGgCgEQgCgFgDgDQgDgCgFAAQgDAAgEACg");
	this.shape_30.setTransform(32.3,-6.875);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgEAqIgCgBIAAgCIAAg2QAAAAAAgBQAAAAAAAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAA2IgBACIgCABgAgEgZQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgBIAAgLQAAgBAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIAKAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_31.setTransform(27.1,-8.05);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAFAoQgGAAgEgEQgEgDAAgHIAAghQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgHAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgHQAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAJAAIABgBIABgRQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAJAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAARIABABIANAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAHQAAAAgBABQAAAAAAAAQAAAAgBABQAAAAAAAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBAAAAABIAAAdQAAAEACACQACABAEAAIAHAAIABABIABABIgBAGQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgEAAIgEABg");
	this.shape_32.setTransform(24.05,-7.875);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgUAaQgFgEAAgIQAAgGADgEQAEgEAHgCQAHgDAJAAIAGgBIABAAIABgBIAAgDQAAgFgDgDQgDgCgGAAIgGABQgDACgDAEIgBABIgBAAIgJgCIgBgBIAAgCQADgGAHgDQAGgEAJAAQAJAAAFADQAFACADAEQACAEAAAGIAAAnIAAABIgBABIgKAAIgCgBIAAgCIAAgDQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAAAABIgJAFQgDACgGAAQgJAAgEgFgAAGABIgGABIgGACIgEAEQgBACAAADQAAAEADACQACACAFAAIAFgBIAEgDIADgDIACgDIAAgIQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAg");
	this.shape_33.setTransform(17.675,-6.875);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgMAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgHAHgEQAHgEAHAAQAHAAAFADQAFACADAEIAFAHQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgKACIgCgBIgDgFIgDgDIgFgBQgEAAgDACQgEADgCAFQgBAEAAAGQAAAHACAFQABAEAEADQADACAEAAQAFAAAEgCIAGgIIAAAAIABAAIAHACQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIgDAFIgFAFIgHAEQgFACgFAAQgHAAgHgEg");
	this.shape_34.setTransform(11.4313,-6.875);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgUAaQgFgEAAgIQAAgGADgEQAEgEAHgCQAHgDAJAAIAGgBIABAAIABgBIAAgDQAAgFgDgDQgDgCgGAAIgGABQgDACgDAEIgBABIgBAAIgJgCIgBgBIAAgCQADgGAHgDQAGgEAJAAQAJAAAFADQAFACADAEQACAEAAAGIAAAnIAAABIgBABIgKAAIgCgBIAAgCIAAgDQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAAAABIgJAFQgDACgGAAQgJAAgEgFgAAGABIgGABIgGACIgEAEQgBACAAADQAAAEADACQACACAFAAIAFgBIAEgDIADgDIACgDIAAgIQAAgBAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAg");
	this.shape_35.setTransform(4.225,-6.875);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgFAqQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAgBIgbhNIAAgCIABgBIANAAQABAAAAABQABAAAAAAQAAAAAAAAQABABAAAAIATA7QAAABAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBIAUg7QAAAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIALAAIABABIAAACIgbBNQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_36.setTransform(-2.875,-8.05);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgFAcQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgNQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIAMAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAANQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAgAgFgLQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgMQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAMAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAMQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAg");
	this.shape_37.setTransform(-13.475,-6.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgPAbQgHgDgDgFIAAgCIAAgBIAHgDIABgBIABABIAFAEIAEADIAHABIAHgBIAEgCQABgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAIgGgDIgLgDQgJgCgDgDQgEgEgBgGQABgFADgFQADgEAFgCQAGgDAGAAQAIAAAGADQAGADADAFIABABIgBABIgHAEIgBAAIgBgBIgGgFQgDgCgFAAQgEAAgEACQgCACAAAEIAAADQACACAFABIAMADQAIACAFAEQADAFAAAFQAAAGgDAEQgDAEgGADQgGACgIAAQgJAAgGgEg");
	this.shape_38.setTransform(-18.4,-6.875);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgRAcQgEgCgCgEQgCgEAAgFIAAgoQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAlQAAAEADADQACADAEAAQADAAAEgCIAGgGIAAgnQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAKAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAA2QAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgLAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGIAAgBIgBAAQgGAFgEACQgEACgFAAQgFAAgEgCg");
	this.shape_39.setTransform(-24.975,-6.825);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAOAeIgCAAIAAgCIAAglQAAgFgDgCQgCgCgFAAIgDAAIgFADIgFAEIAAAnQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgKAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAg2QAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAMAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAFIAAABIABAAIAHgFIAEgDIAHgBQAJAAAEAFQAGAEgBAIIAAAoQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_40.setTransform(-31.9,-6.925);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgOAbQgHgEgEgHQgEgHAAgJQAAgIAEgHQAFgHAGgEQAHgEAHAAQAJAAAGAEQAHAEAEAHQAEAHAAAIQAAAJgEAHQgEAHgHAEQgGAEgJAAQgIAAgGgEgAgHgSQgDADgCAFQgBAEAAAGQAAAHABAEQACAFADACQADADAEAAQAFAAADgDQADgCACgFQACgEAAgHQAAgGgCgEQgCgFgDgDQgDgCgFAAQgEAAgDACg");
	this.shape_41.setTransform(-38.9,-6.875);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgeAqIgBgBIgBgCIAAhNIABgCIABgBIAdAAQAPAAAIAGQAJAGAAAKQAAAGgEAFQgDAEgIAEIAAAAIAAAAQAJACAEAFQAEAEAAAIQAAAMgJAFQgIAGgQAAgAgPAHIAAAVQAAABAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIAOAAQAHAAAEgDQAFgEAAgFQAAgFgCgCQgDgDgDgBIgIgBIgNAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAgAgPgbIAAAUQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAOAAIAFAAIAFgCIADgDIABgGQAAgGgEgDQgFgDgGAAIgMAAQgBAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABg");
	this.shape_42.setTransform(-46.325,-8.05);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAFAoQgGAAgEgEQgEgDAAgHIAAghQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgHAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgHQAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAJAAIABgBIABgRQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAJAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAARIABABIANAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAAAQAAAAgBABQAAAAAAAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBAAAAABIAAAdQAAAEACACQACABAEAAIAHAAIABABIAAABIAAAGQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgEAAIgEABg");
	this.shape_43.setTransform(-56.05,-7.875);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgPAbQgHgDgCgFIgBgCIABgBIAGgDIACgBIABABIADAEIAGADIAHABIAGgBIAEgCQABgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAIgHgDIgKgDQgIgCgEgDQgFgEAAgGQAAgFADgFQADgEAGgCQAFgDAHAAQAIAAAGADQAGADADAFIAAABIAAABIgHAEIgBAAIgBgBIgGgFQgDgCgFAAQgEAAgDACQgDACAAAEIABADQABACAEABIANADQAJACADAEQAEAFAAAFQAAAGgDAEQgDAEgGADQgGACgHAAQgJAAgHgEg");
	this.shape_44.setTransform(-61.9,-6.875);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgRAcQgEgCgCgEQgCgEAAgFIAAgoQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAlQAAAEADADQACADAEAAQADAAAEgCIAGgGIAAgnQAAAAAAgBQABAAAAgBQAAAAABAAQABAAAAAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAA2QAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgLAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGIAAgBIgBAAQgGAFgEACQgEACgFAAQgFAAgEgCg");
	this.shape_45.setTransform(-68.475,-6.825);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgYAlQgIgEAAgHQAAgEADgDIAIgFQAAAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIgEgDQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgBAAgBIABgDIAEgCIAFgDIABgBIgBgBQgFgCgDgDQgCgFAAgEQAAgJAHgFQAHgGANAAQAFAAAEACQAFABACADIACAAIABAAIAEgDIAEgDIAEgBIABABIABACIAAAGIgBACIgCABIgDAAIgCAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAABABIAAACIABAEQAAAEgDAFQgDAEgGACQgFADgIAAIgIAAIgEABQAAAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABABAAQAAAAABAAIAGABIAOAAQALACAFADQAFAFAAAHQAAAIgIAGQgHAEgOAAQgQABgIgEgAgOARIgEADQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQAAACACADQADACAEABIALABQAIAAAEgCQAEgDAAgEQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQgCgCgFAAIgRAAIgCgBIgCABgAgLgbQgDACAAAGQAAAEADADQAEADAGAAQAFAAAEgDQADgDAAgEQAAgGgDgCQgEgEgFAAQgGAAgEAEg");
	this.shape_46.setTransform(-75.325,-6);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgRAcQgEgCgCgEQgCgEAAgFIAAgoQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAlQAAAEADADQACADAEAAQADAAAEgCIAGgGIAAgnQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAKAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAA2QAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgLAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGIAAgBIgBAAQgGAFgEACQgEACgFAAQgFAAgEgCg");
	this.shape_47.setTransform(-82.475,-6.825);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AAXAqQAAAAgBgBQAAAAAAAAQAAAAgBAAQAAgBAAAAIgHgSIAAgBIgBAAIgcAAIgBABIgHASIgBABIgBABIgLAAIgBgBIAAgDIAchMIABgCIACgBIANAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABIAcBNIAAACIgBABgAgBgXIgLAeQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAUAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIgKgeIAAgBIgBABg");
	this.shape_48.setTransform(-89.8,-8.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-96.9,-15.3,194,30.8);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAPAiIgBgBIgBgCIAAgqQAAgFgCgCQgDgDgFAAIgFABIgFADIgFAEIAAAsQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgMAAQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAgBIAAg9QAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIANAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHIABAAIABAAIAHgFIAGgEQADgBAFAAQAJAAAFAGQAGAEAAAJIAAAtQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(46.225,18.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAQAhQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgMgmIgBgBIAAABIgMAmIgBACIgCAAIgJAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgUg9IAAgCIACAAIAMAAIACAAIABABIAMAoIABABQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAgBIAMgnIABgBIACAAIAIAAIABAAIABABIAMAoIABABIABgCIAMgnIABgBIACAAIAIAAIACAAIAAACIgVA9IAAACIgCAAg");
	this.shape_1.setTransform(37.925,18.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgQAfQgIgFgEgIQgEgIAAgKQAAgJAEgIQAEgHAIgFQAHgFAJAAQAKAAAHAFQAIAFAEAHQAEAIAAAJQAAAKgEAIQgEAIgIAFQgHADgKAAQgJAAgHgDgAgIgUQgEADgCAFQgCAGAAAGQAAAHACAGQACAFAEADQAEACAEABQAFgBAEgCQAEgDACgFQACgGAAgHQAAgGgCgGQgCgFgEgDQgEgCgFAAQgEAAgEACg");
	this.shape_2.setTransform(29.075,18.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgjAvQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAgBgBIAAhXIABgCIACgBIAGAAIAHAAIAGAAIAGAAQARABAKAFQALAGAGAKQAEAKABAOQAAAOgGALQgFALgMAFQgLAGgPAAgAgTgfIAAA/QAAAAAAAAQAAABABAAQAAAAAAAAQABAAAAAAIADAAQAMAAAGgDQAIgDADgIQAEgHAAgMQAAgLgDgIQgEgHgHgDQgHgDgLAAIgFAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAg");
	this.shape_3.setTransform(20.5,17.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgaArQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgIIABgBQAAAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAIAAIAEgBIAEgDIACgFIgBgEIgYg6IAAgCIACgBIANAAIACAAIABACIAOApIABAAIABAAIAQgpIABgCIABAAIAKAAIABABQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAIgaBBIgFAJIgFAGQgDACgEABIgKABg");
	this.shape_4.setTransform(8.2875,19.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgPAfQgIgFgEgIQgEgHgBgKQABgKAEgIQAEgIAIgEQAIgFAIAAQAJABAIAEQAGAEAFAHQADAJAAAJIAAADIgBAAIgsAAIgBABIAAACQgBAFADAEQADADAEADQAEACAEABQAFgBAEgCQAFgCADgFIABAAIABAAIAIADQAAABABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgJAJQgEAEgFACIgMAAQgIAAgIgDgAgGgUQgFACgCAEQgBAEAAAFIAcAAIACAAIAAgCIgBgHQgCgFgDgBQgEgDgEAAQgFAAgDADg");
	this.shape_5.setTransform(1,18.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAPAiIgBgBIgBgCIAAgqQAAgFgCgCQgDgDgFAAIgFABIgFADIgFAEIAAAsQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgMAAQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAgBIAAg9QAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIANAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHIABAAIABAAIAHgFIAGgEQADgBAFAAQAJAAAFAGQAGAEAAAJIAAAtQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-6.425,18.65);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgQAfQgIgFgEgIQgEgIAAgKQAAgJAEgIQAEgHAIgFQAHgFAJAAQAKAAAHAFQAIAFAEAHQAEAIAAAJQAAAKgEAIQgEAIgIAFQgHADgKAAQgJAAgHgDgAgIgUQgEADgCAFQgCAGAAAGQAAAHACAGQACAFAEADQAEACAEABQAFgBAEgCQAEgDACgFQACgGAAgHQAAgGgCgGQgCgFgEgDQgEgCgFAAQgEAAgEACg");
	this.shape_7.setTransform(-13.975,18.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAhAvIgCgBIgBgCIAAhAIAAgBIgBABIgYBBQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgIAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIgYhBIAAAAIgBABIAABAIAAABIgCABIgKAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAhYQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIAWAAIABABIABABIAWA7IAAAAIABgBIAWg5QAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAWAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAABYQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_8.setTransform(-22.875,17.375);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgQAfQgIgFgEgIQgEgIAAgKQAAgJAEgIQAEgHAIgFQAHgFAJAAQAKAAAHAFQAIAFAEAHQAEAIAAAJQAAAKgEAIQgEAIgIAFQgHADgKAAQgJAAgHgDgAgIgUQgEADgCAFQgCAGAAAGQAAAHACAGQACAFAEADQAEACAEABQAFgBAEgCQAEgDACgFQACgGAAgHQAAgGgCgGQgCgFgEgDQgEgCgFAAQgEAAgEACg");
	this.shape_9.setTransform(-36.475,18.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAZAvIgBAAIgCgCIgqg8IgBAAIAAAAIAAA8QAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgMAAQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAAAIAAhZQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIANAAIACABIABABIAoA5IABABIABgBIAAg5QAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIALAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAABZIgBABIgBABg");
	this.shape_10.setTransform(-45.125,17.375);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgHATIgBgBIAAgCIAGgNQAAgBAAgBQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAIAAgPQAAAAAAgBQABAAAAAAQAAgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAAOIAAABIgKASIgCABIgCABg");
	this.shape_11.setTransform(78.0625,7.675);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAGAtQgHAAgFgEQgEgEAAgIIAAglQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAIgIAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgIQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAJAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIABgUQABAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAKAAQABAAAAAAQABABAAAAQAAAAAAAAQABABAAAAIAAAUIABABIAOAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgNAAQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAAgQAAAFACACQACACAFAAIAHAAIABABIABABIAAAGQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBAAIgEAAIgGABg");
	this.shape_12.setTransform(75.2,3.175);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgRAfQgIgEgDgGIAAgCIAAgBIAIgDIABgBIABABIAFAEIAGAEIAHABIAHgBQAEgBACgCQAAAAABgBQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgCgDgCIgHgDIgMgDQgKgDgEgDQgFgFAAgGQAAgHAEgEQADgFAGgDQAGgDAIAAQAJAAAHAEQAHAEADAFIABABIgBABIgIAEIgBAAIgBgBQgDgDgEgCQgEgCgFAAQgFAAgDACQgEACAAAEQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAABQACACAFABIAOAEQAKACAEAFQAEAFAAAGQAAAGgDAFQgEAFgHADQgGABgJAAQgKAAgHgDg");
	this.shape_13.setTransform(68.975,4.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgPAfQgIgFgEgIQgEgHgBgKQABgKAEgIQAFgIAHgEQAHgFAJAAQAJABAIAEQAGAEAFAHQADAJAAAJIAAADIgCAAIgrAAIgBABIgBACQABAFACAEQADADADADQAFACAEABQAFgBAEgCQAEgCAEgFIABAAIABAAIAIADQAAABABAAQAAAAAAAAQAAAAAAABQAAAAgBAAIgIAJQgEAEgGACIgLAAQgIAAgIgDgAgGgUQgFACgCAEQgBAEAAAFIAcAAIACAAIABgCIgCgHQgCgFgDgBQgEgDgEAAQgEAAgEADg");
	this.shape_14.setTransform(61.95,4.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgRAiIgCgBIgBgCIAAg9QAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIANAAQAAAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAIIAAABIACgBIAFgGQADgCAEgCQADgBADAAQABAAABAAQABAAAAABQABAAAAAAQABABAAAAIAAAMQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAAAIgFgBIgDAAIgFABIgFADIgDADIgBAFIAAAlQAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_15.setTransform(56.35,4.25);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgPAfQgIgFgEgIQgEgHgBgKQABgKAEgIQAEgIAIgEQAHgFAJAAQAJABAIAEQAHAEAEAHQADAJAAAJIAAADIgCAAIgrAAIgBABIAAACQAAAFACAEQADADAEADQAEACAEABQAFgBAEgCQAEgCAEgFIABAAIABAAIAIADQAAABABAAQAAAAAAAAQAAAAAAABQAAAAgBAAIgIAJQgEAEgGACIgLAAQgIAAgIgDgAgGgUQgEACgDAEQgBAEAAAFIAcAAIACAAIABgCIgCgHQgCgFgDgBQgEgDgEAAQgEAAgEADg");
	this.shape_16.setTransform(49.7,4.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAGAtQgHAAgFgEQgEgEAAgIIAAglQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAIgIAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgIQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAJAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIACgUQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAKAAQABAAAAAAQABABAAAAQAAAAAAAAQABABAAAAIAAAUIABABIAOAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgNAAQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAAgQAAAFACACQACACAFAAIAHAAIABABIABABIAAAGQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBAAIgEAAIgGABg");
	this.shape_17.setTransform(44.6,3.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAPAiIgBgBIgBgCIAAgqQAAgFgCgCQgDgDgFAAIgFABIgFADIgFAEIAAAsQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgMAAQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAgBIAAg9QAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIANAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHIABAAIABAAIAHgFIAGgEQADgBAFAAQAJAAAFAGQAGAEAAAJIAAAtQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_18.setTransform(38.225,4.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgGAvIgCgBIAAgCIAAhYQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABYIAAACIgDABg");
	this.shape_19.setTransform(32.375,2.975);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgQAfQgIgFgEgIQgEgIAAgKQAAgJAEgIQAEgHAIgFQAHgFAJAAQAKAAAHAFQAIAFAEAHQAEAIAAAJQAAAKgEAIQgEAIgIAFQgHADgKAAQgJAAgHgDgAgIgUQgEADgCAFQgCAGAAAGQAAAHACAGQACAFAEADQAEACAEABQAFgBAEgCQAEgDACgFQACgGAAgHQAAgGgCgGQgCgFgEgDQgEgCgFAAQgEAAgEACg");
	this.shape_20.setTransform(22.725,4.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAZAvIgBAAIgCgCIgqg8IgBAAIAAAAIAAA8QAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgMAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAhZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIANAAIACABIABABIAoA5IABABIABgBIAAg5QAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIALAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAABZIgBABIgBABg");
	this.shape_21.setTransform(14.075,2.975);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgHATIgBgBIAAgCIAGgNQAAgBAAgBQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAgBAAAAIAAgPQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAAOIAAABIgKASIgCABIgCABg");
	this.shape_22.setTransform(2.7625,7.675);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgRAfQgIgEgDgGIAAgCIAAgBIAIgDIABgBIABABIAFAEIAGAEIAHABIAHgBQAEgBACgCQAAAAABgBQAAgBAAAAQABgBAAAAQAAgBAAgBQAAgCgDgCIgHgDIgMgDQgKgDgEgDQgFgFAAgGQAAgHAEgEQADgFAGgDQAGgDAIAAQAJAAAHAEQAHAEADAFIABABIgBABIgIAEIgBAAIgBgBQgDgDgEgCQgEgCgFAAQgFAAgDACQgEACAAAEQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAABQACACAFABIAOAEQAKACAEAFQAEAFAAAGQAAAGgDAFQgEAFgHADQgGABgJAAQgKAAgHgDg");
	this.shape_23.setTransform(-2.325,4.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAGAtQgHAAgFgEQgEgEAAgIIAAglQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAIgIAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgIQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAJAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIABgUQABAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIALAAQAAAAAAAAQABABAAAAQAAAAAAAAQABABAAAAIAAAUIABABIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgNAAQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAAgQAAAFACACQACACAFAAIAHAAIABABIABABIAAAGQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBAAIgEAAIgGABg");
	this.shape_24.setTransform(-7.5,3.175);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AAPAiIgBgBIgBgCIAAgqQAAgFgCgCQgDgDgFAAIgFABIgFADIgFAEIAAAsQAAABAAABQgBAAAAAAQAAABgBAAQgBAAAAAAIgMAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAg9QAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIANAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHIABAAIABAAIAHgFIAGgEQADgBAFAAQAJAAAFAGQAGAEAAAJIAAAtQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_25.setTransform(-13.825,4.25);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgPAfQgIgFgEgIQgEgHgBgKQABgKAEgIQAEgIAIgEQAHgFAJAAQAJABAIAEQAHAEAEAHQADAJAAAJIAAADIgCAAIgrAAIgBABIgBACQABAFACAEQADADADADQAFACAEABQAFgBAEgCQAEgCAEgFIABAAIABAAIAIADQAAABABAAQAAAAAAAAQAAAAAAABQAAAAgBAAIgIAJQgEAEgGACIgLAAQgIAAgIgDgAgGgUQgEACgDAEQgBAEAAAFIAcAAIACAAIABgCIgCgHQgCgFgDgBQgEgDgEAAQgEAAgEADg");
	this.shape_26.setTransform(-21.4,4.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAkAiIgCgBIAAgCIAAgqQgBgFgCgCQgCgDgFAAIgGABIgEADIgFADIgBACIAAACIAAApQAAABAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgLAAIgCgBIAAgCIAAgqQAAgFgDgCQgCgDgFAAQgFAAgDACIgHAGIAAAsQAAABgBABQAAAAAAAAQgBABAAAAQgBAAgBAAIgLAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAg9QAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIAMAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAHIABAAIABAAIAGgFIAHgEIAIgBQAHAAADADQAFAEABAEIABABIABgBIAHgFIAIgFIAIgBQAIAAAGAGQAFAEAAAKIAAAsQAAABAAABQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_27.setTransform(-30.35,4.25);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgaArQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgIIABgBQAAAAAAAAQAAAAABgBQAAAAAAAAQABAAABAAIAIAAIAEgBIAEgDIACgFIgBgEIgYg6IAAgCIACgBIANAAIACAAIABACIAOApIABAAIABAAIAQgpIABgCIABAAIAKAAIABABQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAIgaBBIgFAJIgFAGQgDACgEABIgKABg");
	this.shape_28.setTransform(-39.4625,5.375);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgXAeQgGgFABgJQAAgGADgFQAFgFAIgCQAHgDALgBIAGgBIACAAIAAgCIAAgCQAAgGgEgDQgCgDgHAAQgCAAgFACQgEACgCAFIgBABIgCAAIgLgEIAAAAIAAgCQADgHAIgEQAHgEAKAAQAKAAAGADQAGADADAFQACAEAAAHIAAArIAAACIgCABIgKAAIgCgBIAAgCIgBgFQAAAAAAAAQAAgBgBAAQAAAAAAABQgBAAgBAAQgDAFgGACQgEABgGAAQgKAAgFgEgAAHABIgHACIgHACQgDABgBADQgBACAAAEQAAADADADQADACAFABIAFgBIAFgEIADgDIACgEIAAgJQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAg");
	this.shape_29.setTransform(-47.2,4.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgiAvIgBgBIgBgCIAAhYQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAjAAQAKAAAIADQAIADAFAHQAFAGAAAKQAAAJgFAGQgEAGgHADQgIADgKAAIgTAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAhQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAgAgRgeIAAAZQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABAAIAPAAQAIAAAFgEQAFgDAAgIQAAgFgDgDQgCgDgEgCQgEgBgFAAIgPAAQAAAAgBAAQAAAAgBAAQAAAAAAABQAAAAAAABg");
	this.shape_30.setTransform(-54.725,2.975);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgQAfQgIgFgEgIQgEgIAAgKQAAgJAEgIQAEgHAIgFQAHgFAJAAQAKAAAHAFQAIAFAEAHQAEAIAAAJQAAAKgEAIQgEAIgIAFQgHADgKAAQgJAAgHgDgAgIgUQgEADgCAFQgCAGAAAGQAAAHACAGQACAFAEADQAEACAEABQAFgBAEgCQAEgDACgFQACgGAAgHQAAgGgCgGQgCgFgEgDQgEgCgFAAQgEAAgEACg");
	this.shape_31.setTransform(-67.125,4.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAZAvIgBAAIgCgCIgqg8IgBAAIAAAAIAAA8QAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgMAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAhZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIANAAIACABIABABIAoA5IABABIABgBIAAg5QAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIALAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAABZIgBABIgBABg");
	this.shape_32.setTransform(-75.775,2.975);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgRAfQgIgEgDgGIAAgCIAAgBIAIgEIABAAIABAAIAFAFIAGAEIAHABIAHgBQAEgBACgCQAAAAABgBQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgDgDgCIgHgDIgMgDQgKgDgEgDQgFgEAAgIQAAgGAEgFQADgEAGgDQAGgCAIAAQAJAAAHADQAHADADAFIABABIgBACIgIAEIgBAAIgBgBQgDgDgEgCQgEgCgFAAQgFAAgDACQgEACAAAEQAAABAAAAQAAAAAAABQAAAAABABQAAAAAAAAQACADAFABIAOAEQAKACAEAEQAEAFAAAHQAAAGgDAFQgEAEgHADQgGADgJAAQgKAAgHgEg");
	this.shape_33.setTransform(34.375,-10.05);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAPAvIgBgBIgBgCIAAgrQAAgEgCgCQgDgDgFAAIgFABIgFADIgFAEIAAAsQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAIgLAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAhYQAAAAAAgBQABAAAAAAQAAAAAAgBQABAAAAAAIANAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAhIABABIABgBIAHgFIAGgDIAIgBQAJAAAGAFQAFAFAAAKIAAAsQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_34.setTransform(27.425,-11.375);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAGAtQgHAAgEgEQgFgEAAgIIAAglQAAAAAAgBQAAAAAAAAQgBAAAAgBQAAAAgBAAIgIAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgIQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAKAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIACgUQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAUIABABIAPAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAIQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgPAAQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAAgQAAAFACACQACACAEAAIAIAAIABABIAAABIAAAGQAAABAAAAQAAABAAAAQAAABgBAAQAAAAgBAAIgFAAIgEABg");
	this.shape_35.setTransform(21.7,-11.175);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAPAiIgBAAIgBgCIAAgrQAAgEgCgDQgDgDgFAAIgFABIgFADIgFAFIAAAsQAAAAAAABQgBAAAAAAQAAABgBAAQgBAAAAAAIgMAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAg9QAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIANAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHIABABIABgBIAHgFIAGgDQADgCAFAAQAJAAAFAFQAGAFAAAKIAAAtQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_36.setTransform(15.325,-10.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgQAeQgIgEgEgIQgEgHAAgKQAAgKAEgIQAEgIAIgEQAHgEAJAAQAKAAAHAEQAIAEAEAJQAEAHAAAKQAAAKgEAHQgEAIgIAEQgHAFgKAAQgJAAgHgFgAgIgUQgEADgCAFQgCAFAAAHQAAAHACAGQACAFAEADQAEACAEAAQAFAAAEgCQAEgDACgFQACgGAAgHQAAgHgCgFQgCgFgEgDQgEgCgFgBQgEABgEACg");
	this.shape_37.setTransform(7.825,-10.05);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AAhAvIgCgBIgBgCIAAhAIAAgBIgBABIgYBBQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgIAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIgYhBIAAAAIgBABIAABAIAAABIgCABIgKAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAhYQAAAAAAgBQABAAAAAAQAAAAAAgBQABAAAAAAIAWAAIABABIABABIAWA7IAAAAIABgBIAWg5QAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAWAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAABYQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_38.setTransform(-1.075,-11.375);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgeAvIgCAAIgBgCIAAgIIABgCIABgCIADgDIAZgXIAJgIIAFgHIAEgFIAAgGQAAgEgCgDQgCgEgEgBQgDgCgEAAIgHACIgGAEQgDACgDAFIgBABIgCAAIgJgFIgBgCIAAgCQAGgKAJgEQAIgEAKAAQAJAAAHADQAIADAEAGQAEAGABAJQAAAFgCAFIgHAJIgKAKIgYAUIgBABIACABIAoAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAALIAAACIgCAAg");
	this.shape_39.setTransform(-14.6,-11.425);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgXAvQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAOAAIABgBIAAg6QAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgNAFQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgIIABgBIABgBIAUgKIACgCIACAAIAHAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAABMIABABIANAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKIgBABIgBABg");
	this.shape_40.setTransform(-22.85,-11.375);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgDAdQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAgBAAAAIAAgVIALAAIAAAWQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAgAAGAGIAAgLIgLAAIAAgVIABgCIABAAIAHAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAWIAWAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAAAIAAAHQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAgAgFAGIAAgLIALAAIAAALgAgaAGIgCgBIgBgBIAAgHQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAWAAIAAALgAgFgFg");
	this.shape_41.setTransform(-34.275,-11.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-82.4,-18.2,164.9,45);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#47C434").s().p("AgFAqQgEAAAAgEIAAgcIAAgSIASAAIAAASIAAgSIgSAAIAAgdIABgDIADgBIALAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAeIAeAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAMQAAAEgFAAIgcAAIgSAAIASAAIAAAdQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAgAglAKIgDgBIgBgCIAAgMQAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAdAAIAAASgAgJgIg");
	this.shape.setTransform(-1.525,22.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAKBFQgMABgHgHQgHgGAAgNIAAg5QAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAgBAAIgNAAQAAAAgBgBQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAgMQAAgBAAAAQABgBAAAAQAAAAABAAQABAAAAAAIAOAAQABAAAAgBQABAAAAAAQAAAAAAgBQAAAAAAgBIADgdQAAgBAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAdQAAABAAAAQAAABAAAAQAAAAABAAQAAABAAAAIAXAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAMQAAABAAABQgBAAAAABQgBAAAAAAQgBABgBAAIgWAAQAAAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABIAAAzQAAAIADADQADACAHAAIAMAAIACABIAAACIAAALQAAADgDABIgHAAIgIAAg");
	this.shape_1.setTransform(85.175,44);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgIBJIgDgBIgBgDIAAhgQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIASAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAABfQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAIgEABgAgIgtIgEgBIAAgDIAAgTQAAgEADAAIAUAAQAAAAABAAQAAABAAAAQABABAAAAQAAABAAABIAAATQAAAEgEAAg");
	this.shape_2.setTransform(79.3,43.675);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAYA1IgDgBIAAgDIAAhCQAAgHgFgFQgEgEgIAAQgEAAgEABIgIAFIgIAHIAABFQAAAEgEAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAhgQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAAAAAIAUAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAALIABABIACgBIALgIQAFgEAFgCQAFgCAHAAQAOAAAJAJQAIAIAAANIAABHQAAAEgEAAg");
	this.shape_3.setTransform(71.825,45.65);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AggBDQgMgGgGgNQgFgNAAgTIAAhVQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAABAAIAXAAQABAAAAAAQABABAAAAQAAAAAAABQABABAAAAIAABbQAAAQAHAIQAIAIANAAQAJAAAIgEQAGgDAEgHQADgHAAgMIAAhZQAAgBABgBQAAAAAAgBQABAAAAgBQABAAABAAIASAAQABAAAAAAQABABAAAAQAAAAAAABQAAABAAAAIAABaQAAATgGAMQgHAMgNAFQgMAGgSAAQgTAAgNgHg");
	this.shape_4.setTransform(58.8,43.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgpBEQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgNIABgCQAAAAAAAAQABAAAAgBQABAAABAAQAAAAABAAIANAAQAEAAADgCIAGgFQACgDAAgEQABgDgBgDIgmhcIAAgDQABAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAVAAIACABIACACIAXBAQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAYhAIACgCIACgBIAOAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAABAAIAAADIgqBmQgDAJgEAGQgDAFgFAEQgFADgGABQgGABgJAAg");
	this.shape_5.setTransform(42.025,47.375);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgbA1IgDgBIgBgDIAAhgQAAAAAAgBQABgBAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAAAMIAAACQAAAAABAAQAAAAAAAAQAAgBABAAQAAAAAAAAQAEgGAEgEQAFgEAGgCQAFgCAFAAQAHAAAAADIAAATQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAIgGgCIgGAAIgIACQgEABgEADIgEAHQgCADAAADIAAA7QAAAEgFAAg");
	this.shape_6.setTransform(33.525,45.65);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgYAvQgMgGgHgMQgGgMAAgPQAAgQAGgNQAIgMALgHQAMgHANAAQAPAAALAHQALAGAGAMQAHAMAAARIAAACIgEACIhEAAIgBABIgBACQAAAIAEAGQADAHAHADQAGAEAIAAQAHAAAHgDQAGgEAHgHIABgBIACAAIAMAGQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQgGAJgGAFQgHAFgIADQgJACgKAAQgNAAgMgHgAgKghQgHAEgCAGQgDAGAAAJIAtAAIACgBIABgDQAAgFgDgHQgCgFgGgEQgGgEgHAAQgHAAgFAEg");
	this.shape_7.setTransform(24,45.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgFA0QgEAAgCgEIgnheQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAVAAIACABIACACIAYBAQAAAAAAABQABAAAAAAQABAAAAAAQABgBAAgBIAZg/IACgCIACgBIAOAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIAAADIgnBfQgCAEgEAAg");
	this.shape_8.setTransform(13.9792,45.75);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgvBJQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAiJQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAAAAAIBfAAQAAAAABAAQAAABAAAAQABAAAAABQAAABAAAAIAAAPQAAABAAABQAAAAgBABQAAAAgBABQgBAAgBAAIg/AAQgBAAgBAAQAAAAgBAAQAAABAAAAQAAABAAABIAAAiQAAAAAAABQAAABAAAAQABAAAAABQABAAAAAAIAsAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAPIgBABIgCABIgsAAQgBAAAAAAQgBABAAAAQAAAAAAAAQAAABAAAAIAAAlQAAAAAAABQAAAAAAABQAAAAABAAQAAAAAAAAIBEAAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAQIAAACIgDABg");
	this.shape_9.setTransform(2.15,43.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgLBJQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAhRQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgQAAQAAAAgBAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgMIABgCIACgBIAPAAQABAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBIAAgMQAAgNAHgHQAHgHAMAAIATAAQAEAAAAAEIAAALIgBACIgCABIgLAAQgGAAgCADQgDAEAAAFIAAAKQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAAAIATAAIACABIABACIAAAMQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABIAABPQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_10.setTransform(-11.775,43.675);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgLBJQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAhRQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgQAAQAAAAgBAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgMIABgCIACgBIAPAAQABAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBIAAgMQAAgNAHgHQAHgHAMAAIATAAQAEAAAAAEIAAALIgBACIgCABIgLAAQgGAAgCADQgDAEAAAFIAAAKQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAAAIATAAIACABIABACIAAAMQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABIAABPQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_11.setTransform(-18.975,43.675);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgiBCQgPgJgHgRQgJgQABgXQgBgXAJgRQAHgRAPgJQAPgJATAAQAUAAAPAJQAPAJAHARQAIARAAAWQAAAYgIAQQgHARgPAJQgPAJgUAAQgTAAgPgJgAgagoQgIANAAAcQAAAbAIANQAKANAQAAQASAAAIgNQAJgMAAgcQAAgcgJgNQgIgNgSAAQgRAAgJANg");
	this.shape_12.setTransform(-30.55,43.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgdBCQgNgJgIgQQgHgRAAgXQgBgRAFgOQAEgOAJgKQAHgJALgFQALgGALAAQANAAALAGQAKAFAIAJQAIAKAEAOQAFAOAAARQAAAXgIARQgHAQgNAJQgNAJgSAAQgQAAgNgJgAgOgwQgHAGgEAMQgDANAAASQAAASADAMQAEAMAHAGQAGAFAIAAQAJAAAHgFQAGgGAEgMQAEgLAAgTQAAgSgEgNQgEgMgGgGQgHgFgJAAQgIAAgGAFg");
	this.shape_13.setTransform(-47.45,43.65);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgdBCQgNgJgIgQQgHgRAAgXQgBgRAFgOQAEgOAJgKQAHgJALgFQALgGALAAQANAAALAGQAKAFAIAJQAIAKAEAOQAFAOAAARQAAAXgIARQgHAQgNAJQgNAJgSAAQgQAAgNgJgAgOgwQgHAGgEAMQgDANAAASQAAASADAMQAEAMAHAGQAGAFAIAAQAJAAAHgFQAGgGAEgMQAEgLAAgTQAAgSgEgNQgEgMgGgGQgHgFgJAAQgIAAgGAFg");
	this.shape_14.setTransform(-59.6,43.65);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgkBJQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgQQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAVAAQABAAAAAAQABAAAAAAQAAAAAAgBQABAAAAAAIAAhaQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgVAHQgDABAAgFIAAgLIAAgCIACgCIAfgQIAFgBIACgBIALAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIAAB2QAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAUAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAAQIgBACIgDABg");
	this.shape_15.setTransform(-72.4,43.675);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgCBYQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAgJIAAgCIgCgBQgPAAgLgFQgKgFgJgJQgEgDADgDIAKgKIACgBIADABQAGAHAHAEQAIAEAKABQAAABABAAQABgBAAAAQAAAAABAAQAAgBAAAAIAAgnIgBgDIgDgBQgPgFgKgEQgJgGgEgJQgEgHAAgKQAAgKAFgJQAFgIAKgGQAJgGANgCIACgBQABAAAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAIAAgIIAAgCIACgBIAKAAIADABIAAADIAAAJQAAAAAAAAQABAAAAAAQAAABABAAQAAAAABAAQALACAIAEQAIADAHAHQABAAAAABQABAAAAABQAAAAgBABQAAAAAAABIgJALIgDACIgCgCQgEgEgFgDQgGgDgGgCIgCAAIgBACIAAAnQAAAAAAAAQABABAAAAQAAAAABABQAAAAABAAIAJADQALAEAHAEQAIAGAEAIQAEAIAAAKQAAAKgFAKQgFAJgKAFQgKAFgNABIgCABIgBACIAAAIQAAAFgEAAgAAKAQIAAAlQAAAAAAAAQABAAAAAAQAAABABAAQAAAAABgBQAKAAAFgGQAGgFAAgHQAAgIgFgEQgFgGgLgDIgCAAIgBACgAgIg2QgKABgFAGQgGAFAAAHQAAAFACADQACAEAEADQAFADAHACQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAIAAgiQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIgBABg");
	this.shape_16.setTransform(-81.9731,43.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6CC14C").s().p("AguBHQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIgBgDIAAiHQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAIBfAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAABIAAARQAAAEgEAAIg7AAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIAAAeQAAABAAAAQABABAAAAQAAABABAAQAAAAABAAIApAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAAARQAAABAAABQgBAAAAABQAAAAgBAAQgBABAAAAIgpAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAABIAAAzQAAAEgFAAg");
	this.shape_17.setTransform(99.225,3.75);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6CC14C").s().p("AguBHQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIgBgDIAAiHQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAIBfAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAABIAAARQAAAEgEAAIg7AAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABIAAAeQAAABAAAAQABABAAAAQAAABABAAQAAAAABAAIApAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAAARQAAABAAABQgBAAAAABQAAAAgBAAQgBABAAAAIgpAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAABIAAAzQAAAEgFAAg");
	this.shape_18.setTransform(87.525,3.75);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6CC14C").s().p("AgiBAQgPgIgIgQQgIgRAAgXQAAgVAIgRQAJgQAPgKQAOgJAUAAQATAAAPAJQAPAKAIAQQAIARAAAVQAAAXgIARQgIAQgPAIQgPAJgTAAQgUAAgPgJgAgWglQgIAMAAAZQAAAaAIAMQAHAMAQAAQAPAAAHgMQAIgLgBgbQABgZgIgMQgHgMgPAAQgQAAgHAMg");
	this.shape_19.setTransform(73.55,3.75);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6CC14C").s().p("AAdBEQgIgFgFgJQgFgKAAgLQAAgLAFgKQAFgIAIgFQAIgGAKAAQALAAAIAGQAIAFAFAIQAEAKAAALQAAALgEAKQgFAJgIAFQgIAFgLABQgKgBgIgFgAAnAKQgDAEgBAFQgCAGAAAJQAAAHACAFQABAGADADQADADAFAAQAFAAADgDQAEgDABgGQACgFAAgHQAAgJgCgGQgCgFgDgEQgDgCgFAAQgFAAgDACgAgyBIQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIABgFIBaiIIADgCIACAAIAKAAIACABIAAACIhcCLQgBACgEABgAhAACQgJgEgEgKQgFgIAAgMQAAgLAFgJQAFgKAIgFQAIgGAKABQALgBAIAGQAIAFAFAKQAEAJAAALQAAAMgEAIQgFAKgIAEQgIAGgLAAQgKAAgIgGgAg2g2QgDACgCAHQgBAGAAAHQAAAIABAGQACAFADAEQADACAFAAQAIAAADgGQAEgHAAgMQAAgMgEgHQgDgHgIAAQgFAAgDAEg");
	this.shape_20.setTransform(75.175,-13.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6CC14C").s().p("Ag2B0QgZgQgNgdQgOgegBgnQAAgeAJgYQAHgZAPgSQAPgRATgKQAUgJAWAAQAYAAATAJQAUAKAOARQAOASAJAZQAIAYAAAdQgBAogOAeQgOAdgYAQQgXAQggAAQgeAAgYgQgAgYhPQgKAJgGAUQgFAUAAAgQAAAfAFAUQAGATAKAJQAKAIAOAAQAQAAAKgIQAKgJAEgTQAGgUAAgfQAAgggGgUQgFgUgKgJQgKgKgPAAQgOAAgKAKg");
	this.shape_21.setTransform(53.05,-2.975);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6CC14C").s().p("AAPCBQgHAAAAgHIAAgzQAAgDgEAAIhnAAQgIAAAAgGIAAgdIACgHIAHgKIBoiJIAGgFIAIgCIAsAAQAFAAAAAGIAACRQAAAEAEAAIAcAAQAHAAAAAFIAAAeQAAAGgHAAIgcAAQgEAAAAAEIAAAxQAAAIgJAAgAADg/Ig9BVQgDAFAGAAIA8AAQABAAABAAQAAgBAAAAQABAAAAgBQAAAAAAgBIAAhVIgBgFg");
	this.shape_22.setTransform(31.875,-2.925);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6CC14C").s().p("Ag+B0QgbgPgOgeQgPgdAAgpQAAgoAPgeQAPgeAbgQQAagQAjAAQAlAAAaAQQAbAQAOAeQAPAdAAApQAAAogPAeQgOAdgbAQQgaAQglAAQgjAAgbgQgAgphDQgNAWAAAuQAAAvANAVQAOAVAbAAQAdAAANgVQANgVAAgvQAAgugNgWQgOgWgcAAQgbAAgOAWg");
	this.shape_23.setTransform(-3.175,-2.925);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6CC14C").s().p("Ag6B0QgagQgOgeQgPgdAAgoQAAgoAPgeQAPgeAbgQQAbgQAjAAQAcAAAWALQAWAKAOARQANARAEASIAAAHQgBACgDABIgtAHQgBAAgBAAQgBAAAAgBQgBAAAAAAQAAAAgBgBIgBgEQgCgLgHgKQgGgJgLgGQgKgFgOAAQgQAAgMAJQgNAIgGAUQgGATAAAgQAAAgAGAUQAIAUAMAJQAMAJASAAQAKAAAJgEQAJgDAFgGQAGgFAFgHQADgHACgIIAAgKQACgFgFAAIgqAAIgEgBIgBgFIAAgaQgBgEAGAAIBdAAQAFAAACABQADADAAADIAAB1IgCAEIgEACIgKAAIgFgBIgEgFIgKgZIgBgBIgDACQgHAIgIAHQgKAIgOAFQgOAFgUAAQgiAAgagQg");
	this.shape_24.setTransform(-30.65,-2.925);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6CC14C").s().p("Ag+B0QgbgPgOgeQgPgdAAgpQAAgoAPgeQAPgeAbgQQAagQAjAAQAlAAAaAQQAbAQAOAeQAPAdAAApQAAAogPAeQgOAdgbAQQgaAQglAAQgjAAgbgQgAgphDQgNAWAAAuQAAAvANAVQAOAVAbAAQAdAAANgVQANgVAAgvQAAgugNgWQgOgWgcAAQgbAAgOAWg");
	this.shape_25.setTransform(-57.075,-2.925);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6CC14C").s().p("AhiCBQgDAAgCgCIgCgFIAAjyQAAgEACgCQABAAAAgBQABAAAAAAQABgBAAAAQABAAABAAIBeAAQAyAAAbASQAbARAAAhQAAATgLANQgKANgZALIgBACIABABQAcAIAMAOQAMAPAAAXQAAAjgbASQgaARg1AAgAgsAaIAAA3QAAAHAFAAIAmAAQAVAAAMgKQALgJAAgPQAAgMgGgHQgFgIgKgDQgJgEgNAAIgmAAQgGAAAAAGgAgshRIAAA1QAAAGAFAAIAnAAIAPgBQAHgCAGgEQAFgEADgGQAEgGAAgIQAAgQgMgJQgMgJgSAAIgkAAQgGAAAAAGg");
	this.shape_26.setTransform(-80.575,-2.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgKBJQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIAAgWQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIAWAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAAAWQAAAEgFAAgAgEAfIgDgBIgBgDIgGhgIABgCIACgBIAXAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIgHBgQAAAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAIgDABg");
	this.shape_27.setTransform(91.875,-39.875);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgYAwQgMgIgGgLQgIgMABgPQgBgRAIgMQAGgNAMgGQAMgHANAAQAPAAALAGQALAHAHAMQAFAMAAARIAAADIgCABIhFAAIgBABIgBACQAAAIADAHQAFAGAGADQAHAEAGAAQAJAAAGgDQAHgEAFgHIACgBIACABIAMAFQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAABQgHAIgGAFQgHAFgIACQgIADgKAAQgOAAgMgGgAgLghQgFAEgEAGQgCAHAAAHIAsAAIADAAIABgDQAAgFgDgGQgDgGgFgEQgGgEgHAAQgGAAgHAEg");
	this.shape_28.setTransform(84.25,-37.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgIBJQgEAAAAgEIABiJQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAAAAAIATAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIAACJIgBAEIgEABg");
	this.shape_29.setTransform(76.65,-39.875);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AglAuQgIgIAAgNQAAgKAGgJQAHgGAMgFQAMgEARgBIAKgBIACgBIABgBIAAgFQAAgJgFgEQgFgFgKgBQgFAAgGAEQgGACgEAIIgCABIgCAAIgRgEIgBgBIAAgEQAGgLALgFQAMgGAQAAQAPAAAJAEQAKAEAEAIQAEAHAAAKIAABEIgBADIgCABIgRAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIgBgCIAAgHQAAAAAAgBQAAAAgBAAQAAAAgBAAQgBAAgBABQgGAGgIADQgHAEgKAAQgPAAgJgIgAATACIgIAAQgHAAgEACIgLADIgHAGQgCAEAAAFQAAAHAFAEQAEAEAJAAQAEAAAFgCIAHgEIAGgHQACgCAAgDIAAgPQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAIAAABg");
	this.shape_30.setTransform(68.425,-37.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgWBIQgLgDgIgGQgJgGgGgHIAAgDIACgDIAMgIQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAIACABQAFAGAFAEQAFAEAGACQAGACAJAAQANAAAIgFQAJgEAAgKQgBgEgBgDQgCgDgEgDQgDgDgIgCIgdgJQgLgEgHgFQgIgGgDgHQgEgIAAgJQAAgMAGgKQAIgKAMgFQALgGAQAAQALAAAJADQAJACAIAFQAHAEAFAHIABACIgBACIgOAKIgCABIgCgCQgFgFgGgEQgIgEgLAAQgNAAgGAFQgIAFABAJIABAGQABADAEADQAEADAHACIAdAJQASAFAJAKQAHAKAAAOQAAAOgHAKQgGAJgNAFQgMAGgSAAQgMAAgLgDg");
	this.shape_31.setTransform(56.7,-39.875);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgbA1IgDgBIgBgCIAAhhQAAAAAAgBQABgBAAAAQAAgBABAAQAAAAABAAIATAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAMIAAACQABAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAgBQAEgFAEgEQAFgDAGgCQAFgDAFAAQAHAAAAAEIAAASQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBgBIgGgBIgGAAIgIABQgEACgEADIgEAGQgCADAAAEIAAA7QAAAEgFAAg");
	this.shape_32.setTransform(42.775,-37.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgYAwQgMgIgHgLQgGgMgBgPQABgRAGgMQAIgNALgGQAMgHANAAQAPAAALAGQALAHAHAMQAFAMABARIAAADIgEABIhEAAIgCABIAAACQAAAIAEAHQAEAGAGADQAHAEAGAAQAIAAAHgDQAGgEAGgHIACgBIACABIAMAFQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBABQgFAIgHAFQgHAFgIACQgIADgLAAQgNAAgMgGgAgKghQgHAEgCAGQgEAHAAAHIAtAAIADAAIABgDQAAgFgDgGQgCgGgGgEQgFgEgIAAQgHAAgFAEg");
	this.shape_33.setTransform(33.25,-37.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AA4A1IgDgBIgBgCIAAhDQAAgIgEgEQgDgEgIAAQgFAAgEACIgHAEIgGAFIgCACIAAADIAABCQAAAEgEAAIgRAAIgDgBIgBgCIAAhDQAAgIgEgEQgDgEgIAAQgHAAgFADQgGAEgGAGIAABFQAAAEgFAAIgRAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAhhQAAAAAAgBQABgBAAAAQAAgBABAAQAAAAABAAIATAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAKIABABIABAAIALgJQAFgDAGgCQAFgCAGAAQALAAAGAFQAIAFACAIIABABIACgCIALgJQAFgEAHgBQAGgDAGAAQAOAAAIAIQAIAJAAAOIAABGQAAAEgEAAg");
	this.shape_34.setTransform(20.225,-37.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AA4A1IgDgBIgBgCIAAhDQAAgIgEgEQgDgEgIAAQgFAAgEACIgHAEIgGAFIgCACIAAADIAABCQAAAEgEAAIgRAAIgDgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAIAAhDQAAgIgEgEQgDgEgIAAQgHAAgFADQgGAEgGAGIAABFQAAAEgFAAIgRAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAhhQAAAAAAgBQABgBAAAAQAAgBABAAQAAAAABAAIATAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAKIABABIABAAIALgJQAFgDAGgCQAFgCAGAAQALAAAGAFQAIAFACAIIABABIACgCIALgJQAFgEAHgBQAGgDAGAAQAOAAAIAIQAIAJAAAOIAABGQAAAEgEAAg");
	this.shape_35.setTransform(3.925,-37.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgeAxQgHgEgEgGQgEgIAAgJIAAhGQAAgEAEAAIASAAQADAAAAAEIAABCQAAAHAFAFQAEAFAHgBQAHAAAGgEQAFgDAHgGIAAhFQAAgEAEAAIARAAQAEAAAAAEIAABgQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBAAIgTAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgKIAAgBIgCAAQgJAJgIADQgHAEgJAAQgKAAgGgEg");
	this.shape_36.setTransform(-10.25,-37.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgWBIQgLgDgIgGQgJgGgGgHIAAgDIACgDIAMgIQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAIACABQAFAGAFAEQAEAEAHACQAGACAJAAQANAAAIgFQAJgEAAgKQgBgEgBgDQgCgDgEgDQgDgDgIgCIgdgJQgLgEgHgFQgIgGgDgHQgEgIAAgJQAAgMAGgKQAIgKAMgFQALgGAQAAQALAAAJADQAJACAIAFQAHAEAFAHIABACIgBACIgOAKIgCABIgCgCQgFgFgGgEQgIgEgLAAQgNAAgGAFQgIAFABAJIABAGQABADAEADQAEADAHACIAdAJQASAFAIAKQAIAKAAAOQAAAOgHAKQgGAJgNAFQgMAGgSAAQgMAAgLgDg");
	this.shape_37.setTransform(-22.5,-39.875);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgLBJQAAAAgBAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAhRQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgQAAQAAAAgBAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgMIABgCIACgBIAPAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAgBIAAgMQAAgNAHgHQAHgHAMAAIATAAQAEAAAAAEIAAALIgBACIgCABIgLAAQgGAAgCADQgDAEAAAFIAAAKQAAAAAAABQAAAAABAAQAAAAAAABQABAAAAAAIATAAIACABIABACIAAAMQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAIgSAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAABIAABPQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_38.setTransform(-35.825,-39.875);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgaAvQgMgHgGgMQgHgMAAgPQAAgQAHgMQAHgMALgHQAMgHAOAAQAQAAALAHQAMAHAGAMQAHAMAAAQQAAAPgHAMQgHAMgLAHQgMAHgPAAQgOAAgMgHgAgNgfQgGADgDAJQgDAIAAALQAAAMADAIQADAIAGAEQAGAEAHABQAIgBAGgEQAGgEADgIQADgIAAgMQAAgLgDgIQgDgJgGgDQgGgFgIAAQgHAAgGAFg");
	this.shape_39.setTransform(-44.725,-37.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgcBEQgJgGgGgMQgGgMABgRQgBgRAGgLQAGgMAKgHQAKgHAMAAQAIAAAGADQAGACAFAFIADABIABgCIAAguQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAUAAQABAAABAAQAAABABAAQAAABAAAAQABABAAABIAACJQAAABgBAAQAAABAAAAQAAAAAAAAQAAABgBAAIgDABIgRAAIgCgBIgBgDIAAgGQAAgBgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIgCABIgHAGQgEADgFACQgGACgHAAQgMAAgJgGgAgKgMQgGAEgDAIQgDAHgBANQABAOADAIQADAIAGAEQAFADAHAAQAGAAAFgDQAFgDADgEQADgFAAgEIAAgrQgFgGgFgCQgFgDgHAAQgGAAgGAEg");
	this.shape_40.setTransform(-61.15,-39.775);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AAYA1IgDgBIAAgCIAAhDQAAgIgFgEQgEgEgIAAQgEAAgEACIgIAEIgIAHIAABFQAAAEgEAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAhhQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAAAAAIAUAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAKIABABIACAAIALgJQAFgDAFgCQAFgCAHAAQAOAAAJAIQAIAJAAAOIAABGQAAAEgEAAg");
	this.shape_41.setTransform(-71.825,-37.9);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgvBJQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAiJQAAgBABgBQAAAAAAgBQABAAAAgBQABAAABAAIBdAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAPQAAABAAABQAAAAgBABQAAAAgBABQgBAAgBAAIg/AAQgBAAgBAAQAAAAgBAAQAAABAAAAQAAABAAABIAAAiQAAAAAAABQAAABAAAAQABAAAAABQABAAAAAAIAsAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAPIgBABIgCABIgsAAQgBAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIAAAlQAAAAAAABQAAAAAAABQAAAAABAAQAAAAABAAIBDAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAAQIgBACIgDABg");
	this.shape_42.setTransform(-84,-39.875);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#48C435").ss(1,1,1).p("ABHAAIOeAAAvkAAIOAAA");
	this.shape_43.setTransform(-0.85,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104.8,-50.5,213.7,108.8);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_02_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_01();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AFrA4QgJgFgEgHIgBgDIABgBIAMgFIABABIAFAFQAEAEAEABQAFACAGgBQAFABAEgCQAEgBADgCQACgDAAgDQAAgEgDgCQgCgCgHgCIgRgEQgMgCgGgHQgFgFAAgJQAAgHAEgGQAEgGAIgEQAIgDALAAQAMAAAIAEQAJAFAEAGIABACIgBACIgKAEIgCAAIgBgBQgDgEgFgCQgFgDgHAAQgHAAgFADQgFACAAAFQAAADACACQACABAHACIATAGQAMACAGAHQAFAGAAAJQAAAIgFAGQgEAGgJADQgIADgLAAQgOAAgKgFgAD/A4QgKgFgFgLQgFgLAAgPIAAhFQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAABJQAAAOAGAGQAGAGAMAAQAIAAAFgDQAGgCADgHQADgFAAgKIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABIQAAAQgGAKQgFAJgLAFQgKAEgOAAQgRAAgKgFgABAA4QgJgGgGgKQgFgJAAgNQAAgNAFgKQAGgKAJgGQAKgFAMAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEgGIgFgEQgDgCgEAAQgHAAgFAEQgFADgCAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAHAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgMAAgKgFgAgsA3QgHgHAAgKQAAgJAFgHQAFgGALgEQAKgEAOAAIAHAAIACgBIAAgCIAAgDQAAgHgDgDQgEgFgHAAQgGAAgFADQgFADgDAFIgBACIgCAAIgOgEIgBgBIABgCQAEgJAJgGQAKgEAOAAQALAAAIADQAHAEAEAGQADAGAAAHIAAA4IAAADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBgBAAQAAgBAAAAQgBAAAAABQgBAAAAAAQgFAGgGACQgHADgIAAQgMAAgHgGgAgFATIgKABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAHAAQAEAAAEgBIAGgEIAEgFIABgFIAAgLQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAgAkbA4QgKgGgFgKQgFgKAAgMQAAgNAFgKQAGgKAJgGQAKgFAMAAQAMAAAKAGQAJAFAGAKQAFAKAAANQAAAMgGAKQgFAKgJAGQgKAFgMAAQgNAAgJgFgAkRgIQgEADgDAGQgCAHAAAJQAAAJACAIQADAGAEAEQAFADAHAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgJgDgHQgCgGgFgDQgFgEgGAAQgHAAgFAEgAmOA2QgMgIgGgOQgHgOAAgSQAAgSAHgOQAGgNAMgHIAEgCQAKgGAOAAQAJAAAIADIAGADIAIAEQAGAFAEAGQAEAGABAIIABACIgCABIgSABIgCAAIgBgCQgCgIgFgGQgGgGgKAAQgOAAgHAKQgIALAAAWQAAAWAHALQAIALAOAAQAKgBAHgFQAHgEAFgMQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANADIABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgEAIIgGAJQgEAFgFADQgGADgHADQgHACgJAAQgQAAgMgHgACVA3QgGgGAAgKIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIADgZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIASAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgSABQgLAAgFgEgAhgA3QgFgGAAgKIAAguQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgKQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIALAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAABIASAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAAAqQAAAGADADQACACAGAAIAJAAIACABIABABIgBAJQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgRABQgLAAgGgEgAiTA7IgCAAIgBgDIAAg2QAAgFgDgEQgEgDgGAAIgIABIgGADIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgEQAFgCAFAAQAMAAAHAHQAHAHAAALIAAA5QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(-9.6077,0.1314,0.9718,0.9718);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AAhgpIAeApAg+AAIB9AAIgkAq");
	this.shape_1.setTransform(43.225,-0.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(0.4,1,1).p("ApCiqISFAAIAAFVIyFAAg");
	this.shape_2.setTransform(-0.025,0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC24D").s().p("ApCCrIAAlVISFAAIAAFVgAHMAmIAkgpIh/AAIB/AAgAHwgDIgegpg");
	this.shape_3.setTransform(-0.025,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.9,-17.8,117.8,36.2);


(lib.BG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


// stage content:
(lib.WBAY_219645_MM_300X600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(375));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(150.05,585.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(75).to({_off:false},0).to({y:565.6,alpha:1},17,cjs.Ease.get(1)).wait(283));

	// logo_png
	this.instance_1 = new lib.logo_1("synched",0);
	this.instance_1.setTransform(80,290);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({y:300,alpha:1},17,cjs.Ease.get(1)).wait(347));

	// T3
	this.instance_2 = new lib.T3("synched",0);
	this.instance_2.setTransform(149.95,540.05);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(59).to({_off:false},0).to({y:520.05,alpha:1},17,cjs.Ease.get(1)).wait(299));

	// T2
	this.instance_3 = new lib.T2("synched",0);
	this.instance_3.setTransform(149.95,493.15);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(42).to({_off:false},0).to({y:473.15,alpha:1},17,cjs.Ease.get(1)).wait(316));

	// T1
	this.instance_4 = new lib.T1("synched",0);
	this.instance_4.setTransform(148,374.55);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(26).to({_off:false},0).to({y:394.55,alpha:1},17,cjs.Ease.get(1)).wait(332));

	// Img_04_jpg
	this.instance_5 = new lib.Img_04_1("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(253).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(105));

	// Img_03_jpg
	this.instance_6 = new lib.Img_03_1("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(210).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(148));

	// Img_02_jpg
	this.instance_7 = new lib.Img_02_1("synched",0);
	this.instance_7.setTransform(80,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(166).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(192));

	// Img_01_jpg
	this.instance_8 = new lib.Img_01_1("synched",0);
	this.instance_8.setTransform(80,300);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(14).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(344));

	// BG_jpg
	this.instance_9 = new lib.BG_1("synched",0);
	this.instance_9.setTransform(80,300);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},17,cjs.Ease.get(1)).wait(358));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,290,152,314);
// library properties:
lib.properties = {
	id: '45EA4FADEDA04BCCBB7A758F81F2D007',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['45EA4FADEDA04BCCBB7A758F81F2D007'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;