(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgOAdQgIgEgEgHQgEgHAAgKQAAgJAEgIQAFgHAHgEQAHgFAIAAQAJAAAHAEQAGAEAEAIQAEAHAAAKIAAABIgCABIgpAAIgBAAIgBACQAAAFADAEQACAEAEACQAEACAEAAQAFAAAEgCQAEgCADgFIABAAIABAAIAIAEQAAAAAAAAQABAAAAABQAAAAgBAAQAAABAAAAIgIAJQgEADgFABIgLABQgIAAgHgEgAgGgTQgEACgCADQgCAFAAAEIAcAAIABAAIABgBIgCgIQgCgDgDgCQgDgDgFAAQgEAAgDADg");
	this.shape.setTransform(70.825,25.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgQAdQgHgDgDgGIgBgBIABgBIAHgEIACgBIABABIADAFIAGADIAIABIAHgBQADgBABgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgCgCgGgBIgLgDQgJgCgEgDQgEgFAAgHQAAgGADgEQADgFAGgCQAGgDAHAAQAJAAAHAEQAGADADAEIABACIgBABIgHADIgCABIgBgBIgGgFQgEgCgFAAQgEAAgEACQgDACAAAEIABAEIAGADIAOADQAJADAEADQAEAFAAAGQAAAHgDAEQgEAFgGACQgHACgHAAQgKAAgHgEg");
	this.shape_1.setTransform(63.75,25.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWAdQgFgFAAgIQAAgHAEgFQAEgEAHgDQAIgCAKgBIAGAAIABAAIABgCIAAgCQAAgGgEgDQgDgDgFAAIgHACQgEACgCAEIgBABIgCAAIgKgDIgBAAIABgCQADgHAHgDQAHgEAJAAQAKAAAFACQAGADADAEQACAGAAAFIAAApIAAACIgCABIgKAAIgBgBIgBgCIAAgDQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAgBABQgEADgEACQgEACgGAAQgKAAgFgEgAAHACIgHAAIgGADIgEAEQgCACAAADQAAAEADACQADACAFAAIAFgBIAFgCIADgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAg");
	this.shape_2.setTransform(56.575,25.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAPAtIgCgBIAAgBIAAgqQAAgEgDgCQgCgDgFAAIgEABIgFADIgGAEIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAgIAAABIABgBIAIgGIAFgCIAHgBQAKAAAFAEQAEAGAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_3.setTransform(49.775,23.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgNAdQgHgEgEgHQgEgIAAgJQAAgKAEgHQAEgHAHgEQAHgFAIAAQAHAAAFACQAGADADAEIAFAIQABABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgKACIgCgBIgDgFIgEgDQgCgCgEAAQgDAAgEADQgEADgCAFQgCAFAAAGQAAAIADAEQACAGADACQAEADAEAAQAGAAADgDQAEgDADgFIAAgBIACAAIAHADQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIgEAFQgCAEgDADQgDACgFABQgEACgGAAQgIAAgHgEg");
	this.shape_4.setTransform(42.9583,25.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgRAhIgBgBIAAgBIAAg7QAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAIAMAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABAAIAFgHIAGgDIAGgBQABAAABAAQABAAAAAAQABAAAAABQAAAAAAABIAAALQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAgBIgEAAIgEAAIgEAAIgFAEIgCADQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAABIAAAjQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAg");
	this.shape_5.setTransform(37.75,25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgSAeQgEgCgDgEQgCgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAoQgBAEADADQADADAEAAQAEAAADgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIAAgBIgBABQgGAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_6.setTransform(31.3,25.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AggAtIgCgBIAAgBIAAhVQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAgAAQAKgBAIADQAIADAFAGQAEAGAAAKQAAAJgEAGQgEAEgIAEQgGADgKgBIgSAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgBAAAAAAIAAAgQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAgAgRgdIAAAYQAAABABAAQAAABAAAAQAAAAABAAQAAABABAAIAOAAQAIAAAFgEQAEgEAAgHQAAgEgCgEQgCgDgFgBIgIgCIgOAAQgBAAAAABQgBAAAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_7.setTransform(23.65,23.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgaAnQgIgEAAgIQAAgEADgDQADgDAFgCQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAgBAAQgDgBgBgCQgCgCAAgDQAAgBAAAAQAAgBAAgBQAAAAABAAQAAgBAAAAIAEgDIAGgDIAAAAIAAgBQgGgDgCgEQgDgEAAgFQAAgJAHgGQAIgFAOAAQAFAAAFABQAFACADACIABABIACgBIADgDIAFgDIAEAAIABAAIABACIAAAHIgBACIgBAAIgEAAIgCAAQgBABgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIABADIABAEQAAAFgDAEQgDAFgHADQgGACgIAAIgJABIgEABIgBACQAAAAAAAAQAAABAAAAQAAAAABAAQAAABABAAIAGABIAQABQAMABAFAEQAFAFAAAHQAAAJgIAGQgJAFgPAAQgQAAgJgEgAgQASIgDADQgBAAAAABQAAAAgBABQAAAAAAABQAAABAAAAQAAADACADQACACAFABIAMABQAIAAAFgCQAFgDAAgEQAAgEgDgCQgCgCgGAAIgSgBIgFABgAgMgeQgDADAAAGQAAAFADADQAEADAHAAQAGAAADgDQADgDAAgFQAAgGgDgDQgDgDgGAAQgHAAgEADg");
	this.shape_8.setTransform(11.725,26.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAPAhIgCgBIAAgBIAAgpQAAgFgDgCQgCgDgFAAIgFABIgEADIgGAFIAAApQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg7QAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAGIAAABIABAAIAHgGQADgCADgBQADgBAEAAQAJgBAFAGQAFAFAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_9.setTransform(4.375,25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgEAtIgCgBIgBgBIAAg7QAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAABAAAAIAAA6IAAACIgCABgAgFgbIgBAAIgBgCIAAgNQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_10.setTransform(-0.9,23.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgZApIgCgBIAAgIIABgBIADgBIAIAAIAEgBIADgEIACgEIAAgDIgXg4IAAgCIABgBIANAAIABABIABABIAOAnQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIABgBIAPgnIABgBIABgBIAJAAIABABIAAACIgZA+IgFAJIgEAFQgDACgEABIgJABg");
	this.shape_11.setTransform(-5.725,26.075);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgHAtQAAAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgxIgBgBIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgHIAAgBIABgBIAJAAQABAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAIAAgIQAAgIAFgFQADgEAHABIAMAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIABAHIgBABIgCABIgGAAQgBAAgBAAQgBAAAAABQgBAAAAAAQgBABAAAAQgCADAAACIAAAHQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIAMAAIACABIAAABIAAAHQAAAAAAABQAAAAgBABQAAAAAAAAQAAAAgBAAIgLAAQAAAAgBAAQAAAAAAAAQAAAAAAABQAAAAgBAAIAAAxQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_12.setTransform(-10.55,23.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgFAtIgBgBIgBgBIAAg7QAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQABABAAAAIAAA6IgBACIgCABgAgFgbIgBAAIgBgCIAAgNQAAAAAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIALAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_13.setTransform(-14.65,23.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgEAtQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAAAIABhVQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIALAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAABUIgBACIgCABg");
	this.shape_14.setTransform(-17.925,23.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgWAdQgFgFAAgIQAAgHAEgFQAEgEAHgDQAIgCAKgBIAGAAIABAAIABgCIAAgCQAAgGgEgDQgDgDgFAAIgHACQgEACgCAEIgBABIgCAAIgKgDIgBAAIABgCQADgHAHgDQAHgEAJAAQAKAAAFACQAGADADAEQACAGAAAFIAAApIAAACIgCABIgKAAIgBgBIgBgCIAAgDQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAgBABQgEADgEACQgEACgGAAQgKAAgFgEgAAHACIgHAAIgGADIgEAEQgCACAAADQAAAEADACQADACAFAAIAFgBIAFgCIADgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBAAAAAAg");
	this.shape_15.setTransform(-23.575,25.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgSAeQgFgCgCgEQgCgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAoQgBAEADADQADADAEAAQAEAAADgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIAAgBIgCABQgFAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_16.setTransform(-30.45,25.125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAXAxQgHgEgFgGQAAgBgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgEABIgFAAQgLAAgJgGQgJgFgFgKQgFgKAAgOQAAgOAFgLQAFgKAJgGQAJgEALAAQAMAAAJAEQAJAGAFAKQAFALAAAOQAAANgEAIQgEAKgHAFIAAABIABAEIAGADIAGABIABABIABABIAAAIIgBADIgDABQgHAAgGgEgAgPgfQgGAIAAASQAAAQAGAHQAFAIAKAAQALAAAFgIQAGgHAAgQQAAgSgGgIQgFgIgLAAQgKAAgFAIg");
	this.shape_17.setTransform(-39.225,24.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAPAtIgCgBIAAgBIAAgqQAAgEgDgCQgCgDgFAAIgEABIgFADIgGAEIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAgIAAABIABgBIAIgGIAFgCIAHgBQAKAAAFAEQAEAGAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_18.setTransform(-51.425,23.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAGArQgHAAgEgFQgFgDABgIIAAgjQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgHQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIACgTQAAAAAAgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAKAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIAAASQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAOAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgOAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACADAEAAIAHAAIABAAIABABIgBAHQAAAAAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgFAAIgEABg");
	this.shape_19.setTransform(-56.95,24);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgFAtIgBgBIgBgBIAAg7QAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAABAAAAIAAA6IAAACIgCABgAgFgbIgBAAIgBgCIAAgNQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_20.setTransform(-61.1,23.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAVAtQgBAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAAAIgQg6IgBgBIAAABIgQA5QAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAIgMAAQAAAAgBgBQgBAAAAAAQAAAAgBgBQAAAAAAAAIgYhUIAAgCIACAAIAMAAIACAAIABABIARA7IABACIABgBIAQg8IABgBIACAAIAKAAIACAAIABABIARA8IABABIAAgBIARg8IABgBIACAAIAJAAIACAAIABACIgZBTQAAABAAAAQgBABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_21.setTransform(-68.1125,23.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgQAgIgCAAIAAgCIAAg6QAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAAIIABABIABgBIAFgFIAGgEIAGgCQABAAABABQABAAAAAAQABAAAAABQAAAAABAAIAAAMQgBAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAIgEgBIgDAAIgGABIgEACIgCAEQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAABIAAAjQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAg");
	this.shape_22.setTransform(50.25,11);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgOAdQgIgEgEgHQgEgHAAgKQAAgKAEgHQAFgIAHgEQAHgEAIAAQAJAAAHAEQAGAEAEAHQAEAIAAAJIAAADIgCAAIgpAAIgBABIgBABQAAAFADAEQACAEAEACQAEACAEABQAFgBAEgCQAEgCADgEIABgBIABABIAIACQAAABAAAAQABAAAAABQAAAAgBAAQAAABAAAAIgIAIQgEAEgFABIgLABQgIAAgHgEgAgGgUQgEACgCAFQgCADAAAGIAcAAIABgBIABgCIgCgGQgCgFgDgCQgDgCgFAAQgEAAgDACg");
	this.shape_23.setTransform(43.825,11.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAPAsIgCAAIAAgCIAAgpQAAgDgDgDQgCgDgFAAIgEABIgFADIgGAEIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgLAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhTQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIALAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAeIAAABIABAAIAIgFIAFgEIAHgBQAKAAAFAGQAEAFAAAIIAAArQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_24.setTransform(36.625,9.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgNAdQgHgEgEgIQgEgHAAgKQAAgIAEgIQAEgIAHgEQAHgEAIAAQAHAAAFADQAGACADAEIAFAIQABABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgKABIgCgBIgDgFIgEgDQgCgCgEABQgDgBgEADQgEADgCAFQgCAFAAAGQAAAHADAGQACAEADAEQAEACAEAAQAGAAADgDQAEgDADgFIAAAAIACAAIAHACQABAAAAAAQAAAAAAAAQAAABAAAAQAAABAAAAIgEAGQgCADgDACQgDADgFACQgEABgGAAQgIAAgHgEg");
	this.shape_25.setTransform(29.8083,11.05);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgSAeQgEgCgCgEQgDgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAKAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAoQAAAEADADQADADAEAAQAEAAADgCIAHgGIAAgqQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAA6QAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgMAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgGIgBgBIAAABQgGAFgFACQgEACgFAAQgGAAgEgCg");
	this.shape_26.setTransform(22.7,11.125);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgQAdQgGgEgFgIQgDgHAAgKQAAgIADgIQAFgIAGgEQAIgEAIAAQAJAAAHAEQAIAFADAHQAFAIAAAIQAAAKgFAHQgDAIgIAEQgHAEgJAAQgIAAgIgEgAgIgTQgDADgCAFQgCAFAAAGQAAAHACAGQACAFADACQAEACAEABQAFgBADgCQAEgCACgFQABgGABgHQgBgGgBgFQgCgFgEgDQgDgDgFABQgEgBgEADg");
	this.shape_27.setTransform(15.55,11.05);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgGAsQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgdhTIAAgCIACgBIAOAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAABABIAUA/QAAAAAAABQAAAAABAAQAAAAAAAAQAAgBAAAAIAWg/QAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIALAAIACABIAAACIgeBTQAAABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_28.setTransform(7.7,9.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAPAgIgCAAIAAgCIAAgoQAAgEgDgDQgCgDgFAAIgFABIgEADIgGAEIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAg6QAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIALAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAAHIAAABIABgBIAHgEQADgDADgBQADgBAEgBQAJABAFAFQAFAFAAAIIAAArQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_29.setTransform(-4.225,11);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgQAdQgGgEgFgIQgDgHAAgKQAAgIADgIQAFgIAGgEQAIgEAIAAQAJAAAHAEQAIAFADAHQAFAIAAAIQAAAKgFAHQgDAIgIAEQgHAEgJAAQgIAAgIgEgAgIgTQgDADgCAFQgCAFAAAGQAAAHACAGQACAFADACQAEACAEABQAFgBADgCQAEgCACgFQABgGAAgHQAAgGgBgFQgCgFgEgDQgDgDgFABQgEgBgEADg");
	this.shape_30.setTransform(-11.45,11.05);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgEAsIgCAAIgBgCIAAg6QAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIALAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAA6IAAACIgCAAgAgFgbIgBgBIgBgCIAAgLQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIALAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAALQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_31.setTransform(-16.75,9.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAGAqQgHAAgEgDQgEgEgBgHIAAgjQAAgBAAAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgIQAAAAAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIABgSQAAAAABgBQAAAAAAAAQAAAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAASQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAIQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgOAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACACQACABAEAAIAHAAIACABIAAABIAAAHQAAAAgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIgEAAIgFAAg");
	this.shape_32.setTransform(-20,10);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgWAcQgFgEAAgIQAAgHAEgFQAEgEAHgCQAIgDAKAAIAGgBIABgBIABgBIAAgCQAAgGgEgDQgDgDgFABIgHABQgEACgCAEIgBABIgCAAIgKgDIgBAAIABgCQADgHAHgDQAHgEAJAAQAKAAAFADQAGACADAFQACAEAAAHIAAApIAAACIgCAAIgKAAIgBgBIgBgCIAAgEQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAgBAAQgEAEgEACQgEACgGAAQgKAAgFgFgAAHABIgHACIgGACIgEADQgCADAAADQAAAEADACQADACAFABIAFgBIAFgDIADgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQAAAAgBAAQAAgBAAAAQgBAAAAAAg");
	this.shape_33.setTransform(-26.575,11.05);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgNAdQgHgEgEgIQgEgHAAgKQAAgIAEgIQAEgIAHgEQAHgEAIAAQAHAAAFADQAGACADAEIAFAIQABABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgKABIgCgBIgDgFIgEgDQgCgCgEABQgDgBgEADQgEADgCAFQgCAFAAAGQAAAHADAGQACAEADAEQAEACAEAAQAGAAADgDQAEgDADgFIAAAAIACAAIAHACQABAAAAAAQAAAAAAAAQAAABAAAAQAAABAAAAIgEAGQgCADgDACQgDADgFACQgEABgGAAQgIAAgHgEg");
	this.shape_34.setTransform(-32.9417,11.05);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgWAcQgFgEAAgIQAAgHAEgFQAEgEAHgCQAIgDAKAAIAGgBIABgBIABgBIAAgCQAAgGgEgDQgDgDgFABIgHABQgEACgCAEIgBABIgCAAIgKgDIgBAAIABgCQADgHAHgDQAHgEAJAAQAKAAAFADQAGACADAFQACAEAAAHIAAApIAAACIgCAAIgKAAIgBgBIgBgCIAAgEQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAgBAAQgEAEgEACQgEACgGAAQgKAAgFgFgAAHABIgHACIgGACIgEADQgCADAAADQAAAEADACQADACAFABIAFgBIAFgDIADgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAg");
	this.shape_35.setTransform(-40.425,11.05);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgFAsQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgdhTIAAgCIABgBIAPAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAVA/QAAAAAAABQAAAAABAAQAAAAAAAAQAAgBABAAIAUg/QABgBAAAAQAAgBAAAAQABAAAAAAQABgBAAAAIALAAIACABIAAACIgeBTQAAABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_36.setTransform(-47.8,9.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgGAeQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgOQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIANAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAANQAAABAAAAQgBABAAAAQAAAAgBAAQgBAAAAAAgAgGgNQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgNQAAAAAAgBQAAAAABAAQAAAAAAAAQAAgBABAAIANAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIAAANQAAABAAAAQgBABAAAAQAAAAgBAAQgBAAAAAAg");
	this.shape_37.setTransform(40.325,-2.85);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgQAeQgIgEgDgGIAAgBIAAgBIAIgEIABgBIABABIAFAFIAFADIAHABIAHgBQADgBACgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgCgCgFgBIgMgDQgIgCgFgDQgEgFAAgHQAAgFADgFQADgFAGgCQAGgDAHAAQAJAAAGADQAHAEADAEIAAACIAAABIgIAEIgBAAIgBgBIgGgFQgEgCgFAAQgFAAgDACQgDACAAAEIABADIAHAEIANADQAJADAEADQAEAFAAAGQAAAHgEAEQgDAEgGADQgGACgJAAQgJAAgHgDg");
	this.shape_38.setTransform(35.35,-2.95);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgSAeQgEgCgCgEQgDgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAKAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAoQAAAEADADQADADAEAAQAEAAADgCIAHgGIAAgqQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgMAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIgBgBIAAABQgGAFgFACQgEACgFAAQgGAAgEgCg");
	this.shape_39.setTransform(28.55,-2.875);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAPAhIgCgBIAAgBIAAgpQAAgEgDgDQgCgDgFAAIgFABIgEADIgGAFIAAApQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg7QAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAGIAAABIABAAIAHgGQADgCADgBQADgBAEAAQAJgBAFAGQAFAFAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_40.setTransform(21.375,-3);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgPAdQgIgEgDgHQgFgIAAgJQAAgJAFgIQADgHAIgEQAHgFAIAAQAJAAAIAFQAGAEAFAHQADAIAAAJQAAAJgDAIQgFAHgGAEQgIAEgJAAQgIAAgHgEgAgHgTQgEADgCAFQgCAFAAAGQAAAIACAEQACAFAEADQADADAEgBQAFABAEgDQADgDACgFQABgEAAgIQAAgGgBgFQgCgFgDgDQgEgCgFgBQgEABgDACg");
	this.shape_41.setTransform(14.15,-2.95);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AggAtIgCgBIAAgBIAAhVIAAgBIACAAIAfAAQAQgBAJAHQAJAFAAAMQAAAGgEAFQgDAFgJAEIAAAAIAAAAQAJACAFAFQAEAFAAAIQAAANgJAFQgJAHgRAAgAgRAIIAAAWQAAABAAAAQABABAAAAQAAAAAAAAQABAAAAAAIAOAAQAJAAAEgDQAFgEAAgGQAAgFgDgDQgCgDgEgBQgEgCgEAAIgOAAQgBAAAAABQgBAAAAAAQAAAAgBABQAAAAAAABgAgRgeIAAAWQAAABAAAAQABABAAAAQAAAAAAAAQABAAAAAAIAPAAIAFgBIAFgBQADgCABgDQABgCAAgDQAAgHgEgDQgFgDgHgBIgNAAQgBAAAAABQgBAAAAAAQAAAAgBABQAAAAAAAAg");
	this.shape_42.setTransform(6.425,-4.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAGArQgHAAgEgFQgFgDABgIIAAgjQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgHQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIACgTQAAAAAAgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAKAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIAAASQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAOAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgOAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACACAEABIAHAAIABAAIABABIgBAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgFAAIgEABg");
	this.shape_43.setTransform(-3.4,-4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgQAeQgIgEgDgGIAAgBIAAgBIAIgEIABgBIABABIAFAFIAFADIAHABIAIgBQADgBABgCQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQgCgCgFgBIgMgDQgIgCgFgDQgEgFAAgHQAAgFADgFQADgFAGgCQAGgDAHAAQAJAAAHADQAGAEADAEIAAACIAAABIgIAEIgBAAIgBgBIgGgFQgEgCgFAAQgFAAgDACQgEACABAEIABADIAHAEIANADQAJADAEADQAEAFAAAGQAAAHgDAEQgEAEgGADQgGACgJAAQgJAAgHgDg");
	this.shape_44.setTransform(-9.4,-2.95);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgSAeQgEgCgCgEQgDgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAoQABAEACADQACADAFAAQADAAAEgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgMAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIAAgBIgBABQgGAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_45.setTransform(-16.2,-2.875);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgaAnQgIgEAAgIQAAgEADgDQADgDAFgCQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAgBAAQgDgBgBgCQgCgCAAgDQAAgBAAAAQAAgBAAgBQAAAAABAAQAAgBAAAAIAEgDIAGgDIAAAAIAAgBQgGgDgCgEQgDgEAAgFQAAgJAHgGQAIgFAOAAQAFAAAFABQAFACADACIABABIACgBIADgDIAFgDIAEAAIABAAIABACIAAAHIgBACIgBAAIgEAAIgCAAQgBABgBAAQAAAAgBABQAAAAAAAAQAAABAAAAIABADIABAEQAAAFgDAEQgDAFgHADQgGACgIAAIgJABIgEABIgBACQAAAAAAAAQAAABAAAAQAAAAABAAQAAABABAAIAGABIAQABQAMABAFAEQAFAFAAAHQAAAJgIAGQgJAFgPAAQgQAAgJgEgAgQASIgDADQgBAAAAABQAAAAgBABQAAAAAAABQAAABAAAAQAAADACADQACACAFABIAMABQAIAAAFgCQAFgDAAgEQAAgEgDgCQgCgCgGAAIgSgBIgFABgAgMgeQgDADAAAGQAAAFADADQAEADAHAAQAGAAADgDQADgDAAgFQAAgGgDgDQgDgDgGAAQgHAAgEADg");
	this.shape_46.setTransform(-23.275,-1.975);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgSAeQgFgCgBgEQgDgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAoQABAEACADQACADAFAAQADAAAEgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgMAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIAAgBIgBABQgGAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_47.setTransform(-30.7,-2.875);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AAZAtQAAAAgBgBQAAAAAAAAQgBAAAAAAQAAgBAAAAIgHgUIAAgBIgBAAIgfAAIgBABIgHAUIgBABIgCABIgLAAIgCgBIAAgDIAfhTIABgBIACAAIAOAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAABIAeBSIAAADIgBABgAgBgYIgMAfQAAAAAAABQAAAAAAAAQAAABABAAQAAAAAAAAIAWAAQABAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIgLgfIAAgBIgBABg");
	this.shape_48.setTransform(-38.275,-4.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.6,-11,153.3,44);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AANAdIgBAAIgBgCIAAgkQAAgEgCgCQgCgDgFAAIgEABQgCABgCACIgFAEIAAAlQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAg0QAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIALAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFIAAABIABAAIAGgFIAGgDQADgBADAAQAIAAAFAFQAEAEAAAIIAAAmQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(40.05,14.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAOAcQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIgKgfIgBgCIAAACIgKAgIgBABIgBAAIgIAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIgRg0IAAgBIACgBIAKAAIABAAIABACIALAhIABABIABgBIAKghIABgCIABAAIAHAAIABAAIABACIALAhIAAABIABgBIALghIAAgCIACAAIAHAAIABABIAAABIgRA1IgBABIgBAAg");
	this.shape_1.setTransform(32.8875,14.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgOAaQgHgEgDgGQgEgHAAgJQAAgIAEgGQAEgHAHgEQAFgEAIAAQAJAAAGAEQAGAEADAHQAFAHAAAHQAAAJgFAHQgDAGgHAEQgFAEgJAAQgIAAgGgEgAgHgRQgDACgCAFQgBAFAAAFQAAAHABAEQACAFADACQAEACADAAQAEAAADgCQAEgCACgFQABgEAAgHQAAgFgBgFQgCgFgEgCQgDgCgEAAQgDAAgEACg");
	this.shape_2.setTransform(25.2,14.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgeAoQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhLIABgCIABAAIAFAAIAGAAIAGAAIAFAAQAOABAJAEQAJAFAEAIQAFAKAAALQAAAMgFAKQgEAJgKAEQgJAFgOAAgAgQgaIAAA1QAAAAAAABQAAAAAAAAQABAAAAAAQAAABABAAIACAAQAKAAAGgDQAGgDADgHQADgGAAgKQAAgJgDgHQgDgGgGgDQgFgDgKAAIgEAAQAAAAAAABQgBAAAAAAQAAAAAAAAQAAABAAAAg");
	this.shape_3.setTransform(17.8,13.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgWAlQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgHIABgBIACAAIAHAAIAEgBIADgDIACgEIgBgDIgUgzIAAgBIABgBIAMAAIABAAIABACIAMAjIABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIANgjIABgCIABAAIAIAAIABABIAAABIgWA4IgEAJIgEAEIgGACIgIABg");
	this.shape_4.setTransform(7.175,15.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgNAaQgGgEgEgGQgEgHAAgIQAAgJAEgGQAEgHAGgEQAHgEAHAAQAIAAAGAEQAGAEADAGQAEAHAAAIIAAACIgCABIglAAIgBAAIAAACQAAAEACAEQACADADACQAEACADAAQAFAAADgCQAEgCADgEIABAAIABAAIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQgBAAAAABQgDAFgEACQgEADgEACIgKABQgHAAgHgEgAgFgSQgEADgBADQgCAEAAAEIAYAAIACAAIAAgCQAAgDgBgDIgFgGQgDgCgEAAQgDAAgDACg");
	this.shape_5.setTransform(0.825,14.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AANAdIgBAAIgBgCIAAgkQAAgEgCgCQgDgDgEAAIgDABQgDABgCACIgFAEIAAAlQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAg0QAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIALAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFIAAABIABAAIAGgFIAFgDQADgBAEAAQAIAAAFAFQAEAEAAAIIAAAmQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-5.6,14.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgOAaQgHgEgDgGQgEgHAAgJQAAgIAEgGQAEgHAHgEQAFgEAIAAQAJAAAGAEQAGAEADAHQAFAHAAAHQAAAJgFAHQgDAGgHAEQgFAEgJAAQgIAAgGgEgAgHgRQgDACgCAFQgBAFAAAFQAAAHABAEQACAFADACQADACAEAAQAEAAADgCQAEgCACgFQABgEAAgHQAAgFgBgFQgCgFgEgCQgDgCgEAAQgEAAgDACg");
	this.shape_7.setTransform(-12.15,14.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAcAoIgBAAIgBgCIAAg4IAAAAIgBAAIgVA5QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgHAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAgBAAIgUg3IAAgCIgBACIAAA3IAAABIgBAAIgKAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAhMQAAAAAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIASAAIACAAIABABIASAzIAAAAIABAAIASgyQABAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIATAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAABMQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_8.setTransform(-19.85,13.05);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgOAaQgHgEgDgGQgEgHABgJQgBgIAEgGQAEgHAGgEQAHgEAHAAQAJAAAGAEQAGAEAEAHQADAHAAAHQAAAJgDAHQgEAGgHAEQgFAEgJAAQgHAAgHgEgAgHgRQgDACgCAFQgCAFAAAFQAAAHACAEQACAFADACQAEACADAAQAEAAAEgCQADgCABgFQACgEAAgHQAAgFgCgFQgCgFgCgCQgEgCgEAAQgDAAgEACg");
	this.shape_9.setTransform(-31.65,14.175);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAWAoIgCAAIgBgBIgkg0IgBAAIAAAAIAAA0QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAhNQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIALAAIABAAIACABIAhAyIACAAIABgBIAAgxQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAABNIAAABIgBAAg");
	this.shape_10.setTransform(-39.15,13.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgGAQIgBgBIAAgBIAFgMQAAAAABgBQAAAAAAgBQAAAAgBAAQAAAAAAAAIgCAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgMQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAALIAAACIgJAOIgBACIgCAAg");
	this.shape_11.setTransform(67.85,4.475);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAFAmQgGAAgEgDQgEgEAAgGIAAggQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAIAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIABgRQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAIAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAARIABABIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgNAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAAcQAAAEACACQACABAEAAIAGAAIABABIAAABIAAAFQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgEAAIgEAAg");
	this.shape_12.setTransform(65.325,0.625);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgPAaQgGgDgDgFIAAgBIAAgBIAHgEIABAAIABABIAEAEIAFADIAGABIAGgBIAFgDQAAAAAAgBQABAAAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAgBgBAAIgGgDIgKgDQgIgCgEgDQgEgDAAgGQAAgGADgEQADgEAFgCQAFgDAHAAQAIAAAFADQAGADADAFIABABIgBABIgHADIgBAAIgBAAQgCgDgDgCQgEgCgFAAQgDAAgDACQgDACAAADIABADIAGADIALAEQAJACADADQAEAEAAAGQAAAGgDAEQgDAEgGACQgGACgHAAQgIAAgHgEg");
	this.shape_13.setTransform(59.925,1.575);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgNAaQgGgEgEgGQgEgHAAgIQAAgJAEgGQAEgHAGgEQAHgEAHAAQAIAAAGAEQAGAEADAGQAEAHAAAIIAAACIgCABIglAAIgBAAIAAACQAAAEACAEQACADADACQAEACADAAQAFAAADgCQAEgCADgEIABAAIABAAIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQgBAAAAABQgDAFgEACQgEADgEACIgKABQgHAAgHgEgAgFgSQgEADgBADQgCAEAAAEIAYAAIACAAIAAgCQAAgDgBgDIgFgGQgDgCgEAAQgDAAgDACg");
	this.shape_14.setTransform(53.825,1.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgPAdIgCAAIAAgCIAAg0QABgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAGIAAABIABAAIAEgGIAGgDIAFgBQABAAABAAQABAAABAAQAAABAAAAQABAAAAABIAAAKQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgEAAIgCAAIgFAAIgEADIgCADIgBAEIAAAgQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_15.setTransform(49,1.525);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgNAaQgGgEgEgGQgEgHAAgIQAAgJAEgGQAEgHAGgEQAHgEAHAAQAIAAAGAEQAGAEADAGQAEAHAAAIIAAACIgCABIglAAIgBAAIAAACQAAAEACAEQACADADACQAEACADAAQAFAAADgCQAEgCADgEIABAAIABAAIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAgBABQgDAFgEACQgEADgEACIgKABQgHAAgHgEgAgFgSQgEADgBADQgCAEAAAEIAYAAIACAAIAAgCQAAgDgBgDIgFgGQgDgCgEAAQgDAAgDACg");
	this.shape_16.setTransform(43.175,1.575);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAFAmQgGAAgEgDQgEgEAAgGIAAggQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAIAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIABgRQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAIAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAARIABABIAMAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAIAAAHQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAAAIgNAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAcQAAAEACACQACABAEAAIAGAAIABABIAAABIAAAFQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgEAAIgEAAg");
	this.shape_17.setTransform(38.725,0.625);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AANAdIgBAAIgBgCIAAgkQAAgEgCgCQgDgDgEAAIgEABQgCABgCACIgFAEIAAAlQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAg0QAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIALAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFIAAABIABAAIAGgFIAGgDQADgBADAAQAIAAAFAFQAEAEAAAIIAAAmQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_18.setTransform(33.2,1.525);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgFAoIgBAAIgBgCIAAhMQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAABMIAAACIgDAAg");
	this.shape_19.setTransform(28.1,0.45);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgOAaQgGgEgEgGQgDgHgBgJQABgIADgGQAEgHAHgEQAFgEAIAAQAJAAAGAEQAGAEADAHQAEAHABAHQgBAJgEAHQgDAGgHAEQgFAEgJAAQgHAAgHgEgAgHgRQgDACgBAFQgCAFAAAFQAAAHACAEQABAFADACQAEACADAAQAEAAADgCQAEgCACgFQABgEAAgHQAAgFgBgFQgDgFgDgCQgDgCgEAAQgDAAgEACg");
	this.shape_20.setTransform(19.7,1.575);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAVAoIgBAAIgBgBIgkg0IgBAAIAAAAIAAA0QAAAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgJAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIAAhNQAAAAABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAKAAIACAAIABABIAiAyIABAAIAAgBIAAgxQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAABNIgBABIgCAAg");
	this.shape_21.setTransform(12.2,0.45);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgGAQIgBgBIAAgBIAFgMQAAAAABgBQAAAAAAgBQAAAAgBAAQAAAAgBAAIgBAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgMQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAALIAAACIgJAOIgBACIgCAAg");
	this.shape_22.setTransform(2.35,4.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgPAaQgGgDgDgFIAAgBIAAgBIAHgEIABAAIABABIAEAEIAFADIAGABIAGgBIAFgDQAAAAAAgBQABAAAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAgBgBAAIgGgDIgKgDQgIgCgEgDQgEgDAAgGQAAgGADgEQADgEAFgCQAFgDAHAAQAIAAAFADQAGADADAFIABABIgBABIgHADIgBAAIgBAAQgCgDgDgCQgEgCgFAAQgDAAgDACQgDACAAADIABADIAGADIALAEQAJACADADQAEAEAAAGQAAAGgDAEQgDAEgGACQgGACgHAAQgIAAgHgEg");
	this.shape_23.setTransform(-2.075,1.575);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAFAmQgGAAgEgDQgEgEAAgGIAAggQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAIAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIABgRQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAIAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAARIABABIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgNAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAAcQAAAEACACQACABAEAAIAGAAIABABIAAABIAAAFQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgEAAIgEAAg");
	this.shape_24.setTransform(-6.675,0.625);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AANAdIgCAAIAAgCIAAgkQAAgEgCgCQgDgDgEAAIgDABQgDABgCACIgEAEIAAAlQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAg0QAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFIABABIAAAAIAGgFIAFgDQADgBAEAAQAIAAAEAFQAGAEAAAIIAAAmQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_25.setTransform(-12.2,1.525);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgNAaQgGgEgEgGQgEgHAAgIQAAgJAEgGQAEgHAGgEQAHgEAHAAQAIAAAGAEQAGAEADAGQAEAHAAAIIAAACIgCABIglAAIgBAAIAAACQAAAEACAEQACADADACQAEACADAAQAFAAADgCQAEgCADgEIABAAIABAAIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAgBABQgDAFgEACQgEADgEACIgKABQgHAAgHgEgAgFgSQgEADgBADQgCAEAAAEIAYAAIACAAIAAgCQAAgDgBgDIgFgGQgDgCgEAAQgDAAgDACg");
	this.shape_26.setTransform(-18.775,1.575);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAfAdIgCAAIAAgCIAAgkQAAgEgCgCQgCgDgFAAIgEABIgFADIgDACIgBACIAAABIAAAkQAAAAAAABQgBAAAAABQAAAAAAAAQgBAAAAAAIgJAAIgCAAIAAgCIAAgkQAAgEgCgCQgCgDgFAAQgDAAgDACQgDACgEAEIAAAlQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgKAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAg0QAAgBAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIAKAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAAAFIAAABIABAAIAGgFIAGgDIAGgBQAGAAADADQAEACACAFIAAAAIABAAIAGgFQADgDAEgBQADgBADAAQAIAAAEAFQAFAEAAAIIAAAmQAAAAAAABQgBAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_27.setTransform(-26.475,1.525);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgWAlQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgHIABgBIACAAIAHAAIAEgBIADgDIACgEIgBgDIgUgzIAAgBIABgBIAMAAIABAAIABACIAMAjIABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIANgjIABgCIABAAIAIAAIABABIAAABIgWA4IgEAJIgEAEIgGACIgIABg");
	this.shape_28.setTransform(-34.425,2.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgUAZQgEgEAAgHQAAgGADgEQAEgEAGgCQAHgDAJAAIAFAAIABgBIABgBIAAgCQAAgFgDgDQgDgCgFAAIgGABQgDACgCAEIgBABIgBAAIgKgDIAAAAIAAgCQADgGAGgDQAHgEAIAAQAIAAAFADQAGACACAEQACAEAAAGIAAAlIAAABIgBABIgKAAIgBgBIgBgCIAAgDQAAgBAAAAQAAAAgBAAQAAAAAAAAQAAAAgBABQgEADgEACQgDACgGAAQgIAAgFgFgAAGABIgGABIgFACIgEAEQgBAAAAABQAAAAAAABQgBAAAAABQAAABAAAAQAAAEADACQADACAEAAIAFgBIAEgCIADgDQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgHQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_29.setTransform(-41.075,1.575);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgcAoIgCAAIAAgCIAAhMQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAdAAQAJAAAIACQAGADAEAFQAEAGABAJQAAAHgEAFQgEAFgHACQgGADgJAAIgQAAIgBACIAAAcQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgPgaIAAAWQAAAAABABQAAAAAAABQAAAAAAAAQABAAAAAAIANAAQAHAAAEgDQAEgEAAgGQAAgEgBgDQgDgDgDgCIgIgBIgMAAQgBAAAAABQgBAAAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_30.setTransform(-47.65,0.45);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgOAaQgHgEgDgGQgDgHAAgJQAAgIADgGQAEgHAGgEQAHgEAHAAQAIAAAHAEQAGAEAEAHQADAHAAAHQAAAJgDAHQgEAGgGAEQgHAEgIAAQgIAAgGgEgAgHgRQgDACgBAFQgCAFgBAFQABAHACAEQABAFADACQADACAEAAQAFAAADgCQADgCABgFQACgEAAgHQAAgFgCgFQgCgFgCgCQgDgCgFAAQgEAAgDACg");
	this.shape_31.setTransform(-58.45,1.575);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAWAoIgCAAIgBgBIgkg0IgBAAIAAAAIAAA0QAAAAAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgJAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAhNQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAKAAIABAAIACABIAhAyIACAAIAAgBIAAgxQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAABNIgBABIgBAAg");
	this.shape_32.setTransform(-65.9,0.45);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgPAaQgGgDgDgFIAAgBIAAgBIAHgEIABAAIABABIAEAEIAFADIAGABIAGgBIAFgDQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAgBgBAAIgGgDIgKgDQgIgCgEgDQgEgDAAgGQAAgGADgEQADgEAFgCQAFgDAHAAQAIAAAFADQAGADADAFIABABIgBABIgHADIgBAAIgBAAQgCgDgDgCQgEgCgFAAQgDAAgDACQgDACAAADIABADIAGADIALAEQAJACADADQAEAEAAAGQAAAGgDAEQgDAEgGACQgGACgHAAQgIAAgHgEg");
	this.shape_33.setTransform(29.875,-10.975);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AANAoIgCgBIAAgBIAAglQAAgDgCgDQgCgCgFAAIgDABQgDAAgCADIgEADIAAAmQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhLQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAcIABAAIAAAAIAHgFIAFgDIAGgBQAIABAFAEQAEAFABAIIAAAlQAAABgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_34.setTransform(23.8,-12.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAFAmQgGAAgEgDQgEgEAAgGIAAggQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIAIAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIABgRQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAIAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAARIABABIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgNAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAAcQAAAEACACQACABAEAAIAGAAIABABIAAABIAAAFQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgEAAIgEAAg");
	this.shape_35.setTransform(18.725,-11.925);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AANAdIgBAAIgBgCIAAgkQAAgEgCgCQgCgDgFAAIgEABQgCABgCACIgFAEIAAAlQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgKAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAg0QAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFIAAABIABAAIAGgFIAGgDQADgBADAAQAIAAAFAFQAEAEABAIIAAAmQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_36.setTransform(13.25,-11.025);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgOAaQgHgEgDgGQgEgHABgJQgBgIAEgGQAEgHAGgEQAHgEAHAAQAJAAAGAEQAGAEAEAHQADAHAAAHQAAAJgDAHQgEAGgGAEQgHAEgIAAQgHAAgHgEgAgHgRQgDACgBAFQgDAFAAAFQAAAHADAEQABAFADACQAEACADAAQAFAAADgCQADgCABgFQACgEAAgHQAAgFgCgFQgCgFgCgCQgDgCgFAAQgDAAgEACg");
	this.shape_37.setTransform(6.7,-10.975);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AAcAoIgCgBIAAgBIAAg4IgBAAIAAAAIgUA4QgBABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgHAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIgVg3IgBgBIAAABIAAA3IgBABIgBABIgJAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhLQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIASAAIABAAIABACIATAxIAAABIABgBIATgxQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIATAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAABKQAAABAAABQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_38.setTransform(-1,-12.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgaAoIgCAAIAAgBIAAgIIAAgBIABgBIAEgDIAUgUIAIgHIAEgFIADgFIABgFQAAgEgCgCIgFgFQgDgBgDAAIgFABIgGAEIgFAGIgBABIgCAAIgIgFIgBgBIAAgCQAGgIAIgEQAHgDAHgBQAIABAHACQAGADAEAFQAEAGAAAHQAAAEgCAFQgBADgEAEIgJAIIgVASIAAABIACABIAhAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAKIAAABIgCAAg");
	this.shape_39.setTransform(-12.7,-12.15);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgUAoQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgJQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAMAAIACgBIAAgxQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgMAEQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgGIAAgBIABgBIARgJIACgBIABAAIAHAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAABAIABABIAMAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIAAAJIgBABIgBABg");
	this.shape_40.setTransform(-19.9,-12.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgCAZQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgSIAAgJIAJAAIgJAAIAAgSIAAgCIABAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIAAATIATAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAGQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAIgSAAIAAgJIAAAJIgJAAIAJAAIAAATQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAgAgXAFIgBAAIgBgCIAAgFQABgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIATAAIAAAJg");
	this.shape_41.setTransform(-29.85,-12.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.9,-18.2,143.9,39.599999999999994);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#47C434").s().p("AgDAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgUIANAAIAAAVQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAAAgAAHAHIAAgNIgNAAIAAgUIABgCIACgBIAIAAQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAAAIAAAVIAVAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAgAgGAHIAAgNIANAAIAAANgAgaAHIgCgBIgBgBIAAgIQAAgBAAAAQABgBAAAAQAAAAAAgBQABAAAAAAIAVAAIAAANgAgGgGg");
	this.shape.setTransform(-0.575,16.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAIAyQgJAAgFgFQgFgEAAgJIAAgpQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgJQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIALAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIACgVQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIALAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAVIACABIAPAAQABAAAAAAQABABAAAAQAAAAAAAAQABABAAAAIAAAJQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgPAAQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAAkQAAAGADACQACACAEAAIAIAAIACAAIABACIAAAHQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAIgFAAIgGABg");
	this.shape_1.setTransform(61.4,32.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgFA0IgCgBIgBgBIAAhFQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIANAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAABEIAAACIgEABgAgGgfIgCgBIAAgDIAAgNQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAABIAAANQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_2.setTransform(57.25,32.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AARAmIgBgBIgBgCIAAgvQAAgFgEgDQgCgDgGAAIgFABIgGADIgGAFIAAAxQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIANAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGIAHgDQAEgCAEAAQALAAAGAGQAGAGAAAKIAAAyQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_3.setTransform(51.9,33.725);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgXAwQgIgFgEgJQgEgJAAgNIAAg9QAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAQAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABAQAAAMAGAFQAFAGAJAAQAHAAAFgDQAFgCACgFQADgFAAgJIAAg/QAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIANAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAA/QAAAOgFAJQgEAIgJAEQgJAEgNAAQgOAAgJgFg");
	this.shape_4.setTransform(42.625,32.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgdAwQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgIIAAgCIAEgBIAJAAQADAAACgBIAEgEIACgFQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBgBIgbhAIABgDIACgBIAOAAIACABIABACIAQAtIABABQABAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIARguIABgBIACgBIAKAAIABABQAAAAABAAQAAABAAAAQAAAAAAAAQgBABAAAAIgdBJIgGAKQgBAEgEADQgDACgFABIgKAAg");
	this.shape_5.setTransform(30.625,34.95);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_6.setTransform(24.575,33.725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgRAiQgIgFgFgJQgFgIAAgLQAAgLAFgJQAFgJAJgFQAIgFAJABQAKgBAJAFQAHAFAFAIQAEAJAAALIAAACIgCABIgwAAIgBABIgBACQAAAFACAFQADAFAFACQAFACAEABQAGAAAEgCQAGgDADgFIABgBIACABIAIADQABAAAAABQABAAAAAAQAAAAAAABQgBAAAAAAQgFAHgEAEQgFADgGACQgGABgHAAQgJAAgJgEgAgHgYQgFAEgCAEQgCAEAAAGIAgAAIACgBIABgBQAAgEgCgFQgDgDgDgEQgEgCgFAAQgFAAgEACg");
	this.shape_7.setTransform(17.75,33.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgDAlQgDAAgCgCIgbhEIAAgCIACgBIAOAAIACABIABABIARAtQABABAAAAQAAAAABAAQAAAAAAAAQAAgBABgBIASgtIABAAIABgBIAKAAIACABIAAABIgcBFQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAg");
	this.shape_8.setTransform(10.6,33.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhiQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIguAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAALIAAAAIgCABIgfAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAIAwAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAABIAAALIgBABIgCABg");
	this.shape_9.setTransform(2.125,32.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgHA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAg5QAAAAgBgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIgMAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIACgBIALAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABgBAAAAIAAgJQAAgJAEgFQAFgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAIIAAABIgCABIgJAAQgDAAgCACQgBADAAAEIAAAHQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABABIABABIAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgNAAQAAAAgBABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAA5QAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_10.setTransform(-7.8,32.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgHA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg5QAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBgBAAIgLAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgIIABgBIABgBIALAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQABgJAEgFQAFgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAIIgBABIgBABIgJAAQgDAAgCACQgCADAAAEIAAAHQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABABIABABIAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgNAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgBABAAAAIAAA5QAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_11.setTransform(-12.95,32.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgYAvQgKgGgGgMQgGgMAAgRQAAgQAGgMQAGgMALgGQAKgHANAAQAPAAAKAHQAKAGAGAMQAGAMAAAQQAAARgGAMQgFAMgLAGQgKAHgPgBQgNABgLgHgAgSgcQgGAJAAATQAAAVAGAJQAHAIALABQANgBAGgIQAGgJAAgVQAAgTgGgJQgGgKgNAAQgLAAgHAKg");
	this.shape_12.setTransform(-21.225,32.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgVAvQgJgGgGgMQgFgMAAgQQAAgMADgKQADgKAGgHQAGgHAIgDQAHgEAJAAQAIAAAIAEQAHADAGAHQAGAHADAKQADAKAAAMQAAAQgFAMQgGAMgJAGQgKAGgMAAQgLAAgKgGgAgKghQgFAEgCAIQgCAJgBANQABANACAJQACAIAFAEQAFAEAFAAQAHAAAFgEQAEgEADgIQACgJAAgNQAAgNgCgJQgDgIgEgEQgGgEgGAAQgFAAgFAEg");
	this.shape_13.setTransform(-33.3,32.275);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgVAvQgJgGgGgMQgFgMAAgQQAAgMADgKQAEgKAFgHQAGgHAIgDQAHgEAIAAQAJAAAIAEQAHADAGAHQAGAHADAKQADAKAAAMQAAAQgGAMQgFAMgJAGQgKAGgMAAQgLAAgKgGgAgKghQgFAEgCAIQgCAJgBANQABANACAJQACAIAFAEQAEAEAGAAQAHAAAFgEQAEgEACgIQADgJAAgNQAAgNgDgJQgCgIgEgEQgGgEgGAAQgGAAgEAEg");
	this.shape_14.setTransform(-41.95,32.275);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgZA0QgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgLQAAgBAAAAQAAgBABAAQAAAAAAAAQABgBABAAIAPAAIABgBIAAhAQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgOAFQgBAAgBAAQAAAAAAAAQgBAAAAgBQAAgBAAgBIAAgIIABgBIABgBIAWgLIADgBIACgBIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABTQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAPAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAALIAAABIgCABg");
	this.shape_15.setTransform(-51.1,32.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgBA+QgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgHIAAgBIgCgBQgKABgIgEQgHgDgHgHQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAIgIIABgBIACABIAKAIQAFAEAHAAQABAAAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIAAgbIAAgDIgCgBQgLgDgHgDQgHgEgCgGQgDgGAAgHQAAgHADgHQAEgFAHgFQAHgEAJgBIABAAIABgCIAAgGIABgBIABAAIAHAAIACAAIAAACIAAAGQAAAAAAAAQAAABABAAQAAAAAAAAQAAAAABAAQAIABAGADIALAHQAAAAABABQAAAAAAABQAAAAAAABQAAAAgBAAIgHAIIgBABIgCgBIgHgFIgIgDIgBAAIgBABIAAAbQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABABIAHACQAHACAGADQAFAEADAGQADAGAAAHQAAAIgEAGQgEAGgGAEQgHAEgKAAIgBABIgBABIAAAGQAAABAAABQAAAAAAABQgBAAAAAAQgBAAgBAAgAAHALIAAAbQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAHgBAEgDQAEgEAAgFQAAgGgDgDQgEgEgIgCIgBAAIgBABgAgFgnQgIABgEAFQgDADAAAGIABAFIAEAFIAIADIADAAIAAgCIAAgYQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAgBAAIAAAAg");
	this.shape_16.setTransform(-57.9281,32.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6CC14C").s().p("AggAzIgCAAIgBgDIAAhfQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIBDAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgqAAQgBAAgBABQAAAAAAAAQgBAAAAABQAAAAAAABIAAAVQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAAMQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgdAAQgBAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAIAAAlQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_17.setTransform(71.475,3.75);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6CC14C").s().p("AggAzIgCAAIgBgDIAAhfQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIBDAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgqAAQgBAAgBABQAAAAgBAAQAAAAAAABQAAAAAAABIAAAVQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAAMQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgdAAQgBAAAAABQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAlQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_18.setTransform(63.075,3.75);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6CC14C").s().p("AgYAuQgLgGgFgMQgGgMAAgQQAAgPAGgMQAGgMAKgGQALgHANAAQAPAAAKAHQALAGAFAMQAGAMAAAPQAAARgGALQgFALgLAHQgKAGgPABQgNgBgLgGgAgPgaQgGAIAAASQAAATAFAIQAGAIAKAAQALABAGgJQAFgIAAgTQAAgSgFgIQgGgJgLAAQgKAAgFAJg");
	this.shape_19.setTransform(53.125,3.75);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6CC14C").s().p("AAUAwQgFgDgEgGQgEgIABgIQgBgHAEgHQAEgGAFgDQAHgFAHAAQAHAAAGAFQAFADAEAGQADAHAAAHQAAAIgDAIQgEAGgFADQgGAEgHABQgHgBgHgEgAAcAIQgCABgBAFIgCAJIACAKQABAEACACQACACAEAAQADAAACgCIAEgGIABgKIgBgJQgCgFgCgBQgCgDgDAAQgEAAgCADgAgjAzQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgDIBAhhIACgBIABAAIAIAAIABAAQAAAAAAAAQABAAAAABQAAAAgBAAQAAABAAAAIhBBjQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAgAguACQgGgDgDgHQgDgGgBgJQABgHADgHQADgHAHgEQAFgDAHAAQAIAAAGADQAGAEADAHQADAHABAHQgBAJgDAGQgDAHgGADQgGADgIAAQgHAAgGgDgAgngnQgCACgBAFQgBAEAAAFIABAKQACAFABACQADABADAAQAGAAADgEQABgFAAgJQABgIgDgFQgDgFgFAAQgDAAgDACg");
	this.shape_20.setTransform(54.3,-8.35);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6CC14C").s().p("AgnBTQgRgMgKgVQgKgUAAgdQAAgVAGgRQAGgSAKgMQALgNAOgHQAOgGAPAAQARAAAOAGQAOAHAKANQAKAMAGASQAGARAAAVQAAAcgKAVQgKAVgRAMQgSALgWAAQgVAAgSgLgAgRg5QgHAHgEAOQgEAPAAAWQAAAXAEANQAEAOAHAHQAHAGAKAAQALAAAHgGQAIgHADgOQAEgNAAgXQAAgWgEgPQgEgOgHgHQgHgGgLAAQgKAAgHAGg");
	this.shape_21.setTransform(38.425,-1.075);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6CC14C").s().p("AALBcQgGAAABgFIAAgkQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBgBgBAAIhIAAQgGABAAgFIAAgVIACgEIAEgIIBKhhIAFgEIAGgBIAfAAQADAAAAAEIAABoQAAAAABABQAAAAAAAAQAAABABAAQAAAAABAAIAVAAQAEAAAAAEIAAAVQAAAFgFgBIgTAAQgBAAgBABQAAAAgBAAQAAABAAAAQgBABAAABIAAAiQABAGgHAAgAACgsIgrA8QgCADAEAAIAqAAQABAAABAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAAg9IAAgEg");
	this.shape_22.setTransform(23.35,-1.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6CC14C").s().p("AgsBTQgTgLgKgVQgLgVAAgdQAAgdALgVQAKgWAUgLQATgMAYAAQAaAAATAMQATALALAWQAKAVAAAdQAAAdgKAUQgLAWgTALQgTALgaAAQgZAAgTgLgAgdgwQgJAQAAAhQAAAiAJAOQAKAPATAAQAVAAAJgPQAKgOAAgiQAAghgKgQQgKgPgUAAQgTAAgKAPg");
	this.shape_23.setTransform(-1.725,-1.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6CC14C").s().p("AgpBTQgTgMgKgVQgKgVAAgcQAAgcAKgWQALgVATgLQATgNAZAAQAUABAQAHQAQAIAKAMQAJAMADANIAAAFQAAAAAAABQAAAAgBAAQAAAAgBABQgBAAAAAAIghAFIgCgBIgCgDQgBgJgFgGQgEgHgIgEQgHgEgKAAQgLAAgJAGQgJAHgEAOQgFAOAAAWQAAAXAFAOQAFAPAJAFQAJAHALAAQAIAAAGgCQAHgCAEgEQAEgFADgEQADgGABgFIAAgHQABgBgBgBQAAgBAAAAQAAgBgBAAQAAAAgBAAIgeAAIgDgBIgBgEIAAgSQAAgDAEABIBCAAQAEAAABAAQABAAAAABQAAABABAAQAAABAAAAQAAABAAAAIAABUIgBADIgCABIgIAAIgEgBIgDgDIgHgSIgBAAIgCABIgLALQgGAFgKAEQgKAEgPgBQgYAAgSgLg");
	this.shape_24.setTransform(-21.325,-1.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6CC14C").s().p("AgsBTQgTgLgKgVQgLgVAAgdQAAgdALgVQAKgWAUgLQATgMAYAAQAaAAATAMQATALALAWQAKAVAAAdQAAAdgKAUQgLAWgTALQgTALgaAAQgZAAgTgLgAgdgwQgJAQAAAhQAAAiAJAOQAKAPATAAQAVAAAJgPQAKgOAAgiQAAghgKgQQgKgPgUAAQgTAAgKAPg");
	this.shape_25.setTransform(-40.225,-1.05);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6CC14C").s().p("AhGBcIgEgBIgBgDIAAiuQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAIBDAAQAkAAATAMQATAMAAAYQAAAOgHAKQgIAJgRAHIgBACIABABQATAFAJALQAJAJAAARQAAAZgUANQgTAMglAAgAgfATIAAAnQAAAEADABIAbAAQAPgBAIgGQAIgHAAgLQAAgHgEgGQgEgFgGgDQgHgDgJAAIgbAAQgEAAAAAFgAgfg6IAAAnQAAAEADAAIAcAAIALgBQAFgBAEgEQAEgDACgDQACgFAAgFQAAgMgIgGQgJgHgMABIgaAAQgEAAAAADg");
	this.shape_26.setTransform(-56.975,-1.05);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgHA0QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAgPQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAgBIAQAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAQQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAgAgCAWIgDAAIAAgCIgEhFIAAgBIABgBIARAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgEBFIgBACIgDAAg");
	this.shape_27.setTransform(66.2,-27.45);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgRAiQgJgFgEgJQgFgIAAgLQAAgLAFgJQAFgJAJgFQAIgEAJAAQAKAAAJAEQAHAFAFAIQAEAJAAALIAAACIgCACIgwAAIgBAAIgBACQAAAFADAFQADAFAEACQAFACAEABQAGgBAFgBQAEgDAFgFIAAgBIACABIAIADQABAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgFAGgEAEQgFADgGACQgFABgIAAQgJAAgJgEgAgHgYQgFADgBAFQgDAEAAAGIAgAAIACgBIABgBQgBgEgCgFQgCgDgDgEQgEgCgFAAQgFAAgEACg");
	this.shape_28.setTransform(60.75,-25.95);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgFA0QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhiQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABiIAAACIgDABg");
	this.shape_29.setTransform(55.325,-27.45);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgaAhQgGgGAAgJQAAgIAFgFQAFgFAIgDQAJgEAMAAIAGgBIACAAIABgBIAAgEQAAgGgEgDQgDgEgHAAQgEAAgEACQgEADgEAEIgBABIgBAAIgMgDIgBAAIABgCQADgIAJgFQAIgDAKAAQALAAAHACQAHADADAFQADAGAAAHIAAAwIAAACIgDABIgLAAIgCgBIgBgCIAAgFQAAAAAAAAQgBgBAAAAQAAAAgBABQAAAAgBAAQgEAEgGADQgFACgHAAQgKABgHgGgAAAACIgHAEQgEABgBACQgCADAAAEQAAAFAEADQADACAGAAIAGgBIAFgDIAEgFQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIAAgKQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgFAAIgIABg");
	this.shape_30.setTransform(49.45,-25.95);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgGIgBgCIABgCIAJgGIADgBIACABIAGAIQAEADAEACIALABQAJAAAGgEQAGgDAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgEgDgGQgCgGAAgGQAAgJAEgHQAFgGAJgFQAJgDAKAAQAIAAAGACQAHABAFADQAGAEADAEIABABIgBADIgKAGIgBABIgCgBQgDgEgFgCQgFgEgIAAQgJABgFADQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMAEAGAGQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAEgMAAQgJAAgIgCg");
	this.shape_31.setTransform(41.1167,-27.45);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAAAAAABQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_32.setTransform(31.175,-26.025);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgRAiQgJgFgEgJQgFgIAAgLQAAgLAFgJQAFgJAIgFQAJgEAJAAQAKAAAIAEQAJAFAEAIQAEAJAAALIAAACIgCACIgxAAIgBAAIAAACQAAAFACAFQADAFAFACQAEACAFABQAGgBAFgBQAEgDAFgFIABgBIABABIAJADQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgEAGgFAEQgFADgGACQgFABgIAAQgKAAgIgEgAgIgYQgDADgDAFQgCAEAAAGIAgAAIACgBIAAgBQAAgEgBgFQgCgDgEgEQgEgCgGAAQgEAAgFACg");
	this.shape_33.setTransform(24.35,-25.95);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAnAmIgBgBIAAgCIAAgvQAAgFgDgDQgDgDgFAAIgHABIgFADIgEADIgBACIgBADIAAAuQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgBgBIgBgCIAAgvQAAgFgDgDQgDgDgFAAQgFAAgEACQgEACgEAFIAAAxQAAAAgBABQAAABAAAAQgBAAAAABQgBAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGQADgCAEgBQAEgCAEAAQAIAAAFAEQAEADADAGIAAAAIACAAIAHgHQAEgDAFgBQAEgCAEAAQAKAAAFAGQAHAGAAAKIAAAyQAAAAgBABQAAABAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_34.setTransform(15.05,-26.025);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAoAmIgCgBIgBgCIAAgvQAAgFgDgDQgCgDgGAAIgGABIgFADIgFADIgBACIAAADIAAAuQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgCgBIAAgCIAAgvQAAgFgDgDQgDgDgFAAQgFAAgEACQgEACgFAFIAAAxQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgNAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAhEQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHIAAABIABgBIAIgGQAEgCAEgBQAEgCAFAAQAHAAAEAEQAGADABAGIABAAIABAAIAIgHQAEgDAEgBQAEgCAFAAQAKAAAGAGQAFAGAAAKIAAAyQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_35.setTransform(3.4,-26.025);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgVAjQgFgDgDgFQgDgFAAgGIAAgyQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIANAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAuQAAAGADADQADADAGAAQAEAAAEgCIAJgHIAAgxQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAABEQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgGADQgFADgGAAQgGAAgFgDg");
	this.shape_36.setTransform(-6.725,-25.875);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgGIgBgCIABgCIAJgGIADgBIACABIAGAIQAEADAEACIALABQAJAAAGgEQAGgDAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgEgDgGQgCgGAAgGQAAgJAEgHQAFgGAJgFQAJgDAKAAQAIAAAGACQAHABAFADQAGAEADAEIABABIgBADIgKAGIgBABIgCgBQgDgEgFgCQgFgEgIAAQgJABgFADQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMAEAGAGQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAEgMAAQgJAAgIgCg");
	this.shape_37.setTransform(-15.4833,-27.45);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgHA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAgBIAAg4QAAAAgBgBQAAAAAAAAQAAAAAAAAQAAgBgBAAIgLAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgIIAAgCIACAAIALAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABgBAAAAIAAgJQAAgJAEgFQAFgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAAJIgBABIgBAAIgJAAQgDABgCACQgBADAAADIAAAIQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABAAIABACIAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgNAAQAAAAgBABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAA4QAAABgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_38.setTransform(-25,-27.45);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgSAiQgJgFgEgJQgFgJAAgLQAAgLAFgIQAEgJAJgFQAIgEAKAAQALAAAIAEQAJAGAEAIQAFAJAAAKQAAAMgFAIQgFAJgIAFQgIAEgLAAQgKAAgIgEgAgJgWQgEACgDAHQgCAFAAAIQAAAIACAGQADAGAEADQAEADAFAAQAGAAAEgDQAEgDACgGQADgGgBgIQABgIgDgFQgCgHgEgCQgEgEgGAAQgFAAgEAEg");
	this.shape_39.setTransform(-31.35,-25.95);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgUAwQgHgEgEgIQgDgJAAgMQAAgMAEgIQAEgJAHgEQAHgFAJAAQAFAAAEACQAFACAEADIACABIAAgCIAAggQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAOAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABiIAAACIgDAAIgMAAIgCAAIgBgCIAAgFIAAgBIgBABIgFAEIgHADQgEACgFAAQgIAAgHgFgAgHgIQgEACgDAGQgCAFAAAKQAAAJACAGQADAGAEACQAEADAEAAQAFAAADgCQAEgCACgEQACgDAAgDIAAgfIgHgFQgEgCgEAAQgFAAgEADg");
	this.shape_40.setTransform(-43.075,-27.375);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AARAmIgBgBIgBgCIAAgvQAAgFgEgDQgCgDgGAAIgFABIgGADIgGAFIAAAxQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIANAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGIAHgDQAEgCAEAAQALAAAGAGQAGAGAAAKIAAAyQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_41.setTransform(-50.7,-26.025);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhiQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIguAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAKIAAABIgCABIgfAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAABABAAIAwAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAALIgBABIgCABg");
	this.shape_42.setTransform(-59.425,-27.45);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#48C435").ss(1,1,1).p("AAzAAIKVAAArHAAIKAAA");
	this.shape_43.setTransform(-0.025,16.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.3,-35,152.7,77.7);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_02_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_01();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AFrA4QgJgFgEgHIgBgDIABgBIAMgFIABABIAFAFQAEAEAEABQAFACAGgBQAFABAEgCQAEgBADgCQACgDAAgDQAAgEgDgCQgCgCgHgCIgRgEQgMgCgGgHQgFgFAAgJQAAgHAEgGQAEgGAIgEQAIgDALAAQAMAAAIAEQAJAFAEAGIABACIgBACIgKAEIgCAAIgBgBQgDgEgFgCQgFgDgHAAQgHAAgFADQgFACAAAFQAAADACACQACABAHACIATAGQAMACAGAHQAFAGAAAJQAAAIgFAGQgEAGgJADQgIADgLAAQgOAAgKgFgAD/A4QgKgFgFgLQgFgLAAgPIAAhFQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAABJQAAAOAGAGQAGAGAMAAQAIAAAFgDQAGgCADgHQADgFAAgKIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABIQAAAQgGAKQgFAJgLAFQgKAEgOAAQgRAAgKgFgABAA4QgJgGgGgKQgFgJAAgNQAAgNAFgKQAGgKAJgGQAKgFAMAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEgGIgFgEQgDgCgEAAQgHAAgFAEQgFADgCAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAHAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgMAAgKgFgAgsA3QgHgHAAgKQAAgJAFgHQAFgGALgEQAKgEAOAAIAHAAIACgBIAAgCIAAgDQAAgHgDgDQgEgFgHAAQgGAAgFADQgFADgDAFIgBACIgCAAIgOgEIgBgBIABgCQAEgJAJgGQAKgEAOAAQALAAAIADQAHAEAEAGQADAGAAAHIAAA4IAAADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBgBAAQAAgBAAAAQgBAAAAABQgBAAAAAAQgFAGgGACQgHADgIAAQgMAAgHgGgAgFATIgKABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAHAAQAEAAAEgBIAGgEIAEgFIABgFIAAgLQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAgAkbA4QgKgGgFgKQgFgKAAgMQAAgNAFgKQAGgKAJgGQAKgFAMAAQAMAAAKAGQAJAFAGAKQAFAKAAANQAAAMgGAKQgFAKgJAGQgKAFgMAAQgNAAgJgFgAkRgIQgEADgDAGQgCAHAAAJQAAAJACAIQADAGAEAEQAFADAHAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgJgDgHQgCgGgFgDQgFgEgGAAQgHAAgFAEgAmOA2QgMgIgGgOQgHgOAAgSQAAgSAHgOQAGgNAMgHIAEgCQAKgGAOAAQAJAAAIADIAGADIAIAEQAGAFAEAGQAEAGABAIIABACIgCABIgSABIgCAAIgBgCQgCgIgFgGQgGgGgKAAQgOAAgHAKQgIALAAAWQAAAWAHALQAIALAOAAQAKgBAHgFQAHgEAFgMQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANADIABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgEAIIgGAJQgEAFgFADQgGADgHADQgHACgJAAQgQAAgMgHgACVA3QgGgGAAgKIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIADgZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIASAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgSABQgLAAgFgEgAhgA3QgFgGAAgKIAAguQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgKQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIALAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAABIASAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAAAqQAAAGADADQACACAGAAIAJAAIACABIABABIgBAJQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgRABQgLAAgGgEgAiTA7IgCAAIgBgDIAAg2QAAgFgDgEQgEgDgGAAIgIABIgGADIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgEQAFgCAFAAQAMAAAHAHQAHAHAAALIAAA5QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(-7.882,0.1104,0.8099,0.8099);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(1,1,1).p("AA1AAIgeAjAg0AAIBpAAAAcgiIAZAi");
	this.shape_1.setTransform(36.025,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(0.4,1,1).p("AniiOIPFAAIAAEdIvFAAg");
	this.shape_2.setTransform(-0.025,0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC24D").s().p("AniCPIAAkdIPFAAIAAEdgAF/AgIAegiIgZgjIAZAjIhpAAIBpAAgAGdgCgAGdgCg");
	this.shape_3.setTransform(-0.025,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49.3,-14.9,98.6,30.5);


(lib.BG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


// stage content:
(lib.WBAY_219645_MM_300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(375));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(221.05,220.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(74).to({_off:false},0).to({alpha:1},13,cjs.Ease.get(1)).wait(288));

	// logo_png
	this.instance_1 = new lib.logo_1("synched",0);
	this.instance_1.setTransform(80,290);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(7).to({_off:false},0).to({y:300,alpha:1},17,cjs.Ease.get(1)).wait(351));

	// T3
	this.instance_2 = new lib.T3("synched",0);
	this.instance_2.setTransform(221,173.95);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(59).to({_off:false},0).to({y:162.45,alpha:1},15,cjs.Ease.get(1)).wait(301));

	// T2
	this.instance_3 = new lib.T2("synched",0);
	this.instance_3.setTransform(220.95,136.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(42).to({_off:false},0).to({y:124.6,alpha:1},16,cjs.Ease.get(1)).wait(317));

	// T1
	this.instance_4 = new lib.T1("synched",0);
	this.instance_4.setTransform(219,43.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(26).to({_off:false},0).to({y:52,alpha:1},15,cjs.Ease.get(1)).wait(334));

	// Img_04_jpg
	this.instance_5 = new lib.Img_04_1("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(253).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(105));

	// Img_03_jpg
	this.instance_6 = new lib.Img_03_1("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(210).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(148));

	// Img_02_jpg
	this.instance_7 = new lib.Img_02_1("synched",0);
	this.instance_7.setTransform(80,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(166).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(192));

	// Img_01_jpg
	this.instance_8 = new lib.Img_01_1("synched",0);
	this.instance_8.setTransform(80,300);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(9).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(349));

	// BG_jpg
	this.instance_9 = new lib.BG_1("synched",0);
	this.instance_9.setTransform(80,300);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},17,cjs.Ease.get(1)).wait(358));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,115,152,136);
// library properties:
lib.properties = {
	id: 'EEE0CBDE3F5A41B0A2F5275DEDC5F0C8',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EEE0CBDE3F5A41B0A2F5275DEDC5F0C8'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;