(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.frog = function() {
	this.initialize(img.frog);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,225);


(lib.lizart = function() {
	this.initialize(img.lizart);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,35);


(lib.snake = function() {
	this.initialize(img.snake);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,319,208);


(lib.Tounge = function() {
	this.initialize(img.Tounge);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,167,210);


(lib.turtle = function() {
	this.initialize(img.turtle);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,253);


(lib.tr = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.turtle();
	this.instance.setTransform(-150,-126.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-126.5,300,253);


(lib.tg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Tounge();
	this.instance.setTransform(-23.35,-29.4,0.28,0.28);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.3,-29.4,46.7,58.8);


(lib.t3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDAGQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgJQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIAIAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape.setTransform(-29.125,-4.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgQAgQgHgEgEgHIAAgBIABgBIADgCIABAAIACAAIAEAGIAIAEQAFACADAAQAGAAAEgCQAEgBADgDQADgDgBgDQAAgEgCgDQgDgDgIgCIgNgEQgKgCgDgEQgEgEAAgGQAAgGAEgEQADgFAGgCQAFgDAHAAQAIAAAHADQAHAEAEAFIAAABIAAABIgFACIgBAAIgBAAQgCgEgGgDQgFgCgGAAQgHAAgEADQgGADAAAGQAAADACACQADADAHACIAQAFQAIACAEAEQAEAFAAAGQAAAGgDAEQgEAFgGACQgGADgJAAQgJAAgHgEg");
	this.shape_1.setTransform(-33.8,-7.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAUAjIgBAAIAAgBIAAgvQAAgGgEgEQgDgEgIAAIgGABIgIAEIgIAGIAAAyQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAhCQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAFAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAIIAAABIABgBIAIgFIAIgEIAHgBQALAAAFAFQAFAGAAAIIAAAxQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_2.setTransform(-40.675,-7.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgVAeQgGgFAAgIQAAgHAEgFQAEgFAHgCQAIgDAJAAIAMgBIACgBIAAgBIAAgEQAAgHgEgFQgFgEgIAAQgFAAgFADQgFACgEAGIgBAAIgBAAIgFgCIgBAAIABgCQAEgGAHgEQAGgEAJAAQAIAAAGADQAGACADAFQADAGAAAGIAAAuIgBABIgBAAIgFAAIgBAAIAAgBIgBgHQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAABQgFAFgGACQgGADgGAAQgKAAgGgGgAARAAIgJAAIgLABQgFABgDACIgGAFQgBADAAAEQAAAGAEADQAEAEAIAAQADAAAEgCIAIgEIAFgGIABgFIAAgLQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgBAAg");
	this.shape_3.setTransform(-48.225,-7.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgCAwIgBAAIAAgBIAAhBQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABAIAAACIgCAAgAgCghIgCgBIAAgBIAAgKQAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAFAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIAAAKQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_4.setTransform(-53.025,-8.575);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJAvIgHgEIgEgFIgBAAIAAABIgBAGQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDAAIgCAAIAAgCIAAhbQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAFAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAgIAAACIABgCIAEgCIAHgEQAFgBAFAAQAKgBAGAFQAGAFADAIQADAHAAAKQAAAQgIAKQgIAKgOAAQgFAAgEgCgAgLgMQgGADgDAEIAAAeQAAAEADAFQACAEAFACQAFACAFAAQAFAAAFgDQAFgDADgHQADgGAAgKQAAgNgGgIQgFgHgKAAQgGAAgFADg");
	this.shape_5.setTransform(-58.175,-8.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgCAwIgBAAIAAgBIAAhBQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABAIAAACIgCAAgAgCghIgCgBIAAgBIAAgKQAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAFAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIAAAKQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_6.setTransform(-63.725,-8.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAUAwIgBAAIAAgBIAAgvQAAgGgEgEQgDgEgIAAIgGABIgIAEIgIAGIAAAyQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhdQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAABAAIAFAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAjIAAABIABAAIAIgGIAIgEIAHgBQALAAAFAFQAFAGAAAJIAAAwQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_7.setTransform(-68.975,-8.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgcAuQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAhWIAAgBIACgBIAFAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAGIABABIABAAIAEgEIAGgEQAEgCAGAAQAIAAAGAEQAHAEAEAHQAEAIAAAMQAAAKgEAIQgEAJgHAEQgGAFgJAAQgGAAgFgCIgHgFIgCgBIAAACIAAAYQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAgLgkQgEADgDAEQgCADAAAEIAAAgQAEAEAEACQAFADAFAAQAGAAAGgEQAFgDADgHQADgFAAgKQAAgKgDgGQgDgGgFgDQgGgDgFAAQgFAAgFACg");
	this.shape_8.setTransform(-76.425,-6.175);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AApAjIgBAAIAAgBIAAgvQAAgGgEgEQgDgEgHAAIgIABIgHAEIgFAFIgBABIgBACIAAAwQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgFAAIgBAAIgBgBIAAgvQAAgGgDgEQgDgEgHAAQgGAAgFACIgLAJIAAAyQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAhCQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAFAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAIIAAABIABgBIAIgFIAHgEIAIgBQAIAAAFADQADAEACAEIABAAIABAAIAIgGIAHgEIAIgBQAKAAAFAFQAFAGAAAIIAAAxQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_9.setTransform(-86.275,-7.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgVAeQgGgFAAgIQAAgHAEgFQAEgFAHgCQAIgDAJAAIAMgBIACgBIAAgBIAAgEQAAgHgEgFQgFgEgIAAQgFAAgFADQgFACgEAGIgBAAIgBAAIgFgCIgBAAIABgCQAEgGAHgEQAGgEAJAAQAIAAAGADQAGACADAFQADAGAAAGIAAAuIgBABIgBAAIgFAAIgBAAIAAgBIgBgHQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAABQgFAFgGACQgGADgGAAQgKAAgGgGgAARAAIgJAAIgLABQgFABgDACIgGAFQgBADAAAEQAAAGAEADQAEAEAIAAQADAAAEgCIAIgEIAFgGIABgFIAAgLQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgBAAg");
	this.shape_10.setTransform(-95.925,-7.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgkArQgIgHAAgMQgBgHAFgHQAFgGAKgGIABgBIAAgCQgFgFgCgEQgDgFABgFQAAgHADgFQAEgGAFgDQAHgDAHAAQAGAAAFACQAFACADAFQADAEAAAGQAAAFgCAEQgDAFgFAEQgFAFgHAEIgBAAIAAACIAVAZIABAAIABgBIAFgFIAGgIIAEgHIADgFQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIADABIABAAIAAABIgEAJIgHAKIgJAKIAAABIAAABQADADAEABIAJAEIAIABQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAAAEIgBABIgBABIgLgCIgLgEIgJgFIgBgBIAAABQgGAFgHADQgHADgIAAQgOAAgGgGgAgUADQgGADgFAGQgEAGAAAGQAAAGADAEQACAEAFACQAFACAFAAQAGAAAGgCQAFgDAEgEIABgBIgBgCIgWgbIgBgBgAgQgnQgEACgCAEQgCAEAAAFIABAGIAFAHIADADIABABIABAAQAMgGADgFQAFgFAAgGQAAgGgFgDQgDgEgFAAQgGAAgEADg");
	this.shape_11.setTransform(-106.9,-8.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgQAgQgHgEgEgHIAAgBIABgBIADgCIABAAIABAAIAGAGIAHAEQAEACAFAAQAFAAAFgCQAEgBACgDQACgDABgDQAAgEgEgDQgDgDgHgCIgMgEQgLgCgDgEQgEgEAAgGQAAgGADgEQAEgFAFgCQAHgDAGAAQAIAAAHADQAHAEAEAFIAAABIAAABIgFACIgBAAIAAAAQgEgEgEgDQgFgCgHAAQgGAAgGADQgEADAAAGQAAADACACQACADAHACIAQAFQAIACAEAEQAEAFAAAGQAAAGgEAEQgDAFgHACQgGADgHAAQgJAAgIgEg");
	this.shape_12.setTransform(-8,-21.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgPAfQgHgEgFgIQgEgIAAgLQABgKAEgIQAEgIAIgFQAGgEAJAAQAJAAAHAEQAHAEAEAIQADAIABALIAAABIgCABIgzAAIgBAAIAAACQAAAGADAGQAEAGAFADQAGAEAGAAQAGAAAGgDQAFgDAEgGIAAAAIABAAIAFACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAAAABQgDAFgEADQgEADgFACQgFACgHAAQgJAAgHgFgAgLgZQgFAEgDAGQgDAGAAAGIArAAIABgBIABgBQAAgGgDgGQgDgFgEgDQgFgDgHAAQgGAAgGADg");
	this.shape_13.setTransform(-14.85,-21.925);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCAwQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhdQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAFAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABcIAAACIgCAAg");
	this.shape_14.setTransform(-20.125,-23.325);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgCAwIgBAAIAAgBIAAhBQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABAIAAACIgCAAgAgCghIgCgBIAAgBIAAgKQAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAFAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIAAAKQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_15.setTransform(-23.125,-23.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAIAuQgIAAgDgDQgDgEAAgIIAAgtQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgLAAQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgFQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIALAAIABgBIABgVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAEAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAUIABABIARAAIABABIAAAFIgBABIgRAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAABIAAArQAAAGADACQACADAEAAIAJAAIABAAIAAABIAAADIgBACIgDAAIgFAAg");
	this.shape_16.setTransform(-27.125,-23.125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgcAuQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAhWIAAgBIACgBIAFAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAGIABABIABAAIAEgEIAGgEQAEgCAGAAQAIAAAGAEQAHAEAEAHQAEAIAAAMQAAAKgEAIQgEAJgHAEQgGAFgJAAQgGAAgFgCIgHgFIgCgBIAAACIAAAYQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAgLgkQgEADgDAEQgCADAAAEIAAAgIAIAGQAFADAFAAQAGAAAGgEQAFgDADgHQADgFAAgKQAAgKgDgGQgDgGgFgDQgGgDgFAAQgFAAgFACg");
	this.shape_17.setTransform(-33.125,-20.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgPAfQgHgEgFgIQgDgIAAgLQgBgKAFgIQAEgIAHgFQAIgEAIAAQAJAAAHAEQAHAEAEAIQAEAIAAALIAAABIgDABIgxAAIgBAAIAAACQAAAGADAGQADAGAGADQAFAEAFAAQAIAAAFgDQAFgDAEgGIABAAIABAAIAEACQAAAAAAABQABAAAAAAQAAAAgBAAQAAAAAAABQgDAFgFADQgDADgGACQgFACgGAAQgJAAgHgFgAgLgZQgFAEgCAGQgDAGAAAGIApAAIADgBIAAgBQAAgGgDgGQgCgFgGgDQgEgDgHAAQgGAAgGADg");
	this.shape_18.setTransform(-40.9,-21.925);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgOAjIgCAAIAAgBIAAhCQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAFAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAJIAAAAIABAAIAHgGIAFgEIAHgBQACAAAAAAQABAAABAAQAAABABAAQAAAAAAAAIAAAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAIgDAAIgHABIgFAEIgEAFQgCADAAADIAAAsQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_19.setTransform(-46.7,-22);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAIAuQgIAAgDgDQgDgEAAgIIAAgtQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAAAAAIgLAAQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgFQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIALAAIABgBIABgVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAEAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAUIABABIARAAIABABIAAAFIgBABIgRAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAABIAAArQAAAGADACQACADAEAAIAJAAIABAAIAAABIAAADIgBACIgDAAIgFAAg");
	this.shape_20.setTransform(-54.775,-23.125);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgQAhQgFgDgDgEQgCgFAAgFIAAgwQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAGAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAuQgBAGAEAFQAEAEAHAAQAFAAAGgDQAFgEAGgFIAAgxQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAGAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAABBQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgGAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgHIAAgBIgBAAQgIAHgGACQgEACgFAAQgGAAgFgCg");
	this.shape_21.setTransform(-60.9,-21.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgQAfQgHgEgEgIQgEgIAAgLQAAgJAEgJQAEgIAHgEQAIgFAIAAQAKAAAHAFQAHAEAEAIQAEAIAAAKQAAAKgEAIQgEAIgHAFQgHAFgKAAQgIAAgIgFgAgLgZQgGAEgCAHQgDAGAAAIQAAAJADAGQACAHAGADQAFAEAGAAQAIAAAFgEQAFgDADgHQADgGAAgJQAAgIgDgGQgDgHgFgEQgGgDgHAAQgGAAgFADg");
	this.shape_22.setTransform(-68.475,-21.925);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgJAvQgFgCgCgCIgEgFIgBAAIAAABIgBAGQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgDAAIgCAAIAAgCIAAhbQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAFAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAgIAAACIABgBIAEgDIAHgEQAFgBAFAAQAKgBAGAFQAGAFADAIQADAHAAAKQAAAQgIAKQgIAKgOAAQgFAAgEgCgAgLgMQgGADgDAFIAAAdQAAAEADAFQACADAFADQAFACAFAAQAFAAAFgDQAFgDADgHQADgGAAgKQAAgNgGgIQgFgHgKAAQgGAAgFADg");
	this.shape_23.setTransform(-75.975,-23.25);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgVAeQgGgFAAgIQAAgHAEgFQAEgFAHgCQAIgDAJAAIAMgBIACgBIAAgBIAAgEQAAgHgEgFQgFgEgIAAQgFAAgFADQgFACgEAGIgBAAIgBAAIgFgCIgBAAIABgCQAEgGAHgEQAGgEAJAAQAIAAAGADQAGACADAFQADAGAAAGIAAAuIgBABIgBAAIgFAAIgBAAIAAgBIgBgHQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAABQgFAFgGACQgGADgGAAQgKAAgGgGgAARAAIgJAAIgLABQgFABgDACIgGAFQgBADAAAEQAAAGAEADQAEAEAIAAQADAAAEgCIAIgEIAFgGIABgFIAAgLQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgBAAg");
	this.shape_24.setTransform(-83.775,-21.925);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAUAjIgBAAIAAgBIAAguQAAgIgEgDQgDgEgIAAIgGABIgIAEIgIAGIAAAyQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAhCQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAFAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAIIAAABIABgBIAIgFIAIgEIAHgBQALAAAFAFQAFAGAAAIIAAAxQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_25.setTransform(-93.625,-22);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgOAjIgCAAIAAgBIAAhCQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAFAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAJIAAAAIABAAIAHgGIAFgEIAIgBQABAAAAAAQABAAABAAQAAABABAAQAAAAAAAAIAAAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAIgDAAIgGABIgGAEIgEAFQgCADAAADIAAAsQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_26.setTransform(-99.45,-22);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgVAeQgGgFAAgIQAAgHAEgFQAEgFAHgCQAIgDAJAAIAMgBIACgBIAAgBIAAgEQAAgHgEgFQgFgEgIAAQgFAAgFADQgFACgEAGIgBAAIgBAAIgFgCIgBAAIABgCQAEgGAHgEQAGgEAJAAQAIAAAGADQAGACADAFQADAGAAAGIAAAuIgBABIgBAAIgFAAIgBAAIAAgBIgBgHQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAABQgFAFgGACQgGADgGAAQgKAAgGgGgAARAAIgJAAIgLABQgFABgDACIgGAFQgBADAAAEQAAAGAEADQAEAEAIAAQADAAAEgCIAIgEIAFgGIABgFIAAgLQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgBAAg");
	this.shape_27.setTransform(-105.975,-21.925);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgPAfQgHgEgEgIQgEgIgBgLQAAgKAFgIQAEgIAHgFQAIgEAIAAQAJAAAHAEQAHAEAEAIQADAIAAALIAAABIgCABIgxAAIgCAAIAAACQABAGADAGQADAGAGADQAFAEAFAAQAIAAAFgDQAFgDAEgGIABAAIABAAIAEACQAAAAAAABQABAAAAAAQAAAAgBAAQAAAAAAABQgDAFgFADQgDADgGACQgFACgGAAQgJAAgHgFgAgLgZQgFAEgCAGQgDAGgBAGIAqAAIACgBIABgBQAAgGgDgGQgDgFgFgDQgEgDgHAAQgGAAgGADg");
	this.shape_28.setTransform(-113,-21.925);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgCAwQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhdQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAFAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABcIAAACIgCAAg");
	this.shape_29.setTransform(-118.275,-23.325);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgQAfQgHgEgEgIQgEgIAAgLQAAgJAEgJQAEgIAHgEQAIgFAIAAQAKAAAHAFQAHAEAEAIQAEAIAAAKQAAAKgEAIQgEAIgHAFQgHAFgKAAQgIAAgIgFgAgLgZQgGAEgCAHQgDAGAAAIQAAAJADAGQACAHAGADQAFAEAGAAQAIAAAFgEQAFgDADgHQADgGAAgJQAAgIgDgGQgDgHgFgEQgGgDgHAAQgGAAgFADg");
	this.shape_30.setTransform(-126.475,-21.925);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAIAuQgIAAgDgDQgDgEAAgIIAAgtQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAAAAAIgLAAQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgFQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIALAAIABgBIABgVQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAAAAAIAEAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAUIABABIARAAIABABIAAAFIgBABIgRAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAABIAAArQAAAGADACQACADAEAAIAJAAIABAAIAAABIAAADIgBACIgDAAIgFAAg");
	this.shape_31.setTransform(-132.825,-23.125);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgQAgQgHgEgEgHIAAgBIABgBIAEgCIAAAAIABAAIAGAGIAHAEQAEACAFAAQAFAAAFgCQAEgBACgDQACgDABgDQAAgEgEgDQgDgDgHgCIgMgEQgLgCgDgEQgEgEAAgGQAAgGADgEQAEgFAFgCQAHgDAGAAQAIAAAHADQAHAEAEAFIAAABIAAABIgFACIgBAAIAAAAQgEgEgFgDQgEgCgHAAQgGAAgGADQgEADAAAGQAAADABACQADADAHACIAQAFQAIACAEAEQAEAFAAAGQAAAGgEAEQgDAFgHACQgGADgHAAQgJAAgIgEg");
	this.shape_32.setTransform(-47.15,-36.675);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgOAjIgCAAIAAgBIAAhBQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAFAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAIIAAABIABAAIAHgHIAFgEIAIgBQABAAAAAAQABAAABAAQAAABABAAQAAAAAAAAIAAAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAIgDAAIgGABIgGAEIgEAFQgCADgBADIAAAsQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_33.setTransform(-52.3,-36.75);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgPAfQgHgEgFgIQgDgIAAgLQgBgKAFgIQAEgIAHgFQAIgEAIAAQAJAAAHAEQAHAEAEAIQAEAIAAALIAAABIgDABIgxAAIgBAAIAAACQAAAGACAGQAEAGAFADQAGAEAFAAQAIAAAFgDQAFgDAEgGIABAAIABAAIAEACQAAAAAAABQABAAAAAAQAAAAgBAAQAAABAAAAQgDAFgEADQgFADgEACQgGACgGAAQgJAAgHgFgAgLgZQgFAEgDAGQgCAGAAAGIApAAIADgBIAAgBQAAgGgDgGQgCgFgFgDQgFgDgHAAQgGAAgGADg");
	this.shape_34.setTransform(-58.8,-36.675);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgcAuQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhWIAAgBIACgBIAFAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAGIABABIABAAIAEgEIAGgEQAEgCAGAAQAIAAAGAEQAHAEAEAHQAEAIAAAMQAAAKgEAIQgEAJgHAEQgGAFgJAAQgGAAgFgCIgHgFIgCgBIAAACIAAAYQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAgLgkQgEADgDAEQgCADAAAEIAAAgQAEAEAEACQAFADAFAAQAGAAAGgEQAFgDADgHQADgFAAgKQAAgKgDgGQgDgGgFgDQgGgDgFAAQgFAAgFACg");
	this.shape_35.setTransform(-66.225,-35.675);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AApAjIgBAAIAAgBIAAguQAAgIgEgDQgDgEgHAAIgIABIgHAEIgFAEIgBACIgBACIAAAwQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgFAAIgBAAIgBgBIAAguQAAgIgDgDQgDgEgHAAQgGAAgFACIgLAJIAAAyQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAhBQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAABAAIAFAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHIAAABIABgBIAIgFIAHgEIAIgBQAIAAAFAEQADADACAEIABABIABgBIAIgGIAHgEIAIgBQAKAAAFAFQAFAGAAAIIAAAxQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_36.setTransform(-76.075,-36.75);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgVAeQgGgFAAgIQAAgHAEgFQAEgFAHgCQAIgDAJAAIAMgBIACgBIAAgBIAAgEQAAgHgEgFQgFgEgIAAQgFAAgFADQgFACgEAGIgBAAIgBAAIgFgCIgBAAIABgCQAEgGAHgEQAGgEAJAAQAIAAAGADQAGACADAFQADAGAAAGIAAAuIgBABIgBAAIgFAAIgBAAIAAgBIgBgHQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAABQgFAFgGACQgGADgGAAQgKAAgGgGgAARAAIgJAAIgLABQgFABgDACIgGAFQgBADAAAEQAAAGAEADQAEAEAIAAQADAAAEgCIAIgEIAFgGIABgFIAAgLQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgBAAg");
	this.shape_37.setTransform(-85.725,-36.675);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgNAfQgIgEgEgIQgEgIAAgLQAAgJAEgJQAEgIAIgEQAHgFAIAAQAHAAAFACQAEACAEADQAEAEADAEQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgFACQgBAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAgBIgGgGQgCgDgDgBQgDgBgEAAQgGAAgGADQgFAEgDAGQgDAHAAAIQAAAJADAGQADAHAFADQAGAEAGAAQAHAAAEgDQAFgDAEgHIABAAIABAAIAEACQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIgFAHIgGAFQgEACgEABQgEACgFAAQgIAAgHgFg");
	this.shape_38.setTransform(-92.4167,-36.675);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgOAjIgCgBIAAgBIAAhAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAFAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAIIAAABIABAAIAHgHIAFgEIAIgBQABAAAAAAQABAAABAAQAAABABAAQAAAAAAABIAAAFQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAIgDAAIgGABIgGAEIgEAFQgCADgBADIAAArQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_39.setTransform(-4.15,-51.5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgQAfQgHgEgEgIQgEgIAAgLQAAgJAEgJQAEgIAHgEQAIgFAIAAQAKAAAHAFQAHAEAEAIQAEAIAAAKQAAAKgEAIQgEAIgHAFQgHAFgKAAQgIAAgIgFgAgLgZQgGAEgCAHQgDAGAAAIQAAAJADAGQACAHAGADQAFAEAGAAQAIAAAFgEQAFgDADgHQADgGAAgJQAAgIgDgGQgDgHgFgEQgGgDgHAAQgGAAgFADg");
	this.shape_40.setTransform(-10.825,-51.425);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgDAwQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAg7IgBgBIgNAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIAAgEIAAgBIABgBIANAAIABgBIAAgKQAAgIAEgEQADgEAIAAIAKAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAEIAAABIgBAAIgKAAQgEAAgBADQgDADAAAEIAAAKIABABIAQAAIABABIABABIAAAEQAAAAAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgPAAIgBABIAAA7QAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_41.setTransform(-17.05,-52.825);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgZAtQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIAAgEIABgBIAEgBIAIAAQADAAACgCIAEgFIACgGQAAgEAAgCIgZg9IAAgCIABAAIAGAAIABAAIABABIAUA1IABABIABgCIAVg0IAAgBIABAAIAFAAIABAAIAAABIgdBKIgDAHIgEAEIgGADIgHAAg");
	this.shape_42.setTransform(-25.65,-50.375);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAIAuQgIAAgDgDQgDgEAAgIIAAgtQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgLAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAAAIAAgFQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIALAAIABgBIABgVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAEAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAUIABABIARAAIABABIAAAFIgBABIgRAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAABIAAArQAAAGADACQACADAEAAIAJAAIABAAIAAABIAAADIgBACIgDAAIgFAAg");
	this.shape_43.setTransform(-31.525,-52.625);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgCAwIgBAAIAAgBIAAhBQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABAIAAACIgCAAgAgCghIgCgBIAAgBIAAgKQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAFAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAKQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_44.setTransform(-35.375,-52.825);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAUAjIgBgBIAAgBIAAgtQAAgIgEgDQgDgEgIAAIgGABIgIAEIgIAGIAAAxQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhAQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAABAAIAFAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHIAAABIABAAIAIgGIAIgEIAHgBQALAAAFAFQAFAFAAAJIAAAwQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_45.setTransform(-40.625,-51.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgQAhQgFgDgDgEQgCgFAAgFIAAgwQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAGAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAuQAAAGADAFQAEAEAHAAQAFAAAGgDQAFgEAFgFIAAgxQABAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAGAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAABBQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgGAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgHIgBgBIAAAAQgIAHgGACQgEACgFAAQgGAAgFgCg");
	this.shape_46.setTransform(-48.2,-51.375);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AAIAuQgIAAgDgDQgDgEAAgIIAAgtQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgLAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAAAIAAgFQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIALAAIABgBIABgVQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAEAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAUIABABIARAAIABABIAAAFIgBABIgRAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAABIAAArQAAAGADACQACADAEAAIAJAAIABAAIAAABIAAADIgBACIgDAAIgFAAg");
	this.shape_47.setTransform(-54.375,-52.625);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgPAjIgBgBIAAgBIAAhAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAGAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAIIAAABIABAAIAHgHIAFgEIAHgBQACAAAAAAQABAAABAAQAAABABAAQAAAAAAABIAAAFQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAIgDAAIgHABIgEAEIgGAFQgBADAAADIAAArQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_48.setTransform(-58.75,-51.5);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgQAfQgHgEgEgIQgEgIAAgLQAAgJAEgJQAEgIAHgEQAIgFAIAAQAKAAAHAFQAHAEAEAIQAEAIAAAKQAAAKgEAIQgEAIgHAFQgHAFgKAAQgIAAgIgFgAgLgZQgGAEgCAHQgDAGAAAIQAAAJADAGQACAHAGADQAFAEAGAAQAIAAAFgEQAFgDADgHQADgGAAgJQAAgIgDgGQgDgHgFgEQgGgDgHAAQgGAAgFADg");
	this.shape_49.setTransform(-65.425,-51.425);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgcAuQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAhWIAAgBIACgBIAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAGIABABIABAAIAEgEIAGgEQAEgCAGAAQAIAAAGAEQAHAEAEAHQAEAIAAAMQAAAKgEAIQgEAJgHAEQgGAFgJAAQgGAAgFgCIgHgFIgCgBIAAACIAAAYQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAgLgkQgEADgDAEQgCADAAAEIAAAgQAEAEAEACQAFADAFAAQAGAAAGgEQAFgDADgHQADgFAAgKQAAgKgDgGQgDgGgFgDQgGgDgFAAQgFAAgFACg");
	this.shape_50.setTransform(-72.925,-50.425);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgcAuQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhWIAAgBIACgBIAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAGIABABIABAAIAEgEIAGgEQAEgCAGAAQAIAAAGAEQAHAEAEAHQAEAIAAAMQAAAKgEAIQgEAJgHAEQgGAFgJAAQgGAAgFgCIgHgFIgCgBIAAACIAAAYQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAgLgkQgEADgDAEQgCADAAAEIAAAgIAIAGQAFADAFAAQAGAAAGgEQAFgDADgHQADgFAAgKQAAgKgDgGQgDgGgFgDQgGgDgFAAQgFAAgFACg");
	this.shape_51.setTransform(-80.625,-50.425);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgQAfQgHgEgEgIQgEgIAAgLQAAgJAEgJQAEgIAHgEQAIgFAIAAQAKAAAHAFQAHAEAEAIQAEAIAAAKQAAAKgEAIQgEAIgHAFQgHAFgKAAQgIAAgIgFgAgLgZQgGAEgCAHQgDAGAAAIQAAAJADAGQACAHAGADQAFAEAGAAQAIAAAFgEQAFgDADgHQADgGAAgJQAAgIgDgGQgDgHgFgEQgGgDgHAAQgGAAgFADg");
	this.shape_52.setTransform(-88.575,-51.425);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgPAfQgHgEgFgIQgDgIAAgLQgBgKAFgIQAEgIAHgFQAIgEAIAAQAJAAAHAEQAHAEAEAIQAEAIAAALIAAABIgDABIgxAAIgBAAIAAACQAAAGADAGQADAGAGADQAFAEAFAAQAIAAAFgDQAFgDAEgGIABAAIABAAIAEACQAAAAAAABQABAAAAAAQAAAAgBAAQAAABAAAAQgDAFgFADQgDADgGACQgFACgGAAQgJAAgHgFgAgLgZQgFAEgCAGQgDAGAAAGIApAAIADgBIAAgBQAAgGgDgGQgCgFgGgDQgEgDgHAAQgGAAgGADg");
	this.shape_53.setTransform(-98.95,-51.425);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgQAhQgFgDgDgEQgCgFAAgFIAAgwQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAGAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAuQABAGADAFQAEAEAHAAQAFAAAGgDQAFgEAFgFIAAgxQAAAAABAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAFAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAABBQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgGAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgHIgBgBIgBAAQgHAHgFACQgFACgFAAQgGAAgFgCg");
	this.shape_54.setTransform(-106.5,-51.375);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AAXAuQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgYIgBgCIgBABQgEADgFACQgFACgGAAQgIAAgHgFQgHgEgDgIQgEgJAAgJQAAgLAEgIQADgIAHgFQAHgEAIAAQAHAAAEACIAHAEIADADQABABAAAAQAAAAAAAAQABAAAAgBQAAAAAAAAIAAgGIABgBIACgBIACAAIACABIAAABIAABWQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAgAgJgjQgFADgDAGQgDAHAAAJQAAAKADAFQADAHAFADQAFAEAGAAQAFAAAGgCQAFgDAEgEIAAgfQgBgEgCgEQgDgEgEgDQgFgCgFAAQgGAAgFADg");
	this.shape_55.setTransform(-114.275,-50.425);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgCAwIgBAAIAAgBIAAhBQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABAIAAACIgCAAgAgCghIgCgBIAAgBIAAgKQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAFAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAKQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_56.setTransform(-119.425,-52.825);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AAUAjIgBgBIAAgBIAAgtQAAgIgEgDQgDgEgIAAIgGABIgIAEIgIAGIAAAxQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhAQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAFAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHIAAABIABAAIAIgGIAIgEIAHgBQALAAAFAFQAFAFAAAJIAAAwQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_57.setTransform(-124.675,-51.5);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgSAtQgHgDgEgJQgEgHAAgMIAAg9QAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAABAAIAGAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAABAQAAAMAGAGQAGAGALAAQAJAAAFgDQAFgCAEgGQACgFAAgJIAAg/QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAHAAQAAAAAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAA/QgBAMgDAGQgEAIgIADQgHAEgLAAQgLAAgHgEg");
	this.shape_58.setTransform(-133.05,-52.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-149.3,-62.5,158.8,64);


(lib.t2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#167ABE").s().p("AgPAwQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAEgQIAIgUIAKgVIANgYIABgBIgCgBIgxAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgIQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIA9AAIACAAIAAABIAAAFIAAACIgCADIgKARIgJASIgHARIgFARIgDANQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(1.275,-34.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#167ABE").s().p("AgOAFIgBgBIgBgBIAAgFIABgBIAeAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAFQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_1.setTransform(-7.825,-32.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#167ABE").s().p("AgdAxIgBAAIgBgCIAAgFIAAgCIABgBIACgDIAcgcIAIgIIAHgIIACgGQACgDAAgEQAAgFgDgEQgDgEgFgCQgEgCgEAAIgHABIgIAFQgDACgDAFIgBAAIgCAAIgGgEIgBAAIABgCQAFgJAJgEQAJgEAHAAQAJAAAHADQAGADAFAGQAEAGAAAKQAAAFgCAFQgCAFgFAFIgMANIgZAYIgBABIABABIAtAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAIIAAABIgCAAg");
	this.shape_2.setTransform(-16.95,-34.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#167ABE").s().p("AAHAuQgHAAgEgEQgDgDAAgJIAAgqQAAgBAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgFQAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIALAAIABgBIACgUQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAABAAIAGAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAUIABABIARAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAABIAAAFQAAABgBAAQAAAAAAAAQAAABAAAAQAAAAAAAAIgRAAIgBABIAAAoQgBAGADACQACACAEAAIAJAAIABAAIABACIAAAEQAAAAgBAAQAAABAAAAQAAAAgBAAQAAABAAAAIgEAAIgEAAg");
	this.shape_3.setTransform(-26.1,-34.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#167ABE").s().p("AgQAfQgIgEgDgGIgBgBIABgBIAFgDIABAAIABAAIAFAGIAHAEQAEACAFAAQAFAAAEgCQAEgBACgDQADgCAAgEQAAgDgDgDQgDgCgHgCIgNgEQgJgCgEgEQgEgEAAgGQAAgHADgEQADgFAGgCQAGgDAHAAQAJAAAHADQAHAEADAFIABABIgBABIgFADIgBAAIgBAAQgDgEgFgDQgEgCgHAAQgGAAgEADQgFADAAAFQAAADACACQACACAGACIAQAFQAJACAEAEQAEAFAAAGQAAAGgEAFQgDAFgHACQgGADgIAAQgKAAgHgFg");
	this.shape_4.setTransform(-32.025,-32.925);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#167ABE").s().p("AgRAhQgFgDgCgEQgDgFAAgGIAAgvQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAHAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAsQAAAHADAEQAEADAGAAQAFAAAFgDQAFgDAFgFIAAgvQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAABAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgFADQgFACgFAAQgGAAgFgCg");
	this.shape_5.setTransform(-38.975,-32.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#167ABE").s().p("AgaAqQgJgFAAgJQAAgEADgEQAEgEAFgDQABAAAAAAQAAAAAAAAQAAAAAAgBQAAAAgBAAIgEgDQAAgBgBAAQAAgBAAAAQAAgBAAgBQgBAAAAgBIACgDIADgDIAGgCIAAgBIAAgBQgGgDgDgEQgDgEAAgGQAAgLAIgFQAIgGAOAAQAGAAAFABQAEACAEADIABAAIABAAIADgDIAFgCIAEgBIACAAIABACIAAAEIgBACIgCABIgEAAIgCABQgBAAgBAAQAAABgBAAQAAAAAAABQAAAAAAABIABADIABAGQAAAFgDAFQgDAFgHADQgFADgJAAIgLAAIgFACIgBACQAAABAAAAQAAABAAAAQABAAAAABQABAAABAAIAJABIAPABQAMABAFAFQAFAFAAAHQAAAKgJAGQgIAFgPAAQgRAAgIgEgAgSARIgFAEQgCACAAAEQAAAEACADQADADAGABQAGACAIAAQAKAAAFgDQAGgEAAgGQAAgFgDgCQgDgDgHAAIgVgCIgFACgAgPgiQgEAEgBAHQABAGAEAEQAFAEAJAAQAIAAAEgEQAEgEAAgGQAAgHgEgEQgEgEgIAAQgJAAgFAEg");
	this.shape_6.setTransform(-46.6,-31.875);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#167ABE").s().p("AgRAhQgFgDgCgEQgDgFAAgGIAAgvQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAHAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAsQAAAHADAEQAEADAGAAQAFAAAFgDQAFgDAFgFIAAgvQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAABAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgFADQgFACgFAAQgGAAgFgCg");
	this.shape_7.setTransform(-54.275,-32.875);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#167ABE").s().p("AAfAwQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIgJgZIgBgBIgBAAIglAAIgBABIgJAZIgBABIgBAAIgIAAIgBAAIAAgCIAhhbIABgCIACAAIAJAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAhBbIAAACIgBAAgAAAghIgQAqQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAfAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIgQgqIAAgBg");
	this.shape_8.setTransform(-62.725,-34.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#167ABE").s().p("AgBBCQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAh/IAAgCIABAAIAEAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAB/QAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_9.setTransform(-71.85,-33.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#167ABE").s().p("AgWAwQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgHQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIARAAIABAAIAAhHQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAIgQAGQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgGIAAgBIABgBIATgJIACgBIABAAIAGAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABTIABABIAPAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAHIAAABIgBAAg");
	this.shape_10.setTransform(-79.225,-34.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#167ABE").s().p("AgOAwQgGgBgEgEQgFgDgFgEIAAgBIAAgBIAHgFIABAAIABAAIAHAGQAEADAFABQADABAGAAQAKAAAHgFQAFgFAAgIQABgGgEgFQgDgEgGgCQgFgCgGAAIgMAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAgFQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAKAAQAGAAAFgCQAFgDAEgEQADgDAAgGQAAgEgDgDQgCgEgFgCQgFgCgFAAQgGAAgGACQgGADgFAFIgBAAIgBAAIgFgFQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAFgEAEgDQAFgDAGgBQAEgCAGAAQAKAAAHAEQAHADAEAFQAEAGAAAHQAAAHgEAGQgEAFgIADIgCABIACABQAFABAFADQAEADACAFQADAEAAAHQAAAIgEAGQgFAGgHAEQgJAEgLAAQgGAAgHgCg");
	this.shape_11.setTransform(-86.55,-34.325);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#167ABE").s().p("AgOAFIgBgBIgBgBIAAgFIABgBIAeAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAFQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_12.setTransform(-95.825,-32.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#167ABE").s().p("AgPAwQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAEgQIAIgUIAKgVIANgYIABgBIgCgBIgxAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgIQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIA9AAIACAAIAAABIAAAFIAAACIgCADIgKARIgJASIgHARIgFARIgDANQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_13.setTransform(-104.925,-34.325);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#167ABE").s().p("AgdAxIgBAAIgBgCIAAgFIAAgCIABgBIACgDIAcgcIAIgIIAHgIIACgGQACgDAAgEQAAgFgDgEQgDgEgFgCQgDgCgFAAIgHABIgIAFQgDACgDAFIgBAAIgCAAIgGgEIgBAAIABgCQAFgJAJgEQAJgEAHAAQAJAAAGADQAHADAFAGQAEAGAAAKQAAAFgCAFQgCAFgFAFIgMANIgZAYIgBABIACABIAsAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAIIAAABIgCAAg");
	this.shape_14.setTransform(-112.7,-34.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#167ABE").s().p("AgaAtQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIAAgFIABgBIADAAIAIAAQADAAADgCIADgFIADgGQAAgDgBgCIgZg9IAAgBIACgBIAIAAIABAAIAAABIATAyIABABIABgCIAUgxIABgBIABAAIAFAAIACAAIAAACIgdBIQgBAFgCADQgCADgDABIgGADIgHAAg");
	this.shape_15.setTransform(-122.7,-31.875);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#167ABE").s().p("AgDAwQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAABgBIAAhbQAAgBAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAHAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAABcIAAACIgCAAg");
	this.shape_16.setTransform(-127.7,-34.325);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#167ABE").s().p("AgRAhQgFgDgCgEQgDgFAAgGIAAgvQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAHAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAsQAAAHADAEQAEADAGAAQAFAAAFgDQAFgDAFgFIAAgvQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAABAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgFADQgFACgFAAQgGAAgFgCg");
	this.shape_17.setTransform(-133.025,-32.875);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#167ABE").s().p("AgLAvIgFgBIgBgBIAAgBIABgIQAAAAAAAAQAAAAAAAAQAAgBAAAAQABAAAAABIAEABIAHABQAEAAADgDQADgDAAgIIAAhGQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAABJQAAALgGAFQgEAGgLAAQgEAAgFgCg");
	this.shape_18.setTransform(-139.75,-34.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#167ABE").s().p("AgPAwQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIAEgQIAIgUIAKgVIANgYIABgBIgCgBIgxAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgIQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIA9AAIACAAIAAABIAAAFIAAACIgCADIgKARIgJASIgHARIgFARIgDANQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_19.setTransform(0.175,-53.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#167ABE").s().p("AgWAwQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgHQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIARAAIABAAIAAhHQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAIgQAGQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgGIAAgBIABgBIATgJIACgBIABAAIAGAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABTIABABIAPAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAHIAAABIgBAAg");
	this.shape_20.setTransform(-6.625,-53.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#167ABE").s().p("AgOAFIgBgBIgBgBIAAgFIABgBIAeAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAEQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_21.setTransform(-14.925,-51.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#167ABE").s().p("AgNAwQgHgBgEgEQgGgDgDgEIgBgBIABgBIAFgFIABAAIABAAIAIAGQAEADAEABQAFABAEAAQALAAAGgFQAHgFAAgIQgBgGgDgFQgEgEgFgCQgFgCgGAAIgLAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAgFQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAJAAQAGAAAFgCQAFgDADgEQAEgDAAgGQAAgEgDgDQgDgEgEgCQgEgCgGAAQgGAAgGACQgGADgEAFIgBAAIgCAAIgFgFQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAFgEAEgDQAFgDAFgBQAFgCAGAAQAJAAAIAEQAHADAEAFQAEAGAAAHQAAAHgFAGQgDAFgJADIgBABIABABQAGABAEADQAFADADAFQACAEAAAHQAAAIgEAGQgEAGgJAEQgIAEgLAAQgHAAgFgCg");
	this.shape_22.setTransform(-24.4,-53.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#167ABE").s().p("AgWAwQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgHQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIARAAIABAAIAAhHQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAIgQAGQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgGIAAgBIABgBIATgJIACgBIABAAIAGAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABTIABABIAPAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAHIAAABIgBAAg");
	this.shape_23.setTransform(-31.375,-53.075);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#167ABE").s().p("AgaAtQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIAAgFIABgBIADAAIAIAAQADAAACgCIAFgFIACgGQAAgDgBgCIgZg9IAAgBIABgBIAJAAIABAAIAAABIATAyIABABIACgCIATgxIABgBIABAAIAGAAIABAAIAAACIgdBIQgBAFgCADQgCADgDABIgGADIgIAAg");
	this.shape_24.setTransform(-40.6,-50.625);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#167ABE").s().p("AgDAwQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAhbQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAHAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAABcIAAACIgCAAg");
	this.shape_25.setTransform(-45.6,-53.075);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#167ABE").s().p("AgRAhQgFgDgCgEQgDgFAAgGIAAgvQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAHAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAsQAAAHADAEQAEADAGAAQAFAAAFgDQAFgDAFgFIAAgvQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAHAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAABAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgFADQgFACgFAAQgGAAgFgCg");
	this.shape_26.setTransform(-50.925,-51.625);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#167ABE").s().p("AgKAwIgGgCIgBgBIAAgCIAAgGQABgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAABIAFABIAGABQAFAAACgDQADgDAAgJIAAhGQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAABKQABAKgGAGQgFAGgJAAQgGAAgDgBg");
	this.shape_27.setTransform(-57.65,-53);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#167ABE").s().p("AgCBCQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAh/IAAgCIABAAIAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAB/QAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_28.setTransform(-64.45,-52.675);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#167ABE").s().p("AgdAxIgCgBIAAgBIAAgFIAAgCIABgCIACgCIAcgbIAJgJIAFgIIAEgHQABgDAAgDQAAgFgDgFQgDgDgEgCQgFgCgEAAIgHABIgIAEQgEADgDAFIgBAAIgBAAIgGgDIgBgBIAAgCQAHgJAIgEQAJgEAIAAQAIAAAGADQAIADAEAGQAEAGAAAKQAAAFgCAFQgCAFgFAFIgMAMIgZAZIAAABIABAAIAsAAQAAAAABABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAHIgBABIgBABg");
	this.shape_29.setTransform(-72.8,-53.15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#167ABE").s().p("AgdAxIgCgBIAAgBIAAgFIAAgCIABgCIACgCIAcgbIAIgJIAGgIIADgHQACgDAAgDQAAgFgDgFQgDgDgFgCQgDgCgFAAIgHABIgIAEQgEADgDAFIAAAAIgCAAIgGgDIgBgBIAAgCQAGgJAJgEQAJgEAIAAQAIAAAGADQAIADAEAGQAEAGAAAKQAAAFgCAFQgCAFgFAFIgMAMIgZAZIAAABIABAAIAsAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIAAAHIgBABIgBABg");
	this.shape_30.setTransform(-80.55,-53.15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#167ABE").s().p("AgOAFIgBgBIgBgBIAAgFIABgBIAeAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAEQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_31.setTransform(-89.625,-51.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#167ABE").s().p("AgdAxIgBgBIgBgBIAAgFIAAgCIABgCIACgCIAcgbIAIgJIAHgIIACgHQACgDAAgDQAAgFgDgFQgDgDgFgCQgDgCgFAAIgHABIgIAEQgDADgDAFIgBAAIgCAAIgGgDIgBgBIABgCQAFgJAJgEQAJgEAHAAQAJAAAGADQAHADAFAGQAEAGAAAKQAAAFgCAFQgCAFgFAFIgMAMIgZAZIgBABIACAAIAsAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIAAAHIAAABIgCABg");
	this.shape_32.setTransform(-98.75,-53.15);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#167ABE").s().p("AgdAxIgBgBIgBgBIAAgFIAAgCIABgCIACgCIAcgbIAIgJIAHgIIACgHQACgDAAgDQAAgFgDgFQgDgDgFgCQgEgCgEAAIgHABIgIAEQgDADgDAFIgBAAIgCAAIgGgDIgBgBIABgCQAFgJAJgEQAJgEAHAAQAJAAAHADQAGADAFAGQAEAGAAAKQAAAFgCAFQgCAFgFAFIgMAMIgZAZIgBABIABAAIAtAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIAAAHIAAABIgCABg");
	this.shape_33.setTransform(-106.5,-53.15);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#167ABE").s().p("AgPAfQgIgEgEgIQgEgIAAgLQAAgKAEgIQAEgIAIgFQAHgEAJAAQAJAAAHAEQAIAEADAIQAEAIAAALIAAABQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAIgxAAIAAABIAAABQAAAGACAGQADAFAFADQAFADAGAAQAGAAAGgCQAEgDAFgGIAAAAIABAAIAFADQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQgEAFgEADQgEADgFACQgGACgGAAQgJAAgHgFgAgKgYQgEADgDAGQgDAFABAGIAmAAIACAAIABgCQAAgFgDgFQgDgFgEgDQgFgDgGAAQgGAAgFADg");
	this.shape_34.setTransform(-116.85,-51.675);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#167ABE").s().p("AATAjIgBgBIAAgBIAAgtQAAgGgEgEQgDgDgHAAIgGABIgHADIgHAGIAAAwQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgHAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAIAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABAAIAIgHIAHgDIAIgBQAKAAAFAFQAFAGAAAJIAAAvQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_35.setTransform(-124.375,-51.75);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#167ABE").s().p("AgRAhQgFgDgCgEQgDgFAAgGIAAgvQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAHAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAsQAAAHADAEQAEADAGAAQAFAAAFgDQAFgDAFgFIAAgvQAAgBAAAAQABgBAAAAQAAAAAAAAQABAAAAAAIAHAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgFADQgFACgFAAQgGAAgFgCg");
	this.shape_36.setTransform(-131.975,-51.625);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#167ABE").s().p("AgLAwIgFgCIgCgBIAAgCIABgGQAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAABIAEABIAHABQAFAAACgDQADgDAAgJIAAhGQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAKAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAABKQAAAKgEAGQgFAGgLAAQgFAAgEgBg");
	this.shape_37.setTransform(-138.7,-53);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-144.2,-62.8,151.5,38.5);


(lib.t1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0B9444").s().p("AgOBoQgGAAABgFIAAgfQgBgFAEABIAhAAQADAAAAADIAAAfQAAAGgHAAgAgGAsIgEgBIgBgEIgJiJIABgEIACgBIAiAAQAEAAAAAEIgJCJQAAABAAABQAAABAAAAQgBABAAAAQAAABgBAAIgEABg");
	this.shape.setTransform(-0.5,-11.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0B9444").s().p("AhBBjQgFgBAAgEIAAi3IABgFQABAAAAAAQABAAAAgBQABAAABAAQAAAAABAAIAaAAQAFAAAAAFIAAAKQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIADgBIAKgIQAFgEAHgDQAIgDAKABQARgBAOAJQANAIAIARQAHAQABAZQgBAagHARQgJASgNAIQgOAJgSAAQgKAAgKgDQgKgEgHgHIgEgCQAAAAAAAAQgBAAAAABQAAAAAAABQAAABAAABIAAAzQAAAEgEABgAgRhGQgIAEgEAFQgEAHAAAGIAABAQAHAHAHAEQAIAEAJAAQAJAAAJgFQAIgGAFgMQAFgLAAgUQAAgSgFgMQgFgLgIgFQgJgFgIAAQgKAAgGAEg");
	this.shape_1.setTransform(-12.2,-6.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0B9444").s().p("ABQBMIgEgBIgBgEIAAhgQAAgKgGgHQgFgGgLAAQgGAAgGADIgLAGIgIAHIgDAEIgBAEIAABeQAAAGgGAAIgYAAIgEgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAIAAhgQAAgKgFgHQgGgGgLAAQgJAAgJAFQgHAFgKAJIAABjQAAAGgGAAIgZAAQgFAAAAgFIAAiKQAAgFAEAAIAbAAQAEAAAAAFIAAAOIABACIADgBIAPgMQAHgFAIgDQAIgDAJAAQAQAAAJAIQAKAHAEALIACABIACgCIAPgMQAIgGAJgDQAJgDAIAAQAUAAAMALQALAMAAAVIAABkQAAAGgGAAg");
	this.shape_2.setTransform(-33.675,-9.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0B9444").s().p("Ag1BCQgMgMAAgSQAAgPAKgMQAIgKATgGQARgHAXgBIAOgBIAEgBIABgDIAAgGQAAgNgHgHQgHgGgOAAQgIAAgJAEQgIAEgGAKIgCACIgEAAIgXgGIgDgBIABgFQAJgQAPgIQARgIAYAAQAVAAANAGQAOAGAGAKQAGALAAAOIAABiIgBAEIgEABIgYAAQAAAAgBAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIgBgEIgBgJQgBgFgFAFQgJAIgLAFQgLAFgOAAQgVAAgNgLgAAQADIgRACQgIACgHAEQgGADgEAGQgDAFAAAHQAAAJAHAGQAGAFANAAQAGAAAGgCQAHgDAEgEIAIgIQADgEAAgFIAAgUQAAgEgEAAg");
	this.shape_3.setTransform(-54.85,-8.975);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0B9444").s().p("AgsBdQgVgNgLgYQgLgYAAggQAAghALgYQALgXAVgNQAVgNAbABQAQAAAOAEQANAFALAIQALAIAHALQAHALACANIAAAEIgCACIggADIgDgCIgBgDQgEgQgKgJQgKgKgSAAQgWAAgNASQgOATAAAnQAAAnANASQANASAYAAQASAAAMgIQAMgJAIgUQABgCAEABIAYAFIACACQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAABQgCAHgEAIQgEAHgHAIQgHAIgKAGQgJAHgNAEQgMAEgPAAQgcAAgVgOg");
	this.shape_4.setTransform(-72.0417,-11.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0B9444").s().p("Ag7BhQgFgBAAgDIAAgSIABgDIAHgBIASAAQAHAAAEgDQAEgEADgEQADgFACgEQABgFgCgEIg2iEQAAAAAAgBQgBgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAIAdAAIAEABIACADIAiBcQAAAAAAAAQAAABABAAQAAAAAAABQABAAAAAAQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAihcIADgDIADgBIAVAAQAAAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAAAQAAABgBABQAAAAAAABIg7CSQgFANgGAIQgFAIgHAFQgGAEgKACQgIABgMAAg");
	this.shape_5.setTransform(-95.85,-6.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0B9444").s().p("Ag1BCQgMgMAAgSQAAgPAKgMQAJgKASgGQARgHAYgBIANgBIAEgBIABgDIAAgGQAAgNgHgHQgHgGgNAAQgJAAgIAEQgJAEgGAKIgCACIgEAAIgXgGIgDgBIACgFQAHgQAQgIQARgIAYAAQAVAAANAGQAOAGAGAKQAGALAAAOIAABiIgBAEIgEABIgYAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgBgEIgBgJQgBgFgFAFQgJAIgLAFQgKAFgPAAQgVAAgNgLgAAQADIgRACQgIACgHAEQgFADgFAGQgDAFAAAHQAAAJAHAGQAHAFAMAAQAGAAAGgCQAHgDAEgEIAIgIQADgEAAgFIAAgUQAAgEgEAAg");
	this.shape_6.setTransform(-111.9,-8.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0B9444").s().p("AhOBoQgHAAABgGIAAjEQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBIAFgBIALAAIARAAIAQAAIALAAQAlABAZANQAYAMALAXQALAXAAAfQABAggMAYQgNAXgYANQgaAMgjAAgAgrhFIAACMQAAADAEABIAHAAQAZgBARgHQAQgIAIgPQAIgRAAgbQABgagJgQQgHgRgQgHQgQgHgZAAIgKAAQgBAAAAAAQgBAAAAABQgBAAAAABQAAABAAABg");
	this.shape_7.setTransform(-129.15,-11.95);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0B9444").s().p("AgnBMIgFgCIAAgEIAAiJQAAgFADAAIAbAAQAFAAAAAFIAAAQIAAADQABAAAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQAGgIAHgGQAGgFAIgDQAHgCAHAAQALgBgBAFIAAAaQAAAFgDgBIgJgCIgIAAQgGAAgFADQgHACgFADQgEAFgDAEQgDAFAAAFIAABVQAAAGgHAAg");
	this.shape_8.setTransform(-16.6,-34.05);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0B9444").s().p("AgjBEQgRgKgKgRQgJgRAAgWQAAgXAKgSQAKgSARgJQAQgKATAAQAWAAAQAJQAPAJAJASQAJARAAAYIAAAEQAAABgBAAQAAAAAAAAQgBABgBAAQAAAAgBAAIhiAAIgDABIAAADQAAAMAFAJQAFAJAKAFQAJAGAKAAQAMAAAJgFQAJgFAJgLIACgBIADABIARAHQADACgCADQgJANgJAHQgKAIgMADQgLADgPAAQgUAAgRgJgAgQgwQgIAGgEAJQgFAJAAALIBBAAIAEAAIABgEQAAgIgEgJQgEgIgIgGQgHgFgLAAQgKAAgJAFg");
	this.shape_9.setTransform(-31.025,-33.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0B9444").s().p("ABQBMIgEgBIgBgEIAAhgQAAgKgGgHQgFgGgLAAQgGAAgGADIgLAGIgIAHIgDAEIgBAEIAABeQAAAGgGAAIgYAAIgEgBQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIAAhgQAAgKgFgHQgGgGgLAAQgJAAgJAFQgHAFgKAJIAABjQAAAGgGAAIgZAAQgFAAAAgFIAAiKQAAgFAEAAIAbAAQAEAAAAAFIAAAOIABACIADgBIAPgMQAHgFAIgDQAIgDAJAAQAQAAAJAIQAKAHAEALIACABIACgCIAPgMQAIgGAJgDQAJgDAIAAQAUAAAMALQALAMAAAVIAABkQAAAGgGAAg");
	this.shape_10.setTransform(-51.925,-34.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0B9444").s().p("ABQBMIgEgBIgBgEIAAhgQAAgKgGgHQgFgGgLAAQgGAAgGADIgLAGIgIAHIgDAEIgBAEIAABeQAAAGgGAAIgYAAIgEgBQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIAAhgQAAgKgFgHQgGgGgLAAQgJAAgJAFQgHAFgKAJIAABjQAAAGgGAAIgZAAQgFAAAAgFIAAiKQAAgFAEAAIAbAAQAEAAAAAFIAAAOIABACIADgBIAPgMQAHgFAIgDQAIgDAJAAQAQAAAJAIQAKAHAEALIACABIACgCIAPgMQAIgGAJgDQAJgDAIAAQAUAAAMALQALAMAAAVIAABkQAAAGgGAAg");
	this.shape_11.setTransform(-77.475,-34.075);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0B9444").s().p("AgsBHQgJgGgGgKQgFgKgBgOIAAhkQAAgFAHAAIAZAAQAFgBAAAGIAABfQAAAKAGAHQAGAGALAAQAIAAAJgFQAJgGAIgIIAAhjQAAgFAGAAIAZAAQAFgBABAGIgBCKQAAAEgEAAIgbAAQgEAAAAgEIAAgPIgBgCIgCABQgNAMgMAGQgLAEgMAAQgMAAgLgEg");
	this.shape_12.setTransform(-98.65,-33.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0B9444").s().p("AggBnQgQgEgMgIQgMgJgHgLQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBABAAIACgDIASgNQADgCACAAIADACQAHAKAHAFQAHAGAJADQAJACANAAQASAAAMgGQAMgHAAgOQAAgFgCgFQgDgFgFgEQgGgDgKgEIgpgMQgRgGgKgHQgLgJgFgLQgFgMAAgMQAAgRAJgOQAKgOARgIQARgIAXABQAPgBANAEQANADALAHQALAGAHAKIACACQAAABAAAAQAAAAgBABQAAAAAAABQgBAAAAABIgUAOIgDABIgDgDQgHgHgKgFQgJgGgSAAQgRAAgKAIQgKAHAAAMIACAIQACAFAFAEQAGAEAKAEIAqAMQAaAIALAOQAMAPAAAUQAAATgKAOQgKAOgSAIQgSAGgZAAQgRAAgQgDg");
	this.shape_13.setTransform(-116.1562,-36.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141.9,-55.5,147.1,62.9);


(lib.lizart_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.lizart();
	this.instance.setTransform(-75,-52,0.7,0.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75,-52,179.2,24.5);


(lib.f = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.frog();
	this.instance.setTransform(-72,-41,0.36,0.36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72,-41,144,81);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXAzIgCAAIgBgCIAAhfQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIAAAMIAAABIACAAIAIgKIAKgGIAKgBQAHAAAAACIAAAMQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgEAAIgEgBQgFAAgEACIgIAFIgHAHQgDAEAAAEIAAA+QAAABAAABQAAAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape.setTransform(15.375,1.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAuQgLgHgGgMQgGgLAAgQQAAgOAGgMQAGgMALgHQALgGANAAQAPAAAKAGQALAHAGAMQAGAMAAAOQAAAPgGAMQgGAMgLAHQgKAGgPAAQgNAAgLgGgAgQgjQgHAFgEAJQgEAJAAAMQAAAMAEAJQAEAJAHAFQAIAFAIAAQAKAAAHgFQAHgFAEgJQAEgJAAgMQAAgMgEgJQgEgJgHgFQgHgFgKAAQgIAAgIAFg");
	this.shape_1.setTransform(5.575,1.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHBGQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhUQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgTAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgJIAAgBIACAAIASAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIAAgOQAAgMAGgGQAFgGALAAIAQAAQABAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAHIgBABIgBABIgNAAQgGAAgDAEQgCAEAAAGIAAANQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAWAAIABAAIABABIAAAJQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgVAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAABTQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAg");
	this.shape_2.setTransform(-3.65,-0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgqBDQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAh+IABgDIACAAIAKAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAHIABADIABgBIAGgGQADgDAHgDQAFgCAIAAQAMAAAJAGQAJAFAGAMQAGAKAAASQAAAPgGANQgFAMgKAGQgKAHgNAAQgHAAgIgEQgGgCgFgEIgCgCIgBADIAAAkQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAgAgPgzQgGADgEAGQgDAEAAAGIAAAtQAGAGAGAEQAHADAHAAQAIAAAHgFQAHgFAFgJQADgJAAgNQAAgOgDgJQgFgJgHgDQgHgFgHAAQgIAAgGAEg");
	this.shape_3.setTransform(-16.7,2.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgaAwQgGgEgEgHQgEgGAAgJIAAhFQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAABAAIAKAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAABCQAAAJAGAGQAFAGAKAAQAGAAAIgFQAHgEAIgIIAAhGQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAABAAIAKAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAABfQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAIgLAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAgLIAAgBIgBAAQgKAJgJAEQgHADgIAAQgIAAgIgDg");
	this.shape_4.setTransform(-28.2,1.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAcAzIgCAAIAAgCIAAhDQAAgJgGgGQgEgFgKAAQgGAAgDACQgGACgFADIgLAJIAABGQAAABAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgKAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAAAIAAhfQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAALIAAABIACgBIAMgIIALgGQAEgBAHAAQAOAAAJAIQAHAIABAMIAABGQAAABgBABQAAAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_5.setTransform(-43.15,1.125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnA9QgMgHAAgNQgBgGAFgGQAFgFAJgEQAAAAAAgBQABAAAAAAQAAAAgBgBQAAAAAAAAIgHgFQgCgDAAgEQAAgCACgDQABgCADgCIAIgEIABgBIgBgBQgHgEgEgHQgEgGAAgJQAAgOALgJQALgIAUAAQAJAAAHACQAHACAFAEIACABIACgBIAFgEIAGgDIAHgCIACABIABACIAAAHIgBADQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAAAAAIgGABIgEABQgFACABADIACAFIABAHQAAAJgFAHQgDAHgKAEQgJAEgNAAIgQABQgFABgCACQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAADAFACIANACIAXABQARABAIAHQAIAHAAALQAAAOgNAJQgNAIgWAAQgYAAgNgHgAgbAYQgEADgDADQgDAEAAAFQAAAGAEAFQAEAEAIACQAIACAMAAQAQAAAHgFQAJgEAAgKQAAgGgFgEQgEgEgKgBIgfgCQgDAAgFACgAgWgzQgHAGAAAKQAAAKAHAGQAHAFANAAQAMAAAGgFQAHgGAAgKQAAgKgHgGQgGgFgMAAQgNAAgHAFg");
	this.shape_6.setTransform(-54.45,2.775);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEBGIgDAAIAAgCIAAheQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABdIgBADIgDAAgAgFgvIgCgBIgBgCIAAgRQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQABAAAAAAQAAABABAAQAAABAAAAIAAAQQAAAEgEAAg");
	this.shape_7.setTransform(-62.375,-0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgTBFQgKgCgIgGQgHgEgFgIIgBgCIACgDIAHgEIADgCIABACQAFAGAFAEQAFAFAHACQAGABAJAAQAPAAAJgFQAKgFAAgNQAAgEgCgEQgCgFgFgCQgEgEgJgDIgcgKQgKgDgHgFQgGgGgDgHQgDgHAAgHQAAgMAGgJQAGgJALgFQALgEANAAQAKAAAIACQAIACAHAFQAGADAGAHIAAABIAAACIgJAHIgCAAIgCgBQgFgGgHgEQgIgFgMAAQgNABgIAGQgJAGAAALIACAIQABADAFAEQAEAEAJADIAaAJQASAFAHAJQAHAJAAANQAAAMgGAKQgGAIgLAEQgMAFgPABQgLAAgJgEg");
	this.shape_8.setTransform(-70.775,-0.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#167ABE").s().p("ArvCrQgyAAgkgkQgigigBgyIAAhlQABgyAigjQAkgjAyAAIXgAAQAxAAAjAjQAjAjAAAyIAABlQAAAygjAiQgjAkgxAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-87.2,-17.1,174.5,34.2);


(lib.bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,160,600);


(lib.turtle_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.tr("synched",0);
	this.instance.setTransform(-26.05,0,0.9362,0.9362,0,0,0,-0.6,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0,scaleX:1,scaleY:1,x:0},49,cjs.Ease.get(1)).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-165.9,-126.5,316.4,253.1);


(lib.snake_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(102,102,102,0.898)").s().p("AgmAmQgPgPAAgXQAAgVAPgRQAQgPAWAAQAXAAAPAPQAQARAAAVQAAAXgQAPQgPAQgXAAQgWAAgQgQg");
	this.shape.setTransform(8.55,-2.05);
	this.shape._off = true;

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(102,102,102,0.898)").s().p("AgiAjQgQgNgCgSQAAgUAPgPQAPgPAVgBQAHAAAIACQAMADAJAJQALAKAEANQACAGABAFQABANgGALQgEAGgFAEQgQANgVAAQgUAAgQgNg");
	this.shape_1.setTransform(8.5077,-2.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(102,102,102,0.898)").s().p("AAFApQgTAAgQgKQgPgKgGgOIAAAAQABgSAOgOQAOgOAVgBQAGgBAHACQAMACAJAIQALAJAFAMQACAFABAFQACAMgEALIgJAHQgPAJgTAAIgCAAg");
	this.shape_2.setTransform(8.4475,-3.28);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(102,102,102,0.898)").s().p("AAHAjQgSAAgQgIQgPgHgIgJIgBAAQACgRANgNQAOgOATgBQAGgBAGACQAMABAJAHQALAHAGAMIAEAJQACALgCAKIgKAFQgOAGgSAAIgCAAg");
	this.shape_3.setTransform(8.4444,-3.8795);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(102,102,102,0.898)").s().p("AAIAdQgRAAgPgFQgQgEgKgFIgBAAQACgPAMgNQAOgNASgCIALABQALABAJAFQALAGAHALIAEAIQAEAKgBAKIgKACQgNADgQAAIgEAAg");
	this.shape_4.setTransform(8.46,-4.5052);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(102,102,102,0.898)").s().p("AAJAWQgPAAgPgCIgdgBIgBAAQADgPALgLQAMgMASgDQAFAAAFAAQALAAAIAFQALAFAIAJIAFAHQAFAJABAKIgKAAIgKAAIgXgBg");
	this.shape_5.setTransform(8.5,-5.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(102,102,102,0.898)").s().p("AgzAUQADgOAKgJQAQgQAWAAQAXAAAPAQQALAJADAOQgzgMg0AMg");
	this.shape_6.setTransform(8.55,-5.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},6).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[]},1).wait(21));
	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6).to({_off:false},0).wait(7).to({_off:true},1).wait(27));

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_6 = new cjs.Graphics().p("Ak9hTIChiwIHaD+IgqEJQllgXjslAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(6).to({graphics:mask_graphics_6,x:54.9875,y:32.5}).wait(16).to({graphics:null,x:0,y:0}).wait(19));

	// Layer_2
	this.instance = new lib.tg("synched",0);
	this.instance.setTransform(40.35,4.35,1,1,-29.9992);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(6).to({_off:false},0).to({rotation:-30.9912,x:62.85,y:17.6},7,cjs.Ease.get(1)).wait(1).to({rotation:-31.0292,x:62.6986,y:17.5149},0).wait(1).to({regX:0.1,regY:0.1,rotation:-31.1431,x:62.3,y:17.25},0).wait(1).to({regX:0,regY:0,rotation:-31.5024,x:60.502,y:16.3438},0).wait(1).to({rotation:-32.0731,x:57.8845,y:14.9841},0).wait(1).to({rotation:-32.8551,x:54.2976,y:13.1207},0).wait(1).to({rotation:-33.8486,x:49.7413,y:10.7537},0).wait(1).to({rotation:-35.0533,x:44.2156,y:7.8832},0).wait(1).to({rotation:-36.4695,x:37.85,y:4.6},0).to({_off:true},1).wait(19));

	// Layer_1
	this.instance_1 = new lib.snake();
	this.instance_1.setTransform(-148.6,-96.9,0.9316,0.9316);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-148.6,-96.9,297.2,193.8);


(lib.Frog = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.instance = new lib.f("synched",0);
	this.instance.setTransform(-119.2,-10.2,0.24,0.24,0,0,0,0,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:-0.5,scaleX:0.3844,scaleY:0.3844,x:-133.1,y:-18.75},0).wait(1).to({regX:-0.1,regY:-0.3,scaleX:0.5136,scaleY:0.5136,x:-145.6,y:-26.25},0).to({regY:-0.4,scaleX:0.81,scaleY:0.6866,x:-163.7,y:-20.5},1).wait(1).to({regX:0,regY:-0.5,scaleX:0.9525,scaleY:0.9216,x:-174.45,y:-12.9},0).wait(1).to({regY:0,scaleX:1,scaleY:1,x:-178.2,y:-10.2},0).wait(16));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-250.2,-51.2,148.29999999999998,81);


// stage content:
(lib.KSFY_216373_MM_160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgMfgu3IY/AAMAAABdvI4/AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(168));

	// t3
	this.instance = new lib.t3("synched",0);
	this.instance.setTransform(80.05,449.8,0.7,0.7,0,0,0,-69.9,-30.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(62).to({_off:false},0).to({regY:-30.6,scaleX:1,scaleY:1,x:80.1,y:449.75,alpha:1},12,cjs.Ease.get(1)).wait(94));

	// t2
	this.instance_1 = new lib.t2("synched",0);
	this.instance_1.setTransform(80.25,309.05,0.7,0.7,0,0,0,-68.5,-43.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(45).to({_off:false},0).to({regY:-43.6,scaleX:1,scaleY:1,y:309,alpha:1},12,cjs.Ease.get(1)).wait(111));

	// t1
	this.instance_2 = new lib.t1("synched",0);
	this.instance_2.setTransform(86,259.15,0.7,0.7,0,0,0,-63.1,-20);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(26).to({_off:false},0).to({regY:-20.1,scaleX:1,scaleY:1,y:259.1,alpha:1},13,cjs.Ease.get(1)).wait(129));

	// lizart_png
	this.instance_3 = new lib.lizart_png("synched",0);
	this.instance_3.setTransform(11,422.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:46,y:415.5},104,cjs.Ease.get(1)).wait(64));

	// snake_png
	this.instance_4 = new lib.snake_1("synched",0);
	this.instance_4.setTransform(81.95,551.85,0.77,0.77);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(168));

	// turtle_png
	this.instance_5 = new lib.turtle_1("synched",0,false);
	this.instance_5.setTransform(32.45,106.65,0.648,0.648,0,0,0,0,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(168));

	// Frog
	this.instance_6 = new lib.Frog("synched",0,false);
	this.instance_6.setTransform(244.95,193.85,0.7,0.7);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(14).to({_off:false},0).wait(154));

	// Cta
	this.instance_7 = new lib.cta("synched",0);
	this.instance_7.setTransform(-72.8,204.35,0.81,0.81,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({x:77.2},13,cjs.Ease.get(1)).wait(155));

	// BG_jpg
	this.instance_8 = new lib.bg("synched",0);
	this.instance_8.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(168));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-63.5,299,259.9,327.4);
// library properties:
lib.properties = {
	id: '9FDEB53A9669492982F620CA953230C7',
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"frog.png", id:"frog"},
		{src:"lizart.png", id:"lizart"},
		{src:"snake.png", id:"snake"},
		{src:"Tounge.png", id:"Tounge"},
		{src:"turtle.png", id:"turtle"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['9FDEB53A9669492982F620CA953230C7'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;