(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgZAwQgMgHgHgMQgHgMAAgQQAAgQAIgMQAHgNAMgHQAMgHANAAQAPAAAMAHQALAGAGANQAHAMAAARIgBACQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAgBAAIhFAAIgCABIgBACQAAAJAEAGQAEAGAHAEQAGAEAHAAQAJAAAGgDQAHgEAGgIIABgBIACABIANAFQAAABABAAQAAAAAAABQAAAAAAABQAAAAgBABQgGAJgHAFQgHAGgIACQgIACgLAAQgOAAgMgHgAgLgiQgGAEgDAGQgDAHAAAIIAuAAIADAAIAAgCQAAgHgDgGQgCgGgGgEQgFgDgIAAQgHAAgGADg");
	this.shape.setTransform(41.025,-11.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgcAwQgMgFgFgKIgBgDIABgBIAMgGIADgBIABABIAHAHQAEAEAGACQAFACAIAAQAGAAAFgCQAFgBADgEQADgCAAgEQAAgFgDgCQgEgEgJgCIgTgEQgPgEgHgGQgHgHAAgLQAAgKAFgIQAFgHAKgFQAKgEAMAAQAPAAALAFQALAGAFAIIABACIgBACIgNAGIgCAAIgCgBQgEgFgGgDQgGgEgJABQgIgBgFAEQgGADAAAGQAAADACADQADADAIACIAXAGQAPAFAHAGQAHAJAAAKQAAAKgGAHQgGAIgLAEQgKAEgOAAQgQAAgMgHg");
	this.shape_1.setTransform(29.225,-11.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AglAvQgJgIAAgNQAAgLAHgIQAGgIANgEQAMgFARAAIAKgBIACgBIABgCIAAgEQAAgJgFgGQgFgEgJAAQgGAAgGADQgGADgFAHIgBABIgDAAIgRgDIgBgCIABgDQAFgMAMgFQAMgGAQAAQAPAAAKAEQAJAFAFAHQAEAIAAAKIAABFIgBADIgCABIgRAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgBgEIAAgGQAAgBgBAAQAAAAAAAAQgBAAgBAAQAAAAgBABQgHAGgIAEQgHADgKAAQgPAAgJgIgAALACQgHAAgEABIgLAFQgEACgDAEQgCADAAAFQAAAHAEAFQAFADAJAAQAEAAAFgBQAEgCAEgDIAFgGQACgDAAgDIAAgPQAAAAAAgBQAAgBAAAAQgBgBAAAAQgBAAgBAAg");
	this.shape_2.setTransform(17.575,-11.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAZBKIgDgBIgBgCIAAhFQAAgHgEgEQgEgFgIAAQgFAAgDACIgIAEIgJAIIAABGQAAAEgFAAIgRAAQgEAAAAgDIAAiNQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAUAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAA0IABABIABAAIANgJQAFgEAFgBQAFgCAGAAQAQAAAIAJQAIAIAAAPIAABHQAAAEgEAAg");
	this.shape_3.setTransform(5.925,-13.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgWAwQgMgHgHgMQgHgNAAgPQAAgQAHgMQAHgNAMgHQAMgHAOAAQAMAAAIAEQAJAEAGAGQAGAHADAHQAAABAAABQAAABAAAAQAAABgBAAQAAAAgBAAIgSADQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBgBgBIgFgHQgDgDgEgDQgDgBgFAAQgHAAgGADQgHAFgDAJQgDAIAAALQAAAMADAJQAEAIAGAFQAGAEAIAAQAJAAAGgFQAFgFAFgIIACgBIACAAIAMADQABABAAAAQAAAAABABQAAAAAAABQAAAAgBABIgFAKQgEAFgFAFQgGAEgHADQgIACgJAAQgPAAgLgHg");
	this.shape_4.setTransform(-6.0333,-11.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgcA2IgDgBIgBgDIAAhiQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIATAAQABAAAAAAQABAAAAABQAAAAAAABQAAAAABABIAAAMIAAACIACgBQAEgGAEgEIALgGQAFgCAGAAQAGAAAAADIAAATQAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgHgCIgFAAIgIACQgFABgEADIgEAHQgCADgBAEIAAA8QAAAEgEAAg");
	this.shape_5.setTransform(-15.9,-11.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgfAyQgHgEgEgHQgEgHAAgJIAAhIQAAgEAEAAIATAAQADAAAAAEIAABDQAAAHAEAFQAFAFAHAAQAGAAAHgEQAGgEAGgGIAAhGQAAgEAEAAIASAAQAEAAAAAEIAABiQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAIgUAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgLIAAgBIgCABQgJAIgIAFQgIADgJAAQgJAAgHgEg");
	this.shape_6.setTransform(-26.925,-11.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("Ag2BKIgDgBIAAgCIAAiNQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIA3AAQAQAAANAFQANAEAIAKQAHALAAAPQAAAPgHAKQgGAJgMAFQgMAFgQAAIgfAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIAAA0QAAAEgEAAgAgcgxIAAApQAAABAAAAQABABAAAAQAAABABAAQAAAAABAAIAaAAQAMAAAIgGQAHgGAAgMQAAgIgEgFQgDgFgHgCQgGgDgIAAIgYAAQgBAAgBAAQAAABgBAAQAAAAgBABQAAABAAAAg");
	this.shape_7.setTransform(-40.025,-13.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgsBCQgOgHAAgNQAAgHAGgFQAFgFAIgEQABAAAAAAQAAAAAAgBQAAAAAAAAQAAAAgBgBQgEgCgDgDQgDgEAAgEQAAgEACgDIAGgFIAKgFIABgBIgBgBQgJgEgFgHQgFgHAAgJQAAgPANgJQAMgJAYAAQAKAAAIACQAHACAFAFIADABIADgCIAFgFIAIgEIAHgBIACABQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAALQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAIgDABIgFAAIgFABQgFABABADIACAFIABAGQAAAJgFAHQgFAIgLAEQgKAEgPAAIgOABQgFABgCACQgBAAAAAAQAAAAgBABQAAAAAAABQAAAAAAABQAAADADABIALABIAbACQATABAJAIQAJAHAAANQAAAPgOAJQgOAJgaAAQgbAAgPgGgAgbAeIgGAFQgDADAAAEQAAAFAEAEQAEAEAIACQAIACAMAAQAOAAAIgEQAHgEAAgIQAAgFgEgEQgEgDgJgBIgfgBIgIABgAgUgyQgGAFAAAJQAAAIAGAGQAGAFALAAQALAAAFgFQAGgGAAgIQAAgJgGgFQgFgGgLAAQgLAAgGAGg");
	this.shape_8.setTransform(44.475,-34.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAZA2IgDgBIgBgDIAAhDQAAgIgEgFQgEgEgJAAQgEAAgDABQgFACgEADIgIAIIAABGQAAAEgFAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAhiQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAUAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAALIABABIABgBIAMgIIAKgGQAGgCAGAAQAPAAAJAJQAIAIAAAOIAABIQAAAEgEAAg");
	this.shape_9.setTransform(31.925,-36.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgIBKQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgBgCIAAhiQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAUAAQAAAAABAAQAAABAAAAQABAAAAABQAAABAAAAIAABiIgBADIgDABgAgIguIgEgBIgBgDIAAgTQAAgEAEAAIAUAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAUQAAAEgEAAg");
	this.shape_10.setTransform(22.8,-38.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgqBFQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgNIABgCIAFAAIANAAQAEgBADgCQADgCACgEQADgCAAgEQABgDgBgDIgnheQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAQABAAAAAAIAVAAIADABIABACIAYBBIACABQAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAZhBIABgCIADgBIAOAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAIgqBpQgEAJgEAGQgDAFgFAEQgFADgHACIgOAAg");
	this.shape_11.setTransform(14.1417,-34.85);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgLBKQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAhSQAAAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAAAIgQAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgNIAAgCIADgBIAPAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAgBAAAAIAAgNQAAgNAHgHQAHgHANAAIASAAQAEAAABADIAAAMIgBACIgCAAIgMAAQgFAAgDAEQgDAEABAFIAAAKQAAABAAAAQAAAAAAABQAAAAABAAQAAAAABAAIASAAIADABIAAACIAAANQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAIgSAAQAAAAgBAAQAAABgBAAQAAAAAAAAQAAABAAAAIAABSQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_12.setTransform(4.15,-38.625);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgIBKQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgBgCIAAhiQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIATAAQABAAABAAQAAABAAAAQABAAAAABQAAABAAAAIAABiIgBADIgEABgAgJguIgCgBIgBgDIAAgTQgBgEAEAAIATAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAUQgBAEgFAAg");
	this.shape_13.setTransform(-3,-38.625);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgIBKQgEAAAAgDIAAiNQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIASAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAACMIgBADIgDABg");
	this.shape_14.setTransform(-8.7,-38.625);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AglAvQgJgIAAgNQAAgLAHgIQAGgIANgEQAMgFARAAIAKgBIACgBIABgCIAAgEQAAgJgFgGQgFgEgJAAQgGAAgGADQgGADgFAHIgBABIgDAAIgRgDIgBgCIABgDQAFgMAMgFQAMgGAQAAQAPAAAKAEQAJAFAFAHQAEAIAAAKIAABFIgBADIgCABIgRAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgBgEIAAgGQAAgBgBAAQAAAAAAAAQgBAAgBAAQAAAAgBABQgHAGgIAEQgHADgKAAQgPAAgJgIgAALACQgHAAgEABIgLAFQgEACgDAEQgCADAAAFQAAAHAEAFQAFADAJAAQAEAAAFgBQAEgCAEgDIAFgGQACgDAAgDIAAgPQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBAAgBAAg");
	this.shape_15.setTransform(-17.775,-36.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgfAyQgHgEgEgHQgEgHAAgJIAAhIQAAgEAEAAIATAAQADAAAAAEIAABDQAAAHAEAFQAFAFAHAAQAGAAAHgEQAGgEAGgGIAAhGQAAgEAEAAIASAAQAEAAAAAEIAABiQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgUAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgLIAAgBIgCABQgJAIgIAFQgIADgJAAQgJAAgHgEg");
	this.shape_16.setTransform(-29.525,-36.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAlBSQgKgGgJgMQAAAAgBAAQAAgBAAAAQgBAAAAAAQgBAAAAABIgHAAIgIABQgTAAgQgJQgPgJgIgRQgIgRAAgXQAAgYAIgRQAJgRAPgKQAPgJATAAQAUAAAPAJQAPAKAIARQAJARAAAYQAAAVgHAPQgHAPgMAKIAAACQAAACADADIAIAFQAGADAFAAIACABIABACIAAAOQAAABAAAAQAAABgBAAQAAABAAAAQAAABgBAAIgFABQgLAAgLgGgAgag0QgJAOAAAcQAAAcAJANQAJANARAAQASAAAJgNQAJgNAAgcQAAgcgJgOQgJgOgSAAQgRAAgJAOg");
	this.shape_17.setTransform(-43.625,-37.475);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAZBKIgDgBIgBgCIAAhFQAAgHgEgEQgEgFgIAAQgFAAgDACIgIAEIgJAIIAABGQAAAEgFAAIgRAAQgEAAAAgDIAAiNQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAUAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAA0IABABIABAAIANgJQAFgEAFgBQAFgCAGAAQAQAAAIAJQAIAIAAAPIAABHQAAAEgEAAg");
	this.shape_18.setTransform(65.275,-63.825);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAKBHQgMAAgHgHQgIgFAAgOIAAg6QAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAgBAAIgOAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgNQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAABgBQAAAAAAAAQAAgBAAAAIACgfQABgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAQAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAfQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIAXAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAANQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgXAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIAAA1QAAAHACADQAEAEAGAAIANAAIACABIAAABIAAALQAAADgEABIgHABIgHAAg");
	this.shape_19.setTransform(54.5,-63.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgIBKQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgBgCIAAhiQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAUAAQAAAAABAAQAAABAAAAQABAAAAABQAAABAAAAIAABiIgBADIgEABgAgJguIgDgBIAAgDIAAgTQAAgEADAAIAUAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAUQAAAEgGAAg");
	this.shape_20.setTransform(47.25,-63.825);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAiBKQgEAAgBgDIgchgIgBgBIAAABIgcBfQgBAEgEAAIgTAAQgEAAgCgDIgoiLQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAVAAIADABIABACIAcBjIACACIABgCIAchjIABgCIAEgBIARAAIADABIABACIAdBkIABABIABgBIAchkIACgCIADgBIAPAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABQAAABAAAAIgpCKQgBAEgEAAg");
	this.shape_21.setTransform(33.425,-63.825);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgcA2IgCgBIgBgDIAAhiQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIATAAQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAMIABACIACgBQAEgGAFgEIAKgGQAGgCAFAAQAHAAAAADIAAATQAAABgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgGgCIgHAAIgIACQgEABgEADIgEAHQgDADAAAEIAAA8QABAEgFAAg");
	this.shape_22.setTransform(13.65,-61.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgZAwQgMgHgHgMQgHgMAAgQQAAgQAIgMQAHgNAMgHQAMgHANAAQAPAAAMAHQALAGAGANQAHAMAAAQIgBADQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAgBAAIhFAAIgCABIgBACQAAAJAEAGQAEAGAHAEQAGAEAHAAQAJAAAGgDQAHgEAGgIIABgBIACABIANAFQAAABABAAQAAAAAAABQAAAAAAABQAAAAgBABQgGAJgHAFQgHAGgIACQgIACgLAAQgOAAgMgHgAgLgiQgGAEgDAGQgDAHAAAIIAuAAIADAAIAAgCQAAgHgDgGQgCgGgGgEQgFgDgIAAQgHAAgGADg");
	this.shape_23.setTransform(2.775,-61.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAZBKIgDgBIgBgCIAAhFQAAgHgEgEQgEgFgIAAQgFAAgDACIgIAEIgJAIIAABGQAAAEgFAAIgRAAQgEAAAAgDIAAiNQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAUAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAA0IABABIABAAIANgJQAFgEAFgBQAFgCAGAAQAQAAAIAJQAIAIAAAPIAABHQAAAEgEAAg");
	this.shape_24.setTransform(-9.525,-63.825);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgWAwQgMgHgHgMQgHgNAAgQQAAgPAHgMQAHgNAMgHQAMgHAOAAQAMAAAIAEQAJAEAGAGQAGAHADAIQAAAAAAABQAAABAAAAQAAABgBAAQAAAAgBAAIgSADQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBgBgBIgFgHQgDgDgEgCQgDgCgFAAQgHAAgGADQgHAFgDAJQgDAIAAALQAAAMADAJQAEAIAGAFQAGAEAIAAQAJAAAGgFQAFgFAFgIIACgBIACAAIAMADQABABAAAAQAAAAABABQAAAAAAABQAAAAgBABIgFAKQgEAFgFAEQgGAFgHADQgIACgJAAQgPAAgLgHg");
	this.shape_25.setTransform(-21.4833,-61.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgfAyQgHgEgEgHQgEgHAAgJIAAhIQAAgEAEAAIATAAQADAAAAAEIAABDQAAAHAEAFQAFAFAHAAQAGAAAHgEQAGgEAGgGIAAhGQAAgEAEAAIASAAQAEAAAAAEIAABiQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgUAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgLIAAgBIgCABQgJAIgIAFQgIADgJAAQgJAAgHgEg");
	this.shape_26.setTransform(-33.575,-61.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgaAwQgMgHgHgNQgHgMAAgQQAAgPAHgMQAHgNAMgHQAMgHAOAAQAQAAAMAHQAMAIAGAMQAHAMAAAPQAAAQgHAMQgHANgLAHQgMAHgQAAQgPAAgLgHgAgNghQgGAFgDAJQgDAIAAALQAAAMADAIQADAJAGAEQAGAEAHAAQAJAAAGgEQAFgEADgJQADgIAAgMQAAgLgDgIQgDgJgGgFQgFgEgJAAQgHAAgGAEg");
	this.shape_27.setTransform(-45.975,-61.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgKBKQgEAAgBgDIgxiMQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAXAAQAEAAABADIAjBrQAAABAAAAQAAABABAAQAAAAAAgBQABAAAAgBIAjhrQABgDADAAIATAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABIgxCLQgBAEgEAAg");
	this.shape_28.setTransform(-59.75,-63.825);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAZA2IgDgBIgBgDIAAhDQAAgIgEgFQgEgEgJAAQgEAAgDABQgFACgEADIgIAIIAABGQAAAEgFAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAhiQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAUAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAALIABABIABgBIAMgIIAKgGQAGgCAGAAQAPAAAJAJQAIAIAAAOIAABIQAAAEgEAAg");
	this.shape_29.setTransform(40.775,-87);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgaAwQgMgHgHgNQgHgMAAgPQAAgQAHgMQAHgNAMgHQAMgHAOAAQAQAAAMAHQAMAIAGAMQAHAMAAAQQAAAPgHAMQgHANgLAHQgMAHgQAAQgPAAgLgHgAgNghQgGAFgDAJQgDAIAAALQAAAMADAIQADAJAGAEQAGAEAHAAQAJAAAGgEQAFgEADgJQADgIAAgMQAAgLgDgIQgDgJgGgFQgFgEgJAAQgHAAgGAEg");
	this.shape_30.setTransform(28.225,-86.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgIBKQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgBgCIAAhiQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAUAAQAAAAABAAQAAABAAAAQABAAAAABQAAABAAAAIAABiIgBADIgDABgAgIguIgEgBIgBgDIAAgTQABgEADAAIAUAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAUQAAAEgEAAg");
	this.shape_31.setTransform(19.1,-89.025);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAKBHQgMAAgHgHQgIgFAAgOIAAg6QAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAgBAAIgOAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAgNQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAABgBQAAAAAAAAQAAgBAAAAIACgfQABgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAQAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAfQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIAXAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAANQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgXAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIAAA1QAAAHACADQAEAEAGAAIANAAIACABIAAABIAAALQAAADgEABIgHABIgHAAg");
	this.shape_32.setTransform(11.75,-88.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AglAvQgJgIAAgNQAAgLAHgIQAGgIANgEQAMgFARAAIAKgBIACgBIABgCIAAgEQAAgJgFgGQgFgEgJAAQgGAAgGADQgGADgFAHIgBABIgDAAIgRgDIgBgCIABgDQAFgMAMgFQAMgGAQAAQAPAAAKAEQAJAFAFAHQAEAIAAAKIAABFIgBADIgCABIgRAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgBgEIAAgGQAAgBgBAAQAAAAAAAAQgBAAgBAAQAAAAgBABQgHAGgIAEQgHADgKAAQgPAAgJgIgAALACQgHAAgEABIgLAFQgEACgDAEQgCADAAAFQAAAHAEAFQAFADAJAAQAEAAAFgBQAEgCAEgDIAFgGQACgDAAgDIAAgPQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBAAgBAAg");
	this.shape_33.setTransform(1.125,-86.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgWAwQgMgHgHgMQgHgNAAgPQAAgQAHgMQAHgNAMgHQAMgHAOAAQAMAAAIAEQAJAEAGAGQAGAHADAHQAAABAAABQAAABAAAAQAAABgBAAQAAAAgBAAIgSADQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBgBgBIgFgHQgDgDgEgDQgDgBgFAAQgHAAgGADQgHAFgDAJQgDAIAAALQAAAMADAJQAEAIAGAFQAGAEAIAAQAJAAAGgFQAFgFAFgIIACgBIACAAIAMADQABABAAAAQAAAAABABQAAAAAAABQAAAAgBABIgFAKQgEAFgFAFQgGAEgHADQgIACgJAAQgPAAgLgHg");
	this.shape_34.setTransform(-10.0833,-86.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AglAvQgJgIAAgNQAAgLAHgIQAGgIANgEQAMgFARAAIAKgBIACgBIABgCIAAgEQAAgJgFgGQgFgEgJAAQgGAAgGADQgGADgFAHIgBABIgDAAIgRgDIgBgCIABgDQAFgMAMgFQAMgGAQAAQAPAAAKAEQAJAFAFAHQAEAIAAAKIAABFIgBADIgCABIgRAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgBgEIAAgGQAAgBgBAAQAAAAAAAAQgBAAgBAAQAAAAgBABQgHAGgIAEQgHADgKAAQgPAAgJgIgAALACQgHAAgEABIgLAFQgEACgDAEQgCADAAAFQAAAHAEAFQAFADAJAAQAEAAAFgBQAEgCAEgDIAFgGQACgDAAgDIAAgPQAAAAAAgBQAAgBgBAAQAAgBAAAAQgBAAgBAAg");
	this.shape_35.setTransform(-22.175,-86.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgKBKQgEAAgBgDIgxiMQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAXAAQADAAACADIAjBrQAAABAAAAQAAABABAAQAAAAAAgBQABAAAAgBIAkhrQAAgDADAAIATAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABIgxCLQgBAEgEAAg");
	this.shape_36.setTransform(-35.2,-89.025);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgKAzQgDAAAAgEIAAgWQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAABAAIAXAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAAWQAAAEgGAAgAgKgVQgDAAAAgEIAAgWQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIAXAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAABIAAAWQAAAEgGAAg");
	this.shape_37.setTransform(31.3,-111.975);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgcAwQgMgFgFgKIgBgDIABgBIAMgGIADgBIABABIAHAHQAEAEAGACQAFACAIAAQAGAAAFgCQAFgBADgEQADgCAAgEQAAgFgDgCQgEgEgJgCIgTgEQgPgEgHgGQgHgHAAgLQAAgKAFgIQAFgHAKgFQAKgEAMAAQAPAAALAFQALAGAFAIIABACIgBACIgNAGIgCAAIgCgBQgEgFgGgDQgGgEgJABQgIgBgFAEQgGADAAAGQAAADACADQADADAIACIAXAGQAPAFAHAGQAHAJAAAKQAAAKgGAHQgGAIgLAEQgKAEgOAAQgQAAgMgHg");
	this.shape_38.setTransform(23.025,-112.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgfAyQgHgEgEgHQgEgHAAgJIAAhIQAAgEAEAAIATAAQADAAAAAEIAABDQAAAHAEAFQAFAFAHAAQAGAAAHgEQAGgEAGgGIAAhGQAAgEAEAAIASAAQAEAAAAAEIAABiQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAIgUAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgLIAAgBIgCABQgJAIgIAFQgIADgJAAQgJAAgHgEg");
	this.shape_39.setTransform(11.375,-112);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAZA2IgDgBIgBgDIAAhDQAAgIgEgFQgEgEgJAAQgEAAgDABQgFACgEADIgIAIIAABGQAAAEgFAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAhiQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAUAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAALIABABIABgBIAMgIIAKgGQAGgCAGAAQAPAAAJAJQAIAIAAAOIAABIQAAAEgEAAg");
	this.shape_40.setTransform(-0.875,-112.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgaAwQgMgHgHgNQgHgMAAgQQAAgPAHgMQAHgNAMgHQAMgHAOAAQAQAAAMAHQAMAIAGAMQAHAMAAAPQAAAQgHAMQgHANgLAHQgMAHgQAAQgPAAgLgHgAgNghQgGAFgDAJQgDAIAAALQAAAMADAIQADAJAGAEQAGAEAHAAQAJAAAGgEQAFgEADgJQADgIAAgMQAAgLgDgIQgDgJgGgFQgFgEgJAAQgHAAgGAEg");
	this.shape_41.setTransform(-13.425,-112.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("Ag3BKIgCgBIAAgCIAAiMIABgDIACgBIA0AAQAbAAAPAKQAPAKAAATQAAALgGAIQgGAIgOAFIgBABIABABQAPAEAIAIQAGAIABAOQAAAUgPAKQgQAKgcAAgAgcANIAAAlQAAABAAABQAAAAABABQAAAAAAABQABAAAAAAIAZAAQAOAAAHgGQAIgGAAgKQAAgIgEgFQgDgFgHgCQgGgCgIAAIgZAAQAAAAgBAAQgBAAAAABQgBAAAAAAQAAABAAABgAgcgyIAAAkQAAABAAABQAAAAABABQAAAAAAABQABAAAAAAIAaAAIAJgBQAFgBADgDIAHgGQABgEAAgGQAAgLgHgFQgIgGgMAAIgXAAQAAAAgBAAQgBABAAAAQgBAAAAABQAAAAAAABg");
	this.shape_42.setTransform(-26.85,-114.225);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAKBHQgMAAgIgHQgGgFgBgOIAAg6QAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAgBAAIgNAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAgNQAAAAABgBQAAAAAAAAQABgBAAAAQABAAABAAIAOAAQABAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIADgfQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAIARAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAfQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABAAIAWAAQABAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAANQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgWAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAIAAA1QAAAHAEADQADAEAHAAIALAAIACABIABABIAAALQAAADgEABIgHABIgIAAg");
	this.shape_43.setTransform(31.85,-139.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgcAwQgMgFgFgKIgBgDIABgBIAMgGIADgBIABABIAHAHQAEAEAGACQAFACAIAAQAGAAAFgCQAFgBADgEQADgCAAgEQAAgFgDgCQgEgEgJgCIgTgEQgPgEgHgGQgHgHAAgLQAAgKAFgIQAFgHAKgFQAKgEAMAAQAPAAALAFQALAGAFAIIABACIgBACIgNAGIgCAAIgCgBQgEgFgGgDQgGgEgJABQgIgBgFAEQgGADAAAGQAAADACADQADADAIACIAXAGQAPAFAHAGQAHAJAAAKQAAAKgGAHQgGAIgLAEQgKAEgOAAQgQAAgMgHg");
	this.shape_44.setTransform(21.825,-137.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgfAyQgHgEgEgHQgEgHAAgJIAAhIQAAgEAEAAIATAAQADAAAAAEIAABDQAAAHAEAFQAFAFAHAAQAGAAAHgEQAGgEAGgGIAAhGQAAgEAEAAIASAAQAEAAAAAEIAABiQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgUAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgLIAAgBIgCABQgJAIgIAFQgIADgJAAQgJAAgHgEg");
	this.shape_45.setTransform(10.175,-137.2);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgsBCQgOgHAAgNQAAgHAGgFQAFgFAIgEQABAAAAAAQABAAAAgBQAAAAgBAAQAAAAgBgBQgEgCgDgDQgDgEAAgEQAAgEACgDIAGgFIAKgFIABgBIgBgBQgJgEgFgHQgFgHAAgJQAAgPANgJQAMgJAYAAQAKAAAIACQAHACAFAFIADABIADgCIAFgFIAIgEIAHgBIACABQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAALQAAAAAAABQAAAAgBABQAAAAAAABQAAAAgBAAIgDABIgFAAIgFABQgFABABADIACAFIABAGQAAAJgFAHQgFAIgLAEQgKAEgPAAIgOABQgFABgCACQgBAAAAAAQAAAAgBABQAAAAAAABQAAAAAAABQAAADADABIALABIAbACQATABAJAIQAJAHAAANQAAAPgOAJQgOAJgaAAQgbAAgPgGgAgbAeIgGAFQgDADAAAEQAAAFAEAEQAEAEAIACQAIACAMAAQAOAAAIgEQAHgEAAgIQAAgFgEgEQgEgDgJgBIgfgBIgIABgAgUgyQgGAFAAAJQAAAIAGAGQAGAFALAAQALAAAFgFQAGgGAAgIQAAgJgGgFQgFgGgLAAQgLAAgGAGg");
	this.shape_46.setTransform(-2.525,-135.725);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgfAyQgHgEgEgHQgEgHAAgJIAAhIQAAgEAEAAIATAAQADAAAAAEIAABDQAAAHAEAFQAFAFAHAAQAGAAAHgEQAGgEAGgGIAAhGQAAgEAEAAIASAAQAEAAAAAEIAABiQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAIgUAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgLIAAgBIgCABQgJAIgIAFQgIADgJAAQgJAAgHgEg");
	this.shape_47.setTransform(-15.175,-137.2);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AApBKQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAIgMghIAAgBIgCgBIgzAAQgBAAAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIgMAhIgBACIgCAAIgUAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAyiLIACgCIADgBIAYAAQAEAAACAEIAyCKIAAAEQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAgAgDgpIgTA0QAAABAAABQAAAAAAABQAAAAAAABQABAAAAAAIAmAAQAAAAABAAQAAgBABAAQAAgBAAAAQAAgBgBgBIgSg0IgBgBIgCABg");
	this.shape_48.setTransform(-29.1375,-139.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.2,-153.3,152.4,154.20000000000002);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(64.375,3.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAWAtQgDAAgBgDIgRg0IgBgBIAAABIgQA1IgCACIgCAAIgNAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIgchTIAAgCIADgBIAQAAIACAAIACACIARA2QAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAABAAIABgBIARg2IABgCIACAAIALAAIACAAIABACIARA2IACABIABgBIAQg2IACgCIACAAIALAAIACABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAIgbBUIgBACIgDAAg");
	this.shape_1.setTransform(51.7875,3.475);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgXApQgKgGgFgKQgGgLAAgNQAAgOAGgKQAGgLAKgGQAKgGAMAAQAOAAAKAGQAKAHAFAKQAGAKAAAOQAAANgGALQgFAKgLAGQgKAGgNAAQgMAAgLgGgAgLgbQgFADgDAIQgDAHAAAJQAAAKADAIQADAGAFAFQAFADAGAAQAHAAAFgDQAFgFADgGQACgIAAgKQAAgJgCgHQgDgIgFgDQgFgEgHAAQgGAAgFAEg");
	this.shape_2.setTransform(39.225,3.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgwBAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAh4IABgBIACgBIAIAAIAKAAIAJAAIAHAAQAXABAOAHQAPAIAHANQAHAOAAATQAAATgHAPQgIAOgPAIQgPAHgWABgAgagqIAABWQAAAAAAAAQAAABABAAQAAAAAAAAQABABAAAAIAFAAQAPgBAKgEQAKgEAFgKQAFgLAAgQQAAgPgFgKQgFgLgKgEQgJgFgPABIgGAAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAABg");
	this.shape_3.setTransform(27.525,1.65);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgkA7QgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIAAgLIABgCIAEgBIAMAAQADAAADgCIAFgEIACgGQABgDgCgDIgghQIAAgCIACgBIASAAIACAAIABACIAVA4QAAAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIACgBIAVg4IABgCIACAAIAMAAIACABQAAAAABAAQAAABAAAAQAAAAAAABQgBAAAAAAIgkBZQgDAIgDAFQgDAFgEADQgEACgGABIgMABg");
	this.shape_4.setTransform(11.5875,4.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgVApQgKgFgGgLQgGgKAAgNQAAgOAGgMQAGgKAKgGQALgGALAAQANAAAKAGQAJAFAGALQAFAKAAAPIAAACQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAIg7AAIgCABIAAACQAAAHADAGQADAGAGADQAGACAGAAQAHAAAGgCQAFgDAFgGIACgBIABAAIALAEQAAABABAAQAAAAAAABQAAAAAAABQAAAAgBABQgFAHgGAEQgGAFgHACQgHACgJAAQgMAAgKgGgAgJgcQgFADgDAGQgDAFAAAHIAoAAIACAAIAAgCQAAgGgCgFQgCgFgFgDQgFgEgGAAQgGAAgFAEg");
	this.shape_5.setTransform(1.375,3.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-9.125,3.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgXApQgKgGgFgKQgGgLAAgNQAAgOAGgKQAGgLAKgGQAKgGAMAAQAOAAAKAGQAKAHAFAKQAGAKAAAOQAAANgGALQgFAKgLAGQgKAGgNAAQgMAAgLgGgAgLgbQgFADgDAIQgDAHAAAJQAAAKADAIQADAGAFAFQAFADAGAAQAHAAAFgDQAFgFADgGQACgIAAgKQAAgJgCgHQgDgIgFgDQgFgEgHAAQgGAAgFAEg");
	this.shape_7.setTransform(-19.875,3.45);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAsBAIgCgBIgBgCIAAhZIAAgBIgBABIghBZQAAABAAAAQgBABAAAAQgBAAAAAAQgBABAAAAIgLAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgghYIgBgBIgBACIAABXIAAACIgCABIgPAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAh4QAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAcAAIADAAIABACIAeBQIAAABIABgBIAehPQAAgBAAgBQABAAAAgBQABAAAAAAQABAAAAAAIAeAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAB4QAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAg");
	this.shape_8.setTransform(-33.525,1.65);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgXApQgKgGgFgKQgGgLAAgNQAAgOAGgKQAGgLAKgGQAKgGAMAAQAOAAAKAGQAKAHAFAKQAGAKAAAOQAAANgGALQgFAKgLAGQgKAGgNAAQgMAAgLgGgAgLgbQgFADgDAIQgDAHAAAJQAAAKADAIQADAGAFAFQAFADAGAAQAHAAAFgDQAFgFADgGQACgIAAgKQAAgJgCgHQgDgIgFgDQgFgEgHAAQgGAAgFAEg");
	this.shape_9.setTransform(-51.225,3.45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAiBAIgCgBIgCgBIg5hTIgCgBIAAABIAABSQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgPAAQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAh5QAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIARAAIACAAIACACIA2BOIACACIABgCIAAhOQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAB5IAAACIgDABg");
	this.shape_10.setTransform(-63.375,1.65);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgKAZIgCgBIAAgCIAIgSQABgBAAgBQAAgBAAgBQAAAAgBAAQAAAAgBAAIgDAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgTQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIATAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAABIAAASIgBACIgOAZIgDABIgCABg");
	this.shape_11.setTransform(48.7625,-12.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAJA9QgKAAgHgGQgGgFAAgLIAAgyQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgLAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgLQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAABAAIAMAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIACgaQABAAAAgBQAAgBAAAAQABAAAAgBQAAAAABAAIAOAAQABAAAAAAQABABAAAAQAAAAAAABQABABAAAAIAAAaQAAABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIAUAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgUAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAAsQAAAHADACQADADAGAAIAKAAIABABIABABIAAAJQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgHAAIgGABg");
	this.shape_12.setTransform(42.6,-18.725);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgYAqQgKgGgEgHIgBgDIABgBIAKgFIACgBIACABIAFAGIAJAFQAEABAGAAQAGAAAEgBQAFgBACgDQADgCAAgEQAAgDgDgDQgDgDgIgBIgQgFQgNgCgGgGQgGgFAAgKQAAgIAEgHQAFgGAIgEQAJgEAKAAQANAAAJAFQAJAFAEAGIABACQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAgBAAIgKAFIgCAAIgCAAQgDgFgFgDQgFgDgIAAQgHAAgEADQgFADAAAFQAAADACADQACACAHABIATAGQANADAGAGQAGAHAAAJQAAAJgFAGQgFAHgJADQgJADgMAAQgNAAgLgFg");
	this.shape_13.setTransform(33.975,-17.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgVApQgKgGgGgKQgGgKAAgNQAAgPAGgKQAGgLAKgGQALgGALAAQANAAAKAGQAJAGAGAKQAFAKAAAOIAAAEQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIg7AAIgCAAIAAACQAAAHADAGQADAGAGADQAGADAGAAQAHAAAGgDQAFgDAFgGIACgCIABABIALAEQAAABABAAQAAAAAAABQAAAAAAABQAAAAgBAAQgFAIgGAFQgGAEgHACQgHACgJAAQgMAAgKgGgAgJgdQgFAEgDAFQgDAGAAAHIAoAAIACgBIAAgCQAAgFgCgFQgCgFgFgEQgFgDgGAAQgGAAgFADg");
	this.shape_14.setTransform(24.175,-17.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgYAuIgCgBIgBgCIAAhTQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAALIABABIACgBQADgFAEgDIAJgFQAEgCAEAAQAHAAAAADIAAAQQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAIgFgBIgFAAIgHABIgHAEQgCADgCADQgCACAAADIAAA0QAAADgEAAg");
	this.shape_15.setTransform(15.425,-17.275);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgVApQgKgGgGgKQgGgKAAgNQAAgPAGgKQAGgLAKgGQALgGALAAQANAAAKAGQAJAGAGAKQAFAKAAAOIAAAEQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIg7AAIgCAAIAAACQAAAHADAGQADAGAGADQAGADAGAAQAHAAAGgDQAFgDAFgGIACgCIABABIALAEQAAABABAAQAAAAAAABQAAAAAAABQAAAAgBAAQgFAIgGAFQgGAEgHACQgHACgJAAQgMAAgKgGgAgJgdQgFAEgDAFQgDAGAAAHIAoAAIACgBIAAgCQAAgFgCgFQgCgFgFgEQgFgDgGAAQgGAAgFADg");
	this.shape_16.setTransform(6.125,-17.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAJA9QgKAAgHgGQgGgFAAgLIAAgyQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAIgMAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgLQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAIANAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAABgBIABgaQABAAAAgBQAAgBAAAAQABAAAAgBQABAAAAAAIAOAAQABAAAAAAQABABAAAAQAAAAAAABQAAABAAAAIAAAaQAAABABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAUAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgUAAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAABIAAAsQAAAHADACQACADAHAAIAKAAIACABIAAABIAAAJQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgHAAIgGABg");
	this.shape_17.setTransform(-3.05,-18.725);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_18.setTransform(-12.075,-17.275);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgIA/IgDgBIgBgCIAAh3QAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAIATAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAABIAAB2QAAABAAABQAAAAgBAAQAAABAAAAQAAAAAAAAIgEABg");
	this.shape_19.setTransform(-20.325,-19);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgXApQgKgGgFgLQgGgKAAgOQAAgNAGgKQAGgLAKgGQAKgGAMAAQAOAAAKAHQAKAFAFALQAGAKAAANQAAAOgGAKQgFALgLAGQgKAGgNAAQgMAAgLgGgAgLgcQgFAFgDAGQgDAIAAAJQAAALADAGQADAHAFAFQAFADAGAAQAHAAAFgDQAFgFADgHQACgGAAgLQAAgJgCgIQgDgGgFgFQgFgDgHAAQgGAAgFADg");
	this.shape_20.setTransform(-32.675,-17.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAiA/IgCAAIgCgCIg5hRIgCgBIAAABIAABQQAAABAAABQgBAAAAABQAAAAgBAAQgBAAAAAAIgPAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAh3QAAgBAAgBQAAAAAAgBQABAAAAAAQABgBABAAIARAAIACABIACACIA2BOIACACIABgDIAAhMQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIAQAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAB5IAAACIgDAAg");
	this.shape_21.setTransform(-44.825,-19);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgKAZIgCgBIAAgCIAIgSQABgBAAgBQAAgBAAgBQAAAAgBAAQAAAAgBAAIgDAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgTQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIATAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAABIAAASIgBACIgOAZIgDABIgCABg");
	this.shape_22.setTransform(57.7125,-33.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgYAqQgKgGgEgHIgBgDIABgBIAKgFIACgBIACABIAFAGIAJAFQAEABAGAAQAGAAAEgBQAFgBACgDQADgCAAgEQAAgDgDgDQgDgDgIgBIgQgFQgNgCgGgGQgGgFAAgKQAAgIAEgHQAFgHAIgDQAJgEAKAAQANAAAJAFQAJAFAEAGIABACQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAgBAAIgKAFIgCABIgCgBQgDgFgFgDQgFgDgIAAQgHAAgEADQgFADAAAGQAAACACADQACACAHABIATAGQANADAGAGQAGAHAAAJQAAAJgFAGQgFAHgJADQgJADgMAAQgNAAgLgFg");
	this.shape_23.setTransform(50.575,-37.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAIA9QgKAAgGgGQgGgFAAgLIAAgyQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgLAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgLQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAABAAIAMAAQAAAAABAAQAAAAAAAAQAAAAAAgBQABAAAAgBIACgaQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAAAAAIAPAAQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAAAIAAAaQABABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIATAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgTAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIAAAsQAAAHADACQADADAFAAIAKAAIADABIAAABIAAAJQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgFAAIgHABg");
	this.shape_24.setTransform(41.55,-39.425);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_25.setTransform(32.525,-37.975);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgVAqQgKgHgGgKQgGgKAAgNQAAgPAGgKQAGgLAKgGQALgGALAAQANAAAKAGQAJAGAGAKQAFAKAAAOIAAAEQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIg7AAIgCAAIAAACQAAAHADAGQADAGAGADQAGADAGAAQAHAAAGgDQAFgDAFgGIACgCIABABIALAFQAAAAABAAQAAAAAAABQAAAAAAABQAAAAgBAAQgFAIgGAFQgGAEgHACQgHACgJAAQgMAAgKgFgAgJgdQgFAEgDAFQgDAGAAAHIAoAAIACgBIAAgCQAAgFgCgFQgCgFgFgEQgFgDgGAAQgGAAgFADg");
	this.shape_26.setTransform(21.925,-37.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAwAuIgCAAIAAgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACIgHADIgFAFIgCACIAAADIAAA5QAAADgEAAIgOAAIgCAAIgBgDIAAg6QAAgGgDgEQgEgEgHAAQgFAAgFADQgFADgGAGIAAA8QAAADgEAAIgPAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhTQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIARAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAJIAAABIACAAIAJgIQAEgDAFgBQAFgCAGAAQAJAAAFAEQAHAFACAGIABABIABgBIAKgIQAFgDAFgCQAFgCAGAAQAMAAAHAHQAHAHAAANIAAA9QAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_27.setTransform(8.625,-37.975);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgkA7QgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIAAgLIABgCIAEgBIAMAAQADAAADgCIAFgEIACgGQABgDgCgDIgghQIAAgCIACgBIASAAIACAAIABACIAVA4QAAAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIACgBIAVg4IABgCIACAAIAMAAIACABQAAAAAAAAQABABAAAAQAAAAgBABQAAAAAAAAIgkBZQgDAIgDAFQgDAFgEADQgEACgGABIgMABg");
	this.shape_28.setTransform(-4.4625,-36.475);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AggApQgHgIAAgLQAAgJAFgHQAGgGALgEQAKgEAPgBIAIAAIACgBIABgCIAAgDQAAgIgEgFQgFgDgIAAQgFgBgFADQgFADgEAGIgBABIgCAAIgPgDIgBgBIABgDQAEgKAKgFQAKgFAOAAQANAAAIAEQAJADADAHQAEAGAAAJIAAA7IAAACIgDABIgOAAIgDgBIAAgCIgBgGQAAgBAAAAQAAAAgBAAQAAAAgBAAQAAAAgBABQgGAFgHADQgGADgIAAQgNAAgIgGgAAQACIgHAAQgFAAgEACQgFAAgEADIgGAFQgCADAAAFQAAAFAEAEQAEADAHAAQAEAAAEgBIAHgFIAEgEQACgDAAgDIAAgMQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAIgBABg");
	this.shape_29.setTransform(-14.825,-37.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AguA/IgDgBIAAgCIAAh3QAAgBAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAwAAQAOAAAKAFQAMAEAGAIQAHAJAAAOQAAAMgGAJQgGAHgKAEQgLAEgNABIgaAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAtQAAADgFAAgAgXgpIAAAiQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAIAXAAQAKAAAHgFQAGgGAAgJQAAgHgDgFQgDgEgGgCQgFgCgHAAIgVAAQgBAAAAAAQgBAAAAABQAAAAAAAAQAAABAAABg");
	this.shape_30.setTransform(-25.55,-39.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgXApQgKgGgFgLQgGgKAAgOQAAgNAGgKQAGgLAKgGQAKgGAMAAQAOAAAKAHQAKAFAFALQAGAKAAANQAAAOgGAKQgFALgLAGQgKAGgNAAQgMAAgLgGgAgLgcQgFAFgDAGQgDAIAAAJQAAALADAGQADAHAFAFQAFADAGAAQAHAAAFgDQAFgFADgHQACgGAAgLQAAgJgCgIQgDgGgFgFQgFgDgHAAQgGAAgFADg");
	this.shape_31.setTransform(-41.625,-37.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAiA/IgCAAIgCgCIg5hSIgCAAIAAAAIAABRQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgPAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAh3QAAgBAAgBQAAAAABgBQAAAAAAAAQABgBABAAIARAAIACABIACACIA2BOIACACIABgDIAAhMQAAgBAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIAQAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAB5IAAACIgDAAg");
	this.shape_32.setTransform(-53.775,-39.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgYAqQgKgGgEgHIgBgDIABgBIAKgFIACgBIACABIAFAGIAJAFQAEABAGAAQAGAAAEgBQAFgBACgDQADgCAAgEQAAgDgDgDQgDgDgIgBIgQgFQgNgCgGgGQgGgFAAgKQAAgIAEgHQAFgHAIgDQAJgEAKAAQANAAAJAFQAJAFAEAGIABACQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAgBAAIgKAFIgCAAIgCAAQgDgFgFgDQgFgDgIAAQgHAAgEADQgFADAAAFQAAADACADQACACAHABIATAGQANADAGAGQAGAHAAAJQAAAJgFAGQgFAHgJADQgJADgMAAQgNAAgLgFg");
	this.shape_33.setTransform(47.375,-58.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAVA/IgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEABgDABIgHAEIgHAGIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAh3QAAgBAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIARAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAtIABABIABAAQAGgFAFgDQAEgDAEgCQAFgBAFAAQANAAAHAHQAHAIAAAMIAAA9QAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_34.setTransform(37.475,-60.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAJA9QgKAAgHgGQgGgFAAgLIAAgyQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgLAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgLQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAABAAIAMAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIACgaQABAAAAgBQAAgBAAAAQABAAAAgBQAAAAABAAIAOAAQABAAAAAAQABABAAAAQAAAAAAABQABABAAAAIAAAaQAAABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIAUAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgUAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAAsQAAAHADACQADADAGAAIAKAAIABABIABABIAAAJQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgHAAIgGABg");
	this.shape_35.setTransform(27.65,-60.125);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_36.setTransform(18.675,-58.675);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgXApQgKgGgFgLQgGgKAAgOQAAgNAGgKQAGgLAKgGQAKgGAMAAQAOAAAKAHQAKAFAFALQAGAKAAANQAAAOgGAKQgFALgLAGQgKAGgNAAQgMAAgLgGgAgLgcQgFAFgDAGQgDAIAAAJQAAALADAGQADAHAFAFQAFADAGAAQAHAAAFgDQAFgFADgHQACgGAAgLQAAgJgCgIQgDgGgFgFQgFgDgHAAQgGAAgFADg");
	this.shape_37.setTransform(7.925,-58.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AAsA/IgCgBIgBgCIAAhYIAAgBIgBABIghBZQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgLAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgghYIgBgBIgBABIAABXIAAADIgCAAIgPAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAh3QAAgBAAgBQAAAAABgBQAAAAAAAAQABgBABAAIAcAAIADABIABACIAeBQIAAABIABgBIAehPQAAgBAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAeAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAABIAAB3QAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_38.setTransform(-5.725,-60.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgqBAIgCAAIgBgDIAAgLIAAgCIACgDIAFgEIAhgfIAMgLIAIgJIAEgIIABgIQAAgGgDgEQgDgEgEgCQgFgDgFAAQgFAAgEACQgFACgEAEQgFADgDAHIgCABIgDgBIgMgGIgCgCIABgDQAIgNAMgGQAMgGANAAQAMAAAKAEQAKAEAGAJQAGAIAAAMQAAAHgDAHQgCAGgGAGQgFAGgKAIIgfAbIgBACIACAAIA2AAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAPIgBACIgCABg");
	this.shape_39.setTransform(-23.675,-60.475);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgfA/QgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgOQAAgBAAAAQAAgBAAAAQABAAAAAAQABgBAAAAIATAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAgBIAAhOQAAgBAAAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgSAGQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAgBAAAAIAAgLIAAgCIACgBIAbgNIAEgCIACgBIAKAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAABIAABmQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAIASAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAOIAAABIgDABg");
	this.shape_40.setTransform(-33.725,-60.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgEAoQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAgcIAQAAIAAAdQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAgAAJAJIAAgQIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAKQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAgAgHAJIgdAAIgCgBIgBgDIAAgJQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAdAAIAAAQIAAgQIAQAAIAAAQgAAJgHIgQAAIAAgdIABgDIACAAIAJAAQABAAABAAQAAAAABABQAAAAAAAAQABAAAAABIAAAegAgHgHg");
	this.shape_41.setTransform(-47.5,-60.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.7,-72.4,143.5,86.4);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#47C434").s().p("AgDAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgUIgUAAIgCgBIgBgBIAAgIQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAVAAIANAAIAAANIgNAAIAAgNIAAANIANAAIAAAVQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAgAAHAHIAAgNIgNAAIAAgUIABgCIACgBIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAVIAVAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAgAAHAHgAAHgGg");
	this.shape.setTransform(4.775,77.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#48C435").ss(1,1,1).p("ABgAAIJYAAAq3AAIJYAA");
	this.shape_1.setTransform(3.75,77.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6CC14C").s().p("AhICXQgfgVgTgmQgRgmAAg0QAAgnAKggQAKggAUgXQASgXAagMQAagMAdAAQAfAAAZAMQAZAMATAXQATAXAKAgQALAgAAAmQAAA0gSAnQgTAmgfAVQgfAVgpAAQgoAAgggVgAgghoQgNAMgHAaQgHAaAAAqQAAApAHAZQAHAaANALQANALATAAQAUAAAOgLQANgLAGgaQAHgZAAgpQgBgqgGgaQgHgagNgMQgOgMgTAAQgTAAgNAMg");
	this.shape_2.setTransform(1.85,46.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC14C").s().p("AAUCoQgKAAAAgJIAAhCQAAgEgFAAIiHAAQgJAAAAgIIAAgmIACgJIAJgNICIizIAIgHIAKgCIA5AAQAHAAAAAIIAAC9QAAAFAFAAIAlAAQAIAAAAAHIAAAnQAAAIgIAAIglAAQgFAAAAAFIAABAQAAAKgLAAgAAEhRIhQBuQgEAGAIAAIBPAAQABAAAAAAQABAAABgBQAAAAAAgBQABAAAAgBIAAhwIgCgGg");
	this.shape_3.setTransform(-31.725,46.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6CC14C").s().p("AgrBEIgEgBIAAgDIAAh/QAAgBAAgBQAAgBAAAAQABgBAAAAQABAAAAAAIBaAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAAQQAAAFgEAAIg4AAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABAAAAIAAAdQAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAIAnAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAQQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgnAAQAAAAgBABQAAAAgBAAQAAAAAAABQAAAAAAABIAAAxQAAAEgFAAg");
	this.shape_4.setTransform(50.025,56.55);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6CC14C").s().p("AgrBEIgEgBIAAgDIAAh/QAAgBAAgBQAAgBAAAAQABgBAAAAQABAAAAAAIBaAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAAQQAAAFgEAAIg4AAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABAAAAIAAAdQAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAIAnAAQABAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAAQQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgnAAQAAAAgBABQAAAAgBAAQAAAAAAABQAAAAAAABIAAAxQAAAEgFAAg");
	this.shape_5.setTransform(38.475,56.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6CC14C").s().p("AggA+QgOgJgIgPQgIgQAAgVQAAgVAIgQQAIgQAOgIQAOgJASAAQATAAAOAJQAOAIAIAQQAIAPAAAWQAAAVgIAQQgHAPgPAJQgOAIgTAAQgSAAgOgIgAgVgjQgHALAAAZQAAAZAHALQAHALAOgBQAPABAHgLQAHgLAAgZQAAgZgHgLQgHgMgPABQgOgBgHAMg");
	this.shape_6.setTransform(25.225,56.55);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6CC14C").s().p("AAbBBQgHgFgFgJQgFgJAAgLQAAgKAFgJQAFgJAHgEQAIgGAKABQAJgBAIAGQAIAEAFAJQAEAJAAAKQAAALgEAJQgFAJgIAFQgHAFgKAAQgKAAgIgFgAAlAKQgDADgBAGQgCAFAAAHQAAAIACAGQABAEADADQADAEAEAAQAGAAACgEQADgDACgEQABgGABgIQgBgHgBgFQgCgGgDgDQgCgDgGAAQgEAAgDADgAgvBEQgBAAgBAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAIBViDIADgBIACAAIAJAAIACAAQAAAAAAABQABAAAAAAQAAAAgBABQAAAAAAAAIhYCFQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAgAg+ACQgHgEgEgJQgFgJAAgKQAAgLAFgIQAEgKAIgFQAIgFAJAAQAKAAAIAFQAHAFAFAKQAEAIAAALQAAAKgEAJQgEAJgIAEQgIAFgKAAQgJAAgJgFgAg0gzQgCADgCAFQgCAGABAHQgBAIACAFQACAFACADQAEADAEAAQAIAAADgHQADgGAAgLQAAgMgEgGQgCgHgIAAQgEABgEADg");
	this.shape_7.setTransform(26.8,36.55);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6CC14C").s().p("Ag7BuQgagOgNgdQgOgcAAgmQAAgmAOgcQAOgdAagPQAZgQAhAAQAjAAAZAQQAZAPAOAdQAOAcAAAmQAAAmgOAcQgOAdgZAOQgZAPgjABQgigBgZgPgAgng/QgNAUAAAsQAAAsANAUQANAVAagBQAbABANgVQAMgTAAgtQAAgsgMgUQgNgVgbAAQgaAAgNAVg");
	this.shape_8.setTransform(41.125,8.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6CC14C").s().p("Ag3BuQgZgPgOgcQgNgcAAgmQAAgmAOgcQAOgdAagPQAZgQAhAAQAbAAAVAKQAVALANAPQANAQAEATIAAAGQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBABIgsAGQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgCgDQgCgLgGgJQgGgJgKgGQgKgFgNAAQgPAAgMAIQgMAJgGASQgGATAAAeQAAAfAHASQAGATAMAJQAMAJAQgBQAKAAAIgDQAJgDAFgGQAGgFAEgGQADgHACgIIABgJQABgFgFAAIgoAAIgDgBIgCgEIAAgZQAAgEAFAAIBZAAQAFAAACACQACACAAADIAABwIgBADIgEACIgKAAIgFgCIgEgEIgJgYIgCgBIgCACQgGAHgJAIQgJAHgNAFQgNAEgTABQgggBgZgPg");
	this.shape_9.setTransform(15.825,8.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6CC14C").s().p("Ag7BuQgagOgNgdQgOgcAAgmQAAgmAOgcQAOgdAagPQAZgQAhAAQAjAAAZAQQAZAPAOAdQAOAcAAAmQAAAmgOAcQgOAdgZAOQgZAPgjABQgigBgZgPgAgng/QgNAUAAAsQAAAsANAUQANAVAagBQAbABANgVQAMgTAAgtQAAgsgMgUQgNgVgbAAQgaAAgNAVg");
	this.shape_10.setTransform(-9.175,8.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6CC14C").s().p("AhdB7QgBAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIgCgEIAAjoQAAAAAAgBQAAAAABgBQAAAAAAgBQABgBAAAAQACgDADAAIBZAAQAwAAAZARQAaARAAAfQAAASgKANQgKANgXAJIgBACIABABQAaAIALANQAMAOAAAWQAAAigaAQQgZAQgyABgAgqAZIAAA0QAAAGAFAAIAkAAQAUABALgKQALgIAAgPQAAgLgFgGQgGgIgJgEQgJgDgMAAIgkAAQgGAAAAAGgAgqhNIAAAzQAAAFAFABIAlAAIAPgCQAGgBAFgEQAGgFADgFQADgFAAgJQAAgPgMgIQgLgJgRABIgiAAQgGAAAAAFg");
	this.shape_11.setTransform(-33.375,8.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAMBOQgOAAgJgHQgHgHAAgOIAAhBQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBAAIgOAAQgBAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgOQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAQAAQABAAAAgBQABAAAAAAQAAAAAAgBQABAAAAgBIACghQAAgBAAgBQABgBAAAAQABgBAAAAQABAAAAAAIATAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAhQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAZAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAOQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgZAAQgBAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABIAAA6QgBAIAEAEQADADAIAAIANAAIACAAIABADIgBAMQAAADgDAAIgIABIgJABg");
	this.shape_12.setTransform(53.75,125.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgJBSIgEgBIAAgDIAAhsQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAABAAIAVAAQABAAABAAQAAABAAAAQABABAAAAQAAABAAABIAABrIgBAEIgEABgAgKgyQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgBgEIAAgVQAAgFAEAAIAVAAQAEAAAAAEIAAAWQAAAFgGAAg");
	this.shape_13.setTransform(46.475,125.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAbA7IgDAAIgBgDIAAhLQAAgJgEgEQgFgFgJAAQgFAAgEABQgEACgFAEIgJAIIAABNQAAAEgFAAIgUAAQgEABAAgEIAAhtQAAAAAAgBQABgBAAAAQAAgBABAAQAAAAABAAIAWAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAAMIABACIACgBIAMgKQAGgEAFgCQAGgDAIABQAQAAAKAJQAJAKAAAPIAABPQAAAEgFAAg");
	this.shape_14.setTransform(37.225,127.25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgkBMQgOgIgGgOQgGgOAAgWIAAhgQAAgEADAAIAaAAQADAAAAAEIAABlQAAATAJAJQAIAIAPAAQALAAAIgDQAHgEAEgIQAFgIAAgNIAAhlQAAgEADAAIAUAAQADAAAAAEIAABkQAAAWgHAOQgIANgOAGQgOAGgUAAQgWAAgOgHg");
	this.shape_15.setTransform(22.775,125.125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgvBMQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgNIABgDIAGgBIAOAAQAEAAAEgCIAGgGIADgIQABgDgBgDIgrhoQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAABAAIAXAAIACABIACACIAaBIQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAbhIIACgCIACgBIAQAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAIguBzQgFAKgEAGQgEAHgFADQgGAEgGABQgHACgKAAg");
	this.shape_16.setTransform(4.2917,129.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgfA7IgDAAIgBgDIAAhtQAAAAAAgBQABgBAAAAQAAgBABAAQAAAAABAAIAVAAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIAAAOIAAABIADgBQAEgGAFgEIALgHQAGgDAGABQAIgBAAAEIAAAWQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgHgBIgHAAIgJABIgJAFIgFAHQgCAEAAADIAABDQAAAEgFAAg");
	this.shape_17.setTransform(-6.525,127.25);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgbA1QgOgIgHgNQgIgNAAgRQAAgSAIgOQAIgOANgHQANgJAPABQARAAAMAHQANAHAHAOQAHANAAATIgBADQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIhNAAIgCABIAAADQAAAJAEAHQAEAHAIAFQAHAEAIAAQAJgBAHgDQAHgEAHgIIACgCIACABIANAHQABAAAAAAQABABAAAAQAAAAAAABQgBABAAAAQgHAKgHAGQgIAFgJADQgJADgMgBQgPAAgNgHgAgMglQgHAEgDAIQgEAHAAAIIAzAAIADAAIABgCQAAgIgDgGQgDgGgGgFQgGgFgJABQgIgBgGAFg");
	this.shape_18.setTransform(-17.825,127.35);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgGA6QgEAAgCgEIgshrQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIADgBIAXAAIADABIACACIAbBHQABAEADgEIAchHIABgCIADgBIAQAAIADABIAAADIgsBrQgCAEgFAAg");
	this.shape_19.setTransform(-30.4875,127.375);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("Ag1BSQgEAAAAgEIAAibQAAgEADAAIBqAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAARQAAAEgEAAIhIAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABAAABIAAAmQAAABAAABQAAAAABABQAAAAAAABQABAAABAAIAxAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAARIAAACIgDAAIgxAAQgBAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABIAAApQAAAAAAABQAAABAAAAQABAAAAABQABAAAAAAIBMAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAAARIgBADIgDABg");
	this.shape_20.setTransform(-43.325,125.025);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgNBSQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhaQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgOIAAgCIAEgBIAQAAQABAAAAAAQABAAAAAAQAAgBAAAAQABgBAAgBIAAgOQgBgOAJgIQAHgIAOAAIAUAAQAFAAAAAEIAAANIAAACIgDABIgNAAQgGAAgDAEQgCAEAAAGIAAALQAAAAAAABQAAAAAAABQAAAAABAAQAAAAABAAIAUAAIADABIABACIAAAOQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgUAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAABaQAAABAAAAQAAABgBABQAAAAgBAAQAAABgBAAg");
	this.shape_21.setTransform(47.8,102.375);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgMBSQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAhaQAAAAAAgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgOIABgCIACgBIARAAQABAAAAAAQABAAAAAAQAAgBAAAAQAAgBAAgBIAAgOQABgOAHgIQAIgIAOAAIAVAAQAEAAAAAEIAAANIgBACIgCABIgNAAQgFAAgDAEQgEAEAAAGIAAALQAAAAABABQAAAAAAABQAAAAABAAQAAAAABAAIAVAAIACABIABACIAAAOQAAABAAABQAAAAgBAAQAAABgBAAQgBAAAAAAIgUAAQgBAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAABaQAAABAAAAQAAABgBABQAAAAgBAAQAAABgBAAg");
	this.shape_22.setTransform(37.85,102.375);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgmBKQgRgKgIgTQgJgSAAgaQAAgaAJgTQAJgSAQgLQARgKAVAAQAXAAAQAKQAQALAJASQAJATAAAaQAAAagIASQgJATgRAKQgQAKgXAAQgVAAgRgKgAgdgtQgJAPAAAfQAAAfAJAOQAKAPATAAQAUAAAKgPQAJgOAAgfQAAgfgJgPQgKgPgUAAQgTAAgKAPg");
	this.shape_23.setTransform(25.025,102.375);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AghBKQgPgKgIgTQgJgSAAgaQAAgTAFgPQAFgQAJgLQAJgLAMgGQAMgGANAAQAOAAAMAGQAMAGAJALQAJALAFAPQAFAQAAATQAAAagJASQgIATgPAKQgPAKgTAAQgSAAgPgKgAgRg2QgHAHgEANQgEAOAAAVQAAAVAEANQAEANAHAGQAIAGAJAAQALAAAHgGQAHgGAEgNQAEgNAAgVQAAgVgEgOQgEgNgHgHQgIgGgKAAQgJAAgIAGg");
	this.shape_24.setTransform(4.325,102.375);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AghBKQgPgKgIgTQgJgSAAgaQAAgTAFgPQAFgQAJgLQAJgLAMgGQAMgGANAAQAOAAAMAGQAMAGAJALQAJALAFAPQAFAQAAATQAAAagJASQgIATgPAKQgPAKgTAAQgSAAgPgKgAgRg2QgHAHgEANQgEAOAAAVQAAAVAEANQAEANAHAGQAIAGAJAAQALAAAHgGQAHgGAEgNQAEgNAAgVQAAgVgEgOQgEgNgHgHQgIgGgKAAQgJAAgIAGg");
	this.shape_25.setTransform(-11.975,102.375);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgpBSQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBgBAAAAIAAgTQAAgBABAAQAAgBAAAAQABAAAAgBQABAAABAAIAYAAQABAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIAAhlQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgXAHQgFABAAgEIAAgNIABgDIACgBIAjgSIAFgCIADgBIAOAAQAAAAABABQAAAAAAAAQABABAAABQAAAAAAABIAACEQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAXAAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAASIgBADIgCABg");
	this.shape_26.setTransform(-25.05,102.375);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgDBiQgBAAAAAAQgBAAgBgBQAAAAAAgBQAAAAAAgBIAAgLIgBgCIgCgBQgRAAgMgGQgMgFgJgKQgFgEADgDIALgLIADgCIADACQAHAHAIAFQAIAFAMABQAAAAABAAQAAAAABAAQAAgBAAAAQABAAAAgBIAAgrIgBgDIgDgCQgRgFgLgGQgKgGgFgJQgEgJAAgLQAAgMAGgJQAFgKALgGQALgHAOgCIADgBIABgCIAAgJIABgDIABAAIAMAAIADABIABADIAAAJQAAABAAAAQAAAAAAAAQABABAAAAQAAAAABAAQAMACAKAEQAJAFAIAGQADACgCADIgLANIgCABIgDgBQgEgFgGgDQgGgEgIgBIgCAAIAAACIAAArQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABABIALADQAMAEAIAFQAJAHAFAJQAEAIAAALQAAANgGAKQgGAKgKAGQgLAGgPABIgDABIAAACIAAAKQAAAEgFAAgAAMASIAAApQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAQALgBAHgGQAGgGAAgIQAAgIgFgGQgGgGgMgDIgDgBIAAADgAgJg9QgLABgGAHQgGAGAAAIQAAAFACAEIAHAHQAEADAIADIAEAAIABgEIAAgmQAAAAgBgBQAAAAAAgBQAAAAAAAAQgBAAAAAAIgBAAg");
	this.shape_27.setTransform(-37.61,102.525);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgGA0QgBAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIAAgPQAAgBABAAQAAgBAAAAQAAAAABAAQAAgBABAAIAPAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAQQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAgAgDAWIgBgBIgBgBIgFhFIABgCIABAAIARAAQAAAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIgFBFIgBABIgCABg");
	this.shape_28.setTransform(70.75,-19.15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgRAhQgJgEgEgIQgFgJAAgLQAAgMAFgIQAFgJAJgFQAIgEAJgBQAKABAJAEQAHAEAFAJQAEAJAAALIAAADIgCABIgwAAIgBAAIgBABQAAAGADAFQACAEAFADQAFADAEgBQAGAAAEgCQAFgCAEgGIABAAIACAAIAIAEQABAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgEAGgFAEQgFADgGACQgGACgHAAQgKgBgIgFgAgHgXQgFADgBAEQgDAEAAAGIAgAAIACAAIABgCQAAgEgDgFQgBgDgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_29.setTransform(64.9,-17.65);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgFA0QgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhiQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIANAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAABiIAAACIgDABg");
	this.shape_30.setTransform(59.025,-19.15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgZAhQgHgGAAgJQAAgIAFgFQAFgFAIgDQAJgDALgBIAIgBIABAAIAAgCIAAgDQABgGgEgDQgDgEgHAAQgEAAgEADQgEACgDAEIgBACIgCAAIgMgEIgBgBIAAgBQAEgJAJgDQAHgFAMAAQALAAAGADQAHAEADAEQADAGAAAHIAAAwIgBACIgBABIgMAAIgCgBIgBgDIAAgDQAAgBAAAAQgBgBAAAAQAAAAgBABQAAAAgBABQgEAEgGACQgFADgHAAQgLAAgFgGgAAAADIgHACQgDACgCACQgCAEAAACQAAAFADADQAEADAFAAIAHgBIAGgDIADgFQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgGAAIgIACg");
	this.shape_31.setTransform(53.1,-17.65);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgFIgBgDIABgCIAJgFIADgCIACACIAGAHQAEADAEACIALAAQAJAAAGgCQAGgEAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgFgDgFQgCgFAAgHQAAgIAEgIQAFgGAJgFQAJgDAKAAQAIAAAGABQAHACAFAEQAGADADAEIABACIgBACIgKAHIgBAAIgCgBQgDgEgFgCQgFgDgIgBQgJAAgFAEQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMADAGAHQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAFgMAAQgJAAgIgDg");
	this.shape_32.setTransform(44.7667,-19.15);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_33.setTransform(34.675,-17.725);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgRAhQgJgEgEgIQgFgJAAgLQAAgMAFgIQAFgJAJgFQAIgEAJgBQAKABAJAEQAHAEAFAJQAEAJAAALIAAADIgCABIgwAAIgBAAIgBABQAAAGADAFQADAEAEADQAFADAEgBQAGAAAFgCQAEgCAFgGIAAAAIACAAIAIAEQABAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgFAGgEAEQgFADgGACQgFACgIAAQgJgBgJgFgAgHgXQgFADgBAEQgDAEAAAGIAgAAIACAAIABgCQgBgEgCgFQgCgDgDgDQgEgDgFAAQgFAAgEADg");
	this.shape_34.setTransform(27.45,-17.65);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAnAmIgBgBIgBgCIAAgvQAAgFgCgDQgDgDgFAAIgHABIgFADIgFADIgBACIAAADIAAAuQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgBgBIgBgCIAAgvQAAgFgDgDQgCgDgGAAQgFAAgEACQgEACgEAFIAAAxQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGQADgCAEgBQAEgCAFAAQAHAAAFAEQAEADADAGIAAAAIABAAIAIgHQAEgDAFgBQAEgCAEAAQAKAAAFAGQAHAGgBAKIAAAyQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_35.setTransform(17.05,-17.725);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAoAmIgCgBIgBgCIAAgvQAAgFgDgDQgCgDgGAAIgGABIgFADIgFADIgBACIAAADIAAAuQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgCgBIAAgCIAAgvQAAgFgDgDQgDgDgFAAQgFAAgEACQgEACgFAFIAAAxQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgNAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAhEQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAOAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHIAAABIABgBIAIgGQAEgCAEgBQAEgCAFAAQAHAAAEAEQAGADABAGIABAAIABAAIAIgHQAEgDAEgBQAEgCAFAAQAKAAAGAGQAFAGAAAKIAAAyQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_36.setTransform(4.3,-17.725);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgVAjQgFgDgDgFQgDgFAAgGIAAgyQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIANAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAuQAAAGADADQADADAGAAQAEAAAEgCIAJgHIAAgxQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAABEQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgGADQgFADgGAAQgGAAgFgDg");
	this.shape_37.setTransform(-6.275,-17.575);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgFIgBgDIABgCIAJgFIADgCIACACIAGAHQAEADAEACIALAAQAJAAAGgCQAGgEAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgFgDgFQgCgFAAgHQAAgIAEgIQAFgGAJgFQAJgDAKAAQAIAAAGABQAHACAFAEQAGADADAEIABACIgBACIgKAHIgBAAIgCgBQgDgEgFgCQgFgDgIgBQgJAAgFAEQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMADAGAHQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAFgMAAQgJAAgIgDg");
	this.shape_38.setTransform(-15.0333,-19.15);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgIA0QAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAgBIAAg4QAAAAgBgBQAAAAAAAAQAAAAAAAAQAAAAAAAAIgMAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgCIACAAIALAAQAAAAABAAQAAAAAAAAQAAgBAAAAQABAAAAgBIAAgJQAAgJAEgFQAFgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAAIIAAACIgCAAIgIAAQgEAAgCADQgCACABAEIAAAHQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIACAAIAAACIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQAAABgBAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAA4QAAABgBABQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_39.setTransform(-25.25,-19.15);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgSAhQgJgEgFgJQgEgJAAgLQAAgKAFgJQAEgJAJgEQAIgGAKAAQALAAAJAGQAHAEAFAJQAFAJAAAKQAAALgFAJQgFAJgIAEQgIAFgLABQgKgBgIgFgAgJgWQgEACgCAHQgCAFAAAIQAAAJACAFQACAGAEADQAEADAFAAQAGAAAEgDQAEgDACgGQACgFABgJQgBgIgCgFQgCgHgEgCQgEgDgGgBQgFABgEADg");
	this.shape_40.setTransform(-32.2,-17.65);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgUAwQgHgEgEgIQgDgJAAgMQAAgMAEgIQAEgJAHgEQAHgFAJAAQAFAAAEACQAFACAEADIACABIAAgCIAAggQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAOAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABiIAAACIgDAAIgMAAIgCAAIgBgCIAAgFIAAgBIgBABIgFAEIgHADQgEACgFAAQgIAAgHgFgAgHgIQgEACgDAGQgCAFAAAKQAAAJACAGQADAGAEACQAEADAEAAQAFAAADgCQAEgCACgEQACgDAAgDIAAgfIgHgFQgEgCgEAAQgFAAgEADg");
	this.shape_41.setTransform(-43.675,-19.075);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AARAmIgBgBIgBgCIAAgvQgBgFgDgDQgCgDgGAAIgFABIgGADIgGAFIAAAxQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIANAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGIAHgDQAEgCAEAAQALAAAGAGQAGAGAAAKIAAAyQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_42.setTransform(-51.8,-17.725);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhiQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIguAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIAAAYQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAAKIAAABIgCABIgfAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAABABAAIAwAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAMIgBABIgCABg");
	this.shape_43.setTransform(-60.225,-19.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.2,-29.4,160,170);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,160,600);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,160,600);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,160,600);


(lib.Img_02_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,160,600);


(lib.Img_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_01();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,160,600);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Ag0AAIBpAAIgeAjAAcgiIAZAi");
	this.shape.setTransform(34.575,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AFrA4QgJgFgEgHIgBgDIABgBIAMgFIABABIAFAFQAEAEAEABQAFACAGgBQAFABAEgCQAEgBADgCQACgDAAgDQAAgEgDgCQgCgCgHgCIgRgEQgMgCgGgHQgFgFAAgJQAAgHAEgGQAEgGAIgEQAIgDALAAQAMAAAIAEQAJAFAEAGIABACIgBACIgKAEIgCAAIgBgBQgDgEgFgCQgFgDgHAAQgHAAgFADQgFACAAAFQAAADACACQACABAHACIATAGQAMACAGAHQAFAGAAAJQAAAIgFAGQgEAGgJADQgIADgLAAQgOAAgKgFgAD/A4QgKgFgFgLQgFgLAAgPIAAhFQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAABJQAAAOAGAGQAGAGAMAAQAIAAAFgDQAGgCADgHQADgFAAgKIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABIQAAAQgGAKQgFAJgLAFQgKAEgOAAQgRAAgKgFgABAA4QgJgGgGgKQgFgJAAgNQAAgNAFgKQAGgKAJgGQAKgFAMAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEgGIgFgEQgDgCgEAAQgHAAgFAEQgFADgCAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAHAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgMAAgKgFgAgsA3QgHgHAAgKQAAgJAFgHQAFgGALgEQAKgEAOAAIAHAAIACgBIAAgCIAAgDQAAgHgDgDQgEgFgHAAQgGAAgFADQgFADgDAFIgBACIgCAAIgOgEIgBgBIABgCQAEgJAJgGQAKgEAOAAQALAAAIADQAHAEAEAGQADAGAAAHIAAA4IAAADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBgBAAQAAgBAAAAQgBAAAAABQgBAAAAAAQgFAGgGACQgHADgIAAQgMAAgHgGgAgFATIgKABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAHAAQAEAAAEgBIAGgEIAEgFIABgFIAAgLQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAgAkbA4QgKgGgFgKQgFgKAAgMQAAgNAFgKQAGgKAJgGQAKgFAMAAQAMAAAKAGQAJAFAGAKQAFAKAAANQAAAMgGAKQgFAKgJAGQgKAFgMAAQgNAAgJgFgAkRgIQgEADgDAGQgCAHAAAJQAAAJACAIQADAGAEAEQAFADAHAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgJgDgHQgCgGgFgDQgFgEgGAAQgHAAgFAEgAmOA2QgMgIgGgOQgHgOAAgSQAAgSAHgOQAGgNAMgHIAEgCQAKgGAOAAQAJAAAIADIAGADIAIAEQAGAFAEAGQAEAGABAIIABACIgCABIgSABIgCAAIgBgCQgCgIgFgGQgGgGgKAAQgOAAgHAKQgIALAAAWQAAAWAHALQAIALAOAAQAKgBAHgFQAHgEAFgMQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANADIABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgEAIIgGAJQgEAFgFADQgGADgHADQgHACgJAAQgQAAgMgHgACVA3QgGgGAAgKIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIADgZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIASAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgSABQgLAAgFgEgAhgA3QgFgGAAgKIAAguQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgKQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIALAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAABIASAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAAAqQAAAGADADQACACAGAAIAJAAIACABIABABIgBAJQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgRABQgLAAgGgEgAiTA7IgCAAIgBgDIAAg2QAAgFgDgEQgEgDgGAAIgIABIgGADIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgEQAFgCAFAAQAMAAAHAHQAHAHAAALIAAA5QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(-9.3817,0.16,0.8099,0.8099);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(0.4,1,1).p("AoliLIRLAAIAAEXIxLAAg");
	this.shape_2.setTransform(-1.85,0.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC24D").s().p("AolCMIAAkXIRLAAIAAEXg");
	this.shape_3.setTransform(-1.85,0.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.8,-14.9,112,30);


(lib.BG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,160,600);


// stage content:
(lib.WBAY_219645_MM_160x600_V2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgMfgu3IY/AAMAAABdvI4/AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(390));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(81.9,585.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(42).to({_off:false},0).to({y:565.6,alpha:1},17,cjs.Ease.get(1)).wait(331));

	// logo_png
	this.instance_1 = new lib.logo_1("synched",0);
	this.instance_1.setTransform(80,290);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({y:300,alpha:1},17,cjs.Ease.get(1)).wait(362));

	// T3
	this.instance_2 = new lib.T3("synched",0);
	this.instance_2.setTransform(80.25,540.05);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(272).to({_off:false},0).to({y:520.05,alpha:1},15,cjs.Ease.get(1)).wait(103));

	// T2
	this.instance_3 = new lib.T2("synched",0);
	this.instance_3.setTransform(80.05,493.15);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(151).to({_off:false},0).to({y:473.15,alpha:1},16,cjs.Ease.get(1)).wait(77).to({startPosition:0},0).to({alpha:0},11).to({_off:true},1).wait(134));

	// T1
	this.instance_4 = new lib.T1("synched",0);
	this.instance_4.setTransform(76.3,374.55);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(26).to({_off:false},0).to({y:394.55,alpha:1},17,cjs.Ease.get(1)).wait(81).to({startPosition:0},0).to({alpha:0},10).to({_off:true},1).wait(255));

	// Img_04_jpg
	this.instance_5 = new lib.Img_04_1("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(299).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(74));

	// Img_03_jpg
	this.instance_6 = new lib.Img_03_1("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(255).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(118));

	// Img_02_jpg
	this.instance_7 = new lib.Img_02_1("synched",0);
	this.instance_7.setTransform(80,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(134).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(239));

	// Img_01_jpg
	this.instance_8 = new lib.Img_01_1("synched",0);
	this.instance_8.setTransform(80,300);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(14).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(359));

	// BG_jpg
	this.instance_9 = new lib.BG_1("synched",0);
	this.instance_9.setTransform(80,300);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},17,cjs.Ease.get(1)).wait(373));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(79,290,82,311);
// library properties:
lib.properties = {
	id: '0A6D29F88ACD4E3BA69B7CAF200CDDDF',
	width: 160,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0A6D29F88ACD4E3BA69B7CAF200CDDDF'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;