(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.IM1 = function() {
	this.initialize(img.IM1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.IM2 = function() {
	this.initialize(img.IM2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.IM3 = function() {
	this.initialize(img.IM3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.IM4 = function() {
	this.initialize(img.IM4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.PBB_logo1 = function() {
	this.initialize(img.PBB_logo1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,244,194);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// T3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#993020").s().p("AgJA1QgGgHAAgDQAAgEAGgHQAGgFADAAQAEAAAGAFQAGAGAAAFQAAADgGAHQgGAGgEAAQgDAAgGgGgAgGAPIgBgKIgFgbQgCgMAAgJQAAgPAOAAQAPAAAAAQQAAAHgCANQgEAQAAALIgCAKQgCAEgFAAQgEAAgCgEg");
	this.shape.setTransform(-274.75,-15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993020").s().p("AAKA8QgGAAAAgEQAAgDAEgCQAEgDABgEQACgEAAgNIAAgUQAAgNgNAAQgFAAgEAEQgIAGABAXQAAANABAEQACAEAEADQAEACAAADQAAAEgGAAIgiAAQgHAAAAgEQAAgDAFgCQAEgDABgEQACgEAAgNIAAg2QAAgHgCgDQgBgDgEgDIgEgBIgBgDQAAgDAGgBQANgDAIgEIAFgBQADAAABAGIAAAqIAAABIABgBQAJgOAQAAQAPAAAIAMQAEAHAAANIAAAUQAAAMACAFQABAEAFADQAEACAAADQAAAEgGAAg");
	this.shape_1.setTransform(-281.95,-15.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#993020").s().p("AgQAoQgEgHAAgOIACgiQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgKAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgHQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQALgCAEgGQADgDABgJQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAJAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAPIABAEIAEABIAHgBIAJgBQAGAAAAAEIgBAFIgCAEIgGABIgIAAIgIAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAANQAAAWACAHQAEAJAHAAQADAAAEgCIAGgDQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABQAAACgCADQgHAMgRAAQgPAAgHgMg");
	this.shape_2.setTransform(-290.6,-14.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#993020").s().p("AACA6QgDAAAAgEIAAhOQAAgJgBgCQgBgDgFAAIgMAAQgEABAAgIQAAgEAEgBIAOgCIANgCIAMgDQAGAAAAAGIAABpQAAAEgEAAg");
	this.shape_3.setTransform(-300.225,-15.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#993020").s().p("AACA6QgDAAAAgEIAAhOQAAgJgBgCQgBgDgFAAIgMAAQgEABAAgIQAAgEAEgBIAOgCIANgCIAMgDQAGAAAAAGIAABpQAAAEgEAAg");
	this.shape_4.setTransform(-307.925,-15.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#993020").s().p("AgnA1QgEgFgBgHQAAgLAJAAQACAAAFAFQAFAFAFAAQAGAAAEgHIABgCIgBgCIgbg+QgDgJgDgDIgFgDQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgEAGAAIAiAAQAGAAAAAEQAAACgEACQgEACAAAEIACAGIAOAjIABABIABgBIAKgXQADgJAAgGQABgFgFgDQgEgDAAgCQAAgEAGAAIAaAAQAGAAAAAEQAAAAAAABQAAABgBAAQAAABAAAAQAAAAgBABIgEADIgGAGQgDAFgGAMIgSAtQgOAigXAAQgIAAgFgEg");
	this.shape_5.setTransform(-318.1,-11.925);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#993020").s().p("AAJAgIAAgBIgBAAQgIANgRAAQgKAAgHgGQgIgGAAgKQAAgMAMgHQAHgEATgGQALgGAAgIQAAgJgJAAQgGAAgEADQgEACgFAIQgEAFgEAAQgDAAgCgCQgBgDgBgFQAAgJAEgDQADgFAKgCQAJgCAIAAQANAAAKAHQAMAHAAAOIgBAdIABALQABAEAFAAQAEAAAAAEQAAADgEADQgFAFgJAAQgMAAgEgMgAAGAAQgLAEgFAFQgGAEgBAGQAAAEADADQADADAEAAQAIAAAEgIQACgFAAgOIAAgCIgBAAg");
	this.shape_6.setTransform(-327.35,-13.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#993020").s().p("AAaA5QgFAAAAgEQAAgCADgDQAFgDABgEQACgEAAgMIAAg7IgBgBIgBABIgdBFQgBADgCAAIgHAAQgDAAgBgDIgdhFIgBgBIgBABIABA/QAAANAJAEIAFADQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABQAAAEgGAAIgdAAQgHAAABgEQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABgBIAEgDQAEgHABgTIAAg7IAAgEIgEgDIgEgDQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQgBgEAHAAIAgAAQAFAAACAEIAWA0IAAABIABgBIAWg0QABgEAEAAIAjAAQAGAAAAAEQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAAAIgEADQgFACABAKIAAA8QgBAMACAEQACAFAEACQADADAAACQABAEgHAAg");
	this.shape_7.setTransform(-339.05,-15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3927").s().p("AAHApQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQAEgCABgDQABgDAAgJIAAgNQAAgJgJAAQgEAAgDADQgEAEAAAPQAAAJABADQAAADAEACQABAAAAABQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIgXAAQgEAAAAgDQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBABAAQAEgCABgDIABgMIAAgkIgBgIQgBgCgEgBIgCgBQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAQAAgCAEgBIAPgEIADgBQABAAAAAAQABAAAAABQAAAAAAABQABABAAAAIAAAdIAAABIABgBQAHgIAKgBQAKABAFAHQADAGABAIIAAANIABAMQAAADADACQABAAABABQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQgBAAgBAAg");
	this.shape_8.setTransform(-259.45,-30.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3927").s().p("AgTAmQgKgEABgHQAAgIAHgCIABgBIgBAAQgCgCAAgDQAAgIAIgDIABAAIgBAAQgLgGAAgLQAAgJAHgGQAIgHAKAAQAGABAGACIAFADQABAAAAgBQABAAAAAAQAAAAABgBQAAAAAAgBQACgDAEAAQAEAAAAAGQAAAHgGAAIgCgBQACAEAAAFQAAAJgHAGQgIAFgIAAIgCAAQgIAAAAADQAAADAKABIAJAAQAKAAAEADQAGAEgBAFQABAJgIAEQgIAGgOAAQgKAAgIgCgAgQAXQAAAGAGABQAFACAFAAQAHAAAEgCQAEgBAAgEQAAgDgIAAIgHAAQgLAAgEgBIgBACgAgJgVQAAAGACAEQACAGAFAAQACAAACgDQACgDAAgFQAAgFgBgEQgDgGgDAAQgIAAAAAKg");
	this.shape_9.setTransform(-266.25,-28.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3927").s().p("AAKAaIAAgFIAAgBIAAAAQgHAKgKAAQgLAAgFgIQgDgFAAgJIAAgPIgBgHQgBgCgDgCQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABgBIAQgEIADgBQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAgQAAAFADACQACAEAEAAQAEAAADgDQAEgFAAgPIAAgJQgBgCgDgCQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQABAAABgBIAPgEIADgBQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAAhIABAHQABADADABQABAAAAAAQABABAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgQAEIgDABQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBg");
	this.shape_10.setTransform(-272.925,-29.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3927").s().p("AgVAWQgIgIAAgOQAAgLAJgJQAJgJAMAAQANAAAIAIQAIAJAAAMQAAAMgIAJQgJAJgNAAQgMAAgJgIgAgMgDQAAAHADAIQAEAJAGAAQAGAAADgFQADgFAAgIQAAgIgDgGQgEgKgGAAQgMAAAAASg");
	this.shape_11.setTransform(-279.425,-29.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3927").s().p("AgTAdQgEAAAAgDQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAEgCABgDQABgCAAgJIAAgNIgBgIQgBgCgDgBQgBgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAOgEIADgBQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAJIAAAAIAAAAQACgFADgDQAFgEAFAAQAEAAADADQADADgBAEQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAIgFgCIgEgBQgKAAAAAVIABALQABADADACQABABAAAAQABAAAAABQABAAAAABQAAAAAAAAQAAADgEAAg");
	this.shape_12.setTransform(-284.85,-29.275);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3927").s().p("AAHApQgBAAgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBABAAQACgCABgDQACgDAAgJIAAgNQAAgJgJAAQgDAAgDADQgGAEAAAPQABAJABADQABADADACQABAAAAABQABAAAAABQAAAAAAAAQABABAAAAQAAADgFAAIgXAAQgFAAAAgDQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBABAAQADgCABgDIABgMIAAgkIgBgIQAAgCgDgBIgDgBQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBQABAAAAgBQABAAAAAAQABgBABAAIAPgEIADgBQABAAAAAAQABAAAAABQAAAAAAABQAAABAAAAIAAAdIABABIABgBQAGgIAKgBQALABAFAHQAEAGgBAIIAAANIABAMQACADADACQAAAAABABQAAAAAAABQABAAAAAAQAAABAAAAQAAADgEAAg");
	this.shape_13.setTransform(-291,-30.45);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3927").s().p("AgLAoQgFAAAAgDQAAgBAAAAQAAAAABgBQAAAAAAAAQABgBABAAQADgCAAgCQACgDAAgJIAAgsQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQgEAAgDACQgFACgCAGIgCAEIgCABQgGAAAAgEIABgKIAAgHIABgDIAFgBIAVABIAOAAIAWgBIAFABIABADIAAAIIAAAJQAAAEgEAAIgDgBIgCgEQgDgGgEgCQgDgCgEAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAAAABIAAAsQAAAIABADQACADADACQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAABQAAADgEAAg");
	this.shape_14.setTransform(-298.2,-30.325);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("AgTAZQgEgDAAgJQAAgFAEAAIADABIAEAFQAGAHAGAAQADAAACgBQADgCAAgDQAAgDgFgCIgJgEQgHgCgDgDQgFgDAAgHQAAgJAHgGQAHgFAJAAQAJAAAFADQAFACAAAHIgBAGQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAgBgBQAAAAAAAAQgBgBAAgBQgGgIgHAAQgCAAgCACQgBABAAAAQAAAAgBABQAAABAAAAQAAABAAAAQAAADAEACIAKAEQAQAGAAAKQAAAJgIAGQgHAFgKAAQgMAAgGgFg");
	this.shape_15.setTransform(-307.375,-29.225);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AAHAdQgFAAAAgDQAAAAABAAQAAgBAAAAQABgBAAAAQABAAABgBQACgCABgDIABgLIAAgNQAAgKgJAAQgCAAgDADQgGAFAAAPIABALQABADAEACQAAABABAAQAAAAABABQAAAAAAABQABAAAAAAQgBADgEAAIgXAAQgFAAAAgDQAAAAABAAQAAgBAAAAQAAgBABAAQAAAAABgBQADgCABgDIABgLIAAgNIgBgIQgBgCgCgBQgBgBgBAAQgBAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQABAAABAAIAOgFIAEAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAGIABAAIAAAAQAHgJAKAAQAKAAAGAIQADAFAAAJIAAANIABALQABADADACQABABAAAAQABAAAAABQABAAAAABQAAAAAAAAQAAADgEAAg");
	this.shape_16.setTransform(-313.05,-29.275);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("AAKAaIAAgFIAAgBIAAAAQgHAKgKAAQgLAAgFgIQgDgFAAgJIAAgPIgBgHQgBgCgDgCQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABgBIAQgEIADgBQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAgQAAAFADACQACAEAEAAQAEAAADgDQAEgFAAgPIAAgJQgBgCgDgCQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAQABAAABgBIAPgEIADgBQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAAhIABAHQABADADABQABAAAAAAQABABAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgQAEIgDABQAAAAgBAAQgBgBAAAAQAAgBgBAAQAAgBAAgBg");
	this.shape_17.setTransform(-320.025,-29.225);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AAYAnQgHAAgCgEQgCgCgGgOQgGgPgKAAIgBAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAABIAAALQAAAJABACQABAEADABQABABAAAAQABAAAAABQAAAAABABQAAAAAAAAQAAADgEAAIgaAAQgEAAAAgDQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABgBQADgCABgDQABgCAAgJIAAgpQAAgGgDgCIgDgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAQABAAABAAIAWAAIAJAAQAQAAAGAFQAHAFAAAJQAAAEgBADQgFAJgMACIgBAAIABABQAHAAAEAFQADAEAEAKQAFALADADIACABQABABAAAAQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAAAQgBAAgBAAgAgMgcIAAAWQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIAEAAQAGAAADgDQAEgEAAgGQAAgMgMAAIgFAAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAg");
	this.shape_18.setTransform(-327.375,-30.275);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("AgTAZQgEgDAAgJQAAgFAEAAIADABIAEAFQAGAHAGAAQADAAACgBQADgCAAgDQAAgDgFgCIgJgEQgHgCgDgDQgFgDAAgHQAAgJAHgGQAHgFAJAAQAJAAAFADQAFACAAAHIgBAGQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAgBgBQAAAAAAAAQgBgBAAgBQgGgIgHAAQgCAAgCACQgBABAAAAQAAAAgBABQAAABAAAAQAAABAAAAQAAADAEACIAKAEQAQAGAAAKQAAAJgIAGQgHAFgKAAQgMAAgGgFg");
	this.shape_19.setTransform(-337.525,-29.225);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AgSAWQgIgIAAgMQAAgMAIgJQAJgKALAAQAKAAAHAGQAIAHAAAKQAAAEgDACIgGAAIgaAAIgBABIAAABQAAAFADADQAFAJAKAAQAFAAAFgCIAEgDQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQABADgHAFQgIAFgKAAQgLAAgIgIgAgFgSQgDAEgBAFIgBABQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAMAAQAHAAAAgFQgBgDgCgDQgCgDgEAAQgEAAgDADg");
	this.shape_20.setTransform(-343.25,-29.225);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AgKApQgFAAAAgDQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBABAAQADgCABgDIABgMIAAgkIgBgIQgBgCgDgBQgBAAAAgBQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAABAAQABgBABAAIAOgEIADgBQAAAAABAAQABAAAAABQAAAAABABQAAABAAAAIAAA3IABAMQABADADACQAAAAABABQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAg");
	this.shape_21.setTransform(-347.575,-30.45);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AAHAWIgBgBIAAABQgGAIgLAAQgHAAgFgEQgGgEAAgHQAAgIAIgFIASgHQAIgDAAgGQAAgGgGAAQgEAAgDACQgDABgDAFQgDAEgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgFQAAgGACgCQACgDAIgCIALgBQAJAAAGAEQAIAFAAAKIAAAUQAAAGABABQAAADAEAAQABAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQAAADgDACQgEADgGAAQgIAAgCgIgAgHAGQgEADAAAEQAAABAAABQAAAAAAABQABAAAAABQAAAAABABQACACADAAQAFAAACgGQACgDAAgKIAAgBIgBAAIAAAAIgLAGg");
	this.shape_22.setTransform(-352.425,-29.225);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AgRAmQgIgCgCgEQgCgEAAgGIgBgEQABgFAEAAQAAAAABAAQAAAAABABQAAAAABAAQABABAAABIAGAHQAIAJAIgBQAGAAADgDQADgDAAgFQAAgFgGgEIgNgGQgJgDgFgDQgHgGAAgIQAAgLAJgGQAJgIAMAAQAOAAAHAHQADADAAAHQAAAIgFAAQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgFgGQgGgHgIgBQgDAAgDADQgEACAAAEQAAAGAHADIANAGQAJADAFAEQAGAFABAKQAAALgJAIQgKAGgNAAQgIAAgIgCg");
	this.shape_23.setTransform(-359.55,-30.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},47).to({state:[]},1).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},120).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},11).to({state:[]},1).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},11).wait(55));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-369.9,-37.6,119.99999999999997,34);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#993020").s().p("Ag6BCQgSgaAAgmQAAgoAXgbQAXgbAgAAQAjAAAUAZQAUAZAAAoQAAAtgYAZQgWAZgfAAQglAAgVgbgAgfgFQAAAgAJAWQAJAXAOgBQAfABAAhCQAAglgKgVQgJgTgNAAQgfAAAABCg");
	this.shape.setTransform(-241.225,-25.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993020").s().p("AACBbIgxAAQgPAAAAgSQAAgYAZgZIAYgVQAOgMAGgIQAKgNAAgPQAAgKgFgIQgGgIgKAAQgPAAgMATIgHAMQgEAGgFAAQgKAAAAgTQAAgSALgIQASgMAZAAQAYAAATANQAUAOAAAYQAAAYgVASQgLAIgWALQgVALgHAGQgKAHAAAHQAAAEAFAAIAnAAQAWAAAGgDQAFgBAEgFQAEgFADAAQAHAAAAAIIgDAQQgBAOgCAEQgEAIgMAAg");
	this.shape_1.setTransform(-256.925,-25.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#993020").s().p("AgxBDQgRgWAAgkQAAglARgdQAVgjAmAAQAcAAALALQAHAIgBAOQABAUgMAAQgEAAgFgEIgGgMQgLgSgNAAQgOAAgJASQgHARgBAcIABABIACgBQANgWAZABQAXAAAOAQQAPAPAAAXQAAAdgRAUQgTAVgfAAQgfAAgSgagAgQADQgIAKAAAUQAAATAHAKQAHALALAAQANAAAHgMQAGgLAAgRQAAgSgGgLQgIgKgMABQgKAAgHAIg");
	this.shape_2.setTransform(-270.2,-25.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#993020").s().p("AgcAmQAAgDAEgCIAKgIQALgKAAgIQAAgGgHgGQgKgLAAgEQAAgGAJgJQAKgJAEAAQAEAAAGAEIAIAIQAIAKAAAJQAAAOgYAZQgRATgJAAQgHAAAAgHg");
	this.shape_3.setTransform(-281.375,-16.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#993020").s().p("AgEBbQgKAAAAgGQgBgEAHgEQAHgDABgIQADgFAAgNQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBAAAAAAIhCAAQgEAAAAgGIAAgOQAAgHADgFQATgdAIgWQAJgYAAgYQAAgGAHABIAVAAQAFgBAAAFIAAABQgBAWgLAaQgKAWgWAcIgBACQAAAAAAABQAAAAAAAAQABAAAAAAQAAABABAAIApAAQAAAAABgBQAAAAAAAAQABAAAAgBQAAAAAAgBIAAg/QAAgFAEABIAdAAQAFgBAAAFIAAA/QAAABAAAAQAAABABAAQAAAAAAAAQABABAAAAIAWAAQAFgBAAAGIAAASQAAAFgFABIgWAAQAAAAgBAAQAAAAAAAAQAAABAAAAQgBABAAAAQABANACAFQACAIAHADQAGAEAAAEQABAGgKAAg");
	this.shape_4.setTransform(-291.25,-25.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#993020").s().p("AAEBbQgFABAAgHIAAh9QAAgMgBgFQgCgDgJAAIgSABQgHAAAAgMQAAgHAFAAIAXgEIAVgFIAUgDQAIgBAAAJIAACnQAAAHgGgBg");
	this.shape_5.setTransform(-309,-25.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#993020").s().p("AgCBnQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgSQgQAAgOgFQgPgFgEgHQgDgFgCgHIAAgJIgBgIQABgKAHAAQAFABAEAFQAGAIAGAGQAQARAQAAIAJgBQAHgCAGgFQAEgGAAgIQAAgLgNgHQgFgDgWgIQgTgIgJgHQgMgKgBgSQABgSAPgOQANgNAUgCIAAgWQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAKAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAIAAAVQAaACALAKQAFAGABAPQAAAQgKAAQgDAAgFgGIgLgNQgOgMgLAAQgHgBgGAFQgHAFAAAJQAAAKANAIIAbALQATAHAJAHQANAMAAATQAAATgPAOQgOANgVADIAAAUQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-321.25,-26.55);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3829").s().p("AgMAfQgDgFAAgLIABgbQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgGQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQAJgBADgFQACgCABgHQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAMIABADIADAAIAFAAIAIgBQAEAAAAADIgBAEIgBADIgFABIgGAAIgHAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAALQAAARACAGQACAHAGAAQADAAADgCIAEgCQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAABQgBAAAAABQgGAJgNAAQgMAAgFgKg");
	this.shape_7.setTransform(-332.825,-20.125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3829").s().p("AAIAZIgBgBIAAABQgHAJgNAAQgIAAgGgEQgGgFAAgIQAAgKAJgFQAGgDAPgFQAIgEAAgGQAAgIgHAAQgEAAgDADQgDACgEAFQgDAFgDAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAIgBgGQAAgHADgDQACgDAJgCIANgBQAKAAAIAEQAJAGAAALIgBAXIABAJQABADAEAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABQAAACgDADQgEADgHAAQgKAAgCgJgAAEAAQgHADgFAEQgFADAAAFQAAADACACQADACADAAQAGAAADgGQABgDAAgMIAAgBIAAAAg");
	this.shape_8.setTransform(-339.025,-19.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3829").s().p("AgVArQgMgEAAgJQAAgIAJgDIAAgBQgCgDAAgDQAAgIAKgEIAAAAIAAAAQgOgHAAgNQAAgLAIgGQAJgIALAAQAIAAAGADIAHAEIADgEQACgDAEAAQAGAAAAAHQAAAHgJAAIgBAAQACAEAAAGQAAAKgIAHQgJAGgKAAIgCAAQgIAAAAAEQAAAEAKgBIAMAAQAKABAGADQAFAEAAAIQAAAJgIAGQgJAGgRAAQgLAAgIgDgAgTAaQABAGAGADQAGACAGAAQAIAAAEgDQAFgCAAgDQAAgEgJAAIgJAAQgLAAgFgCIgCADgAgLgYQAAAGADAFQADAHAEAAQAEAAABgEQACgDAAgGQAAgGgBgEQgDgHgEAAQgJAAAAAMg");
	this.shape_9.setTransform(-349.55,-18.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3829").s().p("AAIAiQgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAQAEgCABgEIABgNIAAgPQAAgLgKAAQgEgBgEAEQgFAGAAARIABANQABAEAEACQABAAAAAAQABABAAAAQABABAAAAQAAABAAAAQAAAEgFAAIgbAAQgFAAABgEQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAAAQAEgCABgEIABgNIAAgPIAAgIQgBgDgEgCQgEgCAAgCQAAgCAEgBIARgFIADgBQAEAAAAAFIAAAFIABABIAAAAQAHgLAMAAQAMAAAGAJQAEAGAAALIAAAPIABANQABAEAEACQABAAAAAAQABABAAAAQABABAAAAQAAABAAAAQAAAEgFAAg");
	this.shape_10.setTransform(-357.15,-19.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3829").s().p("AgMAwQgFAAAAgEQAAAAAAgBQAAAAABAAQAAgBABAAQAAgBABAAQADgCABgEQACgDAAgKIAAgQIgBgIQgBgCgDgCQgFgBAAgCQAAgDAFgBIAQgFIADAAQADAAAAAEIAAAkQAAAKACADQABAEADACQABAAABABQAAAAABABQAAAAAAAAQAAABAAAAQABAEgFAAgAgGgbQgFgFAAgDQAAgDAFgEQAEgFACAAQADAAAEAFQAFAEABADQgBADgFAFQgEAEgDAAQgCAAgEgEg");
	this.shape_11.setTransform(-363.35,-20.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3829").s().p("AgMAfQgDgFAAgLIABgbQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAAAAAIgIAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgGQAAAAAAAAQABgBAAAAQAAAAAAAAQABgBAAAAQAJgBADgFQACgCABgHQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAHAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAMIABADIADAAIAFAAIAIgBQAEAAAAADIgBAEIgBADIgFABIgGAAIgHAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAALQAAARACAGQACAHAGAAQADAAADgCIAEgCQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAABQgBAAAAABQgGAJgNAAQgMAAgFgKg");
	this.shape_12.setTransform(-368.075,-20.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3829").s().p("AgWAiQgEAAgBgEQAAAAABgBQAAAAAAgBQABAAAAgBQABAAAAAAQAEgCABgEQABgDAAgKIAAgPIAAgJQgCgDgDgBQgEgCAAgCQAAgCAEgBQAJgCAGgDIAFgBQADAAAAAFIAAAJIAAABIAAgBQADgFAEgEQAFgEAFgBQAFABAEADQACADAAAFQAAAEgCACQgBACgDAAIgFgCIgGgBQgLgBAAAZQAAAJABAEQABAEAEACQABAAAAAAQABABAAAAQABABAAAAQAAABAAAAQAAAEgEAAg");
	this.shape_13.setTransform(-373.8,-19.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3829").s().p("AAIAZIgBgBIAAABQgHAJgNAAQgIAAgGgEQgGgFAAgIQAAgKAJgFQAGgDAPgFQAIgEAAgGQAAgIgHAAQgEAAgDADQgDACgEAFQgDAFgDAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAIgBgGQAAgHADgDQACgDAJgCIANgBQAKAAAIAEQAJAGAAALIgBAXIABAJQABADAEAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABQAAACgDADQgEADgHAAQgKAAgCgJgAAEAAQgHADgFAEQgFADAAAFQAAADACACQADACADAAQAGAAADgGQABgDAAgMIAAgBIAAAAg");
	this.shape_14.setTransform(-380.325,-19.425);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3829").s().p("AgMAfQgDgFAAgLIABgbQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgIAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgGQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQAJgBADgFQACgCABgHQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAMIABADIADAAIAFAAIAIgBQAEAAAAADIgBAEIgBADIgFABIgGAAIgHAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAALQAAARACAGQACAHAGAAQADAAADgCIAEgCQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAABQgBAAAAABQgGAJgNAAQgMAAgFgKg");
	this.shape_15.setTransform(-386.825,-20.125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3829").s().p("AgUAsQgIgDgDgFQgCgDAAgIIgBgFQAAgFAFAAQACAAADADIAHAIQAIAKAKAAQAGAAAEgDQAFgFgBgEQABgHgIgFIgPgGQgLgEgFgDQgIgHAAgKQAAgMAKgHQAKgJAOABQARgBAIAIQACACAAAKQAAAIgEAAQgDAAgCgCIgFgGQgIgKgIAAQgEABgDACQgEADAAAFQAAAGAHAEIAPAGQALAFAGAEQAHAGAAALQAAANgLAIQgKAIgQAAQgJAAgJgCg");
	this.shape_16.setTransform(-393.55,-20.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-399.1,-37.4,167.10000000000002,28.799999999999997);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// T1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3829").s().p("AgFAhQgEgEAAgCQAAgDAEgDQAEgEABAAQACAAAEAEQAEADAAADQAAACgEAEQgEAEgCAAQgBAAgEgEgAgDAKIgBgHIgDgQIgCgNQAAgKAJAAQAJAAAAAKIgBANIgCAQIgCAHQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAQgCAAgBgCg");
	this.shape.setTransform(-230.6,-23.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B3829").s().p("AgRAXQgEgDAAgIQAAgFAEAAIADACIADAEQAFAGAGAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAQAAgBABAAQABgBAAAAQAAgBABAAQAAgBAAAAQAAgDgFgCIgIgDQgHgCgDgDQgEgDAAgGQAAgJAHgEQAGgFAIAAQAIAAAFACQAEADAAAGQAAABAAABQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAgBgBAAQgEgIgHAAQgCAAgCACQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAADAFACIAIADQAPAFAAAKQAAAIgIAFQgGAEgJAAQgLAAgFgEg");
	this.shape_1.setTransform(-234.825,-22.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B3829").s().p("AgQAUQgIgHABgLQgBgLAIgIQAIgJAKAAQAJAAAGAFQAIAGgBAJQAAAEgBACQgCAAgFAAIgXAAIgBABIAAABQAAAEADAEQAEAHAJAAQAFAAAEgCIAFgCQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAEgHAEQgGAEgKAAQgKAAgHgHgAgEgQQgDADgBAFIAAABIABABIALAAQAGAAAAgFQAAgDgDgCQgBgDgFAAQgDAAgCADg");
	this.shape_2.setTransform(-240.05,-22.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B3829").s().p("AgJAmQgBAAgBAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQADgCABgDQABgDAAgIIAAgMIgBgGQgBgCgDgBQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBQABAAAAgBQABAAAAAAQABAAABAAIANgFIACgBQABAAAAABQABAAAAAAQAAABABAAQAAABAAABIAAAcQAAAIABADQABADACACQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAgAgFgVQgDgEAAgCQAAgCADgFQAEgDABAAQADAAADADQAEAFAAACQAAACgEAEQgDADgDAAQgBAAgEgDg");
	this.shape_3.setTransform(-244.225,-23.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B3829").s().p("AgRAbQgBAAAAAAQgBgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABgBQACgBABgDQABgDAAgIIAAgMIAAgGQgBgCgDgCQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAIAMgEIAEgBQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAHIAAABIAAgBQACgEADgDQAEgEAFAAQAEAAACADQACADAAAEIgBAEQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgEgBIgFgCQgJAAAAATQAAAIABADQABADADABQAAABABAAQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_4.setTransform(-248.375,-22.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B3829").s().p("AgQAUQgHgHgBgLQABgLAHgIQAIgJAKAAQAJAAAHAFQAGAGAAAJQAAAEgCACQgBAAgFAAIgXAAIgBABIAAABQAAAEADAEQAEAHAKAAQAEAAAEgCIAEgCQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAAEgFAEQgIAEgJAAQgKAAgHgHgAgFgQQgCADgBAFIAAABIABABIAKAAQAHAAAAgFQAAgDgCgCQgDgDgDAAQgDAAgEADg");
	this.shape_5.setTransform(-253.6,-22.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B3829").s().p("AgPAjQgHgDgDgDQgCgDAAgGIAAgEQAAgEAEAAQAAAAABAAQAAAAABAAQAAABABAAQAAABABAAIAFAHQAIAHAGAAQAGAAADgCQADgDAAgEQAAgGgGgDIgMgFQgIgDgEgDQgGgFAAgIQAAgJAIgGQAHgHALAAQAOAAAGAGQACACAAAHQAAAHgEAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgEgEQgHgIgGAAQgDAAgDACQgDACAAAEQAAAFAGAEIAMAFQAJADAEADQAGAFAAAJQAAAKgJAGQgIAHgMAAQgIAAgGgCg");
	this.shape_6.setTransform(-259.775,-23.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3829").s().p("AADAaQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIABgDQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgCgEgHIgCgDIgBAAIgBAAQgFAIAAADQAAABAAAAQABAAAAABQAAAAABABQAAAAABABIACADQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgSAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgCAEgCQAEgEAHgJIAFgHIABAAIgBgBIgGgJIgFgGIgFgDIgDgBIgBgCQAAgBAAgBQABAAAAAAQABgBAAAAQABAAABAAIAYAAQABAAABAAQAAAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAAAABQAAAAAAAAQAAADAEAGIACAEIABAAIAAAAQAFgJAAgCQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAIgDgCQAAgBAAgBQABAAAAAAQABgBAAAAQABAAABAAIASAAQABAAAAAAQABAAABABQAAAAAAAAQABABAAABIgEADQgEADgHAKIgGAGIAAABIAAABIAHAJIAFAGIAFADIACACQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_7.setTransform(-267.375,-22.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3829").s().p("AgTAUQgHgHAAgNQAAgKAIgIQAIgIALAAQAMAAAHAIQAHAHAAALQAAALgHAIQgIAIgMAAQgLAAgIgHgAgKgDQAAAHACAHQADAJAGAAQAFAAADgFQACgFAAgHQAAgHgCgGQgDgJgGAAQgKAAAAAQg");
	this.shape_8.setTransform(-273.075,-22.625);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3829").s().p("AgKAiIgDgBQAAAAgBAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQgDAAAAgEIAAgzIAAgHQAAAAgBgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAOgEIADgBQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAaIABABIABgBQAFgIAKAAQAJAAAGAIQAFAHAAAJQAAAMgHAJQgIAJgMAAQgHAAgGgEgAgEAAQgDAFAAAHQAAAJADAFQAEAEAEAAQAFAAADgFQADgFAAgIQAAgIgDgEQgEgFgFAAQgFAAgCAFg");
	this.shape_9.setTransform(-279.325,-23.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3829").s().p("AgKAZQgCgFAAgIIABgVQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAAAAAgBIgGAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAgEQAAAAABgBQAAAAAAAAQAAAAAAgBQABAAAAAAQAHgBACgEIADgHIACgBIAFAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAAJIAAACIACABIAFAAIAFgBQABAAABABQABAAAAAAQABAAAAABQAAAAAAAAIgBAEIgBACIgDABIgFAAIgFgBQgBABAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAIQAAANABAFQABAFAGABQAAAAABgBQAAAAABAAQAAAAABAAQABgBAAAAIADgCQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQgBABAAAAQgFAHgKABQgJgBgFgHg");
	this.shape_10.setTransform(-284.5,-23.15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3829").s().p("AgKAlQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQADgCABgDQABgCAAgIIAAghIgBgHQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAgBAAQgBgBAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAIANgEIADAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAyQAAAIABACQABADACACQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_11.setTransform(-287.875,-23.725);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3829").s().p("AAGAUIgBgBIAAABQgFAHgKAAQgGAAgFgDQgFgEAAgGQAAgIAHgEQAFgCALgEQAHgDAAgFQAAgGgGAAQgDAAgCACQgDABgDAFQgDADgBAAIgEgBIgBgFQAAgGACgCQACgDAHgBIAKgBQAIAAAGAEQAHAEABAJIgBASIABAHQAAAAAAABQAAAAABABQAAAAABAAQABAAAAAAQABAAABABQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAgBABQgDACgFAAQgJAAgBgHgAADAAQgFADgEADQgEACAAAEQAAABAAAAQAAABAAABQABAAAAAAQAAABABAAQAAABABAAQAAABABAAQAAAAABAAQAAAAABAAQAEAAADgFIABgMIAAgBIAAAAg");
	this.shape_12.setTransform(-292.3,-22.625);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3829").s().p("AgPAjQgHgDgDgDQgCgDAAgGIAAgEQAAgEAEAAQAAAAABAAQAAAAABAAQAAABABAAQAAABABAAIAFAHQAIAHAGAAQAGAAADgCQADgDAAgEQAAgGgGgDIgMgFQgIgDgEgDQgGgFAAgIQAAgJAIgGQAHgHALAAQAOAAAGAGQACACAAAHQAAAHgEAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgEgEQgHgIgGAAQgDAAgDACQgDACAAAEQAAAFAGAEIAMAFQAJADAEADQAGAFAAAJQAAAKgJAGQgIAHgMAAQgIAAgGgCg");
	this.shape_13.setTransform(-298.775,-23.575);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3829").s().p("AgRAbQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABgBQACgBABgDQABgDAAgIIAAgMIAAgGQgBgCgDgCQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAIAMgEIAEgBQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAHIAAABIAAgBQACgEADgDQAEgEAFAAQAEAAACADQACADAAAEIgBAEQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgEgBIgFgCQgJAAAAATQAAAIABADQABADADABQAAABABAAQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_14.setTransform(-305.325,-22.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3829").s().p("AAJAYIAAgFIAAgBIAAABQgHAIgJAAQgJAAgEgHQgEgEAAgJIAAgNIgBgHQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIAOgEIADgBQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAeQgBAEACACQADADAEAAQACAAADgDQAEgEAAgOIAAgIQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQABAAABAAIANgEIADgBQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABIAAAeIAAAHQAAAAABABQAAAAAAABQABAAAAABQABAAAAAAQABABABAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAQgBABgBAAIgNAEIgDAAQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBg");
	this.shape_15.setTransform(-311,-22.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3829").s().p("AgTAUQgHgHAAgNQAAgKAIgIQAIgIALAAQAMAAAHAIQAHAHAAALQAAALgHAIQgIAIgMAAQgLAAgIgHgAgKgDQAAAHACAHQADAJAGAAQAFAAADgFQACgFAAgHQAAgHgCgGQgDgJgGAAQgKAAAAAQg");
	this.shape_16.setTransform(-316.925,-22.625);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3829").s().p("AAGAbQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQABAAAAgBQADgBABgDQABgDAAgIIAAgLQAAgJgIAAQgDAAgDACQgEAFAAANQAAAIABADQAAADADABQABABAAAAQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAQgBABAAAAQgBAAgBABQAAAAgBAAIgWAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQABAAAAgBQADgBABgDQABgDAAgIIAAgLIgBgHQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAQABgBABAAIANgEIADgBQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAAFIAAAAIABAAQAFgJAKAAQAJAAAFAIQADAEAAAJIAAALIABALIADAEQABABAAAAQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_17.setTransform(-324.775,-22.675);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3829").s().p("AgTAUQgHgHAAgNQAAgKAIgIQAIgIALAAQAMAAAHAIQAHAHAAALQAAALgHAIQgIAIgMAAQgLAAgIgHgAgKgDQAAAHACAHQADAJAGAAQAFAAADgFQACgFAAgHQAAgHgCgGQgDgJgGAAQgKAAAAAQg");
	this.shape_18.setTransform(-330.775,-22.625);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#A72415").s().p("AAKAoQgFgHAAgKQAAgLAHgHQAGgGAJAAQALAAAGAGQAGAHABALQAAAMgIAGQgGAHgKAAQgKAAgHgIgAAVAXQAAAHACAFQABAFADAAQAIAAgBgRQABgRgIAAQgGAAAAARgAghAvIA4hdIALAAIg4BdgAgsgFQgGgHABgKQgBgLAHgHQAGgHAKAAQAKAAAHAHQAGAHAAALQAAALgHAHQgHAGgJAAQgLAAgGgHgAgigWQAAAHACAFQACAFADAAQAHAAAAgRQAAgRgHAAQgHAAAAARg");
	this.shape_19.setTransform(-343.1,-24.65);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#A72415").s().p("AgSAwQgHgDgDgEQgCgEAAgMQgBgGAHAAQACAAADADIAEAIQAHAKAKAAQAGAAAFgEQAEgEAAgHQABgIgJgGQgLgIgUAAIgEAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIABgCIAIgpQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIASAAIANgBIAGgDQABgCADAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIgBAHIgCAIQAAADgCACQgBABgIAAIgZAAQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAAAIgCAIIAAABQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAQAVAAAMALQALAIAAANQAAAOgKAJQgKAJgPAAQgHAAgIgCg");
	this.shape_20.setTransform(-352.45,-24.875);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#A72415").s().p("AACAvQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAgBIAAhAQAAgHgBgCQgBgCgEAAIgJABQgEAAAAgGQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAABAAIALgCIALgCIAKgCQAEAAAAAEIAABWQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_21.setTransform(-361.15,-24.725);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#A72415").s().p("AgVAaQgKgJAAgPQAAgOAKgLQAKgMAOABQALgBAJAIQAJAHAAAMQAAAFgDACQgCABgGAAIgeAAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAACQABAFADAFQAGAJAMAAQAGAAAFgCIAGgDQAAAAABAAQABAAAAABQAAAAABAAQAAABAAABQAAAEgIAFQgJAHgNgBQgNAAgJgJgAgGgVQgEAEgBAGIAAABQAAAAAAABQAAAAAAAAQABAAAAAAQAAAAAAAAIAPAAQAIAAAAgFQAAgFgDgDQgDgCgFAAQgEgBgEAEg");
	this.shape_22.setTransform(-370.575,-23.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#A72415").s().p("AgGAjQgBAAAAgBQgBAAAAAAQAAAAgBAAQAAgBAAAAIgTgvQgEgIgCgCIgEgDQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAgFAEAAIAdAAQAEABAAADQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAAAQgEACAAAEIABAEIAMAdIABACIAAgCIAJgTQADgHAAgFQAAgEgDgDQgBAAgBgBQgBAAAAgBQgBAAAAgBQAAAAAAAAQAAgFAFAAIAVAAQAGAAgBAFQAAAAAAAAQAAABAAAAQAAAAgBAAQAAABAAAAQgFAEgDAEIgIAOIgRAmQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAg");
	this.shape_23.setTransform(-377.65,-23.35);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#A72415").s().p("AAIAZIAAAAIgBAAQgHAKgOAAQgIABgFgFQgHgEAAgJQAAgKAJgFQAHgEAPgEQAJgFAAgGQAAgIgIAAQgFAAgDACIgHAIQgDAFgDgBQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQgCgBAAgFQAAgGADgEQACgDAJgCQAGgBAIAAQAKgBAIAGQAKAFAAALIgBAZIABAJQAAACAEAAQABABABAAQABAAAAAAQABABAAAAQAAABAAAAQAAADgEADQgDADgIAAQgKAAgCgKgAAEAAQgHAEgFADQgGAEAAAEQAAAEADACQACADAEgBQAGAAADgGQACgDAAgMIAAgBIgBgBg");
	this.shape_24.setTransform(-385.25,-23.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#A72415").s().p("AgUAtQgJgDgDgEQgCgFgBgHIAAgFQAAgGAFAAQACAAADAEIAHAIQAJAKAJAAQAIAAADgEQAFgDAAgGQAAgGgIgFIgPgHQgLgEgGgEQgHgGgBgKQAAgMALgJQAKgIAOAAQASAAAHAHQAEADAAAKQAAAJgFAAQgDAAgCgDIgFgFQgJgLgIAAQgEAAgEADQgDADAAAGQAAAGAIAEIAPAHQAMADAEAFQAIAGAAAMQAAANgLAIQgKAJgQAAQgKAAgJgDg");
	this.shape_25.setTransform(-393.7,-24.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},108).to({state:[]},1).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},14).wait(123));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-399.6,-32,172.00000000000003,17);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.PBB_logo1();
	this.instance.setTransform(-44,-39,0.1803,0.1805);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44,-39,44,35);


(lib.IM4_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM4();
	this.instance.setTransform(-150,-144);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-144,320,50);


(lib.IM3_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM3();
	this.instance.setTransform(-150,-143.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-143.5,320,50);


(lib.IM2_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM2();
	this.instance.setTransform(-150,-143.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-143.5,320,50);


(lib.IM1_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM1();
	this.instance.setTransform(-150,-144);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-144,320,50);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAMAjIgBgBIgLgqIAAAAIgJAqQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgLAAIgBgBIgRhCIAAgBIAAgBIANAAIABABIAKAnIAAABIABgBIAJgnIABgBIALAAIABABIALAnIAAABIAAgBIAJgnIACgBIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIgQBCIgCABg");
	this.shape.setTransform(60.4,14.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNAhQgFgDgEgGQgDgGgBgHIAAgVQABgHADgGQAEgGAFgCQAGgEAHAAQAIAAAGAEQAGACADAGQADAGAAAHIAAAVQAAAHgDAGQgDAGgGADQgGADgIAAQgHAAgGgDgAgIgTQgDADAAAGIAAAVQAAAGADAEQADADAFAAQAFAAAEgDQAEgEAAgGIAAgVQAAgGgEgDQgEgDgFgBQgFABgDADg");
	this.shape_1.setTransform(51.9,14.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAPAjIgCgBIgZgpIAAgBIAAABIAAApIAAAAIgBABIgMAAIgBgBIAAAAIAAhDIAAAAIABgBIALAAIACABIAZAqIAAgBIAAgpIAAAAIABgBIAMAAIABABIAAAAIAABDIAAAAIgBABg");
	this.shape_2.setTransform(44.475,14.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXAjIgBgBIgBAAIAAhDIABAAIABgBIAbAAQAGAAAFADQAFACADAFQADAFAAAGQAAAHgDAEQgDAEgFADQgFADgHAAIgNAAIgBABIAAAZIAAAAIgBABgAgLgWIAAATIABAAIAMAAQAEABADgDQADgDAAgEQAAgFgDgCQgDgDgEAAIgMAAIgBAAg");
	this.shape_3.setTransform(34.325,14.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNAhQgGgDgDgGQgEgGABgHIAAgVQgBgHAEgGQADgGAGgCQAGgEAHAAQAIAAAGAEQAGACADAGQAEAGAAAHIAAAVQAAAHgEAGQgDAGgGADQgGADgIAAQgHAAgGgDgAgIgTQgDADAAAGIAAAVQAAAGADAEQAEADAEAAQAGAAADgDQADgEABgGIAAgVQgBgGgDgDQgDgDgGgBQgEABgEADg");
	this.shape_4.setTransform(27.1,14.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AANAjIgBgBIAAAAIAAgcIgBgBIgVAAIgBABIAAAcIAAAAIgBABIgLAAIgBgBIgBAAIAAhDIABAAIABgBIALAAIABABIAAAAIAAAbIABABIAVAAIABgBIAAgbIAAAAIABgBIALAAIABABIABAAIAABDIgBAAIgBABg");
	this.shape_5.setTransform(19.925,14.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMAhQgHgCgCgFQgEgFAAgGIAAgCIAAgBIABAAIAMAAIABAAIAAABIAAABQAAAEADADQAFADAEgBQAGAAACgBQADgDAAgDQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgBgCgDgBIgHgEIgMgEQgEgBgDgFQgEgEAAgGQAAgGADgEQADgFAGgCQAGgDAGAAQAHAAAGADQAGADAEAFQACAFABAGIAAABIAAABIgBAAIgMAAIgBAAIAAgBIAAgBQAAgEgEgDQgDgCgFgBQgFABgDABQgCACAAAEQAAABAAAAQAAABAAAAQABABAAAAQAAABAAAAIAFADIAJAEIALAEQADACAEADQADAEAAAGQAAAKgHAGQgGAFgNAAQgGAAgGgDg");
	this.shape_6.setTransform(12.75,14.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer_1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#993020").s().p("Ak7BrQgOAAAAgSIAAiyQAAgRAOAAIJ2AAQAPAAAAARIAACyQAAASgPAAg");
	this.shape_7.setTransform(37.7,13.575);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.7,2.9,66,21.400000000000002);


(lib.circle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3828").s().p("AmdGeQirisAAjyQAAjyCrirQCsirDxAAQDzAACqCrQCsCrAADyQAADyisCsQiqCrjzAAQjxAAisirg");
	this.shape.setTransform(0,-0.0156,1,0.7692);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.5,-45,117,90);


// stage content:
(lib.WFSB_213829_MM_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [293];
	// timeline functions:
	this.frame_293 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(293).call(this.frame_293).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(294));

	// CTA
	this.instance = new lib.CTA();
	this.instance.setTransform(253.85,-12.65,0.9025,0.9025,0,0,0,89.6,21.2);
	this.instance.alpha = 0;
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.CTA(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(264).to({_off:false},0).to({regX:89.5,x:250.15,y:32.4,alpha:1},11).wait(19));

	// T3
	this.instance_1 = new lib.T3("synched",168);
	this.instance_1.setTransform(461.55,47);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(179).to({_off:false},0).to({alpha:1,startPosition:191},12,cjs.Ease.get(1)).wait(65).to({startPosition:10},0).to({x:423.3,startPosition:29},19).wait(19));

	// T2
	this.instance_2 = new lib.T2("synched",0);
	this.instance_2.setTransform(462.25,50.65);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(103).to({_off:false},0).to({alpha:1},14,cjs.Ease.get(1)).wait(51).to({startPosition:0},0).to({alpha:0},11,cjs.Ease.get(1)).wait(115));

	// T1
	this.instance_3 = new lib.T1("synched",21);
	this.instance_3.setTransform(460.25,141);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(21).to({_off:false},0).to({y:51,alpha:1,startPosition:46},19,cjs.Ease.get(1)).wait(49).to({startPosition:95},0).to({alpha:0,startPosition:123},14,cjs.Ease.get(1)).wait(191));

	// Logo
	this.instance_4 = new lib.Symbol1("synched",0);
	this.instance_4.setTransform(-42,48.55);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:58,alpha:1},22,cjs.Ease.get(1)).wait(272));

	// Layer_6 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AMXE+QiriDAAi7QAAi6CriDQCsiEDyAAQDzAACrCEQCrCDAAC6QAAC7irCDQirCEjzAAQjyAAisiEg");
	mask.setTransform(179.025,18.0344);

	// IM4_jpg
	this.instance_5 = new lib.IM4_jpg("synched",0);
	this.instance_5.setTransform(163.5,144);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(255).to({_off:false},0).to({alpha:1},21).wait(18));

	// IM3_jpg
	this.instance_6 = new lib.IM3_jpg("synched",0);
	this.instance_6.setTransform(167,143.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(168).to({_off:false},0).to({alpha:1},23).wait(103));

	// IM2_jpg
	this.instance_7 = new lib.IM2_jpg("synched",0);
	this.instance_7.setTransform(169,143.5);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(89).to({_off:false},0).to({alpha:1},28).wait(177));

	// IM1_jpg
	this.instance_8 = new lib.IM1_jpg("synched",0);
	this.instance_8.setTransform(178,144);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(21).to({_off:false},0).to({alpha:1},19).wait(254));

	// Layer_7
	this.instance_9 = new lib.circle("synched",0);
	this.instance_9.setTransform(296.05,16.05);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(21).to({_off:false},0).to({alpha:1},19).wait(254));

	// BG_png
	this.instance_10 = new lib.BG();

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(294));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(74,-4.2,280.6,130.2);
// library properties:
lib.properties = {
	id: '75E153FF2D744F028C65A7813D4CAE23',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.png", id:"BG"},
		{src:"IM1.jpg", id:"IM1"},
		{src:"IM2.jpg", id:"IM2"},
		{src:"IM3.jpg", id:"IM3"},
		{src:"IM4.jpg", id:"IM4"},
		{src:"PBB_logo1.png", id:"PBB_logo1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['75E153FF2D744F028C65A7813D4CAE23'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;