(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib._320x50_1 = function() {
	this.initialize(img._320x50_1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,50);


(lib._320x50jpgcopy = function() {
	this.initialize(img._320x50jpgcopy);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,50);


(lib._320x50jpgcopy2 = function() {
	this.initialize(img._320x50jpgcopy2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,50);


(lib._320x501 = function() {
	this.initialize(img._320x501);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,50);


(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.PBB_logo1 = function() {
	this.initialize(img.PBB_logo1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,244,194);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// T3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#993020").s().p("AgKA7QgHgHAAgEQAAgEAHgHQAHgHADAAQAFAAAGAHQAHAHAAAEQAAAEgHAHQgGAHgFAAQgDAAgHgHgAgHARIgCgLQgBgMgDgSQgDgPAAgJQAAgRAQAAQARAAAAASQAAAIgCAPIgFAeQgBAIgBADQgCAFgGAAQgEAAgDgFg");
	this.shape.setTransform(-276.075,-13.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993020").s().p("AALBDQgHAAAAgEQAAgDAFgDQAFgDACgEQABgFAAgOIAAgXQAAgPgOAAQgGAAgFAEQgIAHAAAbQAAAOABAFQACAEAFADQAFADAAADQAAAEgHAAIgnAAQgHAAAAgEQAAgDAFgDQAFgDABgEQACgFAAgOIAAg9QAAgJgBgDQgCgEgFgCIgDgCQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAgDAGgCQAOgDAKgEIAFgBQAFAAAAAGIAAAvIAAABIABgBQALgPASAAQAQAAAJANQAFAIAAAPIAAAXQAAAMACAHQABAEAGADQAEADAAADQAAAEgHAAg");
	this.shape_1.setTransform(-284.125,-13.475);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#993020").s().p("AgSAtQgEgIAAgPIACgnQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgIQAAAAAAgBQABAAAAgBQAAAAABAAQABgBAAAAQANgCAEgHQADgDACgKQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAARIABAEIAEABIAIAAIAKgBQAHAAAAADIgBAGIgDAFQgCABgEAAIgJAAIgJAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAAAPQAAAZACAIQAEAKAIAAQAEAAAFgDIAFgDQAEAAAAAEQAAADgCADQgKAOgSAAQgRAAgIgOg");
	this.shape_2.setTransform(-293.625,-12.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#993020").s().p("AADBBQgDAAAAgEIAAhZQgBgJgBgDQgBgDgGAAIgNABQgFAAAAgJQAAgEAEgBIAPgCIAQgEIAOgCQAGAAAAAGIAAB3QAAAEgEAAg");
	this.shape_3.setTransform(-304.5,-13.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#993020").s().p("AADBBQgDAAAAgEIAAhZQgBgJgBgDQgBgDgGAAIgNABQgFAAAAgJQAAgEAEgBIAPgCIAQgEIAOgCQAGAAAAAGIAAB3QAAAEgEAAg");
	this.shape_4.setTransform(-313.15,-13.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#993020").s().p("AgsA8QgFgFAAgJQAAgMAJAAQADAAAFAGQAGAFAFAAQAHAAAFgIIABgCIgBgCIgehGQgEgKgDgEIgGgDQgDgCAAgCQAAgFAGAAIAnAAQAGAAAAAEQAAADgEACQgFADAAAEIACAGIARAoIABABIABgBIALgaQAEgKAAgHQAAgGgFgDQgFgDAAgCQAAgFAHAAIAdAAQAHAAAAAEQAAADgCACIgFADIgGAHQgEAGgGANIgVAzQgPAmgbAAQgIAAgGgEg");
	this.shape_5.setTransform(-324.625,-9.725);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#993020").s().p("AALAjIgBgBIgBABQgJAOgTAAQgLAAgIgGQgKgHABgLQgBgOANgIQAKgEAVgHQAMgHAAgIQAAgLgLAAQgGAAgFAEQgEACgGAJQgEAFgEABQgEAAgCgDQgCgDAAgGQAAgKADgDQAEgFANgDQAIgCAKAAQAOAAAMAHQANAJAAAOIgBAiQAAAKABACQABAFAGAAQAFAAAAADQAAAEgFAEQgGAFgKAAQgOAAgDgOgAAGAAQgLAFgGAEQgIAGAAAHQAAAEADAEQAEACAEAAQAJAAAFgIQACgFAAgRIAAgCIgBAAg");
	this.shape_6.setTransform(-335.1,-11.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#993020").s().p("AAeBAQgHAAAAgEQAAgDAEgDQAFgDACgEQACgFAAgOIAAhCIgBgBIgBABIggBNQgCAEgCAAIgIAAQgEAAgBgEIghhOIAAAAIgBABIAABHQABAOAJAFIAGADQADACAAACQAAAFgHAAIghAAQgHAAAAgEQAAgDACgCIAFgEQAFgGAAgWIABhCIgBgGIgEgDIgEgCQgBgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgFAHAAIAkAAQAGAAACAEIAZA7IAAABIABgBIAZg7QACgEAEAAIAnAAQAGAAAAAEQAAAAAAABQAAABAAAAQgBABAAAAQAAAAgBABIgEACQgFADAAAKIAABEQAAAOABAFQACAFAFACQAEADAAADQAAAEgGAAg");
	this.shape_7.setTransform(-348.075,-13.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3927").s().p("AAHAtQgEAAAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABgBQADgCABgDQABgDAAgKIAAgPQAAgKgJAAQgEAAgDAEQgGAEAAARQAAAKACADQABADADACQABABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAADgFAAIgZAAQgFAAAAgDQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABgBQADgCABgDQACgDAAgKIAAgoIgBgIQgBgCgEgCIgCgBIgBgCQAAgCAEgBIAQgFIADgBQABAAABABQAAAAAAAAQABABAAAAQAAABAAABIAAAgIABAAIABAAQAHgKALAAQALAAAGAJQADAFAAAJIAAAPQAAAJACAEQABADADACQABABABAAQAAAAABABQAAAAAAABQAAAAAAABQAAADgFAAg");
	this.shape_8.setTransform(-260.625,-29.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3927").s().p("AgUApQgLgDAAgJQAAgIAIgCIAAgBIAAAAQgCgDAAgDQAAgIAJgEIABAAIgBAAQgMgGAAgNQAAgKAIgGQAIgHALAAQAHAAAGADIAGACQABAAAAAAQAAAAABgBQAAAAABAAQAAgBAAgBQACgDAEAAQAFAAAAAHQAAAHgHAAIgCAAQACAEAAAFQAAAKgIAHQgIAFgKAAIgCAAQgHAAAAAEQAAADAJAAIALAAQAKAAAFAEQAGAEAAAHQAAAIgIAGQgJAGgQAAQgKAAgIgDgAgRAaQAAAFAGACQAFACAGAAQAHAAAFgCQAEgCAAgDQAAgEgIAAIgIAAQgLAAgFgCIgBAEgAgKgWQAAAFACAFQADAGAFAAQACAAACgDQACgDAAgGQAAgFgBgFQgDgGgEAAQgIAAAAAMg");
	this.shape_9.setTransform(-268.075,-27.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3927").s().p("AALAcIAAgGIAAAAIgBAAQgHALgLAAQgLAAgGgJQgDgGAAgKIAAgQIgBgIQgBgCgEgCQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAIARgFIADgBQADAAAAAEIAAAkQAAAFADADQACADAFAAQAEAAADgDQAFgFAAgRIgBgKQAAgCgEgCQgEgBAAgCQAAgCAEgBIARgFIADgBQADAAAAAEIAAAlQAAAGABABQABADADABQAEACAAACQAAACgEABIgQAFIgEABQgDAAAAgFg");
	this.shape_10.setTransform(-275.225,-28.475);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3927").s().p("AgXAYQgJgJAAgPQAAgMAJgKQALgKANAAQAOAAAJAJQAJAJAAAOQAAANgKAKQgJAKgOAAQgOAAgJgJgAgNgEQAAAJADAHQAEALAHAAQAGAAAEgGQACgFAAgJQAAgIgCgIQgEgKgHAAQgNAAAAATg");
	this.shape_11.setTransform(-282.3,-28.475);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3927").s().p("AgUAgQgFAAAAgDQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAABgBQADgCABgDQABgDAAgKIAAgOIAAgIQgBgCgEgCQgEgCAAgBQAAgCAEgCQAIgBAHgDIAEgBQADAAAAAEIAAAJIAAAAIAAAAQACgFAEgEQAFgEAGAAQAFAAACADQADAEAAAEIgBAGQgCACgDAAIgFgCIgFgCQgLAAAAAXQAAAKACADQABADADACQAAABABAAQABABAAAAQAAABABAAQAAABAAAAQAAADgFAAg");
	this.shape_12.setTransform(-288.125,-28.55);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3927").s().p("AAHAtQgEAAAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABgBQADgCABgDQABgDAAgKIAAgPQAAgKgJAAQgEAAgDAEQgGAEAAARQAAAKACADQABADADACQABABABAAQAAAAABABQAAAAAAABQAAAAAAABQAAADgFAAIgZAAQgFAAAAgDQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABgBQADgCABgDQACgDAAgKIAAgoIgBgIQgBgCgEgCIgCgBIgBgCQAAgCAEgBIAQgFIADgBQADAAAAAEIAAAgIABAAIABAAQAHgKALAAQALAAAGAJQADAFAAAJIAAAPQAAAJACAEQABADADACQABABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAADgFAAg");
	this.shape_13.setTransform(-294.675,-29.825);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3927").s().p("AgNArQgFAAAAgDQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAIAFgFQABgDAAgKIAAgvQAAgBAAgBQAAAAgBgBQAAAAgBgBQAAAAgBAAQgFAAgDACQgEADgDAGIgDAFIgCAAQgGAAAAgEIABgKIAAgIIABgDIAFgBIAYABIAPAAIAYgBIAEAAQABABAAAAQAAAAAAABQABAAAAABQAAAAAAABIAAAJIABAKQAAAEgGAAIgCgBIgDgFQgCgGgFgDQgEgCgEAAQgBAAAAAAQgBABAAAAQgBABAAAAQAAABAAABIAAAvQAAAKABADQABADAEACQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAADgFAAg");
	this.shape_14.setTransform(-302.525,-29.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("AgVAbQgEgDAAgJQAAgGAEAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIAEAFQAHAIAGAAQADAAADgCQADgCAAgDQAAgDgFgDIgKgDQgIgDgDgDQgGgEAAgHQAAgKAIgGQAIgGAKAAQAJAAAGADQAFADAAAIIgBAFQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgDAAgCgDQgGgJgHAAQgEAAgCACQgCACAAADQAAADAFACIALAEQARAGAAAMQAAAKgIAGQgJAGgKAAQgOAAgGgGg");
	this.shape_15.setTransform(-312.55,-28.475);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AAIAgQgFAAAAgDQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABgBQADgCABgDQACgDAAgKIAAgOQAAgKgKgBQgEABgDADQgFAFAAAQQAAAKABADQABADADACQABABABAAQAAABAAAAQABABAAAAQAAABAAAAQAAADgEAAIgaAAQgFAAAAgDQAAAAAAgBQABAAAAgBQAAAAABgBQABAAAAgBQAEgCABgDQABgDAAgKIAAgOIgBgIQgBgCgDgCQgEgCAAgBQAAgDAEgBIAQgEIADgBQAEAAAAAEIAAAGIAAABIABgBQAHgKALAAQALAAAGAJQAEAFAAAKIAAAOIABANQABADADACQABABABAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgEAAg");
	this.shape_16.setTransform(-318.675,-28.55);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("AALAcIAAgGIAAAAIgBAAQgHALgLAAQgLAAgGgJQgDgGAAgKIAAgQIgBgIQgBgCgEgCQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABAAIARgFIADgBQADAAAAAEIAAAkQAAAFADADQACADAFAAQAEAAADgDQAFgFAAgRIgBgKQAAgCgEgCQgEgBAAgCQAAgCAEgBIARgFIADgBQADAAAAAEIAAAlQAAAGABABQABADADABQAEACAAACQAAACgEABIgQAFIgEABQgDAAAAgFg");
	this.shape_17.setTransform(-326.175,-28.475);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AAbArQgIAAgDgEIgIgSQgHgQgLAAIgCAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAALQAAAKABADQABADAEACQABABAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAADgEAAIgcAAQgEAAAAgDQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAgBQAEgCABgDQABgDAAgKIAAgsQAAgHgDgCIgDgBQAAgBgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAABAAQAAgBABAAIAZAAIAKAAQARAAAHAGQAIAFAAAKQAAAFgCAEQgEAJgNACIgCABIACAAQAGAAAFAGQAEAEAEAKQAGANADADIACABQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAgAgNgeIAAAYQAAAAAAABQAAAAAAAAQABAAAAAAQAAAAAAAAIAGAAQAGAAAEgDQAEgEAAgGQAAgOgNAAIgGAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAAAABg");
	this.shape_18.setTransform(-334.25,-29.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("AgVAbQgEgDAAgJQAAgGAEAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIAEAFQAGAIAHAAQAEAAACgCQADgCAAgDQAAgDgFgDIgLgDQgHgDgDgDQgGgEAAgHQAAgKAIgGQAIgGAKAAQAJAAAGADQAFADAAAIIgBAFQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgDAAgCgDQgGgJgHAAQgDAAgDACQgCACAAADQAAADAGACIAKAEQARAGAAAMQAAAKgIAGQgJAGgKAAQgOAAgGgGg");
	this.shape_19.setTransform(-345.3,-28.475);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AgUAYQgJgIAAgOQAAgNAJgKQAKgLANAAQAKAAAIAHQAJAHAAALQAAAFgDABQgCABgFAAIgdAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAABIAAABQABAFADAEQAFAJALAAQAFAAAGgCIAEgDQABAAABAAQAAABABAAQAAAAAAABQABAAAAABQAAAEgIAFQgJAGgKAAQgNAAgJgJgAgFgTQgEADgBAGIAAABQAAAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIANAAQAIAAAAgFQAAgEgDgDQgDgDgEAAQgEAAgDAEg");
	this.shape_20.setTransform(-351.55,-28.475);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AgMAtQgFAAAAgDQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABgBQAEgCABgDQABgDAAgKIAAgoIgBgIQgBgCgDgCQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAABAAIAQgFIADgBQADAAAAAEIAAA8QAAAKABADQABADAEACQABABAAAAQABABAAAAQAAABABAAQAAAAAAABQAAADgFAAg");
	this.shape_21.setTransform(-356.175,-29.825);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AAHAYIAAgBIgBAAQgGAKgNAAQgHAAgGgEQgFgFAAgHQAAgKAIgFQAGgDAOgEQAIgEAAgGQAAgHgHAAQgEAAgDACQgDACgEAFQgDAEgCAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBIgBgFQAAgHADgCQACgEAIgCIANgBQAJAAAIAFQAIAFAAALIAAAWIAAAIQABADAEAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAQAAADgDACQgEAEgGAAQgKAAgCgJgAAEAAIgMAGQgEAEAAAEQAAADACACQACACADAAQAFAAADgGQACgDAAgLIAAgBIAAAAg");
	this.shape_22.setTransform(-361.475,-28.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AgTAqQgIgDgDgFQgCgDAAgHIAAgFQAAgFAEAAQADAAACADIAGAIQAJAJAIAAQAHAAADgDQAEgEAAgFQAAgGgGgEIgPgGQgKgEgFgDQgHgGAAgKQAAgLAJgIQAKgHANAAQAQAAAHAGQADADAAAJQAAAIgFAAQgCAAgCgCIgFgGQgHgJgIAAQgEAAgDADQgEACAAAFQAAAGAHAEIAPAGQAKAEAFAEQAHAGAAAKQAAAMgKAIQgKAIgPAAQgJAAgIgCg");
	this.shape_23.setTransform(-369.275,-29.625);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},47).to({state:[]},1).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},120).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},11).to({state:[]},1).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},11).wait(55));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-378,-36.6,125.1,36);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// T2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#993020").s().p("AhABJQgUgcAAgrQAAgsAZgeQAageAjAAQAnAAAWAcQAWAbAAAtQAAAxgaAeQgZAagiAAQgqAAgWgegAgigGQAAAlAJAXQAKAZARAAQAhAAAAhIQAAgqgKgWQgKgWgPAAQgiAAAABJg");
	this.shape.setTransform(-236.325,-25.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993020").s().p("AACBlIg2AAQgRAAAAgUQAAgaAbgbIAbgZQAQgNAHgJQAMgPgBgQQAAgLgFgIQgIgKgLAAQgRAAgNAVIgIAOQgEAGgFAAQgLAAAAgVQAAgUAMgJQATgNAdAAQAbAAAUAOQAXAQAAAbQAAAagYAUQgMAKgYALQgYANgIAGQgLAIABAIQAAAEAFAAIArAAQAZAAAHgDQAFgCAFgFQAEgFAEAAQAHAAAAAIIgEASQgBAPgCAGQgEAIgOAAg");
	this.shape_1.setTransform(-253.75,-25.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#993020").s().p("Ag3BLQgSgZAAgoQAAgpASggQAXgnArAAQAfAAAMANQAIAHgBAQQABAXgNAAQgFAAgEgFIgIgNQgMgTgPAAQgPAAgJATQgJASAAAgIAAABIACgBQAOgYAcAAQAZAAASASQAPARAAAbQABAfgUAWQgUAXgiAAQgkAAgUgcgAgSADQgJAMAAAWQAAAVAIALQAIAMAMAAQAPAAAHgNQAHgMAAgTQAAgUgHgMQgIgLgNAAQgMAAgIAJg");
	this.shape_2.setTransform(-268.5,-25.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#993020").s().p("AgfAqQAAgDAFgDQAHgEADgEQAMgLAAgJQABgHgIgHQgLgMAAgFQAAgGAKgKQAKgKAGAAQADAAAHAEQAGAFADAFQAJAKAAALQAAAPgaAcQgUAVgKAAQgHAAAAgIg");
	this.shape_3.setTransform(-280.95,-15.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#993020").s().p("AgFBmQgLAAAAgHQAAgFAHgEQAHgEACgIQADgHAAgNQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAIhJAAQgFAAgBgGIAAgRQAAgGAEgGQAWggAJgaQAKgaAAgbQAAgGAHAAIAZAAQAEAAAAAFIAAABQgBAagMAcQgMAYgYAgIgBACQAAAAAAAAQAAABAAAAQABAAAAAAQABAAAAAAIAuAAQABAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIAAhHQAAgEAFAAIAgAAQAGAAgBAEIAABHQAAABABAAQAAAAAAABQABAAAAAAQABAAABAAIAXAAQAGAAABAHIAAATQAAAHgIAAIgXAAQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAOADAGQACAIAIAEQAHAEAAAFQAAAHgLAAg");
	this.shape_4.setTransform(-291.9,-25.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#993020").s().p("AAFBmQgHAAAAgHIAAiLQABgPgCgEQgCgEgKAAIgUABQgIAAAAgNQABgHAFgBIAZgEQAOgCALgDIAVgFQAJAAAAAKIAAC6QAAAHgHAAg");
	this.shape_5.setTransform(-311.6,-25.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#993020").s().p("AgCBzQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAgVQgUAAgPgEQgPgGgGgJQgDgEgBgHIgBgLIgBgJQAAgLAKAAQAEAAAFAGIANAQQARATAUAAIAJgBQAIgCAGgGQAEgHABgIQgBgMgOgIQgFgEgYgKQgWgIgKgGQgOgNABgTQAAgVAQgPQAPgOAXgDIAAgXQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAKAAQAFAAAAAEIAAAWQAbACANAMQAHAFgBASQABARgLAAQgEAAgFgFIgNgPQgOgPgNAAQgIAAgHAGQgHAFAAAKQAAAMAOAIQAEACAaAKQAWAIAJAIQAPANgBAVQAAAWgQAPQgPAPgXADIAAAWQAAAEgFAAg");
	this.shape_6.setTransform(-324.45,-26.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3829").s().p("AgNAjQgEgGAAgMIABgeQAAgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgJAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAgGQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQAJgCAEgFQACgDABgHQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIAIAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAOIABADIACABIAHgBIAIAAQAFAAAAACIgBAFIgBAEIgGABIgGAAIgHgBQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAALQAAAUACAGQADAIAGAAQADAAAEgCIAEgCQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAABIgBAEQgHALgOAAQgNAAgGgLg");
	this.shape_7.setTransform(-337.35,-19.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3829").s().p("AAIAbIAAgBIgBABQgHALgPAAQgJAAgGgFQgHgEAAgKQAAgKAKgGQAHgEARgFQAJgFAAgHQAAgJgIAAQgFAAgEAEQgDACgEAGQgEAEgDAAQgDAAgCgBQgBgDAAgFQAAgGADgEQADgEAJgCQAHgBAHAAQAMAAAIAGQALAFAAANIgBAaQAAAHABACQABADAEAAQABAAABABQAAAAABAAQAAABABAAQAAABAAAAQAAADgEADQgFAEgHAAQgLAAgDgLgAAFAAQgJAEgFADQgFAEAAAFQAAAEACADQADACADAAQAHAAADgHQACgEAAgNIAAgBIAAAAg");
	this.shape_8.setTransform(-344.175,-18.65);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3829").s().p("AgXAwQgOgEAAgKQAAgJAKgDIABgBIgBgBQgCgDAAgDQAAgKALgEIAAAAIAAAAQgPgHAAgPQAAgMAJgIQAJgHAOAAQAIAAAHADIAHADQACAAACgDQACgEAEAAQAHAAAAAHQAAAJgJgBIgCAAQACAGAAAFQAAAMgJAIQgJAHgMgBIgCAAQgJABAAAEQAAAEALAAIANgBQAMAAAGAFQAGAFAAAHQAAAKgJAHQgKAHgTAAQgNAAgIgDgAgUAdQAAAHAHADQAGACAHAAQAIAAAGgDQAFgCAAgDQAAgFgKAAIgJAAQgNAAgGgDIgBAEgAgMgbQAAAIADAFQADAHAGAAQADAAACgEQADgEAAgGQAAgHgDgFQgCgHgFABQgKAAAAAMg");
	this.shape_9.setTransform(-355.875,-17.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3829").s().p("AAJAlQgGAAAAgDQAAgCADgDQAEgCACgDQACgEgBgLIAAgRQAAgNgLAAQgFAAgDAEQgHAGAAAUQABALABAEQABADAEACQAEADgBACQABADgGAAIgeAAQgFAAAAgDQAAgCADgDQAEgCACgDIABgPIAAgRIgBgJQgBgEgEgBQgFgCABgCQgBgDAFgBIASgGIAFAAQAEAAgBAEIAAAHIABABIABgBQAIgLAOAAQAMAAAHAKQAFAGAAAMIAAARIABAPQABADAEACQAEACAAADQAAADgGAAg");
	this.shape_10.setTransform(-364.3,-18.725);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3829").s().p("AgOA1QgFAAAAgEQAAgCADgBQAEgDABgEQACgEAAgKIAAgSIgBgJQgCgDgEgCQgEgBAAgCQAAgDAFgBIASgGIAEAAQADgBAAAFIAAApQAAAKACAEQABAEAEADQAEABAAACQAAAEgGAAgAgHgfQgFgFAAgDQAAgDAFgFQAFgFACAAQADAAAFAFQAFAFAAADQAAADgFAFQgFAGgDgBQgCABgFgGg");
	this.shape_11.setTransform(-371.175,-20.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3829").s().p("AgNAjQgEgGAAgMIABgeQAAgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgJAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAgGQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQAJgCAEgFQACgDABgHQABgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIAIAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAOIABADIADABIAGgBIAIAAQAFAAAAACIgBAFIgBAEIgGABIgGAAIgHgBQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAALQAAAUACAGQADAIAGAAQADAAAEgCIAEgCQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAABIgBAEQgHALgOAAQgNAAgGgLg");
	this.shape_12.setTransform(-376.5,-19.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3829").s().p("AgYAlQgGAAAAgDQAAgCAEgCQADgDACgDQABgEAAgLIAAgSIgBgJQgBgDgEgBQgEgCAAgCQAAgDAEgBIARgFIAFgBQAEAAAAAEIAAALIAAAAIAAAAQACgGAFgEQAGgFAGAAQAGAAADAEQADADAAAGQAAAEgCACQgCADgDAAIgFgCQgEgCgCAAQgNAAAAAbQAAALABAEQABADAEADQAEABAAADQAAADgFAAg");
	this.shape_13.setTransform(-382.825,-18.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3829").s().p("AAIAbIAAgBIgBABQgHALgPAAQgJAAgGgFQgHgEAAgKQAAgKAKgGQAHgEARgFQAJgFAAgHQAAgJgIAAQgFAAgEAEQgDACgEAGQgEAEgDAAQgDAAgCgBQgBgDAAgFQAAgGADgEQADgEAJgCQAHgBAHAAQAMAAAIAGQALAFAAANIgBAaQAAAHABACQABADAEAAQABAAABABQAAAAABAAQAAABABAAQAAABAAAAQAAADgEADQgFAEgHAAQgLAAgDgLgAAFAAQgJAEgFADQgFAEAAAFQAAAEACADQADACADAAQAHAAADgHQACgEAAgNIAAgBIAAAAg");
	this.shape_14.setTransform(-390.075,-18.65);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3829").s().p("AgNAjQgEgGAAgMIACgeQAAgBgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgIAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAgGQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQAJgCAEgFQACgDABgHQABgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAOIAAADIADABIAHgBIAIAAQAFAAAAACIgBAFIgCAEIgEABIgHAAIgIgBQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAALQAAAUABAGQADAIAHAAQADAAAEgCIAEgCQABAAAAAAQABAAAAAAQAAABAAAAQABABAAABIgCAEQgHALgPAAQgNAAgFgLg");
	this.shape_15.setTransform(-397.35,-19.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3829").s().p("AgWAxQgKgEgDgEQgDgFAAgIIAAgFQAAgHAFAAQADAAADADIAHAKQALALAJAAQAIAAAEgEQAFgEAAgGQAAgHgIgFIgRgIQgMgEgGgEQgIgHAAgLQAAgNALgIQALgJAQAAQASgBAJAIQADAEAAAKQAAAJgFAAQgDAAgDgCIgFgHQgJgKgJAAQgEAAgEACQgEADAAAGQAAAHAIAEIARAHQAMAFAGAFQAIAHAAAMQAAAOgMAKQgMAJgRgBQgLAAgJgCg");
	this.shape_16.setTransform(-404.775,-20);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},59).to({state:[]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},29).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},13).to({state:[]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},14).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},61).to({state:[]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},12).wait(55));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-411,-38.5,185.8,32);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// T1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3829").s().p("AgFAhQgEgEAAgCQAAgDAEgDQAEgEABAAQACAAAEAEQAEADAAADQAAACgEAEQgEAEgCAAQgBAAgEgEgAgDAKIgBgHIgDgQIgCgNQAAgKAJAAQAKAAAAAKIgCANIgDAQIgBAHQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAQgCAAgBgCg");
	this.shape.setTransform(-229.05,-22.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B3829").s().p("AgRAXQgEgDAAgIQAAgFAEAAIADACIADAEQAFAGAGAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAQADgCAAgCQAAgDgFgCIgIgDQgHgCgDgDQgEgDAAgGQAAgJAHgEQAGgFAIAAQAIAAAFACQAEADAAAGQAAABAAABQAAABAAAAQAAABAAAAQgBAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAgBgBAAQgEgIgHAAQgCAAgCACQAAAAgBABQAAAAAAABQAAAAgBABQAAAAAAABQAAADAFACIAIADQAPAFAAAKQAAAIgIAFQgGAEgJAAQgLAAgFgEg");
	this.shape_1.setTransform(-233.275,-21.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B3829").s().p("AgQAUQgHgHAAgLQAAgLAHgIQAIgJAKAAQAJAAAGAFQAIAGgBAJQAAAEgBACQgCAAgFAAIgXAAIgBABIAAABQABAEACAEQAFAHAIAAQAFAAAEgCIAFgCQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAQABAEgHAEQgGAEgKAAQgKAAgHgHgAgEgQQgDADgBAFIAAABIABABIALAAQAGAAAAgFQAAgDgDgCQgCgDgDAAQgEAAgCADg");
	this.shape_2.setTransform(-238.5,-21.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B3829").s().p("AgJAmQgBAAgBAAQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQADgCABgDQABgCAAgJIAAgMIgBgGQgBgCgDgBQAAAAgBgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAAAAAgBQABAAAAgBQABAAAAAAQABAAABgBIANgDIACgBQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAcQAAAJABACQABADACACQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAABAAABQgBAAAAAAQgBABAAAAQgBAAgBAAgAgFgVQgDgEAAgDQAAgBADgFQAEgDABAAQADAAADADQAEAFAAABQAAADgEAEQgDADgDAAQgBAAgEgDg");
	this.shape_3.setTransform(-242.675,-22.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B3829").s().p("AgRAbQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABgBQACgBABgDQABgDAAgIIAAgMIAAgGQgBgCgDgCQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAIAMgEIAEgBQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAHIAAABIAAgBQACgEADgDQAEgEAFAAQAEAAACADQACADAAAEIgBAEQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgEgBIgFgCQgJAAAAATQAAAIABADQABADADABQAAABABAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_4.setTransform(-246.825,-21.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B3829").s().p("AgQAUQgIgHAAgLQAAgLAIgIQAIgJAKAAQAJAAAHAFQAGAGABAJQAAAEgDACQgBAAgFAAIgXAAIgBABIAAABQAAAEACAEQAGAHAJAAQAEAAAEgCIAEgCQABAAAAAAQABABAAAAQAAAAAAAAQABABAAAAQgBAEgFAEQgIAEgJAAQgKAAgHgHgAgFgQQgCADgBAFIAAABIABABIAKAAQAHAAAAgFQAAgDgCgCQgDgDgEAAQgCAAgEADg");
	this.shape_5.setTransform(-252.05,-21.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B3829").s().p("AgPAjQgHgDgDgDQgCgDAAgGIAAgEQAAgEAEAAQAAAAABAAQAAAAABAAQAAABABAAQAAABABAAIAFAHQAIAHAGAAQAGAAADgCQADgDAAgEQAAgGgGgDIgMgFQgIgDgEgDQgGgFAAgIQAAgJAIgGQAHgHALAAQAOAAAGAGQACACAAAHQAAAHgEAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgEgEQgHgIgGAAQgDAAgDACQgDACAAAEQAAAFAGAEIAMAFQAJADAEADQAGAFAAAJQAAAKgJAGQgIAHgMAAQgIAAgGgCg");
	this.shape_6.setTransform(-258.225,-22.025);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3829").s().p("AADAaQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIABgCQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgCgEgGIgCgEIgBAAIgBAAQgFAIAAADQAAAAAAABQABAAAAABQAAAAABABQAAAAABABIACACQAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgSAAQgBAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAgBQAAgBAEgCQAEgEAHgJIAFgHIABAAIgBgBIgGgJIgFgGIgFgDIgDgCIgBgBQAAgBAAgBQABAAAAAAQABgBAAAAQABAAABAAIAYAAQABAAABAAQAAAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAQAAABgBAAQAAAAAAABQAAAAAAABQAAACAEAHIACADIABAAIAAAAQAFgJAAgCQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAIgDgCQAAgBAAgBQABAAAAAAQABgBAAAAQABAAABAAIASAAQABAAAAAAQABAAABABQAAAAABAAQAAABAAABIgEADQgEAEgHAJIgGAGIAAABIAAABIAHAJIAFAGIAFADIACACQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAABQgBAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_7.setTransform(-265.825,-21.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3829").s().p("AgTAUQgHgHAAgNQAAgKAIgIQAIgIALAAQAMAAAHAIQAHAHAAALQAAALgHAIQgIAIgMAAQgLAAgIgHgAgKgDQAAAHACAHQADAJAGAAQAFAAADgFQACgFAAgHQAAgHgCgGQgDgJgGAAQgKAAAAAQg");
	this.shape_8.setTransform(-271.525,-21.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3829").s().p("AgKAiIgDgBQAAAAgBAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAQgDAAAAgEIAAgzIAAgHQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAgBgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAOgEIADgBQAAAAABAAQAAABABAAQAAAAAAABQAAABAAAAIAAAaIABABIABgBQAFgIAKAAQAJAAAGAIQAFAHAAAJQAAAMgHAJQgIAJgMAAQgHAAgGgEgAgEAAQgDAFAAAHQAAAJADAFQAEAEAEAAQAFAAADgFQADgFAAgIQAAgIgDgEQgEgFgFAAQgFAAgCAFg");
	this.shape_9.setTransform(-277.775,-22.125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3829").s().p("AgKAZQgCgFAAgIIABgVQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAgBAAAAIgGAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAgEQAAAAABgBQAAAAAAAAQAAAAAAgBQABAAAAAAQAHgBADgEIACgHIABgBIAGAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAAJIAAACIACABIAFAAIAFgBQABAAABABQABAAAAAAQABAAAAABQAAAAAAABIAAADIgCACIgDABIgFAAIgGgBQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAIQgBAOACAEQABAFAGAAQAAAAABAAQAAAAABAAQAAAAABAAQABgBAAAAIAEgBQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQgBABAAAAQgFAHgKAAQgJAAgFgHg");
	this.shape_10.setTransform(-282.95,-21.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3829").s().p("AgKAlQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQADgCABgDQABgCAAgIIAAghIgBgHQAAgBgBAAQAAgBAAAAQgBAAAAgBQgBAAgBAAQAAgBgBAAQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQABgBAAAAIANgEIADAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAyQAAAIABACQABADACACQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_11.setTransform(-286.325,-22.175);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3829").s().p("AAGAUIAAgBIgBABQgFAHgKAAQgHAAgEgDQgFgEAAgGQAAgIAHgEQAFgCAMgEQAGgDAAgFQAAgGgFAAQgEAAgDACQgCABgDAFQgCADgCAAIgEgBIgBgFQAAgGACgCQACgDAHgBIAKgBQAIAAAGAEQAHAEAAAJIAAASIAAAHQABAAAAABQAAAAABABQAAAAABAAQABAAABAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAABQgEACgFAAQgIAAgCgHgAADAAQgFADgEADQgEACAAAEQAAABAAAAQAAABAAABQABAAAAAAQAAABABAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQAEAAADgFIABgMIAAgBIAAAAg");
	this.shape_12.setTransform(-290.75,-21.075);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3829").s().p("AgPAjQgHgDgDgDQgCgDAAgGIAAgEQAAgEAEAAQAAAAABAAQAAAAABAAQAAABABAAQAAABABAAIAFAHQAIAHAGAAQAGAAADgCQADgDAAgEQAAgGgGgDIgMgFQgIgDgEgDQgGgFAAgIQAAgJAIgGQAHgHALAAQAOAAAGAGQACACAAAHQAAAHgEAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgEgEQgHgIgGAAQgDAAgDACQgDACAAAEQAAAFAGAEIAMAFQAJADAEADQAGAFAAAJQAAAKgJAGQgIAHgMAAQgIAAgGgCg");
	this.shape_13.setTransform(-297.225,-22.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3829").s().p("AgRAbQgBAAAAAAQgBgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABgBQACgBABgDQABgDAAgIIAAgMIAAgGQgBgCgDgCQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAIAMgEIAEgBQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAAHIAAABIAAgBQACgEADgDQAEgEAFAAQAEAAACADQACADAAAEIgBAEQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgEgBIgFgCQgJAAAAATQAAAIABADQABADADABQAAABABAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_14.setTransform(-303.775,-21.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3829").s().p("AAJAYIAAgFIAAgBIgBABQgFAIgKAAQgJAAgEgHQgDgEgBgJIAAgNIgBgHQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIAOgEIADgBQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAeQABAEABACQADADADAAQADAAADgDQAFgEgBgOIgBgIQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAQABAAABAAIANgEIADgBQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABIAAAeIAAAHQAAAAABABQAAAAAAABQABAAAAABQABAAAAAAQABABABAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAQgBAAgBABIgNAEIgDAAQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBg");
	this.shape_15.setTransform(-309.45,-21.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3829").s().p("AgTAUQgHgHAAgNQAAgKAIgIQAIgIALAAQAMAAAHAIQAHAHAAALQAAALgHAIQgIAIgMAAQgLAAgIgHgAgKgDQAAAHACAHQADAJAGAAQAFAAADgFQACgFAAgHQAAgHgCgGQgDgJgGAAQgKAAAAAQg");
	this.shape_16.setTransform(-315.375,-21.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3829").s().p("AAGAbQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAgBQADgBABgDQABgDAAgIIAAgLQAAgJgIAAQgDAAgDACQgEAFAAANQAAAIABADQAAADADABQABABAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgWAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAgBQADgBABgDQABgDAAgIIAAgLIgBgHQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAQABgBABAAIANgEIADgBQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIAAAFIAAAAIABAAQAFgJAKAAQAJAAAFAIQADAEAAAJIAAALIABALIADAEQABABAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_17.setTransform(-323.225,-21.125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3829").s().p("AgTAUQgHgHAAgNQAAgKAIgIQAIgIALAAQAMAAAHAIQAHAHAAALQAAALgHAIQgIAIgMAAQgLAAgIgHgAgKgDQAAAHACAHQADAJAGAAQAFAAADgFQACgFAAgHQAAgHgCgGQgDgJgGAAQgKAAAAAQg");
	this.shape_18.setTransform(-329.225,-21.075);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#A72415").s().p("AAMAvQgGgIAAgMQAAgNAIgIQAHgHALAAQAMAAAHAHQAIAIAAANQgBANgHAIQgIAHgLAAQgMAAgIgIgAAYAbQAAAIACAFQADAGADAAQAIAAAAgTQAAgUgIAAQgIAAAAAUgAgmA2IBAhqIANAAIhBBqgAgzgFQgGgIAAgNQAAgMAHgIQAIgIALAAQAMAAAHAIQAIAIgBAMQAAAOgHAIQgIAGgLAAQgMAAgIgHgAgngaQAAAJACAFQADAGADAAQAIAAAAgUQAAgTgIAAQgIAAAAATg");
	this.shape_19.setTransform(-342.4,-23.825);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#A72415").s().p("AgUA4QgIgEgEgFQgDgEAAgOQAAgHAHgBQADABADAEIAEAJQAIAMALAAQAIAAAFgFQAGgFAAgHQAAgLgKgGQgMgKgYAAIgEAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgBIAKgxQAAAAABAAQAAgBAAAAQABAAAAAAQABgBAAAAIAVAAQAMAAAEAAQADgCACgCQADgDADAAQADAAAAAEIgBAIIgBAJQgBAEgCABQgCACgJAAIgdAAQAAAAAAABQgBAAAAAAQAAAAAAAAQgBABAAAAIgBAJIgBABQAAAAAAAAQAAAAABABQAAAAAAAAQABAAAAAAQAZAAAOAMQAMAJAAAQQAAARgLAKQgMAKgRAAQgJAAgHgCg");
	this.shape_20.setTransform(-353.175,-24.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#A72415").s().p("AADA2QgDAAAAgDIAAhKQAAgIgBgCQgBgDgFABIgLAAQgEAAAAgHQAAgEADAAIANgDIANgCIALgCQAFAAAAAEIAABkQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_21.setTransform(-363.225,-23.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#A72415").s().p("AgZAeQgLgKAAgSQAAgQALgNQAMgNAQAAQAOAAAJAJQALAIAAAOQAAAGgDACQgDABgHAAIgjAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAACQAAAGAEAFQAHAMANAAQAHAAAGgDIAHgEQABAAABAAQAAABABAAQAAABAAAAQAAABAAABQAAAFgJAGQgKAHgOAAQgQAAgLgLgAgHgYQgEAEgBAHIgBABQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIAQAAQAKAAAAgHQAAgEgEgEQgDgDgFAAQgGAAgEAEg");
	this.shape_22.setTransform(-374.075,-22.375);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#A72415").s().p("AgIAoQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIgXg2QgDgJgDgDIgFgDQAAAAgBgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgFAGAAIAhAAQAFAAAAAEQAAADgEACQgDACAAADIABAFIANAjIABABIABgBIAKgXQADgIAAgGQAAgFgEgDQgEgDAAgBQAAgFAHAAIAYAAQAGAAAAAFQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgGAEgDAFIgJAQIgUAsQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_23.setTransform(-382.075,-22.325);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#A72415").s().p("AAJAeIgBgBIAAABQgIALgQAAQgJAAgHgFQgHgGAAgJQAAgMAKgGQAIgEARgGQAKgFAAgHQAAgJgIAAQgGAAgEADQgDACgFAHQgDAFgEAAQgEAAgBgCIgBgIQAAgHACgEQAEgEAKgCQAHgCAIAAQAMAAAKAGQAKAHAAANIAAAbQAAAJABACQABADAEAAQAEABAAADQAAADgDADQgGAEgHAAQgMAAgDgLgAAFAAQgJAEgGAEQgGAEAAAGQAAAEADADQADACAEAAQAHAAADgIQACgEAAgNIAAgCIAAAAg");
	this.shape_24.setTransform(-390.825,-22.375);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#A72415").s().p("AgXA0QgLgDgDgGQgDgEAAgJIAAgGQAAgHAFAAQADAAADAEIAIAKQALAMALAAQAIAAAFgEQAEgFAAgGQABgIgJgFIgTgIQgMgFgHgEQgIgHAAgMQAAgOAMgJQALgKARAAQAUAAAJAIQADAEAAALQABAKgGAAQgDAAgDgDIgFgHQgKgLgKAAQgFAAgEADQgEADAAAGQAAAIAJAFIASAHQANAFAGAFQAIAHAAANQAAAQgMAKQgNAJgSAAQgMAAgJgDg");
	this.shape_25.setTransform(-400.6,-23.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},108).to({state:[]},1).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},14).wait(123));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-407.1,-32,181.10000000000002,19);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.PBB_logo1();
	this.instance.setTransform(-44,-39,0.1803,0.1805);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44,-39,44,35);


(lib.IM4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// IM4_png
	this.instance = new lib._320x501();
	this.instance.setTransform(-299,-46,1.05,1.05);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).wait(38).to({_off:true},1).wait(198));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-299,-46,100.80000000000001,52.5);


(lib.IM3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// IM3_png
	this.instance = new lib._320x50jpgcopy2();
	this.instance.setTransform(-298,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(29).to({_off:true},1).wait(138).to({_off:false},0).wait(78));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-298,-45,96,50);


(lib.IM2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// IM2_png
	this.instance = new lib._320x50_1();
	this.instance.setTransform(-302,-46,1.05,1.05);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(89).to({_off:false},0).wait(101).to({_off:true},1).wait(55));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-302,-46,100.80000000000001,52.5);


(lib.IM1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// IM1_png
	this.instance = new lib._320x50jpgcopy();
	this.instance.setTransform(-304,-46,1.05,1.05);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(21).to({_off:false},0).wait(18).to({_off:true},1).wait(6).to({_off:false},0).wait(76).to({_off:true},1).wait(123));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-304,-46,100.80000000000001,52.5);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAMAjQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIgKgpIAAAAIAAAAIgJApQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIgRhBQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAKAmIAAABIABgBIAJgmQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIALAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAJAmIABABIAAgBIAJgmQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIgQBBQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape.setTransform(60.175,14.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgSAdQgIgHABgLIAAgVQgBgLAIgHQAHgHALAAQAMAAAHAHQAIAHgBALIAAAVQABALgIAHQgHAHgMAAQgLAAgHgHgAgIgTQgDADAAAGIAAAVQAAAGADAEQAEADAEAAQAFAAAEgDQADgEABgGIAAgVQgBgGgDgDQgEgDgFgBQgEABgEADg");
	this.shape_1.setTransform(51.75,14.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAPAjIgCgBIgYgpQgBgCAAACIAAAoQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgLAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhBQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAKAAIACABIAYAoQABABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIAAgnQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAKAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAABBQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAg");
	this.shape_2.setTransform(44.375,14.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXAjQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhBQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAbAAQAKAAAGAGQAGAGAAAJQAAAKgGAFQgHAGgKAAIgNAAIgBABIAAAYQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAgAgLgWIAAATIABAAIAMAAQAEABADgDQADgDAAgEQAAgFgDgCQgDgDgEAAIgMAAIgBAAg");
	this.shape_3.setTransform(34.275,14.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSAdQgHgHgBgLIAAgVQABgLAHgHQAHgHALAAQAMAAAHAHQAHAHABALIAAAVQgBALgHAHQgHAHgMAAQgLAAgHgHgAgIgTQgDADAAAGIAAAVQAAAGADAEQADADAFAAQAFAAAEgDQADgEAAgGIAAgVQAAgGgDgDQgEgDgFgBQgFABgDADg");
	this.shape_4.setTransform(27.05,14.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AANAjQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgbIgBgBIgVAAIgBABIAAAbQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgLAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhBQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAaIABABIAVAAIABgBIAAgaQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIALAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAABBQAAABAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_5.setTransform(19.875,14.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSAeQgHgGAAgJIAAgCQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIAKAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAABQAAAEADADQAEADAFgBQALAAAAgHQAAgDgEgDIgKgFQgLgDgEgDQgHgFAAgJQAAgJAGgGQAHgFALAAQALAAAHAGQAHAGAAAKIAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgLAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAgBIAAgBQAAgDgDgEQgEgDgFAAQgKABAAAHQAAAEAEABQADADAIADQAKAEAEACQAIAFAAAIQAAAKgHAFQgHAGgMAAQgLAAgHgGg");
	this.shape_6.setTransform(12.775,14.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer_1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#993020").s().p("Ak7BrQgOAAAAgSIAAiyQAAgRAOAAIJ2AAQAPAAAAARIAACyQAAASgPAAg");
	this.shape_7.setTransform(37.7,13.575);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.7,2.9,66,21.400000000000002);


// stage content:
(lib._320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [293];
	// timeline functions:
	this.frame_293 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(293).call(this.frame_293).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(294));

	// CTA
	this.instance = new lib.CTA();
	this.instance.setTransform(260.1,-14.4,1,1,0,0,0,89.5,21.2);
	this.instance.alpha = 0;
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.CTA(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(264).to({_off:false},0).to({x:256.1,y:35.6,alpha:1},11).wait(19));

	// T3
	this.instance_1 = new lib.T3("synched",168);
	this.instance_1.setTransform(461.55,47);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(179).to({_off:false},0).to({alpha:1,startPosition:191},12,cjs.Ease.get(1)).wait(65).to({startPosition:10},0).to({x:423.3,startPosition:29},19).wait(19));

	// T2
	this.instance_2 = new lib.T2("synched",89);
	this.instance_2.setTransform(462.25,50.65);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(103).to({_off:false},0).to({alpha:1,startPosition:117},14,cjs.Ease.get(1)).wait(51).to({startPosition:168},0).to({alpha:0,startPosition:191},11,cjs.Ease.get(1)).wait(115));

	// T1
	this.instance_3 = new lib.T1("synched",21);
	this.instance_3.setTransform(460.25,141);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(21).to({_off:false},0).to({y:51,alpha:1,startPosition:46},19,cjs.Ease.get(1)).wait(49).to({startPosition:95},0).to({alpha:0,startPosition:123},14,cjs.Ease.get(1)).wait(191));

	// Logo
	this.instance_4 = new lib.Symbol1("synched",0);
	this.instance_4.setTransform(-50.5,48.55);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:49.5,alpha:1},22,cjs.Ease.get(1)).wait(272));

	// Layer_8 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AKPJnQj+AAi0i0Qi0i0AAj/QAAj+C0i0QC0i0D+AAIR1AAQD/AACzC0QC1C0AAD+QAAD/i1C0QizC0j/AAg");
	mask.setTransform(241.1,28.55);

	// IM4
	this.instance_5 = new lib.IM4("synched",9);
	this.instance_5.setTransform(529,45);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(255).to({_off:false},0).to({alpha:1,startPosition:30},21,cjs.Ease.get(1)).wait(18));

	// IM3
	this.instance_6 = new lib.IM3("synched",168);
	this.instance_6.setTransform(529,45);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(168).to({_off:false},0).to({alpha:1,startPosition:191},23,cjs.Ease.get(1)).to({_off:true},85).wait(18));

	// IM2
	this.instance_7 = new lib.IM2("synched",89);
	this.instance_7.setTransform(529,45);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(89).to({_off:false},0).to({alpha:1,startPosition:117},28,cjs.Ease.get(1)).to({_off:true},74).wait(103));

	// IM1
	this.instance_8 = new lib.IM1("synched",21);
	this.instance_8.setTransform(529,45);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(21).to({_off:false},0).to({alpha:1,startPosition:46},19,cjs.Ease.get(1)).to({_off:true},77).wait(177));

	// BG_png
	this.instance_9 = new lib.BG();

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(294));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(65.5,-7.7,265.3,135.7);
// library properties:
lib.properties = {
	id: '75E153FF2D744F028C65A7813D4CAE23',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"_320x50_1.jpg", id:"_320x50_1"},
		{src:"_320x50jpgcopy.jpg", id:"_320x50jpgcopy"},
		{src:"_320x50jpgcopy2.jpg", id:"_320x50jpgcopy2"},
		{src:"_320x501.jpg", id:"_320x501"},
		{src:"BG.png", id:"BG"},
		{src:"PBB_logo1.png", id:"PBB_logo1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['75E153FF2D744F028C65A7813D4CAE23'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;