(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.IM1 = function() {
	this.initialize(img.IM1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.IM2 = function() {
	this.initialize(img.IM2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,160,600);


(lib.PBB_logo1 = function() {
	this.initialize(img.PBB_logo1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,244,194);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// T2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3927").s().p("AgLBCQgIgHAAgFQAAgGAIgHQAHgIAEAAQAFAAAIAIQAHAHAAAGQAAAFgHAHQgIAIgFAAQgEAAgHgIgAgHATQgCgDgBgKIgFghQgDgQAAgKQAAgTASgBQATAAAAAVQAAAIgDARQgEATgBAOQgBAKgBADQgDAGgGgBQgFABgCgGg");
	this.shape.setTransform(-323.225,179.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B3927").s().p("AgUAyQgFgJAAgQIACgsQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAAgIQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAOgCAFgIQADgDACgLQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAMAAQAAAAABAAQABAAAAABQAAAAABAAQAAABAAABIAAATIAAAFQAAAAABAAQAAAAABABQAAAAABAAQABAAABAAIAJgBIALgBQAHAAAAAEIgBAGIgCAGQgCABgFAAIgKAAIgLAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAQQAAAcADAKQAEALAJAAQAFAAAFgDQAEgEACAAQAEAAAAAFQAAADgDADQgKAPgUAAQgUAAgIgPg");
	this.shape_1.setTransform(-331.275,180.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B3927").s().p("AgUBMQgIAAAAgFQAAgDAFgDQAGgDABgFQACgGAAgPIAAgaIgBgNQgCgEgFgDQgHgCAAgDQAAgEAHgCQARgDAKgFIAFgBQAFABAAAGIAAA7QAAAPACAGQACAFAGADQAFADAAADQAAAFgIAAgAgKgsQgIgHAAgFQAAgFAIgGQAHgIADAAQAFAAAHAIQAHAGAAAFQAAAFgHAHQgHAIgFgBQgDABgHgIg");
	this.shape_2.setTransform(-338.475,178.75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B3927").s().p("AgjAuQgIgGAAgQQABgKAHAAQADAAADADIAGAIQALANAMAAQAFAAAFgCQAFgDAAgGQAAgGgIgEIgSgGQgNgEgGgFQgJgHAAgNQAAgQAOgKQAMgJASAAQAPAAAJAEQAJAFAAANQAAAHgBACQgCADgFAAQgEAAgDgFQgKgOgNAAQgEAAgFADQgDADAAAEQAAAGAJAEIASAGQAcAKABAVQAAAQgPAKQgOAJgRAAQgWAAgLgIg");
	this.shape_3.setTransform(-352.75,181.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B3927").s().p("AgjAuQgIgGAAgQQAAgKAIAAQADAAADADIAGAIQALANAMAAQAFAAAFgCQAFgDAAgGQAAgGgIgEIgSgGQgNgEgHgFQgIgHAAgNQAAgQAOgKQAMgJARAAQAQAAAJAEQAKAFgBANQABAHgCACQgCADgFAAQgEAAgDgFQgKgOgNAAQgEAAgEADQgEADgBAEQABAGAIAEIATAGQAcAKABAVQAAAQgPAKQgNAJgSAAQgWAAgLgIg");
	this.shape_4.setTransform(-362.75,181.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B3927").s().p("AgUBMQgIAAAAgFQAAgDAFgDQAGgDABgFQACgGAAgPIAAgaIgBgNQgCgEgFgDQgHgCAAgDQAAgEAHgCQARgDAKgFIAFgBQAFABAAAGIAAA7QAAAPACAGQACAFAGADQAFADAAADQAAAFgIAAgAgKgsQgIgHAAgFQAAgFAIgGQAHgIADAAQAFAAAHAIQAHAGAAAFQAAAFgHAHQgHAIgFgBQgDABgHgIg");
	this.shape_5.setTransform(-370.425,178.75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B3927").s().p("AAtA1QgIAAAAgFQAAgDAFgDQAGgEACgEQACgGAAgPIAAgYQAAgTgRAAQgHAAgGAFQgEAFgCAJIgBAYQAAASABAEQABAEAEADQAFAEAAACQAAAFgIAAIgjAAQgHAAAAgFQAAgDAFgDQAEgDAAgEQABgEAAgSIAAgWQAAgVgQAAQgHAAgEAFQgFAFgCAJQgCAIAAAQQAAAOACAHQACAFAGADQAFADAAADQAAAFgIAAIgrAAQgIAAAAgFQAAgDAFgDQAFgDACgFQACgGAAgPIAAgZIgBgOQgCgEgFgCQgHgDAAgDQAAgDAHgCQAQgEALgEIAGgBQAFAAAAAGIAAAKIABABIABAAQAMgRAVAAQATAAAJAQIABABIACgBQALgQAVAAQASAAAJAOQAGAKAAAQIAAAZQAAAPACAGQACAFAGADQAFADAAADQAAAFgIAAg");
	this.shape_6.setTransform(-383.475,181.025);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3927").s().p("AgUAyQgFgJAAgQIACgsQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAAgIQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAOgCAFgIQADgDACgLQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAMAAQAAAAABAAQABAAAAABQAAAAABAAQAAABAAABIAAATIAAAFQAAAAABAAQAAAAABABQAAAAABAAQABAAABAAIAJgBIALgBQAHAAAAAEIgBAGQgBAEgBACQgCABgFAAIgKAAIgLAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAQQAAAcADAKQAEALAJAAQAFAAAFgDQAEgEACAAQAEAAAAAFQAAADgDADQgKAPgUAAQgUAAgIgPg");
	this.shape_7.setTransform(-400.375,180.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3927").s().p("AgHAUQgFgPAAgSQAAgIACgDQADgDAHAAQAIAAADADQACADAAAIQAAASgFAPQgDAIgFAAQgEAAgDgIg");
	this.shape_8.setTransform(-406.425,174.875);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3927").s().p("AANA1QgIAAAAgFQAAgDAFgDQAFgDACgFQACgGAAgQIAAgXQAAgTgQAAQgHAAgFAGQgJAIAAAcQAAAQACAGQABAFAGADQAFADAAADQAAAFgIAAIgqAAQgIAAAAgFQAAgDAFgDQAGgDABgFQACgGAAgQIAAgYQAAgKgBgDQgCgFgFgCQgHgDAAgDQAAgEAHgBQAOgDANgFIAGgBQAFAAAAAGIAAAKIABABIABgBQAMgQATAAQATAAAJAOQAGAJAAASIAAAXQAAAPACAHQACAFAGADQAFADAAADQAAAFgIAAg");
	this.shape_9.setTransform(-412.675,181.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3927").s().p("AgnAoQgPgPAAgYQAAgWAQgQQAQgQAXAAQAYAAAPAPQAPAPAAAXQAAAWgQAQQgQAQgXAAQgYAAgPgOgAgWgHQAAAPAFANQAGASANAAQAKAAAFgKQAGgJAAgPQAAgPgFgMQgGgRgNAAQgVAAAAAgg");
	this.shape_10.setTransform(-424.675,181.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3927").s().p("AAQBFIAAgIQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAAAAAAAIgCABQgNAQgSAAQgSAAgMgOQgLgOAAgVQAAgYANgQQAPgTAYAAQAKAAAKAFIACAAIABgBIAAgHIgBgNQgCgEgGgCQgGgDAAgDQAAgEAHgBQAQgEALgEIAFgCQAFAAAAAHIAABoQAAAJACAEQABAEAGADQAGADAAADQAAADgGACIgaAHIgHACQgFAAAAgHgAgYgEQgEAIAAAOQAAAQAGAKQAGAKALAAQAIAAAGgIQAHgJAAgRQAAgSgGgJQgHgJgJAAQgMAAgGAMg");
	this.shape_11.setTransform(-436.725,178.975);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3927").s().p("AgtA0QgPgTAAggQAAgeASgXQASgUAaAAQAbAAAQATQAQAUAAAgQAAAjgTAUQgRAUgZgBQgdAAgQgVgAgYgEQAAAZAHARQAGATAMgBQAYABAAg0QAAgegHgQQgIgPgKAAQgYAAAAA0g");
	this.shape_12.setTransform(-352.6,157.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3927").s().p("AgfBGQgLgFgGgGQgDgHAAgMQgBgIACgDQACgEAGAAQAEAAAEAFIAFAMQALAQAOAAQAJgBAGgHQAEgIAAgNQAAgYgVAAIgOABQgGgBAAgFIAAgGQAAgGAGAAIANABQATAAAAgYQAAgJgDgGQgGgHgHAAQgLAAgHAJIgJANQgDAHgFAAQgEAAgCgDQgCgDAAgJQAAgOAJgHQAMgIAXAAQAVAAAOAIQAQAKABARQAAALgJAIQgIAJgQAFIgCABIACABQAQACAJAHQALAJAAAPQABAPgMAMQgRAPgcAAQgPABgMgEg");
	this.shape_13.setTransform(-364.85,157.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3927").s().p("AgxBCQgGgGAAgIQAAgOAKAAQAEAAAGAGQAGAGAGAAQAIAAAFgIIABgDIAAgCIgihPQgFgLgEgDIgGgEQgEgCAAgDQAAgFAIAAIArAAQAHgBAAAGQAAACgFADQgFADAAAEIACAIIATAsIABABIABgBIAMgdQAFgLAAgIQAAgGgGgEQgFgDAAgDQAAgFAIAAIAgAAQAIAAAAAFQAAACgDACIgGAFQgDACgEAFQgEAGgGAQIgXA3QgRArgeABQgKgBgGgFg");
	this.shape_14.setTransform(-380.275,161.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("AAMAnIgBgBIgBABQgKAPgVAAQgNAAgJgGQgKgHAAgNQAAgQAPgJQAJgEAYgIQAOgHAAgKQAAgMgMAAQgHAAgGAEQgEADgHAJQgEAHgFAAQgFAAgCgDQgCgDAAgHQAAgKAEgFQAEgGAOgCQAKgCAKAAQARAAAMAHQAPAKAAAQIgBAmQAAALABADQACAEAGAAQAFABAAAEQAAAEgFAEQgHAFgKAAQgQAAgEgPgAAHAAQgNAFgHAGQgIAGAAAHQAAAFAEAEQADADAGAAQAJAAAFgKQADgGAAgSIAAgCIgBAAg");
	this.shape_15.setTransform(-391.875,159.125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AAhBHQgIAAABgEQAAgEAEgCQAGgEABgFQACgGAAgPIAAhKIAAgBIgCACIgjBWQgCAFgDAAIgJAAQgDAAgCgFIgkhXIAAgBIgBABIAABQQABAQAKAGIAGACQADADAAACQABAFgJAAIgkAAQgIAAAAgEQAAgDADgCIAFgFQAFgIABgYIABhJIgBgGQgBgDgEgBIgEgDQgEgBAAgDQABgFAHgBIAoAAQAGABADAEIAcBCIABABIAAgBIAchBQABgGAGAAIArAAQAHAAgBAGQAAAAAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgEADQgGADAAALIAABMQAAAPACAGQACAGAFADQAFACAAAEQAAAEgHAAg");
	this.shape_16.setTransform(-406.95,157.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("AgkAuQgGgGAAgQQAAgKAIAAQACAAADADIAHAIQAKANAMAAQAFAAAFgCQAFgDAAgGQAAgGgJgEIgSgGQgMgEgHgFQgIgHAAgNQAAgQAOgKQANgJARAAQAOAAALAEQAIAFABANQgBAHgBACQgCADgEAAQgEAAgEgFQgKgOgMAAQgFAAgFADQgEADAAAEQAAAGAKAEIASAGQAcAKAAAVQAAAQgOAKQgNAJgTAAQgWAAgLgIg");
	this.shape_17.setTransform(-340.2,137.125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AAQBFIAAgIQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAAAAAAAIgCABQgNAQgSAAQgSAAgMgOQgLgOAAgVQAAgYANgQQAPgTAYAAQAKAAAKAFIACAAIABgBIAAgHIgBgNQgCgEgGgCQgGgDAAgDQAAgEAHgBQAQgEALgEIAFgCQAFAAAAAHIAABoQAAAJACAEQABAEAGADQAGADAAADQAAADgGACIgaAHIgHACQgFAAAAgHgAgYgEQgEAIAAAOQAAAQAGAKQAGAKALAAQAIAAAGgIQAHgJAAgRQAAgSgGgJQgHgJgJAAQgMAAgGAMg");
	this.shape_18.setTransform(-351.525,134.975);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("AANA1QgIAAAAgFQAAgDAFgDQAFgDACgFQACgGAAgQIAAgXQAAgTgQAAQgHAAgFAGQgJAIAAAcQAAAQACAGQABAFAGADQAFADAAADQAAAFgIAAIgqAAQgIAAAAgFQAAgDAFgDQAGgDABgFQACgGAAgQIAAgYQAAgKgBgDQgCgFgFgCQgHgDAAgDQAAgEAHgBQAOgDANgFIAGgBQAFAAAAAGIAAAKIABABIABgBQAMgQATAAQATAAAJAOQAGAJAAASIAAAXQAAAPACAHQACAFAGADQAFADAAADQAAAFgIAAg");
	this.shape_19.setTransform(-364.275,137.025);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AgiAoQgOgOAAgXQAAgWAPgRQAPgRAXAAQARAAANALQAOALAAASQAAAJgEACQgDACgKAAIgvAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIAAACQABAIAFAHQAJAPASAAQAKAAAIgEIAJgEQAEAAAAAEQAAAHgMAIQgOAJgTAAQgVAAgPgOgAgKghQgFAGgCAJIAAACQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAWAAQAMAAAAgJQAAgGgEgEQgEgFgHAAQgIAAgGAFg");
	this.shape_20.setTransform(-376.85,137.125);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AgiAoQgOgOAAgXQAAgWAPgRQAPgRAXAAQARAAANALQAOALAAASQAAAJgEACQgDACgKAAIgvAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIAAACQABAIAFAHQAJAPASAAQAKAAAIgEIAJgEQAEAAAAAEQAAAHgMAIQgOAJgTAAQgVAAgPgOgAgKghQgFAGgCAJIAAACQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAWAAQAMAAAAgJQAAgGgEgEQgEgFgHAAQgIAAgGAFg");
	this.shape_21.setTransform(-393.5,137.125);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AgVBLQgHAAAAgFQAAgDAFgDQAFgDADgGQACgFAAgQIAAhEQgBgJgBgEQgCgEgFgCQgHgDAAgDQABgEAGgBQARgEAKgEIAFgCQAFAAAAAHIAABlQAAAQACAFQACAGAFADQAGADAAADQgBAFgHAAg");
	this.shape_22.setTransform(-401.95,134.875);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AAMAnIgBgBIgBABQgKAPgVAAQgNAAgJgGQgKgHAAgNQAAgQAPgJQAJgEAYgIQAOgHAAgKQAAgMgMAAQgHAAgGAEQgEADgHAJQgEAHgFAAQgFAAgCgDQgCgDAAgHQAAgKAEgFQAEgGAOgCQAKgCAKAAQARAAAMAHQAPAKAAAQIgBAmQAAALABADQACAEAGAAQAFABAAAEQAAAEgFAEQgHAFgKAAQgQAAgEgPgAAHAAQgNAFgHAGQgIAGAAAHQAAAFAEAEQADADAGAAQAJAAAFgKQADgGAAgSIAAgCIgBAAg");
	this.shape_23.setTransform(-410.825,137.125);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B3927").s().p("AggBFQgNgEgFgIQgEgFAAgMIAAgIQAAgJAHAAQAEAAAEAFIALANQAOAQAPAAQALAAAGgGQAGgGAAgHQAAgLgLgHIgZgKQgRgHgIgGQgMgKAAgQQAAgSAPgMQAQgNAXAAQAbAAAMALQAFAEAAAPQAAANgIAAQgEAAgEgDIgHgKQgNgPgNAAQgHAAgFAFQgGAEAAAIQAAAKAMAHIAYAJQASAHAIAHQALAKAAARQAAAVgRAMQgQANgZABQgQAAgNgFg");
	this.shape_24.setTransform(-423.775,135.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},89).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},13).to({state:[]},1).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},14).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},80).to({state:[]},1).wait(48));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-461.9,125,159,68);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// T1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3927").s().p("AgIAJQgFgGAAgDQAAgDAFgFQAGgFACAAQAEAAAFAFQAFAFAAADQAAADgFAGQgFAFgEAAQgCAAgGgFg");
	this.shape.setTransform(-354.725,245.775);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B3927").s().p("AgbAkQgFgFAAgLQAAgHAFAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABIAFAGQAJAMAJAAQAHAAAEgDQAEgDAAgFQAAgHgJgDIgOgFQgJgEgGgDQgGgGAAgJQAAgPAOgIQAIgFALAAQANAAAGAFQAGADAAAKQAAAKgFAAQgDAAgCgEQgJgNgJAAQgFAAgEADQgDADAAAEQAAAHALAEIAPAFQAIADAFAEQAFAGAAAJQAAANgMAIQgJAHgNAAQgSAAgIgIg");
	this.shape_1.setTransform(-361.025,242.825);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B3927").s().p("AAPA4IAAgIQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgBABQgLANgOAAQgHAAgHgEQgTgKAAgaQAAgTALgNQAMgPARAAQAJAAAKAGIABAAIAAgBIAAgIIgBgMQgBgDgFgCQgEgBAAgCQAAgDAEgBIARgFIAGgCQADAAAAAFIAABVQABAKABACQACADAEABQAEACAAACQAAADgFABQgMADgGADIgEABQgEAAAAgFgAgTgHQgGAHAAAPQAAANAGAJQAGAJAJAAQAIAAAFgHQAGgIAAgPQAAgPgGgIQgFgIgIAAQgKAAgFAIg");
	this.shape_2.setTransform(-370.55,241.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B3927").s().p("AgOA8QgFAAAAgEQAAgCADgCQAEgCABgEQACgEAAgMIAAg6QAAgKgBgCQgBgDgEgCQgFgBAAgCQAAgDAFgBIAPgFIAGgCQAEAAAAAFIAABUQAAAMACAEQACAEADACQAEACAAACQAAAEgFAAg");
	this.shape_3.setTransform(-378.675,241.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B3927").s().p("AgOA8QgFAAAAgDQAAgCADgCQAEgCACgEQACgEAAgNIAAgZQAAgHgCgDQgBgDgEgBQgFgDAAgCQAAgCAFgBQAJgCAGgDIAGgCQAEAAAAAFIAAAxQAAANACAEQACAEAEACQADACAAACQAAADgFAAgAgHgmQgFgFAAgDQAAgDAFgFQAFgFACAAQADAAAFAFQAGAFAAADQAAADgGAFQgFAGgDAAQgCAAgFgGg");
	this.shape_4.setTransform(-384.125,240.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B3927").s().p("AARAnIAAgJIAAgBIgBAAQgJAPgQAAQgOAAgHgLQgGgHAAgPIAAgXQAAgJgBgDQgBgDgFgBQgEgCAAgCQAAgDAFgBIASgGIAEgBQAEAAAAAFIAAAxQAAARAPAAQAGAAAFgEQAHgIAAgaQAAgLgBgDQgCgDgEgBQgEgCAAgCQAAgDAFgBIASgGIAEgBQAEAAAAAFIAAAzQAAAJABADQABADAFABQAEACAAACQAAADgFABIgSAGIgEABQgEAAAAgFg");
	this.shape_5.setTransform(-392.425,242.825);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B3927").s().p("AgQA3IgFgCQgDAAgBADQgCAFgDAAQgDAAAAgHIAAhTQAAgJgCgDQgCgDgDgCQgFgBAAgCQAAgDAFgBIASgGIAEgBQAEAAAAAFIAAAqQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIABgBQAKgNAPAAQAPAAAKAMQAIALAAAQQAAANgGAMQgMAXgYAAQgLAAgJgGgAgJgEQgFAHAAAPQAAAQAFAIQAGAIAJAAQAJAAAFgIQAGgJgBgOQABgNgGgIQgGgJgKAAQgHAAgGAHg");
	this.shape_6.setTransform(-402.75,241.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3927").s().p("AAMArQgFAAgBgEQABgCADgCQAEgCABgEQACgEAAgNIAAgVQAAgIgDgFQgEgEgHAAQgHAAgFAEQgEAFgBAHQgCAIAAAOQAAANACAEQABAEAEACQAEACAAACQAAAEgGAAIgeAAQgFAAgBgEQABgCADgCQAEgDABgDQACgEAAgNIAAgXQAAgJgBgDQgBgDgEgBQgFgCAAgCQAAgDAFgBQAKgCAFgDIAHgCQAEAAAAAFIAAAJIABABIABgBQAIgOARAAQAOAAAHALQAFAIAAAOIAAAVQAAANACAEQACAEADACQAEACAAACQAAAEgGAAg");
	this.shape_7.setTransform(-317.35,223.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3927").s().p("AgZArQgGAAAAgEQAAgCAEgCQAEgCABgEQACgEAAgMIAAgYQAAgJgBgDQgCgDgEgBQgEgCAAgCQAAgDAEgBQALgDAGgDIAEgBQAEAAAAAFIAAANIABAAIAAAAQACgHAGgFQAHgGAHAAQAFAAADAEQADADAAAHQAAAIgGAAQgCAAgEgCIgGgCQgEAAgDADQgHAJAAAZQAAAMABAEQABAEAEACQAEACAAACQAAAEgGAAg");
	this.shape_8.setTransform(-326.225,223.725);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3927").s().p("AALAfIgBgBQgIAOgRAAQgKAAgHgGQgIgGAAgJQAAgMALgHQAJgEASgGQAMgGAAgJQAAgIgJgDIgCAAQgHAAgGAEIgFAHIgEAFQgCACgDAAQgFAAAAgJQAAgIACgEQAEgEAKgCQAGgCAKAAQANAAAJAIQAJAIAAAMIAAAhQAAANAFAAIACgBQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgBADQgEAHgJAAQgNAAgCgNgAAAADIgLAGQgHAEAAAIQAAAFADADQADACAFAAQAJAAAFgJQACgGABgPIAAgCIgBAAIAAAAIgJAEg");
	this.shape_9.setTransform(-334.5,223.825);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3927").s().p("AgQA3IgFgCQgDAAgBADQgCAFgCAAQgEAAgBgHIAAhTQAAgJgBgDQgBgDgEgCQgFgBAAgCQAAgDAFgBIATgGIADgBQAEAAAAAFIAAAqQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIABgBQALgNAOAAQAPAAAJAMQAJALAAAQQAAANgGAMQgMAXgYAAQgLAAgJgGgAgJgEQgFAHAAAPQAAAQAFAIQAGAIAJAAQAJAAAFgIQAFgJAAgOQAAgNgFgIQgGgJgJAAQgIAAgGAHg");
	this.shape_10.setTransform(-344,222.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3927").s().p("AAlArQgFAAAAgEQAAgCADgCQAEgCACgEQACgEAAgMIAAgWQAAgRgPAAQgHAAgFAEQgEAFgBAIIgBAWQAAANACAEQABADADACQADACAAACQAAAEgFAAIgaAAQgFAAAAgEQAAgCADgCQADgCABgDQACgDAAgOIAAgVQAAgSgPAAQgGAAgFAEQgEAEgCAIQgBAIAAAPQAAAMACAEQABADAEADQAEACAAACQAAAEgGAAIgeAAQgGAAAAgEQAAgCAEgCQAEgCABgEQACgEAAgMIAAgYQAAgJgBgDQgCgDgEgBQgEgCAAgCQAAgDAFgBIASgGIAEgBQAEAAAAAFIAAAJIAAABIABAAQAJgPARAAQAJAAAFAFQAGAEACAGIABAAIABAAQAJgPARAAQAOAAAIALQAFAIAAAOIAAAWQAAAMABAEQACADAEADQADACAAACQAAAEgFAAg");
	this.shape_11.setTransform(-358.525,223.725);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3927").s().p("AAMAfIgBgBQgJAOgQAAQgLAAgHgGQgHgGAAgJQAAgMAKgHQAIgEATgGQALgGAAgJQAAgIgHgDIgEAAQgGAAgFAEIgGAHIgEAFQgCACgDAAQgFAAAAgJQAAgIADgEQADgEAJgCQAHgCAJAAQAOAAAJAIQAKAIAAAMIgBAhQAAANAEAAIADgBQABAAABAAQAAABABAAQAAABAAAAQABABAAABIgCADQgEAHgKAAQgMAAgBgNgAAAADIgLAGQgHAEAAAIQAAAFADADQADACAFAAQAJAAAFgJQACgGAAgPIAAgCIAAAAIgBAAIgIAEg");
	this.shape_12.setTransform(-370.9,223.825);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3927").s().p("AgTAmQgKgHgFgMQgDgIAAgJQAAgLAFgKQAHgMALgGQAJgFAJgBQANABAJAHQAMAKAAAOQAAAGgDACQgCADgIAAIgoAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAQABAKAFAIQAHAKAMAAQAKAAAHgEIAIgEQABAAABAAQAAAAABABQAAAAAAABQAAABAAABQAAAFgKAGQgKAIgPAAQgLgBgJgFgAgMgYQgFAHAAAGQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIAVAAQAMAAAAgIQAAgGgEgDQgFgFgHgBQgJABgFAIg");
	this.shape_13.setTransform(-379.75,223.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3927").s().p("AgQA3IgFgCQgDAAgBADQgCAFgDAAQgDAAAAgHIAAhTQAAgJgCgDQgCgDgDgCQgFgBAAgCQAAgDAFgBIASgGIAEgBQAEAAAAAFIAAAqQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIABgBQAKgNAPAAQAPAAAKAMQAIALAAAQQAAANgGAMQgMAXgYAAQgLAAgJgGgAgJgEQgFAHAAAPQAAAQAFAIQAGAIAJAAQAJAAAFgIQAGgJgBgOQABgNgGgIQgGgJgKAAQgHAAgGAHg");
	this.shape_14.setTransform(-389.25,222.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("AgnAqQgNgKAAgOQAAgKAFgHQAGgGAJgDQgDgHAAgIQAAgMAKgIQAIgHAMAAQANAAAFAHQADADAAAHQAAAMgFAAQgEAAgCgDIgCgFIgDgGQgEgFgFAAQgFAAgDAEQgDADgBAGQAAAHAHAHQAGAGANAIIAUANIACABQACgEAAgHQAAgIgIgEQgEgDgBgCQAAgDAGAAIAbAAQAEAAAAADQAAACgEADQgFADgCAFQgEANgEAHIAAABIABABIAFAFQAJAKAAAKQAAABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgNAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBgFgFgEIgBAAIAAAAQgMANgWAAQgQAAgMgJgAgcAAQgEAFAAAHQAAAMAJAHQAJAJALgBQALAAAHgHIABgBIgBAAIgUgPQgPgKgGgGIgBAAIgBAAg");
	this.shape_15.setTransform(-403.1,223.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AgOApQgDgHgBgNIABgmQAAgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgKAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQAMgCADgHIADgLQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAPIAAAEQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAIASgCQAFAAAAAEIgBADQgBAGgGAAIgSgBQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAABIAAASQAAAWACAHQAEAIAIAAQAEAAAEgDIAFgDQABAAAAAAQABABAAAAQABAAAAABQAAABAAAAIgCAFQgDAFgHAEQgGADgHAAQgOAAgGgLg");
	this.shape_16.setTransform(-414.4,222.975);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("AgbAkQgFgFAAgLQAAgHAFAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABIAFAGQAJAMAJAAQAHAAAEgDQAEgDAAgFQAAgHgJgDIgOgFQgJgEgGgDQgGgGAAgJQAAgPAOgIQAIgFALAAQANAAAGAFQAGADAAAKQAAAKgFAAQgDAAgCgEQgJgNgJAAQgFAAgEADQgDADAAAEQAAAHALAEIAPAFQAIADAFAEQAFAGAAAJQAAANgMAIQgJAHgNAAQgSAAgIgIg");
	this.shape_17.setTransform(-422.025,223.825);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AgeAgQgLgMAAgTQAAgSAMgMQAMgNARgBQATAAAMANQALAMAAASQAAASgMANQgMANgSAAQgSAAgMgMgAgPgZQgFAHAAANQAAAPAFALQAHAMAKAAQAJAAAFgIQAFgIAAgMQAAgPgFgKQgHgNgKAAQgIAAgGAIg");
	this.shape_18.setTransform(-430.875,223.825);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("AgnA6QgFAAAAgDQAAgDADgCQAEgCACgDQABgFAAgMIAAg3QABgJgCgCQgBgDgFgCQgEgBAAgDQAAgDAFgBIASgFIAEgBQAEAAAAAFIAAAHQAAABAAAAQAAAAAAAAQAAABABAAQAAAAAAAAIACgBQAJgNAPAAQAIAAAGADQATAKAAAaQAAATgLAOQgMAOgRAAQgJAAgKgFIgBAAIAAABIAAAEQAAAMACAEQACADADACQAEACAAADQAAADgFAAgAgIgjQgGAIAAAPQAAAOAGAJQAGAIAIAAQAJAAAGgJQAEgJABgMQgBgOgFgJQgGgJgJAAQgIAAgFAIg");
	this.shape_19.setTransform(-441.05,225.275);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AgZArQgGAAAAgEQAAgCAEgCQAEgCABgEQACgEAAgMIAAgYQAAgJgBgDQgCgDgEgBQgEgCAAgCQAAgDAEgBQALgDAGgDIAEgBQAEAAAAAFIAAANIABAAIAAAAQACgHAGgFQAHgGAHAAQAFAAADAEQADADAAAHQAAAIgGAAQgCAAgEgCIgGgCQgEAAgDADQgHAJAAAZQAAAMABAEQABAEAEACQAEACAAACQAAAEgGAAg");
	this.shape_20.setTransform(-316.225,204.725);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AALAfIgBgBQgIAOgRAAQgKAAgHgGQgIgGAAgJQAAgMALgHQAJgEASgGQALgGAAgJQABgIgJgDIgCAAQgHAAgGAEIgFAHIgEAFQgCACgDAAQgFAAAAgJQAAgIACgEQAEgEAKgCQAGgCAKAAQANAAAJAIQAJAIAAAMIAAAhQAAANAFAAIACgBQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgBADQgEAHgJAAQgNAAgCgNgAAAADIgLAGQgHAEAAAIQAAAFADADQADACAFAAQAJAAAFgJQACgGAAgPIAAgCIAAAAIAAAAIgJAEg");
	this.shape_21.setTransform(-324.5,204.825);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AgOA8QgFAAAAgEQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAABgBQAEgCABgEQACgEAAgMIAAg6QAAgKgBgCQgBgDgEgCQgFgBAAgCQAAgDAFgBIAPgFIAGgCQAEAAAAAFIAABUQAAAMACAEQACAEADACQAEACAAACQAAAEgFAAg");
	this.shape_22.setTransform(-331.875,203.025);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AARAnIAAgJIAAgBIgBAAQgJAPgQAAQgOAAgHgLQgGgHAAgPIAAgXQAAgJgBgDQgBgDgFgBQgEgCAAgCQAAgDAFgBIASgGIAEgBQAEAAAAAFIAAAxQAAARAPAAQAGAAAFgEQAHgIAAgaQAAgLgBgDQgCgDgEgBQgEgCAAgCQAAgDAFgBIASgGIAEgBQAEAAAAAFIAAAzQAAAJABADQABADAFABQAEACAAACQAAADgFABIgSAGIgEABQgEAAAAgFg");
	this.shape_23.setTransform(-340.075,204.825);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B3927").s().p("AgnA6QgFAAAAgDQAAgDADgCQAEgCACgDQABgFAAgMIAAg3QABgJgCgCQgBgDgFgCQgEgBAAgDQAAgDAFgBIASgFIAEgBQAEAAAAAFIAAAHQAAABAAAAQAAAAAAAAQAAABABAAQAAAAAAAAIACgBQAJgNAPAAQAIAAAHADQASAKAAAaQAAATgLAOQgLAOgSAAQgJAAgKgFIgBAAIAAABIAAAEQAAAMACAEQACADADACQAEACAAADQAAADgFAAgAgIgjQgGAIAAAPQAAAOAGAJQAGAIAIAAQAJAAAGgJQAEgJABgMQgBgOgFgJQgGgJgJAAQgIAAgFAIg");
	this.shape_24.setTransform(-350.15,206.275);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B3927").s().p("AgeAgQgLgMAAgTQAAgSAMgMQAMgNARgBQATAAAMANQALAMAAASQAAASgMANQgMANgSAAQgSAAgMgMgAgPgZQgFAHAAANQAAAPAFALQAHAMAKAAQAJAAAFgIQAFgIAAgMQAAgPgFgKQgHgNgKAAQgIAAgGAIg");
	this.shape_25.setTransform(-359.175,204.825);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B3927").s().p("AgnA6QgFAAAAgDQAAgDADgCQAEgCABgDQACgFAAgMIAAg3QAAgJgBgCQgBgDgEgCQgFgBAAgDQAAgDAFgBQAKgCAIgDIAEgBQAEAAAAAFIAAAHQAAABAAAAQAAAAAAAAQAAABABAAQAAAAAAAAIACgBQAKgNAOAAQAIAAAGADQATAKAAAaQAAATgLAOQgLAOgSAAQgJAAgJgFIgBAAIgBABIAAAEQAAAMACAEQABADAEACQAEACAAADQAAADgGAAgAgJgjQgFAIAAAPQAAAOAGAJQAFAIAJAAQAKAAAFgJQAEgJAAgMQAAgOgFgJQgGgJgJAAQgIAAgGAIg");
	this.shape_26.setTransform(-368.85,206.275);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B3927").s().p("AgOApQgDgHgBgNIABgmQAAgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgKAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQALgCAEgHIADgLQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAPIAAAEQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAIASgCQAFAAAAAEIgBADQAAAGgHAAIgRgBQgBAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAABIAAASQAAAWADAHQADAIAIAAQAEAAAEgDIAFgDQABAAAAAAQABABAAAAQABAAAAABQAAABAAAAIgCAFQgDAFgHAEQgGADgHAAQgOAAgGgLg");
	this.shape_27.setTransform(-379.2,203.975);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B3927").s().p("AgbAkQgFgFAAgLQAAgHAFAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABIAFAGQAJAMAJAAQAHAAAEgDQAEgDAAgFQAAgHgJgDIgOgFQgJgEgGgDQgGgGAAgJQAAgPAOgIQAIgFALAAQANAAAGAFQAGADAAAKQAAAKgFAAQgDAAgCgEQgJgNgJAAQgFAAgEADQgDADAAAEQAAAHALAEIAPAFQAIADAFAEQAFAGAAAJQAAANgMAIQgJAHgNAAQgSAAgIgIg");
	this.shape_28.setTransform(-386.825,204.825);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B3927").s().p("AgeAgQgLgMAAgTQAAgSAMgMQAMgNARgBQATAAAMANQALAMAAASQAAASgMANQgMANgSAAQgSAAgMgMgAgPgZQgFAHAAANQAAAPAFALQAHAMAKAAQAJAAAFgIQAFgIAAgMQAAgPgFgKQgHgNgKAAQgIAAgGAIg");
	this.shape_29.setTransform(-395.675,204.825);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B3927").s().p("AAlArQgFAAAAgEQAAAAAAgBQABAAAAgBQAAAAABgBQAAAAABgBQAEgCACgEQACgEAAgMIAAgWQAAgRgPAAQgHAAgFAEQgEAFgBAIIgBAWQAAANACAEQABADADACQADACAAACQAAAEgFAAIgaAAQgFAAAAgEQAAgCADgCQADgCABgDQACgDAAgOIAAgVQAAgSgPAAQgGAAgFAEQgEAEgCAIQgBAIAAAPQAAAMACAEQABADAEADQAEACAAACQAAAEgGAAIgeAAQgGAAAAgEQAAgCAEgCQAEgCABgEQACgEAAgMIAAgYQAAgJgBgDQgCgDgEgBQgEgCAAgCQAAgDAFgBIASgGIAEgBQAEAAAAAFIAAAJIAAABIABAAQAJgPARAAQAJAAAFAFQAGAEACAGIABAAIABAAQAJgPARAAQAOAAAIALQAFAIAAAOIAAAWQAAAMABAEQACADAEADQADACAAACQAAAEgFAAg");
	this.shape_30.setTransform(-407.875,204.725);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B3927").s().p("AgZArQgGAAAAgEQAAgCAEgCQAEgCABgEQACgEAAgMIAAgYQAAgJgBgDQgCgDgEgBQgEgCAAgCQAAgDAEgBQALgDAGgDIAEgBQAEAAAAAFIAAANIABAAIAAAAQACgHAGgFQAHgGAHAAQAFAAADAEQADADAAAHQAAAIgGAAQgCAAgEgCIgGgCQgEAAgDADQgHAJAAAZQAAAMABAEQABAEAEACQAEACAAACQAAAEgGAAg");
	this.shape_31.setTransform(-421.675,204.725);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B3927").s().p("AARAnIAAgJIAAgBIgBAAQgJAPgQAAQgOAAgHgLQgGgHAAgPIAAgXQAAgJgBgDQgBgDgFgBQgEgCAAgCQAAgDAFgBQALgDAHgDIAEgBQAEAAAAAFIAAAxQAAARAPAAQAGAAAFgEQAHgIAAgaQAAgLgBgDQgCgDgEgBQgEgCAAgCQAAgDAFgBQALgDAHgDIAEgBQAEAAAAAFIAAAzQAAAJABADQABADAFABQAEACAAACQAAADgFABIgSAGIgEABQgEAAAAgFg");
	this.shape_32.setTransform(-431.125,204.825);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B3927").s().p("AgeAgQgLgMAAgTQAAgSAMgMQAMgNARgBQATAAAMANQALAMAAASQAAASgMANQgMANgSAAQgSAAgMgMgAgPgZQgFAHAAANQAAAPAFALQAHAMAKAAQAJAAAFgIQAFgIAAgMQAAgPgFgKQgHgNgKAAQgIAAgGAIg");
	this.shape_33.setTransform(-440.375,204.825);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B3927").s().p("AgPAXIACgCQAEgDADgEQAGgFgBgEQABgFgGgDQgFgHAAgCQAAgDAFgFQAFgFACgBQAEAAAGAHQAEAFABAHQAAAKgMANQgJALgFgBQgEABgBgEg");
	this.shape_34.setTransform(-345.45,190.15);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B3927").s().p("AgbAkQgFgFAAgLQAAgHAFAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABIAFAGQAJAMAJAAQAHAAAEgDQAEgDAAgFQAAgHgJgDIgOgFQgJgEgGgDQgGgGAAgJQAAgPAOgIQAIgFALAAQANAAAGAFQAGADAAAKQAAAKgFAAQgDAAgCgEQgJgNgJAAQgFAAgEADQgDADAAAEQAAAHALAEIAPAFQAIADAFAEQAFAGAAAJQAAANgMAIQgJAHgNAAQgSAAgIgIg");
	this.shape_35.setTransform(-351.875,185.825);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B3927").s().p("AgOApQgEgHAAgNIACgmQAAgBgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgKAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAMgCADgHIACgLQABgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAPIABAEQAAAAAAAAQAAAAABABQAAAAABAAQAAAAABAAIARgCQAGAAAAAEIAAADQgBAGgHAAIgRgBQgBAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAAASQAAAWACAHQADAIAIAAQAEAAAEgDIAFgDQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIgCAFQgEAFgFAEQgHADgIAAQgMAAgHgLg");
	this.shape_36.setTransform(-358.65,184.975);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B3927").s().p("AgOA8QgFAAAAgDQAAgCADgCQAEgCACgEQACgEAAgMIAAgZQAAgJgCgCQgBgDgEgCQgFgBAAgCQAAgDAFgCQAJgBAGgDIAGgCQAEAAAAAFIAAAyQAAAMACAEQACAEAEACQABABAAAAQABABAAAAQAAAAABABQAAAAAAABQAAADgFAAgAgHgmQgFgEAAgEQAAgDAFgFQAFgGACABQADgBAFAGQAGAFAAADQAAAEgGAEQgFAFgDABQgCgBgFgFg");
	this.shape_37.setTransform(-363.975,183.95);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B3927").s().p("AAgA8QgIAAgEgDQgEgCgKgQQgJgQgDAAQgCAAgCACIgFAFIgBACQAAAKACAEQACAEAEACQAEACgBACQABAEgGAAIggAAQgEAAAAgEQgBgCAEgCQAEgCABgEQACgEAAgNIAAg5QAAgJgBgDQgCgDgEgBQgEgCAAgCQAAgDAEgBQAMgDAGgCIAGgCQADAAAAAFIAABFIABAAIAAAAIAPgOQAJgJAAgEQAAgBAAAAQAAAAAAgBQAAAAgBgBQAAAAgBgBQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgEAGAAIAeAAQAGAAgBAEQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAIgFACQgKAEgWAUIgBABIABABIADgBQAEAAAEAFIAJANQAMAUAGACQAEADAAACQABAEgFAAg");
	this.shape_38.setTransform(-371.3,184.025);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B3927").s().p("AgTAmQgKgHgFgMQgDgIAAgJQAAgLAGgKQAFgMAMgGQAJgGAJAAQANAAAJAIQAMAKAAAOQAAAGgDACQgCADgIAAIgoAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAQABAKAFAIQAHAKAMAAQAKAAAHgEIAIgEQABAAABAAQAAAAABABQAAAAAAABQAAABAAABQAAAFgKAHQgLAHgOAAQgLgBgJgFgAgMgYQgFAHAAAGQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIAVAAQAMAAAAgIQAAgFgEgEQgFgGgHAAQgJABgFAIg");
	this.shape_39.setTransform(-385.5,185.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B3927").s().p("AgbAkQgFgFAAgLQAAgHAFAAQAAAAABAAQABAAAAAAQABABAAAAQABAAAAABIAFAGQAJAMAJAAQAHAAAEgDQAEgDAAgFQAAgHgJgDIgOgFQgJgEgGgDQgGgGAAgJQAAgPAOgIQAIgFALAAQANAAAGAFQAGADAAAKQAAAKgFAAQgDAAgCgEQgJgNgJAAQgFAAgEADQgDADAAAEQAAAHALAEIAPAFQAIADAFAEQAFAGAAAJQAAANgMAIQgJAHgNAAQgSAAgIgIg");
	this.shape_40.setTransform(-394.075,185.825);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B3927").s().p("AALAfIgBgBQgIAOgRAAQgKAAgHgGQgIgGAAgJQAAgMALgHQAJgEASgGQALgGAAgJQABgIgJgDIgCAAQgHAAgGAEIgFAHIgEAFQgCACgDAAQgFAAAAgJQAAgIACgEQAEgEAKgCQAGgCAKAAQANAAAJAIQAJAIAAAMIAAAhQAAANAFAAIACgBQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgBADQgEAHgJAAQgNAAgCgNgAAAADIgLAGQgHAEAAAIQAAAFADADQADACAFAAQAJAAAFgJQACgGAAgPIAAgCIAAAAIAAAAIgJAEg");
	this.shape_41.setTransform(-402.35,185.825);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B3927").s().p("AgQA3IgFgCQgDAAgBADQgCAFgDAAQgDAAAAgHIAAhTQAAgJgCgDQgBgDgEgCQgFgBAAgCQAAgDAFgBIATgGIADgBQAEAAAAAFIAAAqQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIABgBQAKgNAPAAQAPAAAKAMQAIALAAAQQAAANgGAMQgMAXgYAAQgLAAgJgGgAgJgEQgFAHAAAPQAAAQAFAIQAGAIAJAAQAJAAAFgIQAGgJgBgOQABgNgGgIQgGgJgJAAQgIAAgGAHg");
	this.shape_42.setTransform(-411.85,184.125);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B3927").s().p("AgiAyQgGgFAAgHQAAgDABgDQAFgIAHAAQAFAAAAADIgBADIgBAFQAAAGAGAEQAHAEALAAQAKAAAHgEQAGgDAAgFQAAgHgMAAIgYgCQgIgBgFgEQgEgEAAgFQAAgKALgEIABAAIgBgBQgRgIAAgRQAAgNAKgJQAKgJAPAAQAJAAAJAFIAGADQACAAADgEQACgEAEAAQAHAAAAAHQAAAJgKAAIgDAAQAEAGAAAIQAAANgKAIQgJAIgNAAIgHABQgHAAAAAEQAAAFALAAIALABIANAAQAJACAFAFQAFAEAAAHIgBAHQgGAUgjAAQgWAAgKgIgAgMgqQgDAFAAAHQAAALAFAGQAEAGAGAAQAFAAADgFQADgFAAgIQAAgJgDgGQgEgHgGAAQgHAAgDAFg");
	this.shape_43.setTransform(-321.375,168.275);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B3927").s().p("AAMArQgFAAgBgEQABgCADgCQAEgCABgEQACgEAAgNIAAgVQAAgIgEgFQgEgEgGAAQgHAAgFAEQgEAFgBAHQgCAIAAAOQAAANACAEQABAEAEACQAEACAAACQAAAEgGAAIgeAAQgFAAgBgEQABgCADgCQAEgDABgDQACgEAAgNIAAgXQAAgJgBgDQgBgDgEgBQgFgCAAgCQAAgDAFgBQAKgCAFgDIAHgCQAEAAAAAFIAAAJIABABIABgBQAIgOARAAQAOAAAHALQAFAIAAAOIAAAVQAAANACAEQACAEADACQAEACAAACQAAAEgGAAg");
	this.shape_44.setTransform(-331.2,166.725);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B3927").s().p("AgOA9QgFgBAAgDQAAgCADgCQAEgDACgDQACgEAAgMIAAgZQAAgJgCgCQgBgDgEgCQgFgBAAgCQAAgEAFgBQAJgBAGgDIAGgCQAEAAAAAFIAAAyQAAAMACAEQACADAEADQABABAAAAQABABAAAAQAAABABAAQAAAAAAABQAAADgFABgAgHglQgFgFAAgEQAAgDAFgFQAFgGACABQADgBAFAGQAGAFAAADQAAAEgGAFQgFAEgDABQgCgBgFgEg");
	this.shape_45.setTransform(-339.475,164.95);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B3927").s().p("AgOA8QgFAAAAgEQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAABgBQAEgCABgEQACgEAAgMIAAg6QAAgKgBgCQgBgDgEgCQgFgBAAgCQAAgDAFgBIAPgFIAGgCQAEAAAAAFIAABUQAAAMACAEQACAEADACQAEACAAACQAAAEgFAAg");
	this.shape_46.setTransform(-345.125,165.025);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B3927").s().p("AgZArQgGAAAAgEQAAgCAEgCQAEgCABgEQACgEAAgMIAAgYQAAgJgBgDQgCgDgEgBQgEgCAAgCQAAgDAEgBQALgDAGgDIAEgBQAEAAAAAFIAAANIABAAIAAAAQACgHAGgFQAHgGAHAAQAFAAADAEQADADAAAHQAAAIgGAAQgCAAgEgCIgGgCQgEAAgDADQgHAJAAAZQAAAMABAEQABAEAEACQAEACAAACQAAAEgGAAg");
	this.shape_47.setTransform(-351.175,166.725);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B3927").s().p("AgTAmQgKgHgFgMQgDgIAAgJQAAgLAFgKQAHgMALgGQAJgGAJAAQANAAAKAJQALAJAAAOQAAAGgCACQgDADgIAAIgoAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAABQgBAKAGAIQAHAKANAAQAIAAAIgEIAIgEQABAAABAAQAAAAABABQAAAAAAABQABABAAABQAAAFgLAHQgLAGgNABQgLAAgKgGgAgNgYQgDAHAAAFQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAVAAQAMAAAAgIQAAgFgEgEQgFgGgHAAQgIAAgHAJg");
	this.shape_48.setTransform(-359.45,166.8);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6B3927").s().p("AgOApQgDgHAAgNIAAgmQAAgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgKAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQAMgCADgHIADgLQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAIAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAPIAAAEQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAIASgCQAFAAAAAEIgBADQgBAGgGAAIgSgBQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAABIAAASQAAAWACAHQAEAIAIAAQAEAAAEgDIAFgDQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIgCAFQgEAFgGAEQgGADgHAAQgOAAgGgLg");
	this.shape_49.setTransform(-366.8,165.975);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#6B3927").s().p("AgYA4QgKgEgEgGQgCgDgBgKIAAgGQAAgHAFAAQADAAACAEIAIALQAMANAMAAQAJAAAGgFQAGgGAAgIQAAgJgIgFQgFgEgLgDQgNgEgFgEQgRgHAAgRQAAgMAJgJQAJgJAMgDIALgBQAUAAAJAJQAEAEAAALQAAAKgFAAQgDAAgCgCIgFgHIgGgHQgHgHgJAAQgHAAgFAEQgFAFAAAGQAAAKAMAGIAVAIQAMAEAGAGQAIAIAAAMQAAAHgDAHQgLAXgfAAQgMAAgJgDg");
	this.shape_50.setTransform(-375.175,165.275);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#6B3927").s().p("AgnAqQgNgJAAgQQAAgIAFgIQAGgGAKgDQgEgIAAgGQAAgNAJgIQAJgHAMAAQANAAAGAHQACACAAAJQAAALgGAAQgDAAgBgDIgDgFIgDgGQgEgFgFAAQgFAAgDADQgDAEAAAGQgBAHAIAHQAFAGANAIIAUANIABABQADgFAAgGQAAgHgIgGQgFgCAAgCQABgDAFAAIAbAAQAEAAAAADQAAACgEACQgEAEgDAFQgEAOgEAGIAAABIABABIAGAFQAIAKAAAKQAAABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgNAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBQgCgFgEgEIAAAAIgBAAQgMANgWAAQgQAAgMgJgAgcAAQgEAFAAAHQAAALAJAIQAJAJALAAQAKgBAIgHIABgBIgBAAIgUgPQgPgKgGgGIgBgBIgBABg");
	this.shape_51.setTransform(-389,166.05);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#6B3927").s().p("AgZArQgGAAAAgEQAAgCAEgCQAEgCABgEQACgEAAgMIAAgYQAAgJgBgDQgCgDgEgBQgEgCAAgCQAAgDAEgBQALgDAGgDIAEgBQAEAAAAAFIAAANIABAAIAAAAQACgHAGgFQAHgGAHAAQAFAAADAEQADADAAAHQAAAIgGAAQgCAAgEgCIgGgCQgEAAgDADQgHAJAAAZQAAAMABAEQABAEAEACQAEACAAACQAAAEgGAAg");
	this.shape_52.setTransform(-400.825,166.725);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#6B3927").s().p("AgTAmQgLgHgEgMQgDgIAAgJQAAgLAFgKQAHgMALgGQAIgGAKAAQANAAAKAJQALAJAAAOQAAAGgCACQgDADgIAAIgoAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBAAAAABQABAKAFAIQAHAKANAAQAJAAAHgEIAIgEQABAAABAAQAAAAABABQAAAAAAABQAAABAAABQAAAFgKAHQgKAGgPABQgLAAgJgGgAgNgYQgDAHgBAFQAAABABAAQAAAAAAABQAAAAAAAAQABAAAAAAIAVAAQAMAAAAgIQAAgFgEgEQgEgGgIAAQgIAAgHAJg");
	this.shape_53.setTransform(-409.1,166.8);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#6B3927").s().p("AAgA8QgIAAgDgDQgFgCgKgQQgJgQgCAAQgCAAgDACIgFAFIAAACQAAAKACAEQABAEAEACQADACABACQgBAEgFAAIgfAAQgGAAAAgEQABgCADgCQADgCACgEQACgEAAgNIAAg5QAAgJgBgDQgBgDgEgBQgGgCAAgCQAAgDAGgBQALgDAGgCIAFgCQAEAAABAFIAABFIAAAAIABAAIAOgOQAKgJgBgEQAAgBAAAAQAAAAAAgBQAAAAgBgBQAAAAgBgBQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgEAFAAIAfAAQAEAAAAAEQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAIgFACQgKAEgXAUIAAABIAAABIAEgBQADAAAEAFIAJANQAOAUAEACQAGADAAACQgBAEgEAAg");
	this.shape_54.setTransform(-418.15,165.025);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#6B3927").s().p("AAMAfIgBgBQgJAOgQAAQgLAAgHgGQgHgGgBgJQAAgMALgHQAIgEATgGQAMgGAAgJQgBgIgHgDIgEAAQgGAAgFAEIgGAHIgEAFQgCACgDAAQgFAAAAgJQAAgIACgEQAEgEAJgCQAIgCAIAAQAOAAAJAIQAKAIAAAMIgBAhQAAANAEAAIADgBQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgBADQgEAHgKAAQgMAAgBgNgAAAADIgLAGQgHAEAAAIQAAAFADADQADACAFAAQAJAAAFgJQADgGAAgPIAAgCIgBAAIgBAAIgIAEg");
	this.shape_55.setTransform(-427.95,166.825);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#6B3927").s().p("AgoA5QgHAAAAgEQABgCADgBQAEgCABgEQACgFAAgMIAAg8QAAgIgBgCQAAgDgDgCIgEgCQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAgDAGAAIAlAAIAUABQAKABAGAFQAJAHAAAMQAAAHgDAFQgHALgPADIgBAAIABABQAOABAIAHQAIAHABANQAAAJgGAHQgMAQgjAAgAgMACQgBAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAABIAAAZQAAANABACQACACAJAAQAaAAAAgXQAAgVgagBgAgOgrIAAAhQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIAIAAQAYAAAAgUIAAAAQAAgRgXAAIgJAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAABg");
	this.shape_56.setTransform(-437.6,165.3);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#6B3927").s().p("AgTAmQgKgGgFgMQgDgJAAgIQAAgMAGgLQAGgLALgHQAJgEAJAAQANAAAKAIQALAJAAAOQAAAGgCACQgDADgIAAIgoAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAABQgBAKAGAIQAHAKANAAQAIAAAIgEIAIgEQABAAABAAQAAAAABABQAAAAAAABQABABAAAAQAAAGgLAHQgLAGgNAAQgLABgKgGgAgNgXQgDAGAAAFQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAVAAQAMAAAAgIQAAgGgEgEQgFgEgHAAQgIgBgHAKg");
	this.shape_57.setTransform(-314.9,147.15);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#6B3927").s().p("AAMA8QgGAAABgEQgBgCAEgCQAEgCACgEQACgEgBgNIAAgWQAAgQgPAAQgGAAgFAEQgEAFgCAGQgBAIAAAPQAAANACAEQACAEADACQADACAAACQAAAEgEAAIgfAAQgFAAAAgEQAAgCADgCQAFgDABgDQABgEABgNIAAg5QgBgKgBgCQgBgDgFgCQgEgBAAgCQAAgDAFgBIASgGIAEgBQAEAAAAAFIAAArIAAABIABAAQAJgPAQAAQAPAAAHALQAFAIAAANIAAAWQAAANACAEQACAEAEACQADACAAACQAAAEgFAAg");
	this.shape_58.setTransform(-324.85,145.375);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#6B3927").s().p("AgOApQgEgHAAgNIABgmQAAgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgKAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAQAMgCADgHIACgLQABgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAPIABAEQAAAAAAAAQAAAAABAAQAAABABAAQAAAAABAAIASgCQAFAAAAAEIAAADQgCAGgGAAIgRgBQgBAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAAASQAAAWACAHQADAIAIAAQAEAAAEgDIAFgDQABAAAAAAQABABAAAAQABAAAAABQAAABAAAAIgCAFQgDAFgGAEQgHADgIAAQgMAAgHgLg");
	this.shape_59.setTransform(-333.1,146.325);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#6B3927").s().p("AAMArQgGAAABgEQAAgCADgCQAEgCACgEQACgEAAgNIAAgVQAAgIgFgFQgDgEgIAAQgGAAgEAEQgFAFgCAHQgBAIAAAOQAAANACAEQABAEAFACQACACAAACQAAAEgEAAIgfAAQgGAAABgEQAAgCADgCQAEgDACgDQACgEAAgNIAAgXQgBgJgBgDQgBgDgFgBQgEgCAAgCQAAgDAFgBQAKgCAGgDIAGgCQAEAAAAAFIAAAJIAAABIABgBQAKgOAPAAQAPAAAHALQAFAIAAAOIAAAVQAAANACAEQACAEAEACQADACAAACQAAAEgFAAg");
	this.shape_60.setTransform(-344.4,147.075);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#6B3927").s().p("AgeAgQgLgMAAgTQAAgSAMgMQAMgNARgBQATAAAMANQALAMAAASQAAASgMANQgMANgSAAQgSAAgMgMgAgPgZQgFAHAAANQAAAPAFALQAHAMAKAAQAJAAAFgIQAFgIAAgMQAAgPgFgKQgHgNgKAAQgIAAgGAIg");
	this.shape_61.setTransform(-353.825,147.175);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#6B3927").s().p("AAPA7QgIgKAAgQQAAgPAKgLQAJgIAPgBQAOABAKAIQAJAKAAAQQAAARgKAKQgKAKgNAAQgQAAgKgLgAAeAhQAAALADAHQADAHAFAAQAKAAgBgZQABgYgKAAQgLAAAAAYgAgwBEIBRiHIAQAAIhSCHgAhBgHQgIgLAAgOQAAgQAJgKQALgLAOAAQAOAAAKALQAJAKAAAQQAAAQgKAKQgKAJgNAAQgQAAgKgKgAgyggQAAAKADAHQADAHAFAAQAKAAAAgYQAAgZgKAAQgLAAAAAZg");
	this.shape_62.setTransform(-371.35,144.55);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#6B3927").s().p("AgaBGQgLgDgEgHQgEgGAAgRQAAgKAJABQAEgBADAGIAGALQAKAPAPAAQAJAAAHgFQAHgHAAgJQAAgNgNgIQgPgMgegBIgGAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgCIAMg9QABgBAAgBQABAAAAAAQABgBAAAAQABAAABAAIAbAAQAOAAAFgCQAEgBADgCQAEgEADAAQAFAAgBAEIgBALIgCALQgBAFgCACQgDADgLAAIglAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAABIgDALIAAAAQAAABABAAQAAABAAAAQAAAAABAAQAAAAAAAAQAhABARAPQAQAMAAAUQAAAUgPANQgPANgVABQgLgBgKgDg");
	this.shape_63.setTransform(-385,144.2);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#6B3927").s().p("AADBFQgEAAAAgEIAAhfQAAgKgBgCQgBgEgHAAIgNABQgFAAgBgJQABgEAEgBIARgCIAQgEIAOgDQAHAAAAAHIAAB+QgBAEgEAAg");
	this.shape_64.setTransform(-397.8,144.45);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#6B3927").s().p("AggAnQgOgOAAgWQAAgVAPgQQAOgRAVAAQARAAAMALQAOALAAARQAAAIgEADQgDABgJAAIgtAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAACQABAIAEAGQAJAOASAAQAJAAAHgDIAJgEQAEAAAAAEQAAAGgMAIQgNAJgSAAQgUAAgOgNgAgJgfQgGAFgBAJIAAACQAAABAAAAQAAAAAAAAQABABAAAAQAAAAABAAIAVAAQAMAAAAgIQAAgGgEgFQgFgEgHAAQgHAAgFAFg");
	this.shape_65.setTransform(-411.575,146.375);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#6B3927").s().p("AgKAyQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIgchFQgGgMgDgDIgGgEQgDgBAAgDQgBgFAIAAIApAAQAHAAAAAEQAAADgFADQgFACABAFIABAGIARAsIABACIABgCIANgcQAEgLAAgHQABgHgGgDQgEgEAAgCQAAgFAHAAIAfAAQAHAAABAFQgBACgCACQgHAFgFAHIgKAUIgaA4QAAAAgBABQAAAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_66.setTransform(-422.3,146.475);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#6B3927").s().p("AAMAmIgBgCIgBABQgLAPgTAAQgMAAgJgGQgJgHAAgMQAAgPANgJQAKgEAWgIQANgGAAgKQAAgLgLAAQgGAAgGAEQgEADgHAIQgEAHgEAAQgFAAgCgDQgBgDAAgGQAAgKADgFQAEgFANgDQAJgCAKAAQAQAAAMAIQAOAJAAAQIgBAjQAAAKABADQABAEAHABQAEAAAAAEQAAAEgEAEQgHAFgKAAQgPAAgDgOgAAGAAQgMAFgGAFQgIAGAAAHQAAAFADADQAEADAFAAQAJAAAEgJQADgFAAgSIAAgBIgBgBg");
	this.shape_67.setTransform(-433.45,146.375);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#6B3927").s().p("AgeBCQgNgEgFgHQgDgGAAgLIgBgHQAAgJAIAAQADAAAEAFIAKAMQAOAPAOAAQAKAAAGgFQAGgGAAgHQAAgKgLgHIgXgKQgRgGgHgGQgLgJAAgPQAAgRAOgNQAPgMAWAAQAZAAAMALQAEAEAAAOQAAAOgHAAQgEgBgDgEIgIgJQgMgNgMAAQgGAAgFADQgGAFAAAHQAAAJALAGIAXAKQARAGAIAHQALAJAAARQAAATgQANQgQAMgYAAQgPAAgMgEg");
	this.shape_68.setTransform(-445.775,144.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},21).to({state:[{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},18).to({state:[]},1).to({state:[{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},6).to({state:[{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},171).to({state:[]},1).wait(28));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-454.9,134.7,150,118);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.PBB_logo1();
	this.instance.setTransform(-36,-25,0.5328,0.533);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36,-25,130,103.4);


(lib.IMG1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM1();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,160,600);


(lib.IM2_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM2();
	this.instance.setTransform(-80,-158.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-158.5,160,600);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAXBGQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgVhVIAAgCIAAACIgTBVQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgXAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgkiHIAAAAQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAZAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIATBQIAAABIABgBIAShQQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIAXAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAUBQIAAABIABgBIAShQQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAIAYAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIghCHQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(123.4792,22.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbBCQgMgHgGgLQgHgMAAgPIAAgqQAAgOAHgMQAGgLAMgHQAMgGAPAAQAQAAALAGQAMAHAHALQAHAMAAAOIAAAqQAAAPgHAMQgHALgMAHQgLAGgQAAQgPAAgMgGgAgRgoQgHAIAAALIAAArQAAAMAHAHQAHAHAKAAQALAAAHgHQAGgHAAgMIAAgrQAAgLgGgIQgHgHgLAAQgKAAgHAHg");
	this.shape_1.setTransform(106.525,22.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAdBGQAAAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIg0hUIAAAAIAAAAIAABTIgBACIgBABIgYAAIgBgBIgBgCIAAiGIABgBIABgBIAXAAQAAAAAAAAQABAAAAAAQABABAAAAQAAAAABAAIAyBVIABABIABgCIgBhTIABgBIABgBIAYAAIACABIABABIAACGIgBACIgCABg");
	this.shape_2.setTransform(91.65,22.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwBGIgBgBIgBgCIAAiGIABgBIABgBIA3AAQANAAALAFQAJAFAGAKQAFALABAMQgBANgFAJQgGAJgKAGQgLAEgMAAIgcAAIgBABIAAAzIgBACIgCABgAgWgsIAAAlIABABIAZAAQAIAAAGgGQAFgEABgJQgBgJgFgGQgGgFgIAAIgZAAIgBABg");
	this.shape_3.setTransform(71.35,22.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbBCQgMgHgGgLQgHgMAAgPIAAgqQAAgOAHgMQAGgLAMgHQAMgGAPAAQAQAAALAGQAMAHAHALQAHAMAAAOIAAAqQAAAPgHAMQgHALgMAHQgLAGgQAAQgPAAgMgGgAgRgoQgHAIAAALIAAArQAAAMAHAHQAHAHAKAAQALAAAHgHQAGgHAAgMIAAgrQAAgLgGgIQgHgHgLAAQgKAAgHAHg");
	this.shape_4.setTransform(56.925,22.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAaBGIgCgBIgBgCIAAg2IgBgBIgrAAIgBABIAAA2IgBACIgBABIgYAAIgCgBIAAgCIAAiGIAAgBIACgBIAYAAIABABIABABIAAA2IABABIArAAIABgBIAAg2IABgBIACgBIAXAAIABABIABABIAACGIgBACIgBABg");
	this.shape_5.setTransform(42.5,22.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgaBCQgMgEgHgKQgGgKAAgMIAAgFIABgCIABAAIAXAAIACAAIABACIAAAEQAAAHAHAGQAHAFAMABQALgBAFgEQAFgEAAgHQAAgFgDgEQgDgDgGgCIgQgHQgOgFgJgEQgJgEgHgJQgGgIAAgMQAAgMAGgJQAGgJALgFQALgFAPABQAOgBAMAGQAMAFAGAKQAHAJAAANIAAAEIgBABIgBABIgXAAIgCgBIgBgBIAAgCQAAgJgHgFQgGgGgLgBQgKAAgFAFQgFADAAAIQAAAEADAEQADAEAGACIASAHIAWAJQAIAEAHAIQAGAHAAANQAAATgOAKQgNAMgYAAQgPgBgMgFg");
	this.shape_6.setTransform(28.175,22.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer_1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#DD002A").s().p("Aq5CyQggAAAAgdIAAkpQAAgdAgAAIVzAAQAgAAAAAdIAAEpQAAAdggAAg");
	this.shape_7.setTransform(78.05,21.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(5.1,3.8,146,35.6);


(lib.circle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00348F").s().p("AyKSLQninhAAqqQAAqoHinjQHhnhKpAAQKpAAHiHhQHiHjAAKoQAAKqniHhQniHiqpAAQqpAAnhnig");
	this.shape.setTransform(0.0025,0.0252,1.6568,1.1029);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-272.5,-181.4,545.1,362.9);


// stage content:
(lib.WFSB_215325_MM_160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [228];
	// timeline functions:
	this.frame_228 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(228).call(this.frame_228).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgMfgu3IY/AAMAAABdvI4/AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(229));

	// CTA
	this.instance = new lib.CTA();
	this.instance.setTransform(280.45,512.7,0.9,0.9,0,0,0,89.5,21.3);
	this.instance.alpha = 0;
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.CTA(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(150).to({_off:false},0).to({x:90.3,alpha:1},13).wait(66));

	// T2
	this.instance_1 = new lib.T2("synched",89);
	this.instance_1.setTransform(462.25,288.65);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(134).to({_off:false},0).to({alpha:1,startPosition:117},14,cjs.Ease.get(1)).wait(81));

	// T1
	this.instance_2 = new lib.T1("synched",21);
	this.instance_2.setTransform(460.25,373);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(21).to({_off:false},0).to({y:283,alpha:1,startPosition:46},19,cjs.Ease.get(1)).wait(80).to({startPosition:95},0).to({alpha:0,startPosition:123},14,cjs.Ease.get(1)).wait(95));

	// Logo
	this.instance_3 = new lib.Symbol1("synched",0);
	this.instance_3.setTransform(-50.5,320.55);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:49.5,alpha:1},22,cjs.Ease.get(1)).wait(207));

	// Layer_11 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_21 = new cjs.Graphics().p("A+HUDQseoTAArwQAArvMeoTQMfoTRoAAQRpAAMeITQMfITAALvQAALwsfITQseITxpAAQxoAAsfoTg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(21).to({graphics:mask_graphics_21,x:136.4525,y:101.6252}).wait(208));

	// IM2_jpg
	this.instance_4 = new lib.IM2_jpg("synched",0);
	this.instance_4.setTransform(80,158.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(120).to({_off:false},0).to({alpha:1},28).wait(81));

	// IM1_png
	this.instance_5 = new lib.IMG1("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(21).to({_off:false},0).to({alpha:1},19).wait(189));

	// Layer_1
	this.instance_6 = new lib.circle("synched",0);
	this.instance_6.setTransform(153.95,109.6);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(21).to({_off:false},0).to({alpha:1},19).wait(189));

	// BG_png
	this.instance_7 = new lib.BG();

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(229));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-38.6,228.2,465.1,397.50000000000006);
// library properties:
lib.properties = {
	id: '9FDEB53A9669492982F620CA953230C7',
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.png", id:"BG"},
		{src:"IM1.png", id:"IM1"},
		{src:"IM2.jpg", id:"IM2"},
		{src:"PBB_logo1.png", id:"PBB_logo1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['9FDEB53A9669492982F620CA953230C7'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;