(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.IMG1 = function() {
	this.initialize(img.IMG1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.LOGO = function() {
	this.initialize(img.LOGO);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.LOGO_R = function() {
	this.initialize(img.LOGO_R);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.t4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDAIIgCgCIgCgCIgBgEIABgDIACgCIACgDIADAAIADAAIADADIACACIABADIgBAEIgCACIgDACIgDABg");
	this.shape.setTransform(87.05,12.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_1.setTransform(82.625,9.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_2.setTransform(76.975,9.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_3.setTransform(70.775,9.525);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIAgQgGgCgEgFQgEgEgCgGQgCgHAAgIQAAgGACgHQACgGAEgEQAEgFAGgCQAGgDAGAAQAIAAAFACQAGADAEAEIgEAFIgBABIgCABIgCgBIgDgCIgEgCIgGAAQgEAAgDABQgDACgDADIgDAHQgBAFAAAEQAAAGABAEQABAEADADIAFAFQADABAEAAIAGgBIAEgCIADgCIADgBQAAAAABAAQAAAAABABQAAAAAAAAQAAAAABABIADAFIgFAFIgGADIgHACIgHAAQgFAAgFgCg");
	this.shape_4.setTransform(64.325,9.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_5.setTransform(57.425,9.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSAiIAAhCIAIAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAAAIABADIABAJQADgHAEgDQAEgEAGAAIAEABIADABIAAALIgBABIgCABIgDgBIgDAAIgGABIgEACIgCAEIgCAGIAAAog");
	this.shape_6.setTransform(51.725,9.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdAtIAAhYIAJAAQAAAAABAAQAAABABAAQAAAAABABQAAAAAAABIABAHQAFgFAEgDQAGgDAGAAQAGAAAEACQAFADADAEQADAEACAHQACAGAAAIQAAAHgCAGQgCAGgEAFQgEAEgFADQgFADgHAAQgFAAgEgCIgHgFIAAAcgAgIgeIgHAGIAAAeQADAEADABQAEACAEAAQAHAAAFgGQAEgGABgLIgBgKQgCgFgCgCQgCgDgCgBQgDgCgEAAQgEAAgEADg");
	this.shape_7.setTransform(45.5,10.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_8.setTransform(34.875,9.475);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_9.setTransform(27.525,9.525);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgCgdIgEgCIgCgDIgBgEIABgDIACgDIAEgCIACgBIAEABIADACIABADIABADIgBAEIgBADIgDACIgEABIgCgBg");
	this.shape_10.setTransform(22.2,8.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAgmIgHAAIgCAAIgBgCIAAgGIALgBIADgTIABgCIACgBIAGAAIAAAWIASAAIAAAJIgSAAIAAAlQAAAEACACQAAAAABAAQAAABABAAQAAAAABAAQABAAABAAIACAAIACgBIACAAIABgBIACABIAEAHQgDADgFABIgJACQgHAAgEgEg");
	this.shape_11.setTransform(18.3,8.55);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgdAtIAAhYIAJAAQAAAAABAAQAAABABAAQAAAAABABQAAAAAAABIABAHQAFgFAEgDQAGgDAGAAQAGAAAEACQAFADADAEQADAEACAHQACAGAAAIQAAAHgCAGQgCAGgEAFQgDAEgGADQgFADgHAAQgEAAgFgCIgHgFIAAAcgAgIgeIgHAGIAAAeQADAEADABQAEACAEAAQAIAAAEgGQAEgGABgLIgBgKQgBgFgCgCQgDgDgCgBQgDgCgEAAQgEAAgEADg");
	this.shape_12.setTransform(12.4,10.575);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_13.setTransform(4.875,9.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgPAuQgEgCgDgEQgDgEgCgHQgCgGAAgJQAAgHACgGQACgFAEgFQADgFAGgCQAFgDAHAAQAEAAAEACQAEABAEAEIAAgkIAOAAIAABgIgJAAQAAAAgBgBQgBAAAAAAQgBAAAAgBQAAAAgBgBIAAgHQgEAEgGAEQgFADgGAAQgGgBgFgCgAgKgCQgFAFAAALIABALQACAEACADIAEAEIAGABQAFAAADgCIAIgGIAAgfQgDgDgEgBQgDgCgEAAQgHAAgFAGg");
	this.shape_14.setTransform(-2.65,8.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgPAhQgDgBgDgCQgCgCgCgEQgBgDAAgFQAAgDACgEQACgEAFgDQAFgCAHgBQAHgCALAAIAAgFQAAgHgDgDQgDgEgFAAIgHABIgEACIgEACIgDABIgCAAIgCgCIgDgFQAMgKAOAAQAGAAAEACQAFABADAEQADADACAFQABAEAAAGIAAApIgGAAIgDAAIgCgDIgCgFIgEAEIgGADIgEACIgHAAIgIgBgAABAFIgIADIgEADQAAABgBAAQAAABAAAAQAAABAAABQgBAAAAABIABAEIADADIACABIAEABQAFAAAEgCIAHgGIAAgNIgMABg");
	this.shape_15.setTransform(-9.6,9.525);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_16.setTransform(-19.275,9.525);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAOAwIAAgqQAAgGgDgEQgDgDgGAAQgEAAgEACQgEACgDADIAAAwIgOAAIAAhfIAOAAIAAAmQAEgFAFgCQAEgDAGABQAGAAAEACIAHAFIAEAHQABAEAAAGIAAAqg");
	this.shape_17.setTransform(-26.325,8.05);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAgmIgHAAIgCAAIgBgCIAAgGIAKgBIAEgTIABgCIACgBIAGAAIAAAWIATAAIAAAJIgTAAIAAAlQAAAEACACQAAAAABAAQAAABABAAQAAAAABAAQABAAABAAIADAAIABgBIACAAIABgBIACABIAEAHQgDADgFABIgJACQgHAAgEgEg");
	this.shape_18.setTransform(-32.3,8.55);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgHAoQgEgFAAgJIAAgmIgHAAIgCAAIgBgCIAAgGIAKgBIAEgTIABgCIACgBIAGAAIAAAWIATAAIAAAJIgTAAIAAAlQAAAEACACQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAIAEAAIACgBIABAAIABgBIACABIAEAHQgDADgEABIgJACQgIAAgFgEg");
	this.shape_19.setTransform(-40.25,8.55);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgSAiIAAhCIAIAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAAAIABADIABAJQADgHAEgDQAEgEAGAAIAEABIADABIAAALIgBABIgCABIgDgBIgDAAIgGABIgEACIgCAEIgCAGIAAAog");
	this.shape_20.setTransform(-44.675,9.475);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgPAhQgDgBgCgCQgDgCgCgEQgBgDAAgFQAAgDACgEQACgEAFgDQAFgCAHgBQAHgCALAAIAAgFQAAgHgDgDQgCgEgHAAIgGABIgEACIgEACIgDABIgCAAIgCgCIgDgFQAMgKAOAAQAGAAAEACQAFABADAEQADADACAFQABAEAAAGIAAApIgGAAIgDAAIgCgDIgBgFIgGAEIgFADIgEACIgHAAIgIgBgAABAFIgIADIgEADQAAABgBAAQAAABAAAAQAAABAAABQgBAAAAABIACAEIACADIACABIAFABQAEAAAEgCIAHgGIAAgNIgMABg");
	this.shape_21.setTransform(-50.9,9.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAgmIgHAAIgCAAIgBgCIAAgGIAKgBIAEgTIABgCIACgBIAGAAIAAAWIATAAIAAAJIgTAAIAAAlQAAAEACACQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAIAEAAIABgBIACAAIABgBIACABIAEAHQgDADgFABIgJACQgHAAgEgEg");
	this.shape_22.setTransform(-56.25,8.55);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_23.setTransform(-61.575,9.525);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgPAuQgEgCgDgEQgEgEgBgHQgCgGAAgJQAAgHACgGQACgFADgFQAFgFAEgCQAGgDAHAAQAEAAAFACQAEABADAEIAAgkIAOAAIAABgIgJAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgBgHQgFAEgFAEQgFADgGAAQgGgBgFgCgAgKgCQgEAFgBALIABALQABAEACADIAFAEIAGABQAFAAAEgCIAHgGIAAgfQgDgDgDgBQgEgCgEAAQgHAAgFAGg");
	this.shape_24.setTransform(-71.35,8.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_25.setTransform(-78.425,9.475);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgPAhQgDgBgCgCQgDgCgCgEQgBgDAAgFQAAgDACgEQACgEAFgDQAFgCAHgBQAHgCALAAIAAgFQAAgHgDgDQgCgEgHAAIgGABIgEACIgEACIgDABIgCAAIgCgCIgDgFQAMgKAOAAQAGAAAEACQAFABADAEQADADACAFQABAEAAAGIAAApIgGAAIgDAAIgCgDIgBgFIgFAEIgGADIgEACIgHAAIgIgBgAABAFIgIADIgEADQAAABgBAAQAAABAAAAQAAABAAABQgBAAAAABIACAEIACADIACABIAFABQAEAAAEgCIAHgGIAAgNIgMABg");
	this.shape_26.setTransform(-85.55,9.525);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgGAPIgBgBIAAgBIABgCIACgBIACgEIACgDIAAgDIAAAAIgDgBIgCgBIgCgDIgBgEIABgDIACgCIACgCIADAAIAEAAIACADIACACIABAFIgBAGIgDAFIgEAHIgEAFg");
	this.shape_27.setTransform(119.7,-2.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_28.setTransform(115.325,-6.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgdAtIAAhYIAIAAQABAAABAAQAAABABAAQAAAAABABQAAABAAAAIACAHQAEgFAFgDQAFgDAGAAQAGAAAEACQAFADADAEQADAEACAHQACAGAAAIQAAAHgCAGQgCAGgEAFQgEAEgFADQgFADgGAAQgGAAgDgCIgIgFIAAAcgAgIgeIgHAGIAAAeQADAEAEABQADACAEAAQAIAAAEgGQAFgGgBgLIgBgKQgBgFgBgCQgCgDgEgBQgCgCgDAAQgFAAgEADg");
	this.shape_29.setTransform(109.1,-5.025);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgPAgQgEgCgDgDQgDgDgBgFQgBgFAAgFIAAgqIAOAAIAAAqQAAAGADAEQADAEAGAAQAEAAAEgCQAEgCADgEIAAgwIAOAAIAABCIgIAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgBgGIgEAEIgFADIgGACIgFABQgGAAgEgCg");
	this.shape_30.setTransform(101.625,-6.025);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgdAtIAAhYIAJAAQAAAAABAAQAAABABAAQAAAAABABQAAABAAAAIABAHQAFgFAEgDQAGgDAGAAQAGAAAEACQAFADADAEQADAEACAHQACAGAAAIQAAAHgCAGQgCAGgEAFQgEAEgFADQgFADgHAAQgFAAgEgCIgHgFIAAAcgAgIgeIgHAGIAAAeQADAEADABQAEACAEAAQAHAAAFgGQAEgGABgLIgBgKQgCgFgCgCQgCgDgCgBQgDgCgEAAQgEAAgEADg");
	this.shape_31.setTransform(94.55,-5.025);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_32.setTransform(84.075,-6.075);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAOAwIAAgqQAAgGgDgEQgDgDgGAAQgEAAgEACQgEACgDADIAAAwIgOAAIAAhfIAOAAIAAAlQAEgEAFgCQAEgDAGAAQAGABAEACIAHAEIAEAIQABAEAAAGIAAAqg");
	this.shape_33.setTransform(77.025,-7.55);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgHAoQgEgFAAgJIAAglIgHAAIgCgBIgBgDIAAgFIALgBIADgTIABgDIACAAIAGAAIAAAWIASAAIAAAKIgSAAIAAAlQAAADACACQAAAAABAAQAAABABAAQAAAAABAAQABABABAAIACAAIACgBIACgBIABgBIACACIAEAGQgDADgEACIgJABQgIAAgFgEg");
	this.shape_34.setTransform(71.05,-7.05);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAglIgHAAIgCgBIgBgDIAAgFIAKgBIAEgTIABgDIACAAIAGAAIAAAWIATAAIAAAKIgTAAIAAAlQAAADACACQAAAAABAAQAAABABAAQAAAAABAAQABABABAAIADAAIABgBIACgBIABgBIACACIAEAGQgDADgFACIgJABQgHAAgEgEg");
	this.shape_35.setTransform(63.1,-7.05);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_36.setTransform(57.225,-6.075);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_37.setTransform(50.325,-6.075);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAgAiIAAgpQAAgHgDgEQgDgEgGAAIgFABIgEADIgDAEIgBAHIAAApIgNAAIAAgpQAAgIgDgDQgDgEgFAAQgEAAgEACIgGAGIAAAwIgOAAIAAhCIAJAAQAAAAABAAQABABAAAAQABAAAAABQAAABAAAAIABAGIAEgEIAEgDIAFgCIAGgBIAFABIAFADIADAEIACAFIAEgFIAFgFIAGgCIAGgBQAGAAAEACQAEACADADQADADABAFQACAFAAAGIAAApg");
	this.shape_38.setTransform(41.525,-6.125);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgGAPIgBgBIAAgBIABgCIACgBIACgEIACgDIAAgDIAAAAIgCgBIgEgBIgBgDIgBgEIABgDIABgCIAEgCIACAAIADAAIAEADIABACIABAFIgBAGIgCAFIgFAHIgFAFg");
	this.shape_39.setTransform(31.45,-2.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_40.setTransform(27.075,-6.075);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAgAiIAAgpQAAgHgDgEQgDgEgGAAIgFABIgEADIgDAEIgBAHIAAApIgNAAIAAgpQAAgIgDgDQgDgEgFAAQgEAAgEACIgGAGIAAAwIgOAAIAAhCIAJAAQAAAAABAAQABABAAAAQABAAAAABQAAABAAAAIABAGIAEgEIAEgDIAFgCIAGgBIAFABIAFADIADAEIACAFIAEgFIAFgFIAGgCIAGgBQAGAAAEACQAEACADADQADADABAFQACAFAAAGIAAApg");
	this.shape_41.setTransform(18.975,-6.125);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_42.setTransform(10.125,-6.075);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAglIgHAAIgCgBIgBgDIAAgFIALgBIADgTIABgDIACAAIAGAAIAAAWIASAAIAAAKIgSAAIAAAlQAAADACACQAAAAABAAQAAABABAAQAAAAABAAQABABABAAIACAAIACgBIACgBIABgBIACACIAEAGQgDADgFACIgJABQgHAAgEgEg");
	this.shape_43.setTransform(4.35,-7.05);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgDgdIgDgCIgBgDIgBgEIABgDIABgDIADgCIADgBIADABIAEACIACADIABADIgBAEIgCADIgEACIgDABIgDgBg");
	this.shape_44.setTransform(0.3,-7.525);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_45.setTransform(-8.075,-6.125);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_46.setTransform(-15.425,-6.075);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgCgdIgEgCIgCgDIAAgEIAAgDIACgDIAEgCIACgBIADABIAEACIACADIAAADIAAAEIgCADIgEACIgDABIgCgBg");
	this.shape_47.setTransform(-20.75,-7.525);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAglIgHAAIgCgBIgBgDIAAgFIAKgBIAEgTIABgDIACAAIAGAAIAAAWIATAAIAAAKIgTAAIAAAlQAAADACACQAAAAABAAQAAABABAAQAAAAABAAQABABABAAIADAAIABgBIACgBIABgBIACACIAEAGQgDADgFACIgJABQgHAAgEgEg");
	this.shape_48.setTransform(-24.65,-7.05);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgIAgQgGgCgEgFQgEgEgCgGQgCgHAAgIQAAgGACgHQACgGAEgEQAEgFAGgCQAGgDAGAAQAIAAAFACQAGADAEAEIgEAFIgBABIgCABIgCgBIgDgCIgEgCIgGAAQgEAAgDABQgDACgDADIgDAHQgBAFAAAEQAAAGABAEQABAEADADIAFAFQADABAEAAIAGgBIAEgCIADgCIADgBQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABIADAFIgFAFIgGADIgHACIgHAAQgFAAgFgCg");
	this.shape_49.setTransform(-30.075,-6.075);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgPAgQgEgCgDgDQgDgDgBgFQgBgFAAgFIAAgqIAOAAIAAAqQAAAGADAEQADAEAGAAQAEAAAEgCQAEgCADgEIAAgwIAOAAIAABCIgIAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgBgGIgEAEIgFADIgGACIgFABQgGAAgEgCg");
	this.shape_50.setTransform(-36.925,-6.025);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgOAhQgEgBgDgCQgCgCgBgEQgCgDAAgFQAAgDADgEQACgEAEgDQAEgCAJgBQAGgCALAAIAAgFQAAgHgCgDQgDgEgGAAIgGABIgFACIgEACIgDABIgDAAIgBgCIgDgFQAMgKAOAAQAGAAAEACQAFABADAEQADADABAFQACAEAAAGIAAApIgGAAIgDAAIgCgDIgCgFIgEAEIgGADIgEACIgHAAIgHgBgAABAFIgHADIgFADQAAABgBAAQAAABAAAAQAAABAAABQgBAAAAABIABAEIACADIAEABIADABQAFAAAEgCIAHgGIAAgNIgMABg");
	this.shape_51.setTransform(-44,-6.075);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAglIgHAAIgCgBIgBgDIAAgFIAKgBIAEgTIABgDIACAAIAGAAIAAAWIATAAIAAAKIgTAAIAAAlQAAADACACQAAAAABAAQAAABABAAQAAAAABAAQABABABAAIADAAIABgBIACgBIABgBIACACIAEAGQgDADgFACIgJABQgHAAgEgEg");
	this.shape_52.setTransform(-52.55,-7.05);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_53.setTransform(-58.575,-6.125);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_54.setTransform(-65.675,-6.075);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgGAwIAAhfIANAAIAABfg");
	this.shape_55.setTransform(-70.725,-7.55);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgCgdIgDgCIgDgDIgBgEIABgDIADgDIADgCIACgBIAEABIACACIACADIABADIgBAEIgCADIgCACIgEABIgCgBg");
	this.shape_56.setTransform(-73.9,-7.525);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_57.setTransform(-78.375,-6.075);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_58.setTransform(-87.925,-6.125);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_59.setTransform(-95.275,-6.075);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgPAuQgEgCgDgEQgEgFgBgGQgCgHAAgHQAAgIACgGQACgGADgEQAFgFAEgDQAGgCAHAAQAEAAAFACQAEACADADIAAgjIAOAAIAABeIgJAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgBgIQgFAGgFACQgFADgGABQgGAAgFgDgAgKgCQgEAFgBAMIABAKQABAFACACIAFAEIAGABQAFAAAEgCIAHgHIAAgdQgDgEgDgCQgEgBgEAAQgHAAgFAGg");
	this.shape_60.setTransform(-106,-7.5);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgCgdIgEgCIgCgDIgBgEIABgDIACgDIAEgCIACgBIADABIAEACIABADIABADIgBAEIgBADIgEACIgDABIgCgBg");
	this.shape_61.setTransform(-111.1,-7.525);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AghAvIAAhdIAfAAQAIAAAHACQAGACAEADQAEADACAFQACAEAAAGIgBAGIgDAGIgFAFQgDACgFABQAUAEAAARQAAAGgCAFQgCAFgFADQgEAEgHACQgFACgJAAgAgSAjIASAAIAJgBIAFgEQADgCABgDIABgGQAAgGgFgEQgEgEgKAAIgSAAgAgSgFIAQAAQAJAAAEgDQAFgEAAgHQAAgIgEgEQgFgDgJAAIgQAAg");
	this.shape_62.setTransform(-116.65,-7.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125.2,-17.6,250.5,35.2);


(lib.t3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAoAwIAAgxQAAgGgDgDQgDgDgEAAQgFAAgDADQgDADAAAGIAAAxIgmAAIAAgxQAAgGgCgDQgDgDgFAAQgEAAgDADQgDADAAAGIAAAxIgnAAIAAhdIAnAAIAAANQALgPARAAQASAAAIAQQAOgQARAAQAPAAAJAJQAJAKAAAQIAAA8g");
	this.shape.setTransform(113.325,0.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag0A9IAAh3IAmAAIAAALQAHgGAEgDQAGgEAKAAQARAAALANQAMAOAAAVIAAABQAAAUgMAOQgLANgRAAQgPAAgMgMIAAAlgAgKgXQgEAEgBAIIAAAAQABAGAEAFQAEAFAGAAQAGAAAFgFQAFgEAAgHIAAAAQAAgIgFgEQgFgGgGAAQgGAAgEAGg");
	this.shape_1.setTransform(99.3,1.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgFA8IAAhUIgTAEIgIgdIAjgKIAeAAIAAB3g");
	this.shape_2.setTransform(89.375,-0.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgdAQIAAgfIA7AAIAAAfg");
	this.shape_3.setTransform(78.5,-0.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAoAwIAAgxQAAgGgDgDQgDgDgEAAQgFAAgDADQgDADAAAGIAAAxIgmAAIAAgxQAAgGgCgDQgDgDgFAAQgEAAgDADQgDADAAAGIAAAxIgnAAIAAhdIAnAAIAAANQALgPARAAQASAAAIAQQAOgQARAAQAPAAAJAJQAJAKAAAQIAAA8g");
	this.shape_4.setTransform(62.425,0.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgmApQgJgIAAgNQAAgOAKgHQAJgHARAAQANAAAHADIAAgBQAAgOgQAAQgMAAgOAFIgGgZQARgHAWAAQAaAAAMAMQAKAKAAATIAAA0IgnAAIAAgJQgKALgQAAQgNAAgIgHgAgHAJQgDADAAAFIAAAAQAAAEACADQADACAEAAQAEAAAEgEQADgEAAgGIAAgEQgEgCgFAAQgFAAgDADg");
	this.shape_5.setTransform(48.65,0.475);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgFA8IAAhUIgTAEIgIgdIAjgKIAeAAIAAB3g");
	this.shape_6.setTransform(39.625,-0.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgFA8IAAhUIgTAEIgIgdIAjgKIAeAAIAAB3g");
	this.shape_7.setTransform(32.475,-0.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUAUQASgCAAgNIgQAAIAAgmIAnAAIAAAfQAAATgLAJQgJAHgRABg");
	this.shape_8.setTransform(22.6,4.525);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjAwQgPgPAAgeQAAgbAOgTQAQgSAbAAQAYAAASANIgRAaQgMgJgMABQgQAAgDAXQALgLAPAAQAOAAALAKQAMAJAAARIAAAAQgBAUgPANQgNALgVAAQgXAAgOgOgAgIAKQgDAEAAAFIAAABQAAAFADAEQAEAFAEAAQAHAAADgFQADgDABgGQAAgFgFgFQgDgDgGAAQgEAAgEADg");
	this.shape_9.setTransform(14.65,-0.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgFA8IAAhUIgTAEIgIgdIAjgKIAeAAIAAB3g");
	this.shape_10.setTransform(5.025,-0.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag0AzIALgbQALAHAGAAQADAAAEgCIglhYIAoAAIAPAxIAPgxIAnAAIggBVQgHATgIAIQgJAHgPAAQgSAAgSgJg");
	this.shape_11.setTransform(-7.9,1.825);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgmApQgJgIAAgNQAAgOAKgHQAJgHARAAQANAAAHADIAAgBQABgOgRAAQgMAAgNAFIgHgZQASgHAVAAQAaAAAMAMQAKAKAAATIAAA0IgnAAIAAgJQgJALgRAAQgNAAgIgHgAgHAJQgDADAAAFIAAAAQAAAEACADQADACAEAAQAEAAADgEQAEgEAAgGIAAgEQgEgCgFAAQgFAAgDADg");
	this.shape_12.setTransform(-18.2,0.475);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAbA8IAAg8IgbArIAAAAIgbgrIAAA8IgnAAIAAh3IApAAIAZAqIAagqIApAAIAAB3g");
	this.shape_13.setTransform(-30.55,-0.85);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag0AzIALgbQALAHAGAAQAEAAADgCIglhYIAoAAIAPAxIAPgxIAnAAIggBVQgHATgIAIQgJAHgPAAQgTAAgRgJg");
	this.shape_14.setTransform(-47.75,1.825);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgnApQgIgIAAgNQAAgOAKgHQAJgHAQAAQANAAAJADIAAgBQAAgOgQAAQgNAAgNAFIgHgZQARgHAWAAQAaAAAMAMQAKAKAAATIAAA0IgmAAIAAgJQgKALgQAAQgOAAgJgHgAgHAJQgDADAAAFIAAAAQAAAEADADQACACAEAAQAEAAADgEQAEgEAAgGIAAgEQgEgCgFAAQgFAAgDADg");
	this.shape_15.setTransform(-58.05,0.475);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgpAyQgLgNAAgWIAAAAQAAgVALgOQAMgNAQAAQAQAAAMAMIAAgpIAmAAIAAB7IgmAAIAAgLQgGAGgGADQgFAEgKAAQgRAAgMgNgAgKADQgEAEgBAIIAAAAQABAHAEAEQAFAGAFAAQAGAAAFgGQAFgEAAgHIAAAAQAAgIgFgEQgFgFgGAAQgFAAgFAFg");
	this.shape_16.setTransform(-68.9,-1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AghAvIAAhcIAmAAIAAATQAIgVAVABIAAApIgEAAQgZAAAAAdIAAAXg");
	this.shape_17.setTransform(-77.775,0.3977);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgoAnQgJgKABgPIAAg9IAmAAIAAAxQAAAGADADQADADAEAAQAEAAAEgDQACgEAAgFIAAgxIAoAAIAABdIgoAAIAAgNQgKAPgRAAQgOAAgJgJg");
	this.shape_18.setTransform(-87.25,0.55);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgXAaIAAgfIgMAAIAAgeIAMAAIAAgXIAlAAIAAAXIAVAAIAAAeIgVAAIAAAXQAAAJAKAAQAFAAAGgDIAAAeQgKAFgPAAQghAAAAghg");
	this.shape_19.setTransform(-96.5,-0.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgnApQgIgIAAgNQAAgOAKgHQAJgHAQAAQANAAAJADIAAgBQgBgOgQAAQgMAAgOAFIgGgZQASgHAVAAQAaAAAMAMQAKAKAAATIAAA0IgmAAIAAgJQgLALgPAAQgOAAgJgHgAgHAJQgDADAAAFIAAAAQAAAEADADQACACAEAAQAEAAAEgEQADgEAAgGIAAgEQgEgCgFAAQgEAAgEADg");
	this.shape_20.setTransform(-105.45,0.475);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("Ag4AqIAVgZQATANAWAAQAKABAAgGQAAgEgQgEQgXgFgLgGQgPgJAAgRQAAgSANgLQANgMAXAAQAhABAVAPIgUAbQgQgLgSAAQgJAAAAAEIAAABQAAAEAPADQAZAFAMAIQAOAJAAAQIAAAAQAAATgPALQgOALgYAAQglgBgXgTg");
	this.shape_21.setTransform(-116.325,-0.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141.5,-10.5,283,21);


(lib.t2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAnQgIgDgFgFQgFgGgDgHQgDgIAAgKQAAgJADgHQADgIAFgGQAFgFAIgDQAHgDAIAAQAJAAAHADQAIADAFAFQAFAGADAIQADAHAAAJQAAAKgDAIQgDAHgFAGQgFAFgIADQgHADgJAAQgIAAgHgDgAgQgUQgFAIAAAMQAAAOAFAHQAGAIAKAAQALAAAFgIQAGgHAAgOQAAgMgGgIQgFgIgLABQgKgBgGAIg");
	this.shape.setTransform(89.475,2.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIA7IAAhRIAQAAIAABRgAgEgkIgEgCIgCgEIAAgEIAAgFIACgEIAEgCIAEgBIAEABIAEACIACAEIABAFIgBAEIgCAEIgEACIgEABIgEgBg");
	this.shape_1.setTransform(82.95,0.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSA5QgFgDgEgFQgFgFgBgIQgDgIAAgKQAAgJADgIQACgGAFgGQAEgGAHgDQAGgDAJAAQAGAAAFACQAFACAEAEIAAgsIARAAIAAB2IgKAAQgEAAgBgEIgBgIQgFAGgHADQgGAEgJAAQgGAAgGgDgAgNgDQgFAHAAAOIABANQABAFADAEQACADAEACQADABAEAAQAGAAAFgDQAFgDAEgFIAAglQgEgEgEgCQgFgCgEAAQgKAAgGAHg");
	this.shape_2.setTransform(76.25,0.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSAnQgFgCgEgEQgDgFgCgFQgCgGAAgHIAAgzIASAAIAAAzQAAAJADAEQAEAEAIABQAFgBAFgCQAEgCAFgFIAAg7IARAAIAABRIgKAAQgEAAgBgEIgBgHIgGAFIgFAEIgIACIgHACQgGAAgFgDg");
	this.shape_3.setTransform(67.45,2.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIAxQgGgGAAgLIAAguIgJAAIgCgBIgBgDIAAgGIANgDIAEgXIABgCIADgCIAHAAIAAAbIAXAAIAAANIgXAAIAAAtQAAAFADACQACACADABIAEgBIACgBIACgBIACgBQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAFAIQgEADgFACQgGACgGABQgJgBgFgFg");
	this.shape_4.setTransform(60.225,0.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLA6IgKgDIgJgFIgHgHIAFgJIACgBIACgBIAEACIAGAEIAIADQAEACAGAAQAJAAAGgEQAGgGAAgJQAAgEgDgEIgGgEIgJgEIgIgDIgKgEQgFgBgEgDIgGgKQgDgEAAgIQAAgHADgGQACgFAFgFQAFgFAHgCQAGgDAIAAQAKAAAIADQAJADAGAGIgFAJIgCACIgCABIgDgCIgFgDIgHgCQgDgBgGAAIgHABIgGADQgDACgBADQgBADAAADQAAAFACADIAGAFIAIADIAKAEIAKAEIAJAFQADADADAFQACAFAAAHQAAAHgDAIQgCAGgFAFQgFAFgIADQgHADgIAAQgGAAgFgBg");
	this.shape_5.setTransform(52.775,0.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMAnQgHgDgFgFQgGgGgDgHQgDgJAAgJQAAgJADgHQADgIAFgFQAFgFAHgDQAHgEAIAAQAHAAAHACQAGADAFAEQAEAGADAHQADAGAAAJQAAAEgBAAQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAABIg0AAIACALQACAGADADQADADAFACQAEABAEABIAJgBIAGgDIAFgDIADgBQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAIAFAGQgDAEgEACIgIAEIgJACIgJABQgIAAgHgDgAAVgIQAAgEgBgEQgBgEgDgDQgCgDgEgBQgDgBgFAAQgIgBgGAGQgFAGgBAJIAnAAIAAAAg");
	this.shape_6.setTransform(40.375,2.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AASA7IAAg0QAAgHgEgEQgEgFgIAAQgEAAgFADQgFACgFAEIAAA7IgRAAIAAh1IARAAIAAAuQAFgFAHgDQAFgDAHAAQAHAAAFADQAFACAEAEQADAEACAGQACAEAAAHIAAA0g");
	this.shape_7.setTransform(31.675,0.275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgIAxQgGgGAAgLIAAguIgJAAIgCgBIgBgDIAAgGIANgDIAEgXIABgCIADgCIAHAAIAAAbIAXAAIAAANIgXAAIAAAtQAAAFADACQACACADABIAEgBIACgBIACgBIACgBQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAFAIQgEADgFACQgGACgGABQgJgBgFgFg");
	this.shape_8.setTransform(24.375,0.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMAnQgHgDgFgFQgGgGgDgHQgDgJAAgJQAAgJADgHQADgIAFgFQAFgFAHgDQAHgEAIAAQAHAAAHACQAGADAFAEQAEAGADAHQADAGAAAJQAAAEgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBAAAAABIg0AAIACALQACAGADADQADADAFACQAEABAEABIAJgBIAGgDIAFgDIADgBQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAIAFAGQgDAEgEACIgIAEIgJACIgJABQgIAAgHgDgAAVgIQAAgEgBgEQgBgEgDgDQgCgDgEgBQgDgBgFAAQgIgBgGAGQgFAGgBAJIAnAAIAAAAg");
	this.shape_9.setTransform(13.225,2.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSA5QgFgDgEgFQgFgFgBgIQgDgIAAgKQAAgJADgIQACgGAFgGQAEgGAHgDQAGgDAJAAQAGAAAFACQAFACAEAEIAAgsIARAAIAAB2IgKAAQgEAAgBgEIgBgIQgFAGgHADQgGAEgIAAQgHAAgGgDgAgNgDQgFAHAAAOIABANQABAFADAEQACADAEACQADABAEAAQAGAAAFgDQAFgDAEgFIAAglQgEgEgEgCQgFgCgEAAQgKAAgGAHg");
	this.shape_10.setTransform(4.25,0.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIA7IAAhRIAQAAIAABRgAgEgkIgEgCIgCgEIgBgEIABgFIACgEIAEgCIAEgBIAEABIAEACIACAEIACAFIgCAEIgCAEIgEACIgEABIgEgBg");
	this.shape_11.setTransform(-2,0.325);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgJApIgIgCIgGgDIgGgEIAEgHIACgBIADgBIADABIAEACIAFADIAIABIAGgBIAEgDIADgDIABgFQAAgDgCgCIgFgDIgGgDIgHgCIgHgDIgHgDIgFgHQgBgDAAgGQAAgFACgEQACgFADgDQAEgDAGgCQAFgCAHAAQAIAAAHADQAGACAFAFIgEAGIgCACIgBAAIgDgBIgEgCIgFgCIgHAAIgFAAIgEACIgDAEIgBAEQAAADACACQABACADABIAGACIAHADIAIADQAEABACACIAFAGQACADAAAFQAAAGgCAFQgCAFgEADQgEAEgGACQgGACgHAAg");
	this.shape_12.setTransform(-7.525,2.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgIAxQgGgGAAgLIAAguIgJAAIgCgBIgBgDIAAgGIANgDIAEgXIABgCIADgCIAHAAIAAAbIAXAAIAAANIgXAAIAAAtQAAAFADACQACACADABIAEgBIACgBIACgBIACgBQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAFAIQgEADgFACQgGACgGABQgJgBgFgFg");
	this.shape_13.setTransform(-13.725,0.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgSAnQgGgCgDgEQgDgFgCgFQgCgGAAgHIAAgzIARAAIAAAzQAAAJAEAEQAEAEAIABQAEgBAFgCQAFgCAEgFIAAg7IASAAIAABRIgLAAQgDAAgBgEIgCgHIgEAFIgHAEIgHACIgGACQgHAAgFgDg");
	this.shape_14.setTransform(-21.25,2.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgWA3QgLgFgIgIQgHgHgEgLQgFgLAAgNQAAgMAFgKQAEgLAHgIQAIgIALgEQAKgFAMAAQANAAALAFQAKAEAIAIQAHAIAEALQAFAKAAAMQAAANgFALQgEALgHAHQgIAIgKAFQgLAEgNAAQgMAAgKgEgAgPgnQgHADgFAGQgFAFgDAIQgCAIAAAJQAAAKACAIQADAIAFAGQAFAFAHADQAHADAIAAQAJAAAHgDQAHgDAFgFQAFgGADgIQADgIAAgKQAAgJgDgIQgDgIgFgFQgFgGgHgDQgHgDgJAAQgIAAgHADg");
	this.shape_15.setTransform(-32.125,0.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgJApIgIgCIgGgDIgGgEIAEgHIACgBIADgBIADABIAEACIAFADIAIABIAGgBIAEgDIADgDIABgFQAAgDgCgCIgFgDIgGgDIgHgCIgHgDIgHgDIgFgHQgBgDAAgGQAAgFACgEQACgFADgDQAEgDAGgCQAFgCAHAAQAIAAAHADQAGACAFAFIgEAGIgCACIgBAAIgDgBIgEgCIgFgCIgHAAIgFAAIgEACIgDAEIgBAEQAAADACACQABACADABIAGACIAHADIAIADQAEABACACIAFAGQACADAAAFQAAAGgCAFQgCAFgEADQgEAEgGACQgGACgHAAg");
	this.shape_16.setTransform(-46.025,2.125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgTA3QgIgEgGgGQgGgHgEgIQgDgJAAgKIAAhEIATAAIAABEQAAAHACAFQACAGADAEQAEAEAFACQAFADAGAAQAHAAAFgDQAFgCAEgEQADgEACgFQACgGAAgHIAAhEIATAAIAABEQAAAKgEAJQgDAIgGAHQgGAGgJAEQgIADgLAAQgKAAgJgDg");
	this.shape_17.setTransform(-55.325,0.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AASAqIAAg0QAAgHgEgFQgEgFgIAAQgEAAgFADQgFACgFAFIAAA7IgRAAIAAhRIALAAQADAAABADIABAHIAGgEIAGgEIAGgCIAHgBQAHAAAFACQAFACAEAEQADAEACAGQACAGAAAGIAAA0g");
	this.shape_18.setTransform(-69.625,2.05);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgIA7IAAhRIARAAIAABRgAgEgkIgEgCIgCgEIAAgEIAAgFIACgEIAEgCIAEgBIAEABIAEACIACAEIABAFIgBAEIgCAEIgEACIgEABIgEgBg");
	this.shape_19.setTransform(-76.1,0.325);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgPAnQgIgDgFgFQgFgGgDgHQgDgIAAgKQAAgJADgHQADgIAFgGQAFgFAIgDQAHgDAIAAQAJAAAHADQAIADAFAFQAFAGADAIQADAHAAAJQAAAKgDAIQgDAHgFAGQgFAFgIADQgHADgJAAQgIAAgHgDgAgQgUQgFAIAAAMQAAAOAFAHQAGAIAKAAQALAAAFgIQAGgHAAgOQAAgMgGgIQgFgIgLABQgKgBgGAIg");
	this.shape_20.setTransform(-82.625,2.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgRA6IgJgCIABgLIABgDIADgBIAEABIAGAAQAFAAAEgBQACgCADgDQADgDABgFQABgEAAgHIAAhKIATAAIAABJQAAAKgDAIQgCAHgFAGQgEAFgHADQgGADgJAAg");
	this.shape_21.setTransform(-91.125,0.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-108.8,-11.6,217.7,23.2);


(lib.t1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FECA00").s().p("AhOBRIAAigIA+AAQAuAAAZAVQAYAVAAAkIAAABQAAAkgYAWQgaAXgvAAgAgYAhIAJAAQAnABAAgiQAAgggnAAIgJAAg");
	this.shape.setTransform(119.35,11.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FECA00").s().p("AARBRIgdgvIgMAAIAAAvIg2AAIAAigIBOAAQAoAAASASQAPAPAAAXIAAABQAAAhggAPIAmA3gAgYgDIAYAAQATAAAAgQIAAAAQAAgPgTAAIgYAAg");
	this.shape_1.setTransform(102.925,11.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FECA00").s().p("Ag+A7QgZgYAAgiIAAgBQAAgiAZgYQAagZAkAAQAlAAAZAZQAaAYAAAiIAAAAQAAAjgaAYQgZAZglAAQglAAgZgZgAgXgYQgKAKAAAOIAAAAQAAAPAKAKQAJAMAOAAQAPAAAKgMQAJgKAAgOIAAgBQAAgOgJgKQgLgLgOAAQgOAAgJALg");
	this.shape_2.setTransform(84.85,11.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FECA00").s().p("AAcBRIgchQIgbBQIgvAAIg1ihIA5AAIAWBOIAahOIAuAAIAaBOIAXhOIA3AAIg1Chg");
	this.shape_3.setTransform(63.625,11.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FECA00").s().p("AhOBRIAAigIA+AAQAuAAAZAVQAYAVAAAkIAAABQAAAkgYAWQgaAXgvAAgAgYAhIAJAAQAnABAAgiQAAgggnAAIgJAAg");
	this.shape_4.setTransform(36.65,11.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FECA00").s().p("AhEBRIAAigICIAAIAAAsIhTAAIAAAQIBNAAIAAAmIhNAAIAAASIBUAAIAAAsg");
	this.shape_5.setTransform(20.425,11.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FECA00").s().p("Ag1A9QgbgYAAgkIAAgBQAAgjAagYQAZgYAlAAQAnAAAcAZIgeAkQgQgPgTAAQgPAAgKAMQgLAKAAAQIAAAAQAAARALALQALALAQAAQAMgBAGgDIAAgQIgbAAIAAghIBOAAIAABJQgeAYgpAAQgmAAgZgXg");
	this.shape_6.setTransform(3.925,11.35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FECA00").s().p("Ag1A9QgbgYAAgkIAAgBQAAgjAagYQAZgYAlAAQAnAAAcAZIgeAkQgQgPgTAAQgPAAgKAMQgLAKAAAQIAAAAQAAARALALQALALAQAAQAMgBAGgDIAAgQIgbAAIAAghIBOAAIAABJQgeAYgpAAQgmAAgZgXg");
	this.shape_7.setTransform(-13.375,11.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FECA00").s().p("AhEBRIAAigICIAAIAAAsIhTAAIAAAQIBNAAIAAAmIhNAAIAAASIBUAAIAAAsg");
	this.shape_8.setTransform(-29.225,11.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FECA00").s().p("AhABRIAAigIA2AAIAABxIBLAAIAAAvg");
	this.shape_9.setTransform(-43.775,11.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FECA00").s().p("AgnAWIAAgrIBPAAIAAArg");
	this.shape_10.setTransform(-55.8,12.15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FECA00").s().p("AARBRIgdgvIgMAAIAAAvIg2AAIAAigIBOAAQAoAAASASQAPAPAAAXIAAABQAAAhggAPIAmA3gAgYgDIAYAAQATAAAAgQIAAAAQAAgPgTAAIgYAAg");
	this.shape_11.setTransform(-68.125,11.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FECA00").s().p("AhOAHIAAhYIA2AAIAABXQAAAcAYAAQAZAAgBgbIAAhYIA3AAIAABWQAABNhPAAQhPAAABhLg");
	this.shape_12.setTransform(-85.6,11.525);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FECA00").s().p("Ag+A7QgZgYAAgiIAAgBQAAgiAagYQAZgZAkAAQAlAAAaAZQAZAYAAAiIAAAAQAAAjgZAYQgaAZglAAQglAAgZgZgAgYgYQgJAKAAAOIAAAAQAAAPAJAKQAKAMAOAAQAPAAAKgMQAIgKABgOIAAgBQgBgOgIgKQgKgLgPAAQgOAAgKALg");
	this.shape_13.setTransform(-103.65,11.35);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FECA00").s().p("AhDBRIAAigICGAAIAAAuIhQAAIAAAUIBKAAIAAApIhKAAIAAA1g");
	this.shape_14.setTransform(-120.05,11.35);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FECA00").s().p("AAkBRIgJgVIg3AAIgIAVIg5AAIBDihIA0AAIBFChgAAOAWIgOgnIgOAnIAcAAg");
	this.shape_15.setTransform(48.95,-13.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FECA00").s().p("AhMA4IAdgiQAZATAeAAQAOAAAAgHIAAAAQAAgHgWgEQgggHgPgJQgUgLAAgYQAAgYARgPQATgPAfAAQAtgBAcAWIgaAlQgWgQgaAAQgLAAAAAGIAAABQAAAGAUAEQAiAHAQAKQATAMAAAWIAAABQAAAZgUAPQgTAOggAAQgzAAgfgbg");
	this.shape_16.setTransform(25.975,-13.65);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FECA00").s().p("AgaBRIAAigIA1AAIAACgg");
	this.shape_17.setTransform(15.05,-13.65);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FECA00").s().p("AhEBRIAAigICIAAIAAAsIhTAAIAAAQIBNAAIAAAmIhNAAIAAASIBUAAIAAAsg");
	this.shape_18.setTransform(-1.825,-13.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FECA00").s().p("AgZBRIhBihIA8AAIAeBZIAghZIA7AAIhBChg");
	this.shape_19.setTransform(-18.5,-13.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FECA00").s().p("Ag+A7QgZgYAAgiIAAgBQAAgiAZgZQAagYAkAAQAlAAAaAYQAZAYAAAjIAAAAQAAAjgZAYQgaAZglAAQglAAgZgZgAgYgZQgJALAAAOIAAAAQAAAPAJALQAKAKAOABQAPgBAKgKQAIgLABgOIAAgBQgBgOgIgLQgLgLgOABQgOgBgKALg");
	this.shape_20.setTransform(-35.6,-13.65);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FECA00").s().p("AhABRIAAigIA2AAIAAByIBLAAIAAAug");
	this.shape_21.setTransform(-50.775,-13.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-175.6,-26,351.29999999999995,52);


(lib.logo_r = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.LOGO_R();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


(lib.logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.LOGO();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


(lib.img1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IMG1();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


(lib.doted = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCA00").s().p("AgKE3QgEgFAAgGQAAgGAEgEQAFgFAFAAQAGAAAFAFQAEAEAAAGQAAAGgEAFQgFAEgGAAQgFAAgFgEgAgKD6QgEgEAAgGQAAgGAEgEQAFgFAFAAQAGAAAFAFQAEAEAAAGQAAAGgEAEQgFAFgGAAQgFAAgFgFgAgKC/QgEgFAAgGQAAgGAEgFQAFgEAFAAQAGAAAFAEQAEAFAAAGQAAAGgEAFQgFAEgGAAQgFAAgFgEgAgKCDQgEgFAAgGQAAgGAEgEQAFgFAFAAQAGAAAFAFQAEAEAAAGQAAAGgEAFQgFAEgGAAQgFAAgFgEgAgKBGQgEgEAAgGQAAgGAEgEQAFgFAFAAQAGAAAFAFQAEAEAAAGQAAAGgEAEQgFAFgGAAQgFAAgFgFgAgKALQgEgFAAgGQAAgFAEgFQAFgEAFAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgFAAgFgEgAgKgwQgEgFAAgGQAAgGAEgEQAFgFAFAAQAGAAAFAFQAEAEAAAGQAAAGgEAFQgFAEgGAAQgFAAgFgEgAgKhtQgEgEAAgGQAAgGAEgFQAFgEAFAAQAGAAAFAEQAEAFAAAGQAAAGgEAEQgFAFgGAAQgFAAgFgFgAgKioQgEgFAAgGQAAgGAEgFQAFgEAFAAQAGAAAFAEQAEAFAAAGQAAAGgEAFQgFAEgGAAQgFAAgFgEgAgKjlQgEgEAAgGQAAgGAEgEQAFgFAFAAQAGAAAFAFQAEAEAAAGQAAAGgEAEQgFAFgGAAQgFAAgFgFgAgKkhQgEgEAAgGQAAgGAEgFQAFgEAFAAQAGAAAFAEQAEAFAAAGQAAAGgEAEQgFAFgGAAQgFAAgFgFg");
	this.shape.setTransform(0,-0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-32.4,3,63);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgKAiQgGgCgFgFQgFgFgCgHQgDgHAAgIQAAgIADgGQACgHAEgEQAEgFAHgDQAGgDAHAAQAGAAAGADQAFACAEAEQAEAEACAGQADAGAAAHIgBAEIgCABIguAAIACALQABAFADADQADADAEABQAEACAEAAIAHgBIAGgCIAEgDIADgBQABAAAAAAQAAAAABABQAAAAAAAAQABAAAAABIAEAFIgGAFIgHADIgIACIgIABQgGAAgGgDgAATgHIgBgHQgBgEgCgCQgCgDgEgBIgHgBQgIAAgFAEQgEAFgCAJIAkAAIAAAAg");
	this.shape.setTransform(27.025,1.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgTAkIAAhGIAIAAIADABIAAADIABAKQAEgHAEgEQAFgEAGAAIAFAAIADACIgBAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgDAAIgEgBIgGABIgEADIgDAFIgDAGIAAArg");
	this.shape_1.setTransform(21.2,1.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgNAiQgGgCgFgFQgEgFgDgHQgCgGAAgJQAAgHACgHQADgHAEgFQAFgEAGgDQAGgDAHAAQAIAAAGADQAHADAEAEQAFAFACAHQACAHAAAHQAAAJgCAGQgCAHgFAFQgEAFgHACQgGADgIAAQgHAAgGgDgAgOgSQgFAHAAALQAAANAFAGQAFAHAJAAQAKAAAFgHQAFgGAAgNQAAgLgFgHQgFgHgKAAQgJAAgFAHg");
	this.shape_2.setTransform(14.225,1.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAoAyIAAhGIAAgEIAAgDIghA8QgCADgEAAIgBAAQgDAAgCgDIgig9IAAAIIAABGIgNAAIAAhjIALAAIADAAIACACIAiA7IACAEIAAAEIAEgIIAhg7IACgCIADAAIALAAIAABjg");
	this.shape_3.setTransform(3.725,0.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AARAkIAAgsQAAgIgEgEQgEgEgHAAQgEAAgFACQgFADgDAEIAAAzIgOAAIAAhGIAIAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIABAHIAEgFIAGgDIAGgCIAGgBQAGAAAFACQAEACADADQADAEACAFQABAFAAAGIAAAsg");
	this.shape_4.setTransform(-10.15,1.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgUAkIAAhGIAIAAIADABIACADIABAKQADgHAEgEQAEgEAIAAIAEAAIAEACIgBAKQgBABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgDAAIgEgBIgGABIgEADIgDAFIgDAGIAAArg");
	this.shape_5.setTransform(-16.2,1.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgPAkQgDgBgDgDIgFgGQgBgDAAgFQgBgEADgEQADgEAEgDQAFgDAJgBQAHgCANAAIAAgGQgBgIgDgEQgEgEgGAAIgHABIgFADIgEACIgDACIgCgBIgCgCIgDgEQAGgGAHgDQAHgDAHAAQAGAAAGACQAEACADAEQADADACAFQACAFgBAGIAAAtIgFAAIgEgBIgBgCIgBgHIgGAFIgFADIgGACIgHABIgIgBgAABAFIgJADQgDACgBACQgCACAAADIABAFIACADIADACIAFAAIAFAAIAFgCIAEgDIAFgEIAAgOIgPABg");
	this.shape_6.setTransform(-22.9,1.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgKAiQgGgCgFgFQgFgFgCgHQgDgHAAgIQAAgIADgGQACgHAEgEQAEgFAHgDQAGgDAHAAQAGAAAGADQAFACAEAEQAEAEACAGQADAGAAAHIgBAEIgCABIguAAIACALQABAFADADQADADAEABQAEACAEAAIAHgBIAGgCIAEgDIADgBQABAAAAAAQAAAAABABQAAAAAAAAQAAAAABABIAEAFIgGAFIgHADIgIACIgIABQgGAAgGgDgAATgHIgBgHQgBgEgCgCQgCgDgEgBIgHgBQgIAAgFAEQgEAFgCAJIAkAAIAAAAg");
	this.shape_7.setTransform(-29.825,1.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgcAyIAAhjIAPAAIAABXIAqAAIAAAMg");
	this.shape_8.setTransform(-36.625,0.125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F6CC00").s().p("AnzCgIAAk/IPnAAIAAE/g");
	this.shape_9.setTransform(-5,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55,-16,100,32);


(lib.bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


(lib._2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000F35").s().p("AqKJfIgGgEIgJgIQhThLgTifQgFgwgBgwQgChTAKhSQBroKFKipIARgIQFaiaH1HPIATASQC2CxAfCPQAKAzgGApQgKBAgvApQhgBNjcgMQglgFglgBQgbgBgbABQj0AKj6CqQgnAdgjAYQiZBlhmAAQg5AAgpgfg");
	this.shape.setTransform(0.0201,0.0015);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77.4,-63.8,154.8,127.6);


(lib._1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCA00").s().p("AqKJfIgGgEIgJgIQhThLgTifQgFgwgBgwQgChTAKhSQBroKFKipIARgIQFaiaH1HPIATASQC2CxAfCPQAKAzgGApQgKBAgvApQhgBNjcgMQglgFglgBQgbgBgbABQj0AKj6CqQgnAdgjAYQiZBlhmAAQg5AAgpgfg");
	this.shape.setTransform(0.0201,0.0015);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77.4,-63.8,154.8,127.6);


(lib.shape = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib._1("synched",0);
	this.instance.setTransform(0,-4.55,1.0043,1.0043);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_2
	this.instance_1 = new lib._2("synched",0);
	this.instance_1.setTransform(-2.5,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-79.9,-68.6,157.7,131.89999999999998);


// stage content:
(lib.KSFY_214866_MM_1024x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EhP/gHBMCf/AAAIAAODMif/AAAg");
	this.shape.setTransform(512,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(192));

	// cta
	this.instance = new lib.cta();
	this.instance.setTransform(764.9,48,1.3823,1.3823,0,0,0,0.1,0.1);
	this.instance.alpha = 0;
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.cta(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(68).to({_off:false},0).to({scaleX:1.0367,scaleY:1.0367,x:764.85,y:47.95,alpha:1},9,cjs.Ease.get(-1)).to({scaleX:1.152,scaleY:1.152},5).wait(110));

	// t4
	this.instance_1 = new lib.t4("synched",0);
	this.instance_1.setTransform(563.25,58.1,0.6,0.6,0,0,0,0.1,0);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(53).to({_off:false},0).to({regX:0,scaleX:1,scaleY:1,alpha:1},14,cjs.Ease.get(1)).wait(125));

	// t3
	this.instance_2 = new lib.t3("synched",0);
	this.instance_2.setTransform(562.5,28.05,0.6,0.6,0,0,0,0.1,0.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(39).to({_off:false},0).to({regX:0,regY:0,scaleX:1,scaleY:1},13,cjs.Ease.get(1)).wait(140));

	// doted
	this.instance_3 = new lib.doted("synched",0);
	this.instance_3.setTransform(420.95,47.45,1,0.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(39).to({_off:false},0).to({scaleY:1},13,cjs.Ease.get(1)).wait(140));

	// t2
	this.instance_4 = new lib.t2("synched",0);
	this.instance_4.setTransform(273.3,69.3,0.6,0.6,0,0,0,0.1,0.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(25).to({_off:false},0).to({regX:0,regY:0,scaleX:1,scaleY:1,alpha:1},13,cjs.Ease.get(1)).wait(154));

	// t1
	this.instance_5 = new lib.t1("synched",0);
	this.instance_5.setTransform(273.3,36,1.0968,1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(25).to({_off:false},0).to({scaleX:1,alpha:1},13,cjs.Ease.get(1)).wait(154));

	// LOGO_png
	this.instance_6 = new lib.logo("synched",0);
	this.instance_6.setTransform(80,211);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(2).to({_off:false},0).to({y:300},11,cjs.Ease.get(1)).wait(179));

	// LOGO_R_png
	this.instance_7 = new lib.logo_r("synched",0);
	this.instance_7.setTransform(80,210);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(84).to({_off:false},0).to({y:300},10,cjs.Ease.get(1)).wait(98));

	// IMG1_png
	this.instance_8 = new lib.img1("synched",0);
	this.instance_8.setTransform(80,290);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(13).to({_off:false},0).to({y:300},11,cjs.Ease.get(1)).wait(168));

	// Layer_10
	this.instance_9 = new lib.shape("synched",0,false);
	this.instance_9.setTransform(966.25,70.9,0.6,0.4753,0,0,0,0.1,30.1);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(13).to({_off:false},0).to({regY:30,scaleY:0.6,y:66.7},11,cjs.Ease.get(1)).wait(168));

	// BG_png
	this.instance_10 = new lib.bg("synched",0);
	this.instance_10.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(192));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(511,-45,514,136);
// library properties:
lib.properties = {
	id: '1B2175A397DA418A911C8D25A6AE7677',
	width: 1024,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.png", id:"BG"},
		{src:"IMG1.png", id:"IMG1"},
		{src:"LOGO.png", id:"LOGO"},
		{src:"LOGO_R.png", id:"LOGO_R"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['1B2175A397DA418A911C8D25A6AE7677'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;