(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.IMG1 = function() {
	this.initialize(img.IMG1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.LOGO = function() {
	this.initialize(img.LOGO);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.LOGO_R = function() {
	this.initialize(img.LOGO_R);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.t4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgCAJIgDgDIgDgDIAAgDIAAgDIADgCIADgCIACgBIAEABIACACIACACIABADIgBADIgCADIgCADIgEAAg");
	this.shape.setTransform(147.5,6.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_1.setTransform(143.075,3.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_2.setTransform(137.425,3.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_3.setTransform(131.225,3.525);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIAgQgGgCgEgFQgEgEgCgGQgCgHAAgIQAAgGACgHQACgGAEgEQAEgFAGgCQAGgDAGAAQAIAAAFACQAGADAEAEIgEAFIgBABIgCABIgCgBIgDgCIgEgCIgGAAQgEAAgDABQgDACgDADIgDAHQgBAFAAAEQAAAGABAEQABAEADADIAFAFQADABAEAAIAGgBIAEgCIADgCIADgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIADAFIgFAFIgGADIgHACIgHAAQgFAAgFgCg");
	this.shape_4.setTransform(124.775,3.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_5.setTransform(117.875,3.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSAiIAAhCIAIAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIABADIABAJQADgHAEgDQAEgEAGAAIAEABIADABIAAALIgBABIgCABIgDgBIgDAAIgGABIgEACIgCAEIgCAGIAAAog");
	this.shape_6.setTransform(112.175,3.475);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdAtIAAhYIAIAAQABAAABAAQAAABABAAQAAAAABABQAAABAAAAIACAHQAEgFAFgDQAFgDAGAAQAGAAAEACQAFADADAEQADAEACAHQACAGAAAIQAAAHgCAGQgCAGgEAFQgEAEgFADQgFADgGAAQgGAAgDgCIgIgFIAAAcgAgIgeIgHAGIAAAeQADAEAEABQADACAEAAQAIAAAEgGQAFgGgBgLIgBgKQgBgFgBgCQgCgDgEgBQgCgCgDAAQgFAAgEADg");
	this.shape_7.setTransform(105.95,4.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_8.setTransform(95.325,3.475);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_9.setTransform(87.975,3.525);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgDgdIgDgCIgBgDIgBgEIABgDIABgDIADgCIADgBIADABIAEACIACADIABADIgBAEIgCADIgEACIgDABIgDgBg");
	this.shape_10.setTransform(82.65,2.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgGAnQgFgFAAgHIAAgnIgHAAIgCAAIgBgDIAAgFIAKgCIAEgTIABgCIACAAIAGAAIAAAVIATAAIAAAKIgTAAIAAAmQAAADACABQAAABABAAQAAABABAAQAAAAABAAQABAAAAAAIAEAAIABgBIACgBIABAAIACABIAEAHQgDADgFACIgJABQgHAAgEgFg");
	this.shape_11.setTransform(78.75,2.55);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgdAtIAAhYIAJAAQAAAAABAAQAAABABAAQAAAAABABQAAABAAAAIABAHQAEgFAFgDQAGgDAGAAQAFAAAFACQAEADAEAEQADAEACAHQACAGAAAIQAAAHgCAGQgCAGgEAFQgDAEgGADQgFADgHAAQgEAAgEgCIgIgFIAAAcgAgIgeIgHAGIAAAeQADAEAEABQADACAEAAQAHAAAFgGQAFgGAAgLIgBgKQgCgFgCgCQgBgDgDgBQgDgCgDAAQgFAAgEADg");
	this.shape_12.setTransform(72.85,4.575);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_13.setTransform(65.325,3.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgOAuQgFgCgDgFQgEgEgBgGQgCgHAAgIQAAgHACgGQACgFADgFQAFgFAEgCQAGgDAHAAQAEAAAFACQAEACADADIAAgkIAOAAIAABfIgJAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgBgIQgFAFgFAEQgFACgGAAQgGABgEgDgAgKgCQgEAFAAALIAAALQABAEACADIAFAEIAGABQAFAAAEgCIAHgGIAAgeQgDgFgDAAQgEgCgEAAQgHAAgFAGg");
	this.shape_14.setTransform(57.8,2.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgOAhQgEgBgDgCQgCgCgBgEQgCgDAAgFQAAgDADgEQACgEAEgDQAEgCAJgBQAGgCAMAAIAAgFQAAgHgDgDQgEgEgFAAIgGABIgFACIgDACIgEABIgDAAIgBgCIgCgFQALgKAOAAQAGAAAFACQAEABADAEQADADABAFQACAEAAAGIAAApIgGAAIgEAAIgBgDIgCgFIgEAEIgFADIgFACIgHAAIgHgBgAABAFIgHADIgFADQAAABgBAAQAAABAAAAQAAABAAABQAAAAAAABIAAAEIACADIAEABIADABQAFAAAEgCIAIgGIAAgNIgNABg");
	this.shape_15.setTransform(50.85,3.525);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_16.setTransform(41.175,3.525);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAOAwIAAgqQAAgGgDgDQgDgFgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhfIAOAAIAAAlQAEgDAFgDQAEgCAGgBQAGAAAEACIAHAGIAEAIQABADAAAGIAAAqg");
	this.shape_17.setTransform(34.125,2.05);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgHAnQgEgFAAgHIAAgnIgHAAIgCAAIgBgDIAAgFIALgCIADgTIABgCIACAAIAGAAIAAAVIATAAIAAAKIgTAAIAAAmQAAADACABQAAABABAAQAAABABAAQAAAAABAAQABAAAAAAIAEAAIACgBIABgBIABAAIACABIAEAHQgDADgEACIgJABQgIAAgFgFg");
	this.shape_18.setTransform(28.15,2.55);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgHAnQgEgFAAgHIAAgnIgHAAIgCAAIgBgDIAAgFIALgCIADgTIABgCIACAAIAGAAIAAAVIASAAIAAAKIgSAAIAAAmQAAADACABQAAABABAAQAAABABAAQAAAAABAAQABAAABAAIACAAIACgBIACgBIABAAIACABIAEAHQgDADgEACIgJABQgIAAgFgFg");
	this.shape_19.setTransform(20.2,2.55);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgSAiIAAhCIAIAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAIABADIABAJQADgHAEgDQAEgEAGAAIAEABIADABIAAALIgBABIgCABIgDgBIgDAAIgGABIgEACIgCAEIgCAGIAAAog");
	this.shape_20.setTransform(15.775,3.475);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgOAhQgEgBgDgCQgCgCgBgEQgCgDAAgFQAAgDADgEQACgEAEgDQAEgCAIgBQAHgCALAAIAAgFQAAgHgCgDQgDgEgGAAIgHABIgEACIgEACIgDABIgDAAIgBgCIgCgFQALgKAOAAQAGAAAEACQAFABADAEQADADABAFQACAEAAAGIAAApIgGAAIgDAAIgCgDIgCgFIgEAEIgGADIgEACIgHAAIgHgBgAABAFIgHADIgFADQAAABgBAAQAAABAAAAQAAABAAABQgBAAAAABIABAEIACADIAEABIADABQAFAAAEgCIAHgGIAAgNIgMABg");
	this.shape_21.setTransform(9.55,3.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgHAnQgEgFAAgHIAAgnIgHAAIgCAAIgBgDIAAgFIALgCIADgTIABgCIACAAIAGAAIAAAVIASAAIAAAKIgSAAIAAAmQAAADACABQAAABABAAQAAABABAAQAAAAABAAQABAAAAAAIADAAIADgBIABgBIABAAIACABIAEAHQgDADgEACIgJABQgIAAgFgFg");
	this.shape_22.setTransform(4.2,2.55);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_23.setTransform(-1.125,3.525);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgOAuQgFgCgDgFQgDgEgCgGQgCgHAAgIQAAgHACgGQACgFAEgFQAEgFAFgCQAFgDAGAAQAGAAADACQAEACAEADIAAgkIAOAAIAABfIgIAAQgBAAgBAAQAAAAgBAAQgBAAAAgBQAAAAgBgBIgBgIQgEAFgFAEQgFACgGAAQgGABgEgDgAgKgCQgFAFABALIABALQABAEABADIAFAEIAGABQAFAAADgCIAIgGIAAgeQgDgFgEAAQgDgCgEAAQgIAAgEAGg");
	this.shape_24.setTransform(-10.9,2.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_25.setTransform(-17.975,3.475);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgOAhQgEgBgDgCQgCgCgBgEQgCgDAAgFQAAgDADgEQACgEAEgDQAEgCAIgBQAHgCALAAIAAgFQAAgHgCgDQgDgEgGAAIgHABIgEACIgEACIgDABIgDAAIgBgCIgDgFQAMgKAOAAQAGAAAEACQAFABADAEQADADABAFQACAEAAAGIAAApIgGAAIgDAAIgCgDIgCgFIgEAEIgGADIgEACIgHAAIgHgBgAABAFIgHADIgFADQAAABgBAAQAAABAAAAQAAABAAABQgBAAAAABIABAEIACADIAEABIADABQAFAAAEgCIAHgGIAAgNIgMABg");
	this.shape_26.setTransform(-25.1,3.525);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgGAQIgBgCIAAgBIABgCIACgBIACgDIACgEIAAgDIAAAAIgDAAIgCgCIgCgDIgBgDIABgEIACgDIACgBIADAAIAEAAIACACIACAEIABAEIgBAGIgCAFIgFAHIgEAGg");
	this.shape_27.setTransform(178.55,-8.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_28.setTransform(174.175,-12.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgdAtIAAhYIAIAAQABAAABAAQAAABABAAQAAAAABABQAAAAAAABIACAHQADgFAGgDQAFgDAGAAQAFAAAFACQAEADAEAEQADAEACAHQACAGAAAIQAAAHgCAGQgCAGgEAFQgEAEgFADQgFADgGAAQgGAAgDgCIgIgFIAAAcgAgIgeIgHAGIAAAeQADAEAEABQADACAEAAQAIAAAEgGQAFgGgBgLIgBgKQgBgFgBgCQgCgDgEgBQgCgCgDAAQgFAAgEADg");
	this.shape_29.setTransform(167.95,-11.025);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgPAgQgEgCgDgDQgDgDgBgFQgBgFAAgFIAAgqIAOAAIAAAqQAAAGADAEQADAEAGAAQAEAAAEgCQAEgCADgEIAAgwIAOAAIAABCIgIAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgBgGIgEAEIgFADIgGACIgFABQgGAAgEgCg");
	this.shape_30.setTransform(160.475,-12.025);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgdAtIAAhYIAJAAQAAAAABAAQAAABABAAQAAAAABABQAAAAAAABIABAHQAEgFAFgDQAGgDAGAAQAFAAAFACQAEADAEAEQADAEACAHQACAGAAAIQAAAHgCAGQgCAGgEAFQgDAEgGADQgFADgHAAQgEAAgEgCIgIgFIAAAcgAgIgeIgHAGIAAAeQADAEAEABQADACAEAAQAHAAAFgGQAFgGAAgLIgBgKQgCgFgCgCQgBgDgDgBQgDgCgEAAQgEAAgEADg");
	this.shape_31.setTransform(153.4,-11.025);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_32.setTransform(142.925,-12.075);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAOAwIAAgqQAAgGgDgEQgDgEgGAAQgEABgEACQgEACgDADIAAAwIgOAAIAAhfIAOAAIAAAmQAEgFAFgCQAEgDAGABQAGAAAEABIAHAGIAEAHQABAEAAAGIAAAqg");
	this.shape_33.setTransform(135.875,-13.55);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAgmIgHAAIgCAAIgBgCIAAgGIALgCIADgSIABgCIACgBIAGAAIAAAVIASAAIAAAKIgSAAIAAAlQAAAEACACQAAAAABAAQAAABABAAQAAAAABAAQABAAABAAIACAAIACgBIACAAIABgBIACABIAEAHQgDADgFABIgJACQgHAAgEgEg");
	this.shape_34.setTransform(129.9,-13.05);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAgmIgHAAIgCAAIgBgCIAAgGIAKgCIAEgSIABgCIACgBIAGAAIAAAVIATAAIAAAKIgTAAIAAAlQAAAEACACQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAIAEAAIACgBIABAAIABgBIACABIAEAHQgDADgFABIgJACQgHAAgEgEg");
	this.shape_35.setTransform(121.95,-13.05);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_36.setTransform(116.075,-12.075);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_37.setTransform(109.175,-12.075);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAgAiIAAgpQAAgHgDgEQgDgEgGAAIgFABIgEADIgDAEIgBAHIAAApIgNAAIAAgpQAAgIgDgDQgDgEgFAAQgEAAgEACIgGAGIAAAwIgOAAIAAhCIAJAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIABAGIAEgEIAEgDIAFgCIAGgBIAFABIAFADIADAEIACAFIAEgFIAFgFIAGgCIAGgBQAGAAAEACQAEACADADQADADABAFQACAFAAAGIAAApg");
	this.shape_38.setTransform(100.375,-12.125);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgGAQIgBgCIAAgBIABgCIACgBIACgDIACgEIAAgDIAAAAIgDAAIgDgCIgBgDIgBgDIABgEIABgDIADgBIADAAIADAAIAEACIABAEIABAEIgBAGIgDAFIgEAHIgFAGg");
	this.shape_39.setTransform(90.3,-8.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_40.setTransform(85.925,-12.075);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAgAiIAAgpQAAgHgDgEQgDgEgGAAIgFABIgEADIgDAEIgBAHIAAApIgNAAIAAgpQAAgIgDgDQgDgEgFAAQgEAAgEACIgGAGIAAAwIgOAAIAAhCIAJAAQAAAAABAAQABABAAAAQABAAAAABQAAAAAAABIABAGIAEgEIAEgDIAFgCIAGgBIAFABIAFADIADAEIACAFIAEgFIAFgFIAGgCIAGgBQAGAAAEACQAEACADADQADADABAFQACAFAAAGIAAApg");
	this.shape_41.setTransform(77.825,-12.125);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_42.setTransform(68.975,-12.075);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAgmIgHAAIgCAAIgBgCIAAgGIAKgCIAEgSIABgCIACgBIAGAAIAAAVIASAAIAAAKIgSAAIAAAlQAAAEACACQAAAAABAAQAAABABAAQAAAAABAAQABAAABAAIACAAIACgBIACAAIABgBIACABIAEAHQgDADgFABIgJACQgHAAgEgEg");
	this.shape_43.setTransform(63.2,-13.05);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgDgdIgDgCIgBgDIgBgEIABgDIABgDIADgCIADgBIADABIADACIADADIABADIgBAEIgDADIgDACIgDABIgDgBg");
	this.shape_44.setTransform(59.15,-13.525);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_45.setTransform(50.775,-12.125);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_46.setTransform(43.425,-12.075);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgDgdIgDgCIgBgDIgBgEIABgDIABgDIADgCIADgBIADABIAEACIACADIABADIgBAEIgCADIgEACIgDABIgDgBg");
	this.shape_47.setTransform(38.1,-13.525);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAgmIgHAAIgCAAIgBgCIAAgGIAKgCIAEgSIABgCIACgBIAGAAIAAAVIATAAIAAAKIgTAAIAAAlQAAAEACACQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAIAEAAIABgBIACAAIABgBIACABIAEAHQgDADgFABIgJACQgHAAgEgEg");
	this.shape_48.setTransform(34.2,-13.05);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgIAgQgGgCgEgFQgEgEgCgGQgCgHAAgIQAAgGACgHQACgGAEgEQAEgFAGgCQAGgDAGAAQAIAAAFACQAGADAEAEIgEAFIgBABIgCABIgCgBIgDgCIgEgCIgGAAQgEAAgDABQgDACgDADIgDAHQgBAFAAAEQAAAGABAEQABAEADADIAFAFQADABAEAAIAGgBIAEgCIADgCIADgBQAAAAABAAQAAAAABABQAAAAAAAAQAAAAABABIADAFIgFAFIgGADIgHACIgHAAQgFAAgFgCg");
	this.shape_49.setTransform(28.775,-12.075);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgPAgQgEgCgDgDQgDgDgBgFQgBgFAAgFIAAgqIAOAAIAAAqQAAAGADAEQADAEAGAAQAEAAAEgCQAEgCADgEIAAgwIAOAAIAABCIgIAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgBgGIgEAEIgFADIgGACIgFABQgGAAgEgCg");
	this.shape_50.setTransform(21.925,-12.025);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgOAhQgEgBgDgCQgCgCgBgEQgCgDAAgFQAAgDADgEQACgEAEgDQAEgCAJgBQAGgCAMAAIAAgFQAAgHgDgDQgEgEgFAAIgGABIgFACIgEACIgDABIgDAAIgBgCIgCgFQALgKAOAAQAGAAAFACQAEABADAEQADADABAFQACAEAAAGIAAApIgGAAIgEAAIgBgDIgCgFIgEAEIgFADIgFACIgHAAIgHgBgAABAFIgHADIgFADQAAABgBAAQAAABAAAAQAAABAAABQAAAAgBABIABAEIACADIAEABIADABQAFAAAEgCIAIgGIAAgNIgNABg");
	this.shape_51.setTransform(14.85,-12.075);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgGAoQgFgFAAgJIAAgmIgHAAIgCAAIgBgCIAAgGIAKgCIAEgSIABgCIACgBIAGAAIAAAVIATAAIAAAKIgTAAIAAAlQAAAEACACQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAIAEAAIACgBIABAAIABgBIACABIAEAHQgDADgFABIgJACQgHAAgEgEg");
	this.shape_52.setTransform(6.3,-13.05);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_53.setTransform(0.275,-12.125);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgKAgQgFgCgFgFQgEgEgDgHQgCgHAAgHQAAgHACgGQACgGAEgFQAFgEAFgCQAGgDAGAAQAHAAAFACQAFACAEAEQAEAEACAFQACAGAAAHIgBADIgCABIgqAAIACAKQABAEADADQACADAEABQADABADAAIAIgBIAFgCIADgCIADgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAEAFIgGAFIgGADIgIACIgHAAQgGAAgGgCgAARgGIgBgHIgDgFIgFgEIgGgBQgHAAgEAEQgFAFgBAIIAgAAIAAAAg");
	this.shape_54.setTransform(-6.825,-12.075);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgGAwIAAhfIANAAIAABfg");
	this.shape_55.setTransform(-11.875,-13.55);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgCgdIgDgCIgDgDIgBgEIABgDIADgDIADgCIACgBIAEABIACACIACADIABADIgBAEIgCADIgCACIgEABIgCgBg");
	this.shape_56.setTransform(-15.05,-13.525);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgHAiIgGgCIgGgDIgEgDIADgFIACgCIACAAIADABIADACIAEABIAGABIAFAAIADgCIADgDIAAgEQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIgEgDIgFgCIgFgCIgHgCIgFgDIgEgFQgBgDAAgEQAAgEABgEIAFgGIAIgFQAEgBAFAAQAHAAAFACQAGACADAEIgDAFIgBABIgBABIgDgBIgDgCIgEgBIgGgBIgDABIgEACIgCACIgBAEIABADIAEADIAFACIAGACIAGADIAFACQADACABADQABADAAAEQAAAEgBAEQgCAEgDADQgDADgFACQgFABgFAAg");
	this.shape_57.setTransform(-19.525,-12.075);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AAOAiIAAgpQAAgHgDgEQgDgEgGAAQgEAAgEADQgEACgDADIAAAwIgOAAIAAhCIAIAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIABAGIAEgEIAFgDIAFgCIAGgBQAGAAAEACIAHAFIAEAIQABAFAAAGIAAApg");
	this.shape_58.setTransform(-29.075,-12.125);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgMAgQgGgDgFgEQgEgFgCgGQgCgGAAgIQAAgHACgGQACgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAEAEQAFAFACAGQACAGAAAHQAAAIgCAGQgCAGgFAFQgEAEgGADQgGACgHAAQgGAAgGgCgAgNgQQgEAGAAAKQAAALAEAGQAFAGAIAAQAJAAAEgGQAFgGAAgLQAAgKgFgGQgEgGgJAAQgIAAgFAGg");
	this.shape_59.setTransform(-36.425,-12.075);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgOAuQgFgCgDgEQgEgEgBgHQgCgGAAgJQAAgHACgGQACgFADgFQAEgFAFgCQAGgDAGAAQAFAAAFACQAEABADAEIAAgkIAOAAIAABgIgJAAQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgCgHQgEAEgFAEQgFADgGAAQgGgBgEgCgAgKgCQgEAFAAALIAAALQABAEACADIAFAEIAGABQAFAAAEgCIAHgGIAAgfQgDgDgDgBQgEgCgEAAQgHAAgFAGg");
	this.shape_60.setTransform(-47.15,-13.5);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgGAwIAAhCIANAAIAABCgAgCgdIgEgCIgCgDIAAgEIAAgDIACgDIAEgCIACgBIADABIAEACIACADIAAADIAAAEIgCADIgEACIgDABIgCgBg");
	this.shape_61.setTransform(-52.25,-13.525);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AghAvIAAhdIAfAAQAIAAAHACQAGACAEADQAEADACAFQACAEAAAGIgBAGIgDAGIgFAFQgEACgEABQAUAEAAARQAAAGgCAFQgCAFgFADQgEAEgGACQgHACgIAAgAgSAjIASAAIAJgBIAGgEQACgCABgDIABgGQAAgGgEgEQgFgEgKAAIgSAAgAgSgFIAQAAQAJAAAEgDQAFgEAAgHQAAgIgEgEQgFgDgJAAIgQAAg");
	this.shape_62.setTransform(-57.8,-13.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.3,-23.6,280.3,35.2);


(lib.t3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AArAyIAAgzQAAgGgDgDQgEgEgEAAQgFAAgDAEQgDADAAAGIAAAzIgoAAIAAgzQAAgGgDgDQgEgEgEAAQgFAAgDAEQgDADAAAGIAAAzIgpAAIAAhhIApAAIAAANQALgPASAAQAUAAAIAQQAOgQAUAAQAPAAAKAJQAIAKABAQIAABAg");
	this.shape.setTransform(188.35,-21.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag3BBIAAh/IApAAIAAANQAGgHAFgDQAHgFAKAAQASAAAMAOQAMAPAAAWIAAAAQAAAWgMAPQgMAOgSAAQgQAAgMgNIAAAogAgKgZQgFAFAAAHIAAABQAAAHAFAFQAEAEAGAAQAHAAAFgEQAFgFAAgHIAAgBQAAgHgFgFQgFgFgHAAQgGAAgEAFg");
	this.shape_1.setTransform(173.475,-20.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgGBAIAAhZIgUAEIgIgfIAlgLIAgAAIAAB/g");
	this.shape_2.setTransform(163.025,-22.95);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeARIAAghIA9AAIAAAhg");
	this.shape_3.setTransform(151.525,-22.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAqAyIAAgzQAAgGgCgDQgDgEgFAAQgFAAgDAEQgEADABAGIAAAzIgpAAIAAgzQAAgGgCgDQgDgEgFAAQgFAAgDAEQgEADABAGIAAAzIgqAAIAAhhIAqAAIAAANQAMgPARAAQAUAAAIAQQAOgQAUAAQAPAAAKAJQAIAKABAQIAABAg");
	this.shape_4.setTransform(134.45,-21.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpArQgJgIAAgOIAAgBQAAgOAKgHQAKgIASAAQAOAAAIADIAAgBQAAgOgRAAQgOAAgNAFIgHgbQASgHAXAAQAbAAANANQAKAKAAAVIAAA3IgoAAIAAgKQgLAMgQAAQgPAAgJgIgAgHAKQgDADgBAFQAAAEADADQADACAEAAQAEAAAEgEQADgEABgHIAAgEQgFgBgFAAQgFAAgDADg");
	this.shape_5.setTransform(119.9,-21.475);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGBAIAAhZIgUAEIgIgfIAlgLIAgAAIAAB/g");
	this.shape_6.setTransform(110.375,-22.95);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgGBAIAAhZIgUAEIgIgfIAlgLIAgAAIAAB/g");
	this.shape_7.setTransform(102.825,-22.95);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVAWQATgDAAgNIgRAAIAAgpIApAAIAAAhQAAATgLAKQgKAJgSAAg");
	this.shape_8.setTransform(92.325,-17.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AglAzQgQgRAAgeIAAgBQAAgdAPgTQARgTAdAAQAZAAATANIgSAbQgNgIgMgBQgSAAgDAZQAMgLAQAAQAPAAALAKQAMAKAAARIAAABQAAAWgPAMQgPAMgWAAQgYAAgPgOgAgJALQgDAEAAAGIAAAAQAAAGAEAFQAEAEAFgBQAGABAEgEQADgFAAgGIAAAAQAAgGgEgEQgEgEgGAAQgFAAgEAEg");
	this.shape_9.setTransform(83.925,-22.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGBAIAAhZIgUAEIgIgfIAlgLIAgAAIAAB/g");
	this.shape_10.setTransform(73.775,-22.95);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag3A2IAMgcQALAGAHAAQADAAADgCIgmhdIAqAAIAQA0IAQg0IApAAIgiBbQgHATgJAJQgJAIgQAAQgUAAgSgKg");
	this.shape_11.setTransform(60.075,-20.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgpArQgJgIABgOIAAgBQgBgOAKgHQAKgIASAAQAOAAAIADIAAgBQAAgOgRAAQgNAAgOAFIgHgbQASgHAXAAQAbAAANANQALAKgBAVIAAA3IgoAAIAAgKQgLAMgQAAQgPAAgJgIgAgHAKQgEADAAAFQAAAEADADQADACAEAAQAFAAADgEQADgEABgHIAAgEQgFgBgFAAQgFAAgDADg");
	this.shape_12.setTransform(49.15,-21.475);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAdA/IAAg/IgdAtIAAAAIgcgtIAAA/IgqAAIAAh9IAsAAIAaAsIAbgsIAsAAIAAB9g");
	this.shape_13.setTransform(36.05,-22.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag3A2IAMgcQALAGAHAAQADAAADgCIgmhdIAqAAIAQA0IAQg0IApAAIgiBbQgHATgJAJQgJAIgQAAQgUAAgSgKg");
	this.shape_14.setTransform(17.875,-20.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgpArQgJgIAAgOIAAgBQAAgOAKgHQAKgIASAAQAOAAAIADIAAgBQAAgOgRAAQgOAAgNAFIgHgbQASgHAXAAQAbAAANANQAKAKAAAVIAAA3IgoAAIAAgKQgLAMgQAAQgPAAgJgIgAgHAKQgDADgBAFQAAAEADADQADACAEAAQAEAAAEgEQADgEABgHIAAgEQgFgBgFAAQgFAAgDADg");
	this.shape_15.setTransform(6.95,-21.475);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgrA0QgMgOAAgWIAAgBQAAgVAMgPQAMgOARAAQARAAAMAOIAAgtIApAAIAACDIgpAAIAAgNQgGAIgGACQgGAFgKAAQgSAAgMgPgAgLADQgEAEgBAIIAAAAQABAIAEAFQAEAFAHAAQAGAAAFgFQAFgFAAgIIAAAAQAAgHgFgFQgFgFgGAAQgHAAgEAFg");
	this.shape_16.setTransform(-4.55,-23.05);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgjAyIAAhhIAoAAIAAAUQAJgWAWAAIAAAsIgFAAQgaAAAAAeIAAAZg");
	this.shape_17.setTransform(-13.95,-21.6006);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgqAoQgJgJAAgRIAAhAIAoAAIAAA0QAAAFAEAEQADAEAEgBQAEABAEgEQADgEAAgFIAAg0IApAAIAABiIgpAAIAAgNQgLAPgSAAQgPAAgJgKg");
	this.shape_18.setTransform(-23.975,-21.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgZAcIAAgiIgMAAIAAgfIAMAAIAAgYIAoAAIAAAYIAXAAIAAAfIgXAAIAAAZQAAAKAKgBQAFAAAHgCIAAAfQgKAFgQABQgkgBAAgig");
	this.shape_19.setTransform(-33.775,-22.65);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgpArQgIgIgBgOIAAgBQABgOAJgHQALgIARAAQANAAAJADIAAgBQAAgOgRAAQgNAAgOAFIgIgbQAUgHAWAAQAbAAANANQALAKAAAVIAAA3IgpAAIAAgKQgLAMgQAAQgPAAgJgIgAgIAKQgCADAAAFQAAAEACADQADACAEAAQAFAAADgEQADgEAAgHIAAgEQgEgBgFAAQgFAAgEADg");
	this.shape_20.setTransform(-43.25,-21.475);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("Ag7AsIAWgaQAUAOAYAAQAKAAAAgGQAAgEgRgEQgZgFgLgHQgQgKAAgRIAAgBQAAgSAOgMQAOgMAYAAQAjAAAWARIgUAdQgRgNgUAAQgJAAAAAFIAAAAQAAAFAPADQAbAFAMAIQAPAJAAATQAAATgPAMQgPALgZAAQgoAAgYgVg");
	this.shape_21.setTransform(-54.825,-22.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.3,-33,299.3,22);


(lib.t2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPAnQgIgCgFgGQgFgFgDgJQgDgHAAgKQAAgJADgHQADgIAFgGQAFgFAIgDQAHgDAIAAQAJAAAHADQAIADAFAFQAFAGADAIQADAHAAAJQAAAKgDAHQgDAJgFAFQgFAGgIACQgHADgJAAQgIAAgHgDgAgQgUQgFAHAAANQAAAOAFAIQAGAGAKABQALgBAFgGQAGgIAAgOQAAgNgGgHQgFgIgLAAQgKAAgGAIg");
	this.shape.setTransform(157.825,2.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIA7IAAhRIARAAIAABRgAgEgkIgDgCIgDgEIgBgEIABgFIADgEIADgCIAEgBIAEABIAEACIADAEIABAFIgBAEIgDAEIgEACIgEABIgEgBg");
	this.shape_1.setTransform(151.3,0.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSA5QgGgDgEgFQgEgFgCgIQgCgIAAgKQAAgJACgIQADgGAEgGQAFgGAGgDQAHgDAIAAQAHAAAEACQAGACADAEIAAgsIASAAIAAB2IgLAAQgDAAgBgEIgCgIQgFAGgGADQgHAEgIAAQgGAAgGgDgAgMgDQgGAHAAAOIABANQACAFACAEQACADADACQAEABAEAAQAGAAAFgDQAEgDAEgFIAAglQgDgEgFgCQgDgCgGAAQgJAAgFAHg");
	this.shape_2.setTransform(144.6,0.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSAnQgGgCgDgFQgDgEgCgFQgCgGAAgGIAAg0IARAAIAAA0QAAAHAEAFQAEAFAIAAQAEAAAFgDQAFgDAEgEIAAg7IASAAIAABRIgLAAQgDAAgBgDIgCgIIgEAFIgHAEIgHACIgGABQgHABgFgDg");
	this.shape_3.setTransform(135.8,2.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIAxQgGgGAAgKIAAgvIgJAAIgCgBIgBgDIAAgHIANgCIAEgXIABgDIADgBIAHAAIAAAbIAXAAIAAANIgXAAIAAAtQAAAEADADQACADADAAIAEgBIACgCIACgBIACAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIAFAJQgEADgFADQgGABgGAAQgJAAgFgFg");
	this.shape_4.setTransform(128.575,1.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLA6IgKgEIgJgEIgHgGIAFgJIACgCIACAAIAEABIAGAEIAIAEQAEACAGAAQAJAAAGgGQAGgEAAgJQAAgFgDgDIgGgGIgJgDIgIgDIgKgEQgFgBgEgDIgGgJQgDgGAAgIQAAgGADgFQACgGAFgFQAFgEAHgDQAGgDAIAAQAKAAAIADQAJAEAGAFIgFAJIgCACIgCABIgDgCIgFgCIgHgDQgDgCgGAAIgHABIgGAEQgDACgBADQgBADAAADQAAAFACADIAGAFIAIAEIAKACIAKAFIAJAEQADAEADAFQACAFAAAHQAAAIgDAGQgCAHgFAFQgFAFgIADQgHADgIAAQgGAAgFgBg");
	this.shape_5.setTransform(121.125,1.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMAoQgHgDgFgGQgGgFgDgJQgDgIAAgKQAAgIADgHQADgIAFgFQAFgGAHgDQAHgDAIAAQAHAAAHACQAGADAFAFQAEAFADAGQADAHAAAJQAAAEgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAIg0AAIACAMQACAEADAEQADAEAFABQAEACAEAAIAJgBIAGgDIAFgCIADgCQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAIAFAGQgDAEgEACIgIAFIgJABIgJABQgIAAgHgCgAAVgIQAAgEgBgEQgBgEgDgCQgCgDgEgCQgDgBgFgBQgIABgGAFQgFAGgBAJIAnAAIAAAAg");
	this.shape_6.setTransform(108.725,2.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AASA7IAAg0QAAgHgEgEQgEgFgIAAQgEAAgFADQgFACgFAEIAAA7IgRAAIAAh1IARAAIAAAuQAFgFAHgDQAFgDAHAAQAHAAAFADQAFACAEAEQADAEACAGQACAEAAAHIAAA0g");
	this.shape_7.setTransform(100.025,0.875);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgIAxQgGgGAAgKIAAgvIgJAAIgCgBIgBgDIAAgHIANgCIAEgXIABgDIADgBIAHAAIAAAbIAXAAIAAANIgXAAIAAAtQAAAEADADQACADADAAIAEgBIACgCIACgBIACAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIAFAJQgEADgFADQgGABgGAAQgJAAgFgFg");
	this.shape_8.setTransform(92.725,1.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMAoQgHgDgFgGQgGgFgDgJQgDgIAAgKQAAgIADgHQADgIAFgFQAFgGAHgDQAHgDAIAAQAHAAAHACQAGADAFAFQAEAFADAGQADAHAAAJQAAAEgBAAQgBAAAAABQAAAAAAAAQgBAAAAAAQgBABAAAAIg0AAIACAMQACAEADAEQADAEAFABQAEACAEAAIAJgBIAGgDIAFgCIADgCQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAIAFAGQgDAEgEACIgIAFIgJABIgJABQgIAAgHgCgAAVgIQAAgEgBgEQgBgEgDgCQgCgDgEgCQgDgBgFgBQgIABgGAFQgFAGgBAJIAnAAIAAAAg");
	this.shape_9.setTransform(81.575,2.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSA5QgGgDgDgFQgFgFgCgIQgCgIAAgKQAAgJACgIQADgGAEgGQAFgGAGgDQAHgDAJAAQAGAAAEACQAGACADAEIAAgsIASAAIAAB2IgLAAQgDAAgBgEIgCgIQgFAGgGADQgHAEgIAAQgGAAgGgDgAgMgDQgGAHAAAOIABANQACAFACAEQACADADACQAEABAEAAQAGAAAFgDQAEgDAEgFIAAglQgDgEgFgCQgDgCgGAAQgJAAgFAHg");
	this.shape_10.setTransform(72.6,0.925);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIA7IAAhRIARAAIAABRgAgEgkIgDgCIgDgEIgBgEIABgFIADgEIADgCIAEgBIAEABIAEACIADAEIABAFIgBAEIgDAEIgEACIgEABIgEgBg");
	this.shape_11.setTransform(66.35,0.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgJApIgIgCIgGgDIgGgEIAEgHIACgBIADgBIADABIAEACIAFADIAIABIAGgBIAEgDIADgDIABgFQAAgDgCgCIgFgDIgGgDIgHgCIgHgDIgHgDIgFgHQgBgDAAgGQAAgFACgEQACgFADgDQAEgDAGgCQAFgCAHAAQAIAAAHADQAGACAFAFIgEAGIgCACIgBAAIgDgBIgEgCIgFgCIgHAAIgFAAIgEACIgDAEIgBAEQAAADACACQABACADABIAGACIAHADIAIADQAEABACACIAFAGQACADAAAFQAAAGgCAFQgCAFgEADQgEAEgGACQgGACgHAAg");
	this.shape_12.setTransform(60.825,2.725);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgIAxQgGgGAAgKIAAgvIgJAAIgCgBIgBgDIAAgHIANgCIAEgXIABgDIADgBIAHAAIAAAbIAXAAIAAANIgXAAIAAAtQAAAEADADQACADADAAIAEgBIACgCIACgBIACAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAIAFAJQgEADgFADQgGABgGAAQgJAAgFgFg");
	this.shape_13.setTransform(54.625,1.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgSAnQgGgCgDgFQgDgEgCgFQgCgGAAgGIAAg0IASAAIAAA0QAAAHADAFQAEAFAIAAQAFAAAFgDQAEgDAFgEIAAg7IARAAIAABRIgKAAQgEAAgBgDIgBgIIgGAFIgFAEIgHACIgHABQgHABgFgDg");
	this.shape_14.setTransform(47.1,2.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgWA3QgLgFgIgIQgHgHgEgLQgFgLAAgNQAAgMAFgKQAEgLAHgIQAIgIALgEQAKgFAMAAQANAAALAFQAKAEAIAIQAHAIAEALQAFAKAAAMQAAANgFALQgEALgHAHQgIAIgKAFQgLAEgNAAQgMAAgKgEgAgPgnQgHADgFAGQgFAFgDAIQgCAIAAAJQAAAKACAIQADAIAFAGQAFAFAHADQAHADAIAAQAJAAAHgDQAHgDAFgFQAFgGADgIQADgIAAgKQAAgJgDgIQgDgIgFgFQgFgGgHgDQgHgDgJAAQgIAAgHADg");
	this.shape_15.setTransform(36.225,1.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgJApIgIgCIgGgDIgGgEIAEgHIACgBIADgBIADABIAEACIAFADIAIABIAGgBIAEgDIADgDIABgFQAAgDgCgCIgFgDIgGgDIgHgCIgHgDIgHgDIgFgHQgBgDAAgGQAAgFACgEQACgFADgDQAEgDAGgCQAFgCAHAAQAIAAAHADQAGACAFAFIgEAGIgCACIgBAAIgDgBIgEgCIgFgCIgHAAIgFAAIgEACIgDAEIgBAEQAAADACACQABACADABIAGACIAHADIAIADQAEABACACIAFAGQACADAAAFQAAAGgCAFQgCAFgEADQgEAEgGACQgGACgHAAg");
	this.shape_16.setTransform(22.325,2.725);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgTA3QgIgEgGgGQgGgHgEgIQgDgJAAgKIAAhEIATAAIAABEQAAAHACAFQACAGADAEQAEAEAFACQAFADAGAAQAHAAAFgDQAFgCAEgEQADgEACgFQACgGAAgHIAAhEIATAAIAABEQAAAKgEAJQgDAIgGAHQgGAGgJAEQgIADgLAAQgKAAgJgDg");
	this.shape_17.setTransform(13.025,1.125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AASAqIAAgzQAAgJgEgEQgEgFgIAAQgEAAgFADQgFADgFAEIAAA7IgRAAIAAhRIALAAQADAAABADIABAIIAGgFIAGgEIAGgDIAHgBQAHAAAFADQAFACAEAEQADAEACAGQACAFAAAIIAAAzg");
	this.shape_18.setTransform(-1.275,2.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgIA7IAAhRIAQAAIAABRgAgEgkIgEgCIgCgEIgBgEIABgFIACgEIAEgCIAEgBIAEABIAEACIADAEIABAFIgBAEIgDAEIgEACIgEABIgEgBg");
	this.shape_19.setTransform(-7.75,0.925);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgPAnQgIgCgFgGQgFgFgDgJQgDgHAAgKQAAgJADgHQADgIAFgGQAFgFAIgDQAHgDAIAAQAJAAAHADQAIADAFAFQAFAGADAIQADAHAAAJQAAAKgDAHQgDAJgFAFQgFAGgIACQgHADgJAAQgIAAgHgDgAgQgUQgFAHAAANQAAAOAFAIQAGAGAKABQALgBAFgGQAGgIAAgOQAAgNgGgHQgFgIgLAAQgKAAgGAIg");
	this.shape_20.setTransform(-14.275,2.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgRA6IgJgCIABgLIABgDIADgBIAEABIAGAAQAFAAAEgBQACgCADgDQADgDABgFQABgEAAgHIAAhKIATAAIAABJQAAAKgDAIQgCAHgFAGQgEAFgHADQgGADgJAAg");
	this.shape_21.setTransform(-22.775,1.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.3,-11,299.3,23.2);


(lib.t1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FECA00").s().p("AhRBUIAAinIBAAAQAwAAAaAWQAZAWAAAmIAAABQAAAmgZAWQgbAYgxAAgAgZAjIAJAAQAqAAAAgjIAAAAQAAgigqAAIgJAAg");
	this.shape.setTransform(192.375,26.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FECA00").s().p("AASBUIgegwIgNAAIAAAwIg4AAIAAinIBRAAQApAAAUATQAPAPAAAZIAAABQAAAighAQIAnA5gAgZgDIAZAAQAUAAAAgRIAAAAQAAgQgUAAIgZAAg");
	this.shape_1.setTransform(175.2,26.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FECA00").s().p("AhAA+QgbgZAAglIAAAAQAAgjAbgaQAbgZAlAAQAnAAAbAZQAaAZAAAkIAAAAQAAAkgbAaQgaAagngBQgmABgagagAgYgaQgKALAAAPIAAAAQAAAPAKALQAKAMAOAAQAQAAAKgMQAJgKAAgQIAAAAQAAgOgJgMQgKgLgQAAQgPAAgJALg");
	this.shape_2.setTransform(156.325,26.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FECA00").s().p("AAdBVIgdhUIgcBUIgyAAIg3ioIA8AAIAXBQIAbhRIAwAAIAbBRIAYhQIA6AAIg3Cog");
	this.shape_3.setTransform(134.25,26.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FECA00").s().p("AhRBUIAAinIBAAAQAwAAAaAWQAZAWAAAmIAAABQAAAmgZAWQgbAYgxAAgAgZAjIAJAAQAqAAAAgjIAAAAQAAgigqAAIgJAAg");
	this.shape_4.setTransform(106.075,26.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FECA00").s().p("AhHBUIAAinICOAAIAAAuIhXAAIAAARIBRAAIAAAnIhRAAIAAATIBYAAIAAAug");
	this.shape_5.setTransform(89.125,26.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FECA00").s().p("Ag4A/QgbgYAAgnIAAAAQgBglAbgZQAagZAnABQApAAAeAZIggAmQgRgPgUAAQgPAAgLALQgLAMAAAPIAAABQAAASAMALQALALARAAQALAAAIgEIAAgQIgdAAIAAgjIBSAAIAABMQggAagrgBQgnABgbgZg");
	this.shape_6.setTransform(71.9,26.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FECA00").s().p("Ag3A/QgdgYAAgnIAAAAQAAglAbgZQAbgZAnABQApAAAdAZIggAmQgRgPgUAAQgQAAgKALQgKAMAAAPIAAABQgBASAMALQALALAQAAQANAAAGgEIAAgQIgcAAIAAgjIBRAAIAABMQgeAagsgBQgnABgagZg");
	this.shape_7.setTransform(53.85,26.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FECA00").s().p("AhHBUIAAinICOAAIAAAuIhXAAIAAARIBRAAIAAAnIhRAAIAAATIBYAAIAAAug");
	this.shape_8.setTransform(37.325,26.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FECA00").s().p("AhDBUIAAinIA4AAIAAB3IBOAAIAAAwg");
	this.shape_9.setTransform(22.15,26.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FECA00").s().p("AgpAWIAAgrIBTAAIAAArg");
	this.shape_10.setTransform(9.575,27.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FECA00").s().p("AASBUIgfgwIgMAAIAAAwIg4AAIAAinIBRAAQApAAAUATQAPAPAAAZIAAABQAAAighAQIAnA5gAgZgDIAZAAQAUAAAAgRIAAAAQAAgQgUAAIgZAAg");
	this.shape_11.setTransform(-3.3,26.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FECA00").s().p("AhSAHIAAhcIA5AAIAABbQAAAeAZAAQAaAAAAgdIAAhcIA5AAIAABbQAABQhTAAQhSAAAAhPg");
	this.shape_12.setTransform(-21.525,26.975);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FECA00").s().p("AhAA+QgbgZAAglIAAAAQAAgjAbgaQAbgZAlAAQAnAAAbAZQAaAZAAAkIAAAAQAAAkgbAaQgaAagngBQgmABgagagAgYgaQgKALAAAPIAAAAQAAAPAKALQAKAMAOAAQAQAAAKgMQAJgKAAgQIAAAAQAAgOgJgMQgKgLgQAAQgPAAgJALg");
	this.shape_13.setTransform(-40.375,26.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FECA00").s().p("AhFBUIAAinICLAAIAAAwIhTAAIAAAWIBOAAIAAAqIhOAAIAAA3g");
	this.shape_14.setTransform(-57.475,26.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FECA00").s().p("AAmBUIgJgWIg6AAIgJAWIg7AAIBGioIA3AAIBHCogAAPAWIgPgnIgPAnIAeAAg");
	this.shape_15.setTransform(118.9,0.75);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FECA00").s().p("AhPA7IAegkQAaAUAgAAQAOAAAAgIIAAAAQAAgHgXgEQghgHgQgKQgVgMAAgYIAAgBQAAgZASgPQAUgQAgAAQAvAAAdAXIgbAmQgXgQgbAAQgMgBAAAHIAAAAQAAAHAWAFQAjAGAQALQAUAMAAAYIAAAAQAAAbgUAPQgUAPgiAAQg1AAgggcg");
	this.shape_16.setTransform(94.925,0.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FECA00").s().p("AgbBUIAAinIA3AAIAACng");
	this.shape_17.setTransform(83.55,0.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FECA00").s().p("AhHBUIAAinICOAAIAAAuIhXAAIAAARIBRAAIAAAoIhRAAIAAASIBYAAIAAAug");
	this.shape_18.setTransform(65.925,0.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FECA00").s().p("AgaBUIhEinIA+AAIAhBdIAghdIA+AAIhECng");
	this.shape_19.setTransform(48.55,0.85);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FECA00").s().p("AhAA+QgbgZAAglIAAAAQAAgkAbgZQAbgZAlAAQAnAAAbAZQAaAZAAAkIAAAAQAAAlgbAZQgaAagngBQgmAAgagZgAgYgaQgKALAAAPIAAAAQAAAQAKAKQAKAMAOAAQAQAAAKgMQAJgKAAgQIAAAAQAAgOgJgMQgKgLgQAAQgPAAgJALg");
	this.shape_20.setTransform(30.625,0.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FECA00").s().p("AhCBUIAAinIA3AAIAAB3IBPAAIAAAwg");
	this.shape_21.setTransform(14.85,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.3,-12,298.3,54);


(lib.logo_r = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.LOGO_R();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.LOGO();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.img1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IMG1();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.doted = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCA00").s().p("AHVALQgEgFAAgGQAAgFAEgFQAFgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgFgEgAGaALQgFgFAAgGQAAgFAFgFQAEgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgEgEgAFeALQgFgFAAgGQAAgFAFgFQAEgEAGAAQAGAAAEAEQAFAFAAAFQAAAGgFAFQgEAEgGAAQgGAAgEgEgAEhALQgEgFAAgGQAAgFAEgFQAFgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgFgEgADmALQgFgFAAgGQAAgFAFgFQAEgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgEgEgACqALQgFgFAAgGQAAgFAFgFQAEgEAGAAQAGAAAEAEQAFAFAAAFQAAAGgFAFQgEAEgGAAQgGAAgEgEgABtALQgEgFAAgGQAAgFAEgFQAFgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgFgEgAAyALQgFgFAAgGQAAgFAFgFQAEgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgEgEgAgJALQgFgFAAgGQAAgFAFgFQAEgEAFAAQAGAAAEAEQAFAFAAAFQAAAGgFAFQgEAEgGAAQgFAAgEgEgAhGALQgEgFAAgGQAAgFAEgFQAFgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgFgEgAiBALQgFgFAAgGQAAgFAFgFQAEgEAGAAQAGAAAEAEQAFAFAAAFQAAAGgFAFQgEAEgGAAQgGAAgEgEgAi9ALQgFgFAAgGQAAgFAFgFQAEgEAGAAQAGAAAEAEQAFAFAAAFQAAAGgFAFQgEAEgGAAQgGAAgEgEgAj6ALQgEgFAAgGQAAgFAEgFQAFgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgFgEgAk1ALQgFgFAAgGQAAgFAFgFQAEgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgEgEgAlyALQgEgFAAgGQAAgFAEgFQAFgEAGAAQAGAAAEAEQAFAFAAAFQAAAGgFAFQgEAEgGAAQgGAAgFgEgAmuALQgEgFAAgGQAAgFAEgFQAFgEAGAAQAGAAAFAEQAEAFAAAFQAAAGgEAFQgFAEgGAAQgGAAgFgEgAnpALQgFgFAAgGQAAgFAFgFQAEgEAGAAQAGAAAEAEQAFAFAAAFQAAAGgFAFQgEAEgGAAQgGAAgEgEg");
	this.shape.setTransform(7.8,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-41.7,-1.5,99,3);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgKAiQgGgCgFgFQgFgFgCgHQgDgHAAgIQAAgIADgGQACgHAEgEQAEgFAHgDQAGgDAHAAQAGAAAGADQAFACAEAEQAEAEACAGQADAGAAAHIgBAEIgCABIguAAIACALQABAFADADQADADAEABQAEACAEAAIAHgBIAGgCIAEgDIADgBQABAAAAAAQAAAAABABQAAAAAAAAQABAAAAABIAEAFIgGAFIgHADIgIACIgIABQgGAAgGgDgAATgHIgBgHQgBgEgCgCQgCgDgEgBIgHgBQgIAAgFAEQgEAFgCAJIAkAAIAAAAg");
	this.shape.setTransform(27.025,1.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgTAkIAAhGIAIAAIADABIAAADIABAKQAEgHAEgEQAFgEAGAAIAFAAIADACIgBAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgDAAIgEgBIgGABIgEADIgDAFIgDAGIAAArg");
	this.shape_1.setTransform(21.2,1.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgNAiQgGgCgFgFQgEgFgDgHQgCgGAAgJQAAgHACgHQADgHAEgFQAFgEAGgDQAGgDAHAAQAIAAAGADQAHADAEAEQAFAFACAHQACAHAAAHQAAAJgCAGQgCAHgFAFQgEAFgHACQgGADgIAAQgHAAgGgDgAgOgSQgFAHAAALQAAANAFAGQAFAHAJAAQAKAAAFgHQAFgGAAgNQAAgLgFgHQgFgHgKAAQgJAAgFAHg");
	this.shape_2.setTransform(14.225,1.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAoAyIAAhGIAAgEIAAgDIghA8QgCADgEAAIgBAAQgDAAgCgDIgig9IAAAIIAABGIgNAAIAAhjIALAAIADAAIACACIAiA7IACAEIAAAEIAEgIIAhg7IACgCIADAAIALAAIAABjg");
	this.shape_3.setTransform(3.725,0.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AARAkIAAgsQAAgIgEgEQgEgEgHAAQgEAAgFACQgFADgDAEIAAAzIgOAAIAAhGIAIAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIABAHIAEgFIAGgDIAGgCIAGgBQAGAAAFACQAEACADADQADAEACAFQABAFAAAGIAAAsg");
	this.shape_4.setTransform(-10.15,1.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgUAkIAAhGIAIAAIADABIACADIABAKQADgHAEgEQAEgEAIAAIAEAAIAEACIgBAKQgBABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgDAAIgEgBIgGABIgEADIgDAFIgDAGIAAArg");
	this.shape_5.setTransform(-16.2,1.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgPAkQgDgBgDgDIgFgGQgBgDAAgFQgBgEADgEQADgEAEgDQAFgDAJgBQAHgCANAAIAAgGQgBgIgDgEQgEgEgGAAIgHABIgFADIgEACIgDACIgCgBIgCgCIgDgEQAGgGAHgDQAHgDAHAAQAGAAAGACQAEACADAEQADADACAFQACAFgBAGIAAAtIgFAAIgEgBIgBgCIgBgHIgGAFIgFADIgGACIgHABIgIgBgAABAFIgJADQgDACgBACQgCACAAADIABAFIACADIADACIAFAAIAFAAIAFgCIAEgDIAFgEIAAgOIgPABg");
	this.shape_6.setTransform(-22.9,1.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgKAiQgGgCgFgFQgFgFgCgHQgDgHAAgIQAAgIADgGQACgHAEgEQAEgFAHgDQAGgDAHAAQAGAAAGADQAFACAEAEQAEAEACAGQADAGAAAHIgBAEIgCABIguAAIACALQABAFADADQADADAEABQAEACAEAAIAHgBIAGgCIAEgDIADgBQABAAAAAAQAAAAABABQAAAAAAAAQAAAAABABIAEAFIgGAFIgHADIgIACIgIABQgGAAgGgDgAATgHIgBgHQgBgEgCgCQgCgDgEgBIgHgBQgIAAgFAEQgEAFgCAJIAkAAIAAAAg");
	this.shape_7.setTransform(-29.825,1.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgcAyIAAhjIAPAAIAABXIAqAAIAAAMg");
	this.shape_8.setTransform(-36.625,0.125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F6CC00").s().p("AnzCgIAAk/IPnAAIAAE/g");
	this.shape_9.setTransform(-5,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55,-16,100,32);


(lib.bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib._2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000F35").s().p("AqKJfIgGgEIgJgIQhThLgTifQgFgwgBgwQgChTAKhSQBroKFKipIARgIQFaiaH1HPIATASQC2CxAfCPQAKAzgGApQgKBAgvApQhgBNjcgMQglgFglgBQgbgBgbABQj0AKj6CqQgnAdgjAYQiZBlhmAAQg5AAgpgfg");
	this.shape.setTransform(0.0201,0.0015);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77.4,-63.8,154.8,127.6);


(lib._1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCA00").s().p("AqKJfIgGgEIgJgIQhThLgTifQgFgwgBgwQgChTAKhSQBroKFKipIARgIQFaiaH1HPIATASQC2CxAfCPQAKAzgGApQgKBAgvApQhgBNjcgMQglgFglgBQgbgBgbABQj0AKj6CqQgnAdgjAYQiZBlhmAAQg5AAgpgfg");
	this.shape.setTransform(0.0201,0.0015);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77.4,-63.8,154.8,127.6);


(lib.shape = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib._1("synched",0);
	this.instance.setTransform(0,-4.55,1.0043,1.0043);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_2
	this.instance_1 = new lib._2("synched",0);
	this.instance_1.setTransform(-2.5,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-79.9,-68.6,157.7,131.89999999999998);


// stage content:
(lib.KSFY_214866_MM_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(192));

	// cta
	this.instance = new lib.cta();
	this.instance.setTransform(234.95,275.95,1.2,1.2);
	this.instance.alpha = 0;
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.cta(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(68).to({_off:false},0).to({scaleX:0.9,scaleY:0.9,alpha:1},9,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,x:235,y:276},5).wait(110));

	// t4
	this.instance_1 = new lib.t4("synched",0);
	this.instance_1.setTransform(150,207.3,0.8,0.8,0,0,0,58.9,-6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(53).to({_off:false},0).to({scaleX:1,scaleY:1,x:150.05,y:207.35,alpha:1},14,cjs.Ease.get(1)).wait(125));

	// t3
	this.instance_2 = new lib.t3("synched",0);
	this.instance_2.setTransform(149.9,180.1,0.9,0.9,0,0,0,68.4,-21.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(39).to({_off:false},0).to({regY:-22,scaleX:1,scaleY:1,x:149.95,y:180.05,alpha:1},13,cjs.Ease.get(1)).wait(140));

	// doted
	this.instance_3 = new lib.doted("synched",0);
	this.instance_3.setTransform(140.4,157.85,1.8863,1,0,0,0,0.1,0);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(39).to({_off:false},0).to({regX:0,scaleX:1,x:140.2,alpha:1},13,cjs.Ease.get(1)).wait(140));

	// t2
	this.instance_4 = new lib.t2("synched",0);
	this.instance_4.setTransform(149.9,134.85,0.9,0.9,0,0,0,68.4,0.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(25).to({_off:false},0).to({scaleX:1,scaleY:1,x:149.95,alpha:1},13,cjs.Ease.get(1)).wait(154));

	// t1
	this.instance_5 = new lib.t1("synched",0);
	this.instance_5.setTransform(149.35,98.65,1.6235,1,0,0,0,67.8,15);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(25).to({_off:false},0).to({scaleX:1,alpha:1},13,cjs.Ease.get(1)).wait(154));

	// LOGO_png
	this.instance_6 = new lib.logo("synched",0);
	this.instance_6.setTransform(80,201);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(2).to({_off:false},0).to({y:300},9,cjs.Ease.get(1)).wait(181));

	// LOGO_R_png
	this.instance_7 = new lib.logo_r("synched",0);
	this.instance_7.setTransform(145,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(84).to({_off:false},0).to({x:80,alpha:1},13,cjs.Ease.get(1)).wait(95));

	// IMG1_png
	this.instance_8 = new lib.img1("synched",0);
	this.instance_8.setTransform(79.95,309.95,1.02,1.02);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(13).to({_off:false},0).to({scaleX:1,scaleY:1,x:80,y:300},11,cjs.Ease.get(1)).wait(168));

	// Layer_10
	this.instance_9 = new lib.shape("synched",0,false);
	this.instance_9.setTransform(151.2,547,1.5829,1.5829,0,0,0,0.1,30);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(13).to({_off:false},0).to({alpha:1},11,cjs.Ease.get(1)).wait(168));

	// BG_png
	this.instance_10 = new lib.bg("synched",0);
	this.instance_10.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(192));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(57.3,201,334.3,415);
// library properties:
lib.properties = {
	id: '1D42CF45455647789E9AE0A47792069B',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.png", id:"BG"},
		{src:"IMG1.png", id:"IMG1"},
		{src:"LOGO.png", id:"LOGO"},
		{src:"LOGO_R.png", id:"LOGO_R"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['1D42CF45455647789E9AE0A47792069B'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;