(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.frog = function() {
	this.initialize(img.frog);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,225);


(lib.lizart = function() {
	this.initialize(img.lizart);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,35);


(lib.snake = function() {
	this.initialize(img.snake);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,319,208);


(lib.Tounge = function() {
	this.initialize(img.Tounge);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,167,210);


(lib.turtle = function() {
	this.initialize(img.turtle);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,253);


(lib.tr = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.turtle();
	this.instance.setTransform(-150,-126.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-126.5,300,253);


(lib.tg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Tounge();
	this.instance.setTransform(-23.35,-29.4,0.28,0.28);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.3,-29.4,46.7,58.8);


(lib.t3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0B9444").s().p("AgGAJQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgMQAAgBAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIANAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAMQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(-38.775,11.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0B9444").s().p("AgQAdQgIgEgDgFIAAgBIAAgBIAIgEIABgBIABABIAFAFIAFADIAHABIAHgBQADgBACgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgCgCgFgBIgMgDQgIgCgFgDQgEgFAAgGQAAgHADgEQADgEAGgDQAGgDAHAAQAJAAAGAEQAHACADAGIAAABIAAABIgIADIgBABIgBgBIgGgFQgEgCgFAAQgFAAgDACQgDACAAAEIABAEIAHADIANADQAJADAEADQAEAFAAAGQAAAHgEAEQgDAEgGADQgGACgJAAQgJAAgHgEg");
	this.shape_1.setTransform(-43.4,9.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0B9444").s().p("AAPAhIgCgBIAAgBIAAgpQAAgFgDgCQgCgDgFAAIgFABIgEADIgGAFIAAApQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAABIgLAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg7QAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAHIAAABIABAAIAHgGQADgCADgBQADgCAEABQAJgBAFAGQAFAFAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAABg");
	this.shape_2.setTransform(-49.975,9.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0B9444").s().p("AgWAcQgFgFAAgHQAAgHAEgFQAEgEAHgCQAIgDAJgBIAGAAIACgBIAAgBIAAgCQAAgGgDgDQgDgDgFAAQgEAAgDACQgEACgDAEIAAABIgCAAIgKgDIgBAAIABgCQADgHAHgDQAHgEAJAAQAKAAAFADQAGACADAEQACAGAAAGIAAAoIAAACIgCABIgKAAIgCgBIAAgCIAAgDQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAgBABQgEADgFACQgDACgGAAQgKAAgFgFgAAHABIgHABIgGADIgEAEQgCACAAADQAAAEADACQADACAFAAIAFgBIAFgCIADgEIABgEIAAgIQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAAAg");
	this.shape_3.setTransform(-57.075,9.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0B9444").s().p("AgFAtIgCgBIAAgBIAAg7QAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAIAAA6IgBACIgCABgAgFgbIgCAAIAAgCIAAgNQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIALAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_4.setTransform(-61.7,8.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0B9444").s().p("AgFArIgGgDIgEgEIgBgBIgBABIgBAFQAAABAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgHAAIgCgBIAAgCIAAhTQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAMAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAdIABABIABgBIAEgDIAGgDQADgBAEAAQAIAAAGAFQAGADACAIQADAGAAAKQAAAPgHAJQgHAJgNAAQgEAAgEgCgAgHgHQgEACgDACIAAAZQAAAEACADQACADADABQADACAEABQAEAAADgDQADgCACgGQACgEAAgJQAAgLgDgFQgEgGgHAAQgEABgDACg");
	this.shape_5.setTransform(-66.725,8.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0B9444").s().p("AgEAtIgCgBIgBgBIAAg7QAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIALAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAA6IAAACIgCABgAgFgbIgBAAIgBgCIAAgNQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIALAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-72,8.15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0B9444").s().p("AAPAtIgCgBIAAgBIAAgqQAAgEgDgCQgCgDgFAAIgEABIgFADIgGAEIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAABIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhVQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIALAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAgIAAABIABgBIAIgGIAFgCIAHgBQAKAAAFAEQAEAGAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAABg");
	this.shape_7.setTransform(-77.075,8.15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0B9444").s().p("AgbAqQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhPIAAgBIACgBIALAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAEIABABIABAAIAEgEQACgCAEgBQACgCAFABQAHgBAGAEQAFAEAEAHQADAHAAALQAAAKgDAIQgEAIgFADQgGADgIAAQgEABgEgCQgEgBgDgEIgCgBIgBADIAAAWQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAgAgHgeQgDACgCADQgCACAAADIAAAbIAGAFQAEABADAAQAEAAAEgCQADgDACgEQACgFAAgIQAAgIgCgFQgCgFgDgCQgEgCgDAAIgHABg");
	this.shape_8.setTransform(-84.125,10.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0B9444").s().p("AAiAhIgCgBIAAgBIAAgpQAAgFgCgCQgDgDgEAAIgGABIgEADIgEADIgBACIAAABIAAAoQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBABIgKAAIgBgBIgBgBIAAgpQAAgFgCgCQgCgDgFAAQgEAAgEACIgHAHIAAApQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBABIgLAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAg7QAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAMAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAAAIAAAHIAAABIABAAIAGgGIAHgDQADgCAEABQAHAAADACQAFAEABAFIABAAIABAAIAHgGIAHgEQADgCAEABQAJgBAFAGQAFAFAAAJIAAAqQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBABg");
	this.shape_9.setTransform(-93.325,9.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0B9444").s().p("AgWAcQgFgFAAgHQAAgHAEgFQAEgEAHgCQAIgDAJgBIAGAAIACgBIAAgBIAAgCQAAgGgDgDQgDgDgFAAQgEAAgDACQgEACgDAEIAAABIgCAAIgKgDIgBAAIABgCQADgHAHgDQAHgEAJAAQAKAAAFADQAGACADAEQACAGAAAGIAAAoIAAACIgCABIgKAAIgCgBIAAgCIAAgDQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAgBABQgEADgFACQgDACgGAAQgKAAgFgFgAAHABIgHABIgGADIgEAEQgCACAAADQAAAEADACQADACAFAAIAFgBIAFgCIADgEIABgEIAAgIQAAAAAAgBQAAAAAAAAQAAgBgBAAQAAAAAAAAg");
	this.shape_10.setTransform(-102.375,9.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0B9444").s().p("AglAoQgHgHAAgLQAAgHAFgGQAFgGAKgFIABgBIgBgCQgEgEgCgEQgCgFAAgEQAAgHADgEQAEgGAGgCQAHgDAHgBQAGAAAGADQAGACADAEQADAFABAGQAAAEgCADQgDAFgEADQgFAFgGACIAAABIAAABIAOAQIABAAIACAAIAEgEIACgFIAEgEIACgEQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAIACIABABIAAACIgDAGIgFAIIgHAHIAAACIABABIAEADIAHACIAGABQABgBAAABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAJIAAACIgDABIgKgBIgKgDIgIgFIgBgBIgBABQgHAFgGACQgGADgIAAQgNgBgJgFgAgQAFQgFADgDAEQgDAEAAAFQAAAEACACQACADADACQAEACAEAAQAEAAAEgCIAGgEIABgCIAAgBIgQgTIgCgBgAgLghQgDABAAADQgCADAAADIABADIACAFIAFAEIABABIABgBQAGgDADgDQACgEAAgEQAAgEgCgDQgDgCgFAAQgDAAgDABg");
	this.shape_11.setTransform(-112.85,8.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0B9444").s().p("AgQAeQgHgEgEgGIAAgCIAAgBIAIgDIABAAIABAAIAFAEIAFAEIAHABIAHgBQADgBACgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQgCgCgFgCIgLgCQgKgCgEgEQgEgEAAgHQAAgFADgFQADgEAGgDQAGgDAHAAQAJAAAGADQAHAEADAEIAAACIAAABIgIAEIgBAAIgBgBIgGgFQgEgCgFAAQgEAAgEACQgDACgBAEIACADIAHADIANAEQAJADAEAEQAEAEAAAHQAAAFgEAFQgDAEgGADQgHACgIAAQgJAAgHgDg");
	this.shape_12.setTransform(3.95,-4.15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0B9444").s().p("AgOAdQgIgEgEgHQgEgIAAgJQAAgJAEgIQAFgHAHgFQAHgEAIAAQAJAAAHAEQAGAEAEAHQAEAIAAAJIAAADIgCAAIgpAAIgBABIgBABQAAAFADAEQACAEAEACQAEACAEABQAFgBAEgCQAEgCADgEIABgBIABABIAIACQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgIAIQgEAEgFABIgLABQgIAAgHgEgAgGgUQgEACgCAFQgCADAAAGIAcAAIABgBIABgBIgCgHQgCgFgDgCQgDgCgFAAQgEAAgDACg");
	this.shape_13.setTransform(-2.575,-4.15);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0B9444").s().p("AgEAsQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIABhTQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIALAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAABTIgBACIgCAAg");
	this.shape_14.setTransform(-7.625,-5.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0B9444").s().p("AgEAsIgDAAIAAgCIAAg6QAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAA6IAAACIgCAAgAgFgbIgCgBIAAgCIAAgLQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIALAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAALQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_15.setTransform(-10.65,-5.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0B9444").s().p("AAGAqQgHAAgEgEQgFgDAAgHIAAgjQAAgBAAAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIACgSQAAAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAASQAAABABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgOAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACACAEAAIAHAAIABABIABABIgBAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgFAAIgEAAg");
	this.shape_16.setTransform(-14.75,-5.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0B9444").s().p("AgbArQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhNIAAgDIACAAIALAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAEIABABIABgBIAEgDQACgCAEgBQACgBAFgBQAHABAGADQAFAEAEAHQADAHAAALQAAAKgDAIQgEAHgFAEQgGAEgIAAQgEAAgEgCQgEgBgDgDIgCgBIgBABIAAAWQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAgAgHgdQgDABgCADQgCACAAADIAAAbIAGAEQAEACADAAQAEAAAEgCQADgDACgFQACgEAAgIQAAgIgCgFQgCgFgDgCQgEgCgDAAIgHACg");
	this.shape_17.setTransform(-20.675,-3.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#0B9444").s().p("AgOAdQgIgEgEgHQgEgIAAgJQAAgJAEgIQAFgHAHgFQAHgEAIAAQAJAAAHAEQAGAEAEAHQAEAIAAAJIAAADIgCAAIgpAAIgBABIgBABQAAAFADAEQACAEAEACQAEACAEABQAFgBAEgCQAEgCADgEIABgBIABABIAIACQAAABAAAAQABAAAAABQAAAAgBAAQAAABAAAAIgIAIQgEAEgFABIgLABQgIAAgHgEgAgGgUQgEACgCAFQgCADAAAGIAcAAIABgBIABgBIgCgHQgCgFgDgCQgDgCgFAAQgEAAgDACg");
	this.shape_18.setTransform(-27.925,-4.15);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#0B9444").s().p("AgQAgIgCAAIgBgCIAAg6QAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABgBIAFgFIAGgEIAGgCQABAAABABQABAAAAAAQABAAAAABQABAAAAAAIAAAMQAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAAAIgEgBIgDAAIgGABIgEACIgDAEQAAAAAAABQAAABgBAAQAAABAAAAQAAABAAAAIAAAkQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_19.setTransform(-33.65,-4.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0B9444").s().p("AAGAqQgHAAgEgEQgFgDAAgHIAAgjQAAgBAAAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIACgSQAAAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAASQAAABABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgOAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACACAEAAIAHAAIACABIAAABIAAAGQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgFAAIgEAAg");
	this.shape_20.setTransform(-41.4,-5.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#0B9444").s().p("AgSAeQgEgCgDgEQgCgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAoQAAAEADADQACADAFAAQADAAAEgCIAHgGIAAgqQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAA6QAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgMAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgGIgBgBIgBABQgFAFgFACQgEACgFAAQgGAAgEgCg");
	this.shape_21.setTransform(-47.4,-4.075);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0B9444").s().p("AgPAdQgHgEgFgIQgEgHAAgKQAAgIAEgIQAFgHAHgFQAHgEAIAAQAKAAAGAEQAHAFAFAHQADAIAAAIQAAAKgDAHQgFAIgHAEQgGAEgKAAQgJAAgGgEgAgHgTQgEADgCAFQgCAFAAAGQAAAHACAGQACAEAEADQADACAEABQAFgBADgCQAEgDACgEQACgGgBgHQABgGgCgFQgCgFgEgDQgDgDgFABQgEgBgDADg");
	this.shape_22.setTransform(-54.45,-4.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#0B9444").s().p("AgFAsIgGgEIgEgFIgBAAIgBABIgBAGQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgHAAIgCAAIAAgCIAAhUQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAMAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAcIABACIABAAIAEgEIAGgCQADgCAEAAQAIAAAGAEQAGAFACAHQADAGAAAKQAAAPgHAJQgHAJgNAAQgEAAgEgBgAgHgIQgEACgDAEIAAAYQAAAEACADQACADADACQADABAEAAQAEAAADgCQADgDACgEQACgFAAgJQAAgMgDgEQgEgFgHAAQgEAAgDABg");
	this.shape_23.setTransform(-61.525,-5.35);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#0B9444").s().p("AgWAdQgFgGAAgIQAAgGAEgFQAEgEAHgCQAIgDAJAAIAGgBIACAAIAAgCIAAgDQAAgFgDgDQgDgDgFABQgEgBgDACQgEACgDAEIAAABIgCAAIgKgCIgBgBIABgCQADgHAHgEQAHgDAJAAQAKAAAFACQAGADADAFQACAFAAAFIAAAqIAAACIgCAAIgKAAIgCgBIAAgCIAAgEQAAAAgBAAQAAgBAAAAQAAAAgBABQAAAAgBAAQgEAEgFACQgDACgGAAQgKAAgFgEgAAHACIgHABIgGACIgEADQgCADAAADQAAAEADACQADACAFABIAFgBIAFgDIADgEIABgDIAAgJQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAg");
	this.shape_24.setTransform(-68.825,-4.15);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#0B9444").s().p("AAPAgIgCAAIAAgCIAAgoQAAgEgDgDQgCgDgFAAIgFABIgEADIgGAEIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgLAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAg6QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAGIAAABIABgBIAHgEQADgDADgBQADgBAEgBQAJABAFAFQAFAFAAAIIAAArQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_25.setTransform(-77.975,-4.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#0B9444").s().p("AgRAgIgBAAIAAgCIAAg6QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAMAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABgBIAFgFIAGgEIAGgCQABAAABABQABAAAAAAQABAAAAABQAAAAAAAAIAAAMQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAIgEgBIgEAAIgEABIgFACIgCAEQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAIAAAkQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAg");
	this.shape_26.setTransform(-83.75,-4.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#0B9444").s().p("AgWAdQgFgGAAgIQAAgGAEgFQAEgEAHgCQAIgDAJAAIAGgBIACAAIAAgCIAAgDQAAgFgDgDQgDgDgFABQgEgBgDACQgEACgDAEIAAABIgCAAIgKgCIgBgBIABgCQADgHAHgEQAHgDAJAAQAKAAAFACQAGADADAFQACAFAAAFIAAAqIAAACIgCAAIgKAAIgCgBIAAgCIAAgEQAAAAgBAAQAAgBAAAAQAAAAgBABQAAAAgBAAQgEAEgFACQgDACgGAAQgKAAgFgEgAAHACIgHABIgGACIgEADQgCADAAADQAAAEADACQADACAFABIAFgBIAFgDIADgEIABgDIAAgJQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAg");
	this.shape_27.setTransform(-89.975,-4.15);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#0B9444").s().p("AgOAdQgIgEgEgHQgEgIAAgJQAAgJAEgIQAFgHAHgFQAHgEAIAAQAJAAAHAEQAGAEAEAHQAEAIAAAJIAAADIgCAAIgpAAIgBABIgBABQAAAFADAEQACAEAEACQAEACAEABQAFgBAEgCQAEgCADgEIABgBIABABIAIACQAAABAAAAQABAAAAABQAAAAgBAAQAAABAAAAIgIAIQgEAEgFABIgLABQgIAAgHgEgAgGgUQgEACgCAFQgCADAAAGIAcAAIABgBIABgBIgCgHQgCgFgDgCQgDgCgFAAQgEAAgDACg");
	this.shape_28.setTransform(-96.575,-4.15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#0B9444").s().p("AgEAsQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIABhTQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIALAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAABTIgBACIgCAAg");
	this.shape_29.setTransform(-101.625,-5.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#0B9444").s().p("AgQAdQgHgEgEgIQgDgHAAgKQAAgIADgIQAEgHAHgFQAIgEAIAAQAJAAAHAEQAIAFADAHQAFAIAAAIQAAAKgFAHQgDAIgIAEQgHAEgJAAQgIAAgIgEgAgIgTQgDADgCAFQgCAFAAAGQAAAHACAGQACAEADADQAEACAEABQAFgBADgCQAEgDACgEQABgGABgHQgBgGgBgFQgCgFgEgDQgDgDgFABQgEgBgEADg");
	this.shape_30.setTransform(-109.2,-4.15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#0B9444").s().p("AAGAqQgHAAgEgEQgFgDABgHIAAgjQAAgBgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIACgSQAAAAAAgBQAAAAAAAAQAAAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAASQAAABABAAQAAAAAAABQAAAAAAAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgNAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACACAEAAIAHAAIABABIABABIgBAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgEAAIgFAAg");
	this.shape_31.setTransform(-115.35,-5.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#0B9444").s().p("AgQAdQgIgDgCgGIgBgBIABgBIAHgEIACgBIAAABIAFAFIAFADIAHABIAIgBQADgBABgCQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQgCgCgFgBIgMgDQgIgCgFgDQgEgFAAgHQAAgGADgEQADgFAGgCQAGgDAHAAQAJAAAHAEQAGADADAEIABACIgBABIgIADIgBABIgBgBIgGgFQgEgCgFAAQgFAAgDACQgEACABAEIABAEIAHADIANADQAJADAEADQAEAFAAAGQAAAHgDAEQgEAEgGADQgGACgJAAQgJAAgHgEg");
	this.shape_32.setTransform(60.35,-17.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#0B9444").s().p("AgQAhIgCgBIAAgBIAAg7QAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAAIIABABIABAAIAFgHIAGgDIAGgBQABAAABAAQABAAAAAAQABAAAAABQABAAAAABIAAALQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAgBIgEAAIgDAAIgGAAIgEAEIgDADQAAABAAAAQAAABgBAAQAAABAAAAQAAABAAABIAAAjQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape_33.setTransform(55.1,-17.75);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#0B9444").s().p("AgOAdQgIgEgEgHQgEgHAAgKQAAgJAEgIQAFgHAHgEQAHgFAIAAQAJAAAHAEQAGAEAEAIQAEAHAAAKIAAABIgCABIgpAAIgBAAIgBACQAAAFADAEQACAEAEACQAEACAEAAQAFAAAEgCQAEgCADgFIABAAIABAAIAIAEQAAAAAAAAQABAAAAABQAAAAgBAAQAAABAAAAIgIAJQgEADgFABIgLABQgIAAgHgEgAgGgTQgEACgCADQgCAFAAAEIAcAAIABAAIABgCIgCgHQgCgDgDgCQgDgDgFAAQgEAAgDADg");
	this.shape_34.setTransform(48.925,-17.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#0B9444").s().p("AgbAqQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhPIAAgBIACgBIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAEIABABIABAAIAEgEQACgCAEgBQACgBAFAAQAHgBAGAEQAFAEAEAHQADAHAAALQAAAKgDAIQgEAHgFAEQgGADgIAAQgEAAgEgBQgEgBgDgEIgCgBIgBACIAAAXQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAgAgHgeQgDACgCACQgCADAAADIAAAbIAGAFQAEACADAAQAEgBAEgCQADgDACgEQACgFAAgIQAAgIgCgFQgCgFgDgCQgEgCgDAAIgHABg");
	this.shape_35.setTransform(41.925,-16.75);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#0B9444").s().p("AAiAhIgCgBIAAgBIAAgpQAAgFgCgCQgDgDgEAAIgGABIgEADIgEADIgBACIAAABIAAAoQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgKAAIgBgBIgBgBIAAgpQAAgFgCgCQgCgDgFAAQgEAAgEACIgHAHIAAApQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgLAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAIAAg7QAAAAAAgBQABAAAAgBQAAAAAAAAQABAAAAAAIAMAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAHIAAABIABAAIAGgGIAHgDQADgBAEAAQAHAAADACQAFAEABAFIABAAIABAAIAHgGIAHgEQADgBAEAAQAJgBAFAGQAFAFAAAJIAAAqQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_36.setTransform(32.725,-17.75);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#0B9444").s().p("AgWAcQgFgEAAgIQAAgHAEgFQAEgEAHgDQAIgCAJgBIAGAAIACgBIAAgBIAAgCQAAgGgDgDQgDgDgFAAQgEAAgDACQgEACgDAEIAAABIgCAAIgKgDIgBAAIABgCQADgHAHgDQAHgEAJAAQAKAAAFACQAGADADAEQACAGAAAFIAAApIAAACIgCABIgKAAIgCgBIAAgCIAAgDQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAgBABQgEADgFACQgDACgGAAQgKAAgFgFgAAHABIgHABIgGADIgEAEQgCACAAADQAAAEADACQADACAFAAIAFgBIAFgCIADgEIABgEIAAgIQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAAAAAAAg");
	this.shape_37.setTransform(23.675,-17.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#0B9444").s().p("AgNAdQgHgEgEgHQgEgIAAgJQAAgKAEgHQAEgHAHgEQAHgFAIAAQAHAAAFACQAGADADAEIAFAIQABABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgKACIgCgBIgDgFIgEgDQgCgCgEAAQgDAAgEADQgEADgCAFQgCAFAAAGQAAAIADAEQACAGADACQAEADAEAAQAGAAADgDQAEgDADgFIAAgBIACAAIAHADQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIgEAFQgCAEgDADQgDACgFABQgEACgGAAQgIAAgHgEg");
	this.shape_38.setTransform(17.3583,-17.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#0B9444").s().p("AgQAhIgCgBIAAgBIAAg7QAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAAIIABABIABAAIAFgHIAGgDIAGgBQABAAABAAQABAAAAAAQABAAAAABQAAAAAAABIAAALQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAgBIgEAAIgDAAIgGAAIgEAEIgCADQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAABIAAAjQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAg");
	this.shape_39.setTransform(9.3,-17.75);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#0B9444").s().p("AgPAdQgHgEgFgHQgDgIAAgJQAAgKADgHQAFgHAHgEQAHgFAIAAQAKAAAGAFQAIAEADAHQAFAHAAAKQAAAJgFAIQgDAHgIAEQgGAEgKAAQgJAAgGgEgAgIgTQgDADgCAFQgCAFAAAGQAAAIACAEQACAFADADQAEACAEAAQAFAAADgCQAEgDACgFQACgEgBgIQABgGgCgFQgCgFgEgDQgDgDgFAAQgEAAgEADg");
	this.shape_40.setTransform(3.05,-17.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#0B9444").s().p("AgHAtQAAAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgxIgBgBIgJAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgIIABAAIACgBIAJAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAIAAgIQAAgIAEgFQAEgDAIAAIALAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAHIAAABIgCABIgHAAQAAAAgBAAQgBAAAAABQgBAAAAAAQgBABAAAAQgCADAAACIAAAHQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAABAAIALAAIABABIABAAIAAAIQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgLAAQAAAAgBAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAxQAAAAgBAAQAAABAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_41.setTransform(-2.85,-18.95);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#0B9444").s().p("AgZApIgCgBIAAgIIABgBIADgBIAIAAIAEgBIADgEIACgEIAAgDIgXg4IAAgCIABgBIANAAIABABIABABIAOAnQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIABgBIAPgnIABgBIABgBIAJAAIABABIAAACIgZA+IgFAJIgEAFQgDACgEABIgJABg");
	this.shape_42.setTransform(-11.025,-16.675);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#0B9444").s().p("AAGArQgHAAgEgFQgFgDABgIIAAgjQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgIQAAAAAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIACgTQAAAAAAgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAKAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIAAASQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAOAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAIQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgOAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACADAEAAIAHAAIABAAIABABIgBAHQAAAAAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgFAAIgEABg");
	this.shape_43.setTransform(-16.9,-18.75);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#0B9444").s().p("AgFAtIgCgBIAAgBIAAg7QAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQABABAAAAIAAA6IgBACIgCABgAgFgbIgCAAIAAgCIAAgNQAAAAAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_44.setTransform(-20.85,-18.95);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#0B9444").s().p("AAPAhIgCgBIAAgBIAAgpQAAgFgDgCQgCgDgFAAIgFABIgEADIgGAFIAAApQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAg7QAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAAHIAAABIABAAIAHgGQADgCADgBQADgBAEAAQAJgBAFAGQAFAFAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_45.setTransform(-25.925,-17.75);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#0B9444").s().p("AgSAeQgEgCgDgEQgCgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAoQgBAEADADQADADAEAAQAEAAADgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIAAgBIgBABQgGAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_46.setTransform(-33.05,-17.625);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#0B9444").s().p("AAGArQgHAAgEgFQgEgDAAgIIAAgjQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgIQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIABgTQAAAAABgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAKAAQAAAAABABQAAAAAAAAQAAAAAAABQABAAAAABIAAASQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAIQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgNAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACADAEAAIAHAAIABAAIABABIgBAHQAAAAAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgEAAIgFABg");
	this.shape_47.setTransform(-39.1,-18.75);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#0B9444").s().p("AgRAhIgBgBIgBgBIAAg7QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAAAAAIAMAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAAIIAAABIABAAIAFgHIAGgDIAGgBQABAAABAAQABAAAAAAQABAAAAABQABAAAAABIAAALQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAgBIgEAAIgDAAIgGAAIgEAEIgDADQAAABAAAAQAAABgBAAQAAABAAAAQAAABAAABIAAAjQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape_48.setTransform(-43.75,-17.75);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#0B9444").s().p("AgQAdQgGgEgEgHQgEgIgBgJQABgKAEgHQAEgHAGgEQAIgFAIAAQAJAAAIAFQAGAEAFAHQADAHAAAKQAAAJgDAIQgFAHgGAEQgIAEgJAAQgIAAgIgEgAgIgTQgDADgCAFQgCAFAAAGQAAAIACAEQACAFADADQAEACAEAAQAFAAAEgCQADgDACgFQACgEAAgIQAAgGgCgFQgCgFgDgDQgEgDgFAAQgEAAgEADg");
	this.shape_49.setTransform(-50,-17.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#0B9444").s().p("AgbAqQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhPIAAgBIACgBIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAEIABABIABAAIAEgEQACgCAEgBQACgBAFAAQAHgBAGAEQAFAEAEAHQADAHAAALQAAAKgDAIQgEAHgFAEQgGADgIAAQgEAAgEgBQgEgBgDgEIgCgBIgBACIAAAXQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAgAgHgeQgDACgCACQgCADAAADIAAAbIAGAFQAEACADAAQAEgBAEgCQADgDACgEQACgFAAgIQAAgIgCgFQgCgFgDgCQgEgCgDAAIgHABg");
	this.shape_50.setTransform(-57.075,-16.75);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#0B9444").s().p("AgbAqQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhPIAAgBIACgBIALAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAEIABABIABAAIAEgEQACgCAEgBQACgBAFAAQAHgBAGAEQAFAEAEAHQADAHAAALQAAAKgDAIQgEAHgFAEQgGADgIAAQgEAAgEgBQgEgBgDgEIgCgBIgBACIAAAXQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAgAgHgeQgDACgCACQgCADAAADIAAAbIAGAFQAEACADAAQAEgBAEgCQADgDACgEQACgFAAgIQAAgIgCgFQgCgFgDgCQgEgCgDAAIgHABg");
	this.shape_51.setTransform(-64.325,-16.75);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#0B9444").s().p("AgPAdQgHgEgFgHQgDgIAAgJQAAgKADgHQAFgHAHgEQAHgFAIAAQAKAAAGAFQAIAEADAHQAFAHAAAKQAAAJgFAIQgDAHgIAEQgGAEgKAAQgJAAgGgEgAgIgTQgDADgCAFQgCAFAAAGQAAAIACAEQACAFADADQAEACAEAAQAFAAADgCQAEgDACgFQACgEgBgIQABgGgCgFQgCgFgEgDQgDgDgFAAQgEAAgEADg");
	this.shape_52.setTransform(-71.65,-17.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#0B9444").s().p("AgOAdQgIgEgEgHQgEgHAAgKQAAgJAEgIQAFgHAHgEQAHgFAIAAQAJAAAHAEQAGAEAEAIQAEAHAAAKIAAABIgCABIgpAAIgBAAIgBACQAAAFADAEQACAEAEACQAEACAEAAQAFAAAEgCQAEgCADgFIABAAIABAAIAIAEQAAAAAAAAQABAAAAABQAAAAgBAAQAAABAAAAIgIAJQgEADgFABIgLABQgIAAgHgEgAgGgTQgEACgCADQgCAFAAAEIAcAAIABAAIABgCIgCgHQgCgDgDgCQgDgDgFAAQgEAAgDADg");
	this.shape_53.setTransform(-81.225,-17.7);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#0B9444").s().p("AgSAeQgFgCgBgEQgDgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAoQABAEACADQACADAFAAQADAAAEgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIAAgBIgBABQgGAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_54.setTransform(-88.3,-17.625);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#0B9444").s().p("AAQAqQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgWIgBgCIgBAAIgIAFQgEABgEAAQgIAAgGgDQgGgEgDgIQgDgHAAgKQAAgJADgIQADgHAGgFQAHgDAIAAQAEAAAEABIAHADIAEAFQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIACgGIAAgBIACgBIAGAAIACABIAAABIAABPQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAgAgGgdQgDACgCAGQgCAFAAAHQAAAIACAFQACAEADADQAEACADABQAEgBAEgBQADgCADgDIAAgaQAAgDgCgDIgFgFQgDgCgEABQgDgBgEADg");
	this.shape_55.setTransform(-95.575,-16.75);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#0B9444").s().p("AgEAtIgDgBIAAgBIAAg7QAAAAAAgBQAAAAABgBQAAAAAAAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAABAAAAIAAA6IAAACIgCABgAgFgbIgCAAIAAgCIAAgNQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIALAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAMQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_56.setTransform(-100.55,-18.95);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#0B9444").s().p("AAPAhIgCgBIAAgBIAAgpQAAgFgDgCQgCgDgFAAIgFABIgEADIgGAFIAAApQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg7QAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAHIAAABIABAAIAHgGQADgCADgBQADgBAEAAQAJgBAFAGQAFAFAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_57.setTransform(-105.625,-17.75);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#0B9444").s().p("AgTApQgHgEgEgHQgDgJAAgLIAAg0QAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAOAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAA3QAAAKAFAFQAEAEAJAAQAFAAAEgBQAEgCACgFQADgFAAgGIAAg3QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAA2QAAAMgDAHQgFAHgIAEQgHADgLAAQgMAAgHgEg");
	this.shape_58.setTransform(-113.5,-18.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-119.8,-28.1,194.39999999999998,45.7);


(lib.t2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#167ABE").s().p("AgVBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAIAHgXIAKgbIAOgeIATghIAAgCIgCAAIhEAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIABgKQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIBUAAIADABIAAABIAAAHIgBADIgCADIgOAYQgGAMgGANIgKAZIgHAWIgEASQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape.setTransform(96.875,7.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_1.setTransform(84.225,9.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_2.setTransform(71.525,7.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#167ABE").s().p("AAKBAQgKAAgGgGQgFgEAAgMIAAg7QAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgOAAQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAAAAAgBIAAgHQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIAPAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIACgcQAAgBABgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAIAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAcQAAAAAAABQAAAAAAAAQAAAAAAAAQABAAAAAAIAXAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgXAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAA3QAAAJADADQADADAGAAIAMAAIACAAIAAACIAAAGQAAAAAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgFABIgHAAg");
	this.shape_3.setTransform(58.825,7.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#167ABE").s().p("AgXAsQgLgGgEgJIgBgBIABgCIAHgDIACgBIABABIAHAIQAEADAGACQAFACAHAAIAMgCQAGgCADgDQADgDAAgFQAAgFgEgDQgEgEgJgDIgSgFQgNgDgGgGQgFgGAAgIQAAgJAEgGQAFgHAIgDQAJgEAJABQAMgBAKAFQAJAEAFAIIABACIgBABIgHADIgCABIgBgBQgEgFgGgEQgHgDgJAAQgIAAgHAEQgGAEAAAHQAAAEADADQADAEAIADIAWAHQANACAFAHQAGAGAAAIQAAAJgFAGQgFAHgJADQgJAEgLAAQgNgBgLgFg");
	this.shape_4.setTransform(50.625,9.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#167ABE").s().p("AgYAtQgGgDgEgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAJAAQAGAAAIgFQAHgEAGgHIAAhCQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAIALAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABZQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgLAAQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgLIAAgBIgBABQgLAIgHADQgHAEgHAAQgIAAgHgEg");
	this.shape_5.setTransform(40.95,9.225);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#167ABE").s().p("AglA6QgMgHABgMQAAgGADgFQAFgGAJgDQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIgHgFQgCgCAAgEIACgFQABgCADgCIAIgEIABAAIgBgCQgIgEgDgGQgEgGAAgIQAAgOALgIQAKgIATAAQAIAAAIACQAGACAEAEIACABIACgBIAFgEIAGgDIAGgBIADAAIABADIAAAGIgBACQgBAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgFABIgFABQgEABABADIACAFIABAHQAAAIgEAHQgEAGgJAEQgJAEgMAAIgPABQgFABgCACQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAADAEABQADABAJABIAXABQAPABAIAHQAHAGAAALQAAAOgLAHQgMAIgWAAQgWAAgNgGgAgZAXIgHAGQgDADAAAFQAAAGAEAEQADAEAJACQAHACALAAQAOAAAJgEQAHgFAAgJQAAgGgEgEQgEgEgKAAIgdgCIgBAAIgGACgAgUgwQgHAFAAAKQAAAJAHAFQAGAGAMAAQAMAAAGgGQAGgFAAgJQAAgKgGgFQgGgGgMAAQgMAAgGAGg");
	this.shape_6.setTransform(30.4,10.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAIAAQAHAAAIgFQAHgEAHgHIAAhCQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAABAAIAJAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIgBBZQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgJAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgLIgBgBIgCABQgJAIgIADQgHAEgHAAQgIAAgHgEg");
	this.shape_7.setTransform(19.75,9.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#167ABE").s().p("AAqBDQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIgNgjIgBgBIgBAAIgzAAQgBAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAIgMAjIgBABIgCABIgLAAIgBgBIAAgCIAuh/IABgCIADgBIANAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAABIAuB/IAAACQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAgBguIgWA7QgBAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIAqAAQABAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIgWg7IAAgBg");
	this.shape_8.setTransform(8.125,7.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#167ABE").s().p("AgDBbQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAixIABgBIABgBIAHAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAACxQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_9.setTransform(-4.6,7.75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#167ABE").s().p("AgfBDQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgKQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAhiQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgXAIQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBgBAAAAIAAgHIAAgCIACgBIAbgNIADgCIABAAIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAB0QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAUAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAKIgBABIgCABg");
	this.shape_10.setTransform(-14.9,7.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#167ABE").s().p("AgTBCQgIgCgHgEQgHgEgGgHIAAgBIABgCIAIgGIABAAIABAAQAFAGAGADQAFADAHACQAFABAHAAQAPAAAJgHQAJgHAAgLQgBgIgFgGQgEgGgIgDQgHgDgIAAIgRAAQAAAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgJQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAOgBQAIAAAHgDQAIgDAEgGQAFgFgBgHQABgGgEgFQgDgFgHgDQgGgDgIAAQgJAAgIAEQgHAEgHAGIgCABIgCgBIgGgGQAAAAgBgBQAAAAAAAAQAAgBAAAAQABAAAAgBQAFgGAHgEQAGgEAIgCQAIgCAHAAQANAAALAFQAKAEAFAIQAFAHAAAKQABAKgHAIQgGAIgKADIgDACIADABQAHACAGADQAGAFAEAHQAEAGAAAJQAAALgGAJQgGAJgMAFQgLAFgQAAQgJAAgIgDg");
	this.shape_11.setTransform(-25.05,7.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_12.setTransform(-37.925,9.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#167ABE").s().p("AgVBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAIAHgXIAKgbIAOgeIATghIAAgCIgCAAIhEAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIABgKQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIBUAAIADABIAAABIAAAHIgBADIgCADIgOAYQgGAMgGANIgKAZIgHAWIgEASQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_13.setTransform(-50.575,7.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_14.setTransform(-61.375,7.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#167ABE").s().p("AgkA+QgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIAAgHIABgCIAEAAIAMAAQAEAAADgCIAFgHIADgIQABgFgBgDIgjhUIAAgDIACgBIALAAIACABIABACIAaBEIACACQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIAbhEIABgCIABgBIAJAAIACABIAAADIgoBkQgCAGgDAEQgDAEgEADIgIACIgLABg");
	this.shape_15.setTransform(-75.2625,10.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#167ABE").s().p("AgEBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAh/QAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIAKAAQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAB/IAAACIgCABg");
	this.shape_16.setTransform(-82.2,7.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAIAAQAHAAAHgFQAIgEAHgHIAAhCQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAABAAIAJAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIgBBZQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgJAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgLIgBgBIgCABQgJAIgIADQgHAEgHAAQgIAAgHgEg");
	this.shape_17.setTransform(-89.6,9.225);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#167ABE").s().p("AgPBCIgIgCIgBgCIgBgCIACgJQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAFACQADACAGAAQAHAAAEgFQADgEAAgMIAAhgQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAOAAQAAAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABkQgBAQgGAIQgHAIgOAAQgHAAgGgCg");
	this.shape_18.setTransform(-98.95,7.325);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#167ABE").s().p("AgVBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAIAHgXIAKgbIAOgeIATghIAAgCIgCAAIhEAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIABgKQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIBUAAIADABIAAABIAAAHIgBADIgCADIgOAYQgGAMgGANIgKAZIgHAWIgEASQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_19.setTransform(95.425,-14.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#167ABE").s().p("AgeBDQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgKQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAWAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAgBIAAhiQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgWAIQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHIAAgCIABgBIAbgNIACgCIACAAIAIAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAB0QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAUAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAKIAAABIgCABg");
	this.shape_20.setTransform(85.95,-14.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_21.setTransform(74.425,-12.725);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#167ABE").s().p("AgTBCQgIgCgHgEQgHgEgGgHIAAgBIABgCIAIgGIABAAIABAAQAFAGAGADQAFADAGACQAGABAIAAQAOAAAJgHQAJgHAAgLQgBgIgEgGQgFgGgIgDQgIgDgHAAIgQAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAMgBQAJAAAHgDQAIgDAEgGQAEgFAAgHQAAgGgDgFQgDgFgHgDQgGgDgIAAQgJAAgIAEQgHAEgIAGIgBABIgCgBIgGgGQAAAAgBgBQAAAAAAAAQAAgBAAAAQABAAAAgBQAGgGAGgEQAHgEAHgCQAHgCAIAAQANAAALAFQAJAEAGAIQAFAHABAKQAAAKgHAIQgFAIgMADIgCACIACABQAIACAGADQAGAFAEAHQADAGAAAJQABALgGAJQgGAJgLAFQgMAFgQAAQgJAAgIgDg");
	this.shape_22.setTransform(61.25,-14.625);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#167ABE").s().p("AgeBDQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgKQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAWAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIAAhiQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgWAIQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHIAAgCIABgBIAbgNIADgCIABAAIAIAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAB0QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAVAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAKIgBABIgBABg");
	this.shape_23.setTransform(51.55,-14.625);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#167ABE").s().p("AgkA+QgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIAAgHIABgCIAEAAIAMAAQAEAAADgCIAFgHIADgIQABgFgBgDIgjhUIAAgCIACgBIALAAIACAAIABACIAaBFIACABQAAAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAIAbhEIABgCIABAAIAJAAIACABIAAACIgoBjQgCAHgDAEQgDAEgEACIgIADIgLABg");
	this.shape_24.setTransform(38.7375,-11.25);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#167ABE").s().p("AgEBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAh/QAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAKAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAAB/IgBACIgDABg");
	this.shape_25.setTransform(31.8,-14.625);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAJAAQAHAAAHgFQAHgEAGgHIAAhCQAAAAABgBQAAgBAAAAQABAAAAgBQABAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABZQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgKAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgLIAAgBIgCABQgKAIgHADQgGAEgIAAQgJAAgGgEg");
	this.shape_26.setTransform(24.4,-12.625);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#167ABE").s().p("AgPBCIgIgCIgBgCIAAgCIABgJQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAGACQAEACAFAAQAHAAADgFQAEgEAAgMIAAhgQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABkQAAAQgHAIQgHAIgPAAQgHAAgFgCg");
	this.shape_27.setTransform(15.05,-14.525);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#167ABE").s().p("AgDBbQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAixIAAgBIACgBIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAACxQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_28.setTransform(5.6,-14.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_29.setTransform(-6.025,-14.725);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_30.setTransform(-16.775,-14.725);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_31.setTransform(-29.375,-12.725);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_32.setTransform(-42.075,-14.725);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_33.setTransform(-52.825,-14.725);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#167ABE").s().p("AgVArQgLgGgGgLQgFgLAAgPQAAgOAGgLQAGgMAKgFQAKgHAMABQANAAAKAFQAKAGAFALQAFALAAAPIAAACIgCABIhEAAIgBABIgBACQAAAIAEAIQAFAHAHAEQAHAEAIABQAJAAAHgEQAHgEAFgHIABgBIABABIAIADQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgFAHgGAFQgFAEgIACQgHACgJABQgMgBgKgGgAgOghQgHAEgDAIQgDAHAAAIIA1AAIADAAIAAgDQAAgHgDgHQgDgGgHgFQgGgEgJAAQgIAAgHAFg");
	this.shape_34.setTransform(-67.175,-12.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#167ABE").s().p("AAaAxIgBgBIgBgCIAAg/QAAgJgFgFQgEgFgKAAQgFAAgEACQgEABgFAEIgKAIIAABDQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgKAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhaQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAKAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAKIABACIABgBIALgIQAFgDAGgCQAEgCAGABQAOAAAIAHQAHAIAAAMIAABBQAAABAAABQAAAAgBABQAAAAAAAAQgBABgBAAg");
	this.shape_35.setTransform(-77.625,-12.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAJAAQAGAAAIgFQAHgEAGgHIAAhCQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAIALAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABZQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgLAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgLIAAgBIgCABQgKAIgHADQgHAEgHAAQgIAAgHgEg");
	this.shape_36.setTransform(-88.2,-12.625);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#167ABE").s().p("AgOBCIgJgCIgBgCIAAgCIABgJQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAGACQAEACAFAAQAHAAADgFQAEgEAAgMIAAhgQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABkQABAQgHAIQgHAIgPAAQgGAAgFgCg");
	this.shape_37.setTransform(-97.55,-14.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104.3,-27.3,208.7,47.7);


(lib.t1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0B9444").s().p("AgNBgQgFABAAgFIAAgdQAAgEADAAIAeAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAcQAAAGgGgBgAgGApQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAIgBgEIgIiAIAAgDIACAAIAgAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgICAQAAAAAAABQAAABAAAAQgBABAAAAQAAABgBAAIgEABg");
	this.shape.setTransform(70.7,12.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0B9444").s().p("Ag9BcQgDAAAAgFIAAiqIABgEIAEgBIAXAAQAFAAAAAFIAAAIQAAABAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIADgBIAJgHQAFgEAHgDQAGgDALAAQAPAAANAIQAMAIAHAPQAHAQAAAXQAAAYgHAQQgHAQgNAIQgNAIgQAAQgKAAgJgDQgJgDgHgHIgEgCQAAAAAAAAQAAABgBAAQAAABAAAAQAAABAAABIAAAvQAAAFgDAAgAgQhBQgHADgEAGQgEAFAAAGIAAA8QAGAGAHAEQAHAEAJAAQAJAAAIgFQAHgFAFgMQAEgKAAgSQAAgSgEgKQgFgKgHgFQgIgFgIAAQgJAAgGAEg");
	this.shape_1.setTransform(59.825,17.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0B9444").s().p("ABKBGIgEgBIgBgDIAAhZQAAgKgFgGQgFgFgKAAQgGAAgFACQgGACgEAEIgIAGIgDAEIAAAEIAABXQAAAFgGAAIgXAAIgDgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAIAAhZQAAgKgFgGQgFgFgKAAQgJAAgIAEQgHAFgJAIIAABcQAAAFgGAAIgXAAQgEAAAAgEIAAiAQAAgEADAAIAaAAQAEAAAAADIAAAOIAAACIADgBIAOgLIAOgIQAHgCAJAAQAOAAAJAGQAJAHAEAKIABABIACgBIAPgMQAHgFAIgDQAIgDAIAAQATAAAKALQALALAAATIAABdQAAAFgFAAg");
	this.shape_2.setTransform(39.875,14.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0B9444").s().p("AgxA9QgLgLAAgQQAAgOAJgLQAIgJAQgHQARgFAWgBIANgBIADgCIABgDIAAgGQAAgLgHgGQgHgGgMAAQgIAAgIADQgHAFgGAJIgCACIgDAAIgWgGIgCgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAgBABAAQAHgPAPgIQAPgIAWAAQAUAAAMAGQANAGAGAKQAFAJAAANIAABbIgBAEIgDABIgWAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAIgBgEIgBgIQAAgEgEADQgJAJgLAEQgJAFgNgBQgUAAgMgKgAAOADIgPACIgNAFQgGADgDAFQgEAFAAAHQAAAIAGAFQAHAFALABQAGAAAGgDQAGgCAEgDIAHgIQADgEAAgEIAAgTQAAgFgEAAg");
	this.shape_3.setTransform(20.175,15.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0B9444").s().p("AgoBWQgUgMgKgXQgLgWAAgdQAAgfALgVQAKgWAUgMQATgMAZAAQAPAAAMAEQANAFAKAHQAKAIAHAKQAGAKACAMIABAEIgDACIgeACIgCgBIgBgDQgEgPgJgIQgKgKgQABQgVgBgMASQgMAQAAAlQAAAkAMARQALARAXAAQAQAAAMgHQALgJAHgSQABgDAEACIAWAEIACABQAAABABAAQAAAAAAABQAAAAAAABQAAABAAABIgGANQgEAHgGAIQgGAHgJAGQgJAGgMADQgLAEgOAAQgaAAgTgNg");
	this.shape_4.setTransform(4.2333,12.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0B9444").s().p("Ag3BaQgEgBAAgDIAAgRIABgDIAHgBIARAAQAFAAAEgDIAHgHQADgEABgEQABgFgCgEIgyh6QAAAAAAgBQAAAAAAgBQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIAbAAIADABIACACIAgBWQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAABgBQAAAAAAAAQABAAAAgBIAghVIACgCIADgBIATAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAABIg3CHQgFANgFAHQgEAIgHAEQgGAEgIACQgJABgKAAg");
	this.shape_5.setTransform(-17.8625,17.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0B9444").s().p("AgxA9QgLgLAAgQQAAgOAJgLQAIgJAQgHQARgFAWgBIANgBIADgCIABgDIAAgGQAAgLgHgGQgHgGgMAAQgIAAgIADQgHAFgGAJIgCACIgDAAIgWgGIgCgCQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAgBABAAQAHgPAPgIQAPgIAWAAQAUAAAMAGQANAGAGAKQAFAJAAANIAABbIgBAEIgDABIgWAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAIgBgEIgBgIQAAgEgEADQgJAJgLAEQgJAFgNgBQgUAAgMgKgAAOADIgPACIgNAFQgGADgDAFQgEAFAAAHQAAAIAGAFQAHAFALABQAGAAAGgDQAGgCAEgDIAHgIQADgEAAgEIAAgTQAAgFgEAAg");
	this.shape_6.setTransform(-32.775,15.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0B9444").s().p("AhJBgQgGABAAgGIAAi2IACgEIAEAAIAKAAIAQAAIAPAAIALAAQAiABAWALQAXAMALAVQALAVgBAdQAAAegLAVQgLAXgXALQgXAMgigBgAgohAIAACCQAAABAAAAQAAABABAAQAAABABAAQABAAAAAAIAHAAQAYAAAOgHQAQgGAIgQQAHgPAAgZQAAgZgHgPQgIgOgPgHQgOgHgXAAIgKAAQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAABg");
	this.shape_7.setTransform(-48.8,12.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0B9444").s().p("AglBGIgDgBIgBgDIAAiAQAAgEADAAIAZAAQAEAAAAADIAAAQIABACQAAAAABAAQAAAAAAAAQABAAAAAAQAAgBABAAQAFgIAGgFQAGgFAHgCQAHgDAHAAQAJAAAAAEIAAAZQAAAEgDgBIgJgBIgHgBQgFAAgGACQgFACgFAEQgEAEgDAEQgDAFAAAEIAABPQAAAFgGAAg");
	this.shape_8.setTransform(69.225,-13.525);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0B9444").s().p("AghA/QgPgJgJgQQgJgPAAgVQAAgWAJgQQAKgRAPgIQAPgJASAAQAUgBAPAJQAOAJAJAPQAIARAAAWIgBAEQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIhbAAIgCABIgBAEQAAALAFAIQAFAJAJAEQAIAFAKAAQAKAAAJgFQAIgEAJgJIACgCIACABIAQAHQADACgCACQgIAMgJAGQgJAIgLACQgKADgPABQgSAAgQgJgAgPgsQgHAFgEAIQgEAJAAAKIA7AAIAEgBIABgCQAAgJgEgHQgDgIgIgFQgGgFgLAAQgJAAgIAFg");
	this.shape_9.setTransform(55.85,-13.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0B9444").s().p("ABKBGIgEgBIgBgDIAAhZQAAgKgFgGQgFgFgKAAQgGAAgFACQgGACgEAEIgIAGIgDAEIAAAEIAABXQAAAFgGAAIgXAAIgDgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAIAAhZQAAgKgFgGQgFgFgKAAQgJAAgIAEQgHAFgJAIIAABcQAAAFgGAAIgXAAQgEAAAAgEIAAiAQAAgEADAAIAaAAQAEAAAAADIAAAOIAAACIADgBIAOgLIAOgIQAHgCAJAAQAOAAAJAGQAJAHAEAKIABABIACgBIAPgMQAHgFAIgDQAIgDAIAAQATAAAKALQALALAAATIAABdQAAAFgFAAg");
	this.shape_10.setTransform(36.425,-13.525);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0B9444").s().p("ABKBGIgEgBIgBgDIAAhZQAAgKgFgGQgFgFgKAAQgGAAgFACQgGACgEAEIgIAGIgDAEIAAAEIAABXQAAAFgGAAIgXAAIgDgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAIAAhZQAAgKgFgGQgFgFgKAAQgJAAgIAEQgHAFgJAIIAABcQAAAFgGAAIgXAAQgEAAAAgEIAAiAQAAgEADAAIAaAAQAEAAAAADIAAAOIAAACIADgBIAOgLIAOgIQAHgCAJAAQAOAAAJAGQAJAHAEAKIABABIACgBIAPgMQAHgFAIgDQAIgDAIAAQATAAAKALQALALAAATIAABdQAAAFgFAAg");
	this.shape_11.setTransform(12.675,-13.525);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0B9444").s().p("AgoBBQgJgEgGgKQgFgJAAgNIAAhdQAAgFAGAAIAXAAQAFAAAAAEIAABZQAAAJAFAHQAGAFAKAAQAIAAAIgEQAIgGAIgIIAAhbQAAgFAGAAIAXAAQAFAAAAAEIgBCAQAAAFgDAAIgaAAQgDAAAAgFIAAgNIgBgCIgCABQgMALgLAGQgKAEgMAAQgLAAgJgFg");
	this.shape_12.setTransform(-6.975,-13.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0B9444").s().p("AgeBfQgOgEgMgHQgLgIgHgKQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAIADgDIAQgMQABAAABAAQAAgBABAAQABAAAAAAQAAAAABAAIADABQAGAJAHAFQAGAGAIACQAJACAMAAQARABALgHQALgFAAgOQAAgEgCgFQgDgEgFgEQgFgDgJgDIgngNQgPgEgJgHQgKgIgFgKQgFgLAAgLQAAgRAJgNQAJgMAQgIQAQgHAUAAQAOAAANADQAMAEAKAFQAKAHAHAIIABACQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAABIgTANIgCABIgEgDQgGgGgJgFQgJgGgQAAQgQAAgJAIQgJAGAAAMIABAHQACAEAFAFQAFADAKADIAnANQAYAGAKANQALAOAAATQAAARgJANQgKANgQAHQgRAHgXAAQgQAAgPgEg");
	this.shape_13.setTransform(-23.2312,-16.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61,-33.6,137,64);


(lib.lizart_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.lizart();
	this.instance.setTransform(-128,-17.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128,-17.5,256,35);


(lib.f = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.frog();
	this.instance.setTransform(-72,-41,0.36,0.36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72,-41,144,81);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVAuIgBAAIgBgCIAAhVQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAKAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAALIABABIACgBQAEgFAEgDQAEgDAEgCQAEgCAFAAQAGAAAAADIAAAKQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgDgBIgFAAIgIACQgEABgCAEIgGAGQgCADAAAEIAAA3QAAABgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(5.5,1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgVApQgLgGgFgKQgFgLAAgNQAAgNAFgLQAGgLAKgGQAKgGALAAQANAAAKAHQAJAGAGAKQAFALAAANQAAANgFALQgGAKgJAGQgKAGgNAAQgMAAgJgGgAgOgfQgHAFgDAIQgDAIgBAKQABALADAIQADAJAHAEQAHAEAHAAQAJAAAGgEQAGgEAEgIQADgJAAgLQAAgKgDgIQgEgIgGgFQgGgEgJAAQgHAAgHAEg");
	this.shape_1.setTransform(-3.25,1.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgGA/QgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhLQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAAAAAAAIgQAAQgBAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgHIAAgBIACgBIAQAAQAAAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIAAgMQAAgLAFgGQAFgFAKAAIAPAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAHIAAABIgCAAIgMAAQgGAAgBADQgDAEAAAFIAAANQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIAUAAIACABIAAABIAAAHQAAAAAAABQAAAAgBAAQAAAAAAAAQgBABAAAAIgTAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAABKQAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_2.setTransform(-11.5,-0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AglA8QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhxIAAgBIADgBIAJAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIABgBIAFgFQAEgDAFgBQAFgDAHAAQAKAAAJAFQAIAFAFALQAFAJAAAQQAAAOgFAKQgFALgJAGQgIAFgMABQgHAAgGgCQgGgDgEgEIgCgBIgBACIAAAgQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAgAgNguQgGADgDAFQgDAFAAAEIAAApIALAIQAFAEAHAAQAHgBAHgEQAGgEAEgIQADgIAAgMQAAgMgDgJQgEgHgGgEQgGgEgHABQgHAAgFACg");
	this.shape_3.setTransform(-23.125,2.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXArQgGgDgDgGQgEgGAAgIIAAg+QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAJAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAA6QAAAIAFAGQAFAFAIAAQAGAAAHgEQAHgEAGgHIAAg+QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAJAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIgBBUQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgKAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgKIgBgBIgBABQgJAIgHADQgHADgHAAQgHAAgHgDg");
	this.shape_4.setTransform(-33.375,1.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAZAuIgBAAIgBgCIAAg8QAAgIgFgFQgEgFgIABQgGgBgDACQgEACgEACIgKAIIAAA/QAAABgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAhVQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAJIABABIABAAIAKgIIAKgEQAEgCAGAAQANAAAHAHQAHAIAAALIAAA+QAAABAAABQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_5.setTransform(-46.75,1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgiA2QgMgFAAgMQAAgGAEgFQAEgEAIgFQABAAAAAAQAAAAAAgBQAAAAAAAAQAAAAgBAAQgDgCgCgCQgDgDAAgDQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABgBIAEgDIAHgEIABgBIgBgBQgHgEgDgGQgEgFAAgIQAAgNAKgIQAKgIATABQAHAAAGACQAHACAEADIACABIACgBIAEgEIAFgCIAHgBIACAAIABACIAAAGIgBADQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgGABIgDAAQgFACABACIACAFIABAHQAAAHgEAHQgEAGgIADQgIAFgMAAIgOABIgHACQAAAAAAAAQgBABAAAAQAAABAAAAQgBAAAAABQABABAAAAQAAABAAAAQABABAAAAQABAAABABQAEABAIAAIAVABQAPACAHAFQAHAHAAAKQAAANgMAHQgLAIgTAAQgWAAgLgHgAgYAWQgDACgDADQgDADAAAFQAAAFADAEQAEAEAIACQAHACALAAQANAAAHgEQAHgFABgIQAAgGgFgDQgDgEgKAAIgbgCIgHACgAgTguQgHAGABAJQgBAJAHAEQAFAGAMAAQALAAAGgGQAFgEAAgJQAAgJgFgGQgGgEgLAAQgMAAgFAEg");
	this.shape_6.setTransform(-56.85,2.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEA/IgCAAIAAgDIAAhUQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAJAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAABUIAAADIgDAAgAgEgqIgCgBIgBgCIAAgPQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAJAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAPQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_7.setTransform(-63.975,-0.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgRA/QgJgDgGgFQgHgEgFgHIgBgCIACgCIAGgFIADgBIACABIAIAKQAFAEAGACQAGACAHAAQAOAAAIgFQAIgFAAgLQAAgFgBgDQgCgEgEgDQgEgDgIgCIgZgJQgJgDgGgFQgGgFgCgGQgDgGAAgGQAAgLAFgIQAGgIAJgEQAKgFAMAAQAJAAAHACQAHACAGAEQAGAEAFAFIABACIgBACIgIAGIgBAAIgCgBQgEgGgHgDQgHgEgLAAQgMAAgHAFQgHAGAAAKIABAGQABAEAEADQAEAEAIACIAXAJQAQAEAGAIQAHAJAAALQAAALgGAIQgFAIgKAEQgKAEgOAAQgJAAgJgCg");
	this.shape_8.setTransform(-71.475,-0.725);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#167ABE").s().p("ArUCrQhkAAAAhkIAAiNQAAhkBkAAIWpAAQBkAAAABkIAACNQAABkhkAAg");
	this.shape_9.setTransform(-4.75,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-87.2,-17.1,165,34.2);


(lib.bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,728,90);


(lib.turtle_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.tr("synched",0);
	this.instance.setTransform(-37.45,0,0.7604,0.7604,0,0,0,-0.7,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:0,scaleX:0.7637,scaleY:0.7637,x:-36.2169},0).wait(1).to({scaleX:0.7669,scaleY:0.7669,x:-35.5477},0).wait(1).to({scaleX:0.77,scaleY:0.77,x:-34.8922},0).wait(1).to({scaleX:0.7731,scaleY:0.7731,x:-34.2505},0).wait(1).to({scaleX:0.776,scaleY:0.776,x:-33.6227},0).wait(1).to({scaleX:0.779,scaleY:0.779,x:-33.0086},0).wait(1).to({scaleX:0.7818,scaleY:0.7818,x:-32.4084},0).wait(1).to({scaleX:0.7846,scaleY:0.7846,x:-31.8219},0).wait(1).to({scaleX:0.7874,scaleY:0.7874,x:-31.2492},0).wait(1).to({scaleX:0.79,scaleY:0.79,x:-30.6903},0).wait(1).to({scaleX:0.7926,scaleY:0.7926,x:-30.1453},0).wait(1).to({scaleX:0.7952,scaleY:0.7952,x:-29.614},0).wait(1).to({scaleX:0.7976,scaleY:0.7976,x:-29.0965},0).wait(1).to({scaleX:0.8,scaleY:0.8,x:-28.5929},0).wait(1).to({scaleX:0.8024,scaleY:0.8024,x:-28.103},0).wait(1).to({scaleX:0.8046,scaleY:0.8046,x:-27.6269},0).wait(1).to({scaleX:0.8068,scaleY:0.8068,x:-27.1646},0).wait(1).to({scaleX:0.809,scaleY:0.809,x:-26.7162},0).wait(1).to({scaleX:0.811,scaleY:0.811,x:-26.2815},0).wait(1).to({scaleX:0.813,scaleY:0.813,x:-25.8606},0).wait(1).to({scaleX:0.815,scaleY:0.815,x:-25.4535},0).wait(1).to({scaleX:0.8169,scaleY:0.8169,x:-25.0603},0).wait(1).to({scaleX:0.8187,scaleY:0.8187,x:-24.6808},0).wait(1).to({scaleX:0.8204,scaleY:0.8204,x:-24.3151},0).wait(1).to({scaleX:0.8221,scaleY:0.8221,x:-23.9632},0).wait(1).to({scaleX:0.8237,scaleY:0.8237,x:-23.6251},0).wait(1).to({scaleX:0.8252,scaleY:0.8252,x:-23.3009},0).wait(1).to({scaleX:0.8267,scaleY:0.8267,x:-22.9904},0).wait(1).to({scaleX:0.8281,scaleY:0.8281,x:-22.6937},0).wait(1).to({scaleX:0.8295,scaleY:0.8295,x:-22.4108},0).wait(1).to({scaleX:0.8308,scaleY:0.8308,x:-22.1417},0).wait(1).to({scaleX:0.832,scaleY:0.832,x:-21.8864},0).wait(1).to({scaleX:0.8331,scaleY:0.8331,x:-21.645},0).wait(1).to({scaleX:0.8342,scaleY:0.8342,x:-21.4173},0).wait(1).to({scaleX:0.8352,scaleY:0.8352,x:-21.2034},0).wait(1).to({scaleX:0.8362,scaleY:0.8362,x:-21.0033},0).wait(1).to({scaleX:0.8371,scaleY:0.8371,x:-20.817},0).wait(1).to({scaleX:0.8379,scaleY:0.8379,x:-20.6445},0).wait(1).to({scaleX:0.8387,scaleY:0.8387,x:-20.4858},0).wait(1).to({scaleX:0.8393,scaleY:0.8393,x:-20.3409},0).wait(1).to({scaleX:0.84,scaleY:0.84,x:-20.2098},0).wait(1).to({scaleX:0.8405,scaleY:0.8405,x:-20.0925},0).wait(1).to({scaleX:0.841,scaleY:0.841,x:-19.9891},0).wait(1).to({scaleX:0.8415,scaleY:0.8415,x:-19.8994},0).wait(1).to({scaleX:0.8418,scaleY:0.8418,x:-19.8235},0).wait(1).to({scaleX:0.8421,scaleY:0.8421,x:-19.7614},0).wait(1).to({scaleX:0.8423,scaleY:0.8423,x:-19.7131},0).wait(1).to({scaleX:0.8425,scaleY:0.8425,x:-19.6786},0).wait(1).to({regX:-0.6,scaleX:0.8426,scaleY:0.8426,x:-20.2},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.9,-106.5,257.7,213.2);


(lib.snake_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(102,102,102,0.898)").s().p("AgmAmQgPgPAAgXQAAgVAPgRQAQgPAWAAQAXAAAPAPQAQARAAAVQAAAXgQAPQgPAQgXAAQgWAAgQgQg");
	this.shape.setTransform(8.55,-2.05);
	this.shape._off = true;

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(102,102,102,0.898)").s().p("AgiAjQgQgNgCgSQAAgUAPgPQAPgPAVgBQAHAAAIACQAMADAJAJQALAKAEANQACAGABAFQABANgGALQgEAGgFAEQgQANgVAAQgUAAgQgNg");
	this.shape_1.setTransform(8.5077,-2.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(102,102,102,0.898)").s().p("AAFApQgTAAgQgKQgPgKgGgOIAAAAQABgSAOgOQAOgOAVgBQAGgBAHACQAMACAJAIQALAJAFAMQACAFABAFQACAMgEALIgJAHQgPAJgTAAIgCAAg");
	this.shape_2.setTransform(8.4475,-3.28);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(102,102,102,0.898)").s().p("AAHAjQgSAAgQgIQgPgHgIgJIgBAAQACgRANgNQAOgOATgBQAGgBAGACQAMABAJAHQALAHAGAMIAEAJQACALgCAKIgKAFQgOAGgSAAIgCAAg");
	this.shape_3.setTransform(8.4444,-3.8795);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(102,102,102,0.898)").s().p("AAIAdQgRAAgPgFQgQgEgKgFIgBAAQACgPAMgNQAOgNASgCIALABQALABAJAFQALAGAHALIAEAIQAEAKgBAKIgKACQgNADgQAAIgEAAg");
	this.shape_4.setTransform(8.46,-4.5052);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(102,102,102,0.898)").s().p("AAJAWQgPAAgPgCIgdgBIgBAAQADgPALgLQAMgMASgDQAFAAAFAAQALAAAIAFQALAFAIAJIAFAHQAFAJABAKIgKAAIgKAAIgXgBg");
	this.shape_5.setTransform(8.5,-5.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(102,102,102,0.898)").s().p("AgzAUQADgOAKgJQAQgQAWAAQAXAAAPAQQALAJADAOQgzgMg0AMg");
	this.shape_6.setTransform(8.55,-5.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},6).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[]},1).wait(21));
	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6).to({_off:false},0).wait(7).to({_off:true},1).wait(27));

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_6 = new cjs.Graphics().p("Ak9hTIChiwIHaD+IgqEJQllgXjslAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(6).to({graphics:mask_graphics_6,x:54.9875,y:32.5}).wait(16).to({graphics:null,x:0,y:0}).wait(19));

	// Layer_2
	this.instance = new lib.tg("synched",0);
	this.instance.setTransform(40.35,4.35,1,1,-29.9992);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(6).to({_off:false},0).to({rotation:-30.9912,x:62.85,y:17.6},7,cjs.Ease.get(1)).wait(1).to({rotation:-31.0292,x:62.6986,y:17.5149},0).wait(1).to({regX:0.1,regY:0.1,rotation:-31.1431,x:62.3,y:17.25},0).wait(1).to({regX:0,regY:0,rotation:-31.5024,x:60.502,y:16.3438},0).wait(1).to({rotation:-32.0731,x:57.8845,y:14.9841},0).wait(1).to({rotation:-32.8551,x:54.2976,y:13.1207},0).wait(1).to({rotation:-33.8486,x:49.7413,y:10.7537},0).wait(1).to({rotation:-35.0533,x:44.2156,y:7.8832},0).wait(1).to({rotation:-36.4695,x:37.85,y:4.6},0).to({_off:true},1).wait(19));

	// Layer_1
	this.instance_1 = new lib.snake();
	this.instance_1.setTransform(-148.6,-96.9,0.9316,0.9316);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-148.6,-96.9,297.2,193.8);


(lib.Frog = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.instance = new lib.f("synched",0);
	this.instance.setTransform(-119.2,-10.2,0.24,0.24,0,0,0,0,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:-0.5,scaleX:0.3844,scaleY:0.3844,x:-133.1,y:-18.75},0).wait(1).to({regX:-0.1,regY:-0.3,scaleX:0.5136,scaleY:0.5136,x:-145.6,y:-26.25},0).to({regY:-0.4,scaleX:0.81,scaleY:0.6866,x:-163.7,y:-20.5},1).wait(1).to({regX:0,regY:-0.5,scaleX:0.9525,scaleY:0.9216,x:-174.45,y:-12.9},0).wait(1).to({regY:0,scaleX:1,scaleY:1,x:-178.2,y:-10.2},0).wait(16));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-250.2,-51.2,148.29999999999998,81);


// stage content:
(lib.KSFY_216373_MM_728x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Eg43gHBMBxvAAAIAAODMhxvAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(168));

	// Layer_11
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#009738").ss(2,2,1).p("AAAgrIAABX");
	this.shape_1.setTransform(511,35.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#009738").ss(2,2,1).p("AAABDIAAiF");
	this.shape_2.setTransform(511,35.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#009738").ss(2,2,1).p("AAABZIAAix");
	this.shape_3.setTransform(511,35.625);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#009738").ss(2,2,1).p("AAABtIAAjZ");
	this.shape_4.setTransform(511,35.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#009738").ss(2,2,1).p("AAAB/IAAj9");
	this.shape_5.setTransform(511,35.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#009738").ss(2,2,1).p("AAACPIAAkd");
	this.shape_6.setTransform(511,35.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#009738").ss(2,2,1).p("AAACdIAAk5");
	this.shape_7.setTransform(511,35.625);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#009738").ss(2,2,1).p("AAACqIAAlT");
	this.shape_8.setTransform(511,35.625);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#009738").ss(2,2,1).p("AAAC0IAAln");
	this.shape_9.setTransform(511,35.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#009738").ss(2,2,1).p("AAAC9IAAl5");
	this.shape_10.setTransform(511,35.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#009738").ss(2,2,1).p("AAADDIAAmF");
	this.shape_11.setTransform(511,35.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#009738").ss(2,2,1).p("AAADIIAAmP");
	this.shape_12.setTransform(511,35.625);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#009738").ss(2,2,1).p("AAADLIAAmV");
	this.shape_13.setTransform(511,35.625);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#009738").ss(2,2,1).p("AAAjLIAAGX");
	this.shape_14.setTransform(511,35.625);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},45).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).wait(110));

	// t3
	this.instance = new lib.t3("synched",0);
	this.instance.setTransform(640.5,38.85,0.6,0.6,0,0,0,0.1,0);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(45).to({_off:false},0).to({regX:0,scaleX:1,scaleY:1,alpha:1},13,cjs.Ease.get(1)).wait(110));

	// t2
	this.instance_1 = new lib.t2("synched",0);
	this.instance_1.setTransform(323.25,72.3,0.3888,0.3888,0,0,0,0.1,0.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(64).to({_off:false},0).to({regY:0.2,scaleX:0.6479,scaleY:0.6479,alpha:1},13,cjs.Ease.get(1)).wait(91));

	// t1
	this.instance_2 = new lib.t1("synched",0);
	this.instance_2.setTransform(443.2,34.75,0.4592,0.4592,0,0,0,0.5,0.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(26).to({_off:false},0).to({regX:0.2,regY:0.2,scaleX:0.7654,scaleY:0.7654,x:443.1,y:34.7,alpha:1},13,cjs.Ease.get(1)).wait(129));

	// lizart_png
	this.instance_3 = new lib.lizart_png("synched",0);
	this.instance_3.setTransform(537.55,76,0.49,0.49,0,0,180,-0.1,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({regY:0.1,x:520.4,y:77},104,cjs.Ease.get(1)).wait(64));

	// snake_png
	this.instance_4 = new lib.snake_1("synched",0);
	this.instance_4.setTransform(672.55,58.9,0.4665,0.4665,0,0,180,0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(168));

	// turtle_png
	this.instance_5 = new lib.turtle_1("synched",0,false);
	this.instance_5.setTransform(208.95,48.95,0.729,0.729);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(168));

	// Frog
	this.instance_6 = new lib.Frog("synched",0,false);
	this.instance_6.setTransform(458.5,30.5,0.567,0.567,0,0,0,0.1,0.1);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(14).to({_off:false},0).wait(154));

	// Cta
	this.instance_7 = new lib.cta("synched",0);
	this.instance_7.setTransform(328.1,113.4,0.81,0.81,0,0,0,0.6,0.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({regX:0.2,regY:0,x:328.25,y:33.35},14,cjs.Ease.get(1)).wait(154));

	// BG_jpg
	this.instance_8 = new lib.bg("synched",0);
	this.instance_8.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(168));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(363,16.3,379,110.5);
// library properties:
lib.properties = {
	id: 'EEF434D48E144756B168A098B39DCC79',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"frog.png", id:"frog"},
		{src:"lizart.png", id:"lizart"},
		{src:"snake.png", id:"snake"},
		{src:"Tounge.png", id:"Tounge"},
		{src:"turtle.png", id:"turtle"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EEF434D48E144756B168A098B39DCC79'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;