(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgUAnQgJgGgGgJQgFgKAAgNQAAgNAFgKQAGgKAJgFQAKgGALAAQAMAAAJAGQAJAEAFALQAFAJAAANIAAADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAACQAAAGADAFQADAGAGACQAFADAFABQAHAAAFgDQAGgDAEgGIACgBIABAAIAKAFQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBAAQgEAHgGAEQgFAEgHADQgHABgIAAQgLAAgKgFgAgJgbQgFADgCAFQgDAGAAAGIAlAAIACAAIABgCQAAgFgCgFQgDgFgEgDQgEgDgHAAQgFAAgFADg");
	this.shape.setTransform(64.125,23.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgWAnQgKgFgEgIIAAgBIABgCIAJgFIACgBIABABIAGAHQADACAFACQAEACAGAAQAFAAAEgCQAEgBACgDQADgCAAgDQAAgDgDgDQgDgCgHgCIgPgEQgMgDgGgEQgGgGAAgJQAAgIAFgGQAEgGAIgDQAHgEAKAAQAMAAAJAFQAIAEAEAGIABACIgBABIgKAFIgBAAIgCAAQgDgEgFgDQgFgDgHAAQgGAAgFADQgEADAAAEQAAADACADQACACAGACIASAFQANADAFAFQAFAHAAAHQAAAJgEAGQgFAGgIADQgJADgKAAQgNAAgKgFg");
	this.shape_1.setTransform(54.525,23.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgeAlQgHgGAAgKQAAgJAGgGQAFgGAKgDQAKgFANAAIAIgBIACAAIABgCIAAgDQAAgHgEgFQgEgDgIAAQgEgBgFADQgFACgEAGIgBABIgCAAIgNgDIgBgBIAAgDQAEgIAKgFQAJgFANAAQAMAAAIAEQAIADADAGQAEAGAAAIIAAA4IgBACIgCABIgOAAIgCgBIgBgDIAAgFQAAgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBABQgFAEgHAEQgFACgIAAQgNAAgHgHgAAJABIgJACIgIAEIgGAFQgCACAAAEQAAAGAEADQAEADAGAAQAEAAADgCIAHgDIAEgFIACgFIAAgLQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAAAg");
	this.shape_2.setTransform(45.125,23.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAUA7IgCAAIgBgDIAAg3QAAgFgDgDQgEgEgGAAIgGABIgHAEIgHAGIAAA4QAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgPAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIAAAqIAAABIABgBIAKgHQAFgDADgBQAFgBAEAAQANAAAGAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_3.setTransform(35.675,21.525);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgSAnQgJgGgGgKQgFgJAAgOQAAgLAFgKQAGgLAJgFQAKgGALAAQAJAAAHAEQAHADAFAFQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAABAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgEgGIgFgFQgDgBgEAAQgGAAgFADQgFAEgCAGQgDAIAAAIQAAAKADAGQADAIAFADQAFAEAGAAQAHAAAEgFQAFgDAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAHQgFAEgGACQgGACgHAAQgLAAgKgFg");
	this.shape_4.setTransform(26.0313,23.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWArIgCAAIgBgDIAAhOQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAABAAIAPAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAKIABABQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQADgFAEgDIAIgEQAEgCAFAAQAFAAAAACIAAAQQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgFgBIgFAAIgHABIgFADIgFAGQgBACAAADIAAAwQAAABAAABQgBAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_5.setTransform(18,23.125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgZAoQgFgDgDgFQgDgGAAgIIAAg5QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAPAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAA2QABAGADADQADAEAHAAQAEAAAFgDQAFgDAFgFIAAg4QAAgDADAAIAPAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAABOQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgQAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgBAAQgIAHgHADQgFADgHAAQgIAAgGgDg");
	this.shape_6.setTransform(9.05,23.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgrA7IgCAAIgBgDIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAsAAQANAAAKADQALAEAGAIQAGAIAAANQAAAMgGAHQgFAHgKAEQgJAEgNAAIgYAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAABIAAAqQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAgAgWgnIAAAhQAAAAAAABQABAAAAABQAAAAAAAAQABAAAAAAIAVAAQAKAAAGgFQAGgEAAgKQAAgGgDgEQgDgEgFgCQgFgCgHAAIgTAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABAAAAg");
	this.shape_7.setTransform(-1.525,21.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgiA0QgMgFAAgLQAAgFAFgEQAEgEAGgDQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAgBAAIgGgFQgCgCgBgEQAAgDACgDIAGgDIAHgEIABgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQgIgDgDgGQgFgFAAgIQAAgMAKgHQALgHASAAQAIAAAGACQAHABADAEIACABIADgBIAEgFIAGgDIAFgBIADABIABACIAAAJIgBADIgDABIgEgBIgDABQgBABgBAAQgBAAAAABQgBAAAAABQAAAAAAABIABADIABAFQAAAHgEAGQgEAGgIAEQgIADgMAAIgLABQgFABgBABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAIAJACIAVABQAQABAGAGQAIAGAAAKQAAAMgMAHQgLAIgUAAQgXAAgKgGgAgVAYIgFAEQgDADAAADQAAAEAEADQADADAGACQAGABAKAAQALAAAHgDQAFgEAAgGQABgEgEgDQgDgCgHgBIgZgBIgCAAIgEABgAgQgoQgEAEgBAIQABAGAEAEQAFAEAJAAQAIAAAFgEQAEgEAAgGQAAgIgEgEQgFgEgIAAQgJAAgFAEg");
	this.shape_8.setTransform(-17,24.475);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAABAAABQAAAAgBABQAAAAgBAAQgBAAgBAAIgOAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_9.setTransform(-27.175,23.125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgGA7IgDAAIgBgDIAAhOQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABOIgBACIgEABgAgGglIgDAAIgBgDIAAgPQAAgBABgBQAAAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAQQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_10.setTransform(-34.55,21.525);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgiA3QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgKIABgCIAEgBIAKAAQADAAADgBIAEgFIADgFIgBgFIgfhLQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAQAAIACABIACACIATA0IABABIABgBIAUg0IABgCIACgBIAMAAIACACIAAACIgiBTIgGAMQgDAFgEACQgEADgFABIgLABg");
	this.shape_11.setTransform(-41.6208,24.525);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgIA7QgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAhCIgBgBIgNAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgKIAAgCIACgBIAMAAQABAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIAAgKQAAgKAFgGQAGgFAKAAIAQAAQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAAAJIgBACIgCABIgJAAQgEAAgCACQgCADAAAFIAAAIQAAAAAAAAQAAABAAAAQAAAAAAAAQABAAAAAAIAPAAIACABIABACIAAAKQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAAAAAIgPAAQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAABBQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_12.setTransform(-49.75,21.525);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgHA7IgCAAIgBgDIAAhOQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABOIgBACIgDABgAgHglIgCAAIgBgDIAAgPQAAgBABgBQAAAAAAgBQAAAAABAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAQQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_13.setTransform(-55.55,21.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgHA7QAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAhwQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAABwIgBACQAAABAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_14.setTransform(-60.25,21.525);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgeAlQgHgGAAgKQAAgJAGgGQAFgGAKgDQAKgFANAAIAIgBIACAAIABgCIAAgDQAAgHgEgFQgEgDgIAAQgEgBgFADQgFACgEAGIgBABIgCAAIgNgDIgBgBIAAgDQAEgIAKgFQAJgFANAAQAMAAAIAEQAIADADAGQAEAGAAAIIAAA4IgBACIgCABIgOAAIgCgBIgBgDIAAgFQAAgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBABQgFAEgHAEQgFACgIAAQgNAAgHgHgAAJABIgJACIgIAEIgGAFQgCACAAAEQAAAGAEADQAEADAGAAQAEAAADgCIAHgDIAEgFIACgFIAAgLQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAAAg");
	this.shape_15.setTransform(-67.625,23.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgZAoQgFgDgDgFQgDgGgBgIIAAg5QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAOAAQABAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAA2QAAAGAEADQAEAEAGAAQAEAAAFgDQAFgDAEgFIAAg4QAAgDAFAAIAOAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAABOQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgQAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgBAAQgIAHgHADQgGADgGAAQgIAAgGgDg");
	this.shape_16.setTransform(-77.15,23.275);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAeBCQgIgFgIgJQAAgBAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgGABIgGAAQgPAAgMgHQgMgHgHgOQgGgOAAgSQAAgTAGgOQAHgOAMgHQAMgHAPAAQAQAAAMAHQAMAHAHAOQAGAOAAATQAAARgFAMQgFAMgKAIIAAABQAAABAAAAQAAAAAAABQABAAAAABQABABAAAAIAHAEQAEADAFAAIABABIABABIAAAMQAAAAAAABQAAAAgBAAQAAABAAAAQAAABgBAAIgEAAQgJAAgIgEgAgVgpQgHAKAAAYQAAAVAHALQAHAKAOAAQAPAAAHgKQAHgLAAgWQAAgWgHgLQgHgLgPAAQgOAAgHALg");
	this.shape_17.setTransform(-88.575,22.425);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAUA7IgCAAIgBgDIAAg3QAAgFgDgDQgEgEgGAAIgGABIgHAEIgHAGIAAA4QAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgPAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAqIAAABIABgBIAKgHQAFgDADgBIAJgBQANAAAGAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_18.setTransform(77.425,2.125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape_19.setTransform(67.675,2.375);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgHA7IgCAAIAAgDIAAhOQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABOIgBACIgCABgAgHglIgCAAIAAgDIAAgPQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAQQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_20.setTransform(61.8,2.125);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAcA7QgEAAgBgDIgWhMIgBgBIAAABIgWBMQgBADgDAAIgPAAQgEAAgBgDIgghuIAAgDIADgBIARAAIACAAIABACIAXBPIABACIABgCIAWhPIABgCIADAAIANAAIADAAIABACIAXBQIABABIABgBIAWhQIABgCIADAAIAMAAIADABIAAADIggBuQgBADgEAAg");
	this.shape_21.setTransform(50.625,2.125);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgWArIgDAAIAAgDIAAhOQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAQAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAAKIAAABQABAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQADgFAEgDIAIgEQAEgCAEAAQAGAAAAACIAAAQQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgFgBIgFAAIgGABIgHADIgDAGQgCACAAADIAAAwQAAADgEAAg");
	this.shape_22.setTransform(34.6,3.725);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgUAnQgJgGgGgKQgFgJAAgMQAAgOAFgKQAGgKAJgGQAKgFALAAQAMAAAJAFQAJAFAFAKQAFALAAANIAAACQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAABQAAAHADAGQADAEAGAEQAFADAFAAQAHgBAFgCQAGgDAEgGIACgBIABABIAKAEQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBAAQgEAHgGAEQgFAFgHABQgHACgIAAQgLAAgKgFgAgJgaQgFACgCAGQgDAFAAAHIAlAAIACgBIABgCQAAgFgCgFQgDgEgEgDQgEgEgHAAQgFAAgFAEg");
	this.shape_23.setTransform(25.825,3.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAUA7IgCAAIgBgDIAAg3QAAgFgDgDQgEgEgGAAIgGABIgHAEIgHAGIAAA4QAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgPAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAqIAAABIABgBIAKgHQAFgDADgBIAJgBQANAAAGAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_24.setTransform(15.825,2.125);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgSAnQgJgGgGgKQgFgJAAgNQAAgMAFgLQAGgKAJgGQAKgFALAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOACQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAAAIgEgGIgFgEQgDgCgEAAQgGAAgFAEQgFADgCAHQgDAHAAAIQAAAKADAHQADAGAFAEQAFADAGAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgLAAgKgFg");
	this.shape_25.setTransform(6.1813,3.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgZAoQgFgDgDgFQgEgGABgIIAAg5QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAPAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAA2QABAGADADQADAEAHAAQAEAAAFgDQAFgDAFgFIAAg4QAAgDADAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAABIAABOQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgQAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgBAAQgIAHgHADQgFADgHAAQgIAAgGgDg");
	this.shape_26.setTransform(-3.65,3.875);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgVAnQgJgGgGgKQgFgKAAgMQAAgMAGgLQAFgKAJgGQAKgFALAAQAMAAAKAGQAJAFAGAKQAFALAAAMQAAAMgFAKQgGAKgJAGQgKAFgMAAQgLAAgKgFgAgKgZQgFADgCAHQgDAHAAAIQAAAJADAIQACAGAFAEQAFADAFAAQAHAAAEgDQAFgEADgGQACgIAAgJQAAgIgCgHQgDgHgFgDQgEgEgHAAQgFAAgFAEg");
	this.shape_27.setTransform(-13.65,3.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgIA7QgEAAAAgDIgnhvQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIACgBIATAAQABAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAcBVQAAABAAAAQABABAAAAQAAAAAAgBQABAAAAgBIAchVQABgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAPAAIADABIAAACIgoBvQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAg");
	this.shape_28.setTransform(-24.7958,2.125);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgOAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhOQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_29.setTransform(-39.775,3.725);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgVAnQgKgGgFgKQgFgKAAgMQAAgMAFgLQAGgKAKgGQAJgFALAAQAMAAAKAGQAJAFAGAKQAFALAAAMQAAAMgGAKQgEAKgKAGQgKAFgMAAQgLAAgKgFgAgKgZQgFADgCAHQgDAHAAAIQAAAJADAIQACAGAFAEQAEADAGAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgIgDgHQgCgHgFgDQgFgEgGAAQgGAAgEAEg");
	this.shape_30.setTransform(-49.9,3.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgHA7IgCAAIAAgDIAAhOQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABOIAAACIgDABgAgHglIgCAAIAAgDIAAgPQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAQAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAQQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_31.setTransform(-57.3,2.125);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape_32.setTransform(-64.325,2.375);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgeAmQgHgHAAgLQAAgIAGgHQAFgFAKgEQAKgEANAAIAIAAIACgBIABgCIAAgDQAAgIgEgDQgEgFgIAAQgEAAgFADQgFADgEAFIgBACIgCAAIgNgEIgBgBIAAgCQAEgJAKgGQAJgEANAAQAMAAAIADQAIAEADAGQAEAGAAAIIAAA3IgBADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBAAQgFAGgHACQgFADgIAAQgNAAgHgGgAAJACIgJABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAGAAQAEAAADgBIAHgEIAEgFIACgFIAAgLQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAAAg");
	this.shape_33.setTransform(-72.925,3.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgSAnQgJgGgGgKQgFgJAAgNQAAgMAFgLQAGgKAJgGQAKgFALAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOACQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIgEgGIgFgEQgDgCgEAAQgGAAgFAEQgFADgCAHQgDAHAAAIQAAAKADAHQADAGAFAEQAFADAGAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgLAAgKgFg");
	this.shape_34.setTransform(-81.9687,3.8);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgeAmQgHgHAAgLQAAgIAGgHQAFgFAKgEQAKgEANAAIAIAAIACgBIABgCIAAgDQAAgIgEgDQgEgFgIAAQgEAAgFADQgFADgEAFIgBACIgCAAIgNgEIgBgBIAAgCQAEgJAKgGQAJgEANAAQAMAAAIADQAIAEADAGQAEAGAAAIIAAA3IgBADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBAAQgFAGgHACQgFADgIAAQgNAAgHgGgAAJACIgJABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAGAAQAEAAADgBIAHgEIAEgFIACgFIAAgLQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAg");
	this.shape_35.setTransform(-91.775,3.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgIA7QgEAAAAgDIgnhvQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIACgBIATAAQABAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAcBVQAAABAAAAQABABAAAAQAAAAAAgBQABAAAAgBIAchVQABgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAPAAIADABIAAACIgoBvQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAg");
	this.shape_36.setTransform(-102.2958,2.125);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgIApQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgRQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIARAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAARQAAAEgEAAgAgIgRQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAgRQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIARAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAASQAAAEgEgBg");
	this.shape_37.setTransform(44.225,-15.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgWAnQgKgFgEgIIAAgBIABgCIAJgFIACgBIABABIAGAHQADADAFABQAEACAGAAQAFAAAEgCQAEgBACgDQADgCAAgDQAAgEgDgCQgDgCgHgCIgPgEQgMgDgGgEQgGgGAAgJQAAgIAFgGQAEgGAIgDQAHgEAKAAQAMAAAJAFQAIAEAEAGIABACIgBABIgKAGIgBAAIgCgBQgDgFgFgCQgFgDgHAAQgGAAgFADQgEADAAAFQAAACACACQACADAGACIASAEQANAEAFAFQAFAHAAAHQAAAJgEAGQgFAGgIADQgJADgKAAQgNAAgKgFg");
	this.shape_38.setTransform(37.475,-15.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgZAoQgFgDgDgFQgDgGAAgIIAAg5QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAPAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAA2QAAAGAEADQADAEAHAAQAEAAAFgDQAFgDAFgFIAAg4QAAgDADAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAABIAABOQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgQAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgBAAQgIAHgHADQgGADgGAAQgIAAgGgDg");
	this.shape_39.setTransform(28.05,-15.525);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_40.setTransform(18.125,-15.675);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgVAmQgJgFgGgKQgFgKAAgNQAAgMAFgJQAGgLAJgFQAKgGALAAQANAAAJAGQAKAGAFAKQAFAJAAAMQAAANgGAKQgEAKgKAFQgJAGgNAAQgLAAgKgGgAgLgaQgEAEgDAGQgCAIAAAIQAAAJACAHQADAHAEADQAFAEAGAAQAHAAAFgEQAEgDACgHQADgHAAgJQAAgIgDgIQgCgGgEgEQgGgDgGAAQgGAAgFADg");
	this.shape_41.setTransform(8,-15.6);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgrA7IgCAAIgBgCIAAhwIABgDIACAAIApAAQAWAAAMAHQAMAIAAAQQAAAJgFAGQgEAGgMAFIAAAAIAAABQAMADAGAGQAGAHAAALQAAAQgMAIQgNAIgWAAgAgWAKIAAAeQAAABAAAAQAAABABAAQAAAAAAABQABAAAAAAIATAAQALAAAHgFQAFgEAAgIQAAgHgDgEQgDgEgFgCQgFgBgGAAIgTAAQgBAAgBAAQAAAAAAAAQgBABAAAAQAAABAAAAgAgWgoIAAAdQAAABAAAAQAAABABAAQAAAAAAABQABAAAAAAIAUAAIAIgBIAGgDQADgCACgDQACgDgBgFQABgIgHgFQgGgEgJAAIgSAAQgBAAgBAAQAAAAAAAAQgBABAAAAQAAABAAAAg");
	this.shape_42.setTransform(-2.85,-17.275);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQgBABAAAAIgGAAIgGABg");
	this.shape_43.setTransform(-16.675,-17.025);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgWAnQgKgFgEgIIAAgBIABgCIAJgFIACgBIABABIAGAHQADADAFABQAEACAGAAQAFAAAEgCQAEgBACgDQADgCAAgDQAAgEgDgCQgDgCgHgCIgPgEQgMgDgGgEQgGgGAAgJQAAgIAFgGQAEgGAIgDQAHgEAKAAQAMAAAJAFQAIAEAEAGIABACIgBABIgKAGIgBAAIgCgBQgDgFgFgCQgFgDgHAAQgGAAgFADQgEADAAAFQAAACACACQACADAGACIASAEQANAEAFAFQAFAHAAAHQAAAJgEAGQgFAGgIADQgJADgKAAQgNAAgKgFg");
	this.shape_44.setTransform(-24.825,-15.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgZAoQgFgDgDgFQgEgGABgIIAAg5QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAPAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAA2QABAGADADQADAEAHAAQAEAAAFgDQAFgDAFgFIAAg4QAAgDADAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAABIAABOQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgQAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgBAAQgIAHgHADQgFADgHAAQgIAAgGgDg");
	this.shape_45.setTransform(-34.25,-15.525);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgiA0QgMgFAAgLQAAgFAFgEQADgEAHgDQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAgBAAIgGgFQgCgCgBgEQAAgDACgDIAGgDIAHgEIABgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQgIgDgEgGQgEgFAAgIQAAgMAKgHQALgHASAAQAIAAAGACQAGABAEAEIACABIADgBIAEgFIAGgDIAFgBIADABIABACIAAAJIgBADIgDABIgEgBIgEABQgBAAAAABQgBAAAAABQgBAAAAABQAAAAAAABIABADIABAFQAAAHgEAGQgEAGgJAEQgHADgMAAIgLABQgEABgCABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAIAJACIAVABQAPABAHAGQAIAGAAAKQAAAMgLAHQgMAIgUAAQgXAAgKgGgAgVAYIgGAEQgCADAAADQAAAEAEADQADADAGACQAGABAKAAQALAAAGgDQAHgEgBgGQAAgEgDgDQgDgCgHgBIgZgBIgCAAIgEABgAgQgoQgEAEgBAIQABAGAEAEQAFAEAJAAQAIAAAFgEQAEgEAAgGQAAgIgEgEQgFgEgIAAQgJAAgFAEg");
	this.shape_46.setTransform(-44.55,-14.325);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgYAoQgGgDgDgFQgEgGAAgIIAAg5QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAOAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAAA2QgBAGAEADQAEAEAFAAQAFAAAFgDQAFgDAEgFIAAg4QABgDAEAAIAOAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAABIAABOQAAABgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIgPAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgCAAQgHAHgGADQgHADgHAAQgHAAgFgDg");
	this.shape_47.setTransform(-54.8,-15.525);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AAhA7QAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgJgaIgBgBIgBAAIgpAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAgBAAIgJAaIgBACIgCAAIgQAAIgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQABAAAAgBIAohvIABgCIADAAIATAAQADAAABADIAoBuIAAADIgCABgAgCghIgQAqQAAABAAAAQAAABAAAAQAAAAABABQAAAAABAAIAdAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAgBgBIgOgqIgBgBIgBABg");
	this.shape_48.setTransform(-66.0375,-17.275);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-129.9,-28.8,234.5,62.2);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AARAkIgCAAIgBgCIAAgtQAAgGgCgCQgDgDgGAAIgFABIgFADIgGAFIAAAvQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgMAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhCQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAHIABABIABgBIAHgFIAHgEQAEgBAFgBQAKAAAFAHQAGAFAAAJIAAAxQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(-113.575,38.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AARAkQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgNgoIgBgBIAAABIgNApIgBABIgCABIgKAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAgBgBIgVhBIAAgCIACgBIANAAIABABIABABIAOAqIABACIABgCIANgqIABgBIACgBIAIAAIACABIABABIANAqIABACIABgCIANgqIABgBIACgBIAIAAIACABIAAACIgVBCIgBABIgCABg");
	this.shape_1.setTransform(-123.575,38.475);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgRAgQgJgEgEgJQgEgIgBgLQABgKAEgIQAEgJAJgEQAIgFAJAAQALAAAHAFQAJAEAEAJQAEAIAAAKQAAALgEAIQgEAJgJAEQgHAFgLAAQgJAAgIgFgAgJgWQgEADgCAGQgCAGAAAHQAAAIACAGQACAFAEADQAEADAFAAQAGAAADgDQAEgDADgFQABgGAAgIQAAgHgBgGQgDgGgEgDQgDgDgGAAQgFAAgEADg");
	this.shape_2.setTransform(-133.6,38.475);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AglAyQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhdIABgCIACgBIAGAAIAHAAIAIAAIAGAAQARABAMAFQALAHAGAKQAFALAAAPQAAAPgFALQgGAMgMAGQgMAGgRAAgAgUghIAABDQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAABAAIADAAQAMAAAIgDQAIgDAEgJQADgHAAgNQAAgMgDgIQgEgIgIgDQgHgEgMAAIgFAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAg");
	this.shape_3.setTransform(-143.025,37.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgcAvQgBgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgIIABgCIADAAIAJAAIAFgCIADgDIACgFIAAgEIgag/IAAgCIACgBIAOAAIACAAIABACIAPAsIABABIACgBIAQgsIABgCIACAAIAKAAIABABIAAACIgcBFIgFALQgCAEgEACIgHADIgKABg");
	this.shape_4.setTransform(-155.775,39.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgQAhQgJgFgEgIQgFgIAAgLQAAgLAFgIQAFgJAIgEQAIgFAJAAQAKAAAIAEQAHAFAEAIQAFAIAAALIAAACIgCABIgvAAIgBABIgBABQAAAGADAEQACAFAFACQAEADAFAAQAFAAAFgCQAEgDAFgFIAAgBIACABIAIADQABABAAAAQAAAAAAAAQAAABAAAAQAAAAgBABQgEAGgEADQgFAEgFACQgGABgHAAQgJAAgIgEgAgHgWQgEACgCAFQgCAEAAAFIAeAAIACAAIABgCQAAgEgCgEQgCgEgEgCQgDgDgGAAQgEAAgEADg");
	this.shape_5.setTransform(-163.975,38.475);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AARAkIgCAAIgBgCIAAgtQAAgGgCgCQgDgDgGAAIgFABIgFADIgGAFIAAAvQAAABAAAAQgBABAAAAQAAAAgBAAQgBAAAAAAIgMAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhCQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAHIABABIABgBIAHgFIAHgEQAEgBAFgBQAKAAAFAHQAGAFAAAJIAAAxQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-172.425,38.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgSAgQgHgEgFgJQgFgIAAgLQAAgKAFgIQAFgJAHgEQAJgFAJAAQALAAAHAFQAJAEAEAJQAFAIgBAKQABALgFAIQgEAJgJAEQgHAFgLAAQgJAAgJgFgAgJgWQgDADgCAGQgDAGAAAHQAAAIADAGQACAFADADQAEADAFAAQAGAAADgDQAFgDABgFQACgGAAgIQAAgHgCgGQgBgGgFgDQgEgDgFAAQgFAAgEADg");
	this.shape_7.setTransform(-181,38.475);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAjAyIgCAAIAAgDIAAhFIgBgBIAAABIgaBGQgBAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgIAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAIgZhFIgBgBIAAABIAABFIgBACIgBAAIgMAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAgBIAAheQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAWAAIACAAIACACIAXA/IAAABIABgBIAXg+QAAgBABgBQAAAAAAAAQABgBAAAAQABAAAAAAIAYAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABeQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_8.setTransform(-191.9,37.05);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgSAgQgIgEgEgJQgEgIgBgLQABgKAEgIQAEgJAIgEQAJgFAJAAQALAAAHAFQAJAEAEAJQAEAIABAKQgBALgEAIQgEAJgJAEQgHAFgLAAQgJAAgJgFgAgIgWQgFADgCAGQgCAGAAAHQAAAIACAGQACAFAFADQADADAFAAQAGAAADgDQAEgDADgFQABgGAAgIQAAgHgBgGQgDgGgEgDQgDgDgGAAQgFAAgDADg");
	this.shape_9.setTransform(-206.05,38.475);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAbAyIgCAAIgBgBIgthBIgBgBIAAABIAABAQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgMAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhfQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAOAAIACAAIABACIArA9IABABIAAgBIAAg9QAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIANAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAABfIgBACIgBAAg");
	this.shape_10.setTransform(-215.75,37.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgIAUIgBgBIAAgBIAGgPQABgBAAgBQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIAAgPQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAPAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAOIAAACIgLATIgCACIgCAAg");
	this.shape_11.setTransform(-75.9625,23.95);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAHAwQgIAAgFgEQgFgFAAgIIAAgnQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBgBAAIgJAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIAKAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIACgUQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIALAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAABIAAAUQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAPAAQABAAAAABQABAAAAAAQAAAAABAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgPAAQgBAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAjQAAAGACABQACADAEAAIAIAAIACAAIAAACIAAAHQAAAAAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgFABIgFAAg");
	this.shape_12.setTransform(-80.925,19.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgTAhQgIgEgDgHIAAgBIAAgCIAIgEIACAAIABABIAFAFIAGADQAEACAEgBIAIgBQAEgBACgCQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgDgBgCQgDgCgGgCIgNgDQgKgCgFgEQgEgFgBgHQABgHADgFQADgFAHgDQAHgDAIAAQAKAAAHADQAHAEAEAGIABABIgBABIgIAFIgCAAIgBgBIgHgGQgEgCgGAAQgFAAgEACQgEADAAAEIABAEIAIADIAPAEQALADAEAEQAEAGABAHQAAAHgFAFQgDAFgIACQgGADgKAAQgKAAgJgEg");
	this.shape_13.setTransform(-87.85,20.325);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgQAhQgJgFgEgIQgFgIAAgLQAAgLAFgIQAFgJAIgEQAIgFAJAAQAKAAAIAEQAHAFAEAIQAFAIAAALIAAACIgCABIgvAAIgBABIgBABQAAAGADAEQACAFAFACQAEADAFAAQAFAAAFgCQAEgDAFgFIAAgBIACABIAIADQABAAAAABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAGgEADQgFAEgFACQgGABgHAAQgJAAgIgEgAgHgWQgEACgCAFQgCAEAAAFIAeAAIACAAIABgCQAAgEgCgEQgCgEgEgCQgDgDgGAAQgEAAgEADg");
	this.shape_14.setTransform(-95.725,20.325);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgSAlIgDgBIAAgCIAAhCQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAIIAAACIABgBIAGgHIAHgEIAHgCQAFAAAAADIAAAMQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgEgBIgFAAIgEABIgGAEIgDAEQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAABIAAAoQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAg");
	this.shape_15.setTransform(-102.75,20.25);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgQAhQgJgFgEgIQgFgIAAgLQAAgLAFgIQAFgJAIgEQAIgFAJAAQAKAAAIAEQAHAFAEAIQAFAIAAALIAAACIgCABIgvAAIgBABIgBABQAAAGADAEQACAFAFACQAEADAFAAQAFAAAFgCQAEgDAFgFIAAgBIACABIAIADQABAAAAABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAGgEADQgFAEgFACQgGABgHAAQgJAAgIgEgAgHgWQgEACgCAFQgCAEAAAFIAeAAIACAAIABgCQAAgEgCgEQgCgEgEgCQgDgDgGAAQgEAAgEADg");
	this.shape_16.setTransform(-110.225,20.325);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAHAwQgIAAgFgEQgFgFAAgIIAAgnQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAIgJAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAABAAQAAAAAAAAQABgBAAAAIAKAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIACgUQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIALAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAABIAAAUQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAPAAQABAAAAABQABAAAAAAQAAAAABAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgPAAQgBAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAjQAAAGACABQACADAEAAIAIAAIACAAIAAACIAAAHQAAAAAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgFABIgFAAg");
	this.shape_17.setTransform(-117.575,19.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AARAlIgCgBIgBgCIAAguQAAgFgCgDQgDgCgGAAIgFAAIgFADIgGAGIAAAvQAAABAAAAQgBABAAAAQAAAAgBAAQgBABAAAAIgMAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhCQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABAAIAHgGIAHgEQAEgCAFAAQAKABAFAFQAGAGAAAKIAAAvQAAABAAABQgBAAAAABQAAAAgBAAQAAABgBAAg");
	this.shape_18.setTransform(-124.875,20.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgGAyIgCAAIgBgCIAAhfQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAABeIgBADIgCAAg");
	this.shape_19.setTransform(-131.45,18.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgSAgQgHgEgFgJQgFgIAAgLQAAgKAFgIQAFgJAHgEQAJgFAJAAQALAAAHAFQAJAEAEAJQAFAIgBAKQABALgFAIQgEAJgJAEQgHAFgLAAQgJAAgJgFgAgJgWQgDADgCAGQgDAGAAAHQAAAIADAGQACAFADADQAEADAFAAQAGAAADgDQAFgDABgFQACgGAAgIQAAgHgCgGQgBgGgFgDQgEgDgFAAQgFAAgEADg");
	this.shape_20.setTransform(-141.4,20.325);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAbAyIgCAAIgBgBIguhBIAAgBIAAABIAABAQgBAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIgMAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIAAhfQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAOAAIABAAIACABIAqA+IABABIABgBIAAg9QAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAMAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAABgIAAACIgBAAg");
	this.shape_21.setTransform(-151.1,18.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgIAUIgBgBIAAgBIAGgPQAAgBABgBQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgPQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAPAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAOIAAACIgLATIgCACIgCAAg");
	this.shape_22.setTransform(-161.6625,23.95);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgTAhQgIgEgDgHIgBgBIABgCIAIgEIACAAIABABIAFAFIAGADQAEACAFgBIAHgBQADgBACgCQABAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgDgCgCQgCgCgGgCIgMgDQgLgCgFgEQgFgFAAgHQAAgHAEgFQADgFAHgDQAHgDAIAAQAKAAAHADQAIAEADAGIABABIgBABIgIAFIgCAAIgBgBIgHgGQgEgCgGAAQgFAAgEACQgEADAAAEIABAEIAIADIAPAEQALADAEAEQAEAGABAHQgBAHgDAFQgFAFgHACQgHADgIAAQgLAAgJgEg");
	this.shape_23.setTransform(-167.4,20.325);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAHAwQgIAAgFgEQgFgFAAgIIAAgnQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAgBgBAAIgJAAQAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAgBIAAgIQAAAAAAgBQABAAAAAAQAAAAAAAAQABgBAAAAIAKAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIACgUQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIALAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAABIAAAUQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAPAAQABAAAAABQABAAAAAAQAAAAABAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgPAAQAAAAgBABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAjQAAAGACABQACADAEAAIAIAAIACAAIAAACIAAAHQAAAAAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgFABIgFAAg");
	this.shape_24.setTransform(-174.775,19.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AARAlIgCgBIgBgCIAAguQAAgFgCgDQgDgCgGAAIgFAAIgFADIgGAGIAAAvQAAABAAAAQgBABAAAAQAAAAgBAAQgBABAAAAIgMAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhCQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABAAIAHgGIAHgEQAEgCAFAAQAKABAFAFQAGAGAAAKIAAAvQAAABAAABQgBAAAAABQAAAAgBAAQAAABgBAAg");
	this.shape_25.setTransform(-182.025,20.25);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgQAhQgJgFgEgIQgFgIAAgLQAAgLAFgIQAFgJAIgEQAIgFAJAAQAKAAAIAEQAHAFAEAIQAFAIAAALIAAACIgCABIgvAAIgBABIgBABQAAAGADAEQACAFAFACQAEADAFAAQAFAAAFgCQAEgDAFgFIAAgBIACABIAIADQABAAAAABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAGgEADQgFAEgFACQgGABgHAAQgJAAgIgEgAgHgWQgEACgCAFQgCAEAAAFIAeAAIACAAIABgCQAAgEgCgEQgCgEgEgCQgDgDgGAAQgEAAgEADg");
	this.shape_26.setTransform(-190.525,20.325);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAnAlIgCgBIgBgCIAAguQAAgFgDgDQgCgCgGAAIgFAAIgGADIgDAEIgCACIAAACIAAAsQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgLAAIgCgBIAAgCIAAguQAAgFgDgDQgDgCgFAAQgFgBgEADQgEACgEAFIAAAvQAAABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAIgMAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhCQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAMAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABAAIAHgGIAIgEQADgCAFAAQAHAAAFAEQAEAEACAFIABABIABgBIAHgHIAIgEIAJgCQAJABAGAFQAGAGgBAKIAAAvQAAABAAABQAAAAAAABQAAAAgBAAQAAABgBAAg");
	this.shape_27.setTransform(-201.15,20.25);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgcAvQgBgBAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgJIABgBIADgBIAJAAIAFgCIADgDIACgFQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgag/IAAgCIACgBIAOAAIACABIABABIAPAsIABABIACgBIAQgsIABgBIACgBIAKAAIABABIAAACIgcBGIgFAKQgCAEgEACIgHADIgKABg");
	this.shape_28.setTransform(-211.625,21.45);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgZAgQgGgGAAgJQAAgHAFgFQAEgFAJgDQAIgDALgBIAHAAIABgBIABgBIAAgDQAAgGgDgEQgEgDgGAAQgEAAgEACQgEACgDAFIgBABIgCAAIgLgDIgBAAIAAgDQAEgHAIgEQAIgEALAAQAKAAAGADQAHADADAFQADAFAAAHIAAAuIgBACIgBABIgMAAIgCgBIAAgCIgBgFQAAAAAAgBQAAAAgBAAQAAAAAAAAQgBABAAAAQgFAEgFADQgFACgHAAQgKAAgGgFgAAIABIgIABIgHADIgFAEQgBADAAADQAAAFADADQADACAGAAIAGgBIAFgDIAEgEIABgEIAAgKQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAAAgBAAg");
	this.shape_29.setTransform(-219.875,20.325);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgkAyIgCAAIAAgCIAAhfQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAmAAQALAAAIADQAJADAFAHQAFAHABAKQAAAKgFAHQgFAGgIADQgIAEgLAAIgUAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAAAkQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAgAgTggIAAAbQAAAAABABQAAAAAAAAQAAABABAAQAAAAAAAAIARAAQAJAAAFgEQAFgEAAgIQAAgGgDgDQgCgDgEgCQgFgBgFAAIgQAAQgBAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAABg");
	this.shape_30.setTransform(-228.45,18.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgRAgQgJgEgEgJQgEgIAAgLQAAgKAEgIQAEgJAJgEQAIgFAJAAQAKAAAJAFQAHAEAFAJQAEAIABAKQgBALgEAIQgFAJgHAEQgJAFgKAAQgJAAgIgFgAgIgWQgFADgCAGQgCAGAAAHQAAAIACAGQACAFAFADQAEADAEAAQAGAAAEgDQADgDADgFQACgGAAgIQAAgHgCgGQgDgGgDgDQgEgDgGAAQgEAAgEADg");
	this.shape_31.setTransform(-241.35,20.325);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAbAyIgBAAIgCgBIgthBIgCgBIAAABIAABAQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIgMAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhfQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIANAAIADAAIABABIArA+IABABIABgBIAAg9QAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIANAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAABgIgBACIgCAAg");
	this.shape_32.setTransform(-251.05,18.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgSAhQgJgEgDgHIgBgBIABgCIAIgEIACAAIABABIAEAFIAHADQAEACAFgBIAHgBQADgBACgCQABAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQgBgDgCgCQgCgCgGgCIgMgDQgLgCgFgEQgFgFABgHQgBgHAEgFQADgFAHgDQAHgDAIAAQAKAAAHADQAHAEAEAGIAAABIAAABIgJAFIgBAAIgBgBIgHgGQgEgCgGAAQgFAAgEACQgEADAAAEIACAEIAHADIAPAEQAKADAFAEQAFAGgBAHQAAAHgDAFQgEAFgHACQgHADgJAAQgMAAgHgEg");
	this.shape_33.setTransform(-127.05,2.125);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AARAyIgCAAIgBgCIAAgvQAAgEgCgDQgDgDgGAAIgFABIgFADIgGAFIAAAwQAAAAAAABQgBAAAAAAQAAABgBAAQgBAAAAAAIgMAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhfQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAjIABABIABAAIAIgHIAHgDIAIgBQAKAAAFAGQAGAFAAAKIAAAwQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_34.setTransform(-134.975,0.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAHAwQgIAAgFgFQgFgDAAgJIAAgoQAAAAAAAAQAAgBAAAAQAAAAgBAAQAAgBgBAAIgJAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgIQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAKAAQABAAAAgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIACgVQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIALAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAVQAAAAAAABQAAAAAAAAQAAAAABAAQAAABAAAAIAPAAQABAAAAAAQABAAAAAAQAAAAABAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgPAAQgBAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAjQAAAFACACQACACAEAAIAIAAIACABIAAACIAAAGQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgFABIgFAAg");
	this.shape_35.setTransform(-142.925,0.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AARAkIgCAAIgBgCIAAgtQAAgFgCgEQgDgCgGAAIgFABIgFACIgGAGIAAAvQAAABAAAAQgBABAAAAQAAAAgBAAQgBAAAAAAIgMAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhCQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAHIABABIABgBIAHgFIAHgEQAEgBAFgBQAKAAAFAHQAGAFAAAKIAAAwQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_36.setTransform(-150.175,2.05);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgRAgQgJgEgEgJQgFgIABgLQgBgKAFgIQAEgJAJgEQAIgFAJAAQAKAAAJAFQAHAEAFAJQAFAIAAAKQAAALgFAIQgFAJgHAEQgJAFgKAAQgKAAgHgFgAgIgWQgFADgBAGQgDAGAAAHQAAAIADAGQABAFAFADQAEADAEAAQAGAAAEgDQADgDACgFQACgGABgIQgBgHgCgGQgCgGgDgDQgEgDgGAAQgEAAgEADg");
	this.shape_37.setTransform(-158.75,2.125);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AAjAyIgCAAIgBgCIAAhGIAAgBIAAABIgbBGQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgIAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAIgZhFIAAgBIgBABIAABFIgBACIgCAAIgLAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhfQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAWAAIADAAIABACIAXA+IAAABIABgBIAXg+QAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAIAXAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABeQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_38.setTransform(-169.65,0.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AghAzIgCgBIAAgCIAAgJIAAgBIABgCIAEgDIAagZIAKgJIAGgHIADgGIABgGQAAgFgDgDQgCgEgDgBQgEgCgEAAQgDAAgEABIgHAFQgDADgDAFIgCABIgCgBIgKgFIgBgCIAAgCQAHgKAKgFQAIgFAKAAQAKAAAIAEQAJADAEAHQAEAGABAKQAAAFgCAFQgCAFgFAFIgMALIgYAWIgBABIABAAIArAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABABAAIAAANIgBABIgCABg");
	this.shape_39.setTransform(-184.1,0.625);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgZAyQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgLQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAPAAQABAAAAAAQAAAAAAAAQABAAAAgBQAAAAAAAAIAAg+QAAAAAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAIgOAFQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAgHIAAgCIACgBIAWgLIACgBIACAAIAIAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAABRIABABIAOAAQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAAAIAAALIgBACIgBAAg");
	this.shape_40.setTransform(-192.125,0.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgDAfQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgXIAMAAIgMAAIAAgLIAMAAIAAALIAAAYQAAAAAAABQgBAAAAAAQAAAAAAAAQgBAAAAAAgAAHAGIAAgLIgMAAIAAgXIAAgCIACgBIAHAAQABAAAAABQABAAAAAAQAAAAABAAQAAABAAAAIAAAYIAXAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAgAgcAGIgCAAIgBgCIAAgHQAAgBAAAAQABgBAAAAQAAAAAAAAQABAAAAAAIAYAAIAAALgAgFAGg");
	this.shape_41.setTransform(-203.225,0.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-281.9,-9.1,233.99999999999997,56.4);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6CC14C").s().p("AggAzIgCAAIgBgDIAAhfQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgqAAQgBAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIAAAVQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgdAAQgBAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAIAAAlQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape.setTransform(55.575,4.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6CC14C").s().p("AggAzIgCAAIgBgDIAAhfQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIBDAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgqAAQgBAAgBAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAAVQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgdAAQgBAAAAABQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAlQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(46.875,4.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6CC14C").s().p("AgYAuQgLgGgFgMQgGgLAAgRQAAgPAGgMQAGgMAKgGQALgHANAAQAPAAAKAHQALAGAFAMQAGAMAAAPQAAAQgGAMQgFALgLAHQgKAGgPAAQgNAAgLgGgAgPgaQgGAIAAASQAAATAFAIQAGAIAKAAQALABAGgJQAFgIAAgTQAAgSgFgIQgGgJgLAAQgKAAgFAJg");
	this.shape_2.setTransform(36.975,4.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC14C").s().p("AAVAxQgHgEgDgGQgDgIgBgIQABgHADgHQADgGAHgEQAGgEAGAAQAIAAAGAEQAGAEADAGQADAHABAHQgBAIgDAIQgDAGgGAEQgGADgIAAQgGAAgGgDgAAcAHQgCADgCAEIgBAJIABAKQACAEACACQACACADAAQAEAAADgCIADgGIABgKIgBgJQgBgEgCgDQgDgCgEAAQgDAAgCACgAgkAzQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAIABgCIBAhiIACgBIACAAIAHAAIABAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIhCBjQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAAAAAgAguACQgGgEgDgGQgEgGABgJQgBgIAEgGQAEgHAFgEQAGgEAIABQAHgBAFAEQAGAEAEAHQAEAGAAAIQAAAJgEAGQgEAGgFAEQgGADgHAAQgIAAgGgDgAgmgnQgCACgBAFQgCAEAAAFIABAKQABAFADACQACACAEgBQAFAAADgEQACgFAAgJQgBgIgCgFQgCgFgFAAQgEAAgCACg");
	this.shape_3.setTransform(38.15,-10.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6CC14C").s().p("AgnBTQgRgMgKgVQgKgUAAgdQAAgVAGgRQAGgSAKgMQALgNAOgHQAOgGAPAAQARAAAOAGQAOAHAKANQAKAMAGASQAGARAAAVQAAAcgKAVQgKAVgRAMQgSALgWAAQgVAAgSgLgAgRg5QgHAHgEAOQgEAPAAAWQAAAXAEANQAEAOAHAHQAHAGAKAAQALAAAHgGQAIgHADgOQAEgNAAgXQAAgWgEgPQgEgOgHgHQgHgGgLAAQgKAAgHAGg");
	this.shape_4.setTransform(21.475,-1.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6CC14C").s().p("AALBcQgGAAABgFIAAgkQAAgBgBAAQAAgBAAAAQgBAAAAAAQgBAAgBAAIhJAAQgFAAAAgFIAAgUIACgGIAEgHIBKhhIAFgEIAGgBIAfAAQADAAAAAEIAABoQAAAAABABQAAAAAAAAQAAABABAAQAAAAABAAIAVAAQAEAAAAAEIAAAVQAAAFgFAAIgTAAQgBAAgBAAQAAAAgBAAQAAABAAAAQgBABAAABIAAAjQABAFgHAAgAACgtIgrA9QgCADAEAAIAqAAQABAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIAAg9IAAgDg");
	this.shape_5.setTransform(3.1,-1.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6CC14C").s().p("AgsBTQgTgLgKgVQgLgVAAgdQAAgcALgWQAKgVAUgMQATgLAYAAQAaAAATALQATAMALAVQAKAVAAAcQAAAdgKAWQgLAUgTAMQgTAMgaAAQgZAAgTgMgAgdgvQgJAPAAAhQAAAhAJAPQAKAPATAAQAVAAAJgOQAKgPAAgiQAAghgKgPQgKgQgUAAQgTAAgKAQg");
	this.shape_6.setTransform(-20.125,-1.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6CC14C").s().p("AgpBTQgTgMgKgVQgKgVAAgcQAAgdAKgUQALgWATgLQATgMAZAAQAUAAAQAIQAQAHAKAMQAJALADAOIAAAFQAAAAAAABQAAAAgBAAQAAABgBAAQgBAAAAAAIghAFIgCgBIgCgDQgBgIgFgHQgEgHgIgEQgHgEgKAAQgLAAgJAHQgJAGgEAOQgFAOAAAWQAAAXAFAOQAFAOAJAHQAJAGALAAQAIAAAGgCQAHgCAEgFQAEgDADgGQADgFABgGIAAgHQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAAAgBAAIgeAAIgDgBIgBgEIAAgSQAAgCAEgBIBCAAQAEABABAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIAABTIgBADIgCABIgIAAIgEgBIgDgDIgHgSIgBAAIgCAAIgLALQgGAHgKADQgKAEgPAAQgYAAgSgMg");
	this.shape_7.setTransform(-39.125,-1.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6CC14C").s().p("AgsBTQgTgLgKgVQgLgVAAgdQAAgcALgWQAKgVAUgMQATgLAYAAQAaAAATALQATAMALAVQAKAVAAAcQAAAdgKAWQgLAUgTAMQgTAMgaAAQgZAAgTgMgAgdgvQgJAPAAAhQAAAhAJAPQAKAPATAAQAVAAAJgOQAKgPAAgiQAAghgKgPQgKgQgUAAQgTAAgKAQg");
	this.shape_8.setTransform(-57.925,-1.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6CC14C").s().p("AhGBcIgEgBIgBgDIAAitQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAIBDAAQAkAAATAMQATANAAAXQAAAOgHAKQgIAJgRAIIgBABIABAAQATAGAJALQAJAKAAAQQAAAagUAMQgTAMglAAgAgfASIAAAoQAAAEADAAIAbAAQAPAAAIgGQAIgHAAgLQAAgHgEgGQgEgFgGgDQgHgDgJAAIgbAAQgEAAAAAEgAgfg5IAAAmQAAAEADAAIAcAAIALgCQAFgBAEgCQAEgDACgFQACgEAAgFQAAgNgIgFQgJgHgMAAIgaAAQgEAAAAAFg");
	this.shape_9.setTransform(-76.075,-1.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#47C434").s().p("AgDAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgUIgUAAIgCgBIgBgBIAAgIQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAVAAIAAANIAAgNIANAAIgNAAIAAgUIABgCIACgBIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAVIAVAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAIgUAAIAAgNIAAANIgNAAIANAAIAAAVQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_10.setTransform(-13.225,17.825);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAHAyQgIAAgFgFQgFgEAAgJIAAgpQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgJQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIACgVQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIALAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAVIABABIAQAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAJQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgQAAQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAAkQAAAGADACQACACAEAAIAIAAIACAAIAAACIAAAHQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgFAAIgFABg");
	this.shape_11.setTransform(51.85,32.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgFA0IgCAAIgBgCIAAhFQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAABEIgBADIgDAAgAgGggIgCgBIgBgCIAAgNQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAABIAAANQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_12.setTransform(47.25,32);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AARAmIgCgBIgBgCIAAgvQAAgFgCgDQgDgDgGAAIgGABIgFADIgGAFIAAAxQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgNAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAHIAAABIABgBIAIgGIAHgDQAEgCAFAAQAKAAAGAGQAGAGAAAKIAAAyQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_13.setTransform(41.4,33.425);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgXAwQgIgFgEgJQgEgJAAgNIAAg9QAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIAQAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABAQAAAMAGAFQAFAGAJAAQAHAAAFgDQAFgCACgFQADgFAAgJIAAg/QAAgBAAAAQABgBAAAAQAAAAAAgBQABAAAAAAIANAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAA/QAAAOgFAJQgEAIgJAEQgJAEgNAAQgOAAgJgFg");
	this.shape_14.setTransform(32.225,32.075);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgdAxQgBgBAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgIIAAgCIAEgBIAJAAQADAAACgCIAEgDIACgFQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgbhCIABgCIACgBIAOAAIACABIABABIAQAuIABABQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIARguIABgBIACgBIAKAAIABABQAAAAABABQAAAAAAAAQAAAAAAABQgBAAAAAAIgdBJIgGALQgBADgEACQgDADgFABIgKABg");
	this.shape_15.setTransform(20.425,34.65);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAAAAAABQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_16.setTransform(13.275,33.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgRAhQgIgEgFgJQgFgIAAgLQAAgLAFgJQAFgJAJgFQAIgFAJAAQAKAAAJAFQAHAFAFAIQAEAJAAALIAAADIgCAAIgxAAIAAABIgBABQAAAHACAEQADAFAFACQAFADAEAAQAGgBAEgCQAGgCADgGIABAAIACAAIAIAEQABAAAAABQABAAAAAAQAAAAAAABQgBAAAAAAQgFAHgEADQgFAEgGACQgGABgHABQgJAAgJgGgAgHgXQgFACgCAFQgCAFAAAFIAgAAIACAAIABgCQAAgEgCgEQgDgFgDgCQgEgDgFAAQgFAAgEADg");
	this.shape_17.setTransform(6.05,33.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgDAlQgDAAgBgCIgchEIAAgCIACgBIAPAAIABABIABABIARAtQABABAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIASgtIABgBIACgBIALAAIABABIAAACIgcBEQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_18.setTransform(-1.95,33.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhiQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAABIguAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAAZQAAAAAAABQAAAAABABQAAAAAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAAAIAAALIAAABIgCAAIgfAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAABAAAAIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAIAwAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAAAIAAAMIgBACIgCAAg");
	this.shape_19.setTransform(-10.125,32);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgIA0QAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAg5QAAAAgBgBQAAAAAAAAQAAAAAAAAQAAAAAAAAIgMAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgJIAAgBIACgBIALAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAgBIAAgJQAAgJAEgFQAFgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAHIAAACIgCABIgIAAQgEAAgCACQgCADABAEIAAAGQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIACABIAAABIAAAJQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAA5QAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_20.setTransform(-20.75,32);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgIA0QAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg5QAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAgBAAIgLAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgJIABgBIACgBIAKAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgJQAAgJAGgFQAEgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAHIgBACIgBABIgJAAQgDAAgCACQgBADgBAEIAAAGQAAABABAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABABIABABIAAAJQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAAA5QAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_21.setTransform(-27.55,32);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgYAvQgKgGgGgMQgGgMAAgRQAAgPAGgMQAGgMALgHQAKgGANgBQAPABAKAGQAKAHAGAMQAGAMAAAPQAAARgGAMQgFALgLAHQgKAGgPABQgNgBgLgGgAgSgcQgGAKAAASQAAAVAGAIQAHAJALAAQANAAAGgJQAGgIAAgVQAAgSgGgKQgGgJgNAAQgLAAgHAJg");
	this.shape_22.setTransform(-35.725,32);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgUAvQgKgGgGgMQgFgMAAgQQAAgMAEgKQACgKAHgHQAFgHAHgDQAIgEAIAAQAJAAAIAEQAIADAFAHQAFAHAEAKQADAKAAAMQAAAQgGAMQgFAMgJAGQgJAGgNAAQgLAAgJgGgAgKghQgEAEgDAIQgDAJABANQgBANADAJQADAIAEAEQAFAEAFAAQAHAAAEgEQAFgEACgIQADgJAAgNQAAgNgDgJQgCgIgFgEQgFgEgGAAQgFAAgFAEg");
	this.shape_23.setTransform(-48.9,31.975);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgUAvQgKgGgGgMQgFgMAAgQQAAgMADgKQAEgKAFgHQAGgHAHgDQAIgEAIAAQAJAAAIAEQAIADAFAHQAGAHADAKQADAKAAAMQAAAQgGAMQgFAMgJAGQgJAGgNAAQgLAAgJgGgAgKghQgFAEgCAIQgCAJgBANQABANACAJQACAIAFAEQAEAEAGAAQAHAAAFgEQAEgEACgIQADgJAAgNQAAgNgDgJQgCgIgEgEQgGgEgGAAQgGAAgEAEg");
	this.shape_24.setTransform(-59.6,31.975);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgaA0QAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgMQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIAQAAIABgBIAAg/QAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAAAAAIgQAFQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAgBAAAAIAAgIIABgCIABgBIAXgMIACgBIABAAIAJAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAABIAABTQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAPAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAMIgBACIgBAAg");
	this.shape_25.setTransform(-67.9,32);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgBA+QgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgHIAAgBIgCAAQgKgBgIgDQgHgEgHgGQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAIgIIABAAIACAAIAKAIQAFADAHABQABAAAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIAAgcIAAgBIgCgBQgLgDgHgEQgHgFgCgFQgDgFAAgIQAAgIADgFQAEgGAHgEQAHgEAJgCIABgBIABgBIAAgGIABgBIABgBIAHAAIACABIAAACIAAAGQAAAAAAAAQAAABABAAQAAAAAAAAQAAAAABAAQAIACAGACIALAHQAAAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgHAIIgBAAIgCgBIgHgFIgIgDIgBAAIgBABIAAAcQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAABAAIAHACQAHADAGADQAFAEADAGQADAFAAAIQAAAHgEAHQgEAGgGAEQgHAEgKABIgBAAIgBABIAAAHQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAgAAHALIAAAaQAAABAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAHAAAEgEQAEgEAAgFQAAgFgDgEQgEgEgIgCIgBAAIgBABgAgFgmQgIABgEADQgDAEAAAFIABAGIAEAEIAIAFIADgBIAAgCIAAgYQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBgBAAIAAABg");
	this.shape_26.setTransform(-75.8781,32.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgHA0QAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAIAAgQQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAQAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAPQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAgAgCAWIgCAAIgBgDIgFhDIABgDIABAAIAQAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIgEBEIgBADIgCAAg");
	this.shape_27.setTransform(54.25,-27.75);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgRAiQgIgFgFgJQgFgIAAgLQAAgLAFgJQAFgJAIgFQAJgFAJABQALgBAHAFQAJAEAEAJQAEAJAAALIAAACIgCABIgwAAIgCABIAAABQAAAHADAEQADAEAEADQAFADAEAAQAGAAAFgDQAEgCAFgFIABgBIABABIAJADQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAAAQgFAHgEADQgFAEgGACQgGACgHgBQgKAAgIgEgAgIgYQgDADgCAFQgDAFAAAFIAgAAIACgBIAAgBQAAgEgCgEQgCgEgDgEQgEgCgGAAQgEAAgFACg");
	this.shape_28.setTransform(48.4,-26.25);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgFA0QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhiQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAABhIAAADIgDAAg");
	this.shape_29.setTransform(42.525,-27.75);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgaAhQgGgGAAgJQAAgHAFgHQAEgEAJgEQAJgDAMAAIAHAAIABgBIABgBIAAgEQgBgGgDgEQgEgDgGAAQgEAAgEACQgEADgDAFIgCAAIgCAAIgLgCIgBgBIABgDQADgHAIgFQAJgDAKAAQALAAAHADQAHACADAGQADAFAAAHIAAAwIAAADIgCAAIgMAAIgCgBIgBgCIAAgFQAAAAAAAAQgBgBAAAAQAAAAgBABQAAAAgBAAQgFAEgFADQgFADgHgBQgKAAgHgFgAAAACIgHADQgDACgCADQgCACAAAEQAAAEAEADQADADAGAAIAGgBIAFgEIAEgDQAAgBABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIAAgKQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgGAAIgIABg");
	this.shape_30.setTransform(36.6,-26.25);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgQA0QgHgDgHgEQgGgEgDgGIgBgBIABgCIAJgHIADAAIACAAIAGAIQAEADAEABIALABQAJAAAGgDQAGgDAAgHIgBgFIgEgEIgIgEIgUgGQgJgDgFgDQgFgFgDgFQgCgGAAgFQAAgKAEgGQAFgIAJgDQAJgFAKAAQAIAAAGACQAHACAFADQAGADADAFIABABIgBACIgKAHIgBABIgCgBQgDgEgFgDQgFgCgIAAQgJAAgFADQgFAEAAAGIABAEQABADADABIAIAFIAVAGQAMAEAGAGQAGAIAAAKQAAAJgFAHQgFAHgJAEQgJADgMAAQgJAAgIgBg");
	this.shape_31.setTransform(28.2667,-27.75);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQABgBAAAAQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_32.setTransform(18.175,-26.325);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgRAiQgIgFgFgJQgFgIAAgLQAAgLAFgJQAFgJAIgFQAJgFAJABQALgBAHAFQAJAEAEAJQAEAJAAALIAAACIgCABIgxAAIgBABIAAABQAAAHADAEQADAEAEADQAFADAEAAQAGAAAFgDQAEgCAFgFIABgBIABABIAJADQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAAAQgEAHgFADQgFAEgGACQgGACgHgBQgKAAgIgEgAgIgYQgDADgCAFQgDAFAAAFIAgAAIACgBIAAgBQAAgEgBgEQgDgEgDgEQgEgCgGAAQgEAAgFACg");
	this.shape_33.setTransform(10.95,-26.25);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAoAmIgCgBIAAgCIAAgvQAAgFgEgDQgCgDgFAAIgHABIgFADIgEADIgBACIgBADIAAAuQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgBgBIgBgCIAAgvQAAgFgDgDQgDgDgFAAQgFAAgEACQgEACgFAFIAAAxQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAhEQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAHIAAABIACgBIAHgGQAEgCAEgBQAEgCAEAAQAIAAAFAEQAEADACAGIABAAIACAAIAHgHQAEgDAEgBQAFgCAEAAQAKAAAFAGQAHAGAAAKIAAAyQAAAAgBABQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_34.setTransform(0.55,-26.325);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAnAmIgBgBIgBgCIAAgvQAAgFgCgDQgDgDgFAAIgHABIgFADIgFADIgBACIAAADIAAAuQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgCgBIAAgCIAAgvQAAgFgDgDQgCgDgGAAQgFAAgEACQgEACgEAFIAAAxQAAAAgBABQAAABAAAAQgBAAAAABQgBAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAHIABABIABgBIAIgGQADgCAEgBQAEgCAFAAQAHAAAEAEQAFADADAGIAAAAIABAAIAIgHQAEgDAFgBQAEgCAEAAQAKAAAFAGQAHAGgBAKIAAAyQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_35.setTransform(-12.2,-26.325);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgVAjQgFgDgDgFQgDgFAAgGIAAgyQAAAAAAgBQABgBAAAAQAAAAABgBQABAAAAAAIANAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAAuQAAAGADADQADADAGAAQAEAAAEgCIAJgHIAAgxQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAABEQAAAAAAABQgBAAAAABQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgGADQgFADgGAAQgGAAgFgDg");
	this.shape_36.setTransform(-22.775,-26.175);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgQA0QgHgDgHgEQgGgEgDgGIgBgBIABgCIAJgHIADAAIACAAIAGAIQAEADAEABIALABQAJAAAGgDQAGgDAAgHIgBgFIgEgEIgIgEIgUgGQgJgDgFgDQgFgFgDgFQgCgGAAgFQAAgKAEgGQAFgIAJgDQAJgFAKAAQAIAAAGACQAHACAFADQAGADADAFIABABIgBACIgKAHIgBABIgCgBQgDgEgFgDQgFgCgIAAQgJAAgFADQgFAEAAAGIABAEQABADADABIAIAFIAVAGQAMAEAGAGQAGAIAAAKQAAAJgFAHQgFAHgJAEQgJADgMAAQgJAAgIgBg");
	this.shape_37.setTransform(-31.5333,-27.75);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgHA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg5QAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBgBAAIgLAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgJIABgBIABgBIALAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQABgJAFgFQAEgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAIIgBABIgBABIgJAAQgDgBgCADQgCACAAAFIAAAHQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABABIABABIAAAJQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgNAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgBABAAAAIAAA5QAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_38.setTransform(-41.75,-27.75);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgTAiQgHgGgFgIQgFgIAAgLQAAgLAFgJQAFgJAIgFQAIgEAKAAQALAAAJAEQAHAFAFAJQAFAJAAAKQAAALgFAJQgEAIgJAGQgIAEgLAAQgKAAgJgEgAgJgXQgEADgCAGQgDAHAAAHQAAAIADAGQACAGAEADQAEADAFAAQAGAAAEgDQAEgDACgGQACgGAAgIQAAgHgCgHQgCgGgEgDQgEgCgGAAQgFAAgEACg");
	this.shape_39.setTransform(-48.7,-26.25);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgUAwQgHgEgEgIQgDgJAAgMQAAgMAEgIQAEgJAHgEQAHgFAJAAQAFAAAEACQAFACAEADIACABIAAgCIAAggQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAOAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABiIAAACIgDAAIgMAAIgCAAIgBgCIAAgFIAAgBIgBABIgFAEIgHADQgEACgFAAQgIAAgHgFgAgHgIQgEACgDAGQgCAFAAAKQAAAJACAGQADAGAEACQAEADAEAAQAFAAADgCQAEgCACgEQACgDAAgDIAAgfIgHgFQgEgCgEAAQgFAAgEADg");
	this.shape_40.setTransform(-60.175,-27.675);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AARAmIgCgBIgBgCIAAgvQAAgFgCgDQgDgDgGAAIgGABIgFADIgGAFIAAAxQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgNAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAHIAAABIABgBIAIgGIAHgDQAEgCAFAAQAKAAAGAGQAGAGAAAKIAAAyQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_41.setTransform(-68.3,-26.325);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhiQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIguAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAAAAAIAAAZQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAAAIAAALIAAABIgCAAIgfAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAABAAAAIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAIAwAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAAAIAAAMIgBACIgCAAg");
	this.shape_42.setTransform(-76.725,-27.75);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#48C435").ss(1,1,1).p("ArHAAIKAAAAAzAAIKVAA");
	this.shape_43.setTransform(-12.725,18);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-89.7,-38,154,80.7);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,728,90);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,728,90);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,728,90);


(lib.Img_02_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,728,90);


(lib.Img_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_01();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,728,90);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Ag0AAIBpAAIgeAjAAcgiIAZAi");
	this.shape.setTransform(35.525,0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AFrA4QgJgFgEgHIgBgDIABgBIAMgFIABABIAFAFQAEAEAEABQAFACAGgBQAFABAEgCQAEgBADgCQACgDAAgDQAAgEgDgCQgCgCgHgCIgRgEQgMgCgGgHQgFgFAAgJQAAgHAEgGQAEgGAIgEQAIgDALAAQAMAAAIAEQAJAFAEAGIABACIgBACIgKAEIgCAAIgBgBQgDgEgFgCQgFgDgHAAQgHAAgFADQgFACAAAFQAAADACACQACABAHACIATAGQAMACAGAHQAFAGAAAJQAAAIgFAGQgEAGgJADQgIADgLAAQgOAAgKgFgAD/A4QgKgFgFgLQgFgLAAgPIAAhFQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAABJQAAAOAGAGQAGAGAMAAQAIAAAFgDQAGgCADgHQADgFAAgKIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABIQAAAQgGAKQgFAJgLAFQgKAEgOAAQgRAAgKgFgABAA4QgJgGgGgKQgFgJAAgNQAAgNAFgKQAGgKAJgGQAKgFAMAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEgGIgFgEQgDgCgEAAQgHAAgFAEQgFADgCAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAHAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgMAAgKgFgAgsA3QgHgHAAgKQAAgJAFgHQAFgGALgEQAKgEAOAAIAHAAIACgBIAAgCIAAgDQAAgHgDgDQgEgFgHAAQgGAAgFADQgFADgDAFIgBACIgCAAIgOgEIgBgBIABgCQAEgJAJgGQAKgEAOAAQALAAAIADQAHAEAEAGQADAGAAAHIAAA4IAAADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBgBAAQAAgBAAAAQgBAAAAABQgBAAAAAAQgFAGgGACQgHADgIAAQgMAAgHgGgAgFATIgKABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAHAAQAEAAAEgBIAGgEIAEgFIABgFIAAgLQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAgAkbA4QgKgGgFgKQgFgKAAgMQAAgNAFgKQAGgKAJgGQAKgFAMAAQAMAAAKAGQAJAFAGAKQAFAKAAANQAAAMgGAKQgFAKgJAGQgKAFgMAAQgNAAgJgFgAkRgIQgEADgDAGQgCAHAAAJQAAAJACAIQADAGAEAEQAFADAHAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgJgDgHQgCgGgFgDQgFgEgGAAQgHAAgFAEgAmOA2QgMgIgGgOQgHgOAAgSQAAgSAHgOQAGgNAMgHIAEgCQAKgGAOAAQAJAAAIADIAGADIAIAEQAGAFAEAGQAEAGABAIIABACIgCABIgSABIgCAAIgBgCQgCgIgFgGQgGgGgKAAQgOAAgHAKQgIALAAAWQAAAWAHALQAIALAOAAQAKgBAHgFQAHgEAFgMQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANADIABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgEAIIgGAJQgEAFgFADQgGADgHADQgHACgJAAQgQAAgMgHgACVA3QgGgGAAgKIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIADgZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIASAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgSABQgLAAgFgEgAhgA3QgFgGAAgKIAAguQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgKQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIALAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAABIASAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAAAqQAAAGADADQACACAGAAIAJAAIACABIABABIgBAJQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgRABQgLAAgGgEgAiTA7IgCAAIgBgDIAAg2QAAgFgDgEQgEgDgGAAIgIABIgGADIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgEQAFgCAFAAQAMAAAHAHQAHAHAAALIAAA5QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(-8.5806,0.5584,0.8098,0.8098);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(0.4,1,1).p("AoliLIRLAAIAAEXIxLAAg");
	this.shape_2.setTransform(-0.95,0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC24D").s().p("AolCMIAAkXIRLAAIAAEXg");
	this.shape_3.setTransform(-0.95,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.9,-14.7,112,30);


(lib.BG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,728,90);


// stage content:
(lib.WBAY_219645_MM_728x90_V1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#010101").ss(1,1,1).p("Eg43gHBMBxvAAAIAAODMhxvAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(390));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(658.95,64.7);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(41).to({_off:false},0).to({y:44.7,alpha:1},13,cjs.Ease.get(1)).wait(336));

	// logo_png
	this.instance_1 = new lib.logo_1("synched",0);
	this.instance_1.setTransform(80,290);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({y:300,alpha:1},17,cjs.Ease.get(1)).wait(362));

	// T3
	this.instance_2 = new lib.T3("synched",0);
	this.instance_2.setTransform(498.3,82.55);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(272).to({_off:false},0).to({y:42.55,alpha:1},15,cjs.Ease.get(1)).wait(103));

	// T2
	this.instance_3 = new lib.T2("synched",0);
	this.instance_3.setTransform(650.55,15.75);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(151).to({_off:false},0).to({y:25.75,alpha:1},16,cjs.Ease.get(1)).wait(77).to({startPosition:0},0).to({alpha:0},11).to({_off:true},1).wait(134));

	// T1
	this.instance_4 = new lib.T1("synched",0);
	this.instance_4.setTransform(498.3,32.55);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(26).to({_off:false},0).to({y:42.55,alpha:1},16,cjs.Ease.get(1)).wait(82).to({startPosition:0},0).to({alpha:0},10).to({_off:true},1).wait(255));

	// Img_04_jpg
	this.instance_5 = new lib.Img_04_1("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(327).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(46));

	// Img_03_jpg
	this.instance_6 = new lib.Img_03_1("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(255).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(118));

	// Img_02_jpg
	this.instance_7 = new lib.Img_02_1("synched",0);
	this.instance_7.setTransform(80,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(134).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(239));

	// Img_01_jpg
	this.instance_8 = new lib.Img_01_1("synched",0);
	this.instance_8.setTransform(80,300);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(14).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(359));

	// BG_jpg
	this.instance_9 = new lib.BG_1("synched",0);
	this.instance_9.setTransform(80,300);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},17,cjs.Ease.get(1)).wait(373));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(363,35,366,81);
// library properties:
lib.properties = {
	id: 'B3844AD6079A43EDABE40AC988E66FE4',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['B3844AD6079A43EDABE40AC988E66FE4'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;