(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.frog = function() {
	this.initialize(img.frog);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,225);


(lib.lizart = function() {
	this.initialize(img.lizart);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,35);


(lib.snake = function() {
	this.initialize(img.snake);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,319,208);


(lib.Tounge = function() {
	this.initialize(img.Tounge);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,167,210);


(lib.turtle = function() {
	this.initialize(img.turtle);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,253);


(lib.tr = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.turtle();
	this.instance.setTransform(-150,-126.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-126.5,300,253);


(lib.tg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Tounge();
	this.instance.setTransform(-23.35,-29.4,0.28,0.28);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.3,-29.4,46.7,58.8);


(lib.t3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAIQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgLQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIALAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAALQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(50.175,23.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUAnQgKgFgDgHIAAgCIAAgBIAFgCIACgBIAAABQADAEAEADQADAEAGABQAFACAGAAQAGAAAFgCQAGgCADgDQADgDAAgFQAAgFgEgEQgEgDgJgDIgPgEQgMgCgFgGQgFgGAAgGQABgIAEgFQAEgGAGgDQAIgDAIAAQAKAAAJAEQAIAEAEAHIABABIgBABIgFADIgBAAIgBAAQgDgFgGgEQgHgCgIAAQgIgBgHAEQgFAEAAAHQAAADACAEQADADAIADIAUAGQALACAEAGQAFAGABAHQAAAHgFAFQgFAGgHADQgIADgJAAQgLAAgKgFg");
	this.shape_1.setTransform(44.4,19.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAZArIgBAAIgBgCIAAg4QAAgJgEgFQgFgEgIAAQgGAAgDABIgJAFIgKAHIAAA9QAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgHAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAhQQAAAAABgBQAAAAAAAAQAAAAAAgBQABAAAAAAIAHAAQAAAAABAAQAAABAAAAQAAAAAAAAQAAABAAAAIAAAKIABABIABgBIAKgHQAEgDAGgCQAEgBAFAAQANAAAGAGQAHAHAAALIAAA7QAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_2.setTransform(35.95,19.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaAmQgHgGAAgLQAAgIAFgHQAEgFAJgDQAJgDANgBIAOgBIACgBIABgCIAAgEQAAgKgGgGQgGgEgKAAQgGAAgGACQgGAEgFAHIgBABIgBgBIgHgCIAAgBIAAgBQAFgIAIgFQAJgFALAAQAKAAAHADQAHADAEAHQADAGAAAJIAAA3IAAACIgCAAIgGAAIgBAAIgBgCIAAgIQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABgBAAQgGAGgHADQgHADgIAAQgNAAgHgGgAAKAAIgOACIgKAEQgEACgCAEQgCAEAAAEQAAAIAFADQAFAFAJAAQAFAAAFgCIAJgFQAEgDACgEQACgEAAgDIAAgOQAAgBAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAg");
	this.shape_3.setTransform(26.625,19.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgCA7IgCAAIAAgCIAAhQQAAAAAAgBQAAAAAAAAQABAAAAgBQAAAAAAAAIAHAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAABQIAAACIgCAAgAgDgpIgBgBIgBgCIAAgMQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAHAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_4.setTransform(20.7,18.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgMA6QgFgCgDgDIgFgGIgBAAIgBABIAAAIQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgEAAIgBAAIgBgCIAAhyQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAHAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAoIAAABIACAAIAEgEIAJgFQAGgCAGAAQAMAAAIAGQAHAGAEAJQAEAKAAAMQAAAUgKAMQgKAMgRAAQgHAAgFgCgAgOgPQgHAEgEAFIAAAkQAAAGADAFQAEAFAFADQAGADAGAAQAHAAAGgEQAGgEAEgHQAEgJAAgMQAAgQgHgJQgHgJgMAAQgIgBgGAEg");
	this.shape_5.setTransform(14.375,18.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgCA7IgCAAIAAgCIAAhQQAAAAAAgBQAAAAAAAAQABAAAAgBQAAAAAAAAIAGAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAABQIAAACIgCAAgAgDgpIgCgBIAAgCIAAgMQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_6.setTransform(7.5,18.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAZA7IgCAAIAAgCIAAg5QAAgIgEgFQgEgEgKAAQgFAAgDABIgJAFIgKAHIAAA9QAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgHAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAgBgBIAAhyQABAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAHAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAArIABABIABAAIAKgHIAJgFQAFgBAFAAQANAAAGAGQAHAHgBALIAAA7QAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_7.setTransform(1.1,18.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgiA5QAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAhqIABgDIACAAIAFAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAABIAAAGIAAACIACAAIAEgFQADgDAFgCQAGgCAGgBQAKAAAIAGQAIAEAFAJQAFAKAAAOQAAANgFALQgFAJgIAGQgJAFgKABQgHgBgGgCQgGgCgDgEIgCgBIgBACIAAAfQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAgAgNgsQgGADgDAEQgDAGAAAEIAAAnQAFAGAGADQAFACAHAAQAHAAAHgEQAHgEADgJQAEgGAAgMQAAgNgEgHQgEgIgGgDQgHgEgGAAQgHAAgFADg");
	this.shape_8.setTransform(-8.1,21.15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAzArIgCAAIAAgCIAAg4QAAgJgEgFQgEgEgJAAQgFAAgEABQgFACgEADIgGAFIgCACIgBADIAAA6QAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgFAAIgCAAIAAgCIAAg4QAAgJgEgFQgEgEgJAAQgHAAgGADQgGADgIAHIAAA9QAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgHAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhQQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAHAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAKIAAABIABgBIAKgHIAJgFQAEgBAGAAQAKAAAFAEQAFAFACAFIABAAIABgBIAKgHIAJgFQAFgBAFAAQAMAAAGAGQAGAHAAALIAAA7QAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_9.setTransform(-20.225,19.825);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgaAmQgHgGAAgLQAAgIAFgHQAEgFAJgDQAJgDANgBIAOgBIACgBIABgCIAAgEQAAgKgGgGQgGgEgKAAQgGAAgGACQgGAEgFAHIgBABIgBgBIgHgCIAAgBIAAgBQAFgIAIgFQAJgFALAAQAKAAAHADQAHADAEAHQADAGAAAJIAAA3IAAACIgCAAIgGAAIgBAAIgBgCIAAgIQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABgBAAQgGAGgHADQgHADgIAAQgNAAgHgGgAAKAAIgOACIgKAEQgEACgCAEQgCAEAAAEQAAAIAFADQAFAFAJAAQAFAAAFgCIAJgFQAEgDACgEQACgEAAgDIAAgOQAAgBAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAg");
	this.shape_10.setTransform(-32.125,19.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AguA0QgJgIAAgOQAAgKAGgIQAFgIANgHIACgBIgCgDQgFgFgDgGQgCgGAAgGQAAgJAEgGQAEgHAIgEQAHgEAJAAQAIAAAGADQAGADAEAFQAEAGAAAHQAAAGgDAGQgDAFgGAGQgHAFgJAEIgCACIABABIAaAfIABABIACgBIAGgHIAHgJIAGgJIADgGQAAgBAAAAQABAAAAAAQAAAAABAAQAAAAABAAIAEACIACAAIAAABQgCAFgEAGIgJANIgKAMIgBABIABABQADADAFADIAKAEIALABQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAFIgBACIgCABQgGAAgHgCIgNgFQgGgDgEgEIgCAAIgBABQgHAGgIAEQgJAEgKAAQgQAAgKgJgAgYADQgJAEgFAHQgFAHAAAJQAAAGADAFQADAFAGADQAFADAHAAQAIAAAHgDQAGgDAFgFIABgCIAAgCIgcghIgCgCgAgUgxQgFADgCAFQgDAFAAAFQAAAFACAEIAFAIIAEAEIABABIACgBQAOgGAEgGQAGgHAAgHQAAgIgFgEQgEgEgHAAQgHAAgFADg");
	this.shape_11.setTransform(-45.575,18.175);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgUAnQgKgFgDgIIAAgBIAAAAIAFgDIACgBIAAABQADAEAEADQADADAGACQAFACAGAAQAGAAAFgCQAGgCADgDQADgDAAgFQAAgFgEgDQgEgEgJgCIgPgFQgMgCgFgGQgFgGAAgGQABgHAEgGQAEgGAGgDQAIgDAIAAQAKAAAJAEQAIAEAEAHIABABIgBAAIgFAEIgBAAIgBgBQgDgEgGgDQgHgEgIAAQgIABgHADQgFAEAAAHQAAAEACADQADADAIADIAUAHQALABAEAGQAFAFABAIQAAAHgFAGQgFAFgHADQgIADgJAAQgLAAgKgFg");
	this.shape_12.setTransform(76.35,1.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgTAmQgJgFgFgJQgFgKAAgNQAAgNAGgKQAFgKAJgFQAJgGAKAAQAMAAAIAGQAJAEAEAKQAFAKAAANIAAABIgCABIg/AAIAAABIgBACQAAAIAEAHQAEAHAHAFQAHADAHAAQAJAAAGgDQAHgEAEgGIABgBIABAAIAGADQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQgEAGgFAEQgFAEgHACQgGACgIAAQgLAAgJgGgAgOgeQgGAFgDAGQgEAIAAAHIA0AAIADAAIAAgDQAAgHgDgGQgDgHgGgEQgGgDgJgBQgIABgHAEg");
	this.shape_13.setTransform(67.875,1.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCA7QgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhyQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAByIAAACIgCAAg");
	this.shape_14.setTransform(61.375,-0.175);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgCA7IgCAAIAAgCIAAhQQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAFAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAABQIgBACIgCAAgAgDgpIgCgBIAAgCIAAgMQAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAHAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAMQAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_15.setTransform(57.65,-0.175);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAKA5QgKAAgEgFQgEgEAAgLIAAg2QAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgOAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAOAAIABgBIACgaQAAAAAAgBQAAAAAAAAQABAAAAgBQAAAAAAAAIAFAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAaQAAAAAAAAQAAAAAAAAQAAABABAAQAAAAAAAAIAVAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAGQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgVAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAAAIAAA1QAAAIACADQADACAFAAIAMAAIABABIAAABIAAAEQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgFAAIgFABg");
	this.shape_16.setTransform(52.725,0.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgiA4QAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIAAhqIAAgCIACAAIAGAAQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAAHIAAACIABgBIAFgEQADgDAFgCQAFgDAHABQAKAAAIAEQAIAFAFAKQAEAJABAOQgBANgEAKQgEALgJAFQgIAGgLAAQgIAAgFgDQgGgCgEgDIgBgBIgBACIAAAdQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAgAgOgsQgFADgDAFQgDAEAAAFIAAAnQAFAFAFADQAHAEAGAAQAIAAAGgFQAHgEADgIQAEgIAAgLQAAgMgEgJQgEgHgGgEQgGgDgHAAQgHAAgGADg");
	this.shape_17.setTransform(45.3,2.75);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgTAmQgJgFgFgJQgFgKAAgNQAAgNAGgKQAFgKAJgFQAJgGAKAAQAMAAAIAGQAJAEAEAKQAFAKAAANIAAABIgCABIg/AAIAAABIgBACQAAAIAEAHQAEAHAHAFQAHADAHAAQAJAAAGgDQAHgEAEgGIABgBIABAAIAGADQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQgEAGgFAEQgFAEgHACQgGACgIAAQgLAAgJgGgAgOgeQgGAFgDAGQgEAIAAAHIA0AAIADAAIAAgDQAAgHgDgGQgDgHgGgEQgGgDgJgBQgIABgHAEg");
	this.shape_18.setTransform(35.725,1.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgSArIgCAAIAAgCIAAhQQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAGAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAALIABABIACgBQAEgFAEgDIAHgFQAEgBAEAAQAGAAAAACIAAAHQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAAAAAIgDAAIgEAAIgIABIgGAFQgEADgCADQgCAEAAAEIAAA1QAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_19.setTransform(28.55,1.425);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAKA5QgKAAgEgFQgEgEAAgLIAAg2QAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgOAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAOAAIABgBIACgaQAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAAAAAIAFAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAaQAAAAAAAAQAAAAAAAAQAAABABAAQAAAAAAAAIAVAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAGQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgVAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAAAIAAA1QAAAIACADQADACAFAAIAMAAIABABIAAABIAAAEQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgFAAIgFABg");
	this.shape_20.setTransform(18.575,0.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgUAoQgGgDgDgFQgDgGAAgHIAAg7QAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAIAIAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAA4QAAAIAFAFQAFAGAIAAQAHAAAGgEQAHgEAHgIIAAg7QAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAGAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABQQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAIgHAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgKIAAgBIgBABQgKAIgGADQgGACgGAAQgIAAgGgDg");
	this.shape_21.setTransform(11,1.575);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgFgKQgFgJAAgOQAAgMAFgJQAFgKAJgGQAJgGALAAQAMAAAJAGQAJAFAFALQAFAJAAAMQAAANgFAKQgFAKgJAFQgJAGgMAAQgLAAgJgGgAgOgeQgHAEgDAIQgEAJAAAJQAAALAEAIQADAIAHAFQAGADAIAAQAJAAAHgDQAGgFAEgIQADgIAAgLQAAgJgDgJQgEgIgGgEQgHgEgJgBQgIABgGAEg");
	this.shape_22.setTransform(1.675,1.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgMA6QgFgDgDgDIgFgEIgBgBIgBABIAAAIQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAIgEAAIgBgBIgBgCIAAhxQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAHAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAnIAAADIACgCIAEgDIAJgEQAGgDAGAAQAMAAAIAGQAHAGAEAKQAEAIAAANQAAAUgKAMQgKAMgRAAQgHAAgFgCgAgOgPQgHAEgEAFIAAAkQAAAGADAFQAEAFAFADQAGADAGAAQAHAAAGgEQAGgDAEgJQAEgHAAgNQAAgQgHgJQgHgKgMAAQgIABgGADg");
	this.shape_23.setTransform(-7.575,-0.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgaAmQgHgHAAgKQAAgJAFgFQAEgGAJgDQAJgEANgBIAOgBIACgBIABgBIAAgFQAAgJgGgFQgGgGgKAAQgGAAgGAEQgGADgFAHIgBABIgBAAIgHgDIAAgBIAAgBQAFgIAIgFQAJgFALAAQAKAAAHAEQAHADAEAGQADAGAAAIIAAA5IAAABIgCABIgGAAIgBgBIgBgBIAAgJQAAgBAAAAQAAAAAAAAQgBAAAAAAQAAAAgBABQgGAGgHADQgHADgIAAQgNAAgHgGgAAKAAIgOABIgKAFQgEADgCADQgCAEAAAEQAAAHAFAFQAFAEAJAAQAFAAAFgCIAJgFQAEgDACgEQACgDAAgEIAAgOQAAgBAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_24.setTransform(-17.225,1.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAZArIgBAAIgBgCIAAg4QAAgJgEgFQgFgEgIAAQgGAAgDABIgJAFIgKAHIAAA9QAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgHAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQgBAAAAgBIAAhQQAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAAAIAHAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAAKIABABIABgBIAKgHQAEgDAGgCQAEgBAFAAQANAAAGAGQAHAHAAALIAAA7QAAABgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_25.setTransform(-29.3,1.425);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgSArIgBAAIgBgCIAAhQQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAHAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABABAAAAIAAALIAAABIACgBQADgFAFgDIAHgFQAEgBAFAAQAFAAAAACIAAAHQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgCAAIgEAAIgHABIgHAFQgEADgCADQgDAEABAEIAAA1QAAABgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_26.setTransform(-36.5,1.425);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaAmQgHgHAAgKQAAgJAFgFQAEgGAJgDQAJgEANgBIAOgBIACgBIABgBIAAgFQAAgJgGgFQgGgGgKAAQgGAAgGAEQgGADgFAHIgBABIgBAAIgHgDIAAgBIAAgBQAFgIAIgFQAJgFALAAQAKAAAHAEQAHADAEAGQADAGAAAIIAAA5IAAABIgCABIgGAAIgBgBIgBgBIAAgJQAAgBAAAAQAAAAAAAAQgBAAAAAAQAAAAgBABQgGAGgHADQgHADgIAAQgNAAgHgGgAAKAAIgOABIgKAFQgEADgCADQgCAEAAAEQAAAHAFAFQAFAEAJAAQAFAAAFgCIAJgFQAEgDACgEQACgDAAgEIAAgOQAAgBAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_27.setTransform(-44.575,1.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgTAmQgJgFgFgJQgFgKAAgNQAAgNAGgKQAFgKAJgFQAJgGAKAAQAMAAAIAGQAJAEAEAKQAFAKAAANIAAABIgCABIg/AAIAAABIgBACQAAAIAEAHQAEAHAHAFQAHADAHAAQAJAAAGgDQAHgEAEgGIABgBIABAAIAGADQAAAAAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQgEAGgFAEQgFAEgHACQgGACgIAAQgLAAgJgGgAgOgeQgGAFgDAGQgEAIAAAHIA0AAIADAAIAAgDQAAgHgDgGQgDgHgGgEQgGgDgJgBQgIABgHAEg");
	this.shape_28.setTransform(-53.225,1.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgCA7QgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhyQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAByIAAACIgCAAg");
	this.shape_29.setTransform(-59.725,-0.175);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgFgKQgFgJAAgOQAAgMAFgJQAFgKAJgGQAJgGALAAQAMAAAJAGQAJAFAFALQAFAJAAAMQAAANgFAKQgFAKgJAFQgJAGgMAAQgLAAgJgGgAgOgeQgHAEgDAIQgEAJAAAJQAAALAEAIQADAIAHAFQAGADAIAAQAJAAAHgDQAGgFAEgIQADgIAAgLQAAgJgDgJQgEgIgGgEQgHgEgJgBQgIABgGAEg");
	this.shape_30.setTransform(-69.825,1.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAKA5QgKAAgEgFQgEgEAAgLIAAg2QAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgOAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAOAAIABgBIACgaQAAAAAAgBQAAAAAAAAQABAAAAgBQAAAAAAAAIAFAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAaQAAAAAAAAQAAAAAAAAQAAABABAAQAAAAAAAAIAVAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAGQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgVAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAAAIAAA1QAAAIACADQADACAFAAIAMAAIABABIAAABIAAAEQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgFAAIgFABg");
	this.shape_31.setTransform(-77.675,0.075);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgUAnQgJgFgEgHIAAgCIAAgBIAFgDIABAAIABAAQADAFAEADQAEAEAEABQAGACAFAAQAHAAAGgCQAFgCADgDQADgEAAgEQAAgFgEgEQgEgDgJgDIgQgEQgMgCgEgGQgEgFAAgHQAAgHADgGQAFgGAHgDQAHgDAIAAQAKAAAJAEQAIAEAFAHIAAABIgBABIgFADIgBAAIgBgBQgEgEgGgEQgFgCgJAAQgJgBgFAEQgHAEAAAHQABADACAEQADADAJADIAUAHQAJACAGAFQAEAFAAAIQABAHgFAFQgFAGgHADQgIADgKAAQgKAAgKgFg");
	this.shape_32.setTransform(113.3,-16.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgTArIAAAAIgBgCIAAhQQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAIAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABABgBAAIAAALIABABIABgBQAFgFAEgDIAHgFQAEgBAFAAQAFAAAAACIAAAHQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgCAAIgDAAIgIABIgHAFQgEADgCADQgCAEgBAEIAAA1QAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_33.setTransform(106.9,-16.975);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgTAmQgJgFgFgKQgFgJAAgNQAAgNAGgKQAFgKAJgGQAJgFAKAAQAMAAAIAFQAJAGAEAJQAFAJAAAOIAAACIgCABIg/AAIAAAAIgBACQAAAIAEAHQAEAHAHAEQAHAFAHAAQAJAAAGgEQAHgDAEgIIABAAIABAAIAGADQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQgEAGgFAEQgFAEgHACQgGACgIAAQgLAAgJgGgAgOgeQgGAEgDAIQgEAGAAAIIA0AAIADgBIAAgBQAAgIgDgHQgDgGgGgEQgGgEgJABQgIgBgHAFg");
	this.shape_34.setTransform(98.875,-16.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgiA5QAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAhqIABgCIABgBIAGAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAAAHIABABIABAAIAFgFQADgDAFgCQAGgDAGAAQAKABAIAFQAIAEAFAJQAFAKgBAOQABANgFALQgFAKgIAFQgJAFgKAAQgHABgGgDQgGgCgDgEIgDgBIAAACIAAAfQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAgAgNgsQgGADgDAEQgDAGAAAEIAAAnQAFAGAFADQAHACAGAAQAIABAGgFQAGgEAEgJQAEgGAAgNQAAgMgEgHQgEgIgGgDQgGgEgHAAQgHAAgFADg");
	this.shape_35.setTransform(89.7,-15.65);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAzArIgCAAIAAgCIAAg4QAAgJgEgFQgEgEgJAAQgFAAgEABQgFACgEADIgGAFIgCACIgBADIAAA6QAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgFAAIgCAAIAAgCIAAg4QAAgJgEgFQgEgEgJAAQgHAAgGADQgGADgIAHIAAA9QAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgHAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhQQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAKIAAABIABgBIAKgHIAJgFQAEgBAGAAQAKAAAFAEQAFAFACAFIABAAIABgBIAKgHIAJgFQAFgBAFAAQAMAAAGAGQAGAHAAALIAAA7QAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_36.setTransform(77.575,-16.975);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgaAmQgHgHAAgKQAAgIAFgHQAEgGAJgCQAJgDANgBIAOgBIACgBIABgCIAAgFQAAgJgGgGQgGgEgKAAQgGAAgGACQgGAEgFAHIgBABIgBgBIgHgCIAAgBIAAgBQAFgIAIgFQAJgFALAAQAKAAAHADQAHADAEAHQADAGAAAJIAAA3IAAACIgCAAIgGAAIgBAAIgBgCIAAgIQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABgBAAQgGAGgHADQgHADgIAAQgNAAgHgGgAAKAAIgOACIgKAEQgEACgCAEQgCAEAAAEQAAAIAFADQAFAFAJAAQAFAAAFgCIAJgFQAEgEACgDQACgEAAgDIAAgOQAAgBAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_37.setTransform(65.675,-16.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgRAmQgJgFgFgKQgFgJAAgNQAAgMAFgLQAFgKAJgFQAJgGALAAQAIAAAGACQAGADAEAEIAIAKQABAAAAABQAAAAAAAAQgBABAAAAQAAAAAAAAIgHACIgCgBIgHgIIgHgEQgEgCgFABQgHgBgHAFQgHAEgDAJQgEAHAAAKQAAALAEAIQAEAIAGAEQAHAFAIAAQAIAAAGgEQAGgEAEgIIABAAIABAAIAGACQAAAAAAAAQAAABABAAQAAAAAAAAQAAABgBAAIgGAIIgHAGIgJAEQgFACgGAAQgLAAgJgGg");
	this.shape_38.setTransform(57.4583,-16.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgTArIAAAAIgBgCIAAhQQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAIAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABABAAAAIAAALIAAABIABgBQAFgFAEgDIAHgFQAEgBAFAAQAFAAAAACIAAAHQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgCAAIgDAAIgIABIgHAFQgEADgCADQgCAEgBAEIAAA1QAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_39.setTransform(47.05,-16.975);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgFgKQgFgJAAgNQAAgMAFgLQAFgKAJgFQAJgGALAAQAMAAAJAFQAJAGAFAKQAFAKAAAMQAAANgFAKQgFAKgJAFQgJAGgMAAQgLAAgJgGgAgOgeQgHAEgDAJQgEAHAAAKQAAALAEAIQADAIAHAEQAGAFAIAAQAJAAAHgFQAGgEAEgIQADgIAAgLQAAgKgDgHQgEgJgGgEQgHgFgJABQgIgBgGAFg");
	this.shape_40.setTransform(38.825,-16.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgFA7QAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhIIgBgBIgRAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgFIAAgBIABgBIARAAIABgBIAAgMQAAgKAEgFQAEgFAKAAIANAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAFIAAABIgBABIgMAAQgGAAgCADQgCADAAAGIAAAMIABABIAUAAIABABIAAABIAAAFQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgTAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAABIQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_41.setTransform(31.125,-18.575);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgfA3QAAAAgBAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIAAgFIABgBIAEgBIAKAAQAEAAACgCQADgDACgEIADgIQABgEgCgDIgehLIAAgCQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAHAAIABABIABABIAZBBIABABIACgCIAZhAIAAgBIACgBIAFAAIACABIAAABIgkBcQgBAFgDADIgFAFQgDACgEABIgJABg");
	this.shape_42.setTransform(20.525,-15.575);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAKA5QgKAAgEgFQgEgEAAgLIAAg2QAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgOAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAOAAIABgBIACgaQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAFAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAaQAAAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIAVAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAGQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgVAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAAAIAAA1QAAAIACADQADACAFAAIAMAAIABABIAAABIAAAEQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgFAAIgFABg");
	this.shape_43.setTransform(13.275,-18.325);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgCA7IgCAAIAAgCIAAhQQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAFAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAABQIgBACIgCAAgAgDgpIgCgBIAAgCIAAgMQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAHAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_44.setTransform(8.5,-18.575);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAZArIgCAAIAAgCIAAg4QAAgJgEgFQgEgEgKAAQgFAAgDABIgJAFIgKAHIAAA9QAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgHAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAhQQAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAAAIAHAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAAKIABABIABgBIAKgHQAEgDAGgCQAEgBAFAAQANAAAGAGQAHAHAAALIAAA7QAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_45.setTransform(2.1,-16.975);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgUAoQgGgDgDgFQgDgGgBgHIAAg7QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAAAAAIAHAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA4QAAAIAFAFQAFAGAIAAQAGAAAHgEQAHgEAHgIIAAg7QAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAABQQAAAAgBABQAAAAAAAAQAAAAAAABQgBAAAAAAIgHAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgKIgBgBIgBABQgJAIgHADQgGACgHAAQgHAAgGgDg");
	this.shape_46.setTransform(-7.25,-16.825);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AAKA5QgKAAgEgFQgEgEAAgLIAAg2QAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgOAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgGQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAOAAIABgBIACgaQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAFAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAaQAAAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIAVAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAGQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAgBAAIgVAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAAAIAAA1QAAAIACADQADACAFAAIAMAAIABABIAAABIAAAEQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgFAAIgFABg");
	this.shape_47.setTransform(-14.875,-18.325);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgSArIgBAAIgBgCIAAhQQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAHAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABABAAAAIAAALIAAABIACgBQADgFAFgDIAHgFQAEgBAFAAQAFAAAAACIAAAHQAAABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgCAAIgEAAIgHABIgHAFQgEADgCADQgDAEABAEIAAA1QAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_48.setTransform(-20.3,-16.975);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgFgKQgFgJAAgNQAAgMAFgLQAFgKAJgFQAJgGALAAQAMAAAJAFQAJAGAFAKQAFAKAAAMQAAANgFAKQgFAKgJAFQgJAGgMAAQgLAAgJgGgAgOgeQgHAEgDAJQgEAHAAAKQAAALAEAIQADAIAHAEQAGAFAIAAQAJAAAHgFQAGgEAEgIQADgIAAgLQAAgKgDgHQgEgJgGgEQgHgFgJABQgIgBgGAFg");
	this.shape_49.setTransform(-28.525,-16.9);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgiA5QAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAhqIABgCIACgBIAFAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAABIAAAHIAAABIACAAIAEgFQADgDAFgCQAGgDAGAAQAKABAIAFQAIAEAFAJQAFAKAAAOQAAANgFALQgFAKgIAFQgJAFgKAAQgHABgGgDQgGgCgDgEIgCgBIgBACIAAAfQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAgAgNgsQgGADgDAEQgDAGAAAEIAAAnQAFAGAGADQAFACAHAAQAHABAHgFQAHgEADgJQAEgGAAgNQAAgMgEgHQgEgIgGgDQgHgEgGAAQgHAAgFADg");
	this.shape_50.setTransform(-37.8,-15.65);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgiA5QAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAhqIAAgCIABgBIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAAAHIABABIABAAIAFgFQADgDAFgCQAGgDAGAAQAKABAIAFQAIAEAFAJQAEAKAAAOQAAANgEALQgEAKgJAFQgIAFgLAAQgIABgFgDQgGgCgEgEIgCgBIAAACIAAAfQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAgAgOgsQgFADgDAEQgDAGAAAEIAAAnQAFAGAFADQAHACAGAAQAHABAHgFQAGgEAEgJQAEgGAAgNQAAgMgEgHQgEgIgGgDQgHgEgGAAQgHAAgGADg");
	this.shape_51.setTransform(-47.3,-15.65);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgFgKQgFgJAAgNQAAgMAFgLQAFgKAJgFQAJgGALAAQAMAAAJAFQAJAGAFAKQAFAKAAAMQAAANgFAKQgFAKgJAFQgJAGgMAAQgLAAgJgGgAgOgeQgHAEgDAJQgEAHAAAKQAAALAEAIQADAIAHAEQAGAFAIAAQAJAAAHgFQAGgEAEgIQADgIAAgLQAAgKgDgHQgEgJgGgEQgHgFgJABQgIgBgGAFg");
	this.shape_52.setTransform(-57.075,-16.9);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgTAmQgJgFgFgKQgFgJAAgNQAAgNAGgKQAFgKAJgGQAJgFAKAAQAMAAAIAFQAJAGAEAJQAFAJAAAOIAAACIgCABIg/AAIAAAAIgBACQAAAIAEAHQAEAHAHAEQAHAFAHAAQAJAAAGgEQAHgDAEgIIABAAIABAAIAGADQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQgEAGgFAEQgFAEgHACQgGACgIAAQgLAAgJgGgAgOgeQgGAEgDAIQgEAGAAAIIA0AAIADgBIAAgBQAAgIgDgHQgDgGgGgEQgGgEgJABQgIgBgHAFg");
	this.shape_53.setTransform(-69.875,-16.9);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgUAoQgGgDgDgFQgEgGABgHIAAg7QAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIAHAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA4QAAAIAFAFQAEAGAJAAQAHAAAGgEQAHgEAHgIIAAg7QAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAABQQAAAAAAABQAAAAAAAAQAAAAAAABQgBAAAAAAIgHAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgKIAAgBIgBABQgJAIgHADQgGACgGAAQgIAAgGgDg");
	this.shape_54.setTransform(-79.2,-16.825);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AAbA5QAAAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgfIAAgCIgCABIgKAGQgHADgHgBQgKAAgJgFQgIgFgEgKQgFgLAAgMQAAgNAEgKQAFgKAIgFQAIgGALAAQAIAAAGADIAIAEIAEAFQAAAAABABQAAAAAAAAQABAAAAgBQAAAAAAAAIABgHIABgCIACgBIACAAIACABIABACIAABqQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAgAgLgrQgHAEgDAHQgEAIgBAMQABAMAEAGQADAJAGAEQAGAFAIgBQAHAAAGgCQAGgEAFgFIAAglQAAgGgDgFQgDgFgGgDQgFgDgHgBQgHAAgGAFg");
	this.shape_55.setTransform(-88.75,-15.65);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgCA7IgCAAIAAgCIAAhQQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAGAAQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAABQIgBACIgCAAgAgDgpIgBgBIgBgCIAAgMQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAHAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_56.setTransform(-95.15,-18.575);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AAZArIgBAAIgBgCIAAg4QAAgJgEgFQgFgEgIAAQgGAAgDABIgJAFIgKAHIAAA9QAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgHAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAhQQAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAAAIAHAAQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAIAAAKIAAABIABgBIAKgHQAFgDAFgCQADgBAGAAQAMAAAHAGQAGAHABALIAAA7QAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_57.setTransform(-101.55,-16.975);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgXA3QgJgEgEgJQgEgKgBgOIAAhLQAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAABPQAAAPAIAHQAIAIAOAAQAJAAAIgEQAHgDADgHQADgHAAgKIAAhOQAAAAAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAHAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAABOQABAOgFAJQgFAIgJAFQgKAEgNAAQgNAAgKgFg");
	this.shape_58.setTransform(-111.85,-18.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-121.3,-30.1,242.6,60.2);


(lib.t2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#167ABE").s().p("AgVBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAHgXIAKgbIAOgeIATghIAAgCIgCAAIhEAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIABgKQAAAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAIBUAAIADABIAAABIAAAHIgBADIgCADIgOAYQgGAMgGANIgKAZIgHAWIgEASQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape.setTransform(96.875,14.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAqAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_1.setTransform(84.225,16.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_2.setTransform(71.525,14.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#167ABE").s().p("AAKBAQgKAAgGgGQgFgEAAgMIAAg7QAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgOAAQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIAAgIQAAAAAAAAQAAgBABAAQAAAAAAAAQAAgBABAAIAPAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIACgcQAAgBABgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAIAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAcQAAAAAAABQAAAAAAAAQAAAAAAAAQABAAAAAAIAXAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgXAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAA4QAAAIADADQADACAGAAIAMAAIACABIAAACIAAAFQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgFABIgHAAg");
	this.shape_3.setTransform(58.825,14.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#167ABE").s().p("AgXAsQgLgGgEgJIgBgBIABgBIAHgFIACAAIABABIAHAIQAEADAGADQAFABAHAAIAMgBQAGgDADgDQADgDAAgFQAAgFgEgDQgEgEgJgCIgSgGQgNgDgGgGQgFgGAAgIQAAgJAEgGQAFgGAIgEQAJgEAJAAQAMAAAKAFQAJAFAFAHIABABIgBACIgHAEIgCAAIgBgBQgEgFgGgDQgHgEgJAAQgIAAgHAEQgGAEAAAHQAAAEADADQADAEAIADIAWAHQANACAFAHQAGAGAAAIQAAAIgFAHQgFAGgJAEQgJADgLAAQgNAAgLgFg");
	this.shape_4.setTransform(50.625,16.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#167ABE").s().p("AgYAtQgGgDgEgGQgEgHAAgIIAAhCQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAJAAQAGAAAIgFQAHgEAGgHIAAhCQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAIALAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABZQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgLAAQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgLIAAgBIgBABQgLAIgHADQgHAEgHAAQgIAAgHgEg");
	this.shape_5.setTransform(40.95,16.225);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#167ABE").s().p("AglA6QgMgHABgMQAAgGADgFQAFgGAJgDQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIgHgFQgCgCAAgEIACgFQABgCADgCIAIgEIABAAIgBgCQgIgEgDgGQgEgGAAgIQAAgOALgIQAKgIATAAQAIAAAIACQAGACAEAEIACABIACgBIAFgEIAGgDIAGgBIADAAIABADIAAAGIgBACIgDABIgFABIgFABQgEABABADIACAFIABAHQAAAIgEAHQgEAGgJAEQgJAEgMAAIgPABQgFABgCACQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAADAEABQADABAJABIAXABQAPABAIAHQAHAGAAALQAAAOgLAHQgMAIgWAAQgWAAgNgGgAgZAXIgHAGQgDADAAAFQAAAGAEAEQADAEAJACQAHACALAAQAOAAAJgEQAHgFAAgJQAAgGgEgEQgEgEgKAAIgdgCIgBAAIgGACgAgUgwQgHAFAAAKQAAAJAHAFQAGAGAMAAQAMAAAGgGQAGgFAAgJQAAgKgGgFQgGgGgMAAQgMAAgGAGg");
	this.shape_6.setTransform(30.4,17.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAIAAQAHAAAIgFQAHgEAHgHIAAhCQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAJAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIgBBZQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgJAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgLIgBgBIgCABQgJAIgIADQgHAEgHAAQgIAAgHgEg");
	this.shape_7.setTransform(19.75,16.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#167ABE").s().p("AAqBDQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIgNgjIgBgBIgBAAIgzAAQgBAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAIgMAjIgBABIgCABIgLAAIgBgBIAAgCIAuh/IABgCIADgBIANAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAABIAuB/IAAACQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAgBguIgWA7QgBAAAAABQAAAAAAAAQABAAAAABQAAAAABAAIAqAAQABAAAAAAQAAgBABAAQAAAAAAAAQAAgBAAAAIgWg7IAAgBg");
	this.shape_8.setTransform(8.125,14.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#167ABE").s().p("AgDBbQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAixIABgCIABAAIAHAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAACxQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(-4.6,14.75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#167ABE").s().p("AgfBDQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgKQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAhiQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgXAIQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBgBAAAAIAAgHIAAgCIACgBIAbgNIADgCIABAAIAIAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAB0QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAUAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAKIgBABIgCABg");
	this.shape_10.setTransform(-14.9,14.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#167ABE").s().p("AgTBCQgIgCgHgEQgHgEgGgHIAAgBIABgCIAIgGIABAAIABAAQAFAGAGADQAFADAHACQAFABAHAAQAPAAAJgHQAJgHAAgLQgBgIgFgGQgEgGgIgDQgHgDgIAAIgRAAQAAAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgJQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAOgBQAIAAAHgDQAIgDAEgGQAFgFgBgHQABgGgEgFQgDgFgHgDQgGgDgIAAQgJAAgIAEQgHAEgHAGIgCABIgCgBIgGgGQAAgBgBAAQAAAAAAAAQAAgBAAAAQABAAAAgBQAFgGAHgEQAGgEAIgCQAIgCAHAAQANAAALAFQAKAEAFAIQAFAHAAAKQABAKgHAIQgGAIgKADIgDACIADABQAHACAGADQAGAFAEAHQAEAGAAAJQAAALgGAJQgGAJgMAFQgLAFgQAAQgJAAgIgDg");
	this.shape_11.setTransform(-25.05,14.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAqAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAHQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_12.setTransform(-37.925,16.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#167ABE").s().p("AgVBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAHgXIAKgbIAOgeIATghIAAgCIgCAAIhEAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIABgKQAAAAAAgBQAAAAABAAQAAAAABgBQAAAAABAAIBUAAIADABIAAABIAAAHIgBADIgCADIgOAYQgGAMgGANIgKAZIgHAWIgEASQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_13.setTransform(-50.575,14.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_14.setTransform(-61.375,14.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#167ABE").s().p("AgkA/QgBgBAAAAQgBAAAAAAQgBAAAAgBQAAAAAAAAIAAgHIABgCIAEgBIAMAAQAEAAADgDIAFgGIADgIQABgFgBgDIgjhVIAAgCIACgBIALAAIACABIABABIAaBFIACACQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIAbhFIABgBIABgBIAJAAIACABIAAACIgoBlQgCAGgDAEQgDAEgEADIgIADIgLABg");
	this.shape_15.setTransform(-75.2625,17.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#167ABE").s().p("AgEBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAh/QAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIAKAAQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAB/IAAACIgCABg");
	this.shape_16.setTransform(-82.2,14.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAIAAQAHAAAHgFQAIgEAHgHIAAhCQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAJAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIgBBZQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgJAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgLIgBgBIgCABQgJAIgIADQgHAEgHAAQgIAAgHgEg");
	this.shape_17.setTransform(-89.6,16.225);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#167ABE").s().p("AgPBCIgIgCIgBgCIgBgCIACgJQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAFACQADACAGAAQAHAAAEgFQADgEAAgMIAAhgQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAOAAQAAAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABkQgBAQgGAIQgHAIgOAAQgHAAgGgCg");
	this.shape_18.setTransform(-98.95,14.325);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#167ABE").s().p("AgVBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAIAHgXIAKgbIAOgeIATghIAAgCIgCAAIhEAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIABgKQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIBUAAIADABIAAABIAAAHIgBADIgCADIgOAYQgGAMgGANIgKAZIgHAWIgEASQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_19.setTransform(95.425,-14.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#167ABE").s().p("AgeBDQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgKQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAWAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAgBIAAhiQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgWAIQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHIAAgCIABgBIAbgNIACgCIACAAIAIAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAB0QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAUAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAKIAAABIgCABg");
	this.shape_20.setTransform(85.95,-14.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_21.setTransform(74.425,-12.725);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#167ABE").s().p("AgTBCQgIgCgHgEQgHgEgGgHIAAgBIABgCIAIgGIABAAIABAAQAFAGAGADQAFADAGACQAGABAIAAQAOAAAJgHQAJgHAAgLQgBgIgEgGQgFgGgIgDQgIgDgHAAIgQAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAMgBQAJAAAHgDQAIgDAEgGQAEgFAAgHQAAgGgDgFQgDgFgHgDQgGgDgIAAQgJAAgIAEQgHAEgIAGIgBABIgCgBIgGgGQAAAAgBgBQAAAAAAAAQAAgBAAAAQABAAAAgBQAGgGAGgEQAHgEAHgCQAHgCAIAAQANAAALAFQAJAEAGAIQAFAHABAKQAAAKgHAIQgFAIgMADIgCACIACABQAIACAGADQAGAFAEAHQADAGAAAJQABALgGAJQgGAJgLAFQgMAFgQAAQgJAAgIgDg");
	this.shape_22.setTransform(61.25,-14.625);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#167ABE").s().p("AgeBDQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgKQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAWAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIAAhiQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgWAIQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHIAAgCIABgBIAbgNIADgCIABAAIAIAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAB0QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAVAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAKIgBABIgBABg");
	this.shape_23.setTransform(51.55,-14.625);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#167ABE").s().p("AgkA+QgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIAAgHIABgCIAEAAIAMAAQAEAAADgCIAFgHIADgIQABgFgBgDIgjhUIAAgCIACgBIALAAIACAAIABACIAaBFIACABQAAAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAIAbhEIABgCIABAAIAJAAIACABIAAACIgoBjQgCAHgDAEQgDAEgEACIgIADIgLABg");
	this.shape_24.setTransform(38.7375,-11.25);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#167ABE").s().p("AgEBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAh/QAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAKAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAAB/IgBACIgDABg");
	this.shape_25.setTransform(31.8,-14.625);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAJAAQAHAAAHgFQAHgEAGgHIAAhCQAAAAABgBQAAgBAAAAQABAAAAgBQABAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABZQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgKAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgLIAAgBIgCABQgKAIgHADQgGAEgIAAQgJAAgGgEg");
	this.shape_26.setTransform(24.4,-12.625);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#167ABE").s().p("AgPBCIgIgCIgBgCIAAgCIABgJQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAGACQAEACAFAAQAHAAADgFQAEgEAAgMIAAhgQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABkQAAAQgHAIQgHAIgPAAQgHAAgFgCg");
	this.shape_27.setTransform(15.05,-14.525);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#167ABE").s().p("AgDBbQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAixIAAgBIACgBIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAACxQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_28.setTransform(5.6,-14.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_29.setTransform(-6.025,-14.725);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_30.setTransform(-16.775,-14.725);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_31.setTransform(-29.375,-12.725);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_32.setTransform(-42.075,-14.725);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_33.setTransform(-52.825,-14.725);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#167ABE").s().p("AgVArQgLgGgGgLQgFgLAAgPQAAgOAGgLQAGgMAKgFQAKgHAMABQANAAAKAFQAKAGAFALQAFALAAAPIAAACIgCABIhEAAIgBABIgBACQAAAIAEAIQAFAHAHAEQAHAEAIABQAJAAAHgEQAHgEAFgHIABgBIABABIAIADQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgFAHgGAFQgFAEgIACQgHACgJABQgMgBgKgGgAgOghQgHAEgDAIQgDAHAAAIIA1AAIADAAIAAgDQAAgHgDgHQgDgGgHgFQgGgEgJAAQgIAAgHAFg");
	this.shape_34.setTransform(-67.175,-12.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#167ABE").s().p("AAaAxIgBgBIgBgCIAAg/QAAgJgFgFQgEgFgKAAQgFAAgEACQgEABgFAEIgKAIIAABDQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgKAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhaQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAKAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAKIABACIABgBIALgIQAFgDAGgCQAEgCAGABQAOAAAIAHQAHAIAAAMIAABBQAAABAAABQAAAAgBABQAAAAAAAAQgBABgBAAg");
	this.shape_35.setTransform(-77.625,-12.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAJAAQAGAAAIgFQAHgEAGgHIAAhCQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAIALAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABZQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgLAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgLIAAgBIgCABQgKAIgHADQgHAEgHAAQgIAAgHgEg");
	this.shape_36.setTransform(-88.2,-12.625);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#167ABE").s().p("AgOBCIgJgCIgBgCIAAgCIABgJQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAGACQAEACAFAAQAHAAADgFQAEgEAAgMIAAhgQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABkQABAQgHAIQgHAIgPAAQgGAAgFgCg");
	this.shape_37.setTransform(-97.55,-14.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104.3,-27.3,208.7,54.7);


(lib.t1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0B9444").s().p("AgUCNQgHAAAAgHIAAgqQAAgGAFAAIAsAAQAFAAAAAGIAAApQAAAIgJAAgAgIA7QgEABgCgCIgBgFIgNi7IACgFIADgBIAuAAQAGAAgBAGIgMC6QAAAEgCACQgCACgFgBg");
	this.shape.setTransform(92.2021,18.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0B9444").s().p("AhZCGQgFAAgBgGIAAj5IACgGQABgCAFAAIAjAAQAHAAAAAHIAAANQAAAAAAABQAAAAAAABQABAAAAAAQAAAAABAAIADgBIANgLQAHgGALgEQAKgEAPAAQAXAAARALQASALALAXQALAXgBAiQABAjgLAYQgLAYgSALQgTAMgZAAQgOAAgNgFQgNgFgLgJIgEgDQgCAAAAAFIAABGQAAAGgGAAgAgYhfQgKAFgGAIQgFAHAAAJIAABYQAJAJAKAGQAKAGAMAAQAOAAALgIQAMgIAGgQQAGgQABgaQgBgagGgPQgGgPgMgHQgLgHgMAAQgNAAgJAGg");
	this.shape_1.setTransform(76.35,25.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0B9444").s().p("ABsBnIgFgCIgBgFIAAiCQAAgPgIgIQgHgIgPAAQgJAAgIADQgIAEgGAEIgMAKIgDAFIgBAGIAACAQAAAIgIAAIgiAAIgFgCQgCgBAAgEIAAiCQAAgPgHgIQgHgIgPAAQgNAAgLAHQgLAGgMANIAACGQAAAIgJAAIgiAAQgHAAAAgHIAAi7QAAgHAGAAIAlAAQAFAAAAAGIAAAUIACADIADgCIAUgQQAKgHALgEQALgEAMAAQAVAAANAKQAOAKAFAPIACABIADgCQAKgKALgHQALgIAMgEQAMgEAMAAQAbAAAPAQQAQAQAAAcIAACIQAAAIgIAAg");
	this.shape_2.setTransform(47.175,21.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0B9444").s().p("AhIBZQgQgPAAgZQAAgVAMgPQANgPAYgIQAYgJAggCIATgBIAEgBQABAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAIAAgJQAAgRgKgJQgKgKgRAAQgNAAgLAGQgMAGgIANIgCAEIgFAAIgggIIgDgDQgBgBACgFQALgVAWgMQAWgKAgAAQAdAAASAIQATAHAIAPQAIAOAAATIAACFIgBAGQgCACgDAAIghAAQgDAAgCgDIgBgGIgBgMQgBgGgGAGQgNALgQAHQgOAGgTAAQgdAAgRgPgAAVAEIgXADQgLADgIAFQgJAEgFAIQgFAHAAAJQAAANAJAHQAKAIAQAAQAJAAAIgDQAJgEAHgFIAKgLQAEgGAAgGIAAgbQAAgHgGAAg");
	this.shape_3.setTransform(18.425,22.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0B9444").s().p("Ag8B/QgcgTgPggQgPghAAgsQAAgsAPggQAPggAcgSQAcgQAmAAQAVAAASAFQATAHAPALQAPALAJAPQAKAPADARIAAAHIgEACIgrADIgEgBIgCgFQgEgVgOgOQgOgNgYAAQgfAAgSAZQgRAZAAA2QAAA0ARAZQARAaAiAAQAXAAARgMQARgMAKgbQABgDAGABIAgAHIADACQACACgBAFQgCAIgGALQgGAKgJALQgJALgNAJQgNAIgRAFQgRAFgVABQglAAgdgSg");
	this.shape_4.setTransform(-4.93,18.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0B9444").s().p("AhRCEQgGgCAAgFIAAgYQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAAAQACgCAHAAIAZAAQAIAAAGgFQAGgEAEgGQAEgGABgGQACgHgDgGIhJizQgBgDACgCQABgDAEAAIAoAAIAEACIADAEIAuB9QABAAAAABQAAAAABABQAAAAABAAQAAAAAAAAQACABACgEIAvh8IADgEIAEgCIAcAAQADAAABADQACACgCADIhQDGQgHATgIALQgHAKgJAHQgJAGgMACQgMACgQAAg");
	this.shape_5.setTransform(-37.2325,25.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0B9444").s().p("AhIBZQgQgPAAgZQAAgVAMgPQANgPAYgIQAYgJAggCIATgBIAEgBQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAIAAgJQAAgRgKgJQgKgKgRAAQgNAAgLAGQgMAGgIANIgCAEIgFAAIgggIIgDgDQgBgBACgFQALgVAWgMQAWgKAgAAQAdAAASAIQATAHAIAPQAIAOAAATIAACFIgBAGQgCACgDAAIghAAQgDAAgCgDIgBgGIgBgMQgBgGgGAGQgNALgQAHQgOAGgTAAQgdAAgRgPgAAVAEIgXADQgLADgIAFQgJAEgFAIQgFAHAAAJQAAANAJAHQAKAIAQAAQAJAAAIgDQAJgEAHgFIAKgLQAEgGAAgGIAAgbQAAgHgGAAg");
	this.shape_6.setTransform(-59.025,22.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0B9444").s().p("AhrCNQgIAAAAgIIAAkKQAAgEABgCIAHgBIAQAAIAVAAIAXAAIAPABQA0ABAgAQQAhASAPAeQAQAeAAArQAAAtgQAgQgRAfgiARQghARgyAAgAg7heIAAC+QAAAEAGABIAJAAQAjAAAVgKQAYgKAKgXQALgWAAgkQABgkgLgWQgLgWgWgJQgVgLgiAAIgOAAQgDAAgBAGg");
	this.shape_7.setTransform(-82.5,18.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0B9444").s().p("Ag2BmQgEABgBgCIgCgGIAAi7QAAgGAGAAIAkAAQAGAAAAAFIAAAYIABADQABAAAAAAQAAAAABAAQAAAAABgBQAAAAABgBQAIgLAJgIQAJgHAKgDQALgFAJAAQAOABAAAGIAAAkQAAAFgFAAIgMgDIgMAAQgHAAgIADQgIADgHAGQgGAFgEAHQgEAFAAAHIAAB0QAAAHgJAAg");
	this.shape_8.setTransform(70.325,-15.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0B9444").s().p("AgwBcQgWgNgOgXQgNgXAAgeQAAggANgYQAOgYAXgNQAXgNAaAAQAdAAAVAMQAWANAMAXQAMAXAAAhIgBAGQAAACgFAAIiFAAIgEACIgBAFQAAAPAHANQAIAMAMAHQANAHAOAAQAQAAANgHQANgGALgOIACgDIAFACIAWAKQAGACgEAFQgMARgMAKQgOAKgPAEQgRAEgTAAQgcAAgXgMgAgVhBQgMAIgGAMQgGAMAAAPIBYAAIAGAAIABgFQAAgMgGgLQgEgLgLgIQgKgHgPAAQgOAAgLAHg");
	this.shape_9.setTransform(50.75,-14.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0B9444").s().p("ABsBnIgFgCIgBgFIAAiCQAAgPgIgIQgHgIgPAAQgJAAgIADQgIAEgGAEIgMAKIgDAFIgBAGIAACAQAAAIgIAAIgiAAIgFgCQgCgBAAgEIAAiCQAAgPgHgIQgHgIgPAAQgNAAgLAHQgLAGgMANIAACGQAAAIgJAAIgiAAQgHAAAAgHIAAi7QAAgHAGAAIAlAAQAFAAAAAGIAAAUIACADIADgCIAUgQQAKgHALgEQALgEAMAAQAVAAANAKQAOAKAFAPIACABIADgCQAKgKALgHQALgIAMgEQAMgEAMAAQAbAAAPAQQAQAQAAAcIAACIQAAAIgIAAg");
	this.shape_10.setTransform(22.375,-15.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0B9444").s().p("ABsBnIgFgCIgBgFIAAiCQAAgPgIgIQgHgIgPAAQgJAAgIADQgIAEgGAEIgMAKIgDAFIgBAGIAACAQAAAIgIAAIgiAAIgFgCQgCgBAAgEIAAiCQAAgPgHgIQgHgIgPAAQgNAAgLAHQgLAGgMANIAACGQAAAIgJAAIgiAAQgHAAAAgHIAAi7QAAgHAGAAIAlAAQAFAAAAAGIAAAUIACADIADgCIAUgQQAKgHALgEQALgEAMAAQAVAAANAKQAOAKAFAPIACABIADgCQAKgKALgHQALgIAMgEQAMgEAMAAQAbAAAPAQQAQAQAAAcIAACIQAAAIgIAAg");
	this.shape_11.setTransform(-12.325,-15.125);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0B9444").s().p("Ag8BfQgNgGgHgOQgIgOAAgSIAAiJQAAgHAIgBIAjAAQAGAAAAAHIAACBQAAAPAIAJQAJAIAOAAQAMABAMgIQAMgHALgMIAAiGQAAgHAJgBIAiAAQAHAAAAAHIgBC8QAAAGgFAAIglAAQgGAAAAgGIAAgUIAAgDIgDACQgSARgQAHQgPAGgRABQgRAAgOgIg");
	this.shape_12.setTransform(-41.025,-14.75);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0B9444").s().p("AgsCLQgVgGgRgKQgQgMgKgPQgCgDAAgDIAEgEIAYgRQAFgCACAAIAEADQAKAMAJAIQAJAHANAEQAMAEARAAQAaAAAQgJQAQgJAAgTQAAgIgDgGQgEgGgHgFQgIgGgNgEIg5gSQgWgGgOgLQgOgMgIgPQgHgQAAgQQAAgYANgTQANgTAXgKQAYgKAfAAQAUAAASAEQASAEAPAKQAOAIAKAMIACAFQABABgDADIgbAUIgEACIgEgFQgJgKgOgHQgNgIgXAAQgZABgNAJQgNAKAAAQQAAAGACAGQADAGAHAGQAHAGAOAEIA6ASQAjAKAPATQAQAVAAAbQAAAZgOAUQgNASgYALQgZAKghAAQgYgBgWgFg");
	this.shape_13.setTransform(-64.83,-18.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-99.2,-43.5,198.4,87.1);


(lib.lizart_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.lizart();
	this.instance.setTransform(-128,-17.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128,-17.5,256,35);


(lib.f = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.frog();
	this.instance.setTransform(-72,-41,0.36,0.36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72,-41,144,81);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZA2IgCAAIAAgCIAAhlQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAMAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAANIABABIABAAIAJgKIAKgGQAGgCAFAAQAHAAAAACIAAANQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgEAAIgFAAQgEAAgFACQgFACgEADQgDADgEAEQgCAEAAAFIAABBQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape.setTransform(28.15,0.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZAwQgMgHgGgMQgHgNAAgQQAAgPAHgMQAGgNAMgHQALgHAOAAQAPAAAMAHQALAIAGAMQAHAMAAAPQAAAQgHAMQgGANgLAHQgMAHgPAAQgOAAgLgHgAgRgkQgHAFgEAKQgEAJAAAMQAAANAEAKQAEAJAHAFQAIAGAJAAQALAAAHgGQAIgFAEgJQADgKAAgNQAAgMgEgJQgEgKgHgFQgHgFgLgBQgJABgIAFg");
	this.shape_1.setTransform(17.825,0.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgIBKQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhZQAAAAgBAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgTAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgJIABgBIACgBIATAAQAAAAAAAAQABAAAAAAQAAAAAAgBQABAAAAgBIAAgOQgBgNAHgHQAFgGANAAIAQAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAIIgBACIgBAAIgOAAQgHAAgDAEQgCAEAAAGIAAAOQAAABAAAAQAAABAAAAQAAAAABAAQAAAAABAAIAWAAIACABIABABIAAAJQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgWAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAABYQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(8.15,-1.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgsBGQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAiFIAAgCIADAAIAKAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIACgBIAGgFQAEgDAGgDQAGgDAIAAQAMABAKAFQAKAHAGALQAGAMAAASQAAARgGANQgGAMgKAHQgKAHgOAAQgIAAgHgEQgHgCgFgEIgDgCIgBADIAAAlQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAgAgQg2QgGAEgEAFQgEAFAAAFIAAAxQAHAGAGAEQAHADAIAAQAIAAAIgEQAHgGAFgKQAEgJAAgOQAAgPgFgIQgEgKgHgEQgIgFgHABQgJAAgGADg");
	this.shape_3.setTransform(-5.575,2.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAyQgHgEgEgGQgEgIAAgIIAAhKQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIALAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAABFQAAAKAFAGQAGAGAJAAQAIAAAIgFQAIgFAHgHIAAhKQAAgBAAAAQABgBAAAAQABgBAAAAQABAAABAAIALAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABkQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgMAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgMIAAgBIgCAAQgLAKgIAEQgIADgIAAQgJAAgIgEg");
	this.shape_4.setTransform(-17.675,1.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAeA2IgDAAIAAgCIAAhHQAAgKgFgGQgFgFgLAAQgGAAgEACIgKAFIgMAJIAABLQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgLAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhlQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIALAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAMIAAABIACAAIAMgJQAGgEAFgCQAGgCAHAAQAPAAAIAJQAJAIgBANIAABKQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_5.setTransform(-33.4,0.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgpBAQgNgHAAgOQAAgGAFgGQAEgGAJgEQABgBAAAAQABAAAAAAQAAgBgBAAQAAAAgBgBQgEgCgCgCQgCgEgBgEIACgFIAGgEIAIgFIABgBIgBgBQgIgEgFgGQgEgIAAgJQAAgPAMgJQAMgJAVAAQAKAAAHADQAHACAFAEIADABIACgBIAFgFIAGgDIAHgCIADACIABACIAAAHIgBADQAAAAgBAAQAAAAAAAAQgBABAAAAQgBAAAAgBIgGABIgEABQgFACAAADIADAFIABAIQAAAJgFAIQgEAHgKAEQgKAFgNAAQgLgBgGACQgFABgDACQgCABAAADQAAADAEABQAFACAJAAIAZACQASAAAIAIQAIAHAAAMQAAAPgOAJQgNAJgXgBQgaABgNgIgAgcAZQgEADgEAEQgDAEAAAGQAAAFAEAFQAEAEAJADQAJACAMAAQAQAAAJgFQAJgEAAgLQgBgGgEgEQgFgFgKgBIghgBQgDAAgFABgAgXg2QgIAGABALQgBALAIAGQAHAFAOAAQANAAAGgFQAHgGAAgLQAAgLgHgGQgGgFgNAAQgOAAgHAFg");
	this.shape_6.setTransform(-45.3,2.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEBKIgDAAIgBgDIAAhjQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIALAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABjIgBADIgCAAgAgFgyQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBgBAAIAAgCIAAgRQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIALAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAQQAAAEgEAAg");
	this.shape_7.setTransform(-53.65,-1.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUBJQgKgDgIgFQgIgGgGgIIgBgCIACgDIAIgFIADgBIACABQAFAHAFAFQAFAEAHACQAHADAJAAQAQAAAKgGQAKgGAAgNQAAgFgCgEQgCgEgFgEQgFgDgJgEIgdgKQgLgDgHgGQgHgGgDgHQgDgHAAgIQAAgMAGgKQAHgJALgFQALgFAOAAQALAAAIACQAJADAHAEQAHAEAFAHIABABIgBACIgJAIIgCAAIgCgCQgFgGgIgEQgIgFgNAAQgOAAgIAHQgJAHAAALIACAIQABAEAFAEQAEAEAKADIAcAKQASAFAHAKQAIAKAAANQAAANgGAJQgHAJgMAFQgLAFgRAAQgLAAgKgDg");
	this.shape_8.setTransform(-62.525,-1.175);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#167ABE").s().p("ArvCrQgyAAgkgkQgigigBgyIAAhlQABgyAigjQAkgjAyAAIXgAAQAxAAAjAjQAjAjAAAyIAABlQAAAygjAiQgjAkgxAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-87.2,-17.1,174.5,34.2);


(lib.bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.turtle_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.tr("synched",0);
	this.instance.setTransform(-26.05,0,0.9362,0.9362,0,0,0,-0.6,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0,scaleX:1,scaleY:1,x:0},49,cjs.Ease.get(1)).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-165.9,-126.5,316.4,253.1);


(lib.snake_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(102,102,102,0.898)").s().p("AgmAmQgPgPAAgXQAAgVAPgRQAQgPAWAAQAXAAAPAPQAQARAAAVQAAAXgQAPQgPAQgXAAQgWAAgQgQg");
	this.shape.setTransform(8.55,-2.05);
	this.shape._off = true;

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(102,102,102,0.898)").s().p("AgiAjQgQgNgCgSQAAgUAPgPQAPgPAVgBQAHAAAIACQAMADAJAJQALAKAEANQACAGABAFQABANgGALQgEAGgFAEQgQANgVAAQgUAAgQgNg");
	this.shape_1.setTransform(8.5077,-2.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(102,102,102,0.898)").s().p("AAFApQgTAAgQgKQgPgKgGgOIAAAAQABgSAOgOQAOgOAVgBQAGgBAHACQAMACAJAIQALAJAFAMQACAFABAFQACAMgEALIgJAHQgPAJgTAAIgCAAg");
	this.shape_2.setTransform(8.4475,-3.28);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(102,102,102,0.898)").s().p("AAHAjQgSAAgQgIQgPgHgIgJIgBAAQACgRANgNQAOgOATgBQAGgBAGACQAMABAJAHQALAHAGAMIAEAJQACALgCAKIgKAFQgOAGgSAAIgCAAg");
	this.shape_3.setTransform(8.4444,-3.8795);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(102,102,102,0.898)").s().p("AAIAdQgRAAgPgFQgQgEgKgFIgBAAQACgPAMgNQAOgNASgCIALABQALABAJAFQALAGAHALIAEAIQAEAKgBAKIgKACQgNADgQAAIgEAAg");
	this.shape_4.setTransform(8.46,-4.5052);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(102,102,102,0.898)").s().p("AAJAWQgPAAgPgCIgdgBIgBAAQADgPALgLQAMgMASgDQAFAAAFAAQALAAAIAFQALAFAIAJIAFAHQAFAJABAKIgKAAIgKAAIgXgBg");
	this.shape_5.setTransform(8.5,-5.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(102,102,102,0.898)").s().p("AgzAUQADgOAKgJQAQgQAWAAQAXAAAPAQQALAJADAOQgzgMg0AMg");
	this.shape_6.setTransform(8.55,-5.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},6).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[]},1).wait(21));
	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6).to({_off:false},0).wait(7).to({_off:true},1).wait(27));

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_6 = new cjs.Graphics().p("Ak9hTIChiwIHaD+IgqEJQllgXjslAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(6).to({graphics:mask_graphics_6,x:54.9875,y:32.5}).wait(16).to({graphics:null,x:0,y:0}).wait(19));

	// Layer_2
	this.instance = new lib.tg("synched",0);
	this.instance.setTransform(40.35,4.35,1,1,-29.9992);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(6).to({_off:false},0).to({rotation:-30.9919,x:62.85,y:17.6},7,cjs.Ease.get(1)).wait(1).to({rotation:-31.0297,x:62.6986,y:17.5149},0).wait(1).to({regX:0.1,regY:0.1,rotation:-31.1431,x:62.3,y:17.25},0).wait(1).to({regX:0,regY:0,rotation:-31.5024,x:60.502,y:16.3438},0).wait(1).to({rotation:-32.0731,x:57.8845,y:14.9841},0).wait(1).to({rotation:-32.8551,x:54.2976,y:13.1207},0).wait(1).to({rotation:-33.8486,x:49.7413,y:10.7537},0).wait(1).to({rotation:-35.0533,x:44.2156,y:7.8832},0).wait(1).to({rotation:-36.4695,x:37.85,y:4.6},0).to({_off:true},1).wait(19));

	// Layer_1
	this.instance_1 = new lib.snake();
	this.instance_1.setTransform(-148.6,-96.9,0.9316,0.9316);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-148.6,-96.9,297.2,193.8);


(lib.Frog = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.instance = new lib.f("synched",0);
	this.instance.setTransform(-119.2,-10.2,0.24,0.24,0,0,0,0,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:-0.5,scaleX:0.3844,scaleY:0.3844,x:-133.1,y:-18.75},0).wait(1).to({regX:-0.1,regY:-0.3,scaleX:0.5136,scaleY:0.5136,x:-145.6,y:-26.25},0).to({regY:-0.4,scaleX:0.81,scaleY:0.6866,x:-163.7,y:-20.5},1).wait(1).to({regX:0,regY:-0.5,scaleX:0.9525,scaleY:0.9216,x:-174.45,y:-12.9},0).wait(1).to({regY:0,scaleX:1,scaleY:1,x:-178.2,y:-10.2},0).wait(16));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-250.2,-51.2,148.29999999999998,81);


// stage content:
(lib.KSFY_216373_MM_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(181));

	// t3
	this.instance = new lib.t3("synched",0);
	this.instance.setTransform(150,480.35,0.6,0.6,0,0,0,0.1,0);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(62).to({_off:false},0).to({regX:0,scaleX:1,scaleY:1,alpha:1},13,cjs.Ease.get(1)).wait(106));

	// t2
	this.instance_1 = new lib.t2("synched",0);
	this.instance_1.setTransform(148.75,352.6,0.6,0.6,0,0,0,0.1,0);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(45).to({_off:false},0).to({regX:0,scaleX:1,scaleY:1,alpha:1},13,cjs.Ease.get(1)).wait(123));

	// t1
	this.instance_2 = new lib.t1("synched",0);
	this.instance_2.setTransform(149.1,279.2,0.6,0.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(26).to({_off:false},0).to({scaleX:1,scaleY:1,alpha:1},13,cjs.Ease.get(1)).wait(142));

	// lizart_png
	this.instance_3 = new lib.lizart_png("synched",0);
	this.instance_3.setTransform(11,423.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:46,y:415.5},104,cjs.Ease.get(1)).wait(77));

	// snake_png
	this.instance_4 = new lib.snake_1("synched",0);
	this.instance_4.setTransform(249.6,558.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(181));

	// turtle_png
	this.instance_5 = new lib.turtle_1("synched",0,false);
	this.instance_5.setTransform(56.45,141.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(181));

	// Frog
	this.instance_6 = new lib.Frog("synched",0,false);
	this.instance_6.setTransform(401,200.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(14).to({_off:false},0).wait(167));

	// Cta
	this.instance_7 = new lib.cta("synched",0);
	this.instance_7.setTransform(-100.8,216.95);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({x:149.2},14,cjs.Ease.get(1)).wait(167));

	// BG_jpg
	this.instance_8 = new lib.bg("synched",0);
	this.instance_8.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(181));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-38.1,299,436.3,356.79999999999995);
// library properties:
lib.properties = {
	id: '1D42CF45455647789E9AE0A47792069B',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"frog.png", id:"frog"},
		{src:"lizart.png", id:"lizart"},
		{src:"snake.png", id:"snake"},
		{src:"Tounge.png", id:"Tounge"},
		{src:"turtle.png", id:"turtle"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['1D42CF45455647789E9AE0A47792069B'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;