(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.IM1 = function() {
	this.initialize(img.IM1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.IM2 = function() {
	this.initialize(img.IM2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.PBB_logo1 = function() {
	this.initialize(img.PBB_logo1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,244,194);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3927").s().p("AgGAkQgEgEAAgDQAAgCAEgEQAEgFACAAQADAAAEAFQAEAEAAACQAAADgEAEQgEAFgDAAQgCAAgEgFgAgEAKIgBgGIgDgTIgBgNQAAgLAJAAQALAAAAALIgCANIgDATIgBAGQgBAEgEAAQgCAAgCgEg");
	this.shape.setTransform(-312.275,-19.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B3927").s().p("AgLAbQgCgEAAgJIABgYIgBgBIgHAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIAAgFQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAQAIgCADgEQABgCACgGQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAKIAAADIADABIAFAAIAHgBQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAABIgBADIgBAEIgEABIgFgBIgGAAIgBABIAAAJQAAAPABAFQACAGAGAAQADABACgCIADgCQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBAEQgGAIgLAAQgKAAgFgJg");
	this.shape_1.setTransform(-316.15,-18.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B3927").s().p("AgLAqQgEAAAAgDQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQADgCABgDIABgMIAAgOIgBgGQgBgDgDgBQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAPgEIACgBQABAAABAAQAAAAAAABQABAAAAABQAAABAAABIAAAfIABAMQABADADACQABAAABABQAAAAABAAQAAABAAAAQAAAAAAABQAAADgEAAgAgFgYQgEgEAAgCQAAgDAEgEQAEgEABAAQADAAAEAEQAEAEAAADQAAACgEAEQgEAEgDAAQgBAAgEgEg");
	this.shape_2.setTransform(-319.775,-19.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B3927").s().p("AgTAaQgEgEAAgJQAAgFAEAAIADACIAEAEQAGAHAGAAQADABACgCQADgCAAgDQAAgDgEgCIgKgDQgHgDgDgDQgFgDAAgHQAAgJAIgGQAGgFAJAAQAJAAAFADQAFADAAAHQAAADgBABQAAABAAAAQgBABAAAAQgBAAAAAAQgBABAAAAQgCAAgCgEQgGgHgHgBQgCABgCACQgBAAAAAAQAAABgBAAQAAABAAAAQAAABAAAAQAAAEAFACIAJADQAQAGAAAKQAAAKgIAFQgHAFgKAAQgMAAgGgEg");
	this.shape_3.setTransform(-327.625,-18.15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B3927").s().p("AgTAaQgEgEAAgJQAAgFAEAAIADACIAEAEQAGAHAGAAQADABACgCQADgCAAgDQAAgDgEgCIgKgDQgHgDgDgDQgFgDAAgHQAAgJAIgGQAGgFAJAAQAJAAAFADQAFADAAAHQAAADgBABQAAABAAAAQgBABAAAAQgBAAAAAAQgBABAAAAQgCAAgCgEQgGgHgHgBQgCABgCACQgBAAAAAAQAAABgBAAQAAABAAAAQAAABAAAAQAAAEAFACIAJADQAQAGAAAKQAAAKgIAFQgHAFgKAAQgMAAgGgEg");
	this.shape_4.setTransform(-333.125,-18.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B3927").s().p("AgLAqQgEAAAAgDQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQADgCABgDIABgMIAAgOIgBgGQgBgDgDgBQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAPgEIACgBQADAAAAAEIAAAfIABAMQABADADACQABAAABABQAAAAABAAQAAABAAAAQAAAAAAABQAAADgEAAgAgFgYQgEgEAAgCQAAgDAEgEQAEgEABAAQADAAAEAEQAEAEAAADQAAACgEAEQgEAEgDAAQgBAAgEgEg");
	this.shape_5.setTransform(-337.725,-19.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B3927").s().p("AAZAeQgFgBAAgDQAAAAAAAAQABgBAAAAQAAAAABgBQABAAAAAAQADgCABgEIABgLIAAgMQAAgLgJAAQgEAAgDADQgCACgBAGIgBAMIABAMQAAABAAABQAAAAABABQAAAAAAAAQABABAAAAIADADQAAADgEABIgTAAQgEgBAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQABgBABAAQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAgBIABgMIAAgLQAAgMgJAAQgEAAgDADQgCACgBAGIgBAMIABALQABAEADACQAAAAABAAQABABAAAAQAAAAABABQAAAAAAAAQAAADgFABIgXAAQgEgBAAgDQAAAAAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQADgCABgEIABgLIAAgNIAAgHQgBgDgDgBQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQABgBABAAIAPgFIADAAQAAAAABAAQABAAAAAAQAAABABABQAAAAAAABIAAAGIAAAAIABAAQAGgKAMABQAKgBAFAKIABAAIAAAAQAHgKALABQAKgBAFAJQAEAFAAAJIAAANIABALQABAEADACQAAAAABAAQABABAAAAQAAAAABABQAAAAAAAAQgBADgEABg");
	this.shape_6.setTransform(-345.075,-18.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3927").s().p("AgLAbQgCgEAAgJIABgYIgBgBIgHAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIAAgFQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAQAIgCADgEQABgCACgGQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAKIAAADIADABIAFAAIAHgBQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAABIgBADIgBAEIgEABIgFgBIgGAAIgBABIAAAJQAAAPABAFQACAGAGAAQADABACgCIADgCQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBAEQgGAIgLAAQgKAAgFgJg");
	this.shape_7.setTransform(-354.4,-18.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3927").s().p("AgDALQgDgJAAgJQAAgEABgCQACgCADAAQAEAAACACQABACAAAEQAAAJgDAJQgBAEgDABQgCgBgBgEg");
	this.shape_8.setTransform(-357.725,-21.55);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3927").s().p("AAHAeQgEgBAAgDQAAAAAAAAQAAgBAAAAQABAAAAgBQABAAAAAAQAEgCABgEIABgLIAAgMQAAgLgJAAQgDAAgEADQgEAFAAAPIABALQABAEACACQABAAABAAQAAABABAAQAAAAAAABQAAAAAAAAQABADgFABIgYAAQgDgBAAgDQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAABAAQADgCABgEIABgLIAAgNIAAgHQgCgDgDgBQAAAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQABAAAAAAIAQgFIACAAQADAAABADIAAAGIAAAAIABAAQAGgKALABQAJAAAFAIQAEAFAAAKIAAAMIABALQABAEADACQABAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQAAADgFABg");
	this.shape_9.setTransform(-361.15,-18.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3927").s().p("AgVAWQgIgIAAgNQAAgMAJgJQAJgJAMAAQANAAAIAIQAIAJAAAMQAAANgIAIQgJAJgNAAQgMAAgJgIgAgMgDQAAAIADAGQAEALAGgBQAGAAADgEQADgGAAgIQAAgHgDgIQgDgIgHgBQgMABAAARg");
	this.shape_10.setTransform(-367.825,-18.15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3927").s().p("AAJAmIAAgEIgBgBIgBAAQgHAJgJAAQgKAAgHgIQgGgIAAgLQAAgNAHgJQAJgKANAAQAFAAAGACIABABIAAgBIAAgEIgBgHQgBgCgDgBQgBgBAAAAQgBAAAAgBQgBAAAAgBQAAAAAAAAQAAgCAEgCIAOgEIADgBQADAAAAAEIAAA5IABAHQABADADABQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBABIgOAEIgEABQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBgAgMgCQgDAEAAAIQAAAJAEAFQADAGAGAAQAEAAADgFQAEgFAAgJQAAgKgDgEQgEgGgFAAQgGAAgDAHg");
	this.shape_11.setTransform(-374.175,-19.325);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3927").s().p("AgZAdQgHgLAAgRQAAgRAKgLQAJgMAOgBQAPABAJAKQAIAMABARQgBATgKALQgJAKgOAAQgPABgKgMgAgMgCQgBAOAEAJQAEALAFgBQAOAAAAgdQAAgPgEgJQgEgJgGAAQgNAAABAdg");
	this.shape_12.setTransform(-301.25,-31.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3927").s().p("AgQAmQgHgBgDgFQgCgDAAgHIABgGQAAgCAEgBQADAAABAEIADAGQAGAJAIAAQAEAAADgEQAEgFAAgHQgBgOgMAAIgGABQgFAAAAgDIAAgDQAAgDAFAAIAGAAQALABAAgNQgBgGgCgDQgCgEgFAAQgFAAgEAFIgEAIQgCADgEAAQAAAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQgBgCAAgFQAAgIAEgEQAHgEANgBQALAAAIAGQAIAFABAJQgBAGgEAFQgFAFgIACIgBABIABABQAIAAAGAEQAGAFAAAIQAAAIgHAHQgJAIgPAAQgIAAgGgCg");
	this.shape_13.setTransform(-307.95,-31.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3927").s().p("AgbAkQgDgDAAgFQABgHAFAAQABAAAEADQADAEAEAAQAEgBADgFIABgBIAAgBIgTgrQgDgGgCgCIgDgCQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAQgBgEAFAAIAYAAQAAAAABABQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgDABgBADIACAFIAKAYIABAAIAAAAIAHgQQACgGAAgEQAAgEgDgCQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAAAQAAgEAFAAIASAAQADAAAAAEQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgDACIgEAFIgFALIgOAeQgIAYgRAAQgFAAgEgDg");
	this.shape_14.setTransform(-316.45,-29.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("AAHAWIgBAAIAAAAQgGAIgLAAQgHAAgFgEQgGgDAAgIQAAgIAIgFIATgGQAHgFAAgEQAAgIgGAAQgEABgDACQgDACgDAEQgDAEgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgEQAAgHACgCQACgDAIgCIALgBQAJAAAGAFQAIAEAAAKIAAAUQAAAGABABQABADADABQAAAAABAAQABAAAAAAQAAAAABABQAAAAAAABQAAACgDACQgEADgFAAQgJAAgCgIgAgHAGQgEAEAAAEQAAAAAAABQAAABABAAQAAABAAAAQAAABABAAQACACADAAQAFAAACgGQACgDAAgJIAAgCIgBAAIAAAAQgHADgEADg");
	this.shape_15.setTransform(-322.875,-30.25);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AASAnQgBAAgBAAQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQABAAABgBQACgCABgDQACgDAAgIIAAgoIgBgBIgBABIgTAvQAAABgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgFAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgTgvIgBgBIAAABIAAArQAAAJAFADIAEACQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQAAADgFAAIgUAAQgEAAAAgCIACgDIACgDQADgEAAgNIABgoIgBgEIgCgCIgCgBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgDAEAAIAWAAQADAAACACIAPAkIAAAAIABAAIAPgkQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAIAZAAQAAAAABAAQABAAAAAAQABABAAAAQAAABAAAAIgBACIgDACQgDACAAAGIAAApIABALQABAEADABQABABAAAAQABAAAAABQABAAAAABQAAAAAAAAQAAADgEAAg");
	this.shape_16.setTransform(-330.8,-31.275);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("AgTAZQgEgDAAgIQAAgGAEAAIADABIAEAFQAGAIAGAAQADgBACgBQADgCAAgDQAAgDgEgCIgKgEQgHgCgDgDQgFgDAAgHQAAgKAIgEQAGgGAJAAQAJAAAFADQAFADAAAGQAAAFgBAAQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBgBAAAAQgGgJgHAAQgCAAgCACQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAABQAAACAFACIAJAFQAQAFAAALQAAAIgIAGQgHAFgKAAQgMAAgGgFg");
	this.shape_17.setTransform(-341.775,-30.25);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AAJAmIAAgEIgBgBIgBAAQgHAJgJAAQgKAAgHgIQgGgIAAgLQAAgNAHgJQAJgKANAAQAFAAAGACIABABIAAgBIAAgEIgBgHQgBgCgDgBQgBgBAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgCAEgCIAOgEIADgBQADAAAAAEIAAA5IABAHQABADADABQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAQAAABgBAAIgOAEIgEABQgBAAAAAAQgBgBAAAAQAAgBgBAAQAAgBAAgBgAgMgCQgDAEAAAIQAAAJAEAFQADAGAGAAQAEAAADgFQAEgFAAgJQAAgKgDgEQgEgGgFAAQgGAAgDAHg");
	this.shape_18.setTransform(-347.675,-31.425);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("AAHAdQgEAAgBgCQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAgBQAEgCABgCIABgMIAAgNQAAgKgJAAQgEAAgDADQgEAFAAAPIABAMQABACACACQABABABAAQAAABABAAQAAAAAAABQABAAAAABQAAACgFAAIgYAAQgBAAAAAAQgBAAgBAAQAAgBAAAAQgBgBABAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABgBQADgCABgCIABgMIAAgNIAAgIQgBgCgEgBQAAAAgBgBQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQABAAAAAAIAPgEIADgBQAEAAAAADIAAAGIAAABIABgBQAGgKALABQAKgBAEAJQAEAEAAAKIAAANIABAMQABACADACQABABABAAQAAABAAAAQABAAAAABQAAAAAAABQAAACgFAAg");
	this.shape_19.setTransform(-354.3,-30.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AgSAXQgIgJAAgMQAAgMAIgJQAIgKAMAAQAKAAAHAHQAIAGAAAKQAAAFgCABQgCAAgGAAIgZAAIgBABIAAACQABAEACAEQAFAIAKAAQAFAAAEgDIAGgCQAAABABAAQAAAAAAAAQABAAAAABQAAAAAAABQAAADgHAFQgHAFgLAAQgLAAgIgHgAgFgSQgDAEgBAFIAAABIABABIAMAAQAGAAAAgFQAAgDgCgDQgDgDgEAAQgDAAgDADg");
	this.shape_20.setTransform(-361.2,-30.25);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AgSAXQgIgJAAgMQAAgMAIgJQAJgKALAAQAKAAAHAHQAIAGAAAKQAAAFgDABQgBAAgGAAIgZAAIgBABIAAACQABAEACAEQAFAIAKAAQAFAAAFgDIAEgCQABABABAAQAAAAAAAAQABAAAAABQAAAAAAABQAAADgHAFQgHAFgLAAQgLAAgIgHgAgFgSQgDAEgBAFIAAABIABABIAMAAQAGAAABgFQAAgDgDgDQgCgDgEAAQgEAAgDADg");
	this.shape_21.setTransform(-370.35,-30.25);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AgKApQgFAAAAgDQAAAAAAAAQABgBAAAAQAAgBABAAQAAAAABgBQADgCABgDIABgLIAAglIgBgHQAAgDgEgBQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAgCAEgBIAOgEIADgBQADAAAAAEIAAA3IABALQABADADACQAAABABAAQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAg");
	this.shape_22.setTransform(-374.725,-31.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AAHAWIgBAAIAAAAQgGAIgLAAQgHAAgFgEQgGgDAAgIQAAgIAIgFIATgGQAHgFAAgEQAAgIgGAAQgEABgDACQgDACgDAEQgDAEgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgBgEQAAgHACgCQACgDAIgCIALgBQAJAAAGAFQAIAEAAAKIAAAUQAAAGABABQABADADABQAAAAABAAQABAAAAAAQAAAAABABQAAAAAAABQAAACgDACQgEADgFAAQgJAAgCgIgAgHAGQgEAEAAAEQAAAAAAABQAAABABAAQAAABAAAAQAAABABAAQACACADAAQAFAAACgGQACgDAAgJIAAgCIgBAAIAAAAQgHADgEADg");
	this.shape_23.setTransform(-379.575,-30.25);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B3927").s().p("AgRAmQgIgCgCgEQgCgDAAgHIAAgEQAAgFAEAAQABAAAAAAQAAAAABABQAAAAABAAQAAABABAAIAGAIQAIAIAHAAQAHAAADgCQADgEABgEQgBgGgGgEIgNgGQgJgDgFgDQgGgFgBgJQAAgKAJgIQAJgHAMAAQAPAAAGAHQADADAAAHQAAAIgEAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAgBgBAAIgDgGQgIgHgHgBQgDAAgDACQgDADgBAEQABAGAGADIANAGQAKAEAEADQAGAFABAKQgBAMgIAGQgKAIgNgBQgJAAgHgCg");
	this.shape_24.setTransform(-386.75,-31.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-400.7,-36.6,112.30000000000001,24.700000000000003);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#DD002A").s().p("AgTAYQgJgIAAgOQAAgNAJgKQAJgLAMAAQALAAAIAHQAIAHAAALQABAFgDABQgCABgGAAIgbAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAABIABABQAAAFACAEQAGAJALAAQAGAAAEgCIAGgDQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABQAAAEgHAFQgJAGgLAAQgMAAgIgJgAgGgTQgDADgBAGIAAABQAAAAAAAAQAAAAAAAAQABABAAAAQAAAAABAAIAMAAQAIAAAAgFQAAgEgDgDQgDgDgEAAQgEAAgEAEg");
	this.shape.setTransform(-256.55,-40.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#DD002A").s().p("AgMAtQgFAAAAgDQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAgBQAEgCABgDQABgDAAgKIAAgoQAAgGgBgCQgBgCgDgCQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABgBQAAAAABAAIAQgFIADgBQADAAAAAEIAAA8QAAAKABADQABADAEACQABABAAAAQABABAAAAQAAABABAAQAAAAAAABQAAADgFAAg");
	this.shape_1.setTransform(-261.425,-41.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#DD002A").s().p("AAHAYIAAgBIgBAAQgGAKgNAAQgHAAgGgEQgFgFAAgHQAAgKAIgFQAGgDAOgEQAIgEAAgGQAAgHgHAAQgEAAgDACQgDACgEAFQgDAEgCAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBIgBgFQAAgHADgCQACgEAIgCIANgBQAJAAAIAFQAIAFAAALIAAAWIAAAIQABADAEAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAQAAADgDACQgEAEgGAAQgKAAgCgJgAAEAAIgMAGQgEAEAAAEQAAADACACQACACADAAQAFAAADgGQACgDAAgLIAAgBIAAAAg");
	this.shape_2.setTransform(-267.225,-40.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#DD002A").s().p("AgTAqQgIgDgDgFQgCgDAAgHIAAgFQAAgFAEAAQADAAACADIAGAIQAJAJAIAAQAHAAADgDQAEgEAAgFQAAgGgGgEIgPgGQgKgEgFgDQgHgGAAgKQAAgLAJgIQAKgHANAAQAQAAAHAGQADADAAAJQAAAIgFAAQgCAAgCgCIgFgGQgHgJgIAAQgEAAgDADQgEACAAAFQAAAGAHAEIAPAGQAKAEAFAEQAHAGAAAKQAAAMgKAIQgKAIgPAAQgJAAgIgCg");
	this.shape_3.setTransform(-274.275,-41.775);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#DD002A").s().p("AgdAoQgEgEAAgFQAAgIAGAAQACAAAEADQAEAEAEAAQAEAAADgFIABgCIAAgBIgVguIgFgKIgEgCQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAgDAFAAIAaAAQABAAAAAAQABABABAAQAAAAAAABQABAAAAABQAAABAAAAQgBAAAAABQAAAAgBAAQgBABAAAAQgDACAAADIABAEIALAbIAAAAIABAAIAHgSQADgGAAgFQAAgEgDgCQgBgBAAAAQgBgBAAAAQgBgBAAAAQAAAAAAgBQAAgDAEAAIAUAAQAFAAAAADQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIgEACIgEAFIgGANIgOAhQgKAagRAAQgGAAgEgDg");
	this.shape_4.setTransform(-285.475,-39.475);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#DD002A").s().p("AAHAYIAAgBIgBAAQgGAKgNAAQgHAAgGgEQgFgFAAgHQAAgKAIgFQAGgDAOgEQAIgEAAgGQAAgHgHAAQgEAAgDACQgDACgEAFQgDAEgCAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBIgBgFQAAgHADgCQACgEAIgCIANgBQAJAAAIAFQAIAFAAALIAAAWIAAAIQABADAEAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAQAAADgDACQgEAEgGAAQgKAAgCgJgAAEAAIgMAGQgEAEAAAEQAAADACACQACACADAAQAFAAADgGQACgDAAgLIAAgBIAAAAg");
	this.shape_5.setTransform(-292.625,-40.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#DD002A").s().p("AglArQgFAAAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAEgEQABgDAAgMIAAgsQAAgHgCgCIgDgCQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQABAAABAAIATAAIAXABQAKABAGAEQAKAFAGAJQAGAKAAAMQAAASgMALQgOAOgZAAgAgOgdIAAAwQABALACABQABACAFAAIAFgBQAIgBAHgIQAGgIAAgPQAAgUgMgIQgHgEgKAAIgCAAQgBAAgBAAQAAAAgBABQAAAAAAABQgBAAAAABg");
	this.shape_6.setTransform(-301,-41.775);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#DD002A").s().p("AgMAtQgFAAAAgDQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAgBQAEgCABgDQABgDAAgKIAAgoIgBgIQgBgCgDgCQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgCAEgBIAQgFIADgBQADAAAAAEIAAA8QAAAKABADQABADAEACQAAABABAAQABABAAAAQAAABABAAQAAAAAAABQAAADgFAAg");
	this.shape_7.setTransform(-311.575,-41.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#DD002A").s().p("AAHAYIAAgBIgBAAQgGAKgNAAQgHAAgGgEQgFgFAAgHQAAgKAIgFQAGgDAOgEQAIgEAAgGQAAgHgHAAQgEAAgDACQgDACgEAFQgDAEgCAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBIgBgFQAAgHADgCQACgEAIgCIANgBQAJAAAIAFQAIAFAAALIAAAWIAAAIQABADAEAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAQAAADgDACQgEAEgGAAQgKAAgCgJgAAEAAIgMAGQgEAEAAAEQAAADACACQACACADAAQAFAAADgGQACgDAAgLIAAgBIAAAAg");
	this.shape_8.setTransform(-317.125,-40.625);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#DD002A").s().p("AgLAtQgGAAAAgCQAAgBABAAQAAgBAAAAQABgBAAAAQABgBAAAAQAEgCABgEQABgCAAgKIAAgPIAAgHQgCgDgDgBQgEgCAAgCQAAgCAEgBIAQgFIADgBQADAAAAAFIAAAiQAAAKABACQABAEAEACQAAAAABABQABAAAAABQABAAAAABQAAAAAAABQAAACgFAAgAgGgaQgFgFABgCQgBgDAFgEQAEgEACgBQADABAFAEQADAEAAADQAAACgDAFQgFAEgDABQgCgBgEgEg");
	this.shape_9.setTransform(-323.05,-42.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#DD002A").s().p("AgUAgQgFAAAAgDQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAABgBQADgCABgDQABgDAAgKIAAgOIAAgIQgBgCgEgCQgEgCAAgBQAAgCAEgCQAIgBAHgDIAEgBQADAAAAAEIAAAJIAAAAIAAAAQACgFAEgEQAFgEAGAAQAFAAACADQADAEAAAFIgBAFQgCACgDAAIgFgCIgFgCQgLAAAAAXQAAAKACADQABADADACQABABAAAAQABABAAAAQAAABABAAQAAABAAAAQAAADgFAAg");
	this.shape_10.setTransform(-328.125,-40.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#DD002A").s().p("AgXAYQgJgJAAgPQAAgMAJgKQALgKANAAQAOAAAJAJQAJAJAAAOQAAANgKAKQgKAKgNAAQgOAAgJgJgAgNgEQAAAJADAHQAEALAHAAQAGAAAEgGQACgFAAgJQAAgIgCgIQgEgKgHAAQgNAAAAATg");
	this.shape_11.setTransform(-335.15,-40.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#DD002A").s().p("AAbAgQgFAAAAgDQAAAAABgBQAAAAAAgBQABAAAAgBQABAAABgBQADgCABgDQABgDAAgKIAAgOQAAgKgKgBQgEAAgEAEQgDADAAAFIAAANIAAAOQAAABAAAAQABABAAAAQAAABABAAQAAABAAAAQAEADAAABQgBADgEAAIgUAAQgFAAAAgDQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABgBQAAAAABgBQAAAAABgBQAAAAAAgBQAAAAABgBQABgCAAgMIAAgMQAAgNgKAAQgFAAgDAEQgCACgBAFIgCAOQAAAJACAEQABADADACQABABABAAQAAABABAAQAAABAAAAQAAABAAAAQAAADgEAAIgaAAQgFAAAAgDQAAAAAAgBQAAAAABgBQAAAAABgBQAAAAABgBQAEgCAAgDQABgDAAgKIAAgOIAAgIQgBgCgDgCQgEgCgBgBQAAgDAFgBIAQgEIADgBQADAAAAAEIAAAGIABABIABAAQAGgLANAAQALAAAGAKIABABIABgBQAGgKAMAAQAMAAAGAJQADAGAAAJIAAAOQAAAKABADQABADAEACQAAABABAAQAAABABAAQAAABAAAAQAAABAAAAQABADgFAAg");
	this.shape_12.setTransform(-344.4,-40.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#DD002A").s().p("AgUAYQgJgIAAgOQAAgNAJgKQAKgLANAAQAKAAAIAHQAJAHAAALQAAAFgDABQgCABgFAAIgdAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAABIAAABQABAFADAEQAFAJALAAQAFAAAGgCIAEgDQABAAABAAQAAABABAAQAAAAAAABQABAAAAABQAAAEgIAFQgJAGgKAAQgNAAgJgJgAgFgTQgEADgBAGIAAABQAAAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIANAAQAIAAAAgFQAAgEgDgDQgDgDgEAAQgEAAgDAEg");
	this.shape_13.setTransform(-353.8,-40.625);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#DD002A").s().p("AAUArQgFAAAAgDQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQADgCABgDQACgDAAgKIAAgrIgBgBIgBABIgUAzQgBABAAAAQgBABAAAAQAAAAAAABQgBAAAAAAIgFAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgXg0IAAAAIgBABIABAvQAAAKAHADIADACQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAAAQAAAEgEAAIgWAAQgFAAAAgDQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIADgDQAEgEAAgPIABgsIgBgDIgCgDIgEgBQAAgBAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBQgBgDAGAAIAXAAQAEAAACADIAQAnIAAABIABgBIARgnQAAgBAAAAQABgBAAAAQABAAAAgBQABAAAAAAIAbAAQAAAAABAAQABABAAAAQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDACQgDACAAAHIAAAsQAAAKABADQABADADACQABABABAAQAAAAABABQAAAAAAABQABAAAAABQgBADgEAAg");
	this.shape_14.setTransform(-362.5,-41.775);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("AgSAYQgDgDAAgIQAAgEAEAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAIAEAEQAGAIAFAAQAFAAADgCQACgCAAgDQAAgFgGgCIgJgDQgHgDgDgCQgEgEAAgGQAAgJAJgFQAGgEAGAAQAJAAAFADQADADAAAGQAAAHgDgBQgBAAAAAAQAAAAgBAAQAAAAgBgBQAAAAgBgBQgFgJgHAAQgCAAgDACQgCACAAADQAAAFAHACIAKADQAGACACADQAEAEAAAGQAAAIgIAGQgGAEgIAAQgMAAgGgFg");
	this.shape_15.setTransform(-248.45,-9.35);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AgJAcQgCgFAAgJIABgZIgBgBIgHAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgEQAAgBAAAAQAAAAABAAQAAgBAAAAQAAAAABAAQAHgBADgFIACgHIABgCIAFAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAKIABADIACAAIAMgBQABAAAAAAQABABABAAQAAAAAAAAQABABAAAAIgBADQAAAEgFAAIgMgBIgBABIAAAMQAAAPACAEQACAFAFAAIAFgBIAEgCQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIgBADQgDADgEADQgEACgFAAQgJAAgEgHg");
	this.shape_16.setTransform(-252.675,-9.925);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("AgJAoQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABgBQADgBAAgDQACgCAAgJIAAgQIgBgHIgEgDQgBgBAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAKgDIAEgCQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAAgQAAAJABACIAEAEIACADQAAAAAAABQgBAAAAABQgBAAAAAAQgBAAgBAAgAgEgZQgEgDAAgCQAAgCAEgEQADgDABAAQACAAAEADQADAEAAACQAAACgDADQgEAEgCAAQgBAAgDgEg");
	this.shape_17.setTransform(-256.025,-10.575);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AAVAoQgFAAgDgCQgCgBgHgLQgFgLgDAAIgCACIgEADIAAABQAAAHABADQABACADACQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAgBABQgBAAgBAAIgUAAQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIACgCIAEgEIABgMIAAglIgBgIQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAABAAIAMgEIADgBQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAAAuIAAAAIAKgJQAGgGAAgDIgCgCIgBgCQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAVAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIgCACIgDABQgHADgOANIgBAAIABABIACgBQACAAADADIAGAKQAIAMAEACQABABAAAAQABABAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_18.setTransform(-260.975,-10.525);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("AgMAZQgHgEgDgIQgCgFAAgGQAAgHADgIQAFgHAHgEQAGgEAGAAQAIAAAHAGQAHAGAAAJQAAAEgBABQgCACgFAAIgbAAIgBABQAAAHAEAEQAFAIAIAAQAGgBAFgCIAFgDQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAAEgHAEQgHAFgJAAQgHAAgGgEgAgIgPQgDAEAAAEQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAAAIAOAAQAIAAAAgGQAAgDgDgDQgDgDgFAAQgFAAgEAGg");
	this.shape_19.setTransform(-269.025,-9.35);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AgSAYQgDgDAAgIQAAgEAEAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAIADAEQAHAIAFAAQAFAAADgCQACgCAAgDQAAgFgGgCIgJgDQgGgDgEgCQgEgEAAgGQAAgJAJgFQAGgEAHAAQAIAAAEADQAFADAAAGQgBAHgDgBQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBQgFgJgGAAQgEAAgCACQgCACAAADQAAAFAHACIAKADQAGACADADQADAEAAAGQAAAIgIAGQgGAEgIAAQgMAAgGgFg");
	this.shape_20.setTransform(-274.75,-9.35);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AAIAVIAAAAQgHAIgKAAQgHAAgEgEQgGgEAAgGQAAgHAIgFQAFgDAMgEQAIgEAAgGQgBgFgFgCIgBAAQgFAAgDADIgEAEIgDAEQAAAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQgDgBAAgFQAAgGACgCQACgDAGgBQAFgCAGAAQAIAAAHAFQAFAGAAAHIAAAWQAAAJADAAIACAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAADQgDAEgHAAQgHAAgCgIgAAGAAIgGACIgHAEQgFADABAFQAAADACACQACACADAAQAFAAAEgHQABgDABgKIAAgBIAAgBIgBABg");
	this.shape_21.setTransform(-280.3,-9.35);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AgKAlIgDgCQgBAAAAAAQgBABAAAAQAAAAgBABQAAAAgBABQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIAAg3IgBgIQAAAAgBgBQAAAAAAAAQgBgBAAAAQgBgBgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIANgEIADAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAcIAAABIABgBQAHgJAJAAQALAAAGAIQAGAIAAAKQAAAJgFAHQgHAPgQAAQgHAAgGgDgAgFgCQgEAEAAAKQAAALAEAFQAEAGAFAAQAGAAAEgGQADgGAAgJQAAgJgDgFQgFgGgGAAQgEAAgEAFg");
	this.shape_22.setTransform(-286.4,-10.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AgWAhQgEgDAAgEQAAgBAAAAQAAgBAAgBQAAAAAAgBQABAAAAgBQACgFAGAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAIgBACIAAADQAAAEADADQAFACAHAAQAHAAAFgCQADgCAAgDQABgFgIAAIgQgBQgGgBgDgDQgDgCAAgEQAAgGAIgDIAAAAQgLgFAAgMQAAgJAHgFQAGgGAJgBQAGAAAHAEIADACQABAAAAAAQABgBAAAAQAAAAABgBQAAAAABgBQAAgBAAAAQABgBAAAAQABAAAAgBQABAAAAAAQAFAAABAFQgBAGgGAAIgCAAQACAEABAFQgBAJgGAGQgGAEgJABIgEAAQgFAAABADQgBADAHAAIAHABIAJAAQAGABADADQADADABAFIgBAEQgEAOgXAAQgOAAgHgGgAgHgcQgCAEgBAEQABAIADAEQADAEADAAQADAAACgDQADgEAAgFQAAgGgDgEQgDgFgDAAQgEAAgCADg");
	this.shape_23.setTransform(-295.55,-8.375);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B3927").s().p("AAIAcQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIACgCIAEgFQACgCAAgJIAAgOQAAgFgDgDQgDgDgFAAQgDAAgDADQgEADgBAFIgBAOQABAJABACQABADADACIACACQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgUAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIACgCIADgFQACgCAAgJIAAgPIgBgIQgBgCgDgBQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABgBQABAAAAAAIALgDIAEgBQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAABIAAAGIABABIAAgBQAHgJAKAAQAJAAAGAHQACAFAAAJIAAAOQABAJABACQABADADACQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAg");
	this.shape_24.setTransform(-301.7,-9.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B3927").s().p("AgJAoQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABgBQADgBAAgDQACgCAAgJIAAgQIgBgHIgEgDQAAgBgBAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQABAAAAAAIAKgDIAEgCQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAAgQAAAJABACIAEAEIACADQAAAAAAABQgBAAAAABQgBAAAAAAQgBAAgBAAgAgEgZQgEgDAAgCQAAgCAEgEQADgDABAAQACAAAEADQADAEAAACQAAACgDADQgEAEgCAAQgBAAgDgEg");
	this.shape_25.setTransform(-306.825,-10.575);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B3927").s().p("AgJAoQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABgBQAAAAABAAQACgCABgCQACgDAAgIIAAgnQAAgGgBgBQgBgCgDgBIgDgDQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBABAAIAKgCIAEgCQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAAA4QAAAIABADIADAEIADACQAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_26.setTransform(-310.225,-10.525);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B3927").s().p("AgQAcQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAQADgCABgDQABgCAAgJIAAgPIgBgIQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAABAAIALgEIACAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAAAIQABgEADgEQAFgDAEAAQAFgBACADQABADAAAEQAAAFgDAAIgFgCIgDgBQgDAAgDACQgEAGAAAQQAAAJABACQABADACACIACACQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAgBAAg");
	this.shape_27.setTransform(-313.9,-9.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B3927").s().p("AgMAZQgHgEgDgIQgCgFAAgGQAAgHADgIQAFgHAHgEQAGgEAGAAQAIAAAHAGQAHAGAAAJQAAAEgBABQgCACgFAAIgbAAIgBABQAAAHAEAEQAFAIAIAAQAGgBAFgCIAFgDQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAAEgHAEQgHAFgJAAQgHAAgGgEgAgIgPQgDAEAAAEQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAAAIAOAAQAIAAAAgGQAAgDgDgDQgDgDgFAAQgFAAgEAGg");
	this.shape_28.setTransform(-319.425,-9.35);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B3927").s().p("AgJAcQgCgFAAgJIABgZIgBgBIgHAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgEQAAgBAAAAQAAAAABAAQAAgBAAAAQAAAAABAAQAHgBADgFIACgHIABgCIAFAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAKIABADIACAAIAMgBQABAAABAAQAAABABAAQAAAAAAAAQABABAAAAIgBADQAAAEgFAAIgMgBIgBABIAAAMQAAAPACAEQACAFAFAAIAFgBIAEgCQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIgBADQgDADgEADQgEACgFAAQgJAAgEgHg");
	this.shape_29.setTransform(-323.975,-9.925);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B3927").s().p("AgQAlQgGgCgDgEIgCgJIAAgEQAAgEADAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAABABIAFAHQAIAJAHAAQAHAAADgEQAFgDAAgFQgBgHgFgDIgKgFIgMgFQgLgEAAgLQAAgIAGgHQAFgGAJgBIAGgBQAOAAAGAGQACACABAIQgBAHgDAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBgBAAAAIgDgEIgFgFQgFgFgFAAQgEAAgEADQgDADAAAEQAAAHAIAEIANAFQAIADAFADQAFAGAAAIQAAAFgCAEQgIAPgTAAQgJAAgGgCg");
	this.shape_30.setTransform(-329.7,-10.375);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B3927").s().p("AgaAcQgIgHAAgKQAAgFADgFQAEgEAGgCQgCgFAAgFQAAgIAGgFQAGgFAIAAQAIAAAEAFQACABAAAGQAAAHgEAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBgBIgBgDIgCgEQgCgDgEAAQgDAAgCACQgCADAAAEQAAAEAEAFIAMAIIAOAKIAAAAQACgDAAgFQAAgEgGgEQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIASAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAABIgCADQgEACgBADQgDAJgCAFIAAAAIAAABIAEADQAFAGAAAIQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgIAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAQgBgEgDgDIAAAAIgBAAQgIAJgOAAQgLAAgIgGgAgSAAQgDADAAAFQAAAHAGAGQAFAFAIAAQAHABAFgGIAAAAIAAgBIgNgKQgKgGgEgEIgBAAIAAAAg");
	this.shape_31.setTransform(-338.925,-9.85);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B3927").s().p("AgQAcQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQADgCABgDQABgCAAgJIAAgPQAAgGgBgCQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAABAAIALgEIACAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAAIQACgEADgEQAFgDAEAAQAEgBADADQABADAAAEQAAAFgDAAIgFgCIgDgBQgDAAgDACQgEAGAAAQQAAAJABACQAAADADACIACACQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAgBAAg");
	this.shape_32.setTransform(-346.85,-9.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B3927").s().p("AgMAZQgHgEgDgIQgCgFAAgGQAAgHADgIQAFgHAHgEQAGgEAGAAQAIAAAHAGQAHAGAAAJQAAAEgBABQgCACgFAAIgbAAIgBABQAAAHAEAEQAFAIAIAAQAGgBAFgCIAFgDQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAAEgHAEQgHAFgJAAQgHAAgGgEgAgIgPQgDAEAAAEQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAAAIAOAAQAIAAAAgGQAAgDgDgDQgDgDgFAAQgFAAgEAGg");
	this.shape_33.setTransform(-352.375,-9.35);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B3927").s().p("AAVAoQgFAAgDgCQgCgBgHgLQgFgLgDAAIgCACIgEADIAAABQAAAHABADQABACADACQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAgBABQgBAAgBAAIgUAAQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIACgCIAEgEIABgMIAAglIgBgIQAAgBAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAABAAIAMgEIADgBQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAAAuIAAAAIAKgJQAGgGAAgDIgCgCIgBgCQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAVAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIgCACIgDABQgHADgOANIgBAAIABABIACgBQACAAADADIAGAKQAIAMAEACQABABAAAAQABABAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_34.setTransform(-358.025,-10.525);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B3927").s().p("AAIAVIgBAAQgFAIgLAAQgHAAgEgEQgGgEAAgGQAAgHAHgFQAGgDAMgEQAHgEAAgGQAAgFgFgCIgCAAQgEAAgEADIgDAEIgCAEQgBAAAAABQgBAAAAAAQgBAAAAAAQAAABgBAAQgDgBAAgFQAAgGABgCQACgDAHgBQAFgCAFAAQAKAAAGAFQAFAGABAHIgBAWQAAAJADAAIACAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIgBADQgDAEgGAAQgIAAgBgIgAAGAAIgGACIgHAEQgEADgBAFQAAADACACQACACAEAAQAGAAADgHQACgDgBgKIAAgBIAAgBIAAABg");
	this.shape_35.setTransform(-364.6,-9.35);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B3927").s().p("AgbAmQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABAAQACgBABgDIACgLIAAgoIgBgGQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAIgCgCIgBgCQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIAZAAIANAAQAHABAEAEQAGAFAAAHQAAAFgCADQgFAIgJABIgCABIABAAQAJABAFAEQAHAFAAAIQgBAHgDAEQgIALgXAAgAgKADIAAARQAAAIABACQABABAHAAQARgBAAgPQAAgOgSAAIgGAAQAAAAgBAAQAAAAAAAAQAAABAAAAQgBAAAAABgAgJgdIAAAXQAAAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIAGAAQAPAAAAgNIAAgBQAAgLgPAAIgGAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAg");
	this.shape_36.setTransform(-371,-10.35);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B3927").s().p("AgMAZQgHgEgDgIQgCgFAAgGQAAgIADgGQAFgJAHgDQAGgEAGAAQAIAAAHAGQAHAGAAAJQAAAEgBABQgCACgFAAIgbAAIgBAAQAAAHAEAGQAFAGAIABQAGAAAFgDIAFgDQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAAEgHAEQgHAFgJAAQgHAAgGgEgAgIgPQgDAEAAADQAAABAAAAQAAAAABABQAAAAAAAAQAAAAAAAAIAOAAQAIAAAAgFQAAgEgDgDQgDgDgFAAQgFAAgEAGg");
	this.shape_37.setTransform(-254.975,-22.15);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B3927").s().p("AAIAoQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIADgCIADgEQACgDAAgIIAAgPQAAgLgKAAQgEAAgDADQgDADgBAEIgBAQQAAAIABADIAEAEIACACQAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAIgUAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIACgCIAEgEQABgDAAgIIAAgnQAAgGgBgBQgBgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAAAAAgBQABAAAAgBQAAAAABAAQABgBAAAAQAHgBAGgCIACgBQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAIAAAdIAAABIAAgBQAHgJAKAAQAKAAAEAHQAEAFAAAJIAAAPQAAAIABADIAEAEIACACQAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_38.setTransform(-261.225,-23.325);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B3927").s().p("AgJAcQgCgFAAgJIABgZIgBgBIgHAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAgEQAAgBAAAAQAAAAABAAQAAgBAAAAQAAAAABAAQAHgBADgFIACgHIABgCIAFAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAKIABADIACAAIAMgBQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAIgBADQAAAEgFAAIgMgBIgBABIAAAMQAAAPACAEQACAFAFAAIAFgBIAEgCQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIgBADQgDADgEADQgEACgFAAQgJAAgEgHg");
	this.shape_39.setTransform(-266.425,-22.725);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B3927").s().p("AAIAcQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIACgDIAEgDQABgDABgIIAAgPQgBgFgCgDQgDgDgEAAQgFAAgCADQgDADgCAFIgBAPQAAAIACADQABACADABIABADQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgUAAQgBAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIACgDIAFgDQABgDAAgIIAAgQIgBgIQgBgCgDgBQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABgBQABAAAAAAIALgDIAEgBQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAABIAAAGIABABIAAgBQAHgJAKAAQAKgBAEAIQADAFAAAJIAAAPQAAAIACADQABACADABQAAABABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAgBAAQgBAAgBAAg");
	this.shape_40.setTransform(-273.95,-22.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B3927").s().p("AgUAWQgHgJAAgNQAAgKAIgJQAIgIALgBQANAAAIAIQAHAJAAALQAAAMgIAJQgIAIgMAAQgLAAgJgHgAgKgRQgDAGAAAIQAAAKAEAHQAEAJAGAAQAHgBADgFQADgGAAgHQAAgKgDgHQgFgIgGAAQgGAAgEAEg");
	this.shape_41.setTransform(-280.25,-22.15);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B3927").s().p("AAPA3QgIgJAAgPQAAgOAJgKQAJgJANABQAOgBAJAJQAJAKAAAOQgBAQgIAKQgJAJgOAAQgOAAgJgLgAAcAfQABAKACAHQADAGAEABQAKAAAAgYQAAgWgKAAQgKAAAAAWgAgtBAIBMh/IAPAAIhNB/gAg9gHQgHgJgBgPQABgPAIgJQAKgKANAAQAOAAAIAKQAKAJgBAPQAAAQgJAJQgJAJgNgBQgPAAgJgJgAgvgfQAAAKADAGQACAIAFAAQAJAAABgYQgBgXgJAAQgKAAAAAXg");
	this.shape_42.setTransform(-294.35,-25.8);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B3927").s().p("AgYBCQgKgDgEgGQgEgGAAgRQAAgIAIAAQAEAAADAFIAGAKQAJAPAOAAQAJAAAGgGQAHgGAAgJQAAgMgMgIQgPgLgdAAIgEAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgCIAMg5QAAAAAAgBQAAgBABAAQAAAAABgBQABAAAAAAIAZAAQAPAAAEgBQAEgBADgDQADgDADAAQAEAAAAAEIgBAKIgCALQgBAEgCACQgDACgKAAIgjAAQAAAAgBAAQAAAAAAABQAAAAgBAAQAAABAAAAIgCALIAAABQAAAAAAABQAAAAAAAAQABAAAAABQABAAAAAAQAeAAARAOQAOALAAATQAAATgOANQgOAMgUAAQgKAAgJgDg");
	this.shape_43.setTransform(-307.225,-26.125);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B3927").s().p("AADBBQgEAAAAgFIAAhXQAAgKgBgDQgBgDgGABIgNAAQgFAAAAgJQAAgDAEgCIAQgCIAPgDIAOgDQAGAAAAAGIAAB2QAAAFgFAAg");
	this.shape_44.setTransform(-319.275,-25.9);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B3927").s().p("AgeAkQgNgNAAgUQAAgUANgPQAOgQATAAQAQAAAMAKQANALAAAQQAAAHgEADQgDABgIAAIgrAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAADQAAAHAFAGQAIANAQAAQAJAAAHgDIAIgEQAEAAAAAEQAAAGgLAHQgNAJgRAAQgSAAgNgNgAgJgdQgFAFgBAIIAAACQAAAAAAABQAAAAAAAAQAAABAAAAQABAAAAAAIAUAAQAMAAAAgIQAAgGgFgEQgEgEgGAAQgGAAgGAFg");
	this.shape_45.setTransform(-332.25,-24.075);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B3927").s().p("AgKAvQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgbhBQgEgKgEgDIgGgEQgDgCAAgCQAAgFAHAAIAnAAQAGAAABAEQgBADgEACQgFADABAEIABAGIAQAqIABABIABgBIAMgbQAEgLAAgGQAAgGgFgEQgEgDAAgCQAAgFAHAAIAdAAQAHAAAAAFQAAAAAAABQAAAAgBABQAAAAAAABQgBAAgBABQgGAFgEAGQgEAFgGAOIgZA0QAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_46.setTransform(-341.75,-24.025);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B3927").s().p("AALAjIgBgBIgBABQgJAOgTAAQgLAAgIgGQgJgHAAgLQAAgOANgIQAJgEAUgHQANgGAAgJQAAgLgLAAQgGAAgFADQgEADgGAIQgEAGgEAAQgEAAgCgCQgCgDAAgGQAAgJAEgEQADgFAMgDQAJgCAKAAQAPAAALAHQANAIAAAQIgBAhQAAAKABACQABAEAGABQAEAAAAAEQAAADgEAEQgGAFgJAAQgPAAgDgOgAAGAAQgLAFgGAFQgHAFAAAGQAAAFADADQADADAFAAQAIAAAEgJQADgFAAgQIAAgCIgBAAg");
	this.shape_47.setTransform(-352.275,-24.075);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B3927").s().p("AgdA+QgLgEgFgGQgDgGgBgKIAAgHQABgJAGAAQAEABADAEIAKAMQANAOANAAQAKAAAEgEQAHgGgBgHQABgKgLgGIgWgJQgPgHgHgFQgLgIABgOQAAgRANgLQAOgMAUAAQAZAAAKAKQAFAEAAAOQgBAMgGAAQgEAAgDgDIgHgJQgMgOgLAAQgGABgFADQgFAEAAAHQAAAJALAGIAVAJQAQAFAHAHQAKAJAAAPQABASgPAMQgQAMgWAAQgOAAgMgEg");
	this.shape_48.setTransform(-363.85,-25.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},21).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},18).to({state:[]},1).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},6).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},134).to({state:[]},1).wait(65));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-397.5,-48.7,174.8,48.800000000000004);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.PBB_logo1();
	this.instance.setTransform(-44,-35,0.1803,0.1805);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44,-35,44,35);


(lib.IM2_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM2();
	this.instance.setTransform(-163,-144);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-163,-144,320,50);


(lib.IM1_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM1();
	this.instance.setTransform(-155,-144);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-155,-144,320,50);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAMAjIgBgBIgLgqIAAAAIgJAqQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgLAAIgBgBIgRhCIAAgBIAAgBIANAAIABABIAKAnIAAABIABgBIAJgnIABgBIALAAIABABIALAnIAAABIAAgBIAJgnIACgBIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIgQBCIgCABg");
	this.shape.setTransform(60.4,14.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNAhQgFgDgEgGQgDgGgBgHIAAgVQABgHADgGQAEgGAFgCQAGgEAHAAQAIAAAGAEQAGACADAGQADAGAAAHIAAAVQAAAHgDAGQgDAGgGADQgGADgIAAQgHAAgGgDgAgIgTQgDADAAAGIAAAVQAAAGADAEQADADAFAAQAFAAAEgDQAEgEAAgGIAAgVQAAgGgEgDQgEgDgFgBQgFABgDADg");
	this.shape_1.setTransform(51.9,14.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAPAjIgCgBIgZgpIAAgBIAAABIAAApIAAAAIgBABIgMAAIgBgBIAAAAIAAhDIAAAAIABgBIALAAIACABIAZAqIAAgBIAAgpIAAAAIABgBIAMAAIABABIAAAAIAABDIAAAAIgBABg");
	this.shape_2.setTransform(44.475,14.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXAjIgBgBIgBAAIAAhDIABAAIABgBIAbAAQAGAAAFADQAFACADAFQADAFAAAGQAAAHgDAEQgDAEgFADQgFADgHAAIgNAAIgBABIAAAZIAAAAIgBABgAgLgWIAAATIABAAIAMAAQAEABADgDQADgDAAgEQAAgFgDgCQgDgDgEAAIgMAAIgBAAg");
	this.shape_3.setTransform(34.325,14.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNAhQgGgDgDgGQgEgGABgHIAAgVQgBgHAEgGQADgGAGgCQAGgEAHAAQAIAAAGAEQAGACADAGQAEAGAAAHIAAAVQAAAHgEAGQgDAGgGADQgGADgIAAQgHAAgGgDgAgIgTQgDADAAAGIAAAVQAAAGADAEQAEADAEAAQAGAAADgDQADgEABgGIAAgVQgBgGgDgDQgDgDgGgBQgEABgEADg");
	this.shape_4.setTransform(27.1,14.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AANAjIgBgBIAAAAIAAgcIgBgBIgVAAIgBABIAAAcIAAAAIgBABIgLAAIgBgBIgBAAIAAhDIABAAIABgBIALAAIABABIAAAAIAAAbIABABIAVAAIABgBIAAgbIAAAAIABgBIALAAIABABIABAAIAABDIgBAAIgBABg");
	this.shape_5.setTransform(19.925,14.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMAhQgHgCgCgFQgEgFAAgGIAAgCIAAgBIABAAIAMAAIABAAIAAABIAAABQAAAEADADQAFADAEgBQAGAAACgBQADgDAAgDQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgBgCgDgBIgHgEIgMgEQgEgBgDgFQgEgEAAgGQAAgGADgEQADgFAGgCQAGgDAGAAQAHAAAGADQAGADAEAFQACAFABAGIAAABIAAABIgBAAIgMAAIgBAAIAAgBIAAgBQAAgEgEgDQgDgCgFgBQgFABgDABQgCACAAAEQAAABAAAAQAAABAAAAQABABAAAAQAAABAAAAIAFADIAJAEIALAEQADACAEADQADAEAAAGQAAAKgHAGQgGAFgNAAQgGAAgGgDg");
	this.shape_6.setTransform(12.75,14.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer_1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#DD002A").s().p("Ak7BrQgOAAAAgSIAAiyQAAgRAOAAIJ2AAQAPAAAAARIAACyQAAASgPAAg");
	this.shape_7.setTransform(37.7,13.575);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.7,2.9,66,21.400000000000002);


(lib.circle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003595").s().p("AmdGeQirisAAjyQAAjyCrirQCsirDxAAQDzAACqCrQCsCrAADyQAADyisCsQiqCrjzAAQjxAAisirg");
	this.shape.setTransform(0,-0.0156,1,0.7692);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.5,-45,117,90);


// stage content:
(lib.RECOVER_WFSB_215325_MM_320x50_V2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [190];
	// timeline functions:
	this.frame_190 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(190).call(this.frame_190).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(191));

	// CTA
	this.instance = new lib.CTA();
	this.instance.setTransform(253.85,-12.65,0.9025,0.9025,0,0,0,89.6,21.2);
	this.instance.alpha = 0;
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.CTA(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(148).to({_off:false},0).to({regX:89.5,x:250.15,y:32.4,alpha:1},11,cjs.Ease.get(1)).wait(32));

	// T2
	this.instance_1 = new lib.T2("synched",0);
	this.instance_1.setTransform(462.25,50.65);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(133).to({_off:false},0).to({alpha:1},14,cjs.Ease.get(1)).wait(44));

	// T1
	this.instance_2 = new lib.T1("synched",21);
	this.instance_2.setTransform(460.25,141);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(21).to({_off:false},0).to({y:51,alpha:1,startPosition:46},19,cjs.Ease.get(1)).wait(79).to({startPosition:95},0).to({alpha:0,startPosition:123},14,cjs.Ease.get(1)).wait(58));

	// Logo
	this.instance_3 = new lib.Symbol1("synched",0);
	this.instance_3.setTransform(-37,42.55);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:63,alpha:1},22,cjs.Ease.get(1)).wait(169));

	// Layer_6 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AMXE+QiriDAAi7QAAi6CriDQCsiEDyAAQDzAACrCEQCrCDAAC6QAAC7irCDQirCEjzAAQjyAAisiEg");
	mask.setTransform(179.025,18.0344);

	// IM2_jpg
	this.instance_4 = new lib.IM2_jpg("synched",0);
	this.instance_4.setTransform(169,143.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(119).to({_off:false},0).to({alpha:1},28).wait(44));

	// IM1_jpg
	this.instance_5 = new lib.IM1_jpg("synched",0);
	this.instance_5.setTransform(178,144);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(21).to({_off:false},0).to({alpha:1},19).wait(151));

	// Layer_7
	this.instance_6 = new lib.circle("synched",0);
	this.instance_6.setTransform(296.05,16.05);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(21).to({_off:false},0).to({alpha:1},19).wait(151));

	// BG_png
	this.instance_7 = new lib.BG();

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(191));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(79,-4.2,275.6,142);
// library properties:
lib.properties = {
	id: '75E153FF2D744F028C65A7813D4CAE23',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"IM1.jpg", id:"IM1"},
		{src:"IM2.jpg", id:"IM2"},
		{src:"PBB_logo1.png", id:"PBB_logo1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['75E153FF2D744F028C65A7813D4CAE23'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;