(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_05 = function() {
	this.initialize(img.Img_05);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAOAeIgCgBIgBgBIAAglQAAgEgCgDQgCgCgFAAIgDABIgFACIgFAEIAAAnQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAgBAAIgJAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAg2QAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIAMAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAGIAAABIABgBIAHgEIAEgEIAIgBQAIAAAEAFQAFAFAAAHIAAAnQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAg");
	this.shape.setTransform(41,12.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAOAdQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBgBIgKghIgBgBIAAABIgKAiIgBABIgCAAIgIAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgSg1IAAgBIACgBIAKAAIACAAIABACIALAiIAAABIABgBIALgjIABgBIABAAIAHAAIABAAIABACIALAiIAAABIABgBIALgjIABgBIABAAIAHAAIACABIAAABIgSA2IgBABIgBAAg");
	this.shape_1.setTransform(33.6625,13.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgOAbQgGgEgFgHQgDgHAAgJQAAgIADgHQAFgGAGgEQAGgEAIAAQAIAAAHAEQAHAEAEAHQADAGAAAIQAAAJgEAHQgDAHgHAEQgHADgIAAQgIAAgGgDgAgHgRQgDACgCAFQgBAEAAAGQAAAHABAEQACAFADACQADADAEAAQAEAAAEgDQADgCACgFQABgEABgHQAAgGgCgEQgCgFgDgCQgEgDgEAAQgEAAgDADg");
	this.shape_2.setTransform(25.8,13.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeApQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAhMIABgBIACgBIAFAAIAGAAIAGAAIAFAAQAOABAJAEQAKAFAEAJQAFAJAAAMQAAAMgFAKQgFAJgKAFQgJAFgOAAgAgQgbIAAA3QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIADAAQAKAAAGgDQAGgDADgGQAEgHAAgKQAAgKgDgGQgEgGgGgDQgFgDgKAAIgEAAQgBAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAg");
	this.shape_3.setTransform(18.225,11.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXAmIgBgBIAAgIIAAgBIACAAIAIAAIAEgBIADgDIACgEIgBgEIgVgzIAAgBIACgBIALAAIABAAIABACIANAjIABABIABgBIANgkIABgBIACAAIAIAAIABABIAAABIgYA5IgDAIIgFAFQgDACgDABIgIAAg");
	this.shape_4.setTransform(7.3,13.925);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgEgHQgDgGAAgJQAAgJAEgHQAEgHAGgDQAHgEAHAAQAIAAAGADQAGAEAEAHQADAHAAAIIAAACIgBABIgmAAIgBAAIAAACQAAAEACAEQACADADACQAEACAEAAQAEAAAEgCQADgBAEgFIAAAAIACAAIAGADQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAIgHAIQgEADgFABIgKABQgHAAgHgDgAgGgSQgDACgCAEQgBADAAAFIAZAAIABgBIAAgBIgBgHQgCgDgDgCQgDgCgEAAQgDAAgEACg");
	this.shape_5.setTransform(0.775,13.025);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AANAeIgBgBIAAgBIAAglQgBgEgCgDQgCgCgEAAIgFABIgEACIgFAEIAAAnQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAIgKAAQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAg2QAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAGIAAABIABgBIAGgEIAGgEIAGgBQAJAAAEAFQAFAFAAAHIAAAnQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_6.setTransform(-5.85,12.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOAbQgGgEgFgHQgDgHAAgJQAAgIADgHQAFgGAGgEQAGgEAIAAQAIAAAHAEQAHAEAEAHQADAGAAAIQAAAJgEAHQgDAHgHAEQgHADgIAAQgIAAgGgDgAgHgRQgDACgCAFQgCAEAAAGQAAAHACAEQACAFADACQADADAEAAQAEAAAEgDQADgCACgFQACgEAAgHQAAgGgDgEQgBgFgDgCQgEgDgEAAQgEAAgDADg");
	this.shape_7.setTransform(-12.55,13.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAdApIgCgBIAAgBIAAg5IgBAAIAAAAIgVA5QAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgHAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgUg4IgBgBIAAABIAAA4IgBABIgBABIgJAAQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBAAAAIAAhNQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIATAAIABAAIABACIATAzIAAAAIABgBIATgyQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAIATAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAABMQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_8.setTransform(-20.475,11.875);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgOAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAHgEAHAAQAIAAAHAEQAGAEAFAHQADAGAAAIQAAAJgEAHQgEAHgGAEQgHADgIAAQgHAAgHgDgAgHgRQgDACgCAFQgBAEgBAGQABAHABAEQACAFADACQAEADADAAQAFAAADgDQADgCACgFQABgEAAgHQAAgGgCgEQgBgFgDgCQgDgDgFAAQgDAAgEADg");
	this.shape_9.setTransform(-32.65,13.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAWApIgBAAIgBgBIglg1IgBAAIAAAAIAAA0QAAAAAAABQAAAAgBAAQAAAAAAABQAAAAgBAAIgKAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAhNQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIALAAIACAAIABACIAiAyIACAAIAAgBIAAgxQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIALAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABNIgBABIgBABg");
	this.shape_10.setTransform(-40.3,11.875);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgGAQIgBAAIAAgCIAFgMQABAAAAgBQAAAAAAgBQgBAAAAAAQAAAAgBAAIgCAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgNQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAMIAAACIgJAPIgBABIgCAAg");
	this.shape_11.setTransform(69.725,2.975);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAFAnQgFAAgEgDQgEgEgBgHIAAggQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgIAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgHQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAIAAIABgBIACgRQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAARIABABIANAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAHQAAAAAAABQAAAAgBAAQAAAAAAAAQgBABAAAAIgMAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAcQAAAFABABQACACAEAAIAHAAIABAAIAAABIAAAGQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgEAAIgEABg");
	this.shape_12.setTransform(67.05,-0.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgPAbQgHgEgDgFIAAgBIABgBIAGgDIACgBIABABIADAEQACACAEABIAGABIAGgBIAFgCQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBgBQAAAAAAAAQgBgBAAAAIgHgDIgKgDQgJgCgDgDQgEgEAAgGQAAgFACgEQADgEAGgDQAFgCAHAAQAIAAAGADQAGADACAEIABABQAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAIgGADIgCAAIgBgBIgFgEQgEgCgFAAQgDAAgDACQgEACAAADIACADQABACAFABIAMADQAIADAEADQAEAEAAAGQAAAGgEAEQgDAEgGACQgFACgIAAQgIAAgHgDg");
	this.shape_13.setTransform(61.525,0.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgEgHQgDgGAAgJQAAgJAEgHQAEgHAGgDQAHgEAHAAQAIAAAGADQAGAEAEAHQADAHAAAIIAAACIgBABIgmAAIgBAAIAAACQAAAEACAEQACADADACQAEACAEAAQAEAAAEgCQADgBAEgFIAAAAIACAAIAGADQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAIgHAIQgEADgFABIgKABQgHAAgHgDgAgGgSQgDACgCAEQgBADAAAFIAZAAIABgBIAAgBIgBgHQgCgDgDgCQgDgCgEAAQgDAAgEACg");
	this.shape_14.setTransform(55.225,0.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgPAeIgBgBIgBgBIAAg2QAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAABAAIAKAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAHIAAABIABgBIAFgFIAFgDIAGgCQABAAABAAQAAABABAAQAAAAABAAQAAABAAAAIAAALQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAIgEgBIgDAAIgFABQgCABgCACIgCADQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAhQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_15.setTransform(50.225,-0.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgEgHQgDgGAAgJQAAgJAEgHQAEgHAGgDQAHgEAHAAQAIAAAGADQAGAEAEAHQADAHAAAIIAAACIgBABIgmAAIgBAAIAAACQAAAEACAEQACADADACQAEACAEAAQAEAAAEgCQADgBAEgFIAAAAIACAAIAGADQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAIgHAIQgEADgFABIgKABQgHAAgHgDgAgGgSQgDACgCAEQgBADAAAFIAZAAIABgBIAAgBIgBgHQgCgDgDgCQgDgCgEAAQgDAAgEACg");
	this.shape_16.setTransform(44.275,0.025);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAGAnQgGAAgFgDQgDgEAAgHIAAggQgBAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgIAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgHQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAJAAIABgBIABgRQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAJAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAARIABABIAMAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAHQAAAAAAABQAAAAAAAAQgBAAAAAAQAAABgBAAIgMAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAcQAAAFACABQABACAEAAIAGAAIABAAIABABIAAAGQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIgEAAIgFABg");
	this.shape_17.setTransform(39.65,-0.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAOAeIgCgBIAAgBIAAglQAAgEgDgDQgCgCgEAAIgFABIgEACIgFAEIAAAnQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgKAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAg2QAAAAAAgBQAAAAAAAAQABAAAAgBQAAAAABAAIALAAQAAAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAAGIAAABIABgBIAHgEIAEgEIAHgBQAJAAAEAFQAFAFAAAHIAAAnQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAg");
	this.shape_18.setTransform(34,-0.025);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgFApIgCgBIAAgBIAAhNQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAMAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABMIAAACIgCABg");
	this.shape_19.setTransform(28.725,-1.125);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgOAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAHgEAHAAQAIAAAHAEQAGAEAFAHQADAGAAAIQAAAJgEAHQgEAHgGAEQgHADgIAAQgHAAgHgDgAgHgRQgDACgCAFQgBAEgBAGQABAHABAEQACAFADACQAEADADAAQAFAAADgDQADgCACgFQABgEAAgHQAAgGgCgEQgBgFgDgCQgDgDgFAAQgDAAgEADg");
	this.shape_20.setTransform(20,0.025);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAWApIgBAAIgBgBIglg1IgBAAIAAAAIAAA0QAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAhNQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIALAAIACAAIABACIAiAyIACAAIAAgBIAAgxQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIALAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABNIgBABIgBABg");
	this.shape_21.setTransform(12.35,-1.125);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGAQIgBAAIAAgCIAFgMQAAAAABgBQAAAAgBgBQAAAAAAAAQAAAAgBAAIgCAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAgBAAAAIAAgNQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAMIAAACIgJAPIgBABIgCAAg");
	this.shape_22.setTransform(2.175,2.975);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgPAbQgHgEgDgFIAAgBIABgBIAGgDIACgBIABABIADAEQACACAEABIAGABIAGgBIAFgCQAAgBABAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBgBQAAAAAAAAQgBgBAAAAIgHgDIgKgDQgJgCgDgDQgEgEAAgGQAAgFACgEQADgEAGgDQAFgCAHAAQAIAAAGADQAGADACAEIABABQAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAIgGADIgCAAIgBgBIgFgEQgEgCgFAAQgDAAgDACQgEACAAADIACADQABACAFABIAMADQAIADAEADQAEAEAAAGQAAAGgEAEQgDAEgGACQgFACgIAAQgIAAgHgDg");
	this.shape_23.setTransform(-2.375,0.025);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAFAnQgFAAgEgDQgEgEgBgHIAAggQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgIAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgHQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAIAAIABgBIACgRQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAARIABABIANAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAHQAAAAAAABQAAAAgBAAQAAAAAAAAQgBABAAAAIgMAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABgBAAIAAAcQAAAFACABQACACAEAAIAHAAIABAAIAAABIAAAGQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgEAAIgEABg");
	this.shape_24.setTransform(-7.2,-0.95);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AANAeIgBgBIAAgBIAAglQgBgEgCgDQgCgCgFAAIgEABIgEACIgFAEIAAAnQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgJAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAg2QAAAAAAgBQAAAAAAAAQABAAAAgBQAAAAAAAAIALAAQABAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAAGIAAABIABgBIAGgEIAGgEIAHgBQAHAAAFAFQAFAFAAAHIAAAnQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_25.setTransform(-12.85,-0.025);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgEgHQgDgGAAgJQAAgJAEgHQAEgHAGgDQAHgEAHAAQAIAAAGADQAGAEAEAHQADAHAAAIIAAACIgBABIgmAAIgBAAIAAACQAAAEACAEQACADADACQAEACAEAAQAEAAAEgCQADgBAEgFIAAAAIACAAIAGADQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAIgHAIQgEADgFABIgKABQgHAAgHgDgAgGgSQgDACgCAEQgBADAAAFIAZAAIABgBIAAgBIgBgHQgCgDgDgCQgDgCgEAAQgDAAgEACg");
	this.shape_26.setTransform(-19.625,0.025);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAfAeIgBgBIgBgBIAAglQAAgEgCgDQgCgCgEAAIgFABIgEACIgEADIgBACIAAABIAAAkQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgJAAIgCgBIAAgBIAAglQAAgEgCgDQgCgCgFAAQgEAAgDACIgHAFIAAAnQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgKAAQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAAAIAAg2QAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAABAAIALAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAGIAAABIABgBIAGgEIAGgEIAHgBQAGAAADADQAEADACAEIAAABIABgBIAGgFQADgCAEgBIAHgCQAHAAAFAFQAFAFAAAIIAAAmQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_27.setTransform(-27.525,-0.025);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgXAmIgBgBIAAgIIAAgBIADAAIAHAAIAEgBIADgDIACgEIgBgEIgVgzIAAgBIABgBIAMAAIACAAIAAACIANAjIABABIABgBIANgkIABgBIABAAIAIAAIACABIAAABIgXA5IgFAIIgDAFQgDACgEABIgIAAg");
	this.shape_28.setTransform(-35.65,0.925);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgUAaQgFgFAAgHQAAgGAEgEQADgEAHgCQAHgDAJAAIAGgBIABAAIAAgBIAAgDQAAgFgDgCQgCgDgGAAIgGACQgDACgCADIgBABIgCAAIgJgCIgBgBIABgBQADgHAGgDQAHgDAIAAQAJAAAFACQAFACADAFQACAEAAAFIAAAmIAAACIgCAAIgJAAIgCgBIAAgBIAAgEQAAAAgBgBQAAAAAAAAQAAAAgBAAQAAABgBAAQgDAEgFABQgDACgGAAQgIAAgFgEgAAGABIgGABIgFACIgEAEQgCACAAADQAAADADACQACADAFAAIAFgBIAEgDIADgDIABgEIAAgHQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_29.setTransform(-42.525,0.025);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgdApIgCgBIAAgBIAAhNQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAeAAQAJAAAHADQAHACAEAGQAEAFAAAJQAAAIgEAGQgDAEgHADQgHADgIAAIgRAAIgBABIAAAdQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAgAgPgaIAAAWQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABAAIAOAAQAGAAAEgEQAEgDAAgGQAAgFgBgDQgCgCgEgCQgEgBgEAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABg");
	this.shape_30.setTransform(-49.225,-1.125);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgOAbQgHgEgEgHQgDgHAAgJQAAgIADgHQAEgGAHgEQAHgEAHAAQAJAAAGAEQAGAEAFAHQADAGAAAIQAAAJgEAHQgDAHgHAEQgGADgJAAQgHAAgHgDgAgHgRQgDACgCAFQgCAEAAAGQAAAHACAEQACAFADACQAEADADAAQAFAAADgDQADgCACgFQACgEAAgHQgBgGgCgEQgBgFgDgCQgDgDgFAAQgDAAgEADg");
	this.shape_31.setTransform(-60.35,0.025);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAWApIgBAAIgCgBIgkg1IgBAAIAAAAIAAA0QAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgKAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAhNQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIALAAIACAAIABACIAiAyIABAAIABgBIAAgxQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIALAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABNIAAABIgCABg");
	this.shape_32.setTransform(-68,-1.125);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgFApQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgtIgBgBIgJAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAgHIABgBIABgBIAIAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAgBAAAAIAAgHQAAgHAEgEQADgEAHAAIAKAAQABAAAAAAQABABAAAAQAAAAAAAAQABABAAAAIAAAGIgBABIgBABIgGAAQgBAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBACgBADIAAAFQABAAAAABQAAAAAAAAQAAAAAAAAQABAAAAAAIAKAAIABABIABABIAAAHQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgKAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAAAsQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAAAAAg");
	this.shape_33.setTransform(39.5,-14.125);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgOAbQgGgEgFgHQgDgHAAgJQAAgIADgHQAFgGAGgEQAGgEAIAAQAIAAAHAEQAHAEAEAHQADAGAAAIQAAAJgEAHQgDAHgHAEQgHADgIAAQgIAAgGgDgAgHgRQgDACgCAFQgBAEAAAGQAAAHABAEQACAFADACQADADAEAAQAEAAAEgDQADgCACgFQABgEABgHQAAgGgCgEQgCgFgDgCQgEgDgEAAQgEAAgDADg");
	this.shape_34.setTransform(33.9,-12.975);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgPAbQgHgEgDgFIAAgBIABgBIAGgDIACgBIABABIADAEQACACAEABIAGABIAGgBIAFgCQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAIgHgDIgKgDQgJgCgDgDQgEgEAAgGQAAgFACgEQADgEAGgDQAFgCAHAAQAIAAAGADQAGADACAEIABABQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABgBAAIgGADIgCAAIgBgBIgFgEQgEgCgFAAQgDAAgDACQgEACAAADIACADQABACAFABIAMADQAIADAEADQAEAEAAAGQAAAGgEAEQgDAEgGACQgFACgIAAQgIAAgHgDg");
	this.shape_35.setTransform(23.675,-12.975);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAOApIgCgBIAAgBIAAgmQAAgDgDgDQgCgCgEAAIgFABIgEACIgFAEIAAAnQAAAAAAABQAAAAAAAAQgBAAAAABQgBAAAAAAIgKAAQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAhNQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIALAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAcIAAABIABAAIAHgFIAFgDIAGgBQAJAAAFAFQAEAFAAAIIAAAmQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAg");
	this.shape_36.setTransform(17.45,-14.125);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAFAnQgFAAgEgEQgEgDgBgHIAAggQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIgIAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgHQAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBAAAAIAIAAIABgBIACgRQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAQIABABIANAAQAAAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAHQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAIgMAAQAAAAgBABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAdQAAADABACQACACAEAAIAHAAIABABIAAABIAAAFQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAABIgEAAIgEAAg");
	this.shape_37.setTransform(12.15,-13.95);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AANAeIgBgBIAAgBIAAglQgBgEgCgDQgCgCgEAAIgFABIgEACIgFAEIAAAnQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAgBAAIgJAAQAAAAgBAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAg2QAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAGIAAABIABgBIAGgEIAGgEIAHgBQAHAAAFAFQAFAFAAAHIAAAnQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_38.setTransform(6.5,-13.025);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgOAbQgGgEgFgHQgDgHAAgJQAAgIADgHQAFgGAGgEQAHgEAHAAQAIAAAHAEQAHAEADAHQAEAGAAAIQAAAJgEAHQgEAHgGAEQgHADgIAAQgHAAgHgDgAgHgRQgDACgCAFQgBAEAAAGQAAAHABAEQACAFADACQADADAEAAQAEAAAEgDQADgCACgFQABgEABgHQAAgGgCgEQgCgFgDgCQgEgDgEAAQgEAAgDADg");
	this.shape_39.setTransform(-0.2,-12.975);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAdApIgCgBIAAgBIAAg5IgBAAIAAAAIgVA5QAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgHAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgUg4IgBgBIAAABIAAA4IgBABIgBABIgJAAQgBAAAAAAQgBgBAAAAQAAAAgBAAQAAgBAAAAIAAhNQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIATAAIABAAIABACIATAzIAAAAIABgBIATgyQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAIATAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAABMQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_40.setTransform(-8.125,-14.125);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgaApIgCAAIgBgCIAAgHIABgBIABgCIADgDIAVgUIAHgHIAGgFIACgFIABgGQAAgDgCgDQgCgDgDgBIgGgBIgGABIgFADIgGAHIgBABIgBgBIgIgEIgCgCIABgBQAFgJAIgEQAHgDAJAAQAIAAAGACQAGADAEAGQAEAFAAAIQAAAEgCAEIgFAIIgKAJIgUASIAAAAIABABIAjAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAKIgBACIgBAAg");
	this.shape_41.setTransform(-20.175,-14.175);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgUApQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgJQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAMAAIACgBIAAgyQAAgBgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgMADQAAAAgBABQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgHIABgBIAAgBIASgJIACgBIABAAIAHAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAABCIABABIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAJIAAABIgCABg");
	this.shape_42.setTransform(-27.55,-14.125);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgCAaQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgSIAJAAIAAAUQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAgAAFAFIAAgJIATAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAGQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgEAFIAAgJIAAAJIgTAAIgBAAIgBgBIAAgGQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIATAAIAAgTIAAgBIACgBIAFAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAATIgJAAIAJAAIAAAJgAAFgEg");
	this.shape_43.setTransform(-37.775,-14.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.2,-20.5,148.4,41);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape.setTransform(68.125,-1.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgSAmQgJgFgGgKQgFgKAAgNQAAgMAFgJQAGgLAJgFQAKgGALAAQAJAAAHAEQAHADAFAFQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAABgBAAQAAAAAAgBQAAAAgBAAQAAAAAAgBIgEgGIgFgEQgDgCgEAAQgGAAgFADQgFAEgCAGQgDAIAAAIQAAAKADAHQADAGAFAEQAFADAGAAQAHAAAEgDQAFgEAEgHIABAAIACAAIAKACQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAHQgFAEgGACQgGACgHAAQgLAAgKgGg");
	this.shape_1.setTransform(60.7313,0.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgGgJQgFgKAAgNQAAgMAFgLQAGgKAJgFQAKgGALAAQAMAAAJAGQAJAFAFAJQAFAKAAANIAAADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAACQAAAGADAFQADAFAGAEQAFACAFAAQAHAAAFgCQAGgDAEgGIACgBIABABIAKAEQAAAAABABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAHgGAEQgFAFgHACQgHABgIAAQgLAAgKgGgAgJgbQgFAEgCAFQgDAFAAAGIAlAAIACAAIABgCQAAgFgCgFQgDgFgEgDQgEgDgHAAQgFAAgFADg");
	this.shape_2.setTransform(51.525,0.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgQBIQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgLIAAgBIACgBIAHgBQAEAAACgDQABgCABgFIAAhRQAAgBAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAABTQABANgHAGQgGAHgOAAgAAAgyQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgQQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAQAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAPQAAAEgEAAg");
	this.shape_3.setTransform(43.9,-0.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVAmQgJgFgGgKQgFgKAAgNQAAgMAGgJQAFgLAJgFQAKgGALAAQAMAAAKAGQAJAGAGAKQAFAJAAAMQAAANgFAKQgGAKgJAFQgKAGgMAAQgMAAgJgGgAgLgaQgEAEgCAGQgDAIAAAIQAAAJADAIQACAGAEAEQAGADAFAAQAHAAAFgDQAEgEADgGQACgIAAgJQAAgIgCgIQgDgGgEgEQgFgDgHAAQgFAAgGADg");
	this.shape_4.setTransform(38,0.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgWArIgCAAIgBgDIAAhOQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAQAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAKIAAABQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQADgFAEgDIAIgEQAFgCADAAQAGAAAAACIAAAQQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgFgBIgFAAIgGABIgGADIgFAGQgBACAAADIAAAwQAAADgEAAg");
	this.shape_5.setTransform(30.9,-0.025);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AglA4QAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhpIAAgCIADgBIAPAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAAAGIAAABIACgBIAFgFQADgCAFgBQADgCAHAAQAJAAAIAEQAHAFAFAKQAEAJAAAOQAAAPgEAJQgFALgIAFQgHAEgLAAQgFAAgGgCQgFgCgEgDIgDgCIAAADIAAAdQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAgAgKgoQgEADgCADQgCADAAAEIAAAkQADAEAFADQAEACAFAAQAFAAAFgDQAFgEADgHQACgFAAgMQAAgKgCgHQgDgGgFgDQgFgDgEAAQgGAAgEACg");
	this.shape_6.setTransform(22.875,1.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgGgJQgFgKAAgNQAAgMAFgLQAGgKAJgFQAKgGALAAQAMAAAJAGQAJAFAFAJQAFAKAAANIAAADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAACQAAAGADAFQADAFAGAEQAFACAFAAQAHAAAFgCQAGgDAEgGIACgBIABABIAKAEQAAAAABABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAHgGAEQgFAFgHACQgHABgIAAQgLAAgKgGgAgJgbQgFAEgCAFQgDAFAAAGIAlAAIACAAIABgCQAAgFgCgFQgDgFgEgDQgEgDgHAAQgFAAgFADg");
	this.shape_7.setTransform(8.125,0.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgWArIgCAAIgBgDIAAhOQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAQAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAKIAAABQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQADgFAEgDIAIgEQAFgCAEAAQAFAAAAACIAAAQQAAAAAAABQAAAAgBABQAAAAAAAAQAAAAgBAAIgFgBIgFAAIgGABIgGADIgFAGQgBACAAADIAAAwQAAADgEAAg");
	this.shape_8.setTransform(1.1,-0.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgGA7IgDAAIgBgDIAAhOQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABOQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAgBAAIgDABgAgGglIgDAAIgBgDIAAgPQAAgBABgBQAAAAAAgBQAAAAABAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAQQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_9.setTransform(-4.6,-1.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape_10.setTransform(-9.275,-1.375);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_11.setTransform(-17.225,-0.025);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgGgJQgFgKAAgNQAAgMAFgLQAGgKAJgFQAKgGALAAQAMAAAJAGQAJAFAFAJQAFAKAAANIAAADQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAACQAAAGADAFQADAFAGAEQAFACAFAAQAHAAAFgCQAGgDAEgGIACgBIABABIAKAEQAAAAABABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAHgGAEQgFAFgHACQgHABgIAAQgLAAgKgGgAgJgbQgFAEgCAFQgDAFAAAGIAlAAIACAAIABgCQAAgFgCgFQgDgFgEgDQgEgDgHAAQgFAAgFADg");
	this.shape_12.setTransform(-26.725,0.05);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgWArIgDAAIAAgDIAAhOQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAQAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAAKIAAABQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQADgFAEgDIAIgEQAEgCAEAAQAGAAAAACIAAAQQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgFgBIgFAAIgGABIgHADIgDAGQgCACAAADIAAAwQAAADgEAAg");
	this.shape_13.setTransform(-38.75,-0.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgYAoQgGgDgDgFQgEgGAAgIIAAg5QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAOAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAAA2QgBAGAEADQAEAEAFAAQAFAAAFgDQAFgDAEgFIAAg4QABgDAEAAIAOAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAABIAABOQAAABgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIgPAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgCAAQgHAHgGADQgHADgHAAQgHAAgFgDg");
	this.shape_14.setTransform(-47.15,0.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVAmQgJgFgGgKQgFgKAAgNQAAgMAFgJQAGgLAKgFQAJgGALAAQANAAAJAGQAJAGAGAKQAFAJAAAMQAAANgGAKQgEAKgKAFQgJAGgNAAQgLAAgKgGgAgLgaQgEAEgDAGQgCAIAAAIQAAAJACAIQADAGAEAEQAFADAGAAQAHAAAFgDQAEgEACgGQADgIAAgJQAAgIgDgIQgCgGgEgEQgGgDgGAAQgGAAgFADg");
	this.shape_15.setTransform(-56.45,0.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgiA3QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgKIABgCIAEgBIAKAAQADAAADgBIAEgFIADgFIgBgFIgfhLQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAQAAIACABIACACIATA0IABABIABgBIAUg0IABgCIACgBIAMAAIACACIAAACIgiBTIgGAMQgDAFgEACQgEADgFABIgLABg");
	this.shape_16.setTransform(-65.4208,1.375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.9,-10,143.9,20);


(lib.Promo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B0FBC6").s().p("AguBKIgDgBIgBgCIAAiNQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIBdAAQABAAABAAQAAAAABABQAAAAAAAAQABABAAABIAAAPQgBAEgEAAIg+AAQgBAAgBAAQgBAAAAAAQgBABAAAAQAAABAAABIAAAlQAAABAAAAQAAABABAAQAAAAAAABQABAAABAAIAtAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAAPQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAIgtAAQgBAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABIAAA3QAAAEgFAAg");
	this.shape.setTransform(45.85,61.775);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#B0FBC6").s().p("AguBKIgDgBIgBgCIAAiNQAAgBABAAQAAgBAAAAQABgBAAAAQABAAAAAAIBeAAQABAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAAPQAAAEgDAAIg/AAQgBAAgBAAQgBAAAAAAQgBABAAAAQAAABAAABIAAAlQAAABAAAAQAAABABAAQAAAAAAABQABAAABAAIAuAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAAPQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIguAAQgBAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABIAAA3QAAAEgEAAg");
	this.shape_1.setTransform(33.05,61.775);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B0FBC6").s().p("AgjBDQgPgJgIgRQgIgRAAgXQAAgXAIgSQAJgRAPgJQAPgJATAAQAUAAAPAJQAPAJAIARQAJARAAAXQAAAYgJARQgIARgPAJQgPAJgUAAQgUAAgPgJgAgagpQgJAOAAAcQAAAcAJANQAJANARAAQASAAAJgNQAJgNAAgcQAAgcgJgOQgJgNgSAAQgRAAgJANg");
	this.shape_2.setTransform(17.975,61.775);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#B0FBC6").s().p("AAmBcQgLgHgGgMQgGgMAAgQQAAgQAGgNQAGgMALgGQALgHAOAAQANAAALAHQALAGAGAMQAGANAAAQQAAAQgGAMQgGAMgLAHQgLAHgNAAQgOAAgLgHgAAyAMQgFAFgCAIQgDAJAAALQAAALADAIQACAJAFAEQAFAFAIAAQAHAAAFgFQAFgEACgJQADgIAAgLQAAgLgDgJQgDgIgEgFQgFgFgHAAQgIAAgFAFgAhDBiQgBAAAAAAQgBgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIB8i6IACgCIADAAIAMAAIACABQABAAAAAAQAAAAAAABQAAAAgBABQAAAAAAABIh9C8QgBADgFAAgAhVAEQgLgGgGgNQgHgMAAgQQAAgQAHgMQAGgNALgHQALgHANAAQAOAAAKAHQALAHAGANQAHAMAAAQQAAAQgGAMQgHANgKAGQgLAHgOAAQgNAAgLgHgAhJhMQgFAFgDAIQgCAJAAALQAAALACAJQADAIAFAEQAFAFAHAAQALAAAGgKQAFgKAAgRQAAgRgFgKQgGgKgLAAQgHAAgFAEg");
	this.shape_3.setTransform(26.475,41.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#B0FBC6").s().p("AhICkQgigVgRgpQgTgoABg3QgBg7AUgsQATgrAkgXQAigXAvAAQAWAAASAGQARAFAPAJQANAJAKAKQAKALAEAKIAAAFQAAADgDABIgtAQQgEABgCgCIgDgEQgJgNgMgIQgLgIgUAAQgbAAgTAOQgTAOgJAYQgJAYAAAeIACALQABACAHgDIAjgNQASgHAZAAQAmAAAcAOQAbAOAQAXQAPAYgBAgQABAigTAbQgSAagfAPQgfAPgmAAQgtAAghgWgAgRAMIgZAHIgTAJIgGAHIgBAMQgBAQAFAQQAFAQAJANQAKANANAIQAOAIASAAQASAAAPgIQAQgJAIgPQAJgPAAgTQAAgSgIgOQgJgNgOgIQgPgIgTAAg");
	this.shape_4.setTransform(-7.3,49.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#B0FBC6").s().p("Ah5C4IgIgCQgCgCAAgFIAAggIABgGIAGgHIAMgMIBghaIAkghIAXgbQAJgLADgLQAEgLAAgLQAAgRgJgMQgJgMgNgGQgOgHgPAAQgOAAgNAFQgNAFgMALQgNALgLATQgBADgDAAIgIgCIgkgTQgFgCAAgEQgBgEADgEQAYgmAigRQAhgRAoAAQAkAAAcAMQAdANAQAYQARAYAAAiQAAAVgHASQgHASgQATQgRARgbAXIhcBPIgDAEQAAABAGAAICeAAQAIAAAAAHIAAAtIgBAGQgDACgEAAg");
	this.shape_5.setTransform(-36.725,48.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#B0FBC6").s().p("AgcDIQgKABAAgKIAAg8QAAgJAGAAIBAAAQAHAAAAAIIAAA7QAAALgNAAgAgMBVQgGAAgCgCIgCgIIgSkJIACgHIAFgCIBCAAQAIAAgBAHIgREKQAAAGgDADQgDACgGAAg");
	this.shape_6.setTransform(53.4016,3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#B0FBC6").s().p("AhFCCQgggTgTggQgSghAAgqQAAguATgjQATghAggTQAhgTAmAAQApABAeARQAfASARAhQARAiAAAuIgBAJQAAACgHABIi+AAIgFACIgBAHQAAAWAKASQAKARASAKQASAKAVAAQAWAAASgJQASgJAQgVIAEgDIAGACIAhAPQAHADgGAHQgQAYgTANQgSAPgXAGQgWAGgcAAQgoAAghgSgAgfhdQgRALgIARQgIASAAAWIB+AAIAHgCIACgGQAAgRgIgQQgHgQgPgLQgPgLgUAAQgVAAgQALg");
	this.shape_7.setTransform(32.375,8.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#B0FBC6").s().p("AgXDIQgLABAAgKIABl9QAAgKAIABIA1AAQAHAAAAAJIAAF7QAAAGgCADQgDADgHgBg");
	this.shape_8.setTransform(11.425,3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#B0FBC6").s().p("AhnB/QgXgWAAgkQAAgdASgWQARgVAigMQAigNAwgCIAagCIAGgBQADgCAAgFIAAgMQAAgYgOgNQgOgOgZAAQgSAAgQAJQgQAIgMATIgFAFIgGAAIgugMIgDgDIABgJQAPgeAggQQAfgQAuAAQApABAaAKQAaAMAMAUQAMAUAAAcIAAC9IgCAIQgCADgFAAIguAAQgFAAgCgEIgDgJIgBgRQgBgIgKAIQgRAQgWAKQgVAJgcAAQgpAAgYgVgAA0ADIgWACQgSABgPAEQgQAEgMAHQgMAHgHAKQgHAKAAANQAAASANALQANALAXAAQAOAAAMgFQAMgFAKgHIAOgRQAGgHAAgKIAAgmQAAgJgGAAIgCAAg");
	this.shape_9.setTransform(-11.325,8.75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#B0FBC6").s().p("Ag/DGQgegJgYgPQgXgQgPgWQgCgEABgDIAFgHIAigYQAGgDAEAAIAGAEQANARAOALQANALARAGQARAFAZAAQAlAAAXgNQAWgMAAgbQAAgLgEgJQgFgJgKgHQgLgIgUgHIhQgZQgggJgUgQQgUgQgKgWQgLgVAAgYQAAgiATgbQASgaAhgQQAigPAsAAQAdAAAaAHQAZAHAVAMQAVAMANASIAEAFQABAEgFADIgmAdIgFABIgHgFQgNgOgTgLQgTgLghAAQgjAAgTAOQgTAOAAAYQAAAHAEAJQADAJALAIQAKAIAUAHIBTAZQAxAOAWAcQAWAdAAAmQAAAlgTAbQgTAbgiAOQgjAPgwAAQgiAAgfgIg");
	this.shape_10.setTransform(-43.6393,3.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgwBTQgBAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBIAAgJIABgDIAGAAIAPAAQAFAAAEgEQAFgDADgGQADgFABgFQABgGgCgEIguhxIAAgDIADgBIAPAAIACAAIABACIAjBcIACACQABAAAAAAQAAAAAAAAQABgBAAAAQAAgBAAAAIAkhcIABgCIACAAIALAAIADABIAAACIg1CGQgDAJgEAFQgEAGgFADQgFADgGABIgOABg");
	this.shape_11.setTransform(61.0125,-42.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgdBBIgDgBIgBgCIAAh4QAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAOAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAQIABACIACgCIALgMIANgHQAGgCAGAAQAJAAAAADIAAAPQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgFgBIgGAAQgGAAgGACQgGACgEAFQgFAEgDAFQgEAFAAAFIAABOQAAABAAABQAAAAgBABQAAAAgBABQAAAAgBAAg");
	this.shape_12.setTransform(51.675,-44.525);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgpA4QgLgJAAgQQAAgNAHgJQAIgJAOgEQAOgGATgBIATgBIADgBIABgDIAAgGQAAgOgIgHQgIgIgOAAQgJAAgJAFQgIAFgHAKIgBABIgDAAIgMgFIgCgBIABgCQAHgMANgIQANgHASAAQAQAAALAFQALAFAFAJQAGAJAAANIAABUIgBADIgDAAIgMAAIgCgBIgBgCIAAgLQAAgBgBgBQAAAAgBAAQAAAAgBAAQAAAAgBABQgJAJgKAEQgLAFgMAAQgSAAgLgKgAAOAAQgLABgIACQgJACgFAEQgGAEgEAEQgDAFAAAGQAAALAIAGQAHAGAMAAQAHAAAHgCQAHgDAGgFQAFgEADgFQADgFAAgEIAAgVQAAgDgDABg");
	this.shape_13.setTransform(39.325,-44.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgfA7QgOgJgHgKIAAgDIABgCIAJgEIADgBIABABQAFAGAFAFQAFAEAHADQAIADAJAAQAJgBAIgCQAHgDAEgEQAFgFAAgGQAAgHgGgFQgEgEgOgEIgYgHQgSgEgGgIQgIgIAAgLQAAgLAGgJQAHgIAKgGQAMgEANAAQAQAAAMAGQANAGAHAKIABACIgBACIgLAFIgCAAIgBgBQgFgHgIgEQgKgFgMAAQgLAAgIAFQgKAGABAKQAAAFADAEQAFAFALAEIAdAJQARADAHAIQAIAJAAALQAAALgHAJQgHAJgMAEQgLAFgPAAQgSAAgOgHg");
	this.shape_14.setTransform(27.05,-44.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgdBBIgDgBIgBgCIAAh4QAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAOAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAQIABACIACgCIALgMQAHgEAGgDQAGgCAGAAQAJAAAAADIAAAPQAAAAAAABQgBAAAAABQAAAAAAAAQgBAAAAAAIgFgBIgGAAQgGAAgGACQgGACgEAFQgFAEgDAFQgEAFAAAFIAABOQAAABAAABQAAAAgBABQAAAAgBABQAAAAgBAAg");
	this.shape_15.setTransform(18.425,-44.525);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgdA6QgNgJgIgOQgIgPAAgTQAAgUAIgPQAIgPAOgIQANgIAQAAQASAAANAIQANAHAHAPQAHAOAAAVIAAACQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIhbAAIgCACIAAACQAAALAFAKQAGAKAJAGQAKAFALABQAMAAAJgGQAJgEAHgKIACgCIABABIALAFQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBAAQgGAKgIAGQgIAGgKADQgJADgMAAQgRAAgOgIgAgTgtQgJAHgEAKQgFAJAAALIBIAAIAEgBIAAgCQAAgLgEgIQgFgKgIgFQgIgGgMAAQgMABgJAFg");
	this.shape_16.setTransform(6.925,-44.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgDA/QgFABgBgEIgxh3IAAgDIADgBIAPAAIACABIACACIAkBeQACAEACgFIAlhdIACgCIACgBIALAAIADABIAAADIgxB3QgBAEgFgBg");
	this.shape_17.setTransform(-5.5125,-44.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgGBZIgDAAIAAgEIAAh3QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIANAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAB3IgBADIgDABgAgGg8QgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAAAIgBgDIAAgVQAAAAAAgBQABgBAAAAQAAgBABAAQABAAAAAAIAOAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAAAVQAAAEgEAAg");
	this.shape_18.setTransform(-14.525,-46.95);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAjBBIgCgBIgBgCIAAhVQAAgMgGgGQgGgHgNAAQgHAAgFACIgMAHIgOAKIAABaQAAABAAABQgBAAAAABQgBAAAAABQgBAAgBAAIgNAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIAAh4QAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAOIABACIACgBIAOgLQAHgEAHgDQAHgCAIAAQASAAAKAKQAKAKAAAQIAABZQAAAEgDAAg");
	this.shape_19.setTransform(-23.625,-44.525);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAjBBIgCgBIgBgCIAAhVQAAgMgGgGQgGgHgNAAQgHAAgFACIgMAHIgOAKIAABaQAAABAAABQgBAAAAABQgBAAAAABQgBAAgBAAIgNAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIAAh4QAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAOIABACIACgBIAOgLQAHgEAHgDQAHgCAIAAQASAAAKAKQAKAKAAAQIAABZQAAAEgDAAg");
	this.shape_20.setTransform(-36.925,-44.525);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AA5BZQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAgBIgQguIgBgCIgCAAIhFAAQgBAAAAAAQgBAAAAABQAAAAAAAAQgBABAAAAIgRAvIgBACIgDAAIgOAAIgCgBIAAgDIA+iqIACgCIADgBIARAAQAFAAABADIA9CqIAAADQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAgAgCg9IgdBPQgBAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIA5AAQABAAABAAQAAAAAAgBQABAAAAgBQAAAAgBgBIgchOIgBgCg");
	this.shape_21.setTransform(-51.275,-46.95);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgdA6QgNgJgIgOQgIgOAAgUQAAgUAIgPQAIgPAOgIQANgIAQAAQASAAANAHQANAIAHAPQAHAPAAAUIAAACQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIhbAAIgCABIAAADQAAALAFAKQAGAKAJAGQAKAGALgBQAMAAAJgEQAJgFAHgLIACgBIABABIALAFQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBAAQgGAKgIAGQgIAGgKADQgJADgMAAQgRAAgOgIgAgTgsQgJAGgEAJQgFAKAAALIBIAAIAEAAIAAgEQAAgJgEgKQgFgIgIgGQgIgFgMgBQgMAAgJAHg");
	this.shape_22.setTransform(18.175,-66.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAjBBIgCgBIgBgCIAAhVQAAgMgGgGQgGgHgNAAQgHAAgFACIgMAHIgOAKIAABaQAAABAAABQgBAAAAABQgBAAAAABQgBAAgBAAIgNAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAIAAh4QAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAOIABACIACgBIAOgLQAHgEAHgDQAHgCAIAAQASAAAKAKQAKAKAAAQIAABZQAAAEgDAAg");
	this.shape_23.setTransform(4.925,-66.525);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AggA8QgJgEgFgJQgFgIAAgLIAAhYQAAgBAAgBQABAAAAgBQABAAAAgBQABAAABAAIANAAQABAAABAAQAAABAAAAQABAAAAABQAAABAAAAIAABUQAAALAHAIQAGAHAMAAQAJAAAKgGQAJgFAKgKIAAhYQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAOAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAIgBB4QAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAgPIAAgBIgCABQgNALgKAEQgJAFgLAAQgLAAgIgFg");
	this.shape_24.setTransform(-8.575,-66.275);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgUBYIgKgDIgCgCIgBgCIACgNQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAIAEQAEABAIAAQAKAAAEgGQAFgFAAgQIAAiBQAAgBAAgBQAAAAABgBQAAAAABAAQAAAAABAAIARAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAABIAACHQAAAUgJALQgJAKgUAAQgJAAgHgCg");
	this.shape_25.setTransform(-20.05,-68.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.3,-80.5,152.7,161.1);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.line = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#B1FBC6").ss(1,1,1).p("AqBAAIUDAA");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.2,-1,130.4,2);


(lib.Img_05_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_05();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.img_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#013229").s().p("ADnA3QgKgGgFgJQgGgJAAgNQAAgNAGgJQAFgLAKgFQAKgGALAAQANAAAIAGQAKAFAFAKQAFAIAAAPIAAACQAAABAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIg2AAIgBABIAAACQAAAGADAEQADAEAEADQAFADAGAAQAGAAAEgDQAFgDAFgFIABgBIANAGQABAAAAAAQABAAAAABQAAAAgBABQAAAAgBABQgFAHgFAEQgFAEgIADQgGABgJAAQgMAAgJgFgAD0gJQgFADgCAEQgCAEAAAGIAgAAIACAAIABgCQAAgEgDgEQgBgDgEgDQgDgDgGAAQgFAAgEACgAgGA1QgMgHgHgOQgGgNAAgTQAAgRAGgOQAIgOAMgHQALgHAQAAQAQAAANAHQAMAHAGAOQAHAOAAARQAAATgHANQgGAOgMAHQgNAHgQAAQgRAAgLgHgAADgeQgFAKAAAUQAAAWAFAJQAGAKANAAQANAAAGgKQAGgJAAgWQAAgUgGgKQgGgKgNAAQgNAAgGAKgAjWA3QgKgGgFgJQgGgJAAgNQAAgNAGgJQAGgLAJgFQAKgGAMAAQAMAAAIAGQAKAFAGAKQAFAIAAAPIAAACIgDABIg2AAIgCABIAAACQAAAGADAEIAHAHQAFADAGAAQAGAAAEgDQAFgDAFgFIABgBIAOAGQAAAAABAAQAAAAAAABQAAAAAAABQgBAAAAABQgFAHgFAEQgGAEgHADQgHABgIAAQgNAAgJgFgAjJgJQgEADgDAEQgCAEAAAGIAgAAIACAAIABgCQAAgEgCgEQgCgDgDgDQgEgDgGAAQgFAAgEACgAlUA1QgMgHgGgOQgGgOAAgSQAAgRAGgOQAHgOAMgHQANgHAQAAQAMAAALAEQAKAFAGAIQAHAHABAJIAAAEIgCAAIgVAEIgBgBIgBgCQgBgFgDgEQgDgFgFgDQgFgCgGAAQgHAAgGAEQgGAEgDAJQgDAJAAAOQAAAPADAIQAEAKAGADQAFAFAIAAQAFAAAEgCQAEgBACgDQADgCACgEIADgGIAAgFQABAAAAgBQAAgBgBAAQAAAAAAgBQgBAAgBAAIgVAAIAAgCIAAgMQAAAAAAgBQAAAAAAAAQABAAAAAAQABAAAAAAIArAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIABACIAAA2IgBACIgBABIgFAAIgCgBIgCgCIgFgLIAAgBIgCABIgHAHQgEAEgGACQgHACgJAAQgQAAgMgHgAE5A7QAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgBgCIAAhNQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAABAAIASAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAIAAAKIAAABIACgBIAHgIIAJgEQADgCAFAAQAFAAAAADIAAASQAAAAAAABQAAABgBAAQAAAAAAAAQgBAAgBAAIgKgBIgGABQgEABgCACIgEAEIgCAFIAAAuQAAAEgEAAgACtA7QAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAg+QAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAIgLAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgMIABgBQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAAAQABAAAAgBQAAAAAAgBIAAgJQAAgKAGgGQAGgGALAAIAQAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIAAALIAAABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgIAAQgEAAgCADQgCADAAADIAAAHQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAIANAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIABABIAAAMQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAIgNAAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAA+QAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAgABxA7QAAAAgBAAQAAgBAAAAQAAAAgBgBQAAgBAAAAIAAg+QAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgMIABgBQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAABAAQAAAAAAgBQAAAAAAgBIAAgJQAAgKAGgGQAGgGALAAIAQAAQABAAABAAQAAABABAAQAAAAABABQAAAAAAABIAAALIgBABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgIAAQgEAAgCADQgCADAAADIAAAHQAAAAAAAAQAAABAAAAQABAAAAAAQABAAAAAAIANAAIACACIABABIAAAMQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAIgNAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAA+QAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAgAh3A2QgGgFAAgLIAAgrQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAgBAAIgJAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIAAgMQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIACgYQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIARAAQAAAAABAAQABABAAAAQAAAAABABQAAABAAAAIAAAYQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIARAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAIAAAMQAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAIgRAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAlQAAAGACACQADACAFAAIAJAAIACABIABACIgBAKQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIgTABQgLAAgGgFg");
	this.shape.setTransform(0.025,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C2F9CB").s().p("AlWC2QhKAAg2g2Qg1g1AAhLIAAAAQAAhKA1g2QA2g1BKAAIKtAAQBKAAA2A1QA1A2AABKIAAAAQAABLg1A1Qg2A2hKAAg");
	this.shape_1.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.4,-18.1,104.8,36.3);


// stage content:
(lib.WBAY_216348_MM_300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#010101").ss(1,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(200));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(73,237.15);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(48).to({_off:false},0).to({y:227.15,alpha:1},12,cjs.Ease.get(1)).wait(140));

	// logo
	this.instance_1 = new lib.logo_1("synched",0);
	this.instance_1.setTransform(80,276);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:300,alpha:1},14,cjs.Ease.get(1)).wait(186));

	// mask_idn (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ArAR2MAAAgjrIWBAAMAAAAjrg");
	mask.setTransform(69.575,173.85);

	// Img_05_jpg
	this.instance_2 = new lib.Img_05_1("synched",0);
	this.instance_2.setTransform(80,300);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(153).to({_off:false},0).to({alpha:1},12,cjs.Ease.get(1)).wait(35));

	// Img_04_jpg
	this.instance_3 = new lib.Img_04_1("synched",0);
	this.instance_3.setTransform(80,300);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(119).to({_off:false},0).to({alpha:1},11,cjs.Ease.get(1)).wait(70));

	// Img_03_jpg
	this.instance_4 = new lib.Img_03_1("synched",0);
	this.instance_4.setTransform(80,300);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(89).to({_off:false},0).to({alpha:1},12,cjs.Ease.get(1)).wait(99));

	// Img_02_jpg
	this.instance_5 = new lib.img_02("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(60).to({_off:false},0).to({alpha:1},11,cjs.Ease.get(1)).wait(129));

	// Img_01_jpg
	this.instance_6 = new lib.Img_01();

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(200));

	// line
	this.instance_7 = new lib.line("synched",0);
	this.instance_7.setTransform(220,193.25);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(24).to({_off:false},0).wait(176));

	// Promo
	this.instance_8 = new lib.Promo("synched",0);
	this.instance_8.setTransform(219.5,82.5);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(12).to({_off:false},0).to({y:87.5,alpha:1},12,cjs.Ease.get(1)).wait(176));

	// T1
	this.instance_9 = new lib.T1("synched",0);
	this.instance_9.setTransform(220,192.9);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(24).to({_off:false},0).to({y:177.9,alpha:1},12,cjs.Ease.get(1)).wait(164));

	// T2
	this.instance_10 = new lib.T2("synched",0);
	this.instance_10.setTransform(220.8,230.5);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(36).to({_off:false},0).to({y:220.5,alpha:1},12,cjs.Ease.get(1)).wait(152));

	// BG_jpg
	this.instance_11 = new lib.BG();

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(200));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,101,152,154.4);
// library properties:
lib.properties = {
	id: 'AF07DFB303784816B072C874A5B8C623',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"Img_05.jpg", id:"Img_05"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['AF07DFB303784816B072C874A5B8C623'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;