(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Logo = function() {
	this.initialize(img.Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgMAYQgGgDgDgGQgEgGAAgIQAAgIAEgHQADgFAGgEQAGgDAHAAQAHAAAGADQAGADADAGQADAHAAAHIAAACIgCAAIgiAAIgBABIAAABQAAAEACADQACADADADQADACADAAQAEAAAEgCQADgCADgEIABgBIABABIAGACQAAABAAAAQABAAAAABQAAAAAAAAQAAAAgBABQgDAEgDACIgIAFIgJABQgHgBgGgDgAgFgRQgDADgBADQgCADAAAEIAXAAIABAAIAAgCIgBgFIgEgGQgDgBgEAAQgDAAgDABg");
	this.shape.setTransform(68.725,13.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgNAZQgGgEgDgEIAAgBIAAgBIAGgEIACAAIAAAAIADAFIAGACIAGABIAFgBIAEgCQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgGgDIgJgCQgIgCgDgCQgEgEAAgFQAAgGACgDQADgEAFgDQAFgBAGAAQAHgBAGADQAFADADAEIAAABIAAABIgHADIgBAAIgBgBQgCgCgDgCQgDgBgEAAQgEAAgCABQgDACgBADIACADQABABAEABIALAEQAIACADACQADAFAAAFQAAAFgCAEQgDAEgGACQgFACgGAAQgJAAgFgDg");
	this.shape_1.setTransform(62.55,13.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgSAYQgEgFgBgGQABgGADgEQADgDAHgCQAGgDAHAAIAGAAIABgBIABgBIAAgCQAAgEgDgDQgDgCgEAAQgDAAgDABQgDACgCAEIgBABIgCAAIgIgDIgBgBIABgBQADgGAFgDQAHgCAHAAQAIAAAEABQAGACABAFQACADAAAGIAAAiIAAABIgBABIgJAAIgBgBIAAgCIAAgDQgBAAAAgBQAAAAAAAAQAAAAgBAAQAAABAAAAIgIAFQgDABgFABQgIAAgEgEgAAFABIgFABIgFACIgDADIgBAEQAAADACADQACACAFAAIADgBIAFgCIACgEIACgCIAAgIQgBAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_2.setTransform(56.45,13.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAMAlIgBgBIgBgBIAAgiQAAgDgBgCQgCgDgFAAIgDACIgFACIgDADIAAAjQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgJAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAhGQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAaIABABIAAgBIAGgDIAFgDIAGgBQAHAAAEAEQAEAFABAGIAAAkQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_3.setTransform(50.35,12.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgLAYQgFgDgEgGQgDgHAAgIQAAgHADgHQAEgFAGgEQAFgDAHAAQAGAAAEABQAFACADAEIAEAGQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAIgJABQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIgDgEIgDgDIgFgBQgDAAgDACQgDACgBAFQgCAEAAAFQAAAGACAEQACAEADADQADACADAAQAFAAACgCIAGgHIAAAAIABAAIAHABQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAIgCAFIgFAEQgDADgEABQgDABgFABQgHgBgGgDg");
	this.shape_4.setTransform(44.0833,13.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgOAbIgBgBIAAgBIAAgwQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAFIAAABIABAAIAEgFIAFgDIAFgBQABAAABAAQABAAAAAAQABABAAAAQAAAAAAABIAAAJQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAIgDgBIgDAAIgFABIgDACIgCADIgBAEIAAAdQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(38.875,13.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgPAZQgEgCgCgDQgCgEAAgFIAAgjQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAAAhQAAAEACACQACACAEAAQACAAADgCIAHgEIAAgjQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAwQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgFIAAAAIgBAAQgFAEgEACQgDACgFAAQgEAAgEgCg");
	this.shape_6.setTransform(33.05,13.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgbAlIgBgBIAAgBIAAhGQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAbAAQAIAAAHACQAGADAEAEQAEAGAAAIQAAAHgDAFQgEADgGADQgGADgIgBIgPAAIgBABIAAAbQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAgAgOgYIAAAVQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAABAAIAMAAQAGAAAEgDQAEgDAAgGQAAgEgCgCIgFgFIgHgBIgMAAQAAAAgBABQAAAAAAAAQgBAAAAAAQAAABAAAAg");
	this.shape_7.setTransform(26.225,12.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgVAhQgHgDAAgHQAAgEACgCIAHgEQAAAAABgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgEgDQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIABgDIADgCIAFgDIAAAAQABgBgBAAQgFgCgCgDQgCgEAAgEQAAgIAGgFQAGgEAMAAQAEAAAEABQAEABADACIABABIABgBIADgCIAEgCIADgBIACAAIAAACIAAAGIAAABIgCABIgDAAIgCAAQAAAAgBAAQAAABgBAAQAAAAAAABQAAAAAAAAIABACIAAAEQAAAEgCAEQgDADgFADQgFACgHAAIgHAAIgEABIgBACIACACIAFAAIANABQAKABAFAEQAEADAAAGQAAAIgHAFQgHAEgMAAQgOAAgHgDgAgNAPIgDADQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABABABQAAAAAAABQABAAAAABQACACAEABIAKABQAHAAAEgDQADgCAAgDQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAgBgBQgCgBgEgBIgPAAIgBAAIgDAAgAgKgYQgDACAAAFQAAAEADACQADADAGAAQAFAAADgDQACgCAAgEQAAgFgCgCQgDgDgFAAQgGAAgDADg");
	this.shape_8.setTransform(16.125,14.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAMAbIgBgBIAAgBIAAghQAAgEgCgCQgDgDgEAAIgEACIgDACIgFADIAAAjQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgJAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgwQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAEIAAABIABAAIAFgEIAGgDIAFgBQAIAAAFAEQADAFAAAGIAAAkQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_9.setTransform(9.55,13.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgEAlIgBgBIAAgBIAAgwQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAJAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAwIgBABIgCABgAgEgWIgBgBIgBgCIAAgKQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAJAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_10.setTransform(4.675,12.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgVAjIgBgCIAAgGIAAgBIADgBIAGAAIAEgBIADgDIABgDIAAgDIgTgvIAAgBIABgBIAKAAIACABIAAABIAMAgIABABIABgBIAMggIABgBIABgBIAHAAIABABIAAABIgVA0IgEAHIgDAFQgDACgDAAIgHABg");
	this.shape_11.setTransform(0.075,14.275);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgFAlQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgoIgBgBIgIAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgGIABgBIABgBIAIAAQAAAAAAAAQAAAAAAAAQAAgBAAAAQABAAAAgBIAAgGQAAgGADgDQADgEAGAAIAKAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAAGIAAABIgBAAIgGAAQgBAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQAAABgBAAQAAABAAABQAAAAAAABIAAAFQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIAJAAIACABIABABIAAAGQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgKAAIgBABIAAAoQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_12.setTransform(-5.2,12.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgEAlIgBgBIAAgBIAAgwQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAJAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAwIgBABIgCABgAgEgWIgBgBIgBgCIAAgKQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAJAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_13.setTransform(-9.075,12.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgEAlQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIABhGQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAJAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAABGIgBABIgCABg");
	this.shape_14.setTransform(-12.225,12.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgSAYQgFgFAAgGQAAgGAEgEQADgDAHgCQAGgDAIAAIAEAAIACgBIAAgBIAAgCQAAgEgDgDQgCgCgFAAQgCAAgDABQgDACgCAEIgBABIgBAAIgIgDIgBgBIAAgBQACgGAHgDQAFgCAIAAQAHAAAGABQAEACACAFQADADAAAGIAAAiIAAABIgCABIgIAAIgCgBIgBgCIAAgDQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABgBAAIgHAFQgDABgFABQgHAAgFgEgAAGABIgGABIgFACIgEADIAAAEQgBADADADQACACAFAAIADgBIAFgCIACgEIABgCIAAgIQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_15.setTransform(-17.05,13.45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgPAZQgEgCgCgDQgCgEAAgFIAAgjQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAAAhQAAAEACACQACACAEAAQACAAADgCIAHgEIAAgjQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAwQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgFIAAAAIgBAAQgFAEgEACQgDACgFAAQgEAAgEgCg");
	this.shape_16.setTransform(-23.2,13.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AATApQgGgDgEgGQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIgEAAIgEAAQgJAAgIgEQgHgFgEgIQgFgJAAgLQAAgMAFgIQAEgJAHgEQAIgFAJAAQAKAAAIAFQAHAEAEAJQAFAIAAAMQgBAKgDAIQgDAIgGAEIgBABIACADIAEACIAGACIABABIAAAAIAAAHIAAACIgEABQgFAAgFgDgAgMgaQgFAHAAAPQAAANAFAGQAEAHAIAAQAJAAAFgHQAEgGAAgOQAAgOgEgHQgFgGgJAAQgIAAgEAGg");
	this.shape_17.setTransform(-30.55,12.975);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAMAlIgBgBIgBgBIAAgiQAAgDgBgCQgCgDgFAAIgDACIgFACIgDADIAAAjQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgJAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAhGQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAaIABABIAAgBIAGgDIAFgDIAGgBQAHAAAEAEQAEAFABAGIAAAkQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_18.setTransform(-40.55,12.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAJAkIgEAAQgFAAgEgDQgEgEAAgGIAAgdQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAgBIgGAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAIAAIABgBIABgQQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAgBIAIAAQABABAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAQIABABIALAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAGQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgMAAIgBABIAAAaQAAAEACACQACABADABIAGAAIABAAIAAABIAAAFQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAIgDABg");
	this.shape_19.setTransform(-47.075,12.55);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgEAlIgBgBIAAgBIAAgwQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAJAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAwIgBABIgCABgAgEgWIgBgBIgBgCIAAgKQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAJAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_20.setTransform(-50.975,12.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AASAlQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBgBIgNgvIAAgBIgBABIgNAvQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgJAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgVhFIAAgCIACAAIALAAIACAAIAAABIAOAxIABACIABgBIANgyIABgBIACAAIAIAAIACAAIABABIANAyIABABIAAgBIAPgyIAAgBIACAAIAHAAIACAAIAAACIgUBFQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_21.setTransform(-58.3,12.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgOAbIgBAAIAAgCIAAgxQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAAHIAAAAIABAAIAEgFIAFgDIAFgBQABAAABAAQABAAAAAAQABABAAAAQAAAAAAAAIAAAKQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgDAAIgDgBIgFABIgDADIgCADIgBADIAAAeQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_22.setTransform(49.025,1.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgMAYQgGgEgDgGQgEgFAAgIQAAgIAEgGQADgGAGgEQAGgEAHAAQAHAAAGAEQAGADADAGQADAGAAAIIAAACIgCABIgiAAIgBAAIAAABQAAAEACAEQACACADACQADACADABQAEgBAEgCQADgBADgEIABAAIABAAIAGADQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAgBAAQgDAFgDADIgIADIgJACQgHAAgGgEgAgFgQQgDABgBAEQgCADAAAEIAXAAIABAAIAAgBIgBgHIgEgEQgDgDgEAAQgDAAgDADg");
	this.shape_23.setTransform(43.275,1.35);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAMAlIgBAAIgBgCIAAgiQAAgDgBgCQgCgCgFgBIgDABIgFACIgDAEIAAAjQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgJAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIAAhFQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAaIABAAIAAAAIAGgFIAFgCIAGgBQAHAAAEAEQAEAEABAIIAAAjQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_24.setTransform(36.85,0.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgLAYQgFgEgEgGQgDgFAAgJQAAgHADgGQAEgGAGgEQAFgEAHAAQAGABAEACQAFACADADIAEAHQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgJABQAAABAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIgDgEIgDgDIgFgBQgDAAgDADQgDACgBADQgCAFAAAFQAAAGACAFQACADADACQADADADAAQAFAAACgDIAGgGIAAAAIABAAIAHACQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIgCAFIgFAFQgDACgEABQgDACgFAAQgHAAgGgEg");
	this.shape_25.setTransform(30.5833,1.35);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgPAZQgEgCgBgEQgDgDAAgFIAAgjQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAIAAAhQgBAEADACQACACAEABQACAAADgCIAGgGIAAgiQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAIAAAxQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgGIgBgBIAAABQgFAEgEACQgEACgEAAQgFAAgDgCg");
	this.shape_26.setTransform(24.25,1.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgNAYQgGgEgDgGQgEgGAAgHQAAgIAEgGQADgGAHgEQAFgEAHAAQAIAAAGAEQAGAEADAGQAEAGgBAHQABAIgEAGQgEAGgFAEQgGAEgIAAQgHAAgGgEgAgGgPQgDACgCADQgBAFAAAFQAAAGABAEQACAEADACQADACADABQAEgBADgCQADgCACgEQABgEAAgGQAAgFgBgFQgCgDgDgCQgDgDgEAAQgDAAgDADg");
	this.shape_27.setTransform(17.8,1.35);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgEAlQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIgYhFIAAgBIABgBIAMAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIARA1QAAAAAAAAQAAAAAAAAQAAAAABAAQAAgBAAAAIASg0QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAIABABIAAABIgYBFQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_28.setTransform(10.625,0.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAMAbIgBAAIgBgCIAAghQAAgEgBgCQgCgCgFgBIgDABIgFACIgDAFIAAAiQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgJAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIAAgxQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIALAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAGIABABIAAgBIAFgEIAFgDIAHgBQAHAAAEAEQAEAEABAIIAAAjQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_29.setTransform(0.85,1.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgNAYQgGgEgDgGQgDgGgBgHQABgIADgGQADgGAHgEQAFgEAHAAQAIAAAGAEQAGAEADAGQADAGAAAHQAAAIgDAGQgEAGgFAEQgGAEgIAAQgHAAgGgEgAgGgPQgDACgBADQgCAFAAAFQAAAGACAEQABAEADACQADACADABQAEgBADgCQADgCABgEQACgEAAgGQAAgFgCgFQgBgDgDgCQgDgDgEAAQgDAAgDADg");
	this.shape_30.setTransform(-5.7,1.35);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgEAlIgBAAIAAgCIAAgxQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAJAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAxIgBACIgCAAgAgEgXIgBAAIgBgCIAAgJQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAJAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAJQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_31.setTransform(-10.575,0.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAJAjIgEAAQgFAAgEgDQgEgDAAgGIAAgdQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgGAAQgBAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAIAAIABgCIABgPQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAIAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAPIABACIALAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAGQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAIgMAAIgBABIAAAaQAAAEACABQACABADAAIAGAAIABAAIAAACIAAAFQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgDAAg");
	this.shape_32.setTransform(-14.775,0.45);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgSAXQgFgDABgHQgBgGAEgDQADgEAGgCQAHgDAIABIAEgBIACAAIABgBIAAgDQAAgEgEgCQgCgDgEAAQgDAAgDACQgDABgDADIAAABIgCAAIgIgCIAAAAIAAgCQADgFAFgDQAGgDAIgBQAIABAFACQAEACADADQABAEABAFIAAAiIAAACIgCAAIgIAAIgCAAIAAgCIAAgDQgBAAAAgBQAAAAAAAAQAAAAgBAAQAAABgBAAIgHAFQgDACgFAAQgHgBgFgEgAAFABIgFABIgEACIgFADIgBAFQABACACACQACACAEABIAFgBIADgDIADgCIACgDIAAgHQAAgBgBAAQAAgBAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_33.setTransform(-20.35,1.35);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgLAYQgFgEgEgGQgDgFAAgJQAAgHADgGQAEgGAGgEQAFgEAHAAQAGABAEACQAFACADADIAEAHQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgJABQAAABAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIgDgEIgDgDIgFgBQgDAAgDADQgDACgBADQgCAFAAAFQAAAGACAFQACADADACQADADADAAQAFAAACgDIAGgGIAAAAIABAAIAHACQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIgCAFIgFAFQgDACgEABQgDACgFAAQgHAAgGgEg");
	this.shape_34.setTransform(-26.2167,1.35);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgSAXQgEgDgBgHQABgGADgDQADgEAHgCQAGgDAHABIAGgBIABAAIAAgBIAAgDQAAgEgCgCQgDgDgFAAQgCAAgDACQgDABgCADIgBABIgCAAIgHgCIgCAAIABgCQACgFAGgDQAHgDAHgBQAHABAFACQAGACABADQACAEAAAFIAAAiIAAACIgBAAIgJAAIgBAAIgBgCIAAgDQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABAAAAIgIAFQgDACgFAAQgHgBgFgEgAAFABIgFABIgFACIgDADIgBAFQAAACACACQACACAFABIADgBIAFgDIACgCIABgDIAAgHQAAgBAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_35.setTransform(-32.55,1.35);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgEAlQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIgYhFIAAgBIABgBIAMAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIARA1QAAAAAAAAQAAAAAAAAQAAAAABAAQAAgBAAAAIASg0QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAIABABIAAABIgYBFQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_36.setTransform(-39.325,0.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgEAZQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgLQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAIALAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAgAgEgKQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgLQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAALQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAg");
	this.shape_37.setTransform(41.025,-10.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgNAZQgHgEgCgEIAAgBIAAgBIAGgEIABAAIABAAIAEAFIAEACIAGABIAGgBIAEgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgGgDIgKgCQgHgCgEgCQgDgEAAgFQAAgFACgEQADgEAFgDQAFgCAFAAQAIABAGACQAFADADAEIAAABIAAABIgHADIgBAAIgBAAQgBgDgEgCQgDgBgFAAQgCAAgEABQgDACAAADIABADQACACAEAAIALAEQAIABADADQADAFABAFQAAAFgEAEQgDAEgFACQgFABgHAAQgHAAgGgCg");
	this.shape_38.setTransform(36.6,-10.75);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgPAZQgDgCgCgDQgCgEAAgFIAAgjQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAhQABAEACACQACADAEAAQADgBADgCIAGgEIAAgjQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAABABIAAAwQgBABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgFIAAAAIgBAAQgFAFgEABQgDACgFAAQgEAAgEgCg");
	this.shape_39.setTransform(30.5,-10.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAMAbIgBgBIgBgBIAAghQAAgEgCgCQgCgCgEAAIgDABIgEACIgFADIAAAjQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgJAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgwQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAABAAIAKAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAEIAAABIABAAIAGgEIAEgDIAGgBQAIAAAEAEQAFAFAAAGIAAAkQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_40.setTransform(24.1,-10.8);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgNAYQgFgEgEgFQgDgHAAgIQAAgHADgHQAEgGAGgDQAFgDAHgBQAIABAGADQAFAEAEAGQADAGAAAHQAAAIgDAHQgEAFgGAEQgFADgIAAQgHAAgGgDgAgGgQQgDADgCAEQgBAEAAAFQAAAGABAEQACAFADACQADABADAAQAFAAACgBQADgCACgFQABgEAAgGQAAgFgBgEQgCgEgDgDQgDgCgEAAQgDAAgDACg");
	this.shape_41.setTransform(17.55,-10.75);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgbAlIgBgBIAAgBIAAhGIAAgBIABAAIAaAAQANAAAIAFQAIAFAAAJQAAAGgDAEQgDADgIADIAAABIAAAAQAIABAEAFQADAEAAAHQAAAKgHAFQgIAFgOAAgAgOAGIAAATQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABAAIAMAAQAGAAAEgDQAEgDAAgFQAAgEgCgDQgCgCgDgBQgDgCgEABIgMAAQAAAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAAAgAgOgYIAAASQAAAAAAAAQAAABABAAQAAAAAAAAQAAABABAAIAMAAIAEgBIAFgCIADgEIABgEQAAgGgEgCQgEgDgFAAIgMAAQAAAAgBAAQAAAAAAAAQAAABgBAAQAAAAAAABg");
	this.shape_42.setTransform(10.525,-11.8);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAJAjIgEAAQgFAAgEgCQgEgEAAgGIAAgdQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIgGAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgGQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIAIAAIABgBIABgPQAAAAAAgBQAAAAAAAAQABAAAAAAQAAgBAAAAIAIAAQABAAAAABQAAAAAAAAQABAAAAAAQAAABAAAAIAAAPIABABIALAAQAAAAAAABQABAAAAAAQAAAAAAAAQAAABAAAAIAAAGQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgMAAIgBABIAAAaQAAAFACABQACABADAAIAGAAIABAAIAAABIAAAGQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAIgDAAg");
	this.shape_43.setTransform(1.425,-11.65);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgOAZQgFgEgDgEIgBgBIABgBIAGgEIABAAIABAAIADAFIAGACIAGABIAFgBIAEgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIgGgDIgJgCQgIgCgDgCQgEgEAAgFQAAgFADgEQACgEAFgDQAFgCAGAAQAHABAFACQAGADACAEIABABIgBABIgGADIgBAAIgBAAQgCgDgDgCQgDgBgEAAQgEAAgCABQgDACAAADIABADQABACAEAAIALAEQAIABADADQAEAFgBAFQAAAFgDAEQgCAEgGACQgFABgGAAQgIAAgHgCg");
	this.shape_44.setTransform(-3.85,-10.75);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgPAZQgEgCgBgDQgDgEAAgFIAAgjQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAAAhQgBAEADACQACADAEAAQACgBADgCIAGgEIAAgjQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAAAwQAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgFIgBAAIAAAAQgFAFgEABQgEACgEAAQgFAAgDgCg");
	this.shape_45.setTransform(-9.95,-10.7);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgVAhQgHgDAAgHQAAgEACgCQADgCAEgCQABAAAAgBQAAAAAAAAQAAAAAAAAQAAAAgBAAIgEgDQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIABgDIADgCIAFgDIAAAAQABgBgBAAQgFgCgCgDQgCgEAAgEQAAgIAGgFQAGgEAMAAQAEAAAEABQAEABADACIABABIABgBIADgCIAEgCIADgBIACAAIAAACIAAAGIAAABIgCABIgDAAIgCAAQAAAAgBAAQgBABAAAAQAAAAAAABQAAAAAAAAIABACIAAAEQAAAEgCAEQgDADgFADQgFACgHAAIgHAAIgEABIgBACIACACIAFAAIANABQAKABAFAEQAEADAAAGQAAAIgHAFQgHAEgMAAQgOAAgHgDgAgNAPIgDADQgBAAAAABQAAAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAQAAABABABQAAAAAAABQABAAAAABQACACAEABIAKABQAHAAAEgDQADgCAAgDQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAgBgBQgCgBgEgBIgPAAIgBAAIgDAAgAgKgYQgDACAAAFQAAAEADACQADADAGAAQAFAAADgDQACgCAAgEQAAgFgCgCQgDgDgFAAQgGAAgDADg");
	this.shape_46.setTransform(-16.575,-9.975);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgPAZQgEgCgCgDQgCgEAAgFIAAgjQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAAAhQAAAEACACQACADAEAAQACgBADgCIAHgEIAAgjQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAwQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgFIAAAAIgBAAQgFAFgEABQgDACgFAAQgEAAgEgCg");
	this.shape_47.setTransform(-23.2,-10.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AAVAlQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIgGgPIAAgCIgBAAIgZAAIgBACIgGAQIgBAAIgBABIgKAAIgBgBIAAgCIAZhFIABgBIACAAIALAAQABAAAAAAQAAAAABABQAAAAABAAQAAABAAAAIAZBEIAAACIgBABgAgBgUIgJAaQgBAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIASAAQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIgJgaIAAgBg");
	this.shape_48.setTransform(-30.4625,-11.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72.2,-19.7,153,40.3);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(-116.175,39.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAVArQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgQgxIgBgBIAAABIgPAxIgBACIgCABIgMAAQgBAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBIgahOQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAABAAIACgCIAPAAIACACIABABIAQAyIABACIACgCIAPgyIABgBIACgCIALAAIACACIABABIAQAyIABACIABgCIAPgyIACgBIACgCIAKAAIACACIAAACIgaBOIgBACIgCABg");
	this.shape_1.setTransform(-128.0208,39.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgVAmQgKgFgFgKQgFgKAAgNQAAgMAGgJQAFgLAJgFQAKgGALAAQAMAAAKAGQAJAGAGAKQAFAJAAAMQAAANgFAKQgGAKgJAFQgKAGgMAAQgMAAgJgGgAgLgaQgEAEgCAGQgDAIAAAIQAAAJADAIQACAGAEADQAGAEAFAAQAHAAAFgEQAEgDADgGQACgIAAgJQAAgIgCgIQgDgGgEgEQgFgDgHAAQgFAAgGADg");
	this.shape_2.setTransform(-139.85,39.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgtA7QAAAAgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhwIABgCIACAAIAIAAIAIAAIAJAAIAIAAQAUAAAOAHQAOAHAHANQAGANAAASQAAASgHAOQgHANgOAHQgOAHgVAAgAgYgnIAABPQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABAAIAEAAQAPAAAIgEQAKgEAEgJQAFgKAAgPQAAgPgFgJQgEgJgJgEQgIgFgPAAIgFAAQgBAAAAAAQAAABgBAAQAAAAAAABQAAAAAAABg");
	this.shape_3.setTransform(-150.95,37.625);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgiA3QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgKIABgCIAEgBIAKAAQADAAADgBIAEgFIADgFQAAgDgBgCIgfhLQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAQAAIACABIACACIATA0IABABIABgBIAUg0IABgCIACgBIAMAAIACACIAAACIgiBTIgGAMQgDAFgEACQgEADgFABIgLABg");
	this.shape_4.setTransform(-166.0208,40.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgUAmQgJgFgGgJQgFgKAAgNQAAgNAFgKQAGgKAJgFQAKgGALAAQAMAAAJAGQAJAEAFALQAFAJAAANIAAADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAACQAAAGADAFQADAGAGACQAFADAFAAQAHAAAFgCQAGgDAEgGIACgBIABAAIAKAFQAAAAABABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAHgGAEQgFAFgHACQgHABgIAAQgLAAgKgGgAgJgbQgFAEgCAFQgDAFAAAGIAlAAIACAAIABgCQAAgFgCgFQgDgFgEgDQgEgDgHAAQgFAAgFADg");
	this.shape_5.setTransform(-175.625,39.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_6.setTransform(-185.625,39.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgVAmQgKgFgFgKQgFgKAAgNQAAgMAFgJQAGgLAJgFQAKgGALAAQANAAAJAGQAKAGAFAKQAFAJAAAMQAAANgFAKQgGAKgJAFQgJAGgNAAQgMAAgJgGgAgLgaQgEAEgDAGQgCAIAAAIQAAAJACAIQADAGAEADQAGAEAFAAQAHAAAFgEQAEgDADgGQACgIAAgJQAAgIgCgIQgDgGgEgEQgGgDgGAAQgFAAgGADg");
	this.shape_7.setTransform(-195.75,39.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AApA7IgCAAIgBgDIAAhSIAAgBIgBABIgeBTQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAIgKAAQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIgehSIgBgBIgBABIAABSIAAACIgCAAIgOAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAhwQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAcAAIACAAIABACIAcBKQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIABgBIAchJQAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAcAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAABwQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_8.setTransform(-208.575,37.625);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgVAmQgJgFgGgKQgFgKAAgNQAAgMAFgJQAGgLAKgFQAJgGALAAQAMAAAKAGQAJAGAGAKQAFAJAAAMQAAANgGAKQgEAKgKAFQgKAGgMAAQgLAAgKgGgAgKgaQgFAEgDAGQgCAIAAAIQAAAJACAIQADAGAFADQAEAEAGAAQAHAAAEgEQAFgDACgGQADgIAAgJQAAgIgDgIQgCgGgFgEQgFgDgGAAQgGAAgEADg");
	this.shape_9.setTransform(-225.3,39.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAgA7IgCAAIgCgCIg2hMIAAgBIgBABIAABMQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgOAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAhxQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAQAAIACAAIACACIAzBJIABABQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIAAhIQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAPAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAABxIgBACIgCAAg");
	this.shape_10.setTransform(-236.75,37.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgJAYIgCgBIAAgCIAIgSQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBAAgBAAIgCAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIAAgSQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIASAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAARIgBACIgNAXIgCABIgDABg");
	this.shape_11.setTransform(-71.9875,22.175);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape_12.setTransform(-77.825,16.475);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgWAnQgKgFgEgIIAAgCIABgBIAJgFIACgBIABABIAGAGQADADAFACQAEABAGABQAFgBAEgBQAEgBACgDQADgCAAgDQAAgDgDgDQgDgCgHgCIgPgEQgMgDgGgFQgGgFAAgJQAAgIAFgGQAEgGAIgDQAHgEAKAAQAMAAAJAFQAIAEAEAGIABACIgBACIgKAEIgBAAIgCAAQgDgEgFgDQgFgDgHAAQgGAAgFADQgEADAAAEQAAADACADQACACAGABIASAGQANADAFAFQAFAHAAAHQAAAJgEAGQgFAGgIADQgJADgKAAQgNAAgKgFg");
	this.shape_13.setTransform(-85.975,17.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgUAnQgJgGgGgJQgFgKAAgMQAAgNAFgLQAGgKAJgGQAKgFALAAQAMAAAJAFQAJAFAFALQAFAKAAAMIAAADQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAABQAAAHADAFQADAGAGACQAFAEAFAAQAHAAAFgDQAGgDAEgGIACgBIABAAIAKAFQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBAAQgEAHgGAEQgFAEgHACQgHACgIAAQgLAAgKgFgAgJgbQgFAEgCAEQgDAGAAAHIAlAAIACgBIABgCQAAgFgCgFQgDgEgEgEQgEgDgHAAQgFAAgFADg");
	this.shape_14.setTransform(-95.225,17.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgWArIgCAAIgBgDIAAhOQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAABAAIAPAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAKIABABQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQADgFAEgDIAIgEQAEgCAFAAQAFAAAAACIAAAQQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgFgBIgFAAIgHABIgFADIgFAGQgBACAAADIAAAwQAAABAAABQgBAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_15.setTransform(-103.5,17.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgUAnQgJgGgGgJQgFgKAAgMQAAgNAFgLQAGgKAJgGQAKgFALAAQAMAAAJAFQAJAFAFALQAFAKAAAMIAAADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAABQAAAHADAFQADAGAGACQAFAEAFAAQAHAAAFgDQAGgDAEgGIACgBIABAAIAKAFQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBAAQgEAHgGAEQgFAEgHACQgHACgIAAQgLAAgKgFgAgJgbQgFAEgCAEQgDAGAAAHIAlAAIACgBIABgCQAAgFgCgFQgDgEgEgEQgEgDgHAAQgFAAgFADg");
	this.shape_16.setTransform(-112.275,17.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQgBABAAAAIgGAAIgGABg");
	this.shape_17.setTransform(-120.975,16.475);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgOAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_18.setTransform(-129.525,17.825);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgIA7IgCAAIgBgDIAAhwQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIARAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAABwIgBACIgDABg");
	this.shape_19.setTransform(-137.3,16.225);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgVAnQgJgGgGgKQgFgKAAgNQAAgLAGgKQAFgKAKgHQAJgFALAAQAMAAAKAGQAKAFAFALQAFAKAAALQAAANgGAKQgEAKgKAGQgKAFgMAAQgLAAgKgFgAgKgaQgFAEgCAHQgDAGAAAJQAAAKADAGQACAHAFADQAFAEAFAAQAHAAAEgEQAFgDACgHQADgGAAgKQAAgJgDgGQgCgHgFgEQgEgDgHAAQgFAAgFADg");
	this.shape_20.setTransform(-149,17.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAgA7IgCAAIgBgCIg2hMIgBgBIgBABIAABMQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgOAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAhxQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAPAAIADAAIACACIAzBJIABABQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIAAhIQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAABxIAAACIgCAAg");
	this.shape_21.setTransform(-160.45,16.225);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgJAYIgCgBIAAgCIAIgSQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBAAgBAAIgCAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIAAgSQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIASAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAARIgBACIgNAXIgCABIgDABg");
	this.shape_22.setTransform(-172.9375,22.175);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgWAnQgKgFgEgIIAAgCIABgBIAJgFIACgBIABABIAGAGQADADAFACQAEABAGABQAFgBAEgBQAEgBACgDQADgCAAgDQAAgDgDgDQgDgCgHgCIgPgEQgMgDgGgFQgGgFAAgJQAAgIAFgGQAEgGAIgDQAHgEAKAAQAMAAAJAFQAIAEAEAGIABACIgBACIgKAEIgBAAIgCAAQgDgEgFgDQgFgDgHAAQgGAAgFADQgEADAAAEQAAADACADQACACAGABIASAGQANADAFAFQAFAHAAAHQAAAJgEAGQgFAGgIADQgJADgKAAQgNAAgKgFg");
	this.shape_23.setTransform(-179.675,17.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQgBABAAAAIgGAAIgGABg");
	this.shape_24.setTransform(-188.325,16.475);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_25.setTransform(-196.875,17.825);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgUAnQgJgGgGgJQgFgKAAgMQAAgNAFgLQAGgKAJgGQAKgFALAAQAMAAAJAFQAJAFAFALQAFAKAAAMIAAADQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAABQAAAHADAFQADAGAGACQAFAEAFAAQAHAAAFgDQAGgDAEgGIACgBIABAAIAKAFQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBAAQgEAHgGAEQgFAEgHACQgHACgIAAQgLAAgKgFgAgJgbQgFAEgCAEQgDAGAAAHIAlAAIACgBIABgCQAAgFgCgFQgDgEgEgEQgEgDgHAAQgFAAgFADg");
	this.shape_26.setTransform(-206.825,17.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAuArIgCAAIgBgDIAAg2QAAgGgEgDQgCgEgHAAQgDAAgEACQgDABgDACIgFAEIgBACIAAADIAAA1QAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAIgNAAIgCAAIgBgDIAAg2QgBgGgDgDQgDgEgGAAQgFAAgFADQgFADgFAFIAAA4QAAABAAABQAAAAAAAAQgBABgBAAQAAAAgBAAIgPAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhOQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgFQAEgBAGAAQAJAAAFAEQAGAEACAGIABABIABgBIAJgHIAJgFQAFgCAFAAQALAAAHAHQAGAGABAMIAAA5QAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_27.setTransform(-219.4,17.825);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgiA3QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgKIABgCIAEgBIAKAAQADAAADgBIAEgFIADgFIgBgFIgfhLQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAQAAIACABIACACIATA0IABABIABgBIAUg0IABgCIACgBIAMAAIACACIAAACIgiBTIgGAMQgDAFgEACQgEADgFABIgLABg");
	this.shape_28.setTransform(-231.7708,19.225);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgeAmQgHgHAAgKQAAgJAGgGQAFgGAKgDQAKgEANgBIAIgBIACAAIABgCIAAgDQAAgHgEgFQgEgDgIAAQgEAAgFACQgFACgEAGIgBABIgCAAIgNgDIgBgBIAAgCQAEgKAKgEQAJgFANAAQAMAAAIAEQAIADADAGQAEAGAAAIIAAA4IgBACIgCAAIgOAAIgCAAIgBgDIAAgFQAAgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBAAQgFAFgHAEQgFACgIAAQgNAAgHgGgAAJACIgJABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAGAAQAEAAADgBIAHgEIAEgFIACgFIAAgLQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAAAg");
	this.shape_29.setTransform(-241.525,17.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgrA7IgCAAIgBgDIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAsAAQANAAAKADQALAEAGAIQAGAIAAANQAAAMgGAHQgFAHgKAEQgJAEgNAAIgYAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAABIAAAqQAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAgAgWgnIAAAhQAAAAAAABQABAAAAABQAAAAAAAAQABAAAAAAIAVAAQAKAAAGgFQAGgEAAgKQAAgGgDgEQgDgEgFgCQgFgCgHAAIgTAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABAAAAg");
	this.shape_30.setTransform(-251.625,16.225);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgVAnQgKgGgFgKQgFgKAAgNQAAgLAFgKQAGgKAKgHQAJgFALAAQAMAAAKAGQAJAFAGALQAFAKAAALQAAANgGAKQgEAKgKAGQgKAFgMAAQgLAAgKgFgAgKgaQgFAEgCAHQgDAGAAAJQAAAKADAGQACAHAFADQAEAEAGAAQAHAAAEgEQAFgDACgHQADgGAAgKQAAgJgDgGQgCgHgFgEQgFgDgGAAQgGAAgEADg");
	this.shape_31.setTransform(-266.8,17.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAgA7IgCAAIgBgCIg2hMIgBgBIgBABIAABMQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgOAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAhxQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAQAAIACAAIACACIAzBJIABABQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIAAhIQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAABxIgBACIgBAAg");
	this.shape_32.setTransform(-278.25,16.225);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgWAnQgKgFgEgHIAAgDIABgBIAJgEIACgBIABABIAGAFQADAEAFABQAEABAGAAQAFAAAEgBQAEgBACgDQADgCAAgDQAAgDgDgDQgDgCgHgCIgPgEQgMgCgGgGQgGgFAAgJQAAgIAFgGQAEgGAIgEQAHgDAKAAQAMAAAJAEQAIAFAEAGIABACIgBACIgKAEIgBAAIgCgBQgDgEgFgCQgFgDgHAAQgGAAgFADQgEACAAAFQAAADACADQACABAGACIASAGQANADAFAFQAFAHAAAIQAAAIgEAGQgFAFgIAEQgJADgKAAQgNAAgKgFg");
	this.shape_33.setTransform(-132.125,-3.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAUA7IgCAAIgBgDIAAg3QAAgFgDgDQgEgEgGAAIgGABIgHAEIgHAGIAAA4QAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgPAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAqIAAABIABgBIAKgHQAFgDADgBIAJgBQANAAAGAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_34.setTransform(-141.475,-5.175);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape_35.setTransform(-150.825,-4.925);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhOQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_36.setTransform(-159.375,-3.575);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgVAnQgJgGgGgKQgFgKAAgMQAAgMAFgLQAGgKAKgGQAJgFALAAQAMAAAKAGQAJAFAGAKQAFALAAAMQAAAMgGAKQgEAKgKAGQgKAFgMAAQgLAAgKgFgAgKgZQgFADgDAHQgCAGAAAJQAAAKACAGQADAHAFAEQAEADAGAAQAHAAAEgDQAFgEACgHQADgGAAgKQAAgJgDgGQgCgHgFgDQgFgEgGAAQgGAAgEAEg");
	this.shape_37.setTransform(-169.5,-3.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AApA7IgCAAIgBgDIAAhSIAAgBIgBABIgeBTQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAIgKAAQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIgehSIgBgBIgBABIAABSIAAACIgCAAIgOAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhwQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAcAAIACAAIABACIAcBKQAAABAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIABgBIAchJQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAcAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAABwQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_38.setTransform(-182.325,-5.175);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgnA8IgCAAIgBgDIAAgKIAAgCIACgCIAEgEIAfgeIAMgKIAHgJIAEgHQABgDAAgEQAAgGgDgEIgHgGQgEgCgFAAQgEAAgEACQgFACgEADQgEAEgDAGIgCABIgCgBIgMgGIgCgCIABgDQAIgMALgFQALgGAMAAQAMAAAJAEQAJAEAGAIQAFAIAAALQAAAHgCAGQgDAGgFAFIgOANIgdAaIgBABIABABIAzAAQABAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAPIAAACIgDAAg");
	this.shape_39.setTransform(-199.325,-5.275);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgeA7QAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgNQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIASAAQABAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAIAAhKQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAAAgBAAIgRAFQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIAAgKIABgCIABgBIAagNIADgBIACAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAABgQAAABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIARAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAANIgBABIgBABg");
	this.shape_40.setTransform(-208.8,-5.175);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgEAlQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgaIgbAAIgDAAIgBgCIAAgKQAAgBABAAQAAgBAAAAQAAAAABAAQAAgBABAAIAcAAIAAAPIAOAAIAAAbQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAgAAIAIIAAgPIAbAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABIAAAJQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAgAAIAIgAgGAIIAAgPIAOAAIAAAPgAAIgHIgOAAIAAgbIAAgCIACgBIAJAAQABABAAAAQABAAAAAAQABAAAAABQAAAAAAABIAAAbg");
	this.shape_41.setTransform(-221.85,-5.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-304.5,-16.7,255.4,66.2);


(lib.Promo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6CC14C").s().p("AggAzIgCAAIgBgDIAAhfQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIBDAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgqAAQgBAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIAAAVQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAALQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgdAAQgBAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAIAAAlQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape.setTransform(88.575,-13.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6CC14C").s().p("AggAzIgCAAIgBgDIAAhfQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgqAAQgBAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAABIAAAVQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgdAAQgBAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAIAAAlQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(79.875,-13.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6CC14C").s().p("AgYAuQgLgGgFgMQgGgLAAgRQAAgPAGgMQAGgMAKgGQALgHANAAQAPAAAKAHQALAGAFAMQAGAMAAAPQAAAQgGAMQgFALgLAHQgKAGgPAAQgNAAgLgGgAgPgaQgGAIAAASQAAATAFAIQAGAIAKAAQALABAGgJQAFgIAAgTQAAgSgFgIQgGgJgLAAQgKAAgFAJg");
	this.shape_2.setTransform(69.975,-13.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC14C").s().p("AAUAwQgFgDgEgHQgDgHAAgHQAAgJADgGQAEgHAFgCQAHgEAHgBQAHABAGAEQAGACADAHQAEAGAAAJQAAAHgEAHQgDAHgGADQgGAFgHAAQgHAAgHgFgAAcAIQgDACAAAEIgBAKIABAKQAAADADACQACADAEAAQADAAACgDIAEgFIABgKIgBgKQgBgEgDgCQgCgDgDAAQgEAAgCADgAgkA0QAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgDIBAhhIACgBIABgBIAHAAIACABQAAAAAAAAQABABAAAAQAAAAgBAAQAAABAAAAIhBBjQgBAAAAABQAAAAgBAAQAAAAgBAAQAAABAAAAgAguABQgGgDgDgGQgEgHAAgIQAAgHAEgHQAEgHAGgEQAFgDAHgBQAIABAGADQAFAEAEAHQAEAHgBAHQABAIgEAHQgDAGgGADQgGAFgIAAQgHAAgGgFgAgmgmQgCACgCAEQgBAEAAAFIABAKQACAEACACQACACADAAQAGABACgFQACgFAAgJQAAgIgCgFQgDgFgFAAQgDAAgCADg");
	this.shape_3.setTransform(71.15,-28.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6CC14C").s().p("AgnBTQgRgMgKgVQgKgUAAgdQAAgVAGgRQAGgSAKgMQALgNAOgHQAOgGAPAAQARAAAOAGQAOAHAKANQAKAMAGASQAGARAAAVQAAAcgKAVQgKAVgRAMQgSALgWAAQgVAAgSgLgAgRg5QgHAHgEAOQgEAPAAAWQAAAXAEANQAEAOAHAHQAHAGAKAAQALAAAHgGQAIgHADgOQAEgNAAgXQAAgWgEgPQgEgOgHgHQgHgGgLAAQgKAAgHAGg");
	this.shape_4.setTransform(54.475,-19.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6CC14C").s().p("AALBcQgFAAgBgFIAAgkQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIhJAAQgGAAAAgFIAAgUIABgGIAGgHIBJhhIAFgEIAFgBIAgAAQADAAAAAEIAABnQAAABABABQAAAAAAAAQAAABABAAQAAAAABAAIAVAAQAEAAAAAEIAAAVQAAAFgFAAIgUAAQAAAAgBAAQAAAAgBAAQAAABAAAAQgBABAAABIAAAjQAAAFgGAAgAADgtIgsA9QgDADAFAAIArAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIAAg9IgBgDg");
	this.shape_5.setTransform(36.1,-19.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6CC14C").s().p("AgsBTQgTgLgKgVQgLgVAAgdQAAgcALgWQAKgVAUgMQATgLAYAAQAaAAATALQATAMALAVQAKAVAAAcQAAAdgKAWQgLAUgTAMQgTAMgaAAQgZAAgTgMgAgdgvQgJAPAAAhQAAAhAJAPQAKAPATAAQAVAAAJgOQAKgPAAgiQAAghgKgPQgKgQgUAAQgTAAgKAQg");
	this.shape_6.setTransform(12.875,-19.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6CC14C").s().p("AgpBTQgTgMgKgVQgKgVAAgcQAAgdAKgUQALgWATgMQATgLAZAAQAUAAAQAIQAQAHAKAMQAJALADAOIAAAFQAAAAAAABQAAAAgBAAQAAABgBAAQgBAAAAAAIghAFIgCgBIgCgDQgBgIgFgHQgEgHgIgEQgHgEgKAAQgLAAgJAHQgJAGgEAOQgFAOAAAWQAAAXAFAOQAFAOAJAHQAJAGALAAQAIAAAGgDQAHgBAEgFQAEgDADgGQADgFABgGIAAgHQABAAgBgBQAAgBAAAAQAAgBgBAAQAAAAgBAAIgeAAIgDgBIgBgEIAAgSQAAgCAEgBIBCAAQAEABABAAQABABAAAAQAAABABAAQAAABAAAAQAAABAAABIAABTIgBADIgCABIgIAAIgEgBIgDgDIgHgSIgBAAIgCAAIgLALQgGAHgKADQgKAEgPAAQgYAAgSgMg");
	this.shape_7.setTransform(-6.125,-19.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6CC14C").s().p("AgsBTQgTgLgKgVQgLgVAAgdQAAgcALgWQAKgVAUgMQATgLAYAAQAaAAATALQATAMALAVQAKAVAAAcQAAAdgKAWQgLAUgTAMQgTAMgaAAQgZAAgTgMgAgdgvQgJAPAAAhQAAAhAJAPQAKAPATAAQAVAAAJgOQAKgPAAgiQAAghgKgPQgKgQgUAAQgTAAgKAQg");
	this.shape_8.setTransform(-24.925,-19.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6CC14C").s().p("AhGBcIgEgBIgBgDIAAitQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAIBDAAQAkAAATAMQATANAAAXQAAAOgHAKQgIAJgRAIIgBABIABAAQATAGAJALQAJAKAAAQQAAAagUAMQgTAMglAAgAgfASIAAAoQAAAEADAAIAbAAQAPAAAIgGQAIgHAAgLQAAgHgEgGQgEgFgGgDQgHgDgJAAIgbAAQgEAAAAAEgAgfg5IAAAmQAAAEADAAIAcAAIALgCQAFgBAEgCQAEgDACgFQACgEAAgFQAAgNgIgFQgJgHgMAAIgaAAQgEAAAAAFg");
	this.shape_9.setTransform(-43.075,-19.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#47C434").s().p("AgDAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgUIgUAAIgCgBIgBgBIAAgIQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAVAAIAAANIAAgNIAAgUIABgCIACgBIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAVIgNAAIANAAIAAANIgNAAIANAAIAAAVQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAgAAHAHIAAgNIAVAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAgAAHAHg");
	this.shape_10.setTransform(19.725,-4.375);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#48C435").ss(1,1,1).p("AAzAAIKVAAArHAAIKAAA");
	this.shape_11.setTransform(20.275,-4.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAIAyQgJAAgFgFQgFgEAAgJIAAgpQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAgJQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIALAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAgBIABgVQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIALAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAAAVIABABIAQAAQAAAAAAAAQABABAAAAQAAAAAAAAQABABAAAAIAAAJQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgQAAQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAAkQAAAGADACQABACAGAAIAIAAIABAAIABACIAAAHQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAIgFAAIgGABg");
	this.shape_12.setTransform(83.2,9.575);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgGA0IgBgBIgBgBIAAhFQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIANAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAABEIAAACIgEABgAgGgfIgCgBIAAgDIAAgNQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAABIAAANQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_13.setTransform(78.6,9.35);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AARAmIgBgBIgCgCIAAgvQAAgFgDgDQgCgDgGAAIgGABIgFADIgGAFIAAAxQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgNAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGIAHgDQAEgCAFAAQAKAAAGAGQAGAGAAAKIAAAyQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_14.setTransform(72.75,10.775);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgXAwQgIgFgEgJQgEgJAAgNIAAg9QAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAQAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABAQAAAMAGAFQAFAGAJAAQAHAAAFgDQAFgCACgFQADgFAAgJIAAg/QAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIANAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAA/QAAAOgFAJQgEAIgJAEQgJAEgNAAQgOAAgJgFg");
	this.shape_15.setTransform(63.575,9.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgdAwQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgIIAAgCIAEgBIAJAAQADAAACgBIAEgEIACgFQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBgBIgbhAIABgDIACgBIAOAAIACABIABACIAQAtIABABQABAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIARguIABgBIACgBIAKAAIABABQAAAAABAAQAAABAAAAQAAAAAAAAQgBABAAAAIgdBJIgGAKQgBAEgEADQgDACgFABIgKAAg");
	this.shape_16.setTransform(51.775,12);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_17.setTransform(44.625,10.775);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgRAiQgJgFgEgJQgFgIAAgLQAAgLAFgJQAFgJAIgFQAJgFAJABQAKgBAIAFQAJAFAEAIQAEAJAAALIAAACIgCABIgxAAIgBABIAAACQAAAFACAFQADAFAFACQAEACAFABQAGAAAFgCQAEgDAFgFIABgBIABABIAJADQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAAAQgEAHgFAEQgFADgGACQgFABgIAAQgKAAgIgEgAgIgYQgDAEgDAEQgCAEAAAGIAgAAIACgBIAAgBQAAgEgBgFQgCgDgEgEQgEgCgGAAQgEAAgFACg");
	this.shape_18.setTransform(37.4,10.85);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgDAlQgDAAgCgCIgbhEIAAgCIACgBIAPAAIABABIABABIARAtQABABAAAAQAAAAAAAAQABAAAAAAQAAgBABgBIASgtIABAAIABgBIALAAIABABIAAABIgcBFQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_19.setTransform(29.4,10.85);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhiQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIguAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAALIAAAAIgCABIgfAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAIAwAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAALIgBABIgCABg");
	this.shape_20.setTransform(21.225,9.35);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgIA0QAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAg5QAAAAgBgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIgMAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIADgBIAKAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABgBAAAAIAAgJQAAgJAEgFQAFgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAIIAAABIgCABIgIAAQgEAAgCACQgCADABAEIAAAHQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIACABIAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgNAAQAAAAgBABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAA5QAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_21.setTransform(10.85,9.35);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgIA0QAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAg5QAAAAgBgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIgMAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIADgBIAKAAQAAAAABAAQAAAAAAgBQAAAAAAAAQABgBAAAAIAAgJQAAgJAEgFQAFgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAIIAAABIgCABIgIAAQgEAAgCACQgCADABAEIAAAHQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIACABIAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgNAAQAAAAgBABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAA5QAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_22.setTransform(5.45,9.35);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgYAvQgKgGgGgMQgGgMAAgRQAAgQAGgMQAGgMALgGQAKgHANAAQAPAAAKAHQAKAGAGAMQAGAMAAAQQAAARgGAMQgFAMgLAGQgKAHgPgBQgNABgLgHgAgSgcQgGAJAAATQAAAVAGAJQAHAIALABQANgBAGgIQAGgJAAgVQAAgTgGgJQgGgKgNAAQgLAAgHAKg");
	this.shape_23.setTransform(-2.725,9.35);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgVAvQgJgGgFgMQgGgMAAgQQAAgMAEgKQACgKAHgHQAFgHAHgDQAIgEAJAAQAIAAAIAEQAHADAGAHQAFAHAEAKQADAKAAAMQAAAQgFAMQgGAMgKAGQgIAGgNAAQgLAAgKgGgAgKghQgEAEgDAIQgCAJAAANQAAANACAJQADAIAEAEQAEAEAGAAQAHAAAEgEQAFgEADgIQACgJAAgNQAAgNgCgJQgDgIgFgEQgEgEgHAAQgGAAgEAEg");
	this.shape_24.setTransform(-15.9,9.325);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgVAvQgJgGgFgMQgGgMAAgQQAAgMADgKQAEgKAFgHQAGgHAIgDQAHgEAJAAQAIAAAIAEQAIADAFAHQAFAHAEAKQADAKAAAMQAAAQgFAMQgGAMgKAGQgJAGgMAAQgLAAgKgGgAgKghQgFAEgCAIQgDAJAAANQAAANADAJQACAIAFAEQAEAEAGAAQAHAAAEgEQAFgEADgIQACgJAAgNQAAgNgCgJQgDgIgFgEQgEgEgHAAQgGAAgEAEg");
	this.shape_25.setTransform(-25,9.325);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgZA0QgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgLQAAgBAAAAQAAgBABAAQAAAAAAAAQABgBABAAIAPAAIABgBIAAhAQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgOAFQgBAAgBAAQAAAAAAAAQgBAAAAgBQAAgBAAgBIAAgIIAAgBIACgBIAWgLIADgBIACgBIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABTQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAOAAQABAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAALIAAABIgDABg");
	this.shape_26.setTransform(-33.3,9.35);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgBA+QgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgHIAAgBIgCgBQgKABgIgEQgHgDgHgHQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAIgIIABgBIACABIAKAIQAFAEAHAAQABAAAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIAAgbIAAgDIgCgBQgLgDgHgDQgHgEgCgGQgDgGAAgHQAAgHADgHQAEgFAHgFQAHgEAJgBIABAAIABgCIAAgGIABgBIABAAIAHAAIACAAIAAACIAAAGQAAAAAAAAQAAABABAAQAAAAAAAAQAAAAABAAQAIABAGADIALAHQAAAAABABQAAAAAAABQAAAAAAABQAAAAgBAAIgHAIIgBABIgCgBIgHgFIgIgDIgBAAIgBABIAAAbQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABABIAHACQAHACAGADQAFAEADAGQADAGAAAGQAAAJgEAGQgEAGgGAEQgHAEgKAAIgBABIgBABIAAAGQAAABAAABQAAAAAAABQgBAAAAAAQgBAAgBAAgAAHALIAAAbQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAHgBAEgDQAEgEAAgFQAAgGgDgDQgEgEgIgCIgBAAIgBABgAgFgnQgIABgEAFQgDADAAAGIABAFIAEAFIAIADIADAAIAAgCIAAgYQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAgBAAIAAAAg");
	this.shape_27.setTransform(-41.2781,9.45);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgHA0QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAgPQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIAPAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAQQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAgAgCAWIgDgBIAAgBIgEhFIAAgCIABAAIARAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIgEBFIgBABIgDABg");
	this.shape_28.setTransform(87.25,-43.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgRAhQgJgEgEgIQgFgJAAgLQAAgMAFgIQAFgJAJgFQAIgEAJgBQALABAHAEQAJAEAEAJQAEAJAAALIAAADIgCABIgxAAIgBAAIAAABQAAAGACAFQAEAEAEADQAEADAFgBQAGAAAEgBQAGgDADgGIACAAIABAAIAJAEQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgEAGgFAEQgFADgGACQgFACgIAAQgJgBgJgFgAgHgXQgFADgCAEQgCAFAAAFIAgAAIACAAIAAgCQABgEgCgFQgCgEgEgCQgEgDgGAAQgEAAgEADg");
	this.shape_29.setTransform(81.4,-42.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgFA0QgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhiQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIANAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAABiIAAACIgDABg");
	this.shape_30.setTransform(75.525,-43.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgZAhQgHgGAAgJQAAgIAFgFQAFgFAIgDQAJgDAMgBIAGgBIACAAIABgCIAAgDQAAgGgEgDQgEgEgGAAQgEAAgEADQgFACgDAEIgBACIgBAAIgMgEIgBgBIABgBQADgJAJgDQAHgFALAAQALAAAHADQAHAEADAEQADAGAAAHIAAAwIgBACIgCABIgLAAIgCgBIgBgDIAAgDQAAgBAAAAQgBgBAAAAQAAAAgBABQAAAAgBABQgFAEgFACQgFADgHAAQgLAAgFgGgAAAADIgHACQgEACgBACQgCAEAAACQAAAFAEAEQADACAGAAIAGgBIAGgDIADgFQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIAAgKQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgFAAIgIACg");
	this.shape_31.setTransform(69.6,-42.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgFIgBgDIABgCIAJgFIADgCIACACIAGAHQAEADAEACIALABQAJgBAGgCQAGgEAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgFgDgFQgCgFAAgHQAAgIAEgIQAFgGAJgFQAJgDAKAAQAIAAAGABQAHACAFAEQAGADADAEIABACIgBACIgKAHIgBAAIgCgBQgDgEgFgCQgFgDgIgBQgJAAgFAEQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMADAGAHQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAFgMAAQgJAAgIgDg");
	this.shape_32.setTransform(61.2667,-43.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_33.setTransform(51.175,-42.475);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgRAhQgIgEgFgIQgFgJAAgLQAAgMAFgIQAFgJAJgFQAIgEAJgBQAKABAJAEQAIAEAEAJQAEAJAAALIAAADIgCABIgxAAIgBAAIAAABQAAAGACAFQADAEAFADQAEADAFgBQAGAAAEgBQAGgDADgGIABAAIACAAIAJAEQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgFAGgEAEQgFADgGACQgGACgHAAQgJgBgJgFgAgHgXQgEADgDAEQgCAFAAAFIAgAAIACAAIABgCQAAgEgCgFQgCgEgEgCQgEgDgFAAQgFAAgEADg");
	this.shape_34.setTransform(43.95,-42.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAoAmIgCgBIgBgCIAAgvQAAgFgDgDQgCgDgGAAIgGABIgFADIgFADIgBACIAAADIAAAuQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgCgBIAAgCIAAgvQAAgFgDgDQgDgDgFAAQgFAAgEACQgEACgFAFIAAAxQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgNAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAhEQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAOAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHIAAABIABgBIAIgGQAEgCAEgBQAEgCAFAAQAHAAAEAEQAGADABAGIABAAIABAAIAIgHQAEgDAEgBQAEgCAFAAQAKAAAGAGQAFAGAAAKIAAAyQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_35.setTransform(33.55,-42.475);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAnAmIgBgBIAAgCIAAgvQAAgFgEgDQgCgDgFAAIgHABIgFADIgEADIgBACIgBADIAAAuQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgBgBIgBgCIAAgvQAAgFgDgDQgCgDgGAAQgFAAgEACQgEACgFAFIAAAxQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAhEQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHIAAABIACgBIAHgGQAEgCAEgBQAEgCAEAAQAIAAAFAEQAEADACAGIABAAIACAAIAHgHQAEgDAEgBQAFgCAEAAQAKAAAFAGQAHAGAAAKIAAAyQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_36.setTransform(20.8,-42.475);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgVAjQgFgDgDgFQgDgFAAgGIAAgyQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAIANAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAAuQAAAGADADQADADAGAAQAEAAAEgCIAJgHIAAgxQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAABEQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgGADQgFADgGAAQgGAAgFgDg");
	this.shape_37.setTransform(10.225,-42.325);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgFIgBgDIABgCIAJgFIADgCIACACIAGAHQAEADAEACIALABQAJgBAGgCQAGgEAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgFgDgFQgCgFAAgHQAAgIAEgIQAFgGAJgFQAJgDAKAAQAIAAAGABQAHACAFAEQAGADADAEIABACIgBACIgKAHIgBAAIgCgBQgDgEgFgCQgFgDgIgBQgJAAgFAEQgFAEAAAGIABAEQABADADACIAIADIAVAHQAMADAGAHQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAFgMAAQgJAAgIgDg");
	this.shape_38.setTransform(1.4667,-43.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgIA0QAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAgBIAAg4QAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAgBAAIgLAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgIIABgCIACAAIAKAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgJQAAgJAGgFQAEgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAAIIgBACIgBAAIgIAAQgEAAgCADQgBACgBAEIAAAHQAAABABAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIACAAIAAACIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAAA4QAAABAAABQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_39.setTransform(-8.75,-43.9);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgSAhQgJgEgFgJQgEgJAAgLQAAgKAFgJQAFgJAIgEQAJgGAJAAQALAAAIAGQAJAEAEAJQAFAJAAAKQAAALgFAJQgFAJgIAEQgIAFgLABQgKgBgIgFgAgJgWQgEACgDAHQgCAFAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDACgGQADgFgBgJQABgIgDgFQgCgHgEgCQgEgDgGgBQgFABgEADg");
	this.shape_40.setTransform(-15.7,-42.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgUAwQgHgEgEgIQgDgJAAgMQAAgMAEgIQAEgJAHgEQAHgFAJAAQAFAAAEACQAFACAEADIACABIAAgCIAAggQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAOAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABiIAAACIgDAAIgMAAIgCAAIgBgCIAAgFIAAgBIgBABIgFAEIgHADQgEACgFAAQgIAAgHgFgAgHgIQgEACgDAGQgCAFAAAKQAAAJACAGQADAGAEACQAEADAEAAQAFAAADgCQAEgCACgEQACgDAAgDIAAgfIgHgFQgEgCgEAAQgFAAgEADg");
	this.shape_41.setTransform(-27.175,-43.825);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AARAmIgCgBIAAgCIAAgvQAAgFgDgDQgDgDgGAAIgFABIgGADIgGAFIAAAxQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIANAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAHIAAABIABgBIAIgGIAHgDQAEgCAEAAQALAAAGAGQAGAGAAAKIAAAyQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_42.setTransform(-35.3,-42.475);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhiQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIguAAQAAAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABIAAAYQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAAAQAAABABAAQAAABAAAAIAAAKIAAABIgCABIgfAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAABABAAIAwAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAALIgBABIgCABg");
	this.shape_43.setTransform(-43.725,-43.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.6,-54.2,175.7,74.2);


(lib.logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Logo();
	this.instance.setTransform(-160,-25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160,-25,320,50);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AF4A6QgJgFgEgIIgBgCIABgCIAMgFIABABIAGAGQAEADAEABQAFACAGAAQAFAAAFgCQAEgBADgCQACgDAAgDQAAgDgDgDQgCgCgIgCIgRgEQgNgDgFgGQgHgGAAgJQAAgIAGgGQADgGAJgEQAHgDAMAAQAMAAAJAEQAJAFAEAGIABACIgBACIgKAFIgBAAIgDgBQgDgEgEgDQgGgDgHAAQgIAAgEADQgFADAAAFQAAADACABQACACAHACIAUAGQANADAFAHQAGAGgBAJQAAAIgEAHQgFAFgJAEQgJADgLAAQgOAAgLgFgAEIA6QgKgGgFgLQgFgLAAgQIAAhIQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIATAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAAAIAABMQAAAOAGAHQAGAGAMAAQAJAAAFgDQAGgCAEgHQADgGAAgKIAAhLQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAIARAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAABLQAAARgGAKQgFAKgLAFQgLAEgPAAQgRAAgLgFgABDA5QgKgFgGgLQgFgKAAgNQAAgOAFgJQAGgKAKgHQAKgFAMAAQAKAAAHADQAHAEAGAFQAEAFACAHQAAAAAAABQAAAAAAABQAAAAAAAAQgBABgBAAIgOAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgEgGQgDgEgDgBQgDgCgEAAQgHAAgFAEQgFAEgDAFQgCAIAAAJQAAALACAHQAEAHAEADQAGAEAHAAQAHAAAFgEQAFgEAEgHIABgBIACAAIAKADQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAIgEAIQgDAFgFADQgFAEgGACQgHACgHAAQgMAAgKgGgAguA4QgHgGAAgLQAAgJAFgHQAFgHAMgDQAKgEAPgBIAHAAIACgBIABgCIAAgEQgBgGgDgEQgEgEgIAAQgFAAgFACQgGADgDAGIgBABIgCAAIgPgDIAAgBIAAgDQAEgJAKgGQAKgEAOAAQAMAAAIADQAIAEAEAGQADAGAAAIIAAA6IgBADIgBAAIgPAAIgCgBIgBgDIAAgEQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAABgBAAQgFAFgHADQgGADgIAAQgOAAgHgHgAgFATIgKACIgIADQgFACgCADQgCADAAAEQAAAGAEADQAFAEAGAAQAFAAADgCIAHgEIAEgFQABgCABgDIAAgLQAAgBgBgBQAAAAAAgBQAAAAgBgBQAAAAAAAAgAklA5QgLgFgFgLQgGgKAAgNQABgOAFgJQAGgKAKgHQAKgFAMAAQANAAAKAGQAKAGAGAKQAEAJAAAOQAAANgFAKQgFALgKAFQgKAGgNAAQgNAAgJgGgAkbgJQgEAEgDAFQgDAIABAJQgBAKADAIQADAGAEAEQAFAEAHAAQAHAAAFgEQAEgEADgGQADgIAAgKQAAgJgDgIQgDgFgEgEQgFgEgHAAQgHAAgFAEgAmcA3QgNgIgHgOQgGgPAAgSQAAgTAGgOQAHgOANgIIADgCQALgFAPAAQAJAAAIADIAGACIAIAFQAHAFAEAGQAEAHABAHIABADIgCABIgTABIgBAAIgBgCQgDgJgFgGQgHgGgKAAQgOAAgIALQgHALAAAXQgBAXAIALQAHALAQAAQAKAAAIgFQAGgFAFgMQAAAAAAgBQABAAAAAAQABAAAAAAQABAAABAAIANADIABABQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgEAJIgGAJQgEAFgGAEQgFADgIADQgHACgJAAQgRAAgMgIgACaA4QgFgFAAgLIAAgwQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAgKQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIAMAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAABAAIACgaQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAOAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAaQAAAAABAAQAAABAAAAQAAAAAAAAQABAAAAAAIATAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgSAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAsQAAAGADADQACACAGAAIAKAAIABABIABACIAAAIQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgSABQgMAAgGgFgAhkA4QgFgFAAgLIAAgwQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAIgMAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIANAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIACgaQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAAAAAIAPAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAAAIAAAaQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIATAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAAAKQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgSAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAAsQAAAGADADQACACAGAAIAKAAIACABIABACIgBAIQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgSABQgLAAgHgFgAiZA9IgCAAIgBgDIAAg5QAAgFgDgEQgEgDgGAAIgIABIgHAEIgHAGIAAA6QAAADgDAAIgPAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAhRQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIARAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAJIAAABIABgBIAKgHIAJgFQAFgBAGAAQAMAAAHAHQAHAHAAAMIAAA7QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(9.25,0.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(0.4,1,1).p("AqCiOIUFAAIAAEdI0FAAg");
	this.shape_1.setTransform(18.325,0.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(1,1,1).p("AA1AAIgeAjAg0AAIBpAAAAcgiIAZAi");
	this.shape_2.setTransform(66.325,0.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC24D").s().p("AqCCPIAAkdIUFAAIAAEdgAH3AgIAegiIgZgjIAZAjIhqAAIBqAAgAIVgCgAIVgCg");
	this.shape_3.setTransform(18.325,0.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46.9,-14.5,130.5,30.5);


// stage content:
(lib.WBAY_219645_MM_320x50_V1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#010101").ss(1,1,1).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(390));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(262,32.1,0.6,0.6,0,0,0,0.1,0.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({_off:false},0).to({y:24.6,alpha:1},13).wait(347));

	// T3
	this.instance_1 = new lib.T3("synched",0);
	this.instance_1.setTransform(153.5,9.35);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(270).to({_off:false},0).to({y:24.35,alpha:1},14,cjs.Ease.get(1)).wait(106));

	// T2
	this.instance_2 = new lib.T2("synched",0);
	this.instance_2.setTransform(263.75,11.25,0.6,0.6,0,0,0,0.1,0.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(136).to({_off:false},0).to({y:16.25,alpha:1},13,cjs.Ease.get(1)).wait(107).to({startPosition:0},0).to({alpha:0},14).to({_off:true},1).wait(119));

	// Promo
	this.instance_3 = new lib.Promo("synched",0);
	this.instance_3.setTransform(148.2,27.45,0.6,0.6,0,0,0,4.6,-16.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(14).to({_off:false},0).to({y:24.95,alpha:1},16,cjs.Ease.get(1)).wait(93).to({startPosition:0},0).to({alpha:0},13).to({_off:true},1).wait(253));

	// logo
	this.instance_4 = new lib.logo("synched",0);
	this.instance_4.setTransform(160,15);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({y:25,alpha:1},14,cjs.Ease.get(1)).wait(376));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(159,14.6,162,36.4);
// library properties:
lib.properties = {
	id: 'ECAEFFBAF1704CA9B680B457A657B9CE',
	width: 320,
	height: 50,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Logo.png", id:"Logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['ECAEFFBAF1704CA9B680B457A657B9CE'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;