(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.IMG1 = function() {
	this.initialize(img.IMG1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.IMG2 = function() {
	this.initialize(img.IMG2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.IMG3 = function() {
	this.initialize(img.IMG3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.LOGO = function() {
	this.initialize(img.LOGO);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.REDBG = function() {
	this.initialize(img.REDBG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBVQgFgEAAgJQAAgHAFgEQAEgFAIABQAHAAAEAEQAFAEAAAHQAAAJgFAEQgEAFgHgBQgIABgEgFgAgDAiIgBgBIgGhDQgDgbgGgYQAAgBAGgCIANgBIAOABQAGACAAABQgGAWgDAZIgGA/IgBAIIgBABIgDABg");
	this.shape.setTransform(136.625,52.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAvBXIg1h+IgoB+QAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAgBABQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAgBAAAAIg0iWQgDgMgFgFQgFgDgHAAIgBgCIABgCIAFABIAPABIAkgBIALgBIABACIgBACQgOAAAAAMQAAAGACAHIAgBdIAmh6IADgBIAEABIA1B8IAXhVQACgJAAgGQAAgUgVAAIAAgCIAAgCIAQABIAWABIANgBIAMgBIAAACIAAACQgLAAgJAJQgLAIgEAQIgmCJQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAgBABQAAgBgBAAQAAAAgBAAQAAAAAAAAQAAgBgBAAg");
	this.shape_1.setTransform(120.45,52.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgyBOQgUgMgLgVQgMgVAAgYQAAgcAPgUQAPgVAWgLQAYgKAWAAQAbAAAUANQAUAMALAUQAKAVAAAXQABAYgNAWQgOAVgWAMQgXANgaAAQgaAAgUgNgAgsg/QgOATAAAiQAAAbAIAVQAJAVAOANQAPAMAQAAQAQAAANgJQAMgKAIgRQAGgSAAgYQAAgZgIgUQgHgUgPgMQgPgLgTAAQgZAAgOATg");
	this.shape_2.setTransform(96.95,52.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABHBaIiCiVIAABsQAAAPAGAJQAGAIALAAIABACIgBACIgMgBIgPAAIgSAAIgNABIgBgCIABgCQAMAAAHgIQAHgJAAgPIAAh1QgJgKgHgEQgGgEgHAAIgBgCIABgBIAMAAIAKAAIAWAAIAJAAIAEABIADAFIAHAIIBgBvIAAhZQAAgPgGgJQgGgJgLAAIgBgCIABgBIAMAAIAPABIAQgBIAMAAIABABIgBACQgLAAgGAJQgHAJAAAPIAACOIgBABIgCAAg");
	this.shape_3.setTransform(76.125,53.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSA8QgJgFAAgOIAAg9QABgJgEgDQgDgEgIAAIAAgBIgBgBIAAgCIABgBQAOgBAJgFQAJgGAFgLIACgBQAAAAABAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAWQAPAAAUgDIABADIABAEIgBAGQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgSgEgQAAIAABCQAAAKAFAFQAFAFAJAAQALAAALgJIABAAIABABIAAACQgKALgKAEQgKAGgLAAQgMAAgIgHg");
	this.shape_4.setTransform(54.7,55.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAJA3IgVAAIgRAAIgLABIgBgCIABgCQAIAAADgEQADgEAAgLIAAg0QAAgJgCgEQgCgDgEAAQgFAAgJADIAAAAIgBgBIAAgCIAngTIACAAQADAAACAFQADAGAAAKQALgMAHgFQAIgEAFAAQAHAAAGAEQAGAFAAAGQAAAGgEAEQgDADgGABQgEgBgDgBIgGgFIgEgEIgEgCQgDAAgDADIgKAJIAAA7QAAALAFAEQAGAEAOAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAg");
	this.shape_5.setTransform(44.3625,56);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AATA1QgCgFAAgJQgKAJgIAFQgJAEgLAAQgMAAgJgFQgKgGgGgLQgFgLAAgQQAAgTAJgPQAJgPAPgIQAPgIARAAQAPAAAMAIQAGgDAFgFIABAAIABAAIABABIAABPQAAAJABADQACAEAEAAQAEAAAIgDIABAAIABABIAAACIgnASIgBABQgDAAgCgFgAgaglQgJAOAAAWQAAAUAIAMQAHAMANAAQAKAAANgJIAAgDIAAg5QAAgLgGgHQgGgHgIAAQgPAAgHAOg");
	this.shape_6.setTransform(32.775,56.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgSA8QgIgFAAgOIAAg9QgBgJgDgDQgDgEgIAAIgBgBIAAgBIAAgCIABgBQAPgBAIgFQAJgGAFgLIACgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAWQAPAAAVgDIABADIABAEIgBAGQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgSgEgQAAIAABCQAAAKAEAFQAGAFAJAAQALAAAKgJIABAAIACABIAAACQgLALgKAEQgJAGgLAAQgLAAgJgHg");
	this.shape_7.setTransform(21,55.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgfBXQgOgDgFgFIgCgCIgBgDIAAgsIAAgBIABgBQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIAOAcQAHAKAJAIQAKAJALAAQALAAAIgGQAHgGAAgPQAAgMgFgKQgGgJgIgGIgUgQIgVgOQgIgGgFgIQgFgJAAgMQAAgPAIgKQAJgKANgFQAOgFAOAAQAJAAAKACQAKACAHACIADADIABADIAAApIgCABIgBAAIgCgFQgHgSgKgMQgJgNgQAAQgLAAgHAHQgIAGAAANQAAAKAGAHQAFAIAHAGIAUAOIAWAPQAJAHAFAJQAGAKAAANQAAAOgHAMQgIALgOAGQgOAHgQAAQgNAAgNgEg");
	this.shape_8.setTransform(9.175,52.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgNBVQgFgFAAgHQAAgIAFgEQAEgEAIgBQAHAAAEAFQAFAEAAAIQAAAHgFAFQgEAEgHABQgIgBgEgEgAgDAjIgBgBIgGhEQgDgbgGgYQAAgBAGgBIANgBIAOABQAGABAAABQgGAWgDAYIgGBAIgBAJIgBABIgDAAg");
	this.shape_9.setTransform(178.425,21);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgeBYQgKgFgJgKIAAgBIABgCIACAAQAFAGAIADQAIADAJAAQARAAAJgLQAJgMAAgTQAAgVgKgNQgJgMgSAAQgIAAgHACIgHACIgDgBIAAgDIAJhKIABgDIADgBIAxgBIARgBQAEgCACgEIABAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIgFAfIgCAFIgFABIg6gCQgDAAgBAEIgFAqQAPgGAOAAQAZABAPAOQAPANAAAZQAAAbgQAPQgQAOgYAAQgNABgLgGg");
	this.shape_10.setTransform(168.525,20.65);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AArBYIgTAAIgWAAIgPAAIgBgBIABgCIAPgBQAFgCABgDQACgEAAgJIAAgcIhAgBIgCgBIAAgCIBbh5IACAAIACAAIAAABIAAByIARgBQABAAAAAGQAAAGgBAAIgRgBIAAAcQAAAJABADQACAFADABQADABAIAAIABACIgBABgAgnAbQAAAAAAABQgBAAABAAQAAABAAAAQABAAAAAAIAwAAIAAhFg");
	this.shape_11.setTransform(155,20.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgBB0IAAgbIgEAAQgNAAgNgEQgOgDgFgEIgCgDIgBgCIAAgtIAAAAIABgBQAAgBAAAAQABAAAAABQAAAAAAAAQABAAAAABIANAaQAHAKAJAJQAJAIALAAIAAhHIgLgIIgVgNQgIgHgFgIQgFgJAAgLQAAgUAOgMQAPgMAVgBIAAgYIABgBIACgBIADABIABABIAAAYIABAAQAJAAAKACQAKABAHACIADADIABADIAAAqIgCABIgBgBIgDgGQgGgPgIgLQgHgLgOgEIAABDIAGADIAWAPQAJAHAFAKQAGAKAAAMQAAATgNAOQgNANgWADIAAAcQAAAAAAABQAAAAgBAAQAAABgBAAQgBAAgBAAQgBAAgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAgAAGBRQAKgBAFgGQAGgGAAgNQAAgMgFgJQgGgJgKgIgAgThPQgHAHAAAMQAAALAHAIQAGAJAMAIIAAg+QgLABgHAGg");
	this.shape_12.setTransform(141.725,21.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgSA9QgJgHAAgOIAAg8QABgJgEgEQgDgDgIAAIAAgBIgBgBIAAgDIABAAQAOAAAJgGQAJgGAFgLIACgBQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAWQAPAAAUgCIABACIACAFIgCAFQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgSgEgQAAIAABBQAAALAFAFQAFAFAJAAQALAAALgIIABAAIABABIAAABQgKAKgKAGQgKAEgLAAQgMAAgIgFg");
	this.shape_13.setTransform(123.2,23.35);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AghAxIgCgDIAAgbIABgBIABAAQAFAOALAKQAKAJAJABQAGAAAEgEQAEgEAAgHQgBgKgFgGQgHgGgKgGIgPgJQgFgCgEgHQgDgGAAgJQAAgRALgHQAMgIAQAAIAMABIALADQABABAAAAQABAAAAAAQABABAAAAQAAABAAAAIgBAMIAAANIgBABIgCgBQAAgFgFgGQgEgGgHgFQgIgEgGgBQgMABAAAKQAAAJAHAGQAFAFAKAGIAPAKQAGAEAEAFQAEAHABAIQAAAKgGAIQgEAJgJAFQgKAFgNAAQgPAAgNgIg");
	this.shape_14.setTransform(113.7,24.25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAYAzQgCgGAAgKQgSAWgWAAQgPAAgIgKQgJgKAAgPIAAgoQAAgTgJAAQgDAAgEACIgCgBIABgCIAlgSIABAAIADABIACACIAAA9QAAAeAXAAQAFAAAGgCQAHgDAFgFIAAguQAAgTgJAAIgHACIAAAAIgCgBIABgCIAlgSIABAAIADABIACACIAABKQAAAJACAEQACAEADAAQAFAAAHgDIABAAIABABIAAACIgmATIgCAAQgCAAgDgGg");
	this.shape_15.setTransform(101.95,24.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgrB1QgGgEAAgJQAAgFAEgEQAEgFAGAAQAIAAADAFQAEADADAIIADAHQADACACAAQAGAAADgJQABgKAAgVIAAitQAAgIgBgEQgCgEgEgBQgFgCgKAAIgBgCIABgBIARAAIAVAAIATAAIAOAAIAAABIAAACQgIAAgEACQgDABgBAEIgBANIAACYQAAAfgPASQgQARgbABQgKgBgIgEg");
	this.shape_16.setTransform(88.7,24.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgRBVQgFgFgBgIQABgIAFgEQAEgEAIAAQAGAAAFAEQAEAEAAAIQAAAIgEAFQgFAEgGAAQgIAAgEgEgAgGAhQgDgIgCgKIgCgQQAAgHADgGIAIgNQAFgHADgGQADgIAAgKQAAgLgDgHQgDgGgFgBQgEAAgCADQgBADAAAGQgBAHgEAHQgCAFgJAAQgIAAgDgEQgEgDAAgGQAAgKALgHQALgGAQAAQARAAANAIQAMAKAAAPQABALgGAHQgFAHgLAIIgGAFQgJAHgEAJQgCAHAAAKIABAQQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_17.setTransform(74.2,21.05);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgSA9QgIgHAAgOIAAg8QgBgJgDgEQgDgDgIAAIgBgBIAAgBIAAgDIABAAQAPAAAIgGQAJgGAFgLIACgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAWQAPAAAVgCIAAACIABAFIgBAFQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAQgSgEgQAAIAABBQAAALAFAFQAFAFAJAAQALAAALgIIABAAIABABIAAABQgKAKgKAGQgKAEgLAAQgLAAgJgFg");
	this.shape_18.setTransform(64.85,23.35);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AATBVIgRAAIgPAAIgMABIAAgCIAAgCQAJAAADgEQADgEAAgLIAAgyQAAgKgBgDQgDgEgEAAQgEAAgGADIgBAAIgCgBIABgCIApgUIABAAIADABIABADIAAAGIAAAaIAAAzQAAALADAEQADAEAJAAIAAACIAAACgAgKg4QgFgFAAgIQABgHAEgFQAFgEAGAAQAIAAAEAEQAFAFAAAHQAAAIgFAFQgEAEgIAAQgHAAgEgEg");
	this.shape_19.setTransform(56.2,21.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AATA1QgCgFAAgJQgKAJgIAFQgJAEgLAAQgMAAgJgFQgKgGgGgLQgFgLAAgQQAAgTAJgPQAJgPAPgIQAPgIARAAQAPAAAMAIQAGgDAFgFIABAAIABAAIABABIAABPQAAAJABADQACAEAEAAQAEAAAIgDIABAAIABABIAAACIgnASIgBABQgDAAgCgFgAgaglQgJAOAAAWQAAAUAIAMQAHAMANAAQAKAAANgJIAAgDIAAg5QAAgLgGgHQgGgHgIAAQgPAAgHAOg");
	this.shape_20.setTransform(46.175,24.275);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAhA2IgjhGIgcBGQAAAAAAAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAAAIgohUQgFgMgFgEQgFgEgGAAIgBgCIABgBIAIAAIATAAIAUAAIALAAIABABIgBACQgOABAAAGIACAEIAcA4IAbhGQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIAlBHIARgrQADgFAAgFQAAgHgFgEQgFgEgIAAIgBgCIABgBIALAAIARAAIALAAIALAAIAAABIAAACQgIABgHAGQgGAFgGANIggBPQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAg");
	this.shape_21.setTransform(29.375,24.25);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgdBZQgNgGAAgLQAAgFAEgEQAEgEAHAAQAHAAAEAEIAIAKQAFAIADAEQAEADAJABQAJAAAGgKQAFgJAAgbIAAgsQgTAVgWgBQgPAAgJgKQgIgJAAgPIAAgoQAAgKgCgFQgCgEgFAAQgDAAgEACIgCgBIAAgCIAmgSIABAAIADABIACACIAAA+QAAAPAFAHQAGAHALgBQAGABAHgCQAHgDAFgEIAAgvQAAgTgIAAQgEAAgDACIgBAAIgBgBIAAgCIAlgSIACAAIADABIABACIAAB9QAAAcgPAQQgPAQgdAAQgRAAgMgGg");
	this.shape_22.setTransform(5.7375,28.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AA5BlIgRAAIgRAAIgLAAIgBgBIABgCQAJAAADgEQADgEAAgLIAAgpQAAgPgFgHQgGgHgMAAQgGAAgHACQgHADgFAFIAAA8QAAALADAEQADAEAJAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgMAAIgQAAIgRAAIgLAAIgBgBIABgCQAIAAAEgEQADgEAAgLIAAiOQAAgJgCgEQgCgFgEAAQgEAAgHADIgCgBIAAgCIApgTIABAAIADAAIACADIAABuQAUgWAVAAQAPAAAJAJQAJAJAAAQIAAA2QAAALADAEQAEAEAIAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_23.setTransform(-7.8625,19.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAvBXIg1h/IgoB/QAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAgBAAAAIg0iWQgEgMgEgEQgEgEgJAAIAAgCIAAgBIAGAAIAPAAIAkAAIAMAAIABABIgBACQgPAAgBAMQABAGACAHIAgBeIAmh6IAEgBIADABIA1B7IAXhVQADgJAAgGQgBgUgVAAIgBgCIABgBIAPAAIAXAAIANAAIAMAAIAAABIAAACQgLAAgJAIQgKAJgFAQIgnCJQAAAAAAABQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAgBgBQAAAAgBAAQAAAAAAAAQAAgBgBAAg");
	this.shape_24.setTransform(-27.3,20.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-79,1.8,300,69.8);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLAMQgFgEAAgIQAAgHAFgEQAEgFAHABQAIAAAEAEQAFAEAAAHQAAAIgFAEQgEAFgIgBQgHABgEgFg");
	this.shape.setTransform(132.325,67.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXAxQgNgHgHgNQgHgMAAgOQAAgPAJgOQAIgOAPgIQAOgIARAAQARAAAKAHQAJAIAAANQAAAHgDABIgRAAIgyABIgBALQAAAXAMAOQAKAOAUAAQAHAAAIgCQAHgCAGgDIABgBIABABIAAACQgKAKgLAFQgKAEgNAAQgRAAgMgIgAgLgsQgGAHgDAMIAngBQgBgYgPgBQgIABgGAGg");
	this.shape_1.setTransform(123.6625,63.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHBlIgTAAIgRAAIgMABQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAABAAQAHAAAEgBQADgBABgFQACgDAAgJIAAg/QAAgJgEgCQgEgDgKAAIgCgCIACgCQAJAAAEgDQAEgCAAgHQABguAQgUQAQgVAgAAQAPAAAIAFQAJAEAAAIQABAGgFAEQgEAEgGAAQgGAAgDgDQgEgDgDgGIgEgJQgEgDgFAAQgOAAgGASQgIASAAAmIAAARIAfgDIABADIAAADIAAAGQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAAAAAQgNgDgRgBIAABLQABAJACAEQABAEAFABQAEABALAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAgBAAg");
	this.shape_2.setTransform(115.6,58.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAUBVIgRAAIgQAAIgLABIgBgCIABgCQAIAAADgEQADgEAAgLIAAgyQAAgKgCgDQgCgEgEAAQgEAAgHADIAAAAIgCgBIABgCIApgUIABAAIADABIABADIAAAGIgBAaIAAAzQABALADAEQADAEAJAAIAAACIAAACgAgLg4QgDgFAAgIQAAgHAEgFQAFgEAGAAQAIAAAEAEQAFAFAAAHQAAAIgFAFQgEAEgIAAQgHAAgFgEg");
	this.shape_3.setTransform(105.5,60.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AATBlIgRAAIgPAAIgMABIAAgCIAAgCQAJAAADgEQADgEAAgLIAAiNQAAgKgBgEQgCgEgFAAQgDAAgHADIgBAAIgBgCIAAgCIAogUIABAAIADABIACADIAACwQAAALADAEQADAEAJAAQAAAAAAAAQAAAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAAAAAQAAABAAAAg");
	this.shape_4.setTransform(97.9375,58.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAJA3IgVAAIgRAAIgLABIgBgCIABgCQAIAAADgEQADgEAAgLIAAg0QAAgJgCgEQgCgDgEAAQgFAAgJADIAAAAIgBgBIAAgCIAngTIACAAQADAAACAFQADAGAAAKQALgMAHgFQAIgEAFAAQAHAAAGAEQAGAFAAAGQAAAGgEAEQgDADgGABQgEgBgDgBIgGgFIgEgEIgEgCQgDAAgDADIgKAJIAAA7QAAALAFAEQAGAEAOAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQgBAAAAAAQAAABAAAAg");
	this.shape_5.setTransform(82.4125,63.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAYAzQgCgGAAgKQgTAWgUAAQgQAAgIgKQgJgKAAgPIAAgoQAAgTgJAAQgDAAgEACIgCgBIABgCIAlgSIABAAIAEABIABACIAAA9QAAAeAXAAQAFAAAHgCQAFgDAGgFIAAguQAAgTgJAAIgHACIgBAAIgBgBIAAgCIAmgSIABAAIAEABIABACIAABKQAAAJABAEQACAEAFAAQADAAAIgDIAAAAIACABIAAACIgnATIgBAAQgDAAgCgGg");
	this.shape_6.setTransform(70.3,63.425);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AggAyQgMgJgIgNQgGgOgBgPQABgRAIgNQAKgNAOgGQAPgHANABQASgBANAJQANAHAHAOQAGANABAOQAAARgJANQgIANgPAIQgNAHgQAAQgSgBgNgHgAgcgLQAAASAEAPQAFAOAJAHQAHAJAKAAQAKAAAGgLQAGgLgBgUQAAgSgEgOQgGgOgIgIQgIgHgIAAQgXAAABAog");
	this.shape_7.setTransform(56.3,63.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgdBZQgNgGAAgKQAAgHAEgDQAEgEAHAAQAHAAAEAEIAIALQAFAHADAEQAEADAJAAQAJABAGgKQAFgKAAgbIAAgsQgTAWgWAAQgPgBgJgJQgIgKAAgOIAAgqQAAgJgCgEQgCgFgFAAQgDAAgEACIgCgCIAAgCIAmgSIABAAIADABIACADIAAA+QAAAPAFAIQAGAFALABQAGAAAHgCQAHgDAFgEIAAgwQAAgSgIAAQgEAAgDACIgBAAIgBgCIAAgCIAlgSIACAAIADABIABADIAAB+QAAAbgPAPQgPARgdgBQgRAAgMgFg");
	this.shape_8.setTransform(41.7875,67.15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgGBlIgUAAIgRAAIgMABQgBAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBQAAAAABgBQAAAAAAAAQAAgBAAAAQAAAAABAAQAHAAAEgBQADgBABgFQABgDAAgJIAAg/QAAgJgDgCQgEgDgLAAIgBgCIABgCQAKAAAEgDQAEgCAAgHQABguAQgUQAQgVAgAAQAPAAAIAFQAJAEAAAIQABAGgFAEQgEAEgGAAQgGAAgDgDQgEgDgCgGIgGgJQgCgDgHAAQgNAAgGASQgIASAAAmIAAARIAfgDIABADIABADIgBAGQgBAAAAABQAAAAAAAAQgBABAAAAQAAAAAAAAQgNgDgRgBIAABLQAAAJADAEQABAEAFABQAEABALAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAgBAAg");
	this.shape_9.setTransform(26.85,58.575);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgfAyQgNgJgIgNQgGgOAAgPQAAgRAJgNQAJgNAOgGQAOgHAOABQASgBANAJQANAHAGAOQAIANAAAOQAAARgJANQgIANgPAIQgNAHgQAAQgRgBgNgHgAgcgLQAAASAEAPQAFAOAJAHQAHAJAKAAQAKAAAGgLQAGgLgBgUQAAgSgEgOQgGgOgIgIQgHgHgJAAQgXAAABAog");
	this.shape_10.setTransform(13.65,63.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgXAxQgNgHgHgNQgHgMAAgOQAAgQAJgNQAIgOAPgIQAOgIARAAQARAAAKAHQAJAIAAANQAAAHgDAAIgRAAIgyACIgBALQAAAXAMAOQAKAOAUAAQAHAAAIgCQAHgBAGgEIABgBIABABIAAACQgKAKgLAFQgKAEgNAAQgRAAgMgIgAgLgsQgGAHgDAMIAngBQgBgYgPgBQgIABgGAGg");
	this.shape_11.setTransform(181.8125,34.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgIBeIgWAAIgRAAIgMAAIAAgBIAAgCQAHAAADgCQAEgBABgEQABgEAAgIIAAiBQAAgJgCgEQgCgEgFAAQgEAAgJAEIAAAAIgCgBIAAgCIAogTIABgBQADAAADAFQACAFABAIQATgSAWAAQALAAALAGQAKAGAGAMQAGALAAAQQAAAXgJAOQgJANgOAHQgPAGgPAAQgMAAgLgDIAAA2QAAAIACAEQACAEAFABQAFACAKAAIABACIgBABgAgRhFIAAACIAABDQAGAHAHADQAGAEAKAAQAcAAAAgvQAAgVgKgMQgKgMgPAAQgLAAgLAJg");
	this.shape_12.setTransform(168.1875,38.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AATA1QgCgFAAgJQgKAJgIAFQgJAEgLAAQgMAAgJgFQgKgGgGgLQgFgLAAgQQAAgTAJgPQAJgPAPgIQAPgIARAAQAPAAAMAIQAGgDAFgFIABAAIABAAIABABIAABPQAAAJABADQACAEAEAAQAEAAAIgDIABAAIABABIAAACIgnASIgBABQgDAAgCgFgAgaglQgJAOAAAWQAAAUAIAMQAHAMANAAQAKAAANgJIAAgDIAAg5QAAgLgGgHQgGgHgIAAQgPAAgHAOg");
	this.shape_13.setTransform(155.125,34.475);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AA5BlIgRAAIgRAAIgLABIgBgCIABgCQAJAAADgEQADgEAAgLIAAgoQAAgQgFgHQgGgHgMAAQgGAAgHADQgHADgFAEIAAA8QAAALADAEQADAEAJAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAIgMgBIgQAAIgRAAIgLABIgBgCIABgCQAIAAAEgEQADgEAAgLIAAiOQAAgJgCgEQgCgEgEgBQgEABgHADIgCgCIAAgCIApgUIABAAIADABIACADIAABuQAUgWAVAAQAPAAAJAJQAJAKAAAPIAAA2QAAALADAEQAEAEAIAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_14.setTransform(140.4875,29.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AghAyIgCgEIAAgcIABgBIABABQAFAOALAKQAKAKAJAAQAGgBAEgDQAEgEAAgHQgBgKgFgGQgHgGgKgHIgPgIQgFgDgEgGQgDgGAAgJQAAgQALgIQAMgIAQAAIAMABIALADQABABAAAAQABAAAAAAQABABAAAAQAAABAAABIgBALIAAAOIgBAAIgCAAQAAgGgFgGQgEgHgHgEQgIgFgGABQgMAAAAALQAAAHAHAGQAFAGAKAHIAPAKQAGADAEAFQAEAHABAJQAAAJgGAJQgEAIgJAFQgKAFgNAAQgPAAgNgHg");
	this.shape_15.setTransform(129,34.45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgSA9QgJgGABgOIAAg9QAAgJgEgDQgDgEgIAAIAAgBIgBgBIAAgCIABgBQAOAAAJgGQAJgGAFgLIACgBQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAWQAPAAAVgDIABADIABAFIgBAFQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgSgEgQAAIAABCQAAAKAEAFQAGAFAJAAQALAAAKgJIABAAIACABIAAACQgLALgKAEQgJAFgLABQgLgBgJgFg");
	this.shape_16.setTransform(113.15,33.55);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgiAyIgBgEIgBgcIACgBIABABQAFAOAKAKQALAKAJAAQAHgBADgDQADgEABgHQAAgKgHgGQgFgGgLgHIgPgIQgEgDgEgGQgFgGAAgJQAAgQAMgIQAMgIAQAAIAMABIALADQABABAAAAQABAAAAAAQABABAAAAQAAABAAABIAAALIgBAOIgCAAIgBAAQAAgGgEgGQgFgHgIgEQgGgFgHABQgMAAAAALQABAHAFAGQAGAGAKAHIAQAKQAFADAEAFQAFAHgBAJQAAAJgEAJQgFAIgKAFQgJAFgMAAQgQAAgOgHg");
	this.shape_17.setTransform(103.65,34.45);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgXAxQgNgHgHgNQgHgMAAgOQAAgQAJgNQAIgOAPgIQAOgIARAAQARAAAKAHQAJAIAAANQAAAHgDAAIgRAAIgyACIgBALQAAAXAMAOQAKAOAUAAQAHAAAIgCQAHgBAGgEIABgBIABABIAAACQgKAKgLAFQgKAEgNAAQgRAAgMgIgAgLgsQgGAHgDAMIAngBQgBgYgPgBQgIABgGAGg");
	this.shape_18.setTransform(93.0625,34.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgOBkQgKgDgIgHIgaAMIAAAAIgCgBIABgCQAHgEADgHQAEgGAAgLIAAiHQAAgKgCgEQgCgEgFAAQgDAAgHADIAAAAIgCgCIAAgCIApgTIACAAIACABIACACIAABqQAJgIAKgFQAIgFAMAAQANAAAKAGQALAFAGAMQAHALAAARQAAAUgJAPQgIAOgOAHQgOAHgQAAQgJAAgLgDgAgTAMIAAAqQAAAPAFAKQAGAKAHAEQAHAFAHAAQAMAAAGgMQAHgNAAgWQAAgYgIgMQgIgMgPAAQgMAAgOAJg");
	this.shape_19.setTransform(79.5625,29.875);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgXAxQgNgHgHgNQgHgMAAgOQAAgQAJgNQAIgOAPgIQAOgIARAAQARAAAKAHQAJAIAAANQAAAHgDAAIgRAAIgyACIgBALQAAAXAMAOQAKAOAUAAQAHAAAIgCQAHgBAGgEIABgBIABABIAAACQgKAKgLAFQgKAEgNAAQgRAAgMgIgAgLgsQgGAHgDAMIAngBQgBgYgPgBQgIABgGAGg");
	this.shape_20.setTransform(60.4125,34.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AA5BlIgRAAIgRAAIgLABIgBgCIABgCQAJAAADgEQADgEAAgLIAAgoQAAgQgFgHQgGgHgMAAQgGAAgHADQgHADgFAEIAAA8QAAALADAEQADAEAJAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAIgMgBIgQAAIgRAAIgLABIgBgCIABgCQAIAAAEgEQADgEAAgLIAAiOQAAgJgCgEQgCgEgEgBQgEABgHADIgCgCIAAgCIApgUIABAAIADABIACADIAABuQAUgWAVAAQAPAAAJAJQAJAKAAAPIAAA2QAAALADAEQAEAEAIAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_21.setTransform(47.1375,29.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgSA9QgJgGABgOIAAg9QAAgJgEgDQgDgEgIAAIgBgBIAAgBIAAgCIABgBQAOAAAJgGQAJgGAFgLIACgBQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAWQAPAAAVgDIABADIABAFIgBAFQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgSgEgQAAIAABCQAAAKAEAFQAGAFAJAAQALAAAKgJIABAAIACABIAAACQgLALgKAEQgJAFgLABQgLgBgJgFg");
	this.shape_22.setTransform(35.75,33.55);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AA6A3IgQAAIgRAAIgLABIgBgCIABgCQAIAAADgEQADgEAAgLIAAgnQAAgPgFgIQgGgHgLAAQgGAAgHADQgHADgGAEIAAA7QAAALADAEQAEAEAJAAIAAACIAAACIgMgBIgRAAIgQAAIgMABIgBgCIABgCQAJAAADgEQADgEAAgLIAAg0QAAgIgCgEQgCgEgFAAQgEAAgJAEIgBAAIgBgCIAAgCIAngTIACAAQADAAADAGQADAGAAAKQAUgXAWAAQAPAAAJAKQAJAKAAAPIAAA1QAAALADAEQADAEAJAAIABACIgBACg");
	this.shape_23.setTransform(16.8125,34.275);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAUBVIgRAAIgQAAIgLABIgBgCIABgCQAIAAADgEQADgEAAgLIAAgyQAAgKgCgDQgCgEgEAAQgEAAgHADIAAAAIgBgBIAAgCIApgUIABAAIADABIABADIAAAGIgBAaIAAAzQAAALAEAEQADAEAJAAIABACIgBACgAgLg4QgDgFAAgIQgBgHAFgFQAFgEAGAAQAIAAAFAEQADAFAAAHQAAAIgDAFQgFAEgIAAQgHAAgFgEg");
	this.shape_24.setTransform(5.85,31.275);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgSA9QgJgGABgOIAAg9QAAgJgEgDQgDgEgIAAIgBgBIAAgBIAAgCIABgBQAOAAAJgGQAJgGAFgLIACgBQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAWQAPAAAVgDIABADIABAFIgBAFQgBABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgSgEgQAAIAABCQAAAKAEAFQAGAFAJAAQALAAAKgJIABAAIACABIAAACQgLALgKAEQgJAFgLABQgLgBgJgFg");
	this.shape_25.setTransform(-8.8,33.55);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgXAxQgNgHgHgNQgHgMAAgOQAAgQAJgNQAIgOAPgIQAOgIARAAQARAAAKAHQAJAIAAANQAAAHgDAAIgRAAIgyACIgBALQAAAXAMAOQAKAOAUAAQAHAAAIgCQAHgBAGgEIABgBIABABIAAACQgKAKgLAFQgKAEgNAAQgRAAgMgIgAgLgsQgGAHgDAMIAngBQgBgYgPgBQgIABgGAGg");
	this.shape_26.setTransform(-19.4875,34.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgqBPQgXgMgMgUQgMgUABgZQgBgaAOgVQAOgWAZgLQAYgMAdAAQANAAAOACQANACAIAEIADACIACAEIADAnIgBABIgCgBQgKgVgRgMQgSgMgWAAQgcAAgPAUQgOAUAAAiQAAAbAJAVQAJAWASAMQAQAMAVAAQALAAAGgDQAHgCACgHQADgIAAgOQAAgPgCgFQgCgGgFgCQgGgCgNAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAgBAAAAIAAgCIABAAIAmABIAegBIABABIABABQAAAAgBABQAAAAAAABQAAAAAAAAQgBAAAAAAQgFAAgCACQgCACAAAGIgBAXIABASIABAGIgBADIgDABQgjAIgeAAQgdAAgYgMg");
	this.shape_27.setTransform(-35.25,31.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-79,12,300,66.8);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLAMQgEgFAAgHQAAgHAEgEQAFgEAGAAQAIAAAEAEQAEAEAAAHQAAAIgEAEQgEAEgIAAQgGAAgFgEg");
	this.shape.setTransform(197.225,65.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggAwIgCgEIAAgbIABAAIACAAQAEAOAKAJQAKAKAJAAQAGgBADgDQAEgDAAgHQAAgKgGgGQgGgGgKgGIgOgIQgFgCgEgHQgDgFAAgJQAAgQALgHQALgIAQAAIALABIALADQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABIgBAKIAAAOIgCABIgBgBQAAgFgEgGQgFgGgHgFQgHgEgGAAQgLAAAAALQAAAHAGAGQAFAGAKAGIAPAKQAFADAEAFQAEAGAAAIQAAAKgEAIQgFAIgJAFQgJAFgMAAQgPAAgNgHg");
	this.shape_1.setTransform(190.025,61.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AggAwIgCgEIAAgbIABAAIACAAQAEAOAKAJQAKAKAJAAQAGgBADgDQAEgDAAgHQAAgKgGgGQgGgGgKgGIgOgIQgFgCgEgHQgDgFAAgJQAAgQALgHQALgIAQAAIALABIALADQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABIgBAKIAAAOIgCABIgBgBQAAgFgEgGQgFgGgHgFQgHgEgGAAQgLAAAAALQAAAHAGAGQAFAGAKAGIAPAKQAFADAEAFQAEAGAAAIQAAAKgEAIQgFAIgJAFQgJAFgMAAQgPAAgNgHg");
	this.shape_2.setTransform(180.975,61.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWAvQgNgGgGgNQgHgMAAgOQAAgOAIgNQAJgOAOgHQAOgIAQAAQARAAAJAHQAJAHAAANQAAAHgDABIgRAAIgvAAIgBAMQAAAWALANQAJANAUAAQAGAAAIgCQAHgBAGgEIABAAIABABIAAACQgKAJgKAEQgLAFgMAAQgQAAgMgIgAgKgqQgGAGgDAMIAmgBQgBgYgPAAQgHABgGAGg");
	this.shape_3.setTransform(170.7875,61.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA5A1IgRAAIgQAAIgLABIAAgCIAAgCQAJAAACgDQADgEAAgLIAAgmQABgPgGgHQgFgHgLAAQgGAAgHADQgGADgGAEIAAA5QAAALAEAEQADADAIAAIABACIgBACIgLgBIgQAAIgQAAIgLABIgBgCIABgCQAIAAADgDQADgEAAgLIAAgyQAAgIgCgEQgCgEgFAAQgEAAgJAEIAAAAIgBgCIAAgBIAmgTIABAAQADAAADAGQADAFAAAKQATgWAVAAQAPAAAIAKQAJAJAAAPIAAAzQAAALADAEQADADAJAAIAAACIAAACg");
	this.shape_4.setTransform(157.85,61.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AA3BhIgQAAIgQAAIgLABIgBgBIABgCQAIAAADgEQADgEAAgLIAAgnQAAgPgFgGQgGgIgLAAQgFAAgHADQgHADgFAEIAAA6QAAALADAEQADAEAIAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgLgBIgQAAIgQAAIgLABIgBgBIABgCQAIAAADgEQAEgEAAgLIAAiIQAAgKgCgDQgCgEgEgBQgEABgHADIgBgCIAAgCIAngTIABAAIADABIACADIAABqQATgWAVAAQAOAAAJAJQAIAJAAAQIAAAzQAAALADAEQADAEAJAAQAAAAAAAAQAAAAAAAAQAAAAABABQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAAAg");
	this.shape_5.setTransform(143.8375,56.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgiBWQgMgFAAgKQAAgHAFgDQAEgEAFAAQAIAAAEAEQADADAEAHQADAIAEADQAEAEAHAAQAKAAAFgKQAGgJAAgaIAAgnQgJAIgJAFQgIAEgKAAQgLAAgKgFQgJgGgFgKQgGgKAAgQQAAgTAJgOQAJgPAPgHQAOgIAQAAQAPAAALAHQAHgCAEgFIABAAIABAAIABABIAAB9QAAAZgQAQQgPAQgaAAQgSAAgLgGgAgPhIQgIAOAAAVQAAAVAHALQAHAKAMAAQAKAAANgIIAAg6QAAgLgGgGQgFgHgKAAQgMAAgIANg");
	this.shape_6.setTransform(130.525,65.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAXAxQgCgGAAgKQgSAWgTAAQgPAAgJgKQgJgJAAgPIAAgnQABgSgJAAQgDAAgDACIgBAAIgBgBIAAgCIAkgRIABAAIADABIABACIAAA7QABAdAWAAQAFAAAGgDQAGgCAFgFIAAgtQAAgSgJAAIgGACIgCgBIAAgCIAkgRIACAAIADABIABACIAABHQAAAJACAEQACAEAEAAQAEAAAGgDIABAAIABABIAAACIglASIgBAAQgDAAgCgGg");
	this.shape_7.setTransform(117.85,61.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgeAwQgNgIgGgNQgIgNABgPQgBgRAKgMQAJgNANgFQAOgHAOAAQAQABANAHQAMAIAHANQAGANABANQAAAQgJANQgIAMgOAIQgNAGgPAAQgRABgMgIgAgbgKQAAARAFAOQAEAOAIAHQAHAIAJAAQAKAAAGgKQAGgLgBgUQABgRgFgOQgFgOgIgGQgIgHgHAAQgWAAAAAng");
	this.shape_8.setTransform(104.3,61.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgRA6QgJgGAAgNIAAg7QAAgJgDgDQgDgDgHAAIgBAAIgBgCIABgCIABgBQANgBAJgEQAIgGAFgLIACgBQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAVIAigCIABACIABAFIgBAFQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAAAAAQgSgEgPAAIAAA/QAAAKAEAFQAFAFAJAAQALAAAKgIIABgBIACACIgBACQgKAKgJAEQgKAFgKAAQgLAAgIgGg");
	this.shape_9.setTransform(93.425,60.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AASBhIgQAAIgPAAIgLABIgBgBIABgCQAIAAADgEQADgEAAgLIABiIQAAgKgCgDQgCgEgEgBQgEABgHADIgBgCIAAgCIAmgTIABAAIADABIACADIAACpQAAALADAEQADAEAIAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAg");
	this.shape_10.setTransform(78.6125,56.85);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AATAzQgCgFgBgJQgIAJgJAFQgIAEgLAAQgLAAgKgFQgJgGgFgLQgGgKAAgQQAAgSAJgOQAJgPAPgHQAOgIAQAAQAPAAALAHQAGgCAEgFIACAAIABAAIABABIAABMQgBAIACAEQACADAEAAQAEAAAHgDIABAAIABACIAAABIglASIgCABQgCAAgCgFgAgagkQgHAOAAAVQAAAUAHALQAGALANAAQAKAAANgJIAAgCIAAg3QAAgLgGgGQgGgHgIAAQgNAAgJANg");
	this.shape_11.setTransform(69,61.475);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgRA6QgJgGAAgNIAAg7QAAgJgDgDQgDgDgHAAIgBAAIgBgCIABgCIABgBQANgBAJgEQAIgGAFgLIACgBQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAVIAigCIABACIABAFIgBAFQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAAAAAQgSgEgPAAIAAA/QAAAKAEAFQAFAFAJAAQALAAAKgIIABgBIACACIgBACQgKAKgJAEQgKAFgKAAQgLAAgIgGg");
	this.shape_12.setTransform(57.675,60.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AA5A1IgRAAIgPAAIgMABIAAgCIAAgCQAJAAADgDQACgEAAgLIAAgmQABgPgGgHQgFgHgLAAQgGAAgHADQgHADgFAEIAAA5QAAALADAEQAEADAIAAIABACIgBACIgLgBIgQAAIgQAAIgLABIgBgCIABgCQAIAAADgDQADgEAAgLIAAgyQAAgIgCgEQgCgEgFAAQgEAAgIAEIgBAAIgBgCIAAgBIAmgTIABAAQADAAADAGQADAFAAAKQATgWAVAAQAPAAAIAKQAJAJAAAPIAAAzQAAALADAEQADADAJAAIABACIgBACg");
	this.shape_13.setTransform(45.7,61.275);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgWAvQgNgGgGgNQgHgMAAgOQAAgOAIgNQAJgOAOgHQAOgIAQAAQARAAAJAHQAJAHAAANQAAAHgDABIgRAAIgvAAIgBAMQAAAWALANQAJANAUAAQAGAAAIgCQAHgBAGgEIABAAIABABIAAACQgKAJgKAEQgLAFgMAAQgQAAgMgIgAgKgqQgGAGgDAMIAmgBQgBgYgPAAQgHABgGAGg");
	this.shape_14.setTransform(33.1875,61.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("ABaA1IgQAAIgQAAIgLABIgBgCIABgCQAIAAADgDQADgEAAgLIAAgmQAAgPgFgHQgEgHgLAAQgHAAgHADQgGADgFAFIAAACIAAA2QAAALADAEQADADAIAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgLgBIgQAAIgPAAIgLABIgBgCIABgCQAJAAADgDQADgEAAgLIAAgmQAAgPgFgHQgFgHgLAAQgGAAgGADQgHADgFAEIAAA5QAAALAEAEQADADAIAAIABACIgBACIgLgBIgQAAIgQAAIgLABIgBgCIABgCQAIAAADgDQADgEAAgLIAAgyQAAgIgCgEQgCgEgEAAQgFAAgIAEIgBAAIgBgCIAAgBIAmgTIACAAQADAAACAGQADAFAAAKQATgWAVAAQANAAAGAHQAIAGABALQATgYAXAAQAOAAAIAJQAIAIAAARIAAAzQAAALADAEQADADAIAAQAAAAABAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_15.setTransform(16.875,61.275);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgYBVIgKgBIgPAAIgUAAIgOAAIgBgBIABgCIANgBQAEgCABgEQACgDAAgJIAAh8QAAgIgCgDQgBgEgEgCQgEgBgJAAIAAgCIAAgBIAPAAIATAAIAXAAIATgBQAaAAAWALQAVALALASQAMATAAAXQAAAZgMAUQgMAUgUALQgVALgXAAgAgbhLQgHADAAALIAAB4QAAALAGAFQAGAEAQAAQAQAAAOgJQANgIAHgSQAIgRAAgYQAAgWgHgTQgHgSgNgLQgNgLgQAAQgRAAgGADg");
	this.shape_16.setTransform(-9.575,58.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("ABEBXIh9iQIAABoQAAAPAGAIQAGAIAKAAIABACIgBACIgMgBIgOAAIgRAAIgNABIgBgCIABgCQAMAAAHgIQAHgIAAgPIAAhxQgJgJgHgEQgGgEgHAAIAAgBIAAgCIAMAAIAKABIAUgBIAJAAIAEABIADAFIAHAIIBcBrIAAhWQAAgPgGgIQgFgJgLAAIgBgBIABgCIAMAAIAOABIAPgBIAMAAIABACIgBABQgKAAgHAJQgGAIAAAPIAACJIgBABIgBAAIgBAAg");
	this.shape_17.setTransform(-28.525,58.4875);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("ABQBVIgRgBIgQABIgOAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJgBQADgCAAgEQABgEgGgLIgcg3IgvAAIgTAqQgDAIAAAHQAAAJAGAGQAHAFAMAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAIgPAAIgRgBIgSABIgOAAQgBAAAAAAQAAAAAAAAQAAAAAAgBQgBAAAAAAQAAgBABAAQAAAAAAgBQAAAAAAAAQAAAAABAAQAHAAAFgDQAFgDAFgIQAFgIAHgQIA7iAIACAAIACAAIBDCEQAKATAGAIQAHAHAGAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgRAAgAAIgCIgUgrIgTArIAnAAg");
	this.shape_18.setTransform(-48.25,58.125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AASBiIgQAAIgPAAIgLAAIgBgBIABgCQAIAAADgEQADgEAAgLIABiIQAAgKgCgDQgCgFgEAAQgEAAgHAEIgBgCIAAgCIAmgTIABAAIADABIACADIAACpQAAALADAEQADAEAIAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAg");
	this.shape_19.setTransform(174.7625,26.15);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AATAzQgCgFgBgJQgJAJgIAFQgIAEgMAAQgLAAgJgFQgJgGgGgLQgFgKAAgQQAAgSAJgOQAJgPAOgHQAPgIAQAAQAOAAAMAHQAGgCAFgFIABAAIAAAAIABABIAABMQABAIABAEQACADAEAAQAEAAAHgDIAAAAIACACIAAABIgmASIgBABQgDAAgBgFgAgZgkQgIAOAAAVQAAAUAHALQAGALAOAAQAJAAANgJIAAgCIAAg3QAAgLgGgGQgFgHgJAAQgOAAgHANg");
	this.shape_20.setTransform(165.15,30.775);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgXAvQgMgHgGgNQgHgMAAgNQAAgQAKgNQAJgNAPgIQAOgGAPAAQANAAAKAFQALAGAAAJQAAAGgEADQgEAEgHgBQgGABgEgEQgEgDgCgHQgDgIgCgCQgCgEgGAAQgLAAgHAMQgHALAAAUQAAAVAKANQAKANAVAAQAHAAAGgBIANgFIACABIAAABQgKAJgKAEQgKAFgNAAQgRAAgMgIg");
	this.shape_21.setTransform(152.3875,30.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AATBSIgRAAIgPAAIgLABIAAgCIAAgCQAJAAADgDQADgEAAgLIAAgwQAAgKgCgDQgCgEgFAAQgDAAgHADIgBgBIAAgCIAogTIAAAAIADABIACADIAAAGIgBAZIAAAxQAAALADAEQADADAJAAIAAACIAAACgAgKg2QgEgFAAgHQAAgHAEgFQAFgEAGAAQAIAAAEAEQAEAEAAAIQAAAHgEAFQgEAEgIAAQgHAAgEgEg");
	this.shape_22.setTransform(143.075,27.675);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AggAvIgCgDIAAgbIABAAIACAAQAEANAKAKQAKAKAJAAQAGAAADgEQAEgDAAgHQAAgKgGgGQgGgGgKgGIgOgIQgFgCgEgHQgDgFAAgJQAAgQALgHQALgIAQAAIALABIALADQABAAAAABQABAAAAAAQAAABABAAQAAAAAAABIgBAKIAAAOIgCABIgBgBQAAgFgEgGQgFgGgHgFQgHgEgGAAQgLAAAAALQAAAHAGAGQAFAGAKAGIAPAKQAFADAEAFQAEAGAAAIQAAAKgEAIQgFAIgJAFQgJAFgMAAQgPAAgNgIg");
	this.shape_23.setTransform(135.175,30.75);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgcBWQgMgGAAgKQAAgGADgEQAEgDAGAAQAIAAADADIAIALQAFAHADAEQAEADAIAAQAJAAAGgJQAFgJAAgaIAAgrQgSAVgWAAQgOAAgIgKQgJgJAAgOIAAgoQAAgJgCgEQgCgFgEAAQgEAAgDACIgBAAIgBgBIABgCIAkgRIABAAIADABIACACIAAA8QAAAOAEAHQAGAGAKAAQAHAAAGgBQAHgDAFgEIAAguQAAgSgIAAQgDAAgEACIgCgBIABgCIAjgRIACAAIADABIABACIAAB5QAAAagOAQQgPAPgcAAQgQAAgMgFg");
	this.shape_24.setTransform(123.1,34.425);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AA3BiIgQAAIgQAAIgLAAIgBgBIABgCQAIAAADgEQADgEAAgLIAAgnQAAgPgFgGQgGgIgLAAQgFABgHACQgHADgFAEIAAA6QAAALADAEQADAEAIAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgLAAIgQAAIgQAAIgLAAIgBgBIABgCQAIAAADgEQAEgEAAgLIAAiIQAAgKgCgDQgCgFgEAAQgEAAgHAEIgBgCIAAgCIAngTIABAAIADABIACADIAABpQATgUAVAAQAOAAAJAIQAIAJAAAQIAAAzQAAALADAEQADAEAJAAQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAAAg");
	this.shape_25.setTransform(110.0375,26.15);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgIBbIgVgBIgQABIgLAAIgBgCIABgBQAGAAADgCQAEgBABgEIABgMIAAh8QAAgIgCgEQgCgEgFAAQgEAAgIAEIgBAAIgBgCIAAgBIAmgTIABAAQADAAACAEQADAFAAAIQATgSAVAAQALAAAKAGQAKAGAGALQAGAMAAAPQAAAVgJAOQgJANgOAGQgNAGgPAAQgMAAgKgDIAAA0QAAAIACAEQACAEAFABQAFACAJAAIABABIgBACgAgQhCIAAACIAABAQAGAHAGADQAGADAJAAQAcAAAAgtQAAgUgKgMQgKgLgOAAQgLAAgKAJg");
	this.shape_26.setTransform(95.9375,34.275);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AA3BiIgQAAIgQAAIgLAAIgBgBIABgCQAIAAADgEQADgEAAgLIAAgnQAAgPgFgGQgGgIgLAAQgFABgHACQgHADgFAEIAAA6QAAALADAEQADAEAIAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgLAAIgQAAIgQAAIgLAAIgBgBIABgCQAIAAADgEQAEgEAAgLIAAiIQAAgKgCgDQgCgFgEAAQgEAAgHAEIgBgCIAAgCIAngTIABAAIADABIACADIAABpQATgUAVAAQAOAAAJAIQAIAJAAAQIAAAzQAAALADAEQADAEAJAAQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAAAg");
	this.shape_27.setTransform(76.1875,26.15);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgRA6QgJgGAAgNIAAg7QAAgJgDgDQgDgDgHAAIgBAAIgBgDIABgBIABgBQANgBAJgEQAIgGAFgLIACgBQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAVIAigCIABACIABAFIgBAFQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAAAAAQgSgEgPAAIAAA/QAAAKAEAFQAFAFAJAAQALAAAKgIIABgBIACABIgBADQgKAJgJAFQgKAFgKAAQgLAAgIgGg");
	this.shape_28.setTransform(65.225,29.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgfAwQgMgIgHgNQgGgNgBgOQABgSAIgMQAJgNAOgFQAOgHANABQARAAAMAHQANAIAHANQAGANAAANQAAARgIAMQgIAMgNAIQgOAGgPAAQgRABgNgIgAgbgKQAAAQAEAOQAFAPAIAHQAIAIAIAAQAKAAAGgKQAFgLABgUQgBgRgEgOQgFgOgIgGQgHgHgJAAQgVAAAAAng");
	this.shape_29.setTransform(53.85,30.75);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgNBhQgKgEgIgGIgYALIgBAAIgBgBIAAgBQAHgEADgHQAEgGAAgLIAAiCQAAgJgCgEQgCgEgFAAQgDAAgGADIgBAAIgBgCIAAgCIAngSIABgBIADACIACACIAABmQAJgIAJgFQAIgEAMAAQAMAAAKAFQAKAFAGALQAGAMAAAQQAAATgIAOQgIAOgNAHQgOAHgPAAQgJAAgKgDgAgSAMIAAAoQAAAPAFAJQAFAKAHAEQAHAEAHAAQALAAAGgLQAHgMAAgWQAAgXgIgMQgIgLgOAAQgMAAgNAJg");
	this.shape_30.setTransform(39.9625,26.325);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AA4A1IgQAAIgPAAIgMABIgBgCIABgCQAJAAADgDQACgEAAgLIAAgmQAAgPgFgHQgFgHgLAAQgGAAgHADQgGADgGAEIAAA5QAAALADAEQADADAJAAIABACIgBACIgLgBIgRAAIgPAAIgMABIAAgCIAAgCQAJAAADgDQADgEAAgLIAAgyQAAgIgCgEQgCgEgFAAQgEAAgIAEIgBAAIgCgCIABgBIAmgTIACAAQADAAACAGQACAFABAKQATgWAVAAQAPAAAJAKQAIAJAAAPIAAAzQAAALADAEQADADAJAAIABACIgBACg");
	this.shape_31.setTransform(19.85,30.575);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAKA1IgWAAIgQAAIgLAAIAAgBIAAgCQAJAAADgDQADgFAAgLIAAgxQAAgJgCgDQgCgEgEAAQgFAAgJAEIAAAAIgCgCIABgBIAlgTIADAAQACgBADAGQACAGAAAJQALgLAHgFQAIgFAFABQAGgBAFAFQAHAFAAAFQgBAHgDADQgEAEgFAAQgEAAgDgCIgFgFIgEgEIgFgBQgCAAgDACIgKAJIAAA4QAAALAFAFQAFADAOAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_32.setTransform(7.65,30.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AATAzQgCgFgBgJQgJAJgIAFQgIAEgMAAQgLAAgJgFQgJgGgGgLQgFgKAAgQQAAgSAJgOQAJgPAOgHQAPgIAQAAQAOAAAMAHQAHgCAEgFIABAAIAAAAIABABIAABMQABAIABAEQABADAFAAQADAAAIgDIAAAAIACACIAAABIgmASIgBABQgDAAgBgFgAgZgkQgIAOAAAVQAAAUAHALQAHALANAAQAJAAANgJIAAgCIAAg3QAAgLgGgGQgGgHgIAAQgOAAgHANg");
	this.shape_33.setTransform(-3.5,30.775);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgWAvQgNgHgGgLQgHgNAAgNQAAgPAIgNQAJgNAOgJQAOgHAQAAQARAAAJAHQAJAHAAANQAAAHgDAAIgRAAIgvABIgBAMQAAAVALAOQAJANAUAAQAGAAAIgCQAHgBAGgEIABgBIABACIAAACQgKAJgKAEQgLAFgMAAQgQAAgMgIgAgKgqQgGAGgDAMIAmgBQgBgYgPAAQgHAAgGAHg");
	this.shape_34.setTransform(-16.0625,30.8);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AhCBUIAAgBIAAgCIANgBQAEgCABgEQACgDAAgJIAAh8QAAgIgCgDQgBgEgEgCQgEgBgJAAIAAgCIAAgBIAOAAIAVAAIAUAAIANAAIABABIgBACQgHAAgFABQgEACgBAEQgBADAAAJIAAB6IABAKQABADADACIAKABIAIAAQAVAAAQgLQAPgMAFgTIABAAIACAAIAAABQgCAaAAASIgBADIgDABg");
	this.shape_35.setTransform(-29.025,27.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78.9,9,299.9,67.4);


(lib.REDBG_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.REDBG();
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,600);


(lib.LOGO_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.LOGO();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.IMG3_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IMG3();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.IMG2_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IMG2();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.IMG1_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IMG1();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgxBIIAAiOIAVAAIAAAOQAFgGAIgFQAJgEAKAAQANAAAKAGQALAGAGALQAGAMAAAOQAAAPgGAKQgGAMgLAGQgKAHgNAAQgKAAgIgFQgJgEgFgHIAAA8gAgNgyQgHAEgEAHQgEAIAAAKQAAAKAEAHQAEAHAHAEQAGADAHAAQAIAAAGgEQAHgDAEgHQAEgIAAgKQAAgKgEgHQgEgHgHgEQgGgEgIAAQgHAAgGAEg");
	this.shape.setTransform(27.925,2.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgXA5QgLgFgGgLQgHgKAAgPIAAhNIAUAAIAABNQAAAOAIAHQAHAHAMAAQANAAAHgHQAIgHAAgOIAAhNIAUAAIAABNQAAAPgHAKQgGALgLAFQgLAFgNAAQgMAAgLgFg");
	this.shape_1.setTransform(15.625,-0.875);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AAZAxIAAg1QgBgNgGgHQgHgHgLAAQgKAAgHAHQgGAHAAANIAAA1IgVAAIAAhgIAVAAIAAALQAEgGAIgDQAIgDAIAAQALAAAJAEQAJAFAGAKQAEAJAAANIAAA4g");
	this.shape_2.setTransform(-0.65,0.275);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgdBAQgNgJgCgQIAUAAQACAHAIAFQAHAFAKAAQAMAAAHgIQAIgHAAgOIAAgQQgFAHgJAEQgJAFgKAAQgNAAgKgHQgLgGgGgMQgGgKAAgPQAAgOAGgMQAGgLALgGQAKgGANAAQAKAAAJAEQAJAFAFAGIAAgOIAUAAIAABiQAAANgGALQgFAKgLAGQgLAGgOAAQgTAAgNgJgAgNgzQgHAEgEAHQgEAHAAAKQAAAKAEAIQAEAHAHADQAHAEAGAAQAIAAAHgDQAGgEAEgHQAFgHAAgKQAAgKgFgIQgEgHgGgEQgHgEgIAAQgHAAgGAEg");
	this.shape_3.setTransform(-12.625,2.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgJBEIAAhgIATAAIAABggAgIgtQgEgDAAgGQAAgFAEgEQAEgEAEAAQAFAAAEAEQAEAEAAAFQAAAGgEADQgEAEgFAAQgEAAgEgEg");
	this.shape_4.setTransform(-20.575,-1.575);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgUA6QgKgEgGgIQgGgHAAgLIAWAAQABAIAFAEQAGAGAJAAQAKAAAGgFQAGgFAAgIQAAgGgEgEQgDgEgGgCIgOgEIgTgHQgIgDgFgGQgFgHAAgLQAAgLAFgIQAFgIAKgEQAJgEAMgBQASAAALAJQALAKACAPIgXAAQAAgHgGgFQgGgEgIAAQgJAAgFAEQgGAFAAAIQAAAGAEADQADAEAFABIAOAFQAMADAIAEQAHACAGAHQAFAHAAAMQAAAJgFAJQgFAHgKAFQgJAGgNAAQgMAAgJgFg");
	this.shape_5.setTransform(-28.225,-0.95);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AolCgIAAk/IRLAAIAAE/g");
	this.shape_6.setTransform(0.0492,0.0402,1.1,1.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.4,-17.5,121,35.2);


// stage content:
(lib.KSFY_214267_MM_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(214));

	// CTA
	this.instance = new lib.cta();
	this.instance.setTransform(150,354,0.5,0.5);
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.cta(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(38).to({_off:false},0).to({scaleX:1,scaleY:1},12,cjs.Ease.get(1)).wait(164));

	// T3
	this.instance_1 = new lib.T3("synched",0);
	this.instance_1.setTransform(159,294.65,0.5,0.5,0,0,0,80,42.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(156).to({_off:false},0).to({regY:42,scaleX:1,scaleY:1,alpha:1},10,cjs.Ease.get(1)).wait(48));

	// T2
	this.instance_2 = new lib.T2("synched",0);
	this.instance_2.setTransform(149,288.65,0.5,0.5,0,0,0,70,42.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(99).to({_off:false},0).to({regY:42.2,scaleX:1,scaleY:1,alpha:1},10,cjs.Ease.get(1)).wait(37).to({startPosition:0},0).to({regY:42.3,scaleX:0.5,scaleY:0.5,alpha:0},10,cjs.Ease.get(1)).to({_off:true},1).wait(57));

	// T1
	this.instance_3 = new lib.T1("synched",0);
	this.instance_3.setTransform(158.05,295.45,0.4,0.4,0,0,0,79.2,47.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(26).to({_off:false},0).to({regX:79,regY:47,scaleX:1,scaleY:1,x:158,alpha:1},11,cjs.Ease.get(1)).wait(52).to({startPosition:0},0).to({regY:47.1,scaleX:0.5,scaleY:0.5,alpha:0},10).to({_off:true},1).wait(114));

	// LOGO_png
	this.instance_4 = new lib.LOGO_1("synched",0);
	this.instance_4.setTransform(80,340.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(15).to({_off:false},0).to({y:300,alpha:1},10,cjs.Ease.get(1)).wait(189));

	// REDBG_png
	this.instance_5 = new lib.REDBG_png("synched",0);
	this.instance_5.setTransform(150,729);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({_off:false},0).to({y:300},11,cjs.Ease.get(1)).wait(202));

	// IMG3_png
	this.instance_6 = new lib.IMG3_1("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(156).to({_off:false},0).to({alpha:1},10).wait(48));

	// IMG2_png
	this.instance_7 = new lib.IMG2_1("synched",0);
	this.instance_7.setTransform(80,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(99).to({_off:false},0).to({alpha:1},10).wait(105));

	// IMG1_png
	this.instance_8 = new lib.IMG1_1("synched",0);
	this.instance_8.setTransform(80,135);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(1).to({_off:false},0).to({y:300},11,cjs.Ease.get(1)).to({_off:true},97).wait(105));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,135,152,894);
// library properties:
lib.properties = {
	id: '1D42CF45455647789E9AE0A47792069B',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"IMG1.png", id:"IMG1"},
		{src:"IMG2.png", id:"IMG2"},
		{src:"IMG3.png", id:"IMG3"},
		{src:"LOGO.png", id:"LOGO"},
		{src:"REDBG.png", id:"REDBG"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['1D42CF45455647789E9AE0A47792069B'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;