(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.IM1 = function() {
	this.initialize(img.IM1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.IM2 = function() {
	this.initialize(img.IM2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.PBB_logo1 = function() {
	this.initialize(img.PBB_logo1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,244,194);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// T2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3927").s().p("AgQBdQgLgLAAgHQAAgHALgKQAKgLAGAAQAHAAALALQAKAKAAAHQAAAHgKALQgLAKgHAAQgGAAgKgKgAgLAbQgCgFgBgNQgCgTgFgcQgEgWAAgOQAAgcAZAAQAbAAAAAcQAAANgFAXQgFAbgCAUQgBANgCAFQgDAHgJAAQgIAAgDgHg");
	this.shape.setTransform(170.275,-5.525);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B3927").s().p("AgcBGQgHgMAAgYQAAgSADgsQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBAAIgRAAQgEAAAAgFIAAgMQAAgEAEgBQATgCAIgLQAEgGADgPQABgEAEgBIARAAQAEABAAAEIAAAaQAAAGABABQABABAFAAIANAAIAQgCQAKABAAAFIgCAJQgBAFgDADQgCACgHAAIgOgBIgPAAQAAAAgBAAQgBAAAAAAQAAABgBAAQAAABAAAAIAAAYQAAAoAEANQAFAPAOAAQAGAAAHgEQAGgFADAAQAFAAAAAGQAAAFgDAFQgPAVgcgBQgcAAgLgVg");
	this.shape_1.setTransform(160.225,-4.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B3927").s().p("AgcBqQgLAAAAgHQAAgEAGgEQAIgFADgHQACgIABgWIAAgkQgBgNgBgEQgDgGgHgEQgJgEAAgEQgBgFAKgCQAYgGAOgFIAHgCQAIAAAAAKIAABRQAAAWACAIQADAHAIAFQAHAEAAAEQgBAHgKAAgAgPg+QgKgKAAgHQAAgGAKgKQAKgKAFAAQAHAAAKAKQAKAKAAAGQAAAHgKAKQgKAKgHAAQgFAAgKgKg");
	this.shape_2.setTransform(150.9,-6.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B3927").s().p("AgyBAQgKgIAAgWQAAgOALAAQAEAAAEAEIAJALQAPATARAAQAIAAAGgEQAHgEAAgIQAAgIgMgGIgZgIQgSgGgJgIQgMgJAAgSQAAgXATgOQASgNAYAAQAWAAANAHQANAGAAASQAAAKgCADQgDAFgGAAQgGAAgFgHQgNgVgSAAQgIAAgFAEQgGAEAAAHQAAAIANAFIAaAJQAoAOAAAeQAAAWgUAOQgTANgaAAQgfAAgPgMg");
	this.shape_3.setTransform(130.925,-2.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B3927").s().p("AgyBAQgKgIAAgWQAAgOALAAQAEAAAEAEIAJALQAPATARAAQAIAAAGgEQAHgEAAgIQAAgIgMgGIgZgIQgSgGgJgIQgMgJAAgSQAAgXATgOQASgNAYAAQAWAAANAHQANAGAAASQAAAKgCADQgDAFgGAAQgGAAgFgHQgNgVgSAAQgIAAgFAEQgGAEAAAHQAAAIANAFIAaAJQAoAOAAAeQAAAWgUAOQgTANgaAAQgfAAgPgMg");
	this.shape_4.setTransform(116.925,-2.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B3927").s().p("AgdBqQgKAAgBgHQAAgEAIgEQAHgFADgHQACgIAAgWIAAgkQAAgNgBgEQgDgGgHgEQgKgEABgEQAAgFAJgCQAXgGAPgFIAHgCQAHAAABAKIAABRQAAAWACAIQADAHAHAFQAIAEgBAEQABAHgLAAgAgPg+QgKgKAAgHQAAgGAKgKQAKgKAGAAQAGAAAKAKQAKAKAAAGQAAAHgKAKQgKAKgGAAQgGAAgKgKg");
	this.shape_5.setTransform(104.95,-6.125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B3927").s().p("AA/BLQgLAAAAgHQAAgFAHgEQAIgFADgHQADgIAAgVIAAgiQAAgagYAAQgKAAgIAHQgGAHgCANQgCAJAAAYQAAAaACAFQACAGAEAEQAIAGAAADQAAAHgLAAIgyAAQgLAAAAgHQABgEAHgFQAFgEABgGQACgFAAgaIAAgfQgBgdgWAAQgJAAgIAHQgGAGgDANQgCAMAAAWQAAAUACAJQAEAIAHAEQAHAEAAAFQAAAHgLAAIg8AAQgLAAAAgHQABgFAGgEQAIgEACgIQADgIAAgVIAAgjQAAgOgCgFQgCgGgIgDQgJgEAAgEQAAgFAJgDQAXgFAQgGQAEgCADAAQAIAAAAAKIAAAOIABABIABAAQARgZAdAAQAbAAANAXIABACIADgCQAPgXAdAAQAbAAANAVQAIANAAAYIAAAiQAAAVADAIQACAHAIAFQAHAEAAAFQgBAHgJAAg");
	this.shape_6.setTransform(85.9,-2.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3927").s().p("AgcBGQgHgMAAgYQAAgSADgsQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBAAIgRAAQgEAAAAgFIAAgMQAAgEAEgBQATgCAIgLQAEgGADgPQABgEAEgBIARAAQAEABAAAEIAAAaQAAAGABABQABABAFAAIANAAIAQgCQAKABAAAFIgCAJQgBAFgDADQgCACgHAAIgOgBIgPAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABAAAAIAAAYQAAAoAEANQAFAPAOAAQAGAAAHgEQAGgFADAAQAFAAAAAGQAAAFgDAFQgPAVgcgBQgcAAgLgVg");
	this.shape_7.setTransform(60.275,-4.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3927").s().p("AgKAcQgIgVAAgZQAAgLAEgEQAEgFAKAAQALAAAEAFQAEAEAAALQAAAZgIAVQgEALgHAAQgGAAgEgLg");
	this.shape_8.setTransform(51.825,-11.575);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3927").s().p("AASBLQgLAAAAgHQAAgFAHgEQAHgEAEgIQACgIAAgVIAAgiQAAgagXAAQgJAAgIAIQgMAMAAAoQgBAVADAIQADAIAHAEQAIAEgBAFQABAHgLAAIg9AAQgKAAAAgHQAAgFAHgEQAIgEACgIQADgIAAgVIAAgjQAAgNgCgGQgDgGgHgDQgJgEAAgEQAAgGAKgCQATgEASgHQAEgCAEAAQAHAAABAKIAAANQAAABAAAAQAAABAAAAQAAAAAAAAQAAAAABAAIABgBQAQgYAcAAQAbAAANAVQAIAMAAAZIAAAiQAAAUADAJQACAHAJAFQAGAEAAAFQAAAHgKAAg");
	this.shape_9.setTransform(43.05,-2.975);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3927").s().p("Ag2A4QgWgVAAgiQAAgfAXgWQAXgXAgAAQAhAAAVAVQAVAVAAAhQAAAfgWAXQgXAWggAAQghAAgVgUgAgfgKQAAAVAHASQAJAaASAAQAOAAAIgOQAHgNAAgVQAAgVgHgRQgJgXgRAAQgeAAAAAsg");
	this.shape_10.setTransform(26.225,-2.825);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3927").s().p("AAWBhIAAgLQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAAAAAAAIgDACQgSAWgZAAQgaAAgRgUQgQgTAAgeQAAggATgYQAWgbAgABQAQAAAOAGIACABQABAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQAAgNgBgGQgDgGgHgDQgKgDABgEQAAgGAJgCQAXgGAPgGIAIgBQAHAAAAAJIAACSQAAANACAGQACAFAIAEQAIAEAAAEQAAAEgJADIgkALIgJACQgIAAAAgJgAghgHQgHAMAAAVQAAAWAJAOQAIAOAQAAQAMAAAIgMQAKgNgBgYQABgYgKgNQgIgOgNAAQgRAAgIARg");
	this.shape_11.setTransform(11.45,-5.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3927").s().p("Ah5AQQgEAAAAgFIAAgVQAAgFAEAAIDzAAQAEAAAAAFIAAAVQAAAFgEAAg");
	this.shape_12.setTransform(-12.175,-3.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3927").s().p("AhABJQgUgcAAgrQAAgsAZgeQAageAjAAQAnAAAWAcQAWAbAAAtQAAAxgaAeQgZAagiAAQgqAAgWgegAgigGQAAAlAJAXQAKAZARAAQAhAAAAhIQAAgqgKgWQgKgWgPAAQgiAAAABJg");
	this.shape_13.setTransform(-35.275,-5.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3927").s().p("AgrBiQgRgGgHgKQgGgJAAgRQAAgLACgEQADgGAIAAQAGAAAFAHIAJAQQAOAXATAAQAOAAAIgMQAHgKAAgSQAAgiggAAIgRABQgLAAAAgIIAAgIQAAgJAKAAIARABQAcAAABghQAAgNgGgIQgHgKgMAAQgOAAgKAMIgMATQgGAKgGAAQgGAAgCgEQgDgFAAgMQAAgVAMgJQARgMAhAAQAeAAATAMQAXAOAAAYQAAAPgLAMQgMANgXAGQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAABAAQAAABABAAQAWACANALQAQANAAAUQAAAWgRAQQgXAWgpAAQgUAAgQgFg");
	this.shape_14.setTransform(-52.425,-5.525);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("AhFBdQgIgJAAgNQAAgSAOgBQAEAAAJAJQAIAIAJAAQALAAAHgLIACgEIgBgDIgvhtQgHgQgFgGIgJgFQgFgDAAgEQAAgHALAAIA8AAQAKAAAAAHQAAAEgHAEQgIADAAAGQAAAEAEAHIAaA+IABACIACgCIARgoQAHgRAAgJQAAgKgIgFQgHgFAAgEQAAgHALAAIAtAAQALAAAAAHQAAAEgFADIgHAFQgFAEgFAHQgGAJgJAVIggBPQgYA8gqAAQgNAAgJgHg");
	this.shape_15.setTransform(-73.975,-0.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AARA3IgBgBIgCABQgPAVgdAAQgSAAgMgJQgPgKAAgSQABgWAUgMQAOgHAggLQAUgKAAgOQAAgQgRAAQgKAAgHAFQgHAEgJANQgHAJgGAAQgHAAgCgEQgDgEAAgJQAAgPAFgGQAHgIASgEQAOgDAOAAQAZAAARALQAUANAAAXIgBA1QAAAPABAFQADAGAIAAQAIABgBAFQABAGgIAFQgJAIgOAAQgXAAgFgVgAAKAAQgTAIgJAHQgMAIAAALQAAAHAFAFQAFAEAIAAQANAAAIgOQADgHAAgZIAAgDIAAgBg");
	this.shape_16.setTransform(-90.25,-2.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("AAuBkQgKAAgBgHQAAgEAIgEQAHgFACgIQADgHAAgWIAAhnIgBgCQAAAAAAABQAAAAgBAAQAAAAAAABQAAAAgBABIgxB4QgCAHgEAAIgOAAQgEAAgDgHIgyh5IgBgCQgBAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAQAABkABALQABAXAOAHIAJAFQAEADABADQAAAIgMAAIgyAAQgMAAAAgHQAAgEAEgCQAGgFACgDQAHgKABgiIABhnQAAgGgBgCQgCgDgEgDIgIgDQgEgDAAgEQAAgHAMAAIA3AAQAJAAADAGIAoBdIAAACIABgCIAohdQACgGAHAAIA8AAQAKAAAAAGQAAAEgDADIgHADQgIAEAAAQIAABqQAAAWADAHQADAIAHAFQAHAEAAAEQAAAHgLAAg");
	this.shape_17.setTransform(-110.55,-5.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AgyBAQgKgIAAgWQAAgOALAAQAEAAAEAEIAJALQAPATARAAQAIAAAGgEQAHgEAAgIQAAgIgMgGIgZgIQgSgGgJgIQgMgJAAgSQAAgXATgOQASgNAYAAQAWAAANAHQANAGAAASQAAAKgCADQgDAFgGAAQgGAAgFgHQgNgVgSAAQgIAAgFAEQgGAEAAAHQAAAIANAFIAaAJQAoAOAAAeQAAAWgUAOQgTANgaAAQgfAAgPgMg");
	this.shape_18.setTransform(-138.475,-2.825);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("AAXBhIAAgLQAAgBgBgBQAAgBAAAAQAAgBgBAAQAAAAAAAAIgDACQgRAWgaAAQgaAAgQgUQgQgTAAgeQAAggASgYQAWgbAgABQAPAAAPAGIADABQAAAAAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIAAgJQAAgNgCgGQgCgGgIgDQgJgDAAgEQgBgGAKgCQAXgGAPgGIAIgBQAHAAAAAJIAACSQAAANACAGQACAFAIAEQAJAEAAAEQAAAEgKADIgjALIgKACQgHAAAAgJgAghgHQgHAMABAVQAAAWAIAOQAIAOAPAAQANAAAJgMQAJgNAAgYQAAgYgJgNQgJgOgOAAQgQAAgIARg");
	this.shape_19.setTransform(-153.55,-5.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AASBLQgLAAAAgHQAAgFAHgEQAHgEAEgIQACgIAAgVIAAgiQAAgagXAAQgJAAgIAIQgMAMgBAoQABAVACAIQADAIAHAEQAIAEgBAFQABAHgMAAIg8AAQgKAAAAgHQAAgFAHgEQAIgEACgIQADgIAAgVIAAgjQAAgNgCgGQgDgGgHgDQgJgEAAgEQAAgGAJgCQAUgEASgHQAEgCAEAAQAHAAAAAKIAAANQAAABABAAQAAABAAAAQAAAAAAAAQAAAAAAAAIACgBQAQgYAcAAQAbAAANAVQAIAMAAAZIAAAiQAAAUADAJQACAHAIAFQAHAEAAAFQAAAHgKAAg");
	this.shape_20.setTransform(-170.6,-2.975);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AgvA5QgVgUAAghQAAgfAVgYQAWgYAfAAQAZAAASAPQAUARAAAZQAAAMgGAEQgFACgNAAIhCAAQgBAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIAAAEQABALAGAKQAOAVAaAAQANAAALgGIANgGQAGAAAAAGQAAAKgRALQgUANgaAAQgeAAgUgTgAgOguQgIAIgCANIgBADQAAAAAAABQABAAAAABQAAAAABAAQABAAAAAAIAgAAQARAAAAgMQAAgJgGgGQgGgHgKAAQgLAAgIAIg");
	this.shape_21.setTransform(-188.175,-2.825);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AgvA5QgVgUAAghQAAgfAVgYQAWgYAfAAQAZAAASAPQAUARAAAZQAAAMgGAEQgFACgNAAIhCAAQgBAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIAAAEQABALAGAKQAOAVAaAAQANAAALgGIANgGQAGAAAAAGQAAAKgRALQgUANgaAAQgeAAgUgTgAgOguQgIAIgCANIgBADQAAAAAAABQABAAAAABQAAAAABAAQABAAAAAAIAgAAQARAAAAgMQAAgJgGgGQgGgHgKAAQgLAAgIAIg");
	this.shape_22.setTransform(-211.475,-2.825);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AgcBpQgLAAAAgIQAAgEAGgEQAJgFACgHQADgIAAgVIAAhgQAAgNgCgFQgCgGgIgDQgJgEAAgEQgBgGAKgCQAYgGAOgFIAHgBQAIAAAAAJIAACOQAAAVACAIQADAHAHAFQAIAEAAAEQgBAIgKAAg");
	this.shape_23.setTransform(-222.6,-5.95);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B3927").s().p("AARA3IgBgBIgCABQgPAVgdAAQgSAAgMgJQgOgKgBgSQAAgWAVgMQANgHAhgLQAUgKAAgOQAAgQgRAAQgJAAgIAFQgHAEgJANQgHAJgFAAQgIAAgCgEQgDgEAAgJQAAgPAGgGQAFgIATgEQAOgDAPAAQAYAAAQALQAVANAAAXIgBA1QAAAPACAFQABAGAJAAQAIABAAAFQAAAGgIAFQgJAIgPAAQgWAAgFgVgAAJAAQgSAIgKAHQgLAIAAALQABAHAEAFQAFAEAIAAQAOAAAGgOQAEgHAAgZIAAgDIAAgBg");
	this.shape_24.setTransform(-235,-2.825);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B3927").s().p("AgtBhQgTgGgGgKQgGgJAAgQIgBgLQAAgNALAAQAGAAAFAIIAPASQAUAWAVAAQAPAAAJgIQAJgIAAgMQAAgOgQgKIgjgOQgYgKgLgIQgRgOAAgWQAAgaAWgSQAWgSAgAAQAmAAAQAQQAHAHAAAUQAAATgLAAQgFAAgFgFIgLgOQgSgVgSAAQgKAAgHAGQgJAHAAALQAAAOARAJIAjAOQAYAJALAKQARAOAAAYQAAAdgYASQgYASgjAAQgWAAgSgGg");
	this.shape_25.setTransform(-253.175,-5.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-282.9,-19,476.9,32);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// T1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3927").s().p("AgLAMQgHgHAAgFQAAgEAHgHQAIgHADAAQAFAAAHAHQAHAHAAAEQAAAFgHAHQgHAHgFAAQgDAAgIgHg");
	this.shape.setTransform(170.475,29.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B3927").s().p("AglAxQgHgHAAgQQAAgJAHAAQADAAADADIAHAIQAMAQAMAAQAJAAAGgEQAFgEAAgHQAAgJgMgEIgTgHQgNgEgHgFQgJgIAAgNQAAgUATgLQALgGAPAAQARAAAJAGQAIAFAAANQAAANgGAAQgFAAgDgFQgLgSgNAAQgHAAgFAEQgFAEAAAGQAAAJAQAFIAUAHQALAFAGAFQAIAIAAAMQAAASgQALQgNAJgSAAQgYAAgLgKg");
	this.shape_1.setTransform(161.975,25.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B3927").s().p("AAUBMIAAgKQAAgBAAAAQAAgBAAAAQAAAAAAAAQgBgBAAAAIgCABQgOASgUAAQgJAAgKgFQgZgNAAgjQAAgbAPgRQAQgTAXgBQANABANAGIAAAAIABAAIAAgMQAAgMgCgEQgBgEgGgCQgFgCAAgDQAAgDAFgCIAXgHIAIgCQAFAAgBAHIAABzQAAANADADQABADAGACQAGADAAADQAAAEgHABQgPAEgJAEIgFABQgFAAgBgGgAgbgKQgGALgBATQAAASAIANQAIAMAMgBQALAAAIgJQAHgLAAgUQABgVgIgLQgHgLgMABQgNgBgIALg");
	this.shape_2.setTransform(150,23.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B3927").s().p("AgUBRQgHAAAAgFQAAgDAFgDQAGgDABgEQADgGAAgRIAAhPQAAgMgCgDQgCgEgFgCQgGgDAAgDQAAgEAGgBQAMgCAJgEIAIgDQAGAAAAAHIAABxQAAARACAGQACAEAGADQAEADAAADQAAAFgHAAg");
	this.shape_3.setTransform(139.925,23.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B3927").s().p("AgTBRQgIAAAAgEQAAgDAFgDQAGgDACgFQACgFAAgRIAAghQAAgMgCgEQgCgDgFgDQgGgCAAgCQAAgEAGgCQAMgCAJgEIAIgDQAGAAAAAHIAABDQAAARACAFQACAEAGAEQAEADAAADQAAAEgHAAgAgKg0QgHgGAAgFQAAgEAHgGQAHgIADABQAEgBAHAIQAHAGAAAEQAAAFgHAGQgHAIgEAAQgDAAgHgIg");
	this.shape_4.setTransform(133.525,23);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B3927").s().p("AAYA0IAAgMIgBgBIgBABQgNATgVAAQgUAAgJgOQgIgKABgUIAAggQAAgMgCgEQgCgEgGgCQgGgCAAgDQAAgEAHgBQAOgEALgEIAFgBQAFAAAAAHIAABCQAAAXAUAAQAJAAAGgGQALgKAAgkQAAgPgCgEQgCgEgGgCQgGgCAAgDQAAgEAHgBQAOgEAKgEIAFgBQAGAAAAAHIAABFQAAALABAFQACADAGADQAGACAAADQAAAEgGABIgaAIIgEABQgFAAAAgHg");
	this.shape_5.setTransform(123.2,25.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B3927").s().p("AgWBLQgEgEgCAAQgEABgCAEQgDAGgEAAQgEAAAAgJIAAhxQAAgLgDgFQgBgEgGgCQgGgCAAgDQAAgDAHgCQAOgEAKgEIAGgBQAEAAABAHIAAA4QAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIACgBQAOgSAUAAQAUAAAMAQQAMAQAAAUQAAATgIAPQgQAfghAAQgPAAgMgHgAgMgFQgHAJAAAVQAAAUAHAMQAIAMAMAAQAMgBAIgLQAGgMABgTQAAgSgIgLQgIgMgMAAQgLAAgIAKg");
	this.shape_6.setTransform(109.65,23.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3927").s().p("AAQA5QgHAAAAgEQAAgDAEgDQAGgDACgFQADgFAAgRIAAgeQAAgLgGgGQgFgGgKAAQgIAAgHAGQgGAGgCAKQgCALAAAUQAAARADAFQACAFAFADQAFADAAADQAAAEgHAAIgqAAQgHAAAAgEQAAgDAFgDQAFgEACgEQADgFAAgRIAAggQAAgNgCgEQgCgDgGgDQgGgCAAgCQAAgEAHgCQAOgDAHgDIAJgDQAFAAAAAHIAAAMIABABIABgBQANgSAVgBQAUAAAJAPQAHAKAAATIAAAeQAAARADAFQACAFAFADQAFADAAADQAAAEgIAAg");
	this.shape_7.setTransform(92.575,25.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3927").s().p("AgjA5QgHAAAAgEQAAgDAFgDQAFgDACgFQADgFAAgRIAAghQAAgMgCgEQgCgDgGgDQgGgCAAgCQAAgEAHgCQAOgDAJgFIAFgBQAFAAAAAHIAAARIABABIAAgBQADgJAIgHQAJgIAKAAQAHAAAEAFQAFAFAAAIQAAAMgJAAQgDgBgFgDQgFgCgDAAQgFAAgFAEQgKALAAAjQAAARACAFQACAFAFADQAFADAAADQAAAEgHAAg");
	this.shape_8.setTransform(81.525,25.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3927").s().p("AAQApIgBAAQgMASgXAAQgOAAgJgIQgLgIAAgNQAAgQAPgJQALgGAZgIQAQgIAAgMQAAgLgLgDIgFgBQgIAAgHAGQgEADgEAGIgFAHQgDADgEAAQgHAAAAgMQAAgLAEgFQAEgGANgCQAKgDALAAQATAAANAKQAMAKAAARIAAAtQAAARAGAAIADAAQAFAAAAAEQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABQgGAJgMAAQgRAAgCgSgAAMgCIgMAGQgLAEgEAEQgKAGAAAKQAAAGAFAEQAEAEAGAAQANAAAGgNQAEgIAAgTIAAgDIgBgBg");
	this.shape_9.setTransform(70.325,25.525);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3927").s().p("AgWBLQgEgEgCAAQgEABgCAEQgDAGgEAAQgEAAAAgJIAAhxQAAgLgDgFQgBgEgGgCQgGgCAAgDQAAgDAHgCQAOgEAKgEIAGgBQAEAAABAHIAAA4QAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIACgBQAOgSAUAAQAUAAAMAQQAMAQAAAUQAAATgIAPQgQAfghAAQgPAAgMgHgAgMgFQgHAJAAAVQAAAUAHAMQAIAMAMAAQAMgBAIgLQAGgMABgTQAAgSgIgLQgIgMgMAAQgLAAgIAKg");
	this.shape_10.setTransform(57.9,23.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3927").s().p("AAyA5QgGAAgBgEQAAgDAFgDQAFgDACgFQADgFAAgRIAAgeQAAgXgUAAQgKAAgGAGQgFAGgCAKIgBAfQAAATABAEQACAFAEACQAFADAAADQAAAEgHAAIgjAAQgIAAABgEQgBgCAFgEQAEgDACgEQABgEAAgTIAAgcQAAgZgTAAQgJAAgGAGQgGAFgCALQgCAKAAAVQAAARACAFQADAEAFAEQAEADABADQAAAEgIAAIgpAAQgHAAAAgEQAAgDAEgDQAGgDACgFQADgFgBgRIAAggQABgNgCgEQgDgDgFgDQgGgCAAgCQAAgEAHgCQAPgDAJgFIAGgBQAFAAAAAHIAAAMIAAABIABgBQANgTAXAAQAMABAIAGQAHAEAEAIIAAACIACgCQAMgTAXAAQASAAAKAPQAIAKAAATIAAAeQgBARADAFQACAEAGAEQAEADAAADQAAAEgHAAg");
	this.shape_11.setTransform(38.25,25.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3927").s().p("AAQApIgBAAQgMASgXAAQgOAAgJgIQgLgIAAgNQAAgQAPgJQALgGAZgIQAQgIAAgMQAAgLgLgDIgFgBQgIAAgHAGQgEADgEAGIgFAHQgDADgEAAQgHAAAAgMQAAgLAEgFQAEgGANgCQAKgDALAAQATAAANAKQAMAKAAARIAAAtQAAARAGAAIADAAQAFAAAAAEQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABQgGAJgMAAQgRAAgCgSgAAMgCIgMAGQgLAEgEAEQgKAGAAAKQAAAGAFAEQAEAEAGAAQANAAAGgNQAEgIAAgTIAAgDIgBgBg");
	this.shape_12.setTransform(21.525,25.525);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3927").s().p("AgaAzQgPgJgFgQQgEgMgBgLQAAgQAIgOQAIgQAQgIQALgHANAAQASAAAMALQAQANABATQgBAIgDACQgEAFgKAAIg2AAQgBAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAOAHALQALANAQAAQAMAAALgFIAKgGQAFAAAAAFQAAAIgOAIQgOAJgTAAQgPABgNgIgAgRggQgGAJAAAHQAAAAAAABQAAAAABABQAAAAAAAAQABAAABAAIAcAAQAQAAABgKQgBgIgFgGQgHgGgKAAQgLAAgIAMg");
	this.shape_13.setTransform(9.6,25.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3927").s().p("AgWBLQgEgEgCAAQgEABgCAEQgDAGgEAAQgEAAAAgJIAAhxQAAgLgDgFQgBgEgGgCQgGgCAAgDQAAgDAHgCQAOgEAKgEIAFgBQAFAAABAHIAAA4QAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIACgBQAOgSAUAAQAUAAAMAQQAMAQAAAUQAAATgIAPQgQAfghAAQgPAAgMgHgAgMgFQgHAJAAAVQAAAUAHAMQAIAMAMAAQAMgBAIgLQAGgMABgTQAAgSgIgLQgIgMgMAAQgLAAgIAKg");
	this.shape_14.setTransform(-2.85,23.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("Ag1A5QgRgNgBgUQABgNAHgKQAIgIAMgEQgFgKAAgJQAAgSANgKQALgKAQAAQATAAAHAJQADAEAAALQABAQgIAAQgEgBgDgEIgDgGIgEgIQgFgHgIAAQgGAAgEAFQgFAFAAAHQAAAKAKAJQAHAJASAKIAcATIABAAQADgGAAgIQAAgLgMgGQgEgDAAgEQAAgEAGAAIAkAAQAGAAAAAFQAAACgFAEQgHAEgDAHQgFATgFAIIAAABIABABIAHAHQALAOAAANQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAIgSAAQgDAAgBgEQgCgGgFgGIgBAAIgBAAQgQASgeAAQgWAAgQgMgAgmAAQgFAHgBAKQAAAOAMAMQAMALAPgBQAPABAKgKIABgBIgBgBIgcgUQgUgNgIgJIgBgBIgBABg");
	this.shape_15.setTransform(-21.55,24.45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AgTA3QgFgIAAgSIABg1QAAAAAAAAQAAgBAAAAQAAAAgBAAQAAgBgBAAIgNAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgIQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAPgDAFgJQABgDADgLQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAIALAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAWQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAAAQABABAAAAQABAAAAAAQABAAABAAIAYgCQAHAAAAAFIgBAFQAAAHgKAAIgYgBQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAABIAAAYQAAAeADAKQAEAKALAAQAFAAAGgEIAHgDQAEAAAAADQAAAEgDADQgFAHgHAEQgJAGgKAAQgTgBgIgPg");
	this.shape_16.setTransform(-36.95,24.35);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("AglAxQgHgHAAgQQAAgJAHAAQADAAADADIAHAIQAMAQAMAAQAJAAAGgEQAFgEAAgHQAAgJgMgEIgTgHQgNgEgHgFQgJgIAAgNQAAgUATgLQALgGAPAAQARAAAJAGQAIAFAAANQAAANgGAAQgFAAgDgFQgLgSgNAAQgHAAgFAEQgFAEAAAGQAAAJAQAFIAUAHQALAFAGAFQAIAIAAAMQAAASgQALQgNAJgSAAQgYAAgLgKg");
	this.shape_17.setTransform(-47.225,25.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AgpArQgPgQAAgaQAAgYAQgRQAQgSAYAAQAbAAAPARQAPAQAAAZQAAAYgRARQgQASgYAAQgZAAgQgQgAgUgjQgIAKABASQgBAVAIAPQAJAQANAAQAMAAAIgLQAHgLAAgRQAAgTgIgPQgIgRgOAAQgMAAgHAKg");
	this.shape_18.setTransform(-58.75,25.525);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("Ag1BOQgHAAAAgEQAAgDAFgDQAEgDADgFQACgGAAgQIAAhKQAAgNgBgDQgCgEgGgCQgGgCAAgDQAAgEAHgCQANgDALgEIAFgBQAGAAAAAGIAAAKQAAABAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIACgBQANgRAVAAQAKAAAJAEQAZAOAAAiQAAAagPATQgPATgYAAQgNAAgNgHIgBAAIAAABIAAAGQAAAQACAFQACAFAGADQAFADAAADQAAAEgIAAgAgLgwQgJALABAUQgBAUAJALQAHAMAMAAQANAAAHgNQAGgLAAgSQAAgSgHgMQgIgMgMAAQgMAAgGAKg");
	this.shape_19.setTransform(-71.85,27.475);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AgjA5QgHAAAAgEQAAgDAFgDQAFgDACgFQADgFAAgRIAAghQAAgMgCgEQgCgDgGgDQgGgCAAgCQAAgEAHgCQAOgDAJgFIAFgBQAFAAAAAHIAAARIABAAIAAAAQADgJAIgHQAJgIAKAAQAHAAAEAFQAFAFAAAIQAAAMgJAAQgDgBgFgDQgFgCgDAAQgFAAgFAEQgKALAAAjQAAARACAFQACAFAFADQAFADAAADQAAAEgHAAg");
	this.shape_20.setTransform(269.125,1.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AAQApIgBAAQgMASgXAAQgOAAgJgIQgLgIAAgNQAAgQAPgJQALgGAZgIQAQgIAAgMQAAgLgLgDIgFgBQgIAAgHAGQgEADgEAGIgFAHQgDADgEAAQgHAAAAgMQAAgLAEgFQAEgGANgCQAKgDALAAQATAAANAKQAMAKAAARIAAAtQAAARAGAAIADAAQAFAAAAAEQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABQgGAJgMAAQgRAAgCgSgAAMgCIgMAGQgLAEgEAEQgKAGAAAKQAAAGAFAEQAEAEAGAAQANAAAGgNQAEgIAAgTIAAgDIgBgBg");
	this.shape_21.setTransform(257.925,1.225);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AgUBRQgHAAAAgFQAAgDAFgDQAGgDABgEQADgGAAgRIAAhPQAAgMgCgDQgCgEgFgCQgGgDAAgDQAAgEAGgBQAMgCAJgEIAIgDQAGAAAAAHIAABxQAAARACAGQACAEAGADQAEADAAADQAAAFgHAAg");
	this.shape_22.setTransform(248.875,-1.225);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AAXA0IAAgMIgBgBIgBABQgMATgWAAQgSAAgKgOQgIgKAAgUIAAggQAAgMgBgEQgCgEgGgCQgGgCAAgDQAAgEAHgBQAOgEALgEIAFgBQAFAAAAAHIAABCQAAAXAUAAQAJAAAGgGQAKgKAAgkQAAgPgCgEQgCgEgFgCQgGgCAAgDQAAgEAGgBQAPgEAKgEIAGgBQAEAAAAAHIAABFQAAALACAFQADADAFADQAGACAAADQAAAEgHABIgZAIIgEABQgGAAAAgHg");
	this.shape_23.setTransform(238.7,1.225);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B3927").s().p("Ag1BOQgHAAAAgEQAAgDAFgDQAEgDADgFQACgGABgQIAAhKQAAgNgCgDQgCgEgGgCQgGgCAAgDQAAgEAHgCQANgDALgEIAFgBQAGAAAAAGIAAAKQAAABAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIACgBQAOgRAUAAQAKAAAJAEQAZAOAAAiQAAAagPATQgPATgXAAQgNAAgNgHIgBAAIgBABIAAAGQAAAQACAFQACAFAGADQAFADgBADQABAEgIAAgAgLgwQgJALABAUQgBAUAJALQAHAMAMAAQANAAAHgNQAGgLABgSQgBgSgHgMQgHgMgNAAQgMAAgGAKg");
	this.shape_24.setTransform(225.5,3.175);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B3927").s().p("AgoArQgQgQAAgaQAAgYAQgRQARgSAXAAQAbAAAPARQAPAQAAAZQAAAYgQARQgRASgYAAQgZAAgPgQgAgUgjQgIAKAAASQAAAVAIAPQAIAQAOAAQANAAAHgLQAHgLAAgRQAAgTgHgPQgJgRgOAAQgMAAgHAKg");
	this.shape_25.setTransform(213.3,1.225);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B3927").s().p("Ag1BOQgHAAAAgEQAAgDAEgDQAFgDADgFQACgGAAgQIAAhKQAAgNgCgDQgBgEgGgCQgGgCAAgDQAAgEAHgCQANgDALgEIAGgBQAFAAAAAGIAAAKQAAABAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIACgBQANgRAVAAQAKAAAJAEQAZAOAAAiQAAAagPATQgPATgYAAQgNAAgNgHIgBAAIAAABIAAAGQAAAQADAFQABAFAGADQAEADABADQgBAEgHAAgAgMgwQgHALgBAUQABAUAHALQAIAMALAAQAOAAAHgNQAHgLgBgSQABgSgIgMQgIgMgNAAQgKAAgIAKg");
	this.shape_26.setTransform(200.7,3.175);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B3927").s().p("AgTA3QgFgIAAgSIABg1QAAAAAAAAQAAgBAAAAQAAAAgBAAQAAgBAAAAIgOAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgIQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAQgDAEgJQABgDADgLQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAIALAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAWQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAAAQABABAAAAQABAAAAAAQABAAABAAIAYgCQAHAAAAAFIgBAFQAAAHgJAAIgZgBQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAABIAAAYQAAAeADAKQAEAKALAAQAFAAAGgEIAHgDQAEAAAAADQAAAEgDADQgFAHgHAEQgKAGgJAAQgTgBgIgPg");
	this.shape_27.setTransform(185.7,0.05);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B3927").s().p("AglAxQgHgHAAgQQAAgJAHAAQADAAADADIAHAIQAMAQAMAAQAJAAAGgEQAFgEAAgHQAAgJgMgEIgTgHQgNgEgHgFQgJgIAAgNQAAgUATgLQALgGAPAAQARAAAJAGQAIAFAAANQAAANgGAAQgFAAgDgFQgLgSgNAAQgHAAgFAEQgFAEAAAGQAAAJAQAFIAUAHQALAFAGAFQAIAIAAAMQAAASgQALQgNAJgSAAQgYAAgLgKg");
	this.shape_28.setTransform(175.425,1.225);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B3927").s().p("AgoArQgQgQAAgaQAAgYAQgRQAQgSAYAAQAbAAAPARQAPAQAAAZQAAAYgRARQgQASgYAAQgZAAgPgQgAgUgjQgIAKAAASQAAAVAIAPQAIAQAOAAQAMAAAIgLQAHgLAAgRQAAgTgHgPQgJgRgOAAQgMAAgHAKg");
	this.shape_29.setTransform(163.9,1.225);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B3927").s().p("AAyA5QgGAAAAgEQgBgDAFgDQAFgDACgFQADgFAAgRIAAgeQAAgXgUAAQgKAAgGAGQgGAGgBAKIgBAfQAAATACAEQABAFAEACQAFADAAADQAAAEgHAAIgjAAQgIAAAAgEQABgCAEgEQAEgDABgEQACgEAAgTIAAgcQAAgZgTAAQgJAAgGAGQgGAFgCALQgCAKAAAVQAAARADAFQACAEAFAEQAEADAAADQABAEgIAAIgpAAQgHAAAAgEQAAgDAEgDQAGgDACgFQADgFAAgRIAAggQAAgNgCgEQgDgDgFgDQgGgCAAgCQAAgEAHgCQAPgDAJgFIAGgBQAFAAAAAHIAAAMIABABIABgBQAMgTAXAAQALABAJAFQAHAFADAIIABACIABgCQANgTAWAAQAUAAAJAPQAIAKgBATIAAAeQABARACAFQACAEAFAEQAFADAAADQAAAEgHAAg");
	this.shape_30.setTransform(148.35,1.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B3927").s().p("AgjA5QgHAAAAgEQAAgDAFgDQAFgDACgFQADgFAAgRIAAghQAAgMgCgEQgCgDgGgDQgGgCAAgCQAAgEAHgCQAOgDAJgFIAFgBQAFAAAAAHIAAARIABAAIAAAAQADgJAIgHQAJgIAKAAQAHAAAEAFQAFAFAAAIQAAAMgJAAQgDgBgFgDQgFgCgDAAQgFAAgFAEQgKALAAAjQAAARACAFQACAFAFADQAFADAAADQAAAEgHAAg");
	this.shape_31.setTransform(129.675,1.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B3927").s().p("AAYA0IAAgMIgBgBIgBABQgNATgVAAQgUAAgJgOQgIgKABgUIAAggQAAgMgCgEQgCgEgGgCQgGgCAAgDQAAgEAHgBQAOgEALgEIAFgBQAFAAAAAHIAABCQAAAXAUAAQAJAAAGgGQALgKAAgkQAAgPgCgEQgCgEgGgCQgGgCAAgDQAAgEAHgBQAOgEAKgEIAFgBQAGAAAAAHIAABFQAAALABAFQACADAGADQAGACAAADQAAAEgGABIgaAIIgEABQgFAAAAgHg");
	this.shape_32.setTransform(118.7,1.225);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B3927").s().p("AgpArQgPgQAAgaQAAgYAQgRQARgSAXAAQAaAAAQARQAPAQAAAZQAAAYgRARQgQASgYAAQgZAAgQgQgAgUgjQgHAKAAASQAAAVAHAPQAJAQANAAQAMAAAIgLQAHgLAAgRQAAgTgIgPQgIgRgOAAQgMAAgHAKg");
	this.shape_33.setTransform(106.15,1.225);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B3927").s().p("AgUAfQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAFgDAFgGQAHgHAAgGQAAgFgHgGQgHgIgBgEQAAgEAIgHQAGgHAEAAQAFAAAHAJQAHAHAAAJQAAANgQARQgMAQgIAAQgFAAAAgFg");
	this.shape_34.setTransform(90.75,7.05);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B3927").s().p("AglAxQgHgHAAgQQAAgJAHAAQADAAADADIAHAIQAMAQAMAAQAJAAAGgEQAFgEAAgHQAAgJgMgEIgTgHQgNgEgHgFQgJgIAAgNQAAgUATgLQALgGAPAAQARAAAJAGQAIAFAAANQAAANgGAAQgFAAgDgFQgLgSgNAAQgHAAgFAEQgFAEAAAGQAAAJAQAFIAUAHQALAFAGAFQAIAIAAAMQAAASgQALQgNAJgSAAQgYAAgLgKg");
	this.shape_35.setTransform(82.075,1.225);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B3927").s().p("AgTA3QgFgIAAgSIABg1QAAAAAAAAQAAgBAAAAQAAAAgBAAQAAgBgBAAIgNAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgIQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAPgDAFgJQABgDADgLQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAIALAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAWQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAAAQABABAAAAQABAAAAAAQABAAABAAIAYgCQAHAAAAAFIgBAFQAAAHgKAAIgYgBQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAABIAAAYQAAAeADAKQAEAKALAAQAFAAAGgEIAHgDQAEAAAAADQAAAEgDADQgFAHgHAEQgJAGgKAAQgTgBgIgPg");
	this.shape_36.setTransform(72.85,0.05);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B3927").s().p("AgTBRQgIAAAAgEQAAgDAFgDQAGgDACgFQACgFAAgRIAAghQAAgMgCgEQgCgDgFgDQgGgCAAgCQAAgEAGgCQAMgDAJgDIAIgDQAGAAAAAHIAABDQAAARACAFQACAEAGAEQAEADAAADQAAAEgHAAgAgKg0QgHgGAAgFQAAgEAHgGQAHgIADABQAEgBAHAIQAHAGAAAEQAAAFgHAGQgHAIgEAAQgDAAgHgIg");
	this.shape_37.setTransform(66.175,-1.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B3927").s().p("AArBRQgLAAgFgDQgFgEgOgWQgMgVgEAAQgCAAgEADIgGAHIgBADQAAANACAFQACAFAGADQAEADAAADQAAAFgHAAIgqAAQgHAAAAgFQAAgDAEgDQAFgDADgFQACgFAAgSIAAhNQAAgMgBgEQgDgEgFgCQgGgCAAgDQAAgEAGgCQAQgDAIgEIAHgCQAFAAAAAHIAABdIABABIABAAIATgTQAOgNAAgGQAAgCgEgCQgDgDAAgCQAAgFAHAAIAqAAQAGAAAAAFQAAADgDABIgHADQgNAFgfAbIAAACIABABIAEgBQAFAAAFAGIAMATQASAaAGAEQAHAEAAACQAAAFgGAAg");
	this.shape_38.setTransform(56.275,-1.225);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B3927").s().p("AgaAzQgPgJgFgQQgEgMgBgLQAAgQAIgOQAIgQAQgIQALgHANAAQASAAAMALQAQANABASQgBAJgDACQgEAFgKAAIg2AAQgBAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAOAHALQALANAQAAQAMAAALgFIAKgGQAFAAAAAFQAAAIgOAIQgOAJgTAAQgPABgNgIgAgRggQgGAJAAAHQAAAAAAABQAAAAABABQAAAAAAAAQABAAABAAIAcAAQAQAAABgLQgBgHgFgGQgHgGgKAAQgLAAgIAMg");
	this.shape_39.setTransform(37.05,1.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B3927").s().p("AglAxQgHgHAAgQQAAgJAHAAQADAAADADIAHAIQAMAQAMAAQAJAAAGgEQAFgEAAgHQAAgJgMgEIgTgHQgNgEgHgFQgJgIAAgNQAAgUATgLQALgGAPAAQARAAAJAGQAIAFAAANQAAANgGAAQgFAAgDgFQgLgSgNAAQgHAAgFAEQgFAEAAAGQAAAJAQAFIAUAHQALAFAGAFQAIAIAAAMQAAASgQALQgNAJgSAAQgYAAgLgKg");
	this.shape_40.setTransform(25.475,1.225);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B3927").s().p("AAQApIgBAAQgMASgXAAQgOAAgJgIQgLgIAAgNQAAgQAPgJQALgGAZgIQAQgIAAgMQAAgLgLgDIgFgBQgIAAgHAGQgEADgEAGIgFAHQgDADgEAAQgHAAAAgMQAAgLAEgFQAEgGANgCQAKgDALAAQATAAANAKQAMAKAAARIAAAtQAAARAGAAIADAAQAFAAAAAEQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABQgGAJgMAAQgRAAgCgSgAAMgCIgMAGQgLAEgEAEQgKAGAAAKQAAAGAFAEQAEAEAGAAQANAAAGgNQAEgIAAgTIAAgDIgBgBg");
	this.shape_41.setTransform(14.225,1.225);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B3927").s().p("AgVBLQgGgEgBAAQgEABgCAEQgDAGgEAAQgEAAAAgJIAAhxQAAgLgCgFQgCgEgGgCQgGgCAAgDQAAgDAHgCQAOgEALgEIAEgBQAGAAAAAHIAAA4QAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIABgBQAPgSAUAAQAUAAANAQQALAQAAAUQAAATgIAPQgQAfggAAQgQAAgLgHgAgLgFQgJAJABAVQgBAUAJAMQAHAMAMAAQAMgBAHgLQAIgMAAgTQgBgSgHgLQgIgMgMAAQgMAAgGAKg");
	this.shape_42.setTransform(1.85,-1.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B3927").s().p("AguBEQgJgHABgJQAAgFABgEQAHgKAKAAQAFAAABAEIgCAEIgBAHQAAAHAIAFQAKAGAPAAQAOgBAJgEQAJgFAAgGQAAgJgQAAIgigCQgLgCgGgGQgGgGAAgGQAAgNAPgGIABAAIgBgBQgWgLAAgYQAAgRANgMQANgMAUAAQANAAAMAHIAJADQACAAADgFQADgGAFABQALAAgBAKQABALgOAAIgEAAQAFAIAAALQAAASgNALQgMALgSABIgJAAQgKABABAFQAAAGANABIAPAAIASABQAMACAHAGQAGAHABAJIgBAJQgJAcgvgBQgeAAgNgKgAgRg5QgDAHAAAJQgBAPAHAJQAFAIAJAAQAGAAAFgHQAEgHABgKQAAgMgGgKQgFgJgIAAQgJAAgFAHg");
	this.shape_43.setTransform(-16.6,3.15);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B3927").s().p("AAQA5QgHAAAAgEQAAgDAEgDQAGgDACgFQADgFAAgRIAAgeQAAgLgGgGQgFgGgKAAQgIAAgHAGQgGAGgCAKQgCALAAAUQAAARADAFQACAFAFADQAFADAAADQAAAEgHAAIgqAAQgHAAAAgEQAAgDAFgDQAFgEACgEQADgFAAgRIAAggQAAgNgCgEQgCgDgGgDQgGgCAAgCQAAgEAHgCQAOgDAHgDIAJgDQAFAAAAAHIAAAMIABABIABgBQANgSAVgBQAUAAAJAPQAHAKAAATIAAAeQAAARADAFQACAFAFADQAFADAAADQAAAEgIAAg");
	this.shape_44.setTransform(-29.025,1.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B3927").s().p("AgTBRQgIAAAAgEQAAgDAFgDQAGgDACgFQACgFAAgRIAAghQAAgMgCgEQgCgDgFgDQgGgCAAgCQAAgEAGgCQAMgDAJgDIAIgDQAGAAAAAHIAABDQAAARACAFQACAEAGAEQAEADAAADQAAAEgHAAgAgKg0QgHgGAAgFQAAgEAHgGQAHgIADABQAEgBAHAIQAHAGAAAEQAAAFgHAGQgHAIgEAAQgDAAgHgIg");
	this.shape_45.setTransform(-39.225,-1.3);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B3927").s().p("AgUBRQgHAAAAgFQAAgDAFgDQAGgDABgEQADgGAAgRIAAhPQAAgMgCgDQgCgEgFgCQgGgDAAgDQAAgEAGgBQAMgCAJgEIAIgDQAGAAAAAHIAABxQAAARACAGQACAEAGADQAEADAAADQAAAFgHAAg");
	this.shape_46.setTransform(-45.925,-1.225);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B3927").s().p("AgjA5QgHAAAAgEQAAgDAFgDQAFgDACgFQADgFAAgRIAAghQAAgMgCgEQgCgDgGgDQgGgCAAgCQAAgEAHgCQAOgDAJgFIAFgBQAFAAAAAHIAAARIABAAIAAAAQADgJAIgHQAJgIAKAAQAHAAAEAFQAFAFAAAIQAAAMgJAAQgDgBgFgDQgFgCgDAAQgFAAgFAEQgKALAAAjQAAARACAFQACAFAFADQAFADAAADQAAAEgHAAg");
	this.shape_47.setTransform(-53.175,1.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B3927").s().p("AgaAzQgPgJgFgQQgFgMAAgLQAAgQAIgOQAIgQAQgIQALgHANAAQASAAANALQAQANAAASQAAAJgEACQgEAFgKAAIg2AAQgBAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAOAHALQALANAQAAQAMAAALgFIALgGQAEAAAAAFQAAAIgNAIQgPAJgTAAQgQABgMgIgAgRggQgGAJAAAHQAAAAAAABQAAAAABABQAAAAAAAAQABAAABAAIAdAAQAQAAAAgLQAAgHgGgGQgHgGgKAAQgLAAgIAMg");
	this.shape_48.setTransform(-64.4,1.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6B3927").s().p("AgTA3QgFgIAAgSIABg1QAAAAAAAAQAAgBAAAAQAAAAgBAAQAAgBgBAAIgNAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgIQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAQgDAEgJQABgDADgLQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAIALAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAWQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAAAQABABAAAAQABAAAAAAQABAAABAAIAYgCQAHAAAAAFIgBAFQAAAHgKAAIgYgBQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAABIAAAYQAAAeADAKQAEAKALAAQAFAAAGgEIAHgDQAEAAAAADQAAAEgDADQgFAHgHAEQgKAGgJAAQgTgBgIgPg");
	this.shape_49.setTransform(-73.5,0.05);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#6B3927").s().p("AghBMQgNgFgFgJQgDgEgBgMIgBgJQAAgJAHAAQAEAAADAEIALAPQAQASAQAAQANgBAIgGQAIgIAAgKQAAgNgLgHQgHgEgPgFQgRgGgIgEQgWgLAAgWQAAgRAMgMQAMgNARgCQAHgCAHAAQAcAAALALQAGAGAAAPQAAANgHABQgEAAgDgEIgGgJIgIgKQgKgJgMAAQgJAAgHAGQgHAGAAAJQAAAOAQAHIAcAKQARAHAIAIQALAMAAAPQAAAKgFAJQgPAfgpgBQgQAAgNgDg");
	this.shape_50.setTransform(-85.275,-0.9);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#6B3927").s().p("Ag2A5QgQgNAAgUQgBgNAIgKQAHgIANgEQgFgKAAgJQAAgSANgKQALgKARAAQARAAAIAJQADAEABALQgBAQgHAAQgFgBgCgEIgDgGIgEgIQgFgHgIAAQgGAAgEAFQgFAFAAAHQAAAKAJAJQAIAJARAKIAcATIABAAQAEgGAAgIQAAgLgLgGQgGgDAAgEQAAgEAIAAIAjAAQAHAAgBAFQABACgGAEQgHAEgDAHQgFATgEAIIgBABIABABIAIAHQAKAOABANQAAABgBABQAAABAAAAQgBABAAAAQgBAAgBAAIgSAAQgEAAAAgEQgBgGgHgGIAAAAIgBAAQgRASgcAAQgXAAgRgMgAgmAAQgGAHABAKQgBAOAMAMQAMALAQgBQAOABALgKIABgBIgBgBIgdgUQgTgNgJgJIgBgBIgBABg");
	this.shape_51.setTransform(-103.95,0.15);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#6B3927").s().p("AgjA5QgHAAAAgEQAAgDAFgDQAFgDACgFQADgFAAgRIAAghQAAgMgCgEQgCgDgGgDQgGgCAAgCQAAgEAHgCQAOgDAJgFIAFgBQAFAAAAAHIAAARIABAAIAAAAQADgJAIgHQAJgIAKAAQAHAAAEAFQAFAFAAAIQAAAMgJAAQgDgBgFgDQgFgCgDAAQgFAAgFAEQgKALAAAjQAAARACAFQACAFAFADQAFADAAADQAAAEgHAAg");
	this.shape_52.setTransform(-119.975,1.1);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#6B3927").s().p("AgaAzQgPgJgGgQQgDgMAAgLQgBgQAIgOQAJgQAPgIQALgHANAAQASAAAMALQAQANABASQgBAJgDACQgEAFgLAAIg1AAQgBAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAOAHALQAKANASAAQALAAAKgFIALgGQAFAAAAAFQAAAIgOAIQgOAJgTAAQgPABgNgIgAgRggQgGAJAAAHQAAAAAAABQAAAAABABQAAAAAAAAQABAAABAAIAcAAQAQAAABgLQgBgHgFgGQgHgGgJAAQgMAAgIAMg");
	this.shape_53.setTransform(-131.15,1.2);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#6B3927").s().p("AArBRQgLAAgFgDQgFgEgOgWQgMgVgEAAQgCAAgEADIgGAHIgBADQAAANACAFQACAFAGADQAEADAAADQAAAFgHAAIgqAAQgHAAAAgFQAAgDAEgDQAFgDADgFQACgFAAgSIAAhNQAAgMgBgEQgDgEgFgCQgGgCAAgDQAAgEAGgCQAQgDAIgEIAHgCQAFAAAAAHIAABdIABABIABAAIATgTQAOgNAAgGQAAgCgEgCQgDgDAAgCQAAgFAHAAIAqAAQAGAAAAAFQAAADgDABIgHADQgNAFgfAbIAAACIABABIAEgBQAFAAAFAGIAMATQASAaAGAEQAHAEAAACQAAAFgGAAg");
	this.shape_54.setTransform(-142.475,-1.225);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#6B3927").s().p("AAQApIgBAAQgMASgXAAQgOAAgJgIQgLgIAAgNQAAgQAPgJQALgGAZgIQAQgIAAgMQAAgLgLgDIgFgBQgIAAgHAGQgEADgEAGIgFAHQgDADgEAAQgHAAAAgMQAAgLAEgFQAEgGANgCQAKgDALAAQATAAANAKQAMAKAAARIAAAtQAAARAGAAIADAAQAFAAAAAEQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABQgGAJgMAAQgRAAgCgSgAAMgCIgMAGQgLAEgEAEQgKAGAAAKQAAAGAFAEQAEAEAGAAQANAAAGgNQAEgIAAgTIAAgDIgBgBg");
	this.shape_55.setTransform(-155.775,1.225);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#6B3927").s().p("Ag3BNQgIAAAAgFQAAgDAFgDQAFgCACgFQACgGAAgRIAAhRQAAgKgBgDQgBgFgDgCIgGgDQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgEAHAAIAyAAIAbABQAOACAJAHQAMAIAAARQAAAKgEAHQgKAOgUADQAAAAgBABQAAAAAAAAQAAAAAAAAQgBAAAAAAIABABQATADALAIQAMALAAAQQAAAMgHAKQgRAWgwAAgAgRACQgBAAgBABQAAAAAAAAQgBAAAAABQAAAAAAABIAAAiQAAASACADQACACAMAAQAlAAAAgfQAAgdglAAgAgTg7IAAAsQAAABAAABQAAAAAAABQABAAAAAAQABABAAAAIAKAAQAiAAAAgbIAAgBQgBgXggAAIgLAAQAAAAgBAAQAAAAgBABQAAAAAAABQAAABAAAAg");
	this.shape_56.setTransform(-168.8,-0.85);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#6B3927").s().p("AgaAzQgOgJgHgQQgDgLAAgLQAAgQAHgPQAJgPAOgJQAMgGANAAQASAAAMAKQARANgBATQABAIgEADQgEADgLAAIg2AAQAAAAgBABQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAOAIAKQAJAOASAAQALAAAKgGIALgFQAFAAAAAFQAAAIgOAIQgOAKgTAAQgPgBgNgHgAgRggQgGAJAAAHQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAIAdAAQARAAgBgKQABgIgGgGQgGgHgKAAQgMAAgIANg");
	this.shape_57.setTransform(152.1,-25.75);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#6B3927").s().p("AAQBRQgHAAAAgFQAAgDAEgDQAFgDADgEQACgGAAgRIAAgfQAAgWgUAAQgJAAgGAHQgGAFgCAKQgCAKAAAVQAAARACAGQADAEAFADQAEADAAADQAAAFgHAAIgpAAQgHAAAAgFQAAgDAFgDQAFgDACgEQADgGAAgRIAAhPQAAgMgCgEQgCgDgGgCQgGgDAAgDQAAgDAHgCQANgDAMgFIAEgBQAGAAAAAHIAAA6IABABIAAAAQANgTAWAAQATAAAKAOQAHAKAAASIAAAfQAAARACAGQADAFAFACQAFADAAADQAAAFgIAAg");
	this.shape_58.setTransform(139.525,-28.175);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#6B3927").s().p("AgTA4QgFgJAAgSIACg0QAAgBgBAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgOAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgIQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAQAQgDAEgJQABgCADgNQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAABIAAAVQAAABAAABQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAQABABAAAAQABAAAAAAQABAAABAAIAYgBQAHAAAAADIAAAGQgCAHgIAAIgZAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAABIgBAZQAAAdADAJQAEALALAAQAGAAAFgDIAHgEQAEAAAAAEQAAADgDADQgFAIgHAEQgKAEgKAAQgRAAgJgOg");
	this.shape_59.setTransform(129.25,-26.9);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#6B3927").s().p("AAQA6QgHgBAAgFQAAgCAEgDQAGgDACgEQADgGAAgSIAAgdQAAgLgGgGQgFgGgKAAQgIAAgHAHQgGAFgCALQgCAJAAAUQAAASADAGQACAEAFADQAFADAAACQAAAFgHABIgqAAQgHgBAAgFQAAgCAFgDQAFgDACgEQADgGAAgSIAAggQAAgMgCgDQgCgFgGgCQgGgCAAgDQAAgEAHgBQAOgDAHgDIAJgCQAFAAAAAGIAAAMIABABIABgBQANgSAVAAQAUAAAJAOQAHAKAAATIAAAdQAAASADAGQACAFAFACQAFACAAADQAAAFgIABg");
	this.shape_60.setTransform(113.925,-25.85);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#6B3927").s().p("AgoArQgQgQAAgaQAAgYAQgRQARgSAXAAQAaAAAQARQAPAQAAAZQAAAYgQARQgRASgYAAQgZAAgPgQgAgUgjQgIAKAAASQAAAVAIAPQAIAQAOAAQANAAAHgLQAHgLAAgRQAAgTgHgPQgJgRgOAAQgMAAgHAKg");
	this.shape_61.setTransform(101.15,-25.725);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#6B3927").s().p("AAbBoQgPgSAAgbQAAgbASgTQARgRAYAAQAaAAAQARQARASAAAcQAAAdgSASQgRARgYAAQgbAAgRgTgAA1A7QAAASAFAMQAFANAIAAQASAAAAgrQAAgrgSAAQgSAAAAArgAhWB3ICRjsIAbAAIiQDsgAhygNQgPgSAAgbQAAgbARgSQASgTAYAAQAaAAAQASQAQASAAAcQAAAdgRASQgRAQgYAAQgcAAgQgSgAhYg6QAAASAFANQAFAMAIAAQASAAAAgrQAAgrgSAAQgSAAAAArg");
	this.shape_62.setTransform(74.375,-32.025);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#6B3927").s().p("AguB7QgSgGgIgLQgIgLAAgfQAAgQAPAAQAIAAAGAKIAKATQASAbAaAAQARAAALgLQANgLAAgQQAAgWgWgPQgdgVg1AAIgIAAQgEAAAAgDIAAgFIAWhrQABgEAGAAIAwAAQAaAAAIgDQAHgBAGgGQAGgHAFAAQAIAAAAAJIgCASIgEAUQgBAJgEADQgFAEgUAAIhBAAQgBAAgBAAQAAABgBAAQAAAAAAABQgBABAAAAIgEAUIAAACQAAADAEAAQA5ABAfAaQAbAWAAAjQAAAkgbAXQgaAXglAAQgVAAgQgGg");
	this.shape_63.setTransform(50.425,-32.625);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#6B3927").s().p("AAFB5QgHAAAAgIIAAilQAAgSgCgFQgCgFgMAAIgYACQgJgBAAgQQAAgHAIgCIAdgEQARgDAMgDQAWgGAEAAQALAAAAAMIAADdQAAAIgJAAg");
	this.shape_64.setTransform(28.025,-32.2);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#6B3927").s().p("Ag4BDQgZgYAAgnQAAglAZgbQAagdAlgBQAeABAVASQAYATAAAeQAAAOgHAFQgGADgQAAIhPAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABAAABIAAADQABAOAIALQAQAaAfAAQAQAAANgHQANgHACAAQAHAAAAAHQAAALgUAOQgYAQgeAAQglAAgXgYgAgRg3QgJAJgDAQIAAADQAAABAAAAQAAABAAAAQABABAAAAQABAAABAAIAlAAQAVAAAAgPQAAgKgHgHQgHgJgNAAQgMAAgKAKg");
	this.shape_65.setTransform(3.875,-28.8);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#6B3927").s().p("AgTBYQgEAAgCgEIgyh6QgIgTgFgGIgLgHQgGgDAAgFQAAgJAMAAIBIAAQANAAAAAJQAAAFgIAEQgJAEAAAIQAAAEADAHIAfBOQAAABAAAAQAAABABAAQAAAAAAABQAAAAAAAAQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBIAXgzQAHgTABgMQgBgMgIgGQgJgGAAgDQAAgKANAAIA2AAQAOAAAAAJQAAAFgFADQgNAJgGALQgHAJgMAaIgtBjQgDAEgFAAg");
	this.shape_66.setTransform(-13.65,-28.675);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#6B3927").s().p("AAUBCIgBgCIgBACQgTAZgjAAQgVAAgPgMQgRgMAAgUQAAgbAZgPQAQgIAngNQAYgMAAgQQgBgUgUAAQgLAAgKAGQgIAGgKAPQgIALgIAAQgIAAgDgFQgDgEAAgMQAAgSAGgHQAHgJAXgFQAQgEASAAQAcAAAVAOQAYAOAAAdIgCA/QABASACAFQACAHAKAAQAJABgBAHQABAGgJAIQgLAIgRABQgbAAgGgZgAALAAQgVAJgNAJQgNAKAAAMQAAAJAHAGQAGAEAIAAQARAAAIgQQAFgJAAgeIAAgDIgBgCg");
	this.shape_67.setTransform(-33.25,-28.8);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#6B3927").s().p("Ag1B0QgXgIgIgMQgHgKAAgTIAAgNQAAgPAMAAQAHAAAHAIIARAWQAZAaAYAAQASAAAKgJQAMgKAAgOQAAgRgUgLQgIgFghgNQgdgLgOgKQgTgRAAgaQAAgfAagVQAagWAnAAQAsAAAUATQAIAIAAAZQAAAWgNAAQgGAAgGgGIgNgQQgVgZgWAAQgMAAgJAHQgKAIAAANQAAAQAUALQAFADAkAOQAdAKAOANQATAQAAAdQAAAigcAWQgcAWgqAAQgaAAgVgHg");
	this.shape_68.setTransform(-54.875,-32.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-269.9,-47.5,634.9,85.5);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.PBB_logo1();
	this.instance.setTransform(-43.5,-34.55,0.3564,0.3565);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.5,-34.5,87,69.1);


(lib.IM2_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM2();
	this.instance.setTransform(-150,-143.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-143.5,1024,90);


(lib.IM1_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM1();
	this.instance.setTransform(-150,-144);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-144,1024,90);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAaBNQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgXhfIAAgBIAAABIgVBfQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgYAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgniUIAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAbAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAVBYIABABIAAgBIAVhYQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAaAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAWBYIABABIAAgBIAVhYQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgkCUQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(127.3611,22.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgeBIQgMgHgIgNQgHgMAAgRIAAguQAAgQAHgNQAIgMAMgHQANgHARAAQARAAANAHQANAHAHAMQAIANAAAQIAAAuQAAARgIANQgHAMgNAHQgNAHgRAAQgRAAgNgHgAgTgsQgHAIAAANIAAAvQAAANAHAIQAIAIALAAQAMAAAIgIQAHgIAAgNIAAgvQAAgNgHgIQgIgHgMAAQgLAAgIAHg");
	this.shape_1.setTransform(108.9,22.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAgBNQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIg4hdIgBAAIAAABIAABcIgBABIgBABIgaAAIgCgBIgBgBIAAiVIABgBIACgBIAZAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIA4BdIAAAAIABgBIAAhcIAAgBIACgBIAaAAIACABIABABIAACVIgBABIgCABg");
	this.shape_2.setTransform(92.775,22.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag1BNIgCgBIgBgBIAAiUIABgCIACgBIA9AAQAPAAAKAGQAMAGAFALQAHALAAAOQAAAOgHAKQgGAKgMAGQgKAFgQAAIgdAAIgBABIAAA5IgBABIgCABgAgYgwIAAAoQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAABAAIAaAAQAKAAAHgGQAGgGAAgKQAAgJgGgGQgHgGgKAAIgaAAIgBABg");
	this.shape_3.setTransform(70.85,22.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdBIQgNgHgIgNQgHgMAAgRIAAguQAAgQAHgNQAIgMANgHQANgHAQAAQARAAANAHQANAHAIAMQAHANAAAQIAAAuQAAARgHANQgIAMgNAHQgNAHgRAAQgQAAgNgHgAgTgsQgHAIAAANIAAAvQAAANAHAIQAIAIALAAQAMAAAHgIQAIgIAAgNIAAgvQAAgNgIgIQgHgHgMAAQgLAAgIAHg");
	this.shape_4.setTransform(55.15,22.725);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAcBNIgCgBIgBgBIAAg+QAAAAAAAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIgvAAIgBABIAAA+IgCABIgBABIgaAAIgCgBIgBgBIAAiVIABgBIACgBIAaAAIABABIACABIAAA8IABABIAvAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAg8IABgBIACgBIAZAAIADABIABABIAACVIgBABIgDABg");
	this.shape_5.setTransform(39.5,22.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgdBJQgNgFgHgLQgHgKAAgOIAAgFIAAgCIACAAIAZAAIACAAIABACIAAADQAAAJAIAGQAIAGANAAQAMAAAGgFQAFgFAAgHQAAgFgDgEQgEgDgGgDIgSgIQgPgFgKgFQgKgEgHgJQgHgKAAgNQAAgNAHgKQAGgKANgFQAMgGAQAAQAPAAANAGQANAGAIALQAHALAAAOIAAADIgBACIgBABIgaAAIgCgBIAAgCIAAgCQAAgJgIgGQgIgHgMAAQgKAAgGAFQgGAEAAAIQAAAFAEAEQADAEAHADIAUAIQAPAFAJAFQAJADAHAJQAHAJAAANQAAAVgPAMQgPAMgaAAQgRAAgNgGg");
	this.shape_6.setTransform(23.975,22.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer_1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#DD002A").s().p("Aq5CyQggAAAAgdIAAkpQAAgdAgAAIVzAAQAgAAAAAdIAAEpQAAAdggAAg");
	this.shape_7.setTransform(78.05,21.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(5.1,3.8,146,35.6);


(lib.circle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003595").s().p("AthNiQlnlnAAn7QAAn7FnlnQFmlmH7AAQH7AAFnFmQFnFnAAH7QAAH7lnFnQlnFnn7AAQn7AAlmlng");
	this.shape.setTransform(0,0.017,1,0.7388);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-122.5,-90.5,245,181);


// stage content:
(lib.WFSB_215325_MM_1024x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [323];
	// timeline functions:
	this.frame_323 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(323).call(this.frame_323).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EhP/gHBMCf/AAAIAAODMif/AAAg");
	this.shape.setTransform(512,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(324));

	// CTA
	this.instance = new lib.CTA();
	this.instance.setTransform(742.6,-47.6,1,1,0,0,0,89.5,21.2);
	this.instance.alpha = 0;
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.CTA(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(148).to({_off:false},0).to({y:43.4,alpha:1},13,cjs.Ease.get(1)).wait(163));

	// T2
	this.instance_1 = new lib.T2("synched",0);
	this.instance_1.setTransform(462.25,50.65);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(133).to({_off:false},0).to({alpha:1},14,cjs.Ease.get(1)).wait(177));

	// T1
	this.instance_2 = new lib.T1("synched",0);
	this.instance_2.setTransform(460.25,141);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(21).to({_off:false},0).to({y:51,alpha:1},19,cjs.Ease.get(1)).wait(79).to({startPosition:0},0).to({alpha:0},14,cjs.Ease.get(1)).wait(191));

	// Logo
	this.instance_3 = new lib.Symbol1("synched",0);
	this.instance_3.setTransform(46.5,48.55);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:146.5,alpha:1},22,cjs.Ease.get(1)).wait(302));

	// Layer_11 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_21 = new cjs.Graphics().p("EAzsAKAQlnkJABl3QgBl2FnkJQFnkJH8AAQH7AAFnEJQFnEJAAF2QAAF3lnEJQlnEJn7AAQn8AAlnkJg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(21).to({graphics:mask_graphics_21,x:539.95,y:34.567}).wait(303));

	// IM2_jpg
	this.instance_4 = new lib.IM2_jpg("synched",0);
	this.instance_4.setTransform(150,143.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(119).to({_off:false},0).to({alpha:1},28).wait(177));

	// IM1_jpg
	this.instance_5 = new lib.IM1_jpg("synched",0);
	this.instance_5.setTransform(150,144);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(21).to({_off:false},0).to({alpha:1},19).wait(284));

	// Layer_1
	this.instance_6 = new lib.circle("synched",0);
	this.instance_6.setTransform(950.4,31.55);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(21).to({_off:false},0).to({alpha:1},19).wait(284));

	// BG_png
	this.instance_7 = new lib.BG();

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(324));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(511,-20,561.9000000000001,199);
// library properties:
lib.properties = {
	id: '1B2175A397DA418A911C8D25A6AE7677',
	width: 1024,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.png", id:"BG"},
		{src:"IM1.jpg", id:"IM1"},
		{src:"IM2.jpg", id:"IM2"},
		{src:"PBB_logo1.png", id:"PBB_logo1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['1B2175A397DA418A911C8D25A6AE7677'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;