(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.frog = function() {
	this.initialize(img.frog);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,400,225);


(lib.lizart = function() {
	this.initialize(img.lizart);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,256,35);


(lib.snake = function() {
	this.initialize(img.snake);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,319,208);


(lib.Tounge = function() {
	this.initialize(img.Tounge);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,167,210);


(lib.turtle = function() {
	this.initialize(img.turtle);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,253);


(lib.tr = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.turtle();
	this.instance.setTransform(-150,-126.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-126.5,300,253);


(lib.tg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Tounge();
	this.instance.setTransform(-23.35,-29.4,0.28,0.28);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.3,-29.4,46.7,58.8);


(lib.t3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDAGQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgIQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAHAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAIQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape.setTransform(81.775,-1.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPAeQgHgEgDgGIAAgBIAAgBIAFgCIABAAIAAAAIAFAGQADADAEAAQADACAFAAQAFAAADgCQAEgBADgCQADgDgBgDQAAgEgCgDQgDgCgHgCIgMgDQgJgCgDgEQgEgEAAgFQAAgGAEgEQADgEAFgDQAFgCAGAAQAIAAAGADQAGADAEAFIAAABIAAAAIgFADIgBAAIAAAAQgDgEgFgCQgEgCgGgBQgGABgEADQgFACAAAGQAAACACACQACADAHACIAOAFQAIABAEAEQADAEAAAGQAAAGgDADQgEAEgFADQgGACgIAAQgIAAgHgDg");
	this.shape_1.setTransform(77.45,-4.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AATAgIgBAAIgBgBIAAgrQAAgGgDgDQgDgDgHgBIgGABIgHAEIgHAFIAAAuQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAg8IABgBIAFAAIABABIAAAHIABABIAAgBIAIgFIAHgDQADgBAEgBQAJAAAFAGQAFAFAAAHIAAAtQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_2.setTransform(71.125,-4.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgTAdQgGgGAAgHQAAgGAEgFQAEgEAGgCQAHgDAJAAIALgBIABgBIABgBIAAgEQAAgGgEgEQgFgEgHgBQgEAAgGADQgEACgEAGIgBAAIAAAAIgFgCIAAgBIAAgBQADgFAHgEQAGgEAJAAQAHAAAFACQAFADADAFQADAFgBAGIAAAqIAAABIgBAAIgEAAIgCAAIAAgBIAAgHQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABgBAAQgEAEgFADQgGACgFAAQgKAAgFgEgAAHAAQgGAAgDACIgJADIgEAEQgCACAAAEQAAAFAFAEQAEADAGAAIAHgCIAHgDIAEgGIACgEIAAgLQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_3.setTransform(64.15,-4.15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgCAsIAAAAIgBgBIAAg7QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAFAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAA6IAAACIgCAAgAgCgfIgBAAIAAgBIAAgJQAAgBAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAFAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAAKQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_4.setTransform(59.75,-5.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJAsIgGgFIgDgDIgBgBIAAABIgBAGQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgDAAIgBAAIAAgCIAAhVQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAFAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAAfIAAABIABgBIADgDIAHgDQAEgCAFAAQAJAAAGAEQAFAFADAIQADAGgBAJQABAPgIAJQgHAJgNAAQgEAAgFgBgAgKgLQgGADgCAEIAAAbQgBAEADAEIAHAGQAEACAFAAQAFAAAEgDQAFgCADgHQACgFAAgKQAAgMgEgHQgGgGgJgBQgFAAgFADg");
	this.shape_5.setTransform(54.95,-5.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgCAsIAAAAIgBgBIAAg7QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAFAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAA6IAAACIgCAAgAgCgfIgBAAIAAgBIAAgJQAAgBAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAFAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAAKQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_6.setTransform(49.85,-5.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AATAsIgBAAIgBgBIAAgrQAAgGgDgDQgDgDgHgBIgGABIgHAEIgHAFIAAAuQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAhVQAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAABAAIAFAAIABABIAAAgIABABIAAgBIAIgFIAHgDQADgBAEgBQAJAAAFAGQAFAFAAAHIAAAtQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_7.setTransform(45.025,-5.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgaArQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAhPIABgCIABAAIAFAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAFIAAABIABgBIAEgDIAGgEQAEgCAFAAQAIABAGADQAFAEAEAHQADAHAAALQAAAJgDAIQgEAIgFADQgHAEgIABQgFAAgFgCIgHgEIgCgBIAAABIAAAXQAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAgAgKghQgEADgDADQgCAEAAADIAAAdIAIAHQAEACAGAAQAFAAAFgDQAEgEADgGQADgFABgJQgBgJgDgGQgDgGgEgDQgFgCgFAAQgFAAgEACg");
	this.shape_8.setTransform(38.15,-3.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAmAgIgBAAIgBgBIAAgrQAAgGgCgDQgDgDgHgBIgHABIgGAEIgFAEIgBABIgBACIAAAsQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAAAAAIgEAAIgBAAIgBgBIAAgrQAAgGgDgDQgCgDgIgBQgFABgEACIgLAHIAAAuQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAIgFAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAg8IABgBIAGAAIABABIAAAHIAAABIABgBIAHgFIAHgDQAEgBAEgBQAHABAEADQADADACAEIABAAIABAAIAHgFIAHgEQADgBAEgBQAJAAAFAGQAFAFgBAHIAAAtQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(29.05,-4.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgTAdQgGgGABgHQAAgGADgFQAEgEAGgCQAHgDAJAAIALgBIABgBIABgBIAAgEQAAgGgEgEQgFgEgHgBQgEAAgGADQgEACgDAGIgCAAIAAAAIgFgCIAAgBIAAgBQAEgFAGgEQAGgEAJAAQAHAAAFACQAFADADAFQADAFgBAGIAAAqIAAABIgBAAIgEAAIgCAAIAAgBIAAgHQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABgBAAQgEAEgGADQgFACgFAAQgKAAgFgEgAAHAAQgGAAgDACIgJADIgEAEQgCACAAAEQABAFAEAEQADADAHAAIAHgCIAHgDIAEgGIACgEIAAgLQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_10.setTransform(20.15,-4.15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgiAnQgHgGAAgLQAAgHAEgFQAEgGAKgFIABgCIgBgCIgGgIQgCgEAAgFQAAgHADgFQADgFAGgDQAGgCAHAAQAGgBADADQAFACADAEQADAEAAAGQAAAEgCAEQgCAEgFAFQgFAEgHADIgBABIABABIATAWIABACIABgCIAFgFIAFgHIAEgGIADgEQAAgBAAAAQAAAAAAAAQABAAAAAAQAAAAABAAIADABIABAAIAAABIgEAIIgHAKIgHAJIgBABIABABIAGAEIAIACIAHACQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAEIgBACIgBAAIgKgBIgKgEIgHgFIgCAAIgBAAQgFAFgGADQgGACgIAAQgMABgHgHgAgSACQgHADgDAGQgEAFAAAGQAAAFACAEQADADAEADQAEACAFAAQAGAAAFgDQAEgCAEgDIABgCIAAgBIgVgZIgBgBgAgPgkQgEACgBAEQgCADAAAEIABAGIAEAHIADADIABAAIABAAQAKgFAEgFQAEgEAAgFQAAgHgEgCQgDgDgFAAQgFAAgEACg");
	this.shape_11.setTransform(10.075,-5.45);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgOAeQgIgEgCgGIgBgBIABgBIADgCIABAAIABAAIAFAGQADADAEAAQADACAFAAQAFAAAEgCQAEgBACgCQADgDAAgDQAAgEgEgDQgCgCgIgCIgLgDQgJgCgEgEQgDgEAAgFQAAgGADgEQADgEAGgDQAFgCAGAAQAIAAAGADQAGADADAFIABABIgBAAIgDADIgBAAIgBAAQgDgEgEgCQgFgCgGgBQgGABgFADQgEACAAAGQAAACACACQACADAGACIAPAFQAIABADAEQAEAEAAAGQAAAGgEADQgCAEgHADQgFACgHAAQgJAAgGgDg");
	this.shape_12.setTransform(-0.35,-4.15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOAdQgGgEgEgIQgEgGAAgKQAAgKAEgHQAEgHAGgFQAIgEAHAAQAIAAAHAEQAGAEADAHQAEAIAAAJIAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAIgvAAIgBABIAAABQAAAGAEAFQACAGAGACQAEAEAGAAQAGAAAFgDQAFgDADgFIABgBIAAABIAFACQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABQgDAEgEADQgEADgEACQgFABgGAAQgIAAgHgEgAgKgWQgEADgDAGQgDAFAAAGIAnAAIACgBIAAgBQAAgGgCgFQgDgFgEgCQgFgDgGgBQgGABgFADg");
	this.shape_13.setTransform(-6.65,-4.15);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgCAsQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAhVQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAFAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAABUIgBACIgBAAg");
	this.shape_14.setTransform(-11.5,-5.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgBAsIgBAAIgBgBIAAg7QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIADAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAA6IAAACIgCAAgAgCgfIgBAAIAAgBIAAgJQAAgBAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAFAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAAKQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_15.setTransform(-14.25,-5.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAKAqIgDAAQgHAAgCgDQgEgEAAgHIAAgpIgBgBIgKAAIgBgBIAAgEIABgBIAKAAIABgBIABgUQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAAAIADAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAATIABABIAQAAIABABIAAAEIgBABIgQAAIgBABIAAAoQABAFABADQACACAEAAIAIAAIABAAIABABIAAACIgCACIgCAAg");
	this.shape_16.setTransform(-17.95,-5.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaArQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAhPIABgCIABAAIAEAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAFIAAABIABgBIAEgDIAGgEQAEgCAFAAQAIABAFADQAGAEAEAHQADAHAAALQAAAJgDAIQgEAIgGADQgGAEgIABQgFAAgFgCIgHgEIgCgBIAAABIAAAXQAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAgAgKghQgEADgDADQgCAEAAADIAAAdIAIAHQAEACAGAAQAFAAAFgDQAEgEADgGQADgFABgJQgBgJgDgGQgDgGgEgDQgFgCgFAAQgFAAgEACg");
	this.shape_17.setTransform(-23.5,-3.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgOAdQgGgEgEgIQgEgGAAgKQAAgKAEgHQAEgHAGgFQAIgEAHAAQAIAAAHAEQAGAEAEAHQADAIAAAJIAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIguAAIAAABIAAABQAAAGACAFQAEAGAFACQAEAEAFAAQAHAAAFgDQAFgDADgFIABgBIAAABIAFACQAAAAAAAAQABAAAAABQAAAAgBAAQAAAAAAABQgDAEgEADQgEADgFACQgEABgGAAQgIAAgHgEgAgKgWQgEADgDAGQgCAFAAAGIAmAAIACgBIAAgBQAAgGgDgFQgCgFgEgCQgFgDgGgBQgGABgFADg");
	this.shape_18.setTransform(-30.65,-4.15);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgNAgIgBAAIgBgBIAAg8IABgBIAGAAIABABIAAAIIAAAAIABAAIAGgGIAFgDQADgBAEgBQABAAABABQAAAAABAAQAAAAAAAAQABABAAAAIAAAFIgBABIgCAAIgDAAIgGABQgDABgBADIgFAEIgCAGIAAAoQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_19.setTransform(-36.025,-4.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAKAqIgDAAQgHAAgCgDQgDgEgBgHIAAgpIgBgBIgKAAIgBgBIAAgEIABgBIAKAAIABgBIACgUQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAIADAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAATIABABIAQAAIABABIAAAEIgBABIgQAAIgBABIAAAoQAAAFACADQACACAEAAIAIAAIABAAIABABIAAACIgCACIgCAAg");
	this.shape_20.setTransform(-43.5,-5.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgPAeQgEgCgDgEQgCgEAAgGIAAgsQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAGAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAqQAAAGADAEQAEAEAGAAQAFAAAFgDQAFgDAFgFIAAgtQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAFAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAA8QAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgFAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAgHIAAgBIgBAAQgHAGgGACQgEACgFAAQgFAAgFgCg");
	this.shape_21.setTransform(-49.2,-4.075);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgPAdQgGgEgEgIQgEgHAAgKQAAgIAEgIQAEgHAHgFQAGgEAIAAQAJAAAHAEQAHAFADAHQAEAIAAAIQAAAKgEAHQgEAIgGAEQgHAEgJAAQgIAAgHgEgAgKgWQgFADgDAGQgDAGAAAHQAAAJADAFQADAGAFADQAFAEAFAAQAHAAAFgEQAFgDACgGQADgFAAgJQAAgHgDgGQgCgGgFgDQgFgDgHgBQgFABgFADg");
	this.shape_22.setTransform(-56.175,-4.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgIAsIgHgFIgDgDIgBgBIAAABIgBAGQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgDAAIgBAAIAAgCIAAhVQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAFAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAAfIAAABIABgBIADgDIAHgDQAEgCAFAAQAJAAAGAEQAFAFADAIQACAGABAJQAAAPgIAJQgHAJgMAAQgGAAgDgBgAgKgLQgGADgCAEIAAAbQAAAEACAEIAHAGQAEACAFAAQAFAAAFgDQAEgCADgHQADgFgBgKQABgMgGgHQgEgGgKgBQgGAAgEADg");
	this.shape_23.setTransform(-63.15,-5.35);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgTAdQgFgGgBgHQABgGADgFQADgEAIgCQAGgDAJAAIALgBIACgBIAAgBIAAgEQAAgGgFgEQgEgEgHgBQgFAAgEADQgFACgEAGIAAAAIgBAAIgFgCIgBgBIABgBQADgFAHgEQAGgEAIAAQAIAAAFACQAFADADAFQADAFAAAGIAAAqIAAABIgCAAIgEAAIgBAAIAAgBIgBgHQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABAAAAQgFAEgFADQgGACgGAAQgIAAgGgEgAAIAAQgHAAgEACIgHADIgFAEQgCACABAEQAAAFADAEQAFADAGAAIAHgCIAHgDIAFgGIABgEIAAgLQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAAAAAAAg");
	this.shape_24.setTransform(-70.35,-4.15);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AATAgIgBAAIgBgBIAAgrQAAgGgDgDQgDgDgHgBIgGABIgHAEIgHAFIAAAuQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAIgFAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAg8IABgBIAFAAIABABIAAAHIABABIAAgBIAIgFIAHgDQADgBAEgBQAJAAAFAGQAFAFAAAHIAAAtQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_25.setTransform(-79.425,-4.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgNAgIgBAAIgBgBIAAg8IABgBIAGAAIABABIAAAIIAAAAIABAAIAGgGIAFgDQADgBAEgBQABAAABABQAAAAABAAQAAAAABAAQAAABAAAAIAAAFIgBABIgCAAIgDAAIgGABQgDABgBADIgFAEIgCAGIAAAoQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_26.setTransform(-84.825,-4.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgTAdQgFgGgBgHQABgGADgFQADgEAIgCQAGgDAJAAIALgBIACgBIAAgBIAAgEQAAgGgEgEQgFgEgHgBQgFAAgFADQgEACgEAGIgBAAIAAAAIgFgCIgBgBIABgBQAEgFAGgEQAGgEAIAAQAIAAAFACQAFADADAFQACAFABAGIAAAqIAAABIgCAAIgEAAIgCAAIAAgBIAAgHQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABAAAAQgFAEgFADQgGACgGAAQgIAAgGgEgAAIAAQgHAAgDACIgIADIgFAEQgBACgBAEQAAAFAFAEQAEADAGAAIAHgCIAHgDIAFgGIABgEIAAgLQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAAAAAAAg");
	this.shape_27.setTransform(-90.85,-4.15);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgNAdQgIgEgDgIQgEgGAAgKQAAgKAEgHQAEgHAHgFQAGgEAIAAQAJAAAGAEQAGAEADAHQAEAIAAAJIAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIguAAIgBABIAAABQAAAGADAFQAEAGAEACQAFAEAGAAQAGAAAFgDQAFgDADgFIABgBIABABIAEACQAAAAAAAAQABAAAAABQAAAAgBAAQAAAAAAABQgDAEgEADQgDADgFACQgFABgGAAQgIAAgGgEgAgKgWQgFADgCAGQgCAFgBAGIAnAAIACgBIAAgBQAAgGgDgFQgCgFgEgCQgFgDgGgBQgGABgFADg");
	this.shape_28.setTransform(-97.3,-4.15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgCAsQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAhVQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAIAFAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAABUIAAACIgCAAg");
	this.shape_29.setTransform(-102.15,-5.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgPAdQgGgEgEgIQgEgHAAgKQAAgIAEgIQAEgHAHgFQAGgEAIAAQAJAAAHAEQAHAFADAHQAEAIAAAIQAAAKgEAHQgEAIgGAEQgHAEgJAAQgIAAgHgEgAgKgWQgFADgDAGQgDAGAAAHQAAAJADAFQADAGAFADQAFAEAFAAQAHAAAFgEQAFgDACgGQADgFAAgJQAAgHgDgGQgCgGgFgDQgFgDgHgBQgFABgFADg");
	this.shape_30.setTransform(-109.725,-4.15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAKAqIgDAAQgHAAgCgDQgEgEAAgHIAAgpIgBgBIgKAAIgBgBIAAgEIABgBIAKAAIABgBIABgUQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAAAIADAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAATIABABIAQAAIABABIAAAEIgBABIgQAAIgBABIAAAoQABAFABADQACACAEAAIAIAAIABAAIABABIAAACIgCACIgCAAg");
	this.shape_31.setTransform(-115.6,-5.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgPAdQgGgDgEgGIAAgBIAAAAIAFgDIABAAIAAABIAFAFQADADAEABQADABAFAAQAEAAAEgBQAFgCACgDQADgCgBgDQAAgEgCgCQgEgDgGgCIgMgEQgJgBgDgEQgEgEAAgFQAAgGAEgEQACgEAGgDQAFgCAGAAQAIAAAGADQAGADAEAFIAAABIAAABIgFACIgBAAIAAAAQgDgEgFgDQgEgBgGAAQgGAAgEACQgFADAAAFQAAADACADQACACAHACIAOAFQAIABAEAEQADAFAAAFQAAAFgDAFQgEAEgFACQgGACgIAAQgHAAgIgEg");
	this.shape_32.setTransform(55.05,-17.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgNAhIgBgBIgBgBIAAg8IABgBIAGAAIABABIAAAIIAAABIABAAIAGgHIAFgDQADgBAEAAQABAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIAAAFIgBACIgCAAIgDgBIgGACQgDAAgBADIgFAFIgCAFIAAAoQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAg");
	this.shape_33.setTransform(50.275,-17.75);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgOAdQgGgEgEgHQgEgIAAgJQAAgKAEgHQAEgHAGgEQAIgFAHAAQAJAAAGAEQAGAEAEAHQADAIAAAJIAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAAAAAIgvAAIgBAAIAAACQABAGADAFQACAFAGADQAEAEAGAAQAGAAAFgDQAFgCADgFIABgBIAAAAIAFACQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAQgDAFgEADQgEADgEABQgFACgGAAQgIAAgHgEgAgKgXQgEAEgDAFQgDAGAAAFIAnAAIACAAIAAgCQAAgFgCgFQgDgFgEgDQgFgCgGAAQgGAAgFACg");
	this.shape_34.setTransform(44.3,-17.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgZAqQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAhQIAAAAIABgBIAEAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAGIAAABIACAAIADgEIAGgDQAEgCAFAAQAIgBAFAEQAHAEADAHQAEAHAAAKQAAAKgEAIQgDAHgHAFQgGADgIAAQgFAAgFgBIgHgFIgCAAIAAABIAAAXQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAgAgKghQgEADgCADQgCADgBAEIAAAdIAIAGQAEACAGAAQAFAAAFgDQAEgDADgGQAEgFAAgJQAAgJgEgGQgDgFgEgDQgFgDgFAAQgFAAgEACg");
	this.shape_35.setTransform(37.45,-16.75);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAmAhIgBgBIAAgBIAAgqQgBgGgDgEQgCgEgHAAIgHACIgGADIgFAEIgBACIgBACIAAArQAAAAAAABQAAAAAAAAQgBAAAAAAQAAABAAAAIgFAAIgBgBIAAgBIAAgqQAAgGgDgEQgDgEgGAAQgGAAgEADIgLAIIAAAtQAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAIgFAAQAAAAgBgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAg8IABgBIAFAAIABABIAAAHIAAABIABAAIAHgGIAHgDQAEgBAEAAQAHgBAEAEQAEAEABADIABABIABgBIAHgGIAHgDQADgBAEAAQAJAAAFAEQAFAGgBAIIAAAsQAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_36.setTransform(28.35,-17.75);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgTAcQgGgEABgIQgBgGAEgFQAEgEAGgCQAHgDAJgBIALgBIACAAIAAgBIAAgDQAAgHgFgFQgEgDgHAAQgEgBgFADQgFADgDAEIgBABIgBAAIgFgCIAAAAIAAgBQADgHAHgDQAGgEAJAAQAHAAAFACQAFADADAFQACAFAAAGIAAApIAAABIgBABIgEAAIgBgBIAAgBIgBgGQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAABgBAAQgEAEgGADQgFACgGAAQgJAAgFgFgAAHAAQgGAAgEABIgIADIgEAFQgBADAAADQAAAFADAEQAEADAHAAIAHgBIAHgFIAEgEIACgGIAAgKQAAgBAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_37.setTransform(19.45,-17.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgMAdQgHgEgEgHQgDgIgBgJQAAgJAFgIQADgHAHgEQAGgFAIAAQAGAAAFACIAIAFQADADACAFQABAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgFABQAAABAAAAQgBAAAAAAQAAAAAAgBQAAAAgBAAQgCgEgDgCIgGgEIgFAAQgGAAgFACQgFAEgDAGQgDAGAAAHQAAAJADAFQADAHAFACQAFAEAGAAQAFAAAGgDQADgDAFgFIAAgCIABABIAEACIAAABIgEAGIgGAFIgHADIgIABQgIAAgGgEg");
	this.shape_38.setTransform(13.3,-17.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgNAhIgBgBIgBgBIAAg8IABgBIAGAAIABABIAAAIIAAABIABAAIAGgHIAFgDQADgBAEAAQABAAAAAAQABAAABAAQAAAAAAAAQABABAAAAIAAAFIgBACIgCAAIgDgBIgGACQgDAAgBADIgFAFIgCAFIAAAoQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAg");
	this.shape_39.setTransform(5.475,-17.75);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgPAdQgGgEgEgHQgEgIAAgJQAAgJAEgIQAEgHAHgEQAGgFAIAAQAJAAAHAFQAHAEADAHQAEAHAAAKQAAAJgEAIQgEAHgGAEQgHAEgJAAQgIAAgHgEgAgKgXQgFAEgDAGQgDAGAAAIQAAAHADAGQADAHAFACQAFAEAFAAQAHAAAFgEQAFgCACgHQADgGAAgHQAAgIgDgGQgCgGgFgEQgFgCgHAAQgFAAgFACg");
	this.shape_40.setTransform(-0.675,-17.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgDAtQAAAAgBgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAg2IgBgBIgNAAIgBgBIAAgEIAAgBIABAAIANAAIABgBIAAgJQAAgIADgEQADgDAHAAIAJAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAIAAAFIgBAAIgBABIgIAAQgEAAgCACQgCADAAAEIAAAJIABABIAPAAIABAAIAAABIAAAEQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgPAAIgBABIAAA2QAAAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_41.setTransform(-6.425,-18.95);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgXApQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgDIABgCIADAAIAHAAQADAAACgCIAEgFIACgFIgBgGIgXg4IAAgBIACgBIAFAAIABAAIABABIASAxIABABQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBIATgwIAAgBIABAAIAFAAIABABIAAABIgbBEIgDAGQgBADgDABIgFACIgGABg");
	this.shape_42.setTransform(-14.425,-16.675);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAKArIgDAAQgHgBgCgDQgEgEAAgHIAAgpIgBgBIgKAAIgBgBIAAgEIABgBIAKAAIABgBIABgTQAAgBABAAQAAAAAAAAQAAAAAAAAQABgBAAAAIADAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAATIABABIAQAAIABABIAAAEIgBABIgQAAIgBABIAAAnQABAHABABQACACAEAAIAJAAIABAAIAAABIAAAEIgBABIgDABg");
	this.shape_43.setTransform(-19.85,-18.75);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgCAtIgBgBIAAgBIAAg8QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAFAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAA8IAAABIgCABgAgCgfIgBAAIgBgCIAAgJQABAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAFAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAJQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_44.setTransform(-23.4,-18.95);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AATAhIgBgBIgBgBIAAgqQAAgGgDgEQgDgEgHAAIgGACIgHADIgHAGIAAAtQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABgBAAIgFAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAg8IABgBIAFAAIABABIAAAHIABABIAAAAIAIgGIAHgDQADgBAEAAQAJAAAFAEQAFAGAAAIIAAAsQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAg");
	this.shape_45.setTransform(-28.225,-17.75);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgPAeQgEgCgDgEQgCgEAAgGIAAgsQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAGAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAqQAAAGADAEQAEAEAGAAQAFAAAFgDQAFgDAFgFIAAgtQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAFAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAA8QAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgFAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgGACQgEACgFAAQgFAAgFgCg");
	this.shape_46.setTransform(-35.25,-17.625);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AALArIgEAAQgHgBgDgDQgCgEAAgHIAAgpIgBgBIgLAAIgBgBIAAgEIABgBIALAAIABgBIABgTQAAgBAAAAQAAAAAAAAQAAAAAAAAQABgBAAAAIADAAQAAAAABABQAAAAAAAAQAAAAAAAAQABABAAAAIAAATIABABIAPAAIABABIAAAEIgBABIgPAAIgBABIAAAnQAAAHABABQACACAEAAIAIAAIACAAIAAABIAAAEIgCABIgDABg");
	this.shape_47.setTransform(-40.95,-18.75);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgNAhIgBgBIgBgBIAAg8IABgBIAGAAIABABIAAAIIAAABIABAAIAGgHIAFgDQADgBAEAAQABAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIAAAFIgBACIgCAAIgDgBIgGACQgDAAgBADIgFAFIgCAFIAAAoQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAg");
	this.shape_48.setTransform(-45.025,-17.75);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgPAdQgGgEgEgHQgEgIAAgJQAAgJAEgIQAEgHAHgEQAGgFAIAAQAJAAAHAFQAHAEADAHQAEAHAAAKQAAAJgEAIQgEAHgGAEQgHAEgJAAQgIAAgHgEgAgKgXQgFAEgDAGQgDAGAAAIQAAAHADAGQADAHAFACQAFAEAFAAQAHAAAFgEQAFgCACgHQADgGAAgHQAAgIgDgGQgCgGgFgEQgFgCgHAAQgFAAgFACg");
	this.shape_49.setTransform(-51.175,-17.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgZAqQgBAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAAhQIAAAAIABgBIAFAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAGIABABIABAAIADgEIAGgDQAEgCAFAAQAHgBAHAEQAGAEADAHQADAHAAAKQAAAKgDAIQgDAHgGAFQgHADgIAAQgGAAgDgBIgIgFIgBAAIAAABIAAAXQAAAAgBABQAAAAAAAAQAAAAAAAAQgBAAAAAAgAgKghQgEADgDADQgBADAAAEIAAAdIAIAGQAEACAFAAQAFAAAFgDQAFgDADgGQACgFAAgJQAAgJgCgGQgDgFgFgDQgFgDgEAAQgGAAgEACg");
	this.shape_50.setTransform(-58.1,-16.75);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgaAqQAAAAAAAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAhQIABAAIABgBIAFAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAGIABABIAAAAIAEgEIAGgDQAEgCAFAAQAHgBAHAEQAFAEAEAHQADAHAAAKQAAAKgDAIQgEAHgFAFQgHADgIAAQgFAAgEgBIgIgFIgBAAIAAABIAAAXQAAAAgBABQAAAAAAAAQAAAAAAAAQgBAAAAAAgAgKghQgEADgDADQgBADAAAEIAAAdIAIAGQAEACAFAAQAFAAAFgDQAFgDADgGQACgFAAgJQAAgJgCgGQgDgFgFgDQgFgDgEAAQgGAAgEACg");
	this.shape_51.setTransform(-65.2,-16.75);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgPAdQgGgEgEgHQgEgIAAgJQAAgJAEgIQAEgHAHgEQAGgFAIAAQAJAAAHAFQAHAEADAHQAEAHAAAKQAAAJgEAIQgEAHgGAEQgHAEgJAAQgIAAgHgEgAgKgXQgFAEgDAGQgDAGAAAIQAAAHADAGQADAHAFACQAFAEAFAAQAHAAAFgEQAFgCACgHQADgGAAgHQAAgIgDgGQgCgGgFgEQgFgCgHAAQgFAAgFACg");
	this.shape_52.setTransform(-72.525,-17.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgNAdQgIgEgDgHQgEgIAAgJQAAgKAEgHQAEgHAHgEQAGgFAIAAQAJAAAGAEQAGAEADAHQAEAIAAAJIAAABQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIguAAIgBAAIAAACQAAAGADAFQAEAFAEADQAFAEAFAAQAHAAAFgDQAFgCADgFIABgBIABAAIAEACQAAAAAAAAQABAAAAABQAAAAgBAAQAAAAAAAAQgDAFgEADQgDADgFABQgFACgGAAQgIAAgGgEgAgKgXQgFAEgCAFQgCAGgBAFIAnAAIACAAIAAgCQAAgFgDgFQgCgFgEgDQgFgCgGAAQgGAAgFACg");
	this.shape_53.setTransform(-82.1,-17.7);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgOAeQgFgCgCgEQgDgEAAgGIAAgsQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAEAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAqQAAAGADAEQAEAEAGAAQAFAAAFgDQAFgDAFgFIAAgtQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAFAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAA8QAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgFAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBAAAAgBIAAgHIAAgBIgBAAQgHAGgFACQgEACgEAAQgGAAgEgCg");
	this.shape_54.setTransform(-89.1,-17.625);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AAVAqQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAgXIAAgBIgCAAIgIAFQgEABgGAAQgHAAgHgDQgGgFgDgHQgEgIAAgJQAAgJAEgIQADgHAGgEQAGgFAIABQAGAAAEACIAGADIAEADQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIABgGIAAAAIACgBIACAAIACABIAAAAIAABQQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAAAAAgAgIggQgFACgCAHQgDAGAAAIQAAAJACAFQADAGAFADQAFADAFAAQAFAAAFgCQAFgCADgEIAAgcQAAgEgCgEQgDgEgEgCQgEgDgFAAQgFAAgFAEg");
	this.shape_55.setTransform(-96.275,-16.75);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgCAtIAAgBIgBgBIAAg8QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAFAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAA8IAAABIgCABgAgCgfIgBAAIAAgCIAAgJQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIAFAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAAJQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_56.setTransform(-101,-18.95);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AATAhIgBgBIgBgBIAAgqQAAgGgDgEQgDgEgHAAIgGACIgHADIgHAGIAAAtQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABgBAAIgFAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAg8IABgBIAFAAIABABIAAAHIABABIAAAAIAIgGIAHgDQADgBAEAAQAJAAAFAEQAFAGAAAIIAAAsQAAAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAg");
	this.shape_57.setTransform(-105.825,-17.75);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgRApQgHgCgDgIQgDgHAAgLIAAg3QAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAGAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAA5QAAAMAFAFQAGAGALAAQAHAAAFgDQAFgCACgFQADgFAAgIIAAg5QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAEAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAA5QAAAKgDAHQgEAHgHADQgHADgKAAQgKAAgHgEg");
	this.shape_58.setTransform(-113.55,-18.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-119.8,-28.1,205,32.1);


(lib.t2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#167ABE").s().p("AgVBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAIAHgXIAKgbIAOgeIATghIAAgCIgCAAIhEAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIABgKQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIBUAAIADABIAAABIAAAHIgBADIgCADIgOAYQgGAMgGANIgKAZIgHAWIgEASQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape.setTransform(96.875,10.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_1.setTransform(84.225,12.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_2.setTransform(71.525,10.125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#167ABE").s().p("AAKBAQgKAAgGgFQgFgGAAgLIAAg8QAAAAAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgOAAQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAAAIAAgHQAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAPAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIACgdQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAIAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAcQAAAAAAABQAAAAAAAAQAAAAAAAAQABABAAAAIAXAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAIQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgXAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIAAA4QAAAJADADQADACAGABIAMAAIACAAIAAABIAAAHQAAAAAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgFAAIgHABg");
	this.shape_3.setTransform(58.825,10.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#167ABE").s().p("AgXArQgLgFgEgIIgBgCIABgCIAHgDIACgBIABABIAHAIQAEADAGADQAFACAHAAIAMgCQAGgDADgDQADgEAAgEQAAgFgEgEQgEgDgJgDIgSgFQgNgDgGgFQgFgHAAgIQAAgJAEgGQAFgGAIgEQAJgDAJAAQAMAAAKAEQAJAFAFAHIABABIgBABIgHAFIgCAAIgBgBQgEgFgGgDQgHgEgJAAQgIAAgHAEQgGAEAAAHQAAAEADAEQADADAIACIAWAHQANADAFAGQAGAHAAAIQAAAJgFAGQgFAGgJAEQgJADgLABQgNAAgLgHg");
	this.shape_4.setTransform(50.625,12.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#167ABE").s().p("AgYAtQgGgDgEgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAJAAQAGAAAIgFQAHgEAGgHIAAhCQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAIALAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABZQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgLAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgLIAAgBIgBABQgLAIgHADQgHAEgHAAQgIAAgHgEg");
	this.shape_5.setTransform(40.95,12.225);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#167ABE").s().p("AglA6QgMgHABgMQAAgGADgFQAFgGAJgDQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIgHgFQgCgCAAgEIACgFQABgCADgCIAIgEIABAAIgBgCQgIgEgDgGQgEgGAAgIQAAgOALgIQAKgIATAAQAIAAAIACQAGACAEAEIACABIACgBIAFgEIAGgDIAGgBIADAAIABADIAAAGIgBACIgDABIgFABIgFABQgEABABADIACAFIABAHQAAAIgEAHQgEAGgJAEQgJAEgMAAIgPABQgFABgCACQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAADAEABQADABAJABIAXABQAPABAIAHQAHAGAAALQAAAOgLAHQgMAIgWAAQgWAAgNgGgAgZAXIgHAGQgDADAAAFQAAAGAEAEQADAEAJACQAHACALAAQAOAAAJgEQAHgFAAgJQAAgGgEgEQgEgEgKAAIgdgCIgBAAIgGACgAgUgwQgHAFAAAKQAAAJAHAFQAGAGAMAAQAMAAAGgGQAGgFAAgJQAAgKgGgFQgGgGgMAAQgMAAgGAGg");
	this.shape_6.setTransform(30.4,13.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAIAAQAHAAAIgFQAHgEAHgHIAAhCQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAABAAIAJAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIgBBZQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgLIgBgBIgCABQgJAIgIADQgHAEgHAAQgIAAgHgEg");
	this.shape_7.setTransform(19.75,12.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#167ABE").s().p("AAqBDQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIgNgjIgBgBIgBAAIgzAAQgBAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAIgMAjIgBABIgCABIgLAAIgBgBIAAgCIAuh/IABgCIADgBIANAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAABIAuB/IAAACQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAgAgBguIgWA7QgBAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIAqAAQABAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIgWg7IAAgBg");
	this.shape_8.setTransform(8.125,10.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#167ABE").s().p("AgDBbQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAixIABgBIABgBIAHAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAACxQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(-4.6,10.75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#167ABE").s().p("AgfBDQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgKQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIAAhiQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgXAIQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAgHIAAgCIACgBIAbgNIADgCIABAAIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAB0QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAUAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAKIgBABIgCABg");
	this.shape_10.setTransform(-14.9,10.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#167ABE").s().p("AgTBCQgIgCgHgEQgHgEgGgHIAAgBIABgCIAIgGIABAAIABAAQAFAGAGADQAFADAHACQAFABAHAAQAPAAAJgHQAJgHAAgLQgBgIgFgGQgEgGgIgDQgHgDgIAAIgRAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAOgBQAIAAAHgDQAIgDAEgGQAFgFgBgHQABgGgEgFQgDgFgHgDQgGgDgIAAQgJAAgIAEQgHAEgHAGIgCABIgCgBIgGgGQAAAAgBgBQAAAAAAAAQAAgBAAAAQABAAAAgBQAFgGAHgEQAGgEAIgCQAIgCAHAAQANAAALAFQAKAEAFAIQAFAHAAAKQABAKgHAIQgGAIgKADIgDACIADABQAHACAGADQAGAFAEAHQAEAGAAAJQAAALgGAJQgGAJgMAFQgLAFgQAAQgJAAgIgDg");
	this.shape_11.setTransform(-25.05,10.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_12.setTransform(-37.925,12.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#167ABE").s().p("AgVBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAIAHgXIAKgbIAOgeIATghIAAgCIgCAAIhEAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIABgKQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIBUAAIADABIAAABIAAAHIgBADIgCADIgOAYQgGAMgGANIgKAZIgHAWIgEASQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_13.setTransform(-50.575,10.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_14.setTransform(-61.375,10.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#167ABE").s().p("AgkA/QgBgBAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIAAgGIABgDIAEAAIAMAAQAEAAADgCIAFgHIADgIQABgEgBgDIgjhVIAAgCIACgBIALAAIACAAIABACIAaBFIACABQAAAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAIAbhEIABgCIABAAIAJAAIACABIAAACIgoBjQgCAHgDAEQgDAEgEACIgIADIgLACg");
	this.shape_15.setTransform(-75.2625,13.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#167ABE").s().p("AgEBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAh/QAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIAKAAQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAB/IAAACIgCABg");
	this.shape_16.setTransform(-82.2,10.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAIAAQAHAAAHgFQAIgEAHgHIAAhCQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAABAAIAJAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIgBBZQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgLIgBgBIgCABQgJAIgIADQgHAEgHAAQgIAAgHgEg");
	this.shape_17.setTransform(-89.6,12.225);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#167ABE").s().p("AgPBCIgIgCIgBgCIgBgCIACgJQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAFACQADACAGAAQAHAAAEgFQADgEAAgMIAAhgQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAOAAQAAAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABkQgBAQgGAIQgHAIgOAAQgHAAgGgCg");
	this.shape_18.setTransform(-98.95,10.325);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#167ABE").s().p("AgVBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAgBAAAAIAHgXIAKgbIAOgeIATghIAAgCIgCAAIhEAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIABgKQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAIBUAAIADABIAAABIAAAHIgBADIgCADIgOAYQgGAMgGANIgKAZIgHAWIgEASQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAg");
	this.shape_19.setTransform(95.425,-14.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#167ABE").s().p("AgeBDQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgKQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAWAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABAAAAgBIAAhiQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgWAIQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHIAAgCIABgBIAbgNIACgCIACAAIAIAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAB0QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAUAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAKIAAABIgCABg");
	this.shape_20.setTransform(85.95,-14.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_21.setTransform(74.425,-12.725);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#167ABE").s().p("AgTBCQgIgCgHgEQgHgEgGgHIAAgBIABgCIAIgGIABAAIABAAQAFAGAGADQAFADAGACQAGABAIAAQAOAAAJgHQAJgHAAgLQgBgIgEgGQgFgGgIgDQgIgDgHAAIgQAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAMgBQAJAAAHgDQAIgDAEgGQAEgFAAgHQAAgGgDgFQgDgFgHgDQgGgDgIAAQgJAAgIAEQgHAEgIAGIgBABIgCgBIgGgGQAAAAgBgBQAAAAAAAAQAAgBAAAAQABAAAAgBQAGgGAGgEQAHgEAHgCQAHgCAIAAQANAAALAFQAJAEAGAIQAFAHABAKQAAAKgHAIQgFAIgMADIgCACIACABQAIACAGADQAGAFAEAHQADAGAAAJQABALgGAJQgGAJgLAFQgMAFgQAAQgJAAgIgDg");
	this.shape_22.setTransform(61.25,-14.625);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#167ABE").s().p("AgeBDQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgKQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAWAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIAAhiQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBAAAAAAIgWAIQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHIAAgCIABgBIAbgNIADgCIABAAIAIAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAB0QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAVAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAAKIgBABIgBABg");
	this.shape_23.setTransform(51.55,-14.625);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#167ABE").s().p("AgkA+QgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIAAgHIABgCIAEAAIAMAAQAEAAADgCIAFgHIADgIQABgFgBgDIgjhUIAAgCIACgBIALAAIACAAIABACIAaBFIACABQAAAAAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAIAbhEIABgCIABAAIAJAAIACABIAAACIgoBjQgCAHgDAEQgDAEgEACIgIADIgLABg");
	this.shape_24.setTransform(38.7375,-11.25);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#167ABE").s().p("AgEBDQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAh/QAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAKAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAAB/IgBACIgDABg");
	this.shape_25.setTransform(31.8,-14.625);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAJAAQAHAAAHgFQAHgEAGgHIAAhCQAAAAABgBQAAgBAAAAQABAAAAgBQABAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABZQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgKAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgLIAAgBIgCABQgKAIgHADQgGAEgIAAQgJAAgGgEg");
	this.shape_26.setTransform(24.4,-12.625);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#167ABE").s().p("AgPBCIgIgCIgBgCIAAgCIABgJQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAGACQAEACAFAAQAHAAADgFQAEgEAAgMIAAhgQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABkQAAAQgHAIQgHAIgPAAQgHAAgFgCg");
	this.shape_27.setTransform(15.05,-14.525);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#167ABE").s().p("AgDBbQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAixIAAgBIACgBIAHAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAACxQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_28.setTransform(5.6,-14.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_29.setTransform(-6.025,-14.725);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_30.setTransform(-16.775,-14.725);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#167ABE").s().p("AgUAGIgCAAIAAgCIAAgHQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAqAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_31.setTransform(-29.375,-12.725);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_32.setTransform(-42.075,-14.725);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#167ABE").s().p("AgpBEIgCgBIAAgCIAAgIIAAgCIABgCIADgDIAngmIAMgMIAIgLQADgFACgEQABgFAAgFQAAgHgEgGQgEgFgGgDQgGgCgGAAQgFAAgFACQgGABgFAEQgFAEgEAHIgCABIgCgBIgIgFIgBgBIABgDQAIgMAMgFQALgGAMAAQALAAAKAFQAJAEAGAIQAGAIAAANQAAAIgDAHQgDAHgGAHQgGAHgLAKIgjAiIgBABIACABIA+AAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIgCABg");
	this.shape_33.setTransform(-52.825,-14.725);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#167ABE").s().p("AgVArQgLgGgGgLQgFgLAAgPQAAgOAGgLQAGgMAKgFQAKgHAMABQANAAAKAFQAKAGAFALQAFALAAAPIAAACIgCABIhEAAIgBABIgBACQAAAIAEAIQAFAHAHAEQAHAEAIABQAJAAAHgEQAHgEAFgHIABgBIABABIAIADQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgFAHgGAFQgFAEgIACQgHACgJABQgMgBgKgGgAgOghQgHAEgDAIQgDAHAAAIIA1AAIADAAIAAgDQAAgHgDgHQgDgGgHgFQgGgEgJAAQgIAAgHAFg");
	this.shape_34.setTransform(-67.175,-12.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#167ABE").s().p("AAaAxIgBgBIgBgCIAAg/QAAgJgFgFQgEgFgKAAQgFAAgEACQgEABgFAEIgKAIIAABDQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgKAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhaQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAKAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAKIABACIABgBIALgIQAFgDAGgCQAEgCAGABQAOAAAIAHQAHAIAAAMIAABBQAAABAAABQAAAAgBABQAAAAAAAAQgBABgBAAg");
	this.shape_35.setTransform(-77.625,-12.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#167ABE").s().p("AgYAtQgHgDgDgGQgEgHAAgIIAAhCQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAKAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAA+QAAAJAFAFQAFAGAJAAQAGAAAIgFQAHgEAGgHIAAhCQAAAAABgBQAAgBAAAAQABAAAAgBQABAAAAAAIALAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABZQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgLAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgLIAAgBIgCABQgKAIgHADQgHAEgHAAQgIAAgHgEg");
	this.shape_36.setTransform(-88.2,-12.625);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#167ABE").s().p("AgOBCIgJgCIgBgCIAAgCIABgJQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAAAAAIAGACQAEACAFAAQAHAAADgFQAEgEAAgMIAAhgQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABkQABAQgHAIQgHAIgPAAQgGAAgFgCg");
	this.shape_37.setTransform(-97.55,-14.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104.3,-27.3,208.7,50.7);


(lib.t1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0B9444").s().p("AgUCNQgHAAAAgHIAAgqQAAgGAFAAIAsAAQAFAAAAAGIAAApQAAAIgJAAgAgIA7QgEABgCgCIgBgFIgNi7IACgFIADgBIAuAAQAGAAgBAGIgMC6QAAAEgCACQgCACgFgBg");
	this.shape.setTransform(92.2021,18.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0B9444").s().p("AhZCGQgFAAgBgGIAAj5IACgGQABgCAFAAIAjAAQAHAAAAAHIAAANQAAAAAAABQAAAAAAABQABAAAAAAQAAAAABAAIADgBIANgLQAHgGALgEQAKgEAPAAQAXAAARALQASALALAXQALAXgBAiQABAjgLAYQgLAYgSALQgTAMgZAAQgOAAgNgFQgNgFgLgJIgEgDQgCAAAAAFIAABGQAAAGgGAAgAgYhfQgKAFgGAIQgFAHAAAJIAABYQAJAJAKAGQAKAGAMAAQAOAAALgIQAMgIAGgQQAGgQABgaQgBgagGgPQgGgPgMgHQgLgHgMAAQgNAAgJAGg");
	this.shape_1.setTransform(76.35,25.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0B9444").s().p("ABsBnIgFgCIgBgFIAAiCQAAgPgIgIQgHgIgPAAQgJAAgIADQgIAEgGAEIgMAKIgDAFIgBAGIAACAQAAAIgIAAIgiAAIgFgCQgCgBAAgEIAAiCQAAgPgHgIQgHgIgPAAQgNAAgLAHQgLAGgMANIAACGQAAAIgJAAIgiAAQgHAAAAgHIAAi7QAAgHAGAAIAlAAQAFAAAAAGIAAAUIACADIADgCIAUgQQAKgHALgEQALgEAMAAQAVAAANAKQAOAKAFAPIACABIADgCQAKgKALgHQALgIAMgEQAMgEAMAAQAbAAAPAQQAQAQAAAcIAACIQAAAIgIAAg");
	this.shape_2.setTransform(47.175,21.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0B9444").s().p("AhIBZQgQgPAAgZQAAgVAMgPQANgPAYgIQAYgJAggCIATgBIAEgBQABAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAIAAgJQAAgRgKgJQgKgKgRAAQgNAAgLAGQgMAGgIANIgCAEIgFAAIgggIIgDgDQgBgBACgFQALgVAWgMQAWgKAgAAQAdAAASAIQATAHAIAPQAIAOAAATIAACFIgBAGQgCACgDAAIghAAQgDAAgCgDIgBgGIgBgMQgBgGgGAGQgNALgQAHQgOAGgTAAQgdAAgRgPgAAVAEIgXADQgLADgIAFQgJAEgFAIQgFAHAAAJQAAANAJAHQAKAIAQAAQAJAAAIgDQAJgEAHgFIAKgLQAEgGAAgGIAAgbQAAgHgGAAg");
	this.shape_3.setTransform(18.425,22.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0B9444").s().p("Ag8B/QgcgTgPggQgPghAAgsQAAgsAPggQAPggAcgSQAcgQAmAAQAVAAASAFQATAHAPALQAPALAJAPQAKAPADARIAAAHIgEACIgrADIgEgBIgCgFQgEgVgOgOQgOgNgYAAQgfAAgSAZQgRAZAAA2QAAA0ARAZQARAaAiAAQAXAAARgMQARgMAKgbQABgDAGABIAgAHIADACQACACgBAFQgCAIgGALQgGAKgJALQgJALgNAJQgNAIgRAFQgRAFgVABQglAAgdgSg");
	this.shape_4.setTransform(-4.93,18.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0B9444").s().p("AhRCEQgGgCAAgFIAAgYQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAAAQACgCAHAAIAZAAQAIAAAGgFQAGgEAEgGQAEgGABgGQACgHgDgGIhJizQgBgDACgCQABgDAEAAIAoAAIAEACIADAEIAuB9QABAAAAABQAAAAABABQAAAAABAAQAAAAAAAAQACABACgEIAvh8IADgEIAEgCIAcAAQADAAABADQACACgCADIhQDGQgHATgIALQgHAKgJAHQgJAGgMACQgMACgQAAg");
	this.shape_5.setTransform(-37.2325,25.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0B9444").s().p("AhIBZQgQgPAAgZQAAgVAMgPQANgPAYgIQAYgJAggCIATgBIAEgBQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAAAIAAgJQAAgRgKgJQgKgKgRAAQgNAAgLAGQgMAGgIANIgCAEIgFAAIgggIIgDgDQgBgBACgFQALgVAWgMQAWgKAgAAQAdAAASAIQATAHAIAPQAIAOAAATIAACFIgBAGQgCACgDAAIghAAQgDAAgCgDIgBgGIgBgMQgBgGgGAGQgNALgQAHQgOAGgTAAQgdAAgRgPgAAVAEIgXADQgLADgIAFQgJAEgFAIQgFAHAAAJQAAANAJAHQAKAIAQAAQAJAAAIgDQAJgEAHgFIAKgLQAEgGAAgGIAAgbQAAgHgGAAg");
	this.shape_6.setTransform(-59.025,22.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0B9444").s().p("AhrCNQgIAAAAgIIAAkKQAAgEABgCIAHgBIAQAAIAVAAIAXAAIAPABQA0ABAgAQQAhASAPAeQAQAeAAArQAAAtgQAgQgRAfgiARQghARgyAAgAg7heIAAC+QAAAEAGABIAJAAQAjAAAVgKQAYgKAKgXQALgWAAgkQABgkgLgWQgLgWgWgJQgVgLgiAAIgOAAQgDAAgBAGg");
	this.shape_7.setTransform(-82.5,18.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0B9444").s().p("Ag2BmQgEABgBgCIgCgGIAAi7QAAgGAGAAIAkAAQAGAAAAAFIAAAYIABADQABAAAAAAQAAAAABAAQAAAAABgBQAAAAABgBQAIgLAJgIQAJgHAKgDQALgFAJAAQAOABAAAGIAAAkQAAAFgFAAIgMgDIgMAAQgHAAgIADQgIADgHAGQgGAFgEAHQgEAFAAAHIAAB0QAAAHgJAAg");
	this.shape_8.setTransform(70.325,-15.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0B9444").s().p("AgwBcQgWgNgOgXQgNgXAAgeQAAggANgYQAOgYAXgNQAXgNAaAAQAdAAAVAMQAWANAMAXQAMAXAAAhIgBAGQAAACgFAAIiFAAIgEACIgBAFQAAAPAHANQAIAMAMAHQANAHAOAAQAQAAANgHQANgGALgOIACgDIAFACIAWAKQAGACgEAFQgMARgMAKQgOAKgPAEQgRAEgTAAQgcAAgXgMgAgVhBQgMAIgGAMQgGAMAAAPIBYAAIAGAAIABgFQAAgMgGgLQgEgLgLgIQgKgHgPAAQgOAAgLAHg");
	this.shape_9.setTransform(50.75,-14.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0B9444").s().p("ABsBnIgFgCIgBgFIAAiCQAAgPgIgIQgHgIgPAAQgJAAgIADQgIAEgGAEIgMAKIgDAFIgBAGIAACAQAAAIgIAAIgiAAIgFgCQgCgBAAgEIAAiCQAAgPgHgIQgHgIgPAAQgNAAgLAHQgLAGgMANIAACGQAAAIgJAAIgiAAQgHAAAAgHIAAi7QAAgHAGAAIAlAAQAFAAAAAGIAAAUIACADIADgCIAUgQQAKgHALgEQALgEAMAAQAVAAANAKQAOAKAFAPIACABIADgCQAKgKALgHQALgIAMgEQAMgEAMAAQAbAAAPAQQAQAQAAAcIAACIQAAAIgIAAg");
	this.shape_10.setTransform(22.375,-15.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0B9444").s().p("ABsBnIgFgCIgBgFIAAiCQAAgPgIgIQgHgIgPAAQgJAAgIADQgIAEgGAEIgMAKIgDAFIgBAGIAACAQAAAIgIAAIgiAAIgFgCQgCgBAAgEIAAiCQAAgPgHgIQgHgIgPAAQgNAAgLAHQgLAGgMANIAACGQAAAIgJAAIgiAAQgHAAAAgHIAAi7QAAgHAGAAIAlAAQAFAAAAAGIAAAUIACADIADgCIAUgQQAKgHALgEQALgEAMAAQAVAAANAKQAOAKAFAPIACABIADgCQAKgKALgHQALgIAMgEQAMgEAMAAQAbAAAPAQQAQAQAAAcIAACIQAAAIgIAAg");
	this.shape_11.setTransform(-12.325,-15.125);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0B9444").s().p("Ag8BfQgNgGgHgOQgIgOAAgSIAAiJQAAgHAIgBIAjAAQAGAAAAAHIAACBQAAAPAIAJQAJAIAOAAQAMABAMgIQAMgHALgMIAAiGQAAgHAJgBIAiAAQAHAAAAAHIgBC8QAAAGgFAAIglAAQgGAAAAgGIAAgUIAAgDIgDACQgSARgQAHQgPAGgRABQgRAAgOgIg");
	this.shape_12.setTransform(-41.025,-14.75);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0B9444").s().p("AgsCLQgVgGgRgKQgQgMgKgPQgCgDAAgDIAEgEIAYgRQAFgCACAAIAEADQAKAMAJAIQAJAHANAEQAMAEARAAQAaAAAQgJQAQgJAAgTQAAgIgDgGQgEgGgHgFQgIgGgNgEIg5gSQgWgGgOgLQgOgMgIgPQgHgQAAgQQAAgYANgTQANgTAXgKQAYgKAfAAQAUAAASAEQASAEAPAKQAOAIAKAMIACAFQABABgDADIgbAUIgEACIgEgFQgJgKgOgHQgNgIgXAAQgZABgNAJQgNAKAAAQQAAAGACAGQADAGAHAGQAHAGAOAEIA6ASQAjAKAPATQAQAVAAAbQAAAZgOAUQgNASgYALQgZAKghAAQgYgBgWgFg");
	this.shape_13.setTransform(-64.83,-18.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-99.2,-43.5,198.4,87.1);


(lib.lizart_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.lizart();
	this.instance.setTransform(-128,-17.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128,-17.5,256,35);


(lib.f = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.frog();
	this.instance.setTransform(-72,-41,0.36,0.36);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72,-41,144,81);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZA2IgCAAIAAgCIAAhlQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAMAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAANIABABIABAAIAJgKIAKgGQAGgCAFAAQAHAAAAACIAAANQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgEAAIgFAAQgEAAgFACQgFACgEADQgDADgEAEQgCAEAAAFIAABBQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape.setTransform(28.15,0.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZAwQgMgHgGgMQgHgNAAgQQAAgPAHgMQAGgNAMgHQALgHAOAAQAPAAAMAHQALAIAGAMQAHAMAAAPQAAAQgHAMQgGANgLAHQgMAHgPAAQgOAAgLgHgAgRgkQgHAFgEAKQgEAJAAAMQAAANAEAKQAEAJAHAFQAIAGAJAAQALAAAHgGQAIgFAEgJQADgKAAgNQAAgMgEgJQgEgKgHgFQgHgFgLgBQgJABgIAFg");
	this.shape_1.setTransform(17.825,0.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgIBKQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAhZQAAAAgBAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgTAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgJIABgBIACgBIATAAQAAAAAAAAQABAAAAAAQAAAAAAgBQABAAAAgBIAAgOQgBgNAHgHQAFgGANAAIAQAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAIIgBACIgBAAIgOAAQgHAAgDAEQgCAEAAAGIAAAOQAAABAAAAQAAABAAAAQAAAAABAAQAAAAABAAIAWAAIACABIABABIAAAJQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgWAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAABYQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(8.15,-1.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgsBGQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAiFIAAgCIADAAIAKAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIACgBIAGgFQAEgDAGgDQAGgDAIAAQAMABAKAFQAKAHAGALQAGAMAAASQAAARgGANQgGAMgKAHQgKAHgOAAQgIAAgHgEQgHgCgFgEIgDgCIgBADIAAAlQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAgAgQg2QgGAEgEAFQgEAFAAAFIAAAxQAHAGAGAEQAHADAIAAQAIAAAIgEQAHgGAFgKQAEgJAAgOQAAgPgFgIQgEgKgHgEQgIgFgHABQgJAAgGADg");
	this.shape_3.setTransform(-5.575,2.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAyQgHgEgEgGQgEgIAAgIIAAhKQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIALAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAABFQAAAKAFAGQAGAGAJAAQAIAAAIgFQAIgFAHgHIAAhKQAAgBAAAAQABgBAAAAQABgBAAAAQABAAABAAIALAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABkQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgMAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgMIAAgBIgCAAQgLAKgIAEQgIADgIAAQgJAAgIgEg");
	this.shape_4.setTransform(-17.675,1.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAeA2IgDAAIAAgCIAAhHQAAgKgFgGQgFgFgLAAQgGAAgEACIgKAFIgMAJIAABLQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgLAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhlQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIALAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAMIAAABIACAAIAMgJQAGgEAFgCQAGgCAHAAQAPAAAIAJQAJAIgBANIAABKQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_5.setTransform(-33.4,0.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgpBAQgNgHAAgOQAAgGAFgGQAEgGAJgEQABgBAAAAQABAAAAAAQAAgBgBAAQAAAAgBgBQgEgCgCgCQgCgEgBgEIACgFIAGgEIAIgFIABgBIgBgBQgIgEgFgGQgEgIAAgJQAAgPAMgJQAMgJAVAAQAKAAAHADQAHACAFAEIADABIACgBIAFgFIAGgDIAHgCIADACIABACIAAAHIgBADQAAAAgBAAQAAAAAAAAQgBABAAAAQgBAAAAgBIgGABIgEABQgFACAAADIADAFIABAIQAAAJgFAIQgEAHgKAEQgKAFgNAAQgLgBgGACQgFABgDACQgCABAAADQAAADAEABQAFACAJAAIAZACQASAAAIAIQAIAHAAAMQAAAPgOAJQgNAJgXgBQgaABgNgIgAgcAZQgEADgEAEQgDAEAAAGQAAAFAEAFQAEAEAJADQAJACAMAAQAQAAAJgFQAJgEAAgLQgBgGgEgEQgFgFgKgBIghgBQgDAAgFABgAgXg2QgIAGABALQgBALAIAGQAHAFAOAAQANAAAGgFQAHgGAAgLQAAgLgHgGQgGgFgNAAQgOAAgHAFg");
	this.shape_6.setTransform(-45.3,2.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEBKIgDAAIgBgDIAAhjQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIALAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABjIgBADIgCAAgAgFgyQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBgBAAIAAgCIAAgRQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIALAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAQQAAAEgEAAg");
	this.shape_7.setTransform(-53.65,-1.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUBJQgKgDgIgFQgIgGgGgIIgBgCIACgDIAIgFIADgBIACABQAFAHAFAFQAFAEAHACQAHADAJAAQAQAAAKgGQAKgGAAgNQAAgFgCgEQgCgEgFgEQgFgDgJgEIgdgKQgLgDgHgGQgHgGgDgHQgDgHAAgIQAAgMAGgKQAHgJALgFQALgFAOAAQALAAAIACQAJADAHAEQAHAEAFAHIABABIgBACIgJAIIgCAAIgCgCQgFgGgIgEQgIgFgNAAQgOAAgIAHQgJAHAAALIACAIQABAEAFAEQAEAEAKADIAcAKQASAFAHAKQAIAKAAANQAAANgGAJQgHAJgMAFQgLAFgRAAQgLAAgKgDg");
	this.shape_8.setTransform(-62.525,-1.175);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#167ABE").s().p("ArvCrQgyAAgkgkQgigigBgyIAAhlQABgyAigjQAkgjAyAAIXgAAQAxAAAjAjQAjAjAAAyIAABlQAAAygjAiQgjAkgxAAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-87.2,-17.1,174.5,34.2);


(lib.bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,300,250);


(lib.turtle_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.tr("synched",0);
	this.instance.setTransform(-26.05,0,0.9362,0.9362,0,0,0,-0.6,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0,scaleX:1,scaleY:1,x:0},49,cjs.Ease.get(1)).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-165.9,-126.5,316.4,253.1);


(lib.snake_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(102,102,102,0.898)").s().p("AgmAmQgPgPAAgXQAAgVAPgRQAQgPAWAAQAXAAAPAPQAQARAAAVQAAAXgQAPQgPAQgXAAQgWAAgQgQg");
	this.shape.setTransform(8.55,-2.05);
	this.shape._off = true;

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(102,102,102,0.898)").s().p("AgiAjQgQgNgCgSQAAgUAPgPQAPgPAVgBQAHAAAIACQAMADAJAJQALAKAEANQACAGABAFQABANgGALQgEAGgFAEQgQANgVAAQgUAAgQgNg");
	this.shape_1.setTransform(8.5077,-2.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(102,102,102,0.898)").s().p("AAFApQgTAAgQgKQgPgKgGgOIAAAAQABgSAOgOQAOgOAVgBQAGgBAHACQAMACAJAIQALAJAFAMQACAFABAFQACAMgEALIgJAHQgPAJgTAAIgCAAg");
	this.shape_2.setTransform(8.4475,-3.28);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(102,102,102,0.898)").s().p("AAHAjQgSAAgQgIQgPgHgIgJIgBAAQACgRANgNQAOgOATgBQAGgBAGACQAMABAJAHQALAHAGAMIAEAJQACALgCAKIgKAFQgOAGgSAAIgCAAg");
	this.shape_3.setTransform(8.4444,-3.8795);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(102,102,102,0.898)").s().p("AAIAdQgRAAgPgFQgQgEgKgFIgBAAQACgPAMgNQAOgNASgCIALABQALABAJAFQALAGAHALIAEAIQAEAKgBAKIgKACQgNADgQAAIgEAAg");
	this.shape_4.setTransform(8.46,-4.5052);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(102,102,102,0.898)").s().p("AAJAWQgPAAgPgCIgdgBIgBAAQADgPALgLQAMgMASgDQAFAAAFAAQALAAAIAFQALAFAIAJIAFAHQAFAJABAKIgKAAIgKAAIgXgBg");
	this.shape_5.setTransform(8.5,-5.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(102,102,102,0.898)").s().p("AgzAUQADgOAKgJQAQgQAWAAQAXAAAPAQQALAJADAOQgzgMg0AMg");
	this.shape_6.setTransform(8.55,-5.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},6).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[]},1).wait(21));
	this.timeline.addTween(cjs.Tween.get(this.shape).wait(6).to({_off:false},0).wait(7).to({_off:true},1).wait(27));

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_6 = new cjs.Graphics().p("Ak9hTIChiwIHaD+IgqEJQllgXjslAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(6).to({graphics:mask_graphics_6,x:54.9875,y:32.5}).wait(16).to({graphics:null,x:0,y:0}).wait(19));

	// Layer_2
	this.instance = new lib.tg("synched",0);
	this.instance.setTransform(40.35,4.35,1,1,-29.9992);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(6).to({_off:false},0).to({rotation:-30.9912,x:62.85,y:17.6},7,cjs.Ease.get(1)).wait(1).to({rotation:-31.0292,x:62.6986,y:17.5149},0).wait(1).to({regX:0.1,regY:0.1,rotation:-31.1431,x:62.3,y:17.25},0).wait(1).to({regX:0,regY:0,rotation:-31.5024,x:60.502,y:16.3438},0).wait(1).to({rotation:-32.0731,x:57.8845,y:14.9841},0).wait(1).to({rotation:-32.8551,x:54.2976,y:13.1207},0).wait(1).to({rotation:-33.8486,x:49.7413,y:10.7537},0).wait(1).to({rotation:-35.0533,x:44.2156,y:7.8832},0).wait(1).to({rotation:-36.4695,x:37.85,y:4.6},0).to({_off:true},1).wait(19));

	// Layer_1
	this.instance_1 = new lib.snake();
	this.instance_1.setTransform(-148.6,-96.9,0.9316,0.9316);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-148.6,-96.9,297.2,193.8);


(lib.Frog = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.instance = new lib.f("synched",0);
	this.instance.setTransform(-119.2,-10.2,0.24,0.24,0,0,0,0,-0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:-0.5,scaleX:0.3844,scaleY:0.3844,x:-133.1,y:-18.75},0).wait(1).to({regX:-0.1,regY:-0.3,scaleX:0.5136,scaleY:0.5136,x:-145.6,y:-26.25},0).to({regY:-0.4,scaleX:0.81,scaleY:0.6866,x:-163.7,y:-20.5},1).wait(1).to({regX:0,regY:-0.5,scaleX:0.9525,scaleY:0.9216,x:-174.45,y:-12.9},0).wait(1).to({regY:0,scaleX:1,scaleY:1,x:-178.2,y:-10.2},0).wait(16));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-250.2,-51.2,148.29999999999998,81);


// stage content:
(lib.KSFY_216373_MM_300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(168));

	// t3
	this.instance = new lib.t3("synched",0);
	this.instance.setTransform(125,238.85,0.6,0.6,0,0,0,0.1,0);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(62).to({_off:false},0).to({regX:0,scaleX:1,scaleY:1,alpha:1},13,cjs.Ease.get(1)).wait(93));

	// t2
	this.instance_1 = new lib.t2("synched",0);
	this.instance_1.setTransform(193.75,152.6,0.486,0.486,0,0,0,0.1,0.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(45).to({_off:false},0).to({regX:0,regY:0.1,scaleX:0.81,scaleY:0.81,alpha:1},13,cjs.Ease.get(1)).wait(110));

	// t1
	this.instance_2 = new lib.t1("synched",0);
	this.instance_2.setTransform(193.2,99.75,0.4592,0.4592,0,0,0,0.5,0.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(26).to({_off:false},0).to({regX:0.2,regY:0.2,scaleX:0.7654,scaleY:0.7654,x:193.1,y:99.7,alpha:1},13,cjs.Ease.get(1)).wait(129));

	// lizart_png
	this.instance_3 = new lib.lizart_png("synched",0);
	this.instance_3.setTransform(-17,195.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:18,y:191.5},104,cjs.Ease.get(1)).wait(64));

	// snake_png
	this.instance_4 = new lib.snake_1("synched",0);
	this.instance_4.setTransform(264.6,226.9,0.4665,0.4665,0,0,0,0.3,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(168));

	// turtle_png
	this.instance_5 = new lib.turtle_1("synched",0,false);
	this.instance_5.setTransform(37.45,114.45,0.729,0.729);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(168));

	// Frog
	this.instance_6 = new lib.Frog("synched",0,false);
	this.instance_6.setTransform(425.95,40.95,0.81,0.81);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(14).to({_off:false},0).wait(154));

	// Cta
	this.instance_7 = new lib.cta("synched",0);
	this.instance_7.setTransform(401.25,51.5,1,1,0,0,0,0.6,0.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({regX:0.1,regY:0,x:216.2,y:51.45},14,cjs.Ease.get(1)).wait(154));

	// BG_jpg
	this.instance_8 = new lib.bg("synched",0);
	this.instance_8.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(168));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(5,124,482.9,148.10000000000002);
// library properties:
lib.properties = {
	id: 'C00A36863C9C464AA8ADF1E18C148E10',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"frog.png", id:"frog"},
		{src:"lizart.png", id:"lizart"},
		{src:"snake.png", id:"snake"},
		{src:"Tounge.png", id:"Tounge"},
		{src:"turtle.png", id:"turtle"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C00A36863C9C464AA8ADF1E18C148E10'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;