(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.IM1 = function() {
	this.initialize(img.IM1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.IM2 = function() {
	this.initialize(img.IM2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.PBB_logo1 = function() {
	this.initialize(img.PBB_logo1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,244,194);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3927").s().p("AgSBjQgLgMAAgHQAAgHALgLQAMgMAGAAQAHAAAMAMQALALAAAHQAAAHgLAMQgMAMgHAAQgGAAgMgMgAgMAdQgCgFgBgOQgCgVgGgeQgFgYAAgPQAAgeAcAAQAdAAAAAeQAAAPgFAYQgGAdgCAWQgBAOgCAFQgEAIgJAAQgIAAgEgIg");
	this.shape.setTransform(-100.525,15.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B3927").s().p("AgeBLQgIgNABgZQgBgUAEgvQAAAAAAgBQAAgBgBAAQAAgBgBAAQgBAAAAAAIgTAAQgEAAgBgFIAAgMQAAgFAGgBQAUgDAIgMQAEgFAEgRQABgEADAAIATAAQAEAAAAAEIAAAcQABAHABABQABABAGAAIANAAIARgCQALAAAAAGIgCAJQgBAHgDACQgDACgHAAIgPAAIgQgBQAAAAgBAAQgBAAAAABQgBAAAAABQAAABAAAAIAAAZQAAAqAEAOQAFARAQAAQAGAAAHgEQAHgFACAAQAHAAAAAGQAAAFgFAFQgPAXgeAAQgeAAgMgXg");
	this.shape_1.setTransform(-111.1,16.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B3927").s().p("AgfByQgLAAAAgIQAAgEAHgFQAJgEADgJQACgIAAgXIAAgnQABgOgDgFQgCgGgJgEQgJgEAAgEQAAgGAKgCQAZgGAPgGIAIgCQAIAAAAAKIAABYQAAAXADAIQADAJAIAEQAIAFAAAEQAAAIgMAAgAgQhDQgLgLAAgGQAAgHALgLQALgLAGAAQAHAAALALQAKALABAHQgBAHgKAKQgLALgHAAQgGAAgLgLg");
	this.shape_2.setTransform(-120.95,14.475);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B3927").s().p("Ag2BEQgKgJAAgWQAAgPALAAQAFAAAEAEIAKALQAPAVATAAQAIAAAHgFQAIgEAAgIQAAgJgNgGIgcgJQgTgGgJgJQgNgKAAgTQAAgZAVgPQASgOAbAAQAWAAAPAIQANAHAAATQAAAKgCAEQgCAFgIAAQgFAAgGgIQgOgWgTAAQgJAAgFAFQgGAEAAAHQAAAIANAGQAHAEAVAGQArAPAAAfQAAAYgWAPQgUAPgcAAQghAAgQgOg");
	this.shape_3.setTransform(-142.325,18.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B3927").s().p("Ag2BEQgKgJAAgWQAAgPALAAQAFAAAEAEIAKALQAPAVATAAQAIAAAHgFQAIgEAAgIQAAgJgNgGIgcgJQgTgGgJgJQgNgKAAgTQAAgZAVgPQASgOAbAAQAWAAAPAIQANAHAAATQAAAKgCAEQgCAFgIAAQgFAAgGgIQgOgWgTAAQgJAAgFAFQgGAEAAAHQAAAIANAGQAHAEAVAGQArAPAAAfQAAAYgWAPQgUAPgcAAQghAAgQgOg");
	this.shape_4.setTransform(-157.325,18.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B3927").s().p("AgfByQgLAAAAgIQAAgEAHgFQAJgEACgJQADgIAAgXIAAgnQAAgOgCgFQgDgGgIgEQgJgEAAgEQgBgGALgCQAYgGARgGIAHgCQAIAAAAAKIAABYQAAAXADAIQADAJAIAEQAIAFAAAEQAAAIgMAAgAgQhDQgLgLAAgGQAAgHALgLQALgLAGAAQAHAAALALQALALAAAHQAAAHgLAKQgLALgHAAQgGAAgLgLg");
	this.shape_5.setTransform(-169.9,14.475);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B3927").s().p("ABDBQQgLAAAAgIQAAgEAHgFQAJgFACgIQADgIAAgXIAAgkQAAgcgYAAQgLgBgIAJQgHAHgDAOIgBAjQAAAbABAHQACAGAFAEQAIAGAAADQAAAIgLAAIg1AAQgMAAAAgIQAAgEAIgFQAFgEACgGQABgHAAgbIAAghQAAgggYABQgLgBgHAIQgHAHgDAOQgCAMAAAYQAAAVADAKQADAJAIAFQAHAEAAAEQAAAIgLAAIhBAAQgLAAAAgIQAAgFAHgDQAIgFADgJQADgIAAgXIAAgmQAAgOgCgGQgDgGgIgEQgKgEAAgEQAAgGALgCQAXgFASgHQAEgCAEAAQAIAAAAAKIAAAPIABACIABgBQASgaAfAAQAdAAAOAZIACACQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAAAAAQARgZAfAAQAcAAAOAVQAJAPAAAaIAAAkQAAAXADAIQADAIAIAFQAIAFAAAEQgBAIgLAAg");
	this.shape_6.setTransform(-189.925,17.85);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3927").s().p("AgfBLQgGgNAAgZQAAgUADgvQAAAAAAgBQAAgBgBAAQAAgBgBAAQgBAAAAAAIgTAAQgEAAgBgFIAAgMQAAgFAGgBQAUgDAJgMQADgFAEgRQABgEADAAIATAAQAEAAABAEIAAAcQgBAHACABQABABAGAAIANAAIARgCQALAAAAAGIgCAJQgCAHgCACQgDACgHAAIgPAAIgQgBQAAAAgBAAQgBAAAAABQgBAAAAABQAAABAAAAIAAAZQgBAqAFAOQAFARAPAAQAHAAAHgEQAHgFACAAQAGAAABAGQAAAFgFAFQgPAXgeAAQgeAAgNgXg");
	this.shape_7.setTransform(-215.25,16.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3927").s().p("AgLAeQgIgXAAgbQAAgMAEgEQAEgFALAAQAMAAAEAFQAEAEAAAMQAAAbgIAXQgEAMgIAAQgGAAgFgMg");
	this.shape_8.setTransform(-224.325,8.65);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3927").s().p("AATBQQgLAAAAgIQgBgEAIgFQAIgEADgJQADgIAAgXIAAgkQAAgcgZAAQgKAAgIAIQgNANAAArQAAAXACAIQADAJAIAEQAIAFAAAEQAAAIgLAAIhBAAQgLAAAAgIQAAgEAHgFQAIgEADgJQADgIAAgXIAAglQAAgPgCgGQgCgGgJgEQgJgDgBgFQAAgGALgCQAVgFATgHQAFgCAEAAQAHAAABAKIAAAPQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAABAAIABgCQASgZAeAAQAcAAAOAWQAJANAAAbIAAAkQAAAVADAKQACAIAJAFQAIAFgBAEQABAIgMAAg");
	this.shape_9.setTransform(-233.7,17.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3927").s().p("Ag6A8QgXgXAAgkQAAghAYgYQAYgZAjAAQAkAAAWAXQAWAXAAAjQAAAhgXAYQgYAZgjAAQgkAAgWgWgAghgLQAAAWAHAUQAKAbATAAQAPAAAIgOQAIgOAAgWQAAgXgHgSQgJgZgUAAQgfAAAAAvg");
	this.shape_10.setTransform(-251.725,18.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3927").s().p("AAYBnIAAgMQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAIgDACQgTAYgbAAQgcAAgRgWQgSgVAAgfQAAgkAVgYQAWgdAkAAQAQAAAPAHIADABQAAAAAAAAQABAAAAgBQAAAAAAAAQAAgBAAAAIAAgKQAAgOgCgGQgCgGgJgEQgJgDAAgFQAAgFAKgDQAZgGAPgGIAIgCQAIAAAAAKIAACdQAAAOACAFQADAHAIADQAKAFAAAEQAAAFgLADIgmALIgKADQgIAAAAgLgAgkgHQgHANAAAVQAAAYAJAPQAKAPAQAAQANAAAJgMQAKgOAAgaQAAgagKgOQgJgPgOAAQgSAAgJATg");
	this.shape_11.setTransform(-269.025,14.825);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3927").s().p("AhFBOQgVgdAAgvQAAgvAbggQAbghAmAAQAqAAAYAeQAXAeAAAwQAAA0gdAgQgZAdgmAAQgrAAgZghgAglgHQAAAoAKAZQALAbARAAQAkAAAAhOQAAgsgLgZQgKgXgRAAQgkAAAABOg");
	this.shape_12.setTransform(-70.5,-17.825);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3927").s().p("AguBpQgTgGgHgLQgGgJAAgTQAAgMACgEQACgHAJAAQAHAAAFAIIAJARQAQAZAUAAQAPAAAIgNQAIgLAAgTQAAglgiAAIgSACQgMAAAAgKIAAgHQAAgKALAAIASABQAfAAgBgkQAAgNgFgKQgIgKgNAAQgPAAgLANIgMAUQgGALgHAAQgHAAgCgFQgDgFgBgMQABgXAOgKQARgNAjAAQAhAAAUAOQAYAPAAAZQAAAQgMANQgMAOgYAGQgBAAAAABQgBAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAAAABQABAAAAAAQABAAABAAQAWADAPALQARAOAAAWQAAAXgSASQgZAYgsAAQgVAAgRgGg");
	this.shape_13.setTransform(-88.85,-17.825);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3927").s().p("AhKBjQgJgIAAgOQAAgVAPAAQAFAAAJAKQAJAIAKAAQALAAAIgMIACgEIgBgDIgzh2QgHgRgFgFIgKgGQgFgDAAgEQAAgIALAAIBBAAQAKAAAAAHQAAAFgHADQgIAEAAAHQAAAEADAHIAdBDIABACIABgCIATgsQAHgRAAgLQAAgKgIgFQgIgGAAgDQAAgIAMAAIAwAAQAMAAAAAHQAAAFgEADIgIAFQgHAFgEAHQgGAJgKAXIgjBUQgZBBgtAAQgPAAgJgIg");
	this.shape_14.setTransform(-111.95,-12.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("AASA7IgBgCIgBACQgRAXgfAAQgUAAgNgKQgPgLAAgTQAAgYAWgNQAPgIAigLQAWgLAAgPQAAgSgTAAQgKAAgIAGQgHAFgKANQgHAKgHAAQgHAAgDgEQgDgEAAgKQAAgQAGgHQAGgIAVgFQAOgDAQAAQAaAAASAMQAWAOAAAZIgBA5QAAAQABAEQADAHAJABQAIAAAAAGQAAAGgIAGQgKAJgPAAQgZAAgFgXgAAKAAQgUAIgKAIQgMAJAAALQAAAIAFAFQAGAFAIAAQAOAAAIgPQAEgJAAgaIAAgDIgBgBg");
	this.shape_15.setTransform(-129.375,-14.925);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AAyBrQgMAAAAgIQAAgEAHgEQAJgGADgIQADgIAAgWIAAhwQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAAAQgBABAAABIg1CBQgCAGgFAAIgNAAQgGAAgDgGIg2iDIgBgBQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAQAABrABANQACAYAPAIIAJAFQAFACAAAFQAAAIgMAAIg2AAQgNAAAAgHQAAgFAFgDIAIgHQAIgKAAglIABhvIgBgKQgBgCgFgDIgIgEQgEgCAAgEQAAgIAMAAIA7AAQAKAAADAHIArBjIAAACIACgCIAphjQADgHAIAAIBBAAQAKAAAAAHQAAAEgEACIgHAEQgJAFAAARIAAByQAAAWADAIQADAJAIAFQAIAEAAAEQAAAIgMAAg");
	this.shape_16.setTransform(-150.975,-17.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("Ag2BEQgKgJAAgWQAAgPALAAQAFAAAEAEIAKALQAPAVATAAQAIAAAHgFQAIgEAAgIQAAgJgNgGIgcgJQgTgGgJgJQgNgKAAgTQAAgZAVgPQASgOAbAAQAWAAAPAIQANAHAAATQAAAKgCAEQgCAFgIAAQgFAAgGgIQgOgWgTAAQgJAAgFAFQgGAEAAAHQAAAIANAGQAHAEAVAGQArAPAAAfQAAAYgWAPQgUAPgcAAQghAAgQgOg");
	this.shape_17.setTransform(-180.875,-14.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AAYBnIAAgMQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAIgDACQgTAYgbAAQgcAAgRgWQgSgVAAgfQAAgkAVgYQAWgdAkAAQAQAAAPAHIADABQAAAAAAAAQABAAAAgBQAAAAAAAAQAAgBAAAAIAAgKQAAgOgCgGQgCgGgJgEQgJgDAAgFQAAgFAKgDQAZgGAPgGIAIgCQAIAAAAAKIAACdQAAAOACAFQADAHAIADQAKAFAAAEQAAAFgLADIgmALIgKADQgIAAAAgLgAgkgHQgHANAAAVQAAAYAJAPQAKAPAQAAQANAAAJgMQAKgOAAgaQAAgagKgOQgJgPgOAAQgSAAgJATg");
	this.shape_18.setTransform(-196.875,-18.125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("AATBQQgMAAAAgIQAAgEAIgFQAIgEADgJQADgIAAgXIAAgkQAAgcgZAAQgKAAgIAIQgOAOAAAqQABAXADAIQACAJAIAEQAIAFAAAEQAAAIgLAAIhBAAQgLAAAAgIQAAgEAHgFQAIgEADgJQADgIAAgXIAAglQAAgPgCgGQgCgGgJgEQgKgDAAgFQAAgGALgCQAVgFATgHQAFgCAEAAQAHAAAAAKIAAAPQAAAAABABQAAAAAAAAQAAABAAAAQAAAAABAAIACgCQARgZAeAAQAcAAAOAWQAJANAAAbIAAAkQAAAVADAKQACAIAJAFQAHAFAAAEQAAAIgLAAg");
	this.shape_19.setTransform(-215,-15.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AgzA9QgWgWAAgjQAAghAXgaQAXgaAhAAQAbAAAUARQAVASAAAbQAAAMgHAEQgFADgOAAIhHAAQgBAAgBAAQAAAAAAAAQgBABAAAAQAAABAAAAIAAAEQABAMAHAKQAOAXAdAAQAOAAAMgGIANgGQAHAAAAAGQAAAKgSAMQgWAPgcAAQggAAgWgVgAgPgyQgJAJgCAOIgBADQAAAAAAABQABAAAAABQAAAAABAAQAAAAABAAIAiAAQATAAAAgNQAAgJgGgHQgHgHgLAAQgMAAgIAIg");
	this.shape_20.setTransform(-233.825,-14.925);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AgzA9QgWgWAAgjQAAghAXgaQAXgaAhAAQAbAAAUARQAVASAAAbQAAAMgHAEQgFADgOAAIhHAAQgBAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIAAAEQABAMAHAKQAOAXAdAAQAOAAAMgGIANgGQAHAAAAAGQAAAKgSAMQgWAPgcAAQggAAgWgVgAgPgyQgJAJgCAOIgBADQAAAAAAABQABAAAAABQAAAAABAAQAAAAABAAIAiAAQATAAAAgNQAAgJgGgHQgHgHgLAAQgMAAgIAIg");
	this.shape_21.setTransform(-258.775,-14.925);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AgeBwQgMAAAAgIQgBgEAIgEQAJgFACgJQADgIAAgXIAAhmQAAgPgCgFQgCgHgJgDQgKgEAAgEQAAgGALgDQAYgGAQgFIAIgCQAIAAAAAKIAACYQAAAXADAIQADAJAIAFQAIAEgBAEQAAAIgMAAg");
	this.shape_22.setTransform(-270.55,-18.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AASA7IgBgCIgBACQgRAXgfAAQgUAAgNgKQgPgLAAgTQAAgYAWgNQAPgIAigLQAWgLAAgPQAAgSgTAAQgKAAgIAGQgHAFgKANQgHAKgHAAQgHAAgDgEQgDgEAAgKQAAgQAGgHQAGgIAVgFQAOgDAQAAQAaAAASAMQAWAOAAAZIgBA5QAAAQABAEQADAHAJABQAIAAAAAGQAAAGgIAGQgKAJgPAAQgZAAgFgXgAAKAAQgUAIgKAIQgMAJAAALQAAAIAFAFQAGAFAIAAQAOAAAIgPQAEgJAAgaIAAgDIgBgBg");
	this.shape_23.setTransform(-283.825,-14.925);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B3927").s().p("AgwBoQgUgHgHgKQgGgKAAgRIgBgLQAAgOALAAQAGAAAGAHIAQAUQAWAXAWAAQAQAAAJgHQALgKAAgMQAAgQgSgKQgHgEgegMQgagJgMgKQgSgPAAgXQAAgcAXgTQAYgUAjAAQAoAAASARQAHAIAAAVQAAAVgMAAQgFAAgGgGIgLgOQgTgXgUAAQgKAAgJAHQgIAGAAAMQAAAPARAKQAFADAgAMQAaAKANALQARAPAAAaQAAAegZAUQgZAUgmAAQgXAAgUgHg");
	this.shape_24.setTransform(-303.325,-17.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-346.9,-32.2,316.9,67);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6B3927").s().p("AgJAKQgHgGAAgEQAAgDAHgGQAGgHADAAQAEAAAHAHQAGAGAAADQAAAEgGAGQgHAHgEAAQgDAAgGgHg");
	this.shape.setTransform(-14.125,26.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6B3927").s().p("AggArQgGgFAAgOQAAgJAGAAQADAAACADIAGAHQAKAOALAAQAIAAAFgEQAFgDAAgGQAAgIgLgEIgQgFQgMgEgGgFQgIgHAAgLQAAgRARgJQAKgHAMAAQAPAAAIAGQAHAEAAAMQAAALgFAAQgEAAgDgFQgKgPgLAAQgGAAgFAEQgEADAAAFQAAAIAOAFIASAFQAJAEAFAFQAHAHAAALQAAAQgOAJQgLAIgQAAQgVAAgJgJg");
	this.shape_1.setTransform(-21.575,23.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6B3927").s().p("AASBCIAAgJQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAQgMAQgRAAQgJAAgIgFQgWgLAAgeQAAgYANgPQAOgSAUAAQALABAMAGIAAAAIABgBIAAgKQAAgLgCgDQgBgDgFgCQgFgCAAgDQAAgDAFgBIAUgGIAHgBQAEgBAAAGIAABlQAAALABACQACADAFADQAFACAAACQAAAEgFABIgWAHIgFABQgEAAAAgGgAgXgIQgGAIAAASQAAAPAHALQAGALALAAQAKAAAGgJQAHgJAAgSQAAgSgHgJQgGgKgKAAQgLAAgHAKg");
	this.shape_2.setTransform(-32.325,21.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6B3927").s().p("AgRBGQgGAAAAgDQAAgDADgDQAGgDABgDQACgFAAgPIAAhFQAAgLgBgDQgCgDgFgCQgEgCAAgDQAAgDAFgBQAKgCAIgDIAHgCQAFgBAAAGIAABjQAAAPACAFQACADAFADQADADAAADQABADgHAAg");
	this.shape_3.setTransform(-41.3,21.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6B3927").s().p("AgRBHQgGAAAAgEQAAgCAEgDQAFgDABgDQADgFAAgPIAAgeQAAgKgCgCQgCgEgEgCQgGgCAAgCQAAgEAGgBQAKgCAIgDIAHgDQAFAAAAAGIAAA7QAAAPACAEQACAEAFADQAEADAAACQAAAEgHAAgAgJgtQgGgGAAgEQAAgDAGgGQAGgGADAAQAEAAAGAGQAGAGAAADQAAAEgGAGQgGAGgEAAQgDAAgGgGg");
	this.shape_4.setTransform(-47.175,21.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6B3927").s().p("AAUAuIAAgLIAAAAIgBAAQgLARgTAAQgQAAgJgNQgGgIAAgSIAAgcQAAgLgCgCQgCgEgFgCQgFgCAAgCQAAgDAGgCIAWgGIAEgCQAFAAAAAHIAAA5QAAAVARAAQAIAAAFgGQAJgJAAgfQAAgNgBgDQgCgEgFgCQgFgBAAgDQAAgDAGgCIAVgGIAFgCQAEAAAAAHIAAA8QAAAKACADQACAEAFACQAFACAAACQAAAEgGABQgNADgJAEIgEABQgFAAAAgGg");
	this.shape_5.setTransform(-56.475,23.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6B3927").s().p("AgSBBIgHgCQgCAAgCADQgDAFgDABQgFgBAAgGIAAhkQAAgKgBgEQgCgDgFgCQgFgCAAgDQAAgDAGgBQAMgDAKgEIAEAAQAEgBAAAGIAAAyQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAABAAIABgBQAMgQASAAQASAAAKAPQAKANAAASQAAAQgGAOQgOAbgdAAQgNAAgKgHgAgKgFQgHAJAAARQAAATAHAKQAHAJAKAAQALAAAGgKQAGgKAAgQQAAgQgGgKQgHgKgLAAQgKAAgGAIg");
	this.shape_6.setTransform(-68.425,21.35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6B3927").s().p("AAOAyQgGABAAgFQAAgCAEgDQAEgDACgDQACgFAAgQIAAgZQAAgJgEgGQgFgFgIgBQgIAAgFAHQgFAFgCAIQgCAJAAARQAAAQACAFQACADAFADQAEADAAACQAAAFgHgBIgkAAQgGABAAgFQAAgCAEgDQAFgDACgDQACgFAAgQIAAgcQAAgLgCgCQgBgEgFgCQgGgCAAgCQAAgDAGgCQAMgCAHgDIAHgDQAFAAAAAHIAAAKIABABIABgBQALgRASAAQARABAJANQAGAIAAARIAAAZQAAAQACAFQACAEAFACQAEADAAACQAAAFgHgBg");
	this.shape_7.setTransform(-83.325,23.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6B3927").s().p("AgeAyQgGAAAAgDQAAgDAEgDQAEgDACgDQACgFAAgPIAAgdQAAgKgCgDQgBgEgFgCQgFgCAAgCQAAgDAFgCQANgDAHgDIAFgCQAFAAAAAHIAAAOIAAABIABAAQACgJAHgGQAIgHAIAAQAHAAADAFQAEAEAAAHQAAAKgHAAQgDABgFgDQgDgCgDAAQgFAAgEAEQgIAJAAAeQAAAPABAFQACADAEADQAEADAAADQAAADgGAAg");
	this.shape_8.setTransform(-93.275,23.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6B3927").s().p("AAOAkIgBAAQgLAQgTAAQgMAAgJgHQgJgHAAgLQAAgOANgIQAKgFAVgHQAPgHAAgLQAAgKgKgCIgEgBQgIAAgGAFIgHAIIgEAHQgCACgEAAQgGAAAAgKQAAgLADgEQAEgFALgCQAJgCAKgBQAQABALAIQALAKAAAOIAAAnQAAAPAFAAIADAAQAEAAAAAEIgBAEQgGAIgLAAQgOAAgCgQgAAAADIgNAHQgIAGAAAJQAAAFADAEQAEADAGAAQALAAAFgLQAEgHAAgRIAAgDIgBAAIgBAAQgDABgHADg");
	this.shape_9.setTransform(-103.075,23.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6B3927").s().p("AgSBBIgHgCQgCAAgCADQgDAFgDABQgFgBAAgGIAAhkQAAgKgBgEQgCgDgFgCQgFgCAAgDQAAgDAGgBQAMgDAKgEIAEAAQAEgBAAAGIAAAyQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAABAAIABgBQAMgQASAAQASAAAKAPQAKANAAASQAAAQgGAOQgOAbgdAAQgNAAgKgHgAgKgFQgHAJAAARQAAATAHAKQAHAJAKAAQALAAAGgKQAGgKAAgQQAAgQgGgKQgHgKgLAAQgKAAgGAIg");
	this.shape_10.setTransform(-114.075,21.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6B3927").s().p("AAtAyQgHAAAAgDQAAgDAEgDQAEgDACgDQACgFAAgPIAAgZQABgWgSAAQgIAAgGAHQgEAEgCAJIgBAbQAAAQACAFQABADAEACQAEADAAADQAAADgGAAIgfAAQgHAAAAgDQAAgDAFgDQADgDABgCQACgFAAgQIAAgYQAAgXgRAAQgIABgFAFQgFAFgCAJQgBAJgBASQAAAPACAFQADADAEADQAEADAAADQAAADgGAAIgkAAQgHAAAAgDQAAgDAFgDQAEgDACgDQACgFAAgPIAAgdQAAgLgCgCQgBgEgFgCQgFgBgBgCQAAgFAHgBQANgDAIgDIAFgCQAFAAgBAHIAAAKIABABIAAgBQAMgQAUgBQAKABAHAFQAGAFADAGIABABIABgBQALgQATgBQARABAJANQAGAIAAARIAAAaQAAAPACAFQACADAFADQADADAAADQAAADgFAAg");
	this.shape_11.setTransform(-131.2,23.25);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#6B3927").s().p("AAOAkIgBAAQgLAQgTAAQgMAAgJgHQgJgHAAgLQAAgOANgIQAKgFAVgHQAPgHAAgLQAAgKgKgCIgEgBQgIAAgGAFIgHAIIgEAHQgCACgEAAQgGAAAAgKQAAgLADgEQAEgFALgCQAJgCAKgBQAQABALAIQALAKAAAOIAAAnQAAAPAFAAIADAAQAEAAAAAEIgBAEQgGAIgLAAQgOAAgCgQgAAAADIgNAHQgIAGAAAJQAAAFADAEQAEADAGAAQALAAAFgLQAEgHAAgRIAAgDIgBAAIgBAAQgDABgHADg");
	this.shape_12.setTransform(-145.875,23.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#6B3927").s().p("AgXAtQgMgIgFgOQgEgKAAgKQAAgOAHgNQAHgNANgHQALgHALAAQAPAAALAKQAOAMAAAPQAAAIgDACQgEAEgIAAIgwAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAABQAAAMAHAJQAIAMAPABQALAAAJgGIAJgEQAEAAAAADQAAAIgMAHQgNAJgRAAQgNgBgLgGgAgPgcQgFAIAAAGQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAZAAQAPAAAAgKQgBgGgFgFQgFgGgIABQgLgBgHALg");
	this.shape_13.setTransform(-156.35,23.35);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#6B3927").s().p("AgSBBIgHgCQgCAAgCADQgDAFgDABQgFgBAAgGIAAhkQAAgKgBgEQgCgDgFgCQgFgCAAgDQAAgDAGgBQAMgDAKgEIAEAAQAEgBAAAGIAAAyQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAABAAIABgBQAMgQASAAQASAAAKAPQAKANAAASQAAAQgGAOQgOAbgdAAQgNAAgKgHgAgKgFQgHAJAAARQAAATAHAKQAHAJAKAAQALAAAGgKQAGgKAAgQQAAgQgGgKQgHgKgLAAQgKAAgGAIg");
	this.shape_14.setTransform(-167.325,21.35);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#6B3927").s().p("AgvAxQgPgKAAgTQAAgKAHgJQAGgIALgDQgEgJAAgHQAAgQAMgJQAKgJAOAAQAPAAAGAIQAEAEAAAKQAAANgGAAQgFAAgCgDIgCgHIgEgHQgEgFgHAAQgFAAgEAEQgFAEABAGQgBAJAJAIQAGAIAPAJIAZARIABAAQADgFAAgJQAAgIgKgGQgFgCABgDQAAgEAFAAIAgAAQAGAAgBAEQABACgFADQgGADgDAIQgEAPgEAIIgBABIABABIAHAGQAJALABAMQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBAAIgPAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBQgBgFgFgFIgBgBIgBABQgPAQgZAAQgTAAgPgMgAghAAQgFAGAAAJQAAANAKAJQAKAJAPAAQALAAAKgIIAAgBIAAAAIgZgSQgRgMgHgHIgBgBIgBABg");
	this.shape_15.setTransform(-183.7,22.45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#6B3927").s().p("AgRAxQgEgIAAgPIABguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgHQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQANgDAEgIQACgCACgLQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAJAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAATIABAEIAEABIAVgCQAGAAAAAEIAAAEQgBAHgIAAIgVgBQAAAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIAAAWQAAAaACAIQAEAJAJAAQAFAAAFgDIAGgDQABAAABAAQAAAAABAAQAAABABAAQAAABAAABQAAACgDAEQgEAGgHAEQgIAEgIAAQgQAAgIgNg");
	this.shape_16.setTransform(-197.125,22.325);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6B3927").s().p("AggArQgGgFAAgOQAAgJAGAAQADAAACADIAGAHQAKAOALAAQAIAAAFgEQAFgDAAgGQAAgIgLgEIgQgFQgMgEgGgFQgIgHAAgLQAAgRARgJQAKgHAMAAQAPAAAIAGQAHAEAAAMQAAALgFAAQgEAAgDgFQgKgPgLAAQgGAAgFAEQgEADAAAFQAAAIAOAFIASAFQAJAEAFAFQAHAHAAALQAAAQgOAJQgLAIgQAAQgVAAgJgJg");
	this.shape_17.setTransform(-206.125,23.35);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6B3927").s().p("AgkAmQgNgOAAgXQAAgVAOgOQAOgQAVgBQAXABANAPQAOANAAAWQAAAVgPAPQgOAQgVAAQgWAAgOgOgAgSgeQgGAJgBAPQABATAGANQAIANAMAAQALAAAGgJQAGgJAAgPQAAgRgHgNQgHgOgMAAQgKgBgHAJg");
	this.shape_18.setTransform(-216.3,23.35);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6B3927").s().p("AguBFQgHAAAAgEQAAgDAEgCQAFgDACgEQACgFAAgPIAAhBQAAgLgBgDQgCgDgFgCQgFgCAAgCQAAgEAGgBQALgCAJgEIAGgCQAEAAAAAGIAAAJQAAABAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIACgBQAMgQARAAQAJAAAIAFQAWALAAAfQAAAWgNAQQgNARgVAAQgLAAgLgGIgBAAIgBABIAAAFQAAAOACAFQACAEAFADQAEACAAADQAAAEgGAAgAgKgqQgHAKAAARQAAARAHALQAHAJAKAAQALAAAGgLQAGgKAAgOQAAgQgGgLQgHgKgLAAQgKAAgGAIg");
	this.shape_19.setTransform(-227.925,25.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6B3927").s().p("AgeAyQgGAAAAgDQAAgDAEgDQAEgDACgDQACgFAAgPIAAgdQAAgKgCgDQgBgEgFgCQgFgCAAgCQAAgDAFgCQANgDAHgDIAFgCQAFAAAAAHIAAAOIAAABIABAAQACgJAHgGQAIgHAIAAQAHAAADAFQAEAEAAAHQAAAKgHAAQgDABgFgDQgDgCgDAAQgFAAgEADQgIAKAAAeQAAAPABAFQACADAEADQAEADAAADQAAADgGAAg");
	this.shape_20.setTransform(71.625,1.65);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6B3927").s().p("AAOAlIgBgBQgLAQgTAAQgMAAgJgHQgJgHAAgLQAAgOANgIQAKgFAVgHQAPgHAAgLQAAgKgKgCIgEgBQgIAAgGAFIgHAIIgEAHQgCACgEAAQgGAAAAgKQAAgLADgEQAEgFALgCQAJgCAKgBQAQABALAIQALAKAAAOIAAAnQAAAPAFABIADgBQAEAAAAAEIgBAEQgGAIgLAAQgOAAgCgPgAAAADIgNAHQgIAGAAAJQAAAFADAEQAEADAGAAQALAAAFgLQAEgHAAgRIAAgDIgBAAIgBAAQgDABgHADg");
	this.shape_21.setTransform(61.775,1.75);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6B3927").s().p("AgRBGQgGAAAAgDQAAgDAEgDQAFgDACgDQACgFAAgPIAAhFQgBgLgBgDQgCgDgFgCQgEgCgBgDQAAgDAGgBQAKgCAIgEIAIgBQAEgBAAAGIAABjQAAAPACAFQACADAEADQAFADAAADQgBADgGAAg");
	this.shape_22.setTransform(53.7,-0.35);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6B3927").s().p("AAUAuIAAgLIAAAAIgBAAQgLARgTAAQgQAAgJgNQgGgIAAgSIAAgcQAAgLgCgCQgCgEgFgCQgFgCAAgCQAAgDAGgCIAWgGIAEgCQAFAAAAAHIAAA5QAAAVARAAQAIAAAFgGQAJgJAAgfQAAgNgBgDQgCgEgFgCQgFgBAAgDQAAgDAGgCIAVgGIAFgCQAEAAAAAHIAAA8QAAAKACADQACAEAFACQAFACAAACQAAAEgGABQgNADgJAEIgEABQgFAAAAgGg");
	this.shape_23.setTransform(44.525,1.75);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6B3927").s().p("AguBFQgHAAAAgEQAAgDAEgCQAFgDACgEQACgFAAgPIAAhBQAAgLgBgDQgCgDgFgCQgFgCAAgCQAAgEAGgBQALgCAJgEIAGgCQAEAAAAAGIAAAJQAAABAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIACgBQAMgQARAAQAJAAAIAFQAWALAAAfQAAAWgNAQQgNARgVAAQgLAAgLgGIgBAAIgBABIAAAFQAAAOACAFQACAEAFADQAEACAAADQAAAEgGAAgAgKgqQgHAKAAARQAAARAHALQAHAJAKAAQALAAAGgLQAGgKAAgOQAAgQgGgLQgHgKgLAAQgKAAgGAIg");
	this.shape_24.setTransform(32.875,3.475);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6B3927").s().p("AgjAmQgOgOAAgXQAAgVAOgPQAPgPAUgBQAXABAOAPQANANAAAWQAAAVgOAPQgPAQgVAAQgVAAgOgOgAgRgeQgIAJABAPQgBATAIANQAHANAMAAQALAAAGgJQAGgJAAgPQAAgRgGgNQgIgOgMAAQgLgBgFAJg");
	this.shape_25.setTransform(22.15,1.75);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6B3927").s().p("AguBFQgHAAAAgEQAAgDAEgCQAFgDACgEQACgFAAgPIAAhBQAAgLgBgDQgCgDgFgCQgFgCAAgCQAAgEAGgBQALgCAJgEIAGgCQAEAAAAAGIAAAJQAAABAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIACgBQAMgQARAAQAJAAAIAFQAWALAAAfQAAAWgNAQQgNARgVAAQgLAAgLgGIgBAAIgBABIAAAFQAAAOACAFQACAEAFADQAEACAAADQAAAEgGAAgAgKgqQgHAKAAARQAAARAHALQAHAJAKAAQALAAAGgLQAGgKAAgOQAAgQgGgLQgHgKgLAAQgKAAgGAIg");
	this.shape_26.setTransform(11.025,3.475);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#6B3927").s().p("AgRAxQgEgIAAgPIABguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgHQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQANgDAEgIQACgCACgLQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAJAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAATIABAEIAEABIAVgCQAGAAAAAEIAAAEQgBAHgIAAIgVgBQAAAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIAAAWQAAAaACAIQAEAJAJAAQAFAAAFgDIAGgDQABAAABAAQAAAAABAAQAAABABAAQAAABAAABQAAACgDAEQgEAGgHAEQgIAEgIAAQgQAAgIgNg");
	this.shape_27.setTransform(-1.275,0.725);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#6B3927").s().p("AggArQgGgFAAgOQAAgJAGAAQADAAACADIAGAHQAKAOALAAQAIAAAFgEQAFgDAAgGQAAgIgLgEIgQgFQgMgEgGgFQgIgHAAgLQAAgRARgJQAKgHAMAAQAPAAAIAGQAHAEAAAMQAAALgFAAQgEAAgDgFQgKgPgLAAQgGAAgFADQgEAEAAAFQAAAIAOAFIASAGQAJADAFAFQAHAHAAALQAAAQgOAJQgLAIgQAAQgVAAgJgJg");
	this.shape_28.setTransform(-10.275,1.75);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#6B3927").s().p("AgjAmQgOgOAAgXQAAgVAOgPQAPgPAUgBQAXABAOAPQANANAAAWQAAAVgOAPQgPAQgVAAQgVAAgOgOgAgRgeQgIAJABAPQgBATAIANQAHANAMAAQALAAAGgJQAGgJAAgPQAAgRgGgNQgIgOgMAAQgLgBgFAJg");
	this.shape_29.setTransform(-20.5,1.75);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#6B3927").s().p("AAtAyQgHAAAAgDQAAgDAEgDQAEgDACgDQACgFAAgPIAAgZQAAgWgQAAQgJAAgGAHQgEAEgCAJIgBAbQAAAQACAFQABADAEACQAEADAAADQgBADgFAAIgfAAQgHAAAAgDQABgDAEgDQADgDABgCQACgFAAgQIAAgYQAAgXgRAAQgIABgFAFQgFAFgCAJQgCAJAAASQAAAPADAFQABADAFADQAEADAAADQAAADgGAAIgkAAQgGAAgBgDQAAgDAFgDQAEgDACgDQACgFAAgPIAAgdQAAgLgBgCQgCgEgFgCQgFgBgBgCQAAgFAHgBQAMgDAJgDIAFgCQAFAAgBAHIAAAKIABABIAAgBQAMgQAUgBQAKABAHAFQAGAFADAGIABABIABgBQALgQAUgBQAQABAJANQAGAIAAARIAAAaQAAAPACAFQACADAEADQAEADAAADQAAADgFAAg");
	this.shape_30.setTransform(-34.35,1.65);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#6B3927").s().p("AgeAyQgGAAAAgDQAAgDAEgDQAEgDACgDQACgFAAgPIAAgdQAAgKgCgDQgBgEgFgCQgFgCAAgCQAAgDAFgCQANgDAHgDIAFgCQAFAAAAAHIAAAOIAAABIABAAQACgJAHgGQAIgHAIAAQAHAAADAFQAEAEAAAHQAAAKgHAAQgDABgFgDQgDgCgDAAQgFAAgEADQgIAKAAAeQAAAPABAFQACADAEADQAEADAAADQAAADgGAAg");
	this.shape_31.setTransform(-50.625,1.65);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#6B3927").s().p("AAUAuIAAgLIAAAAIgBAAQgLARgTAAQgQAAgJgNQgGgIAAgSIAAgcQAAgLgCgCQgCgEgFgCQgFgCAAgCQAAgDAGgCIAWgGIAEgCQAFAAAAAHIAAA5QAAAVARAAQAIAAAFgGQAJgJAAgfQAAgNgBgDQgCgEgFgCQgFgBAAgDQAAgDAGgCIAVgGIAFgCQAEAAAAAHIAAA8QAAAKACADQACAEAFACQAFACAAACQAAAEgGABQgNADgJAEIgEABQgFAAAAgGg");
	this.shape_32.setTransform(-60.375,1.75);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#6B3927").s().p("AgjAmQgOgOAAgXQAAgVAOgPQAPgPAUgBQAXABAOAPQANANAAAWQAAAVgOAPQgPAQgVAAQgVAAgOgOgAgRgeQgIAJABAPQgBATAIANQAHANAMAAQALAAAGgJQAGgJAAgPQAAgRgGgNQgIgOgMAAQgLgBgFAJg");
	this.shape_33.setTransform(-71.35,1.75);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#6B3927").s().p("AgRAbIABgDQAFgCAEgFQAGgHAAgFQAAgEgGgFQgGgHAAgEQAAgDAGgGQAGgGACAAQAFAAAHAHQAFAHAAAHQAAAMgNAPQgLANgHAAQgEAAAAgEg");
	this.shape_34.setTransform(-84.775,6.875);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#6B3927").s().p("AggArQgGgFAAgOQAAgJAGAAQADAAACADIAGAHQAKAOALAAQAIAAAFgEQAFgDAAgGQAAgIgLgEIgQgFQgMgEgGgFQgIgHAAgLQAAgRARgJQAKgHAMAAQAPAAAIAGQAHAEAAAMQAAALgFAAQgEAAgDgFQgKgPgLAAQgGAAgFADQgEAEAAAFQAAAIAOAFIASAGQAJADAFAFQAHAHAAALQAAAQgOAJQgLAIgQAAQgVAAgJgJg");
	this.shape_35.setTransform(-92.375,1.75);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#6B3927").s().p("AgRAxQgEgIAAgPIABguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgHQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQANgDAEgIQACgCACgLQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAJAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAATIABAEIAEABIAVgCQAGAAAAAEIAAAEQgBAHgIAAIgVgBQAAAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIAAAWQAAAaACAIQAEAJAJAAQAFAAAFgDIAGgDQABAAABAAQAAAAABAAQAAABABAAQAAABAAABQAAACgDAEQgEAGgHAEQgIAEgIAAQgQAAgIgNg");
	this.shape_36.setTransform(-99.875,0.725);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#6B3927").s().p("AgRBHQgGAAAAgEQAAgCAEgDQAFgDABgDQADgFAAgPIAAgeQAAgKgCgCQgCgEgEgCQgGgCAAgCQAAgEAGgBQAKgCAIgDIAHgDQAFAAAAAGIAAA7QAAAPACAEQACAEAFADQAEADAAACQAAAEgHAAgAgJgtQgGgGAAgEQAAgDAGgGQAGgGADAAQAEAAAGAGQAGAGAAADQAAAEgGAGQgGAGgEAAQgDAAgGgGg");
	this.shape_37.setTransform(-105.875,-0.425);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#6B3927").s().p("AAmBGQgKAAgEgCQgFgDgMgTQgKgTgEAAQgCAAgDADIgGAGIgBACQAAAMADAFQABAEAFACQAEADAAACQAAAFgGgBIglAAQgGABAAgFQAAgCAEgDQAEgDACgDQACgGAAgPIAAhDQAAgLgBgDQgCgEgFgBQgFgCAAgDQAAgEAGgBQANgDAHgDIAHgBQAEgBAAAGIAABSIABAAIABAAIARgQQALgMAAgEQAAgCgDgDQgDgCAAgCQAAgEAHAAIAkAAQAGAAAAAEQAAADgDABIgGACQgMAEgaAZIgBABIABAAIADAAQAFgBAEAHIALAPQAPAYAGACQAGAEAAADQAAADgFAAg");
	this.shape_38.setTransform(-113.975,-0.35);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#6B3927").s().p("AgXAtQgMgIgFgOQgEgKAAgKQAAgOAHgNQAHgNANgHQAKgHAMAAQAPAAALAKQAOAMAAAPQAAAIgDACQgDAEgKAAIgvAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAAAABQAAAMAHAJQAIAMAPABQALAAAIgGIAKgEQAEAAAAADQAAAIgMAHQgNAJgRAAQgNgBgLgGgAgPgcQgFAIAAAGQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAZAAQAPAAAAgKQgBgGgFgFQgFgGgJABQgKgBgHALg");
	this.shape_39.setTransform(-130.8,1.75);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6B3927").s().p("AggArQgGgFAAgOQAAgJAGAAQADAAACADIAGAHQAKAOALAAQAIAAAFgEQAFgDAAgGQAAgIgLgEIgQgFQgMgEgGgFQgIgHAAgLQAAgRARgJQAKgHAMAAQAPAAAIAGQAHAEAAAMQAAALgFAAQgEAAgDgFQgKgPgLAAQgGAAgFADQgEAEAAAFQAAAIAOAFIASAGQAJADAFAFQAHAHAAALQAAAQgOAJQgLAIgQAAQgVAAgJgJg");
	this.shape_40.setTransform(-140.925,1.75);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#6B3927").s().p("AAOAlIgBgBQgLAQgTAAQgMAAgJgHQgJgHAAgLQAAgOANgIQAKgFAVgHQAPgHAAgLQAAgKgKgCIgEgBQgIAAgGAFIgHAIIgEAHQgCACgEAAQgGAAAAgKQAAgLADgEQAEgFALgCQAJgCAKgBQAQABALAIQALAKAAAOIAAAnQAAAPAFABIADgBQAEAAAAAEIgBAEQgGAIgLAAQgOAAgCgPgAAAADIgNAHQgIAGAAAJQAAAFADAEQAEADAGAAQALAAAFgLQAEgHAAgRIAAgDIgBAAIgBAAQgDABgHADg");
	this.shape_41.setTransform(-150.725,1.75);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#6B3927").s().p("AgSBBIgHgCQgCAAgCADQgDAFgDABQgFgBAAgGIAAhkQAAgKgBgEQgCgDgFgCQgFgCAAgDQAAgDAGgBQAMgDAKgEIAEAAQAEgBAAAGIAAAyQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAABAAIABgBQAMgQASAAQASAAAKAPQAKANAAASQAAAQgGAOQgOAbgdAAQgNAAgKgHgAgKgFQgHAJAAARQAAATAHAKQAHAJAKAAQALAAAGgKQAGgKAAgQQAAgQgGgKQgHgKgLAAQgKAAgGAIg");
	this.shape_42.setTransform(-161.725,-0.25);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#6B3927").s().p("AgpA7QgHgFAAgJQAAgEACgEQAFgIAJAAQAFAAAAADIgBAEIgBAFQAAAIAIAEQAIAEANAAQAMAAAIgEQAIgEAAgGQAAgHgPgBIgdgBQgJgCgGgFQgFgFAAgGQAAgLANgFIABAAIgBgBQgTgJAAgVQAAgPALgLQAMgKARgBQALAAALAGIAHAEQADAAADgFQACgFAFAAQAJAAAAAJQAAAKgNAAIgCAAQADAHAAAKQAAAPgLAKQgLAJgPABIgIAAQgIABAAAFQAAAFAMABIANAAIAPABQALABAGAGQAGAGAAAIIgBAIQgIAYgpAAQgaAAgMgKgAgOgyQgEAGAAAIQAAANAGAIQAFAHAGAAQAGAAAFgGQADgGAAgJQAAgLgEgIQgFgIgHAAQgHAAgEAGg");
	this.shape_43.setTransform(-177.825,3.475);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#6B3927").s().p("AAOAyQgGABAAgFQAAgCAEgDQAEgDACgDQACgFAAgQIAAgZQAAgJgEgGQgFgFgIgBQgIAAgFAHQgFAFgCAIQgCAJAAARQAAAQACAFQACADAFADQAEADAAACQAAAFgHgBIgkAAQgGABAAgFQAAgCAEgDQAFgDACgDQACgFAAgQIAAgcQAAgLgCgCQgBgEgFgCQgGgCAAgCQAAgDAGgCQAMgCAHgDIAHgDQAFAAAAAHIAAAKIABABIABgBQALgRASAAQARABAJANQAGAIAAARIAAAZQAAAQACAFQACAEAFACQAEADAAACQAAAFgHgBg");
	this.shape_44.setTransform(-188.925,1.65);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#6B3927").s().p("AgRBHQgGAAAAgEQAAgCAEgDQAFgDABgDQADgFAAgPIAAgeQAAgKgCgCQgCgEgEgCQgGgCAAgCQAAgEAGgBQAKgCAIgDIAHgDQAFAAAAAGIAAA7QAAAPACAEQACAEAFADQAEADAAACQAAAEgHAAgAgJgtQgGgGAAgEQAAgDAGgGQAGgGADAAQAEAAAGAGQAGAGAAADQAAAEgGAGQgGAGgEAAQgDAAgGgGg");
	this.shape_45.setTransform(-198.075,-0.425);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#6B3927").s().p("AgRBGQgGAAAAgDQAAgDADgDQAGgDABgDQACgFAAgPIAAhFQAAgLgBgDQgCgDgFgCQgEgCAAgDQAAgDAFgBQAKgCAIgEIAHgBQAFgBAAAGIAABjQAAAPACAFQACADAFADQADADAAADQABADgHAAg");
	this.shape_46.setTransform(-204.2,-0.35);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#6B3927").s().p("AgeAyQgGAAAAgDQAAgDAEgDQAEgDACgDQACgFAAgPIAAgdQAAgKgCgDQgBgEgFgCQgFgCAAgCQAAgDAFgCQANgDAHgDIAFgCQAFAAAAAHIAAAOIAAABIABAAQACgJAHgGQAIgHAIAAQAHAAADAFQAEAEAAAHQAAAKgHAAQgDABgFgDQgDgCgDAAQgFAAgEADQgIAKAAAeQAAAPABAFQACADAEADQAEADAAADQAAADgGAAg");
	this.shape_47.setTransform(-210.775,1.65);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#6B3927").s().p("AgXAtQgMgIgFgOQgEgKAAgKQAAgOAGgNQAIgNANgHQALgHALAAQAPAAALAKQAOAMAAAPQAAAIgDACQgEAEgIAAIgwAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAMAHAJQAIAMAPABQALAAAJgGIAJgEQAEAAAAADQAAAIgMAHQgNAJgQAAQgNgBgMgGgAgPgcQgFAIAAAGQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAZAAQAOAAABgKQAAgGgGgFQgFgGgIABQgLgBgHALg");
	this.shape_48.setTransform(-220.6,1.75);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#6B3927").s().p("AgRAxQgEgIAAgPIABguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgHQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQANgDAEgIQACgCACgLQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAJAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAATIABAEIAEABIAVgCQAGAAAAAEIAAAEQgBAHgIAAIgVgBQAAAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIAAAWQAAAaACAIQAEAJAJAAQAFAAAFgDIAGgDQABAAABAAQAAAAABAAQAAABABAAQAAABAAABQAAACgDAEQgEAGgHAEQgIAEgIAAQgQAAgIgNg");
	this.shape_49.setTransform(-228.725,0.725);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#6B3927").s().p("AgdBBQgLgDgFgHQgCgEgBgMIgBgIQAAgHAGAAQAEAAACAEIAKANQAOAPAOAAQALAAAHgGQAHgGAAgJQAAgLgKgHQgGgEgMgEQgPgFgHgEQgTgJAAgTQAAgOAKgLQAKgLAPgEIANgBQAYABAKAJQAFAGAAANQAAAMgHAAQgDAAgCgEIgGgHQgDgFgEgEQgJgIgKAAQgIAAgGAFQgGAGAAAIQAAALAOAHQAHAEASAFQAOAGAHAGQAKAKAAAOQAAAIgEAJQgNAbgkAAQgOAAgMgFg");
	this.shape_50.setTransform(-238.925,-0.05);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#6B3927").s().p("AguAxQgQgKABgTQAAgKAGgJQAHgIAKgDQgEgJAAgHQAAgQALgJQALgJANAAQAQAAAHAIQADAEAAAKQAAANgHAAQgEAAgCgDIgDgHIgDgHQgFgFgHAAQgFAAgDADQgEAFgBAGQABAJAIAIQAHAIAOAJIAZARIABAAQADgFAAgJQAAgIgKgGQgEgCgBgDQAAgEAHAAIAfAAQAFAAABAEQgBACgEADQgGADgDAIQgEAPgFAIIAAABIABABIAGAGQALALgBAMQAAABAAABQAAAAAAABQgBAAAAAAQgBAAgBAAIgPAAQgEAAAAgDQgCgFgFgFIAAgBIgBABQgOAQgaAAQgUAAgNgMgAghAAQgFAGAAAJQAAANAKAJQAKAJAOAAQANAAAJgIIABgBIgBAAIgZgSQgRgMgIgHIAAgBIgBABg");
	this.shape_51.setTransform(-255.3,0.85);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#6B3927").s().p("AgeAyQgGAAAAgDQAAgDAEgDQAEgDACgDQACgFAAgPIAAgdQAAgKgCgDQgBgEgFgCQgFgCAAgCQAAgDAFgCQANgDAHgDIAFgCQAFAAAAAHIAAAOIAAABIABAAQACgJAHgGQAIgHAIAAQAHAAADAFQAEAEAAAHQAAAKgHAAQgDABgFgDQgDgCgDAAQgFAAgEADQgIAKAAAeQAAAPABAFQACADAEADQAEADAAADQAAADgGAAg");
	this.shape_52.setTransform(-269.275,1.65);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#6B3927").s().p("AgXAtQgMgIgFgOQgEgKAAgKQAAgOAGgNQAIgNANgHQALgHALAAQAPAAALAKQAOAMAAAPQAAAIgDACQgEAEgIAAIgwAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAMAHAJQAIAMAPABQALAAAJgGIAJgEQAEAAAAADQAAAIgMAHQgNAJgQAAQgNgBgMgGgAgPgcQgFAIAAAGQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAZAAQAOAAABgKQAAgGgGgFQgFgGgIABQgLgBgHALg");
	this.shape_53.setTransform(-279.1,1.75);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#6B3927").s().p("AAmBGQgKAAgEgCQgFgDgMgTQgKgTgEAAQgCAAgDADIgGAGIgBACQAAAMADAFQABAEAFACQAEADAAACQAAAFgGgBIglAAQgGABAAgFQAAgCAEgDQAEgDACgDQACgGAAgPIAAhDQAAgLgBgDQgCgEgFgBQgFgCAAgDQAAgEAGgBQANgDAHgDIAHgBQAEgBAAAGIAABSIABAAIABAAIARgQQALgMAAgEQAAgCgDgDQgDgCAAgCQAAgEAHAAIAkAAQAGAAAAAEQAAADgDABIgGACQgMAEgaAZIgBABIABAAIADAAQAFgBAEAHIALAPQAPAYAGACQAGAEAAADQAAADgFAAg");
	this.shape_54.setTransform(-289.225,-0.35);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#6B3927").s().p("AAOAlIgBgBQgLAQgTAAQgMAAgJgHQgJgHAAgLQAAgOANgIQAKgFAVgHQAPgHAAgLQAAgKgKgCIgEgBQgIAAgGAFIgHAIIgEAHQgCACgEAAQgGAAAAgKQAAgLADgEQAEgFALgCQAJgCAKgBQAQABALAIQALAKAAAOIAAAnQAAAPAFABIADgBQAEAAAAAEIgBAEQgGAIgLAAQgOAAgCgPgAAAADIgNAHQgIAGAAAJQAAAFADAEQAEADAGAAQALAAAFgLQAEgHAAgRIAAgDIgBAAIgBAAQgDABgHADg");
	this.shape_55.setTransform(-300.875,1.75);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#6B3927").s().p("AgwBDQgHABAAgFQAAgCAEgDQAEgCACgEQACgGAAgOIAAhHIgBgMQAAgDgDgCIgFgDQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAAAQAAgEAGgBIAsAAIAXACQAMABAIAGQALAIAAAOQAAAIgFAIQgHALgSADQAAAAgBABQAAAAAAAAQAAAAAAAAQgBAAAAAAIABABQAQACAKAIQALAIAAAPQAAALgGAIQgPATgqAAgAgQACQAAAAAAABQgBAAAAAAQAAAAAAAAQgBABAAAAIAAAfQABAPABACQACACALABQAgAAAAgbQAAgaggAAgAgRgzIAAAmQAAABAAABQAAAAABAAQAAABAAAAQABAAAAAAIAJAAQAdAAAAgXIAAgBQgBgUgbAAIgKAAQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABg");
	this.shape_56.setTransform(-312.25,-0.05);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#6B3927").s().p("AgXAtQgMgIgGgOQgDgKAAgKQAAgOAGgNQAIgNANgHQAKgHALAAQAQAAALAKQAOAMAAAPQAAAIgDACQgDAEgJAAIgwAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAMAHAJQAJANAOAAQAKgBAKgFIAJgEQAEAAAAAEQAAAHgMAHQgNAJgQAAQgNgBgMgGgAgPgcQgFAIAAAGQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAZAAQAOAAABgKQAAgGgGgFQgFgGgIAAQgLAAgHALg");
	this.shape_57.setTransform(-21.05,-23.1);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#6B3927").s().p("AAOBGQgGABAAgFQAAgCAEgDQAEgDACgDQACgFAAgQIAAgaQAAgUgRAAQgIAAgFAHQgFAFgCAHQgCAJAAASQAAAQACAFQACADAFADQADADAAACQAAAFgFgBIgkAAQgHABABgFQgBgCAEgDQAFgDACgDQACgGAAgPIAAhEQAAgLgCgDQgCgDgEgCQgFgCAAgDQgBgDAHgBQALgCAKgFIAEAAQAFgBAAAGIAAAzIABABIAAgBQALgQAUgBQAQABAJANQAGAIAAAQIAAAaQAAAQACAFQADAEAEACQADADAAACQAAAFgFgBg");
	this.shape_58.setTransform(-32.25,-25.2);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#6B3927").s().p("AgRAxQgEgIAAgPIABguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgHQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQANgDAEgIQACgCACgLQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIAJAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAATIABAEIAEABIAVgCQAGAAAAAEIAAAEQgBAHgIAAIgVgBQAAAAgBAAQAAAAgBAAQAAABAAAAQAAABAAAAIAAAWQAAAaACAIQAEAJAJAAQAFAAAFgDIAGgDQABAAABAAQAAAAABAAQAAABABAAQAAABAAABQAAACgDAEQgEAGgHAEQgIAEgIAAQgQAAgIgNg");
	this.shape_59.setTransform(-41.475,-24.125);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#6B3927").s().p("AAOAyQgGABAAgFQAAgCAEgDQAEgDACgDQACgFAAgQIAAgZQAAgJgEgGQgFgFgIgBQgIAAgFAHQgFAFgCAIQgCAJAAARQAAAQACAFQACADAFADQAEADAAACQAAAFgHgBIgkAAQgGABAAgFQAAgCAEgDQAFgDACgDQACgGAAgPIAAgcQAAgLgCgCQgBgEgFgCQgGgCAAgCQAAgDAGgCQAMgCAHgDIAHgDQAFAAAAAHIAAAKIABABIABgBQALgRASAAQARABAJANQAGAIAAARIAAAZQAAAQACAFQACAEAFACQAEACAAADQAAAFgHgBg");
	this.shape_60.setTransform(-54.875,-23.2);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#6B3927").s().p("AgkAmQgNgOAAgXQAAgUAOgPQAOgQAVgBQAXABANAPQAOANAAAWQAAAVgPAPQgOAPgVABQgWAAgOgOgAgSgeQgGAJgBAPQABATAGANQAIAOAMgBQALAAAGgJQAGgJAAgQQAAgQgHgNQgHgPgMAAQgKAAgHAJg");
	this.shape_61.setTransform(-66,-23.1);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#6B3927").s().p("AAbBoQgPgSAAgbQAAgbASgTQARgRAYAAQAaAAAQARQARASAAAcQAAAdgSASQgRARgYAAQgbAAgRgTgAA1A7QAAASAFAMQAFANAIAAQASAAAAgrQAAgrgSAAQgSAAAAArgAhWB3ICRjsIAbAAIiQDsgAhygNQgPgSAAgbQAAgbARgSQASgTAYAAQAaAAAQASQAQASAAAcQAAAdgRASQgRAQgYAAQgcAAgQgSgAhYg6QAAASAFANQAFAMAIAAQASAAAAgrQAAgrgSAAQgSAAAAArg");
	this.shape_62.setTransform(-92.025,-30.075);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#6B3927").s().p("AguB7QgSgGgIgLQgIgLAAgfQAAgQAPAAQAIAAAGAKIAKATQASAbAaAAQARAAALgLQANgLAAgQQAAgWgWgPQgdgVg1AAIgIAAQgEAAAAgDIAAgFIAWhrQABgEAGAAIAwAAQAaAAAIgDQAHgBAGgGQAGgHAFAAQAIAAAAAJIgCASIgEAUQgBAJgEADQgFAEgUAAIhBAAQgBAAgBAAQAAABgBAAQAAAAAAABQgBAAAAABIgEAUIAAACQAAABAAABQAAAAABAAQAAABABAAQABAAABAAQA5ABAfAaQAbAWAAAjQAAAkgbAXQgaAXglAAQgVAAgQgGg");
	this.shape_63.setTransform(-115.975,-30.675);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#6B3927").s().p("AAFB5QgHAAAAgIIAAilQAAgSgCgEQgCgGgMAAIgYACQgJAAAAgQQAAgJAIgBIAdgFQARgCAMgDQAWgGAEAAQALAAAAALIAADeQAAAIgJAAg");
	this.shape_64.setTransform(-138.375,-30.25);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#6B3927").s().p("Ag4BEQgZgYAAgnQAAgmAZgcQAagdAlAAQAeAAAVATQAYATAAAfQAAANgHAFQgGADgQAAIhPAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABAAABIAAAEQABANAIAMQAQAZAfAAQAQAAANgHQANgHACAAQAHAAAAAHQAAALgUANQgYARgegBQglAAgXgWgAgRg3QgJAJgDAQIAAADQAAABAAAAQAAABABAAQAAABAAAAQABAAABAAIAlAAQAVAAAAgOQAAgKgHgIQgHgIgNAAQgMAAgKAJg");
	this.shape_65.setTransform(-162.525,-26.85);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#6B3927").s().p("AgTBYQgEAAgCgEIgxh6QgJgTgFgGIgLgHQgGgDAAgFQAAgJANAAIBIAAQAMAAAAAJQAAAFgJAEQgIAEAAAIQAAAEADAHIAfBOQAAABAAAAQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBIAXgzQAHgTABgMQgBgMgIgGQgJgGAAgDQAAgKANAAIA2AAQAOAAAAAJQAAAFgFADQgMAJgIALQgGAJgMAaIgtBjQgDAEgFAAg");
	this.shape_66.setTransform(-180.05,-26.725);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#6B3927").s().p("AAUBBIgBgCIgCACQgSAZgjAAQgVABgPgLQgRgMAAgWQAAgaAZgOQAQgJAmgNQAZgMAAgQQgBgUgUAAQgLAAgKAHQgHAFgLAPQgIALgIAAQgIAAgDgFQgDgEAAgMQAAgSAGgHQAHgKAXgEQAQgDASgBQAcABAUANQAZAPAAAcIgBA/QAAASACAFQACAHAKABQAJABgBAGQABAHgJAGQgLAKgRgBQgbAAgGgZgAALAAQgWAJgLAJQgNAJgBANQAAAJAHAFQAGAGAIAAQARAAAIgRQAEgJABgeIAAgDIgBgBg");
	this.shape_67.setTransform(-199.65,-26.85);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#6B3927").s().p("Ag1B0QgXgIgIgMQgHgKAAgTIAAgNQAAgPAMAAQAHAAAHAIIARAWQAZAaAYAAQASAAAKgJQAMgKAAgOQAAgRgUgLQgIgFghgNQgdgLgOgKQgTgRAAgaQAAgfAagVQAagWAnAAQAsAAAUATQAIAIAAAZQAAAWgNAAQgGAAgGgGIgNgQQgVgZgWAAQgMAAgJAHQgKAIAAANQAAAQAUALQAFADAkAOQAdAKAOANQATAQAAAdQAAAigcAWQgcAWgqAAQgaAAgVgHg");
	this.shape_68.setTransform(-221.275,-30.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-340.9,-45.6,436.59999999999997,80.1);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.PBB_logo1();
	this.instance.setTransform(-43.5,-34.55,0.3564,0.3565);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.5,-34.5,87,69.1);


(lib.IM2_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM2();
	this.instance.setTransform(-150,-143.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-143.5,728,90);


(lib.IM1_jpg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IM1();
	this.instance.setTransform(-204,-144);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-204,-144,728,90);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAVA/QAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAgBgBIgShMIAAgBIAAABIgRBMQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgUAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAgBgBIggh4IAAgBQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAWAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIARBIIAAABIABgBIAQhIQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAVAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIASBIIABABIAAgBIARhIQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIAVAAQABAAABAAQAAAAAAABQAAAAABAAQAAABgBABIgdB4QAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(99.1542,22.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYA7QgKgGgGgKQgGgKgBgOIAAgmQABgNAGgKQAGgKAKgGQAKgGAOAAQAOAAALAGQALAGAFAKQAHAKAAANIAAAmQAAAOgHAKQgFAKgLAGQgLAGgOAAQgOAAgKgGgAgPgjQgGAGAAAKIAAAnQAAAKAGAHQAGAGAJAAQAJAAAHgGQAGgHAAgKIAAgnQAAgKgGgGQgGgHgKAAQgJAAgGAHg");
	this.shape_1.setTransform(84.7,22.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaA/QAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIguhLIAAgBIgBABIABBLIgBABIgCABIgVAAIgBgBIgBgBIAAh5IABgBIABgBIAVAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIAuBLIAAAAIABgBIAAhKIAAgBIACgBIAVAAIABABIABABIAAB5IgBABIgBABg");
	this.shape_2.setTransform(72.125,22.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgrA/IgCgBIAAgBIAAh5IAAgBIACgBIAyAAQAMAAAJAEQAJAFAFAKQAEAIAAAMQAAALgFAJQgFAHgJAGQgJAEgMAAIgZAAIgBABIAAAuIAAABIgCABgAgUgnIAAAhIABABIAWAAQAIgBAFgEQAFgFAAgHQAAgJgFgFQgFgEgIAAIgWAAIgBABg");
	this.shape_3.setTransform(55.475,22.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYA7QgKgGgGgKQgGgKgBgOIAAgmQABgNAGgKQAGgKAKgGQALgGANAAQAOAAALAGQALAGAFAKQAHAKAAANIAAAmQAAAOgHAKQgFAKgLAGQgLAGgOAAQgNAAgLgGgAgPgjQgGAGAAAKIAAAnQAAAKAGAHQAGAGAJAAQAJAAAHgGQAGgHAAgKIAAgnQAAgKgGgGQgGgHgKAAQgJAAgGAHg");
	this.shape_4.setTransform(43.3,22.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAXA/IgCgBIAAgBIAAgyIgBAAIgnAAIgBAAIAAAyIAAABIgCABIgVAAIgCgBIAAgBIAAh5IAAgBIACgBIAVAAIACABIAAABIAAAwIABABIAnAAIABgBIAAgwIAAgBIACgBIAVAAIABABIABABIAAB5IgBABIgBABg");
	this.shape_5.setTransform(31.125,22.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYA8QgKgFgGgIQgGgJAAgLIAAgEIABgBIABgBIAUAAIACABIABABIAAACQAAAIAGAFQAHAEAKAAQAKAAAFgDQAEgFABgFQgBgFgDgCQgCgDgGgDIgOgGQgMgEgJgEQgIgEgFgIQgGgHAAgLQAAgKAGgJQAFgIAKgEQAKgFAMAAQANABALAFQALAEAGAJQAGAJAAALIAAADIgBABIgCABIgUAAIgBgBIgBgBIAAgBQAAgIgGgGQgHgEgJAAQgJgBgFAEQgEADAAAHQAAAEACADQADADAFADIARAGQAMAFAIAEQAHACAGAIQAGAGAAAMQAAARgNAKQgMAJgWABQgNAAgLgFg");
	this.shape_6.setTransform(19.05,22.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(4));

	// Layer_1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#DD002A").s().p("AoNCyQgYAAAAgdIAAkpQAAgdAYAAIQbAAQAYAAAAAdIAAEpQAAAdgYAAg");
	this.shape_7.setTransform(60.95,21.6);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(6,3.8,110,35.6);


(lib.circle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003595").s().p("AmdGeQirisAAjyQAAjyCrirQCsirDxAAQDzAACqCrQCsCrAADyQAADyisCsQiqCrjzAAQjxAAisirg");
	this.shape.setTransform(0.0284,0.0069,1.6824,1.2992);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-98.4,-76,196.9,152);


// stage content:
(lib.WFSB_215325_MM_728x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [183];
	// timeline functions:
	this.frame_183 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(183).call(this.frame_183).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Eg43gHBMBxvAAAIAAODMhxvAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(184));

	// CTA
	this.instance = new lib.CTA();
	this.instance.setTransform(524.95,-39.8,0.9,0.9,0,0,0,89.5,21.2);
	this.instance.alpha = 0;
	this.instance._off = true;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.CTA(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(147).to({_off:false},0).to({regY:21.3,x:529.45,y:44.75,alpha:1},16,cjs.Ease.get(1)).wait(21));

	// T2
	this.instance_1 = new lib.T2("synched",0);
	this.instance_1.setTransform(484.25,46.65);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(133).to({_off:false},0).to({alpha:1},14,cjs.Ease.get(1)).wait(37));

	// T1
	this.instance_2 = new lib.T1("synched",0);
	this.instance_2.setTransform(479.25,141);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(21).to({_off:false},0).to({y:51,alpha:1},19,cjs.Ease.get(1)).wait(79).to({startPosition:0},0).to({alpha:0},14,cjs.Ease.get(1)).wait(51));

	// Logo
	this.instance_3 = new lib.Symbol1("synched",0);
	this.instance_3.setTransform(-0.5,42);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:99.5,alpha:1},22,cjs.Ease.get(1)).wait(162));

	// Layer_6 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EAiZAIZQkfjeAAk7QAAk6EfjfQEhjeGYAAQGYAAEfDeQEhDfAAE6QAAE7khDeQkfDfmYAAQmYAAkhjfg");
	mask.setTransform(388.1986,32.9569);

	// IM2_jpg
	this.instance_4 = new lib.IM2_jpg("synched",0);
	this.instance_4.setTransform(150,143.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(119).to({_off:false},0).to({alpha:1},28).wait(37));

	// IM1_jpg
	this.instance_5 = new lib.IM1_jpg("synched",0);
	this.instance_5.setTransform(210,144);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(21).to({_off:false},0).to({alpha:1},19).wait(144));

	// Layer_8
	this.instance_6 = new lib.circle("synched",0);
	this.instance_6.setTransform(671.95,29.95);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(21).to({_off:false},0).to({alpha:1},19).wait(144));

	// BG_png
	this.instance_7 = new lib.BG();

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(184));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(320,-10.5,450.4,186);
// library properties:
lib.properties = {
	id: 'EEF434D48E144756B168A098B39DCC79',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.png", id:"BG"},
		{src:"IM1.jpg", id:"IM1"},
		{src:"IM2.jpg", id:"IM2"},
		{src:"PBB_logo1.png", id:"PBB_logo1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EEF434D48E144756B168A098B39DCC79'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;