(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_05 = function() {
	this.initialize(img.Img_05);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AARAnIgBgBIgBgCIAAgwQAAgFgDgEQgDgDgGAAIgFABIgGADIgGAGIAAAyQAAAAAAABQgBAAAAABQgBAAAAAAQgBABgBAAIgMAAQgBgBAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhFQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAIIABABIABgBIAIgGIAHgEQAEgCAFAAQAKABAGAFQAHAHAAAKIAAAzQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAg");
	this.shape.setTransform(96.875,6.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AASAmQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIgOgrIgBgBIAAABIgOAsIgBABIgBABIgLAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBIgXhFIAAgCIACgBIAOAAIACABIABABIAOAtIABABIABgBIAOgtIABgBIABgBIAKAAIABABIABABIAPAtIAAABQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAOgtIABgBIACgBIAJAAIACABIAAACIgXBGIgBABIgCABg");
	this.shape_1.setTransform(87.3875,7.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgTAiQgIgFgFgJQgFgIAAgMQAAgKAFgJQAFgJAJgFQAIgFAKAAQALAAAJAFQAIAFAFAJQAFAJAAAKQAAAMgFAIQgFAJgIAFQgJAFgLAAQgKAAgJgFgAgJgXQgEADgDAGQgCAGAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDADgGQACgFAAgJQAAgIgDgGQgCgGgEgDQgEgDgGAAQgFAAgEADg");
	this.shape_2.setTransform(77.175,7.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgoA1QgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAhjIAAgCIACgBIAHAAIAHAAIAIAAIAHABQASAAANAGQALAGAHAMQAFALAAAQQAAARgGAMQgGALgNAHQgNAGgRAAgAgVgiIAABGQAAAAAAABQAAAAAAAAQAAABAAAAQABAAAAAAIAEAAQANAAAIgEQAIgDAEgJQAEgJABgNQgBgNgEgIQgDgIgJgEQgHgEgNAAIgFAAQAAAAgBABQAAAAAAAAQAAAAAAABQAAAAAAABg");
	this.shape_3.setTransform(67.4,5.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeAxQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgJIABgBIADgBIAJAAQAEAAABgCIAEgDIADgGQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAgBAAAAIgbhDIAAgCIACgBIAPAAIACABIABABIARAvQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIABgBIARgvIABgBIACgBIAKAAIACABIAAACIgeBLQgCAGgDAEQgDAFgDACQgEACgEABIgKAAg");
	this.shape_4.setTransform(53.2,8.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgRAiQgJgFgFgIQgFgJAAgLQAAgLAFgJQAFgJAJgFQAJgFAJAAQALAAAIAFQAIAEAEAJQAFAJAAALIAAADIgCABIgyAAIgBAAIAAACQAAAGACAEQADAFAFADQAFACAEAAQAGAAAFgCQAFgDAEgFIABgBIABABIAJAEQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgFAGgFAEQgFAEgGACQgFABgIAAQgKAAgIgFgAgHgYQgFADgCAFQgCAEAAAGIAgAAIACAAIABgCQAAgEgCgFQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_5.setTransform(44.775,7.025);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AARAnIgBgBIgBgCIAAgwQAAgFgDgEQgDgDgGAAIgFABIgGADIgGAGIAAAyQAAAAAAABQgBAAAAABQgBAAAAAAQgBABgBAAIgMAAQgBgBAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhFQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAIIABABIABgBIAIgGIAHgEQAEgCAFAAQAKABAGAFQAHAHAAAKIAAAzQAAAAAAABQgBAAAAABQAAAAgBAAQgBABAAAAg");
	this.shape_6.setTransform(36.175,6.95);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgTAiQgIgFgFgJQgFgIAAgMQAAgKAFgJQAFgJAJgFQAIgFAKAAQALAAAJAFQAIAFAFAJQAFAJAAAKQAAAMgFAIQgFAJgIAFQgJAFgLAAQgKAAgJgFgAgJgXQgEADgDAGQgCAGAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDADgGQACgFAAgJQAAgIgDgGQgCgGgEgDQgEgDgGAAQgFAAgEADg");
	this.shape_7.setTransform(27.475,7.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAlA1IgCgBIgBgCIAAhJIAAgBIgBABIgbBKQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgJAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgbhJIgBgBIAAABIAABIIgBACIgCABIgMAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhjQAAgBAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAYAAIACABIABABIAZBCIAAACIABgCIAYhBQAAgBABAAQAAgBAAAAQABgBAAAAQABAAAAAAIAZAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAABIAABjQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_8.setTransform(17.275,5.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgTAiQgIgFgFgJQgFgIAAgMQAAgKAFgJQAFgJAJgFQAIgFAKAAQALAAAJAFQAIAFAFAJQAFAJAAAKQAAAMgFAIQgFAJgIAFQgJAFgLAAQgKAAgJgFgAgJgXQgEADgDAGQgCAGAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDADgGQACgFAAgJQAAgIgDgGQgCgGgEgDQgEgDgGAAQgFAAgEADg");
	this.shape_9.setTransform(1.425,7.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAcA1IgBAAIgCgCIgwhEIgBAAIAAABIAABCQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgMAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhjQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIAPAAIACABIABABIAtBBQAAAAABABQAAAAAAAAQAAAAAAAAQABAAAAAAIAAgBIAAhAQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIANAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAABlIgBABIgCABg");
	this.shape_10.setTransform(-8.425,5.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIAVIgCgBIAAgBIAHgQQABgBAAgBQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIAAgQQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAPIgBACIgLAUIgCACIgDAAg");
	this.shape_11.setTransform(-21.6375,10.825);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAIAzQgJgBgFgEQgGgEABgJIAAgqQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgKAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgJQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIACgVQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAVQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAJQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgQAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAIAAAlQAAAGACACQACACAGABIAIAAIACAAIAAACIAAAHQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBABIgFAAIgGABg");
	this.shape_12.setTransform(-25.15,5.75);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgTAjQgJgFgEgHIAAgBIABgCIAIgEIACAAIABAAIAFAGIAHAEQAEABAFAAIAIgBQADgBACgCQADgDAAgDQAAgCgDgCQgCgDgGgBIgOgEQgLgCgFgEQgFgFAAgIQAAgHAEgGQAEgFAHgDQAHgDAIAAQALAAAHAEQAIADAEAGIAAACQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgJAFIgCAAIgBgBQgDgEgEgCQgFgDgGAAQgFAAgEADQgEACAAAFIABAEQACACAGABIAQAFQALADAFAEQAEAGAAAIQAAAHgEAFQgEAGgHACQgIADgJAAQgMAAgIgEg");
	this.shape_13.setTransform(-32.325,7.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgRAiQgJgFgFgIQgFgJAAgLQAAgLAFgJQAFgJAJgFQAJgFAJAAQALAAAIAFQAIAEAEAJQAFAJAAALIAAADIgCABIgyAAIgBAAIAAACQAAAGACAEQADAFAFADQAFACAEAAQAGAAAFgCQAFgDAEgFIABgBIABABIAJAEQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgFAGgFAEQgFAEgGACQgFABgIAAQgKAAgIgFgAgHgYQgFADgCAFQgCAEAAAGIAgAAIACAAIABgCQAAgEgCgFQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_14.setTransform(-40.475,7.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUAnIgCgBIAAgCIAAhFQAAgBAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAJIAAABIABgBIAGgHQAEgDAEgBIAHgCQAFAAAAADIAAANQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgEgBIgFAAIgFABIgGAEIgDAEIgCAFIAAArQAAAAAAABQAAAAgBABQAAAAgBAAQAAABgBAAg");
	this.shape_15.setTransform(-46.925,6.95);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgRAiQgJgFgFgIQgFgJAAgLQAAgLAFgJQAFgJAJgFQAJgFAJAAQALAAAIAFQAIAEAEAJQAFAJAAALIAAADIgCABIgyAAIgBAAIAAACQAAAGACAEQADAFAFADQAFACAEAAQAGAAAFgCQAFgDAEgFIABgBIABABIAJAEQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgFAGgFAEQgFAEgGACQgFABgIAAQgKAAgIgFgAgHgYQgFADgCAFQgCAEAAAGIAgAAIACAAIABgCQAAgEgCgFQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_16.setTransform(-54.625,7.025);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAHAzQgIgBgFgEQgFgEgBgJIAAgqQAAAAAAgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgKAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgJQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIACgVQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAVQAAABABAAQAAAAAAABQAAAAAAAAQABAAAAAAIAQAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAJQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIgRAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAAAIAAAlQAAAGADACQACACAEABIAJAAIABAAIABACIAAAHQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBABIgFAAIgGABg");
	this.shape_17.setTransform(-60.65,5.75);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AARAnIgBgBIgBgCIAAgwQAAgFgDgEQgDgDgGAAIgFABIgGADIgGAGIAAAyQAAAAAAABQgBAAAAABQgBAAAAAAQgBABgBAAIgMAAQgBgBAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhFQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAIIABABIABgBIAIgGIAHgEQAEgCAFAAQAKABAGAFQAHAHAAAKIAAAzQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAg");
	this.shape_18.setTransform(-67.975,6.95);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgHA1IgCgBIAAgCIAAhjQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAQAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAABjIgBACIgCABg");
	this.shape_19.setTransform(-74.75,5.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgTAiQgIgFgFgJQgFgIAAgMQAAgKAFgJQAFgJAJgFQAIgFAKAAQALAAAJAFQAIAFAFAJQAFAJAAAKQAAAMgFAIQgFAJgIAFQgJAFgLAAQgKAAgJgFgAgJgXQgEADgDAGQgCAGAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDADgGQACgFAAgJQAAgIgDgGQgCgGgEgDQgEgDgGAAQgFAAgEADg");
	this.shape_20.setTransform(-86.075,7.025);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAcA1IgBAAIgCgCIgwhEIgBAAIAAABIAABCQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgMAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhjQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAPAAIACABIABABIAtBBQAAAAABABQAAAAAAAAQAAAAAAAAQAAAAABAAIAAgBIAAhAQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIANAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAABlIgBABIgCABg");
	this.shape_21.setTransform(-95.975,5.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgIAVIgCgBIAAgBIAHgQQABgBAAgBQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIAAgQQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAPIgBACIgLAUIgCACIgDAAg");
	this.shape_22.setTransform(102.0625,-5.975);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgTAjQgJgFgEgHIAAgBIABgCIAIgEIACAAIABAAIAFAGIAHAEQAEABAFAAIAIgBQADgBACgCQADgDAAgDQAAgCgDgCQgCgDgGgBIgOgEQgLgCgFgEQgFgFAAgIQAAgHAEgGQAEgFAHgDQAHgDAIAAQALAAAHAEQAIADAEAGIAAACQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgJAFIgCAAIgBgBQgDgEgEgCQgFgDgGAAQgFAAgEADQgEACAAAFIABAEQACACAGABIAQAFQALADAFAEQAEAGAAAIQAAAHgEAFQgEAGgHACQgIADgJAAQgMAAgIgEg");
	this.shape_23.setTransform(96.125,-9.775);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAHAyQgIABgFgFQgFgEAAgKIAAgpQgBgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgJAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgJQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIACgXQAAAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIAMAAQAAAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAXQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIAQAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgRAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAAAlQAAAFACADQACACAFAAIAJAAIABAAIABABIAAAIQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgFABIgFAAg");
	this.shape_24.setTransform(89.9,-11.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AARAmIgBAAIgBgCIAAgwQAAgFgDgDQgDgEgGAAIgFABIgGAEIgGAFIAAAxQAAABAAABQgBAAAAABQgBAAAAAAQgBAAgBAAIgMAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhGQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAHIABABIABAAIAIgGIAHgEQAEgCAFABQAKAAAGAFQAHAGAAAKIAAAzQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_25.setTransform(82.575,-9.85);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgRAiQgJgFgFgIQgFgJAAgLQAAgLAFgJQAFgJAJgFQAJgFAJAAQALAAAIAFQAIAEAEAJQAFAJAAALIAAADIgCABIgyAAIgBAAIAAACQAAAGACAEQADAFAFADQAFACAEAAQAGAAAFgCQAFgDAEgFIABgBIABABIAJAEQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQgFAGgFAEQgFAEgGACQgFABgIAAQgKAAgIgFgAgHgYQgFADgCAFQgCAEAAAGIAgAAIACAAIABgCQAAgEgCgFQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_26.setTransform(73.775,-9.775);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAoAmIgBAAIgBgCIAAgwQAAgFgCgDQgDgEgGAAQgDAAgDABIgGAEIgEADIgBACIAAADIAAAuQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBAAIgMAAIgBAAIgBgCIAAgwQAAgFgDgDQgCgEgHAAQgEAAgEADQgEACgFAFIAAAxQAAABAAABQAAAAgBABQAAAAgBAAQgBAAAAAAIgNAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAhGQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIANAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAHIABABIABAAIAIgGIAIgEQAEgCAEABQAIgBAFAEQAEAEACAFIACABIABgBIAIgHIAIgEIAJgBQAKAAAGAFQAFAHABAKIAAAyQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAg");
	this.shape_27.setTransform(63.55,-9.85);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgeAxQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgJIABgCIADAAIAJAAQADAAADgBIADgFIACgEQABgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAgBIgbhCIAAgCIACgCIAPAAIABABIACACIARAuQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIABgBIARguIACgCIABgBIAKAAIACACIAAACIgeBJQgDAHgDAEQgCAEgDACQgDADgFAAIgKABg");
	this.shape_28.setTransform(53,-8.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgaAhQgHgFAAgKQAAgHAFgGQAFgFAJgDQAJgEAMAAIAHgBIABAAIABgCIAAgDQAAgGgEgEQgEgDgGAAQgEAAgEACQgFACgDAFIgBABIgCAAIgMgDIgBgBIABgCQAEgIAIgEQAIgEAMAAQALAAAGADQAHADADAFQAEAFAAAIIAAAxIgBACIgCABIgMAAIgCgBIgBgDIAAgEQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBABQgEAEgGADQgFACgHAAQgLAAgGgGgAAIABIgIACIgHACQgEACgBADQgCADAAADQAAAFADADQAEADAGAAQADAAADgCQADgBACgCIAEgEQABgBAAAAQAAgBAAAAQABgBAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBAAAAAAg");
	this.shape_29.setTransform(44.125,-9.775);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgmA1IgCAAIAAgCIAAhlQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAnAAQAMAAAKADQAIAEAGAHQAFAIABALQAAAKgGAHQgEAGgJAEQgIADgMAAIgVAAQAAAAgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAIAAAmQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAgAgUgjIAAAdQAAABABABQAAAAAAAAQAAABAAAAQABAAAAAAIASAAQAKAAAFgFQAFgDAAgJQAAgGgDgDQgCgEgFgCQgEgCgGABIgRAAQgBAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAg");
	this.shape_30.setTransform(35.45,-11.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgTAiQgIgFgFgJQgFgIAAgMQAAgKAFgJQAFgJAJgFQAIgFAKAAQALAAAJAFQAIAFAFAJQAFAJAAAKQAAAMgFAIQgFAJgIAFQgJAFgLAAQgKAAgJgFgAgJgXQgEADgDAGQgCAGAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDADgGQACgFAAgJQAAgIgDgGQgCgGgEgDQgEgDgGAAQgFAAgEADg");
	this.shape_31.setTransform(21.025,-9.775);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAcA1IgBAAIgCgBIgwhFIgBAAIAAAAIAABEQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgMAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhlQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAPAAIACAAIABACIAtBBQAAAAABABQAAAAAAAAQAAAAAAAAQAAAAABAAIAAgBIAAhBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIANAAQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAAAIAABlIgBACIgCAAg");
	this.shape_32.setTransform(11.125,-11.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgHA1QgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg7IgBAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgJIAAgCIACgBIAKAAQABAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAgBIAAgJQABgJAFgFQAEgFAJAAIAOAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAAIIAAABIgCABIgIAAQgEAAgBADQgDACAAAEIAAAHQAAAAABABQAAAAAAAAQAAAAAAAAQABAAAAAAIAOAAIABABIAAACIAAAJQAAAAAAAAQAAABAAAAQAAAAgBAAQAAABAAAAIgNAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAABAAAAIAAA6QAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_33.setTransform(-0.9,-11.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgTAiQgIgFgFgJQgFgIAAgMQAAgKAFgJQAFgJAJgFQAIgFAKAAQALAAAJAFQAIAFAFAJQAFAJAAAKQAAAMgFAIQgFAJgIAFQgJAFgLAAQgKAAgJgFgAgJgXQgEADgDAGQgCAGAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDADgGQACgFAAgJQAAgIgDgGQgCgGgEgDQgEgDgGAAQgFAAgEADg");
	this.shape_34.setTransform(-8.125,-9.775);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgTAjQgJgFgEgHIAAgBIABgCIAIgEIACAAIABAAIAFAGIAHAEQAEABAFAAIAIgBQADgBACgCQADgDAAgDQAAgCgDgCQgCgDgGgBIgOgEQgLgCgFgEQgFgFAAgIQAAgHAEgGQAEgFAHgDQAHgDAIAAQALAAAHAEQAIADAEAGIAAACQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgJAFIgCAAIgBgBQgDgEgEgCQgFgDgGAAQgFAAgEADQgEACAAAFIABAEQACACAGABIAQAFQALADAFAEQAEAGAAAIQAAAHgEAFQgEAGgHACQgIADgJAAQgMAAgIgEg");
	this.shape_35.setTransform(-21.425,-9.775);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AARA1IgBAAIgBgCIAAgyQAAgEgDgDQgDgEgGABQgDgBgCACIgGADIgGAFIAAAyQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAIgNAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhlQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAlIABACIABgBIAJgGIAHgEIAIgBQALAAAGAGQAGAGAAALIAAAyQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_36.setTransform(-29.475,-11.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAHAyQgIABgFgFQgFgEgBgKIAAgpQAAgBAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgKAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgJQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIACgXQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIALAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAXQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIAQAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgRAAQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAAAlQAAAFADADQACACAEAAIAJAAIABAAIABABIAAAIQAAAAAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgFABIgGAAg");
	this.shape_37.setTransform(-36.35,-11.05);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AARAmIgBAAIgBgCIAAgwQAAgFgDgDQgDgEgGAAIgFABIgGAEIgGAFIAAAxQAAABAAABQgBAAAAABQgBAAAAAAQgBAAgBAAIgMAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhGQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAHIABABIABAAIAIgGIAHgEQAEgCAFABQAKAAAGAFQAHAGAAAKIAAAzQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_38.setTransform(-43.675,-9.85);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgTAiQgIgFgFgJQgFgIAAgMQAAgKAFgJQAFgJAJgFQAIgFAKAAQALAAAJAFQAIAFAFAJQAFAJAAAKQAAAMgFAIQgFAJgIAFQgJAFgLAAQgKAAgJgFgAgJgXQgEADgDAGQgCAGAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDADgGQACgFAAgJQAAgIgDgGQgCgGgEgDQgEgDgGAAQgFAAgEADg");
	this.shape_39.setTransform(-52.325,-9.775);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAlA1IgCAAIgBgCIAAhKIAAgBIgBABIgbBKQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAAAAAIgJAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIgbhJIgBgBIAAABIAABJIgBACIgCAAIgMAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhkQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAYAAIACAAIABACIAZBDIAAABIABgBIAYhCQABgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAIAZAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAABkQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_40.setTransform(-62.575,-11.3);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgiA1IgDAAIgBgCIAAgKIAAgBIADgCIADgEIAcgaIAJgJIAHgIIAEgGIABgGQAAgFgDgEQgCgEgEgCQgEgBgEAAQgEAAgDABQgEABgEAEQgDADgEAGIgBABIgCgBIgLgGIgCgCIABgBQAIgMAJgFQAKgEALgBQAKAAAJAEQAHAEAFAGQAGAIAAAKQAAAFgCAGIgHAKQgFAFgIAHIgbAWIAAABIABABIAuAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIAAANIgBACIgCAAg");
	this.shape_41.setTransform(-78.2,-11.35);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgaA1QgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgMQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAQAAIABgBIAAhBQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgQAFQAAABgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgJIAAgBIACgCIAWgMIADgBIACAAIAJAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABWIABABIAPAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAMIAAACIgCAAg");
	this.shape_42.setTransform(-87.8,-11.3);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgDAhQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgXIgYAAIgCgBIgBgBIAAgIQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAZAAIAAANIAAgNIAAgYIABgCIABAAIAIAAQABAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAZIgNAAIANAAIAAANIgNAAIANAAIAAAZQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAgAAHAHIAAgNIAYAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAgAAHAHg");
	this.shape_43.setTransform(-101.05,-11.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-19.6,240.1,36.3);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape.setTransform(68.125,-1.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgSAmQgJgFgGgKQgFgKAAgNQAAgMAFgJQAGgLAJgFQAKgGALAAQAJAAAHAEQAHADAFAFQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAABgBAAQAAAAAAgBQAAAAgBAAQAAAAAAgBIgEgGIgFgEQgDgCgEAAQgGAAgFADQgFAEgCAGQgDAIAAAIQAAAKADAHQADAGAFAEQAFADAGAAQAHAAAEgDQAFgEAEgHIABAAIACAAIAKACQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAHQgFAEgGACQgGACgHAAQgLAAgKgGg");
	this.shape_1.setTransform(60.7313,0.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgGgJQgFgKAAgNQAAgMAFgLQAGgKAJgFQAKgGALAAQAMAAAJAGQAJAFAFAJQAFAKAAANIAAADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAACQAAAGADAFQADAFAGAEQAFACAFAAQAHAAAFgCQAGgDAEgGIACgBIABABIAKAEQAAAAABABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAHgGAEQgFAFgHACQgHABgIAAQgLAAgKgGgAgJgbQgFAEgCAFQgDAFAAAGIAlAAIACAAIABgCQAAgFgCgFQgDgFgEgDQgEgDgHAAQgFAAgFADg");
	this.shape_2.setTransform(51.525,0.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgQBIQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgLIAAgBIACgBIAHgBQAEAAACgDQABgCABgFIAAhRQAAgBAAgBQAAAAAAgBQAAAAABAAQAAAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAABTQABANgHAGQgGAHgOAAgAAAgyQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgQQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAQAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAPQAAAEgEAAg");
	this.shape_3.setTransform(43.9,-0.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVAmQgJgFgGgKQgFgKAAgNQAAgMAGgJQAFgLAJgFQAKgGALAAQAMAAAKAGQAJAGAGAKQAFAJAAAMQAAANgFAKQgGAKgJAFQgKAGgMAAQgMAAgJgGgAgLgaQgEAEgCAGQgDAIAAAIQAAAJADAIQACAGAEAEQAGADAFAAQAHAAAFgDQAEgEADgGQACgIAAgJQAAgIgCgIQgDgGgEgEQgFgDgHAAQgFAAgGADg");
	this.shape_4.setTransform(38,0.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgWArIgCAAIgBgDIAAhOQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAQAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAKIAAABQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQADgFAEgDIAIgEQAFgCADAAQAGAAAAACIAAAQQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgFgBIgFAAIgGABIgGADIgFAGQgBACAAADIAAAwQAAADgEAAg");
	this.shape_5.setTransform(30.9,-0.025);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AglA4QAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhpIAAgCIADgBIAPAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAAAGIAAABIACgBIAFgFQADgCAFgBQADgCAHAAQAJAAAIAEQAHAFAFAKQAEAJAAAOQAAAPgEAJQgFALgIAFQgHAEgLAAQgFAAgGgCQgFgCgEgDIgDgCIAAADIAAAdQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAgAgKgoQgEADgCADQgCADAAAEIAAAkQADAEAFADQAEACAFAAQAFAAAFgDQAFgEADgHQACgFAAgMQAAgKgCgHQgDgGgFgDQgFgDgEAAQgGAAgEACg");
	this.shape_6.setTransform(22.875,1.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgGgJQgFgKAAgNQAAgMAFgLQAGgKAJgFQAKgGALAAQAMAAAJAGQAJAFAFAJQAFAKAAANIAAADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAACQAAAGADAFQADAFAGAEQAFACAFAAQAHAAAFgCQAGgDAEgGIACgBIABABIAKAEQAAAAABABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAHgGAEQgFAFgHACQgHABgIAAQgLAAgKgGgAgJgbQgFAEgCAFQgDAFAAAGIAlAAIACAAIABgCQAAgFgCgFQgDgFgEgDQgEgDgHAAQgFAAgFADg");
	this.shape_7.setTransform(8.125,0.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgWArIgCAAIgBgDIAAhOQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAQAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAKIAAABQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQADgFAEgDIAIgEQAFgCAEAAQAFAAAAACIAAAQQAAAAAAABQAAAAgBABQAAAAAAAAQAAAAgBAAIgFgBIgFAAIgGABIgGADIgFAGQgBACAAADIAAAwQAAADgEAAg");
	this.shape_8.setTransform(1.1,-0.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgGA7IgDAAIgBgDIAAhOQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABOQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAgBAAIgDABgAgGglIgDAAIgBgDIAAgPQAAgBABgBQAAAAAAgBQAAAAABAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAQQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_9.setTransform(-4.6,-1.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape_10.setTransform(-9.275,-1.375);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_11.setTransform(-17.225,-0.025);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgUAmQgJgFgGgJQgFgKAAgNQAAgMAFgLQAGgKAJgFQAKgGALAAQAMAAAJAGQAJAFAFAJQAFAKAAANIAAADQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAACQAAAGADAFQADAFAGAEQAFACAFAAQAHAAAFgCQAGgDAEgGIACgBIABABIAKAEQAAAAABABQAAAAAAAAQAAABAAAAQAAAAgBABQgEAHgGAEQgFAFgHACQgHABgIAAQgLAAgKgGgAgJgbQgFAEgCAFQgDAFAAAGIAlAAIACAAIABgCQAAgFgCgFQgDgFgEgDQgEgDgHAAQgFAAgFADg");
	this.shape_12.setTransform(-26.725,0.05);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgWArIgDAAIAAgDIAAhOQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAQAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAAKIAAABQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQADgFAEgDIAIgEQAEgCAEAAQAGAAAAACIAAAQQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgFgBIgFAAIgGABIgHADIgDAGQgCACAAADIAAAwQAAADgEAAg");
	this.shape_13.setTransform(-38.75,-0.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgYAoQgGgDgDgFQgEgGAAgIIAAg5QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAOAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAAA2QgBAGAEADQAEAEAFAAQAFAAAFgDQAFgDAEgFIAAg4QABgDAEAAIAOAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAABIAABOQAAABgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIgPAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgCAAQgHAHgGADQgHADgHAAQgHAAgFgDg");
	this.shape_14.setTransform(-47.15,0.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVAmQgJgFgGgKQgFgKAAgNQAAgMAFgJQAGgLAKgFQAJgGALAAQANAAAJAGQAJAGAGAKQAFAJAAAMQAAANgGAKQgEAKgKAFQgJAGgNAAQgLAAgKgGgAgLgaQgEAEgDAGQgCAIAAAIQAAAJACAIQADAGAEAEQAFADAGAAQAHAAAFgDQAEgEACgGQADgIAAgJQAAgIgDgIQgCgGgEgEQgGgDgGAAQgGAAgFADg");
	this.shape_15.setTransform(-56.45,0.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgiA3QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgKIABgCIAEgBIAKAAQADAAADgBIAEgFIADgFIgBgFIgfhLQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAQAAIACABIACACIATA0IABABIABgBIAUg0IABgCIACgBIAMAAIACACIAAACIgiBTIgGAMQgDAFgEACQgEADgFABIgLABg");
	this.shape_16.setTransform(-65.4208,1.375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.9,-10,143.9,20);


(lib.Promo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B0FBC6").s().p("AgcDJQgKAAAAgKIAAg8QAAgJAGAAIBAAAQAHAAAAAIIAAA7QAAAMgNAAgAgMBVQgGAAgCgCIgCgHIgSkLIACgGIAFgDIBCAAQAIABgBAHIgREKQAAAGgDADQgDACgGAAg");
	this.shape.setTransform(57.4016,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#B0FBC6").s().p("AhFCCQgggTgTggQgSghAAgqQAAgvATghQATgjAggSQAhgTAmAAQApABAeARQAfASARAhQARAiAAAuIgBAJQAAADgHABIi+AAIgFABIgBAHQAAAWAKASQAKARASAKQASAKAVAAQAWAAASgJQASgJAQgVIAEgCIAGABIAhAPQAHADgGAHQgQAYgTAOQgSAOgXAGQgWAGgcABQgoAAghgTgAgfhdQgRALgIARQgIASAAAWIB+AAIAHgCIACgGQAAgRgIgQQgHgQgPgLQgPgKgUAAQgVAAgQAKg");
	this.shape_1.setTransform(36.375,5.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B0FBC6").s().p("AgXDJQgLAAAAgKIABl9QAAgKAIAAIA1AAQAHABAAAIIAAF8QAAAGgCADQgDACgHABg");
	this.shape_2.setTransform(15.425,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#B0FBC6").s().p("AhnB/QgXgWAAgkQAAgdASgWQARgVAigMQAigMAwgDIAagBIAGgCQADgCAAgEIAAgNQAAgYgOgNQgOgOgZAAQgSABgQAIQgQAJgMASIgFAFIgGAAIgugMIgDgDIABgIQAPgfAggQQAfgQAuAAQApAAAaALQAaAMAMAVQAMATAAAcIAAC9IgCAIQgCADgFAAIguAAQgFAAgCgDIgDgKIgBgRQgBgIgKAIQgRARgWAJQgVAJgcABQgpgBgYgVgAA0AEIgWABQgSABgPAEQgQAEgMAHQgMAGgHALQgHAJAAAOQAAASANALQANALAXAAQAOAAAMgFQAMgFAKgHIAOgQQAGgJAAgJIAAgmQAAgJgGAAIgCABg");
	this.shape_3.setTransform(-7.325,5.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#B0FBC6").s().p("Ag/DGQgegJgYgPQgXgQgPgWQgCgEABgDIAFgHIAigYQAGgDAEAAIAGAEQANARAOALQANALARAGQARAFAZAAQAlAAAXgNQAWgMAAgbQAAgLgEgJQgFgJgKgHQgLgIgUgHIhQgZQgggJgUgQQgUgQgKgWQgLgVAAgYQAAgiATgbQASgaAhgQQAigPAsAAQAdAAAaAHQAZAHAVAMQAVAMANASIAEAFQABAEgFADIgmAdIgFABIgHgFQgNgOgTgLQgTgLghAAQgjAAgTAOQgTAOAAAYQAAAHAEAJQADAJALAIQAKAIAUAHIBTAZQAxAOAWAcQAWAdAAAmQAAAlgTAbQgTAbgiAOQgjAPgwAAQgiAAgfgIg");
	this.shape_4.setTransform(-39.6393,0.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#B0FBC6").s().p("AgyBSQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgBgDIAAibQAAgEAEAAIBnAAQABAAABAAQAAABABAAQAAABAAAAQABABAAABIAAARQgBAEgEAAIhGAAQAAAAgBAAQgBAAAAAAQgBABAAAAQAAABAAABIAAApQAAABAAAAQAAABABAAQAAABABAAQAAAAABAAIAzAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgzAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAABAAAAIAAA+QAAAEgFAAg");
	this.shape_5.setTransform(175.4,13.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#B0FBC6").s().p("AgyBSQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgBgDIAAibQAAgEADAAIBoAAQAAAAABAAQAAABABAAQAAABAAAAQABABAAABIAAARQAAAEgFAAIhFAAQgBAAgBAAQgBAAAAAAQgBABAAAAQAAABAAABIAAApQAAABAAAAQAAABABAAQAAABABAAQAAAAABAAIAyAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAARQAAAAgBABQAAAAAAABQgBAAAAAAQgBAAgBAAIgyAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAABAAAAIAAA+QAAAEgFAAg");
	this.shape_6.setTransform(161.3,13.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#B0FBC6").s().p("AgmBKQgRgKgIgTQgJgSAAgaQAAgaAJgTQAJgSAQgLQARgKAVAAQAXAAAQAKQAQALAJASQAJATAAAaQAAAagIASQgJATgRAKQgQAKgXAAQgVAAgRgKgAgdgtQgJAPAAAfQAAAfAJAOQAKAPATAAQAUAAAKgPQAJgOAAgfQAAgfgJgPQgKgPgUAAQgTAAgKAPg");
	this.shape_7.setTransform(144.725,13.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#B0FBC6").s().p("AAqBlQgMgHgHgOQgHgOAAgRQAAgSAHgNQAHgOAMgHQAMgIAPAAQAPAAALAIQAMAHAHAOQAHANAAASQAAARgHAOQgHAOgMAHQgLAIgPAAQgPAAgMgIgAA3ANQgFAFgDAJQgDAKAAAMQAAAMADAKQACAJAGAFQAFAFAIAAQAIAAAGgFQAFgFADgJQADgKAAgMQAAgMgDgKQgDgJgFgFQgGgFgIAAQgIAAgFAFgAhKBrQgBAAgBAAQAAAAgBAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABgBICIjNIACgCIAEAAIANAAIACABQABAAAAAAQAAAAAAABQAAAAgBABQAAAAAAABIiJDQQgCACgFAAgAheAEQgMgHgHgNQgHgOAAgRQAAgSAHgOQAHgNAMgIQAMgIAPAAQAPAAALAIQAMAIAHANQAHAOAAASQAAARgHAOQgHANgLAHQgMAIgPAAQgPAAgMgIgAhRhTQgFAFgDAJQgDAJAAANQAAAMADAJQACAJAGAFQAGAFAHAAQANAAAGgLQAGgLAAgSQAAgTgGgLQgGgMgNAAQgHAAgGAGg");
	this.shape_8.setTransform(154.125,-8.775);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#B0FBC6").s().p("AhPC1QglgYgUgsQgUgsAAg9QAAhBAVgwQAWgvAmgaQAngaAzAAQAYAAAUAHQAUAGAPAKQAPAJALAMQALALAEALIABAGQAAAEgEABIgxARQgEABgDgCIgDgEQgKgOgNgJQgNgJgWAAQgeAAgUAPQgVAPgKAbQgKAaAAAiIABAMQACACAHgDIAogPQAUgHAbAAQAqAAAeAPQAeAPARAZQARAbAAAjQAAAlgUAeQgUAdgiARQgiAQgqAAQgxAAglgYgAgTAOIgbAIIgVAKIgHAHIgBANQAAASAFARQAFASAKAOQAKAPAPAJQAPAIAUAAQAVAAAQgJQARgKAKgQQAJgRAAgVQAAgUgJgPQgJgPgQgIQgQgJgWAAg");
	this.shape_9.setTransform(117.025,-0.125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#B0FBC6").s().p("AiFDLIgJgCQgDgCABgHIAAgjIABgGIAGgIIAOgNIBphjIAoglIAZgdQAJgNAFgLQADgMAAgNQAAgTgJgNQgJgNgQgHQgPgHgQAAQgPAAgOAGQgPAFgOAMQgOAMgLAVQgCADgEAAIgIgCIgogVQgFgCAAgFQgBgEADgEQAbgpAkgTQAmgUArAAQAoAAAfAOQAfAOATAaQASAbAAAlQAAAXgIAUQgIAUgSAVQgRATgeAZIhmBXIgDAEQABACAFAAICuAAQAKAAgBAIIAAAxIgCAGQgCADgFAAg");
	this.shape_10.setTransform(84.65,-0.375);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag0BaQgEgBgBgCIAAgKQAAgBABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIAGgBIARAAQAFAAAFgEQAFgDADgGQADgGABgGQABgFgCgFIgyh7IABgDQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIARAAIACAAIABACIAmBkQAAABABAAQAAABAAAAQAAAAABABQAAAAABAAQAAAAAAAAQAAgBABAAQAAgBAAAAQABgBAAgBIAmhjIABgCIADAAIAMAAIACABQABAAAAAAQAAABAAAAQAAAAAAABQAAAAgBAAIg5CRQgEAKgDAGQgEAGgGADQgFADgHACQgHABgIAAg");
	this.shape_11.setTransform(154.8,-38.275);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AggBGIgCgBIgCgCIAAiCQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIAOAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAAARIAAACIACgBQAHgIAGgFQAGgFAHgDQAGgCAIAAQAIAAABADIAAAQQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgFgBIgGAAQgGAAgGADQgHACgFAFQgGAEgDAFQgDAGAAAFIAABVQAAAEgFAAg");
	this.shape_12.setTransform(144.9,-40.575);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgsA+QgMgLAAgRQAAgOAIgKQAIgKAPgFQAPgGAVgBIAVgCIADgBIABgCIAAgIQAAgOgJgHQgIgJgPAAQgKAAgKAFQgJAGgHAKIgCABIgCAAIgOgEIgBgBIAAgEQAIgNAOgHQAOgJAUAAQARABAMAFQALAGAGAJQAGALAAANIAABbIgBADIgCABIgOAAIgCgBIgBgDIgBgMQAAgEgDAEQgKAJgLAEQgMAGgMAAQgVAAgLgKgAAgAAIgRAAQgMABgIACQgKADgGADQgHAEgDAGQgDAFAAAIQAAAKAIAHQAIAGANAAQAHAAAIgCQAIgDAGgFQAFgFAEgFQADgFAAgFIAAgWQAAgBAAgBQgBgBAAAAQAAAAgBAAQAAAAgBAAIgBAAg");
	this.shape_13.setTransform(131.475,-40.45);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgiA/QgPgIgHgMIAAgCIABgCIAKgGIADAAIABABQAFAGAFAFQAGAFAIADQAJADAKAAQAJAAAIgDQAJgDAEgFQAFgFAAgGQAAgIgGgFQgGgFgOgEIgZgHQgUgFgIgIQgIgJAAgMQAAgNAHgJQAHgJAMgFQAMgFAOgBQASABANAGQAOAHAHALIABACIgBABIgLAHIgCAAIgCgBQgFgIgKgFQgJgFgNAAQgNAAgJAGQgJAGAAAKQAAAFAEAFQAEAFANAEIAgAKQARAEAIAJQAIAKAAAMQAAAMgHAKQgHAJgNAEQgNAGgQAAQgTAAgQgJg");
	this.shape_14.setTransform(118.175,-40.45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AggBGIgDgBIgBgCIAAiCQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIAOAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAAARIAAACIACgBQAHgIAFgFQAHgFAHgDQAHgCAGAAQAJAAAAADIAAAQQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgFgBIgGAAQgGAAgGADQgHACgFAFQgGAEgDAFQgEAGABAFIAABVQAAAEgFAAg");
	this.shape_15.setTransform(108.8,-40.575);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgfA/QgPgJgJgQQgIgQAAgVQAAgVAIgQQAJgRAPgJQAPgJARAAQATAAAOAJQAPAIAHAQQAIAQAAAWIAAADQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAgBAAIhiAAIgCABIgBACQAAANAHALQAGALAKAFQAKAHAMAAQANAAAKgFQAKgGAHgKIACgCIACABIALAFQAAAAABABQAAAAAAABQAAAAAAABQAAAAgBABQgHAKgIAHQgIAGgLAEQgKACgNABQgSgBgPgIgAgVgwQgJAHgFAKQgFALAAALIBOAAIAEAAIAAgDQAAgMgEgJQgFgKgJgGQgJgGgNAAQgNAAgKAHg");
	this.shape_16.setTransform(96.325,-40.45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgEBFQgFAAgBgEIg1iBIAAgDIADgBIAQAAIADABIABACIAoBlQACAFACgFIAphlIABgCIADgBIAMAAIACABQABABAAAAQAAAAAAAAQAAABAAAAQAAAAgBABIg0CBQgCAEgEAAg");
	this.shape_17.setTransform(82.825,-40.425);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgGBgIgDgBIgBgCIAAiCQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAPAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAACBIgBADIgEABgAgHhBIgDgBIgBgDIAAgXQAAgDAEAAIAPAAQAEAAAAADIAAAWQAAAFgFAAg");
	this.shape_18.setTransform(73.075,-43.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAmBGIgCgBIgBgCIAAhcQAAgNgHgHQgGgHgOAAQgIAAgFADQgHACgHAFIgPALIAABhQAAAEgEAAIgOAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAiCQAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQABAAAAAAQAAABABAAQAAABAAAAIAAAPIAAACIACgBIAQgLQAHgFAIgDQAHgCAJAAQAUAAALALQALALAAARIAABgQAAAEgEAAg");
	this.shape_19.setTransform(63.175,-40.575);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAmBGIgCgBIgBgCIAAhcQAAgNgHgHQgGgHgOAAQgIAAgFADQgHACgHAFIgPALIAABhQAAAEgEAAIgOAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAiCQAAgBAAgBQABAAAAgBQAAAAABAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAPIAAACIACgBIAQgLQAHgFAIgDQAHgCAJAAQAUAAALALQALALAAARIAABgQAAAEgEAAg");
	this.shape_20.setTransform(48.725,-40.575);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AA+BgQgEABgBgDIgSgzIgBgBIgCgBIhKAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAAAAAIgTAzIgBACIgDAAIgPAAIgDgBIAAgDIBEi4IABgCIAEgBIATAAQAFAAABADIBDC4IgBADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAgAgChDIggBWQAAABAAAAQAAABAAAAQAAAAABAAQAAABABAAIA+AAQAAAAABgBQAAAAABAAQAAgBAAAAQAAgBAAAAIgghWIgBgBg");
	this.shape_21.setTransform(33.225,-43.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgfA/QgPgJgJgQQgIgQAAgVQAAgVAIgQQAJgRAPgJQAPgJARAAQATAAAOAJQAPAIAHAQQAIAQAAAWIAAADQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAgBAAIhiAAIgCABIgBACQAAANAHALQAGALAKAFQAKAHAMAAQANAAAKgFQAKgGAHgKIACgCIACABIALAFQAAAAABABQAAAAAAABQAAAAAAABQAAAAgBABQgHAKgIAHQgIAGgLAEQgKACgNABQgSgBgPgIgAgVgwQgJAHgFAKQgFALAAALIBOAAIAEAAIAAgDQAAgMgEgJQgFgKgJgGQgJgGgNAAQgNAAgKAHg");
	this.shape_22.setTransform(9.725,-40.45);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAmBGIgCgBIgBgCIAAhcQAAgNgHgHQgGgHgOAAQgIAAgFADQgHACgHAFIgPALIAABhQAAAEgEAAIgOAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAiCQAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAPIAAACIACgBIAQgLQAHgFAIgDQAHgCAJAAQAUAAALALQALALAAARIAABgQAAAEgEAAg");
	this.shape_23.setTransform(-4.675,-40.575);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgjBBQgJgEgGgKQgFgJgBgMIAAhfQAAgEAFAAIAOAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAIAABaQAAAOAGAHQAIAIANAAQAJAAALgGQAKgGAKgLIAAhgQAAgDAFAAIANAAQAFAAAAADIgBCCQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgPAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgQIgBgBIgCAAQgOANgLAEQgKAFgKAAQgMAAgKgFg");
	this.shape_24.setTransform(-19.35,-40.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgVBgIgLgEIgDgBIgBgDIADgPQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAABAAIAJADQAEACAIAAQALAAAFgGQAFgGAAgRIAAiMQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIATAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIAACSQAAAWgKALQgJAMgVAAQgLAAgHgCg");
	this.shape_25.setTransform(-32.05,-43.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.8,-55.5,247.3,90.1);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.line = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#B1FBC6").ss(1,1,1).p("AzZAAMAmzAAA");
	this.shape.setTransform(60,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.2,-1,250.39999999999998,2);


(lib.Img_05_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_05();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.img_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#013229").s().p("ADnA3QgKgGgFgJQgGgJAAgNQAAgNAGgJQAFgLAKgFQAKgGALAAQANAAAIAGQAKAFAFAKQAFAIAAAPIAAACQAAABAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIg2AAIgBABIAAACQAAAGADAEQADAEAEADQAFADAGAAQAGAAAEgDQAFgDAFgFIABgBIANAGQABAAAAAAQABAAAAABQAAAAgBABQAAAAgBABQgFAHgFAEQgFAEgIADQgGABgJAAQgMAAgJgFgAD0gJQgFADgCAEQgCAEAAAGIAgAAIACAAIABgCQAAgEgDgEQgBgDgEgDQgDgDgGAAQgFAAgEACgAgGA1QgMgHgHgOQgGgNAAgTQAAgRAGgOQAIgOAMgHQALgHAQAAQAQAAANAHQAMAHAGAOQAHAOAAARQAAATgHANQgGAOgMAHQgNAHgQAAQgRAAgLgHgAADgeQgFAKAAAUQAAAWAFAJQAGAKANAAQANAAAGgKQAGgJAAgWQAAgUgGgKQgGgKgNAAQgNAAgGAKgAjWA3QgKgGgFgJQgGgJAAgNQAAgNAGgJQAGgLAJgFQAKgGAMAAQAMAAAIAGQAKAFAGAKQAFAIAAAPIAAACIgDABIg2AAIgCABIAAACQAAAGADAEIAHAHQAFADAGAAQAGAAAEgDQAFgDAFgFIABgBIAOAGQAAAAABAAQAAAAAAABQAAAAAAABQgBAAAAABQgFAHgFAEQgGAEgHADQgHABgIAAQgNAAgJgFgAjJgJQgEADgDAEQgCAEAAAGIAgAAIACAAIABgCQAAgEgCgEQgCgDgDgDQgEgDgGAAQgFAAgEACgAlUA1QgMgHgGgOQgGgOAAgSQAAgRAGgOQAHgOAMgHQANgHAQAAQAMAAALAEQAKAFAGAIQAHAHABAJIAAAEIgCAAIgVAEIgBgBIgBgCQgBgFgDgEQgDgFgFgDQgFgCgGAAQgHAAgGAEQgGAEgDAJQgDAJAAAOQAAAPADAIQAEAKAGADQAFAFAIAAQAFAAAEgCQAEgBACgDQADgCACgEIADgGIAAgFQABAAAAgBQAAgBgBAAQAAAAAAgBQgBAAgBAAIgVAAIAAgCIAAgMQAAAAAAgBQAAAAAAAAQABAAAAAAQABAAAAAAIArAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIABACIAAA2IgBACIgBABIgFAAIgCgBIgCgCIgFgLIAAgBIgCABIgHAHQgEAEgGACQgHACgJAAQgQAAgMgHgAE5A7QAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgBgCIAAhNQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAABAAIASAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAIAAAKIAAABIACgBIAHgIIAJgEQADgCAFAAQAFAAAAADIAAASQAAAAAAABQAAABgBAAQAAAAAAAAQgBAAgBAAIgKgBIgGABQgEABgCACIgEAEIgCAFIAAAuQAAAEgEAAgACtA7QAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAg+QAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAIgLAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgMIABgBQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAAAQABAAAAgBQAAAAAAgBIAAgJQAAgKAGgGQAGgGALAAIAQAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIAAALIAAABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgIAAQgEAAgCADQgCADAAADIAAAHQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAIANAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIABABIAAAMQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAIgNAAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAA+QAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAgABxA7QAAAAgBAAQAAgBAAAAQAAAAgBgBQAAgBAAAAIAAg+QAAAAAAAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgMIABgBQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAABAAQAAAAAAgBQAAAAAAgBIAAgJQAAgKAGgGQAGgGALAAIAQAAQABAAABAAQAAABABAAQAAAAABABQAAAAAAABIAAALIgBABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgIAAQgEAAgCADQgCADAAADIAAAHQAAAAAAAAQAAABAAAAQABAAAAAAQABAAAAAAIANAAIACACIABABIAAAMQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAIgNAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAA+QAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAgAh3A2QgGgFAAgLIAAgrQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAAAgBAAIgJAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIAAgMQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIACgYQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIARAAQAAAAABAAQABABAAAAQAAAAABABQAAABAAAAIAAAYQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIARAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAIAAAMQAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAIgRAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAlQAAAGACACQADACAFAAIAJAAIACABIABACIgBAKQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIgTABQgLAAgGgFg");
	this.shape.setTransform(0.03,0.03,1.2,1.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C2F9CB").s().p("AnrC2QhMAAg1g2Qg1g1AAhLIAAAAQAAhLA1g1QA1g1BMAAIPXAAQBMAAA0A1QA2A2AABKIAAAAQAABLg2A1Qg1A2hLAAg");
	this.shape_1.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.4,-18.1,134.8,36.3);


// stage content:
(lib.WBAY_216348_MM_300X600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#010101").ss(1,1,1).p("EgMfgu3IY/AAMAAABdvI4/AAg");
	this.shape.setTransform(150,300,1.875,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(200));

	// logo
	this.instance = new lib.logo_1("synched",0);
	this.instance.setTransform(80,276);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:300,alpha:1},14,cjs.Ease.get(1)).wait(186));

	// mask_idn (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A3bPjIAA/FMAu3AAAIAAfFg");
	mask.setTransform(149.05,212.225);

	// Img_05_jpg
	this.instance_1 = new lib.Img_05_1("synched",0);
	this.instance_1.setTransform(80,300);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(153).to({_off:false},0).to({alpha:1},12,cjs.Ease.get(1)).wait(35));

	// Img_04_jpg
	this.instance_2 = new lib.Img_04_1("synched",0);
	this.instance_2.setTransform(80,300);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(119).to({_off:false},0).to({alpha:1},11,cjs.Ease.get(1)).wait(70));

	// Img_03_jpg
	this.instance_3 = new lib.Img_03_1("synched",0);
	this.instance_3.setTransform(80,300);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(89).to({_off:false},0).to({alpha:1},12,cjs.Ease.get(1)).wait(99));

	// Img_02_jpg
	this.instance_4 = new lib.img_02("synched",0);
	this.instance_4.setTransform(80,300);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(60).to({_off:false},0).to({alpha:1},11,cjs.Ease.get(1)).wait(129));

	// Img_01_jpg
	this.instance_5 = new lib.Img_01();

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(200));

	// line
	this.instance_6 = new lib.line("synched",0);
	this.instance_6.setTransform(150,465.25,1,1,0,0,0,60,0);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(24).to({_off:false},0).wait(176));

	// cta
	this.instance_7 = new lib.cta("synched",0);
	this.instance_7.setTransform(150,582.65);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(48).to({_off:false},0).to({y:543.65,alpha:1},12,cjs.Ease.get(1)).wait(140));

	// Promo
	this.instance_8 = new lib.Promo("synched",0);
	this.instance_8.setTransform(149.4,391.5,1,1,0,0,0,57.5,-5);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(12).to({_off:false},0).to({y:401.5,alpha:1},12,cjs.Ease.get(1)).wait(176));

	// T1
	this.instance_9 = new lib.T1("synched",0);
	this.instance_9.setTransform(150,457.35,1.2,1.2);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(24).to({_off:false},0).to({y:447.35,alpha:1},12,cjs.Ease.get(1)).wait(164));

	// T2
	this.instance_10 = new lib.T2("synched",0);
	this.instance_10.setTransform(150,487.45,1,1,0,0,0,0,-16.5);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(36).to({_off:false},0).to({y:477.45,alpha:1},12,cjs.Ease.get(1)).wait(152));

	// BG_jpg
	this.instance_11 = new lib.BG();

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(200));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,276,152,325);
// library properties:
lib.properties = {
	id: '123418CE7B7C4A9D9B329B13B057CF06',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"Img_05.jpg", id:"Img_05"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['123418CE7B7C4A9D9B329B13B057CF06'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;