(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Logo = function() {
	this.initialize(img.Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIAAgBIAAgmQAAgFgDgDQgDgDgGAAIgEABIgGADIgHAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAGgFIAHgDIAGgBQAJAAAEAFQAFAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAg");
	this.shape.setTransform(42.25,13.875);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAQAdQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgNgoIgBgBIAAABIgMAoIgBABIgBAAIgGAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgRg2IAAgCIABAAIAGAAIACAAIAAABIANAqIABABIABgBIANgqIABgBIAAAAIAFAAIABAAIAAABIAOAqIABABIAAgBIANgqIABgBIABAAIAEAAIABAAIAAACIgQA2IgBABIgCAAg");
	this.shape_1.setTransform(34.025,13.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_2.setTransform(25.775,13.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgcApQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAhNIABgBIABgBIAEAAIAFAAIAEAAIAEAAQAOAAAKAFQAJAFAEAIQAFAJAAANQAAANgFAJQgFAKgKAEQgJAFgOAAgAgTgeIAAA+QAAAAAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIAEAAQANAAAGgDQAIgEADgHQAEgHAAgMQAAgMgEgHQgDgHgIgDQgGgDgMAAIgFAAQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABg");
	this.shape_3.setTransform(18.15,12.775);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWAmIgBgBIAAgEIAAgBIADgBIAHAAQAAAAABAAQABAAAAAAQABAAAAgBQABAAAAAAIADgEIACgFQABgBAAAAQAAgBgBgBQAAAAAAgBQAAAAAAgBIgVgzIAAgBIABgBIAHAAIABAAIABABIAPAqIABABIABgBIAQgqIABgBIABAAIAFAAIABAAIAAACIgYA8IgDAHIgEAEIgFACIgHAAg");
	this.shape_4.setTransform(7.5625,14.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNAbQgGgEgEgHQgDgHAAgIQAAgJAEgHQADgHAGgDQAHgEAHAAQAIAAAGADQAGAEADAHQADAGAAAJIAAABQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAIgpAAIAAABIgBABQAAAFADAFQADAEAEADQAEACAFAAQAFAAAEgCQAFgCADgFIABAAIAAAAIAFACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAAAABQgDAEgDADQgEADgEABIgKABQgHAAgHgDgAgIgUQgEADgCAFQgCAEAAAFIAgAAIACAAIAAgCQAAgEgCgEQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_5.setTransform(0.925,13.925);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIAAgBIAAgmQgBgFgCgDQgDgDgFAAIgGABIgGADIgGAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgFAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAGgFIAHgDIAGgBQAJAAAEAFQAFAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAAAAAg");
	this.shape_6.setTransform(-6.05,13.875);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_7.setTransform(-13.175,13.925);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAeApIgBgBIAAgBIAAg+IgBAAIAAAAIgYA+QAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgEAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgYg9IAAAAIAAAAIAAA9IAAABIgCABIgGAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIALAAIABAAIABABIAYA+IAAABIABgBIAYg9IACgCIALAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAABNQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_8.setTransform(-22.025,12.775);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_9.setTransform(-33.825,13.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAYApIgBAAIgBgBIgqg9IgBgBIAAABIAAA8QAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgHAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAIABAAIABABIApA8IABAAIAAgBIAAg7QAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAIABABIAABOIAAABIgBABg");
	this.shape_10.setTransform(-41.85,12.775);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgDAOIgCAAIAAAAIAAgCIAFgLQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgKQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAAJIAAACIgHAOIgBABg");
	this.shape_11.setTransform(72.925,1.65);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAKAnIgEAAQgGAAgDgDQgDgEAAgGIAAgkQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAgBAAAAIgJAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgEQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAJAAIABgBIABgRQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAARIABABIAOAAIABABIAAAEIgBABIgOAAIgBACIAAAhQAAAGACABQACACADAAIAIAAIABAAIAAACIAAADIgBABIgDABg");
	this.shape_12.setTransform(69.025,-2.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgFIAAgBIABgBIAEgCIABAAIAAAAIAFAFIAGADQADACAEAAQAEAAADgCQAEgBACgCQACgCAAgDQAAgDgDgCQgCgCgGgCIgKgDQgJgCgDgDQgDgEAAgFQAAgFADgEQACgEAFgCQAGgCAFAAQAIAAAFADQAGACADAFIAAABIAAABIgFACIAAAAIgBAAQgCgDgEgDQgEgCgGAAQgFAAgEADQgEACAAAFQAAAAAAABQABABAAAAQAAABAAAAQABABAAAAQACACAFACIANAEQAIABADAEQADAEAAAFQAAAFgDAEQgDAEgFACQgFACgHAAQgIAAgGgDg");
	this.shape_13.setTransform(63.425,-1.425);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgNAbQgGgEgEgHQgDgHAAgIQAAgJAEgHQADgHAGgDQAHgEAHAAQAIAAAGADQAGAEADAHQADAGAAAJIAAABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgpAAIAAABIgBABQAAAFADAFQADAEAEADQAEACAFAAQAFAAAEgCQAFgCADgFIABAAIAAAAIAFACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQgDAEgDADQgEADgEABIgKABQgHAAgHgDgAgIgUQgEADgCAFQgCAEAAAFIAgAAIACAAIAAgCQAAgEgCgEQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_14.setTransform(57.025,-1.425);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgNAeIgBgBIAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAABIAAAHIAAABIABgBIAEgFIAGgEIAGgBQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAABIAAAGIgBABIgCAAIgCAAIgGABIgEADIgEAEQAAABgBAAQAAABAAAAQAAABAAABQAAAAAAABIAAAjQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_15.setTransform(51.4,-1.475);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgNAbQgGgEgEgHQgDgHAAgIQAAgJAEgHQADgHAGgDQAHgEAHAAQAIAAAGADQAGAEADAHQADAGAAAJIAAABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgpAAIAAABIgBABQAAAFADAFQADAEAEADQAEACAFAAQAFAAAEgCQAFgCADgFIABAAIAAAAIAFACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQgDAEgDADQgEADgEABIgKABQgHAAgHgDgAgIgUQgEADgCAFQgCAEAAAFIAgAAIACAAIAAgCQAAgEgCgEQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_16.setTransform(45.275,-1.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAKAnIgEAAQgGAAgDgDQgDgEAAgGIAAgkQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAgBAAAAIgJAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgEQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAJAAIABgBIABgRQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAEAAQABAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAARIABABIAOAAIABABIAAAEIgBABIgOAAIgBACIAAAhQAAAGACABQACACADAAIAIAAIABAAIAAACIAAADIgBABIgDABg");
	this.shape_17.setTransform(39.275,-2.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIAAgBIAAgmQgBgFgCgDQgDgDgFAAIgFABIgHADIgGAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgFAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAGgFIAHgDIAGgBQAJAAAEAFQAFAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAAAg");
	this.shape_18.setTransform(33.45,-1.475);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgCApIgCgBIAAgBIAAhNQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAABNIAAABIgCABg");
	this.shape_19.setTransform(28.025,-2.575);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_20.setTransform(19.625,-1.425);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAYApIgBAAIgBgBIgqg9IgBgBIAAABIAAA8QAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgHAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAIABAAIABABIApA8IABAAIAAgBIAAg7QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAGAAIABABIAABOIAAABIgBABg");
	this.shape_21.setTransform(11.6,-2.575);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgDAOIgCAAIAAAAIAAgCIAFgLQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgKQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAAJIAAACIgHAOIgBABg");
	this.shape_22.setTransform(2.725,1.65);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgFIAAgBIABgBIAEgCIABAAIAAAAIAFAFIAGADQADACAEAAQAEAAADgCQAEgBACgCQACgCAAgDQAAgDgDgCQgCgCgGgCIgKgDQgJgCgDgDQgDgEAAgFQAAgFADgEQACgEAFgCQAGgCAFAAQAIAAAFADQAGACADAFIAAABIAAABIgFACIAAAAIgBAAQgCgDgEgDQgEgCgGAAQgFAAgEADQgEACAAAFQAAAAAAABQAAABABAAQAAABAAAAQABABAAAAQACACAFACIANAEQAIABADAEQADAEAAAFQAAAFgDAEQgDAEgFACQgFACgHAAQgIAAgGgDg");
	this.shape_23.setTransform(-1.925,-1.425);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAKAnIgEAAQgGAAgDgDQgDgEAAgGIAAgkQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAgBAAAAIgJAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgEQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAJAAIABgBIABgRQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAEAAQABAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAARIABABIAOAAIABABIAAAEIgBABIgOAAIgBACIAAAhQAAAGACABQACACADAAIAIAAIABAAIAAACIAAADIgBABIgDABg");
	this.shape_24.setTransform(-7.975,-2.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIAAgBIAAgmQgBgFgCgDQgDgDgFAAIgFABIgHADIgGAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgFAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAGgFIAHgDIAGgBQAJAAAEAFQAFAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAAAg");
	this.shape_25.setTransform(-13.8,-1.475);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgNAbQgGgEgEgHQgDgHAAgIQAAgJAEgHQADgHAGgDQAHgEAHAAQAIAAAGADQAGAEADAHQADAGAAAJIAAABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgpAAIAAABIgBABQAAAFADAFQADAEAEADQAEACAFAAQAFAAAEgCQAFgCADgFIABAAIAAAAIAFACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQgDAEgDADQgEADgEABIgKABQgHAAgHgDgAgIgUQgEADgCAFQgCAEAAAFIAgAAIACAAIAAgCQAAgEgCgEQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_26.setTransform(-20.775,-1.425);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAiAeIgBgBIgBgBIAAgmQAAgFgCgDQgDgDgFAAIgGABIgGADIgEADIgBACIAAABIAAAnQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgFAAIgBgBIgBgBIAAgmQAAgFgCgDQgDgDgFAAQgFAAgEACIgJAHIAAAoQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgGAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAHgFIAGgDIAHgBQAGAAAEADQADADABAEIABAAIABAAIAHgFIAGgDIAHgCQAIAAAEAFQAFAEAAAIIAAAoQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_27.setTransform(-29.525,-1.475);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgWAmIgBgBIAAgEIAAgBIADgBIAHAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAIADgEIACgFQAAgBABAAQAAgBAAgBQgBAAAAgBQAAAAAAgBIgVgzIAAgBIABgBIAHAAIABAAIABABIAPAqIABABIABgBIAQgqIABgBIABAAIAFAAIABAAIAAACIgYA8IgDAHIgEAEIgFACIgHAAg");
	this.shape_28.setTransform(-38.0375,-0.525);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgSAaQgFgEAAgIQAAgFADgFQAEgEAGgBQAGgDAJAAIAIgBIACgBIAAgBIAAgDQAAgGgDgDQgEgEgGAAQgEAAgEADQgEACgDAEIgBABIgBAAIgGgCIAAgBIAAgBQADgGAGgDQAGgDAIAAQAHAAAFACQAFACADAFQACAEAAAGIAAAmIAAABIgBAAIgGAAIgBAAIAAgCIgBgFQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQgEAEgFACQgFACgFAAQgIAAgFgEgAAOAAIgIAAIgIABIgGADQgDACgCACIgBAFQAAAFADADQAEADAFAAQADAAADgCIAGgDIAEgEQAAgBAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBIAAgJQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAIAAAAg");
	this.shape_29.setTransform(-44.725,-1.425);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgbApIgBgBIgBgBIAAhNQAAgBAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIAbAAQAIAAAHADQAHACAEAFQAEAGAAAIQAAAIgEAFQgEAFgGACQgHADgIAAIgSAAIgBABIAAAfQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAgSgfIAAAdQAAABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIARAAQAIAAAGgEQAFgEAAgIQAAgGgDgDQgCgEgEgBQgFgCgFAAIgRAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAAAg");
	this.shape_30.setTransform(-51.675,-2.575);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_31.setTransform(-62.525,-1.425);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAYApIgBAAIgBgBIgqg9IgBgBIAAABIAAA8QAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgHAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAIABAAIABABIApA8IAAAAIABgBIAAg7QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAHAAIABABIAABOIAAABIgBABg");
	this.shape_32.setTransform(-70.55,-2.575);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgEApQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgwIgBgBIgKAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAAAAAgBIAAgEIAAgBIABgBIAKAAIABgBIAAgIQAAgHAEgDQACgEAHAAIAJAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAABAAIAAAFIAAABIgBAAIgIAAQgBAAgBAAQgBAAAAAAQgBABAAAAQgBAAAAABQgCACAAAEIAAAHIABABIANAAIABABIAAABIAAAEIgBABIgNAAIgBABIAAAwQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_33.setTransform(39.55,-17.925);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_34.setTransform(33.575,-16.775);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgFIAAgBIABgBIAEgCIABAAIAAAAIAFAFIAGADQADACAEAAQAEAAADgCQAEgBACgCQACgCAAgDQAAgDgDgCQgCgCgGgCIgKgDQgJgCgDgDQgDgEAAgFQAAgFADgEQACgEAFgCQAGgCAFAAQAIAAAFADQAGACADAFIAAABIAAABIgFACIAAAAIgBAAQgCgDgEgDQgEgCgGAAQgFAAgEADQgEACAAAFQAAAAAAABQABABAAAAQAAABAAAAQABABAAAAQACACAFACIANAEQAIABADAEQADAEAAAFQAAAFgDAEQgDAEgFACQgFACgHAAQgIAAgGgDg");
	this.shape_35.setTransform(23.825,-16.775);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAQApIgBgBIgBgBIAAgnQAAgEgCgDQgDgDgGAAIgEABIgGADIgHAFIAAAoQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgHAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAIABABIAAAeIAAAAIABAAIAHgFIAGgDIAHgBQAIAAAFAFQAEAEAAAIIAAAoQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAg");
	this.shape_36.setTransform(17.4,-17.925);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAKAnIgEAAQgGAAgDgDQgDgDAAgIIAAgjQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgJAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAAAAAAAIAAgFQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIAJAAIABAAIABgSQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAASIABAAIAOAAIABABIAAAGIgBABIgOAAIgBABIAAAiQAAAFACACQACABADAAIAIAAIABABIAAAAIAAAEIgBACIgDAAg");
	this.shape_37.setTransform(10.775,-17.75);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIgBgBIAAgmQABgFgDgDQgDgDgFAAIgGABIgFADIgHAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgGAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAHgFIAGgDIAGgBQAJAAAFAFQAEAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAAAAAg");
	this.shape_38.setTransform(4.95,-16.825);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_39.setTransform(-2.175,-16.775);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAeApIgBgBIAAgBIAAg+IgBAAIAAAAIgYA+QAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgEAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgYg9IAAAAIAAAAIAAA9IAAABIgCABIgGAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIALAAIABAAIABABIAYA+IAAABIABgBIAYg9IACgCIALAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAABNQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_40.setTransform(-11.025,-17.925);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgPAnQgHgCgDgFQgEgFAAgGQAAgGADgFQADgFAGgEIACgBIgBAAIgGgEIgEgGIgBgHQAAgHAEgFQADgGAGgDQAHgDAHAAQAIAAAGADQAGADADAFQAEAFAAAGQAAAGgDAEQgCAEgGAEQgBAAAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIAIAEQADADACAEQABAEAAAEQAAAHgDAFQgEAFgHADQgHADgJAAQgIAAgHgDgAgJAEIgFADIgEAFQgCAEAAADQAAAHAGAEQAFAEAJAAQAJAAAGgEQAFgEAAgGQAAgGgDgDQgDgDgGgBIgNgEIgBAAIgDABgAgIgfQgEACgCADQgDADAAAFQAAAKALACIALADIAEgBIAEgDIADgGIABgGQAAgGgEgEQgFgEgIAAQgEAAgEACg");
	this.shape_41.setTransform(-23.175,-17.925);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgSApIgCgBIAAgHIACgBIANAAIABAAIAAg8IgBgBIgNAGQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgEIAAgBIACgBIAQgIIACgBIAAAAIAFAAIABABIAABHIAAAAIAOAAIAAABIAAAHIAAAAIAAABg");
	this.shape_42.setTransform(-29.95,-17.925);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgBAYQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgTIAHAAIAAAUQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAAAgAAEADIAAgFIATAAIABABIAAADQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAgAgDADIgSAAIgCAAIAAgBIAAgDIABgBIATAAIAAAFIAAgFIAHAAIAAAFgAAEgCIgHAAIAAgTIABgCIABAAIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAUgAgDgCg");
	this.shape_43.setTransform(-39.125,-17.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-76.8,-26.5,153.6,48.1);


(lib.Promo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAvQAAAAgBAAQAAgBAAAAQAAAAAAAAQgBgBAAAAIAAgLQAAAAABAAQAAgBAAAAQAAAAAAAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAALQAAAAgBABQAAAAAAAAQAAAAgBABQAAAAgBAAgAgBAYIgBAAIgBgBIgDhDIABgBIABgBIAJAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIgCBCIgBACIgCAAg");
	this.shape.setTransform(69.45,-31.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgaAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAKAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABQIABABIArAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIgBABg");
	this.shape_1.setTransform(64.425,-31.575);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAKAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABQIABABIArAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIgBABg");
	this.shape_2.setTransform(56.875,-31.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAeAvIgCgBIgJgZIAAgBIgBAAIgkAAQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIgJAZIAAAAIgCABIgHAAIgBgBIAAgBIAhhZIABgBIABgBIAJAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAhBZIAAABIgBABgAgBggIgPApQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIAdAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIgPgpIAAgBg");
	this.shape_3.setTransform(48.25,-31.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgDAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhQQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIgcAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgGIAAgBIABgBIBDAAIABABIAAABIAAAGQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgaAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAABQQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAg");
	this.shape_4.setTransform(39.625,-31.575);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNAuQgGgCgFgDQgFgEgEgFIAAgBIABgCIAFgDIACgBIABABIAHAHQADADAFABQAEACAFAAQAKAAAGgEQAHgDgBgJQAAgDgBgCIgEgFIgJgFIgSgGQgHgCgFgDQgDgEgCgFQgCgEAAgFQAAgIAEgGQAEgGAGgDQAIgDAIAAIAMABIAKAFIAIAHIAAABIAAABIgGAEIgBABIgCgBQgDgEgEgDQgGgDgIAAQgIAAgGAEQgFAFAAAHIABAFQABACADADQADACAFACIASAGQALADAFAGQAFAHAAAIQAAAIgEAGQgEAGgIADQgHADgLAAQgGAAgHgCg");
	this.shape_5.setTransform(31.45,-31.575);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAcAvIgCAAIgBgBIgvhGIgBgBIgBABIAABFQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIAAhZQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAGAAIACAAIABACIAvBEQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIAAgBIAAhDQAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAHAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAABZIAAABIgBABg");
	this.shape_6.setTransform(22.75,-31.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgDAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAJAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABZIAAABIgCABg");
	this.shape_7.setTransform(16.175,-31.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgaAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAKAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABQIABABIArAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIgBABg");
	this.shape_8.setTransform(8.225,-31.575);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgaAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAKAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABQIABABIArAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIgBABg");
	this.shape_9.setTransform(0.675,-31.575);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAdAvIgCgBIgIgZIgBgBIgBAAIgjAAQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgJAZIgBAAIgBABIgIAAIgBgBIAAgBIAghZIABgBIACgBIAJAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAhBZIAAABIgCABgAgBggIgPApQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAAAAAIAeAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIgPgpIAAgBg");
	this.shape_10.setTransform(-7.95,-31.575);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgaAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIA3AAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgqAAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAAfIABABIAhAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAFQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIghAAIgBABIAAAmQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_11.setTransform(-16.025,-31.575);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAWAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgQgnQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgUAAIgCABIAAABIAAAnQAAAAAAABQAAAAAAAAQgBAAAAABQgBAAAAAAIgIAAIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAjAAQAOAAAJAGQAIAGAAAMQAAAIgDAFQgDAFgEADIgIADQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAAAIASApIAAACIgCABgAgVgkIAAAfQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIAUAAQAKAAAGgEQAFgEAAgIQAAgJgFgEQgFgEgJAAIgVAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAg");
	this.shape_12.setTransform(-26.875,-31.575);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgSAsQgIgEgDgIQgEgHAAgMIAAg5QAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAJAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAA9QAAALAGAGQAGAFAKAAQAHAAAFgCQAFgDADgFQACgFAAgIIAAg8QAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAHAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAA8QAAALgEAIQgEAHgIADQgHADgLAAQgLAAgHgDg");
	this.shape_13.setTransform(-35.975,-31.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUAqQgJgFgFgLQgFgKAAgQQAAgOAFgLQAFgLAJgFQAJgGALAAQANAAAJAGQAIAFAFALQAFALAAAOQAAAPgFALQgFALgIAFQgJAGgNAAQgLAAgJgGgAgTgcQgHAJAAATQAAAUAHAJQAHAKAMAAQAOAAAHgKQAGgJAAgUQAAgTgGgJQgIgKgNAAQgMAAgHAKg");
	this.shape_14.setTransform(-45.2,-31.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgDAvIgBgBIgBgBIAAgjIAAgCIgBgCIgegyIAAgBIABgBIAJAAIACABIABABIAXAoIABACIABgCIAXgoIABgCIACAAIAIAAIABABIAAABIgeAxIgBACIAAACIAAAkQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAg");
	this.shape_15.setTransform(-54.2375,-31.575);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgDAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhQQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgcAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgGIAAgBIABgBIBDAAIABABIAAABIAAAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgaAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAABQQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAg");
	this.shape_16.setTransform(78.975,-46.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgSAsQgIgEgDgIQgEgHAAgMIAAg5QAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAJAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAA9QAAALAGAGQAGAFAKAAQAHAAAFgCQAFgDADgFQACgFAAgIIAAg8QAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAHAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAA8QAAALgEAIQgEAHgIADQgHADgLAAQgLAAgHgDg");
	this.shape_17.setTransform(70.475,-46.775);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUAqQgJgFgFgLQgFgKAAgQQAAgOAFgLQAFgLAJgFQAJgGALAAQAMAAAKAGQAJAFAEALQAFALAAAOQAAAPgFALQgEALgJAFQgKAGgMAAQgLAAgJgGgAgUgcQgGAJAAATQAAAUAGAJQAIAKANAAQANAAAHgKQAGgJABgUQgBgTgGgJQgIgKgNAAQgMAAgIAKg");
	this.shape_18.setTransform(61.2,-46.825);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AggAvIgBgBIAAgBIAAhZIAAgBIACgBIAdAAQAPAAAKAGQAJAHAAALQAAAIgEAFQgEAFgJAEIAAAAIAAAAQAJACAFAFQAFAGAAAJQAAAMgJAHQgKAGgQAAgAgVAGIAAAeQAAABAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIASAAQALAAAGgEQAGgEAAgJQAAgGgDgEQgDgDgFgCQgFgCgGAAIgSAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAABgAgVgjIAAAdQAAABAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIATAAIAHgBIAHgCIAFgFQACgDAAgFQAAgJgHgEQgGgEgJAAIgRAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAABg");
	this.shape_19.setTransform(52.275,-46.825);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAeAvIgDgBIgIgZIgBgBIgBAAIgjAAQAAAAgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgJAZIAAAAIgBABIgIAAIgBgBIAAgBIAhhZIABgBIABgBIAJAAQAAAAABAAQAAABABAAQAAAAAAAAQAAABAAAAIAhBZIAAABIgBABgAgBggIgPApQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIAdAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIgPgpIAAgBg");
	this.shape_20.setTransform(43.1,-46.825);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgTAqQgIgFgFgLQgFgLAAgPQAAgOAFgLQAFgLAJgFQAJgGALAAQAIAAAIAEQAIADAEAGQAFAGABAGIAAACIgBAAIgJACIgBgBIgBgBQgBgFgCgEQgEgEgEgCQgFgDgGAAQgIAAgGAFQgGAEgDAJQgDAIAAAMQAAANADAIQADAJAGAFQAGAEAIAAQAGAAAFgCQAEgCADgEIAFgHIACgIIAAgIQAAAAAAAAQAAAAAAAAQgBgBAAAAQAAAAgBAAIgUAAIgBAAIgBgBIAAgGQABAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAIAfAAIACAAIAAABIAAAsIAAABIgBABIgEAAIgBAAIgBgCIgBgLIAAgBIgBABQgDADgEAEIgJAFQgEACgIAAQgLAAgJgGg");
	this.shape_21.setTransform(31.15,-46.825);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAcAvIgCAAIgBgBIgvhGIgBgBIgBABIAABFQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIAAhZQAAAAABgBQAAAAAAAAQAAAAABgBQAAAAABAAIAGAAIACAAIABACIAvBEQAAAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIAAgBIAAhDQAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAHAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAABZIAAABIgBABg");
	this.shape_22.setTransform(21.85,-46.825);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgDAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAJAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABZIAAABIgCABg");
	this.shape_23.setTransform(15.275,-46.825);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAYAvIgCgBIgbguQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAIgOAQIgBACIAAAbQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgIAAIgCgBIgBgBIAAhZQAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAKAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAtIAAABIABgBIAoguIACgBIABAAIAJAAIABABIAAABIgeAhIAAABIAhA3IAAABIgBABg");
	this.shape_24.setTransform(9.35,-46.825);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAcAvIgBAAIgCgBIgwhGIgBgBIAAABIAABFQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgIAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAIAAIABAAIABACIAuBEQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIABgBIAAhDQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAIAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAABIAABZIgBABIgBABg");
	this.shape_25.setTransform(-0.15,-46.825);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgDAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAJAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABZIAAABIgCABg");
	this.shape_26.setTransform(-6.675,-46.825);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAYAvQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAAAIAAgpQAAAAAAAAQAAAAAAgBQAAAAgBAAQAAAAAAAAIgpAAIgBABIAAApQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgIAAIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAKAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAlQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIApAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIAAglQAAgBAAAAQAAAAABAAQAAgBAAAAQAAAAAAAAIAKAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAABZIAAABIgCABg");
	this.shape_27.setTransform(-13.125,-46.825);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgDAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhQQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIgcAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgGIAAgBIABgBIBDAAIABABIAAABIAAAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgaAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAABQQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAg");
	this.shape_28.setTransform(-21.775,-46.825);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgDAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhQQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgcAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgGIAAgBIABgBIBDAAIABABIAAABIAAAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgaAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAABQQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAg");
	this.shape_29.setTransform(-32.525,-46.825);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAWAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgQgnQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgUAAIgCABIAAABIAAAnQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgIAAIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAjAAQAOAAAJAGQAIAGAAAMQAAAIgDAFQgDAFgEADIgIADQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAAAIASApIAAACIgCABgAgVgkIAAAfQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIAUAAQAKAAAGgEQAFgEAAgIQAAgJgFgEQgFgEgJAAIgVAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAg");
	this.shape_30.setTransform(-40.725,-46.825);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAeAvIgCgBIgJgZIAAgBIgBAAIgkAAQAAAAgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgJAZIAAAAIgCABIgHAAIgBgBIAAgBIAhhZIABgBIABgBIAJAAQABAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAhBZIAAABIgBABgAgBggIgPApQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIAdAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIgPgpIAAgBg");
	this.shape_31.setTransform(-49.85,-46.825);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgDAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhQQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAAAAAAAIgcAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgGIAAgBIABgBIBDAAIABABIAAABIAAAGQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgaAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAABQQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAg");
	this.shape_32.setTransform(-58.475,-46.825);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgNAuQgGgCgFgDQgFgEgDgFIgBgBIACgCIAEgDIACgBIABABIAGAHQAEADAEABQAFACAFAAQAKAAAGgEQAGgDABgJQgBgDgBgCIgFgFIgIgFIgSgGQgHgCgEgDQgFgEgCgFQgCgEAAgFQAAgIAFgGQADgGAIgDQAGgDAKAAIALABIAKAFIAIAHIAAABIAAABIgGAEIgBABIgBgBQgEgEgFgDQgFgDgHAAQgJAAgGAEQgFAFAAAHIABAFQABACADADQADACAGACIARAGQALADAFAGQAFAHAAAIQAAAIgEAGQgEAGgHADQgIADgKAAQgHAAgHgCg");
	this.shape_33.setTransform(-66.6,-46.825);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgDAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhQQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgcAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgGIAAgBIABgBIBDAAIABABIAAABIAAAGQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgaAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAABQQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAg");
	this.shape_34.setTransform(62.225,13.975);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgSAqQgJgGgEgKQgGgLAAgPQAAgOAGgLQAEgLAJgFQAJgGALAAQAGAAAHACQAFACAFAEQAFADADAFQACAFABAFIAAABIgBABIgJAAIgBAAIAAgBQgCgIgGgFQgGgFgJAAQgMAAgHAKQgGAKgBASQAAATAHAKQAHAJANAAQAJAAAGgEQAGgEADgKIACAAIAHACIABAAIAAABQAAAEgDAEIgFAGIgHAGIgJAEIgLABQgLAAgJgGg");
	this.shape_35.setTransform(53.25,13.975);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgcAvQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAhZQAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAAAIA4AAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgrAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAeIABABIAgAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAGIAAABIgBAAIggAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAAAeIABABIAuAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAABIAAAGIAAABIgBABg");
	this.shape_36.setTransform(44.55,13.975);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgKAuIgFgBIgCgBIAAgCIACgGQAAgBAAAAQAAAAAAAAQAAAAAAAAQABAAAAAAIAEABIAHABQAEAAADgDQACgDAAgIIAAhEQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAJAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAABHQAAALgFAFQgFAFgJAAIgJgBg");
	this.shape_37.setTransform(36.8,14.025);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgUAqQgJgFgFgLQgFgKAAgQQAAgOAFgLQAFgLAJgFQAJgGALAAQANAAAIAGQAKAFAEALQAFALAAAOQAAAPgEALQgFALgKAFQgIAGgNAAQgLAAgJgGgAgTgcQgHAJAAATQAAAUAHAJQAGAKANAAQAOAAAGgKQAIgJAAgUQAAgTgIgJQgGgKgOAAQgNAAgGAKg");
	this.shape_38.setTransform(29.2,13.975);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAWAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgQgnQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgUAAIgCABIAAABIAAAnQAAAAAAABQAAAAAAAAQgBAAAAABQgBAAAAAAIgIAAIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAjAAQAOAAAJAGQAIAGAAAMQAAAIgDAFQgDAFgEADIgIADQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAAAIASApIAAACIgCABgAgVgkIAAAfQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIAUAAQAKAAAGgEQAFgEAAgIQAAgJgFgEQgFgEgJAAIgVAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAg");
	this.shape_39.setTransform(19.725,13.975);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgfAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAfAAQAKAAAHADQAIADAEAGQAFAGAAAJQAAAKgEAGQgFAFgHADQgIADgJAAIgUAAIgBABIAAAkQAAAAgBABQAAAAAAAAQAAAAgBABQAAAAAAAAgAgUgjIAAAhQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAABAAIATAAQAKAAAGgFQAGgEAAgKQAAgGgDgEQgDgEgFgCQgFgCgGAAIgTAAQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABg");
	this.shape_40.setTransform(10.5,13.975);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgbAvQgBAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAhZQAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAAAIA4AAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgsAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAeIABABIAgAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAGIAAABIgBAAIggAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAAAeIABABIAtAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIgBABg");
	this.shape_41.setTransform(-1.5,13.975);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAWAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgQgnQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgUAAIgCABIAAABIAAAnQAAAAAAABQAAAAAAAAQgBAAAAABQgBAAAAAAIgIAAIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAjAAQAOAAAJAGQAIAGAAAMQAAAIgDAFQgDAFgEADIgIADQgBAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIASApIAAACIgCABgAgVgkIAAAfQAAAAAAAAQAAABABAAQAAAAAAAAQAAAAAAAAIAUAAQAKAAAGgEQAFgEAAgIQAAgJgFgEQgFgEgJAAIgVAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAg");
	this.shape_42.setTransform(-10.375,13.975);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgDAvIgCgBIAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAJAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAABZIAAABIgCABg");
	this.shape_43.setTransform(-17.375,13.975);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgDAvQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhQQAAgBAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIgcAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgGIAAgBIABgBIBDAAIABABIAAABIAAAGQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgaAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAABQQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAg");
	this.shape_44.setTransform(-23.725,13.975);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAcAvIgBAAIgCgBIgwhGIAAgBIgBABIAABFQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgIAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhZQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAIAIAAIABAAIABACIAuBEQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAIABgBIAAhDQAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAIAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABAAAAABIAABZIgBABIgBABg");
	this.shape_45.setTransform(-33.1,13.975);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgbAvQgBAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAhZQAAAAABgBQAAAAAAAAQAAgBAAAAQABAAAAAAIA4AAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgsAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAeIABABIAgAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAGIAAABIgBAAIggAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAAAeIABABIAtAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIgBABg");
	this.shape_46.setTransform(-42,13.975);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AhRCDQgFAAgBgBIgBgGIAAj4QAAgGAFAAICnAAQAFAAAAAGIAAAbQAAAGgGAAIhxAAQgGAAAAAFIAABBQAAAGAFAAIBRAAQAGAAAAAFIAAAbQAAAEgGABIhSAAQgEAAAAAEIAABiQAAAHgHAAg");
	this.shape_47.setTransform(75.35,-8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AhRCDQgFAAgBgBIgBgGIAAj4QAAgGAFAAICnAAQAFAAAAAGIAAAbQAAAGgHAAIhwAAQgGAAAAAFIAABBQAAAGAFAAIBSAAQAEAAAAAFIAAAbQAAAEgEABIhTAAQgEAAAAAEIAABiQAAAHgHAAg");
	this.shape_48.setTransform(53.5,-8);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("Ag+B3QgagQgOgeQgPgeAAgqQAAgpAPgeQAOgfAagQQAbgQAjAAQAkAAAaAQQAbAQAPAfQANAdAAAqQAAApgNAfQgPAegbAQQgaAQgkAAQgjAAgbgQgAgvhJQgQAYAAAzQAAAxAQAXQAQAXAfAAQAhAAAPgWQAPgYAAgxQAAgzgPgYQgQgXggAAQgfAAgQAXg");
	this.shape_49.setTransform(28.25,-8);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AA0B9QgPgKgIgQQgJgRAAgWQAAgVAJgRQAIgRAPgJQAPgKASABQASgBAPAKQAOAJAJARQAIARAAAVQAAAWgIARQgJAQgOAKQgPAKgSAAQgTAAgOgKgABEAQQgHAGgDAMQgEALAAAPQAAAPAEAMQADAMAHAFQAHAHAKAAQAJAAAHgHQAHgFADgMQAEgMAAgPQAAgPgEgLQgDgMgHgGQgHgHgJABQgKgBgHAHgAhbCEQgFAAAAgCQgBgDACgEICoj9IADgCIAEAAIAQAAIADABQABAAAAAAQAAABAAAAQAAABAAAAQgBABAAABIiqEAQgCAEgGgBgAh0AEQgPgIgIgRQgJgQAAgWQAAgVAJgRQAIgRAPgKQAPgJASAAQASAAAPAJQAOAKAJARQAIARAAAVQAAAWgIAQQgIARgPAIQgOAKgTAAQgSAAgPgKgAhkhoQgHAHgDAMQgEALAAAPQAAAPAEAMQADALAHAGQAHAHAKAAQAPAAAIgPQAHgNAAgXQAAgXgIgOQgHgOgPAAQgKABgHAFg");
	this.shape_50.setTransform(-9.225,-8);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("Ag1B2QgYgQgOgdQgNgeAAgqQAAgeAIgZQAIgZAOgSQAOgSATgJQAUgJAVAAQAXAAATAJQATAJAOASQAPASAHAZQAIAZAAAeQAAAqgNAeQgOAdgYAQQgXAQgfAAQgdAAgYgQgAgbhWQgMAKgGAWQgGAWAAAhQAAAiAGAVQAGAWAMAJQAMAKAPAAQARAAAMgKQALgJAGgVQAGgVAAgjQAAgigGgVQgGgWgMgKQgLgKgRAAQgPAAgMAKg");
	this.shape_51.setTransform(-37.975,-8.025);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AhXCFIgGgCQgBgBAAgEIAAgXIABgEIAEgFIAJgJIBFhAIAZgZIARgSQAGgJACgHQADgIAAgJQAAgMgGgIQgGgJgKgEQgKgFgLAAQgJAAgKAEQgJADgJAIQgJAIgIANQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAIgGgCIgagOQgDgBgBgDQAAgDACgDQASgbAYgMQAYgNAcAAQAaAAAUAJQAVAJAMASQAMARAAAZQAAAOgFAOQgGANgLANQgMANgTAQIhDA5IgBACQAAABAAAAQAAAAABAAQAAABABAAQAAAAABAAIByAAQAGAAAAAFIAAAgIgBAEQgCACgDAAg");
	this.shape_52.setTransform(-61.975,-8.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-93.5,-56.1,199.5,79.7);


(lib.logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Logo();
	this.instance.setTransform(-160,-25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160,-25,320,50);


(lib.line = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AhzAAIDnAA");
	this.shape.setTransform(-0.925,-0.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-13.5,-1.2,25.2,2);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AFrA4QgJgFgEgHIgBgDIABgBIAMgFIABABIAFAFQAEAEAEABQAFACAGgBQAFABAEgCQAEgBADgCQACgDAAgDQAAgEgDgCQgCgCgHgCIgRgEQgMgCgGgHQgFgFAAgJQAAgHAEgGQAEgGAIgEQAIgDALAAQAMAAAIAEQAJAFAEAGIABACIgBACIgKAEIgCAAIgBgBQgDgEgFgCQgFgDgHAAQgHAAgFADQgFACAAAFQAAADACACQACABAHACIATAGQAMACAGAHQAFAGAAAJQAAAIgFAGQgEAGgJADQgIADgLAAQgOAAgKgFgAD/A4QgKgFgFgLQgFgLAAgPIAAhFQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAABJQAAAOAGAGQAGAGAMAAQAIAAAFgDQAGgCADgHQADgFAAgKIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABIQAAAQgGAKQgFAJgLAFQgKAEgOAAQgRAAgKgFgABAA4QgJgGgGgKQgFgJAAgNQAAgNAFgKQAGgKAJgGQAKgFAMAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEgGIgFgEQgDgCgEAAQgHAAgFAEQgFADgCAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAHAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgMAAgKgFgAgsA3QgHgHAAgKQAAgJAFgHQAFgGALgEQAKgEAOAAIAHAAIACgBIAAgCIAAgDQAAgHgDgDQgEgFgHAAQgGAAgFADQgFADgDAFIgBACIgCAAIgOgEIgBgBIABgCQAEgJAJgGQAKgEAOAAQALAAAIADQAHAEAEAGQADAGAAAHIAAA4IAAADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBgBAAQAAgBAAAAQgBAAAAABQgBAAAAAAQgFAGgGACQgHADgIAAQgMAAgHgGgAgFATIgKABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAHAAQAEAAAEgBIAGgEIAEgFIABgFIAAgLQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAgAkbA4QgKgGgFgKQgFgKAAgMQAAgNAFgKQAGgKAJgGQAKgFAMAAQAMAAAKAGQAJAFAGAKQAFAKAAANQAAAMgGAKQgFAKgJAGQgKAFgMAAQgNAAgJgFgAkRgIQgEADgDAGQgCAHAAAJQAAAJACAIQADAGAEAEQAFADAHAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgJgDgHQgCgGgFgDQgFgEgGAAQgHAAgFAEgAmOA2QgMgIgGgOQgHgOAAgSQAAgSAHgOQAGgNAMgHIAEgCQAKgGAOAAQAJAAAIADIAGADIAIAEQAGAFAEAGQAEAGABAIIABACIgCABIgSABIgCAAIgBgCQgCgIgFgGQgGgGgKAAQgOAAgHAKQgIALAAAWQAAAWAHALQAIALAOAAQAKgBAHgFQAHgEAFgMQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANADIABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgEAIIgGAJQgEAFgFADQgGADgHADQgHACgJAAQgQAAgMgHgACVA3QgGgGAAgKIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIADgZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIASAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgSABQgLAAgFgEgAhgA3QgFgGAAgKIAAguQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgKQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIALAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAABIASAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAAAqQAAAGADADQACACAGAAIAJAAIACABIABABIgBAJQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgRABQgLAAgGgEgAiTA7IgCAAIgBgDIAAg2QAAgFgDgEQgEgDgGAAIgIABIgGADIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgEQAFgCAFAAQAMAAAHAHQAHAHAAALIAAA5QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(-0.0004,3.3535,1.0368,1.0368);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6CC24D").s().p("Am1CDQg3AAgmgmQgbgbgIgjQgDgPgBgQIAAAAQAAg1AngmQASgSAUgKQAZgLAeAAINrAAQAeAAAZALQAUAKASASQAnAmAAA1IAAAAQAAAQgEAPQgIAigbAcQgnAmg2AAg");
	this.shape_1.setTransform(0,3.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.9,-9.7,113.9,26.2);


// stage content:
(lib.WBAY_218322_MM_320x50_V2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#010101").ss(1,1,1).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(160));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(262,39.85,0.6,0.6,0,0,0,0.1,0.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(62).to({_off:false},0).to({y:37.35,alpha:1},13).wait(85));

	// T2
	this.instance_1 = new lib.T2("synched",0);
	this.instance_1.setTransform(263.75,11.25,0.6,0.6,0,0,0,0.1,0.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(49).to({_off:false},0).to({y:16.25,alpha:1},13,cjs.Ease.get(1)).wait(98));

	// line
	this.instance_2 = new lib.line("synched",0);
	this.instance_2.setTransform(209.55,25,1,1,-90,0,0,-0.9,-0.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(30).to({_off:false},0).wait(130));

	// Promo
	this.instance_3 = new lib.Promo("synched",0);
	this.instance_3.setTransform(148.2,27.45,0.6,0.6,0,0,0,4.6,-16.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(14).to({_off:false},0).to({y:24.95,alpha:1},16,cjs.Ease.get(1)).wait(130));

	// logo
	this.instance_4 = new lib.logo("synched",0);
	this.instance_4.setTransform(160,15);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({y:25,alpha:1},14,cjs.Ease.get(1)).wait(146));

	// BG
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#54585A").s().p("AyCD6IAAnzMAkFAAAIAAHzg");
	this.shape_1.setTransform(204.5,25);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(160));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(159,15,162,36.5);
// library properties:
lib.properties = {
	id: 'ECAEFFBAF1704CA9B680B457A657B9CE',
	width: 320,
	height: 50,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Logo.png", id:"Logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['ECAEFFBAF1704CA9B680B457A657B9CE'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;