(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.CTA = function() {
	this.initialize(img.CTA);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.IMG = function() {
	this.initialize(img.IMG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.Logo = function() {
	this.initialize(img.Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.Why_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D4A88").s().p("Ag1BvIgDgEQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIAAgEIAEgFIAFgEIAGgFIAGgDIAFgBIAFABIACADQABABAAAAQAAABAAAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIABAEIgCACIgFACIgGAEIgIAFIgEAEIgDACIgBAAIgBAAgAg0BmIgCACQAAAAAAAAQABAAAAAAQAAAAABAAQAAgBABgBIABgBgAgvBCIgEgGIgCgGQgDgJABgHQABgIAGgIQAGgJANgLIAigYQASgNAMgNQALgOACgLIAAgDIgEgDIgIgCIgMgBIgJABIgHAAIgHACIgGAEQgRAIgMAOQgMAOgGASIgCAGIgBADIgDAAIgDgDIgCgDIgCgEIgDgEIAAgHQABgHAEgIQADgJAEgHIAHgJIAJgJIAJgIIAJgHQAKgHAKgDQAKgDAKAAQAKgBAJAEQAJADAGAGIADAEIACAEIACAEIADAFQAIALgCAMQgCAMgLAOIgHAIIgKAJIgOALIgSAMIgRANIgNAOIgGAIIgFAJIgEAJIgBAGQABAFgCAAQgCAAgEgGgAgYANIgIAIIgHAIIgEAGIAAACIABgCIACgDIAFgGIAHgIIAFgFIABgBIgCABgAgIAEIgHAGIgJAJIgJAIIgEAGIgBACIAEgFIALgLIARgPIACgCIgEACgAAtglIgFAFIgHAGIgHAGIgHAGIgIAGIgHAEIgDADIADgCIAHgEIAJgHIAIgGIAGgFIAEgDIACgCIAEgFIACgCIgBAAgAAVgUIgCADQAAAAAAAAQAAAAAAAAQABAAAAgBQABAAAAgBIABgCIgBABgAAwguIgFAGIgJAJIgHAHQgBAAAAABQAAAAAAAAQAAABAAAAQAAAAAAgBIAFgEIAGgGIAGgGIAFgGIADgEIgDADgAAmgmIgCACQAAAAAAAAQABAAAAAAQAAAAABAAQAAgBABgBIABgBIgCABgAApgrIgBACIADgCIABgCgAgkhHIgFAFIgEAGIgFAGIgDAEQgFALAIgNIAGgIIAHgJIAHgHIgGAFgAgbhLIgFAFIgHAHIgFAGIgDAFIACgCIAFgHIAJgJIAJgIIgFADgAgWhOIAAAAg");
	this.shape.setTransform(150.22,-277.0281);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1D4A88").s().p("AAGAWIgDgCIAEgEIAEgHIADgEIgCgBIgDgBIgCgDIgEgEIAAgDIACgGIAEgFIAFgEIAEgCIADACIAEADIADAEIADAEIAAAHIgEAJIgEAKIgGAHQgDADgDAAQgDAAgCgDgAgbAWIgCgCIADgEIAFgHIACgEIgBgBIgCgBIgEgDIgDgEIgBgDIACgGIAFgFIAEgEIAFgCIADACIAEADIAEAEIACADIgBAIIgDAJIgFAKIgFAHQgDADgDAAQgDAAgDgDg");
	this.shape_1.setTransform(138.85,-291.5125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1D4A88").s().p("AgxCBIgCgBIgEgBIgIgDQgJgEABgCQABgDALAAIAGgBIAGgDQAOgHAPgWQAPgWAMghIAFgOIAFgPIAFgNIACgHIgBABIgDADIgFAIIgIAJIgJAHQgDACgFAAQgEAAgDgCIgEgDIgEgBQgEgCgFgEQgFgGgBgFIgDgQIgBgRIAEgVIAHgXIAIgTQAEgJAEgDQAFgFACAAQACAAADACQAAABABABQABAAAAAAQABABAAAAQAAAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQADgBACADIACADIgCAHIgFAPIgIAgIgGAZIgBAIIAAAIIAAAIIABAFIABACIADgBIAFgEIAGgHIAHgIIAFgIIAJgPIAJgRIAHgSIAFgRIABgHIACgFQABgBAGABIABACQAAABAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIABABQAAABAFACQAFACACADIACAHIgBAPIgEAWIgGAaIgHAYIgMAhIgOAfQgLAWgOARQgOARgNAHIgGADIgIACIgGACIgEAAIgBAAgAARAyQAAABAAAAQABABAAAAQAAAAAAgBQABAAAAgBQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAgAAVArIgBADQAAABAAAAQAAAAAAAAQAAAAAAAAQABgBAAAAIABgDIAAgBIgBABgAAvgeIgCAKIgFAOIgGAPIgFAOIgHARIACgDIADgGIAFgLIAGgSIAGgPIAEgNIAAgGgAAdAMIgBADQAAABAAAAQAAAAAAAAQAAAAABgBQAAAAAAAAIABgDIAAgBIgBABgAA0hEIgDAMIgEAPIgEAPIgEAPIgEALIgCAHIgBADIAHgRIAJgdIAHgfIABgFIAAgBIgCAFgAAmgXIAAABIAAgCIAAgBIAAACgAAoggIgBAFQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAgBIABgEIAAgBIgBABgAAxgkIABABIAAgCIgBgBIAAACgAAsguIgCAEIgBAEIAAADIABgBIABgDIABgEIAAgDIAAAAIAAAAgAgJhuIgDAIIgEALIgEALIgGAWIgCAPQAAAAAAAAQAAAAAAAAQAAAAABAAQAAgBAAAAIABgHIAGgaQAEgNAFgMIADgIIABgDIgCADgAgggvIABACIAAgDIAAgBIgBACgAAug6IgBAFQAAABAAABQAAABAAAAQAAAAAAAAQAAAAAAgBIABgCIABgDIgBgCIAAAAgAgVhXIgEANIgEAOIgBAIIAAABIABgEIACgKIAEgMIACgJIACgEIAAgCIAAgBIgCAGgAgShFIgCAGIgCAHIAAAEIABgDIACgGIACgHIAAgEIgBADgAgDhwIgDAHIgEAKIgDAJIgDALIAFgNIAEgMIAEgJIACgEIAAgCIgCADg");
	this.shape_2.setTransform(127.2202,-268.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1D4A88").s().p("AAnB3IgFgCIgCgBIgEgDIgEgEIgDgFQgDgFgCgHQgBgHAAgLIAAgKIABgLIABgLIADgOIACgKIAAgEIgCABIgFAGIgGAHIgFAKIgHANIgKASIgJATIgGAOQgCAFgCAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAgBgBIgCgBIgDgBQgCABgDgDQgDgCgBgIQgBgHAAgLIAEgZIAGgeIAJgeIANgiIAOghIAMgaQAMgVAFAKQAAAAABABQAAABAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIABAFIgDAPIgLAcIgIAVIgFAPIgFAMIgDANIgFAPIgFANIgCAJIgBAFIADgEIAFgJIAHgMIAHgMIAGgJIAGgFQAEgEAEAAQAEgBADADIACACIAEACIAIAFQAEADABADQACAFgBALIgFAYIgGAbIgCAVQAAALABAEQACAFAEABIAFADIgDAEIgFABgAAUhrIgEAJIgGAOIgHAPIgGAQIgFANQgPAogIAcQgIAegCAZIAAAEIADgQIAEgWIAFgWIAHgYIAJgZIAHgTIAIgVIAJgWIAIgRIADgGIAAgDIgCADgAAlAMIgCAJIgDANIgCAMIgCALIgBAIIgBAKIgBAFIACgLIADgOIABgKIADgKIACgKIABgJIABgGIAAgDIgBAFgAgkBHIAAADIAAADIAAADIAAgDIABgDIAAgDIAAgEgAAXBIIAAABIAAAAIABgCIgBAAIAAABgAAfA9IAAADIABAAIAAgEIgBAAIAAABgAAQhYIgFALIgHAQIgGASIgHASIgFAOIgHAUIgGAVIgFASIgCANQgBACABAAQAAABAAgBQAAAAABgCQAAgBABgDIADgNIAEgPIADgMIAEgLIAFgOIAGgTIADgHIADgJIAEgKIAEgLIAEgLIAEgJIADgIIgCAEgAAYA8IABACIAAgBIAAgCIgBgBIAAACgAAhAxIAAADIgBADQAAAEABgFIABgGIAAgBIgBACgAAZA1IAAACIABAAIAAgDIgBgBIAAACgAAbAvQAAAAAAABQAAAAAAABQAAAAAAAAQAAAAAAgBIAAgDIAAAAIAAACgAAnAZIgCAHIgCAIIAAAFIAAgCIACgFIABgHIACgGIgBgBIAAABgAAcAoIAAACIAAAAIAAgCIAAgBIAAABgAAdAkIAAABIABgCIgBgBIAAACgAAeAeIAAABIABgCIgBAAIAAABgAAfAZIAAABIABAAIAAgDIgBAAIAAACgAAgATIABACIAAgCIgBgBIAAABgAApARQgBAAAAABQAAAAAAAAQAAABABAAQAAAAAAAAIAAgDIAAgBIAAACgAAhANQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAAgCIgBADgAAJhbIgBAEIAAAAIADgEIABgDIgDADgAAWhmIgCADIgCAFIACgDIACgDIABgCIgBAAg");
	this.shape_3.setTransform(116.9388,-278.2729);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1D4A88").s().p("AAKB9IgDgBIgCAAIgHgCIgIgGIgGgIIgFgJIgEgLIgCgPIgCgNIgHARIgJAUIgHAOIgGAIIgGAEQgEACgDgCIgEgBIgEgBIgIgFQgGgEgCgFQgJgOgDgUQgDgTACgYIAEgaIAGgcIAIgeIAKgcIAJgWIAIgPQAJgLAFAHIADACIAFACQADACAAAEIgCAKIgGAUIgNAtIgKAsIgGAoQgCATAAAPIABALIABAJIACAIIABACIAEgEIAGgJIAHgMIAGgNIADgJIAFgPIAGgSIAGgSIAFgOIACgKIAEgNIADgQQAGgYAGgRQAGgRAGgHQAHgHAFAEIACABIADACIADACIAAAFIAAAIIgDAOIgLA3IgHAkIgEAaIgBAVIABASIACARIACANQACAEACAAIAEgBIAFgGIAGgHIAGgJQAKgQALgcQAKgcAKgiIAFgSIADgLIAEgQIAEgTIADgSIACgNIABgGIABgEIACgCIADABQADACACADIADAHIgBAGIgBAMIgCANIgBALIgHAcIgJAfIgLAhIgMAjQgPAjgKAQQgLAQgMABIgCAAQgDAAgDgCgAgJAGIgDATIgCAVIAAATIABAQIABADIAAgQIAAgTIABgQIABgOIACgMIABgJQgBACgBAGgAg6hlIgEAKIgFAPIgFAPIgMAqIgHAmQgDATgBAPQAAAPACALIABAFIgBgQIAAgRIAAgMIAFggIAIgkIALgmIALgfIACgGIAAgCIgCAFgAAEgmIgEAUIgEAXIgDAVIgCALIAAAOIAAAMIAAAJQAAAAAAABQAAAAAAAAQAAAAAAgBQAAAAAAgBIABgKIAAgPIABgNIAEgaIAFgeIADgQIABgHIgCAIgAgzhrIgFAMIgGARIgGASIgFARIgDAMIgBAFIgDAKIgFAYIgEAYIgBAVIAAARQAAABAAAAQAAABAAAAQAAAAABAAQAAAAAAgBIAAgLIABgPIABgOIAFgfIAIgiIAKgiIAMggIADgKIABgDgAgQBGIAAgBIAAgFIgBgFQgBgEABAJIABAFgAhiA5IABAFIAAAFQAAACAAgCIAAgFIAAgEIgBgBIAAAAgAgRAwIABADIAAgDIgBgDgAhiAuIABACIAAgDIAAAAIgBABgAgQAnIAAACIAAAAQABgBAAAAQAAAAAAgBQAAAAgBAAQAAgBAAAAIAAgBIAAACgAgQAfQAAABAAAAQAAABAAAAQABAAAAAAQAAAAAAAAIAAgEIgBAAIAAACgAgPAYQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAgBIAAgDIAAAAIAAACgAAUhiIgEAKIgDAMIgBAFIAAABIABgCIACgGIADgLIAEgLIAAgEIgCAGgAAPheIgCAFIgDAGIAAAEIABgBIADgIIACgGIAAgDIgBADg");
	this.shape_4.setTransform(102.2682,-278.2774);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1D4A88").s().p("AAMAXIgEgDIgEgEIgBgEQgBgCABgFIACgJIAGgKIAFgHQAGgGAGAFIACADIgDAEIgFAHIgCAEIABABQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIAEACIADAFIAAADQgBAGgFAFQgEAGgFAAgAgUAXIgEgDIgDgEIgDgEIAAgHIAEgJIAEgKIAGgHQAGgGAFAFIADADIgDAEIgFAHIgDAEIACABQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABAAIADACIADAFIAAADQgBAGgFAFQgEAGgEAAg");
	this.shape_5.setTransform(87.5,-291.494);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgdA3IAAhsIAZAAIAAASIAAAAQADgJAGgGQAGgEALAAIAFAAIAEAAIAAAYIgGgBIgHgBQgGABgFADQgGADgCAFQgCAGAAAIIAAA9g");
	this.shape_6.setTransform(59.65,-272.65);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdAzQgJgFgFgKQgFgJAAgOIAAhEIAaAAIAABAQAAAMAGAGQAFAGALAAQAGAAAGgDQAFgDADgFQADgGAAgJIAAg+IAaAAIAABtIgZAAIAAgSIAEgKIgEAAIAAAKQgFAIgFAEQgKAIgNAAQgLAAgJgFgAAYAkgAAYAaIAEAAIgEAKg");
	this.shape_7.setTransform(49.3,-272.475);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgbAyQgMgHgHgNQgHgNAAgRQAAgQAHgNQAHgNAMgHQAMgHAPAAQAQAAAMAHQAMAHAHANQAHANAAAQQAAARgHANQgHANgMAHQgMAHgQAAQgPAAgMgHgAgOgeQgGAEgDAIQgDAIAAAKQAAALADAIQADAIAGAEQAGAFAIAAQAJAAAGgFQAGgEADgIQADgIAAgLQAAgKgDgIQgDgIgGgEQgGgFgJAAQgHAAgHAFg");
	this.shape_8.setTransform(37.125,-272.575);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMBMIAAg6Ig5heIAgAAIAbAwIAIANIACAIIgCAHIAGAAIgEgHIAEgIIAHgNIAbgwIAgAAIg4BeIAAA6gAgCAAIACgHIAEAHgAAAgHg");
	this.shape_9.setTransform(25.425,-274.75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgWA1QgKgEgHgIQgGgIgBgLIAZgBQABAIAGAEQAGAFAIAAQAKAAAFgEQAGgEAAgGQAAgFgEgCQgEgEgHgBIgSgEQgQgDgIgHQgIgIAAgMQAAgLAGgHQAFgIAKgEQAKgEANAAQANAAAJAEQAKAEAGAIQAGAIAAALIgYABQAAgHgGgFQgFgFgJAAQgHAAgGAEQgFAEAAAGQAAAEAEAEQAEADAHABIATAEQAQAEAHAGQAIAHAAAMQAAALgGAIQgGAIgKAEQgLAEgNAAQgNAAgKgEg");
	this.shape_10.setTransform(8.025,-272.575);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgQAcIAIg3IAZAAIgQA3g");
	this.shape_11.setTransform(0.425,-279.575);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgHA/QgHgIAAgOIAAg8IgSAAIAAgUIASAAIAAAUIAAgUIAAgeIAYAAIAAAeIAXAAIAAAUIgXAAIAAgUIgYAAIAYAAIAAAUIgYAAIAYAAIAAA4QAAAGADADQACACAHAAIAFAAIAGAAIAAAVIgHAAIgJABQgQAAgIgHgAAKgng");
	this.shape_12.setTransform(-6.05,-274);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgdA1QgIgEgFgHQgFgHAAgLQAAgKAEgFQADgHAGgCQAGgEAIgBIAQgDIAPgDIAIgCQADgCAAgEIAAgBQAAgEgCgEQgDgDgEgCQgEgCgHAAQgFAAgFACQgFACgDADQgCADgBAFIgZgBQABgLAGgIQAHgHAKgEQAKgFANAAQAKAAAIADQAIACAGAFQAGAEAEAIQADAHAAAIIAABKIgaAAIAAgPIAAAAQgDAEgEAFQgEAEgGACQgGACgIAAQgLAAgJgEgAASAEIgFABIgIACIgGABIgKADQgFACgDACQgDAEAAAEQAAAFADADQACAEAEABQAEABAGABQAIAAAFgEQAGgDADgFQADgFAAgHIAAgLg");
	this.shape_13.setTransform(-15.575,-272.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAXBMIAAhAQAAgMgGgFQgGgHgKAAQgGAAgGAEQgEACgEAGQgDAFAAAJIAAA+IgaAAIAAiYIAaAAIAAA9IgFAKIAFAAIAAgKQAEgHAGgEQAJgJANABQALgBAKAGQAIAFAFAJQAFAKAAANIAABEgAgbgFIAFgKIAAAKg");
	this.shape_14.setTransform(-27.2,-274.75);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAeBMIgXhWIgFgWIgCgHIAEgSIgGAAIACASIgCgSIAGAAIgEASIAAAHIgFAWIgXBWIgfAAIgqiYIAdAAIAUBSIAEARIAEASIABAGIABgGIAEgSIAEgRIAVhSIAbAAIAVBSIAEARIAEASIABAGIgCAMIAFAAIgDgMIABgGIAEgSIAEgRIAUhSIAdAAIgpCYgAgpA7IgCgMIACAMIgFAAIADgMIgDAMIAFAAgAAqA7IACgMIADAMgAgpA7gAAsAvg");
	this.shape_15.setTransform(-43.675,-274.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.1,-300.7,215.79999999999998,47.099999999999994);


(lib.T3_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#004B8D").s().p("AgsBCIAAiDIBZAAIAAAUIhBAAIAAAjIA8AAIAAATIg8AAIAAAlIBBAAIAAAUg");
	this.shape.setTransform(155.2,-274.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#004B8D").s().p("AAZBCIgZgxIgaAAIAAAxIgXAAIAAiDIAyAAQAOAAALAGQAKAFAGAJQAFAJAAANQAAAOgFAIQgGAIgLAGIgDABIAcA0gAgagBIAaAAQAIAAAEgCQAGgDADgFQADgFAAgGQAAgHgDgFQgDgGgGgCQgGgDgGAAIgaAAg");
	this.shape_1.setTransform(144.1,-274.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#004B8D").s().p("AgsBCIAAiDIBZAAIAAAUIhCAAIAAAjIA9AAIAAATIg9AAIAAAlIBCAAIAAAUg");
	this.shape_2.setTransform(132.775,-274.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#004B8D").s().p("AAfBCIAAg6Ig8AAIAAA6IgYAAIAAiDIAYAAIAAA2IA8AAIAAg2IAWAAIAACDg");
	this.shape_3.setTransform(120.65,-274.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#004B8D").s().p("AAAAxQgKAAgJgEQgHgCgHgIQgFgGgBgKIAVgBQACAHAFADQAEAEAHAAQAHAAAHgDQAEgDAAgFQAAgEgDgDQgDgDgHgBIgPgDQgNgDgHgGQgHgGAAgLQAAgJAFgGQAEgHAJgDQAJgEAKAAQALAAAJAEQAHADAGAHQAFAHABAJIgWAAQAAgFgEgEQgGgEgHAAQgGAAgFADQgEAEAAAEQAAAEAEADQACACAHACIAQADQANADAHAFQAGAHABAKQAAAJgGAHQgFAHgIADQgLAEgLAAg");
	this.shape_4.setTransform(105.35,-272.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#004B8D").s().p("AgFA2QgHgGAAgMIAAg0IgQAAIAAgSIAQAAIAAgZIAVAAIAAAZIATAAIAAASIgTAAIAAAwQAAAGADABQABACAGAAIAJAAIABASIgOABQgOAAgGgGg");
	this.shape_5.setTransform(97.6,-273.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#004B8D").s().p("AgZAwIAAheIAVAAIAAAQIABAAQACgIAFgEQAGgFAJAAIAEAAIADABIAAAUIgKgBQgFAAgFADQgGADAAAEQgDAEAAAIIAAA1g");
	this.shape_6.setTransform(91.325,-272.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#004B8D").s().p("AgYAtQgIgDgEgGQgEgGAAgKQAAgHADgGQACgEAGgDQAGgEAGgBIAagEIAIgCQACgCAAgDIAAgBQAAgEgCgDQgCgDgEgBQgDgCgGAAQgFAAgEACQgDABgDADIgDAHIgVgBQABgJAFgHQAFgGAJgEQAIgEALABQAKAAAGACQAHACAFAEQAGAEACAGQADAGAAAHIAAA/IgWAAIAAgNIAAAAQgDAFgDADIgJAFQgEABgIAAQgJAAgHgDgAAQADIgRAEIgJACQgEACgCACQgCACAAAFQAAAEACADQACACADABQAEACAFAAQAGAAAFgDQAEgCAEgEQACgFAAgGIAAgKg");
	this.shape_7.setTransform(82.525,-272.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#004B8D").s().p("AgFA2QgHgGAAgMIAAg0IgQAAIAAgSIAQAAIAAgZIAVAAIAAAZIATAAIAAASIgTAAIAAAwQAAAGADABQABACAGAAIAJAAIABASIgOABQgOAAgGgGg");
	this.shape_8.setTransform(74.325,-273.625);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#004B8D").s().p("AAAAxQgKAAgJgEQgJgDgFgHQgGgHAAgJIAVgBQABAGAFAEQAGAEAGAAQAIAAAFgDQAFgDAAgFQAAgEgDgDQgFgDgFgBIgPgDQgNgDgHgGQgHgGAAgLQAAgJAFgGQAEgHAJgDQAJgEAKAAQALAAAIAEQAJADAFAHQAFAHABAJIgWAAQAAgFgEgEQgGgEgHAAQgGAAgEADQgFAEAAAEQAAAEAEADQACACAHACIAQADQANADAHAFQAGAHABAKQAAAJgGAHQgFAHgJADQgKAEgLAAg");
	this.shape_9.setTransform(66.55,-272.375);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#004B8D").s().p("AAYBCIgYgxIgaAAIAAAxIgXAAIAAiDIAxAAQAQAAAJAGQALAFAGAJQAFAKABAMQgBANgFAJQgGAIgLAGIgCABIAbA0gAgagBIAaAAQAHAAAGgCQAFgDADgFQADgFAAgGQAAgHgDgFQgDgGgFgCQgGgDgHAAIgaAAg");
	this.shape_10.setTransform(52.25,-274.25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#004B8D").s().p("AgsBCIAAiDIBZAAIAAAUIhCAAIAAAjIA9AAIAAATIg9AAIAAAlIBCAAIAAAUg");
	this.shape_11.setTransform(40.925,-274.25);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#004B8D").s().p("AAeBCIAAg6Ig7AAIAAA6IgXAAIAAiDIAXAAIAAA2IA7AAIAAg2IAYAAIAACDg");
	this.shape_12.setTransform(28.8,-274.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#004B8D").s().p("AgZAwIAAheIAVAAIAAAQIABAAQACgIAFgEQAGgFAJAAIAEAAIADABIAAAUIgKgBQgFAAgFADQgGADAAAEQgDAEAAAIIAAA1g");
	this.shape_13.setTransform(15.225,-272.45);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#004B8D").s().p("AgXArQgLgHgFgKQgGgLAAgPQAAgNAGgMQAFgLALgGQALgGAMAAQAOAAAKAGQAKAGAHALQAFANAAAMQAAAPgFALQgGAKgLAHQgKAGgOAAQgMAAgLgGgAgLgaQgFAEgEAHQgCAHAAAIQAAAJACAHQAEAHAFAEQAFADAGAAQAHAAAGgDQAGgEACgHQADgHAAgJQAAgIgDgHQgEgHgEgEQgFgDgIAAQgGAAgFADg");
	this.shape_14.setTransform(6.35,-272.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#004B8D").s().p("AgMBCIAAhLIgRAAIAAgSIARAAIAAgMQAAgJAEgGQACgFAGgDQAHgDAJAAIAOAAIgBASIgEAAIgFAAQgFAAgDACQgDAEAAAFIAAAJIAUAAIAAASIgUAAIAABLg");
	this.shape_15.setTransform(-1.925,-274.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#004B8D").s().p("AABAxQgNAAgKgGQgKgGgGgLQgGgMAAgOQAAgNAGgMQAGgKAKgHQAJgGANAAQALAAAHAEQAIACAGAHQAGAHADAJQAEAIAAALIAAAGIhDAAQABAHACAFQAEAHAEADQAFAEAHAAQAGAAAEgCIAHgFQADgDACgEIAUABQgBAIgGAIQgHAGgIAEQgKAEgKAAgAgLgbQgFADgDAGQgCAEgBAGIAtAAQAAgGgCgEQgDgGgFgDQgFgDgIAAQgGAAgFADg");
	this.shape_16.setTransform(-14.275,-272.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#004B8D").s().p("AgZAwIAAheIAWAAIAAAQIAAAAQACgIAFgEQAHgFAIAAIAEAAIADABIAAAUIgEgBIgGAAQgFAAgFADQgFAEgCADQgCAFAAAHIAAA1g");
	this.shape_17.setTransform(-22.1,-272.45);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#004B8D").s().p("AgYAtQgIgDgEgGQgEgGAAgKQAAgHADgGQACgEAGgDQAGgEAGgBIAagEIAIgCQACgCAAgDIAAgBQAAgEgCgDQgCgDgEgBQgDgCgGAAQgFAAgEACQgEACgCACIgDAHIgVgBQABgJAFgHQAFgGAJgEQAIgEALABQAKAAAGACQAHACAFAEQAGAEACAGQADAGAAAHIAAA/IgWAAIAAgNIAAAAQgDAFgDADIgJAFQgEABgIAAQgJAAgHgDgAAQADIgRAEIgIACQgFACgCACQgCACAAAFQAAAEACADQABACAEABQAEACAFAAQAGAAAFgDQAEgCAEgEQACgFAAgGIAAgKg");
	this.shape_18.setTransform(-30.875,-272.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#004B8D").s().p("AACBDQgQAAgOgIQgOgHgIgQQgIgPAAgVQAAgUAIgPQAIgPAOgIQAOgJAQAAQAMAAAJAEQAKADAHAGQAGAGAGAJQAEAHADAMIgYAAQgBgGgDgFQgEgGgDgCQgEgDgGgCQgHgCgEAAQgLAAgJAGQgIAGgFAKQgEALAAANQAAAOAEALQAFAKAIAGQAJAGALAAQAHAAAEgCQAGgCAEgDQAEgEADgEQADgFABgGIAYAAQgBAJgGAKQgEAIgIAHQgIAGgJADQgLAEgKAAg");
	this.shape_19.setTransform(-42.125,-274.225);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48,-281,207.7,13.600000000000023);


(lib.T2_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAFQgCgCAAgDQAAgCACgCQABAAAAgBQABAAAAAAQABgBABAAQAAAAAAAAQADAAACACQACACAAACQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBAAQgCADgDAAIgEgCg");
	this.shape.setTransform(168.4,-261.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggAxQgGgHAAgNQAAgNAGgNQAGgLALgHQAJgGANAAIAPACIAHgkIAKAAIgVBiIAAAMIgKAAQAAgGADgOIgBAAQgGAKgFAGQgGAFgJAAQgKAAgGgHgAgLgIQgIAGgEAIQgFAKAAAMQAAAUAOAAQAGAAAGgFQAEgEAGgKQAGgJACgLIAEgUQgGgCgIAAQgJAAgIAFg");
	this.shape_1.setTransform(164.025,-266.425);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgNAFgJQAFgKAKgIQAJgGAKAAQAKAAAGAFQAGAFAAAIQAAAOgMAGQgOAFgaAAIAAAEIAAAAQAAALAGAGQAFAFAKAAQAJAAALgGIgBAJQgJAFgLAAQgOAAgIgIgAgJgWQgJAIgCAMQAUAAALgEQALgEAAgJQAAgFgEgDQgEgDgGAAQgKAAgHAIg");
	this.shape_2.setTransform(156.325,-264.725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AggAxQgFgGgBgOQAAgNAHgNQAEgLAMgHQAJgGAMAAIAQACIAIgkIAJAAIgTBWIgDAYIgJAAIADgUIgBAAQgGALgGAFQgGAFgIAAQgKAAgGgHgAgLgIQgHAFgFAJQgFALAAALQAAAUAOAAQAGAAAGgFQAEgEAGgKQAFgHADgNIAFgUIgBAAQgGgCgIAAQgIAAgJAFg");
	this.shape_3.setTransform(149.2,-266.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLAzQgDgDAAgFIACgNIALgzIAIAAIgLA+QAAAFAEAAIAGgBIgBAIQgEABgDAAQgGAAgDgDgAAIgoQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAgBAAAAIACgGIAFgBQABAAAAAAQABAAABAAQAAABABAAQAAAAABAAQACACAAAEQAAAAAAABQAAABgBAAQAAABAAAAQgBABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAg");
	this.shape_4.setTransform(143.575,-266.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgdAhQgFgGAAgJIAAgHIALgwIAKAAIgMA2QAAANANAAQAFAAAGgEQAGgFAGgIQAGgJABgGIAIgjIAJAAIgLA1IgEAVIgJAAIADgUQgHALgHAFQgGAFgJAAQgKAAgEgFg");
	this.shape_5.setTransform(137.65,-264.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgmAyIACgJQAKAHALAAQAMAAAHgHQAHgHAEgRIADgQQgHAMgGAEQgFAGgIAAQgLAAgFgIQgGgGAAgNQAAgOAGgMQAGgLALgHQAKgHAMAAIAYADIgPBDQgEAXgKAJQgKAJgQAAQgLAAgLgGgAgDgpQgIAFgFAKQgEAKAAAMQAAASAOAAQAGAAAFgEQAHgGAFgIQAEgJADgKIAEgXQgGgBgJAAQgJAAgHAGg");
	this.shape_6.setTransform(129.175,-263.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AggAxQgGgGAAgOQAAgNAGgNQAGgLALgHQAKgGAMAAIAPACIAIgkIAJAAIgTBWIgBAMIgBAMIgKAAIADgUIgBAAQgGALgFAFQgGAFgJAAQgKAAgGgHgAgLgIQgIAGgEAIQgFAMAAAKQAAAUAOAAQAGAAAGgFQAGgGAEgIQAGgJACgLIAEgUQgGgCgIAAQgJAAgIAFg");
	this.shape_7.setTransform(118.175,-266.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAPAmIAKg2QAAgNgLAAQgHAAgGAFQgFAEgGAIQgGAIgBAHIgIAjIgJAAIAPhJIAJAAIgDATIAAAAQAGgKAHgGQAIgFAIAAQATAAAAAUIgLA3g");
	this.shape_8.setTransform(109.575,-264.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcAgQgGgHAAgNQAAgNAGgMQAGgNALgGQALgGALAAQAKAAAOACIgKAwIgCANIgCAMIgJAAQAAgGADgOIgBAAQgGALgHAGQgGAGgHAAQgKAAgGgIgAgHgZQgIAFgFALQgEAJAAALQAAAUAOAAQAGAAAFgFQAFgFAGgKQAGgJACgJIAEgWIgOgBQgKgBgHAGg");
	this.shape_9.setTransform(101.875,-264.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgLASIANgjIAKAAIgPAjg");
	this.shape_10.setTransform(91.525,-260.875);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AggAxQgGgGAAgOQABgNAFgNQAFgLAMgHQAKgGALAAIAQACIAHgkIAKAAIgTBWIgCAYIgKAAIADgUQgIAMgFAEQgGAFgIAAQgKAAgGgHgAgLgIQgHAFgFAJQgFALAAALQAAAUAOAAQAGAAAGgFQAFgFAGgJQAEgHADgNIAFgUIgBAAQgGgCgIAAQgIAAgJAFg");
	this.shape_11.setTransform(87.3,-266.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZAmIAKgwQAEgQAAgJIAJAAIgCARIAAAAQAEgKAGgFQAFgFAHABQAFgBADACIgCAKQgDgDgFABQgJAAgGAJQgIAMgCANIgHAgg");
	this.shape_12.setTransform(81.025,-264.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgcAgQgGgGAAgOQABgNAGgMQAGgNAKgGQALgGALAAQAKAAAOACIgMA9IgBAMIgKAAQAAgGADgOIgBAAQgHAMgGAFQgGAGgHAAQgKAAgGgIgAgHgZQgJAGgDAKQgFAJAAALQAAAUAOAAQAGAAAFgFQAFgFAHgKQAFgJACgJIAFgWIgBAAQgHgBgHAAQgKgBgHAGg");
	this.shape_13.setTransform(74.2,-264.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgLAFgLQAFgLAKgHQAJgGAKAAQAKAAAGAFQAGAFAAAIQAAAOgMAGQgOAFgaAAIAAAEQAAALAGAGQAFAFAKAAQAKAAALgGIgCAJQgJAFgLAAQgOAAgIgIgAgJgWQgJAJgCALQAVAAALgEQAKgEAAgJQAAgFgEgDQgDgDgHAAQgJAAgIAIg");
	this.shape_14.setTransform(66.875,-264.725);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAPA4IAJgsIABgMQAAgMgLAAQgHAAgGAFQgGAEgFAHQgFAIgCAIIgIAjIgJAAIAYhuIAAABIAJAAIgMA2IABAAQAMgUAQAAQAKAAAFAFQAEAGAAAJIAAACIgLA2g");
	this.shape_15.setTransform(59,-266.525);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgLASIANgjIAKAAIgPAjg");
	this.shape_16.setTransform(48.8,-260.875);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAPAmIAKg2QAAgNgLAAQgHAAgGAFQgFAEgGAIQgGAIgBAHIgHAjIgKAAIAPhJIAJAAIgDATIABAAQAFgKAHgGQAJgFAHAAQATAAAAAUIgCAPIgJAog");
	this.shape_17.setTransform(43.8,-264.825);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgNAFgJQAFgKAKgIQAJgGAKAAQAKAAAGAFQAGAFAAAIQAAAOgMAGQgOAFgaAAIAAAEIAAAAQAAAKAFAHQAGAFAKAAQAJAAALgGIgBAJQgJAFgLAAQgOAAgIgIgAgJgWQgJAIgCAMQAUAAALgEQALgEAAgJQAAgFgEgDQgEgDgHAAQgJAAgHAIg");
	this.shape_18.setTransform(36.625,-264.725);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgNAFgJQAFgKAKgIQAJgGAKAAQAKAAAGAFQAGAFAAAIQAAAOgMAGQgOAFgaAAIAAAEQAAALAGAGQAFAFAKAAQAJAAAMgGIgCAJQgJAFgLAAQgOAAgIgIgAgJgWQgJAIgCAMQAVAAAKgEQALgEAAgJQAAgFgEgDQgDgDgHAAQgKAAgHAIg");
	this.shape_19.setTransform(29.625,-264.725);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgRAmQgEgBgFgDIACgJIABAAIAIAFQAFABAFAAQAIAAADgDQAFgDAAgHQAAgEgDgDQgCgCgHgFQgHgEgEgFQgEgFAAgGQAAgKAHgGQAHgGALAAIAJABIAJADIgCAJQgHgFgKAAQgGAAgEAEQgEAEAAAFQAAAFACADQAEAEAEADQAJAEADAFQAEAEAAAHQAAAKgHAGQgHAFgMAAg");
	this.shape_20.setTransform(22.975,-264.725);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgRAmQgEgBgEgDIABgJIABAAIAIAFIAKABQAHAAAEgDQAFgDAAgHQAAgDgDgEIgJgHQgHgEgEgFQgEgFAAgGQAAgKAHgGQAHgGALAAIAJABIAIADIgCAJQgGgFgKAAQgHAAgDAEQgFAEABAFQAAAEACAEQADADAFAEQAIADAEAGQAEAFAAAGQAAAKgHAGQgIAFgLAAg");
	this.shape_21.setTransform(13.3,-264.725);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLA1QgDgDAAgFQAAgGACgHIAShXIAJAAIgUBiQAAAFAFAAIAGgBIgBAIQgDABgEAAQgGAAgDgDg");
	this.shape_22.setTransform(9.3,-266.45);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgXAfQgIgIABgPQgBgLAGgLQAFgLAKgHQAJgGAKAAQAJAAAHAFQAHAFAAAIQAAAOgOAGQgNAFgZAAIAAAEIgBAAQAAAKAFAHQAGAFAKAAQAKAAAKgGIgCAJQgJAFgKAAQgPAAgHgIgAgJgWQgJAIgBAMQAUAAAKgEQALgEAAgJQAAgFgEgDQgEgDgGAAQgKAAgHAIg");
	this.shape_23.setTransform(3.9,-264.725);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQgBgLAGgLQAFgLAKgHQAIgGALAAQAJAAAHAFQAHAFAAAIQgBAOgNAGQgOAFgYAAIAAAEIgBAAQAAAKAFAHQAGAFAKAAQAJAAAMgGIgCAJQgKAFgKAAQgOAAgIgIgAgKgWQgHAIgDAMQAVAAALgEQAKgEAAgJQAAgFgEgDQgDgDgIAAQgJAAgIAIg");
	this.shape_24.setTransform(-3.1,-264.725);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgdBFIAUhbIgNAAIABgIIAOAAIADgOQAEgYAVAAQAFAAAEABIgCAJQgDgCgFAAQgHAAgDAFQgFAEgBAJIgDAMIATAAIgCAIIgSAAIgUBbg");
	this.shape_25.setTransform(-7.75,-265.35);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAPAmIALg2QAAgNgMAAQgGAAgHAFQgFAEgGAIQgFAIgCAHIgIAjIgJAAIAQhJIAIAAIgDATIABAAQAGgKAGgGQAIgFAJAAQASAAAAAUIgCAPIgJAog");
	this.shape_26.setTransform(-18.95,-264.825);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgcAgQgGgHAAgNQAAgNAGgMQAGgNALgGQALgGALAAQAKAAAOACIgOBJIgJAAIACgUQgGALgHAGQgGAGgIAAQgKAAgFgIgAgHgZQgIAFgFALQgEAJAAALQAAAUAOAAQAGAAAFgFQAFgFAGgKQAGgJACgJIAEgWIgOgBQgKgBgHAGg");
	this.shape_27.setTransform(-26.625,-264.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAlAmIAJgqIACgNQAAgMgLAAQgGAAgGAEQgGAFgFAIQgFAIgCAGIgHAkIgJAAIAKg2QAAgNgKAAQgEAAgIAEQgGAFgFAJQgGAHgBAGIgIAkIgKAAIAQhJIAJAAIgDATQAOgWAPABQAIgBAEAGQAEAFAAALQAHgKAHgGQAIgGAIABQASgBAAAVIgCAPIgJAog");
	this.shape_28.setTransform(-37.1,-264.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgZAgQgIgIABgOQAAgNAEgLQAGgLAJgHQAIgGALAAQANAAAHAIQAHAHAAAOQAAAOgEAKQgGAMgJAGQgIAGgLAAQgNAAgHgHgAgOgSQgJALAAARQAAAKAEAGQAGAFAIAAQAHAAAIgFQAGgFAEgKQAEgIAAgLQAAgLgEgGQgGgFgIAAQgMAAgIAMg");
	this.shape_29.setTransform(-47,-264.725);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AADAlIgEg2IAAgHIgBAEIggA5IgIAAIgHhJIAKAAIAEA6IAAABIgBAEIABAAIADgHIAfg4IAGAAIAEA7IgBAEIABAAIAgg/IAJAAIgmBJg");
	this.shape_30.setTransform(-55.3,-264.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgsA2IABgIIABAAIAGABQAFAAAEgEQAEgCAFgHIAJgPIgNhJIAJAAIAKA6IAAAGIABAAIACgEIAjg8IAKAAIg2BXQgGALgHAGQgHAFgIAAg");
	this.shape_31.setTransform(171.85,-280.95);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgZAmIAKgwQAEgOABgLIAJAAIgDARIABAAQADgKAGgFQAGgFAHABQAEgBADACIgBAKIgBAAQgDgDgFABQgIAAgHAJQgHALgDAOIgHAgg");
	this.shape_32.setTransform(166.175,-282.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgLAFgLQAFgLAKgHQAIgGALAAQAJAAAHAFQAHAFAAAIQgBAOgNAGQgOAFgZAAIAAAEIAAAAQAAAKAGAHQAFAFAKAAQAKAAALgGIgCAJQgKAFgLAAQgNAAgIgIgAgKgWQgHAIgDAMQAVAAALgEQAKgEAAgJQAAgFgEgDQgDgDgIAAQgJAAgIAIg");
	this.shape_33.setTransform(159.9,-282.725);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgTAlIgNhJIAKAAIAJA+IAjg+IALAAIgsBJg");
	this.shape_34.setTransform(153.675,-282.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgNAFgJQAFgKAKgIQAJgGAKAAQAKAAAGAFQAGAFAAAIQAAAOgMAGQgOAFgaAAIAAAEQAAALAGAGQAFAFAKAAQAJAAAMgGIgCAJQgJAFgLAAQgOAAgIgIgAgJgWQgJAJgCALQAVAAALgEQAKgEAAgJQAAgFgEgDQgDgDgHAAQgJAAgIAIg");
	this.shape_35.setTransform(146.125,-282.725);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgNAFgJQAFgKAKgIQAJgGAKAAQAKAAAGAFQAGAFAAAIQAAAOgMAGQgOAFgaAAIAAAEIAAAAQAAALAGAGQAFAFAKAAQAJAAALgGIgBAJQgJAFgLAAQgOAAgIgIgAgJgWQgJAIgCAMQAUAAALgEQALgEAAgJQAAgFgEgDQgEgDgGAAQgKAAgHAIg");
	this.shape_36.setTransform(135.175,-282.725);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgZAmIAKgwQADgMABgNIAKAAIgDARQAEgJAGgGQAFgFAHABQAFgBADACIgBAKIgBAAQgDgDgFABQgIAAgHAJQgHALgDAOIgHAgg");
	this.shape_37.setTransform(129.575,-282.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgeAhQgEgGAAgJIACgPIAJgoIAKAAIgLA2QgBANAMAAQAHAAAFgEQAGgFAGgIQAGgIACgHIAHgjIAJAAIgPBKIgJAAIADgUQgHALgHAFQgGAFgJAAQgJAAgGgFg");
	this.shape_38.setTransform(122.75,-282.625);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgQAmQgFgBgEgDIACgJIAIAFIAKABQAHAAAEgDQAFgEAAgGQgBgDgCgEIgJgHQgGgEgFgFQgEgEABgHQgBgKAIgGQAGgGALAAIAJABQAEAAAFADIgDAJQgGgFgJAAQgHAAgEAEQgFAEABAFQgBAEADAEQADADAFAEQAJAEADAFQAEAEAAAHQAAAKgHAGQgIAFgLAAg");
	this.shape_39.setTransform(115.55,-282.725);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgmAyIACgJQAKAHALAAQALAAAHgHQAIgIAEgQIADgQIAAAAQgGAKgHAGQgFAGgIAAQgLAAgFgIQgGgGAAgNQAAgOAGgMQAGgLAKgHQAKgHAMAAIAZADIgPBDQgFAXgKAJQgJAJgRAAQgLAAgKgGgAgDgpQgIAEgFALQgEAKAAAMQAAASANAAQAHAAAFgEQAIgIAEgGQAFgLACgIIAEgXQgGgBgJAAQgJAAgHAGg");
	this.shape_40.setTransform(104.625,-281.05);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAPAmIAKg2QABgNgMAAQgHAAgGAFQgGAEgFAIQgFAHgCAIIgIAjIgJAAIAPhKIAAABIAJAAIgDATIAAAAQAHgLAGgFQAIgFAIAAQATAAAAAUIgLA3g");
	this.shape_41.setTransform(96.8,-282.825);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgLAzQgDgDAAgFIACgNIALgzIAIAAIgLA+QAAAFAEAAIAGgBIgBAIQgEABgDAAQgGAAgDgDgAAIgoQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAQgBgBAAAAQAAgBAAAAIACgGIAFgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABAAQACACAAAEQAAAAAAABQgBABAAAAQAAABAAAAQgBABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_42.setTransform(91.675,-284.25);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAJA3IgZgmIgBAAIgIAmIgJAAIAYhuIAJAAIgPBFIAAAAIAnggIAMAAIgqAiIAbAng");
	this.shape_43.setTransform(86.675,-284.5);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgcAgQgGgGABgOQAAgNAFgMQAHgNAKgGQALgGALAAQAKAAANACIgLA9IgBAMIgKAAQAAgGACgOQgHAMgGAFQgFAGgIAAQgLAAgFgIgAgHgZQgIAGgFAKQgEAJAAALQAAAUAOAAQAGAAAFgFQAGgFAGgKQAFgJACgJIAEgWIAAAAQgGgBgIAAQgKgBgHAGg");
	this.shape_44.setTransform(79,-282.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAlAmIAJgqIACgNQAAgMgLAAQgGAAgGAEQgGAFgFAIQgFAIgCAGIgHAkIgJAAIAKg2QAAgNgKAAQgFAAgHAEQgGAFgFAJQgGAHgBAGIgIAkIgJAAIAPhJIAJAAIgDATQANgWAQABQAIgBAEAGQAEAFAAALQAGgKAIgGQAJgGAHABQASgBAAAVIgCAPIgJAog");
	this.shape_45.setTransform(68.55,-282.8);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgTAjIALg1IgNAAIACgIIANAAIAEgTIAJgDIgFAWIAUAAIgCAIIgTAAIgKA0QAAAEABABQACACAEAAQACAAAIgDIgCAIIgGACIgFABQgOAAAAgOg");
	this.shape_46.setTransform(56.875,-283.725);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgeAhQgEgGAAgJIALg3IAKAAIgLA2QAAANAMAAQAFAAAGgEQAGgFAGgIQAFgIADgHIAHgjIAJAAIgPBKIgJAAIADgUQgHALgHAFQgHAFgIAAQgJAAgGgFg");
	this.shape_47.setTransform(50.2,-282.625);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgZAgQgHgIAAgOQAAgLAEgNQAGgLAJgHQAJgGAKAAQANAAAHAIQAIAIgBANQAAAOgEAKQgGAMgJAGQgIAGgLAAQgMAAgIgHgAgOgSQgJALAAARQAAAKAFAGQAFAFAIAAIABAAQAIAAAGgFQAHgGAEgJQADgKAAgJQAAgKgEgHQgGgFgIAAQgLAAgJAMg");
	this.shape_48.setTransform(42.1,-282.725);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgWA3QgHgCgEgDIAWhpIAJAAIgLA2QALgUAPAAQALAAAFAHQAFAHAAAMQAAAOgFAMQgGAMgKAHQgKAGgMAAIgNgBgAgBgIQgFAEgGAJQgFALgBAHIgFAVIAAABQAGADAJAAQAIAAAIgFQAIgGAFgKQAEgKAAgLQAAgKgDgEQgEgFgHAAQgGAAgGAFg");
	this.shape_49.setTransform(34.275,-284.425);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgcAgQgGgHAAgNQAAgNAGgMQAGgNALgGQALgGALAAQAKAAAOACIgMA9IgBAMIgKAAQAAgGADgOIgBAAQgGALgHAGQgGAGgHAAQgKAAgGgIgAgHgZQgIAFgEALQgFAJAAALQAAAUAOAAQAGAAAFgFQAGgGAGgJQAEgIADgKIAEgWQgGgBgIAAQgJgBgIAGg");
	this.shape_50.setTransform(26.575,-282.7);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgXAfQgIgIAAgPQABgLAFgLQAFgLAKgHQAJgGAKAAQAKAAAGAFQAGAFAAAIQABAOgNAGQgOAFgaAAIAAAEIAAAAQAAAKAGAHQAEAFALAAQAJAAALgGIgBAJQgKAFgLAAQgOAAgHgIgAgJgWQgIAIgDAMQAUAAAMgEQAKgEgBgJQAAgFgDgDQgEgDgGAAQgKAAgHAIg");
	this.shape_51.setTransform(15.3,-282.725);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgTAjIALg1IgNAAIACgIIANAAIAEgTIAJgDIgFAWIAUAAIgCAIIgUAAIgJA0QAAAEABABQACACADAAIALgDIgCAIIgGACIgFABQgOAAAAgOg");
	this.shape_52.setTransform(9.975,-283.725);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgcAgQgGgGABgOQAAgNAFgMQAHgNAKgGQALgGALAAQAKAAANACIgLA9IgBAMIgKAAQAAgGADgOIgBAAQgHAMgGAFQgGAGgHAAQgLAAgFgIgAgHgZQgJAGgEAKQgEAJAAALQAAAUAOAAQAHAAAEgFQAFgFAHgKQAFgJACgJIAEgWIAAAAQgGgBgIAAQgJgBgIAGg");
	this.shape_53.setTransform(3.3,-282.7);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AAPAmIAKg2QABgNgMAAQgHAAgHAFQgFAEgFAIQgGAIgCAHIgHAjIgJAAIAPhKIAAABIAJAAIgDATIAAAAQAGgKAHgGQAIgFAIAAQATAAAAAUIgLA3g");
	this.shape_54.setTransform(-4.9,-282.825);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgaAgQgGgIgBgOQABgNAEgLQAFgLAKgHQAKgGAKAAQAMAAAHAIQAIAIAAANQAAAOgGAKQgFAMgJAGQgIAGgMAAQgMAAgIgHgAgPgSQgIALAAARQAAAKAFAGQAFAFAIAAQAJAAAFgFQAHgFAEgKQAEgIAAgLQAAgLgFgGQgFgFgIAAQgMAAgJAMg");
	this.shape_55.setTransform(-12.65,-282.725);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgLAzQgDgDAAgFIACgNIALgzIAIAAIgLA+QAAAFAEAAQAFAAABgBIgBAIIgHABQgGAAgDgDgAADgqIgCgEIACgGIAFgBQABAAABAAQAAAAABAAQAAABABAAQAAAAABAAQACACAAAEQAAAAAAABQgBABAAAAQAAABAAAAQgBABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAQgDAAgCgCg");
	this.shape_56.setTransform(-17.775,-284.25);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgRAmQgEgBgFgDIACgJIAJAFQAFABAFAAQAHAAAEgDQAEgDAAgHQAAgEgCgDQgCgCgHgFQgHgEgEgFQgEgEAAgHQAAgKAHgGQAHgGALAAIAJABQAFABAEACIgCAJQgHgFgKAAQgGAAgEAEQgEADAAAGQAAAFACADQACADAGAEQAJAEADAFQAEAEAAAHQAAAKgHAGQgHAFgMAAg");
	this.shape_57.setTransform(-22.825,-282.725);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgQAmQgFgBgEgDIACgJIAIAFIAKABQAHAAAEgDQAFgEAAgGQAAgDgDgEIgJgHQgGgEgFgFQgEgEABgHQAAgKAGgGQAHgGALAAIAJABQAEAAAEADIgCAJQgGgFgKAAQgGAAgEAEQgFAEABAFQAAAEACAEQADADAGAEQAIAEADAFQAEAEAAAHQAAAKgHAGQgIAFgLAAg");
	this.shape_58.setTransform(-28.55,-282.725);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgcAgQgGgHAAgNQAAgNAGgMQAGgNALgGQALgGALAAQAKAAAOACIgMA9IgBAMIgKAAQAAgGADgOIgBAAQgGALgHAGQgGAGgHAAQgKAAgGgIgAgHgZQgIAFgEALQgFAJAAALQAAAUAOAAQAGAAAFgFQAGgGAGgJQAEgIADgKIAEgWQgGgBgIAAQgKgBgHAGg");
	this.shape_59.setTransform(-35.125,-282.7);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgmA4IAShWIACgMIABgLIAJAAIgBAKIgBAKIAAAAQALgWAQAAQAKAAAGAHQAGAHAAAOQAAAOgGAMQgGAKgLAHQgKAHgLAAQgIAAgIgDIgIAkgAACgpQgFAFgFAJQgFAKgCAJIgEAUQAGADAJAAQAIAAAIgGQAIgFAFgJQAEgKAAgLQAAgVgOAAQgGAAgHAGg");
	this.shape_60.setTransform(-43.475,-281.075);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AAlAmIAJgqIACgNQAAgMgLAAQgFAAgHAEQgFAEgGAJQgGAJgBAFIgHAkIgJAAIAJgqIABgMQAAgNgKAAQgFAAgHAEQgGAFgGAJQgEAGgCAHIgIAkIgJAAIAPhJIAJAAIgDATIAAAAQANgWAQABQAIgBAEAGQAEAFAAALQAFgJAJgHQAIgGAIABQARgBAAAVIgCAPIgJAog");
	this.shape_61.setTransform(-57.375,-282.8);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgCAQIgBgfIAHAAIgBAfg");
	this.shape_62.setTransform(-64.075,-287.825);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AgPA0IAVhnIAKAAIgVBng");
	this.shape_63.setTransform(-67.9,-284.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69.5,-290,245.9,32.60000000000002);


(lib.T1_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAFQgCgCAAgDQAAgCACgCIAEgCIAFACIACAEIgCAFQgCACgDAAQgCAAgCgCg");
	this.shape.setTransform(170.25,-263.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgMAFgLQAGgKAJgHQAKgGAJAAQALAAAFAFQAGAFAAAIQAAANgMAHQgMAFgcAAIAAAEQAAALAGAFQAFAGAKAAQAIAAANgHIgCAKQgKAFgKAAQgOAAgIgIgAgJgXQgIAIgDANIAAAAQAWAAAJgEQALgEAAgJQAAgGgEgDQgDgCgHAAQgJAAgIAHg");
	this.shape_1.setTransform(165.975,-266.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUAlIgMhJIAKAAIAIA1IABAKIAAAAIAjg/IALAAIgtBJg");
	this.shape_2.setTransform(159.75,-266.65);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgcAgQgGgIAAgMQAAgNAGgMQAHgNAKgGQAKgGAMAAQAIAAAQACIgMA9IgBAMIgKAAQAAgGADgOIgBAAQgHAMgGAFQgFAFgIAAQgKAAgGgHgAgHgZQgIAGgEAJQgFAKAAALQAAAUAOAAQAGAAAFgFQAHgGAFgJQAEgIADgKIAEgWQgGgBgIAAQgKAAgHAFg");
	this.shape_3.setTransform(151.675,-266.625);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAPA3IALg2QAAgNgMAAQgHAAgGAFQgFAEgGAHQgGAIgBAIIgIAjIgJAAIAYhtIAJAAIgMA2IAAAAQANgUAQAAQAKAAAEAFQAFAGAAAJIgLA3g");
	this.shape_4.setTransform(143.475,-268.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTAjIALg1IgNAAIACgIIANAAIAEgTIAJgDIgFAWIAUAAIgCAIIgUAAIgJA0QAAAEABABQACACADAAQADAAAIgDIgCAIIgGACIgFABQgOAAAAgOg");
	this.shape_5.setTransform(134.025,-267.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgCAQIgBggIAHAAIgBAgg");
	this.shape_6.setTransform(130.525,-271.75);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAPAmIALg1QAAgPgMAAQgFABgIAFQgHAFgEAHQgGAJgBAFIgIAkIgJAAIAPhJIAJAAIgDATIAAAAQAGgKAHgGQAIgFAIAAQATAAAAAUIgCAPIgJAog");
	this.shape_7.setTransform(124.375,-266.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AggAxQgFgHAAgNQgBgOAHgMQAGgLAJgHQAKgGANAAQAIAAAHACIAHgkIAJAAIgSBXIgDAWIgJAAIACgTQgGALgFAFQgHAGgIgBQgKABgGgIgAgKgIQgIAFgFAKQgFAJAAAMQAAAUAOAAQAFABAIgGQAEgFAFgKQAGgIACgLIAEgUQgGgCgHAAQgLAAgGAFg");
	this.shape_8.setTransform(117.05,-268.35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLAzQgDgDAAgGIACgMIALgzIAIAAIgLA+QAAAFAEAAIAGgBIgBAIIgHABQgGAAgDgDgAAEgqQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAABQAAADgCACQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAQgDAAgBgCg");
	this.shape_9.setTransform(111.425,-268.175);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AggAxQgFgGAAgOQgBgOAHgMQAGgMAJgGQAKgGANAAQAIAAAHACIAIgkIAJAAIgTBXIgDAWIgJAAQAAgIACgLQgGALgFAFQgIAGgIgBQgJABgGgIgAgLgIQgHAFgFAKQgFAJAAAMQAAAUAOAAQAGABAHgGQAEgFAFgKQAGgIACgLIAFgUQgGgCgIAAQgKAAgIAFg");
	this.shape_10.setTransform(105.9,-268.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgPA0IAVhoIAKAAIgVBog");
	this.shape_11.setTransform(96.1,-268.15);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTAjIALg1IgNAAIACgIIANAAIAEgTIAJgDIgFAWIAUAAIgCAIIgUAAIgJA0QAAAEABABQACACADAAQADAAAIgDIgCAIIgGACIgFABQgOAAAAgOg");
	this.shape_12.setTransform(88.425,-267.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgZAmIAKgwQADgNABgNIAKAAIgDARQAFgKAFgEQAFgEAHAAQAFAAADABIgCAKQgEgDgEAAQgIAAgHAKQgGAJgEAPIgHAhg");
	this.shape_13.setTransform(83.275,-266.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgaAfQgGgGgBgPQABgOAFgKQAEgLAKgHQAKgHAKABQAMAAAHAHQAIAIAAAOQAAANgGALQgEALgKAHQgKAHgKgBQgLAAgJgIgAgPgSQgIAMgBAQQABAKAFAGQAFAFAIAAQAHABAHgGQAHgFAEgKQAEgJAAgKQAAgMgFgFQgFgFgIAAQgLAAgKAMg");
	this.shape_14.setTransform(76.45,-266.65);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgmA4IAThWIACgXIAJAAIgBAKIgBALIAAAAQALgXARAAQAKAAAFAHQAGAIAAAMQAAAOgGAMQgGALgLAHQgJAGgMABQgHgBgJgCIgHAkgAADgpQgHAHgEAHQgFAKgCAJIgEAUQAGADAJAAQAJAAAHgGQAIgFAFgJQAEgKAAgMQAAgTgOgBQgHAAgFAGg");
	this.shape_15.setTransform(68.175,-265);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgmA4IAShWIADgXIAJAAIgCAVIAAAAQALgXAQAAQAKAAAGAHQAGAIAAAMQAAAOgGAMQgGALgLAHQgKAGgLABQgIgBgIgCIgIAkgAACgpQgGAHgEAHQgFAKgCAJIgFAUQAHADAJAAQAIAAAIgGQAIgFAFgJQAEgKAAgMQAAgTgOgBQgGAAgHAGg");
	this.shape_16.setTransform(60.375,-265);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgdAhQgFgFAAgKIABgHIABgIIAJgoIAJAAIgLA2QABANAMAAQAGAAAGgEQAFgFAGgIQAFgIACgHIAIgjIAJAAIgPBJIgJAAIADgTQgGAKgIAGQgIAGgHgBQgJABgFgGg");
	this.shape_17.setTransform(53.05,-266.55);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgRAmQgGgBgDgCIACgJIAJADIAKACQAGAAAFgDQAEgDAAgGQAAgEgCgEIgJgIQgHgDgEgFQgEgEAAgHQAAgKAHgGQAIgHAKABIAJABIAJADIgCAJQgIgFgJAAQgHAAgDAEQgEADAAAGQAAAFACADQACACAGAFQAJAEADAFQAEAEAAAHQAAAKgHAGQgIAFgLAAg");
	this.shape_18.setTransform(45.875,-266.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgMAFgLQAGgKAJgHQAKgGAJAAQALAAAFAFQAGAFAAAIQAAANgMAHQgMAFgcAAIAAAEIAAAAQAAAKAFAGQAGAGAKAAQAJAAALgHIgBAKQgKAFgKAAQgOAAgIgIgAgJgXQgIAIgDANIAAAAQAWAAAJgEQALgEAAgJQAAgGgEgDQgDgCgHAAQgKAAgHAHg");
	this.shape_19.setTransform(35.825,-266.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAPA3IAJgrIACgLQAAgNgMAAQgGAAgHAFQgFAEgGAHQgGAIgBAIIgIAjIgJAAIAYhtIAJAAIgMA2QANgUAQAAQAKAAAFAFQAEAFAAAKIgBAIIgKAvg");
	this.shape_20.setTransform(27.925,-268.45);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgSAjIABgKIAJgrIgNAAIACgIIANAAIAEgTIAJgDIgFAWIAUAAIgCAIIgTAAIgJAqIgBAKQAAAEACABQABACAEAAQADAAAHgDIgCAIIgGACIgFABQgNAAAAgOg");
	this.shape_21.setTransform(22.425,-267.675);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgMAFgLQAGgKAJgHQAKgGAJAAQALAAAFAFQAGAFAAAIQAAANgMAHQgMAFgcAAIAAAEIAAAAQAAAKAFAGQAGAGAKAAQAJAAALgHIgBAKQgKAFgKAAQgOAAgIgIgAgJgXQgIAIgDANIAAAAQAVAAAKgEQALgEAAgJQAAgGgEgDQgDgCgIAAQgJAAgHAHg");
	this.shape_22.setTransform(12.325,-266.625);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgWA2IgMgEIAXhpIAKAAIgNA3QAMgWAPABQALgBAFAIQAGAHAAAMQgBAPgFAMQgGALgLAHQgLAHgKgBQgHAAgGgCgAgBgIQgGAFgFAJQgFAKgBAIIgFAVQAHADAIAAQAIAAAJgFQAHgHAEgJQAFgJAAgMQAAgKgEgEQgDgFgIgBQgFAAgGAGg");
	this.shape_23.setTransform(4.7,-268.35);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgGAnQgLAAgIgIQgIgHAAgOQAAgMAGgMQAFgMAJgGQAKgHAKABQAMAAAHAHQAIAIAAAOQAAAMgGAMQgEALgKAHQgJAGgKAAgAgOgSQgJAMAAAQQAAAKAFAGQAEAFAJAAIAAAAQAHABAHgGQAIgGADgJQAEgJAAgKQAAgMgFgFQgEgFgJAAQgLAAgJAMg");
	this.shape_24.setTransform(-7.025,-266.65);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgTAjIALg1IgMAAIABgIIANAAIAEgTIAJgDIgFAWIAUAAIgCAIIgUAAIgIAqIgBAKQAAAEABABQACACAEAAQACAAAIgDIgCAIIgGACIgFABQgOAAAAgOg");
	this.shape_25.setTransform(-12.55,-267.675);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AggAxQgFgGAAgOQAAgNAFgNQAHgLAJgHQAKgGANAAQAIAAAHACIAIgkIAJAAIgTBXIgDAWIgJAAIACgTIAAAAQgHAMgEAEQgIAGgIgBQgJABgGgIgAgLgIQgHAEgFALQgFAKAAALQAAAUAOAAQAGABAGgGQAGgGAEgJQAFgGADgNIAFgUIgBAAQgGgCgIAAQgJAAgIAFg");
	this.shape_26.setTransform(-22.8,-268.35);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgXAfQgIgIAAgPQABgLAFgMQAGgLAJgGQAJgGAKAAQALAAAFAFQAGAFAAAIQABANgNAHQgNAEgbABIAAAEIAAAAQAAAKAGAGQAFAGAKAAQAJAAALgHIgBAKQgLAFgKAAQgNAAgIgIgAgJgXQgIAIgDANIAAAAQAVAAALgEQAKgEgBgJQAAgGgDgDQgDgCgHAAQgJAAgIAHg");
	this.shape_27.setTransform(-30.5,-266.625);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgTAjIALg1IgNAAIACgIIANAAIAEgTIAJgDIgFAWIAUAAIgCAIIgUAAIgJA0QAAAEABABQACACADAAQADAAAIgDIgCAIIgGACIgFABQgOAAAAgOg");
	this.shape_28.setTransform(-35.825,-267.675);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAPAmIAKg1QAAgPgLAAQgGABgHAFQgHAFgEAHQgGAJgBAFIgIAkIgJAAIAPhJIAJAAIgDATIAAAAQAGgKAHgGQAIgFAIAAQATAAAAAUIgCAPIgJAog");
	this.shape_29.setTransform(-42.875,-266.75);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgcAgQgGgIAAgMQAAgNAGgMQAHgNAKgGQAKgGAMAAQAIAAAQACIgNA9IgBAMIgJAAIACgUQgHAMgGAFQgFAFgJAAQgKAAgFgHgAgHgZQgJAHgEAIQgEAKAAALQAAAUAOAAQAFAAAGgFQAGgFAFgKQAGgKACgIIAEgWIAAAAQgHgBgHAAQgKAAgHAFg");
	this.shape_30.setTransform(-50.575,-266.625);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AACAmIgDg2IAAgHIghA9IgIAAIgHhKIABgBIAJAAIAEBAIAAAAIACgHIAfg5IAHAAIAEA8IgBAEIABAAIACgGIAeg5IAJAAIgnBKg");
	this.shape_31.setTransform(-59,-266.625);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgPA0IAVhnIAKAAIgWBng");
	this.shape_32.setTransform(149.45,-284.15);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgMAFgLQAFgJAKgIQAKgGAJAAQAJgBAHAGQAGAEAAAKQAAANgNAGQgMAFgbABIAAADIAAAAQAAAKAGAHQAFAFAKABQAJgBALgGIgBAJQgKAGgKAAQgOAAgIgJgAgJgWQgIAHgDANIAAABQAWgBAJgEQALgDAAgKQAAgGgEgDQgEgCgGAAQgJAAgIAIg");
	this.shape_33.setTransform(140.075,-282.65);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgRAmQgFgCgEgCIADgJQADADAFABIAKACQAHAAAEgDQAEgDAAgHQAAgFgDgCQgBgDgHgFQgIgEgDgEQgEgFAAgGQAAgJAHgHQAIgGAJAAIAJABIAJACIgCAJQgHgEgJAAQgHAAgDADQgFAEABAGQAAAEACADQABADAIAFQAHAEAEAFQAEAFAAAFQAAAKgHAGQgIAGgLAAg");
	this.shape_34.setTransform(133.45,-282.625);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgdAhQgFgGAAgKIALg2IAJAAIgKA1QAAAPALAAQAGgBAHgFQAGgEAFgIQAGgHABgIIAIgjIAJAAIgLA0QgDALgBAKIgJAAIADgTIAAAAQgFAJgJAHQgHAGgIAAQgKAAgEgGg");
	this.shape_35.setTransform(126.825,-282.55);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgcAgQgGgIAAgMQAAgNAGgMQAHgNAKgGQAKgGAMAAQAKAAAOADIgMA8IgBANIgKAAIAAgBQAAgGADgOIgBAAQgGALgHAGQgFAFgIAAQgKAAgGgHgAgHgZQgIAGgEAJQgFAKAAALQAAAUAOAAQAGAAAFgFQAGgFAGgKQAEgHADgLIAEgWQgGgBgIAAQgKAAgHAFg");
	this.shape_36.setTransform(118.775,-282.625);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgVAgQgHgJAAgOQAAgNAFgLQAFgKAKgHQAJgGALAAQAKAAAHAEIgCAKQgGgGgKAAQgJAAgGAFQgHAGgEAJQgEAJAAAJQAAALAFAHQAFAFAJABQAIAAAKgIIgCAKIgKAEIgIACQgMgBgHgHg");
	this.shape_37.setTransform(112.075,-282.65);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgLAFgMQAFgKAKgHQAKgGAJAAQAKgBAGAGQAGAEAAAKQAAANgMAGQgMAEgcACIAAADQAAAKAGAHQAGAFAJABQAJgBAMgGIgCAJQgKAGgKAAQgOAAgIgJgAgJgWQgIAHgDANIAAABQAVgBALgEQAKgEAAgJQAAgGgEgDQgDgCgHAAQgIAAgJAIg");
	this.shape_38.setTransform(105.275,-282.65);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgWA2QgHgBgEgDIAWhqIAJAAIgMA3IABAAQALgUAPAAQALAAAGAHQAEAHAAAMQABAOgGANQgHAMgJAGQgKAHgMAAQgHgBgGgCgAgBgIQgGAGgFAHQgEAIgDALIgEAUQAGAEAJAAQAJAAAIgFQAHgHAFgJQAFgJgBgMQAAgJgDgGQgDgEgIAAQgGgBgGAGg");
	this.shape_39.setTransform(97.65,-284.35);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgXAfQgIgIAAgPQABgLAFgMQAGgKAJgHQAKgGAJAAQAJgBAIAGQAFAEAAAKQABANgNAGQgMAEgcACIAAADIAAAAQAAAKAGAHQAFAFAKABQAJgBAMgGIgCAJQgLAGgKAAQgOAAgHgJgAgJgWQgIAHgDANIAAABQAVgBALgEQAKgDAAgKQAAgGgEgDQgEgCgGAAQgJAAgIAIg");
	this.shape_40.setTransform(86.5,-282.65);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgQAmQgHgCgCgCIABgJIAJAEIAKACQAHAAAFgDQAEgDAAgHQgBgEgCgDIgIgIQgIgDgEgFQgDgFgBgGQAAgKAIgGQAGgGALAAIAJABIAJACIgCAJQgIgEgIAAQgIAAgDADQgEAEAAAGQAAAFACACQABACAHAGQAJAEAEAFQADAEAAAGQAAAKgHAGQgIAGgLAAg");
	this.shape_41.setTransform(79.85,-282.625);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgZAmIAKgvQAEgQABgKIAJAAIgDARQAFgKAFgFQAGgEAGAAQAFgBADACIgBAKIgBAAQgEgDgEABQgIgBgHALQgHAJgDAPIgHAgg");
	this.shape_42.setTransform(75.025,-282.75);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgdAhQgFgFAAgLIALg2IAKAAIgLA1QAAAPAMAAQAFgBAGgFQAGgEAGgIQAGgIABgHIAIgjIAJAAIgLA0IgEAVIgJAAIADgTQgGAKgIAGQgHAGgIAAQgKAAgEgGg");
	this.shape_43.setTransform(68.2,-282.55);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAPAmIAKg2QAAgNgLAAQgGAAgHAEQgGAGgFAHQgGAJgBAFIgHAkIgKAAIAPhJIAJAAIgDATQAHgKAHgGQAHgGAIABQATgBAAAVIgLA3g");
	this.shape_44.setTransform(59.75,-282.75);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgvA0IAXhnIAaAAQAVAAAMALQAMALABAUQAAASgJAOQgHAPgOAHQgOAIgTgBgAgjAsIAVAAQAYAAANgOQAOgNAAgZQAAgjglAAIgQAAg");
	this.shape_45.setTransform(46.9,-284.15);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AglAvQgJgHAAgMQAAgLAIgIQAIgIARgFQgEgFgEgIIgCgKQAAgLAIgIQAJgHALAAQALAAAHAFQAHAGAAAKQAAALgIAGQgHAIgPAGIAVAdQAMgNAFgRIAJAAQgGAWgPAPIANASIgLAAIgJgMIAAAAQgPANgUAAQgNAAgIgHgAgeANQgGAFAAAKQAAAIAGAFQAFAFAKAAQAPAAAPgLIAAgBIgYghQgQAGgFAGgAgIgpQgFAFAAAIQAAAFACAEQABAFAFAGQANgFAHgFQAGgGAAgIQAAgGgEgEQgEgEgIAAQgIAAgFAFg");
	this.shape_46.setTransform(35.875,-284.125);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgaA0IAWhnIAJAAIgTBeIApAAIgCAJg");
	this.shape_47.setTransform(27.325,-284.15);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgcAgQgGgIAAgMQAAgNAGgMQAHgNAKgGQAKgGAMAAQAKAAAOADIgMA8IgBANIgKAAIAAgBQAAgGADgOIgBAAQgGALgHAGQgFAFgIAAQgKAAgGgHgAgHgZQgIAGgEAJQgFAKAAALQAAAUAOAAQAFAAAGgFQAGgFAGgKQAFgJACgJIAEgWQgGgBgIAAQgKAAgHAFg");
	this.shape_48.setTransform(16.325,-282.625);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgXAfQgIgIAAgPQABgLAFgMQAFgKAKgHQAKgGAJAAQAKgBAGAGQAGAEAAAKQABANgNAGQgMAEgcACIAAADIAAAAQAAAKAGAHQAFAFAKABQAJgBALgGIgBAJQgLAGgKAAQgOAAgHgJgAgJgWQgIAHgDANIAAABQAVgBALgEQAKgDgBgKQAAgGgDgDQgEgCgGAAQgJAAgIAIg");
	this.shape_49.setTransform(5.05,-282.65);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AAlAmIAJgqQACgIAAgFQAAgMgLAAQgGAAgGAEQgHAHgEAHQgGAHgBAGIgHAkIgJAAIAJgqIABgMQAAgNgKAAQgGAAgGAEQgHAHgFAHQgFAIgCAGIgHAjIgJAAIAPhJIAJAAIgDATQAOgWAPABQAIgBAEAGQADAEABAMQAHgLAHgFQAIgFAIAAQARgBAAAVIgCAPIgJAog");
	this.shape_50.setTransform(-5.075,-282.75);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgcAgQgGgIAAgMQAAgNAGgMQAHgNAKgGQAKgGAMAAQAKAAAOADIgMA8IgBANIgKAAIAAgBQAAgGADgOIgBAAQgGALgHAGQgFAFgIAAQgKAAgGgHgAgHgZQgIAGgEAJQgFAKAAALQAAAUAOAAQAFAAAGgFQAGgFAGgKQAEgHADgLIAEgWQgGgBgIAAQgKAAgHAFg");
	this.shape_51.setTransform(-14.975,-282.625);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgVAgQgIgJABgOQAAgNAEgLQAGgKAKgHQAJgGAKAAQAKAAAIAEIgCAKQgHgGgKAAQgIAAgHAFQgGAGgFAJQgDAJAAAJQAAALAEAHQAGAFAJABQAIAAAKgIIgCAKIgKAEIgIACQgNgBgGgHg");
	this.shape_52.setTransform(-21.65,-282.65);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgXAfQgHgIAAgPQAAgLAFgMQAFgKAKgHQAKgGAJAAQAJgBAHAGQAGAEABAKQAAANgNAGQgMAEgcACIAAADIAAAAQAAAKAGAHQAFAFAKABQAJgBAMgGIgCAJQgKAGgLAAQgNAAgIgJgAgJgWQgIAHgDANIAAABQAVgBALgEQAKgDAAgKQAAgGgEgDQgDgCgIAAQgIAAgIAIg");
	this.shape_53.setTransform(-28.45,-282.65);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgWA2QgGgBgFgDIAWhqIAJAAIgLA3IAAAAQALgUAQAAQAKAAAFAHQAGAGgBANQABAOgGANQgGALgKAHQgKAHgMAAQgHgBgGgCgAgBgIQgGAFgFAIQgEAJgCAKIgEAUQAFAEAJAAQAKAAAGgFQAJgHAEgJQAFgJgBgMQABgJgEgGQgDgEgIAAQgGgBgGAGg");
	this.shape_54.setTransform(-36.1,-284.35);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgPA0IAVhnIAKAAIgVBng");
	this.shape_55.setTransform(-45.35,-284.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64,-290,235,30.600000000000023);


(lib.Logo_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,320,50);


(lib.IMG_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.IMG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,320,50);


(lib.Destini = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUAlIAAgBIABgKIAIAAIACgCIACgDIABgFIgUg0IAOAAIAMAnIAOgnIAMAAIgWA8IgEAHIgEAEQgEACgEAAg");
	this.shape.setTransform(89.2,10);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNAbIAAg0IAMAAIAAAJQABgFACgCQADgDAFABIADAAIACAAIAAALIgDgBIgEAAQgDABgCABIgDAEIgBAGIAAAeg");
	this.shape_1.setTransform(84.7,8.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAAbQgHAAgFgDQgGgEgDgGQgDgGAAgIQAAgHADgGQADgGAGgEQAFgDAHAAQAGAAAEACQAEABAEAEQADADACAFQACAFAAAGIAAADIglAAIACAHIAFAGQADABADAAIAFAAIAEgDIADgEIALABQgBAFgDADQgEAEgEACQgGACgFAAgAgGgPQgCACgCADIgCAGIAYAAIgBgGQgBgDgDgCQgDgBgEAAQgDAAgDABg");
	this.shape_2.setTransform(79.875,8.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGAaIgTgzIANAAIAMAnIANgnIANAAIgTAzg");
	this.shape_3.setTransform(74.475,9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgGAlIAAgzIAMAAIAAAzgAgFgYIgCgFIACgFQACgCADAAQAEAAABACQACACABADQgBADgCACQgBACgEAAQgDAAgCgCg");
	this.shape_4.setTransform(70.55,7.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgFAlIAAhIIALAAIAABIg");
	this.shape_5.setTransform(68.125,7.95);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AABAbQgIAAgFgDQgGgEgDgGQgDgHAAgHQAAgGADgHQAEgGAFgEQAGgDAGAAQAGAAAEACQAFABADAEIAFAIQACAFAAAGIAAADIglAAIACAHQABADADADQADABAEAAIAGAAIAEgDIABgEIANABQgCAFgDADQgDAEgFACQgGACgFAAgAgGgPQgCACgCADIgCAGIAYAAIgBgGQgCgDgCgCQgCgBgEAAQgDAAgEABg");
	this.shape_6.setTransform(64.15,8.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdAlIAAhIIAZAAQAKgBAHAFQAJAEAEAJQAEAIAAAKQAAALgEAJQgEAHgJAFQgHAEgLABgAgQAaIAKAAQAIgBAFgDQAEgCAEgGQACgHAAgHQAAgGgCgHQgDgGgFgDQgFgCgHAAIgLAAg");
	this.shape_7.setTransform(57.95,7.95);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgSAjQgFgDgDgEQgDgFAAgGQAAgEABgDIAFgHIAIgFIgCgCIgFgIQgBgCAAgEQAAgGADgEQACgEAEgCQAFgCAFAAQAFAAADACQAEABADAEQACAFAAAEIgBAGIgDAGIgFAEIgEAEIAMAPIACgDQACgFAAgFIALAAIgBAKIgEAJIgCADIAKAMIgNAAIgFgFQgEAEgEABQgEABgFAAIgBABQgGgBgGgCgAgPALQgCADAAADQAAACACADIAEAEQADABADAAQAEAAADgCIAEgCIgOgSgAgIgZIgDACIgBAFIABAEIADAFIABABIAFgDQAAAAABAAQAAgBABAAQAAAAAAgBQAAAAAAgBIACgCIAAgEQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQgCgCgDAAIgEABg");
	this.shape_8.setTransform(48.95,7.95);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgOAbIAAg0IANAAIAAAJQABgFACgCQAEgDAFABIABAAIACAAIAAALIgCgBIgDAAIgGACIgDAEQgBADAAADIAAAeg");
	this.shape_9.setTransform(41.65,8.95);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgMAYQgGgDgDgHQgEgFAAgJQAAgIAEgFQADgHAGgDQAFgDAHAAQAIAAAFADQAGAEADAGQAEAHAAAGQAAAHgEAHQgDAHgGADQgFADgIAAQgHAAgFgDgAgGgOQgDADgCADQgBAEAAAEQAAAGABADQACAEADACQADACADAAIAAAAQAFAAACgCQADgCABgEQACgDAAgGQAAgEgCgEQgBgDgDgDQgDgCgEAAQgEAAgCACg");
	this.shape_10.setTransform(36.725,8.975);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgDAkIgFgDIgEgFIAAAIIgMAAIAAhIIAMAAIAAAcIAEgEQADgDACAAIAGgBQAHAAAEADQAGAEACAFQADAFAAAJQAAAIgDAGQgCAGgFADQgFAEgHAAgAgGgEQgDACgCADQgBAEAAAFQAAAGABADQACAEADABQACACAEAAQAEAAADgCQACgBACgEQACgFAAgEQAAgGgCgDIgEgFQgEgCgDAAQgCAAgEACg");
	this.shape_11.setTransform(30.975,8.025);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgEAbQgFAAgEgCQgEgCgDgDQgCgDAAgGQAAgEACgDQACgDACgBIAHgDIAHgBIAHgBIAEgBIABgDIAAAAIgBgEQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgFgCIgEACIgEACIgCAEIgLgBQABgFACgEQADgDAFgCQAEgCAGAAIAJABQADABAEADQADACABADQACADAAAEIAAAjIgMAAIAAgIIgBAAIgDAFIgFADIgGABgAAGADIgLACIgDACQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABIABAEIADACIAFAAQADAAADgBQADgBABgDQACgCAAgEIAAgFg");
	this.shape_12.setTransform(25.025,9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgWAlIAAhIIANAAIAAA9IAgAAIAAALg");
	this.shape_13.setTransform(19.8,7.95);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAYA2IgyhRIABBRIgTAAIAAhsIAVAAIAxBSIAAhSIATAAIAABsg");
	this.shape_14.setTransform(86.725,-6.85);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAUA2IgUgnIgVAAIAAAnIgUAAIAAhsIAqAAQALAAAJAFQAJAEAFAIQAEAIAAAKQAAALgFAHQgEAHgJAEIgCABIAXArgAgVgBIAVAAQAGAAAEgBQAFgCACgFQADgEAAgGQAAgHgDgCQgCgEgFgDQgFgCgFAAIgVAAg");
	this.shape_15.setTransform(76.675,-6.85);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgLAUIAGgnIARAAIgLAng");
	this.shape_16.setTransform(66.275,-1.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgIA3IAAhNIARAAIAABNgAAAgiQgEAAgDgCQgDgEAAgEQAAgEADgEQADgDAEAAQAFAAADADQADAEAAAEQAAAEgDAEQgDACgFAAg");
	this.shape_17.setTransform(62.775,-6.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AARAoIAAgtQAAgJgFgEQgEgFgHABQgFAAgDACQgDABgDAFQgCADAAAIIAAArIgTAAIAAhOIASAAIAAANQADgFAFgDQAGgGAKAAQAIAAAGADQAGAFADAGQAEAGAAALIAAAwg");
	this.shape_18.setTransform(56.6,-5.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgIA3IAAhNIARAAIAABNgAAAgiQgEAAgDgCQgDgEAAgEQAAgEADgEQADgDAEAAQAFAAADADQADAEAAAEQAAAEgDAEQgDACgFAAg");
	this.shape_19.setTransform(50.475,-6.95);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgEAtQgGgFAAgKIAAgrIgNAAIAAgPIANAAIAAgVIASAAIAAAVIAPAAIAAAPIgPAAIAAAoQAAAEACACQACACAEAAIAHAAIABAOIgLABQgMAAgFgFg");
	this.shape_20.setTransform(45.95,-6.325);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgPAmQgHgDgFgFQgFgGgBgIIASgBQABAFAEAEQAEADAGAAQAHAAAEgDQAEgCAAgEQAAgEgDgCQgDgDgFAAIgMgDQgLgCgGgFQgGgGAAgJQAAgIAEgEQAEgGAHgDQAHgDAJAAQAJAAAHADQAGADAFAGQAEAGABAHIgSABQAAgFgEgEQgDgDgHAAQgFAAgEADQgDADAAAEQAAADACACQADACAFACIANACQAMADAFAEQAGAGAAAIQAAAHgFAGQgFAGgGADQgIADgKAAQgIAAgHgDg");
	this.shape_21.setTransform(39.475,-5.325);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgTAkQgIgGgFgJQgEgJAAgMQAAgLAEgJQAFgJAJgFQAHgGALAAQAIAAAHADQAGACAGAGQAFAGACAHQADAHAAAJIAAAFIg3AAQAAAFACAGQACAEAFAEQAFACAFAAQAFAAADgBQADgBADgDQADgDABgDIARABQgBAGgFAHQgGAGgHADQgHADgJAAQgLAAgJgFgAgJgWQgFACgCAFQgCAEAAAEIAlAAIgCgIQgCgFgEgCQgEgDgHAAQgFAAgEADg");
	this.shape_22.setTransform(31.425,-5.325);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgsA3IAAhtIAUAAIAAABIASAAQAPAAAMAGQAMAIAGALQAGANAAAPQAAAQgGANQgHANgMAGQgLAHgQAAgAgYAmIAQAAQALAAAHgEQAIgFAEgIQAEgJAAgMQAAgKgEgJQgEgIgIgFQgHgFgLAAIgQAAg");
	this.shape_23.setTransform(22.075,-6.875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(17.5,-12.5,74.4,26.2);


(lib.CTA_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CTA();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,320,50);


(lib.BG_png = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,320,50);


// stage content:
(lib.WBAY_218364_MM_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(397));

	// CTA_png
	this.instance = new lib.CTA_png("synched",0);
	this.instance.setTransform(80,300);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(323).to({_off:false},0).to({alpha:1},13).wait(61));

	// T3_png
	this.instance_1 = new lib.T3_png("synched",0);
	this.instance_1.setTransform(80,300);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(266).to({_off:false},0).to({alpha:1},14).wait(28).to({startPosition:0},0).to({alpha:0},14).to({_off:true},1).wait(74));

	// T2_png
	this.instance_2 = new lib.T2_png("synched",0);
	this.instance_2.setTransform(80,300);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(194).to({_off:false},0).to({alpha:1},14).wait(42).to({startPosition:0},0).to({alpha:0},14).to({_off:true},1).wait(132));

	// T1_png
	this.instance_3 = new lib.T1_png("synched",0);
	this.instance_3.setTransform(80,300);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(119).to({_off:false},0).to({alpha:1},14).wait(46).to({startPosition:0},0).to({alpha:0},14).to({_off:true},1).wait(203));

	// Destini_png
	this.instance_4 = new lib.Destini("synched",0);
	this.instance_4.setTransform(160,25);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(56).to({_off:false},0).to({alpha:1},13).wait(36).to({startPosition:0},0).to({alpha:0},13).to({_off:true},1).wait(278));

	// Why_png
	this.instance_5 = new lib.Why_png("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({alpha:1},15).wait(25).to({startPosition:0},0).to({alpha:0},15).to({_off:true},1).wait(341));

	// Logo_png
	this.instance_6 = new lib.Logo_png("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(56).to({_off:false},0).to({alpha:1},13).wait(36).to({startPosition:0},0).to({alpha:0},13).to({_off:true},1).wait(204).to({_off:false},0).to({alpha:1},13).wait(61));

	// IMG_png
	this.instance_7 = new lib.IMG_png("synched",0);
	this.instance_7.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(397));

	// BG_png
	this.instance_8 = new lib.BG_png("synched",0);
	this.instance_8.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(397));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(159,24,162,27);
// library properties:
lib.properties = {
	id: '75E153FF2D744F028C65A7813D4CAE23',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.png", id:"BG"},
		{src:"CTA.png", id:"CTA"},
		{src:"IMG.png", id:"IMG"},
		{src:"Logo.png", id:"Logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['75E153FF2D744F028C65A7813D4CAE23'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;