(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgYAuQgLgHgHgLQgGgMAAgPQAAgPAGgMQAIgMAKgHQAMgGANAAQAPAAAKAGQALAGAGAMQAGAMAAAPIgBADQAAABAAAAQAAAAAAAAQAAAAgBAAQAAABgBAAIhCAAIgCAAIgBADQAAAHAEAHQADAGAHADQAGAEAHAAQAIAAAGgDQAHgEAFgHIABgBIADABIALAFQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgGAJgGAFQgHAFgIACQgIACgKAAQgNAAgMgGgAgKggQgGAEgDAGQgDAGAAAIIArAAIADgBIABgCQAAgGgDgGQgCgFgFgEQgGgEgHAAQgHAAgFAEg");
	this.shape.setTransform(39.1,-5.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgbAuQgLgGgFgJIgBgCIACgCIALgFIACgBIACABIAHAHQADADAGACQAFACAGAAQAGAAAGgCQAFgBACgDQADgDAAgEQAAgEgDgCQgEgDgIgCIgSgFQgPgDgGgGQgHgHAAgKQAAgKAFgHQAFgHAJgEQAJgEANAAQANAAAKAFQALAFAFAIIABACQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABAAAAIgMAFIgDABIgBgCQgEgEgGgEQgFgDgJAAQgHAAgFADQgGAEAAAGQAAACACADQACADAJACIAVAGQAPAEAGAGQAHAIgBAKQABAJgGAIQgGAHgKADQgJAEgOAAQgPAAgMgGg");
	this.shape_1.setTransform(27.8,-5.375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgjAsQgJgHAAgNQAAgKAGgIQAHgGAMgFQAMgEAQgBIAJgBIACAAIABgCIAAgFQAAgIgFgFQgFgEgJAAQgFAAgGADQgGADgEAGIgBACIgDAAIgQgEIgBgBIABgDQAFgLALgGQALgFAPAAQAPAAAJAEQAJAEAFAHQAEAHAAAKIAABBIgBADIgDABIgQAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIgBgDIAAgGQAAgBgBAAQAAgBgBAAQAAAAgBABQAAAAgBABQgHAGgHADQgHADgKAAQgOAAgIgIgAASABIgIABIgKABIgKAEQgFADgCADQgDAEAAAEQAAAHAFAEQAFADAIAAQAEAAAEgBIAIgFIAFgFQACgDAAgDIAAgOQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAIgBAAg");
	this.shape_2.setTransform(16.725,-5.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAXBGIgCAAIgBgDIAAhBQAAgGgEgFQgEgEgIAAQgEAAgDACIgIAEIgIAHIAABDQAAADgEAAIgRAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAiFQAAgBAAgBQABAAAAgBQAAAAABAAQAAgBABAAIATAAQAAAAABABQAAAAABAAQAAABAAAAQAAABAAABIAAAxIABABIABgBIAMgIQAFgDAFgBIALgCQAOAAAIAIQAIAIAAAOIAABEQAAADgEAAg");
	this.shape_3.setTransform(5.625,-7.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgVAuQgMgHgGgMQgGgLAAgQQAAgOAGgMQAHgMALgHQALgGANAAQAMAAAIAEQAIADAGAHQAFAGADAHQAAABAAAAQAAABAAAAQAAABAAAAQgBAAgBAAIgRACQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgFgIQgDgDgDgCQgEgCgFAAQgGAAgGAEQgGAEgDAIQgDAIAAALQAAAMADAIQADAIAGAEQAGAEAHAAQAJAAAFgFQAGgEAFgIIABgBIACAAIAMADQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAABIgGAJQgDAFgFAEQgFAEgIADQgHACgJAAQgNAAgLgGg");
	this.shape_4.setTransform(-5.7437,-5.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgbAzIgCgBIgBgCIAAhdQAAgBAAgBQAAAAABgBQAAAAAAAAQABAAABAAIASAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAMIABABIACAAIAIgKIAKgFQAFgCAFAAQAHAAAAADIAAASQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIgGgBIgFAAIgIABQgEACgEADQgCACgCAEQgDADAAADIAAA5QAAAEgEAAg");
	this.shape_5.setTransform(-15.15,-5.475);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgeAwQgGgEgEgHQgDgHAAgJIAAhDQAAgEADAAIASAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABAQAAAHAEAFQAEAEAHAAQAGAAAGgEQAGgDAGgGIAAhDQgBgDAFAAIARAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABdQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgKIAAgBIgBABQgKAIgHAEQgIADgIAAQgJAAgHgDg");
	this.shape_6.setTransform(-25.65,-5.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgzBGIgCgBIgCgCIAAiFQAAgBABgBQAAAAAAgBQABAAAAAAQABgBABAAIA0AAQAPAAANAFQAMAFAIAJQAHAKAAAOQgBAPgGAJQgHAJgLAEQgMAFgPAAIgcAAQgBAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAAAIAAAzQgBADgEAAgAgaguIAAAmQAAABAAABQAAAAAAABQAAAAABAAQAAABABAAIAZAAQALgBAIgGQAGgFABgLQgBgIgDgEQgDgFgHgDQgFgCgIAAIgXAAQgBAAgBAAQAAAAgBABQAAAAAAABQAAAAAAABg");
	this.shape_7.setTransform(-38.15,-7.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgpA+QgOgGAAgNQAAgGAFgFQAFgFAIgDQABAAAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAQgEgCgDgDQgDgDAAgFQAAgDACgDIAGgFIAJgEIACgBIgCgCQgIgEgFgGQgEgHAAgIQAAgPAMgIQAMgJAWAAQAJAAAIACQAHADAFAEIACAAIADgBIAFgFIAHgDIAHgBIACAAQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAIAAALQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAIgDABIgFAAIgEAAQgFACABADIACAEIABAGQAAAJgFAGQgFAHgKAFQgKAEgOAAIgNAAQgFABgCACQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAQABAAAAAAIALACIAZACQATAAAIAIQAJAHAAAMQAAAOgOAJQgNAIgZAAQgaABgNgHgAgZAdQgEABgCADQgDADAAAEQAAAFADAEQAEAEAIABQAHACAMAAQANAAAHgEQAIgEAAgHQAAgFgEgEQgEgDgJAAIgdgBQgEAAgDABgAgTgwQgGAFAAAJQAAAIAGAFQAGAFAKAAQAKAAAGgFQAFgFAAgIQAAgJgFgFQgGgEgKAAQgKAAgGAEg");
	this.shape_8.setTransform(42.375,-27.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAXAzIgCAAIgBgDIAAhAQAAgIgEgEQgEgEgIAAQgEAAgDABQgEACgEADIgIAHIAABCQAAAEgEAAIgRAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAhdQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKIABACIABgBIALgIQAFgEAFgBQAFgCAHAAQAOAAAIAIQAIAIAAANIAABEQAAAEgEAAg");
	this.shape_9.setTransform(30.425,-29.475);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgIBGIgDgBIAAgCIAAhdQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIASAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABdIgBACIgDABgAgIgrIgDgBIgBgDIAAgTQAAgBAAgBQABAAAAgBQAAAAABAAQABAAAAAAIATAAQAAAAABAAQABAAAAAAQAAABABAAQAAABAAAAIAAATQAAAFgFAAg");
	this.shape_10.setTransform(21.725,-31.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgoBCQgBgBAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgNIABgCIAEAAIANAAQAEAAADgCIAFgGIADgGQAAgEgBgCIgkhZIAAgDIACgBIAUAAIADAAIABADIAXA+QAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAXg+IACgDIACAAIAOAAIACABQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABIgoBjIgHAOQgDAFgFADQgFAEgGABQgGABgIAAg");
	this.shape_11.setTransform(13.4625,-27.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgLBGQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAhNQAAAAAAgBQAAAAAAAAQgBgBAAAAQAAAAAAAAIgQAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIAAgMIABgDIACAAIAPAAQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBAAgBIAAgMQAAgMAHgHQAGgGAMAAIASAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIABAKIgBADIgCABIgLAAQgFAAgCACQgDAEAAAGIAAAJQAAABAAAAQAAAAAAABQABAAAAAAQAAAAABAAIASAAIACAAIABADIAAAMQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgRAAQgBAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIAABNQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_12.setTransform(3.95,-31.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgIBGIgDgBIAAgCIAAhdQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIASAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABdIgBACIgDABgAgIgrIgDgBIgBgDIAAgTQAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIATAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAATQAAAFgFAAg");
	this.shape_13.setTransform(-2.875,-31.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgIBGQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAiGQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAACGIgBACQAAABAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_14.setTransform(-8.325,-31.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgjAsQgJgHAAgNQAAgKAGgIQAHgGAMgFQAMgEAQgBIAJgBIACAAIABgCIAAgFQAAgIgFgFQgFgEgJAAQgFAAgGADQgGADgEAGIgBACIgDAAIgQgEIgBgBIABgDQAFgLALgGQALgFAPAAQAPAAAJAEQAJAEAFAHQAEAHAAAKIAABBIgBADIgDABIgQAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIgBgDIAAgGQAAgBgBAAQAAgBgBAAQAAAAgBABQgBAAAAABQgHAGgHADQgHADgKAAQgOAAgIgIgAASABIgIABIgKABIgKAEQgFADgCADQgDAEAAAEQAAAHAFAEQAFADAIAAQAEAAAEgBIAIgFIAFgFQACgDAAgDIAAgOQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAIgBAAg");
	this.shape_15.setTransform(-16.975,-29.375);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgeAwQgGgEgEgHQgEgHABgJIAAhDQAAgEADAAIASAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABAQAAAHAEAFQAEAEAHAAQAGAAAGgEQAGgDAGgGIAAhDQAAgDAEAAIARAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIgBBdQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgKIAAgBIgBABQgKAIgHAEQgIADgIAAQgJAAgHgDg");
	this.shape_16.setTransform(-28.15,-29.275);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAkBOQgKgFgJgMQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAAAgBAAIgHABIgHABQgSAAgPgJQgOgIgIgRQgHgQAAgVQAAgYAHgQQAIgQAOgIQAPgJASAAQATAAAPAJQAOAIAIAQQAHAQAAAYQAAATgGAPQgGAOgMAJIAAACQAAACADADQADADAFACIAKADIACABIABABIAAAOQAAABAAAAQAAABgBAAQAAABAAAAQAAAAgBAAIgFABQgKAAgKgFgAgZgyQgIAOAAAbQAAAaAIAMQAJAMAQAAQARAAAJgMQAIgMAAgaQAAgbgIgOQgJgNgRABQgQgBgJANg");
	this.shape_17.setTransform(-41.625,-30.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAXBHIgCgBIgBgDIAAhBQAAgHgEgDQgEgFgIAAQgEAAgDACIgIAEIgIAHIAABCQAAAFgEAAIgRAAQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAiGQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAIATAAQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAIAAAyIABABIABgBIAMgIQAFgDAFgBQAFgCAGAAQAOAAAIAIQAIAIAAAOIAABDQAAAFgEAAg");
	this.shape_18.setTransform(59.925,-55.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAKBEQgMAAgHgHQgGgFAAgNIAAg3QAAgBAAgBQgBAAAAAAQAAgBgBAAQAAAAgBAAIgNAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgLQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAOAAQABAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIACgeQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAdQAAAAAAABQAAAAAAAAQAAAAABAAQAAABAAAAIAWAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAALQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgWAAQAAAAgBAAQAAAAAAAAQAAABgBAAQAAAAAAABIAAAyQAAAHADADQADADAHAAIALAAIACABIABABIgBAKQAAADgDACIgHAAIgHABg");
	this.shape_19.setTransform(49.625,-55.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgIBHIgDgBIAAgDIAAhdQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIASAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABcIgBAEIgDABgAgIgsIgDAAIgBgDIAAgTQAAgBAAgBQABAAAAgBQAAAAABAAQABgBAAAAIATAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAIAAATQAAAEgFAAg");
	this.shape_20.setTransform(42.725,-55.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAhBHQgFgBgBgDIgahbIgBgBIAAABIgaBbQgBADgEABIgSAAQgEgBgCgDIgmiDQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQAAgBABAAIATAAIADABIACACIAbBeIABACIABgCIAbheIABgCIADgBIAQAAIADABIACACIAbBfIABACQAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAgBIAbhfIABgCIADgBIAPAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABIgnCDQgBADgEABg");
	this.shape_21.setTransform(29.575,-55.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgaAzIgDgBIgBgCIAAhdQAAgBAAgBQAAAAABgBQAAAAAAAAQABAAABAAIASAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAMIABABIACAAIAIgKIAKgFQAFgCAFAAQAHAAAAADIAAASQAAAAAAABQAAABgBAAQAAAAAAAAQgBAAgBAAIgGgBIgFAAIgIABQgFACgDADQgCACgCAEQgCADgBADIAAA5QAAAEgDAAg");
	this.shape_22.setTransform(10.75,-53.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgYAuQgLgHgHgLQgGgMAAgPQAAgPAGgMQAIgMAKgHQAMgGANAAQAPAAAKAGQALAGAGAMQAGAMAAAPIgBADQAAABAAAAQAAAAAAAAQAAAAgBAAQAAABgBAAIhCAAIgCAAIgBADQAAAHAEAHQADAGAHADQAGAEAHAAQAIAAAGgDQAHgEAFgHIABgBIADABIALAFQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgGAJgGAFQgHAFgIACQgIACgKAAQgNAAgMgGgAgKggQgGAEgDAGQgDAGAAAIIArAAIADgBIABgCQAAgGgDgGQgCgFgFgEQgGgEgHAAQgHAAgFAEg");
	this.shape_23.setTransform(0.4,-53.375);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAXBHIgCgBIgBgDIAAhBQAAgHgEgDQgEgFgIAAQgEAAgDACIgIAEIgIAHIAABCQAAAFgEAAIgRAAQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAiGQAAAAAAgBQABAAAAgBQAAAAABAAQABgBAAAAIATAAQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAIAAAyIABABIABgBIAMgIQAFgDAFgBQAFgCAGAAQAOAAAIAIQAIAIAAAOIAABDQAAAFgEAAg");
	this.shape_24.setTransform(-11.325,-55.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgVAuQgMgHgGgMQgGgLAAgQQAAgOAGgMQAHgMALgHQALgGANAAQAMAAAIAEQAIADAGAHQAFAGADAHQAAABAAAAQABABgBAAQAAABAAAAQgBAAgBAAIgRACQAAAAAAAAQgBAAAAAAQgBAAAAAAQAAgBAAAAIgFgIQgDgDgDgCQgEgCgFAAQgGAAgGAEQgGAEgDAIQgDAIAAALQAAAMADAIQADAIAGAEQAGAEAHAAQAJAAAFgFQAGgEAFgIIABgBIACAAIAMADQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAABIgGAJQgDAFgFAEQgFAEgIADQgHACgJAAQgNAAgLgGg");
	this.shape_25.setTransform(-22.6937,-53.375);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgeAwQgGgEgEgHQgDgHAAgJIAAhDQAAgEAEAAIARAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABAQAAAHAEAFQAEAEAHAAQAGAAAGgEQAGgDAGgGIAAhDQgBgDAFAAIARAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABdQAAABAAABQAAAAgBABQAAAAAAAAQgBAAgBAAIgSAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgKIAAgBIgBABQgKAIgHAEQgIADgIAAQgJAAgHgDg");
	this.shape_26.setTransform(-34.2,-53.275);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgZAuQgMgHgGgMQgGgMAAgPQAAgOAHgMQAGgMAMgHQAKgGAOAAQAPAAALAGQAMAHAFAMQAHAMAAAOQAAAPgHAMQgFAMgMAHQgLAGgPAAQgOAAgLgGgAgMgfQgGAEgDAIQgDAIAAALQAAALADAIQADAIAGAEQAFAEAHAAQAIAAAGgEQAFgEADgIQADgIAAgLQAAgLgDgIQgDgIgFgEQgGgEgIAAQgHAAgFAEg");
	this.shape_27.setTransform(-46,-53.375);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgJBHQgFgBgBgDIguiEIABgEIACgBIAXAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAIAhBmQABABAAAAQAAABABAAQAAAAAAgBQAAAAABgBIAhhmQAAAAABgBQAAAAABgBQAAAAABAAQAAgBABAAIASAAIADABIAAAEIgvCEQgBADgEABg");
	this.shape_28.setTransform(-59.1708,-55.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAXAzIgCAAIgBgDIAAhAQAAgIgEgEQgEgEgIAAQgEAAgDABQgEACgEADIgIAHIAABCQAAAEgEAAIgRAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAhdQAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIATAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKIABACIABgBIALgIQAFgEAFgBQAFgCAHAAQAOAAAIAIQAIAIAAANIAABEQAAAEgEAAg");
	this.shape_29.setTransform(38.875,-77.475);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgZAuQgMgHgGgMQgGgMAAgPQAAgOAGgMQAHgMALgHQALgGAOAAQAPAAALAGQALAHAHAMQAGAMAAAOQAAAPgGAMQgHAMgLAHQgLAGgPAAQgOAAgLgGgAgNgfQgFAEgDAIQgDAIAAALQAAALADAIQADAIAFAEQAGAEAHAAQAIAAAFgEQAGgEADgIQADgIAAgLQAAgLgDgIQgDgIgGgEQgFgEgIAAQgHAAgGAEg");
	this.shape_30.setTransform(26.95,-77.375);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgIBGIgDgBIAAgCIAAhdQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIASAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABdIgBACIgDABgAgIgsIgDgBIgBgCIAAgTQAAgBAAgBQABAAAAgBQAAAAABAAQABgBAAAAIATAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAABIAAASQAAAFgFgBg");
	this.shape_31.setTransform(18.225,-79.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAKBDQgMABgHgHQgGgGAAgMIAAg4QAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAgBAAIgNAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgMQAAAAAAgBQABAAAAAAQAAgBABAAQABAAAAAAIAOAAQABAAAAAAQABAAAAgBQAAAAAAAAQAAgBAAAAIACgeQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAIAQAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAABIAAAdQAAAAAAABQAAAAAAAAQAAAAABAAQAAABAAAAIAWAAQAAAAABAAQABAAAAAAQAAABABAAQAAABAAAAIAAAMQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAIgWAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAABAAAAIAAAyQAAAIADACQADADAHAAIALAAIACABIABABIgBALQAAADgDAAIgHABIgHAAg");
	this.shape_32.setTransform(11.175,-79.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgjAsQgJgHAAgNQAAgKAGgIQAHgGAMgFQAMgEAQgBIAJgBIACAAIABgCIAAgFQAAgIgFgFQgFgEgJAAQgFAAgGADQgGADgEAGIgBACIgDAAIgQgEIgBgBIABgDQAFgLALgGQALgFAPAAQAPAAAJAEQAJAEAFAHQAEAHAAAKIAABBIgBADIgDABIgQAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIgBgDIAAgGQgBgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBABQgHAGgHADQgHADgKAAQgOAAgIgIgAASABIgIABIgKABIgKAEQgFADgCADQgDAEAAAEQAAAHAFAEQAFADAIAAQAEAAAEgBIAIgFIAFgFQACgDAAgDIAAgOQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAIgBAAg");
	this.shape_33.setTransform(1.075,-77.375);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgVAuQgMgHgGgMQgGgLAAgQQAAgOAGgMQAHgMALgHQALgGANAAQAMAAAIAEQAIADAGAHQAFAGADAHQAAABAAAAQAAABAAAAQAAABAAAAQgBAAgBAAIgRACQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgFgIQgDgDgDgCQgEgCgFAAQgGAAgGAEQgGAEgDAIQgDAIAAALQAAAMADAIQADAIAGAEQAGAEAHAAQAJAAAFgFQAGgEAFgIIABgBIACAAIAMADQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAABIgGAJQgDAFgFAEQgFAEgIADQgHACgJAAQgNAAgLgGg");
	this.shape_34.setTransform(-9.5937,-77.375);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgjAsQgJgHAAgNQAAgKAGgIQAHgGAMgFQAMgEAQgBIAJgBIACAAIABgCIAAgFQAAgIgFgFQgFgEgJAAQgFAAgGADQgGADgEAGIgBACIgDAAIgQgEIgBgBIABgDQAFgLALgGQALgFAPAAQAPAAAJAEQAJAEAFAHQAEAHAAAKIAABBIgBADIgDABIgQAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAIgBgDIAAgGQgBgBAAAAQAAgBgBAAQAAAAgBABQgBAAAAABQgHAGgHADQgHADgKAAQgOAAgIgIgAASABIgIABIgKABIgKAEQgFADgCADQgDAEAAAEQAAAHAFAEQAFADAIAAQAEAAAEgBIAIgFIAFgFQACgDAAgDIAAgOQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAIgBAAg");
	this.shape_35.setTransform(-21.125,-77.375);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgJBGQgFAAgBgDIguiEIABgDQAAgBAAAAQAAAAABAAQAAAAAAAAQABgBAAAAIAXAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAABIAhBlQABABAAAAQAAABABAAQAAAAAAgBQAAAAABgBIAhhlQABgDADgBIASAAIADACIAAADIgvCEQgBADgEAAg");
	this.shape_36.setTransform(-33.5708,-79.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgJAxQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAgBAAgBIAAgVQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAVAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAVQAAAFgFAAgAgJgUQgEAAAAgEIAAgVQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAIAVAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAABIAAAVQAAAEgFAAg");
	this.shape_37.setTransform(29.775,-101.25);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgbAuQgLgGgFgJIgBgCIABgCIAMgFIACgBIACABIAHAHQADADAGACQAFACAGAAQAHAAAFgCQAFgBACgDQADgDAAgEQAAgEgDgCQgDgDgJgCIgSgFQgPgDgGgGQgHgHAAgKQAAgKAFgHQAFgHAJgEQAJgEAMAAQAOAAAKAFQALAFAFAIIABACQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABAAAAIgMAFIgDABIgBgCQgEgEgGgEQgFgDgJAAQgHAAgFADQgGAEAAAGQAAACACADQACADAJACIAVAGQAPAEAGAGQAGAIAAAKQABAJgGAIQgGAHgKADQgJAEgOAAQgPAAgMgGg");
	this.shape_38.setTransform(21.85,-101.375);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgeAwQgGgEgEgHQgDgHAAgJIAAhDQAAgEADAAIASAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABAQAAAHAEAFQAEAEAIAAQAFAAAGgEQAGgDAGgGIAAhDQgBgDAFAAIARAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABdQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgKIAAgBIgBABQgKAIgHAEQgIADgIAAQgJAAgHgDg");
	this.shape_39.setTransform(10.8,-101.275);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAXAzIgCAAIgBgDIAAhAQAAgIgEgEQgEgEgIAAQgEAAgDABQgEACgEADIgIAHIAABCQAAAEgEAAIgRAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAhdQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKIABACIABgBIALgIQAFgEAFgBQAFgCAHAAQAOAAAIAIQAIAIAAANIAABEQAAAEgEAAg");
	this.shape_40.setTransform(-0.875,-101.475);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgZAuQgMgHgGgMQgGgMAAgPQAAgOAGgMQAHgMALgHQAMgGANAAQAPAAALAGQAMAHAFAMQAHAMAAAOQAAAPgHAMQgFAMgMAHQgLAGgPAAQgOAAgLgGgAgMgfQgGAEgDAIQgDAIAAALQAAALADAIQADAIAGAEQAFAEAHAAQAIAAAGgEQAFgEADgIQADgIAAgLQAAgLgDgIQgDgIgFgEQgGgEgIAAQgHAAgFAEg");
	this.shape_41.setTransform(-12.8,-101.375);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgzBGIgDgBIgBgCIAAiFIABgCIADgBIAxAAQAaAAAOAJQAOAKAAASQAAAKgFAIQgGAHgOAFIAAABIAAABQAPADAHAJQAHAHAAANQAAAUgPAJQgOAKgbgBgAgbAMIAAAkQAAABAAAAQABABAAAAQAAABABAAQAAAAABAAIAXAAQANAAAHgFQAIgGAAgKQAAgHgEgEQgDgGgHgBQgGgDgHAAIgXAAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABgAgbgvIAAAiQAAABAAABQABAAAAABQAAAAABAAQAAAAABAAIAYAAIAJgBQAEAAAEgDQADgCACgFQACgDAAgGQAAgKgHgFQgIgFgLAAIgVAAQgBAAgBAAQAAAAgBABQAAAAgBABQAAAAAAABg");
	this.shape_42.setTransform(-25.575,-103.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAKBEQgMAAgHgHQgGgFAAgNIAAg3QAAgBAAgBQgBAAAAAAQAAgBgBAAQAAAAgBAAIgNAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgLQAAgBAAgBQABAAAAAAQAAgBABAAQABAAAAAAIAOAAQABAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAgBIACgeQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAdQAAAAAAABQAAAAAAAAQAAAAABAAQAAABAAAAIAWAAQAAAAABAAQABAAAAAAQAAABABAAQAAABAAABIAAALQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAIgWAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAyQAAAHADADQADADAHAAIALAAIACABIABABIgBAKQAAADgDACIgHAAIgHABg");
	this.shape_43.setTransform(30.325,-127.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgbAuQgLgGgFgJIgBgCIABgCIAMgFIADgBIABABIAHAHQADADAGACQAFACAGAAQAHAAAEgCQAFgBADgDQADgDAAgEQAAgEgDgCQgEgDgIgCIgSgFQgOgDgIgGQgGgHAAgKQAAgKAFgHQAFgHAJgEQAJgEAMAAQAOAAALAFQAKAFAFAIIABACQAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAABIgMAFIgDABIgBgCQgEgEgFgEQgHgDgIAAQgHAAgFADQgGAEAAAGQAAACACADQADADAHACIAWAGQAPAEAGAGQAGAIABAKQgBAJgFAIQgGAHgKADQgKAEgNAAQgPAAgMgGg");
	this.shape_44.setTransform(20.75,-125.375);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgdAwQgHgEgEgHQgEgHAAgJIAAhDQAAgEAFAAIARAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABAQAAAHAEAFQAEAEAIAAQAFAAAGgEQAGgDAFgGIAAhDQAAgDAFAAIARAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABdQAAABAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgTAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgKIgBgBIgBABQgIAIgJAEQgGADgJAAQgJAAgGgDg");
	this.shape_45.setTransform(9.7,-125.275);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgpA/QgOgHAAgMQAAgHAFgFQAFgEAIgDQABgBAAAAQAAAAAAgBQAAAAAAAAQAAgBgBAAQgEgCgDgDQgDgDAAgFQAAgDACgDIAGgEIAJgFIACgBIgCgBQgIgFgFgGQgEgGAAgJQAAgOAMgJQAMgJAWAAQAJABAIACQAHACAFAEIACAAIADgBIAFgEIAHgEIAHgCIACABQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAALQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAIgDABIgFgBIgEABQgFABABAEIACAEIABAGQAAAIgFAIQgFAHgKAEQgKAEgOAAIgNAAQgFACgCABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQABAAAAABIALABIAZACQATABAIAHQAJAHAAAMQAAAOgOAJQgNAJgZgBQgaAAgNgFgAgZAdQgEABgCAEQgDADAAADQAAAFADAEQAEADAIACQAHACAMAAQANAAAHgEQAIgEAAgHQAAgFgEgEQgEgCgJgBIgdgBQgEgBgDACgAgTgwQgGAGAAAIQAAAIAGAFQAGAFAKAAQAKAAAGgFQAFgFAAgIQAAgIgFgGQgGgEgKAAQgKAAgGAEg");
	this.shape_46.setTransform(-2.425,-123.9);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgdAwQgHgEgEgHQgDgHAAgJIAAhDQAAgEADAAIASAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABAQAAAHAEAFQAEAEAHAAQAGAAAGgEQAGgDAFgGIAAhDQABgDAEAAIARAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIgBBdQAAABAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgTAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgKIgBgBIgBABQgJAIgIAEQgGADgJAAQgJAAgGgDg");
	this.shape_47.setTransform(-14.45,-125.275);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AAoBHQgBAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBIgLgfIgBgBIgBAAIgxAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAABAAAAIgLAfIgBACIgDABIgSAAQgBAAAAgBQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAAAABgBIAwiEIABgDIADgBIAXAAQAEAAABAFIAwCDIAAADQgBAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAgAgCgmIgTAxQAAABAAAAQAAABAAAAQAAABABAAQAAAAABAAIAjAAQABAAAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIgSgyIgBgBIgBACg");
	this.shape_48.setTransform(-27.7625,-127.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68.1,-140.7,136.3,147);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(64.375,12.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAWAtQgDAAgBgDIgRg0IgBgBIAAABIgQA1IgCACIgCAAIgNAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIgchTIAAgCIADgBIAQAAIACAAIACACIARA2QAAAAAAAAQAAABAAAAQAAAAAAAAQAAAAABAAIABgBIARg2IABgCIACAAIALAAIACAAIABACIARA2IACABIABgBIAQg2IACgCIACAAIALAAIACABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAIgbBUIgBACIgDAAg");
	this.shape_1.setTransform(51.7875,12.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgXApQgKgGgFgLQgGgKAAgNQAAgNAGgLQAGgLAKgGQAKgGAMAAQAOAAAKAGQAKAHAFAKQAGALAAANQAAANgGAKQgFALgLAGQgKAGgNAAQgMAAgLgGgAgLgcQgFAFgDAHQgDAGAAAKQAAAKADAIQADAGAFAFQAFADAGAAQAHAAAFgDQAFgFADgGQACgIAAgKQAAgKgCgGQgDgHgFgFQgFgDgHAAQgGAAgFADg");
	this.shape_2.setTransform(39.225,12.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgwBAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAh3IABgCIACgBIAIAAIAKAAIAJAAIAHAAQAXAAAOAIQAPAIAHAOQAHANAAATQAAATgHAPQgIAPgPAHQgPAIgWAAgAgagqIAABVQAAABAAAAQAAABABAAQAAAAAAAAQABABAAAAIAFAAQAPAAAKgFQAKgFAFgJQAFgKAAgRQAAgQgFgJQgFgLgKgEQgJgFgPABIgGAAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAABg");
	this.shape_3.setTransform(27.525,10.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgkA7QgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIAAgLIABgCIAEgBIAMAAQADAAADgCIAFgEIACgGQABgDgCgDIgghQIAAgCIACgBIASAAIACAAIABACIAVA4QAAAAAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIACgBIAVg4IABgCIACAAIAMAAIACABQAAAAABAAQAAABAAAAQAAAAAAABQgBAAAAAAIgkBZQgDAIgDAFQgDAFgEADQgEACgGABIgMABg");
	this.shape_4.setTransform(11.5875,14.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgVApQgKgFgGgLQgGgKAAgNQAAgOAGgLQAGgLAKgGQALgGALAAQANAAAKAGQAJAGAGAKQAFALAAAOIAAADQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAIg7AAIgCABIAAACQAAAHADAGQADAGAGADQAGACAGAAQAHAAAGgCQAFgDAFgGIACgBIABAAIALAEQAAABABAAQAAAAAAABQAAAAAAABQAAAAgBABQgFAHgGAFQgGAEgHACQgHACgJAAQgMAAgKgGgAgJgdQgFAEgDAFQgDAGAAAHIAoAAIACAAIAAgDQAAgFgCgFQgCgFgFgEQgFgDgGAAQgGAAgFADg");
	this.shape_5.setTransform(1.375,12.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_6.setTransform(-9.125,12.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgXApQgKgGgFgLQgGgKAAgNQAAgNAGgLQAGgLAKgGQAKgGAMAAQAOAAAKAGQAKAHAFAKQAGALAAANQAAANgGAKQgFALgLAGQgKAGgNAAQgMAAgLgGgAgLgcQgFAFgDAHQgDAGAAAKQAAAKADAIQADAGAFAFQAFADAGAAQAHAAAFgDQAFgFADgGQACgIAAgKQAAgKgCgGQgDgHgFgFQgFgDgHAAQgGAAgFADg");
	this.shape_7.setTransform(-19.875,12.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAsBAIgCgBIgBgDIAAhYIAAgBIgBABIghBZQAAABAAAAQgBABAAAAQgBAAAAAAQgBABAAAAIgLAAQgBAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgghYIgBgBIgBACIAABWIAAADIgCABIgPAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAh3QAAgBAAgBQAAAAABgBQAAAAAAAAQABAAABAAIAcAAIADAAIABACIAeBQIAAABIABgBIAehPQAAgBAAgBQABAAAAgBQABAAAAAAQABAAAAAAIAeAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAABIAAB3QAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAg");
	this.shape_8.setTransform(-33.525,10.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgXApQgKgGgFgLQgGgKAAgNQAAgNAGgLQAGgLAKgGQAKgGAMAAQAOAAAKAGQAKAHAFAKQAGALAAANQAAANgGAKQgFALgLAGQgKAGgNAAQgMAAgLgGgAgLgcQgFAFgDAHQgDAGAAAKQAAAKADAIQADAGAFAFQAFADAGAAQAHAAAFgDQAFgFADgGQACgIAAgKQAAgKgCgGQgDgHgFgFQgFgDgHAAQgGAAgFADg");
	this.shape_9.setTransform(-51.225,12.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAiBAIgCgBIgCgCIg5hSIgCgBIAAABIAABRQAAABAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgPAAQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAh3QAAgBAAgBQAAAAABgBQAAAAAAAAQABAAABAAIARAAIACAAIACACIA2BOIACACIABgCIAAhNQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAB5IAAACIgDABg");
	this.shape_10.setTransform(-63.375,10.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgKAZIgCgBIAAgCIAIgSQABgBAAgBQAAgBAAgBQAAAAgBAAQAAAAgBAAIgDAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgUQAAgBAAAAQAAgBAAAAQABAAAAAAQABgBAAAAIATAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAABIAAASIgBACIgOAZIgDABIgCABg");
	this.shape_11.setTransform(48.7625,-3.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAJA9QgKAAgHgGQgGgFAAgLIAAgyQAAgBAAAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgLAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgLQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAABAAIAMAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIACgaQABAAAAgBQAAgBAAAAQABAAAAgBQAAAAABAAIAOAAQABAAAAAAQABABAAAAQAAAAAAABQABABAAAAIAAAaQAAABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIAUAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgUAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAAAsQAAAHADACQADADAGAAIAKAAIABABIABABIAAAJQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgHAAIgGABg");
	this.shape_12.setTransform(42.6,-9.475);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgYAqQgKgFgEgJIgBgCIABgBIAKgGIACAAIACABIAFAGIAJAFQAEABAGABQAGgBAEgBQAFgBACgDQADgCAAgEQAAgDgDgCQgDgDgIgCIgQgEQgNgEgGgEQgGgHAAgJQAAgJAEgGQAFgGAIgEQAJgEAKAAQANAAAJAFQAJAEAEAIIABABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAgBAAIgKAFIgCABIgCgBQgDgFgFgDQgFgDgIAAQgHAAgEADQgFADAAAGQAAACACACQACACAHADIATAFQANADAGAGQAGAHAAAJQAAAIgFAHQgFAGgJAEQgJADgMAAQgNAAgLgFg");
	this.shape_13.setTransform(33.975,-7.95);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgVAqQgKgHgGgKQgGgKAAgOQAAgOAGgLQAGgKAKgGQALgGALAAQANAAAKAGQAJAGAGAKQAFALAAANIAAAEQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIg7AAIgCAAIAAACQAAAHADAGQADAFAGADQAGAEAGAAQAHAAAGgEQAFgCAFgHIACgBIABABIALAFQAAAAABAAQAAAAAAABQAAAAAAABQAAAAgBAAQgFAIgGAEQgGAFgHACQgHACgJAAQgMAAgKgFgAgJgcQgFADgDAGQgDAFAAAHIAoAAIACgBIAAgBQAAgGgCgFQgCgFgFgDQgFgEgGAAQgGAAgFAEg");
	this.shape_14.setTransform(24.175,-7.95);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgYAuIgCgBIgBgCIAAhTQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAALIABABIACgBQADgFAEgDIAJgFQAEgCAEAAQAHAAAAADIAAAQQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAIgFgBIgFAAIgHABIgHAEQgCADgCADQgCACAAADIAAA0QAAADgEAAg");
	this.shape_15.setTransform(15.425,-8.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgVAqQgKgHgGgKQgGgKAAgOQAAgOAGgLQAGgKAKgGQALgGALAAQANAAAKAGQAJAGAGAKQAFALAAANIAAAEQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIg7AAIgCAAIAAACQAAAHADAGQADAFAGADQAGAEAGAAQAHAAAGgEQAFgCAFgHIACgBIABABIALAFQAAAAABAAQAAAAAAABQAAAAAAABQAAAAgBAAQgFAIgGAEQgGAFgHACQgHACgJAAQgMAAgKgFgAgJgcQgFADgDAGQgDAFAAAHIAoAAIACgBIAAgBQAAgGgCgFQgCgFgFgDQgFgEgGAAQgGAAgFAEg");
	this.shape_16.setTransform(6.125,-7.95);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAJA9QgKAAgHgGQgGgFAAgLIAAgyQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgMAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgLQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAIANAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAABgBIABgaQABAAAAgBQAAgBAAAAQABAAAAgBQABAAAAAAIAOAAQABAAAAAAQABABAAAAQAAAAAAABQAAABAAAAIAAAaQAAABABAAQAAAAAAAAQAAABAAAAQABAAAAAAIAUAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgUAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAsQAAAHADACQACADAHAAIAKAAIACABIAAABIAAAJQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgHAAIgGABg");
	this.shape_17.setTransform(-3.05,-9.475);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_18.setTransform(-12.075,-8.025);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgIA/IgDgBIgBgBIAAh5QAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAIATAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAIAAB4QAAAAAAABQAAAAgBAAQAAABAAAAQAAAAAAAAIgEABg");
	this.shape_19.setTransform(-20.325,-9.75);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgXApQgKgGgFgKQgGgLAAgOQAAgMAGgLQAGgLAKgGQAKgGAMAAQAOAAAKAHQAKAFAFALQAGALAAAMQAAAOgGALQgFAKgLAGQgKAGgNAAQgMAAgLgGgAgLgcQgFAFgDAGQgDAIAAAJQAAAKADAHQADAIAFADQAFAEAGAAQAHAAAFgEQAFgDADgIQACgHAAgKQAAgJgCgIQgDgGgFgFQgFgDgHAAQgGAAgFADg");
	this.shape_20.setTransform(-32.675,-7.95);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAiA/IgCAAIgCgCIg5hRIgCgBIAAABIAABRQAAAAAAABQgBAAAAABQAAAAgBAAQgBAAAAAAIgPAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAh5QAAAAAAgBQAAAAAAgBQABAAAAAAQABgBABAAIARAAIACABIACACIA2BOIACABIABgCIAAhNQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIAQAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAB5IAAACIgDAAg");
	this.shape_21.setTransform(-44.825,-9.75);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgKAZIgCgBIAAgCIAIgSQABgBAAgBQAAgBAAgBQAAAAgBAAQAAAAgBAAIgDAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgUQAAgBAAAAQAAgBABAAQAAAAAAAAQABgBAAAAIATAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAABIAAASIgBACIgOAZIgDABIgCABg");
	this.shape_22.setTransform(57.7125,-24.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgYAqQgKgFgEgJIgBgCIABgBIAKgGIACAAIACABIAFAGIAJAFQAEABAGABQAGgBAEgBQAFgBACgDQADgCAAgEQAAgDgDgCQgDgDgIgCIgQgEQgNgEgGgEQgGgHAAgJQAAgJAEgGQAFgGAIgEQAJgEAKAAQANAAAJAFQAJAEAEAIIABABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAgBAAIgKAFIgCABIgCgBQgDgFgFgDQgFgDgIAAQgHAAgEADQgFADAAAGQAAACACACQACACAHADIATAFQANADAGAGQAGAHAAAJQAAAIgFAHQgFAGgJAEQgJADgMAAQgNAAgLgFg");
	this.shape_23.setTransform(50.575,-28.65);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAIA9QgKAAgGgGQgGgFAAgLIAAgyQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgLAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgLQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAABAAIAMAAQAAAAABAAQAAAAAAAAQAAAAAAgBQABAAAAgBIACgaQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAAAAAIAPAAQAAAAAAAAQABABAAAAQAAAAAAABQAAABAAAAIAAAaQABABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIATAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgTAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAsQAAAHADACQADADAFAAIAKAAIADABIAAABIAAAJQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgFAAIgHABg");
	this.shape_24.setTransform(41.55,-30.175);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_25.setTransform(32.525,-28.725);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgVAqQgKgHgGgKQgGgKAAgOQAAgOAGgLQAGgKAKgGQALgGALAAQANAAAKAGQAJAGAGAKQAFALAAANIAAAEQAAAAAAAAQgBAAAAAAQAAAAgBAAQAAABgBAAIg7AAIgCAAIAAACQAAAHADAGQADAFAGADQAGAEAGAAQAHAAAGgEQAFgCAFgHIACgBIABABIALAFQAAAAABAAQAAAAAAABQAAAAAAABQAAAAgBAAQgFAIgGAEQgGAFgHACQgHACgJAAQgMAAgKgFgAgJgcQgFADgDAGQgDAFAAAHIAoAAIACgBIAAgCQAAgFgCgFQgCgFgFgDQgFgEgGAAQgGAAgFAEg");
	this.shape_26.setTransform(21.925,-28.65);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAwAuIgCAAIAAgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACIgHADIgFAFIgCACIAAADIAAA5QAAADgEAAIgOAAIgCAAIgBgDIAAg6QAAgGgDgEQgEgEgHAAQgFAAgFADQgFADgGAGIAAA8QAAADgEAAIgPAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhTQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIARAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAJIAAABIACAAIAJgIQAEgDAFgBQAFgCAGAAQAJAAAFAEQAHAFACAGIABABIABgBIAKgIQAFgDAFgCQAFgCAGAAQAMAAAHAHQAHAHAAANIAAA9QAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_27.setTransform(8.625,-28.725);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgkA7QgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIAAgLIABgCIAEgBIAMAAQADAAADgCIAFgEIACgGQABgDgCgDIgghQIAAgCIACgBIASAAIACAAIABACIAVA4QAAAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIACgBIAVg4IABgCIACAAIAMAAIACABQAAAAAAAAQABABAAAAQAAAAgBABQAAAAAAAAIgkBZQgDAIgDAFQgDAFgEADQgEACgGABIgMABg");
	this.shape_28.setTransform(-4.4625,-27.225);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AggApQgHgIAAgLQAAgJAFgHQAGgGALgEQAKgEAPgBIAIAAIACgBIABgBIAAgFQAAgHgEgFQgFgDgIAAQgFAAgFACQgFADgEAGIgBABIgCAAIgPgDIgBgCIABgCQAEgKAKgFQAKgFAOAAQANAAAIAEQAJAEADAGQAEAGAAAJIAAA7IAAACIgDABIgOAAIgDgBIAAgCIgBgGQAAgBAAAAQAAAAgBAAQAAAAgBAAQAAAAgBABQgGAFgHADQgGADgIAAQgNAAgIgGgAAQABIgHABQgFAAgEACQgFABgEACIgGAFQgCADAAAEQAAAHAEACQAEAEAHAAQAEAAAEgBIAHgFIAEgEQACgDAAgDIAAgMQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAIgBAAg");
	this.shape_29.setTransform(-14.825,-28.65);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AguA/IgDgBIAAgBIAAh5QAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAwAAQAOABAKAEQAMAEAGAIQAHAJAAANQAAANgGAJQgGAHgKAEQgLAFgNAAIgaAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAtQAAAEgFgBgAgXgqIAAAjQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAIAXAAQAKAAAHgFQAGgFAAgKQAAgIgDgEQgDgEgGgCQgFgCgHAAIgVAAQgBAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAg");
	this.shape_30.setTransform(-25.55,-30.45);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgXApQgKgGgFgKQgGgLAAgOQAAgMAGgLQAGgLAKgGQAKgGAMAAQAOAAAKAHQAKAFAFALQAGALAAAMQAAAOgGALQgFAKgLAGQgKAGgNAAQgMAAgLgGgAgLgcQgFAFgDAGQgDAIAAAJQAAAKADAHQADAIAFADQAFAEAGAAQAHAAAFgEQAFgDADgIQACgHAAgKQAAgJgCgIQgDgGgFgFQgFgDgHAAQgGAAgFADg");
	this.shape_31.setTransform(-41.625,-28.65);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAiA/IgCAAIgCgCIg5hRIgCgBIAAABIAABRQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgPAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAh5QAAAAAAgBQAAAAABgBQAAAAAAAAQABgBABAAIARAAIACABIACACIA2BOIACABIABgCIAAhNQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIAQAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAB5IAAACIgDAAg");
	this.shape_32.setTransform(-53.775,-30.45);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgYAqQgKgFgEgJIgBgCIABgBIAKgGIACAAIACABIAFAGIAJAFQAEABAGABQAGgBAEgBQAFgBACgDQADgCAAgEQAAgDgDgCQgDgDgIgCIgQgEQgNgEgGgEQgGgHAAgJQAAgJAEgGQAFgGAIgEQAJgEAKAAQANAAAJAFQAJAEAEAIIABABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAgBAAIgKAFIgCABIgCgBQgDgFgFgDQgFgDgIAAQgHAAgEADQgFADAAAGQAAACACACQACACAHADIATAFQANADAGAGQAGAHAAAJQAAAIgFAHQgFAGgJAEQgJADgMAAQgNAAgLgFg");
	this.shape_33.setTransform(47.375,-49.35);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAVA/IgCAAIgBgCIAAg8QAAgFgEgEQgDgDgHAAQgEgBgDACIgHADIgHAHIAAA8QAAAEgEgBIgPAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAh5QAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIARAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAsIABACIABgBQAGgFAFgCQAEgDAEgCQAFgBAFAAQANAAAHAIQAHAHAAAMIAAA9QAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_34.setTransform(37.475,-51.15);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAJA9QgKAAgHgGQgGgFAAgLIAAgyQAAgBAAAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgLAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgLQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAABAAIAMAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAgBIACgaQABAAAAgBQAAgBAAAAQABAAAAgBQAAAAABAAIAOAAQABAAAAAAQABABAAAAQAAAAAAABQABABAAAAIAAAaQAAABAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIAUAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAALQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIgUAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAAAAAABIAAAsQAAAHADACQADADAGAAIAKAAIABABIABABIAAAJQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAIgHAAIgGABg");
	this.shape_35.setTransform(27.65,-50.875);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAVAuIgCAAIgBgDIAAg6QAAgGgEgEQgDgEgHAAQgEAAgDACQgEABgDACIgHAHIAAA8QAAADgEAAIgPAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhTQAAgBAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIARAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAJIABABIABAAIAKgIQAEgDAEgBQAFgCAGAAQANAAAHAHQAHAHAAAMIAAA+QAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_36.setTransform(18.675,-49.425);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgXApQgKgGgFgKQgGgLAAgOQAAgMAGgLQAGgLAKgGQAKgGAMAAQAOAAAKAHQAKAFAFALQAGALAAAMQAAAOgGALQgFAKgLAGQgKAGgNAAQgMAAgLgGgAgLgcQgFAFgDAGQgDAIAAAJQAAAKADAHQADAIAFADQAFAEAGAAQAHAAAFgEQAFgDADgIQACgHAAgKQAAgJgCgIQgDgGgFgFQgFgDgHAAQgGAAgFADg");
	this.shape_37.setTransform(7.925,-49.35);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AAsA/IgCgBIgBgBIAAhZIAAgBIgBABIghBZQAAABAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAIgLAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgghYIgBgBIgBABIAABYIAAACIgCAAIgPAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAh4QAAAAAAgBQAAAAABgBQAAAAAAAAQABgBABAAIAcAAIADABIABACIAeBQIAAABIABgCIAehOQAAgBAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAeAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAAB4QAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_38.setTransform(-5.725,-51.15);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgqBAIgCAAIgBgDIAAgLIAAgCIACgDIAFgEIAhgfIAMgLIAIgJIAEgIIABgIQAAgGgDgEQgDgEgEgCQgFgDgFAAQgFAAgEACQgFACgEAEQgFADgDAHIgCABIgDgBIgMgGIgCgCIABgDQAIgNAMgGQAMgGANAAQAMAAAKAEQAKAEAGAJQAGAIAAAMQAAAHgDAHQgCAGgGAGQgFAGgKAIIgfAbIgBACIACAAIA2AAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAPIgBACIgCABg");
	this.shape_39.setTransform(-23.675,-51.225);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgfA/QgBAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgOQAAgBAAAAQAAgBAAAAQABAAAAAAQABgBAAAAIATAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIAAhPQAAgBAAAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgSAGQgBAAgBAAQAAAAgBAAQAAAAAAgBQAAgBAAgBIAAgKIAAgCIACgBIAbgOIAEgBIACgBIAKAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAABnQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAIASAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAOIAAABIgDABg");
	this.shape_40.setTransform(-33.725,-51.15);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgEAoQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAgcIgdAAIgCgCIgBgCIAAgJQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAdAAIAAAQIAQAAIAAAdQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAgAAJAJIAAgQIgQAAIAAgdIABgDIACAAIAJAAQABAAABAAQAAAAABABQAAAAAAAAQABABAAAAIAAAeIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAAJQAAABAAABQAAAAgBABQAAAAgBAAQgBABAAAAgAAJAJgAgHAJIAAgQIAQAAIAAAQgAgHgHg");
	this.shape_41.setTransform(-47.5,-51.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.7,-63.1,143.5,86.4);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#47C434").s().p("AgDAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgUIgUAAIgCgBIgBgBIAAgIQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAVAAIAAANIANAAIAAAVQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAgAAHAHIAAgNIgNAAIAAgUIABgCIACgBIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAVIAVAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAgAAHAHgAgGAHIAAgNIANAAIAAANgAgGgGg");
	this.shape.setTransform(2.625,72.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#48C435").ss(1,1,1).p("ABgAAIJYAAAq3AAIJYAA");
	this.shape_1.setTransform(1.55,73.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6CC14C").s().p("AhHCXQgggVgTgmQgRgmAAg0QAAgnAKggQAKggAUgXQASgXAagMQAagMAdAAQAfAAAZAMQAZAMATAXQATAXAKAgQALAgAAAmQAAA0gSAnQgSAmgfAVQggAVgpAAQgoAAgfgVgAgghoQgNAMgHAaQgHAaAAAqQAAApAHAZQAHAaANALQANALATAAQAUAAAOgLQANgLAGgaQAHgZAAgpQgBgqgGgaQgHgagNgMQgOgMgTAAQgTAAgNAMg");
	this.shape_2.setTransform(-0.5,41.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC14C").s().p("AAUCoQgKAAAAgJIAAhCQAAgEgFAAIiHAAQgJAAAAgJIAAglIACgKIAJgMICIizIAIgHIAKgCIA5AAQAHAAAAAJIAAC8QAAAFAFAAIAlAAQAIAAAAAHIAAAmQAAAJgIAAIglAAQgFAAAAAFIAABAQAAAKgLAAgAAEhSIhQBvQgEAGAIAAIBPAAQABAAAAAAQABAAABgBQAAAAAAgBQABAAAAgBIAAhwIgCgGg");
	this.shape_3.setTransform(-34.075,41.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6CC14C").s().p("AgrBEIgEgBIAAgDIAAiAQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAAAAAIBaAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAARQAAADgEAAIg4AAQgBAAAAABQgBAAAAAAQgBABAAAAQAAABAAABIAAAcQAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAIAnAAQABAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAARQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgnAAQAAAAgBAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAAxQAAAEgFAAg");
	this.shape_4.setTransform(47.725,52);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6CC14C").s().p("AgrBEIgEgBIAAgDIAAiAQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAAAAAIBaAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAARQAAADgEAAIg4AAQgBAAAAABQgBAAAAAAQgBABAAAAQAAABAAABIAAAcQAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAIAnAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAARQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAIgnAAQAAAAgBAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAAxQAAAEgFAAg");
	this.shape_5.setTransform(36.175,52);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6CC14C").s().p("AggA9QgOgIgIgQQgIgPAAgWQAAgUAIgQQAIgQAOgJQAOgIASAAQATAAAOAIQAOAJAIAQQAIAQAAAUQAAAWgIAPQgHAQgPAIQgOAJgTAAQgSAAgOgJgAgVgjQgHALAAAYQAAAaAHAKQAHAMAOAAQAPAAAHgMQAHgKAAgaQAAgYgHgLQgHgMgPAAQgOAAgHAMg");
	this.shape_6.setTransform(22.925,52);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6CC14C").s().p("AAcBBQgJgFgEgJQgFgJAAgKQAAgLAFgJQAEgJAJgEQAHgFAKgBQAJABAJAFQAHAEAFAJQAEAJAAALQAAAKgEAJQgFAJgHAFQgIAFgKAAQgKAAgHgFgAAlAKQgDADgCAFQgBAGAAAIQAAAHABAGQACAEADAEQADACAFAAQAEAAAEgCQACgEACgEQACgGgBgHQABgIgCgGQgCgFgCgDQgEgDgEAAQgFAAgDADgAgwBFQAAAAgBgBQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIBWiBIADgCIABgBIAKAAIACABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABIhXCDQgBABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAgAg9ACQgIgEgFgIQgEgKAAgKQAAgLAEgJQAFgIAIgGQAIgFAKAAQAJAAAIAFQAHAGAFAIQAFAJAAALQAAAKgFAKQgEAIgIAEQgHAFgKAAQgLAAgHgFgAgzg0QgDADgCAGQgBAGgBAHQABAIABAFQACAFADADQACADAGAAQAGAAAEgGQADgHAAgLQAAgLgDgHQgEgGgGAAQgGAAgCACg");
	this.shape_7.setTransform(24.5,32);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6CC14C").s().p("Ag7BuQgagOgNgdQgOgcAAgmQAAgmAOgcQAOgdAagPQAZgQAhAAQAjAAAZAQQAZAPAOAdQAOAcAAAmQAAAmgOAcQgOAdgZAOQgZAPgjABQgigBgZgPgAgng/QgNAUAAAsQAAAtANATQANAVAagBQAbABANgVQAMgTAAgtQAAgsgMgUQgNgVgbAAQgaAAgNAVg");
	this.shape_8.setTransform(38.825,4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6CC14C").s().p("Ag3BuQgZgPgOgcQgNgcAAgmQAAgmAOgcQAOgdAagPQAZgQAhAAQAbAAAVAKQAVALANAPQANAQAEATIAAAGQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBABIgsAGQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgCgDQgCgLgGgJQgGgJgKgGQgKgFgNAAQgPAAgMAIQgMAJgGASQgGATAAAeQAAAfAHASQAGATAMAJQAMAJAQgBQAKAAAIgDQAJgDAFgGQAGgFAEgGQADgHACgIIABgJQABgFgFAAIgoAAIgDgBIgCgEIAAgZQAAgEAFAAIBZAAQAFAAACACQACACAAADIAABwIgBADIgEACIgKAAIgFgCIgEgEIgJgYIgCgBIgCACQgGAHgJAIQgJAHgNAFQgNAEgTABQgggBgZgPg");
	this.shape_9.setTransform(13.525,4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6CC14C").s().p("Ag7BuQgagOgNgdQgOgcAAgmQAAgmAOgcQAOgdAagPQAZgQAhAAQAjAAAZAQQAZAPAOAdQAOAcAAAmQAAAmgOAcQgOAdgZAOQgZAPgjABQgigBgZgPgAgng/QgNAUAAAsQAAAtANATQANAVAagBQAbABANgVQAMgTAAgtQAAgsgMgUQgNgVgbAAQgaAAgNAVg");
	this.shape_10.setTransform(-11.475,4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6CC14C").s().p("AhdB7QgBAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIgCgEIAAjoQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQACgDADAAIBZAAQAwAAAZARQAaARAAAfQAAASgKANQgKANgXAJIgBACIABABQAaAIALANQAMAOAAAWQAAAigaAQQgZAQgyABgAgqAZIAAA0QAAAGAFAAIAkAAQAUABALgKQALgIAAgPQAAgLgFgGQgGgIgJgEQgJgDgMAAIgkAAQgGAAAAAGgAgqhNIAAAzQAAAFAFABIAlAAIAPgCQAGgBAFgEQAGgFADgFQADgFAAgJQAAgPgMgIQgLgJgRABIgiAAQgGAAAAAFg");
	this.shape_11.setTransform(-35.675,4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAMBOQgPAAgHgHQgIgHAAgOIAAhBQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBAAIgPAAQAAAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgOQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIARAAQAAAAAAgBQABAAAAAAQAAAAAAgBQAAAAAAgBIADghQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIASAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAhQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABAAIAZAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAOQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgYAAQgBAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAABIAAA6QAAAIAEAEQADADAIAAIANAAIACAAIABADIAAAMQAAADgFAAIgHABIgJABg");
	this.shape_12.setTransform(51.55,120.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgJBSIgEgBIAAgDIAAhsQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAABAAIAVAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIAABrIgBAEIgEABgAgKgyQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgBgEIAAgVQAAgFAEAAIAVAAQAEAAAAAEIAAAWQAAAFgGAAg");
	this.shape_13.setTransform(44.275,120.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAbA7IgDAAIgBgDIAAhLQAAgJgEgEQgFgFgJAAQgFAAgEABQgEACgFAEIgJAIIAABNQAAAEgFAAIgUAAQgEABAAgEIAAhtQAAAAAAgBQABgBAAAAQAAgBABAAQABAAAAAAIAWAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAMIABACIACgBIAMgKQAGgEAFgCQAGgDAIABQAQAAAKAJQAJAKAAAPIAABPQAAAEgFAAg");
	this.shape_14.setTransform(35.025,122.75);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgkBMQgOgIgGgOQgGgOAAgWIAAhgQAAgEADAAIAaAAQADAAAAAEIAABlQAAATAJAJQAIAIAPAAQALAAAIgDQAHgEAEgIQAFgIAAgNIAAhlQAAgEADAAIAUAAQADAAAAAEIAABkQAAAWgHAOQgIANgOAGQgOAGgUAAQgWAAgOgHg");
	this.shape_15.setTransform(20.575,120.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgvBMQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgNIABgDIAGgBIAOAAQAEAAAEgCIAGgGIADgIQABgDgBgDIgrhoQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAABAAIAXAAIACABIACACIAaBIQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAbhIIACgCIACgBIAQAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAIguBzQgFAKgEAGQgEAHgFADQgGAEgGABQgHACgKAAg");
	this.shape_16.setTransform(2.0917,124.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgfA7IgDAAIgBgDIAAhtQAAAAAAgBQABgBAAAAQAAgBABAAQABAAAAAAIAVAAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIAAAOIAAABIADgBQAEgGAFgEIALgHQAGgDAGABQAIgBAAAEIAAAWQAAAAAAABQgBAAAAABQAAAAgBAAQgBAAAAAAIgHgBIgHAAIgJABIgJAFIgFAHQgCAEAAADIAABDQAAAEgFAAg");
	this.shape_17.setTransform(-8.725,122.75);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgbA1QgOgIgHgNQgIgNAAgRQAAgSAIgOQAIgOANgHQANgJAPABQARAAAMAHQANAHAHAOQAHANAAATIgBADQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIhNAAIgCABIAAADQAAAJAEAHQAEAHAIAFQAHADAIABQAJgBAHgDQAHgEAHgIIACgCIACABIANAHQABAAAAAAQABABAAAAQAAAAAAABQgBABAAAAQgHAKgHAGQgIAFgJADQgJADgMgBQgPAAgNgHgAgMglQgHAEgDAIQgEAHAAAIIAzAAIADAAIABgCQAAgIgDgGQgDgGgGgFQgGgFgJABQgIgBgGAFg");
	this.shape_18.setTransform(-20.025,122.85);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgGA6QgEAAgCgEIgshrQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIADgBIAXAAIADABIACACIAbBHQABAEADgEIAchHIABgCIADgBIAQAAIADABIAAADIgsBrQgCAEgFAAg");
	this.shape_19.setTransform(-32.6875,122.875);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("Ag1BSQgEAAAAgEIAAibQAAgEADAAIBqAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAARQAAAEgEAAIhIAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABAAABIAAAmQAAABAAABQAAAAAAABQABAAAAABQABAAABAAIAxAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAARIAAACIgDAAIgxAAQgBAAgBAAQAAABgBAAQAAAAAAABQAAAAAAABIAAApQAAAAAAABQAAABAAAAQABAAAAABQABAAAAAAIBMAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAAARIgBADIgDABg");
	this.shape_20.setTransform(-45.525,120.525);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgMBSQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAhaQAAAAAAgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgOIABgCIACgBIARAAQABAAAAAAQABAAAAAAQAAgBAAAAQAAgBAAgBIAAgOQABgOAHgIQAIgIAOAAIAVAAQAEAAAAAEIAAANIgBACIgCABIgNAAQgFAAgDAEQgDAEgBAGIAAALQAAAAABABQAAAAAAABQAAAAABAAQAAAAABAAIAVAAIACABIABACIAAAOQAAABAAABQAAAAgBAAQAAABgBAAQgBAAAAAAIgUAAQgBAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAABaQAAABAAAAQAAABgBABQAAAAgBAAQAAABgBAAg");
	this.shape_21.setTransform(45.6,97.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgNBSQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhaQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgOIAAgCIAEgBIAQAAQABAAAAAAQABAAAAAAQAAgBAAAAQABgBAAgBIAAgOQgBgOAJgIQAHgIAOAAIAUAAQAFAAAAAEIAAANIAAACIgDABIgNAAQgGAAgDAEQgCAEAAAGIAAALQAAAAAAABQAAAAAAABQAAAAABAAQAAAAABAAIAUAAIADABIABACIAAAOQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgUAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAABaQAAABAAAAQAAABgBABQAAAAgBAAQAAABgBAAg");
	this.shape_22.setTransform(35.65,97.875);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgmBKQgRgKgIgTQgJgSAAgaQAAgaAJgTQAJgSAQgLQARgKAVAAQAXAAAQAKQAQALAJASQAJATAAAaQAAAagIASQgJATgRAKQgQAKgXAAQgVAAgRgKgAgdgtQgJAPAAAfQAAAfAJAOQAKAPATAAQAUAAAKgPQAJgOAAgfQAAgfgJgPQgKgPgUAAQgTAAgKAPg");
	this.shape_23.setTransform(22.825,97.875);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AghBKQgPgKgIgTQgJgSAAgaQAAgTAFgPQAFgQAJgLQAJgLAMgGQAMgGANAAQAOAAAMAGQAMAGAJALQAJALAFAPQAFAQAAATQAAAagJASQgIATgPAKQgPAKgTAAQgSAAgPgKgAgRg2QgHAHgEANQgEAOAAAVQAAAVAEANQAEANAHAGQAIAGAJAAQALAAAHgGQAHgGAEgNQAEgNAAgVQAAgVgEgOQgEgNgHgHQgIgGgKAAQgJAAgIAGg");
	this.shape_24.setTransform(2.125,97.875);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AghBKQgPgKgIgTQgJgSAAgaQAAgTAFgPQAFgQAJgLQAJgLAMgGQAMgGANAAQAOAAAMAGQAMAGAJALQAJALAFAPQAFAQAAATQAAAagJASQgIATgPAKQgPAKgTAAQgSAAgPgKgAgRg2QgHAHgEANQgEAOAAAVQAAAVAEANQAEANAHAGQAIAGAJAAQALAAAHgGQAHgGAEgNQAEgNAAgVQAAgVgEgOQgEgNgHgHQgIgGgKAAQgJAAgIAGg");
	this.shape_25.setTransform(-14.175,97.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgpBSQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAgTQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAZAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIAAhlQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgYAHQgDABAAgEIAAgNIAAgDIACgBIAkgSIAEgCIADgBIANAAQABAAABABQAAAAAAAAQABABAAABQAAAAAAABIAACEQAAABAAAAQAAAAAAABQABAAAAAAQAAAAABAAIAXAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAASIgBADIgDABg");
	this.shape_26.setTransform(-27.25,97.875);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgDBiQgBAAAAAAQgBAAgBgBQAAAAAAgBQAAAAAAgBIAAgLIgBgCIgCgBQgRAAgMgGQgMgFgJgKQgFgEADgDIALgLIADgCIADACQAHAHAIAFQAIAFAMABQAAAAABAAQAAAAABAAQAAgBAAAAQABAAAAgBIAAgrIgBgDIgDgCQgRgFgLgGQgKgGgFgJQgEgJAAgLQAAgMAGgJQAFgKALgGQALgHAOgCIADgBIABgCIAAgJIABgDIABAAIAMAAIADABIABADIAAAJQAAABAAAAQAAAAAAAAQABABAAAAQAAAAABAAQAMACAKAEQAJAFAIAGQADACgCADIgLANIgCABIgDgBQgEgFgGgDQgGgEgIgBIgCAAIAAACIAAArQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABABIALADQAMAEAIAFQAJAHAFAJQAEAIAAALQAAANgGAKQgGAKgKAGQgLAGgPABIgDABIAAACIAAAKQAAAEgFAAgAAMASIAAApQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAQALgBAHgGQAGgGAAgIQAAgIgFgGQgGgGgMgDIgDgBIAAADgAgJg9QgLABgGAHQgGAGAAAIQAAAFACAEIAHAHQAEADAIADIAEAAIABgEIAAgmQAAAAgBgBQAAAAAAgBQAAAAAAAAQgBAAAAAAIgBAAg");
	this.shape_27.setTransform(-39.81,98.025);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgHA0QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAgPQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIAQAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAQQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAgAgCAWIgCgBIgBgBIgEhFIAAgCIABAAIAQAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIgEBFIgBABIgDABg");
	this.shape_28.setTransform(68.55,-23.65);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgRAhQgIgEgFgIQgFgJAAgLQAAgMAFgIQAFgJAIgFQAJgEAJgBQALABAHAEQAJAEAEAJQAEAJAAALIAAADIgCABIgxAAIgBAAIAAABQAAAGADAFQADAEAEADQAFADAEgBQAGAAAFgCQAEgCAFgGIABAAIABAAIAJAEQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgEAGgFAEQgFADgGACQgGACgHAAQgKgBgIgFgAgIgXQgDADgCAEQgDAEAAAGIAgAAIACAAIAAgCQAAgEgCgFQgCgEgDgCQgEgDgGAAQgEAAgFADg");
	this.shape_29.setTransform(62.7,-22.15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgFA0QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhiQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABiIAAACIgDABg");
	this.shape_30.setTransform(56.825,-23.65);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgaAhQgGgGAAgJQAAgIAFgFQAFgFAIgDQAJgDAMgBIAHgBIABAAIABgCIAAgDQgBgGgDgDQgEgEgGAAQgEAAgEADQgFACgDAEIgBACIgCAAIgLgEIgBgBIABgBQADgJAIgDQAJgFAKAAQALAAAHADQAHAEADAEQADAGAAAHIAAAwIAAACIgDABIgLAAIgCgBIgBgDIAAgDQAAgBAAAAQgBgBAAAAQAAAAgBABQAAAAgBABQgEAEgGACQgFADgHAAQgKAAgHgGgAAAADIgHACQgEACgBACQgCAEAAACQAAAFAEADQADADAGAAIAGgBIAFgDIAEgFQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIAAgKQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgGAAIgIACg");
	this.shape_31.setTransform(50.9,-22.15);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgFIgBgDIABgCIAJgFIADgCIACACIAGAHQAEADAEACIALAAQAJAAAGgCQAGgEAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgFgDgFQgCgFAAgHQAAgIAEgIQAFgGAJgFQAJgDAKAAQAIAAAGABQAHACAFAEQAGADADAEIABACIgBACIgKAHIgBAAIgCgBQgDgEgFgCQgFgDgIgBQgJAAgFAEQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMADAGAHQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAFgMAAQgJAAgIgDg");
	this.shape_32.setTransform(42.5667,-23.65);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_33.setTransform(32.475,-22.225);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgRAhQgJgEgEgIQgFgJAAgLQAAgMAFgIQAFgJAIgFQAJgEAJgBQAKABAIAEQAJAEAEAJQAEAJAAALIAAADIgCABIgxAAIgBAAIAAABQAAAGACAFQADAEAFADQAEADAFgBQAGAAAFgCQAEgCAFgGIABAAIABAAIAJAEQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgEAGgFAEQgFADgGACQgGACgHAAQgKgBgIgFgAgIgXQgDADgDAEQgCAEAAAGIAgAAIACAAIAAgCQAAgEgBgFQgCgEgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_34.setTransform(25.25,-22.15);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAoAmIgCgBIAAgCIAAgvQAAgFgEgDQgCgDgGAAIgGABIgFADIgEADIgBACIgBADIAAAuQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgBgBIgBgCIAAgvQAAgFgDgDQgDgDgFAAQgFAAgEACQgEACgFAFIAAAxQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgNAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAhEQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHIAAABIABgBIAIgGQAEgCAEgBQAEgCAEAAQAIAAAFAEQAEADACAGIABAAIACAAIAHgHQAEgDAEgBQAEgCAFAAQAKAAAGAGQAFAGABAKIAAAyQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_35.setTransform(14.85,-22.225);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAnAmIgBgBIgBgCIAAgvQABgFgDgDQgDgDgFAAIgHABIgFADIgEADIgBACIgBADIAAAuQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgBgBIgBgCIAAgvQAAgFgDgDQgCgDgGAAQgFAAgEACQgEACgEAFIAAAxQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIANAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGQADgCAEgBQAEgCAEAAQAIAAAFAEQAFADACAGIAAAAIACAAIAHgHQAEgDAFgBQAEgCAEAAQAKAAAFAGQAHAGAAAKIAAAyQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_36.setTransform(2.1,-22.225);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgVAjQgFgDgDgFQgDgFAAgGIAAgyQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAIANAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAAuQAAAGADADQADADAGAAQAEAAAEgCIAJgHIAAgxQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAABEQAAAAAAABQgBAAAAABQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgGADQgFADgGAAQgGAAgFgDg");
	this.shape_37.setTransform(-8.475,-22.075);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgFIgBgDIABgCIAJgFIADgCIACACIAGAHQAEADAEACIALAAQAJAAAGgCQAGgEAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgFgDgFQgCgFAAgHQAAgIAEgIQAFgGAJgFQAJgDAKAAQAIAAAGABQAHACAFAEQAGADADAEIABACIgBACIgKAHIgBAAIgCgBQgDgEgFgCQgFgDgIgBQgJAAgFAEQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMADAGAHQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAFgMAAQgJAAgIgDg");
	this.shape_38.setTransform(-17.2333,-23.65);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgHA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAgBIAAg4QAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAgBAAIgLAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgIIABgCIABAAIALAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgJQABgJAFgFQAEgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAAIIgBACIgBAAIgJAAQgDAAgCADQgCACAAAEIAAAHQAAABABAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABAAIABACIAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAAA4QAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_39.setTransform(-27.45,-23.65);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgTAhQgHgEgFgJQgFgJAAgLQAAgKAFgJQAFgJAIgEQAIgGAKAAQALAAAIAGQAJAEAEAJQAFAJAAAKQAAALgFAJQgEAJgJAEQgIAFgLABQgKgBgJgFgAgJgWQgEACgDAHQgCAFAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDACgGQACgFAAgJQAAgIgCgFQgCgHgEgCQgEgDgGgBQgFABgEADg");
	this.shape_40.setTransform(-34.4,-22.15);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgUAwQgHgEgEgIQgDgJAAgMQAAgMAEgIQAEgJAHgEQAHgFAJAAQAFAAAEACQAFACAEADIACABIAAgCIAAggQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAOAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABiIAAACIgDAAIgMAAIgCAAIgBgCIAAgFIAAgBIgBABIgFAEIgHADQgEACgFAAQgIAAgHgFgAgHgIQgEACgDAGQgCAFAAAKQAAAJACAGQADAGAEACQAEADAEAAQAFAAADgCQAEgCACgEQACgDAAgDIAAgfIgHgFQgEgCgEAAQgFAAgEADg");
	this.shape_41.setTransform(-45.875,-23.575);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AARAmIgCgBIgBgCIAAgvQAAgFgCgDQgDgDgGAAIgGABIgFADIgGAFIAAAxQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgNAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAHIAAABIABgBIAIgGIAHgDQAEgCAFAAQAKAAAGAGQAGAGAAAKIAAAyQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_42.setTransform(-54,-22.225);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhiQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIguAAQAAAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABIAAAYQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAAAQAAABABAAQAAABAAAAIAAAKIAAABIgCABIgfAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAABABAAIAwAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAIAAAMIgBABIgCABg");
	this.shape_43.setTransform(-62.425,-23.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.7,-33.9,152.60000000000002,170);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_02_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_01();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Ag0AAIBpAAIgeAjAAcgiIAZAi");
	this.shape.setTransform(35.525,0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AFrA4QgJgFgEgHIgBgDIABgBIAMgFIABABIAFAFQAEAEAEABQAFACAGgBQAFABAEgCQAEgBADgCQACgDAAgDQAAgEgDgCQgCgCgHgCIgRgEQgMgCgGgHQgFgFAAgJQAAgHAEgGQAEgGAIgEQAIgDALAAQAMAAAIAEQAJAFAEAGIABACIgBACIgKAEIgCAAIgBgBQgDgEgFgCQgFgDgHAAQgHAAgFADQgFACAAAFQAAADACACQACABAHACIATAGQAMACAGAHQAFAGAAAJQAAAIgFAGQgEAGgJADQgIADgLAAQgOAAgKgFgAD/A4QgKgFgFgLQgFgLAAgPIAAhFQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAABJQAAAOAGAGQAGAGAMAAQAIAAAFgDQAGgCADgHQADgFAAgKIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABIQAAAQgGAKQgFAJgLAFQgKAEgOAAQgRAAgKgFgABAA4QgJgGgGgKQgFgJAAgNQAAgNAFgKQAGgKAJgGQAKgFAMAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEgGIgFgEQgDgCgEAAQgHAAgFAEQgFADgCAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAHAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgMAAgKgFgAgsA3QgHgHAAgKQAAgJAFgHQAFgGALgEQAKgEAOAAIAHAAIACgBIAAgCIAAgDQAAgHgDgDQgEgFgHAAQgGAAgFADQgFADgDAFIgBACIgCAAIgOgEIgBgBIABgCQAEgJAJgGQAKgEAOAAQALAAAIADQAHAEAEAGQADAGAAAHIAAA4IAAADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBgBAAQAAgBAAAAQgBAAAAABQgBAAAAAAQgFAGgGACQgHADgIAAQgMAAgHgGgAgFATIgKABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAHAAQAEAAAEgBIAGgEIAEgFIABgFIAAgLQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAgAkbA4QgKgGgFgKQgFgKAAgMQAAgNAFgKQAGgKAJgGQAKgFAMAAQAMAAAKAGQAJAFAGAKQAFAKAAANQAAAMgGAKQgFAKgJAGQgKAFgMAAQgNAAgJgFgAkRgIQgEADgDAGQgCAHAAAJQAAAJACAIQADAGAEAEQAFADAHAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgJgDgHQgCgGgFgDQgFgEgGAAQgHAAgFAEgAmOA2QgMgIgGgOQgHgOAAgSQAAgSAHgOQAGgNAMgHIAEgCQAKgGAOAAQAJAAAIADIAGADIAIAEQAGAFAEAGQAEAGABAIIABACIgCABIgSABIgCAAIgBgCQgCgIgFgGQgGgGgKAAQgOAAgHAKQgIALAAAWQAAAWAHALQAIALAOAAQAKgBAHgFQAHgEAFgMQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANADIABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgEAIIgGAJQgEAFgFADQgGADgHADQgHACgJAAQgQAAgMgHgACVA3QgGgGAAgKIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIADgZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIASAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgSABQgLAAgFgEgAhgA3QgFgGAAgKIAAguQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgKQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIALAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAABIASAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAAAqQAAAGADADQACACAGAAIAJAAIACABIABABIgBAJQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgRABQgLAAgGgEgAiTA7IgCAAIgBgDIAAg2QAAgFgDgEQgEgDgGAAIgIABIgGADIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgEQAFgCAFAAQAMAAAHAHQAHAHAAALIAAA5QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(-8.4812,0.4592,0.8099,0.8099);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(0.4,1,1).p("AoliLIRLAAIAAEXIxLAAg");
	this.shape_2.setTransform(-0.95,0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC24D").s().p("AolCMIAAkXIRLAAIAAEXg");
	this.shape_3.setTransform(-0.95,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.9,-14.7,112,30);


(lib.BG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


// stage content:
(lib.WBAY_219645_MM_300x250_V2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(390));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(221.05,220.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(41).to({_off:false},0).to({alpha:1},13,cjs.Ease.get(1)).wait(336));

	// logo_png
	this.instance_1 = new lib.logo_1("synched",0);
	this.instance_1.setTransform(80,290);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(7).to({_off:false},0).to({y:300,alpha:1},17,cjs.Ease.get(1)).wait(366));

	// T3
	this.instance_2 = new lib.T3("synched",0);
	this.instance_2.setTransform(220.25,190.05);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(271).to({_off:false},0).to({y:170.05,alpha:1},15,cjs.Ease.get(1)).wait(104));

	// T2
	this.instance_3 = new lib.T2("synched",0);
	this.instance_3.setTransform(220.05,143.15);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(151).to({_off:false},0).to({y:123.15,alpha:1},16,cjs.Ease.get(1)).wait(77).to({startPosition:0},0).to({alpha:0},10).to({_off:true},1).wait(135));

	// T1
	this.instance_4 = new lib.T1("synched",0);
	this.instance_4.setTransform(219,43.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(26).to({_off:false},0).to({y:52,alpha:1},15,cjs.Ease.get(1)).wait(83).to({startPosition:0},0).to({alpha:0},10).to({_off:true},1).wait(255));

	// Img_04_jpg
	this.instance_5 = new lib.Img_04_1("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(299).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(74));

	// Img_03_jpg
	this.instance_6 = new lib.Img_03_1("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(254).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(119));

	// Img_02_jpg
	this.instance_7 = new lib.Img_02_1("synched",0);
	this.instance_7.setTransform(80,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(134).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(239));

	// Img_01_jpg
	this.instance_8 = new lib.Img_01_1("synched",0);
	this.instance_8.setTransform(80,300);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(9).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(364));

	// BG_jpg
	this.instance_9 = new lib.BG_1("synched",0);
	this.instance_9.setTransform(80,300);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},17,cjs.Ease.get(1)).wait(373));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,115,152,136);
// library properties:
lib.properties = {
	id: 'EEE0CBDE3F5A41B0A2F5275DEDC5F0C8',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EEE0CBDE3F5A41B0A2F5275DEDC5F0C8'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;