(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1024,90);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgNAaQgGgEgEgGQgEgHAAgIQAAgJAEgGQAEgHAGgEQAHgEAHAAQAIAAAGAEQAGAEADAGQAEAHAAAIIAAACIgCABIglAAIgBAAIAAACQAAAEACAEQACADADACQAEACADAAQAFAAADgCQAEgCADgEIABAAIABAAIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQAAABgBAAQgDAFgEACQgEADgEACIgKABQgHAAgHgEgAgFgSQgEADgBADQgCAEAAAEIAYAAIACAAIAAgCQAAgDgBgDIgFgGQgDgCgEAAQgDAAgDACg");
	this.shape.setTransform(120.275,10.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgPAaQgGgDgDgFIAAgBIAAgBIAHgEIABAAIABABIAEAEIAFADIAGABIAGgBIAFgDQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAgBgBAAIgGgDIgKgDQgIgCgEgDQgEgDAAgGQAAgGADgEQADgEAFgCQAFgDAHAAQAIAAAFADQAGADADAFIABABIgBABIgHADIgBAAIgBAAQgCgDgDgCQgEgCgFAAQgDAAgDACQgDACAAADIABADIAGADIALAEQAJACADADQAEAEAAAGQAAAGgDAEQgDAEgGACQgGACgHAAQgIAAgHgEg");
	this.shape_1.setTransform(113.925,10.375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgUAZQgEgEAAgHQAAgGADgEQAEgEAGgCQAHgDAJAAIAFAAIABgBIABgBIAAgCQAAgFgDgDQgDgCgFAAIgGABQgDACgCAEIgBABIgBAAIgKgDIAAAAIAAgCQADgGAGgDQAHgEAIAAQAIAAAFADQAGACACAEQACAEAAAGIAAAlIAAABIgBABIgKAAIgBgBIgBgCIAAgDQAAgBAAAAQAAAAAAAAQgBAAAAAAQAAAAgBABQgEADgEACQgDACgGAAQgIAAgFgFgAAGABIgGABIgFACIgEAEQgBAAAAABQAAAAAAABQgBAAAAABQAAABAAAAQAAAEADACQADACAEAAIAFgBIAEgCIADgDQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgHQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_2.setTransform(107.475,10.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AANAoIgBAAIgBgCIAAglQAAgDgCgCQgCgDgFAAIgEABQgCABgCACIgFADIAAAmQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhLQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAbIAAABIABAAIAHgFIAFgDIAGgBQAJABAEAEQAFAFgBAHIAAAmQAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_3.setTransform(101.35,9.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgMAaQgGgEgEgGQgDgHAAgJQAAgIADgGQAEgHAGgEQAHgEAHAAQAGAAAFADQAFACADADIAFAIQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgJABQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIgCgEIgEgDIgFgBQgDAAgDACQgEACgBAFQgCAFAAAFQAAAHACAEQACAFADACQADADAEAAQAFAAADgDQADgDADgEIAAgBIACABIAGABIABACIgDAFIgFAGIgHADQgEACgFAAQgHAAgHgEg");
	this.shape_4.setTransform(95.175,10.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgOAdIgCAAIAAgCIAAg0QAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIALAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAGIAAABIABAAIAFgGIAFgDIAFgBQABAAABAAQABAAABAAQAAAAAAABQABAAAAABIAAAKQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgDAAIgDAAIgFAAIgEADIgDADIgBAEIAAAgQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_5.setTransform(90.55,10.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgQAbQgEgCgCgEQgDgEABgFIAAgmQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAkQAAAEADACQACADAEAAQADAAADgCIAHgFIAAgmQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAA1QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAgGIgBgBIAAABQgFAEgFACQgEACgEAAQgGAAgDgCg");
	this.shape_6.setTransform(84.7,10.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgcAoIgCAAIgBgCIAAhLQAAgBABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAdAAQAKAAAHACQAGADAFAGQADAFAAAJQAAAIgDAEQgEAFgGADQgHACgJAAIgQAAIgBABIAAAdQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgPgaIAAAWQAAAAABABQAAAAAAAAQAAABAAAAQABAAAAAAIANAAQAHAAAEgDQAEgEAAgGQAAgEgCgDQgBgDgEgCIgIgBIgNAAQAAAAAAABQgBAAAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_7.setTransform(77.8,9.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgXAjQgIgDABgIQAAgEACgCIAIgEQAAgBAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIgFgDQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIABgDIAEgDIAEgCIABgBIAAAAQgFgDgDgEQgDgDAAgFQAAgIAIgFQAGgFANAAIAJABIAHAEIABABIABgBIAEgDIAEgDIADAAIACAAIABACIAAAGIgBACIgCAAIgCAAIgDAAQgBABAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIABADIAAADQAAAEgDAEQgDAFgFACQgGADgHgBIgHABIgEABIgCACQAAAAABAAQAAABAAAAQAAAAAAAAQABAAAAABIAGAAIAOABQAKABAGAEQAEAEAAAHQABAIgJAFQgHAFgNAAQgQAAgHgEgAgOAQQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAACACADQACACAFABIAKABQAIAAADgCQAFgDAAgEQAAgDgCgBQgDgDgEAAIgQgBIgFABgAgKgbQgDADgBAFQABAEADADQADADAGAAQAGAAADgDQACgDAAgEQAAgFgCgDQgDgDgGAAQgGAAgDADg");
	this.shape_8.setTransform(67.1,11.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AANAdIgBAAIgBgCIAAgkQAAgEgCgCQgCgDgFAAIgEABQgCABgCACIgFAEIAAAlQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAg0QAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFIAAABIABAAIAGgFIAGgDQADgBADAAQAIAAAFAFQAEAEABAIIAAAmQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_9.setTransform(60.5,10.325);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgEAoIgCAAIAAgCIAAg0QAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAzIgBADIgCAAgAgEgZIgCAAIAAgCIAAgKQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_10.setTransform(55.725,9.25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgWAlQgBAAAAAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAgIIABgBIACAAIAHAAIAEgBIADgDIACgEIgBgDIgUgzIAAgBIABAAIAMAAIABAAIABABIAMAjIABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIANgjIABgBIABAAIAIAAIABAAIAAABIgWA4IgEAIIgEAGIgGABIgIABg");
	this.shape_11.setTransform(51.375,11.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgGAoQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgsIgBgCIgJAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgGIAAgCIABAAIAJAAQAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAgBIAAgHQAAgGAEgFQADgDAHAAIAKAAQAAAAABAAQAAAAAAAAQAAABABAAQAAABAAAAIAAAGIAAABIgBABIgHAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgCACAAAEIAAAEQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABAAIAKAAIABAAIABACIAAAGQAAAAAAABQgBAAAAAAQAAAAAAAAQgBAAAAAAIgKAAIgBACIAAArQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAg");
	this.shape_12.setTransform(46.675,9.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgEAoIgCAAIAAgCIAAg0QAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAzIgBADIgCAAgAgEgZIgCAAIAAgCIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_13.setTransform(42.975,9.25);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgEAoQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhLQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABKIAAADIgCAAg");
	this.shape_14.setTransform(40.025,9.25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgUAZQgEgEAAgHQAAgGADgEQAEgEAGgCQAHgDAJAAIAFAAIABgBIABgBIAAgCQAAgFgDgDQgDgCgFAAIgGABQgDACgCAEIgBABIgBAAIgKgDIAAAAIAAgCQADgGAGgDQAHgEAIAAQAIAAAFADQAGACACAEQACAEAAAGIAAAlIAAABIgBABIgKAAIgBgBIgBgCIAAgDQAAgBAAAAQAAAAgBAAQAAAAAAAAQAAAAgBABQgEADgEACQgDACgGAAQgIAAgFgFgAAGABIgGABIgFACIgEAEQgBAAAAABQAAAAAAABQgBAAAAABQAAABAAAAQAAAEADACQADACAEAAIAFgBIAEgCIADgDQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgHQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_15.setTransform(34.975,10.375);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgRAbQgDgCgCgEQgCgEgBgFIAAgmQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAABIAAAkQAAAEACACQADADAEAAQACAAADgCIAHgFIAAgmQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIALAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIgBA1QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgLAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAgGIAAgBIgBABQgEAEgFACQgEACgEAAQgFAAgFgCg");
	this.shape_16.setTransform(28.75,10.45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAUAsQgFgDgFgGQAAgBAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgDABIgFAAQgKAAgIgFQgIgFgEgJQgFgJAAgMQAAgNAFgJQAEgKAIgFQAIgEAKAAQALAAAIAEQAJAFAEAKQAEAJAAANQAAALgDAIQgEAIgGAFIgBABIACADQABACADABIAHACIAAAAIAAABIAAAIIAAACIgDAAQgGAAgGgDgAgNgcQgFAIAAAPQAAAOAFAHQAEAHAJAAQAKAAAFgHQAFgHgBgOQABgPgFgIQgFgHgKAAQgJAAgEAHg");
	this.shape_17.setTransform(20.85,9.875);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AANAoIgBAAIgBgCIAAglQAAgDgCgCQgCgDgFAAIgEABQgCABgCACIgFADIAAAmQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhLQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIALAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAbIAAABIABAAIAHgFIAFgDIAGgBQAJABAEAEQAFAFgBAHIAAAmQAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_18.setTransform(9.9,9.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAFAmQgGAAgEgDQgEgEAAgGIAAggQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIAIAAQAAAAAAAAQAAAAAAAAQABAAAAgBQAAAAAAAAIABgRQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAIAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAARIABABIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgNAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAcQAAAEACACQACABAEAAIAGAAIABABIAAABIAAAFQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgEAAIgEAAg");
	this.shape_19.setTransform(4.475,9.425);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgEAoIgCAAIAAgCIAAg0QAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAzIgBADIgCAAgAgEgZIgCAAIAAgCIAAgKQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_20.setTransform(0.725,9.25);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AATAoQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIgPgzIgBgBIAAABIgOAzQgBAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgKAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIgWhKIAAgCIACgBIALAAIACABIAAABIAQA1IAAAAIABAAIAPg1IABgBIACgBIAJAAIABABIABABIAPA1IABABIABgBIAPg1IABgBIABgBIAJAAIABABIABABIgWBLQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAAAAAg");
	this.shape_21.setTransform(-5.5542,9.25);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgOAdIgDAAIAAgCIAAg0QAAgBABAAQAAAAAAAAQAAgBAAAAQABAAAAAAIALAAQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAGIAAABIABAAIAFgGIAFgDIAGgBQABAAAAAAQABAAAAAAQABAAAAABQAAAAAAABIAAAKQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgDAAIgEAAIgEAAIgFADIgCADIAAAEIAAAgQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_22.setTransform(142,-2.275);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgNAaQgGgEgEgGQgEgHAAgIQAAgJAEgGQAEgHAGgEQAHgEAHAAQAIAAAGAEQAGAEADAGQAEAHAAAIIAAACIgCABIglAAIgBAAIAAACQAAAEACAEQACADADACQAEACADAAQAFAAADgCQAEgCADgEIABAAIABAAIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQAAABgBAAQgDAFgEACQgEADgEACIgKABQgHAAgHgEgAgFgSQgEADgBADQgCAEAAAEIAYAAIACAAIAAgCQAAgDgBgDIgFgGQgDgCgEAAQgDAAgDACg");
	this.shape_23.setTransform(136.225,-2.225);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AANAoIgCAAIAAgCIAAglQAAgDgCgCQgCgDgFAAIgDABQgDABgCACIgEADIAAAmQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgJAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAhMQAAAAABAAQAAAAAAgBQAAAAAAAAQABAAAAAAIALAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAcIABABIAAAAIAHgFIAFgDIAGgBQAJABAEAEQAEAFABAHIAAAmQgBABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_24.setTransform(129.75,-3.35);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgMAaQgGgEgEgGQgDgHAAgJQAAgIADgGQAEgHAGgEQAHgEAHAAQAGAAAFADQAFACADADIAFAIQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgJABQgBAAAAAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIgCgEIgEgDIgFgBQgDAAgDACQgEACgBAFQgCAFAAAFQAAAHACAEQACAFADACQADADAEAAQAFAAADgDQADgDADgEIAAgBIACABIAGABIABACIgDAFIgFAGIgHADQgEACgFAAQgHAAgHgEg");
	this.shape_25.setTransform(123.575,-2.225);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgQAbQgEgCgCgEQgDgEABgFIAAgmQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAkQAAAEADACQACADAEAAQADAAADgCIAHgFIAAgmQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIgBA1QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAgGIgBgBIAAABQgFAEgFACQgEACgEAAQgGAAgDgCg");
	this.shape_26.setTransform(117.2,-2.15);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgOAaQgHgEgDgGQgDgHAAgJQAAgIADgGQAEgHAGgEQAHgEAHAAQAJAAAGAEQAGAEAEAHQADAHAAAHQAAAJgDAHQgEAGgGAEQgHAEgIAAQgIAAgGgEgAgHgRQgDACgBAFQgCAFgBAFQABAHACAEQABAFADACQADACAEAAQAFAAADgCQADgCABgFQACgEAAgHQAAgFgCgFQgCgFgCgCQgDgCgFAAQgEAAgDACg");
	this.shape_27.setTransform(110.75,-2.225);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgFAoQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAIgahLIAAgBIABgBIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIATA6QAAAAAAABQAAAAAAAAQAAAAABgBQAAAAAAgBIATg5QAAAAABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAKAAIACABIAAABIgbBLQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_28.setTransform(103.7125,-3.35);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AANAdIgCAAIAAgCIAAgkQAAgEgCgCQgDgDgEAAIgDABQgDABgCACIgEAEIAAAlQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAg0QAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFIABABIAAAAIAGgFIAGgDQACgBAEAAQAIAAAEAFQAFAEABAIIAAAmQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_29.setTransform(93,-2.275);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgOAaQgHgEgDgGQgDgHAAgJQAAgIADgGQAEgHAGgEQAHgEAHAAQAJAAAGAEQAGAEAEAHQADAHAAAHQAAAJgDAHQgEAGgGAEQgHAEgIAAQgIAAgGgEgAgHgRQgDACgBAFQgCAFgBAFQABAHACAEQABAFADACQADACAEAAQAFAAADgCQADgCABgFQACgEAAgHQAAgFgCgFQgCgFgCgCQgDgCgFAAQgEAAgDACg");
	this.shape_30.setTransform(86.45,-2.225);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgEAoIgCAAIAAgCIAAg0QAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAzIgBADIgCAAgAgEgZIgCAAIAAgCIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIAKAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_31.setTransform(81.675,-3.35);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAFAmQgGAAgEgDQgEgEAAgGIAAggQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIAIAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIABgRQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAIAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAARIABABIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAHQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgNAAQAAAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAAcQAAAEACACQACABAEAAIAGAAIABABIAAABIAAAFQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgEAAIgEAAg");
	this.shape_32.setTransform(78.125,-3.175);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgUAZQgEgEAAgHQAAgGADgEQAEgEAGgCQAHgDAJAAIAFAAIABgBIABgBIAAgCQAAgFgDgDQgDgCgFAAIgGABQgDACgCAEIgBABIgBAAIgKgDIAAAAIAAgCQADgGAGgDQAHgEAIAAQAIAAAFADQAGACACAEQACAEAAAGIAAAlIAAABIgBABIgKAAIgBgBIgBgCIAAgDQAAgBAAAAQAAAAAAAAQgBAAAAAAQAAAAgBABQgEADgEACQgDACgGAAQgIAAgFgFgAAGABIgGABIgFACIgEAEQgBAAAAABQAAAAAAABQgBAAAAABQAAABAAAAQAAAEADACQADACAEAAIAFgBIAEgCIADgDQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgHQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_33.setTransform(72.175,-2.225);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgMAaQgGgEgEgGQgDgHAAgJQAAgIADgGQAEgHAGgEQAHgEAHAAQAGAAAFADQAFACADADIAFAIQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgJABQgBAAAAAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIgCgEIgEgDIgFgBQgDAAgDACQgEACgBAFQgCAFAAAFQAAAHACAEQACAFADACQADADAEAAQAFAAADgDQADgDADgEIAAgBIACABIAGABIABACIgDAFIgFAGIgHADQgEACgFAAQgHAAgHgEg");
	this.shape_34.setTransform(66.425,-2.225);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgUAZQgEgEAAgHQAAgGADgEQAEgEAGgCQAHgDAJAAIAFAAIABgBIABgBIAAgCQAAgFgDgDQgDgCgFAAIgGABQgDACgCAEIgBABIgBAAIgKgDIAAAAIAAgCQADgGAGgDQAHgEAIAAQAIAAAFADQAGACACAEQACAEAAAGIAAAlIAAABIgBABIgKAAIgBgBIgBgCIAAgDQAAgBAAAAQAAAAgBAAQAAAAAAAAQAAAAgBABQgEADgEACQgDACgGAAQgIAAgFgFgAAGABIgGABIgFACIgEAEQgBAAAAABQAAAAAAABQgBAAAAABQAAABAAAAQAAAEADACQADACAEAAIAFgBIAEgCIADgDQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgHQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_35.setTransform(59.725,-2.225);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgFAoQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAIgahLIAAgBIABgBIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIATA6QAAAAAAABQAAAAAAAAQABAAAAgBQAAAAAAgBIATg5QAAAAABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAKAAIACABIAAABIgbBLQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_36.setTransform(53.0625,-3.35);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgFAcQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgLQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAMQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAgAgFgLQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgMQAAAAAAgBQAAAAAAAAQABAAAAAAQABAAAAAAIALAAQABAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAMQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_37.setTransform(43.4,-2.15);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgPAaQgGgDgDgFIAAgBIAAgBIAHgEIABAAIABABIAEAEIAFADIAGABIAGgBIAFgDQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAIgGgDIgKgDQgIgCgEgDQgEgDAAgGQAAgGADgEQADgEAFgCQAFgDAHAAQAIAAAFADQAGADADAFIABABIgBABIgHADIgBAAIgBAAQgCgDgDgCQgEgCgFAAQgDAAgDACQgDACAAADIABADIAGADIALAEQAJACADADQAEAEAAAGQAAAGgDAEQgDAEgGACQgGACgHAAQgIAAgHgEg");
	this.shape_38.setTransform(38.975,-2.225);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgQAbQgEgCgCgEQgCgEgBgFIAAgmQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAABIAAAkQAAAEACACQADADAEAAQACAAADgCIAHgFIAAgmQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIALAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIgBA1QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgLAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAgGIAAgBIgBABQgEAEgFACQgEACgEAAQgFAAgEgCg");
	this.shape_39.setTransform(32.8,-2.15);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AANAdIgCAAIAAgCIAAgkQAAgEgCgCQgDgDgEAAIgDABQgDABgCACIgEAEIAAAlQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgKAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAg0QAAgBAAAAQAAAAAAAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAFIABABIAAAAIAGgFIAGgDQACgBAEAAQAIAAAEAFQAFAEABAIIAAAmQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_40.setTransform(26.4,-2.275);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgOAaQgHgEgDgGQgDgHAAgJQAAgIADgGQAEgHAGgEQAHgEAHAAQAJAAAGAEQAGAEAEAHQADAHAAAHQAAAJgDAHQgEAGgGAEQgHAEgIAAQgIAAgGgEgAgHgRQgDACgBAFQgCAFgBAFQABAHACAEQABAFADACQADACAEAAQAFAAADgCQADgCABgFQACgEAAgHQAAgFgCgFQgCgFgCgCQgDgCgFAAQgEAAgDACg");
	this.shape_41.setTransform(19.85,-2.225);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgdAoIgBAAIgBgBIAAhMIABgBIABgBIAcAAQAOAAAIAFQAJAFAAALQAAAGgDAEQgEAEgHADIgBABIABAAQAIACAEAEQAEAFAAAHQAAAMgJAEQgIAGgPAAgAgPAHIAAAUQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABAAIANAAQAHAAAEgDQAEgDAAgGQAAgEgCgDQgCgDgDgBQgEgBgEAAIgNAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAABAAAAgAgPgbIAAAUQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIANAAIAFAAIAEgDIAEgDIABgGQAAgFgEgDQgFgDgGAAIgMAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAAAg");
	this.shape_42.setTransform(12.925,-3.35);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAFAmQgGAAgEgDQgEgEAAgGIAAggQAAAAAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgHAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAgHQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIAIAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIABgRQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAIAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAARIABABIAMAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAIAAAHQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAAAIgNAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAcQAAAEACACQACABAEAAIAGAAIABABIAAABIAAAFQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgEAAIgEAAg");
	this.shape_43.setTransform(4.075,-3.175);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgPAaQgGgDgDgFIAAgBIAAgBIAHgEIABAAIABABIAEAEIAFADIAGABIAGgBIAFgDQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBgBAAIgGgDIgKgDQgIgCgEgDQgEgDAAgGQAAgGADgEQADgEAFgCQAFgDAHAAQAIAAAFADQAGADADAFIABABIgBABIgHADIgBAAIgBAAQgCgDgDgCQgEgCgFAAQgDAAgDACQgDACAAADIABADIAGADIALAEQAJACADADQAEAEAAAGQAAAGgDAEQgDAEgGACQgGACgHAAQgIAAgHgEg");
	this.shape_44.setTransform(-1.325,-2.225);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgQAbQgEgCgCgEQgDgEABgFIAAgmQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAkQAAAEADACQACADAEAAQADAAADgCIAHgFIAAgmQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIgBA1QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAgBAAIAAgGIAAgBIAAABQgFAEgFACQgEACgEAAQgGAAgDgCg");
	this.shape_45.setTransform(-7.45,-2.15);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgXAjQgHgDgBgIQABgEACgCIAHgEQABgBAAAAQAAAAAAAAQAAAAAAAAQAAAAgBAAIgDgDQgBgBAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBIABgDIADgDIAGgCIABgBIgBAAQgFgDgCgEQgDgDAAgFQAAgIAGgFQAHgFANAAIAJABIAHAEIACABIABgBIADgDIADgDIAFAAIABAAIAAACIAAAGIAAACIgBAAIgDAAIgDAAQgBABAAAAQgBAAAAABQAAAAAAAAQAAABAAAAIAAADIABADQAAAEgCAEQgDAFgGACQgFADgIgBIgHABIgFABIgBACQABAAAAAAQAAABAAAAQAAAAAAAAQABAAAAABIAGAAIAOABQALABAEAEQAGAEAAAHQgBAIgHAFQgIAFgOAAQgPAAgHgEgAgOAQQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABQAAACACADQACACAEABIALABQAIAAAEgCQAEgDAAgEQAAgDgDgBQgBgDgGAAIgQgBIgEABgAgLgbQgCADgBAFQABAEACADQAEADAGAAQAFAAADgDQAEgDAAgEQAAgFgEgDQgDgDgFAAQgGAAgEADg");
	this.shape_46.setTransform(-13.85,-1.35);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgQAbQgEgCgCgEQgDgEABgFIAAgmQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAkQAAAEADACQACADAEAAQADAAADgCIAHgFIAAgmQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAKAAQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABIgBA1QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAgBAAIAAgGIAAgBIAAABQgFAEgFACQgEACgEAAQgGAAgDgCg");
	this.shape_47.setTransform(-20.5,-2.15);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AAXAoQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIgHgSIAAAAIgBgBIgbAAIgBABIgHASIgBABIgBAAIgKAAIgCAAIAAgDIAchKIABgBIABgBIANAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABABAAIAbBKIAAACIgBABgAgBgVIgKAbQgBAAAAABQAAAAAAABQABAAAAAAQAAAAABAAIATAAQABAAAAAAQAAAAAAAAQAAgBAAAAQAAgBAAAAIgKgbIAAgBIgBABg");
	this.shape_48.setTransform(-27.3125,-3.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-37.4,-9.4,187.1,27);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAOAgIgBgBIgBgBIAAgoQAAgEgCgDQgDgCgEgBIgFABIgEADIgGAEIAAApQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgKAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAIAAg6QAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIAMAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAHIAAAAIABAAIAHgFIAGgEIAHAAQAJAAAFAEQAEAFABAJIAAApQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape.setTransform(85.05,-1.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAPAfQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIgLgjIgBgBIAAABIgLAjIgBABIgBABIgJAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAgBgBIgSg4IAAgCIABgBIAMAAIABABIABABIAMAkQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIAAgBIAMgkIAAgBIACgBIAHAAIACABIAAABIAMAkIABABIABgBIALgkIABgBIABgBIAIAAIABABIAAACIgSA4IgBABIgCABg");
	this.shape_1.setTransform(77.425,-1.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgPAcQgHgEgEgHQgEgHAAgKQAAgIAEgIQAEgHAHgEQAHgEAIAAQAJAAAHAEQAHAFAEAGQAEAIAAAIQAAAKgEAHQgEAHgHAEQgHAEgJAAQgIAAgHgEgAgHgSQgEACgBAFQgCAFAAAGQAAAHACAFQABAFAEACQADADAEAAQAFAAAEgDQADgCACgFQACgFAAgHQAAgGgCgFQgCgFgDgCQgEgDgFAAQgEAAgDADg");
	this.shape_2.setTransform(69.275,-1.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AggArQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAhRIABgCIACAAIAFAAIAHAAIAGAAIAFAAQAPAAAKAFQAKAGAFAJQAFAJAAANQAAANgFAKQgFAKgLAFQgKAFgPAAgAgRgcIAAA5QAAABAAAAQAAAAAAAAQAAABABAAQAAAAAAAAIADAAQALAAAGgDQAHgDADgHQAEgHAAgLQAAgKgEgHQgDgHgHgDQgFgDgLAAIgEAAQgBAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABg");
	this.shape_3.setTransform(61.425,-3.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgYApQgBgBAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgHIABgCIACAAIAIAAIAEgBIADgEIACgEQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgXg2IABgCQAAAAAAAAQAAAAAAAAQAAAAAAAAQABgBAAAAIAMAAIACABIABABIANAmIABABIABgBIAOgmIABgBIACgBIAIAAIACABIAAACIgZA8IgFAJQgBAEgDACQgDABgDABIgJABg");
	this.shape_4.setTransform(50.2875,-0.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgOAcQgHgEgEgHQgEgHAAgJQAAgJAEgIQAEgHAHgEQAHgEAIAAQAIAAAHAEQAHAEADAHQAEAHAAAJIAAACQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgoAAIgBAAIAAACQAAAEACAEQACAEAEACQAEACAEAAQAEAAAEgCQAEgCAEgEIABgBIABABIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQAAABgBAAQgDAGgEADQgEADgFABIgLABQgIAAgHgEgAgGgTQgDACgCAEQgCADAAAFIAaAAIACAAIAAgCIgBgHQgCgDgDgCQgDgDgFAAQgDAAgEADg");
	this.shape_5.setTransform(43.575,-1.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAOAgIgCgBIAAgBIAAgoQAAgEgCgDQgDgCgFgBIgEABIgFADIgFAEIAAApQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgKAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg6QAAAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIALAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAHIAAAAIACAAIAGgFIAGgEIAHAAQAJAAAEAEQAGAFAAAJIAAApQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_6.setTransform(36.75,-1.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgPAcQgHgEgEgHQgEgHAAgKQAAgIAEgIQAEgHAHgEQAHgEAIAAQAJAAAHAEQAHAFAEAGQAEAIAAAIQAAAKgEAHQgEAHgHAEQgHAEgJAAQgIAAgHgEgAgHgSQgEACgBAFQgCAFAAAGQAAAHACAFQABAFAEACQADADAEAAQAFAAAEgDQADgCACgFQACgFAAgHQAAgGgCgFQgCgFgDgCQgEgDgFAAQgEAAgDADg");
	this.shape_7.setTransform(29.825,-1.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAeArIgBAAIgBgCIAAg8IAAAAIgBAAIgWA8QAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgIAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIgWg7IgBgBIAAABIAAA7IAAACIgCAAIgKAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAhRQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAUAAIABAAIABABIAUA2IAAABIABgBIAUg1QAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAVAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABRQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAg");
	this.shape_8.setTransform(21.675,-3.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgPAcQgHgEgEgHQgEgHAAgKQAAgIAEgIQAEgHAHgEQAHgEAIAAQAJAAAHAEQAHAFAEAGQAEAIAAAIQAAAKgEAHQgEAHgHAEQgHAEgJAAQgIAAgHgEgAgHgSQgEACgBAFQgCAFAAAGQAAAHACAFQABAFAEACQADADAEAAQAFAAAEgDQADgCACgFQACgFAAgHQAAgGgCgFQgCgFgDgCQgEgDgFAAQgEAAgDADg");
	this.shape_9.setTransform(9.175,-1.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAYArIgCAAIgBgBIgng4IgBAAIgBAAIAAA3QAAABAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgKAAQgBAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAhRQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAIACAAIACABIAlA1IABABIAAgBIAAg0QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABSIgBACIgBAAg");
	this.shape_10.setTransform(1.25,-3.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgHARIgBAAIAAgCIAGgNQAAAAAAgBQAAAAAAgBQAAAAAAAAQgBAAAAAAIgCAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgOQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIANAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAANIgBABIgJARIgCABIgCAAg");
	this.shape_11.setTransform(114.2125,-11.775);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAGAqQgHgBgEgDQgEgEAAgIIAAghQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBgBAAIgHAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAABAAIAIAAIABgBIACgSQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAKAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAASIABABIAOAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgNAAIgBABIAAAfQAAAEACACQACACAEAAIAHAAIABAAIAAACIAAAGQAAAAAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgEAAIgFABg");
	this.shape_12.setTransform(111.575,-15.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgQAcQgHgDgDgGIAAgBIAAgBIAHgEIACAAIABAAIAEAFIAFADIAHABIAHgBQADAAACgDQAAAAABAAQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQgCgBgGgBIgKgEQgJgCgEgCQgFgFAAgGQAAgGADgFQAEgEAFgCQAGgDAHAAQAIAAAHADQAGADADAFIABACIgBABIgHADIgCAAIgBgBQgCgCgDgCQgEgCgFgBQgEABgEACQgDACAAADQAAABAAAAQAAAAAAABQAAAAABABQAAAAAAABIAHADIAMADQAJACAEAEQAEAFAAAGQAAAGgDAEQgEAEgGADQgGACgIAAQgJAAgHgEg");
	this.shape_13.setTransform(105.925,-14.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgOAcQgHgEgEgHQgEgHAAgJQAAgJAEgIQAEgHAHgEQAHgEAIAAQAIAAAHAEQAHAEADAHQAEAHAAAJIAAACQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgoAAIgBAAIAAACQAAAEACAEQACAEAEACQAEACAEAAQAEAAAEgCQAEgCAEgEIABgBIABABIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQAAABgBAAQgDAGgEADQgEADgFABIgLABQgIAAgHgEgAgGgTQgDACgCAEQgCADAAAFIAaAAIACAAIAAgCIgBgHQgCgDgDgCQgDgDgFAAQgDAAgEADg");
	this.shape_14.setTransform(99.475,-14.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgQAgIgCgBIAAgBIAAg6QAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBAAABIAMAAQAAgBABABQAAAAAAAAQAAAAAAABQABAAAAAAIAAAHIAAABIABAAIAFgGIAFgDIAHgBQABAAAAAAQABAAABAAQAAAAABABQAAAAAAAAIAAALQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgDgBIgEAAIgEABIgGADIgCADIgBAFIAAAiQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape_15.setTransform(94.4,-14.95);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgOAcQgHgEgEgHQgEgHAAgJQAAgJAEgIQAEgHAHgEQAHgEAIAAQAIAAAHAEQAHAEADAHQAEAHAAAJIAAACQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgoAAIgBAAIAAACQAAAEACAEQACAEAEACQAEACAEAAQAEAAAEgCQAEgCAEgEIABgBIABABIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQgBABAAAAQgDAGgEADQgEADgFABIgLABQgIAAgHgEgAgGgTQgDACgCAEQgCADAAAFIAaAAIACAAIAAgCIgBgHQgCgDgDgCQgDgDgFAAQgDAAgEADg");
	this.shape_16.setTransform(88.275,-14.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAGAqQgHgBgEgDQgEgEAAgIIAAghQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBgBAAIgHAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAABAAIAIAAIABgBIACgSQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAKAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAASIABABIAOAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgNAAIgBABIAAAfQAAAEACACQACACAEAAIAHAAIABAAIAAACIAAAGQAAAAAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgEAAIgFABg");
	this.shape_17.setTransform(83.575,-15.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAOAgIgBgBIgBgBIAAgoQAAgEgCgDQgDgCgEgBIgFABIgEADIgGAEIAAApQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgKAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAIAAg6QAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAABIAMAAQAAgBAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAHIAAAAIABAAIAHgFIAGgDIAHgBQAJAAAEAEQAFAFABAJIAAApQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_18.setTransform(77.85,-14.95);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgFArIgCAAIgBgCIAAhRQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIANAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAABRIgBACIgCAAg");
	this.shape_19.setTransform(72.475,-16.125);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgPAcQgHgEgEgHQgEgHAAgKQAAgIAEgIQAEgHAHgEQAHgEAIAAQAJAAAHAEQAHAFAEAGQAEAIAAAIQAAAKgEAHQgEAHgHAEQgHAEgJAAQgIAAgHgEgAgHgSQgEACgBAFQgCAFAAAGQAAAHACAFQABAFAEACQADADAEAAQAFAAAEgDQADgCACgFQACgFAAgHQAAgGgCgFQgCgFgDgCQgEgDgFAAQgEAAgDADg");
	this.shape_20.setTransform(63.625,-14.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAYArIgCAAIgBgBIgng4IgBAAIgBAAIAAA3QAAABAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgKAAQgBAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAhRQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAMAAIABAAIACABIAlA1IABABIAAgBIAAg0QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABSIgBACIgBAAg");
	this.shape_21.setTransform(55.7,-16.125);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgHARIgBAAIAAgCIAGgNQAAAAAAgBQAAAAAAgBQAAAAAAAAQgBAAAAAAIgCAAQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgOQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIANAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAANIgBABIgJARIgCABIgCAAg");
	this.shape_22.setTransform(45.3625,-11.775);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgQAcQgHgDgDgGIAAgBIAAgBIAHgEIACAAIABAAIAEAFIAFADIAHABIAHgBQADAAACgDQAAAAABAAQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQgCgBgGgBIgKgEQgJgCgEgCQgFgFAAgGQAAgGADgFQAEgEAFgCQAGgDAHAAQAIAAAHADQAGADADAFIABACIgBABIgHADIgCAAIgBgBQgCgCgDgCQgEgCgFgBQgEABgEACQgDACAAADQAAABAAAAQAAAAAAABQAAAAABABQAAAAAAABIAHADIAMADQAJACAEAEQAEAFAAAGQAAAGgDAEQgEAEgGADQgGACgIAAQgJAAgHgEg");
	this.shape_23.setTransform(40.725,-14.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAGAqQgHgBgEgDQgEgEAAgIIAAghQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBgBAAIgHAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgHQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAIAAIABgBIACgSQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAKAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAASIABABIAOAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAHQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgNAAIgBABIAAAfQAAAEACACQACACAEAAIAHAAIABAAIAAACIAAAGQAAAAAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgEAAIgFABg");
	this.shape_24.setTransform(35.775,-15.95);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AAOAgIgCgBIAAgBIAAgoQAAgEgCgDQgDgCgFgBIgEABIgFADIgFAEIAAApQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgKAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAg6QAAAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAABIALAAQABgBAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAHIAAAAIACAAIAGgFIAGgDIAHgBQAJAAAEAEQAGAFAAAJIAAApQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_25.setTransform(30,-14.95);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgOAcQgHgEgEgHQgEgHAAgJQAAgJAEgIQAEgHAHgEQAHgEAIAAQAIAAAHAEQAHAEADAHQAEAHAAAJIAAACQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgoAAIgBAAIAAACQAAAEACAEQACAEAEACQAEACAEAAQAEAAAEgCQAEgCAEgEIABgBIABABIAHADQAAAAAAAAQABABAAAAQAAAAAAAAQgBABAAAAQgDAGgEADQgEADgFABIgLABQgIAAgHgEgAgGgTQgDACgCAEQgCADAAAFIAaAAIACAAIAAgCIgBgHQgCgDgDgCQgDgDgFAAQgDAAgEADg");
	this.shape_26.setTransform(23.025,-14.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAhAgIgCgBIAAgBIAAgoQAAgEgCgDQgDgCgEgBIgFABIgFADIgDADIgBACIgBABIAAAnQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgKAAIgBgBIgBgBIAAgoQAAgEgCgDQgCgCgFgBQgEAAgDACIgHAGIAAApQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgKAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAg6QAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBAAABIAMAAQAAgBAAABQABAAAAAAQAAAAAAABQAAAAAAAAIAAAHIABAAIABAAIAGgFIAGgDIAIgBQAGAAADACQAEADACAFIABAAIABAAIAGgGQADgCAEgBIAHgBQAJAAAEAEQAFAGAAAIIAAApQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_27.setTransform(14.875,-14.95);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgYAoQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAgIIABgBIACAAIAIAAIAEgBIADgEIACgEQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIgXg2IABgCQAAAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAgBIAMAAIACABIABABIANAmIABABIABgBIAOgmIABgBIACgBIAIAAIACABIAAACIgZA8IgFAJQgBAEgDACQgDABgDABIgJAAg");
	this.shape_28.setTransform(6.4375,-13.95);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgWAbQgEgEAAgIQAAgGADgFQAEgEAHgCQAIgDAJgBIAGAAIABgBIABAAIAAgDQAAgGgDgCQgDgDgGAAQgCAAgEACQgEACgCADIgBABIgCAAIgKgCIAAgBIAAgBQADgHAHgDQAHgEAJAAQAJAAAGADQAFACADAEQACAFABAGIAAAnIgBACIgBABIgKAAIgCgBIgBgCIAAgDQAAgBAAAAQAAAAAAAAQgBAAAAAAQAAAAgBABQgEADgFACQgEACgFAAQgJAAgGgFgAAAACIgGACIgEAEQgCADAAACQABAEADACQACADAFAAIAFgBIAFgDIADgDIABgEIAAgIQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgEAAIgHABg");
	this.shape_29.setTransform(-0.6,-14.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgfArIgCAAIAAgCIAAhRQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAgAAQAJAAAIADQAHACAFAGQAEAGAAAJQAAAJgEAFQgEAFgHADQgHADgJAAIgSAAIgBABIAAAfQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAgAgQgcIAAAYQAAAAAAABQAAAAABAAQAAAAAAABQAAAAABAAIAOAAQAIAAAEgEQAEgEAAgGQAAgFgCgDQgCgDgEgBQgDgCgFAAIgOAAQAAAAgBAAQAAABAAAAQAAAAgBAAQAAABAAAAg");
	this.shape_30.setTransform(-7.525,-16.125);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgPAcQgHgEgEgHQgEgHAAgKQAAgIAEgIQAEgHAHgEQAHgEAIAAQAJAAAHAEQAHAFAEAGQAEAIAAAIQAAAKgEAHQgEAHgHAEQgHAEgJAAQgIAAgHgEgAgHgSQgEACgBAFQgCAFAAAGQAAAHACAFQABAFAEACQADADAEAAQAFAAAEgDQADgCACgFQACgFAAgHQAAgGgCgFQgCgFgDgCQgEgDgFAAQgEAAgDADg");
	this.shape_31.setTransform(-18.925,-14.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAYArIgCAAIgCgBIgmg4IgBAAIAAAAIAAA3QAAABgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgKAAQgBAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAhRQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAIABAAIACABIAkA1IABABIABgBIAAg0QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABSIAAACIgCAAg");
	this.shape_32.setTransform(-26.85,-16.125);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgQAcQgHgDgDgGIAAgBIAAgBIAHgEIACAAIABAAIAEAFIAFADIAHABIAHgBQADAAACgCQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAAAQgCgCgGgBIgKgEQgJgCgEgCQgFgFAAgHQAAgFADgFQAEgEAFgCQAGgDAHAAQAIAAAHADQAGADADAFIABACIgBABIgHADIgCAAIgBgBQgCgCgDgCQgEgDgFAAQgEAAgEADQgDABAAAEQAAABAAAAQAAAAAAABQAAAAABABQAAAAAAABIAHADIAMADQAJACAEAEQAEAFAAAGQAAAGgDAEQgEAEgGADQgGACgIAAQgJAAgHgEg");
	this.shape_33.setTransform(74.075,-28.05);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAOArIgCAAIAAgCIAAgoQAAgEgCgCQgDgDgEAAIgFABIgEADIgGAEIAAApQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIgKAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhRQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAfIAAABIABgBIAHgFIAGgDIAHgBQAJAAAEAFQAGAFAAAJIAAApQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_34.setTransform(67.7,-29.275);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAGAqQgHgBgEgDQgEgEAAgIIAAghQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAgBgBAAIgHAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgIQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAIAAIABgBIACgSQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAKAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAASIABABIAOAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAAIQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgNAAIgBABIAAAfQAAAFACABQACACAEAAIAHAAIABAAIAAACIAAAFQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgEAAIgFABg");
	this.shape_35.setTransform(62.475,-29.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAOAgIgCgBIAAgBIAAgoQAAgEgCgDQgDgCgFgBIgEABIgFADIgEAFIAAAoQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAIgLAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQgBAAAAAAIAAg6QABAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAHIABABIABgBIAGgFIAFgDIAIgBQAIAAAGAEQAEAGAAAIIAAApQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_36.setTransform(56.75,-28.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgPAcQgHgEgEgHQgEgHAAgJQAAgJAEgIQAEgHAHgEQAHgEAIAAQAJAAAHAEQAHAFAEAGQAEAIAAAJQAAAJgEAHQgEAHgHAEQgHAEgJAAQgIAAgHgEgAgHgSQgEACgBAFQgCAFAAAGQAAAHACAFQABAFAEACQADADAEAAQAFAAAEgDQADgCACgFQACgFAAgHQAAgGgCgFQgCgFgDgCQgEgDgFAAQgEAAgDADg");
	this.shape_37.setTransform(49.825,-28.05);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AAeArIgBAAIgBgCIAAg8IAAAAIgBAAIgWA8QAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgIAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIgWg7IgBgBIAAABIAAA7IAAACIgCAAIgKAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAhRQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAUAAIABAAIABABIAUA2IAAABIABgBIAUg1QAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAVAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABRQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAg");
	this.shape_38.setTransform(41.625,-29.275);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgcAsIgCgBIAAgBIAAgIIAAgBIABgCIADgDIAXgVIAIgIIAFgGIADgFIABgGQgBgEgCgCQgCgDgCgCQgEgBgDAAIgGABIgGAEIgGAHIgBABIgBgBIgJgEIgBgCIAAgCQAGgJAIgEQAIgEAIAAQAJAAAHADQAHADAEAGQADAFAAAJIgBAJQgCAEgEAEQgEAEgGAFIgVATIgBABIABABIAlAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIAAALIgBABIgCABg");
	this.shape_39.setTransform(29.3,-29.325);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgVArQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgKQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIANAAIABAAIAAg2QAAAAAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAIgMAEQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIAAgCIABgBIATgJIACgBIABAAIAHAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABFIABABIAMAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAJIAAACIgCAAg");
	this.shape_40.setTransform(21.725,-29.275);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgDAbQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgTIAJAAIAAAUQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAgAAFAGIAAgLIgJAAIAAgUIAAgBIABAAIAHAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAUIAVAAQAAAAABABQAAAAAAAAQAAAAAAAAQABABAAAAIAAAGQAAABgBAAQAAABAAAAQgBAAAAAAQgBABgBAAgAAFAGIgJAAIAAgLIAAALIgUAAIgCgBIgBgCIAAgFQAAgBABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIAVAAIAJAAIAAALgAgEAGg");
	this.shape_41.setTransform(11.25,-29.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-38.7,-35.4,162.7,40.8);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#47C434").s().p("AgDAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAgUIgUAAIgCgBIgBgBIAAgIQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAVAAIAAANIANAAIAAAVQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAgAAHAHIgNAAIAAgNIAAgUIABgCIACgBIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAVIgNAAIANAAIAAANIAAgNIAVAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAgAAHAHgAAHgGg");
	this.shape.setTransform(-20.575,16.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAHAyQgIAAgFgFQgFgEAAgJIAAgpQAAAAAAgBQAAAAAAAAQgBgBAAAAQgBAAAAAAIgJAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgJQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAKAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIACgVQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAMAAQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAVIABABIAQAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAJQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgQAAQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAAAkQAAAGACACQADACAEAAIAIAAIACAAIAAACIAAAHQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgFAAIgFABg");
	this.shape_1.setTransform(41.4,32.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgFA0IgDgBIAAgBIAAhFQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIANAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAABEIgBACIgDABgAgGgfIgCgBIgBgDIAAgNQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAAANQAAABAAABQAAAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_2.setTransform(37.25,32.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AARAmIgBgBIgBgCIAAgvQgBgFgDgDQgCgDgGAAIgFABIgGADIgGAFIAAAxQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGIAHgDQAEgCAEAAQALAAAGAGQAGAGAAAKIAAAyQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_3.setTransform(31.9,33.725);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgXAwQgIgFgEgJQgEgJAAgNIAAg9QAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIAQAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABAQAAAMAGAFQAFAGAJAAQAHAAAFgDQAFgCACgFQADgFAAgJIAAg/QAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIANAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAA/QAAAOgFAJQgEAIgJAEQgJAEgNAAQgOAAgJgFg");
	this.shape_4.setTransform(22.625,32.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgdAwQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgIIAAgCIAEgBIAJAAQADAAACgBIAEgEIACgFQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAgBIgbhAIABgDIACgBIAOAAIACABIABACIAQAtIABABQABAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIARguIABgBIACgBIAKAAIABABQAAAAABAAQAAABAAAAQAAAAAAAAQgBABAAAAIgdBJIgGAKQgBAEgEADQgDACgFABIgKAAg");
	this.shape_5.setTransform(10.625,34.95);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_6.setTransform(4.575,33.725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgRAiQgJgFgEgJQgFgIAAgLQAAgLAFgJQAFgJAJgFQAIgFAJABQAKgBAJAFQAHAFAFAIQAEAJAAALIAAACIgCABIgwAAIgBABIgBACQAAAFADAFQADAFAEACQAFACAEABQAGAAAEgCQAFgDAFgFIAAgBIACABIAIADQABAAAAABQABAAAAAAQAAAAAAABQgBAAAAAAQgFAHgEAEQgFADgGACQgFABgIAAQgJAAgJgEgAgHgYQgFAEgBAEQgDAEAAAGIAgAAIACgBIABgBQgBgEgCgFQgCgDgDgEQgEgCgFAAQgFAAgEACg");
	this.shape_7.setTransform(-2.25,33.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgDAlQgDAAgCgCIgbhEIAAgCIACgBIAPAAIABABIABABIARAtQABABAAAAQAAAAAAAAQABAAAAAAQAAgBAAgBIASgtIACAAIABgBIALAAIABABIAAABIgcBFQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_8.setTransform(-9.4,33.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhiQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIguAAQAAAAgBABQAAAAAAAAQAAAAgBABQAAAAAAABIAAAYQAAABAAAAQABAAAAABQAAAAAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAALIAAAAIgCABIgfAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAIAwAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAABIAAALIgBABIgCABg");
	this.shape_9.setTransform(-17.875,32.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgHA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg5QAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBgBAAIgLAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgIIABgBIABgBIALAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQABgJAEgFQAFgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAIIgBABIgBABIgJAAQgDAAgCACQgCADAAAEIAAAHQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABABIABABIAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgNAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgBABAAAAIAAA5QAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_10.setTransform(-27.8,32.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgIA0QAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg5QAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBgBAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgIIABgBIACgBIAKAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQAAgJAGgFQAEgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAAIIgBABIgBABIgIAAQgEAAgCACQgBADgBAEIAAAHQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABABIABABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgNAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgBABAAAAIAAA5QAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_11.setTransform(-32.95,32.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgYAvQgKgGgGgMQgGgMAAgRQAAgQAGgMQAGgMALgGQAKgHANAAQAPAAAKAHQAKAGAGAMQAGAMAAAQQAAARgGAMQgFAMgLAGQgKAHgPgBQgNABgLgHgAgSgcQgGAJAAATQAAAVAGAJQAHAIALABQANgBAGgIQAGgJAAgVQAAgTgGgJQgGgKgNAAQgLAAgHAKg");
	this.shape_12.setTransform(-41.225,32.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgUAvQgKgGgGgMQgFgMAAgQQAAgMADgKQAEgKAFgHQAGgHAHgDQAIgEAIAAQAJAAAIAEQAHADAGAHQAGAHADAKQADAKAAAMQAAAQgGAMQgFAMgJAGQgJAGgNAAQgLAAgJgGgAgKghQgFAEgCAIQgCAJgBANQABANACAJQACAIAFAEQAEAEAGAAQAHAAAFgEQAEgEACgIQADgJAAgNQAAgNgDgJQgCgIgEgEQgGgEgGAAQgGAAgEAEg");
	this.shape_13.setTransform(-53.3,32.275);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgUAvQgKgGgGgMQgFgMAAgQQAAgMAEgKQACgKAHgHQAFgHAHgDQAIgEAIAAQAJAAAIAEQAIADAFAHQAFAHAEAKQADAKAAAMQAAAQgGAMQgFAMgJAGQgJAGgNAAQgLAAgJgGgAgKghQgEAEgDAIQgDAJABANQgBANADAJQADAIAEAEQAFAEAFAAQAHAAAEgEQAFgEACgIQADgJAAgNQAAgNgDgJQgCgIgFgEQgFgEgGAAQgFAAgFAEg");
	this.shape_14.setTransform(-61.95,32.275);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgZA0QgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgLQAAgBAAAAQAAgBABAAQAAAAAAAAQABgBABAAIAPAAIABgBIAAhAQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgOAFQgBAAgBAAQAAAAAAAAQgBAAAAgBQAAgBAAgBIAAgIIAAgBIACgBIAWgLIADgBIACgBIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABTQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAIAOAAQABAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAALIAAABIgDABg");
	this.shape_15.setTransform(-71.1,32.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgBA+QgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgHIAAgBIgCgBQgKABgIgEQgHgDgHgHQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAIgIIABgBIACABIAKAIQAFAEAHAAQABAAAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIAAgbIAAgDIgCgBQgLgDgHgDQgHgEgCgGQgDgGAAgHQAAgHADgHQAEgFAHgFQAHgEAJgBIABAAIABgCIAAgGIABgBIABAAIAHAAIACAAIAAACIAAAGQAAAAAAAAQAAABABAAQAAAAAAAAQAAAAABAAQAIABAGADIALAHQAAAAABABQAAAAAAABQAAAAAAABQAAAAgBAAIgHAIIgBABIgCgBIgHgFIgIgDIgBAAIgBABIAAAbQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABABIAHACQAHACAGADQAFAEADAGQADAGAAAHQAAAIgEAGQgEAGgGAEQgHAEgKAAIgBABIgBABIAAAGQAAABAAABQAAAAAAABQgBAAAAAAQgBAAgBAAgAAHALIAAAbQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAHgBAEgDQAEgEAAgFQAAgGgDgDQgEgEgIgCIgBAAIgBABgAgFgnQgIABgEAFQgDADAAAGIABAFIAEAFIAIADIADAAIAAgCIAAgYQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAgBAAIAAAAg");
	this.shape_16.setTransform(-77.9281,32.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#6CC14C").s().p("AggAzIgCAAIgBgDIAAhfQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIBDAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgqAAQgBAAgBABQAAAAgBAAQAAAAAAABQAAAAAAABIAAAVQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAAMQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgdAAQgBAAAAABQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAlQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_17.setTransform(51.475,3.75);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#6CC14C").s().p("AggAzIgCAAIgBgDIAAhfQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAMQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgqAAQgBAAgBABQAAAAgBAAQAAAAAAABQAAAAAAABIAAAVQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAdAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAAMQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgdAAQgBAAAAABQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAlQAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_18.setTransform(43.075,3.75);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#6CC14C").s().p("AgYAuQgLgGgFgMQgGgMAAgQQAAgPAGgMQAGgMAKgGQALgHANAAQAPAAAKAHQALAGAFAMQAGAMAAAPQAAARgGALQgFALgLAHQgKAGgPABQgNgBgLgGgAgPgaQgGAIAAASQAAATAFAIQAGAIAKAAQALABAGgJQAFgIAAgTQAAgSgFgIQgGgJgLAAQgKAAgFAJg");
	this.shape_19.setTransform(33.125,3.75);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#6CC14C").s().p("AAVAwQgGgDgEgGQgEgIAAgIQAAgHAEgHQAEgGAGgDQAFgFAHAAQAIAAAGAFQAGADADAGQAEAHgBAHQABAIgEAIQgDAGgGADQgGAEgIABQgHgBgFgEgAAcAIQgDABgBAFIgBAJIABAKQABAEADACQACACADAAQAEAAADgCIADgGIABgKIgBgJQgBgFgCgBQgDgDgEAAQgDAAgCADgAgjAzQgBAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAIABgDIBAhhIACgBIACAAIAHAAIABAAQAAAAAAAAQABAAAAABQAAAAgBAAQAAABAAAAIhBBjQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAgAguACQgGgDgDgHQgDgGAAgJQAAgHADgHQADgHAGgEQAGgDAIAAQAHAAAFADQAHAEADAHQADAHABAHQgBAJgDAGQgEAHgFADQgGADgHAAQgIAAgGgDgAgngnQgBACgBAFQgCAEAAAFIABAKQABAFACACQADABAEAAQAFAAADgEQACgFAAgJQgBgIgCgFQgDgFgEAAQgEAAgDACg");
	this.shape_20.setTransform(34.3,-8.35);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#6CC14C").s().p("AgnBTQgRgMgKgVQgKgUAAgdQAAgVAGgRQAGgSAKgMQALgNAOgHQAOgGAPAAQARAAAOAGQAOAHAKANQAKAMAGASQAGARAAAVQAAAcgKAVQgKAVgRAMQgSALgWAAQgVAAgSgLgAgRg5QgHAHgEAOQgEAPAAAWQAAAXAEANQAEAOAHAHQAHAGAKAAQALAAAHgGQAIgHADgOQAEgNAAgXQAAgWgEgPQgEgOgHgHQgHgGgLAAQgKAAgHAGg");
	this.shape_21.setTransform(18.425,-1.075);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#6CC14C").s().p("AALBcQgGAAAAgFIAAgkQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBgBAAAAIhJAAQgGABAAgFIAAgVIABgEIAGgIIBJhhIAFgEIAFgBIAgAAQADAAAAAEIAABoQAAAAABABQAAAAAAAAQAAABABAAQAAAAABAAIAVAAQAEAAAAAEIAAAVQAAAFgFgBIgTAAQgBAAgBABQAAAAgBAAQAAABAAAAQgBABAAABIAAAiQAAAGgGAAgAADgsIgsA8QgDADAFAAIAqAAQABAAABAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAAg9IgBgEg");
	this.shape_22.setTransform(3.35,-1.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#6CC14C").s().p("AgsBTQgTgLgKgVQgLgVAAgdQAAgdALgVQAKgWAUgLQATgMAYAAQAaAAATAMQATALALAWQAKAVAAAdQAAAdgKAUQgLAWgTALQgTALgaAAQgZAAgTgLgAgdgwQgJAQAAAhQAAAiAJAOQAKAPATAAQAVAAAJgPQAKgOAAgiQAAghgKgQQgKgPgUAAQgTAAgKAPg");
	this.shape_23.setTransform(-21.725,-1.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#6CC14C").s().p("AgpBTQgTgMgKgVQgKgVAAgcQAAgcAKgWQALgVATgLQATgNAZAAQAUABAQAHQAQAIAKAMQAJAMADANIAAAFQAAAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAIghAFIgCgBIgCgDQgBgJgFgGQgEgHgIgEQgHgEgKAAQgLAAgJAGQgJAHgEAOQgFAOAAAWQAAAXAFAOQAFAPAJAFQAJAHALAAQAIAAAGgCQAHgCAEgEQAEgFADgEQADgGABgFIAAgHQABgBgBgBQAAgBAAAAQAAgBgBAAQAAAAgBAAIgeAAIgDgBIgBgEIAAgSQAAgDAEABIBCAAQAEAAABAAQABAAAAABQAAABABAAQAAABAAAAQAAABAAAAIAABUIgBADIgCABIgIAAIgEgBIgDgDIgHgSIgBAAIgCABIgLALQgGAFgKAEQgKAEgPgBQgYAAgSgLg");
	this.shape_24.setTransform(-41.325,-1.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#6CC14C").s().p("AgsBTQgTgLgKgVQgLgVAAgdQAAgdALgVQAKgWAUgLQATgMAYAAQAaAAATAMQATALALAWQAKAVAAAdQAAAdgKAUQgLAWgTALQgTALgaAAQgZAAgTgLgAgdgwQgJAQAAAhQAAAiAJAOQAKAPATAAQAVAAAJgPQAKgOAAgiQAAghgKgQQgKgPgUAAQgTAAgKAPg");
	this.shape_25.setTransform(-60.225,-1.05);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#6CC14C").s().p("AhGBcIgEgBIgBgDIAAiuQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAIBDAAQAkAAATAMQATAMAAAYQAAAOgHAKQgIAJgRAHIgBACIABABQATAFAJALQAJAJAAARQAAAZgUANQgTAMglAAgAgfATIAAAnQAAAEADABIAbAAQAPgBAIgGQAIgHAAgLQAAgHgEgGQgEgFgGgDQgHgDgJAAIgbAAQgEAAAAAFgAgfg6IAAAnQAAAEADAAIAcAAIALgBQAFgBAEgEQAEgDACgDQACgFAAgFQAAgMgIgGQgJgHgMABIgaAAQgEAAAAADg");
	this.shape_26.setTransform(-76.975,-1.05);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgGA0QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAgPQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAABgBIAPAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAAAIAAAQQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAgAgDAWIgCAAIAAgCIgEhFIAAgBIABgBIARAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAgBABIgEBFIgBACIgDAAg");
	this.shape_27.setTransform(46.2,-27.45);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgRAiQgIgFgFgJQgFgIAAgLQAAgLAFgJQAFgJAIgFQAJgEAJAAQALAAAHAEQAJAFAEAIQAEAJAAALIAAACIgCACIgwAAIgCAAIAAACQAAAFADAFQADAFAEACQAFACAEABQAGgBAFgBQAEgDAFgFIABgBIABABIAJADQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgFAGgEAEQgFADgGACQgGABgHAAQgKAAgIgEgAgIgYQgDADgCAFQgDAEAAAGIAgAAIACgBIAAgBQAAgEgCgFQgCgDgDgEQgEgCgGAAQgEAAgFACg");
	this.shape_28.setTransform(40.75,-25.95);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgFA0QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhiQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABiIAAACIgDABg");
	this.shape_29.setTransform(35.325,-27.45);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgZAhQgHgGAAgJQAAgIAFgFQAEgFAJgDQAJgEALAAIAHgBIACAAIAAgBIAAgEQAAgGgDgDQgEgEgGAAQgEAAgEACQgFADgDAEIAAABIgCAAIgMgDIgBAAIAAgCQAEgIAJgFQAHgDAMAAQALAAAGACQAHADADAFQADAGAAAHIAAAwIgBACIgCABIgLAAIgCgBIgBgCIAAgFQAAAAAAAAQgBgBAAAAQAAAAgBABQAAAAgBAAQgFAEgFADQgFACgHAAQgLABgFgGgAAAACIgHAEQgDABgCACQgCADAAAEQAAAFADADQAEACAFAAIAHgBIAGgDIADgFQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgFAAIgIABg");
	this.shape_30.setTransform(29.45,-25.95);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgGIgBgCIABgCIAJgGIADgBIACABIAGAIQAEADAEACIALABQAJAAAGgEQAGgDAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgEgDgGQgCgGAAgGQAAgJAEgHQAFgGAJgFQAJgDAKAAQAIAAAGACQAHABAFADQAGAEADAEIABABIgBADIgKAGIgBABIgCgBQgDgEgFgCQgFgEgIAAQgJABgFADQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMAEAGAGQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAEgMAAQgJAAgIgCg");
	this.shape_31.setTransform(21.1167,-27.45);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQgBAAAAAAQAAAAAAABQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_32.setTransform(11.175,-26.025);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgRAiQgIgFgFgJQgFgIAAgLQAAgLAFgJQAFgJAJgFQAIgEAJAAQAKAAAJAEQAIAFAEAIQAEAJAAALIAAACIgCACIgxAAIAAAAIgBACQAAAFACAFQADAFAFACQAEACAFABQAGgBAEgBQAGgDADgFIABgBIACABIAJADQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgFAGgEAEQgFADgGACQgGABgHAAQgJAAgJgEgAgHgYQgEADgDAFQgCAEAAAGIAgAAIACgBIABgBQAAgEgCgFQgCgDgEgEQgEgCgFAAQgFAAgEACg");
	this.shape_33.setTransform(4.35,-25.95);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAoAmIgCgBIAAgCIAAgvQAAgFgEgDQgCgDgGAAIgGABIgFADIgEADIgBACIgBADIAAAuQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgBgBIgBgCIAAgvQAAgFgDgDQgDgDgFAAQgFAAgEACQgEACgFAFIAAAxQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAhEQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHIAAABIABgBIAIgGQAEgCAEgBQAEgCAEAAQAIAAAFAEQAEADACAGIABAAIACAAIAHgHQAEgDAEgBQAEgCAFAAQAKAAAGAGQAFAGABAKIAAAyQAAAAgBABQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_34.setTransform(-4.95,-26.025);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAnAmIgBgBIgBgCIAAgvQAAgFgCgDQgDgDgGAAIgGABIgFADIgFADIgBACIAAADIAAAuQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgCgBIAAgCIAAgvQAAgFgDgDQgCgDgGAAQgFAAgEACQgEACgEAFIAAAxQAAAAgBABQAAABAAAAQgBAAAAABQgBAAAAAAIgNAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGQADgCAEgBQAEgCAFAAQAHAAAEAEQAFADADAGIAAAAIABAAIAIgHQAEgDAFgBQADgCAFAAQAKAAAGAGQAFAGAAAKIAAAyQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_35.setTransform(-16.6,-26.025);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgVAjQgFgDgDgFQgDgFAAgGIAAgyQAAAAAAgBQABgBAAAAQAAAAABgBQABAAAAAAIANAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAuQAAAGADADQADADAGAAQAEAAAEgCIAJgHIAAgxQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAABEQAAAAAAABQgBAAAAABQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgGADQgFADgGAAQgGAAgFgDg");
	this.shape_36.setTransform(-26.725,-25.875);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgGIgBgCIABgCIAJgGIADgBIACABIAGAIQAEADAEACIALABQAJAAAGgEQAGgDAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgEgDgGQgCgGAAgGQAAgJAEgHQAFgGAJgFQAJgDAKAAQAIAAAGACQAHABAFADQAGAEADAEIABABIgBADIgKAGIgBABIgCgBQgDgEgFgCQgFgEgIAAQgJABgFADQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMAEAGAGQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAEgMAAQgJAAgIgCg");
	this.shape_37.setTransform(-35.4833,-27.45);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgHA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAgBIAAg4QAAAAAAgBQAAAAAAAAQAAAAAAAAQAAgBgBAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgIIABgCIABAAIALAAQAAAAABAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAgJQABgJAFgFQAEgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAAJIgBABIgBAAIgJAAQgDABgCACQgCADAAADIAAAIQAAAAABAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABAAIABACIAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgNAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgBABAAAAIAAA4QAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_38.setTransform(-45,-27.45);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgSAiQgIgFgGgJQgEgJAAgLQAAgLAFgIQAFgJAIgFQAJgEAJAAQALAAAIAEQAJAGAEAIQAFAJAAAKQAAAMgFAIQgFAJgIAFQgIAEgLAAQgKAAgIgEgAgJgWQgEACgDAHQgBAFAAAIQAAAIABAGQADAGAEADQAEADAFAAQAGAAAEgDQAEgDACgGQACgGAAgIQAAgIgCgFQgCgHgEgCQgEgEgGAAQgFAAgEAEg");
	this.shape_39.setTransform(-51.35,-25.95);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgUAwQgHgEgEgIQgDgJAAgMQAAgMAEgIQAEgJAHgEQAHgFAJAAQAFAAAEACQAFACAEADIACABIAAgCIAAggQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAOAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABiIAAACIgDAAIgMAAIgCAAIgBgCIAAgFIAAgBIgBABIgFAEIgHADQgEACgFAAQgIAAgHgFgAgHgIQgEACgDAGQgCAFAAAKQAAAJACAGQADAGAEACQAEADAEAAQAFAAADgCQAEgCACgEQACgDAAgDIAAgfIgHgFQgEgCgEAAQgFAAgEADg");
	this.shape_40.setTransform(-63.075,-27.375);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AARAmIgBgBIgBgCIAAgvQgBgFgDgDQgCgDgGAAIgFABIgGADIgGAFIAAAxQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIANAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGIAHgDQAEgCAEAAQALAAAGAGQAGAGAAAKIAAAyQAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_41.setTransform(-70.7,-26.025);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhiQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIguAAQAAAAgBABQAAAAAAAAQgBAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAKIAAABIgCABIgfAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAABABAAIAwAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIAAALIgBABIgCABg");
	this.shape_42.setTransform(-79.425,-27.45);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#48C435").ss(1,1,1).p("ArHAAIKAAAAAzAAIKVAA");
	this.shape_43.setTransform(-20.025,16.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-94.3,-35,152.7,77.7);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


(lib.Img_02_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


(lib.Img_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_01();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AFrA4QgJgFgEgHIgBgDIABgBIAMgFIABABIAFAFQAEAEAEABQAFACAGgBQAFABAEgCQAEgBADgCQACgDAAgDQAAgEgDgCQgCgCgHgCIgRgEQgMgCgGgHQgFgFAAgJQAAgHAEgGQAEgGAIgEQAIgDALAAQAMAAAIAEQAJAFAEAGIABACIgBACIgKAEIgCAAIgBgBQgDgEgFgCQgFgDgHAAQgHAAgFADQgFACAAAFQAAADACACQACABAHACIATAGQAMACAGAHQAFAGAAAJQAAAIgFAGQgEAGgJADQgIADgLAAQgOAAgKgFgAD/A4QgKgFgFgLQgFgLAAgPIAAhFQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAABJQAAAOAGAGQAGAGAMAAQAIAAAFgDQAGgCADgHQADgFAAgKIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABIQAAAQgGAKQgFAJgLAFQgKAEgOAAQgRAAgKgFgABAA4QgJgGgGgKQgFgJAAgNQAAgNAFgKQAGgKAJgGQAKgFAMAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEgGIgFgEQgDgCgEAAQgHAAgFAEQgFADgCAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAHAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgMAAgKgFgAgsA3QgHgHAAgKQAAgJAFgHQAFgGALgEQAKgEAOAAIAHAAIACgBIAAgCIAAgDQAAgHgDgDQgEgFgHAAQgGAAgFADQgFADgDAFIgBACIgCAAIgOgEIgBgBIABgCQAEgJAJgGQAKgEAOAAQALAAAIADQAHAEAEAGQADAGAAAHIAAA4IAAADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBgBAAQAAgBAAAAQgBAAAAABQgBAAAAAAQgFAGgGACQgHADgIAAQgMAAgHgGgAgFATIgKABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAHAAQAEAAAEgBIAGgEIAEgFIABgFIAAgLQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAgAkbA4QgKgGgFgKQgFgKAAgMQAAgNAFgKQAGgKAJgGQAKgFAMAAQAMAAAKAGQAJAFAGAKQAFAKAAANQAAAMgGAKQgFAKgJAGQgKAFgMAAQgNAAgJgFgAkRgIQgEADgDAGQgCAHAAAJQAAAJACAIQADAGAEAEQAFADAHAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgJgDgHQgCgGgFgDQgFgEgGAAQgHAAgFAEgAmOA2QgMgIgGgOQgHgOAAgSQAAgSAHgOQAGgNAMgHIAEgCQAKgGAOAAQAJAAAIADIAGADIAIAEQAGAFAEAGQAEAGABAIIABACIgCABIgSABIgCAAIgBgCQgCgIgFgGQgGgGgKAAQgOAAgHAKQgIALAAAWQAAAWAHALQAIALAOAAQAKgBAHgFQAHgEAFgMQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANADIABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgEAIIgGAJQgEAFgFADQgGADgHADQgHACgJAAQgQAAgMgHgACVA3QgGgGAAgKIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIADgZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIASAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgSABQgLAAgFgEgAhgA3QgFgGAAgKIAAguQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgKQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIALAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAABIASAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAAAqQAAAGADADQACACAGAAIAJAAIACABIABABIgBAJQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgRABQgLAAgGgEgAiTA7IgCAAIgBgDIAAg2QAAgFgDgEQgEgDgGAAIgIABIgGADIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgEQAFgCAFAAQAMAAAHAHQAHAHAAALIAAA5QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(-7.9806,-0.1916,0.8098,0.8098);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#000000").ss(0.4,1,1).p("AniiOIPFAAIAAEdIvFAAg");
	this.shape_1.setTransform(0.025,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(1,1,1).p("Ag0AAIBpAAAAcgiIAZAiIgeAj");
	this.shape_2.setTransform(36.075,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC24D").s().p("AniCOIAAkbIPFAAIAAEbgAF/AgIAegiIgZgjIAZAjIhpAAIBpAAgAGdgCg");
	this.shape_3.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-49.2,-15.2,98.5,30.5);


(lib.BG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,1024,90);


// stage content:
(lib.WBAY_219645_MM_1024x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#010101").ss(1,1,1).p("Eg43gHBMBxvAAAIAAODMhxvAAAg");
	this.shape.setTransform(512.0028,45,1.4066,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(420));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(945.55,55,1.4,1.4);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(66).to({_off:false},0).to({y:45,alpha:1},16,cjs.Ease.get(1)).wait(338));

	// logo_png
	this.instance_1 = new lib.logo_1("synched",0);
	this.instance_1.setTransform(80,290);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({y:300,alpha:1},17,cjs.Ease.get(1)).wait(392));

	// T3
	this.instance_2 = new lib.T3("synched",0);
	this.instance_2.setTransform(749.95,80.3,1.2,1.2,0,0,0,56.1,4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(58).to({_off:false},0).to({y:70.3,alpha:1},16,cjs.Ease.get(1)).wait(346));

	// T2
	this.instance_3 = new lib.T2("synched",0);
	this.instance_3.setTransform(750,26.35,1,1,0,0,0,42.6,-12.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(42).to({_off:false},0).to({y:31.35,alpha:1},16,cjs.Ease.get(1)).wait(362));

	// T1
	this.instance_4 = new lib.T1("synched",0);
	this.instance_4.setTransform(568.3,32.55);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(26).to({_off:false},0).to({y:42.55,alpha:1},16,cjs.Ease.get(1)).wait(378));

	// Img_04_jpg
	this.instance_5 = new lib.Img_04_1("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(298).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(105));

	// Img_03_jpg
	this.instance_6 = new lib.Img_03_1("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(255).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(148));

	// Img_02_jpg
	this.instance_7 = new lib.Img_02_1("synched",0);
	this.instance_7.setTransform(80,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(211).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(192));

	// Img_01_jpg
	this.instance_8 = new lib.Img_01_1("synched",0);
	this.instance_8.setTransform(80,300);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(14).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(389));

	// BG_jpg
	this.instance_9 = new lib.BG_1("synched",0);
	this.instance_9.setTransform(80,300);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},17,cjs.Ease.get(1)).wait(403));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(511,35,514,61.599999999999994);
// library properties:
lib.properties = {
	id: '2EB2B724566C40B88A04DB4265FC2499',
	width: 1024,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['2EB2B724566C40B88A04DB4265FC2499'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;