(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Logo = function() {
	this.initialize(img.Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIgBgBIAAgmQABgFgDgDQgDgDgFAAIgGABIgFADIgHAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgGAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAHgFIAGgDIAGgBQAJAAAFAFQAEAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAAAAAg");
	this.shape.setTransform(40.95,12.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAQAdQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgNgoIgBgBIAAABIgMAoIgBABIgBAAIgGAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgRg2IAAgCIABAAIAGAAIACAAIAAABIANAqIABABIABgBIANgqIABgBIAAAAIAFAAIABAAIAAABIAOAqIABABIAAgBIANgqIABgBIABAAIAEAAIABAAIAAACIgQA2IgBABIgCAAg");
	this.shape_1.setTransform(33.575,13.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_2.setTransform(25.775,13.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgcApQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAhNIABgBIABgBIAEAAIAFAAIAEAAIAEAAQAOAAAKAFQAJAFAEAIQAFAJAAANQAAANgFAJQgFAKgKAEQgJAFgOAAgAgTgeIAAA+QAAAAAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIAEAAQANAAAGgDQAIgEADgHQAEgHAAgMQAAgMgEgHQgDgHgIgDQgGgDgMAAIgFAAQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAABg");
	this.shape_3.setTransform(18.15,11.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWAmIgBgBIAAgEIAAgBIADgBIAHAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAIADgEIACgFQAAgBABAAQAAgBgBgBQAAAAAAgBQAAAAAAgBIgVgzIAAgBIABgBIAHAAIABAAIABABIAPAqIABABIABgBIAQgqIABgBIABAAIAFAAIABAAIAAACIgYA8IgDAHIgEAEIgFACIgHAAg");
	this.shape_4.setTransform(7.1625,13.925);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNAbQgGgEgEgHQgDgHAAgIQAAgJAEgHQADgHAGgDQAHgEAHAAQAIAAAGADQAGAEADAHQADAGAAAJIAAABQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAIgpAAIAAABIgBABQAAAFADAFQADAEAEADQAEACAFAAQAFAAAEgCQAFgCADgFIABAAIAAAAIAFACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAAAABQgDAEgDADQgEADgEABIgKABQgHAAgHgDgAgIgUQgEADgCAFQgCAEAAAFIAgAAIACAAIAAgCQAAgEgCgEQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_5.setTransform(0.775,13.025);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIAAgBIAAgmQAAgFgDgDQgDgDgGAAIgEABIgGADIgHAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgGAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAGgFIAHgDIAGgBQAJAAAEAFQAFAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAg");
	this.shape_6.setTransform(-5.9,12.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_7.setTransform(-12.575,13.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAeApIgBgBIAAgBIAAg+IgBAAIAAAAIgYA+QAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgEAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgYg9IAAAAIAAAAIAAA9IAAABIgCABIgGAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIALAAIABAAIABABIAYA+IAAABIABgBIAYg9IACgCIALAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAABNQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_8.setTransform(-20.625,11.875);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_9.setTransform(-32.675,13.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAYApIgBAAIgBgBIgqg9IgBgBIAAABIAAA8QAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgHAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAIABAAIABABIAoA8IABAAIABgBIAAg7QAAAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAIABABIAABOIgBABIgBABg");
	this.shape_10.setTransform(-40.3,11.875);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgDAOIgCAAIAAAAIAAgCIAFgLQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgJQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAAAABAAIAIAAQABAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAJIAAABIgHAOIgBABg");
	this.shape_11.setTransform(69.575,3.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAKAnIgEAAQgGAAgDgDQgDgEAAgGIAAgkQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgJAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgEQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAJAAIABgBIABgRQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAARIABABIAOAAIABABIAAAEIgBACIgOAAIgBABIAAAiQAAAEACACQACACADAAIAIAAIABABIAAABIAAADIgBABIgDABg");
	this.shape_12.setTransform(66.875,-0.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgFIAAgBIABgBIAEgCIABAAIAAAAIAFAFIAGADQADACAEAAQAEAAADgCQAEgBACgCQACgCAAgDQAAgDgDgCQgCgCgGgCIgKgDQgJgCgDgDQgDgEAAgFQAAgFADgEQACgEAFgCQAGgCAFAAQAIAAAFADQAGACADAFIAAABIAAABIgFACIAAAAIgBAAQgCgDgEgDQgEgCgGAAQgFAAgEADQgEACAAAFQAAAAAAABQABABAAAAQAAABAAAAQABABAAAAQACACAFACIANAEQAIABADAEQADAEAAAFQAAAFgDAEQgDAEgFACQgFACgHAAQgIAAgGgDg");
	this.shape_13.setTransform(61.375,0.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgNAbQgGgEgEgHQgDgHAAgIQAAgJAEgHQADgHAGgDQAHgEAHAAQAIAAAGADQAGAEADAHQADAGAAAJIAAABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgpAAIAAABIgBABQAAAFADAFQADAEAEADQAEACAFAAQAFAAAEgCQAFgCADgFIABAAIAAAAIAFACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQgDAEgDADQgEADgEABIgKABQgHAAgHgDgAgIgUQgEADgCAFQgCAEAAAFIAgAAIACAAIAAgCQAAgEgCgEQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_14.setTransform(55.225,0.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgNAeIgBgBIAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAHIAAABIABgBIAFgFIAGgEIAGgBQAAAAABAAQABAAAAABQABAAAAAAQAAAAAAABIAAAGIgBABIgCAAIgCAAIgGABIgEADIgEAEQAAABgBAAQAAABAAAAQAAABAAABQAAAAgBABIAAAjQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_15.setTransform(50.15,-0.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgNAbQgGgEgEgHQgDgHAAgIQAAgJAEgHQADgHAGgDQAHgEAHAAQAIAAAGADQAGAEADAHQADAGAAAJIAAABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgpAAIAAABIgBABQAAAFADAFQADAEAEADQAEACAFAAQAFAAAEgCQAFgCADgFIABAAIAAAAIAFACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQgDAEgDADQgEADgEABIgKABQgHAAgHgDgAgIgUQgEADgCAFQgCAEAAAFIAgAAIACAAIAAgCQAAgEgCgEQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_16.setTransform(44.275,0.025);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAKAnIgEAAQgGAAgDgDQgDgEAAgGIAAgkQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgJAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgEQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAJAAIABgBIABgRQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAARIABABIAOAAIABABIAAAEIgBACIgOAAIgBABIAAAiQAAAEACACQACACADAAIAIAAIABABIAAABIAAADIgBABIgDABg");
	this.shape_17.setTransform(39.475,-0.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIgBgBIAAgmQAAgFgCgDQgDgDgGAAIgFABIgFADIgHAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgHAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAHgFIAGgDIAGgBQAJAAAFAFQAEAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_18.setTransform(33.95,-0.025);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgCApIgCgBIAAgBIAAhNQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAABNIAAABIgCABg");
	this.shape_19.setTransform(28.625,-1.125);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_20.setTransform(19.975,0.025);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAYApIgBAAIgBgBIgqg9IgBgBIAAABIAAA8QAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgHAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAIABAAIABABIApA8IAAAAIABgBIAAg7QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAAAAAIAHAAIABABIAABOIgBABIAAABg");
	this.shape_21.setTransform(12.35,-1.125);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgDAOIgCAAIAAAAIAAgCIAFgLQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgCAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgJQAAgBAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAIAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAJIAAABIgHAOIgBABg");
	this.shape_22.setTransform(2.025,3.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgFIAAgBIABgBIAEgCIABAAIAAAAIAFAFIAGADQADACAEAAQAEAAADgCQAEgBACgCQACgCAAgDQAAgDgDgCQgCgCgGgCIgKgDQgJgCgDgDQgDgEAAgFQAAgFADgEQACgEAFgCQAGgCAFAAQAIAAAFADQAGACADAFIAAABIAAABIgFACIAAAAIgBAAQgCgDgEgDQgEgCgGAAQgFAAgEADQgEACAAAFQAAAAAAABQABABAAAAQAAABAAAAQABABAAAAQACACAFACIANAEQAIABADAEQADAEAAAFQAAAFgDAEQgDAEgFACQgFACgHAAQgIAAgGgDg");
	this.shape_23.setTransform(-2.525,0.025);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAKAnIgEAAQgGAAgDgDQgDgEAAgGIAAgkQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgJAAQAAAAAAgBQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgEQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAJAAIABgBIABgRQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAARIABABIAOAAIABABIAAAEIgBACIgOAAIgBABIAAAiQAAAEACACQACACADAAIAIAAIABABIAAABIAAADIgBABIgDABg");
	this.shape_24.setTransform(-7.375,-0.95);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIAAgBIAAgmQgBgFgCgDQgDgDgFAAIgFABIgHADIgGAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgFAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAGgFIAHgDIAGgBQAJAAAEAFQAFAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAAAg");
	this.shape_25.setTransform(-12.9,-0.025);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgNAbQgGgEgEgHQgDgHAAgIQAAgJAEgHQADgHAGgDQAHgEAHAAQAIAAAGADQAGAEADAHQADAGAAAJIAAABQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAIgpAAIAAABIgBABQAAAFADAFQADAEAEADQAEACAFAAQAFAAAEgCQAFgCADgFIABAAIAAAAIAFACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAQgDAEgDADQgEADgEABIgKABQgHAAgHgDgAgIgUQgEADgCAFQgCAEAAAFIAgAAIACAAIAAgCQAAgEgCgEQgCgEgEgDQgEgDgFAAQgFAAgEADg");
	this.shape_26.setTransform(-19.625,0.025);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAiAeIgBgBIgBgBIAAgmQAAgFgCgDQgDgDgFAAIgGABIgGADIgEADIgBACIAAABIAAAnQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgFAAIgBgBIgBgBIAAgmQAAgFgCgDQgDgDgFAAQgFAAgEACIgJAHIAAAoQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgGAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAHgFIAGgDIAHgBQAGAAAEADQADADABAEIABAAIABAAIAHgFIAGgDIAHgCQAIAAAEAFQAFAEAAAIIAAAoQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAg");
	this.shape_27.setTransform(-27.575,-0.025);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgWAmIgBgBIAAgEIAAgBIADgBIAHAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAIADgEIACgFQAAgBABAAQAAgBAAgBQgBAAAAgBQAAAAAAgBIgVgzIAAgBIABgBIAHAAIABAAIABABIAPAqIABABIABgBIAQgqIABgBIABAAIAFAAIABAAIAAACIgYA8IgDAHIgEAEIgFACIgHAAg");
	this.shape_28.setTransform(-35.7875,0.925);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgSAaQgFgEAAgIQAAgFADgFQAEgEAGgBQAGgDAJAAIAIgBIACgBIAAgBIAAgDQAAgGgDgDQgEgEgGAAQgEAAgEADQgEACgDAEIgBABIgBAAIgGgCIAAgBIAAgBQADgGAGgDQAGgDAIAAQAHAAAFACQAFACADAFQACAEAAAGIAAAmIAAABIgBAAIgGAAIgBAAIAAgCIgBgFQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQgEAEgFACQgFACgFAAQgIAAgFgEgAAOAAIgIAAIgIABIgGADQgDACgCACIgBAFQAAAFADADQAEADAFAAQADAAADgCIAGgDIAEgEQAAgBAAAAQABgBAAAAQAAgBAAgBQAAAAAAgBIAAgJQAAAAAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAIAAAAg");
	this.shape_29.setTransform(-42.575,0.025);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgbApIgBgBIgBgBIAAhNQAAgBAAAAQAAAAABAAQAAgBAAAAQAAAAABAAIAbAAQAIAAAHADQAHACAEAFQAEAGAAAIQAAAIgEAFQgEAFgGACQgHADgIAAIgSAAIgBABIAAAfQAAABAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAgAgSgfIAAAdQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAABAAIARAAQAIAAAGgEQAFgEAAgIQAAgGgDgDQgCgEgEgBQgFgCgFAAIgRAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAAAg");
	this.shape_30.setTransform(-49.275,-1.125);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_31.setTransform(-60.375,0.025);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAZApIgCAAIgBgBIgpg9IgBgBIAAABIAAA8QAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgGAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAGAAIABAAIABABIAoA8IABAAIABgBIAAg7QAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAGAAIABABIAABOIgBABIgBABg");
	this.shape_32.setTransform(-68,-1.125);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgDApQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgwIgBgBIgLAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAgEIABgBIABgBIALAAIABgBIAAgIQAAgHADgDQACgEAHAAIAJAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAAAFIAAABIgBAAIgIAAQAAAAgBAAQgBAAAAAAQgBAAAAABQgBAAAAABQgBACAAAEIAAAHIABABIAMAAIABABIAAABIAAAEIgBABIgMAAIgBABIAAAwQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_33.setTransform(39.4,-14.125);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_34.setTransform(33.875,-12.975);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgFIAAgBIABgBIAEgCIABAAIAAAAIAFAFIAGADQADACAEAAQAEAAADgCQAEgBACgCQACgCAAgDQAAgDgDgCQgCgCgGgCIgKgDQgJgCgDgDQgDgEAAgFQAAgFADgEQACgEAFgCQAGgCAFAAQAIAAAFADQAGACADAFIAAABIAAABIgFACIAAAAIgBAAQgCgDgEgDQgEgCgGAAQgFAAgEADQgEACAAAFQAAAAAAABQAAABABAAQAAABAAAAQABABAAAAQACACAFACIANAEQAIABADAEQADAEAAAFQAAAFgDAEQgDAEgFACQgFACgHAAQgIAAgGgDg");
	this.shape_35.setTransform(23.525,-12.975);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAQApIgBgBIgBgBIAAgnQAAgEgCgDQgDgDgGAAIgEABIgGADIgHAFIAAAoQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgHAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAAAAAIAHAAIABABIAAAeIAAAAIABAAIAHgFIAGgDIAHgBQAIAAAFAFQAEAEAAAIIAAAoQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAg");
	this.shape_36.setTransform(17.4,-14.125);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAKAnIgEAAQgGAAgDgDQgDgDAAgIIAAgkQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAgBAAAAIgJAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIAAgEQAAAAAAgBQAAAAAAAAQAAAAABAAQAAgBAAAAIAJAAIABAAIABgSQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAEAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAIAAASIABAAIAOAAIABABIAAAFIgBABIgOAAIgBABIAAAiQAAAFACADQACABADAAIAIAAIABAAIAAABIAAAEIgBACIgDAAg");
	this.shape_37.setTransform(11.975,-13.95);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAQAeIgBgBIAAgBIAAgmQgBgFgCgDQgDgDgFAAIgFABIgHADIgGAFIAAAoQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgFAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2QAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAHAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAGIAAABIABgBIAGgFIAHgDIAGgBQAJAAAEAFQAFAFAAAHIAAAoQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAAAAAg");
	this.shape_38.setTransform(6.45,-13.025);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgNAbQgHgEgDgHQgEgHAAgJQAAgIAEgHQADgGAHgEQAGgEAHAAQAJAAAGAEQAGAEAEAHQADAGAAAIQAAAJgEAHQgDAHgGAEQgGADgJAAQgHAAgGgDgAgJgTQgEACgCAGQgCAFAAAGQAAAHACAGQACAFAEADQAFACAEAAQAGAAAEgCQAEgDACgFQACgGAAgHQAAgGgCgFQgCgGgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_39.setTransform(-0.225,-12.975);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAeApIgBgBIAAgBIAAg+IgBAAIAAAAIgYA+QAAABgBAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgEAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgYg9IAAAAIAAAAIAAA9IAAABIgCABIgGAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAhNQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIALAAIABAAIABABIAYA+IAAABIABgBIAYg9IACgCIALAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIAABNQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_40.setTransform(-8.275,-14.125);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgYApIgCAAIAAgCIAAgEIAAgBIABgCIACgCIAXgXIAHgHIAFgGIADgGIABgGQAAgFgCgDQgDgDgEgCQgDgBgEAAIgGABQgDABgDACIgGAHIgBAAIgBAAIgFgDIgBgBIAAgBQAFgIAIgDQAHgDAGAAQAHAAAHACQAFADAEAFQADAFAAAHQAAAFgCAFQgBAEgEAEIgLAKIgUAVIgBABIABAAIAlAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAGIAAABIgCAAg");
	this.shape_41.setTransform(-20.35,-14.175);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgSApIgCgBIAAgHIACgBIANAAIABAAIAAg8IgBgBIgNAGQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAAgEIAAgBIACgBIAQgIIACgBIAAAAIAFAAIABABIAABHIAAAAIAOAAIAAABIAAAHIAAAAIAAABg");
	this.shape_42.setTransform(-27.7,-14.125);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgBAYQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgSIAAgGIAAgTIABgBIABgBIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAUIATAAIABAAIAAAEQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABgBAAIgSAAIAAgGIgHAAIAHAAIAAAGIgHAAIAHAAIAAATQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAAAgAgVAEIgCAAIAAgBIAAgFIABAAIATAAIAAAGgAgDgCg");
	this.shape_43.setTransform(-37.875,-14.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.2,-20.5,148.4,41);


(lib.Promo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhbCSQgEgBgBgBIgCgGIAAkUQAAgGAGAAIC6AAQAFAAAAAFIAAAfQAAAHgHAAIh9AAQgHAAAAAFIAABJQAAAGAGAAIBaAAQAGAAgBAFIAAAfQABAFgGgBIhbAAQgFAAAAAGIAABtQAAAHgJABg");
	this.shape.setTransform(76.6,-9.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhaCSQgFgBgCgBIgBgGIAAkUQAAgGAGAAIC5AAQAGAAAAAFIAAAfQAAAHgHAAIh+AAQgGAAAAAFIAABJQAAAGAFAAIBbAAQAFAAABAFIAAAfQgBAFgFgBIhbAAQgFAAAAAGIAABtQAAAHgIABg");
	this.shape_1.setTransform(52.7,-9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhFCDQgdgRgQghQgQgiAAguQAAguAQgiQAQgiAegSQAdgRAnAAQAoAAAdARQAeASAQAiQAQAiAAAuQAAAugQAhQgQAhgeASQgdASgoAAQgnAAgegSgAg0hRQgRAaAAA4QAAA4ARAZQARAaAkAAQAjAAARgaQARgZAAg4QAAg4gRgaQgSgagjAAQgjAAgRAag");
	this.shape_2.setTransform(24.325,-9.675);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA6CLQgRgLgKgSQgJgTAAgYQAAgZAJgSQAKgTARgJQAQgLAVAAQAUAAAQALQAQAJAKATQAJATAAAYQAAAYgJATQgKASgQALQgQAKgUAAQgWAAgPgKgABMASQgHAGgEAOQgFAMAAARQABARADAMQAEANAIAHQAHAHALgBQALABAHgHQAIgHAEgNQAEgMAAgRQAAgRgFgMQgDgOgIgGQgHgIgLABQgLgBgHAIgAhmCTQgEAAgBgDQgBgEADgCIC5kaIAFgDIAEgBIARAAIAFABQAAACgBAEIi8EcQgEAEgFAAgAiBAFQgRgKgJgSQgKgTAAgYQAAgYAKgSQAJgTARgLQAQgLAVAAQAUAAAQALQAQALAKATQAJASAAAYQAAAYgJATQgKASgQAKQgQALgUgBQgVABgQgLgAhvhzQgIAHgDAMQgFANAAASQAAAQAFANQADANAIAGQAHAHALAAQASAAAIgPQAIgPAAgZQAAgagIgPQgJgQgRAAQgLAAgHAHg");
	this.shape_3.setTransform(-16.2,-9.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag5CDQgbgRgPggQgOggAAgtQAAgvAPgiQAQgiAcgUQAcgSAlAAQARAAAPAFQAOAEAMAHQALAHAHAJQAIAIADAIIABAEQAAABAAAAQAAABgBAAQAAABgBAAQgBABAAAAIgkANQgBAAAAAAQgBAAgBAAQAAgBgBAAQAAAAAAAAIgDgEQgHgJgKgHQgKgGgPAAQgVAAgQAKQgPAMgHASQgHAUgBAYIACAJQACACAEgDIAdgLQAOgFAUAAQAeAAAXALQAWALAMATQAMATAAAZQAAAbgPAWQgPAVgYAMQgZAMgeAAQgkAAgagSgAgNAKIgUAFIgPAIIgGAGIgBAJQABANADANQAEAMAHAKQAIAMALAFQALAHAOAAQAPAAAMgHQAMgHAHgMQAHgMAAgPQAAgPgHgLQgGgLgMgGQgMgGgPAAg");
	this.shape_4.setTransform(-42.85,-9.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhgCTIgHgBQgCgCAAgEIAAgaIABgEIAFgGIAKgKIBMhHIAdgbIASgVQAHgKADgIQADgJAAgJQAAgOgIgJQgGgKgLgFQgLgFgMAAQgLAAgKAEQgLAEgJAJQgLAJgIAPQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgGgBIgdgQQgEgCAAgDQAAgDACgDQATgeAbgOQAbgNAfAAQAdAAAXAJQAWAKAOAUQANATAAAbQAAARgFAOQgHAPgMAPQgNAOgWASIhKA/IgCADQAAAAAAAAQABABAAAAQABAAABAAQABAAABAAIB+AAQAHAAAAAGIAAAkIgCAFQgBABgEAAg");
	this.shape_5.setTransform(-66.4,-9.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgFA7QAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgOQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAOQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBAAgAgBAeIgCAAIAAgBIgEhWIABgBIABAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIgDBVIgBACIgCAAg");
	this.shape_6.setTransform(85.025,-39.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgTAnQgJgGgFgJQgFgLgBgMQABgNAFgKQAFgKAKgGQAIgFALAAQALAAAJAFQAJAFAFAKQAEAKAAANIAAACQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIg9AAIAAABIAAACQAAAHADAGQAEAHAGAEQAGAEAIAAQAIAAAGgDQAGgEAEgGIACgBIABAAIAGAEQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgFAHgFAEQgFAEgHACQgGACgIAAQgLAAgJgFgAgNgdQgGAEgDAGQgCAHAAAHIAvAAIADAAIAAgCQAAgHgDgGQgDgGgGgDQgFgEgIgBQgHAAgHAFg");
	this.shape_7.setTransform(78.95,-38);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgEA7QAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAhxQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAJAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIAABxIgBACIgCAAg");
	this.shape_8.setTransform(72.625,-39.675);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbAlQgHgFAAgLQAAgJAFgGQAEgGAKgCQAJgEANgBIAMgBIACgBIABgBIAAgEQAAgJgFgGQgGgEgJgBQgGAAgGAEQgFADgFAHIgBABIgBAAIgJgDIAAgBIAAgCQAFgIAIgFQAJgFAMAAQAKAAAIAEQAHADADAGQAEAGAAAIIAAA4IAAACIgCABIgIAAIgCgBIAAgCIgBgHQAAgBAAAAQAAAAgBAAQAAAAAAAAQgBAAAAABQgGAFgHADQgHADgHAAQgNAAgHgHgAAUAAIgLAAIgMACQgGABgEADQgEADgCADQgCADAAAEQAAAIAFADQAFAEAIAAIAJgBIAIgGIAGgFQACgEAAgDIAAgNQAAgBAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAIAAAAg");
	this.shape_9.setTransform(65.975,-38);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgUAnQgKgFgEgIIAAgBIABgBIAGgDIABgBIABABQADAEAEADQADADAFACQAFABAGAAIALgBQAFgCADgDQADgDAAgEQAAgFgEgDQgDgDgJgDIgPgEQgNgDgEgEQgFgGAAgIQAAgHAEgGQAEgFAHgDQAIgEAIAAQALAAAJAEQAIAFAEAGIABABIgBABIgHAEIgBAAIgBAAQgDgGgGgCQgGgDgIgBQgHAAgGAEQgGAEAAAGQAAADADAEQACADAIACIAUAGQALACAEAGQAFAFAAAIQAAAHgEAHQgFAFgIADQgHADgKAAQgMAAgJgFg");
	this.shape_10.setTransform(57.775,-38);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AggA3QAAAAgBAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIAAgHIABgBIAEgBIAKAAQAEAAACgCQADgCACgEQACgDABgEQAAgEgBgCIgehMIAAgCIACgBIAJAAIACABIABABIAXA9IABACQABAAAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIAXg9IABgBIABgBIAIAAIACABIAAACIgkBZQgCAGgCADQgCAEgEACIgHADIgKABg");
	this.shape_11.setTransform(45.7125,-36.675);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTArIgCAAIAAgCIAAhPQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAIAKAAQAAAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIACgBIAHgIQAEgDAEgCIAIgBQAHAAAAACIAAAKQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgEAAIgDgBIgIACQgEABgDADQgDADgCADQgCAEAAADIAAA0QAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_12.setTransform(39.4,-38.075);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgbAlQgHgFAAgLQAAgJAFgGQAEgGAKgCQAJgEANgBIAMgBIACgBIABgBIAAgEQAAgJgFgGQgGgEgJgBQgGAAgGAEQgFADgFAHIgBABIgBAAIgJgDIAAgBIAAgCQAFgIAIgFQAJgFAMAAQAKAAAIAEQAHADADAGQAEAGAAAIIAAA4IAAACIgCABIgIAAIgCgBIAAgCIgBgHQAAgBAAAAQAAAAgBAAQAAAAAAAAQgBAAAAABQgGAFgHADQgHADgHAAQgNAAgHgHgAAUAAIgLAAIgMACQgGABgEADQgEADgCADQgCADAAAEQAAAIAFADQAFAEAIAAIAJgBIAIgGIAGgFQACgEAAgDIAAgNQAAgBAAAAQAAgBgBAAQAAAAAAAAQAAAAgBAAIAAAAg");
	this.shape_13.setTransform(31.175,-38);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUAnQgKgFgEgIIAAgBIABgBIAGgDIABgBIABABQADAEAEADQADADAFACQAFABAGAAIALgBQAFgCADgDQADgDAAgEQAAgFgEgDQgDgDgJgDIgPgEQgNgDgEgEQgFgGAAgIQAAgHAEgGQAEgFAHgDQAIgEAIAAQALAAAJAEQAIAFAEAGIABABIgBABIgHAEIgBAAIgBAAQgDgGgGgCQgGgDgIgBQgHAAgGAEQgGAEAAAGQAAADADAEQACADAIACIAUAGQALACAEAGQAFAFAAAIQAAAHgEAHQgFAFgIADQgHADgKAAQgMAAgJgFg");
	this.shape_14.setTransform(22.975,-38);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTArIgCAAIAAgCIAAhPQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAIAKAAQAAAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAALIAAABIACgBIAHgIQAEgDAEgCIAIgBQAGAAABACIAAAKQAAAAgBAAQAAABAAAAQAAAAAAAAQgBAAAAAAIgEAAIgDgBIgIACQgEABgCADQgEADgCADQgCAEAAADIAAA0QAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_15.setTransform(17.25,-38.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgTAnQgJgGgGgJQgEgLAAgMQAAgNAEgKQAGgKAKgGQAJgFAKAAQALAAAJAFQAJAFAFAKQAEAKABANIgBACQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIg9AAIgBABIAAACQAAAHAEAGQAEAHAGAEQAHAEAGAAQAJAAAFgDQAHgEAEgGIABgBIABAAIAHAEQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAgBAAQgEAHgFAEQgFAEgGACQgHACgIAAQgLAAgJgFgAgMgdQgHAEgCAGQgEAHAAAHIAwAAIADAAIAAgCQAAgHgDgGQgDgGgFgDQgGgEgIgBQgIAAgFAFg");
	this.shape_16.setTransform(9.6,-38);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgCArQgBgBAAAAQgBAAAAAAQgBAAAAgBQgBAAAAgBIgghPIAAgBIACgBIAKAAIABAAIABACIAYA+QAAAAABABQAAAAAAAAQABAAAAgBQAAAAABgBIAZg9IABgCIABAAIAIAAIABABIAAABIggBPQgBABAAAAQAAABgBAAQAAAAgBAAQgBAAAAABg");
	this.shape_17.setTransform(1.2875,-38);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgEA7IgBAAIgBgCIAAhPQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAJAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABPIgBACIgCAAgAgEgoIgCAAIAAgCIAAgOQAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAANQAAABAAABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_18.setTransform(-4.725,-39.675);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAXArIgBAAIgBgCIAAg4QAAgIgEgEQgEgFgIAAQgFAAgDACQgEABgEADIgJAHIAAA8QAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgJAAQAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAgBIAAhPQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAJAAQABAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAAKIABAAIABAAIAJgHIAKgFQAEgBAFAAQANAAAGAHQAHAGAAALIAAA7QAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_19.setTransform(-10.775,-38.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAXArIgBAAIgBgCIAAg4QAAgIgEgEQgEgFgIAAQgFAAgDACQgEABgEADIgJAHIAAA8QAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgJAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAhPQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAJAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAKIABAAIABAAIAJgHIAKgFQAEgBAFAAQANAAAGAHQAHAGAAALIAAA7QAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_20.setTransform(-19.625,-38.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAmA7QgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgLgfIAAgBIgCgBIgtAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAABIgLAfIgBABIgCAAIgJAAIgCAAIAAgCIAqhxIABgCIACAAIALAAQABAAABAAQAAAAABAAQAAAAAAABQABAAAAABIApBxIAAABIgCABgAgBgpIgTA0QgBABAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIAmAAQABAAAAAAQAAAAAAAAQABAAAAgBQgBAAAAgBIgTg0IAAgBg");
	this.shape_21.setTransform(-29.175,-39.675);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgTAnQgJgGgFgJQgGgLAAgMQAAgNAGgKQAFgKAJgGQAJgFALAAQAMAAAIAFQAJAFAEAKQAGAKgBANIAAACQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg8AAIgBABIAAACQgBAHAEAGQAEAHAGAEQAGAEAIAAQAHAAAGgDQAHgEAEgGIACgBIABAAIAGAEQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAAAQgFAHgFAEQgFAEgHACQgGACgIAAQgLAAgJgFgAgNgdQgFAEgEAGQgCAHAAAHIAvAAIACAAIABgCQAAgHgDgGQgDgGgGgDQgFgEgIgBQgHAAgHAFg");
	this.shape_22.setTransform(-43.55,-38);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAXArIgBAAIgBgCIAAg4QAAgIgEgEQgEgFgIAAQgFAAgDACQgEABgEADIgJAHIAAA8QAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgJAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAhPQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAJAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAKIABAAIABAAIAJgHIAKgFQAEgBAFAAQANAAAGAHQAHAGAAALIAAA7QAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_23.setTransform(-52.375,-38.075);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgVAoQgGgDgDgFQgEgGAAgHIAAg7QAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQAAABABAAQAAABAAAAIAAA3QAAAIAEAFQAFAFAHAAQAGAAAHgEQAGgEAGgGIAAg7QAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAIAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIgBBQQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAAAIgKAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgJIgBgBIgBAAQgJAIgGADQgGACgHAAQgHAAgGgDg");
	this.shape_24.setTransform(-61.375,-37.925);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgNA7IgHgCIgBgBIgBgDIACgIQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAFADQADABAFAAQAGAAADgEQADgEAAgKIAAhWQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAQAAAAABAAQAAAAAAAAQAAABABAAQAAABAAAAIAABZQAAAOgGAHQgGAHgNAAQgGAAgFgBg");
	this.shape_25.setTransform(-69.025,-39.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.2,-48,171.10000000000002,63.5);


(lib.logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Logo();
	this.instance.setTransform(-160,-25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160,-25,320,50);


(lib.line = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("AhzAAIDnAA");
	this.shape.setTransform(-0.925,-0.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-13.5,-1.2,25.2,2);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AEVBCQgMgHgGgLQgHgLAAgQQAAgPAHgLQAHgNALgGQAMgIAOAAQAPAAAKAIQALAGAHAMQAGAKAAARIAAADQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAgBAAIhAAAIgCAAIAAADQAAAHADAFQAEAFAFAEQAGADAHAAQAHAAAFgDIANgLIAAgBIAQAHQABAAAAABQABAAAAAAQAAABgBAAQAAABgBABQgGAIgGAGQgGAFgJADQgIABgKAAQgPAAgLgGgAElgLQgGAEgCAFQgDAEAAAHIAmABIADgBIABgBQAAgGgDgEQgCgEgEgEQgEgDgIAAQgGAAgEACgAgHA/QgPgIgIgRQgIgPAAgXQAAgVAIgRQAJgQAPgIQAOgJASAAQAUAAAPAJQAOAIAIAQQAIARAAAVQAAAXgIAPQgIARgOAIQgPAJgUAAQgUAAgNgJgAAEgkQgHAMAAAYQAAAaAHAMQAHALAPAAQAQAAAIgLQAHgMAAgaQAAgYgHgMQgIgMgQAAQgPAAgHAMgAkBBCQgMgHgGgLQgHgLAAgQQAAgPAHgLQAHgNALgGQAMgIAOAAQAPAAAKAIQALAGAHAMQAGAKAAARIAAADQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAAAAAIhBAAIgCAAIAAADQAAAHAEAFIAIAJQAGADAHAAQAHAAAFgDQAGgEAGgHIACgBIAQAHQAAAAABABQAAAAAAAAQAAABAAAAQgBABAAABQgGAIgGAGQgHAFgJADQgIABgKAAQgPAAgLgGgAjygLQgEAEgDAFQgDAEAAAHIAnABIACgBIABgBQAAgGgDgEQgCgEgEgEQgEgDgHAAQgGAAgGACgAmYA/QgOgIgHgRQgIgQAAgWQAAgVAIgRQAIgQAOgIQAPgJAUAAQAPAAAMAFQAMAGAIAKQAIAIACAKIAAAFIgDABIgZAEIgCgBIgBgDQgBgGgDgEQgEgGgGgDQgGgDgIAAQgIAAgHAEQgHAGgDAKQgEALAAARQAAASAEAKQAEALAHAFQAHAFAJAAQAGAAAEgCQAGgCACgDQAEgDACgEIADgIIABgFQAAgBAAgBQAAAAAAgBQgBAAAAgBQgBAAgBAAIgZAAIAAgCIAAgOQAAgBAAgBQAAAAABAAQAAAAAAAAQABAAABAAIAzAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAAAAAIACADIAABBIgCADIgGAAIgDgCIgDgCIgFgNIgBgBIgCABQgDAFgFAEQgFAEgIACQgHADgLAAQgTAAgPgJgAF4BHQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgBgCIAAhdQAAgEADAAIAWAAQAEAAAAAEIAAALIAAACIACgBIAIgKIALgFQAEgDAGAAQAGAAAAAEIAAAWQAAABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgNgBIgHABQgEACgDACIgFAFIgCAGIAAA3QAAAFgFAAgADQBHQgDAAAAgEIAAhKQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAIgOAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgOIABgCQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIAMAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAgBAAAAIAAgMQAAgMAHgGQAIgHANAAIATAAQAEAAAAADIAAANIgBACQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAIgLAAQgEAAgDADQgCADAAAFIAAAHQAAABAAAAQAAAAAAABQABAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABACIAAAOQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAIgQAAQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAABIAABKQAAAEgDAAgACBBHQAAAAgBAAQAAgBAAAAQAAgBgBgBQAAAAAAgBIAAhKQAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAgBAAIgOAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgOIABgCQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIAMAAQABAAABAAQAAAAABAAQAAgBAAAAQAAgBAAAAIAAgMQAAgMAHgGQAHgHAOAAIATAAQAEAAAAADIAAANIgBACQAAAAAAAAQAAAAgBAAQAAABAAAAQAAAAgBAAIgKAAQgEAAgDADQgDADAAAFIAAAHQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAIAQAAQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIABACIAAAOQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAIgQAAQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAABIAABKQAAAEgDAAgAiPBBQgHgGAAgNIAAg0QAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAIgLAAQgFAAAAgDIAAgOQAAgEAEAAIANAAQABAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIADgcQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAUAAQAEAAAAADIAAAcQAAABAAAAQAAAAAAABQAAAAABAAQAAAAAAAAIAUAAQABAAABAAQAAABABAAQAAABABAAQAAABAAABIAAAOQAAADgEAAIgVAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABIAAAtQAAAHACACQAEADAGAAIAKAAIADABIABACIgBAMQAAAEgDAAIgYACQgNAAgHgGg");
	this.shape.setTransform(0.025,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6CC24D").s().p("Am1CDQg3AAgmgmQgbgbgIgjQgDgPgBgPIAAgBQAAg1AngnQASgRAUgKQAZgLAeAAINrAAQAeAAAZALQAUAKASARQAnAnAAA1IAAABQAAAPgEAPQgIAigbAcQgnAmg2AAg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.9,-13.1,113.9,26.2);


// stage content:
(lib.WBAY_216348_MM_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#010101").ss(1,1,1).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(160));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(262,39.85,0.6,0.6,0,0,0,0.1,0.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(62).to({_off:false},0).to({y:37.35,alpha:1},13).wait(85));

	// T2
	this.instance_1 = new lib.T2("synched",0);
	this.instance_1.setTransform(263.75,11.25,0.6,0.6,0,0,0,0.1,0.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(49).to({_off:false},0).to({y:16.25,alpha:1},13,cjs.Ease.get(1)).wait(98));

	// line
	this.instance_2 = new lib.line("synched",0);
	this.instance_2.setTransform(209.55,25,1,1,-90,0,0,-0.9,-0.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(22).to({_off:false},0).wait(138));

	// Promo
	this.instance_3 = new lib.Promo("synched",0);
	this.instance_3.setTransform(148.2,27.45,0.6,0.6,0,0,0,4.6,-16.4);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(14).to({_off:false},0).to({y:24.95,alpha:1},16,cjs.Ease.get(1)).wait(130));

	// logo
	this.instance_4 = new lib.logo("synched",0);
	this.instance_4.setTransform(160,15);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({y:25,alpha:1},14,cjs.Ease.get(1)).wait(146));

	// BG
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#54585A").s().p("AyCD6IAAnzMAkFAAAIAAHzg");
	this.shape_1.setTransform(204.5,25);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(160));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(159,15,162,36);
// library properties:
lib.properties = {
	id: 'ECAEFFBAF1704CA9B680B457A657B9CE',
	width: 320,
	height: 50,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Logo.png", id:"Logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['ECAEFFBAF1704CA9B680B457A657B9CE'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;