(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgUAnQgJgGgGgKQgFgJAAgMQAAgNAFgLQAGgKAJgGQAKgFALAAQAMAAAJAFQAJAFAFALQAFAKAAAMIAAADQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAABQAAAHADAFQADAGAGACQAFAEAFAAQAHAAAFgDQAGgDAEgGIACgBIABAAIAKAFQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBAAQgEAHgGAEQgFAEgHACQgHACgIAAQgLAAgKgFgAgJgbQgFAEgCAEQgDAGAAAHIAlAAIACgBIABgCQAAgFgCgFQgDgEgEgEQgEgDgHAAQgFAAgFADg");
	this.shape.setTransform(168.625,-10);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgWAnQgKgFgEgIIAAgCIABgBIAJgFIACgBIABABIAGAGQADADAFACQAEABAGABQAFgBAEgBQAEgBACgDQADgCAAgDQAAgDgDgDQgDgCgHgCIgPgEQgMgDgGgFQgGgFAAgJQAAgIAFgGQAEgGAIgDQAHgEAKAAQAMAAAJAEQAIAFAEAGIABACIgBACIgKAEIgBAAIgCgBQgDgDgFgDQgFgDgHAAQgGAAgFADQgEADAAAEQAAADACADQACACAGABIASAGQANADAFAFQAFAHAAAHQAAAJgEAGQgFAGgIADQgJADgKAAQgNAAgKgFg");
	this.shape_1.setTransform(159.025,-10);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgeAmQgHgHAAgKQAAgJAGgGQAFgGAKgDQAKgEANgBIAIgBIACAAIABgCIAAgDQAAgHgEgFQgEgEgIAAQgEABgFACQgFACgEAGIgBABIgCAAIgNgDIgBgBIAAgCQAEgKAKgFQAJgEANAAQAMAAAIAEQAIADADAGQAEAGAAAIIAAA4IgBACIgCAAIgOAAIgCAAIgBgDIAAgFQAAgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBAAQgFAFgHAEQgFACgIAAQgNAAgHgGgAAJACIgJABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAGAAQAEAAADgBIAHgEIAEgFIACgFIAAgLQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAAAg");
	this.shape_2.setTransform(149.625,-10);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAUA7IgCAAIgBgDIAAg3QAAgFgDgDQgEgEgGAAIgGABIgHAEIgHAGIAAA4QAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgPAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAqIAAABIABgBIAKgHQAFgDADgBIAJgBQANAAAGAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_3.setTransform(140.175,-11.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgSAnQgJgGgGgKQgFgJAAgOQAAgMAFgJQAGgKAJgHQAKgFALAAQAJAAAHAEQAHADAFAFQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOACQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIgEgGIgFgFQgDgBgEAAQgGAAgFADQgFAEgCAHQgDAGAAAJQAAAKADAGQADAIAFADQAFADAGABQAHAAAEgFQAFgDAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAHQgFAEgGACQgGACgHAAQgLAAgKgFg");
	this.shape_4.setTransform(130.5313,-10);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgWArIgCAAIgBgDIAAhOQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAABAAIAPAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAKIABABQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQADgFAEgDIAIgEQAFgCAEAAQAFAAAAACIAAAQQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgFgBIgFAAIgHABIgFADIgFAGQgBACAAADIAAAwQAAADgEAAg");
	this.shape_5.setTransform(122.5,-10.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgZAoQgFgDgDgFQgDgGAAgIIAAg5QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAPAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAA2QAAAGAEADQADAEAHAAQAEAAAFgDQAFgDAFgFIAAg4QAAgDADAAIAPAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAABOQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgQAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgBAAQgIAHgHADQgGADgGAAQgIAAgGgDg");
	this.shape_6.setTransform(113.55,-9.925);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgrA7IgCAAIgBgDIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAsAAQANAAAKADQALAEAGAIQAGAIAAANQAAAMgGAHQgFAHgKAEQgJAEgNAAIgYAAQgBAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAABIAAAqQAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAgAgWgnIAAAhQAAAAAAABQABAAAAABQAAAAAAAAQABAAAAAAIAVAAQAKAAAGgFQAGgEAAgKQAAgGgDgEQgDgEgFgCQgFgCgHAAIgTAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAABAAAAg");
	this.shape_7.setTransform(102.975,-11.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgiA0QgMgFAAgLQAAgFAEgEQAFgEAGgDQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAgBAAIgGgFQgCgCgBgEQAAgDACgDIAGgDIAHgEIABgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAAAQgIgDgDgGQgFgFAAgIQABgMAJgHQAKgHAUAAQAHAAAGACQAHABADAEIADABIACgBIAEgFIAGgDIAGgBIACABIABACIAAAJIgBADIgCABIgFgBIgDABQgBABgBAAQgBAAAAABQgBAAAAABQAAAAAAABIABADIABAFQAAAHgEAGQgEAGgIAEQgJADgLAAIgLABQgFABgBABQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAIAJACIAVABQAPABAIAGQAHAGAAAKQAAAMgMAHQgKAIgVAAQgWAAgLgGgAgVAYIgFAEQgCADgBADQABAEADADQADADAGACQAGABAKAAQALAAAHgDQAFgEAAgGQABgEgEgDQgDgCgHgBIgZgBIgCAAIgEABgAgQgoQgFAEAAAIQAAAGAFAEQAFAEAJAAQAIAAAFgEQAEgEAAgGQAAgIgEgEQgFgEgIAAQgJAAgFAEg");
	this.shape_8.setTransform(87.5,-8.725);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_9.setTransform(77.325,-10.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgGA7IgDAAIAAgDIAAhOQAAAAAAgBQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABOIgBACIgEABgAgGglIgDAAIAAgDIAAgPQAAgBAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAQQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_10.setTransform(69.95,-11.675);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgiA3QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgKIABgCIAEgBIAKAAQADAAADgBIAEgFIADgFIgBgFIgfhLQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAQAAIACABIACACIATA0IABABIABgBIAUg0IABgCIACgBIAMAAIACACIAAACIgiBTIgGAMQgDAFgEACQgEADgFABIgLABg");
	this.shape_11.setTransform(62.8792,-8.675);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgIA7QgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAhCIgBgBIgNAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIAAgKIAAgCIACgBIAMAAQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAgBIAAgKQAAgKAFgGQAGgFAKAAIAQAAQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAAAJIgBACIgCABIgJAAQgEAAgCACQgCADAAAFIAAAIQAAAAAAAAQAAABAAAAQAAAAAAAAQABAAAAAAIAPAAIACABIABACIAAAKQAAAAgBABQAAAAAAABQAAAAgBAAQAAAAAAAAIgPAAQgBAAAAAAQAAAAgBABQAAAAAAAAQAAAAAAABIAABBQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_12.setTransform(54.75,-11.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgGA7IgDAAIgBgDIAAhOQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABOQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAgBAAIgDABgAgGglIgDAAIgBgDIAAgPQAAgBABgBQAAAAAAgBQAAAAABAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAQQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_13.setTransform(48.95,-11.675);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgHA7QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhwQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAABwIgBACQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_14.setTransform(44.25,-11.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgeAmQgHgHAAgKQAAgJAGgGQAFgGAKgDQAKgEANgBIAIgBIACAAIABgCIAAgDQAAgHgEgFQgEgEgIAAQgEABgFACQgFACgEAGIgBABIgCAAIgNgDIgBgBIAAgCQAEgKAKgFQAJgEANAAQAMAAAIAEQAIADADAGQAEAGAAAIIAAA4IgBACIgCAAIgOAAIgCAAIgBgDIAAgFQAAgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBAAQgFAFgHAEQgFACgIAAQgNAAgHgGgAAJACIgJABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAGAAQAEAAADgBIAHgEIAEgFIACgFIAAgLQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAAAg");
	this.shape_15.setTransform(36.875,-10);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgYAoQgGgDgDgFQgDgGgBgIIAAg5QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAOAAQABAAABAAQAAAAABABQAAAAAAAAQABABAAABIAAA2QAAAGADADQAEAEAFAAQAFAAAFgDQAFgDAEgFIAAg4QAAgDAFAAIAOAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAABIAABOQAAABgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIgPAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgCAAQgHAHgGADQgGADgHAAQgIAAgFgDg");
	this.shape_16.setTransform(27.35,-9.925);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAeBCQgIgFgIgJQAAgBAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgGABIgGAAQgPAAgMgHQgMgHgHgOQgGgOAAgSQAAgTAGgOQAHgOAMgHQAMgHAPAAQAQAAAMAHQAMAHAHAOQAGAOAAATQAAARgFAMQgFAMgKAIIAAABQAAABAAAAQAAAAAAABQABAAAAABQABABAAAAIAHAEQAEADAFAAIABABIABABIAAAMQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAIgEAAQgJAAgIgEgAgVgpQgHAKAAAYQAAAVAHALQAHAKAOAAQAPAAAHgKQAHgLAAgWQAAgWgHgLQgHgLgPAAQgOAAgHALg");
	this.shape_17.setTransform(15.925,-10.775);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAUA7IgCAAIgBgDIAAg3QAAgFgDgDQgEgEgGAAIgGABIgHAEIgHAGIAAA4QAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgPAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAqIAAABIABgBIAKgHQAFgDADgBIAJgBQANAAAGAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_18.setTransform(0.575,-11.675);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape_19.setTransform(-8.175,-11.425);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgGA7IgDAAIgBgDIAAhOQAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABOQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAgBAAIgDABgAgGglIgDAAIgBgDIAAgPQAAgBABgBQAAAAAAgBQAAAAABAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAQQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_20.setTransform(-14.05,-11.675);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAcA7QgEAAgBgDIgWhMIgBgBIAAABIgWBMQgBADgDAAIgPAAQgEAAgBgDIgghuIAAgDIADgBIARAAIACAAIABACIAXBPIABACIABgCIAWhPIABgCIADAAIANAAIADAAIABACIAXBQIABABIABgBIAWhQIABgCIADAAIAMAAIADABIAAADIggBuQgBADgEAAg");
	this.shape_21.setTransform(-25.225,-11.675);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgWArIgCAAIgBgDIAAhOQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIAPAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAAKIABABQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQADgFAEgDIAIgEQAEgCAFAAQAFAAAAACIAAAQQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgFgBIgFAAIgHABIgFADIgFAGQgBACAAADIAAAwQAAABAAABQgBAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_22.setTransform(139.05,-31.475);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgUAnQgJgGgGgKQgFgJAAgMQAAgOAFgKQAGgKAJgGQAKgFALAAQAMAAAJAFQAJAGAFAJQAFALAAANIAAACQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIg4AAIgCABIAAABQAAAHADAGQADAEAGAEQAFADAFAAQAHgBAFgCQAGgDAEgGIACgBIABABIAKAEQAAAAABABQAAAAAAAAQAAABAAAAQAAABgBAAQgEAHgGAEQgFAEgHACQgHACgIAAQgLAAgKgFgAgJgaQgFADgCAEQgDAGAAAHIAlAAIACgBIABgCQAAgFgCgFQgDgEgEgDQgEgEgHAAQgFAAgFAEg");
	this.shape_23.setTransform(130.275,-31.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAUA7IgCAAIgBgDIAAg3QAAgFgDgDQgEgEgGAAIgGABIgHAEIgHAGIAAA4QAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgPAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhwQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIAAAqIAAABIABgBIAKgHQAFgDADgBIAJgBQANAAAGAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_24.setTransform(120.275,-33.075);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgSAnQgJgGgGgKQgFgJAAgNQAAgMAFgLQAGgKAJgGQAKgFALAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOACQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIgEgGIgFgFQgDgBgEAAQgGAAgFAEQgFADgCAHQgDAGAAAJQAAAKADAGQADAIAFADQAFADAGAAQAHABAEgEQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgLAAgKgFg");
	this.shape_25.setTransform(110.6313,-31.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgYAoQgGgDgDgFQgEgGAAgIIAAg5QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAOAAQABAAABAAQAAAAABABQAAAAAAAAQABABAAABIAAA2QgBAGAEADQAEAEAFAAQAFAAAFgDQAFgDAEgFIAAg4QAAgDAFAAIAOAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAABIAABOQAAABgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIgPAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgCAAQgHAHgGADQgGADgIAAQgHAAgFgDg");
	this.shape_26.setTransform(100.8,-31.325);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgVAnQgJgGgGgKQgFgKAAgMQAAgMAFgLQAGgKAKgGQAJgFALAAQANAAAJAGQAKAFAFAKQAFALAAAMQAAAMgGAKQgEAKgKAGQgJAFgNAAQgLAAgKgFgAgLgZQgEADgDAHQgCAGAAAJQAAAKACAGQADAHAEAEQAFADAGAAQAHAAAFgDQAEgEACgHQADgGAAgKQAAgJgDgGQgCgHgEgDQgGgEgGAAQgGAAgFAEg");
	this.shape_27.setTransform(90.8,-31.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgIA7QgEAAAAgDIgnhvQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIACgBIATAAQABAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAcBVQAAABAAAAQABABAAAAQAAAAAAgBQABAAAAgBIAchVQABgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAPAAIADABIAAACIgoBvQAAADgEAAg");
	this.shape_28.setTransform(79.6542,-33.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgOAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhOQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_29.setTransform(64.675,-31.475);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgVAnQgKgGgFgKQgFgKAAgMQAAgMAGgLQAFgKAJgGQAKgFALAAQANAAAJAGQAJAFAGAKQAFALAAAMQAAAMgFAKQgGAKgJAGQgJAFgNAAQgMAAgJgFgAgLgZQgEADgCAHQgDAGAAAJQAAAKADAGQACAHAEAEQAGADAFAAQAHAAAFgDQAEgEADgHQACgGAAgKQAAgJgCgGQgDgHgEgDQgFgEgHAAQgFAAgGAEg");
	this.shape_30.setTransform(54.55,-31.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgGA7IgDAAIgBgDIAAhOQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAABQABAAAAABIAABOQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAgBAAIgDABgAgGglIgDAAIgBgDIAAgPQAAgBABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAQQAAABgBAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_31.setTransform(47.15,-33.075);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgGAAIgGABg");
	this.shape_32.setTransform(41.125,-32.825);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgeAmQgHgHAAgKQAAgJAGgHQAFgFAKgEQAKgDANgBIAIAAIACgBIABgCIAAgDQAAgIgEgDQgEgFgIAAQgEABgFACQgFACgEAGIgBACIgCAAIgNgEIgBgBIAAgCQAEgJAKgGQAJgEANAAQAMAAAIADQAIAEADAGQAEAGAAAIIAAA3IgBADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBAAQgFAGgHACQgFADgIAAQgNAAgHgGgAAJACIgJABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAGAAQAEAAADgBIAHgEIAEgFIACgFIAAgLQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBAAAAAAg");
	this.shape_33.setTransform(32.525,-31.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgSAnQgJgGgGgKQgFgJAAgNQAAgMAFgLQAGgKAJgGQAKgFALAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOACQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAAAIgEgGIgFgFQgDgBgEAAQgGAAgFAEQgFADgCAHQgDAGAAAJQAAAKADAGQADAIAFADQAFADAGAAQAHABAEgEQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgLAAgKgFg");
	this.shape_34.setTransform(23.4813,-31.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgeAmQgHgHAAgKQAAgJAGgHQAFgFAKgEQAKgDANgBIAIAAIACgBIABgCIAAgDQAAgIgEgDQgEgFgIAAQgEABgFACQgFACgEAGIgBACIgCAAIgNgEIgBgBIAAgCQAEgJAKgGQAJgEANAAQAMAAAIADQAIAEADAGQAEAGAAAIIAAA3IgBADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBAAAAQAAgBgBAAQAAAAgBABQAAAAgBAAQgFAGgHACQgFADgIAAQgNAAgHgGgAAJACIgJABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAGAAQAEAAADgBIAHgEIAEgFIACgFIAAgLQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAAAg");
	this.shape_35.setTransform(13.675,-31.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgIA7QgEAAAAgDIgnhvQAAgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIACgBIATAAQABAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAcBVQAAABAAAAQABABAAAAQAAAAAAgBQABAAAAgBIAchVQABgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAPAAIADABIAAACIgoBvQAAADgEAAg");
	this.shape_36.setTransform(3.1542,-33.075);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgIApQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgSQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIARAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAARQAAAEgEAAgAgIgRQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAgSQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIARAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAABIAAARQAAADgEAAg");
	this.shape_37.setTransform(126.925,-52.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgWAnQgKgFgEgHIAAgCIABgCIAJgEIACgBIABABIAGAGQADACAFACQAEACAGgBQAFABAEgCQAEgBACgCQADgDAAgDQAAgEgDgCQgDgCgHgCIgPgEQgMgCgGgFQgGgGAAgJQAAgIAFgGQAEgGAIgEQAHgDAKAAQAMAAAJAEQAIAFAEAGIABACIgBABIgKAGIgBAAIgCgCQgDgEgFgCQgFgDgHAAQgGAAgFADQgEACAAAGQAAACACACQACACAGADIASAEQANADAFAGQAFAGAAAJQAAAIgEAGQgFAFgIAEQgJADgKAAQgNAAgKgFg");
	this.shape_38.setTransform(120.175,-52.8);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgZAoQgFgDgDgFQgDgGAAgIIAAg5QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAPAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAA2QABAGADADQADAEAHAAQAEAAAFgDQAFgDAFgFIAAg4QAAgDADAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAABIAABOQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgQAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgBAAQgIAHgHADQgFADgHAAQgIAAgGgDg");
	this.shape_39.setTransform(110.75,-52.725);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAUArIgCAAIgBgDIAAg2QAAgGgDgDQgEgEgGAAIgHABIgGAEIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAQAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABIAAAIIAAABIABAAIAJgHIAIgFQAFgBAFAAQAMAAAHAHQAHAGAAAMIAAA5QAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_40.setTransform(100.825,-52.875);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgVAmQgJgFgGgKQgFgKAAgMQAAgMAFgLQAGgJAKgGQAJgGALAAQANAAAJAGQAJAGAGAJQAFALAAAMQAAAMgGAKQgEAKgKAFQgJAGgNAAQgLAAgKgGgAgKgZQgFADgDAGQgCAIAAAIQAAAJACAIQADAGAFAEQAEADAGAAQAHAAAFgDQAEgEACgGQADgIAAgJQAAgIgDgIQgCgGgEgDQgGgEgGAAQgGAAgEAEg");
	this.shape_41.setTransform(90.7,-52.8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgrA7IgCAAIgBgCIAAhwIABgDIACAAIApAAQAWAAAMAHQAMAIAAAQQAAAJgFAGQgEAGgMAFIAAAAIAAABQAMADAGAGQAGAHAAALQAAAQgMAIQgMAIgXAAgAgWAKIAAAeQAAABAAAAQAAABABAAQAAAAAAABQABAAAAAAIATAAQALAAAHgFQAFgEAAgIQAAgHgCgEQgEgEgEgCQgGgBgGAAIgUAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAABAAAAgAgWgoIAAAdQAAABAAAAQAAABABAAQAAAAAAABQABAAAAAAIAUAAIAIgBIAGgDQADgCACgDQABgDABgFQAAgIgHgFQgGgEgJAAIgTAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAABAAAAg");
	this.shape_42.setTransform(79.85,-54.475);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAIA5QgKAAgFgFQgGgFAAgLIAAguQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgLAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAgBQAAAAAAAAQAAAAAAgBIADgYQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIANAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAYQAAABAAAAQAAAAABAAQAAABAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAKQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAABQAAAAgBAAQgBABAAAAIgGAAIgGABg");
	this.shape_43.setTransform(66.025,-54.225);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgWAnQgKgFgEgHIAAgCIABgCIAJgEIACgBIABABIAGAGQADACAFACQAEACAGgBQAFABAEgCQAEgBACgCQADgDAAgDQAAgEgDgCQgDgCgHgCIgPgEQgMgCgGgFQgGgGAAgJQAAgIAFgGQAEgGAIgEQAHgDAKAAQAMAAAJAEQAIAFAEAGIABACIgBABIgKAGIgBAAIgCgCQgDgEgFgCQgFgDgHAAQgGAAgFADQgEACAAAGQAAACACACQACACAGADIASAEQANADAFAGQAFAGAAAJQAAAIgEAGQgFAFgIAEQgJADgKAAQgNAAgKgFg");
	this.shape_44.setTransform(57.875,-52.8);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgYAoQgGgDgDgFQgEgGABgIIAAg5QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAPAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAA2QABAGADADQADAEAGAAQAFAAAFgDQAFgDAFgFIAAg4QAAgDADAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABABABIAABOQgBABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgPAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgBAAQgIAHgGADQgHADgHAAQgHAAgFgDg");
	this.shape_45.setTransform(48.45,-52.725);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgjA0QgLgFAAgLQAAgFAFgEQADgEAIgDQAAAAAAAAQABAAAAAAQAAgBgBAAQAAAAAAAAIgHgFQgDgCABgEQAAgDABgDIAGgDIAHgEIABgBQAAAAAAAAQAAAAAAAAQAAgBAAAAQAAAAAAAAQgIgDgEgGQgDgFAAgIQgBgMALgHQAKgHASAAQAIAAAHACQAFABAEAEIACABIACgBIAGgFIAFgDIAFgBIADABIABACIAAAJIgBADIgDABIgEgBIgEABQgBAAAAABQgBAAAAABQgBAAAAABQAAAAABABIAAADIABAFQAAAHgEAGQgEAGgJAEQgIADgLAAIgLABQgEABgCABQAAAAgBAAQAAAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAIAJACIAVABQAQABAGAGQAIAGAAAKQAAAMgLAHQgMAIgUAAQgXAAgLgGgAgVAYIgGAEQgCADAAADQAAAEADADQAEADAGACQAGABAKAAQALAAAGgDQAHgEgBgGQAAgEgDgDQgDgCgIgBIgYgBIgBAAIgFABgAgQgoQgEAEgBAIQABAGAEAEQAFAEAJAAQAIAAAFgEQAEgEAAgGQAAgIgEgEQgFgEgIAAQgJAAgFAEg");
	this.shape_46.setTransform(38.15,-51.525);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgYAoQgGgDgDgFQgEgGAAgIIAAg5QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIAOAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAAA2QgBAGAEADQAEAEAFAAQAFAAAFgDQAFgDAEgFIAAg4QAAgDAFAAIAOAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAABIAABOQAAABgBAAQAAABAAAAQAAAAgBABQAAAAgBAAIgPAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgIIAAgBIgCAAQgHAHgGADQgGADgIAAQgHAAgFgDg");
	this.shape_47.setTransform(27.9,-52.725);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AAhA7QAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAgBgBIgJgaIgBgBIgBAAIgpAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAgBAAIgJAaIgBACIgCAAIgQAAIgBgBQAAAAAAgBQgBAAAAAAQAAgBABAAQAAAAAAgBIAohvIABgCIADAAIATAAQADAAABADIAoBuIAAADIgCABgAgCghIgQAqQAAABAAAAQAAABAAAAQAAAAABABQAAAAABAAIAdAAQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAgBgBIgOgqIgBgBIgBABg");
	this.shape_48.setTransform(16.6625,-54.475);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70,-66,280,66.2);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAaA6IgCgBIgBgDIAAhJQAAgIgFgFQgEgFgJAAQgFAAgEACIgIAFIgKAIIAABMQAAAEgFAAIgTAAQgEAAAAgEIAAhqQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAVAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAAALIAAACIACgBIAMgJQAGgEAFgCQAHgCAGAAQARAAAJAJQAJAJAAAPIAABOQAAAEgFAAg");
	this.shape.setTransform(150.1,-41.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAcA5QgEAAgCgDIgVhCIgBgCIgBACIgUBCIgCADIgDAAIgQAAQgEAAgBgDIgihqQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAVAAIADABIABACIAWBEQAAAAAAABQAAAAABAAQAAABAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAIAVhEIABgCIADgBIAOAAIADABIABACIAWBEIABACQABAAAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAIAVhEIACgCIACgBIAOAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIAAADIgjBqIgBADIgDAAg");
	this.shape_1.setTransform(134.3542,-41.525);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgdA0QgMgIgIgNQgHgNAAgRQAAgRAHgOQAIgNANgIQANgHAPAAQARAAANAHQANAIAHANQAHAOAAAQQAAASgHANQgIANgMAIQgNAHgRAAQgQAAgNgHgAgOgjQgHAFgDAJQgDAJAAAMQAAANADAJQADAJAHAFQAGAEAIAAQAJAAAHgEQAGgFADgJQADgJAAgNQAAgMgDgJQgDgJgHgFQgGgFgJAAQgIAAgGAFg");
	this.shape_2.setTransform(118.625,-41.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("Ag8BQQgFAAAAgEIAAiXIABgDIAEgBIAKAAIALAAIAMAAIAJAAQAdABATAJQATAKAIARQAJASAAAYQAAAZgJASQgKASgTAKQgTAJgcAAgAghg1IAABsQAAAAAAABQAAAAABABQAAAAABAAQAAAAABAAIAGAAQATAAAMgFQANgGAGgNQAHgMgBgVQABgUgHgMQgFgNgNgFQgLgGgUAAIgIAAQgBAAAAAAQAAAAgBAAQAAABAAAAQAAABAAABg");
	this.shape_3.setTransform(103.95,-43.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AguBKQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIAAgPIABgCIAFAAIAPAAQAEgBADgCIAGgGIADgHQABgEgBgDIgqhlIAAgDQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAXAAIADABIABACIAaBHQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAABAAIAahHIACgCIACgBIAQAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABIguBwQgEAKgEAGQgEAHgFADQgFADgHACIgQABg");
	this.shape_4.setTransform(84.1375,-39.75);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgbA0QgNgHgHgNQgIgNAAgRQABgSAHgOQAHgOANgHQAOgHAOAAQARAAAMAHQAMAHAHANQAHANgBASIAAAEQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIhLAAIgCABIgBADQAAAJAFAHQADAHAIAEQAHAEAIAAQAIAAAIgEQAHgEAGgIIACgBIADABIANAGQAAAAAAAAQABABAAAAQAAABAAAAQAAABgBABQgGAJgIAGQgIAFgIADQgKACgLAAQgPAAgNgHgAgMgkQgHAEgDAHQgDAHAAAIIAyAAIACAAIABgDQAAgGgDgHQgDgGgGgEQgFgFgJAAQgIAAgGAFg");
	this.shape_5.setTransform(71.35,-41.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAaA6IgCgBIgBgDIAAhJQAAgIgFgFQgEgFgJAAQgFAAgEACIgIAFIgKAIIAABMQAAAEgFAAIgTAAQgEAAAAgEIAAhqQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAVAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIAAALIABACIACgBIAMgJQAGgEAFgCQAGgCAIAAQAQAAAJAJQAJAJAAAPIAABOQAAAEgFAAg");
	this.shape_6.setTransform(58.1,-41.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgdA0QgMgIgIgNQgHgNAAgRQAAgRAHgOQAIgNANgIQANgHAPAAQARAAANAHQANAIAHANQAHAOAAAQQAAASgHANQgIANgMAIQgNAHgRAAQgQAAgNgHgAgOgjQgHAFgDAJQgDAJAAAMQAAANADAJQADAJAHAFQAGAEAIAAQAJAAAHgEQAGgFADgJQADgJAAgNQAAgMgDgJQgDgJgHgFQgGgFgJAAQgIAAgGAFg");
	this.shape_7.setTransform(44.675,-41.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AA4BQIgDgBIgBgDIAAhwIgBgBIgBACIgpBwQgBADgDAAIgOAAQgEAAgBgDIgphvIgBgBIgBABIAABvIAAADIgDAAIgTAAQgEAAAAgEIAAiXQAAgEAEAAIAkAAIADABIACACIAmBlQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAAAIACgCIAlhkQABgEADAAIAmAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAACYQAAAEgFAAg");
	this.shape_8.setTransform(27.575,-43.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgdA0QgMgIgIgNQgHgNAAgRQAAgRAHgOQAIgNANgIQANgHAPAAQARAAANAHQANAIAHANQAHAOAAAQQAAASgHANQgIANgMAIQgNAHgRAAQgQAAgNgHgAgOgjQgHAFgDAJQgDAJAAAMQAAANADAJQADAJAHAFQAGAEAIAAQAJAAAHgEQAGgFADgJQADgJAAgNQAAgMgDgJQgDgJgHgFQgGgFgJAAQgIAAgGAFg");
	this.shape_9.setTransform(5.475,-41.525);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AArBQIgCAAIgDgCIhJhoIgBgBIgBABIAABnQAAADgEAAIgTAAQgEAAAAgDIAAiYQAAgEAEAAIAVAAIAEABIACACIBFBjQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAgBIAAhiQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAUAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAACZIgBACIgDABg");
	this.shape_10.setTransform(-9.675,-43.825);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgNAgIgCgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBIAKgYQACgEgEAAIgDAAQgEAAAAgDIAAgZQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAYAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXIAAADIgTAfIgDACIgDABg");
	this.shape_11.setTransform(130.475,-61.95);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AALBNQgNAAgIgHQgHgHAAgOIAAg/QAAgBgBgBQAAAAAAAAQgBgBAAAAQgBAAAAAAIgPAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAgOQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAgBQAAAAAAgBIACghQABgBAAgBQAAAAAAgBQABAAAAgBQABAAABAAIASAAQADAAAAAEIAAAhQAAABAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAZAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAOQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAIgZAAQAAAAAAAAQgBAAAAAAQAAABAAAAQAAABAAAAIAAA5QAAAIADAEQADADAIAAIANAAIABABIABACIAAALQAAAEgEAAIgHABIgJABg");
	this.shape_12.setTransform(122.8,-69.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgeA1QgNgHgFgKIgBgDIABgCIAMgGIAEgBIABABIAIAIQAEAEAGACQAGACAIAAQAHAAAFgCQAGgCADgDQADgDAAgEQAAgFgDgDQgEgDgKgDIgVgFQgQgEgIgGQgIgIAAgMQAAgLAGgIQAGgIALgFQAKgEAOAAQAQAAAMAFQALAGAGAJIABACQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgOAHIgCAAIgCgBQgFgFgGgEQgHgEgJAAQgJAAgGAEQgGAEgBAGQABAEACADQADADAJACIAZAHQAQAEAHAIQAIAJgBALQAAALgGAIQgGAIgMAEQgLAEgOAAQgSAAgNgGg");
	this.shape_13.setTransform(112.05,-67.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgbA0QgNgHgHgNQgIgNAAgRQAAgSAIgOQAHgOANgHQANgHAPAAQAQAAANAHQAMAHAHANQAHANAAASIAAAEQgBAAAAAAQAAABAAAAQgBAAAAAAQgBAAgBAAIhLAAIgCABIgBADQABAJAEAHQADAHAIAEQAHAEAIAAQAJAAAHgEQAHgEAGgIIACgBIADABIAMAGQABAAAAAAQABABAAAAQAAABAAAAQAAABgBABQgGAJgIAGQgIAFgIADQgKACgKAAQgQAAgNgHgAgMgkQgGAEgEAHQgDAHAAAIIAxAAIADAAIACgDQgBgGgDgHQgDgGgGgEQgFgFgJAAQgIAAgGAFg");
	this.shape_14.setTransform(99.8,-67.725);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgeA6IgDgBIgBgDIAAhqQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAVAAQAAAAABAAQABAAAAABQAAAAABAAQAAABAAABIAAANIABACQAAAAAAAAQABAAAAAAQAAAAAAgBQABAAAAAAQAEgGAFgFQAFgEAGgCQAGgCAFAAQAIAAAAADIAAAVQAAAAAAABQAAABAAAAQgBAAAAAAQgBAAgBAAIgHgBIgGAAQgEAAgFACQgFABgDADIgGAHQgCAEAAAEIAABBQAAAEgFAAg");
	this.shape_15.setTransform(88.875,-67.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgbA0QgNgHgIgNQgGgNAAgRQgBgSAIgOQAIgOANgHQANgHAOAAQARAAALAHQANAHAHANQAGANABASIAAAEQgBAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIhMAAIgCABIAAADQAAAJADAHQAFAHAHAEQAHAEAHAAQAJAAAIgEQAHgEAHgIIABgBIACABIAOAGQAAAAAAAAQABABAAAAQAAABAAAAQgBABAAABQgGAJgIAGQgHAFgKADQgIACgLAAQgQAAgNgHgAgMgkQgHAEgDAHQgDAHAAAIIAyAAIADAAIAAgDQAAgGgCgHQgEgGgFgEQgHgFgIAAQgIAAgGAFg");
	this.shape_16.setTransform(77.25,-67.725);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AALBNQgNAAgIgHQgHgHAAgOIAAg/QAAgBgBgBQAAAAAAAAQgBgBAAAAQgBAAAAAAIgPAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAgOQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAQAAQAAAAABAAQAAAAABAAQAAAAAAgBQAAAAAAgBIACghQABgBAAgBQAAAAAAgBQABAAAAgBQABAAABAAIASAAQADAAAAAEIAAAhQAAABAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAYAAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAOQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAIgZAAQAAAAAAAAQgBAAAAAAQAAABAAAAQgBABAAAAIAAA5QABAIADAEQADADAIAAIAMAAIACABIABACIAAALQAAAEgEAAIgIABIgIABg");
	this.shape_17.setTransform(65.75,-69.675);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAaA6IgCgBIgBgDIAAhJQAAgIgEgFQgFgFgJAAQgFAAgEACIgIAFIgKAIIAABMQAAAEgFAAIgTAAQgEAAAAgEIAAhqQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAWAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAABIAAALIAAACIACgBIAMgJQAGgEAFgCQAHgCAGAAQARAAAJAJQAJAJAAAPIAABOQAAAEgEAAg");
	this.shape_18.setTransform(54.45,-67.825);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgLBQIgDgBIgBgDIAAiXQAAgEADAAIAZAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAACYIgBADIgEABg");
	this.shape_19.setTransform(44.2,-70.025);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgdA0QgMgIgIgNQgHgNAAgRQAAgRAHgOQAIgNANgIQANgHAPAAQARAAANAHQANAIAHANQAHAOAAAQQAAASgHANQgIANgMAIQgNAHgRAAQgQAAgNgHgAgOgjQgHAFgDAJQgDAJAAAMQAAANADAJQADAJAHAFQAGAEAIAAQAJAAAHgEQAGgFADgJQADgJAAgNQAAgMgDgJQgDgJgHgFQgGgFgJAAQgIAAgGAFg");
	this.shape_20.setTransform(28.875,-67.725);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AArBQIgCAAIgDgCIhJhoIgBgBIgBABIAABnQAAADgEAAIgTAAQgEAAAAgDIAAiYQAAgEAEAAIAVAAIAEABIACACIBFBjQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAgBIAAhiQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAUAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAACZIgBACIgDABg");
	this.shape_21.setTransform(13.725,-70.025);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgNAgIgCgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAgBIAKgYQACgEgEAAIgDAAQgEAAAAgDIAAgZQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAYAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXIAAADIgTAfIgDACIgDABg");
	this.shape_22.setTransform(141.625,-88.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgeA1QgNgHgFgKIgBgDIABgCIAMgGIAEgBIABABIAIAIQAEAEAGACQAGACAIAAQAHAAAFgCQAGgCADgDQADgDAAgEQAAgFgDgDQgEgDgKgDIgVgFQgQgEgIgGQgIgIAAgMQAAgLAGgIQAGgIALgFQAKgEAOAAQAQAAAMAFQALAGAGAJIABACQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgOAHIgCAAIgCgBQgFgFgGgEQgHgEgJAAQgJAAgGAEQgGAEgBAGQABAEACADQADADAJACIAZAHQAQAEAHAIQAIAJgBALQAAALgGAIQgGAIgMAEQgLAEgOAAQgSAAgNgGg");
	this.shape_23.setTransform(132.75,-93.925);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAMBNQgOAAgIgHQgIgHABgOIAAg/QAAgBgBgBQAAAAAAgBQgBAAAAAAQgBAAgBAAIgOAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBgBAAAAIAAgOQAAgBABAAQAAgBAAAAQABAAAAgBQABAAABAAIAQAAQABAAAAAAQAAAAAAAAQABAAAAgBQAAAAAAgBIADghQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAAAAAIATAAQADAAAAAEIAAAhQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABAAIAZAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAAOQgBAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAIgYAAQgBAAAAAAQgBAAAAAAQAAABAAAAQAAABAAAAIAAA5QgBAIAEAEQADADAHAAIAOAAIACABIABACIgBALQAAAEgEAAIgHABIgJABg");
	this.shape_24.setTransform(121.6,-95.875);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AAbA6IgDgBIgBgDIAAhJQAAgIgFgFQgEgFgJAAQgFAAgEACIgIAFIgKAIIAABMQAAAEgFAAIgTAAQgEAAAAgEIAAhqQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAVAAQABAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAAALIABACIACgBIAMgJQAGgEAFgCQAGgCAIAAQAQAAAJAJQAJAJAAAPIAABOQAAAEgFAAg");
	this.shape_25.setTransform(110.3,-94.025);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgbA0QgNgHgHgNQgIgNAAgRQAAgSAIgOQAHgOANgHQANgHAPAAQAQAAANAHQAMAHAHANQAHANAAASIAAAEQgBAAAAAAQAAABAAAAQgBAAAAAAQgBAAgBAAIhLAAIgCABIgBADQABAJAEAHQADAHAIAEQAHAEAIAAQAJAAAHgEQAHgEAGgIIACgBIADABIAMAGQABAAAAAAQABABAAAAQAAABAAAAQAAABgBABQgGAJgIAGQgIAFgIADQgKACgKAAQgQAAgNgHgAgMgkQgGAEgEAHQgDAHAAAIIAxAAIADAAIACgDQgBgGgDgHQgDgGgGgEQgFgFgJAAQgIAAgGAFg");
	this.shape_26.setTransform(97.1,-93.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AA9A6IgCAAIgBgDIAAhKQAAgIgEgEQgFgFgIgBQgFAAgFADIgIAEIgGAGIgCACIgBAEIAABIQAAAEgEAAIgTAAIgDAAQAAgBAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAhKQAAgIgEgEQgEgFgJgBQgHAAgGAFQgGADgIAHIAABMQAAAEgFAAIgTAAQgEAAAAgDIAAhqQAAgBAAgBQABgBAAAAQAAgBABAAQABAAAAAAIAWAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAMIAAABIACgBIAMgJQAGgEAGgCQAGgCAHgBQAMABAHAFQAIAGADAIIABABIACgBIALgKIANgHQAHgCAHAAQAPAAAJAJQAJAJAAAQIAABNQAAAEgFAAg");
	this.shape_27.setTransform(80.425,-94.05);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AguBLQgBgBAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgPIABgBIAFgBIAPAAQAEAAADgDIAGgGIADgHQABgEgBgDIgqhlIAAgEQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAXAAIADABIABACIAaBHQAAAAAAAAQABABAAAAQAAAAAAAAQAAABABAAQAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAABAAIAahHIACgCIACgBIAQAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAABAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAAAABIguBwQgEAKgEAGQgEAHgFADQgFADgHACIgQABg");
	this.shape_28.setTransform(63.9875,-92.15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgoAzQgKgJAAgOQAAgMAHgJQAIgHANgFQANgFATgBIALgBIACgBIABgCIAAgFQAAgKgGgFQgFgFgKAAQgGAAgHADQgHADgEAIIgCACIgDAAIgSgFIgCgBIABgEQAGgMAMgGQAOgGARAAQAQAAALAEQALAFAEAIQAFAIAAALIAABLIgBADQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAIgSAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgBgEIAAgGQgBgEgEADQgHAHgIAEQgJADgKAAQgRAAgJgIgAAMACIgNACIgKAEQgFADgDAEQgDAEAAAFQgBAIAGAEQAFAEAJAAQAFAAAFgCIAJgEIAGgHQACgDAAgEIAAgPQAAgBAAgBQAAAAgBgBQAAAAgBgBQAAAAgBAAg");
	this.shape_29.setTransform(51.1,-93.925);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("Ag6BQIgDgBIgBgDIAAiXQAAgEAEAAIA8AAQARAAAOAFQAOAFAIALQAIALAAARQAAAQgHAKQgIAKgNAGQgMAFgSAAIghAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAABAAAAIAAA5QAAAEgFAAgAgeg0IAAArQAAABAAABQAAAAABABQAAAAABABQAAAAABAAIAcAAQANAAAJgHQAHgGABgNQAAgJgFgFQgDgGgHgCQgHgDgJAAIgbAAQAAAAgBAAQgBABAAAAQgBABAAAAQAAABAAABg");
	this.shape_30.setTransform(37.7,-96.225);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgdA0QgMgIgIgNQgHgNAAgRQAAgRAHgOQAIgNANgIQANgHAPAAQARAAANAHQANAIAHANQAHAOAAAQQAAASgHANQgIANgMAIQgNAHgRAAQgQAAgNgHgAgOgjQgHAFgDAJQgDAJAAAMQAAANADAJQADAJAHAFQAGAEAIAAQAJAAAHgEQAGgFADgJQADgJAAgNQAAgMgDgJQgDgJgHgFQgGgFgJAAQgIAAgGAFg");
	this.shape_31.setTransform(17.675,-93.925);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AArBQIgCAAIgDgCIhJhoIgBgBIgBABIAABnQAAADgEAAIgTAAQgEAAAAgDIAAiYQAAgEAEAAIAVAAIAEABIACACIBFBjQAAAAAAABQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAgBQAAAAAAgBIAAhiQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAUAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAACZIgBACIgDABg");
	this.shape_32.setTransform(2.525,-96.225);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgeA1QgNgHgFgKIgBgDIABgCIAMgGIAEgBIABABIAIAIQAEAEAGACQAGACAIAAQAHAAAFgCQAGgCADgDQADgDAAgEQAAgFgDgDQgEgDgKgDIgVgFQgQgEgIgGQgIgIAAgMQAAgLAGgIQAGgIALgFQAKgEAOAAQAQAAAMAFQALAGAGAJIABACQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAIgOAHIgCAAIgCgBQgFgFgGgEQgHgEgJAAQgJAAgGAEQgGAEgBAGQABAEACADQADADAJACIAZAHQAQAEAHAIQAIAJgBALQAAALgGAIQgGAIgMAEQgLAEgOAAQgSAAgNgGg");
	this.shape_33.setTransform(128.7,-120.075);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAaBQIgCgBIgBgDIAAhKQAAgHgFgFQgEgFgJAAQgFAAgDACIgJAFIgKAIIAABMQAAAEgFAAIgTAAQgEAAAAgEIAAiXQAAgEAEAAIAUAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAA4IAAACIACgBIANgJIALgGIAMgBQASAAAIAJQAJAJAAAQIAABNQAAAEgFAAg");
	this.shape_34.setTransform(116.35,-122.375);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAMBNQgOAAgIgHQgIgHAAgOIAAg/QAAgBAAgBQAAAAAAAAQgBgBAAAAQgBAAAAAAIgPAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgOQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAABAAIAQAAQABAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIADghQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAABAAIASAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAABIAAAhQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABAAIAYAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIAAAOQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgYAAQgBAAAAAAQgBAAAAAAQAAABAAAAQgBABAAAAIAAA5QAAAIAEAEQADADAIAAIAMAAIADABIABACIgBALQAAAEgEAAIgIABIgIABg");
	this.shape_35.setTransform(104.2,-122.025);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAaA6IgCgBIgBgDIAAhJQAAgIgFgFQgEgFgJAAQgFAAgEACIgIAFIgKAIIAABMQAAAEgFAAIgTAAQgEAAAAgEIAAhqQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAVAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAAALIAAACIACgBIAMgJQAGgEAFgCQAHgCAGAAQARAAAJAJQAJAJAAAPIAABOQAAAEgFAAg");
	this.shape_36.setTransform(92.95,-120.175);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgdA0QgMgIgIgNQgHgNAAgRQAAgRAHgOQAIgNANgIQANgHAPAAQARAAANAHQANAIAHANQAHAOAAAQQAAASgHANQgIANgMAIQgNAHgRAAQgQAAgNgHgAgOgjQgHAFgDAJQgDAJAAAMQAAANADAJQADAJAHAFQAGAEAIAAQAJAAAHgEQAGgFADgJQADgJAAgNQAAgMgDgJQgDgJgHgFQgGgFgJAAQgIAAgGAFg");
	this.shape_37.setTransform(79.525,-120.075);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AA4BQIgDgBIgBgDIAAhwIgBgBIgBACIgpBwQgBADgDAAIgOAAQgEAAgBgDIgphvIgBgBIgBABIAABvIAAADIgDAAIgTAAQgEAAAAgEIAAiXQAAgEAEAAIAkAAIADABIACACIAmBlQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAAAIACgCIAlhkQABgEADAAIAmAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAACYQAAAEgFAAg");
	this.shape_38.setTransform(62.425,-122.375);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("Ag1BRIgDgBQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAAgOIAAgCIADgEIAFgFIAqgnIAQgPIAKgLQAEgGABgEQACgFAAgFQAAgIgEgFQgEgFgGgDQgGgDgGAAQgGAAgGADQgGACgFAFQgGAEgEAJIgCABIgEgBIgQgIQAAgBgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQALgRAPgHQAOgIARAAQAQAAANAFQAMAGAHAKQAIALAAAPQAAAJgDAIQgEAIgHAIQgHAIgMAKIgoAiIgBACIACABIBGAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAUIgBACIgDABg");
	this.shape_39.setTransform(39.925,-122.475);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgoBQQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAgSQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAYAAQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIAAhjQAAgBAAgBQAAAAgBAAQAAgBAAAAQgBAAAAAAIgYAIQgDABAAgFIAAgMIAAgDIACgBIAjgSIAEgCIADAAIANAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAACCQAAABAAAAQAAABAAAAQABAAAAAAQABAAAAAAIAWAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAASIgBACIgDABg");
	this.shape_40.setTransform(27.4,-122.375);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgFAzQgEAAAAgFIAAgjIAUAAIAAAlQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAgAALALIAAgUIAlAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABABABIAAAMQgBAFgEAAgAALALgAALALIgUAAIAAgUIAAglIAAgDIAEgBIAMAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIAAAmIgUAAIAUAAIAAAUgAgJALIglAAIgCgBIgBgDIAAgNQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIAmAAIAAAUgAALgJg");
	this.shape_41.setTransform(10.25,-122.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70.4,-137,280,108.3);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6CC14C").s().p("AhfDJQgrgbgYg0QgXgzAAhEQAAg0ANgrQAOgqAagfQAZgfAigQQAigRAnAAQAoAAAjARQAhAQAZAfQAaAfAOAqQAOArgBAzQAABFgYAzQgYA0gqAbQgqAcg2AAQg1AAgqgcgAgqiLQgSAQgJAjQgJAjAAA4QAAA3AJAhQAJAiASAOQARAPAZABQAagBASgPQASgOAIgiQAJghAAg3QAAg5gJgiQgJgjgSgQQgRgQgaAAQgZAAgRAQg");
	this.shape.setTransform(71,50.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#6CC14C").s().p("AAaDfQgNABABgMIAAhYQAAgGgHAAIi0AAQgNAAAAgLIAAgxIAEgOIAMgRIC0juIALgJIAOgDIBMAAQAJAAAAAMIAAD7QAAAGAGAAIAyAAQALABAAAIIAAA0QAAALgMAAIgwAAQgHAAAAAHIAABUQAAAOgPAAgAAGhtIhrCTQgGAIAKAAIBpAAQAHAAAAgDIAAiWIgCgIg");
	this.shape_1.setTransform(26.35,51);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6CC14C").s().p("Ag6BbIgEgBIgBgFIAAiqQAAgFAEABIB4AAQADAAAAADIAAAXQAAAFgFAAIhLAAQgEAAAAAEIAAAmQAAADADAAIA0AAQAEAAAAAEIAAAWQAAAEgEAAIg0AAQgBAAgBAAQAAAAgBABQAAAAAAABQAAAAAAABIAABBQAAAFgHABg");
	this.shape_2.setTransform(135.075,64.65);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC14C").s().p("Ag6BbIgEgBIgBgFIAAiqQAAgFAEABIB4AAQADAAAAADIAAAXQAAAFgFAAIhLAAQgEAAAAAEIAAAmQAAADADAAIA0AAQAEAAAAAEIAAAWQAAAEgEAAIg0AAQgBAAgBAAQAAAAAAABQgBAAAAABQAAAAAAABIAABBQAAAFgHABg");
	this.shape_3.setTransform(119.725,64.65);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6CC14C").s().p("AgrBSQgUgLgKgVQgJgVgBgcQAAgcALgWQAKgUATgLQATgMAYAAQAaAAASAMQATALAKAUQALAWAAAcQAAAcgLAVQgKAUgTAMQgSALgaAAQgZAAgSgLgAgdguQgJAPAAAgQAAAhAJAOQAKAPATAAQAUAAAKgPQAIgOABghQAAgggKgQQgJgPgUAAQgTAAgKAQg");
	this.shape_4.setTransform(102.15,64.65);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6CC14C").s().p("AAkBWQgKgGgGgMQgHgMAAgOQAAgPAHgLQAGgMAKgFQALgIANAAQANAAAKAIQAKAFAGAMQAGALAAAPQAAAOgGAMQgGAMgKAGQgKAHgNAAQgNAAgLgHgAAxAOQgEADgCAIQgCAHAAAKQAAAKACAHQACAHAEAEQAEAEAGAAQAHAAAEgEQAEgEACgHQACgHAAgKQAAgKgCgHQgDgIgEgEQgEgDgGgBQgGAAgEAFgAhABbQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAIBziuIADgCIADAAIANAAIACABQAAAAABAAQAAAAAAABQAAAAgBABQAAAAAAABIh0CwQgCACgFAAgAhSADQgLgGgGgMQgFgLAAgOQAAgPAGgLQAGgMAKgHQALgHANAAQANAAAKAHQAKAHAGAMQAGALAAAPQAAAOgGALQgGAMgKAGQgKAGgNAAQgOAAgKgGgAhFhFQgEAEgCAIQgCAGAAALQAAAKACAGQACAIAEAEQAEADAGAAQAKAAAEgIQAFgJAAgOQAAgQgFgIQgEgJgKAAQgGAAgEAEg");
	this.shape_5.setTransform(104.225,37.95);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6CC14C").s().p("AhPCTQgigUgSglQgSglAAg0QAAgzATgmQASgmAigUQAigUAtAAQAtAAAiAUQAhAUATAmQASAmAAAzQAAAzgSAlQgSAmgiAUQgiAUgtAAQguAAgigUgAg0hVQgRAcAAA7QAAA7ARAaQARAaAkAAQAkAAAQgaQARgaAAg7QAAg8gRgbQgRgcgjAAQgjAAgSAcg");
	this.shape_6.setTransform(123.625,1.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6CC14C").s().p("AhKCSQghgUgSglQgSgmAAgyQAAgyATgmQATgmAhgVQAigUAtAAQAjAAAcANQAdAOARAVQARAVAFAYIABAJQgCACgFABIg5AIQgEAAgBgBIgCgGQgDgOgIgMQgIgMgNgHQgNgHgSAAQgUAAgQALQgPALgJAZQgIAZAAAoQAAApAIAZQAKAZAPALQAQALAVAAQAOAAALgEQALgEAIgHQAHgHAGgJQAEgJACgKIABgNQACgGgGAAIg2AAIgFgCIgBgGIAAggQAAgGAGAAIB2AAQAGAAADACQAEADAAAFIAACUIgCAFIgFACIgOAAIgGgCIgFgFIgNggIgCgBIgCACQgJAKgLAKQgMAJgRAHQgSAGgZAAQgsAAghgVg");
	this.shape_7.setTransform(90,1.075);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6CC14C").s().p("AhPCTQgigUgSglQgSglAAg0QAAgzATgmQASgmAigUQAigUAtAAQAtAAAiAUQAhAUATAmQASAmAAAzQAAAzgSAlQgSAmgiAUQgiAUgtAAQguAAgigUgAg0hVQgRAcAAA7QAAA7ARAaQARAaAkAAQAkAAAQgaQARgaAAg7QAAg8gRgbQgRgcgjAAQgjAAgSAcg");
	this.shape_8.setTransform(56.675,1.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6CC14C").s().p("Ah9CjQgEAAgCgCIgCgGIAAk0QAAgDACgDQADgDAEAAIB3AAQA/AAAiAWQAiAWAAAqQAAAYgNAQQgNARgfAOIgCACIACACQAiAKAQASQAPASAAAdQAAAugiAWQgiAVhCAAgAg4AhIAABGQAAAIAGAAIAwAAQAcAAAOgMQAOgLAAgUQAAgOgHgKQgHgJgMgFQgMgFgQAAIgwAAQgIAAAAAIgAg4hmIAABCQAAAJAGgBIAyAAIATgBQAJgCAHgGQAHgGAEgGQAEgIAAgKQAAgVgPgLQgPgLgXAAIgtAAQgIAAAAAIg");
	this.shape_9.setTransform(24.475,1.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#47C434").s().p("AgDAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgUIANAAIgNAAIAAgNIANAAIAAANIAAAVQAAABAAAAQgBAAAAAAQAAABAAAAQgBAAAAAAgAAHAHIAAgNIgNAAIAAgUIABgCIACgBIAIAAQAAAAABAAQAAABAAAAQAAAAABAAQAAABAAAAIAAAVIAVAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAgAgaAHIgCgBIgBgBIAAgIQAAgBAAAAQABgBAAAAQAAAAAAgBQABAAAAAAIAVAAIAAANgAgGAHg");
	this.shape_10.setTransform(74.575,88.975);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#48C435").ss(1,1,1).p("ABgAAIJYAAAq3AAIJYAA");
	this.shape_11.setTransform(73.55,89.15);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AALBOQgOAAgHgHQgIgHAAgOIAAhAQAAgBAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAIgOAAQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgOQAAgBAAAAQAAgBABAAQAAAAABAAQAAgBABAAIARAAQAAAAAAAAQABAAAAAAQAAAAAAgBQABAAAAgBIACgiQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIASAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAiQAAAAAAABQAAAAABABQAAAAAAAAQABAAAAAAIAZAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAOQAAABAAABQAAAAgBABQAAAAgBAAQgBAAAAAAIgaAAQAAAAAAABQgBAAAAAAQAAAAAAABQAAAAAAABIAAA5QAAAJADAEQAEADAHAAIANAAIACABIABACIgBAMQAAADgDABIgIAAIgJABg");
	this.shape_12.setTransform(174.1,114.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgJBSIgEgBIAAgDIAAhsQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAABAAIAVAAQABAAABAAQAAABAAAAQABABAAAAQAAABAAABIAABrIgBAEIgEABgAgKgyQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAIgBgEIAAgVQAAgFAEAAIAVAAQAEAAAAAEIAAAWQAAAFgGAAg");
	this.shape_13.setTransform(166.825,113.925);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAbA8IgDgBIgBgEIAAhKQAAgIgEgGQgFgEgJAAQgFAAgEABQgEACgFAEIgJAIIAABNQAAAFgFAAIgUAAQgEAAAAgFIAAhsQAAAAAAgBQABgBAAAAQAAgBABAAQABAAAAAAIAWAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAALIABADIACgCIAMgJQAGgEAFgCQAGgDAIAAQAQAAAKAKQAJAKAAAPIAABPQAAAFgFAAg");
	this.shape_14.setTransform(157.575,116.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgkBMQgOgIgGgOQgGgOAAgWIAAhgQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAABAAIAaAAQABAAABAAQAAABAAAAQABABAAAAQAAABAAABIAABlQAAATAJAJQAIAIAPAAQALAAAIgDQAHgEAEgIQAFgIAAgNIAAhlQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAABAAIAUAAQADAAAAAEIAABkQAAAWgHAOQgIANgOAGQgOAGgUAAQgWAAgOgHg");
	this.shape_15.setTransform(143.125,114.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgvBMQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgPIABgCIAGgBIAOAAQAEAAAEgCIAGgGIADgIQABgDgBgEIgrhmQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAQABgBABAAIAXAAIACABIACADIAaBIQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAABAAQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAbhIIACgDIACgBIAQAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABIguBzQgFAKgEAGQgEAGgFAEQgGADgGACQgHACgKgBg");
	this.shape_16.setTransform(124.6417,118.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgfA8IgDgBIgBgEIAAhsQAAAAAAgBQABgBAAAAQAAgBABAAQAAAAABAAIAVAAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIAAAOIAAACIADgCQAEgGAFgFIALgGQAGgDAGAAQAIAAAAAEIAAAVQAAABAAABQgBAAAAABQAAAAgBAAQgBAAAAAAIgHgBIgHgBIgJACIgJAFIgFAHQgCAEAAAEIAABCQAAAFgFAAg");
	this.shape_17.setTransform(113.825,116.15);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgbA1QgOgHgHgNQgIgOAAgRQAAgTAIgNQAIgOANgIQANgHAPgBQARAAAMAIQANAHAHAOQAHAOAAARIgBAEQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAIhNAAIgCABIAAACQAAAJAEAIQAEAHAIADQAHAFAIAAQAJAAAHgEQAHgDAHgJIACgBIACABIANAGQABAAAAAAQABABAAAAQAAABAAAAQgBABAAABQgHAJgHAGQgIAGgJACQgJACgMABQgPgBgNgHgAgMglQgHAFgDAGQgEAIAAAJIAzAAIADgBIABgCQAAgIgDgGQgDgGgGgFQgGgFgJAAQgIAAgGAFg");
	this.shape_18.setTransform(102.525,116.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgGA6QgEAAgCgEIgshrQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIADgBIAXAAIADABIACACIAbBHQABAEADgEIAchHIABgCIADgBIAQAAIADABIAAADIgsBrQgCAEgFAAg");
	this.shape_19.setTransform(89.8625,116.275);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("Ag1BSQgEAAAAgEIAAibQAAgBAAgBQABAAAAgBQAAAAABgBQABAAAAAAIBqAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAARQAAAEgEAAIhIAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABAAABIAAAmQAAABAAABQAAAAABABQAAAAAAABQABAAABAAIAxAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAARIAAACIgDAAIgxAAQgBAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABIAAApQAAABAAAAQAAABAAAAQABAAAAABQABAAAAAAIBMAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAAARIgBADIgDABg");
	this.shape_20.setTransform(77.025,113.925);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgNBSQAAAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAhaQAAAAAAgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgOIABgCIADgBIAQAAQABAAAAAAQABAAAAgBQAAAAAAAAQAAgBAAgBIAAgOQAAgOAJgIQAHgIAOAAIAVAAQAEAAAAAEIAAANIgBACIgCABIgNAAQgFAAgDAEQgEAEAAAGIAAALQAAAAABABQAAAAAAABQAAAAABAAQAAAAABAAIAVAAIACABIABACIAAAOQAAABAAABQAAAAgBAAQAAABgBAAQgBAAAAAAIgUAAQgBAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAABaQAAAEgDAAg");
	this.shape_21.setTransform(60.7,113.925);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgMBSQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhaQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgOIAAgCIADgBIARAAQABAAAAAAQABAAAAgBQAAAAAAAAQABgBAAgBIAAgOQAAgOAHgIQAIgIAOAAIAUAAQAFAAAAAEIAAANIAAACIgDABIgNAAQgGAAgCAEQgDAEAAAGIAAALQAAAAAAABQAAAAAAABQAAAAABAAQAAAAABAAIAUAAIADABIABACIAAAOQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgTAAQgBAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAABaQAAAEgDAAg");
	this.shape_22.setTransform(50.75,113.925);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgmBKQgRgKgIgTQgJgSAAgaQAAgaAJgTQAJgSAQgLQARgKAVAAQAXAAAQAKQAQALAJASQAJATAAAaQAAAagIASQgJATgRAKQgQAKgXAAQgVAAgRgKgAgdgtQgJAPAAAfQAAAfAJAOQAKAPATAAQAUAAAKgPQAJgOAAgfQAAgfgJgPQgKgPgUAAQgTAAgKAPg");
	this.shape_23.setTransform(37.925,113.925);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AghBKQgPgKgIgTQgJgSAAgaQAAgTAFgPQAFgQAJgLQAJgLAMgGQAMgGANAAQAOAAAMAGQAMAGAJALQAJALAFAPQAFAQAAATQAAAagJASQgIATgPAKQgPAKgTAAQgSAAgPgKgAgRg2QgHAHgEANQgEAOAAAVQAAAVAEANQAEANAHAGQAIAGAJAAQALAAAHgGQAHgGAEgNQAEgNAAgVQAAgVgEgOQgEgNgHgHQgIgGgKAAQgJAAgIAGg");
	this.shape_24.setTransform(17.225,113.925);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AghBKQgPgKgIgTQgJgSAAgaQAAgTAFgPQAFgQAJgLQAJgLAMgGQAMgGANAAQAOAAAMAGQAMAGAJALQAJALAFAPQAFAQAAATQAAAagJASQgIATgPAKQgPAKgTAAQgSAAgPgKgAgRg2QgHAHgEANQgEAOAAAVQAAAVAEANQAEANAHAGQAIAGAJAAQALAAAHgGQAHgGAEgNQAEgNAAgVQAAgVgEgOQgEgNgHgHQgIgGgKAAQgJAAgIAGg");
	this.shape_25.setTransform(0.925,113.925);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgpBSQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBgBAAAAIAAgTQAAAAABgBQAAgBAAAAQABAAAAgBQABAAABAAIAZAAQAAAAAAAAQABAAAAAAQAAAAAAgBQABAAAAAAIAAhlQAAgBgBgBQAAAAAAAAQAAgBgBAAQAAAAgBABIgXAHQgEABgBgEIAAgNIABgDIADgBIAjgSIAEgCIADgBIANAAQABAAABAAQAAABAAAAQABABAAAAQAAABAAABIAACEQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABAAIAXAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIAAASIgCADIgCABg");
	this.shape_26.setTransform(-12.15,113.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgDBiQgBAAAAAAQgBAAgBgBQAAAAAAgBQAAAAAAgBIAAgLIgBgCIgCgBQgRAAgMgGQgMgFgJgKQgFgEADgDIALgLIADgCIADACQAHAHAIAFQAIAFAMABQAAAAABAAQAAAAABAAQAAgBAAAAQABAAAAgBIAAgrIgBgDIgDgCQgRgFgLgGQgKgGgFgJQgEgJAAgLQAAgMAGgJQAFgKALgGQALgHAOgCIADgBIABgCIAAgJIABgDIABAAIAMAAIADABIABADIAAAJQAAABAAAAQAAAAAAAAQABABAAAAQAAAAABAAQAMACAKAEQAJAFAIAGQADACgCADIgLANIgCABIgDgBQgEgFgGgDQgGgEgIgBIgCAAIAAACIAAArQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAIALADQAMAEAIAFQAJAHAFAJQAEAIAAALQAAANgGAKQgGAKgKAGQgLAGgPABIgDABIAAACIAAAKQAAAEgFAAgAAMASIAAApQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAQALgBAHgGQAGgGAAgIQAAgIgFgGQgGgGgMgDIgDgBIAAADgAgJg9QgLABgGAHQgGAGAAAIQAAAFACAEIAHAHQAEADAIADIAEAAIABgEIAAgmQAAAAgBgBQAAAAAAgBQAAAAAAAAQgBAAAAAAIgBAAg");
	this.shape_27.setTransform(-24.71,114.075);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgLBSQgEAAAAgEIAAgZQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAZAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAYQAAAFgGAAgAgEAjQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAAAIgCgDIgHhsIABgDIACgBIAbAAQABAAAAAAQABABAAAAQAAABAAAAQABABgBABIgHBrIgBAEIgEABg");
	this.shape_28.setTransform(178.8536,-45.825);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgbA1QgOgHgHgNQgIgOAAgRQAAgTAIgNQAIgOANgIQANgHAPgBQARAAAMAIQANAHAHAOQAHAOAAARIgBAEQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAIhNAAIgCABIAAACQAAAJAEAHQAEAIAIADQAHAFAIAAQAJAAAHgEQAHgDAHgJIACgBIACABIANAGQABAAAAAAQABABAAAAQAAABAAAAQgBABAAABQgHAJgHAGQgIAGgJACQgJACgMABQgPgBgNgHgAgMglQgHAFgDAGQgEAHAAAKIAzAAIADgBIABgCQAAgIgDgGQgDgGgGgFQgGgFgJAAQgIAAgGAFg");
	this.shape_29.setTransform(169.725,-43.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgJBSQgEAAgBgEIABibQAAgEAEAAIAVAAQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABIAACaIgBAEIgDABg");
	this.shape_30.setTransform(160.4,-45.825);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgpA0QgKgJAAgPQAAgMAHgIQAIgJAOgFQAOgEASgBIALgBIACgBIABgDIAAgEQAAgKgFgGQgGgFgKAAQgGAAgIAEQgGADgFAHIgBACIgEAAIgSgEIgCgBIABgEQAGgNANgGQANgHASAAQARABALAEQAKAFAFAIQAFAJAAALIAABMIgBAEIgDABIgSAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAIgBgEIAAgHQAAAAAAgBQgBAAAAAAQgBAAgBAAQAAABgBAAQgHAHgJAEQgJADgKABQgSAAgJgJgAAMACQgHABgGACIgLADQgFAEgDAEQgDADABAGQAAAHAEAFQAGAEAJABQAGAAAEgCQAFgDAEgCIAGgHQADgDgBgEIAAgQQAAgBAAgBQAAAAAAgBQgBAAAAAAQgBgBgBAAg");
	this.shape_31.setTransform(151.1,-43.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgZBRQgMgEgKgGQgJgGgGgJIgBgDIACgDIAOgKIAEgBIADABQAFAHAGAFQAFAFAHACQAHACAKAAQAPAAAJgFQAJgGAAgKQAAgFgCgEQgCgDgEgDQgEgDgIgDIghgKQgMgEgJgGQgIgGgEgJQgEgJAAgKQAAgOAHgKQAIgLANgHQAOgGARAAQAMAAALADQAKADAJAFQAIAFAGAHIABACQAAABAAAAQAAAAAAABQgBAAAAABQAAAAAAAAIgQAMIgCAAIgDgCQgFgGgIgEQgIgEgNAAQgOAAgHAFQgIAGAAAKIABAGQACAEAEADQAEADAIADIAhAKQAVAGAIALQAJAMAAAPQAAAPgHALQgIALgOAGQgOAGgUAAQgNAAgNgDg");
	this.shape_32.setTransform(137.9917,-45.825);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgfA8IgDgBIgBgEIAAhsQAAAAAAgBQABgBAAAAQAAgBABAAQAAAAABAAIAVAAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIAAAOIAAACIADgCQAEgGAFgFIALgGQAGgDAGAAQAIAAAAAEIAAAVQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgHgBIgHgBIgJACIgJAFIgFAHQgCAEAAAEIAABCQAAAFgFAAg");
	this.shape_33.setTransform(122.175,-43.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgbA1QgOgHgHgNQgIgOAAgRQAAgTAIgNQAIgOANgIQANgHAPgBQARAAAMAIQANAHAHAOQAHAOAAARIgBAEQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAIhNAAIgCABIAAACQAAAJAEAHQAEAIAIADQAHAFAIAAQAJAAAHgEQAHgDAHgJIACgBIACABIANAGQABAAAAAAQABABAAAAQAAABAAAAQgBABAAABQgHAJgHAGQgIAGgJACQgJACgMABQgPgBgNgHgAgMglQgHAFgDAGQgEAHAAAKIAzAAIADgBIABgCQAAgIgDgGQgDgGgGgFQgGgFgJAAQgIAAgGAFg");
	this.shape_34.setTransform(110.875,-43.5);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AA+A8IgCgBIgBgEIAAhKQAAgIgFgGQgEgEgIAAQgGAAgEABIgJAGIgGAFIgCADIgBAEIAABJQAAAFgEAAIgUAAIgCgBQgBgBAAAAQAAAAAAAAQAAgBAAAAQAAgBAAgBIAAhKQAAgIgFgGQgEgEgJAAQgHAAgGADQgHAFgHAHIAABNQAAAFgFAAIgTAAQgEAAAAgFIAAhsQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAVAAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIAAALIAAADIACgCIAMgJQAGgEAGgCQAGgDAHAAQANAAAHAGQAIAGADAJIABABIACgCIAMgKQAGgEAHgCQAHgDAHgBQAPAAAJAKQAJAKAAAPIAABPQAAAFgEAAg");
	this.shape_35.setTransform(94.425,-43.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AA+A8IgCgBIgBgEIAAhKQAAgIgFgGQgEgEgIAAQgGAAgEABIgJAGIgGAFIgCADIgBAEIAABJQAAAFgEAAIgUAAIgCgBQgBgBAAAAQAAAAAAAAQAAgBAAAAQAAgBAAgBIAAhKQAAgIgFgGQgEgEgJAAQgHAAgGADQgHAFgHAHIAABNQAAAFgFAAIgTAAQgEAAAAgFIAAhsQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAVAAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIAAALIAAADIACgCIAMgJQAGgEAGgCQAGgDAHAAQANAAAHAGQAIAGADAJIABABIACgCIAMgKQAGgEAHgCQAHgDAHgBQAPAAAJAKQAJAKAAAPIAABPQAAAFgEAAg");
	this.shape_36.setTransform(74.325,-43.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgiA3QgHgEgFgIQgEgIAAgKIAAhPQAAgEAEAAIAVAAQADAAAAAEIAABKQAAAIAFAFQAEAGAJAAQAGAAAIgFQAGgEAHgHIAAhNQAAgEAFAAIAUAAQADAAAAAEIAABsQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgVAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAgMIAAgBIgBABQgLAJgJAEQgJAEgJAAQgKAAgIgEg");
	this.shape_37.setTransform(57.7,-43.375);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgZBRQgMgEgKgGQgJgGgGgJIgBgDIACgDIAOgKIAEgBIADABQAFAHAGAFQAFAFAHACQAHACAKAAQAPAAAJgFQAJgGAAgKQAAgFgCgEQgCgDgEgDQgEgDgIgDIghgKQgMgEgJgGQgIgGgEgJQgEgJAAgKQAAgOAHgKQAIgLANgHQAOgGARAAQAMAAALADQAKADAJAFQAIAFAGAHIABACQAAABAAAAQAAAAAAABQgBAAAAABQAAAAAAAAIgQAMIgCAAIgDgCQgFgGgIgEQgIgEgNAAQgOAAgHAFQgIAGAAAKIABAGQACAEAEADQAEADAIADIAhAKQAVAGAIALQAJAMAAAPQAAAPgHALQgIALgOAGQgOAGgUAAQgNAAgNgDg");
	this.shape_38.setTransform(43.9417,-45.825);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgMBSQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhaQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgOIAAgCIAEgBIAQAAQABAAAAAAQABAAAAgBQAAAAAAAAQABgBAAgBIAAgOQAAgOAIgIQAHgIAOAAIAUAAQAFAAAAAEIAAANIAAACIgDABIgNAAQgGAAgDAEQgCAEAAAGIAAALQAAAAAAABQAAAAAAABQAAAAABAAQAAAAABAAIAUAAIADABIABACIAAAOQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgUAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAABaQAAAEgDAAg");
	this.shape_39.setTransform(27.9,-45.825);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgeA1QgMgIgIgNQgHgOAAgRQAAgSAHgNQAIgOANgIQANgHAQgBQASABAMAHQAOAJAGANQAIAOAAAQQAAASgIAOQgHANgNAIQgNAHgRABQgQgBgOgHgAgPgkQgGAFgDAKQgEAIAAANQAAAOAEAJQADAIAGAFQAHAFAIAAQAKAAAGgFQAGgFAEgIQADgJAAgOQAAgNgDgIQgEgKgGgFQgHgEgJAAQgIAAgHAEg");
	this.shape_40.setTransform(16.95,-43.5);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgfBMQgMgGgFgNQgHgOAAgTQABgTAGgNQAHgOALgHQALgIAOAAQAIAAAHADQAHADAGAGIADABQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAIAAgzQAAgBAAgBQAAAAABgBQAAAAABgBQAAAAABAAIAWAAQADAAAAAEIAACbIgBADIgDABIgTAAIgEgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQgBgBAAAAIAAgHQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAgBAAIgBABIgIAGIgLAGQgGACgIAAQgNAAgKgHgAgLgOQgHAFgEAJQgEAJAAAOQAAAPAEAJQAEAJAHAEQAGAEAHAAQAHAAAGgDQAFgDAEgFQADgFAAgFIAAgxQgGgGgFgDQgGgDgHAAQgIAAgGAEg");
	this.shape_41.setTransform(-1.1,-45.725);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AAbA8IgDgBIgBgEIAAhKQAAgIgEgGQgFgEgJAAQgFAAgEABQgEACgFAEIgJAIIAABNQAAAFgFAAIgUAAQgEAAAAgFIAAhsQAAAAAAgBQABgBAAAAQAAgBABAAQAAAAABAAIAWAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAALIABADIACgCIAMgJQAGgEAFgCQAGgDAIAAQAQAAAKAKQAJAKAAAPIAABPQAAAFgFAAg");
	this.shape_42.setTransform(-13.925,-43.6);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("Ag1BSQgEAAAAgEIAAibQAAgEADAAIBqAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAARQAAAEgEAAIhIAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABAAABIAAAmQAAABAAABQAAAAABABQAAAAAAABQABAAABAAIAxAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAARIAAACIgDAAIgxAAQgBAAgBAAQAAABAAAAQgBAAAAABQAAAAAAABIAAApQAAABAAAAQAAABAAAAQABAAAAABQABAAAAAAIBMAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAAARIgBADIgDABg");
	this.shape_43.setTransform(-27.125,-45.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.4,-60.9,260,190.4);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_02_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.Img_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_01();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Ag0AAIBpAAIgeAjAAcgiIAZAi");
	this.shape.setTransform(53.1755,-6.2,1.0999,1.0999);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AFrA4QgJgFgEgHIgBgDIABgBIAMgFIABABIAFAFQAEAEAEABQAFACAGgBQAFABAEgCQAEgBADgCQACgDAAgDQAAgEgDgCQgCgCgHgCIgRgEQgMgCgGgHQgFgFAAgJQAAgHAEgGQAEgGAIgEQAIgDALAAQAMAAAIAEQAJAFAEAGIABACIgBACIgKAEIgCAAIgBgBQgDgEgFgCQgFgDgHAAQgHAAgFADQgFACAAAFQAAADACACQACABAHACIATAGQAMACAGAHQAFAGAAAJQAAAIgFAGQgEAGgJADQgIADgLAAQgOAAgKgFgAD/A4QgKgFgFgLQgFgLAAgPIAAhFQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAABJQAAAOAGAGQAGAGAMAAQAIAAAFgDQAGgCADgHQADgFAAgKIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABIQAAAQgGAKQgFAJgLAFQgKAEgOAAQgRAAgKgFgABAA4QgJgGgGgKQgFgJAAgNQAAgNAFgKQAGgKAJgGQAKgFAMAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEgGIgFgEQgDgCgEAAQgHAAgFAEQgFADgCAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAHAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgMAAgKgFgAgsA3QgHgHAAgKQAAgJAFgHQAFgGALgEQAKgEAOAAIAHAAIACgBIAAgCIAAgDQAAgHgDgDQgEgFgHAAQgGAAgFADQgFADgDAFIgBACIgCAAIgOgEIgBgBIABgCQAEgJAJgGQAKgEAOAAQALAAAIADQAHAEAEAGQADAGAAAHIAAA4IAAADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBgBAAQAAgBAAAAQgBAAAAABQgBAAAAAAQgFAGgGACQgHADgIAAQgMAAgHgGgAgFATIgKABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAHAAQAEAAAEgBIAGgEIAEgFIABgFIAAgLQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAgAkbA4QgKgGgFgKQgFgKAAgMQAAgNAFgKQAGgKAJgGQAKgFAMAAQAMAAAKAGQAJAFAGAKQAFAKAAANQAAAMgGAKQgFAKgJAGQgKAFgMAAQgNAAgJgFgAkRgIQgEADgDAGQgCAHAAAJQAAAJACAIQADAGAEAEQAFADAHAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgJgDgHQgCgGgFgDQgFgEgGAAQgHAAgFAEgAmOA2QgMgIgGgOQgHgOAAgSQAAgSAHgOQAGgNAMgHIAEgCQAKgGAOAAQAJAAAIADIAGADIAIAEQAGAFAEAGQAEAGABAIIABACIgCABIgSABIgCAAIgBgCQgCgIgFgGQgGgGgKAAQgOAAgHAKQgIALAAAWQAAAWAHALQAIALAOAAQAKgBAHgFQAHgEAFgMQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANADIABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgEAIIgGAJQgEAFgFADQgGADgHADQgHACgJAAQgQAAgMgHgACVA3QgGgGAAgKIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIADgZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIASAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgSABQgLAAgFgEgAhgA3QgFgGAAgKIAAguQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgKQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIALAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAABIASAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAAAqQAAAGADADQACACAGAAIAJAAIACABIABABIgBAJQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgRABQgLAAgGgEgAiTA7IgCAAIgBgDIAAg2QAAgFgDgEQgEgDgGAAIgIABIgGADIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgEQAFgCAFAAQAMAAAHAHQAHAHAAALIAAA5QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(4.6811,-5.9805,0.8908,0.8908);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(0.4,1,1).p("AoliLIRLAAIAAEXIxLAAg");
	this.shape_2.setTransform(12.9954,-5.9875,1.1818,1.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC24D").s().p("AolCMIAAkXIRLAAIAAEXg");
	this.shape_3.setTransform(12.9954,-5.9875,1.1818,1.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53,-24.5,132,37);


(lib.BG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,600);


// stage content:
(lib.WBAY_219645_MM_300X600_V1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(390));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(137,585.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(43).to({_off:false},0).to({y:565.6,alpha:1},17,cjs.Ease.get(1)).wait(330));

	// logo_png
	this.instance_1 = new lib.logo_1("synched",0);
	this.instance_1.setTransform(80,290);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({y:300,alpha:1},17,cjs.Ease.get(1)).wait(362));

	// T3
	this.instance_2 = new lib.T3("synched",0);
	this.instance_2.setTransform(80.25,540.05);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(167).to({_off:false},0).to({y:520.05,alpha:1},15,cjs.Ease.get(1)).wait(208));

	// T2
	this.instance_3 = new lib.T2("synched",0);
	this.instance_3.setTransform(80.05,493.15);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(151).to({_off:false},0).to({y:473.15,alpha:1},16,cjs.Ease.get(1)).wait(223));

	// T1
	this.instance_4 = new lib.T1("synched",0);
	this.instance_4.setTransform(76.3,374.55);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(26).to({_off:false},0).to({y:394.55,alpha:1},17,cjs.Ease.get(1)).wait(81).to({startPosition:0},0).to({alpha:0},10).wait(256));

	// Img_04_jpg
	this.instance_5 = new lib.Img_04_1("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(253).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(120));

	// Img_03_jpg
	this.instance_6 = new lib.Img_03_1("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(210).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(163));

	// Img_02_jpg
	this.instance_7 = new lib.Img_02_1("synched",0);
	this.instance_7.setTransform(80,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(134).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(239));

	// Img_01_jpg
	this.instance_8 = new lib.Img_01_1("synched",0);
	this.instance_8.setTransform(80,300);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(14).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(359));

	// BG_jpg
	this.instance_9 = new lib.BG_1("synched",0);
	this.instance_9.setTransform(80,300);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},17,cjs.Ease.get(1)).wait(373));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,290,152,311);
// library properties:
lib.properties = {
	id: '45EA4FADEDA04BCCBB7A758F81F2D007',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['45EA4FADEDA04BCCBB7A758F81F2D007'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;