name: Generate Preview Page
on: [push]
permissions:
  contents: write # This gives the script permission to save the index.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run Indexer
        run: python generate_index.py
      - name: Commit and Push all index files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add . # This captures index.html inside all folders
          git commit -m "Auto-update all master preview files" || exit 0
          git push
