name: Generate Preview Page
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run Indexer
        run: python generate_index.py
      - name: Fix Underscore Images
        run: touch .nojekyll # This is the fix for files like _300x600.jpg
      - name: Commit and Push all index files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Auto-update previews and fix underscore assets" || exit 0
          git push
