(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG = function() {
	this.initialize(img.BG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_01 = function() {
	this.initialize(img.Img_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_02 = function() {
	this.initialize(img.Img_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_03 = function() {
	this.initialize(img.Img_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Img_04 = function() {
	this.initialize(img.Img_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.T3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgOAdQgIgEgEgHQgEgIAAgJQAAgJAEgIQAFgHAHgFQAHgEAIAAQAJAAAHAEQAGAEAEAHQAEAIAAAJIAAADIgCAAIgpAAIgBABIgBABQAAAFADAEQACAEAEACQAEACAEABQAFgBAEgCQAEgCADgEIABgBIABABIAIACQAAABAAAAQABAAAAABQAAAAgBAAQAAABAAAAIgIAIQgEAEgFABIgLABQgIAAgHgEgAgGgUQgEACgCAFQgCADAAAGIAcAAIABgBIABgBIgCgHQgCgFgDgCQgDgCgFAAQgEAAgDACg");
	this.shape.setTransform(25.275,3.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgQAeQgIgEgCgGIgBgCIABgBIAHgDIACAAIABAAIADAEIAGAEIAIABIAHgBQADgBABgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgCgCgGgCIgLgCQgJgCgEgEQgEgEAAgGQAAgGADgFQADgEAGgDQAGgDAHAAQAJAAAHADQAGAEADAFIABABIgBABIgHAEIgCAAIgBgBIgGgFQgEgCgFAAQgFAAgDACQgEACABAEIABADIAHADIANAEQAJADAEAEQAEAEAAAHQAAAFgDAFQgEAEgGADQgGACgIAAQgKAAgHgDg");
	this.shape_1.setTransform(17.95,3.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWAdQgFgFAAgJQAAgGAEgFQAEgEAHgCQAIgDAKAAIAGgBIABAAIABgCIAAgDQAAgFgEgDQgDgDgFABIgHABQgEACgCAEIgBABIgCAAIgKgCIgBgBIABgCQADgHAHgEQAHgDAJAAQAKAAAFACQAGADADAFQACAFAAAGIAAApIAAACIgCAAIgKAAIgBgBIgBgCIAAgEQAAAAgBAAQAAgBAAAAQAAAAgBABQAAAAgBAAQgEAEgEACQgEACgGAAQgKAAgFgEgAAHACIgHABIgGACIgEADQgCADAAADQAAAEADACQADACAFABIAFgBIAFgDIADgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAg");
	this.shape_2.setTransform(10.775,3.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AAPAsIgCAAIAAgCIAAgpQAAgDgDgDQgCgDgFAAIgEABIgFADIgGAEIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgLAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhTQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAeIAAABIABAAIAIgFIAFgEIAHgBQAKAAAFAGQAEAFAAAIIAAArQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(3.525,1.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgNAdQgHgEgEgIQgEgHAAgKQAAgIAEgIQAEgHAHgFQAHgEAIAAQAHAAAFACQAGADADAEIAFAIQABABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgKABIgCgBIgDgFIgEgDQgCgCgEABQgDgBgEADQgEADgCAFQgCAFAAAGQAAAHADAGQACAEADAEQAEACAEAAQAGAAADgDQAEgDADgFIAAAAIACAAIAHACQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgEAGQgCADgDACQgDADgFACQgEABgGAAQgIAAgHgEg");
	this.shape_4.setTransform(-3.8417,3.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgRAgIgBAAIgBgCIAAg6QAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAMAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAAAHIAAABIABgBIAFgFIAGgEIAGgCQABAAABABQABAAAAAAQABAAAAABQABAAAAAAIAAAMQAAAAgBABQAAAAAAAAQAAABAAAAQgBAAAAAAIgEgBIgDAAIgFABIgFACIgDAEQAAAAAAABQAAABgBAAQAAABAAAAQAAABAAAAIAAAkQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_5.setTransform(-10,3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgSAeQgEgCgDgEQgCgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAoQgBAEADADQADADAEAAQAEAAADgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAA6QAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgLAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgGIAAgBIgBABQgGAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_6.setTransform(-16.85,3.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AggAsIgCAAIAAgCIAAhTQAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIAgAAQAKAAAIADQAIACAFAGQAEAHAAAJQAAAIgEAGQgEAGgIACQgGADgKABIgSAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBAAAAABIAAAfQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAgAgRgdIAAAZQAAAAABAAQAAABAAAAQAAAAABAAQAAAAABAAIAOAAQAIAAAFgDQAEgEAAgHQAAgFgCgDQgCgDgFgCIgIgBIgOAAQgBABAAAAQgBAAAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_7.setTransform(-24.95,1.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgaAnQgIgEAAgIQAAgEADgDQADgDAFgCQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAgBAAQgDgBgBgCQgCgCAAgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAIAEgDIAGgDIAAAAIAAgBQgGgDgCgEQgDgEAAgFQAAgJAHgGQAIgFAOAAQAFAAAFABQAFACADACIABABIACgBIADgDIAFgDIAEAAIABAAIABACIAAAHIgBACIgBAAIgEAAIgCAAQgBABgBAAQAAAAgBABQAAAAAAAAQAAABAAAAIABADIABAEQAAAFgDAEQgDAFgHADQgGACgIAAIgJABIgEABIgBACQAAAAAAAAQAAABAAAAQABAAAAAAQAAABABAAIAGABIAQABQAMABAFAEQAFAFAAAHQAAAJgIAGQgJAFgPAAQgQAAgJgEgAgQASIgDADQgBAAAAABQAAAAgBABQAAAAAAABQAAABAAAAQAAADACADQACACAFABIAMABQAIAAAFgCQAFgDAAgEQAAgEgDgCQgCgCgGAAIgSgBIgFABgAgMgeQgDADAAAGQAAAFADADQAEADAHAAQAGAAADgDQADgDAAgFQAAgGgDgDQgDgDgGAAQgHAAgEADg");
	this.shape_8.setTransform(44.325,-12.525);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AAPAhIgCgBIAAgCIAAgoQAAgEgDgDQgCgDgFAAIgFABIgEADIgGAFIAAApQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAg6QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAGIAAABIABgBIAHgEQADgDADgBQADgCAEAAQAJAAAFAGQAFAFAAAIIAAArQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_9.setTransform(36.525,-13.55);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgEAtIgDgBIAAgCIAAg6QAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAA6IAAACIgCABgAgFgbIgCgBIAAgCIAAgLQAAgBAAAAQAAgBABAAQAAAAAAAAQAAAAABAAIALAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAALQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_10.setTransform(30.85,-14.75);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgZApIgCgBIAAgIIABgBIADgBIAIAAIAEgBIADgEIACgEIAAgDIgXg4IAAgCIABgBIANAAIABABIABABIAOAnQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIABgBIAPgnIABgBIABgBIAJAAIABABIAAACIgZA+IgFAJIgEAFQgDACgEABIgJABg");
	this.shape_11.setTransform(25.425,-12.475);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgGAtQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgwIgBgBIgJAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgHIABgBIACgBIAJAAQAAAAAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIAAgIQAAgHAEgFQAEgDAIAAIALAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAHIAAABIgCAAIgHAAQAAAAgBAAQgBAAAAAAQgBABAAAAQgBABAAAAQgCACAAAEIAAAFQAAABAAAAQAAAAAAABQABAAAAAAQAAAAABAAIALAAIABABIABABIAAAHQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgLAAQAAAAgBAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAwQAAABgBAAQAAABAAAAQAAAAAAAAQgBABAAAAg");
	this.shape_12.setTransform(19.2,-14.75);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgFAtIgBgBIgBgCIAAg6QAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQABAAAAABIAAA6IgBACIgCABgAgFgbIgBgBIgBgCIAAgLQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAALQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_13.setTransform(14.7,-14.75);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgEAtQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIABhTQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIALAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAABTIgBACIgCABg");
	this.shape_14.setTransform(11.025,-14.75);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgWAdQgFgGAAgIQAAgGAEgFQAEgEAHgDQAIgCAKAAIAGgBIABAAIABgCIAAgDQAAgFgEgDQgDgCgFgBIgHACQgEACgCAEIgBABIgCAAIgKgCIgBgBIABgCQADgHAHgEQAHgDAJAAQAKAAAFACQAGADADAFQACAFAAAFIAAAqIAAABIgCABIgKAAIgBgBIgBgCIAAgEQAAAAgBAAQAAgBAAAAQAAAAgBABQAAAAgBAAQgEAEgEACQgEACgGAAQgKAAgFgEgAAHACIgHABIgGACIgEADQgCADAAADQAAAEADACQADACAFABIAFgBIAFgDIADgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAg");
	this.shape_15.setTransform(5.375,-13.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgSAeQgFgCgBgEQgDgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAoQABAEACADQACADAFAAQADAAAEgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA6QAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgMAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgGIAAgBIgBABQgGAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_16.setTransform(-1.9,-13.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAXAxQgHgEgFgGQAAgBgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAIgEABIgFAAQgLgBgJgFQgJgFgFgKQgFgLAAgNQAAgOAFgKQAFgLAJgGQAJgEALAAQAMAAAJAEQAJAGAFALQAFAKAAAOQAAAMgEAJQgEAJgHAHIAAABIABACIAGAEIAGACIABABIABAAIAAAJIgBACIgDAAQgHABgGgEgAgPgfQgGAIAAASQAAAPAGAIQAFAIAKAAQALAAAFgIQAGgIAAgPQAAgSgGgIQgFgIgLAAQgKAAgFAIg");
	this.shape_17.setTransform(-10.625,-14.05);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAPAtIgCgBIAAgCIAAgpQAAgDgDgDQgCgDgFAAIgEABIgFADIgGAEIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhTQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAeIAAABIABAAIAIgFIAFgEIAHgBQAKABAFAFQAEAFAAAIIAAArQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_18.setTransform(-22.475,-14.75);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAGArQgHgBgEgEQgEgDAAgHIAAgjQAAgBgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgHQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIABgSQAAAAABgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAKAAQAAAAABABQAAAAAAAAQAAAAAAABQABAAAAAAIAAASQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgNAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACACAEAAIAHAAIABABIABABIgBAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgEAAIgFABg");
	this.shape_19.setTransform(-29.2,-14.55);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgEAtIgCgBIgBgCIAAg6QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAA6IAAACIgCABgAgFgbIgBgBIgBgCIAAgLQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAALQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_20.setTransform(-33.75,-14.75);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAVAtQgBAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAgBIgQg4IgBgBIAAABIgQA4QAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAIgMAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIgYhSIAAgCIACgBIAMAAIACAAIABACIARA6IABACIABgBIAQg7IABgCIACAAIAKAAIACAAIABACIARA7IABABIAAgBIARg7IABgCIACAAIAJAAIACABIABACIgZBSQAAABAAAAQgBABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_21.setTransform(-42.3125,-14.75);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgQAhIgCgBIAAgCIAAg6QAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAAHIABABIABAAIAFgHIAGgDIAGgCQABAAABABQABAAAAAAQABAAAAABQAAAAAAABIAAALQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAgBIgEAAIgEAAIgEAAIgFADIgCAEQgBAAAAABQAAABgBAAQAAABAAAAQAAABAAAAIAAAkQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAg");
	this.shape_22.setTransform(54.4,-30.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgOAdQgIgEgEgHQgEgHAAgKQAAgKAEgHQAFgHAHgFQAHgEAIAAQAJAAAHAEQAGAEAEAIQAEAHAAAKIAAACIgCAAIgpAAIgBAAIgBACQAAAFADAEQACAEAEACQAEADAEgBQAFABAEgDQAEgCADgFIABAAIABAAIAIADQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgIAJQgEADgFABIgLABQgIAAgHgEgAgGgUQgEACgCAFQgCAEAAAEIAcAAIABAAIABgBIgCgHQgCgFgDgCQgDgCgFAAQgEAAgDACg");
	this.shape_23.setTransform(47.625,-30.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAPAtIgCgBIAAgCIAAgpQAAgDgDgDQgCgDgFAAIgEABIgFADIgGAEIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhTQAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAeIAAACIABgBIAIgFIAFgDIAHgCQAKABAFAEQAEAGAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_24.setTransform(39.975,-31.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgNAdQgHgEgEgHQgEgIAAgJQAAgJAEgIQAEgHAHgFQAHgEAIAAQAHAAAFACQAGADADAEIAFAIQABABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgKACIgCgBIgDgFIgEgDQgCgBgEgBQgDABgEACQgEADgCAFQgCAFAAAGQAAAIADAEQACAFADAEQAEACAEAAQAGAAADgDQAEgDADgFIAAAAIACAAIAHACQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgEAFQgCAEgDADQgDACgFABQgEACgGAAQgIAAgHgEg");
	this.shape_25.setTransform(32.6083,-30.05);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgSAeQgFgCgBgEQgDgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAoQAAAEACADQACADAFAAQADAAAEgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIAAgBIgBABQgGAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_26.setTransform(25.1,-29.975);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgPAdQgHgEgFgHQgDgIAAgJQAAgJADgIQAFgHAHgFQAHgEAIAAQAKAAAGAEQAIAFADAHQAFAIAAAJQAAAJgFAIQgDAHgIAEQgGAEgKAAQgJAAgGgEgAgIgTQgDADgCAFQgCAFAAAGQAAAIACAEQACAFADADQAEADAEgBQAFABADgDQAEgDACgFQACgEgBgIQABgGgCgFQgCgFgEgDQgDgCgFgBQgEABgEACg");
	this.shape_27.setTransform(17.45,-30.05);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgGAtQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgdhTIAAgCIACAAIAOAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAABABIAUA/QAAABAAAAQAAAAABAAQAAAAAAAAQAAAAAAgBIAWg/QAAgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAIACAAIAAACIgdBTQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_28.setTransform(8.95,-31.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AAPAhIgCgBIAAgCIAAgoQAAgEgDgDQgCgDgFAAIgFABIgEADIgGAFIAAApQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAg6QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAGIAAABIABAAIAHgGQADgCADgBQADgCAEAAQAJAAAFAGQAFAFAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_29.setTransform(-2.625,-30.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgPAdQgHgEgFgHQgEgIAAgJQAAgJAEgIQAFgHAHgFQAHgEAIAAQAKAAAGAEQAHAFAFAHQADAIAAAJQAAAJgDAIQgFAHgHAEQgGAEgKAAQgJAAgGgEgAgHgTQgEADgCAFQgCAFAAAGQAAAIACAEQACAFAEADQADADAEgBQAFABADgDQAEgDACgFQACgEgBgIQABgGgCgFQgCgFgEgDQgDgCgFgBQgEABgDACg");
	this.shape_30.setTransform(-10.35,-30.05);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgEAtIgDgBIAAgCIAAg6QAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAA6IAAACIgCABgAgFgbIgCAAIAAgDIAAgLQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIALAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAALQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_31.setTransform(-16.05,-31.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAGArQgHAAgEgFQgFgDABgIIAAgjQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgHQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIABgSQABAAAAgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAKAAQAAAAABABQAAAAAAAAQAAAAAAABQABAAAAAAIAAASQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIgNAAQgBAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACACAEAAIAHAAIABABIABABIgBAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgEAAIgFABg");
	this.shape_32.setTransform(-20.75,-31.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgWAdQgFgGAAgIQAAgGAEgFQAEgEAHgDQAIgCAKAAIAGgBIABAAIABgCIAAgDQAAgFgEgDQgDgCgFgBIgHACQgEACgCAEIgBABIgCAAIgKgCIgBgBIABgCQADgHAHgEQAHgDAJAAQAKAAAFACQAGADADAEQACAFAAAGIAAAqIAAABIgCABIgKAAIgBgBIgBgCIAAgEQAAAAgBAAQAAgBAAAAQAAAAgBABQAAAAgBAAQgEAEgEACQgEACgGAAQgKAAgFgEgAAHACIgHABIgGACIgEAEQgCACAAADQAAAEADACQADADAFgBIAFgBIAFgCIADgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAg");
	this.shape_33.setTransform(-27.325,-30.05);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgNAdQgHgEgEgHQgEgIAAgJQAAgJAEgIQAEgHAHgFQAHgEAIAAQAHAAAFACQAGADADAEIAFAIQABABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgKACIgCgBIgDgFIgEgDQgCgBgEgBQgDABgEACQgEADgCAFQgCAFAAAGQAAAIADAEQACAFADAEQAEACAEAAQAGAAADgDQAEgDADgFIAAAAIACAAIAHACQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgEAFQgCAEgDADQgDACgFABQgEACgGAAQgIAAgHgEg");
	this.shape_34.setTransform(-34.2417,-30.05);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgWAdQgFgGAAgIQAAgGAEgFQAEgEAHgDQAIgCAKAAIAGgBIABAAIABgCIAAgDQAAgFgEgDQgDgCgFgBIgHACQgEACgCAEIgBABIgCAAIgKgCIgBgBIABgCQADgHAHgEQAHgDAJAAQAKAAAFACQAGADADAEQACAFAAAGIAAAqIAAABIgCABIgKAAIgBgBIgBgCIAAgEQAAAAgBAAQAAgBAAAAQAAAAgBABQAAAAgBAAQgEAEgEACQgEACgGAAQgKAAgFgEgAAHACIgHABIgGACIgEAEQgCACAAADQAAAEADACQADADAFgBIAFgBIAFgCIADgEQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAIAAgJQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAg");
	this.shape_35.setTransform(-41.725,-30.05);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgGAtQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgdhTIAAgCIACAAIAOAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAVA/QAAABAAAAQAAAAABAAQAAAAAAAAQAAAAABgBIAUg/QABgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIALAAIACAAIAAACIgdBTQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_36.setTransform(-49.75,-31.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgGAeQAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAgBIAAgNQAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIANAAQAAAAABAAQAAAAAAABQAAAAABAAQAAABAAAAIAAANQAAABAAAAQgBABAAAAQAAAAgBAAQgBAAAAAAgAgGgNQAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAgBIAAgNQAAAAAAgBQAAAAABAAQAAAAAAAAQAAgBABAAIANAAQAAAAABABQAAAAAAAAQAAAAABAAQAAABAAAAIAAANQAAABAAAAQgBABAAAAQAAAAgBAAQgBAAAAAAg");
	this.shape_37.setTransform(43.525,-46.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgQAdQgIgDgDgGIAAgBIAAgBIAIgEIACgBIAAABIAFAFIAFADIAHABIAIgBQADgBABgCQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQgCgCgFgBIgMgDQgIgCgFgDQgEgFAAgHQAAgFADgFQADgFAGgCQAGgDAHAAQAJAAAHADQAGAEADAEIABACIgBABIgIADIgBABIgBgBIgGgFQgEgCgFAAQgFAAgDACQgEACABAEIABADIAHAEIANADQAJADAEADQAEAFAAAGQAAAHgDAEQgEAEgGADQgGACgJAAQgJAAgHgEg");
	this.shape_38.setTransform(38.3,-46.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgSAeQgFgCgCgEQgCgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAoQAAAEACADQADADAEAAQAEAAADgCIAHgGIAAgqQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIgBgBIgBABQgFAFgFACQgEACgFAAQgGAAgEgCg");
	this.shape_39.setTransform(31.1,-46.525);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAPAhIgCgBIAAgBIAAgpQAAgEgDgDQgCgDgFAAIgFABIgEADIgGAFIAAApQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgLAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAg7QAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIALAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAGIAAABIABAAIAHgGQADgCADgBQADgBAEAAQAJgBAFAGQAFAFAAAJIAAAqQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_40.setTransform(23.475,-46.65);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgPAdQgHgEgFgHQgDgIAAgJQAAgJADgIQAFgHAHgEQAHgFAIAAQAKAAAGAFQAHAEAFAHQADAIAAAJQAAAJgDAIQgFAHgHAEQgGAEgKAAQgJAAgGgEgAgHgTQgEADgCAFQgCAFAAAGQAAAIACAEQACAFAEADQADADAEgBQAFABADgDQAEgDACgFQACgEgBgIQABgGgCgFQgCgFgEgDQgDgCgFgBQgEABgDACg");
	this.shape_41.setTransform(15.75,-46.6);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AggAtIgCgBIAAgBIAAhVIAAgBIACAAIAfAAQAQgBAJAHQAJAFAAAMQAAAGgEAFQgDAFgJAEIAAAAIAAAAQAJACAFAFQAEAFAAAIQAAANgJAFQgJAHgRAAgAgRAIIAAAWQAAABAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAOAAQAJAAAEgDQAFgEAAgGQAAgFgDgDQgCgDgEgBQgEgCgEAAIgOAAQgBAAAAABQgBAAAAAAQAAAAgBABQAAAAAAABgAgRgeIAAAWQAAABAAAAQAAABABAAQAAAAAAAAQABAAAAAAIAPAAIAFgBIAFgBQADgCABgDQABgCAAgDQAAgHgEgDQgFgDgHgBIgNAAQgBAAAAABQgBAAAAAAQAAAAgBABQAAAAAAAAg");
	this.shape_42.setTransform(7.475,-47.85);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AAGArQgHAAgEgFQgEgDgBgIIAAgjQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAAAIgIAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgHQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAJAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIABgTQAAAAABgBQAAAAAAAAQAAAAAAAAQABgBAAAAIAKAAQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAABIAAASQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgOAAQAAAAAAAAQAAAAgBAAQAAAAAAABQAAAAAAAAIAAAfQAAAFACABQACACAEABIAHAAIACAAIAAABIAAAGQAAABgBAAQAAABAAAAQAAAAgBABQAAAAAAAAIgFAAIgEABg");
	this.shape_43.setTransform(-3.25,-47.65);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgQAdQgIgDgCgGIgBgBIABgBIAHgEIACgBIAAABIAEAFIAGADIAIABIAHgBQADgBABgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgCgCgGgBIgLgDQgJgCgEgDQgEgFAAgHQAAgFADgFQADgFAGgCQAGgDAHAAQAJAAAHADQAGAEADAEIABACIgBABIgIADIgBABIgBgBIgGgFQgEgCgFAAQgFAAgDACQgEACABAEIABADIAHAEIANADQAJADAEADQAEAFAAAGQAAAHgDAEQgEAEgGADQgGACgIAAQgKAAgHgEg");
	this.shape_44.setTransform(-9.5,-46.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgSAeQgFgCgCgEQgCgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIALAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAoQAAAEACADQADADAEAAQADAAAEgCIAHgGIAAgqQAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIgBgBIgBABQgFAFgFACQgEACgFAAQgGAAgEgCg");
	this.shape_45.setTransform(-16.7,-46.525);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgaAnQgIgEAAgIQAAgEADgDQADgDAFgCQABAAAAAAQAAAAAAAAQAAgBAAAAQAAAAgBAAQgDgBgBgCQgCgCAAgDQAAgBAAAAQAAgBAAgBQAAAAABAAQAAgBAAAAIAEgDIAGgDIAAAAIAAgBQgGgDgCgEQgDgEAAgFQAAgJAHgGQAIgFAOAAQAFAAAFABQAFACADACIABABIACgBIADgDIAFgDIAEAAIABAAIABACIAAAHIgBACIgBAAIgEAAIgCAAQgBABgBAAQAAAAgBABQAAAAAAAAQAAABAAAAIABADIABAEQAAAFgDAEQgDAFgHADQgGACgIAAIgJABIgEABIgBACQAAAAAAAAQAAABAAAAQABAAAAAAQAAABABAAIAGABIAQABQAMABAFAEQAFAFAAAHQAAAJgIAGQgJAFgPAAQgQAAgJgEgAgQASIgDADQgBAAAAABQgBAAAAABQAAAAAAABQAAABAAAAQAAADACADQACACAFABIAMABQAIAAAFgCQAFgDAAgEQAAgEgDgCQgCgCgGAAIgSgBIgFABgAgMgeQgDADAAAGQAAAFADADQAEADAHAAQAGAAADgDQADgDAAgFQAAgGgDgDQgDgDgGAAQgHAAgEADg");
	this.shape_46.setTransform(-24.575,-45.625);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgSAeQgEgCgCgEQgDgFAAgGIAAgqQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIALAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAoQABAEACADQACADAFAAQADAAAEgCIAIgGIAAgqQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIALAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAABIAAA6QAAABAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIgMAAQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgGIAAgBIgBABQgGAFgFACQgEACgGAAQgFAAgEgCg");
	this.shape_47.setTransform(-32.4,-46.525);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AAZAtQAAAAgBgBQAAAAAAAAQgBAAAAAAQAAgBAAAAIgHgUIAAgBIgBAAIgfAAIgBABIgHAUIgBABIgCABIgLAAIgCgBIAAgDIAfhTIABgBIACAAIAOAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAABIAeBSIAAADIgBABgAgBgYIgMAfQAAAAAAABQAAAAAAAAQAAABABAAQAAAAAAAAIAWAAQABAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIgLgfIAAgBIgBABg");
	this.shape_48.setTransform(-41.025,-47.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59.3,-57,118.6,68.2);


(lib.T2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAUAsIgCgBIgBgCIAAg3QAAgGgDgEQgDgDgHAAQgEAAgCABIgHAEIgHAGIAAA5QAAAAAAABQgBABAAAAQgBAAAAABQgBAAgBAAIgOAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAhPQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAJIAAABIABgBIAJgHIAIgEQAFgCAGAAQAMAAAHAHQAGAHAAALIAAA6QAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAg");
	this.shape.setTransform(61.075,-25.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAVArQgDAAgBgDIgQgxIgBgBIAAABIgQAyIgBABIgCABIgMAAQgDAAgBgDIgahOQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIACgBIAPAAIADABIABACIAQAzIABABIABgCIAQgyIABgCIACgBIALAAIABABIACACIAQAzIABABIABgCIAQgyIABgCIACgBIAKAAIACABIAAADIgaBPIgBABIgCABg");
	this.shape_1.setTransform(49.1542,-25.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgVAnQgKgFgGgKQgEgLAAgNQgBgMAGgKQAGgKAJgGQAKgGALAAQANABAKAFQAJAGAGAKQAEAKAAAMQAAANgFALQgFAKgJAFQgLAGgMgBQgLABgKgGgAgLgaQgEAEgDAGQgCAHAAAJQAAAKACAGQADAHAEADQAFAEAGAAQAHAAAFgEQAFgDACgHQACgGABgKQgBgJgCgHQgCgGgFgEQgFgDgHAAQgGAAgFADg");
	this.shape_2.setTransform(37.25,-25.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgtA8QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAhxIAAgCIADgBIAHAAIAJAAIAJAAIAHAAQAVAAAOAIQAOAHAHANQAGANABASQAAATgIANQgHANgOAIQgPAHgUAAgAgZgoIAABRQAAAAABABQAAAAAAABQAAAAABAAQAAAAAAAAIAFAAQAOAAAJgEQAKgFAEgJQAFgJAAgQQAAgPgFgJQgEgKgJgEQgIgEgPAAIgGAAQAAAAgBAAQAAAAAAAAQAAABAAAAQgBAAAAABg");
	this.shape_3.setTransform(26.15,-27.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgiA4QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgLIAAgBIAEgBIALAAQADAAADgCIAEgEIACgGQABgCgBgDIgfhMQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIACgBIARAAIACABIACABIATA1IABABQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIAUg1IABgBIACgBIAMAAIACABIAAACIgiBUIgGANQgDAEgEADQgEADgFABIgMAAg");
	this.shape_4.setTransform(10.9792,-24.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgUAnQgKgFgFgKQgGgKAAgNQAAgNAGgKQAGgLAJgFQAKgGALAAQAMAAAJAGQAJAFAFAKQAGAKAAANIgBADQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIg4AAIgCABIAAABQAAAIADAEQADAGAGADQAFADAFAAQAHAAAGgDQAFgDAFgGIABgBIACABIAJAFQABAAAAAAQABAAAAAAQAAABgBAAQAAABAAAAQgFAHgGAEQgFAFgHACQgHACgIgBQgLABgKgGgAgJgbQgFADgCAFQgDAFAAAHIAlAAIADgBIAAgBQAAgFgCgFQgCgFgFgDQgEgDgGAAQgGAAgFADg");
	this.shape_5.setTransform(1.275,-25.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAUAsIgCgBIgBgCIAAg3QAAgGgDgEQgDgDgHAAQgEAAgCABIgHAEIgHAGIAAA5QAAAAAAABQgBABAAAAQgBAAAAABQgBAAgBAAIgOAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAhPQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAJIAAABIABgBIAJgHIAIgEQAFgCAGAAQAMAAAHAHQAGAHAAALIAAA6QAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAg");
	this.shape_6.setTransform(-8.825,-25.925);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgVAnQgKgFgGgKQgEgLAAgNQgBgMAGgKQAGgKAJgGQAKgGALAAQANABAKAFQAJAGAGAKQAEAKAAAMQAAANgFALQgFAKgJAFQgLAGgMgBQgMABgJgGgAgLgaQgEAEgDAGQgCAHAAAJQAAAKACAGQADAHAEADQAFAEAGAAQAHAAAFgEQAFgDACgHQACgGABgKQgBgJgCgHQgCgGgFgEQgFgDgHAAQgGAAgFADg");
	this.shape_7.setTransform(-19,-25.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAqA8IgDgBIAAgCIAAhUIgBgBIAAABIgfBVQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgKAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIgehUIgBgBIAAABIAABUIgBABIgCABIgOAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhxQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAbAAIACABIABABIAdBLQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIABgCIAchKQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAcAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAABIAABxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_8.setTransform(-31.925,-27.55);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgVAnQgKgFgGgKQgEgLAAgNQgBgMAGgKQAGgKAJgGQAKgGALAAQANABAKAFQAJAGAFAKQAGAKAAAMQgBANgFALQgFAKgJAFQgKAGgNgBQgLABgKgGgAgLgaQgEAEgDAGQgDAHABAJQgBAKADAGQADAHAEADQAFAEAGAAQAHAAAFgEQAEgDADgHQADgGAAgKQAAgJgDgHQgCgGgFgEQgFgDgHAAQgGAAgFADg");
	this.shape_9.setTransform(-48.8,-25.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAhA8IgDAAIgCgCIg2hOIgBgBIgBABIAABOQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgPAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAhyQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAQAAIACABIACABIAzBKIACABQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAgBIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAABAAIAOAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABzIgBABIgBABg");
	this.shape_10.setTransform(-60.25,-27.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgJAYIgCgBIAAgCIAIgSQAAgBAAgBQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgSQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIASAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAASIAAABIgOAYIgCACIgDAAg");
	this.shape_11.setTransform(46.2875,-41.15);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAIA5QgJAAgGgEQgGgGAAgKIAAgvQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBgBAAAAIgLAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAgKQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAMAAQAAAAABgBQAAAAAAAAQAAAAAAAAQABgBAAAAIABgZQAAgBABAAQAAgBAAAAQAAAAABAAQAAgBABAAIANAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAABIAAAYQAAAAABABQAAAAAAAAQAAAAAAAAQABABAAAAIASAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAKQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgTAAQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAIAAAqQAAAHACACQADADAFAAIAKAAIACABIABABIAAAJQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAgBAAIgFABIgHAAg");
	this.shape_12.setTransform(40.4,-46.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgWAnQgKgEgEgIIgBgCIABgBIAKgGIACAAIABAAIAGAHQADACAEACQAFACAGgBIAJgBIAGgDQADgDAAgDQAAgEgDgBQgDgDgHgCIgPgEQgNgDgFgEQgGgHAAgIQAAgIAEgHQAEgGAIgDQAIgDAKgBQAMABAJAEQAJAEAEAHIABACIgBABIgKAFIgCABIgCgBQgDgFgFgCQgFgDgHAAQgGAAgFADQgEACAAAGQAAAAAAABQAAAAAAABQAAAAABABQAAABABAAQACADAGABIATAFQAMADAGAGQAFAGAAAJQAAAIgFAGQgFAGgIAEQgJADgKAAQgNAAgKgGg");
	this.shape_13.setTransform(32.225,-45.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgUAnQgKgGgFgJQgGgKAAgNQAAgNAGgKQAGgKAJgGQAKgFALgBQAMABAJAFQAJAFAFAKQAGAKAAANIgBADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIg4AAIgCABIAAACQAAAHADAEQADAGAGADQAFADAFAAQAHAAAGgDQAFgCAFgHIABAAIACAAIAJAEQABABAAAAQABAAAAAAQAAABgBAAQAAAAAAABQgFAIgGADQgFAFgHACQgHABgIABQgLgBgKgFgAgJgbQgFADgCAGQgDAEAAAHIAlAAIADgBIAAgBQAAgFgCgFQgCgFgFgDQgEgDgGAAQgGAAgFADg");
	this.shape_14.setTransform(22.925,-45.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgWAsIgDgBIgBgCIAAhPQAAgBABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAPAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAAKIABABIABAAIAHgIIAIgFQAEgCAFAAQAFAAAAADIAAAPQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgFgBIgFAAIgHACQgDABgDACIgDAFQgCADAAADIAAAxQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_15.setTransform(14.65,-45.575);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgUAnQgKgGgFgJQgGgKAAgNQAAgNAGgKQAGgKAJgGQAKgFALgBQAMABAJAFQAJAFAFAKQAGAKAAANIgBADQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIg4AAIgCABIAAACQAAAHADAEQADAGAGADQAFADAFAAQAHAAAGgDQAFgCAFgHIABAAIACAAIAJAEQABABAAAAQABAAAAAAQAAABgBAAQAAAAAAABQgFAIgGADQgFAFgHACQgHABgIABQgLgBgKgFgAgJgbQgFADgCAGQgDAEAAAHIAlAAIADgBIAAgBQAAgFgCgFQgCgFgFgDQgEgDgGAAQgGAAgFADg");
	this.shape_16.setTransform(5.775,-45.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAIA5QgKAAgFgEQgGgGAAgKIAAgvQAAgBAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAIgLAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAMAAQAAAAABgBQAAAAAAAAQAAAAAAAAQABgBAAAAIACgZQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIANAAQABAAAAABQABAAAAAAQAAABAAAAQAAABABABIAAAYQAAAAAAABQAAAAAAAAQAAAAAAAAQABABAAAAIASAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgTAAQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAIAAAqQAAAHACACQADADAFAAIAKAAIACABIAAABIAAAJQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIgGABIgGAAg");
	this.shape_17.setTransform(-3,-46.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AAUAsIgCgBIgBgCIAAg3QAAgGgDgEQgDgDgHAAQgEAAgCABIgHAEIgHAGIAAA5QAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAIgOAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAhPQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAJIAAABIABgBIAJgHIAIgEQAFgCAGAAQAMAAAHAHQAGAHAAALIAAA6QAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAg");
	this.shape_18.setTransform(-11.625,-45.575);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgIA8IgCAAIgBgDIAAhxQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAABAAIARAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABwIgBADIgDABg");
	this.shape_19.setTransform(-19.4,-47.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgVAnQgKgGgFgJQgGgKAAgOQABgMAFgKQAGgKAJgGQAKgFALgBQANAAAJAHQAKAFAFAKQAFAKABAMQAAAOgGAKQgFAJgKAGQgJAFgNABQgLgBgKgFgAgKgaQgFAEgDAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAFAAQAHAAAFgDQAEgEADgGQADgHgBgKQABgJgDgHQgDgGgFgEQgEgDgHAAQgFAAgFADg");
	this.shape_20.setTransform(-31.2,-45.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AAhA8IgDAAIgCgCIg2hNIgBgBIgBABIAABMQAAABAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgPAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAgBIAAhxQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAQAAIACAAIACACIA0BKIABABQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIAAhJQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAABAAIAOAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAByIgBADIgBAAg");
	this.shape_21.setTransform(-42.7,-47.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgJAYIgCgBIAAgCIAIgSQAAgBAAgBQAAAAAAgBQAAAAgBAAQAAAAgBAAIgCAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgRQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIASAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAASIAAABIgOAYIgCACIgDAAg");
	this.shape_22.setTransform(54.7375,-60.85);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgWAnQgKgFgEgHIgBgCIABgBIAKgGIACAAIABAAIAGAHQADADAEABQAFACAGgBIAJgBIAGgDQADgDAAgDQAAgDgDgCQgDgDgHgCIgPgEQgNgDgFgEQgGgHAAgIQAAgIAEgGQAEgHAIgDQAIgDAKgBQAMABAJAEQAJAEAEAHIABABIgBACIgKAFIgCABIgCgBQgDgFgFgCQgFgDgHAAQgGAAgFADQgEACAAAGQAAAAAAABQAAAAAAABQAAAAABABQAAABABAAQACACAGACIATAFQAMADAGAGQAFAGAAAJQAAAIgFAGQgFAGgIAEQgJACgKABQgNAAgKgGg");
	this.shape_23.setTransform(47.975,-65.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AAJA5QgKAAgGgEQgGgGAAgKIAAgvQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBgBAAAAIgLAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIAAgLQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAMAAQAAAAABgBQAAAAAAAAQAAAAAAAAQAAgBAAAAIACgZQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIANAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAABIAAAYQAAAAAAABQAAAAAAAAQAAAAAAAAQABABAAAAIATAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAALQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgSAAQgBAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAIAAAqQAAAHADACQACADAGAAIAKAAIABABIAAABIAAAJQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIgGABIgHAAg");
	this.shape_24.setTransform(39.35,-66.65);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AAUAsIgCgBIgBgCIAAg3QAAgGgDgEQgDgDgHAAQgEAAgCABIgHAEIgHAGIAAA5QAAAAAAABQgBABAAAAQgBAAAAABQgBAAgBAAIgOAAQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAhPQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAJIAAABIABgBIAJgHIAIgEQAFgCAGAAQAMAAAHAHQAGAHAAALIAAA6QAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAg");
	this.shape_25.setTransform(30.725,-65.275);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgUAnQgKgGgFgJQgGgKAAgNQAAgNAGgKQAGgKAJgGQAKgFALgBQAMABAJAFQAJAFAFAKQAGAKAAANIgBADQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIg4AAIgCABIAAACQAAAGADAFQADAGAGADQAFADAFAAQAHAAAGgDQAFgDAFgGIABgBIACABIAJAFQABAAAAAAQABAAAAAAQAAABgBAAQAAAAAAABQgFAIgGADQgFAFgHACQgHABgIABQgLgBgKgFgAgJgbQgFADgCAGQgDAEAAAHIAlAAIADgBIAAgBQAAgFgCgFQgCgFgFgDQgEgDgGAAQgGAAgFADg");
	this.shape_26.setTransform(20.725,-65.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AAuAsIgCgBIAAgCIAAg3QgBgGgDgEQgDgDgHAAIgGABIgGAEIgGAEIgBACIgBADIAAA1QAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAIgOAAIgCgBIAAgCIAAg3QAAgGgEgEQgDgDgGAAQgGAAgFADQgEACgGAGIAAA5QAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAIgPAAQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAhPQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAQAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAJIAAABIACgBIAJgHIAJgEQAEgCAFAAQAKAAAFAEQAFAFADAGIAAABIACgBQAEgFAFgDQAFgDAEgCQAGgCAEAAQAMAAAGAHQAIAHgBAMIAAA5QAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAg");
	this.shape_27.setTransform(8.05,-65.275);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgiA4QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgLIAAgBIAEgBIALAAQADAAADgCIAEgEIACgGQABgCgBgDIgfhMQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIACgBIARAAIACABIACABIATA1IABABQAAAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAAAIAUg1IABgBIACgBIAMAAIACABIAAACIgiBUIgGANQgDAEgEADQgEADgFABIgMAAg");
	this.shape_28.setTransform(-4.4208,-63.875);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgeAmQgHgHAAgKQAAgJAFgGQAGgGAKgEQAKgDAOgBIAIgBIABAAIABgCIAAgEQAAgHgEgEQgEgEgIAAQgEAAgFADQgFACgEAGIgBABIgCAAIgOgDIgBgCIABgCQAEgJAKgFQAJgEANgBQANABAHADQAIADAEAHQADAGAAAHIAAA5IAAADIgDAAIgNAAIgCgBIgBgDIgBgFQAAgBAAAAQAAAAgBAAQAAAAAAAAQgBAAgBABQgFAFgHADQgFACgIABQgNgBgHgGgAAJABIgJACIgIAEQgEABgCADQgCAEAAADQAAAGAEADQADADAHAAQAEAAAEgBIAGgEIAEgFQACgCAAgCIAAgMQAAgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAg");
	this.shape_29.setTransform(-14.225,-65.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgsA8IgCAAIAAgDIAAhxQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIAtAAQANAAAKAEQALAEAGAHQAGAJAAANQAAALgFAJQgGAGgKAEQgJAEgNABIgZAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAArQAAABgBAAQAAABAAAAQgBABgBAAQAAAAgBAAgAgWgnIAAAgQAAABAAABQAAAAAAAAQAAABABAAQAAAAABAAIAUAAQALAAAGgFQAGgFAAgJQAAgGgDgFQgDgEgFgCQgGgCgGAAIgUAAQAAAAgBAAQAAAAgBABQAAAAAAAAQAAABAAABg");
	this.shape_30.setTransform(-24.375,-66.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgVAnQgKgGgGgJQgEgLAAgNQgBgMAGgKQAGgKAJgGQAKgFALgBQANAAAKAHQAJAFAGAKQAEAKAAAMQAAANgFALQgFAJgJAGQgLAFgMABQgMgBgJgFgAgLgaQgEAEgDAGQgCAHgBAJQABAKACAHQADAGAEADQAFAEAGAAQAHAAAFgEQAFgDACgGQACgHABgKQgBgJgCgHQgCgGgFgEQgFgEgHABQgGgBgFAEg");
	this.shape_31.setTransform(-39.7,-65.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AAgA8IgCAAIgBgCIg3hNIgBgBIgBABIAABNQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIgOAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAhyQAAgBABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAQAAIADABIACABIAzBKIABABQAAAAAAAAQABAAAAAAQAAgBAAAAQAAAAAAAAIAAhJQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABzIAAACIgCAAg");
	this.shape_32.setTransform(-51.2,-66.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgWAnQgKgEgEgIIgBgCIABgCIAKgEIACgBIABABIAGAGQADACAEACQAFACAGgBIAJgBIAGgDQADgCAAgEQAAgEgDgCQgDgCgHgCIgPgEQgNgCgFgGQgGgFAAgJQAAgIAEgHQAEgFAIgEQAIgEAKABQAMgBAJAFQAJAFAEAGIABACIgBABIgKAFIgCAAIgCgBQgDgDgFgDQgFgDgHAAQgGAAgFADQgEADAAAEQAAABAAABQAAAAAAABQAAAAABABQAAAAABABQACADAGABIATAFQAMAEAGAFQAFAHAAAIQAAAIgFAGQgFAGgIADQgJAEgKAAQgNgBgKgFg");
	this.shape_33.setTransform(45.025,-84.85);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AAUA8IgCgBIgBgCIAAg4QAAgFgDgDQgDgEgHAAQgEAAgCACQgEAAgDADIgHAGIAAA5QAAABAAAAQgBABAAAAQgBABAAAAQgBAAgBAAIgOAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhyQAAAAAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAqIAAABIABAAIAKgHQAFgDADgBQAFgCAFABQAMgBAHAIQAGAGAAAMIAAA5QAAABAAABQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_34.setTransform(35.625,-86.55);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAIA5QgKABgFgGQgGgEAAgLIAAgwQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBgBAAIgLAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIAMAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABgBAAAAIACgZQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIANAAQABAAAAABQABAAAAAAQAAABAAAAQAAABABABIAAAYQAAAAAAABQAAAAAAAAQAAAAAAAAQABAAAAAAIASAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgTAAQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIACABIAAACIAAAJQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAgBABIgGAAIgGAAg");
	this.shape_35.setTransform(26.25,-86.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAUAsIgCgBIgBgCIAAg3QAAgGgDgEQgDgDgHAAQgEAAgCABIgHAEIgHAGIAAA5QAAABAAAAQgBABAAAAQgBAAAAABQgBAAgBAAIgOAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAhPQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAQAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAAAJIAAABIABgBIAJgHIAIgEQAFgCAGAAQAMAAAHAHQAGAHAAALIAAA6QAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAg");
	this.shape_36.setTransform(17.625,-84.925);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgVAnQgKgGgGgKQgEgJAAgNQgBgNAGgKQAGgKAJgGQAKgGALABQANAAAKAFQAJAGAFAKQAGAKgBANQAAANgFAJQgFAKgJAGQgKAGgNAAQgLAAgKgGgAgKgaQgFADgDAIQgDAGABAJQgBAKADAHQADAGAFAEQAEADAGAAQAHAAAFgDQAEgEADgGQADgHAAgKQAAgJgDgGQgCgIgFgDQgFgEgHAAQgGAAgEAEg");
	this.shape_37.setTransform(7.45,-84.85);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AAqA8IgDgBIAAgCIAAhTIgBgBIAAABIgfBTQAAABgBABQAAAAgBAAQAAABgBAAQAAAAgBAAIgKAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBIgehSIgBgBIAAABIAABSIgBACIgCABIgOAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhyQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAbAAIACAAIABACIAdBMQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIABgBIAchLQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAcAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAABxQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_38.setTransform(-5.475,-86.55);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgnA9IgDgBIgBgCIAAgLIABgBIACgDIAEgEIAfgdIAMgLIAHgIQADgFABgDIABgHQAAgGgCgEQgDgEgFgCQgEgCgFAAQgEAAgEABQgFACgEAEQgEADgEAHIgBABIgDgBIgMgHQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIABgDQAHgMAMgGQALgGAMAAQAMAAAJAEQAKAFAFAIQAGAHAAAMQAAAGgDAGQgCAGgFAGQgGAGgJAHIgeAaIAAABIABABIA0AAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAABIAAAOIgBACIgCABg");
	this.shape_39.setTransform(-22.675,-86.65);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgeA8QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAgBIAAgMQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIASAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAABAAIAAhLQAAAAgBAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgRAGQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgJIAAgCIACgBIAagOIADgBIACAAIAJAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAABhQAAABAAAAQAAAAAAABQAAAAAAAAQABAAAAAAIARAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAAAMIAAACIgCABg");
	this.shape_40.setTransform(-32.15,-86.55);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgEAmQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAgaIAAgPIAOAAIAAAPIgOAAIAOAAIAAAcQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAgBAAgAAIAIIAAgPIAcAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAAAAAABQAAABgBAAQAAABgBAAQgBAAAAAAgAAIAIgAgiAIIgCgBIgBgCIAAgJQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIAdAAIAAAPgAAIgHIgOAAIAAgbIAAgDIACAAIAJAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAcgAgGgHgAgGgHg");
	this.shape_41.setTransform(-45.25,-86.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68.2,-98,136.5,82.2);


(lib.T1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#47C434").s().p("AgDAeQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgUIgUAAIgCgBIgBgBIAAgIQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAVAAIAAANIANAAIAAAVQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAgAAHAHIAAgNIgNAAIAAgUIABgCIACgBIAIAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAVIAVAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAIQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAgAAHAHgAgGAHIAAgNIANAAIAAANgAgGgGg");
	this.shape.setTransform(2.625,72.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#48C435").ss(1,1,1).p("ABgAAIJYAAAq3AAIJYAA");
	this.shape_1.setTransform(1.55,73.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6CC14C").s().p("AhHCXQgggVgTgmQgRgmAAg0QAAgnAKggQAKggAUgXQASgXAagMQAagMAdAAQAfAAAZAMQAZAMATAXQATAXAKAgQALAgAAAmQAAA0gSAnQgSAmgfAVQggAVgpAAQgoAAgfgVgAgghoQgNAMgHAaQgHAaAAAqQAAApAHAZQAHAaANALQANALATAAQAUAAAOgLQANgLAGgaQAHgZAAgpQgBgqgGgaQgHgagNgMQgOgMgTAAQgTAAgNAMg");
	this.shape_2.setTransform(-0.5,41.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC14C").s().p("AAUCoQgKAAAAgJIAAhCQAAgEgFAAIiHAAQgJAAAAgJIAAglIACgKIAJgMICIizIAIgHIAKgCIA5AAQAHAAAAAJIAAC8QAAAFAFAAIAlAAQAIAAAAAHIAAAmQAAAJgIAAIglAAQgFAAAAAFIAABAQAAAKgLAAgAAEhSIhQBvQgEAGAIAAIBPAAQABAAAAAAQABAAABgBQAAAAAAgBQABAAAAgBIAAhwIgCgGg");
	this.shape_3.setTransform(-34.075,41.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#6CC14C").s().p("AgrBEIgEgBIAAgDIAAiAQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAAAAAIBaAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAARQAAADgEAAIg4AAQgBAAAAABQgBAAAAAAQgBABAAAAQAAABAAABIAAAcQAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAIAnAAQABAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAARQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgnAAQAAAAgBAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAAxQAAAEgFAAg");
	this.shape_4.setTransform(47.725,52);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#6CC14C").s().p("AgrBEIgEgBIAAgDIAAiAQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAAAAAIBaAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAARQAAADgEAAIg4AAQgBAAAAABQgBAAAAAAQgBABAAAAQAAABAAABIAAAcQAAABAAAAQAAABAAAAQABABAAAAQABAAAAAAIAnAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAARQAAABAAAAQAAABgBAAQAAAAAAAAQgBABgBAAIgnAAQAAAAgBAAQAAAAgBAAQAAAAAAABQAAAAAAABIAAAxQAAAEgFAAg");
	this.shape_5.setTransform(36.175,52);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#6CC14C").s().p("AggA9QgOgIgIgQQgIgPAAgWQAAgUAIgQQAIgQAOgJQAOgIASAAQATAAAOAIQAOAJAIAQQAIAQAAAUQAAAWgIAPQgHAQgPAIQgOAJgTAAQgSAAgOgJgAgVgjQgHALAAAYQAAAaAHAKQAHAMAOAAQAPAAAHgMQAHgKAAgaQAAgYgHgLQgHgMgPAAQgOAAgHAMg");
	this.shape_6.setTransform(22.925,52);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#6CC14C").s().p("AAcBBQgJgFgEgJQgFgJAAgKQAAgLAFgJQAEgJAJgEQAHgFAKgBQAJABAJAFQAHAEAFAJQAEAJAAALQAAAKgEAJQgFAJgHAFQgIAFgKAAQgKAAgHgFgAAlAKQgDADgCAFQgBAGAAAIQAAAHABAGQACAEADAEQADACAFAAQAEAAAEgCQACgEACgEQACgGgBgHQABgIgCgGQgCgFgCgDQgEgDgEAAQgFAAgDADgAgwBFQAAAAgBgBQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIBWiBIADgCIABgBIAKAAIACABQAAAAAAABQAAAAAAAAQAAAAAAABQAAAAAAABIhXCDQgBABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAgAg9ACQgIgEgFgIQgEgKAAgKQAAgLAEgJQAFgIAIgGQAIgFAKAAQAJAAAIAFQAHAGAFAIQAFAJAAALQAAAKgFAKQgEAIgIAEQgHAFgKAAQgLAAgHgFgAgzg0QgDADgCAGQgBAGgBAHQABAIABAFQACAFADADQACADAGAAQAGAAAEgGQADgHAAgLQAAgLgDgHQgEgGgGAAQgGAAgCACg");
	this.shape_7.setTransform(24.5,32);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#6CC14C").s().p("Ag7BuQgagOgNgdQgOgcAAgmQAAgmAOgcQAOgdAagPQAZgQAhAAQAjAAAZAQQAZAPAOAdQAOAcAAAmQAAAmgOAcQgOAdgZAOQgZAPgjABQgigBgZgPgAgng/QgNAUAAAsQAAAtANATQANAVAagBQAbABANgVQAMgTAAgtQAAgsgMgUQgNgVgbAAQgaAAgNAVg");
	this.shape_8.setTransform(38.825,4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#6CC14C").s().p("Ag3BuQgZgPgOgcQgNgcAAgmQAAgmAOgcQAOgdAagPQAZgQAhAAQAbAAAVAKQAVALANAPQANAQAEATIAAAGQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBABIgsAGQAAAAgBAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgCgDQgCgLgGgJQgGgJgKgGQgKgFgNAAQgPAAgMAIQgMAJgGASQgGATAAAeQAAAfAHASQAGATAMAJQAMAJAQgBQAKAAAIgDQAJgDAFgGQAGgFAEgGQADgHACgIIABgJQABgFgFAAIgoAAIgDgBIgCgEIAAgZQAAgEAFAAIBZAAQAFAAACACQACACAAADIAABwIgBADIgEACIgKAAIgFgCIgEgEIgJgYIgCgBIgCACQgGAHgJAIQgJAHgNAFQgNAEgTABQgggBgZgPg");
	this.shape_9.setTransform(13.525,4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#6CC14C").s().p("Ag7BuQgagOgNgdQgOgcAAgmQAAgmAOgcQAOgdAagPQAZgQAhAAQAjAAAZAQQAZAPAOAdQAOAcAAAmQAAAmgOAcQgOAdgZAOQgZAPgjABQgigBgZgPgAgng/QgNAUAAAsQAAAtANATQANAVAagBQAbABANgVQAMgTAAgtQAAgsgMgUQgNgVgbAAQgaAAgNAVg");
	this.shape_10.setTransform(-11.475,4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#6CC14C").s().p("AhdB7QgBAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIgCgEIAAjoQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQACgDADAAIBZAAQAwAAAZARQAaARAAAfQAAASgKANQgKANgXAJIgBACIABABQAaAIALANQAMAOAAAWQAAAigaAQQgZAQgyABgAgqAZIAAA0QAAAGAFAAIAkAAQAUABALgKQALgIAAgPQAAgLgFgGQgGgIgJgEQgJgDgMAAIgkAAQgGAAAAAGgAgqhNIAAAzQAAAFAFABIAlAAIAPgCQAGgBAFgEQAGgFADgFQADgFAAgJQAAgPgMgIQgLgJgRABIgiAAQgGAAAAAFg");
	this.shape_11.setTransform(-35.675,4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAMBOQgPAAgHgHQgIgHAAgOIAAhBQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBAAIgPAAQAAAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgOQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIARAAQAAAAAAgBQABAAAAAAQAAAAAAgBQAAAAAAgBIADghQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIASAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAhQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABAAIAZAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAOQAAABAAABQAAAAgBABQAAAAgBAAQgBABgBAAIgYAAQgBAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAABIAAA6QAAAIAEAEQADADAIAAIANAAIACAAIABADIAAAMQAAADgFAAIgHABIgJABg");
	this.shape_12.setTransform(51.55,120.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgJBSIgEgBIAAgDIAAhsQAAgBAAgBQAAAAAAgBQABAAAAgBQABAAABAAIAVAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIAABrIgBAEIgEABgAgKgyQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgBgEIAAgVQAAgFAEAAIAVAAQAEAAAAAEIAAAWQAAAFgGAAg");
	this.shape_13.setTransform(44.275,120.525);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAbA7IgDAAIgBgDIAAhLQAAgJgEgEQgFgFgJAAQgFAAgEABQgEACgFAEIgJAIIAABNQAAAEgFAAIgUAAQgEABAAgEIAAhtQAAAAAAgBQABgBAAAAQAAgBABAAQABAAAAAAIAWAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAMIABACIACgBIAMgKQAGgEAFgCQAGgDAIABQAQAAAKAJQAJAKAAAPIAABPQAAAEgFAAg");
	this.shape_14.setTransform(35.025,122.75);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgkBMQgOgIgGgOQgGgOAAgWIAAhgQAAgEADAAIAaAAQADAAAAAEIAABlQAAATAJAJQAIAIAPAAQALAAAIgDQAHgEAEgIQAFgIAAgNIAAhlQAAgEADAAIAUAAQADAAAAAEIAABkQAAAWgHAOQgIANgOAGQgOAGgUAAQgWAAgOgHg");
	this.shape_15.setTransform(20.575,120.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgvBMQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgNIABgDIAGgBIAOAAQAEAAAEgCIAGgGIADgIQABgDgBgDIgrhoQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAABAAIAXAAIACABIACACIAaBIQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAbhIIACgCIACgBIAQAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAIguBzQgFAKgEAGQgEAHgFADQgGAEgGABQgHACgKAAg");
	this.shape_16.setTransform(2.0917,124.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgfA7IgDAAIgBgDIAAhtQAAAAAAgBQABgBAAAAQAAgBABAAQABAAAAAAIAVAAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIAAAOIAAABIADgBQAEgGAFgEIALgHQAGgDAGABQAIgBAAAEIAAAWQAAAAAAABQgBAAAAABQAAAAgBAAQgBAAAAAAIgHgBIgHAAIgJABIgJAFIgFAHQgCAEAAADIAABDQAAAEgFAAg");
	this.shape_17.setTransform(-8.725,122.75);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgbA1QgOgIgHgNQgIgNAAgRQAAgSAIgOQAIgOANgHQANgJAPABQARAAAMAHQANAHAHAOQAHANAAATIgBADQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIhNAAIgCABIAAADQAAAJAEAHQAEAHAIAFQAHADAIABQAJgBAHgDQAHgEAHgIIACgCIACABIANAHQABAAAAAAQABABAAAAQAAAAAAABQgBABAAAAQgHAKgHAGQgIAFgJADQgJADgMgBQgPAAgNgHgAgMglQgHAEgDAIQgEAHAAAIIAzAAIADAAIABgCQAAgIgDgGQgDgGgGgFQgGgFgJABQgIgBgGAFg");
	this.shape_18.setTransform(-20.025,122.85);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgGA6QgEAAgCgEIgshrQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIADgBIAXAAIADABIACACIAbBHQABAEADgEIAchHIABgCIADgBIAQAAIADABIAAADIgsBrQgCAEgFAAg");
	this.shape_19.setTransform(-32.6875,122.875);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("Ag1BSQgEAAAAgEIAAibQAAgEADAAIBqAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAABIAAARQAAAEgEAAIhIAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABAAABIAAAmQAAABAAABQAAAAAAABQABAAAAABQABAAABAAIAxAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAAARIAAACIgDAAIgxAAQgBAAgBAAQAAABgBAAQAAAAAAABQAAAAAAABIAAApQAAAAAAABQAAABAAAAQABAAAAABQABAAAAAAIBMAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIAAARIgBADIgDABg");
	this.shape_20.setTransform(-45.525,120.525);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgMBSQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAhaQAAAAAAgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgOIABgCIACgBIARAAQABAAAAAAQABAAAAAAQAAgBAAAAQAAgBAAgBIAAgOQABgOAHgIQAIgIAOAAIAVAAQAEAAAAAEIAAANIgBACIgCABIgNAAQgFAAgDAEQgDAEgBAGIAAALQAAAAABABQAAAAAAABQAAAAABAAQAAAAABAAIAVAAIACABIABACIAAAOQAAABAAABQAAAAgBAAQAAABgBAAQgBAAAAAAIgUAAQgBAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAABaQAAABAAAAQAAABgBABQAAAAgBAAQAAABgBAAg");
	this.shape_21.setTransform(45.6,97.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgNBSQAAAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAhaQAAAAgBgBQAAAAAAAAQAAgBAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAgOIAAgCIAEgBIAQAAQABAAAAAAQABAAAAAAQAAgBAAAAQABgBAAgBIAAgOQgBgOAJgIQAHgIAOAAIAUAAQAFAAAAAEIAAANIAAACIgDABIgNAAQgGAAgDAEQgCAEAAAGIAAALQAAAAAAABQAAAAAAABQAAAAABAAQAAAAABAAIAUAAIADABIABACIAAAOQAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAIgUAAQAAAAgBAAQAAAAAAABQgBAAAAAAQAAABAAAAIAABaQAAABAAAAQAAABgBABQAAAAgBAAQAAABgBAAg");
	this.shape_22.setTransform(35.65,97.875);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgmBKQgRgKgIgTQgJgSAAgaQAAgaAJgTQAJgSAQgLQARgKAVAAQAXAAAQAKQAQALAJASQAJATAAAaQAAAagIASQgJATgRAKQgQAKgXAAQgVAAgRgKgAgdgtQgJAPAAAfQAAAfAJAOQAKAPATAAQAUAAAKgPQAJgOAAgfQAAgfgJgPQgKgPgUAAQgTAAgKAPg");
	this.shape_23.setTransform(22.825,97.875);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AghBKQgPgKgIgTQgJgSAAgaQAAgTAFgPQAFgQAJgLQAJgLAMgGQAMgGANAAQAOAAAMAGQAMAGAJALQAJALAFAPQAFAQAAATQAAAagJASQgIATgPAKQgPAKgTAAQgSAAgPgKgAgRg2QgHAHgEANQgEAOAAAVQAAAVAEANQAEANAHAGQAIAGAJAAQALAAAHgGQAHgGAEgNQAEgNAAgVQAAgVgEgOQgEgNgHgHQgIgGgKAAQgJAAgIAGg");
	this.shape_24.setTransform(2.125,97.875);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AghBKQgPgKgIgTQgJgSAAgaQAAgTAFgPQAFgQAJgLQAJgLAMgGQAMgGANAAQAOAAAMAGQAMAGAJALQAJALAFAPQAFAQAAATQAAAagJASQgIATgPAKQgPAKgTAAQgSAAgPgKgAgRg2QgHAHgEANQgEAOAAAVQAAAVAEANQAEANAHAGQAIAGAJAAQALAAAHgGQAHgGAEgNQAEgNAAgVQAAgVgEgOQgEgNgHgHQgIgGgKAAQgJAAgIAGg");
	this.shape_25.setTransform(-14.175,97.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgpBSQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAgTQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAZAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAAAIAAhlQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgYAHQgDABAAgEIAAgNIAAgDIACgBIAkgSIAEgCIADgBIANAAQABAAABABQAAAAAAAAQABABAAABQAAAAAAABIAACEQAAABAAAAQAAAAAAABQABAAAAAAQAAAAABAAIAXAAQABAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAASIgBADIgDABg");
	this.shape_26.setTransform(-27.25,97.875);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgDBiQgBAAAAAAQgBAAgBgBQAAAAAAgBQAAAAAAgBIAAgLIgBgCIgCgBQgRAAgMgGQgMgFgJgKQgFgEADgDIALgLIADgCIADACQAHAHAIAFQAIAFAMABQAAAAABAAQAAAAABAAQAAgBAAAAQABAAAAgBIAAgrIgBgDIgDgCQgRgFgLgGQgKgGgFgJQgEgJAAgLQAAgMAGgJQAFgKALgGQALgHAOgCIADgBIABgCIAAgJIABgDIABAAIAMAAIADABIABADIAAAJQAAABAAAAQAAAAAAAAQABABAAAAQAAAAABAAQAMACAKAEQAJAFAIAGQADACgCADIgLANIgCABIgDgBQgEgFgGgDQgGgEgIgBIgCAAIAAACIAAArQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABABIALADQAMAEAIAFQAJAHAFAJQAEAIAAALQAAANgGAKQgGAKgKAGQgLAGgPABIgDABIAAACIAAAKQAAAEgFAAgAAMASIAAApQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAQALgBAHgGQAGgGAAgIQAAgIgFgGQgGgGgMgDIgDgBIAAADgAgJg9QgLABgGAHQgGAGAAAIQAAAFACAEIAHAHQAEADAIADIAEAAIABgEIAAgmQAAAAgBgBQAAAAAAgBQAAAAAAAAQgBAAAAAAIgBAAg");
	this.shape_27.setTransform(-39.81,98.025);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgHA0QAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAgPQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIAQAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAQQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAgAgCAWIgCgBIgBgBIgEhFIAAgCIABAAIAQAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIgEBFIgBABIgDABg");
	this.shape_28.setTransform(68.55,-23.65);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgRAhQgIgEgFgIQgFgJAAgLQAAgMAFgIQAFgJAIgFQAJgEAJgBQALABAHAEQAJAEAEAJQAEAJAAALIAAADIgCABIgxAAIgBAAIAAABQAAAGADAFQADAEAEADQAFADAEgBQAGAAAFgCQAEgCAFgGIABAAIABAAIAJAEQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgEAGgFAEQgFADgGACQgGACgHAAQgKgBgIgFgAgIgXQgDADgCAEQgDAEAAAGIAgAAIACAAIAAgCQAAgEgCgFQgCgEgDgCQgEgDgGAAQgEAAgFADg");
	this.shape_29.setTransform(62.7,-22.15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgFA0QgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhiQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIANAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAABiIAAACIgDABg");
	this.shape_30.setTransform(56.825,-23.65);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgaAhQgGgGAAgJQAAgIAFgFQAFgFAIgDQAJgDAMgBIAHgBIABAAIABgCIAAgDQgBgGgDgDQgEgEgGAAQgEAAgEADQgFACgDAEIgBACIgCAAIgLgEIgBgBIABgBQADgJAIgDQAJgFAKAAQALAAAHADQAHAEADAEQADAGAAAHIAAAwIAAACIgDABIgLAAIgCgBIgBgDIAAgDQAAgBAAAAQgBgBAAAAQAAAAgBABQAAAAgBABQgEAEgGACQgFADgHAAQgKAAgHgGgAAAADIgHACQgEACgBACQgCAEAAACQAAAFAEADQADADAGAAIAGgBIAFgDIAEgFQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIAAgKQAAgBgBAAQAAgBAAAAQAAAAgBAAQAAAAAAAAIgGAAIgIACg");
	this.shape_31.setTransform(50.9,-22.15);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgFIgBgDIABgCIAJgFIADgCIACACIAGAHQAEADAEACIALAAQAJAAAGgCQAGgEAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgFgDgFQgCgFAAgHQAAgIAEgIQAFgGAJgFQAJgDAKAAQAIAAAGABQAHACAFAEQAGADADAEIABACIgBACIgKAHIgBAAIgCgBQgDgEgFgCQgFgDgIgBQgJAAgFAEQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMADAGAHQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAFgMAAQgJAAgIgDg");
	this.shape_32.setTransform(42.5667,-23.65);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AgTAmIgCgBIgBgCIAAhEQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIAOAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAIIAAABIABAAIAGgHIAHgEIAIgCQAFAAAAACIAAAOQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAIgFgBIgEAAIgGABIgFADIgDAEIgCAFIAAAqQAAABAAAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_33.setTransform(32.475,-22.225);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgRAhQgJgEgEgIQgFgJAAgLQAAgMAFgIQAFgJAIgFQAJgEAJgBQAKABAIAEQAJAEAEAJQAEAJAAALIAAADIgCABIgxAAIgBAAIAAABQAAAGACAFQADAEAFADQAEADAFgBQAGAAAFgCQAEgCAFgGIABAAIABAAIAJAEQAAAAAAABQABAAAAAAQAAAAAAABQgBAAAAABQgEAGgFAEQgFADgGACQgGACgHAAQgKgBgIgFgAgIgXQgDADgDAEQgCAEAAAGIAgAAIACAAIAAgCQAAgEgBgFQgCgEgEgCQgEgDgGAAQgEAAgFADg");
	this.shape_34.setTransform(25.25,-22.15);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAoAmIgCgBIAAgCIAAgvQAAgFgEgDQgCgDgGAAIgGABIgFADIgEADIgBACIgBADIAAAuQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgBgBIgBgCIAAgvQAAgFgDgDQgDgDgFAAQgFAAgEACQgEACgFAFIAAAxQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIgNAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBIAAhEQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIANAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAHIAAABIABgBIAIgGQAEgCAEgBQAEgCAEAAQAIAAAFAEQAEADACAGIABAAIACAAIAHgHQAEgDAEgBQAEgCAFAAQAKAAAGAGQAFAGABAKIAAAyQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAg");
	this.shape_35.setTransform(14.85,-22.225);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAnAmIgBgBIgBgCIAAgvQABgFgDgDQgDgDgFAAIgHABIgFADIgEADIgBACIgBADIAAAuQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgMAAIgBgBIgBgCIAAgvQAAgFgDgDQgCgDgGAAQgFAAgEACQgEACgEAFIAAAxQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAIgMAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIANAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAHIABABIABgBIAIgGQADgCAEgBQAEgCAEAAQAIAAAFAEQAFADACAGIAAAAIACAAIAHgHQAEgDAFgBQAEgCAEAAQAKAAAFAGQAHAGAAAKIAAAyQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_36.setTransform(2.1,-22.225);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgVAjQgFgDgDgFQgDgFAAgGIAAgyQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAIANAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAAuQAAAGADADQADADAGAAQAEAAAEgCIAJgHIAAgxQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAABAAIAMAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAABEQAAAAAAABQgBAAAAABQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgHIAAgBIgBAAQgHAGgGADQgFADgGAAQgGAAgFgDg");
	this.shape_37.setTransform(-8.475,-22.075);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgQAzQgHgCgHgEQgGgEgDgFIgBgDIABgCIAJgFIADgCIACACIAGAHQAEADAEACIALAAQAJAAAGgCQAGgEAAgHIgBgFIgEgEIgIgEIgUgHQgJgCgFgDQgFgFgDgFQgCgFAAgHQAAgIAEgIQAFgGAJgFQAJgDAKAAQAIAAAGABQAHACAFAEQAGADADAEIABACIgBACIgKAHIgBAAIgCgBQgDgEgFgCQgFgDgIgBQgJAAgFAEQgFAEAAAGIABAEIAEAFIAIADIAVAHQAMADAGAHQAGAHAAAKQAAAKgFAHQgFAHgJADQgJAFgMAAQgJAAgIgDg");
	this.shape_38.setTransform(-17.2333,-23.65);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgHA0QgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAgBIAAg4QAAAAAAgBQAAAAAAAAQAAAAAAAAQAAAAgBAAIgLAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgIIABgCIABAAIALAAQAAAAABAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgJQABgJAFgFQAEgFAJAAIANAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAIAAAIIgBACIgBAAIgJAAQgDAAgCADQgCACAAAEIAAAHQAAABABAAQAAAAAAABQAAAAAAAAQABAAAAAAIANAAIABAAIABACIAAAIQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBABAAAAIAAA4QAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_39.setTransform(-27.45,-23.65);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgTAhQgHgEgFgJQgFgJAAgLQAAgKAFgJQAFgJAIgEQAIgGAKAAQALAAAIAGQAJAEAEAJQAFAJAAAKQAAALgFAJQgEAJgJAEQgIAFgLABQgKgBgJgFgAgJgWQgEACgDAHQgCAFAAAIQAAAJACAFQADAGAEADQAEADAFAAQAGAAAEgDQAEgDACgGQACgFAAgJQAAgIgCgFQgCgHgEgCQgEgDgGgBQgFABgEADg");
	this.shape_40.setTransform(-34.4,-22.15);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgUAwQgHgEgEgIQgDgJAAgMQAAgMAEgIQAEgJAHgEQAHgFAJAAQAFAAAEACQAFACAEADIACABIAAgCIAAggQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIAOAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAABiIAAACIgDAAIgMAAIgCAAIgBgCIAAgFIAAgBIgBABIgFAEIgHADQgEACgFAAQgIAAgHgFgAgHgIQgEACgDAGQgCAFAAAKQAAAJACAGQADAGAEACQAEADAEAAQAFAAADgCQAEgCACgEQACgDAAgDIAAgfIgHgFQgEgCgEAAQgFAAgEADg");
	this.shape_41.setTransform(-45.875,-23.575);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AARAmIgCgBIgBgCIAAgvQAAgFgCgDQgDgDgGAAIgGABIgFADIgGAFIAAAxQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAIgNAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAhEQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAOAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAAHIAAABIABgBIAIgGIAHgDQAEgCAFAAQAKAAAGAGQAGAGAAAKIAAAyQAAABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_42.setTransform(-54,-22.225);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AghA0QgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAhiQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIBDAAQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAALQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIguAAQAAAAgBAAQAAAAAAAAQAAAAgBABQAAAAAAABIAAAYQAAAAAAABQABAAAAAAQAAABAAAAQABAAAAAAIAfAAQAAAAABAAQAAAAAAAAQAAABABAAQAAABAAAAIAAAKIAAABIgCABIgfAAQgBAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAaQAAAAAAABQAAAAABAAQAAAAAAAAQAAABABAAIAwAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAIAAAMIgBABIgCABg");
	this.shape_43.setTransform(-62.425,-23.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.7,-33.9,152.60000000000002,170);


(lib.logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.logo();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_04();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_03();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_02_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_02();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.Img_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Img_01();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Ag0AAIBpAAIgeAjAAcgiIAZAi");
	this.shape.setTransform(35.525,0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AFrA4QgJgFgEgHIgBgDIABgBIAMgFIABABIAFAFQAEAEAEABQAFACAGgBQAFABAEgCQAEgBADgCQACgDAAgDQAAgEgDgCQgCgCgHgCIgRgEQgMgCgGgHQgFgFAAgJQAAgHAEgGQAEgGAIgEQAIgDALAAQAMAAAIAEQAJAFAEAGIABACIgBACIgKAEIgCAAIgBgBQgDgEgFgCQgFgDgHAAQgHAAgFADQgFACAAAFQAAADACACQACABAHACIATAGQAMACAGAHQAFAGAAAJQAAAIgFAGQgEAGgJADQgIADgLAAQgOAAgKgFgAD/A4QgKgFgFgLQgFgLAAgPIAAhFQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIATAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAABIAABJQAAAOAGAGQAGAGAMAAQAIAAAFgDQAGgCADgHQADgFAAgKIAAhIQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAABIQAAAQgGAKQgFAJgLAFQgKAEgOAAQgRAAgKgFgABAA4QgJgGgGgKQgFgJAAgNQAAgNAFgKQAGgKAJgGQAKgFAMAAQAJAAAHADQAHADAFAGQAFAFACAGQAAABAAAAQAAABAAAAQAAAAgBABQAAAAgBAAIgOABQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEgGIgFgEQgDgCgEAAQgHAAgFAEQgFADgCAGQgDAHAAAJQAAAKADAHQADAGAFAEQAFADAHAAQAHAAAEgDQAFgEAEgHIABgBIACAAIAKADQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgFAIIgHAIQgFADgGACQgGACgHAAQgMAAgKgFgAgsA3QgHgHAAgKQAAgJAFgHQAFgGALgEQAKgEAOAAIAHAAIACgBIAAgCIAAgDQAAgHgDgDQgEgFgHAAQgGAAgFADQgFADgDAFIgBACIgCAAIgOgEIgBgBIABgCQAEgJAJgGQAKgEAOAAQALAAAIADQAHAEAEAGQADAGAAAHIAAA4IAAADIgCAAIgOAAIgCgBIgBgCIAAgFQAAgBgBAAQAAgBAAAAQgBAAAAABQgBAAAAAAQgFAGgGACQgHADgIAAQgMAAgHgGgAgFATIgKABIgIADIgGAGQgCACAAAEQAAAGAEADQAEADAHAAQAEAAAEgBIAGgEIAEgFIABgFIAAgLQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBAAgAkbA4QgKgGgFgKQgFgKAAgMQAAgNAFgKQAGgKAJgGQAKgFAMAAQAMAAAKAGQAJAFAGAKQAFAKAAANQAAAMgGAKQgFAKgJAGQgKAFgMAAQgNAAgJgFgAkRgIQgEADgDAGQgCAHAAAJQAAAJACAIQADAGAEAEQAFADAHAAQAHAAAEgDQAFgEACgGQADgIAAgJQAAgJgDgHQgCgGgFgDQgFgEgGAAQgHAAgFAEgAmOA2QgMgIgGgOQgHgOAAgSQAAgSAHgOQAGgNAMgHIAEgCQAKgGAOAAQAJAAAIADIAGADIAIAEQAGAFAEAGQAEAGABAIIABACIgCABIgSABIgCAAIgBgCQgCgIgFgGQgGgGgKAAQgOAAgHAKQgIALAAAWQAAAWAHALQAIALAOAAQAKgBAHgFQAHgEAFgMQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIANADIABABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIgEAIIgGAJQgEAFgFADQgGADgHADQgHACgJAAQgQAAgMgHgACVA3QgGgGAAgKIAAguQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgLAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgKQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAMAAQAAgBAAAAQABAAAAAAQAAAAAAAAQAAgBAAAAIADgZQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAZQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABABIASAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAKQAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgSAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAABAAAAIAAAqQAAAGACADQADACAFAAIAKAAIABABIABABIAAAJQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgSABQgLAAgFgEgAhgA3QgFgGAAgKIAAguQAAgBAAAAQgBgBAAAAQAAAAAAAAQgBAAAAAAIgLAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAgKQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIALAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIACgZQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAOAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAZQAAAAAAABQAAAAAAAAQAAAAABAAQAAAAAAABIASAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAKQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIAAAqQAAAGADADQACACAGAAIAJAAIACABIABABIgBAJQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgRABQgLAAgGgEgAiTA7IgCAAIgBgDIAAg2QAAgFgDgEQgEgDgGAAIgIABIgGADIgHAGIAAA4QAAADgEAAIgOAAQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAhOQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAQAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAIIAAABIABAAIAJgHIAJgEQAFgCAFAAQAMAAAHAHQAHAHAAALIAAA5QAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_1.setTransform(-8.4812,0.4592,0.8099,0.8099);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(0.4,1,1).p("AoliLIRLAAIAAEXIxLAAg");
	this.shape_2.setTransform(-0.95,0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#6CC24D").s().p("AolCMIAAkXIRLAAIAAEXg");
	this.shape_3.setTransform(-0.95,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.9,-14.7,112,30);


(lib.BG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG();
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,300,250);


// stage content:
(lib.WBAY_219645_MM_300x250_V1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(390));

	// cta
	this.instance = new lib.cta("synched",0);
	this.instance.setTransform(221.05,220.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(41).to({_off:false},0).to({alpha:1},13,cjs.Ease.get(1)).wait(336));

	// logo_png
	this.instance_1 = new lib.logo_1("synched",0);
	this.instance_1.setTransform(80,290);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(7).to({_off:false},0).to({y:300,alpha:1},17,cjs.Ease.get(1)).wait(366));

	// T3
	this.instance_2 = new lib.T3("synched",0);
	this.instance_2.setTransform(220.25,190.05);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(167).to({_off:false},0).to({y:170.05,alpha:1},15,cjs.Ease.get(1)).wait(208));

	// T2
	this.instance_3 = new lib.T2("synched",0);
	this.instance_3.setTransform(220.05,143.15);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(151).to({_off:false},0).to({y:123.15,alpha:1},16,cjs.Ease.get(1)).wait(223));

	// T1
	this.instance_4 = new lib.T1("synched",0);
	this.instance_4.setTransform(219,43.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(26).to({_off:false},0).to({y:52,alpha:1},15,cjs.Ease.get(1)).wait(83).to({startPosition:0},0).to({alpha:0},10).wait(256));

	// Img_04_jpg
	this.instance_5 = new lib.Img_04_1("synched",0);
	this.instance_5.setTransform(80,300);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(253).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(120));

	// Img_03_jpg
	this.instance_6 = new lib.Img_03_1("synched",0);
	this.instance_6.setTransform(80,300);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(210).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(163));

	// Img_02_jpg
	this.instance_7 = new lib.Img_02_1("synched",0);
	this.instance_7.setTransform(80,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(134).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(239));

	// Img_01_jpg
	this.instance_8 = new lib.Img_01_1("synched",0);
	this.instance_8.setTransform(80,300);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(9).to({_off:false},0).to({alpha:1},17,cjs.Ease.get(1)).wait(364));

	// BG_jpg
	this.instance_9 = new lib.BG_1("synched",0);
	this.instance_9.setTransform(80,300);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({alpha:1},17,cjs.Ease.get(1)).wait(373));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,115,152,136);
// library properties:
lib.properties = {
	id: 'EEE0CBDE3F5A41B0A2F5275DEDC5F0C8',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG.jpg", id:"BG"},
		{src:"Img_01.jpg", id:"Img_01"},
		{src:"Img_02.jpg", id:"Img_02"},
		{src:"Img_03.jpg", id:"Img_03"},
		{src:"Img_04.jpg", id:"Img_04"},
		{src:"logo.png", id:"logo"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EEE0CBDE3F5A41B0A2F5275DEDC5F0C8'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;